### ISSUE TITLE
Ohmyzsh automatic upgrade fails due to "wrong" ssh binary being used

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [ohmyzsh/ohmyzsh#10006]
**Describe the bug**
On my systems I have openssh installed via Macports. In my ssh config, I use three configuration options that are unsupported by the Apple-provided version of ssh, namely "IgnoreUnknown", "AddKeysToAgent", and "UseKeychain". 

When I open a new terminal window, I regularly get the "[oh-my-zsh] Would you like to update? [Y/n]" prompt. Prompting YES here, results in
```
Updating Oh My Zsh
/Users/daniel/.ssh/config: line 4: Bad configuration option: IgnoreUnknown
/Users/daniel/.ssh/config: line 11: Bad configuration option: AddKeysToAgent
/Users/daniel/.ssh/config: line 12: Bad configuration option: UseKeychain
/Users/daniel/.ssh/config: terminating, 3 bad configuration options
fatal: Could not read from remote repository.
```
because the upgrade attempt is made in a shell environment where my shell configs haven't been loaded yet, including my upgraded PATH variable, which ensures that Macports' `ssh` binary is used over the system-provided one.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Use a setup as described above and answer yes to the next upgrade prompt.

**Expected behavior**
I think ohmyzsh should finish loading the shell config *before* prompting to update. IIRC, you can replace the shell PID after upgrading with a fresh zsh session if needed?

**Desktop (please complete the following information):**

 - OS / Distro: macOS
 - Latest ohmyzsh update?: Yes, and no, due to the nature of the bug. I am now, after manually running `upgrade_oh_my_zsh` which runs fine once the PATH and other custom shell config has loaded.
 - ZSH Version: zsh 5.8 (x86_64-apple-darwin14.5.0)
 - Terminal emulator: iTerm2

**Comment by grimm26** [comment]
Have you tried putting your path settings in `~/.zshenv`?

**Comment by kunalg** [comment]
Another option could be to use https git urls for fetching updates.
`omz update` does nothing but a [`git pull`](https://github.com/ohmyzsh/ohmyzsh/blob/master/tools/upgrade.sh#L65)

You could do:

```
cd ~/.oh-my-zsh
git remote set-url origin https://github.com/ohmyzsh/ohmyzsh.git
```
and then `omz update`

This would work for unauthenticated pulls.

**Comment by mcornella** [comment]
This is not an OMZ bug but an ssh configuration error. You should correctly set your `$PATH` in `~/.profile` (which gets read when logging in, so you need to log out and back in of your user session) or `~/.zshenv`, which gets read every time zsh starts.

**Comment by DanielSmedegaardBuus** [comment]
Yeah, I can't just put my current PATH construction to `.profile` or `.zshenv`. My PATHs are different depending on the environment, and also depend on the sequence of things and aren't exactly static in nature, so it immediately breaks other stuff if I do that. Too much stuff to untangle to try to circumvent this minor issue. I found `DISABLE_AUTO_UPDATE` in `.zshrc` and enabled that instead. That oughta do it :) Cheers!

**Comment by grimm26** [comment]
You can't put the path you need to have the correct ssh in use with `.zshenv`? 

> Yeah, I can't just put my current PATH construction to `.profile` or `.zshenv`. My PATHs are different depending on the environment, and also depend on the sequence of things and aren't exactly static in nature, so it immediately breaks other stuff if I do that. Too much stuff to untangle to try to circumvent this minor issue. I found `DISABLE_AUTO_UPDATE` in `.zshrc` and enabled that instead. That oughta do it :) Cheers!
>
