### ISSUE TITLE
pyenv 2.0 updated the init process

### ISSUE THREAD

**Issue by alorence** [ohmyzsh/ohmyzsh#10013]
**Describe the bug**
In the recent [2.0.0 release](https://github.com/pyenv/pyenv/blob/master/CHANGELOG.md#release-200) of pyenv, the shell specific init command `pyenv init - zsh` has been deprecated. It now displays a warning message at initialization

> WARNING: `pyenv init -` no longer sets PATH.
> Run `pyenv init` to see the necessary changes to make to your configuration.

**To Reproduce**

1. Update pyenv to 2.0.x using `pyenv update`
2. Open a new shell with pyenv plugin enabled

**Expected behavior**
Shell start without warning message, pyenv command autocompletion work (including for pyenv virtualenv)

**Desktop (please complete the following information):**

 - OS / Distro: Manjaro 21.0.7
 - If on Windows what version of WSL: N/A
 - Latest ohmyzsh update?: Yes
 - ZSH Version: zsh 5.8 (x86_64-pc-linux-gnu)
 - Terminal emulator: Gnome Terminal 3.40.2 for GNOME 40

**Additional context**
The warning shown is printed by `pyenv init - zsh` command when `$PATH` does not contain the `$PYENV_ROOT/shims` folder. It disappear if `eval "$(pyenv init --path)"` is executed before `eval "$(pyenv init - --no-rehash zsh)"`. But since `--path` cli option is new in 2.0.x releases, I am not sure how to update pyenv plugin without breaking setup of older versions (and usually people forget to update pyenv)

**Comment by jimmywan** [comment]
I was able to get pyenv working via the following edit:
```
diff --git a/plugins/pyenv/pyenv.plugin.zsh b/plugins/pyenv/pyenv.plugin.zsh
index 82ba6ff8..ccfaae5c 100644
--- a/plugins/pyenv/pyenv.plugin.zsh
+++ b/plugins/pyenv/pyenv.plugin.zsh
@@ -29,6 +29,7 @@ if [[ $FOUND_PYENV -ne 1 ]]; then
 fi

 if [[ $FOUND_PYENV -eq 1 ]]; then
+    eval "$(pyenv init --path)"
     eval "$(pyenv init - --no-rehash zsh)"
     if (( $+commands[pyenv-virtualenv-init] )); then
         eval "$(pyenv virtualenv-init - zsh)"
```

I no longer have a pre pyenv 2 install handy, but perhaps something as simple as the following could do the trick:
```
pyenv init --path >/dev/null && eval "$(pyenv init --path)"
```

**Comment by alorence** [comment]
@jimmywan I was able to try on another machine with pyenv still in 1.2.27.
Since `pyenv initv --path` return a 0 exit-code, it is not possible to use it to determine if it should be eval'ed or not.

But, since the command does nothing on such install, I assume the `eval "$(pyenv init --path)"` should simply be added before other init command, and everything should work as expected on 1.2 & 2.0 setups.

I will try to make a PR as soon as possible

**Comment by januszm** [comment]
```
$ ~ pyenv
pyenv 2.0.1
```

Starting a new terminal ends with a warning message:

```
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
```
```

**Comment by UsrNameu1** [comment]
This issue helped me a lot. Thanks

**Comment by barend** [comment]
I can confirm that @jimmywan 's suggestion resolves the issue.

**Comment by mcornella** [comment]
As was documented in the pyenv plugin, you need to add these lines to `.profile` and `.zprofile`:
```sh
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```
and restart the user session (log out and log back in).

**Comment by januszm** [comment]
Just to clarify, on Mac OS X with zsh the three lines mentioned above are only needed in `.zprofile`. They have no effect if they're placed in .profile
