### ISSUE TITLE
obraun theme fill leading zero in hour

### ISSUE THREAD

**Issue by mboehm21** [ohmyzsh/ohmyzsh#10020]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
obraun

**Is your feature request related to a problem? Please describe.**

The length of the prompt differs by one char dependent on current time:

```
[8:42:20] mboehm21 :: dws-mboehm21  ➜  ~ » 
[10:42:20] mboehm21 :: dws-mboehm21  ➜  ~ » 
```

**Describe the solution you'd like**

It would be better when the hour would be displayed as two digits all the time:

```
[08:42:20] mboehm21 :: dws-mboehm21  ➜  ~ » 
[10:42:20] mboehm21 :: dws-mboehm21  ➜  ~ » 
```

**Comment by igavelyuk** [comment]
@mboehm21
if you under linux, you can change /home/YourUserName/.oh-my-zsh/themes/obraun.zsh-theme 
to this
```
if [ "$USERNAME" = "root" ]; then CARETCOLOR="red"; else CARETCOLOR="blue"; fi

local return_code="%(?..%{$fg[red]%}%? ↵%{$reset_color%})"
now=$(date +"%T")
PROMPT='%{$fg[green]%}[$now]%{$reset_color%} %{$fg_no_bold[cyan]%}%n %{${fg_bold[blue]}%}::%{$reset_color%} %{$fg[yellow]%}%m%{$reset_color%} %{$fg_no_bold[magenta]%} ➜ %{$reset_color%} %{${fg[green]}%}%3~ $(git_prompt_info)%{${fg_bold[$CARETCOLOR]}%}»%{${reset_color}%} '

RPS1="${return_code}"

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[red]%}‹"
ZSH_THEME_GIT_PROMPT_SUFFIX="› %{$reset_color%}"

```
and it will works fine until next update and will change output from `[8:42:20] mboehm21 :: dws-mboehm21  ➜  ~ » ` to `[08:42:20] mboehm21 :: dws-mboehm21  ➜  ~ » `

**Comment by mboehm21** [comment]
Hi @igavelyuk.

I changed the file locally and I can confirm that it works as intented.

Would be great if your PR would make it into the official code.

**Comment by igavelyuk** [comment]
@mboehm21 pass pull request, will see how it going, but you can use code from my fork, simply change in home folder, no idea what your system but must be in hidden folder with same path as git somewhere in user space, my path is /home/iGavelyuk/.oh-my-zsh/themes/obraun.zsh-theme
