### ISSUE TITLE
Execute command after copy to buffer with copybuffer

### ISSUE THREAD

**Issue by mhalano** [ohmyzsh/ohmyzsh#10039]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
copybuffer

**Is your feature request related to a problem? Please describe.**
I can't say is a problem. The ctrl+o shortcut originally executes the command typed in the command line. The copybuffer replace this behavior for just copying the command to the buffer. I think it could happen both things.

**Describe the solution you'd like**
When pressed ctrl+o the command could be copied to the buffer and executed after that, as original ctrl+o command do.

**Describe alternatives you've considered**
Reimplement the code, just adding the execution part (is a very short plugin).

**Comment by rwmitchell** [comment]
By not executing the command, the user gets one last chance to verify what is about to happen.  The buffer may not contain what the user assumed was in it and the results could cause issues.

**Comment by mhalano** [comment]
@rwmitchell That is a valid point, but I think mimic the original behavior also it is. So couldn't have a flag or an environment variable to set to change the behavior per-user?

**Comment by mcornella** [comment]
This is literally a keystroke away. Copy the command, then run it by pressing Enter. There is no need to extend the plugin to add a setting for this.

If you really hate having to press Enter afterwards, I suggest you make your own zle widget that both calls `copybuffer` and `zle .accept-line`, and bindkey that to `CTRL+O`:

```zsh
my-copybuffer() {
  copybuffer
  zle .accept-line
}
zle -N my-copybuffer
bindkey ^O my-copybuffer
```

**Comment by mhalano** [comment]
I know I could work around easily. My idea when I opened the issue is to create an option to mimic the default, no-copybuffer-used behavior of ctrl+o, so it could be added a feature (copy to clipboard) without the hassle to learn a new behavior for the keystroke (even a simple one).
