### ISSUE TITLE
Show abbreviation after command

### ISSUE THREAD

**Issue by NeilGirdhar** [ohmyzsh/ohmyzsh#10059]
There are so many aliases that it would be nice to learn them as you go.  Can zsh display the alias automatically as you type the command?

For example, suppose I type
```sh
grb --onto master HEAD~1
```
zsh could recognize the aliases:
```
grb='git rebase'
grbo='git rebase --onto'
```
and as I type it could highlight "grb --onto" in some color, and show underneath "grbo" in some other color.  Like this:

Similarly, if I type
```sh
$ git rebase --onto master HEAD~1
```
it would highlight `git rebase --onto` and show
```
grbo
```
underneath.

This would facilitate learning the many aliases.

**Comment by max-ae** [comment]
There already is the [you-should-use plugin](https://github.com/MichaelAquilina/zsh-you-should-use) with this functionality, maybe this already fulfills your request 😄

**Comment by NeilGirdhar** [comment]
@max-ae Thanks for your suggestion.  But it's not that I want to discover a plugin; it's that I want to learn the plugin's aliases after I'm already using it.

**Comment by NeilGirdhar** [comment]
Nice, thanks!
