### ISSUE TITLE
improve xdg support for NVM

### ISSUE THREAD

**Issue by xenoterracide** [ohmyzsh/ohmyzsh#10058]
### Describe the bug

I notice the script is looking for the xdg config dir and putting nvm there, nvm actually belongs in `XDG_DATA_HOME`/`~/.local/share` and a link to the bin in `~/.local/bin` see https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html secondly, a lot of XDG (every one I've ever used) desktops, don't actually set the environment variable, so you should fall back to these directories like the spec says, by default (IMHO). if `NVM_DIR` is set, of course you can ignore.

### Steps to reproduce

1. enable nvm plugin
2. use plugin on linux without additional configuration
3. xdg directories are not used

### Expected behavior

xdg directories are not used

### OS / Distro

Manjaro

### Zsh version

zsh 5.8 (x86_64-pc-linux-gnu)

### Terminal emulator

Gnome Terminal

### Additional context

you might just look to see if `XDG_SESSION` or something is present, but I'm not sure if that's a good idea because you could install nvm from a console login that's later used under a desktop.

**Comment by mcornella** [comment]
The nvm install documentation specifies that you can put it [in `XDG_CONFIG_HOME`](https://github.com/nvm-sh/nvm#additional-notes) if it's enabled:

> Additional Notes
> > If the environment variable $XDG_CONFIG_HOME is present, it will place the nvm files there.

The issue you're describing should be opened on the nvm project, we're simply mirroring their install behavior.
