### ISSUE TITLE
feat(git): change alias gp to include -u origin HEAD

### ISSUE THREAD

**Issue by RebeccaStevens** [ohmyzsh/ohmyzsh#10066]
### If the feature request is for a plugin or theme, specify it here.

git plugin

### If the feature solves a problem you have, specify it here.

When ever I push a new branch, I need to specify that the upstream for it. This change will make it so that is automatic.

Note: my .gitconfig contains:

```
[branch]
	autoSetupRebase = always
```

### Describe the proposed feature.

Change `gp=git push` to `gp=git push -u origin HEAD`

### Describe alternatives you've considered

I'm currently just making this change manually with:

```
unalias gp
alias gp='git push -u origin HEAD'
```

**Comment by kunalg** [comment]
There is already an alias for that:
`gpsup` => `git push --set-upstream origin $(git_current_branch)`
