### ISSUE TITLE
taskwarrior plugin not working

### ISSUE THREAD

**Issue by Hukuta** [ohmyzsh/ohmyzsh#10064]
### Describe the bug

`task 1[TAB] `- adds a space after 1
`task 1 [TAB] `- shows docs such as `task [TAB]`

### Steps to reproduce

install taskwarrior app,
add some tasks
enable taskwarrior plugin in ohmyzsh:
`plugins=(... taskwarrior)`

open a new terminal

`task 1[TAB] `

### Expected behavior

show a list of actions related to task

### OS / Distro

Ubuntu LTE

### Zsh version

5.8

### Terminal emulator

alacritty 0.5.0

### Additional context

I would like to help fix this if it is about the taskwarrior application being changed. However, I am not familiar with how such plugins work. Push me to the reason what is wrong and I will make a patch. 

UPD: updated plugins and got different bug

**Comment by dodona2** [comment]
works perfectly on
Fedora release 34 /  task 2.5.3 / zsh 5.8

**Comment by Hukuta** [comment]
Can confirm for Fedora, in ubuntu a have  task 2.5.1. It seems updating task can fix the issue.

![2107223036](https://user-images.githubusercontent.com/3100053/126618369-55d77c94-cfdf-4c99-bc6e-7b6b8fe0019d.png)

ubuntu left and fedora right
