### ISSUE TITLE
#9602 happens when using system built-in zsh and having only macPorts installed.

### ISSUE THREAD

**Issue by ShikiSuen** [ohmyzsh/ohmyzsh#10068]
### Describe the bug

The GFW interferes accesses to GitHub too much, making the experience of HomeBrew in Mainland PRC into a total pain. I was cornered to use MacPorts as much as possible since it hosts everything in a mirror.

However, in such configuration (macOS 11), ohmyzsh reports the following errors during installation:
```
compinit:503: no such file or directory: /usr/local/share/zsh/site-functions/_brew
compinit:503: no such file or directory: /usr/local/share/zsh/site-functions/_brew_services
```

### Steps to reproduce

1. Your macOS has built-in zsh.
2. You are using MacPorts.
3. You have no homebrew installed.

### Expected behavior

No hard dependency to anything "brew".

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/3164826/126736507-18b9ff02-c7b6-4486-8d50-a5c873922684.png)

### OS / Distro

macOS 11.4

### Zsh version

5.8

### Terminal emulator

macOS built-in Terminal

**Comment by mcornella** [comment]
This is not an Oh My Zsh bug but an issue with zsh probably. In fact, using MacPorts or not should not affect this, it seems that those files are there and `compinit` is finding those files there (probably symlinks to other files that don't exist) for some reason (maybe you installed Homebrew and uninstalled it later?).

You should remove them to fix the error.
