### ISSUE TITLE
When attempting to open ~/.zshrc file from iTerm, native terminal opens with an error.

### ISSUE THREAD

**Issue by Wanna-be-tech-guy** [ohmyzsh/ohmyzsh#10067]
### Describe the bug

I just downloaded oh my zsh. I'm trying to set up some of the themes, but every time I try and access  ~/.zshrc, terminal opens with the following error.

```
/Users/ancampbell/.zshrc ; exit;
➜  ~ /Users/ancampbell/.zshrc ; exit;
/Users/ancampbell/.oh-my-zsh/tools/check_for_upgrade.sh: line 32: syntax error near unexpected token `)'
/Users/ancampbell/.oh-my-zsh/tools/check_for_upgrade.sh: line 32: `() {'
/Users/ancampbell/.oh-my-zsh/oh-my-zsh.sh: line 21: autoload: command not found
/Users/ancampbell/.oh-my-zsh/oh-my-zsh.sh: line 39: syntax error near unexpected token `('
/Users/ancampbell/.oh-my-zsh/oh-my-zsh.sh: line 39: `for plugin ($plugins); do'
Saving session...completed.

[Process completed]
```

I looked around on google to see if I could figure out what was causing the error, but have had no luck so far.
Any advice on the subject would great!

Cheers!

### Steps to reproduce

1. Open iTerm
2. Enter ~/.zshrc
3. Terminal error

### Expected behavior

Open oh my zsh config file and set up one of those awesome themes I see all over the interwebs.

### OS / Distro

macOS Big Sur 11.4

### Zsh version

5.8

### Terminal emulator

iTerm2

**Comment by Wanna-be-tech-guy** [comment]
Sorry guys. Total noob moment... Forgot nano 😄 
I'll close this now.

**Comment by dikko11** [comment]
hello i faced the same problem can you tell me how you solved it?

**Comment by Wanna-be-tech-guy** [comment]
@dikko11 
The resolution for me was to run the command as 
`nano ~./zshrc`
Doing so, allowed me access to edit the config file.
Hope that helps.
