### ISSUE TITLE
Colemak plugin: lesskey is deprecated

### ISSUE THREAD

**Issue by murlakatamenka** [ohmyzsh/ohmyzsh#10081]
### Describe the bug

> NOTE: lesskey is deprecated.
>      It is no longer necessary to run lesskey,
>      when using less version 582 and later.

upon shell startup

### Steps to reproduce

1. `plugins=(... colemak)`
2. launch zsh

### Expected behavior

Clean prompt upon shell start

### OS / Distro

Arch Linux

### Zsh version

5.8

### Terminal emulator

kitty

### Additional context

Root of the issue is here:

https://github.com/ohmyzsh/ohmyzsh/blob/5377cc37c0f71fe22484303a4c6f387aa339f3f5/plugins/colemak/colemak.plugin.zsh#L22

Not sure what should be done about it though. I've disabled the plugin for now.

**Comment by mcornella** [comment]
Can you test #10102? You can do so with `omz pr test 10102`, it should still work without printing an error (delete the `$HOME/.less` file first).

**Comment by murlakatamenka** [comment]
Hi @mcornella it works fine here. 
Cloned the repo and within it I ran:

```sh
ZSH=. && source $ZSH/oh-my-zsh.sh && omz pr test 10102
```

It returns success error code (I'll omit the output, looks OK to me).

**Comment by mcornella** [comment]
Thanks!
