### ISSUE TITLE
No space added after "git fe<TAB>" (git fetch)

### ISSUE THREAD

**Issue by sryze** [ohmyzsh/ohmyzsh#10080]
### Describe the bug

If you type `git fe<TAB>` it will be auto-completed to `git fetch`, without a trailing space.

I think that oh-my-zsh should add a space after `fetch` because the fetch command is usually followed by remote name, such as `git fetch origin`.

### Steps to reproduce

1. Type `git fe`
2. Press `TAB` key

### Expected behavior

`$ git fetch ` (with trailing space)

### OS / Distro

macOS Big Sur

### Zsh version

5.8

### Terminal emulator

iTerm2

**Comment by ExoPlant** [comment]
Happens to me as well

**Comment by Macwin00X** [comment]
it's because you can complete with git fetch or git fetch-pack:

```
╰─ git fetch                                                                                                                                                                                                                                                                                                                                                   
fetch      -- download objects and refs from another repository
fetch-pack -- receive missing objects from another repository

```

**Comment by mcornella** [comment]
> it's because you can complete with git fetch or git fetch-pack:
> 
> ```
> ╰─ git fetch                                                                                                                                                                                                                                                                                                                                                   
> fetch      -- download objects and refs from another repository
> fetch-pack -- receive missing objects from another repository
> ```

That's the reason yes. Thanks for the solution!

**Comment by sryze** [comment]
When I do the same on Windows (via Git Bash), it does not preset the choice between `fetch` and `fetch-pack`, it just autocomplets to `fetch`. Perhaps ZSH should do the same. I don't think a lot of people use `fetch-pack`.

**Comment by mcornella** [comment]
> When I do the same on Windows (via Git Bash), it does not preset the choice between `fetch` and `fetch-pack`, it just autocompletes to `fetch`. Perhaps oh-my-zsh should do the same. I don't think a lot of people use `fetch-pack` daily in their shell.

They're both valid commands, so the completion should offer both. It really only takes pressing space once, which is the biggest key in the keyboard.
