### ISSUE TITLE
cd: string not in pwd

### ISSUE THREAD

**Issue by Dragonizedpizza** [ohmyzsh/ohmyzsh#10092]
### Describe the bug

When I run `cd Hurr*`, I get the error `cd: string not in pwd: Hurricano`.

### Steps to reproduce

1. Clone a repository via git.
2. Attempt to `cd` into it with *, like `cd SomeDir*`, where SomeDir is SomeDirectory.

### Expected behavior

Expected it to change into the correct directory.

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/70718540/128632315-a724fcdd-d8ea-448e-b18d-e6fbc1f3a1e3.png)

### OS / Distro

Ubuntu 18.04

### Zsh version

Zsh 5.4

### Terminal emulator

Gnome Terminal

### Additional context

I use [zsh-autocomplete](https://github.com/marlonrichert/zsh-autocomplete).

**Comment by rwmitchell** [comment]
Just curious, why are you using a wildcard (cd only takes 1 arg) when [TAB] (still a single character and '*' is actually 2, [SHIFT]-8) should expand to the proper thing?

**Comment by mcornella** [comment]
There are many issues like this one. `cd` expects one argument, if you pass a glob that expands to more than one that's the behavior you get.

**Comment by Dragonizedpizza** [comment]
> There are many issues like this one. `cd` expects one argument, if you pass a glob that expands to more than one that's the behavior you get.

but it doesn't expand to more than one

**Comment by rwmitchell** [comment]
> > There are many issues like this one. `cd` expects one argument, if you pass a glob that expands to more than one that's the behavior you get.
> 
> but it doesn't expand to more than one

My own testing shows that not to be the case.  Using cd with a wildcard in a directory name that matches a single entry, works.  Giving cd multiple arguments gives the error you reported.  Again, just use [TAB] - fewer keystrokes and it'll show any additional matches.

**Comment by rwmitchell** [comment]
> There are many issues like this one. `cd` expects one argument, if you pass a glob that expands to more than one that's the behavior you get.

Surprisingly (to me) that isn't true.  It'll take 2:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/15944841/128762029-997425a1-9d3f-484a-8f78-d9474b96a939.png">

**Comment by Dragonizedpizza** [comment]
> > > There are many issues like this one. `cd` expects one argument, if you pass a glob that expands to more than one that's the behavior you get.
> > 
> > 
> > but it doesn't expand to more than one
> 
> My own testing shows that not to be the case. Using cd with a wildcard in a directory name that matches a single entry, works. Giving cd multiple arguments gives the error you reported. Again, just use [TAB] - fewer keystrokes and it'll show any additional matches.

All I did was clone a repo (which has a 1 word name), and couldn't cd into it with a wild card.

**Comment by mcornella** [comment]
> Surprisingly (to me) that isn't true. It'll take 2:

[See the `old new` form of cd](https://zsh.sourceforge.io/Doc/Release/Shell-Builtin-Commands.html#index-cd). That's the behavior on more than one arguments. If there is no `old` part in pwd, you get the mentioned error.

> All I did was clone a repo (which has a 1 word name), and couldn't cd into it with a wild card.

Wasn't there another file or directory starting with `Hurr`? What does `print -l Hurr*` show?

**Comment by Dragonizedpizza** [comment]
> > Surprisingly (to me) that isn't true. It'll take 2:
> 
> [See the `old new` form of cd](https://zsh.sourceforge.io/Doc/Release/Shell-Builtin-Commands.html#index-cd). That's the behavior on more than one arguments. If there is no `old` part in pwd, you get the mentioned error.
> 
> > All I did was clone a repo (which has a 1 word name), and couldn't cd into it with a wild card.
> 
> Wasn't there another file or directory starting with `Hurr`? What does `print -l Hurr*` show?

![image](https://user-images.githubusercontent.com/70718540/128871871-c5f474db-8bc9-41ac-a4fd-5285c2dd4c70.png)

**Comment by rwmitchell** [comment]
And that is why it is failing which is exactly what we’ve been saying but you refused to read.

**Comment by Dragonizedpizza** [comment]
I thought it only picks the first case, sorry for all the trouble :sweat_smile:

**Comment by rwmitchell** [comment]
Reread all the responses carefully for any indication your expectations match the answers given. You completely avoided trying any of the suggestions.
