### ISSUE TITLE
zsh: command not found: $

### ISSUE THREAD

**Issue by ExoPlant** [ohmyzsh/ohmyzsh#10090]
### Describe the bug

On Manjaro 21.0.7 GNOME, using zsh already at the time of installing, I ran the installer (tried this with wget and curl). The last message was `2021-08-06 18:26:01 (6.40 MB/s) - written to stdout [9942/9942]`, after that, it said: ` zsh: command not found: $` I fixed this by instead of using `sh -c $(<wget/curl> <url>)`, I used `zsh -c $(<wget/curl <url>)` (obviously filling the contents between the <>)

### Steps to reproduce

Run the installer under latest Manjaro GNOME using terminal app Archipelago and zsh active

### Expected behavior

Install without errors

### OS / Distro

Manjaro 21.0.7 GNOME 

### Zsh version

5.8

### Terminal emulator

Archipelago

**Comment by mcornella** [comment]
This would go well with a screenshot of the actual output, I can't reproduce your problem unfortunately.
