### ISSUE TITLE
Error when use history -d

### ISSUE THREAD

**Issue by favadi** [ohmyzsh/ohmyzsh#1010]
I cannot use any of history option like -d, -D, -E, -f.
I always get this message.

```
fc: event not found: -d
```

**Comment by WilsonLopezRomero** [comment]
Where I can find that file nowadays ?

**Comment by mcornella** [comment]
It's in `lib/history.zsh` but you shouldn't change it there. Instead, you should redefine the history alias in your zshrc file. 

There's also a PR open to fix it, see #3422. If you test it and you find that `history -d` please +1 the PR. Thanks!
