### ISSUE TITLE
pyenv plugin still warns about bad configuration despite applying suggestion

### ISSUE THREAD

**Issue by ofhellsfire** [ohmyzsh/ohmyzsh#10114]
### Describe the bug

pyenv plugin still warns about bad configuration despite applying warning suggestion.

```
Found pyenv, but it is badly configured. pyenv might not work for
non-interactive shells (for example, when run from a script).

To fix this message, add these lines to the '.profile' and '.zprofile' files
in your home directory:

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

For more info go to https://github.com/pyenv/pyenv/#installation.
$ cat ~/.profile | grep -i pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
$ cat ~/.zprofile | grep -i pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

Looked through the code and if it found installation of pyenv it inevitably goes to the branch and prints the message. 

### Steps to reproduce

Add

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

to `.profile` and `.zprofile`

restart your shell

### Expected behavior

No warning message printed about bad configuration

### OS / Distro

Ubuntu 20.04

### Zsh version

5.4.2

### Terminal emulator

Gnome

**Comment by dcarbone** [comment]
I am also running into this on ubuntu 20.04.  It is highly annoying.

**Comment by mcornella** [comment]
Hi there, a logout might be necessary to apply the changes, since `.zprofile` only loads on login shells. See https://github.com/ohmyzsh/ohmyzsh/pull/9935#issuecomment-893497900

**Comment by mcornella** [comment]
This has now been documented in the plugin error.

**Comment by nathanielford** [comment]
I am getting this as well, because my path is setup in my custom folder. While it's set up correctly, custom integration there happens after the plugin loads. Not sure if there is a reasonable way around this, but I wanted to leave a comment in case any other users run into this problem.
