### ISSUE TITLE
ZSH shell cannot play mpv youtube stream video url, while bash is working fine.

### ISSUE THREAD

**Issue by rishabh3354** [ohmyzsh/ohmyzsh#10125]
### Describe the bug

i was trying to stream youtube video url from my zsh shell, but i was not able to play video. it is sending me error.. but when i tried same with my system bash shell is worked. i don't know why this is happening..

i am using:
UBuntu 20.04
zsh version zsh 5.8 (x86_64-ubuntu-linux-gnu)

here is the screenshot

1. with zsh shell it would not open.

![Screenshot from 2021-08-19 12-50-05](https://user-images.githubusercontent.com/26843758/130025829-e4eebaa4-911a-493b-975c-b7ac2e1e9db7.png)

2. with my system bash shell, it opens

![Screenshot from 2021-08-19 12-49-53](https://user-images.githubusercontent.com/26843758/130025913-d70bb8e7-6ba2-4dab-8ebb-c290857fe2f2.png)

here is the youtube stream url: (subject to be expires , you can get one from youtube-dl)

https://r7---sn-gwpa-cagl.googlevideo.com/videoplayback?expire=1629379165&ei=_QUeYfH7GO-mz7sP1Ne9yAU&ip=157.45.219.11&id=o-APTfwnUi67u69rbqWFeVsQuP8sISZpj8CIMsF-2rKkZd&itag=313&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313%2C394%2C395%2C396%2C397%2C398%2C399%2C400%2C401&source=youtube&requiressl=yes&mh=K2&mm=31%2C29&mn=sn-gwpa-cagl%2Csn-gwpa-cvh6&ms=au%2Crdu&mv=m&mvi=7&pcm2cms=yes&pl=19&initcwndbps=268750&vprv=1&mime=video%2Fwebm&ns=R4tcLV12NxETBbe8wP_uYrEG&gir=yes&clen=273025886&dur=161.160&lmt=1621576659137498&mt=1629357175&fvip=7&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5532434&n=E9TglqYvYIrIn0G1Fwl&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgP6iYigaEmIpY5t3pCh2bu-kV3z0FFREDmCltdzQf7kwCIQCoYo_ulBi_kvxOI1n-TKcYWSOnCwJx5r_JHkmDCJ32nw%3D%3D&sig=AOq0QJ8wRgIhAN20FBx8UxAZbSo07RwY2elfPmb_3O7AfAODrr8qKwfuAiEAo6WUGZDyzKqwz_9oxojhvRNArR7NfD_fgOSJM2WHT-0=

### Steps to reproduce

i have already given

### Expected behavior

It should play video in zsh shell

### OS / Distro

ubuntu 20.04

### Zsh version

zsh 5.8 (x86_64-ubuntu-linux-gnu)

### Terminal emulator

Gnome Terminal

**Comment by mcornella** [comment]
The URL passed to mpv is quoted twice: once because it's put between double quotes (`""`), and second because the special characters have a backslash (`\`). This is probably because of the `url-quote-magic` function that automatically quotes a URL on paste. Try pasting the URL without putting it in double quotes.

**Comment by rishabh3354** [comment]
> The URL passed to mpv is quoted twice: once because it's put between double quotes (`""`), and second because the special characters have a backslash (`\`). This is probably because of the `url-quote-magic` function that automatically quotes a URL on paste. Try pasting the URL without putting it in double quotes.

Thanks it worked without quote, May i ask you why we do not need to pass it in ""(double quotes), after all its a string. i know this is a feature, it handles string all it own, but at the same time its very confusing for me..

**Comment by mcornella** [comment]
This is a bug in `url-quote-magic`, since it should detect that you opened a double quote and not quote the special characters further. If you want to disable that, you can set `DISABLE_MAGIC_FUNCTIONS=true` in your zshrc file, before OMZ is sourced.

**Comment by rishabh3354** [comment]
> This is a bug in `url-quote-magic`, since it should detect that you opened a double quote and not quote the special characters further. If you want to disable that, you can set `DISABLE_MAGIC_FUNCTIONS=true` in your zshrc file, before OMZ is sourced.

Thanks for the answer @mcornella
