### ISSUE TITLE
chinese in git log of Mac will be like "<E9><80>..."

### ISSUE THREAD

**Issue by bolasblack** [ohmyzsh/ohmyzsh#1012]
commit 302424c4eae688feb1214a1b897f8a32ca9f5e3b
Author: c4605 
Date:   Sat Mar 10 10:27:45 2012 +0800

```
<E6><8A><8A><E5><87><A0><E4><B8><AA><E5><81><9A><E5><A5><BD><E7><9A><84><E4><B8><9C><E8><A5><BF><E6><8B>
```

**Comment by usergao** [comment]
recently i have same issue like this , but i set my locale to zh_CN.UTF-8 or zh_TW.UTF-8 . it dosen't work
