### ISSUE TITLE
Shell freezes after writing ssh <anything>@

### ISSUE THREAD

**Issue by ferrarienz0** [ohmyzsh/ohmyzsh#10132]
### Describe the bug

After writing ssh anything and pressing the @ or even pasting it, the shell becomes unresponsive.

### Steps to reproduce

1. Open Zsh
2. Install plugins fast-syntax-highlighting zsh-autosuggestions zsh-completions w/ zinit
2. Write ssh anything@
3. Shell becomes unresponsive

### Expected behavior

Should permit writing freely

### OS / Distro

Ubuntu 20.04

### Zsh version

5.8

### Terminal emulator

Gnome Terminal

**Comment by mcornella** [comment]
Try disabling the plugins one by one until you find the culprit.
