### ISSUE TITLE
two zsh history file

### ISSUE THREAD

**Issue by LiushuiXiaoxia** [ohmyzsh/ohmyzsh#10167]
### Describe the bug

some time, I need `bash` to work, when I use `zsh` to back. There are two zsh history file `.zsh_history` and `.zsh_historyz` . And some shell history was lost.

### Steps to reproduce

1. My plugins: 
```
plugins=(
  adb
  git
  # git-open
  #gradle
  textmate
  #autojump
  vscode
  timer
  sudo
  gradle-completion
)
```
2.  `bash` to change
3.  xxx to work
4. `zsh` to back oh my zsh

### Expected behavior

Before:
```
-rw-r--r--    1 xiaqiulei  staff   372K  9  8 11:18 .zsh_history
-rw-------    1 xiaqiulei  staff   372K  9  8 11:43 .zsh_historyz
```

`.zsh_historyz` file size is 372k.

`bash ` and then `zsh`

```
-rw-r--r--    1 xiaqiulei  staff   372K  9  8 11:18 .zsh_history
-rw-------    1 xiaqiulei  staff    15K  9  8 11:44 .zsh_historyz
```

`.zsh_historyz` file size is 15k，some history was lost

### OS / Distro

macOS Big Sur 11.5.2 

### Zsh version

5.8

### Terminal emulator

iTerm2

**Comment by mcornella** [comment]
Why are there two history files? Are you running `export HISTFILE` in either bash or zsh?

**Comment by LiushuiXiaoxia** [comment]
ok, it is my mistake，thanks
