### ISSUE TITLE
Add ndjson pretty print to jsontools

### ISSUE THREAD

**Issue by eduardofv** [ohmyzsh/ohmyzsh#10177]
### If the feature request is for a plugin or theme, specify it here.

jsontools

### If the feature solves a problem you have, specify it here.

JSON lines (http://ndjson.org) is a format that extends JSON standard to multi-line independent json objects. It's used on streaming, json storage, etc. Sometimes it's necessary to see easily whole or part of such a file.

### Describe the proposed feature.

Want to be able to easy view ndjson streams:
```
# echo two separate json objects and pretty print both
echo '{"a": "b"}\n{"c": [1,2,3]}' | pp_ndjson
```

### Describe alternatives you've considered

python -m json.tool 

### Additional context

Submitted PR #10176 to address this

**Comment by mcornella** [comment]
If you submit a PR you don't have to open an issue.
