### ISSUE TITLE
git prompt very slow in git repo directory

### ISSUE THREAD

**Issue by xiedeacc** [ohmyzsh/ohmyzsh#10175]
### Describe the bug

as title, I notice is oh-my-zsh run git command on git repo directory caused very slow, git takes over 80% CPU these time, how can I fix it ?

### Steps to reproduce

cd xxx(like cocoapods cache directory or other git director)
ls (oops, let me go die, extremly slow)

### Expected behavior

fast

### OS / Distro

macos catalina

### Zsh version

5.7.1

### Terminal emulator

iterm2

**Comment by mcornella** [comment]
Try running this (copy-paste into the terminal) and cd into the repo to see if it no longer blocks the prompt:
```zsh
__git_prompt_git () {
	GIT_OPTIONAL_LOCKS=0 command timeout 1s git "$@"
}
```

**Comment by xiedeacc** [comment]
remove oh-my-zsh 

> Try running this (copy-paste into the terminal) and cd into the repo to see if it no longer blocks the prompt:
> 
> ```shell
> __git_prompt_git () {
> 	GIT_OPTIONAL_LOCKS=0 command timeout 1s git "$@"
> }
> ```

this will set git timeout 1s, will it affect all my git operation?

**Comment by xiedeacc** [comment]
> Try running this (copy-paste into the terminal) and cd into the repo to see if it no longer blocks the prompt:
> 
> ```shell
> __git_prompt_git () {
> 	GIT_OPTIONAL_LOCKS=0 command timeout 1s git "$@"
> }
> ```

after turn on DISABLE_UNTRACKED_FILES_DIRTY="true", oh-my-zsh much faster, but it also slowly a litte bit, anyway it's bearable

**Comment by milipili** [comment]
I noticed both plugins `git` and `gitfast` are very slow when using git lfs (and have medium to large files)

**Comment by EricMzky** [comment]
> 我注意到这两个插件`git`并且`gitfast`在使用 git lfs 时非常慢（并且有中到大文件） 但是设置 git 设置如下解决了缓慢问题
> 
> ```
> git config --global --add oh-my-zsh.hide-status 1
> git config --global --add oh-my-zsh.hide-dirty 1
> ```

How can I go back to the previous look when I can't visually display git related branches? Is there any other solution?

> > 尝试运行它（复制粘贴到终端）并 cd 进入 repo 以查看它是否不再阻止提示：
> > ```shell
> > __git_prompt_git () {
> > 	GIT_OPTIONAL_LOCKS=0命令超时 1s git " $@ " 
> > }
> > ```
> 
> 开启 DISABLE_UNTRACKED_FILES_DIRTY="true" 后，oh-my-zsh 快多了，但也慢了一点，反正可以忍受

How can I go back to the previous look when I can't visually display git related branches? Is there any other solution?

**Comment by ChiragDogra** [comment]
> ```shell
> __git_prompt_git () {
> 	GIT_OPTIONAL_LOCKS=0 command timeout 1s git "$@"
> }
> ```

would you please elaborate the whole process
