### ISSUE TITLE
Trying to create completions directory under $ZSH/cache fails

### ISSUE THREAD

**Issue by pakro** [ohmyzsh/ohmyzsh#10193]
### Describe the bug

Since the last update I get the following error every time I'm opening my terminal:

`mkdir: cannot create directory ‘/usr/share/oh-my-zsh//cache/completions’: Permission denied`

echo $ZSH -> /usr/share/oh-my-zsh/
scho $ZSH_CACHE_DIR -> /usr/share/oh-my-zsh//cache

both folders are present. I have never changed permissions. What am I doing wrong?

### Steps to reproduce

Start the terminal

### Expected behavior

No error is shown

### OS / Distro

Arch

### Zsh version

5.8-1

### Terminal emulator

xfce4-terminal

### Additional context
The following packages are explicitly installed that are related to oh-my-zsh and may also be the problem

oh-my-zsh-git r6147.eb2eacaf0-1
zsh 5.8-1
zsh-syntax-highlighting 0.7.1-1
zsh-theme-powerlevel10k-git r3938.7a72acf-1

**Comment by rwmitchell** [comment]
Even though you didn't change permissions, you have checked to see how they are currently set?
```ls -ld $ZSH $ZSH_CACHE_DIR```

Isn't the default to have those in your home directory, as opposed to a general purpose area?

**Comment by pakro** [comment]
drwxr-xr-x - root 15 Sep 19:59 /usr/share/oh-my-zsh/cache
drwxr-xr-x - root 15 Sep 19:59 /usr/share/oh-my-zsh

you are right.. the cache folder should be in my home folder... at least this same command on my laptop say:

drwxr-xr-x - paul 15 Sep 19:49 /home/paul/.cache/oh-my-zsh

I will compare configurations... Not understanding why this is so different

**Comment by mcornella** [comment]
I believe that path is the one set by the oh-my-zsh-git package distributed by Arch Linux. I've pushed a fix that sets the directory to `$HOME/.cache/oh-my-zsh`, [as the Arch Linux package does](https://aur.archlinux.org/cgit/aur.git/tree/0001-zshrc.patch?h=oh-my-zsh-git).

It's weird that you had this error though, since the Arch Linux package moves the init of OMZ to after `$ZSH_CACHE_DIR` has been redefined.

**Comment by pakro** [comment]
I replaced my .zshrc for testing purposes with the one on my laptop and the error was gone.

**Comment by pakro** [comment]
@mcornella  I replaced the working one with the broken and installed the new version of oh-my-zsh-git from AUR which contains your fix and now my old config is working again.
