### ISSUE TITLE
[Fluxcd Plugin] Create a FluxCD plugin for the autocompetion

### ISSUE THREAD

**Issue by arthtux** [ohmyzsh/ohmyzsh#10196]
### If the feature request is for a plugin or theme, specify it here.

Fluxdc plugins

### Describe the proposed feature.

The plugin make the autocompletion with the command Flux
Documentation is here -> https://fluxcd.io/docs/cmd/flux_completion_zsh/

**Comment by mcornella** [comment]
If you have a PR ready why do you open an issue? You're not the first to do it, I'm just curious why people do that? Should I update some docs?
