### ISSUE TITLE
gdu alias conflicts with go disk usage analyzer

### ISSUE THREAD

**Issue by y0tka** [ohmyzsh/ohmyzsh#10201]
### Describe the bug

The `gdu` alias conflicts with the [go disk usage analyzer](https://github.com/dundee/gdu).

### Steps to reproduce

1. Install Oh-My-Zsh and git plugin
2. Install dundee's gdu
3. Type gdu
4. `git diff` alias executes

### Expected behavior

1. Install Oh-My-Zsh and git plugin
2. Install dundee's gdu
3. Type gdu
4. dundee's `gdu` starts

### Screenshots and recordings

```
> where gdu
gdu: aliased to git diff @{u}
/bin/gdu
/usr/bin/gdu
/bin/gdu
```

### OS / Distro

Arch Linux

### Zsh version

5.8

### Terminal emulator

alacritty

**Comment by igor-simoes** [comment]
Can I fix this issue by ignoring `git`(or all plugins) aliases that conflict with OS commands? What do you think?
