### ISSUE TITLE
installing this overwrote my zshrc file

### ISSUE THREAD

**Issue by gajduk** [ohmyzsh/ohmyzsh#10212]
### Describe the bug

Upon installing the time my entire zshrc file was overwritten without warning.
Please fix this bug. Either append or create an automatic backup.

### Steps to reproduce

Install ohmzzsh

### Expected behavior

Does not do destrcutvie actions

### OS / Distro

macOS

### Zsh version

NA

### Terminal emulator

NA

**Comment by pixelsailor** [comment]
Possibly related. Updated today and node/npm along with my other installed CLI applications were wiped

**Comment by rwmitchell** [comment]
Where were these CLI applications stored?  Are you sure it isn't just the path that was changed?

**Comment by pixelsailor** [comment]
Possibly it was a path change. I'm not technically savvy enough to know for sure. I believe it was only things installed via npm. Used NVM to reinstall node and any global installs, so in my case, it was simple to restore

**Comment by mcornella** [comment]
The installer never deletes old copies of `.zshrc` files: https://github.com/ohmyzsh/ohmyzsh/blob/2ea1fa6cbfc6340463906dfed589d5c976a10abb/tools/install.sh#L222-L224

Look in `~/.zshrc.pre-oh-my-zsh` or `~/.zshrc.pre-oh-my-zsh-<date>`.
