### ISSUE TITLE
[docker-compose plugin] Docker Compose 2.0 compatibility breakage

### ISSUE THREAD

**Issue by vijuarez** [ohmyzsh/ohmyzsh#10241]
### Describe the bug

With the recent release of [Docker Compose 2.0](https://github.com/docker/compose) the plugin no longer works as intended, with the most obvious change being commands changing from `docker-compose *` to `docker compose *`. 

### Steps to reproduce

1. Enable plugin in a system with the latest Docker Compose.
2. Run any command shortcut.
3. Watch it complain with `zsh: command not found: docker-compose`

### Expected behavior

The plugin should use the correct commands for the currently installed Docker Compose version. For now, I believe that a warning on the documentation about the plugin only being valid for Docker Compose v1 should be enough. Requiring [compose-switch](https://github.com/docker/compose-switch) would also solve the problem, but I personally had some trouble with it.

### OS / Distro

Arch Linux

### Zsh version

5.8

### Terminal emulator

Konsole

**Comment by Frederick888** [comment]
Just noticed that starting from `docker-compose 2.0.1`, a symbolic link `usr/bin/docker-compose -> /usr/lib/docker/cli-plugins/docker-compose` is provided in Arch package. Not sure if official packages / other distros are going to follow suit.

**Comment by Joniator** [comment]
There is a [compose-switch ](https://docs.docker.com/compose/cli-command/#compose-switch) mentioned in the official documentation, which should behave similiar to the way Arch does it. 

There was also some discussion in PR #10231 regarding an update to the plugin

**Comment by mcornella** [comment]
Is there a way to test if `docker compose` is available?

**Comment by mcornella** [comment]
Opened #10248 to support the new version, test it out with `omz pr test 10248`. Thanks!

**Comment by vijuarez** [comment]
@mcornella I can confirm that the PR works for both Compose V2 vanilla and the Arch workaround that @Frederick888 mentioned.

**Comment by mcornella** [comment]
Thanks!
