### ISSUE TITLE
Recent change to oh-my-zsh.sh makes it so zsh completely fails to load

### ISSUE THREAD

**Issue by samvimes42** [ohmyzsh/ohmyzsh#10260]
Starting with commit 7152a942802b01cb74d7c0b99f3106f8af17439d, when I try to open a terminal instance, zsh completely fails to load because it cannot parse the new f function that was added at the beginning of the file. When I delete the new code added by that commit and the previous one, zsh loads properly.

**Comment by mcornella** [comment]
Which zsh version are you running?

**Comment by ThatCooperLewis** [comment]
I am seeing the same issue, here's the full printout when running `zsh`

```
/Users/<user>/.oh-my-zsh/oh-my-zsh.sh:5: defining function based on alias `f'
/Users/<user>/.oh-my-zsh/oh-my-zsh.sh:5: parse error near `()'
```

This is on the latest 568584a master commit.

**Comment by ThatCooperLewis** [comment]
@mcornella `f='find . -iname'`

**Comment by ThatCooperLewis** [comment]
I can also confirm that reverting to master commit `c6c3643` (the commit before `7152a94`) resolves this issue

**Comment by samvimes42** [comment]
I see the same error as @ThatCooperLewis. 
Here is my zsh version: `zsh 5.8 (x86_64-ubuntu-linux-gnu)`
Here is my f alias: `f='fasd -f'`
My f alias is from the app fasd.

**Comment by mcornella** [comment]
You should be good to go if you still can update with `omz update`. Otherwise manually upgrade by running `$ZSH/tools/upgrade.sh`.

**Comment by ThatCooperLewis** [comment]
a54148a fixed it for me, thanks @mcornella !!
