### ISSUE TITLE
History prefix search not working

### ISSUE THREAD

**Issue by alex-treebeard** [ohmyzsh/ohmyzsh#10272]
### Describe the bug

when I type the start of a command e.g. `npm` then hit the up arrow, I simply see the previous command, even if it didn't start with `npm`

### Steps to reproduce

1. echo "hello"
2. pwd
3. type echo, hit up

It will say `pwd`

### Expected behavior

It will say `echo "hello"`

### OS / Distro

Darwin Kernel Version 20.6.0

### Zsh version

5.8

### Terminal emulator

iTerm2

### Additional context

I tried manually enabling `omz plugin enable history-substring-search`

**Comment by mcornella** [comment]
Thanks for the quick response. Remember to file a bug in fig!
