### ISSUE TITLE
Commands printed along with output

### ISSUE THREAD

**Issue by joelpeapen** [ohmyzsh/ohmyzsh#10286]
### Describe the bug

When oh-my-Zsh is enabled commands are always printed out along with ouput. No problem when omz is diabled.

### Steps to reproduce

Run any command

### Expected behavior

Command will be printed along with output.

### Screenshots and recordings

Echo is printed along with output.

![omzBug](https://user-images.githubusercontent.com/67512946/136808126-74eb09b6-7090-49af-9e40-7fb26ad6234a.png)

### OS / Distro

Ubuntu

### Zsh version

5.8

### Terminal emulator

Gnome Terminal

### Additional context

Using powerlevel10k prompt and zsh-autosuggestions, installed manually.

**Comment by igavelyuk** [comment]
@joelpeapen Cannot confirm this. 

#### Test on two systems, on one with fresh install of zsh. Second working great, so I'm completely remove and reinstall and it working great.
---
#### Copm1
```bash
-> ~ zsh --version
zsh 5.4.2 (x86_64 - ubuntu-linux-gnu)
-> ~ uname -ra
Linux username-Test 5.4.0-66 - generic #74-18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC ......
```
---
#### Comp2
```bash
% zsh --version
zsh 5.8 (x86_64-ubuntu-linux-gnu)
% uname -ar 
Linux cores-A58MD 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### How I'm install it:
```bash
$ sudo apt-get install zsh
$ sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```
 Check if any plugins installed for terminal, try remove 

>  /home/UserName/.oh-my-zsh/
>  /home/UserName/.zsh_history
>  /home/UserName/.zshrc

and reinstall OMZ
