### ISSUE TITLE
README: Update "Getting Updates" docs to reflect `zstyle` settings

### ISSUE THREAD

**Issue by jjspace** [ohmyzsh/ohmyzsh#10288]
Piggybacking off of https://github.com/ohmyzsh/ohmyzsh/issues/10187 it seems that with commit https://github.com/ohmyzsh/ohmyzsh/commit/3c9743313cc916a6cede71e333eecef4b07ce3ce the settings outlined in the [Getting Updates](https://github.com/ohmyzsh/ohmyzsh#getting-updates) section of the README will no longer work at all. I would've been nice to see a bit of backwards compatability so the old settings still worked but looking at the diff of that commit that doesn't seem to be the case? Regardless if OMZ is moving to `zstyle` settings it would be nice to have those called out more explicitly in the changelog _and_ always make sure the docs are updated to reflect that.

CC. @mcornella because you made this change

**Comment by mcornella** [comment]
> I would've been nice to see a bit of backwards compatability so the old settings still worked but looking at the diff of that commit that doesn't seem to be the case?

It is the case:
https://github.com/ohmyzsh/ohmyzsh/commit/3c9743313cc916a6cede71e333eecef4b07ce3ce#diff-d89110a4c1bd39eb40e5725c84e65531c5064ffc1b4923227afb0def729f5401R15-R17

> _and_ always make sure the docs are updated to reflect that.

Good point, also making a note of [changing the wiki](https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#update-settings).
