### ISSUE TITLE
Add an alias to stash only staged changes

### ISSUE THREAD

**Issue by RaniAgus** [ohmyzsh/ohmyzsh#10300]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### If the feature solves a problem you have, specify it here.

Sometimes I want to stash some of my changes for later and keep some others for now. I use [this oneliner I found in stackoverflow](https://stackoverflow.com/a/59874960):
```
git stash -- $(git diff --staged --name-only)
```

### Describe the proposed feature.

It would be great if you could add a shortcut for this, maybe `gstst`.

**Comment by iccowan** [comment]
Proposed this change in #10301

**Comment by carlosala** [comment]
Looks like git added a command (`git stash --staged` in v2.35). That's not necessary anymore!
https://github.com/ohmyzsh/ohmyzsh/pull/10301#issuecomment-1081796104
