### ISSUE TITLE
Tracking: `kubectl` plugin

### ISSUE THREAD

**Issue by mcornella** [ohmyzsh/ohmyzsh#10312]
- https://github.com/ohmyzsh/ohmyzsh/pull/6539
- https://github.com/ohmyzsh/ohmyzsh/pull/7777
- https://github.com/ohmyzsh/ohmyzsh/pull/7828
- https://github.com/ohmyzsh/ohmyzsh/pull/7849
- https://github.com/ohmyzsh/ohmyzsh/pull/8047
- https://github.com/ohmyzsh/ohmyzsh/pull/8073
- https://github.com/ohmyzsh/ohmyzsh/pull/8114
- https://github.com/ohmyzsh/ohmyzsh/pull/8127
- https://github.com/ohmyzsh/ohmyzsh/pull/8290
- https://github.com/ohmyzsh/ohmyzsh/pull/8309
- https://github.com/ohmyzsh/ohmyzsh/pull/8313
- https://github.com/ohmyzsh/ohmyzsh/pull/8480
- https://github.com/ohmyzsh/ohmyzsh/pull/8684
- https://github.com/ohmyzsh/ohmyzsh/pull/8699
- https://github.com/ohmyzsh/ohmyzsh/pull/8738
- https://github.com/ohmyzsh/ohmyzsh/pull/8810
- https://github.com/ohmyzsh/ohmyzsh/pull/8851
- https://github.com/ohmyzsh/ohmyzsh/pull/9161
- https://github.com/ohmyzsh/ohmyzsh/pull/9243
- https://github.com/ohmyzsh/ohmyzsh/pull/9373
- https://github.com/ohmyzsh/ohmyzsh/pull/9446
- https://github.com/ohmyzsh/ohmyzsh/pull/9578
- https://github.com/ohmyzsh/ohmyzsh/pull/9642
- https://github.com/ohmyzsh/ohmyzsh/pull/9846
- https://github.com/ohmyzsh/ohmyzsh/pull/9992
- https://github.com/ohmyzsh/ohmyzsh/pull/10003
- https://github.com/ohmyzsh/ohmyzsh/pull/10093
- https://github.com/ohmyzsh/ohmyzsh/pull/10100
- https://github.com/ohmyzsh/ohmyzsh/pull/10242
- https://github.com/ohmyzsh/ohmyzsh/pull/10249

**Comment by sid-maddy** [comment]
@mcornella, could I suggest closing the multiple PRs re: adding HPA related aliases and merging the newest one?

PRs adding aliases for HPA management:
- https://github.com/ohmyzsh/ohmyzsh/pull/7777
- https://github.com/ohmyzsh/ohmyzsh/pull/8127
- https://github.com/ohmyzsh/ohmyzsh/pull/9846
- https://github.com/ohmyzsh/ohmyzsh/pull/10242
- https://github.com/ohmyzsh/ohmyzsh/pull/10249
