### ISSUE TITLE
Git checkout only local branches

### ISSUE THREAD

**Issue by angelod1as** [ohmyzsh/ohmyzsh#10323]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### If the feature solves a problem you have, specify it here.

Every time I `gco [tab]` it takes forever to show 200+ lines in some projects. I'd love a `gco` with only local branches. [I found this possible implementation](https://cmetcalfe.ca/blog/git-checkout-autocomplete-local-branches-only.html) but didn't have success setting it up.

### Describe the proposed feature.

`gcol`(for local) is a possible solution: `git checkout` only showing local branches.

### Describe alternatives you've considered

I tried [this](https://cmetcalfe.ca/blog/git-checkout-autocomplete-local-branches-only.html) but it didn't work. I might've implemented it wrongly. or it just doesn't work.

**Comment by mcornella** [comment]
This is really niche, so I won't add a fix in the git plugin. Instead you can use this code that you can add to your zshrc file, which adds the `gcol` function with completion for only local branches:
```zsh
gcol() {
	command git checkout "$@" --
}
_gcol() {
	_alternative 'branches::__git_branch_names'
}
compdef _gcol gcol
```
