### ISSUE TITLE
#9005 created a conflict with Git aliases

### ISSUE THREAD

**Issue by luizkowalski** [ohmyzsh/ohmyzsh#10320]
### Describe the bug

The PR https://github.com/ohmyzsh/ohmyzsh/pull/9005/files introduced the command `gcb` as an alias to `gem cert --build` but `gcb` is already used as `git checkout -b` for quite some time now.

### Steps to reproduce

1. Enable ruby and git plugin
2. run `gcb`

### Expected behavior

I believe `gcb` on ruby should have a new alias

### OS / Distro

MacOS 11.6

### Zsh version

5.8

### Terminal emulator

iTerm

**Comment by paneidos** [comment]
Also `gl` which has been `git pull` for a long time.

In addition it shadows `go`and `gh`, which are commands likely to exist on a developer's machine.
