### ISSUE TITLE
systemadmin: use ss instead of the deprecated netstat

### ISSUE THREAD

**Issue by Langlais115** [ohmyzsh/ohmyzsh#10330]
### If the feature request is for a plugin or theme, specify it here.

systemadmin

### If the feature solves a problem you have, specify it here.

Can I update all functions that are using **netstat** by **ss**?
As in Ubuntu 20.04 the net-tools package is not included by default anymore

### Describe the proposed feature.

Replace all functions using **netstat** by **ss**.

**Comment by arrrgi** [comment]
Just to clear things up for anyone else who stumbles on this issue, **Netstat is not deprecated** in Ubuntu. They have moved it out of the core and into the `net-tools` package from 20.04 onwards.

**Comment by mcornella** [comment]
See http://manpages.ubuntu.com/manpages/focal/en/man8/netstat.8.html#notes
> ## NOTES
> >      This  program is mostly obsolete.  Replacement for netstat is ss.  Replacement for netstat
> >      -r is ip route.  Replacement for netstat -i is ip -s link.  Replacement for netstat -g  is
> >      ip maddr.
