### ISSUE TITLE
fatal error: runtime: bsdthread_register error

### ISSUE THREAD

**Issue by febriyan1302** [ohmyzsh/ohmyzsh#10354]
### Describe the bug

Hello,

i've got error `fatal error: runtime: bsdthread_register error` after update to MacOS Monterey (12.0.1)

<img width="1116" alt="Screen Shot 2021-10-27 at 11 59 23" src="https://user-images.githubusercontent.com/18423871/139002587-adf183bb-0cc2-4995-8533-fee2eca4d7d3.png">

### Steps to reproduce

After enabling theme

<img width="369" alt="Screen Shot 2021-10-27 at 12 32 34" src="https://user-images.githubusercontent.com/18423871/139005659-6c3f869c-31f3-454f-9cae-45ccc14f7005.png">

### Expected behavior

Nothing error `fatal error: runtime: bsdthread_register error` like previously on BigSur

### OS / Distro

MacOS Monterey (12.0.1)
Intel Chip

### Zsh version

5.7.1 (x86_64-apple-darwin19.0.0)

### Terminal emulator

iTerm2

**Comment by blastik** [comment]
@mcornella I'm also having this issue.
at least in my case it's due the `kubectl` plugin. it's weird because kubectl it's normally but when loading zsh it outputs exactly the same go exception
after the error kubectl aliases and everything else work fine. TBH i'm not able to find the cause of the issue.
BTW also in Monterey myself

**Comment by mcornella** [comment]
> @mcornella I'm also having this issue.
> at least in my case it's due the `kubectl` plugin. it's weird because kubectl it's normally but when loading zsh it outputs exactly the same go exception
> after the error kubectl aliases and everything else work fine. TBH i'm not able to find the cause of the issue.
> BTW also in Monterey myself

Well the only kubectl call the plugin makes is to source the completion. Can you trigger it by running [the same command](https://github.com/ohmyzsh/ohmyzsh/blob/eabec36586f990b883e7dbf4583e6d86ac46c7ea/plugins/kubectl/kubectl.plugin.zsh#L18)?

```
kubectl completion zsh
```

**Comment by mcornella** [comment]
In https://github.com/kubernetes/kubectl/issues/1142, the final diagnosis was that [this happens due to binaries compiled with old versions of Go](https://github.com/kubernetes/kubectl/issues/1142#issuecomment-967274236):
> As Brian points out this is an issue with running binaries built with older versions of Go.
>
>Please upgrade your binaries.

Maybe upgrading `kubectl` is going to be the solution.

---
In @febriyan1302's case, the culprit might be `oc` since that is also Go-based and the plugin uses `oc completion zsh` to load the completion. The solution is probably the same.

**Comment by blastik** [comment]
> > @mcornella I'm also having this issue.
> > at least in my case it's due the `kubectl` plugin. it's weird because kubectl it's normally but when loading zsh it outputs exactly the same go exception
> > after the error kubectl aliases and everything else work fine. TBH i'm not able to find the cause of the issue.
> > BTW also in Monterey myself
> 
> Well the only kubectl call the plugin makes is to source the completion. Can you trigger it by running [the same command](https://github.com/ohmyzsh/ohmyzsh/blob/eabec36586f990b883e7dbf4583e6d86ac46c7ea/plugins/kubectl/kubectl.plugin.zsh#L18)?
> 
> ```
> kubectl completion zsh
> ```

no issues when i run that, just printing the `# zsh completion for kubectl                              -*- shell-script -*-`

**Comment by mcornella** [comment]
Try updating `kubectl` to check whether the error is gone on zsh startup.

**Comment by blastik** [comment]
> Try updating `kubectl` to check whether the error is gone on zsh startup.

it's already quite new

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by mcornella** [comment]
Ok then you need to make sure that line is the problem. You should add a couple of `echo`s before and after the command is run in `plugins/kubectl/kubectl.plugin.zsh`, something like:
```patch
diff --git a/plugins/kubectl/kubectl.plugin.zsh b/plugins/kubectl/kubectl.plugin.zsh
index 6edb5975..14e8c585 100644
--- a/plugins/kubectl/kubectl.plugin.zsh
+++ b/plugins/kubectl/kubectl.plugin.zsh
@@ -11,11 +11,14 @@ if (( $+commands[kubectl] )); then
   # If the completion file does not exist, generate it and then source it
   # Otherwise, source it and regenerate in the background
   if [[ ! -f "$ZSH_CACHE_DIR/completions/_kubectl" ]]; then
+    echo 1: before
     kubectl completion zsh >| "$ZSH_CACHE_DIR/completions/_kubectl"
+    echo 1: after
     source "$ZSH_CACHE_DIR/completions/_kubectl"
   else
     source "$ZSH_CACHE_DIR/completions/_kubectl"
-    kubectl completion zsh >| "$ZSH_CACHE_DIR/completions/_kubectl" &|
+    echo 2: before
+    (kubectl completion zsh >| "$ZSH_CACHE_DIR/completions/_kubectl"; echo 2:after) &|
   fi
 fi
 
```

**Comment by blastik** [comment]
> ```diff
> echo 2: before
> ```

```
2: before
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x23d3b5f, 0x21)
        /usr/local/go/src/runtime/panic.go:616 +0x81 fp=0x7ff7bfeff288 sp=0x7ff7bfeff268 pc=0x1028ff1
runtime.goenvs()
        /usr/local/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff2b8 sp=0x7ff7bfeff288 pc=0x1026b73
runtime.schedinit()
        /usr/local/go/src/runtime/proc.go:501 +0xd6 fp=0x7ff7bfeff320 sp=0x7ff7bfeff2b8 pc=0x102b8e6
runtime.rt0_go(0x7ff7bfeff350, 0x3, 0x7ff7bfeff350, 0x1000000, 0x3, 0x7ff7bfeff530, 0x7ff7bfeff538, 0x7ff7bfeff543, 0x0, 0x7ff7bfeff547, ...)
        /usr/local/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff328 sp=0x7ff7bfeff320 pc=0x1052174
2: after
```

**Comment by blastik** [comment]
> Ok then you need to make sure that line is the problem. You should add a couple of `echo`s before and after the command is run in `plugins/kubectl/kubectl.plugin.zsh`, something like:
> 
> ```diff
> diff --git a/plugins/kubectl/kubectl.plugin.zsh b/plugins/kubectl/kubectl.plugin.zsh
> index 6edb5975..14e8c585 100644
> --- a/plugins/kubectl/kubectl.plugin.zsh
> +++ b/plugins/kubectl/kubectl.plugin.zsh
> @@ -11,11 +11,14 @@ if (( $+commands[kubectl] )); then
>    # If the completion file does not exist, generate it and then source it
>    # Otherwise, source it and regenerate in the background
>    if [[ ! -f "$ZSH_CACHE_DIR/completions/_kubectl" ]]; then
> +    echo 1: before
>      kubectl completion zsh >| "$ZSH_CACHE_DIR/completions/_kubectl"
> +    echo 1: after
>      source "$ZSH_CACHE_DIR/completions/_kubectl"
>    else
>      source "$ZSH_CACHE_DIR/completions/_kubectl"
> -    kubectl completion zsh >| "$ZSH_CACHE_DIR/completions/_kubectl" &|
> +    echo 2: before
> +    (kubectl completion zsh >| "$ZSH_CACHE_DIR/completions/_kubectl"; echo 2: after) &|
>    fi
>  fi
>  
> ```

```
2: before
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x23d3b5f, 0x21)
        /usr/local/go/src/runtime/panic.go:616 +0x81 fp=0x7ff7bfeff288 sp=0x7ff7bfeff268 pc=0x1028ff1
runtime.goenvs()
        /usr/local/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff2b8 sp=0x7ff7bfeff288 pc=0x1026b73
runtime.schedinit()
        /usr/local/go/src/runtime/proc.go:501 +0xd6 fp=0x7ff7bfeff320 sp=0x7ff7bfeff2b8 pc=0x102b8e6
runtime.rt0_go(0x7ff7bfeff350, 0x3, 0x7ff7bfeff350, 0x1000000, 0x3, 0x7ff7bfeff530, 0x7ff7bfeff538, 0x7ff7bfeff543, 0x0, 0x7ff7bfeff547, ...)
        /usr/local/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff328 sp=0x7ff7bfeff320 pc=0x1052174
2: after
```

**Comment by mcornella** [comment]
Yes, that looks like the problem. It might be that it doesn't handle well the case where it's run in the background, so can you test the same command in the background to see it that triggers the error?

```
kubectl completion zsh &|
```

**Comment by blastik** [comment]
> Yes, that looks like the problem. It might be that it doesn't handle well the case where it's run in the background, so can you test the same command in the background to see if that triggers the error?
> 
> ```
> kubectl completion zsh &|
> ```

nope. i dont see the error :/

**Comment by mcornella** [comment]
What about
```
kubectl completion zsh > /dev/null &| 
```

**Comment by blastik** [comment]
> kubectl completion zsh > /dev/null &|

nope

**Comment by mcornella** [comment]
OK then, if you disable the plugin and put that same command in your zshrc file, does it start with an error?

**Comment by mcornella** [comment]
Also is it really kubectl that panics?

**Comment by blastik** [comment]
> kubectl completion zsh > /dev/null &|
no luck
<img width="1052" alt="Screenshot 2022-01-31 at 16 54 16" src="https://user-images.githubusercontent.com/3662083/151827140-644eb396-5eb0-4201-943b-f9d8b687eca6.png">

**Comment by blastik** [comment]
> Also is it really kubectl that panics?

as I said earlier kubectl runs totally well. its just that annoying panic whenever i open a new zsh window

**Comment by mcornella** [comment]
> no luck

Looks like that's what causing the panic though, which is what I was trying to cause. It seems to me that if you have a kubectl binary compiled with go1.17.3 you should be able to post a new issue to either kubectl's repo (https://github.com/kubernetes/kubectl/issues/1142) or [go itself](https://github.com/golang/go/issues/49425#issuecomment-964621714):
> It appears that this issue only occurs with binaries built with old unsupported versions of Go. Closing. See [golang.org/wiki/MacOS12BSDThreadRegisterIssue](https://golang.org/wiki/MacOS12BSDThreadRegisterIssue)
> 
> If anyone has a reproduce with a program built with Go 1.16 or later, feel free to reopen. Thanks.

Make sure that you have the smallest reproducible zshrc file. Also test for the command without the `&|` in your zshrc file.

**Comment by blastik** [comment]
Definitely looks like https://golang.org/wiki/MacOS12BSDThreadRegisterIssue is the culprit.
Since I install kubectl using [asdf](https://github.com/asdf-vm/asdf) I've raised [this ticket](https://github.com/asdf-community/asdf-kubectl/issues/25) to see what they say

Thanks for your help
