### ISSUE TITLE
Ohmyzsh ceases to show branch name

### ISSUE THREAD

**Issue by bondeanikets** [ohmyzsh/ohmyzsh#10356]
Since the last update, my terminal does not show the branch name in the command prompt by default, with it did before. I have not changed "~/.zshrc", plus I keep the default configurations for the theme. 
<img width="450" alt="Screen Shot 2021-10-27 at 5 01 55 PM" src="https://user-images.githubusercontent.com/23046701/139164221-f98303df-c4b1-40b5-9c53-d5133031b045.png">

**Comment by llraphael** [comment]
Hi @mcornella, the unset works one time. But as soon as I change dir in the repo (or just Ctrl+C), the branch disappear again. It seems there is process that unset the 'unset` cmd. Do you have any insights on what might cause this? Thanks.
