### ISSUE TITLE
ZSH do not add commands with a space in the beginning to the history

### ISSUE THREAD

**Issue by CryptoMathician** [ohmyzsh/ohmyzsh#10364]
### Describe the bug

For me and also other Person, who use ZSH, have the issue that if you add a command with a space in the beginning this command will not be added to the history. 
An example:
```
 touch test
```
When you now check the history with `history` the ` touch test` command is not in the history.

### Steps to reproduce

1. ` touch test`
2. `history`

### Expected behavior

The expected behavior is that this command shows up in the history.

### OS / Distro

Arch Linux

### Zsh version

5.8

### Terminal emulator

Terminator

**Comment by rwmitchell** [comment]
Check your ```setopt``` settings for ```histignorespace```

**Comment by FeKoerner** [comment]
https://github.com/ohmyzsh/ohmyzsh/issues/2537#issuecomment-163283425

**Comment by mcornella** [comment]
This is actually a feature of zsh, so that if you run commands with secrets in them that you don't want stored in the history file you can just add a space at the beginning.

You can turn it off with `unsetopt histignorespace` (put this in your .zshrc file, after OMZ has loaded).
