### ISSUE TITLE
Plugins Request

### ISSUE THREAD

**Issue by ankusharya** [ohmyzsh/ohmyzsh#10365]
### If the feature request is for a plugin or theme, specify it here.

Bloop plugin

### If the feature solves a problem you have, specify it here.

Makes development of scala project faster.

### Describe the proposed feature.

- Alias for commonly used function
- Function for complex commands

### Describe alternatives you've considered

Manually add alias in ~/.zshrc.

**Comment by mcornella** [comment]
You don't need to open an issue if you have a PR ready.
