### ISSUE TITLE
Theme: refined change the git prompt to allow the branch name to be selected with double click

### ISSUE THREAD

**Issue by januszm** [ohmyzsh/ohmyzsh#10379]
### If the feature request is for a plugin or theme, specify it here.

refined theme

### If the feature solves a problem you have, specify it here.

Double click on the git prompt selects both the git/ prefix and the actual branch name.

### Describe the proposed feature.

Change the format of `$vcs_info_msg_1_` and replace the first `/` after the VCS name with `:` so that you can double-click-select the branch name. When `/` is used as a separator between VCS name (e.g. `git`) and the branch name, a double click will select both the git/ prefix and the branch name.

```patch
- zstyle ':vcs_info:*:*' formats "$FX[bold]%r$FX[no-bold]/%S" "%s/%b" "%%u%c"
- zstyle ':vcs_info:*:*' actionformats "$FX[bold]%r$FX[no-bold]/%S" "%s/%b" "%u%c (%a)"
+ zstyle ':vcs_info:*:*' formats "$FX[bold]%r$FX[no-bold]/%S" "%s:%b" "%%u%c"
+ zstyle ':vcs_info:*:*' actionformats "$FX[bold]%r$FX[no-bold]/%S" "%s:%b" "%u%c (%a)"
```

```
"%s/%b" => "%s:%b"
```

**Comment by mcornella** [comment]
Can you submit a PR?

**Comment by januszm** [comment]
@mcornella  done: https://github.com/ohmyzsh/ohmyzsh/pull/10400
