### ISSUE TITLE
There are some display bug in ys.zsh-theme in Ubuntu18

### ISSUE THREAD

**Issue by Banana-Two** [ohmyzsh/ohmyzsh#10388]
### Describe the bug

Before I fix those bugs, the original display looks not beautiful. This is my ys.zsh-theme  now， It looks more human than before.

```
# Clean, simple, compatible and meaningful.
# Tested on Linux, Unix and Windows under ANSI colors.
# It is recommended to use with a dark background.
# Colors: black, red, green, yellow, *blue, magenta, cyan, and white.
#
# Mar 2013 Yad Smood

# VCS
YS_VCS_PROMPT_PREFIX1=" %{$fg[white]%}on%{$reset_color%} "
YS_VCS_PROMPT_PREFIX2=":%{$fg[cyan]%}"
YS_VCS_PROMPT_SUFFIX="%{$reset_color%}"
YS_VCS_PROMPT_DIRTY=" %{$fg[red]%}x"
YS_VCS_PROMPT_CLEAN=" %{$fg[green]%}o"

# Git info
local git_info='$(git_prompt_info)'
ZSH_THEME_GIT_PROMPT_PREFIX="${YS_VCS_PROMPT_PREFIX1}git${YS_VCS_PROMPT_PREFIX2}"
ZSH_THEME_GIT_PROMPT_SUFFIX="$YS_VCS_PROMPT_SUFFIX"
ZSH_THEME_GIT_PROMPT_DIRTY="$YS_VCS_PROMPT_DIRTY"
ZSH_THEME_GIT_PROMPT_CLEAN="$YS_VCS_PROMPT_CLEAN"

# HG info
local hg_info='$(ys_hg_prompt_info)'
ys_hg_prompt_info() {
	# make sure this is a hg dir
	if [ -d '.hg' ]; then
		echo -n "${YS_VCS_PROMPT_PREFIX1}hg${YS_VCS_PROMPT_PREFIX2}"
		echo -n $(hg branch 2>/dev/null)
		if [[ "$(hg config oh-my-zsh.hide-dirty 2>/dev/null)" != "1" ]]; then
			if [ -n "$(hg status 2>/dev/null)" ]; then
				echo -n "$YS_VCS_PROMPT_DIRTY"
			else
				echo -n "$YS_VCS_PROMPT_CLEAN"
			fi
		fi
		echo -n "$YS_VCS_PROMPT_SUFFIX"
	fi
}

# Virtualenv
local venv_info='$(virtenv_prompt)'
YS_THEME_VIRTUALENV_PROMPT_PREFIX=" %{$fg[green]%}"
YS_THEME_VIRTUALENV_PROMPT_SUFFIX=" %{$reset_color%}%"
virtenv_prompt() {
	[[ -n ${VIRTUAL_ENV} ]] || return
	echo "${YS_THEME_VIRTUALENV_PROMPT_PREFIX}${VIRTUAL_ENV:t}${YS_THEME_VIRTUALENV_PROMPT_SUFFIX}"
}

local exit_code="%(?,,C:%{$fg[red]%}%?%{$reset_color%})"

# Prompt format:
#
# PRIVILEGES USER @ MACHINE in DIRECTORY on git:BRANCH STATE [TIME] C:LAST_EXIT_CODE
# $ COMMAND
#
# For example:
#
# % ys @ ys-mbp in ~/.oh-my-zsh on git:master x [21:47:42] C:0
# $
PROMPT="%{$terminfo[bold]$fg[blue]%}#%{$reset_color%}\
%(#,%{$bg[yellow]%}%{$fg[black]%}%n%{$reset_color%},%{$fg[cyan]%}%n)\
%{$fg[white]%}@\
%{$fg[green]%}%m \
%{$fg[white]%}in \
%{$terminfo[bold]$fg[yellow]%}%~%{$reset_color%}\
${hg_info} \
${git_info}\
${venv_info}\
\
%{$fg[white]%}[%*]$exit_code
%{$terminfo[bold]$fg[yellow]%}$ %{$reset_color%}"
```

### Steps to reproduce

Use ys.zsh-theme

### Expected behavior

Looks beautiful

### OS / Distro

Ubuntu18

### Zsh version

zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

### Terminal emulator

gnome-terminal or terminator

**Comment by Banana-Two** [comment]
![image](https://user-images.githubusercontent.com/62785154/140239788-bcf252f5-8593-437f-87ad-a371b21afbd0.png)
This is what it looks before I fixed bug.
![image](https://user-images.githubusercontent.com/62785154/140239854-851886ee-0e11-496f-a8b1-2999678dd6c1.png)
This is what it looks after I fixed bug,

**Comment by mcornella** [comment]
Is the bug that you're seeing some text less bright than before? Because if so, this light gray was added in #10295 to be compatible with light color schemes.

**Comment by Banana-Two** [comment]
> Is the bug that you're seeing some text less bright than before? Because if so, this light gray was added in #10295 to be compatible with light color schemes.

I don't think there is a problem with color. I think there is something wrong with the layout. Before I modify ys.zsh-theme, it look likes that when I start my terminal. It looks a little weird.
![image](https://user-images.githubusercontent.com/62785154/140419124-999b4c06-2a55-40c1-9055-69d272cb7d3f.png)
So, I modify it, and that is waht it looks now.
![image](https://user-images.githubusercontent.com/62785154/140419283-6101fd4a-41bb-4327-bf8d-c9bcd7f5a675.png)

**Comment by mcornella** [comment]
That is how the theme is supposed to look. This is not a bug. If you want, you can set up your modification as a custom theme. See [the guide here](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes).

**Comment by Banana-Two** [comment]
> That is how the theme is supposed to look. This is not a bug. If you want, you can set up your modification as a custom theme. See [the guide here](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes).

Ok,thanks!
