### ISSUE TITLE
`xc` switches to different desktop if Xcode is already open with a different project

### ISSUE THREAD

**Issue by Cyberbeni** [ohmyzsh/ohmyzsh#10384]
### Describe the bug

I just noticed that there is a plugin for this but I already have a similar script for opening Xcode projects and I use this for opening the file:
```
open() {
	if pgrep "^Xcode$" > /dev/null; then
		# If a different project is already open, this makes sure that we activate the window for the project we are opening now
		command open -g "$*"
	fi
	command open "$*"
}
```

This makes sure that if a new window is opened, then it is opened in the current desktop instead of the desktop for the already open Xcode project.

### Steps to reproduce

```
xc a.xcworkspace
# move the opened window to another desktop
xc b.workspace
# desktop will switch to the one that has the other workspace open and also open the new workspace there
```

### Expected behavior

always open Xcode in the current desktop, except if the workspace is already open in a different desktop, then navigate there

### OS / Distro

macOS 12.0.1

### Zsh version

5.8

### Terminal emulator

iTerm2

**Comment by Cyberbeni** [comment]
I think the reason for not always doing the double open was that if opening takes long then calling open once won't interrupt you if you decided to switch to another app meanwhile, see the discussion part here: https://developer.apple.com/documentation/appkit/nsapplication/1428468-activate

**Comment by mcornella** [comment]
If Xcode is open in another desktop wouldn't you want to open it in the desktop you're in? 

Also, `open -g` says that it "Does not bring the application to the foreground", according to the help output. How does that translate to activating the window? It seems it would do the opposite?

**Comment by Cyberbeni** [comment]
Bringing the application to the foreground happens before the app gets the URL you want to open. That is why if you want to stay on the current desktop and you know the app is already open, you want to use `open -g`.

This will of course not translate to activating the window, that is why calling `open` after `open -g` is required.

But if Xcode is not already open then both `open` and `open -g` will create the new Xcode window on the same desktop but since opening Xcode might take a couple seconds, you might switch to a different app meanwhile (for example answer messages in Slack), that is why in this case you only want to use `open` since using `open -g` then `open` will interrupt what you are doing.

**Comment by mcornella** [comment]
Then the proper algorithm would be

1. If Xcode is open in another desktop, use `open -g`
2. Otherwise use `open`

Am I understanding this correctly?

**Comment by mcornella** [comment]
> This will of course not translate to activating the window, that is why calling `open` after `open -g` is required.

Sorry, I'm having trouble understanding: when calling `open` again, wouldn't the other desktop activate? I don't have Xcode on my macOS VM so I can't test this out, so apologies for being dense.

**Comment by rwmitchell** [comment]
I assumed the first ```open -g``` created a new Xcode instance without switching desktops.
The second ```open``` then raises the newly created instance.

I tried it with safari and it didn't work at all as I hoped.

**Comment by mcornella** [comment]
> but since opening Xcode might take a couple seconds, you might switch to a different app meanwhile

I'm testing this with Visual Studio Code, and the first `open -g` call finishes immediately, so the second `open` call runs immediately afterwards activating the window. I don't see how it would be different in Xcode, since `open` just makes the call and finishes *and* in your algorithm Xcode is already running.

Plus, as you said opening Xcode only takes a couple seconds, so even if we fixed the algorithm to only `open -g` if Xcode isn't running, you'd be saving a couple seconds at most of your time, while making the function code more complex.

**Comment by mcornella** [comment]
@Cyberbeni thoughts?

**Comment by Cyberbeni** [comment]
I tested it on my 2014 mac mini which is currently on macOS 11.5.2 (20G95) and running `time (open -g Package.swift; open Package.swift)` finished in under half a second (which is definitely a change from when I last tested it thoroughly) but even when I didn't do anything after executing the command, the Xcode window opened under iTerm when Xcode wasn't running before. (The Xcode window took longer to appear than the open command finished)

I noticed however that when the other project was open on a different desktop, it still sometimes switched over to that desktop (which never happened on the M1 MBP that I use for work, only on this slow mac mini), so I had to add `sleep 0.1` (sleep handles non-integers on macOS) after `open -g` to make it work correctly.

I'm fine with continuing to use my own script (and finetuning it when needed) instead of `xc` if you don't want to make changes like this as it doesn't seem to bother other people enough to report it (or their usual workflow doesn't trigger this bug)

**Comment by mcornella** [comment]
OK I was finally able to reproduce this on a new virtualized environment. The behavior you reported is what actually happened with Xcode, and the fix worked and is already deployed.

Thank you for the report and fix, and sorry for the delay!
