### ISSUE TITLE
Source homebrew shellenv to setup homebrew in new install location

### ISSUE THREAD

**Issue by caleb** [ohmyzsh/ohmyzsh#10389]
### If the feature request is for a plugin or theme, specify it here.

brew

### If the feature solves a problem you have, specify it here.

Homebrew seems to install in /opt/homebrew now and has a shell script that needs to be eval'd to set it up.

### Describe the proposed feature.

Could the following snippet be included in the brew plugin to configure homebrew correctly.

```bash
# Homebrew
if [[ -f /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
```

### Describe alternatives you've considered

I manually added the above snippet myself to my zshrc file

**Comment by Freed-Wu** [comment]
I did it in <https://github.com/Tarrasch/zsh-command-not-found/pull/2#issuecomment-962217991>. The change is in <https://github.com/Tarrasch/zsh-command-not-found/pull/2/files>. Can it be allowed to exist in ohmyzsh?

**Comment by carlosala** [comment]
Hi Caleb!
Sorry for the late response. Eval-ing unknown scripts by default seems not really interesting. Maybe we can add that code snippet to the `brew` plugin but to be optional, that would be enabled using the following line in your `zshrc`, before sourcing `oh-my-zsh.sh`:
```zsh
zstyle ':omz:plugins:brew` shell-env on
```
Do you think it's a great solution?
Another question, also for non-silicon Macs (that use other directory for brew files) is this necessary?
I would also like to ask you for copying and posting here that script, so we can know what's exactly doing.
Thanks!

**Comment by carlosala** [comment]
ping @caleb

**Comment by jrjohnson** [comment]
This script adds Homebrew in its new location to the $PATH and sets up some ENV variables useful for finding itself. 

The output of this script is:

On a new Homebrew install:
```
$/opt/homebrew/bin/brew shellenv                                                                                             
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew/Homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
```

On older Homebrew installs:
```
$/usr/local/bin/brew shellenv                                                                                             
export HOMEBREW_PREFIX="/usr/local";
export HOMEBREW_CELLAR="/usr/local/Cellar";
export HOMEBREW_REPOSITORY="/usr/local/Homebrew";
export PATH="/usr/local/bin:/usr/local/sbin${PATH+:$PATH}";
export MANPATH="/usr/local/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/usr/local/share/info:${INFOPATH:-}";
```

The problem is you'd need to be sure of where Homebrew had installed itself before knowing exactly where to run this from. It's possible the plugin could assume the new location, but if that's the case maybe just adding these ENV vars is better than running the command every time.

**Comment by mcornella** [comment]
I'm for doing this for both M1 and classic. Perhaps we could check if `HOMEBREW_PREFIX` is set before though, so that we don't call this a second time if the user has done it already.
