### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [ohmyzsh/ohmyzsh#10380]
Hey there!

I belong to an open source security research community, and a member (@ry0tak) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by mcornella** [comment]
You can email me directly this time (it's in my bio). I'll coordinate with Robby on the best way to receive security warnings.

**Comment by mcornella** [comment]
We've now added a Security policy. [Please have a look](https://github.com/ohmyzsh/ohmyzsh/security/policy).

**Comment by mcornella** [comment]
Hey there, just a kind reminder that we're still waiting for news about this. Let me know also if it turned out not to be an issue after all, just for peace of mind. Thanks!

**Comment by Ry0taK** [comment]
Hi @mcornella, I heard that the team sent a report to your email address. I'm currently checking with the team to find out the problem. Sorry for the delay!

**Comment by JamieSlome** [comment]
Hey all 👋 

Our system automatically sent an e-mail to @robbyrussell but you can view the report here:

https://huntr.dev/bounties/ad2b5c3f-a3ce-4407-94dc-354c723310ce/

**Comment by robbyrussell** [comment]
Thanks @JamieSlome. We found it when we searched for the huntr domain. @mcornella is going to look into this further

**Comment by JamieSlome** [comment]
@robbyrussell - great 👍

**Comment by rwmitchell** [comment]
Did anything come of this?  Has anyone (@mcornella) been able to verify this is a vulnerability in OMZ?

**Comment by mcornella** [comment]
Working on it. Expect news by the end of day.

**Comment by JamieSlome** [comment]
@mcornella - let us know if there is anything we can support with on our side! ❤️

**Comment by mcornella** [comment]
You can update now with `omz update`. Expect a report in the next hour or so.

**Comment by mcornella** [comment]
> Did anything come of this? Has anyone (@mcornella) been able to verify this is a vulnerability in OMZ?

@rwmitchell the initial report is posted in https://github.com/ohmyzsh/ohmyzsh/issues/10414. You'll get more details in the next few days.
