### ISSUE TITLE
copybuffer not working

### ISSUE THREAD

**Issue by createchange** [ohmyzsh/ohmyzsh#10394]
### Describe the bug

When trying to use `copybuffer` nothing is copied. `copyfile` and `copydir` both work as I would hope.

### Steps to reproduce

```zsh
/  ✗  copyfile ~/test.txt

/  ➜  # pasting

/  ➜  this is text in a file 
^C

/  ✗  copydir

/  ➜  # pasting

/  ➜  /
^C

/  ✗  copybuffer "HELP\!"

/  ➜  # pasting

/  ➜  # ... nothing :(
```

### Expected behavior

My clipboard would have contained the contents of the buffer.

### OS / Distro

Mac, Big Sur

### Zsh version

5.8

### Terminal emulator

iTerm2

**Comment by mcornella** [comment]
`copybuffer` copies the command that is typed, otherwise called "buffer". You need to type some command, then press CTRL+O, so that it is copied to your clipboard.
