### ISSUE TITLE
The `docker-compose` plugin started docker.service

### ISSUE THREAD

**Issue by YHYJ** [ohmyzsh/ohmyzsh#10409]
### Describe the bug

Prerequisite: I enabled docker.socket, which determines when to start docker.service.

I have enabled the built-in plugins 'docker' and 'docker-compose' a long time ago, there has been no problem.
Until recently, these plugins caused my docker.service to autostart after os booting (the docker.service was only started by manually running the `docker` command before), but I don’t want this, and it also causes the first zsh to be stuck after booting.

### Steps to reproduce

1. Install docker and run `systemctl enable docker.socket`
2. Add 'docker' or 'docker-compose' in the 'plugins' section of zshrc
3. Restart the computer
4. Open a terminal (the login shell is zsh)
5. Enter a command and press 'Enter', you will see that zsh is stuck
6. Open another terminal, now it's normal
7. Run `systemctl status docker`, you can see that docker.service has been running because of docker plugin

### Expected behavior

docker.service is started by manually running `docker`, zsh is no longer stuck

### OS / Distro

Arch Linux

### Zsh version

5.8

### Terminal emulator

Terminator and Guake and tty

### Additional context

I no longer use the built-in docker* plugin of zsh, everything is normal now

**Comment by mcornella** [comment]
The `docker` plugin only adds completion. Can you check if the culprit is the `docker-compose` plugin by disabling it?

**Comment by YHYJ** [comment]
I disabled the docker plugin, and now everything is normal.

**Comment by mcornella** [comment]
Can you post your zshrc file both when it works and when it doesn't? Again, the **docker** plugin [only adds completion](https://github.com/ohmyzsh/ohmyzsh/tree/22de1d304c730c6e364a57a7b901978bd2fcd061/plugins/docker), which doesn't run anything unless you try to complete a `docker` command.

**Comment by mcornella** [comment]
It would also be great to know how your systemd is configured, so I can try to replicate your issue.

**Comment by mcornella** [comment]
You can also record your issue with [asciinema](https://asciinema.org/) so it's clearer than your description of "Steps to reproduce"

> * Install docker and run `systemctl enable docker.socket`
> * Add 'docker' or 'docker-compose' in the 'plugins' section of zshrc
> * Restart the computer
> * Open a terminal (the login shell is zsh)
> * Enter a command and press 'Enter', you will see that zsh is stuck
> * Open another terminal, now it's normal
> * Run `systemctl status docker`, you can see that docker.service has been running because of docker plugin

Particularly, `enter a command and press Enter` (which command?) and what running `systemctl status docker` has to do with this.

**Comment by YHYJ** [comment]
[not_work_zshrc.txt](https://github.com/ohmyzsh/ohmyzsh/files/7524003/not_work_zshrc.txt)

[work_zshrc.txt](https://github.com/ohmyzsh/ohmyzsh/files/7524006/work_zshrc.txt)

I use docker.socket to monitor the /run/docker.sock file. If any program calls the docker command or /run/docker/sock, the docker.socket daemon will start docker.service.
According to my experiment (just annotate the docker* plugin of `plugins` in zshrc), the docker plugin will start docker.service, which is not what I want

About `enter a command and press Enter`, any command is fine (ls, cd, pwd...)

The docker plugin of zshrc will cause docker.service to start automatically (it should be started by me running the `docker` command), and docker.service will cause the terminal to freeze when it is started

**Comment by YHYJ** [comment]
The'docker' plugin in the latest commit is normal, but the'docker-compose' plugin is still abnormal

**Comment by mcornella** [comment]
The `docker-compose` plugin runs `docker compose` to check if the command is available. That's probably what causes this. What's the problem with starting `docker.service`?

**Comment by YHYJ** [comment]
I think the plugin only needs to check if the `docker-compose` command exists in the $PATH. I want to start docker.service by myself when I need to use docker

**Comment by mcornella** [comment]
Made https://github.com/ohmyzsh/ohmyzsh/pull/10429 that checks for `docker-compose` instead of calling `docker compose`. Can you test it to see if it works for you (you can use `omz pr test 10429`)?

**Comment by YHYJ** [comment]
It works great, but I use AUR/oh-my-zsh-git, so please fix it as soon as possible, thanks!
