### ISSUE TITLE
Add plugin for istioctl completion

### ISSUE THREAD

**Issue by jxlwqq** [ohmyzsh/ohmyzsh#10405]
### If the feature request is for a plugin or theme, specify it here.

istioctl plugin

### Describe the proposed feature.

The `istioctl` tool is a configuration command line utility that allows service operators to debug and diagnose their Istio service mesh deployments. 

https://istio.io/latest/docs/ops/diagnostic-tools/istioctl/

**Comment by mcornella** [comment]
No need to open an issue if you have a PR ready.
