### ISSUE TITLE
Git error during auto-update: Unknown option: -C

### ISSUE THREAD

**Issue by alchemistmatt** [ohmyzsh/ohmyzsh#10404]
### Describe the bug

When the auto-updater runs, code added by commit 30d441713c47306fe63c1ce6833ff7a6120c9a47 on 2021-10-04 checks for updates before prompting to update.  This code uses argument `-C` with git, but that argument is not available for git v1.x, leading to this error being shown 3 times:
```
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```
After this, ohmyzsh does successfully update.

### Steps to reproduce

1. Login to a server that has git 1.x and ohmyzsh
2. If enough time has passed, ohmyzsh will check for updates
3. If an update is available, the errors will be shown
4. Respond Y and ohmyzsh will successfully update

### Expected behavior

Error messages should not be shown.

### OS / Distro

Red Hat Enterprise Linux Workstation release 7.9

### Zsh version

5.0.2

### Terminal emulator

Putty

### Additional context

My Git version is 1.8.3.1 but I suspect this happens with any version of git before 2.x.  Although the error can be ignored, it would be better if the code was updated to check the installed version of Git

**Comment by mcornella** [comment]
Thanks for the report!
