### ISSUE TITLE
`bi` from bundler plugin modifies ./.bundle/config

### ISSUE THREAD

**Issue by Cyberbeni** [ohmyzsh/ohmyzsh#10425]
### Describe the bug

Based on the docs, v2.2 defaults to having the same number of jobs as the number of cores on most systems: https://bundler.io/v2.2/bundle_config.html (But the v2.1 docs say it always defaults to 1)

I'm using Bundler version 2.2.31 (and ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21] ) and when running `bi`, it sets/updates the BUNDLE_JOBS in the local config file, making unnecessary changes in the git workspace

### Steps to reproduce

enable plugin `bundler`
run `bi` in a folder with a `Gemfile`
./.bundle/config will be created/modified

### Expected behavior

running `bi` without a parameter doesn't update the local config

### OS / Distro

macOS 12.0.1 (21A559)

### Zsh version

zsh 5.8 (arm-apple-darwin20.2.0)

### Terminal emulator

iTerm2

**Comment by mcornella** [comment]
Try #10430 with `omz pr test 10430`. I've tested it and it seems to work.

**Comment by Cyberbeni** [comment]
Seems to work for me as well

**Comment by mcornella** [comment]
Thanks!
