### ISSUE TITLE
Installer breaks unattended install on openbsd by returning a non 0 exit code

### ISSUE THREAD

**Issue by lhorace** [ohmyzsh/ohmyzsh#10422]
### Describe the bug

Using ansible to deploy omz on a remote machine, the installer exits with a non 0 status:

```
openbsd70-dev% /tmp/install.sh --unattended 
Cloning Oh My Zsh...
Cloning into '/home/sysadmin/.oh-my-zsh'...
remote: Enumerating objects: 1244, done.
remote: Counting objects: 100% (1244/1244), done.
remote: Compressing objects: 100% (1205/1205), done.
remote: Total 1244 (delta 19), reused 1187 (delta 18), pack-reused 0
Receiving objects: 100% (1244/1244), 877.00 KiB | 2.01 MiB/s, done.
Resolving deltas: 100% (19/19), done.

Looking for an existing zsh config...
Using the Oh My Zsh template file and adding it to ~/.zshrc.

         __                                     __   
  ____  / /_     ____ ___  __  __   ____  _____/ /_  
printf: unknown escape sequence `\%'
printf: unknown escape sequence `\ '
printf: unknown escape sequence `\%'
printf: unknown escape sequence `\ '
 / __ %s/ __    / __ `__ %s/ / / /  /_  / / ___/ __  
printf: unknown escape sequence `\%'
printf: unknown escape sequence `\ '
printf: unknown escape sequence `\%'
printf: unknown escape sequence `\ '
 / __ %s/ __    / __ `__ %s/ / / /  /_  / / ___/ __
```

Either we stay quiet on `--unattended`, offer a `--quiet` option, implement a custom printf for openBSD, or stay ugly `exit 0`?

### Steps to reproduce

1. Install a fresh copy of openBSD 7.0
2. Install ZSH: `pkg_add zsh`
2. Download/wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
3. ./install.sh --unattended

### Expected behavior

Return a 0 exit status

### OS / Distro

OpenBSD 7.0

### Zsh version

5.8

### Terminal emulator

Konsole

### Additional context

Since the installer succeeded in installing `omz`, the exit status is incorrect.

**Comment by mcornella** [comment]
Can you check that installing from https://github.com/mcornella/ohmyzsh/raw/fix/rainbow-logo-in-install.sh/tools/install.sh solves the problem?

**Comment by lhorace** [comment]
Sure, testing now.

**Comment by mcornella** [comment]
I already did and pushed the fix, you can use the regular installer URL.
