### ISSUE TITLE
There was an error updating. Try again later?

### ISSUE THREAD

**Issue by alansenairj** [ohmyzsh/ohmyzsh#10420]
### Describe the bug

Auto-update is not working. This is the first one. I'm using Fedora 35.  

```
░▒▓  │  ~ ▓▒░ omz update               ░▒▓ ✔ │ took 41s  │ at 01:46:24  ▓▒░

Updating Oh My Zsh
From https://github.com/ohmyzsh/ohmyzsh
 * branch            master     -> FETCH_HEAD
Updating 04c96e2..b3ba997
error: Your local changes to the following files would be overwritten by merge:
	README.md
	lib/cli.zsh
	lib/diagnostics.zsh
	lib/directories.zsh
	lib/functions.zsh
	lib/git.zsh
	lib/spectrum.zsh
	lib/termsupport.zsh
	plugins/command-not-found/command-not-found.plugin.zsh
	plugins/dirhistory/README.md
	plugins/dirhistory/dirhistory.plugin.zsh
	plugins/frontend-search/_frontend-search.sh
	plugins/hitokoto/hitokoto.plugin.zsh
	plugins/osx/README.md
	plugins/percol/README.md
	plugins/percol/percol.plugin.zsh
	plugins/rand-quote/rand-quote.plugin.zsh
	plugins/systemadmin/README.md
	plugins/systemadmin/systemadmin.plugin.zsh
	plugins/tmux/README.md
	plugins/tmux/tmux.plugin.zsh
	themes/emotty.zsh-theme
	themes/pygmalion-virtualenv.zsh-theme
	themes/pygmalion.zsh-theme
	themes/refined.zsh-theme
	themes/ys.zsh-theme
	tools/check_for_upgrade.sh
Please commit your changes or stash them before you merge.
Aborting
There was an error updating. Try again later?
```

### Steps to reproduce

This error appears automaticlly. 
If I did manual update I can reproduce it again. 

### Expected behavior

Normal update message

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/20565821/141667995-0bc4e564-bf1c-49e6-9dbd-1bc428181453.png)

![image](https://user-images.githubusercontent.com/20565821/141668009-a416a4bb-136d-4a56-914d-27013271e9ff.png)

### OS / Distro

Fedora Linux 35

### Zsh version

5.8

### Terminal emulator

Gnome Termial

### Additional context

Iḿ using power lever 10k plugin

**Comment by alansenairj** [comment]
I don't know if it will solve the problem for future updates. 
But it can be updated by this steps: 

cd ~/.oh-my-zsh
git status 
git stash
omz update

**Comment by mcornella** [comment]
You need to remove or commit your local changes (if you need to keep them) and manually upgrade again, fixing any conflicts that appear.
