### ISSUE TITLE
Option to reuse browser tabs with web-search plugin

### ISSUE THREAD

**Issue by ninjarogue** [ohmyzsh/ohmyzsh#10447]
### If the feature request is for a plugin or theme, specify it here.

web-search

### If the feature solves a problem you have, specify it here.

so when I use the web search plug for searching for things on google or youtube, If a google search tab or youtube tab already exists, then I want the web search plug to reuse the already existing tab instead of creating a new tab or window.

### Describe the proposed feature.

google/youtube search reuses already existing google/youtube tabs or windows on google chrome or any other web browser, instead of opening a new tab for every web search.

**Comment by mcornella** [comment]
This is not possible, see https://bugs.chromium.org/p/chromium/issues/detail?id=141942.
