### ISSUE TITLE
gentoo: change or remove hostname from prompt

### ISSUE THREAD

**Issue by JyanJohn** [ohmyzsh/ohmyzsh#10444]
Hello, is it possible for me to Edit Hostname in ZSH themes, im using the Gentoo theme.

**Comment by mcornella** [comment]
The gentoo theme shows the theme after the username using the `%m` prompt sequence. If you want to remove it from the prompt you can delete that part of the `$PROMPT` variable:

```patch
diff --git a/themes/gentoo.zsh-theme b/themes/gentoo.zsh-theme
index 7ac46103..0a1e75d7 100644
--- a/themes/gentoo.zsh-theme
+++ b/themes/gentoo.zsh-theme
@@ -25,4 +25,4 @@ gentoo_precmd() {
 autoload -U add-zsh-hook
 add-zsh-hook precmd gentoo_precmd
 
-PROMPT='%(!.%B%F{red}.%B%F{green}%n@)%m %F{blue}%(!.%1~.%~) ${vcs_info_msg_0_}%F{blue}%(!.#.$)%k%b%f '
+PROMPT='%(!.%B%F{red}.%B%F{green}%n )%F{blue}%(!.%1~.%~) ${vcs_info_msg_0_}%F{blue}%(!.#.$)%k%b%f '
```

If you only want to change the name in the prompt, you can modify the `HOSTNAME` variable and that will automatically be reflected.

Finally, if you make any changes to the theme it's better to set it up as a custom theme. See [the guide here](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes).
