### ISSUE TITLE
Add prompt support for toolbx

### ISSUE THREAD

**Issue by JayDoubleu** [ohmyzsh/ohmyzsh#10446]
### If the feature solves a problem you have, specify it here.

[toolbx](https://github.com/containers/toolbox) is appending icon indicator to bash shell to indicate when your shell is running in container. When using oh-my-zsh this indicator is lost on every theme so there is no easy way to distinguish if you're running inside toolbx container or not.

### Describe the proposed feature.

Make use of `/run/.toolboxenv` file to determine if you're running inside toolbx shell and append toolbx ⬢ indicator to the beginning of PS1 independently of theme.
Allow to opt-out using flag in .zshrc.

### Describe alternatives you've considered

Modifying theme manually.

**Comment by carlosala** [comment]
This feature looks difficult to be added. Probably the most interesting way would be modifying the theme you use. What do you think about it? Maybe you can share your modified theme for other people interested!
