### ISSUE TITLE
Tiling Windows ZSH Glitch

### ISSUE THREAD

**Issue by asmuiahmad** [ohmyzsh/ohmyzsh#10454]
### Describe the bug

Hi, I got this problem when I'm trying to tiling my windows `kitty terminal` any troubleshot to fix this?
![Screenshot_20211127_035309](https://user-images.githubusercontent.com/25726343/143625513-6110b12b-64de-40a7-bbe7-defca883f33c.png)

### Steps to reproduce

?

### Expected behavior

?

### OS / Distro

Arch Linux

### Zsh version

5.8

### Terminal emulator

kitty

**Comment by rwmitchell** [comment]
After you finish resizing your screen, clear it.  Old prompts aren't going to remap to fit a smaller window.
