### ISSUE TITLE
brew plugin doesn't appear to do anything

### ISSUE THREAD

**Issue by mcandre** [ohmyzsh/ohmyzsh#10457]
### Describe the bug

When I initialize Homebrew via the Oh My Zsh plugin, nothing happens.

### Steps to reproduce

```zsh
    plugins=(
        brew
    )
```

### Expected behavior

Homebrew loads

### OS / Distro

macOS 12

### Zsh version

5.8

### Terminal emulator

Terminal.app

### Additional context

As a workaround, I am initializing Homebrew via a more classic approach, with the modern standard Homebrew initialization command in a suitable location.

```sh
eval "$(/opt/homebrew/bin/brew shellenv)"
```

I happen to place this in a personal convention of `$HOME/.profile.d/enabled/brew.sh`, sourcing that from `$HOME/.profile`, and sourcing that from `$HOME/.zshenv`. So that I can reuse more shell snippets across both zsh and bash. But one could simply copy and paste this snippet directly into `$HOME/.zshenv`.

I am miffed that the brew plugin for Oh My Zsh didn't immediately work as advertised, as that would be a far more convenient method if the glitches get ironed out. On my machine, adding the `brew` plugin does nothing. NO-OP.

**Comment by hkbertoson** [comment]
I installed the brew plugin on my machine and I am having no issues at all. Is your homebrew up to date? Try running 
```
brew update && brew outdated && brew upgrade && brew cleanup
```

**Comment by mcornella** [comment]
The Homebrew plugin does not load Homebrew, it only adds aliases for common operations with `brew`, as is specified in the README. If you want it to also run the `shellenv` feature that is a feature request, not a bug.
