### ISSUE TITLE
command not found: Build

### ISSUE THREAD

**Issue by jopmiddelkamp** [ohmyzsh/ohmyzsh#10451]
### Describe the bug

After I installed ohmyzsh I keep receiving this message each time I start my terminal.

.zprofile:3: command not found: Build

Can someone explain to me how to solve this?

### Steps to reproduce

Install ohmyzsh on a clean installation of MacOS Monterey.

### Expected behavior

Loading without showing me the message

.zprofile:3: command not found: Build

### OS / Distro

macOS 12.0.1

### Zsh version

5.8

### Terminal emulator

Default Mac terminal

**Comment by rwmitchell** [comment]
What are the first 6 lines of .zprofile?

**Comment by mcornella** [comment]
The error message indicates that there's a problem in line 3 of `.zprofile`. It looks like it's a comment missing a `#`, but we can't know if you don't post that. In any case, this is not a bug in Oh My Zsh.
