### ISSUE TITLE
Make default 'master' to 'main' 

### ISSUE THREAD

**Issue by sabahzero** [ohmyzsh/ohmyzsh#10460]
Reasoning and execution:
https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/

![Screen Shot 2021-11-29 at 9 59 20 AM](https://user-images.githubusercontent.com/16907482/143922918-f52f10ba-3942-47d4-8137-d6423296c958.png)

**Comment by mcornella** [comment]
Duplicate of #9015
