### ISSUE TITLE
Support `python3` executable when `python` is not available

### ISSUE THREAD

**Issue by mcornella** [ohmyzsh/ohmyzsh#10469]
Many systems don't link `python` to `python3`. Debian even [maintains it's wrong for their packages to expect `python` to work](https://wiki.debian.org/Python):
> NOTE: Debian testing (bullseye) has removed the "python" package and the '/usr/bin/python' symlink due to the deprecation of Python 2. **No packaged scripts should depend on the existence of '/usr/bin/python'**: if they do, that is a bug that should be reported to Debian. You can use the 'python-is-python3' or 'python-is-python2' packages to restore an appropriate '/usr/bin/python' symlink for third-party or legacy scripts.

Therefore we should support both `python` and `python3`. This can be done from Zsh with the form
```zsh
${commands[python]:-python3}
```
but the use in file shebangs is harder to do.

It should be researched whether `python3` is expected to be available in all systems, so we can just rename all `python` uses to `python3`, or if either command can be available in different systems.

Reference: #10466

-----

Used in plugins:
- aliases
- [django](https://github.com/ohmyzsh/ohmyzsh/blob/3e4b520190f1e4aaced9267bd5dcde59b3d0211f/plugins/django/django.plugin.zsh#L377)
- git-prompt
- jsontools
- python
- shell-proxy (as `python3`)
- urltools (as `python2` or `python3`)

**Comment by carlosala** [comment]
I think that renaming every usage from `python` to `python3` is counterproductive. Python2 is deprecated since 2 years ago, so it's a matter of time for the command `python` be default in every distro/OS. We can discuss about it, I don't see an easy solution for this issue.

**Comment by tkomane** [comment]
> I think that renaming every usage from `python` to `python3` is counterproductive. Python2 is deprecated since 2 years ago, so it's a matter of time for the command `python` be default in every distro/OS. We can discuss about it, I don't see an easy solution for this issue.

Just dealt with this issue and I'm inclined to agree with this. In the interim it might make more sense to recommend installation of 'python-is-python3' or 'python-is-python2' packages - and maybe even prompt the installation as a fallback within the respective plugin zsh scripts, (whenever a python executable can't be detected).

**Comment by carlosala** [comment]
I agree with you! Maybe we can spawn a warning if `python` is missing but `python3` is there. By the way, I don't really know if every system that doesn't link `python` with `python3` has those packages.

**Comment by mcornella** [comment]
I think the solution is to rename everything to `python3`, as stated in https://github.com/ohmyzsh/ohmyzsh/issues/10777#issuecomment-1068518083.

**Comment by mcornella** [comment]
@carlosala can you take care of renaming every call to `python` for `python3`? Judging from the comments, that seems like the safest bet.

**Comment by carlosala** [comment]
Yes, I planned to do it last week but many things came up😅
I'll do it before Sunday!

**Comment by mcornella** [comment]
Awesome!
