### ISSUE TITLE
fzf plugin: 100% CPU usage if terminated while history search is open

### ISSUE THREAD

**Issue by Nic0S** [ohmyzsh/ohmyzsh#10462]
### Describe the bug

If a Mac Terminal window is closed with history search open and the fzf plugin enabled, a rogue zsh process using 100% CPU gets created, must be manually killed.

### Steps to reproduce

1. brew install fzf
2. enable the OMZ fzf plugin in .zshrc, disable other plugins
3. Do a history search (Ctrl + R)
4. With the history search open, close the Terminal window or tab
5. Check activity monitor, a zsh process is using 100% CPU, can also repeat steps 3 and 4 to create more of them

Apologies if this is not actually OMZ related, I suspect it is because it does not happen when running "fzf" by itself, only in history search with the fzf OMZ plugin.

This also does not happen with the default history search function.

### Expected behavior

After the terminal window is closed, the zsh process serving it should terminate as well and not consume CPU.

### Screenshots and recordings

<img width="1066" alt="Screen Shot 2021-11-29 at 6 08 13 PM" src="https://user-images.githubusercontent.com/7006025/143956931-a36a8675-7757-41da-b519-63625377a516.png">

### OS / Distro

macOS Monterey 12.0.1 (M1 Processor)

### Zsh version

5.8

### Terminal emulator

Mac Terminal

**Comment by rwmitchell** [comment]
Just curious, if "the zsh process serving it should terminate as well and not consume CPU.", how is this an OMZ bug and not a more generic ZSH bug?  OMZ and ZSH are not the same thing.

**Comment by Nic0S** [comment]
That’s possible, I’m not sure. I suspected the OMZ fzf plugin since I don’t see this issue when running fzf itself, only when using it under the plugin for history search.

**Comment by rwmitchell** [comment]
looking through the files in plugins/fzf, there really isn't much there, mostly it invokes the stuff already included with fzf, which I believe is installed externally to omz.

**Comment by Nic0S** [comment]
You're right, I think this is not OMZ related. I just tried disabling the plugin and following the installation instructions on the fzf repo (which seeps to give the same history search functionality) and it has the same issue. Sorry for the false alarm, going to dig a little deeper
