### ISSUE TITLE
Support lazy-loading `npx` as part of the `nvm` plugin

### ISSUE THREAD

**Issue by vkomarov-r7** [ohmyzsh/ohmyzsh#10467]
### If the feature request is for a plugin or theme, specify it here.

nvm

### If the feature solves a problem you have, specify it here.

When using `nvm` in lazy mode, any commands that use `npx` do not get loaded lazily as they should.

### Describe the proposed feature.

If possible, please add `npx` as one of the commands that auto loads `nvm` when the command is invoked.

**Comment by carlosala** [comment]
Hi! Sorry for the late response. You can easily customize which commands do get loaded lazily using the variable `$NVM_LAZY_CMD`. For instance, in your `.zshrc` before loading `oh-my-zsh.sh`: 
```zsh
NVM_LAZY_COMMAND=(npx othercommand alsoanothercommand)
```
And, if you just want to use `npx`, you can also use `NVM_LAZY_COMMAND=npx`.

**Comment by vkomarov-r7** [comment]
Hey Carlos, just confirmed and this works perfectly! Thank you. Issue can be closed.

**Comment by carlosala** [comment]
Great! Have a nice day!
