### ISSUE TITLE
git_prompt is failing in case only python3 is available

### ISSUE THREAD

**Issue by robert-franz** [ohmyzsh/ohmyzsh#10466]
### Describe the bug

When using the git_prompt plugin, then no git status is shown in the command line. I analyzed this and I found out that the reason for this is that in my linux distribution (debian) only the binary `python3` is available. I fixed this by adding an alias `alias python=python3`. But it would be great when the git_prompt would work out-of-the-box.

### How to resolve
- In case `python` is not available simply use `python3`

### Steps to reproduce

Install `python3` and having no `python` available.

### Expected behavior

When `python3` is used then the git_prompt should work the same as with having `python` installed

### OS / Linux distribution

debian

### Zsh version

5:8

### Oh My Zsh version

63a7422d

### Terminal emulator

wsl

### If using WSL on Windows, which version of WSL

WSL2

**Comment by mcornella** [comment]
Since this is a project-wide problem I've opened #10469 to track this.
