### ISSUE TITLE
yarn command not found under node corepack

### ISSUE THREAD

**Issue by mihaa1** [ohmyzsh/ohmyzsh#10478]
### Describe the bug

yarn command not found when using node corepack

* Installed node 16.13.1 using asdf. Also install zsh asdf plugin.
* run corepack enable
When trying to run yarn, I'm getting:
zsh: command not found: yarn

### Steps to reproduce

* Installed node 16.13.1 using asdf. Also install zsh asdf plugin.
* run corepack enable
When trying to run yarn, I'm getting:
zsh: command not found: yarn

### Expected behavior

Should recognize yarn command out of the box (according to docs)

### OS / Linux distribution

ubuntu 20.4

### Zsh version

zsh 5.8 (x86_64-ubuntu-linux-gnu)

### Terminal emulator

GNOME

**Comment by mcornella** [comment]
If `node` or `corepack` are not found either, this would mean that `asdf` wasn't properly loaded by the OMZ plugin. If that is not the case, submit your problem to https://github.com/nodejs/corepack.

Reopen if `node` is also not found.
