### ISSUE TITLE
web-search plugin: Adding a question mark to the search returns no matches found (bug)

### ISSUE THREAD

**Issue by evanniedojadlo** [ohmyzsh/ohmyzsh#10476]
### Describe the bug

If you add a question mark to a search, the console returns _zsh: no matches found:_

### Steps to reproduce

Run command `google what is brew tap?`
Returns `zsh: no matches found: tap?`

### Expected behavior

I was expecting the the google search page to load with my question. If you remove the question mark character, it works without issue

### OS / Linux distribution

macOS Catalina 10.15.7

### Zsh version

5.7.1

### Terminal emulator

iTerm2

**Comment by rwmitchell** [comment]
You expected the wrong thing.  Expanding the ? locally is what all shells do.

Enclose your search string in double quotes and it should work.
