### ISSUE TITLE
Brew autocomplete puts in control sequences

### ISSUE THREAD

**Issue by PythonCoderAS** [ohmyzsh/ohmyzsh#10480]
### Describe the bug

The homebrew plugin will put in control sequences whenever a package name is autcompleted.

### Steps to reproduce

1. Type `brew install mysql-`
2. Hit tab
3. Hit tab again to view all suggestions
4. Scroll to any suggestion
5. Hit enter

### Expected behavior

The text that is shown should appear

### Screenshots and recordings

```
> brew install mysql-workbench
124m^[[39mautomysqlbackup^[[38;5;124m^[[39m^[[38
124m^[[39mmysql^[[38;5;124m^[[39m^[[38
124m^[[39mmysql^[[38;5;241m+^[[39m^[[38;5;241m+^[[39m^[[38;5;124m^[[39m^[[38
124m^[[39mmysql^[[38;5;241m-^[[39mclient^[[38;5;124m^[[39m^[[38
124m^[[39mmysql^[[38;5;241m-^[[39mclient^[[38;5;241m@5.7^[[39m^[[38;5;124m^[[39m^[[38
124m^[[39mmysql^[[38;5;241m-^[[39mconnector^[[38;5;241m-^[[39mc^[[38;5;241m+^[[39m^[[38;5;241m+^[[39m^[[38;5;124m^[[39m^[[38
124m^[[39mmysql^[[38;5;241m-^[[39msandbox^[[38;5;124m^[[39m^[[38
124m^[[39mmysql^[[38;5;241m-^[[39msearch^[[38;5;241m-^[[39mreplace^[[38;5;124m^[[39m^[[38
124m^[[39mmysql^[[38;5;241m@5.6^[[39m^[[38;5;124m^[[39m^[[38
124m^[[39mmysql^[[38;5;241m@5.7^[[39m^[[38;5;124m^[[39m^[[38
124m^[[39mmysqltuner^[[38;5;124m^[[39m^[[38
124m^[[39mqt^[[38;5;241m-^[[39mmysql^[[38;5;124m^[[39m^[[38
124m$'\033'\[39m$'\033'\[38\;5\;124mmysql-connector-python$'\033'\[39m$'\033'\[38\;5\;124m$'\033'\[39m
124m$'\033'\[39m$'\033'\[38\;5\;124mmysql-shell$'\033'\[39m$'\033'\[38\;5\;124m$'\033'\[39m
124m$'\033'\[39m$'\033'\[38\;5\;124mmysql-utilities$'\033'\[39m$'\033'\[38\;5\;124m$'\033'\[39m
124m$'\033'\[39m$'\033'\[38\;5\;124mmysqlworkbench$'\033'\[39m$'\033'\[38\;5\;124m$'\033'\[39m
124m$'\033'\[39m$'\033'\[38\;5\;124mnavicat-for-mysql$'\033'\[39m$'\033'\[38\;5\;124m$'\033'\[39m
124m$'\033'\[39m$'\033'\[38\;5\;124msqlpro-for-mysql$'\033'\[39m$'\033'\[38\;5\;124m$'\033'\[39m
```
![image](https://user-images.githubusercontent.com/13932583/144726306-ccd34e92-4f00-4ffb-a4cf-899cd9ce9866.png)

### OS / Linux distribution

macOS 11

### Zsh version

5.8

### Oh My Zsh version

master (841f3cb0)

### Terminal emulator

iTerm2

**Comment by mcornella** [comment]
The `brew` plugin does not add completion for `brew`, it's just a series of aliases for common operations. The completion is provided by the official Homebrew project: https://github.com/Homebrew/brew/blob/d3474d03e700b05fd54670a45b21061afbf53da7/completions/zsh/_brew

Try looking at the [submitted issues](https://github.com/Homebrew/brew/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) or create one if none exists.
