### ISSUE TITLE
asdf plugin is broken for latest homebrew

### ISSUE THREAD

**Issue by wuya666** [ohmyzsh/ohmyzsh#10484]
### Describe the bug

The latest homebrew pour asdf into a `libexec` sub-directory, this is reflected in the official asdf documentation section ZSH & Homebrew:
http://asdf-vm.com/guide/getting-started.html#_3-install-asdf

However the asdf plugin included with Oh My Zsh still sets the ASDF_DIR environment variable to `$(brew --prefix asdf)` instead of `$(brew --prefix asdf)/libexec` which completely breaks the asdf command.

It took me hours and many futile reinstallations of asdf and homebrew to figure out the cause of this problem. If the asdf plugin of Oh My Zsh is no longer maintained, it should be removed from the repo.

### Steps to reproduce

1. Install asdf via Homebrew and setup according to the official documentation
2. enable plugin 'asdf'
3. running asdf will always produce a `/usr/local/opt/asdf/lib/commands/command-help.bash: No such file or directory` error

### Expected behavior

The asdf command should not break after enabling the 'asdf' plugin

### OS / Linux distribution

MacOS 12.0.1

### Zsh version

5.8

### Oh My Zsh version

master

### Terminal emulator

iTerm2

**Comment by emilyaviva** [comment]
Workaround for Homebrew: simply add the line
```zsh
source $(brew --prefix asdf)/libexec/asdf.sh
```
to your `.zshrc`.

**Comment by kevinclark** [comment]
This doesn't fix it for me. I get:

```
$ASDF_DIR is not a directory/usr/local/opt/asdf/libexec/asdf.sh:.:35: no such file or directory: /usr/local/Cellar/asdf/0.8.1_1/libexec/lib/asdf.sh
```

**Comment by pvinis** [comment]
this fixes it https://github.com/ohmyzsh/ohmyzsh/pull/10481

**Comment by wuya666** [comment]
> Workaround for Homebrew: simply add the line
> 
> ```shell
> source $(brew --prefix asdf)/libexec/asdf.sh
> ```
> 
> to your `.zshrc`.

Maybe it depends on where you put that line in the `.zshrc` file,  but I'm pretty sure it's useless if you put it at the end of the `.zshrc` file like the official documentation suggests, since the `asdf.sh` script only sets the `ASDF_DIR` environment variable if it's not already been set, and as the `ASDF_DIR` environment variable has already been set by the asdf plugin, it's still broken after running `asdf.sh`. I guess running putting an `unset ASDF_DIR` before sourcing the `asdf.sh` script should work.

**Comment by maxguzenski** [comment]
This fix it to me at the end of file .zshrc:

```
unset ASDF_DIR
source $(brew --prefix asdf)/libexec/asdf.sh
```
