### ISSUE TITLE
add "always" and "never" options to auto-correct

### ISSUE THREAD

**Issue by yuvalif** [ohmyzsh/ohmyzsh#10488]
### Describe the proposed feature.

when zsh proposes a correction, there will be an option to:
* "never" - never ask for this autocorrection again
* "alsway" - automatically autocorrect the next time it happens

### Describe alternatives you've considered

* for the "never" feature requested the alternative is to set a "nocorrect" alias to the commands that are being wrongly autocorrected
* do not have a workaround for the "always" feature

**Comment by mcornella** [comment]
The correct feature is built into zsh, we can't do anything about this. You should ask over on the [zsh-users mailing list](https://zsh.org/mla), but I have a hunch that this cannot be implemented.
