### ISSUE TITLE
Android 11 zshrc bug

### ISSUE THREAD

**Issue by Jacksack2000** [ohmyzsh/ohmyzsh#10499]
Android 11 - unrooted- user here.
Tried to do some modding in
~/.zshrc 
to disable "name@localhost".

Added at the end:
```
prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)$USER"
  fi
}
```

Still get the name@localhost.

Tried some themes, stuck with fox. 
Changed the fox.zsh-theme in the theme folder 
by adding the above standing code.

Still get the name@localhost.

An android 11 permission bug maybe? 

### Expected behavior

Name@localhost should have disappeared 

### OS / Linux distribution

termux, android 11 zsh 5.8

Appreciate any help

**Comment by Jacksack2000** [comment]
To clarify in short
These are the two directories (files) I added the code to:

~/.zshrc

~/.oh-my-zsh/themes/fox.zsh-theme

**Comment by mcornella** [comment]
The workaround you added only works for agnoster (and maybe some other similar theme). In the `fox` theme, you need to delete some sequences in the `PROMPT` line. Here's a diff for reference:
```diff
diff --git a/themes/fox.zsh-theme b/themes/fox.zsh-theme
index 3ecd4e20..2fda0813 100644
--- a/themes/fox.zsh-theme
+++ b/themes/fox.zsh-theme
@@ -1,6 +1,6 @@
 # fox.zsh-theme
 
-PROMPT='%{$fg[cyan]%}┌[%{$fg_bold[white]%}%n%{$reset_color%}%{$fg[cyan]%}☮%{$fg_bold[white]%}%M%{$reset_color%}%{$fg[cyan]%}]%{$fg[white]%}-%{$fg[cyan]%}(%{$fg_bold[white]%}%~%{$reset_color%}%{$fg[cyan]%})$(git_prompt_info)
+PROMPT='%{$fg[cyan]%}┌(%{$fg_bold[white]%}%~%{$reset_color%}%{$fg[cyan]%})$(git_prompt_info)
 └> % %{$reset_color%}'
 
 ZSH_THEME_GIT_PROMPT_PREFIX="-[%{$reset_color%}%{$fg[white]%}git://%{$fg_bold[white]%}"
```

You should also not change the file directly, but copy it to `$ZSH/custom` and make the modification there. See [the guide here](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes).
