### ISSUE TITLE
Bira theme text in command entry and program response now green

### ISSUE THREAD

**Issue by Tyler-Ward** [ohmyzsh/ohmyzsh#10505]
### Describe the bug

The text in the command input and program response (until it changes colour) is now green.
I have also seen various tab completions seem to cause some sections of the command input to end up in white (I assume they are resetting the colour before being added to the command input).

### Steps to reproduce

Update to latest omz and have bira theme enabled.

### Expected behavior

The command input text used to be white

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/3390465/145811679-b6ede5e1-63fb-4fec-99c6-8fd134ba1d80.png)
This image shows the command now in green as well as the first part of the program output before the program changes colour 

### OS / Linux distribution

Ubuntu 18.04

### Zsh version

5.4.2

### Oh My Zsh version

master (a94e2634)

### Terminal emulator

putty

### Additional context

I have the git and taskwarrior plugins enabled

The update which caused the issue was from 5b987e59 to a94e2634, the update history during the update includes  ```- 137b456 [bira]        Improve theme and add support for mercurial (#6631)``` however a quick look at that PR doesn't show an obvious cause for this issue.

**Comment by bzobl** [comment]
It seems like commit https://github.com/ohmyzsh/ohmyzsh/commit/137b45672dd182e798f7bd0c580aa9b634657990 causes this behaviour.

The `user_host` previously was generated as
```
local user_host='%{$terminfo[bold]$fg[red]%}%n@%m %{$reset_color%}'
```
now it is 
```
local user_host="%B%(!.%F{red}.%F{green})%n@%m %{$reset_color%}"
```
Changing this`%F{red}` and `%F{green}` to `$fg[red]` and `$fg[green]`, respectively, seems to work for me.

**Comment by mcornella** [comment]
Thanks for the report! %-prompt sequences don't seem to be turned off by `$reset_color`.

**Comment by Tyler-Ward** [comment]
Can confirm the update has fixed it at my end. Thanks for fixing so quickly.
