### ISSUE TITLE
Update failed because of rebase

### ISSUE THREAD

**Issue by Kremzon** [ohmyzsh/ohmyzsh#10502]
### Describe the bug

When trying to update I get this
```
Updating Oh My Zsh
From https://github.com/ohmyzsh/ohmyzsh
 * branch              master     -> FETCH_HEAD
fatal: It seems that there is already a rebase-merge directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr ".git/rebase-merge"
and run me again.  I am stopping in case you still have something
valuable there.

There was an error updating. Try again later?
```

### Steps to reproduce

omz update

### Expected behavior

omz gets updated

### OS / Linux distribution

MacOS 11.6

### Zsh version

5.8

### Oh My Zsh version

master (bf303965)

### Terminal emulator

iTerm2

**Comment by mcornella** [comment]
It looks like it failed the rebase on a previous update and it was never finished. You probably modified some files and it generated a conflict with newer changes. You should resolve the conflicts and finish the rebase with `git rebase --continue`, or abort the rebase completely with `git rebase --abort`.

**Comment by Kremzon** [comment]
I didn't actually change any file but ok.
I went in, did `git reset --hard` and then everything worked.
Weird, hope non of my plugins have any problems

**Comment by mcornella** [comment]
> I didn't actually change any file but ok.

Then it might have been that the update was cancelled or it failed mid-update. If you didn't change anything you shouldn't have any problems.

**Comment by molitona** [comment]
> git reset --hard

it's not you, i had the same issue as you. thanks for the solution.

**Comment by molitona** [comment]
> > git reset --hard
> 
> it's not you, i had the same issue as you. thanks for the solution.

@Kremzon

**Comment by ahokinson** [comment]
> It looks like it failed the rebase on a previous update and it was never finished. **You probably modified some files and it generated a conflict with newer changes**. You should ... abort the rebase completely with `git rebase --abort`.

This is the answer everyone is looking for, but by suggesting there is blame on the user for modifying files, you've likely led people to believe this isn't going to solve their problems.

> If you didn't change anything you shouldn't have any problems.

is a weird thing to say after admitting 

>it might have been that the update was cancelled or it failed mid-update.

I agree that this isn't an issue with `ohmyzsh`, but when documenting a problem resolution that other people will search for, this just seems like an unnecessary blame game.

**Comment by mcornella** [comment]
I was not placing blame on anyone, I only suggested the most probable cause of the error (we get a lot of issues like this one, and that is almost always the case). And I said it so that no changes are made to the repository to avoid future errors.

I admit my wording was rushed and it could be misunderstood. I do have little time to deal with posted errors though. If this is happening more consistently I should investigate if there's a bug in OMZ, so do update the issue if you have the same errors and I'll do my best to help.
