### ISSUE TITLE
Latest update causes cursor to not sit in the right place

### ISSUE THREAD

**Issue by JoelDesante** [ohmyzsh/ohmyzsh#10517]
### Describe the bug

The latest update causes the cursor in the Terminal to sit in the wrong location (See Figure 1).

### Steps to reproduce

1. Update to the latest version.

### Expected behavior

The cursor should be in the right place and should not overwrite the existing text on screen.

### Screenshots and recordings

Figure 1:
<img width="171" alt="Screen Shot 2021-12-18 at 1 09 23 PM" src="https://user-images.githubusercontent.com/9503791/146651571-1ab85ea3-a280-4caf-8878-ae34707c9d0c.png">
<img width="394" alt="Screen Shot 2021-12-18 at 1 14 01 PM" src="https://user-images.githubusercontent.com/9503791/146651629-19fca97d-e365-44fb-845c-3be9b3b95d92.png">
<img width="541" alt="Screen Shot 2021-12-18 at 1 14 07 PM" src="https://user-images.githubusercontent.com/9503791/146651630-5d0e3a3e-97b0-40c4-8087-e56669107c05.png">

### OS / Linux distribution

MacOS Big Sur 11.3.1

### Zsh version

5.8

### Terminal emulator

Terminal.app

**Comment by rwmitchell** [comment]
What theme, plugins are you using?  I'm not seeing this with p10k (and just updated omz to check)

**Comment by JoelDesante** [comment]
Theme: af-magic
Plugin(s): git

**Comment by JoelDesante** [comment]
Update: Tried to reboot my computer to see if that would solve anything. No change.
This only started happening once I updated OhMyZsh earlier today.

**Comment by rwmitchell** [comment]
af-magic was changed on Nov. 30, maybe try rolling back to the previous version?

**Comment by JoelDesante** [comment]
I switched to the theme `daveverwer` to see if the issue persists. It has gone away. 
This is odd though, because I am pretty good about updating. I feel that I would have seen this issue earlier if this was exclusively an af-magic issue.

**Comment by rwmitchell** [comment]
Did you fix it?  af-magic is an included omz theme.

**Comment by navelpluisje** [comment]
Same issue here. Just looked at the code and there is a `%` missing in the end of line 30 and should look like
`RPS1+=" ${FG[237]}%n@%m%{$reset_color%}%"`

I will try to create a PR today

**Comment by mcornella** [comment]
This is a bug in `fig`, which introduced a workaround to fix the previous broken version of the `af-magic` theme (see https://github.com/withfig/fig/issues/311#issuecomment-998864268).

This should be fixed in the next fig release, but in the meantime you can add this to your `zshrc` file, before the fig lines at the bottom of the zshrc file:

```zsh
RPS1+='%'
```

When fig updates and you see a broken prompt again, you can remove that line.
