### ISSUE TITLE
dirhistory not working

### ISSUE THREAD

**Issue by mike-boost** [ohmyzsh/ohmyzsh#10523]
### Describe the bug

Obiviously the options + right is not working, as it means skip a word forward.

### Steps to reproduce

Obiviously the options + right is not working, as it means skip a word forward.

### Expected behavior

cd into next folder

### OS / Linux distribution

latest big sur

### Zsh version

zsh 5.8 (x86_64-apple-darwin20.0)

### Oh My Zsh version

master (6babcbd8)

### Terminal emulator

mac terminal

**Comment by mcornella** [comment]
Did you maybe use the `vi-mode` plugin? If so, e9bc107a fixed that so you should `omz update`.
