### ISSUE TITLE
On new termina sessions, nvm plugin says "N/A -> N/A" is not yet installed

### ISSUE THREAD

**Issue by andreasciamanna** [ohmyzsh/ohmyzsh#10527]
### Describe the bug

Every time I start a new terminal session, I get the following:

```
N/A: version "N/A -> N/A" is not yet installed.

You need to run "nvm install N/A" to install it before using it.
```

NVM works just fine, but I get this error and I can't use the `NVM_AUTOLOAD` feature because of that.

Removing the plugin, of course, removes the message, but it also removes NVM :)

I've tried to google around but I can't find anyone reporting this issue.

### Steps to reproduce

1. On a Mac (Big Sur 11.6.1)
2. Enable `nvm`
3. Start a new terminal session

### Expected behavior

No messages like the one reported

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/181780/147226801-c5eb91b0-8422-42b2-bf7d-989c7cbf4d50.png)

![image](https://user-images.githubusercontent.com/181780/147226844-ad1614a7-f9b4-4647-b842-52cb714b1d7b.png)

### OS / Linux distribution

macOS Big Sur 11.6.1

### Zsh version

5.8

### Terminal emulator

Terminal.app, WebStorm terminal

**Comment by mcornella** [comment]
Looks like your nvm default points to an uninstalled node version. See https://stackoverflow.com/a/52305468/5798232.
