### ISSUE TITLE
omz does not respect .zshrc and .zshenv

### ISSUE THREAD

**Issue by PixsaOJ** [ohmyzsh/ohmyzsh#10520]
### Describe the bug

I have moved my zshell configuration in `~/.config/zsh` by creating `.zshenv` in home directory.

When I try to install plugin with `omz` it could not find `.zshrc` and does not know where to look.

### Steps to reproduce

1. create `~/.zshenv` file with contents:
`ZDOTDIR=$HOME/.config/zsh`

2. Move zshell config to desired folder.

3. run `omz plugin enable nvm` you can use any plugin.

### Expected behavior

Respect `.zshenv` and find `.zshrc` file.

### Screenshots and recordings

```bash
➜  ~ omz plugin enable nvm
awk: fatal: cannot open file `/home/pixsa/.zshrc' for reading: No such file or directory
omz::plugin::enable: error enabling plugins.
```

### OS / Linux distribution

Pop OS 21.10

### Zsh version

5.8

### Oh My Zsh version

master (904f8685)

### Terminal emulator

alacritty

**Comment by mcornella** [comment]
Thank you for the report, should be fixed now :)
