### ISSUE TITLE
Changing `$PATH` after `gnu-utils` plugin has loaded breaks functionality

### ISSUE THREAD

**Issue by ardeidae** [ohmyzsh/ohmyzsh#10535]
### Describe the bug

Hello,

I have a problem on macOS with gnu-utils plugin.
It works fine with this minimal .zshrc file:

```
export ZSH="/Users/test/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(
gnu-utils
)
source $ZSH/oh-my-zsh.sh
```

But, when I add the pyenv plugin, gnu-utils plugin seems to break.
Minimal non-working .zshrc file:

```
export ZSH="/Users/test/.oh-my-zsh"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
ZSH_THEME="robbyrussell"
plugins=(
gnu-utils
pyenv
)
source $ZSH/oh-my-zsh.sh
```

Demonstration:
```
➜  ~ mkdir -v test
mkdir: created directory 'test'
➜  ~ rm test -rfv
rm: test: is a directory
rm: -rfv: No such file or directory
➜  ~ rm -rfv test
test
```

### Steps to reproduce

Enable gnu-utils and pyenv plugin.

Run the following commands:
```
➜  ~ mkdir -v test
mkdir: created directory 'test'
➜  ~ rm test -rfv
rm: test: is a directory
rm: -rfv: No such file or directory
```

### Expected behavior

Gnu version of rm should be used, and the -rfv args must be accepted at the end of the line.

### OS / Linux distribution

macOS 11.6

### Zsh version

5.8

### Terminal emulator

iTerm2

**Comment by mcornella** [comment]
Can you post what `which -a rm` prints, as well as `echo $commands[rm]`?

**Comment by ardeidae** [comment]
> Can you post what `which -a rm` prints, as well as `echo $commands[rm]`?

Yes, sure.

```
➜  ~ which -a rm
/bin/rm
➜  ~ echo $commands[rm]
/bin/rm
➜  ~ which grm
/usr/local/bin/grm
```

**Comment by ardeidae** [comment]
So, I just tried to change plugin order. I put pyenv before gnu-utils and it seems to solve the problem.
But, is there something in pyenv that can break others plugins?

**Comment by mcornella** [comment]
I believe the `rehash` function is broken in the `gnu-utils` plugin. Try the patch below:
```diff
diff --git a/plugins/gnu-utils/gnu-utils.plugin.zsh b/plugins/gnu-utils/gnu-utils.plugin.zsh
index 539e7fe4..5b8f71c8 100644
--- a/plugins/gnu-utils/gnu-utils.plugin.zsh
+++ b/plugins/gnu-utils/gnu-utils.plugin.zsh
@@ -73,11 +73,6 @@ function hash() {
 }
 
 function rehash() {
-  if [[ "$*" =~ "-f" ]]; then
-    builtin rehash "$@"
-    __gnu_utils
-  else
-    builtin rehash "$@"
-  fi
+  builtin rehash "$@"
+  __gnu_utils
 }
-
```

You can apply it in the `$ZSH` folder with `clippaste | git apply -`, provided you've copied the diff above.

**Comment by ardeidae** [comment]
```
➜  .oh-my-zsh git:(master) ✗ git diff
diff --git a/plugins/gnu-utils/gnu-utils.plugin.zsh b/plugins/gnu-utils/gnu-utils.plugin.zsh
index 539e7fe..5b8f71c 100644
--- a/plugins/gnu-utils/gnu-utils.plugin.zsh
+++ b/plugins/gnu-utils/gnu-utils.plugin.zsh
@@ -73,11 +73,6 @@ function hash() {
 }

 function rehash() {
-  if [[ "$*" =~ "-f" ]]; then
-    builtin rehash "$@"
-    __gnu_utils
-  else
-    builtin rehash "$@"
-  fi
+  builtin rehash "$@"
+  __gnu_utils
 }
-
(END)
```

Logged out and logged in again, and I still get this error.

```
➜  ~ rm test -rfv
rm: test: is a directory
rm: -rfv: No such file or directory
```

**Comment by mcornella** [comment]
What does `pyenv init - --no-rehash zsh` print?

**Comment by rwmitchell** [comment]
Is PYENV_ROOT set?  if not, that would put /bin first in the path.

**Comment by mcornella** [comment]
> Is PYENV_ROOT set? if not, that would put /bin first in the path.

[It is](https://github.com/ohmyzsh/ohmyzsh/issues/10535#issue-1088843011):

> Minimal non-working .zshrc file:
> 
> ```
> export ZSH="/Users/test/.oh-my-zsh"
> export PYENV_ROOT="$HOME/.pyenv"
> export PATH="$PYENV_ROOT/bin:$PATH"
> eval "$(pyenv init --path)"
> ZSH_THEME="robbyrussell"
> plugins=(
> gnu-utils
> pyenv
> )
> source $ZSH/oh-my-zsh.sh
> ```

**Comment by rwmitchell** [comment]
is the plugin modifying it?  I see the following lines in it:

  local pyenv_root="${PYENV_ROOT/#$HOME/\$HOME}"
export PYENV_ROOT="$pyenv_root"

there's other code around it that may negate it actually changing it.

**Comment by mcornella** [comment]
That's only for the warning message, it doesn't actually change `$PYENV_ROOT`. The only way `PYENV_ROOT` is changed is if the `pyenv` command is not found or if `PYENV_ROOT` is not set to anything, in which case it is set to `pyenv root`.

**Comment by mcornella** [comment]
@ardeidae I can't reproduce your problem in macOS 10.15. You could generate a trace of the zsh initialization (with the configuration that makes the plugin fail) and post it here. You can do that with `zsh -xvic exit &> ~/omz-debug.log`.

Not that this will contain sensitive info like the user and host names. If you prefer, you can email it to me at <marc@ohmyz.sh>.

**Comment by ardeidae** [comment]
> What does `pyenv init - --no-rehash zsh` print?

```
➜  ~ pyenv init - --no-rehash zsh
export PYENV_SHELL=zsh
source '/usr/local/Cellar/pyenv/2.2.3/libexec/../completions/pyenv.zsh'
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  activate|deactivate|rehash|shell)
    eval "$(pyenv "sh-$command" "$@")"
    ;;
  *)
    command pyenv "$command" "$@"
    ;;
  esac
}
```

**Comment by ardeidae** [comment]
@mcornella, here is the log file.
I've created another user account to get the minimal reproducible example, so, no problem with user and host names.

[omz-debug.log](https://github.com/ohmyzsh/ohmyzsh/files/7779047/omz-debug.log)

**Comment by mcornella** [comment]
OK, I could reproduce the problem when using `pyenv-virtualenv`. If it's enabled, the `pyenv` plugin runs
```zsh
eval "$(pyenv virtualenv-init - zsh)"
```
which runs the following:
```zsh
export PATH="/home/user/.pyenv/plugins/pyenv-virtualenv/shims:${PATH}";
export PYENV_VIRTUALENV_INIT=1;
_pyenv_virtualenv_hook() {
  local ret=$?
  if [ -n "$VIRTUAL_ENV" ]; then
    eval "$(pyenv sh-activate --quiet || pyenv sh-deactivate --quiet || true)" || true
  else
    eval "$(pyenv sh-activate --quiet || true)" || true
  fi
  return $ret
};
typeset -g -a precmd_functions
if [[ -z $precmd_functions[(r)_pyenv_virtualenv_hook] ]]; then
  precmd_functions=(_pyenv_virtualenv_hook $precmd_functions);
fi
```

I reduced the culprit to the `export PATH` line. I believe when changing `$PATH`, the commands are rehashed by default, but the `gnu-utils` plugin does not trigger, therefore the old commands are preserved.

I'll try to find a way to hook into the hash when `$PATH` is changed. In the meantime, you can add `__gnu_utils` at the bottom of your .zshrc file to rerun the rehash after `pyenv` is loaded.

**Comment by mcornella** [comment]
I solved the issue by reassigning the GNU utils on every command execution, if they aren't already assigned. You should be good to go now if you `omz update`.

**Comment by ardeidae** [comment]
@mcornella, a very big thanks for this very quick fix.
