### ISSUE TITLE
Error in Wiki

### ISSUE THREAD

**Issue by BudhirajaMadhav** [ohmyzsh/ohmyzsh#10534]
### Describe the proposed feature.

In the wiki [here](https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#zsh_theme_random_quiet) it is mentioned that the variable should be true or 1 but according to the code [here](https://github.com/ohmyzsh/ohmyzsh/blob/master/themes/random.zsh-theme#L45-L47) `-z` is used, which states this variable can be defined with `any value` unless `null`.
![image](https://user-images.githubusercontent.com/73742540/147416558-ff037cab-8314-4dbc-b614-9a784c6ce553.png)

**Comment by mcornella** [comment]
That was written like that for consistency with the rest of the settings. It's now more strict. Thanks for the report.

**Comment by uco16** [comment]
Unfortunately the fix 96e473a introduced a bug: the random message is now produced only if `$ZSH_THEME_RANDOM_QUIET` is set to `true`, which is exactly opposite to what should happen.

**Comment by mcornella** [comment]
> Unfortunately the fix [96e473a](https://github.com/ohmyzsh/ohmyzsh/commit/96e473a1d65cf3a093be2c742eea427706f18c01) introduced a bug: the random message is now produced only if `$ZSH_THEME_RANDOM_QUIET` is set to `true`, which is exactly opposite to what should happen.

Forgot to reply, but after your report I pushed 634296be to fix this.
