### ISSUE TITLE
zsh-navigation-tools 404

### ISSUE THREAD

**Issue by taylorzhangyx** [ohmyzsh/ohmyzsh#10530]
### Describe the bug

the script URL is invalid

### Steps to reproduce

just run the script in readme

### Expected behavior

the .sh file should exist

### OS / Linux distribution

macos

### Zsh version

-

### Terminal emulator

iterm2

**Comment by mcornella** [comment]
This is partially fixed in #10402, but needs to be expanded so that the whole plugin is updated to the fork.

**Comment by mcornella** [comment]
Fixed in #10402.
