### ISSUE TITLE
New rust plugin seems broken

### ISSUE THREAD

**Issue by carlosala** [ohmyzsh/ohmyzsh#10536]
### Describe the bug

The `cargo` and `rustup` completions doesn't work for me as part of `rust` plugin. `rustc` completion works.

### Steps to reproduce

1. Enable plugin `rust`
2. Try to autocomplete `cargo` command

### Expected behavior

Have completions.

### OS / Linux distribution

Debian 11 Bullseye

### Zsh version

5.8

### Terminal emulator

kitty

**Comment by mcornella** [comment]
What does `ls -l $ZSH_CACHE_DIR/completions` show?

**Comment by carlosala** [comment]
The completions were there. After removing `.oh-my-zsh` folder and re-cloning everything works.

**Comment by hxzhao527** [comment]
when `"$ZSH_CACHE_DIR/completions"` not exist, plugin rust will fail

**Comment by rwmitchell** [comment]
Why does it not exist ?

<img width="435" alt="image" src="https://user-images.githubusercontent.com/15944841/210964680-8f16780d-2ea4-4a61-8bf0-a1136e95f1d8.png">

**Comment by hxzhao527** [comment]
@rwmitchell 
I use [antigen](https://github.com/zsh-users/antigen) manage plugins.
this is my `~/.zshrc` content
```
source /usr/share/zsh/share/antigen.zsh
antigen use oh-my-zsh

antigen bundle rust

antigen apply
```

then after login, noticed
```bash
/home/hxzhao/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/rust/rust.plugin.zsh:22: no such file or directory: /home/hxzhao/.antigen/bundles/robbyrussell/oh-my-zsh/cache//completions/_rustup
/home/hxzhao/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/rust/rust.plugin.zsh:23: no such file or directory: /home/hxzhao/.antigen/bundles/robbyrussell/oh-my-zsh/cache//completions/_cargo
```

env info
```
$ zsh --version
zsh 5.9 (x86_64-pc-linux-gnu)
$ omz version
master (69dfd77)
$  ls $ZSH_CACHE_DIR/completions
ls: cannot access '/home/hxzhao/.antigen/bundles/robbyrussell/oh-my-zsh/cache//completions': No such file or directory
```

**Comment by rwmitchell** [comment]
OMZ has a simple initial installation and then continues to maintain itself by autoupdating every couple weeks.  What does using antigen to install OMZ get other, other than breaking things?
