### ISSUE TITLE
fzf plugin must come after the vi-mode plugin otherwise the history search (should document)

### ISSUE THREAD

**Issue by richtong** [ohmyzsh/ohmyzsh#10533]
### Describe the bug

If you do not have the vi-mode plugin installed then fzf works properly. That is a Ctrl-R will get you the FZF find a history, but if vi-mode is installed then you get the vanilla history search

### Steps to reproduce

In .zshrc add

plugins=(fzf vi-mode)

Then when you start Zsh, a Ctrl-R will give you the normal history search

But 

plugins=(vi-mode fzf)

Will give you the correct fzf so it looks like ^R is mapped by vi-mode

### Expected behavior

I think there should probably just be documentation on this so that it is not so unclear what with the many key bindings that all these plugins have and I'm happy to submit an PR for this.

Also in v

### OS / Linux distribution

macOS 12.1

### Zsh version

5.8

### Oh My Zsh version

master (068feca)

### Terminal emulator

iterm2

**Comment by mcornella** [comment]
The `fzf` plugin only sources the proper `fzf` initialization files. This bug should be submitted to fzf.

**Comment by mcornella** [comment]
Submitted in https://github.com/junegunn/fzf/issues/2694.
