### ISSUE TITLE
zsh-navigation-tools install instructions point to broken shell script

### ISSUE THREAD

**Issue by Kallin** [ohmyzsh/ohmyzsh#10549]
### Describe the bug

on the install instructions for zsh-navigation tools, here, https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/zsh-navigation-tools#installation , it says to run:

```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma-continuum/zsh-navigation-tools/master/doc/install.sh)"
```

that script references a repository, `https://github.com/psprint/zsh-navigation-tools.git`, which no longer exists. 

### Steps to reproduce

try installing zsh-navigation-tools as described

### Expected behavior

tool should complete installation

### OS / Linux distribution

Ubuntu 20.04

### Zsh version

5.8

### Oh My Zsh version

master (116fc2fe)

### Terminal emulator

windows terminal 

### If using WSL on Windows, which version of WSL

WSL2

**Comment by mcornella** [comment]
The plugin README is a copy of the upstream project. You should just add `zsh-navigation-tools` to the plugins array in your zshrc file to enable it.
