### ISSUE TITLE
Ohmyzsh Startup Faliure

### ISSUE THREAD

**Issue by Imranplayz** [ohmyzsh/ohmyzsh#10541]
### Describe the bug

**Username = javax**
Alright so whenever I open my konsole it always brings up this error
</home/javax/.oh-my-zsh/oh-my-zsh.sh:source:177: no such file or directory: /home/javax/.oh-my-zsh/themes/powerlevel10k/powerlevel10k.zsh-theme>
And I always have to reintstall ohmyzsh and powerlevel10k
Could someone in the community help me?

### Steps to reproduce

1. Open Internet Browser
2. Insert this url `https://medium.com/@satriajanaka09/setup-zsh-oh-my-zsh-powerlevel10k-on-ubuntu-20-04-c4a4052508fd`
3. Follow to the letter til Step 8
4. Open new Terminal
5. You have found the problem!

### Expected behavior

![image](https://user-images.githubusercontent.com/67116889/147684914-188016ee-51b5-43c9-80d8-c938799b3181.png)
this is what you should have gotten instead of my error above

### OS / Linux distribution

Manjaro KDE Plasma 21.2.0

### Zsh version

5.8

### Terminal emulator

Konsole

**Comment by mcornella** [comment]
You missed the step about running the `git clone`:
```sh
git clone — depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$ZSH/custom}/themes/powerlevel10k
```

**Comment by mcornella** [comment]
Nevermind, the command is broken. It should be `--depth=1` instead:
```sh
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$ZSH/custom}/themes/powerlevel10k
```
Probably a formatting error.

**Comment by Imranplayz** [comment]
But I did that step and it’s not working

**Comment by mcornella** [comment]
The command was wrong, see https://github.com/ohmyzsh/ohmyzsh/issues/10541#issuecomment-1002688167 for the right command.

**Comment by Imranplayz** [comment]
I still get the same issue after i do this command 
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$ZSH/custom}/themes/powerlevel10k
then I follow the guide and edit the ~/.zshrc and make ZSH_THEME "powerlevel10k/powerlevel10k"
"Open new terminal" the guide says. And here we are, the same error comes back
`/home/javax/.oh-my-zsh/oh-my-zsh.sh:source:177: no such file or directory: /home/javax/.oh-my-zsh/themes/powerlevel10k/powerlevel10k.zsh-theme`

**Comment by mcornella** [comment]
Did the `git clone` work or it showed any errors? What is in `$ZSH_CUSTOM/themes`?
