### ISSUE TITLE
iw executable cannot be called after installing ohmyzsh

### ISSUE THREAD

**Issue by jeverling** [ohmyzsh/ohmyzsh#10551]
### Describe the bug

Hi, on a Raspberry Pi running _Raspbian GNU/Linux 11 (bullseye)_, the `pi` user can successfully execute `iw dev` before ohmyzsh installation.
After installation, the same fails:

```
➜  ~ iw dev
zsh: command not found: iw
```

Calling the executable by absolute path still works: 

```
➜  ~ /usr/sbin/iw dev
phy#2
        Interface wlan0
                ifindex 3
[...]
```

When running bash, calling `iw dev` also still works.

So it does not seem to be a problem with the executable, but rather zsh cannot locate it for some reason.

### Steps to reproduce

Try calling `iw dev` as unprivileged user. Install ohmyzsh using install script. Try command again.

### Expected behavior

`iw dev` should work with zsh like it does with bash.

### OS / Linux distribution

Raspbian GNU/Linux 11 (bullseye)

### Zsh version

5.8

### Terminal emulator

SSH session in Konsole

**Comment by rwmitchell** [comment]
check your $PATH
is that getting changed in your .zshrc?
if that isn't it, what plugins are you using?

**Comment by jeverling** [comment]
It's a fresh install, no modifications have been made to `.zshrc` after installation using the install script.

`$PATH` seems to look fine: `/usr/local/bin:/usr/bin:/bin:/usr/games`

`echo $plugins` returns `git`.

**Comment by rwmitchell** [comment]
that path lacks either /sbin or /usr/sbin/ which is why it isn't working.

Do you have a zsh installation without omz to see if it included those in the path before installing omz?

**Comment by jeverling** [comment]
Wait, I just noticed that the executable is in `/usr/sbin`. Don't know why bash finds it there, but it's actually not in `$PATH`.
So this is not a bug but rather the right behavior. Thank you for the quick response!

**Comment by jeverling** [comment]
> Do you have a zsh installation without omz to see if it included those in the path before installing omz?

I checked the $PATH with bash, and it also does not include "sbin" directories, the $PATH is the same.

**Comment by rwmitchell** [comment]
really?!  ```which iw``` shows 'iw' pathing to place not in $PATH ??

**Comment by jeverling** [comment]
I'm confused as well. I'll do a fresh install of the SD card (I'm running on a Raspberry Pi) and confirm.

**Comment by jeverling** [comment]
Sorry, earlier I checked the `$PATH` after calling `bash`, but I should have sourced `.bashrc`, it was printing the wrong `$PATH`.

Checking on a fresh install now, the `$PATH` in bash is `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games`.
So there is no bug, only bash includes sbin directories in the `$PATH` and zsh does not. Thanks for your assistance in debugging.

**Comment by rwmitchell** [comment]
thanks for the follow-up.  you certainly took the debugging much farther than i would have.
