### ISSUE TITLE
Ubuntu.zsh aar parse error

### ISSUE THREAD

**Issue by DrewGoodfellow** [ohmyzsh/ohmyzsh#10560]
After updating to the latest oh-my-zsh, I get these two lines after opening a virtual TTY

`/home/andrew/.oh-my-zsh/plugins/ubuntu/ubuntu.plugin.zsh:56: defining function based on alias `aar'
/home/andrew/.oh-my-zsh/plugins/ubuntu/ubuntu.plugin.zsh:56: parse error near `()'
`

This is my zsh version:

`zsh --version
zsh 5.8 (x86_64-ubuntu-linux-gnu)
`

I'm on Ubuntu 20.04.

I think that this is the same problem as https://github.com/ohmyzsh/ohmyzsh/issues/6237 Adding the word function before aar() on line 56 of ubuntu.zsh appears to resolve the issue for me. I hope this helps @AlexBio !

Thank your for reading this,

Andrew

**Comment by gnuy** [comment]
I had the same issue, and though the `func_name () { ... }` notation should work in bash, the error disappeared when changing line 56 of that file with 
```
function aar {
```

**Comment by mcornella** [comment]
You're probably using the `debian` plugin as well, which defines an `aar` alias. In any case, I prefixed all functions with the keyword `function` so this shouldn't happen again.

**Comment by gnuy** [comment]
Thanks @mcornella for all your work 💪
