### ISSUE TITLE
(kubectx): quote % in `kubectx_prompt_info` breaks coloring

### ISSUE THREAD

**Issue by yhrn** [ohmyzsh/ohmyzsh#10562]
### Describe the bug

[This commit](https://github.com/ohmyzsh/ohmyzsh/commit/d87ab251c7fe18626b2d0c4e4a184e7bed7c508b) introduced quoting of %, but it is unclear to me why (@mcornella who authored the change might be able to shed some light on that). This causes the cursor placement as well as alignment to break when using a colored value in the associative array `kubectx_mapping` for the right side prompt.

### Steps to reproduce

1. Enable plugin kubectx
1. Add the following to `.zshrc`:
```
RPS1='$(kubectx_prompt_info)'
kubectx_mapping[my_kube_ctx]="%{$fg[green]%}My Context%{$reset_color%}"
```
1. Reload `.zshrc`
1. Switch to the `my_kube_ctx` context

The cursor is now too far left and the kubectx info is not fully right aligned and also contains additional %{} characters. If the `%{...%}` indicators are removed from the `kubectx_mapping` the additional characters go away but the cursor is still messed up and the kubectx info is still incorrectly aligned.

### Expected behavior

The cursor is after the left side prompt and the kubectx info is fully right aligned.

### OS / Linux distribution

Ubuntu 20.04

### Zsh version

5.8

### Terminal emulator

Windows Terminal

### If using WSL on Windows, which version of WSL

WSL2

**Comment by mcornella** [comment]
The quote is to remove prompt expansion, but as you correctly point out that shouldn't be done to `$kubectx_mapping`. Should be fixed now.
