### ISSUE TITLE
Sentence in README.md can be improved

### ISSUE THREAD

**Issue by a1cd** [ohmyzsh/ohmyzsh#10573]
> maybe you'll use the **`time that you're saving`** to start flossing more often. 😬

is confusing and can be replaced with:
> maybe you'll use the **`saved time`** to start flossing more often. 😬

I loved the intro and it was just that specific sentence that was hard to understand.

**Comment by mcornella** [comment]
From https://github.com/ohmyzsh/ohmyzsh/pull/10574#issuecomment-1009085146:
> This is not an issue, the wording is clear and proper English. Thanks for the contribution though!
