### ISSUE TITLE
[yarn plugin] Yarn completion is not working accordingly

### ISSUE THREAD

**Issue by franciscocpg** [ohmyzsh/ohmyzsh#10578]
### Describe the bug

Before #10516 I was able to run completion for `scripts` without having to add the `run` command.

### Steps to reproduce

Let's say I have a script called `start-dev`. Typing `yarn s` and pressing TAB was completing `start-dev` successfully. After #10516 it does not work anymore. I need to type `yarn run s` and press TAB to make it work.

Not sure why the two snippets below aren't using the same logic:
https://github.com/ohmyzsh/ohmyzsh/blob/3a1d83d778388b574bde70f41e9674092dafe6ef/plugins/yarn/_yarn#L119
https://github.com/ohmyzsh/ohmyzsh/blob/3a1d83d778388b574bde70f41e9674092dafe6ef/plugins/yarn/_yarn#L147

But I was able to fix it locally using the same logic of line 147 at line 119, that would be:
```bash
scripts=($(cat "${packageJson}" | perl -0777 -MJSON::PP -n -E '%r=%{decode_json($_)->{scripts}}; printf "$_:$r{$_}\n" for sort keys %r'))
```

After this change, I'm able to type `yarn s` and press TAB to make `yarn start-dev` completion.

### Expected behavior

Completion should work when typing `yarn <script>` without the `run` command. 

### OS / Linux distribution

Garuda Linux

### Zsh version

5.8

### Oh My Zsh version

master (9c84c344)

### Terminal emulator

Konsole

**Comment by carlosala** [comment]
Hi Francisco,
The bug was introduced in the upstream repo of `yarn` completion, and of course was replicated in #10516.
I opened a new [PR](#10579) updating the completion, and it fixes the bug.
Sorry about that, have a nice day! ;)
