### ISSUE TITLE
An error is printed when trying to autocomplete maven commands

### ISSUE THREAD

**Issue by peter-janssen** [ohmyzsh/ohmyzsh#10580]
### Describe the bug

An error is printed when trying to autocomplete maven commands

### Steps to reproduce

1. Enable plugin `mvn`
2. Complete command `mvn ` (mind the space)

### Expected behavior

Present a list of options (or warning if too many)

### Screenshots and recordings

```
mvn find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]

zsh: do you wish to see all 521 possibilities (75 lines)?
```

### OS / Linux distribution

macOS 12.1

### Zsh version

5.8

### Oh My Zsh version

master (b4819557)

### Terminal emulator

iTerm2 (3.4.14)

### Additional context

When looking at the source ([`mvn.plugin.zsh`](https://github.com/ohmyzsh/ohmyzsh/blob/93cea53618ebd3f108275c88c948f790492337b4/plugins/mvn/mvn.plugin.zsh#L120)) it seems the path is missing for the `find` command on line 120. If I add a `.` (period) after the `find` command it seems to work as expected. Except that if there is a directory with restricted permissions. A different error is shown.

**Comment by mcornella** [comment]
Can you post a sample repo where I can debug this? I can't trigger the `find` bug. What does `print -l **/pom.xml` show in the directory where you get the error?

**Comment by peter-janssen** [comment]
I'm not really sure what the content of a sample repo would look like. The error occurs regardless of the content of the directory. The example given is from an empty directory. Upon closer inspection it seems the error does not occur when a `pom.xml` file is present.

**Comment by mcornella** [comment]
Can you check if #10586 works? You can test it with `omz pr test 10586`.

**Comment by peter-janssen** [comment]
LGTM, I don't see any errors even with inaccessible directories. I also see all modules listed in the output. Thanks!

**Comment by mcornella** [comment]
Thanks for confirming!
