### ISSUE TITLE
bindkey is not work in "~/.zshrc"

### ISSUE THREAD

**Issue by JamesZwq** [ohmyzsh/ohmyzsh#10599]
d### Describe the bug

I add this three line at the end of ~/.zshrc
```sh
bindkey "^[[B" history-beginning-search-forward     
bindkey "^[[A" history-beginning-search-backward
```
but when I restart the shell, the keys up and down did not perform as expected. But when I run `source ~/.zshrc`, the keys up and down is work, which can find the history.
I tried adding some printable commands to ~/.zshrc, like `echo "this is work"`, this is work when I restart the shell.

I'm incredibly confused, any help is greatly appreciated

### Steps to reproduce

1. add in the end of ~/.zshrc
   ```sh
   bindkey "^[[B" history-beginning-search-forward
   bindkey "^[[A" history-beginning-search-backward
   ```

2. restart shell

### Expected behavior

when I restart shell the Shortcuts should work。

### OS / Linux distribution

Macos 12.2 (21D5039d)

### Zsh version

5.8

### Terminal emulator

Apple Terminal, VScode Terminal

**Comment by Jamesxwq** [comment]
> You need to make sure that `^[[B` and `^[[A` are the keyboard sequences for Down and Up arrow keys. You can test that by pressing CTRL-V and then pressing Down or Up arrow, which will display the keyboard sequence in the command line.
> 
> For me, Up arrow is `^[OA` and Down arrow is `^[OB`. That's going to depend on your terminal (it might be different in Terminal.app and VS Code terminal).

Thanks for your reply,`^[[B` and `^[[A`It's correct for me, the main thing that confuses me is I have to run `source ~/.zshrc` when starting a new zsh to make these two work. when I run ```
bindkey"^[[B" history-beginning-search-forward     
bindkey "^[[A" history-beginning-search-backward
``` after I restart zsh, thay also work.

**Comment by rwmitchell** [comment]
does the debug statement "this is work" occur after the bindkey lines?

Can you show what are the last 3 or 4 lines of your ~/.zshrc file?  I'm assuming it just the 2 bindkey lines and the debug output.

**Comment by Jamesxwq** [comment]
> 

![image](https://user-images.githubusercontent.com/58351018/150244483-b330e5fd-b182-4c0b-bd51-20635fb46bc7.png)
Thanks for the reply, this is the image, I have just added more `echo` commands and they all seem to be working fine

**Comment by rwmitchell** [comment]
As a really brute force to see if something is changing with bindkey, add:
```bindkey > /tmp/bindkey-debug-$$```
at the end of the .zshrc, then restart zsh, followed by sourcing .zshrc.  That should generate two debug files.  use: ```opendiff /tmp/bindkey-debug*``` to compare them.  See if anything jumps out.

**Comment by Jamesxwq** [comment]
> 

OMG, they are the same, it's so weird，I find `
"^[[A" history-substring-search-up
"^[[B" history-substring-search-down
"^@" autosuggest-accept
`
in the both of them.
I'm totally confused

**Comment by mcornella** [comment]
`$$` is not supposed to change in the same zsh session, so when you run `source ~/.zshrc` again you'll write the results of bindkey on the same file.

Just check `bindkey '^[[A'` when it doesn't work before running `source`.

**Comment by mcornella** [comment]
ping @Jamesxwq

**Comment by Jamesxwq** [comment]
I'm sorry for the late reply, I just tried what you said, first open a new terminal, then open another new terminal and run `source ~/.zshrc`,The second terminal's debug file has many more things than the first terminal's debug file, including
```
"^[[A" history-substring-search-up
"^[[B" history-substring-search-down
```
These are compared when I run `bindkey` separately in two different terminals, but if I use `opendiff /tmp/bindkey-debug*` , the comparisons are equal
![image](https://user-images.githubusercontent.com/58351018/152630311-b43afff0-20e0-4eab-a884-c0b8a98c8504.png)
![code](https://user-images.githubusercontent.com/58351018/152630365-7a04e21f-39ee-4286-b617-224b12bc4052.png)

**Comment by mcornella** [comment]
You confuse the terms `up` / `down` with `backward` / `forward`. The proper widgets use `up` / `down` terms.

This should be easily set up by the `history-substring-search` plugin, so you can enable that by adding `history-substring-search` to the `plugins` array in your zshrc file. **After that you don't need to add any `bindkey` lines to the zshrc file**, so you can remove those.

Let me know if after this change you get everything working again.

**Comment by Jamesxwq** [comment]
`history-substring-search` is already in the` plugins `array, but verified nothing changes that if I remove the
```
 bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down 
```

I just tried adding` bindkey > /tmp/bindkey-debug-1` at the end of .zshrc, and then entering the `bindkey` command in a new terminal, the content in the file `bindkey-debug-1` is different from what I get by typing `bindkey` , it feels like` bindkey` gets reset after executing `~/.zshrc` when starting zsh, I'm confused.

**Comment by Lin-Guanguo** [comment]
I may have the same problem.
[fzf](https://github.com/junegunn/fzf) will register the hotkeys ctrl-R and ctlr-T. ctrl-T is work, but ctrl-R only works after I source ~/.zshrc explicitly.

**Comment by cmdjulian** [comment]
I'm also facing the same issue with `atuin`, as `ctrl+r` is not registered :(

**Comment by djmango** [comment]
Facing the same problem with navi and history-substring-search

**Comment by mcornella** [comment]
If this is still happening for someone, please create a trace of the zsh session as follows:

1. Run `zsh -lxv 2> >(tee ~/omz-debug.log &>/dev/null)`
2. Check that the binding is not working
3. Run `source ~/.zshrc` and check that the binding is working
4. Run `exit` or <kbd>CTRL-D</kbd>
5. Send the `omz-debug.log` to logs@ohmyz.sh for our inspection.

**Comment by ShinyZero0** [comment]
I have the same problem but not with OMZ.
I have this in my .zshrc:
```
zinit load zsh-users/zsh-history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
```
but keybinds don't work until i source .zshrc or just copy bindkey lines into shell

**Comment by mcornella** [comment]
This is impossible to debug without more information. Please follow https://github.com/ohmyzsh/ohmyzsh/issues/10599#issuecomment-1406944719.

**Comment by ShinyZero0** [comment]
Maybe not for everyone, but for me issue was with [this vi mode plugin](https://github.com/jeffreytse/zsh-vi-mode#execute-extra-commands)
It overwrites the keybindings so you have to run it before defining any keybindings

**Comment by mcornella** [comment]
It is very likely that the same is happening for everyone else with this or similar plugins.

I'll close this but feel free to reply if it's still happening and post your zshrc file so we can try to reproduce it.

**Comment by mcornella** [comment]
BTW

**Comment by mcornella** [comment]
BTW for the specific case of `vi-mode`, you can define your key bindings for all 3 different keymaps as follows:
```sh
bindkey -M emacs '^[[A' history-substring-search-up
bindkey -M viins '^[[A' history-substring-search-up
bindkey -M vicmd '^[[A' history-substring-search-up

bindkey -M emacs '^[[B' history-substring-search-down
bindkey -M viins '^[[B' history-substring-search-down
bindkey -M vicmd '^[[B' history-substring-search-down
```

**Comment by kamillentee** [comment]
The vi-mode was indeed causing it for me. I temporary removed
`bindkey -v`
and all the other keybindings were working again. 

So as written above you can use vi-mode but it needs to be run at the beginning of the .zshrc

**Comment by OPLIKATO** [comment]
Same problem when I use tcsh and this method works for me. 
I found that when I used ^[[A, .cshrc wont work automatically, but other keys like ESC(^[) worked well.  I guess this problem is associated with ASIIC detecting. 
There is an option in csh,
`-k  "key is interpreted as a symbolic arrow key name, which may be one of 'down', 'up', 'left' or 'right'."`
and finally it works with
`bindkey -k down history-search-forward`
Hope this helps

**Comment by mcornella** [comment]
This is not relevant for Oh My Zsh, which uses zsh not tcsh. Either way someone could somehow get here looking for that, so thanks for sharing.

**Comment by A-ElMahmi** [comment]
Thank you @mcornella,

This fixed it for me:
```
bindkey -M viins '^[[A' history-substring-search-up
```

I spent hours trying to debug this, all I was missing was `-M viins`

**Comment by bmoeskau** [comment]
I was having this issue and ran across this thread. FYI, for me it only works if I bind keys AFTER sourcing OMZ.

Does not work:
```
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

source $ZSH/oh-my-zsh.sh
```

Works:
```
source $ZSH/oh-my-zsh.sh

bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
```

I have no idea why, and YMMV.

**Comment by rwmitchell** [comment]
I'm not sure if it is still true, quit using OMZ some time ago because of this.  lib/key-bindings.zsh has a 'bind key -e' line that resets keybindings to emacs.

**Comment by svenjacobs** [comment]
Found this issue because I had the same problem with [zsh-vi-mode](https://github.com/jeffreytse/zsh-vi-mode) and [Atuin](https://github.com/atuinsh/atuin), where Atuin's `^R` shortcut was overwritten by vi-mode.

Calling `bindkey '^R' atuin-search` in my `.zshrc` didn't help because by default vi-mode's shortcuts are bound [lazily](https://github.com/jeffreytse/zsh-vi-mode?tab=readme-ov-file#lazy-keybindings), so after custom and Antuin's bindings.

Since I use [zinit](https://github.com/zdharma-continuum/zinit) my solution was to delay loading the `atuin` plugin

```zsh
zinit light jeffreytse/zsh-vi-mode
zinit ice wait silent; zinit light atuinsh/atuin
```

Another solution would maybe be to disable vi-mode's lazy keybindings via `ZVM_LAZY_KEYBINDINGS=false`.

**Comment by dkaszews** [comment]
I'm not even using Oh My Zsh, but posting since this is one of the top results searching for similar issues.

I have found that the issue is running `set -o vi`, which resets the `bindkey` commands I use to fix some of the keys not working as expected. Moving `set -o vi` to the top fixes the issue.
