### ISSUE TITLE
Rocky Linux with agnoster theme, remnant characters when tab completing

### ISSUE THREAD

**Issue by Charles94jp** [ohmyzsh/ohmyzsh#10598]
### Describe the bug

Hi, I have installed ohmyzsh from GitHub on rocky linux 8.5 and when I use the tab key to complete, the first character is repeated.
For example, if I type in:

```
~ sys
```

then tab, it turns to

```
~ ssys
sysctl                          systemd-cgtop                   systemd-resolve               
syserror                        systemd-delta                   systemd-run      
...
```
And the first 's' cannot be deleted by backspace.
The ssh software I use is Xshell on Windows.
When I use CentOS 7, this bug does not appear.
It seems to be a problem with agnoster theme under rocky linux, using robbyrussell theme did not find this bug.
I have searched for such issues and configured them.
https://stackoverflow.com/questions/19305291/remnant-characters-when-tab-completing-with-zsh
Here is my .zshrc file.
```
export TERM=xterm-256color
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LANG_ALL="en_US.UTF-8"
ZSH_THEME="agnoster"
...
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)
```
/etc/locale.conf file
```
LANG="en_US.UTF-8"
```
And I have installed the powerline-fonts
```
dnf -y install powerline-fonts
```
Kindly help.

### Steps to reproduce

For example, if I type in:

```
~ sys
```

then tab, it turns to

```
~ ssys
sysctl                          systemd-cgtop                   systemd-resolve               
syserror                        systemd-delta                   systemd-run      
...
```
And the first 's' cannot be deleted by backspace.

### Expected behavior

if I type in:
```
~ sys
```

then tab, it turns to

```
~ sys
sysctl                          systemd-cgtop                   systemd-resolve               
syserror                        systemd-delta                   systemd-run      
...
```

### OS / Linux distribution

Rocky Linux 8.5

### Zsh version

5.5.1

### Oh My Zsh version

master (22c11da)

### Terminal emulator

Xshell on win10

**Comment by Charles94jp** [comment]
On other themes: `cloud` was also found to have this problem, while `arrow` did not.

**Comment by mcornella** [comment]
See https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command

**Comment by Charles94jp** [comment]
> See https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command

Thanks. I'm afraid this is not valid for my situation.
But I found my way to fix it :
Modify the last line of the `.oh-my-zsh/themes/agnoster.zsh-theme` file 
```
PROMPT='%{%f%b%k%}$(build_prompt) '
```
to 
```
PROMPT='%{%f%b%k%}$(build_prompt)%{ %}'
```
It works. \\(@^0^@)/

**Comment by zazitufu** [comment]
> > See https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command
> 
> Thanks. I'm afraid this is not valid for my situation. But I found my way to fix it : Modify the last line of the `.oh-my-zsh/themes/agnoster.zsh-theme` file
> 
> ```
> PROMPT='%{%f%b%k%}$(build_prompt) '
> ```
> 
> to
> 
> ```
> PROMPT='%{%f%b%k%}$(build_prompt)%{ %}'
> ```
> 
> It works. \(@^0^@)/

Your method works for my case, none of the methods described by others works.
My os : debian10~debian12.
Thank you very much!
