### ISSUE TITLE
SSH autocomplete terribly slow 

### ISSUE THREAD

**Issue by jondoe1337** [ohmyzsh/ohmyzsh#10592]
### Describe the bug

I know this behaviour has been reported a numerous times but I', not sure if mine is related to the config of the other reports - anyway: 
I have a not that complex ssh config, but when typing ssh/scp and a first letter then hitting tab it takes 4-5s to complete, which is imho unusable. 

### Steps to reproduce

1. `ssh a`
2. hit tab
3. wait...

My zshrc looks like this:

```
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
export NVM_LAZY_LOAD=true
export NVM_COMPLETION=true
plugins=(git zsh-syntax-highlighting docker zsh-nvm npm docker-compose evalcache)
source $ZSH/oh-my-zsh.sh
_evalcache rbenv init -
zstyle ':completion:*' hosts off
```
Had the powerlevel10k theme and changed that to the default one, which resulted in no change. Just commenting out the oh-my-zsh.sh helps :( 

### Expected behavior

Completion should be done within a blink of an eye

### OS / Linux distribution

macOS 12.1

### Zsh version

5.8

### Oh My Zsh version

master (1e27755)

### Terminal emulator

iTerm2

### Additional context

My ssh config is fairly simple:

```
➜  .ssh cat config
Include ~/.ssh/conf.d/*
```

I have 4 files in `conf.d` which have all Host / Hostname configurations. The overall number of HostName entries is 296. 
All configurations are flat, except one file which has the following pattern:

```
Host node-1
    node-1.fqdn.com

Host node-2
    node-2.fqdn.com

Host node-3
    node-3.fqdn.com

Host node-n
    node-n.fqdn.com

Host node-1 node-2 node-3 ... node-N
    User me
    Port 1234
```

**Comment by carlosala** [comment]
I tried your config, and for me is working with my setup. When I try to use your setup (this one with `conf.d` the `ssh` command doesn't autocomplete anything.
I will try to investigate a little bit further, let's see if we can manage to resolve it :)

**Comment by carlosala** [comment]
By the way, I see that the `_ssh` function is defined in system-wide way, ohmyzsh does not define nor change that function.

**Comment by jondoe1337** [comment]
> By the way, I see that the _ssh function is defined in system-wide way, ohmyzsh does not define nor change that function.

Confused what you mean by that. 🤔 

Don't get me wrong - the completion works entirely. It's just very slow.

**Comment by carlosala** [comment]
> > By the way, I see that the _ssh function is defined in system-wide way, ohmyzsh does not define nor change that function.
> 
> Confused what you mean by that. 🤔 
> 
> Don't get me wrong - the completion works entirely. It's just very slow.
> 

I'm just saying that the `ssh` completion is not defined by Oh My Zsh.

**Comment by jondoe1337** [comment]
> I'm just saying that the `ssh` completion is not defined by Oh My Zsh.

I read about that - the thing is that if I comment out `source $ZSH/oh-my-zsh.sh` then the ssh autocompletion is not working. That's why I thought that it must have some connection to Oh My Zsh.

**Comment by jondoe1337** [comment]
Okay this is strange - after I added that completion snippet:

```
h=()
if [[ -r ~/.ssh/config ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/config)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ -r ~/.ssh/conf.d/one ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/conf.d/one)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ -r ~/.ssh/conf.d/two ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/conf.d/two)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ -r ~/.ssh/conf.d/three ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/conf.d/three)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ -r ~/.ssh/conf.d/four ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/conf.d/four)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ $#h -gt 0 ]]; then
  zstyle ':completion:*:ssh:*' hosts $h
  zstyle ':completion:*:scp:*' hosts $h
fi
```

Everything works.

I also removed that host pattern in that one file (I mentioned in my first comment) and added the config to each Host/HostName. That caused to show weird autocompletion.

**Comment by jondoe1337** [comment]
Gonna slightly revert my solution - if I autocomplete a host that is contained in file `one`, then it will be fast - if it is in `four` it will slow down (also CPU usage goes up for that time range).

**Comment by carlosala** [comment]
> I read about that - the thing is that if I comment out `source $ZSH/oh-my-zsh.sh` then the ssh autocompletion is not working. That's why I thought that it must have some connection to Oh My Zsh.

This happens because `zsh` doesn't load completion as a default. If you add `autoload -U compinit && compinit` to your `.zshrc` (instead of sourcing `.oh-my-zsh.sh`, that does this in a more sophisticated way) you'll have it.
If the performance is the same than sourcing ohmyzsh, then the issue will not be related to ohmyzsh and will be related to the `ssh` completion.

**Comment by jondoe1337** [comment]
Okay understood @carlosala . Tested it and looks like it is not related to ohmyzsh. 👍  

Is there any further documention from ohmyzsh to dive into the compinit sophisticated initalization?

**Comment by carlosala** [comment]
> Okay understood @carlosala . Tested it and looks like it is not related to ohmyzsh. +1
> 
> Is there any further documention from ohmyzsh to dive into the compinit sophisticated initalization?

Sure! You can look in the [`.oh-my-zsh.sh` part](https://github.com/ohmyzsh/ohmyzsh/blob/4f2d8b4d4cbc51e609f4b568e87907883422ab41/oh-my-zsh.sh#L106) that initializes the completion. You will see many functions that maybe you don't understand, in `man zshcompsys` you will get the answers!
Basically the `.zcompdump` file is the angular basis of the completion, and the `compinit` function to load the completions defined in the `.zcompdump` file. I don't know so much about it, but it's really interesting :)

**Comment by jondoe1337** [comment]
Thx for the hint! 👍

**Comment by simonryf** [comment]
I had the same issue. Thx to the hint from @jondoe1337 I adapted my snippet so it supports spaces in the Host line, because I use often aliases in my ssh config:

E.g. I have (besides others): ~/.ssh/config.d/bla.ssh

```
Host relay relay.a relay.lab.site-a.axision.ch
    User bla
    Hostname relay.lab.site-a.axision.ch
    
Host relay.b relay.lab.site-b.axision.ch
    User bla
    Hostname relay.lab.site-b.axision.ch
```

And I put below in my ~/.zshrc before the autoload cmd (but I guess it doesn't matter?)


```zsh
# ---------------------- ssh auto completion --------------------------------
for file in ~/.ssh/config ~/.ssh/config.d/*.ssh; do
    ssh_hosts=(${${(@s: :)${(@M)${(f)"$(< $file)"}:#Host *}#Host }:#*[*?]*})
done
zstyle ':completion:*:(ssh|scp|rysnc):*' hosts $ssh_hosts
```
