### ISSUE TITLE
Implement wd - to replicate the git checkout - behavior but with warp points 

### ISSUE THREAD

**Issue by SimonGodefroid** [ohmyzsh/ohmyzsh#10593]
### If the feature request is for a plugin or theme, specify it here.

Warp points improvement

### If the feature solves a problem you have, specify it here.

I work mainly with 2 repos for which I have 2 warp points: `api` and `front`

I will often go from api to front.

```
$ wd api
```

Do stuff...

```
$ wd front
```

### Describe the proposed feature.

Doing so in git, by switching from branch a to branch a-1 I would do 
```
$ git checkout -
```
to move between two branches.
```
$ wd - 
```
Could behave by retrieving the -1 latest wd command in the history and execute it.

### Describe alternatives you've considered

Up arrow twice :)

**Comment by mcornella** [comment]
Hi! The `wd` plugin is a bundle of the upstream project, https://github.com/mfaerevaag/wd. You should post your feature request there. Thanks!

**Comment by mcornella** [comment]
BTW I think if they're the last directory, you can also `cd -` or just run `-` since it is aliased to `cd -` by OMZ.
