### ISSUE TITLE
PS1 branch name not updated

### ISSUE THREAD

**Issue by Mediashare** [ohmyzsh/ohmyzsh#10607]
### Describe the bug

When I'm on my git project and I'm working on a specific branch (`task#51526/endpoints_examples`), after I commit and push my branch and I change branch: my PS1 doesn't update. I have to restart zsh.

### Steps to reproduce

1. git checkout -b task#51526/endpoints_examples
2. touch exemple.md << "# Hello world"
3. git add . 
4. git commit -am "zsh branch update"
5. git push
6. git checkout main

### Expected behavior

My branch name in PS1 should update.

### OS / Linux distribution

ArchLinux, Manjaro

### Zsh version

5.8

### Terminal emulator

Terminal

**Comment by mcornella** [comment]
What theme are you using?
