### ISSUE TITLE
compinit:141: parse error: condition expected: $1

### ISSUE THREAD

**Issue by jrp2014** [ohmyzsh/ohmyzsh#10611]
### Describe the bug

The message `compinit:141: parse error: condition expected: $1` appears (twice) when starting a new shell.

```zsh
echo $SHELL
$(echo $SHELL) --version
echo $ZSH_VERSION
/bin/zsh
zsh 5.8 (x86_64-apple-darwin21.0)
5.8
```

### Steps to reproduce

1. Start new shell
2. See 

```zsh
Last login: Sun Jan 23 10:54:18 on ttys001
compinit:141: parse error: condition expected: $1
compinit:141: parse error: condition expected: $1
```

### Expected behavior

No error messages.

### OS / Linux distribution

MacOS 12.1 

### Zsh version

5.8

### Terminal emulator

terminal

**Comment by carlosala** [comment]
could you post here your `.zshrc`?

**Comment by mcornella** [comment]
You can also run zsh in xtrace mode and post the output of that. Run
```sh
zsh -xvic exit &>~/omz-debug.log
```
and post the `omz-debug.log` file or send it at <marc@ohmyz.sh> if you're more comfortable with that.

**Comment by jrp2014** [comment]
```zsh
❯ cat ~/.zshrc
export PATH="/usr/local/opt/sphinx-doc/bin:$PATH"

if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
fi
eval "$(starship init zsh)"
``
[omz-debug.log](https://github.com/ohmyzsh/ohmyzsh/files/7928550/omz-debug.log)
`

**Comment by mcornella** [comment]
> ```zsh
> ❯ cat ~/.zshrc
> export PATH="/usr/local/opt/sphinx-doc/bin:$PATH"
> 
> if type brew &>/dev/null; then
>     FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
> 
>     autoload -Uz compinit
>     compinit
> fi
> eval "$(starship init zsh)"
> ```
> omz-debug.log

The error doesn't appear in the generated log file and you don't seem to be using Oh My Zsh.

**Comment by jrp2014** [comment]
Thanks.  How curious.  I used to have it installed!  Sorry to waste your time.

**Comment by mcornella** [comment]
It would be nice to know the reason behind this. This error is not documented anywhere when doing a google search, so feel free to reopen.

If you can still trigger the error, perhaps add `-T` to the `autoload -Uz compinit` call in your zshrc file so you only get a trace of the compinit function:

```shell
export PATH="/usr/local/opt/sphinx-doc/bin:$PATH"

if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz -T compinit
    compinit
fi
eval "$(starship init zsh)"
```

**Comment by jrp2014** [comment]
This is what I get with the above .zshc
```
Last login: Sun Jan 23 10:54:18 on ttys002
compinit:141: parse error: condition expected: $1
compinit:141: parse error: condition expected: $1
```

**Comment by mcornella** [comment]
Ok, what do you get with this:
```
autoload -Uz +X compinit
which compinit
```

If that still fails, you can try to copy the compinit file and paste it here with
```
clipcopy ${^fpath}/compinit(N)
```

**Comment by mcornella** [comment]
ping @jrp2014

**Comment by danielsitnik** [comment]
I'm experiencing a slightly different error here:
```
Last login: Mon Jan 31 15:34:25 on ttys004
/Users/daniel.sitnik/.oh-my-zsh/oh-my-zsh.sh:155: parse error near `<<<'
```

There were no changes to `.zshrc`, this started after I ran `omz update`, and now everytime I run it I get:
```
daniel.sitnik@AMAC02WJ2RFG8WN ~ % omz update
oh-my-zsh.sh: needs merge
error: you need to resolve your current index first
```

**Comment by mcornella** [comment]
That's totally different, you have a merge conflict in `oh-my-zsh.sh` probably because you modified it first and it conflicted with the recent changes made. See https://github.com/ohmyzsh/ohmyzsh/issues/10281#issuecomment-939856460.
