### ISSUE TITLE
Postgres plugin: uses wrong Homebrew location for Apple Silicon

### ISSUE THREAD

**Issue by naxels** [ohmyzsh/ohmyzsh#10612]
### Describe the bug

Homebrew on Apple Silicon is by default installed into `/opt/homebrew`, while the plugin uses the Intel location.
https://docs.brew.sh/Installation

This causes almost all PostgreSQL aliases to fail on Apple Silicon as the now default initialized location for a new database is:
`initdb --locale=C -E UTF-8 /opt/homebrew/var/postgres`

Maybe it's possible to support both? or create a intel/silicon plugin version?

Thank you for the great work :)

### Steps to reproduce

**On Apple Silicon Mac, install Homebrew + Oh My Zsh**

Enable plugin postgres
Reload terminal/.zshrc file
Execute: `startpost`

### Expected behavior

I expect the PostgreSQL database to start, however get this message:

`pg_ctl: directory "/usr/local/var/postgres" does not exist`

### OS / Linux distribution

macOS 12.1

### Zsh version

5.8

### Terminal emulator

iTerm2

### Additional context

postgres plugin

**Comment by carlosala** [comment]
sure, I'm going to do a PR now to resolve it.
Thanks for the report!

**Comment by naxels** [comment]
Awesome! Thanks :)

**Comment by carlosala** [comment]
sure! Thanks!
