### ISSUE TITLE
Can't update oh-my-zsh

### ISSUE THREAD

**Issue by Eyal159** [ohmyzsh/ohmyzsh#10620]
### Describe the bug

Having problems updating oh-my-zsh, adding screenshoot (not much experience using oh-my-zsh)

![Screen Shot 2022-01-25 at 12 15 22](https://user-images.githubusercontent.com/74238936/150957701-9a179d46-b11d-4e32-bcbf-a4e1e9004aed.png)
 

### Steps to reproduce

Hard time to explain, but choose to update oh-my-zsh  ?

### Expected behavior

I expect it to be updated ( worked before)

### OS / Linux distribution

macOS 11.5.2

### Zsh version

5.8

### Oh My Zsh version

master (c6e7f890)

### Terminal emulator

ITerm

**Comment by mcornella** [comment]
Did you make any changes to README? Or maybe there was a conflict?
Run this and post the output:
```sh
cd "$ZSH"; git status -sb; git diff HEAD
```

**Comment by srikrsna** [comment]
I have the same issue, here's my output,
```
## master...origin/master
UU oh-my-zsh.sh
diff --git a/oh-my-zsh.sh b/oh-my-zsh.sh
index ab32ee9d..835ebeba 100644
--- a/oh-my-zsh.sh
+++ b/oh-my-zsh.sh
@@ -64,7 +64,11 @@ fi
 # Initializes Oh My Zsh
 
 # add a function path
+<<<<<<< Updated upstream
 fpath=("$ZSH/functions" "$ZSH/completions" $fpath)
+=======
+fpath=($ZSH/functions $ZSH/completions /opt/homebrew/share/zsh/site-functions $fpath)
+>>>>>>> Stashed changes
 
 # Load all stock functions (from $fpath files) called below.
 autoload -U compaudit compinit
```

**Comment by Eyal159** [comment]
> 

For some reason i saw a lot of diff..just went with `git reset plugins/nvm/README.md` and it seems to be ok
Thanks !

**Comment by srikrsna** [comment]
I've also done the same it works for me now. Thanks!
