### ISSUE TITLE
[Feature Request] support for dolt. Could that be a feature-plugin-theme (?)

### ISSUE THREAD

**Issue by camilogarciabotero** [ohmyzsh/ohmyzsh#10632]
### Discussed in https://github.com/ohmyzsh/ohmyzsh/discussions/10631

<div type='discussions-op-text'>

<sup>Originally posted by **camilogarciabotero** January 27, 2022</sup>
Hi all,

Thanks for working and maintaining ohmyzsh! I was wondering if there is any support (plugin) or theme that supports information from [dolt](https://github.com/dolthub/dolt). I was thinking about something like the theme supporting git information (like the agnoster theme) or a plugin that helps autocomplete.

Thanks.</div>

**Comment by mcornella** [comment]
Hi Camilo, can you create a proper feature request issue? It's a suggested option in https://github.com/ohmyzsh/ohmyzsh/issues/new/choose.
