### ISSUE TITLE
docker-compose plugin service names only if container exists ?

### ISSUE THREAD

**Issue by adamwojt** [ohmyzsh/ohmyzsh#10636]
### Describe the bug

with:
- `docker-compose up <tab>`
- `docker-compose run <tab>`

There seem to be no autocomplete without services actually running (after `docker-compose up`). Is that how the autocomplete is suppose to work? Sometimes it's needed to get autocomplete for services when nothing is actually running so that for example one could choose which services to `up`.

### Steps to reproduce

`docker-compose run <tab>` without any services running.

### Expected behavior

`docker-compose run/up <tab>` without services running should autocomplete services.

### OS / Linux distribution

Linux adam-work 5.15.13-arch1-1 #1 SMP PREEMPT Wed, 05 Jan 2022 16:20:59 +0000 x86_64 GNU/Linux

### Zsh version

zsh 5.8 (x86_64-pc-linux-gnu)

### Terminal emulator

kitty 0.24.1 created by Kovid Goyal

### Additional context

- Docker Compose version 2.2.3
- omz at commit 11a87eac
- Docker version 20.10.12, build e91ed5707e

**Comment by adamwojt** [comment]
Seems that taking [this approach](https://github.com/brgmnn/fish-docker-compose/blob/44a9a5ad593f05ac77e4c5024cfe4a8c55db31e3/completions/docker-compose.fish#L42) fixed it for me.

https://github.com/ohmyzsh/ohmyzsh/blob/11a87eac47c579366620f995330532f47dc651f2/plugins/docker-compose/_docker-compose#L26

-> `__docker-compose_q config --services "$@" \`

**Comment by mcornella** [comment]
We bundled [the upstream completion](https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose), but it looks like [they removed it in v2 and it's still not ready](https://github.com/docker/compose/issues/8550). That is all to say that I'm ok with a unilateral change, as long as it doesn't introduce breaking changes.

Are you willing to make a PR?

**Comment by adamwojt** [comment]
> We bundled [the upstream completion](https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose), but it looks like [they removed it in v2 and it's still not ready](https://github.com/docker/compose/issues/8550). That is all to say that I'm ok with a unilateral change, as long as it doesn't introduce breaking changes.
> 
> Are you willing to make a PR?

@mcornella I could but it's not as easy as it looks actually. Having had second look on this we have some parts that rely on `ps --filter`, for example:

https://github.com/ohmyzsh/ohmyzsh/blob/11a87eac47c579366620f995330532f47dc651f2/plugins/docker-compose/_docker-compose#L122
https://github.com/ohmyzsh/ohmyzsh/blob/11a87eac47c579366620f995330532f47dc651f2/plugins/docker-compose/_docker-compose#L40-L44

Which is impossible to filter with `config` but in current situation it would not complete properly anyway if services don't have their container. Also I've noticed that for v2.2.3 compose doesn't have filtering on `ps` via `source=build` anyway. 
```
$ docker-compose ps --services --filter source=build
> not implemented
```

So I could make PR but we need to decide if we want to go [this direction](https://github.com/brgmnn/fish-docker-compose/blob/44a9a5ad593f05ac77e4c5024cfe4a8c55db31e3/completions/docker-compose.fish#L92-L96) where all service based completion is taken from `docker-compose config --services` solely. I personally think this is way to go.

**Comment by adamwojt** [comment]
@mcornella Submitted what worked for me: https://github.com/ohmyzsh/ohmyzsh/pull/10638

**Comment by HanKruiger** [comment]
A downside of only use the services from `docker-compose config --services` for certain commands is that for people who like to chain commands it is not possible to autocomplete. Example:

```zsh
docker-compose down && docker-compose up --build -d && docker-compose logs -f service-1
```

For the final part, I would be unable to auto-complete it, because at the moment of writing the command, the service `service-1` will not be up yet.

Is it possible to change this behaviour with configuration?

**Comment by adamwojt** [comment]
> A downside of only use the services from `docker-compose config --services` for certain commands is that for people who like to chain commands it is not possible to autocomplete. Example:
> 
> ```shell
> docker-compose down && docker-compose up --build -d && docker-compose logs -f service-1
> ```
> 
> For the final part, I would be unable to auto-complete it, because at the moment of writing the command, the service `service-1` will not be up yet.
> 
> Is it possible to change this behaviour with configuration?

This is not true. Even if using `docker-compose config --services` you would get autocomplete for all services in the file. Have a look on my PR, I describe how I resolved this. 
Also in your presented situation, exactly in current state of the plugin you would not get autocomplete as it is taken from `docker-compose ps` which need to have container created. Maybe you mixed `ps` with `config` ?

**Comment by HanKruiger** [comment]
Apologies if I'm misunderstanding, but in your description, it says:

> * for `build`, `create`, `images`, `pull`, `push`, `run`, `up` take services using `docker-compose config --services` (parses file), for rest: take it from `docker-compose  ps --services` (have to have container).

This list does not include the `logs` command, so I assumed it still uses `docker-compose  ps --services`.

**Comment by mcornella** [comment]
Doing cleanup of old issues. I disagree with my previous statement that we could fix this on our side. Let's continue the conversation on the upstream project.
