### ISSUE TITLE
Infinite recursion when setting theme

### ISSUE THREAD

**Issue by OliveThePuffin** [ohmyzsh/ohmyzsh#10643]
### Describe the bug

I'm not sure if this is a bug worth fixing, but I'll post it here in case anyone else comes across it.
I'd also gladly make a pull request to fix it if needed.

The bug happens with the command `omz theme set [theme]` being run inside of a script. Specifically, this is caused by line 737 in the file `lib/cli.zsh` where omz restarts the shell causing the script to run from the start and loop infinitely. I understand that that line basically is used to load the new theme, but restarting the shell is really only permissible when running on the terminal directly.

I've fixed this in my script using a hacky workaround that prevents this sort of recursion:
```
#!/bin/zsh

# Check if this has been run before
# to prevent infinite recursion
if [[ count -gt 0 ]]
then
    echo "[COMPLETE] Theme set!"
    exit 0
fi
export count=$(expr $count + 1)

# source needed files
source /usr/share/oh-my-zsh/zshrc

# Set the theme
omz theme set fino &

# Commands from this point on will run
```

### Steps to reproduce

Run the following in a script:

```
#!/bin/zsh

source /usr/share/oh-my-zsh/zshrc

omz theme set fino

# Commands from this point on will not run
```

Though it holds true for any theme being set

### Expected behavior

Expected behavior: The script runs once without any looping

### OS / Linux distribution

Artix Linux

### Zsh version

5.6

### Terminal emulator

urxvt

**Comment by carlosala** [comment]
Thanks for the report! Would be great to fix it, sure! I really don't know how to do it, maybe @mcornella would help more than I can. Would be great to detect if the shell where's running the command is an interactive shell or not, and act in consequence. It's just an idea, I don't know if this is possible ;)

**Comment by mcornella** [comment]
Hi @OliveThePuffin, thanks for the bug report. The `omz` CLI is supposed to be used interactively in your own shell, but it does look like this would be a good feature to have.

At the moment it's difficult to use in a script because it's a function, but in the meantime I could add a check for whether the script is run in an interactive session or not.

**Comment by mcornella** [comment]
See https://github.com/ohmyzsh/ohmyzsh/pull/10645. You can test it with `omz pr test 10645`.

**Comment by OliveThePuffin** [comment]
Yes, this change seems to have fixed the issue
