### ISSUE TITLE
fixperms messes with execution permission

### ISSUE THREAD

**Issue by ghost** [ohmyzsh/ohmyzsh#10648]
### Describe the bug

`fixperms` has messed up the execution permissions of all my files. Now I have to go one by one adding the permission back again.

### Expected behavior

There is no description telling me that this is going to mess the execution permissions. I was expecting it to change only the write permissions for the group and others.

This is what I was expecting:
```
# Fixes permissions for files and directories in the given folder or the current folder
fixperms() {
  find "${1:-.}" -type f -executable -exec chmod 744 {} \;
  find "${1:-.}" -type f ! -executable -exec chmod 644 {} \;
  find "${1:-.}" -type d -exec chmod 755 {} \;
}
```

**Comment by carlosala** [comment]
It's well explained in the plugin I think, `fixperms` is a wrapper around `set755`, that changes recursively all the permissions of directories to `755` and `set644`, that changes recursively all the permissions of regular files to `644`, what is read and write for user and only read for group and others.

**Comment by rwmitchell** [comment]
I beg your pardon?  go-w will have no effect on the execute bit of subfolders:

<img width="675" alt="image" src="https://user-images.githubusercontent.com/15944841/152571360-be791996-80b1-4a61-ac4e-dbebe8c19fa7.png">

**Comment by rwmitchell** [comment]
> At the end there are multiple possible implementations to solve one problem, I feel current one is correct.

How is an 82 line custom function using both 'find' and 'chmod' better than just using chmod directly?

**Comment by carlosala** [comment]
> I beg your pardon? go-w will have no effect on the execute bit of subfolders:
> 
> <img alt="image" width="675" src="https://user-images.githubusercontent.com/15944841/152571360-be791996-80b1-4a61-ac4e-dbebe8c19fa7.png">

sorry, I misunderstood your previos message

**Comment by rwmitchell** [comment]
So, as it is 'fixperms' that removes the execute bit on files, it seems to do more harm than good.  None of the programs I've used on unix have incorrectly applied the execute bit, especially when properly setting umask.

What purpose does this function solve that isn't already easily done with a single unix command that has existed forever?

**Comment by rwmitchell** [comment]
If you can't explain what makes an 82 line special script better than a simple standard unix command, then it should  removed from omz.   Code deleted is code debugged.

If you can explain what makes it better, then that should be in the readme file to better explain its purpose.

The name 'fixperms' is rather misleading.  It can't possible know how I want the permissions to be to know how to "fix" them.  The name over promises something it can only get right in a very narrow set of conditions and it does so recursively through all the files and directories below the current location - that is very dangerous!

As I said before, I suspect this was written to fix permissions after copying files from a microsoft formatted media - in which case, change the name to indicate that very narrow purpose.

**Comment by carlosala** [comment]
At the end it's an advanced plugin, it should not be used without any knowledge. I think it's useful, and being optional, looks that it's not going to be removed.

**Comment by rwmitchell** [comment]
if it is advanced, what does it do that can be done without just using chmod -R ?

**Comment by carlosala** [comment]
There are many things in OMZ that can be done with one easy command, such as aliases or many functions, but the idea is that being optional you can have it or not, it's your choice. I'm sure that many people use that function, so if it doesn't cause problems, let's let it there!

**Comment by rwmitchell** [comment]
So you can't answer the question or justify why there is an 82 line script that doesn't do anything useful except wave your hands.  got it.

**Comment by rwmitchell** [comment]
> I'm sure that many people use that function

How are you sure?  Is OMZ recording and sending telemetry data back so you can tell who does what?

Or you just blowing smoke?

**Comment by carlosala** [comment]
> > I'm sure that many people use that function
> 
> How are you sure?  Is OMZ recording and sending telemetry data back so you can tell who does what?
> 
> Or you just blowing smoke?
> 

I think that you are being impolite with me. I'm trying to explain you that `perms` is a plugin and if you don't like it, just don't use it.

**Comment by rwmitchell** [comment]
I don't think you've ever answered a single question that I've asked.

I don't use perms - wouldn't touch it.  But someone else did, which is what started this thread.  Now, we can laugh at the Noob for being so foolish as to run fixperms without looking into the code itself to verify what it is doing, or we can look to see if there is an actual problem.

The README.md does NOT specifically state it'll be removing the execute bits from all programs but only speaks in "strange" octal numbers that most new users are not going to understand the implications of.  I'm not sure you do.  In fact, it merely states:

```Plugin to handle some unix filesystem permissions quickly.```

What version of unix is anyone using that is trashing file permissions that need to be "fixed"????

The name "fixperms" suggests it is fixing something, making it better.  Removing write permissions from group and other is usually a good and safe thing.  Removing the execute bit, not so much.  In fact, I can't think of whenever I'd want to do this, except in the case of copying files from Microsoft media.  An easy fix is to change the name, to make it more obvious this is a special use case and not something to run just to to "fix" things.  It could be called: fixmsperms or msfixperms.

Alternatively, redo it as a simple alias: ```alias -- fixperms='chmod -R go-w'

What is there now is bad, dangerous, and needs to be fixed.  Do you not ever fix existing  issues to make things better or do you just double down on justifying why the crap is there?

**Comment by mcornella** [comment]
I believe the function was there to fix cases where a folder is used from a non-UNIX share, like when copying a folder from a Windows directory. In that case the permissions are all at 777, so just using `chmod -R go-w` doesn't fix the execution bits on regular files.

I do agree that the function is poorly named and it's not properly documented when run, though the README kinda clearly says that it will use `set755` on folders and `set644` on files.

I think a rename and a clearer message when asking for confirmation are enough to keep the feature.

**Comment by rwmitchell** [comment]
> I believe the function was there to fix cases where a folder is used from a non-UNIX share, like when copying a folder from a Windows directory. In that case the permissions are all at 777, so just using `chmod -R go-w` doesn't fix the execution bits on regular files.

That's what I said and recommended renaming it msfixperms as that also removes it out of the fix[TAB] namespace.

> I do agree that the function is poorly named and it's not properly documented when run, though the README kinda clearly says that it will use `set755` on folders and `set644` on files.

You honestly believe someone new is going to understand the implications of 755 and 644 while also asking how to set their directory path?  

> I think a rename and a clearer message when asking for confirmation are enough to keep the feature.

Adding a fixperms aliased to chmod og-w would be generically useful and unlikely to harm anyone in the home single user environment.  The current fixperms is very dangerous except in the single use case of fixing files copied from an OS that lacks even the bare basics of user security.

**Comment by rwmitchell** [comment]
The current warning message is idiotic:

```echo "Fixing perms on $target?"
  printf '%s' "Proceed? (y|n) "```

The person just ran a command to "fix" permissions - of course they want to do it, whatever that it is.  It didn't do any checks and doesn't report what bad things might happen if they continue.

Compare that to "rm".  rm normally does what you ask without question, unless you accidentally type: "rm junk *" instead of "rm junk*"; then it asks "you are sure you want to delete everything?"(sic)

Always prompting to do something you just asked it to do is just annoying, not helpful.

**Comment by mcornella** [comment]
Richard, with all due respect, we've already agreed that the current function is harmful. You don't need to pile on. I'll get to it when I can.

**Comment by rwmitchell** [comment]
Sorry, but I was told repeated I was wrong, it was an advanced script.  This plugin is bad in many ways each time I look at it.

**Comment by rwmitchell** [comment]
> Richard, with all due respect, we've already agreed that the current function is harmful. You don't need to pile on. I'll get to it when I can.

Why should you have to fix it?  Delete it and let the original authors resubmit a fixed version. Delegate!
