### ISSUE TITLE
Pre- and post- execution point files

### ISSUE THREAD

**Issue by jasonlyle88** [ohmyzsh/ohmyzsh#10657]
### If the feature solves a problem you have, specify it here.

I had to completely redo my ohmyzsh and powerlevel10k setups the other day when my cat decided to attack my keyboard and mess up several configuration files. In doing so, it was rather difficult to parse out where I had put all my different customizations and what was just boilerplate for different tools/frameworks/themes/etc.

It would be very nice if users were able to have dedicated files that aren't ever touched by the tool, but allow the user to completely contain their customizations.

To this end, I propose pre-execution and post-execution files

### Describe the proposed feature.

Allow for `.zshrc.pre`, `.zshrc.post`, `.oh-my-zsh.pre.sh`, and `.oh-my-zsh.post.sh` scripts to be sourced at the appropriate  points based on the filename.

For instance, I have edited my `.zshrc` file to start with the following line
`[[ -f "${HOME}/.zshrc.pre" ]] && source "${HOME}/.zshrc.pre"`

And the last line in my `.zshrc` file to be this following line
`[[ -f "${HOME}/.zshrc.post" ]] && source "${HOME}/.zshrc.post"`

And I modified the line `source $ZSH/oh-my-zsh.sh` to be the following
```
[[ -f "${HOME}/.oh-my-zsh.pre.sh" ]] && source "${HOME}/.oh-my-zsh.pre.sh"

source $ZSH/oh-my-zsh.sh

[[ -f "${HOME}/.oh-my-zsh.post.sh" ]] && source "${HOME}/.oh-my-zsh.post.sh"
```

### Describe alternatives you've considered

I'm not sure what other alternatives there are, but I am open to suggestions. The goal is to be able to have dedicated user configuration files specific to the framework.

### Additional context

For example, I have the following file contents in my setup

### .zshrc.pre
```
# Uncomment this line to enable zsh/zprof
# Once uncommenting this, reload the shell and run zprof to get the profile output
# This will profile the loading time of everything
#zmodload zsh/zprof
```

### .oh-my-zsh.pre.sh
```
# Set the theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set the basic list of plugins to use
plugins=(
#    autoupdate
    ohmyzsh-full-autoupdate
    zsh-syntax-highlighting
    brew
    jump
    colored-man-pages
    git
    zsh-autosuggestions
    history
    vscode
    zsh-completions
    tmux
    # jenv
)

# Add mac specific plugins to use
if [[ "${OSTYPE}" == "darwin"* ]]; then
    plugins+=(macos)
fi
```

**Comment by rwmitchell** [comment]
.zshrc is only created by OMZ on initial setup if it does not already exist.

I have moved all of my non-omz zsh settings to separate files, such as:
.zshrc-aliases
.zshrc-set
.zshrc-paths
.zshrc-complete

even bigger stuff goes in:
zsh-auto/
zsh-completions/
zsh-functions/

And I keep all of this under source code control.  I use mercurial, but git would be a better choice now.

Best of all, none of this requires waiting for someone else to change something just for me.

**Comment by carlosala** [comment]
Looks like sourcing your own config files is the best you can do in this case! I would not recommend you to edit OMZ files, as they could change in updates and may cause you errors when updating.
This is not likely to be added to omz as it's not really standard in zsh, it's better to just source your own config files in your `.zshrc`!

**Comment by jasonlyle88** [comment]
@carlosala I get that for the `.zshrc.pre` and `.zshrc.post`, but why not add the `.oh-my-zsh.pre.sh` and `.oh-my-zsh.post.sh`? You are arguing the files aren't standard zsh spec... but the `.oh-my-zsh.pre.sh` and `.oh-my-zsh.post.sh` files are specific to ohmyzsh. And addint them allow all users to keep their customizations for ohmyzsh in ohmyzsh specific files, which has the benefit of keeping the `.zshrc` file clean of the majority of ohmyzsh.

Obviously still the decision of you and the project team, just trying to make sure I understand the rationale and we make the appropriate arguments!

**Comment by rwmitchell** [comment]
I wouldn't be in favor of forcing those files into the home directory.  I try to keep as much of that out as possible, with most of them in a separate repo directory - with symlinks  to just the essential main stuff (.zshrc, .vimrc, etc).

**Comment by jasonlyle88** [comment]
@rwmitchell But this wouldn't be forcing it into the home directory. They would not be created by default. It would just be code that is ready to source the files are there. If they are not there, then nothing changes (so this won't be a breaking change at all). If people don't want to use the files, great, they don't have to use them! If they do, then also great because there is a built in way for them to easily encapsulate their ohmyzsh configurations!
