### ISSUE TITLE
I'm a little unclear on what is going on.

### ISSUE THREAD

**Issue by smitpatel0305** [ohmyzsh/ohmyzsh#10659]
Hey this works. I can change directory but its not changing permanently. When I close terminal it switch back to normal. Can you please tell me who can i change it permanently on mac.

**Comment by rwmitchell** [comment]
If the terminal is no longer open, how do you know it switched back?

**Comment by rwmitchell** [comment]
If you're using iTerm2, in Preferences -> Profiles -> General -> Working Directory -> Advanced Configuration is a whole selection of choices:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/15944841/152690944-6110db8c-7930-4341-bf4c-cf3bad515b3d.png">

**Comment by rwmitchell** [comment]
Or you could add ```last-working-dir``` to your plugins ( assuming you are using OMZ )

**Comment by smitpatel0305** [comment]
<img width="465" alt="Screen Shot 2022-02-06 at 11 43 41 AM" src="https://user-images.githubusercontent.com/97777758/152691384-98041839-e829-4da3-a439-f88ebd9fdf99.png">

**Comment by smitpatel0305** [comment]
I did it but when I close terminal and open terminal it sill takes me to the default directory

**Comment by smitpatel0305** [comment]
and when I tried to change path in Preference -> shells open with -> /Users/smitpatel/cs 214 --> and then I open shell it says permission denied.  If I get answer how to give permission form where then It will works but I don't have any idea how it works.

**Comment by rwmitchell** [comment]
This:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/15944841/152691819-2443e9f6-09f2-439c-8115-9cbcf3e393de.png">

is not a directory path, but the path to the shell you want to run.  /bin/zsh is the current default and a good choice.  Changing that entry to a path will result in the error you are getting.

From quick testing with Terminal, if a Terminal window is already open, a new window still start at the same directory as the previous window.  If all windows are closed, it'll revert back to your home directory.

May I suggest that if you'll be switching back to the terminal often, just leave it open.  You can even leave it up on another Desktop that you switch to when needing to work in the terminal.

If that is not possible for you, then add this line to the end of your .zshrc file:

```chdir '/Users/smitpatel/cs 214'```

well, maybe not exactly that.  Upper/lower case probably matters and believe earlier you referred to it as "CS214".   That space in between 'cs' and '214' is also troubling.  While the filesystem can handle it, it will cause you no end of trouble at the command line..  If it is really there, I recommend renaming the directory name to remove it.

**Comment by smitpatel0305** [comment]
chdir '/Users/smitpatel/cs 214' this works
Thankyou so much.
