### ISSUE TITLE
Add autocompletion to rd

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [ohmyzsh/ohmyzsh#10652]
Same as there is `compdef _dirs d` there should be the same autocompletion for `rd`.

**Comment by carlosala** [comment]
`rd` is currently completing the directories in your actual directory, I think I'm not understanding what do you want to say, could you explain it better?

And, by the way, I ask you for opening the issues with the fabolous templates we have, is easier to understand what's happening!

**Comment by mcornella** [comment]
What is `rd`? If you're referring to the `rd` alias that points to `rmdir`, that already has the completion for `rmdir` automatically.

**Comment by HarleyQuinn-Z6** [comment]
It wasn't working for me for some reason. I'll open it if I'm able to reproduce it.
