### ISSUE TITLE
xdg compliance plugin

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [ohmyzsh/ohmyzsh#10651]
There are some dotfiles that manage to keep the home folder clean by declaring environment variables and wrappers that force programs to comply with the xdg directory structure.

I would like to have a plugin to do that, and not have to search around to see what variable I have to setup to avoid messing the home directory every time I install some new software.

These are some dotfiles I've found that accomplish this: [z0rc](https://github.com/z0rc/dotfiles).

**Comment by mcornella** [comment]
Duplicate of #9543.
