### ISSUE TITLE
There are some repeated ls aliases.

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [ohmyzsh/ohmyzsh#10654]
There are some repeated ls aliases in [lib/directories](https://github.com/ohmyzsh/ohmyzsh/blob/d9c58d5fa10a1e9911d61adf7ccfbd64b24e713f/lib/directories.zsh) and [plugins/common-aliases](https://github.com/ohmyzsh/ohmyzsh/blob/d9c58d5fa10a1e9911d61adf7ccfbd64b24e713f/plugins/common-aliases/common-aliases.plugin.zsh).

And for some reason they are different.

**Comment by carlosala** [comment]
That's true, I'll look further into it.

**Comment by mcornella** [comment]
The `common-aliases` plugin overrides aliases defined by OMZ for others that the plugin considers better. This is not a bug but a feature of the plugin.
