### ISSUE TITLE
auto update with error

### ISSUE THREAD

**Issue by alansenairj** [ohmyzsh/ohmyzsh#10661]
### Describe the bug

It is getting error when it trying to auto update 

Updating Oh My Zsh
From https://github.com/ohmyzsh/ohmyzsh
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	oh-my-zsh.sh
Please commit your changes or stash them before you merge.
Aborting
Updating 2b492ae..2d3bae9
There was an error updating. Try again later?

### Steps to reproduce

just open a terminal and get this error

### Expected behavior

it just auto update by it self as always. 

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/20565821/152788278-dbd9b971-3bf5-49d6-a3eb-57e56eb8810f.png)

### OS / Linux distribution

Fedora 35

### Zsh version

5.8

### Oh My Zsh version

master (2b492ae)

### Terminal emulator

Gnome Termial

**Comment by carlosala** [comment]
Looks like you made some changes to `oh-my-zsh.sh`such as in #10620.
Running `cd $ZSH; git reset oh-my-zsh.sh; omz update` should solve the issue. Try to run it and tell me if it works!

**Comment by alansenairj** [comment]
These lines are the difference: 

diff --git a/oh-my-zsh.sh b/oh-my-zsh.sh
index b388b34..3a7bf76 100644
--- a/oh-my-zsh.sh
+++ b/oh-my-zsh.sh
@@ -177,3 +177,7 @@ if [ ! "$ZSH_THEME" = ""  ]; then
     source "$ZSH/themes/$ZSH_THEME.zsh-theme"
   fi
 fi
+
+export PATH="$HOME/.pyenv/bin:$PATH"
+eval "$(pyenv init --path)"
+eval "$(pyenv virtualenv-init -)"

**Comment by alansenairj** [comment]
Oh, ok. I solved. It was these 3 lines at the bottom. Thanxxx

Let me put my steps here to help someone. 

# If you put some paths to environment variables such as python venv or some other stuffs, you script file oh-my-zsh will not be updated because git original file will be different and git stop the update process. 

1- first you need to backup your lines added in this file. 
2- second you must add all files to remove git  warning message. Just do "git add . " at  cd $ZSH path
3- do a commit with any message like : git commit -m "ok"
4- update oh-my-zsh using: omz update
5- its done! To reload it without restart just do: exec $SHELL

**Comment by mcornella** [comment]
You should never modify files in `$ZSH` directory. These lines can go in your zshrc file. If the oh-my-zsh.sh is modified in the future you might get another conflict.
