### ISSUE TITLE
virtualenvwrapper plugin should not call 'deactivate' if user already deactivated

### ISSUE THREAD

**Issue by zcutlip** [ohmyzsh/ohmyzsh#10670]
### Describe the bug

The 'virtualenvwrapper' plugin's behavior of automatically deactivating the virtualenv doesn't check if the user (or some other mechanism) already deactivated. Thus it calls `deactivate` when it shouldn't, which fails and:

- Prints an error message to the console
- never unsets `$CD_VIRTUAL_ENV`, so the error keeps printing on each `chpwd`

### Steps to reproduce

1. enable `virtualenvwrapper` plugin
2. cd into a project directory that has a corresponding virtualenvwrapper environtment
3. notice the virtualenv has been activated
4. **manually** deactivate
5. cd out of the project directory
6. notice the error text on the console:
```console
> cd
workon_cwd:24: command not found: deactivate
```
7. continue to `cd` around, noticing the error text repeating

### Expected behavior

The `virtualenvwrapper` plugin should notice the virtualenv has been deactivated, and gracefully clean up its state.

### OS / Linux distribution

macOS 12.2

### Zsh version

5.8

### Terminal emulator

iTerm2 3.5.0beta4

**Comment by zcutlip** [comment]
I have a relatively trivial fix and will submit a PR shortly

**Comment by carlosala** [comment]
Looks nice! Could you submit the PR?

**Comment by carlosala** [comment]
Sorry, I didn't saw that! 😉
