### ISSUE TITLE
Why my "cloud" theme got only half of its icon?

### ISSUE THREAD

**Issue by JsthcitPizifly** [ohmyzsh/ohmyzsh#10684]
### Describe the bug

Used cloud, but got only half of its icon.
<img width="139" alt="image" src="https://user-images.githubusercontent.com/32784883/153586931-95c10952-91e8-4b68-812a-dbeaf68f3202.png">

### Steps to reproduce

apple defalt font

### Expected behavior

full icon

### Screenshots and recordings

<img width="139" alt="image" src="https://user-images.githubusercontent.com/32784883/153586975-f9838d1f-c3e7-4719-b60a-34d657549bf2.png">

### OS / Linux distribution

macOS bigSur 11.6

### Zsh version

5.0.2

### Terminal emulator

GNOME Terminal

**Comment by mcornella** [comment]
That's just how the Unicode CLOUD character looks by default: https://www.fileformat.info/info/unicode/char/2601/index.htm.

If you want it to be different, you should use a different font to render emojis, like `Apple Color Emoji`:
![Screenshot_macOS_2022-02-11_14:36:47](https://user-images.githubusercontent.com/1441704/153601171-ef492b62-58f6-4070-b2df-ef289464f74c.png)

**Comment by JsthcitPizifly** [comment]
lol, that's so embarrassing, I got it, thank you so much.

**Comment by escapeanaemia** [comment]
thanks for your information!
