### ISSUE TITLE
there's no rake task

### ISSUE THREAD

**Issue by alec-c4** [ohmyzsh/ohmyzsh#10696]
Hi!
It is required to update this alias to `rails notes` because there's no rake task for notes.

https://github.com/ohmyzsh/ohmyzsh/blob/ef3f7c43a91eb2c90098843b0ee9193bb52cdc96/plugins/rails/rails.plugin.zsh#L73

**Comment by carlosala** [comment]
I don't really see your point. I'm not a Ruby user, but being `rake` like `ruby + make`, so tasks are defined by users, not by the tool. Then, it's not incorrect I think. Could you explain better which is your exactly point on that?
Thanks!

**Comment by alec-c4** [comment]
@carlosala Hey! I'll try to explain :) 
1 - earlier it was a rake task, but in the last versions of the rails framework it was migrated to the rails command, so now the rake task doesn't work anymore
2 - currently in the rails plugin for OMZ it is defined as a rake task, so we just need to change rake to rails command

**Comment by carlosala** [comment]
Ok, now I understood it! Could you make a PR?

**Comment by alec-c4** [comment]
@carlosala https://github.com/ohmyzsh/ohmyzsh/pull/9601

**Comment by carlosala** [comment]
I'll check it! Thanks!
