### ISSUE TITLE
Slow ohmyzsh start after PC restart

### ISSUE THREAD

**Issue by mcornella** [ohmyzsh/ohmyzsh#10693]
### Discussed in https://github.com/ohmyzsh/ohmyzsh/discussions/10690

<div type='discussions-op-text'>

<sup>Originally posted by **erychagov** February 13, 2022</sup>
Hello.
I notice that I have slow start of ohmyzsh.
I found that the next line takes about 20 secs on my PC:
```
zcompdump_revision="#omz revision: $(builtin cd -q "$ZSH"; git rev-parse HEAD 2>/dev/null)"
```
I found this line in the `$ZSH/oh-my-zsh.sh` file.
Why we need it? I want to find a  way to speedup it.

----

> if you cd to $ZSH and then run
> ```
> time git rev-parse HEAD
> ```
> how long does it take?

`git rev-parse HEAD  0.01s user 0.00s system 76% cpu 0.014 total`

> that looks normal.  how did you determine the offending line?  I'm assuming by adding echo or printf statements until you zeroed in on it?

You're right! I used `echo` to find the line.

----

> Does this happen on each new terminal window?

Only first terminal window takes time

> Do you see the same slow behavior when running

No.

</div>

**Comment by mcornella** [comment]
@erychagov can you add `set -xv` at the top of your .zshrc file and confirm whether it hangs in  `git rev-parse HEAD` or in `builtin cd -q "$ZSH"`? Also, is your `$ZSH` folder in a local filesystem (in your hard-drive or SSD?) or in a network share?

**Comment by erychagov** [comment]
It hangs in `git rev-parse HEAD`
```
/Users/erychagov/.oh-my-zsh/oh-my-zsh.sh:111> git rev-parse HEAD
```

`$ZSH` at my local filesystem (SSD).

**Comment by mcornella** [comment]
Right, in macOS you could use `dtruss` but it requires `sudo`. You can try to prefix it with `sudo dtruss` and see if it hangs as well after entering the password. Note that maybe the act of asking for a password can make it not hang since it introduces a significant wait time.

**Comment by erychagov** [comment]
Yeah, I just tried the next case
```
zcompdump_revision="#omz revision: $(builtin cd -q "$ZSH"; sudo dtruss git rev-parse HEAD 2>/dev/null)"
``` 
But I got nothing in console

**Comment by erychagov** [comment]
I got the same lines for another command:
```
> sudo dtruss df -h
dtrace: system integrity protection is on, some features will not be available
dtrace: failed to execute df: Operation not permitted
```

**Comment by mcornella** [comment]
Hmm looks like you ran into [SIP](https://poweruser.blog/using-dtrace-with-sip-enabled-3826a352e64b). You can copy the git binary somewhere else (preferably your home directory) and remove the code signing signature, then reference this new binary in the OMZ code. See https://poweruser.blog/using-dtrace-with-sip-enabled-3826a352e64b#a106

**Comment by erychagov** [comment]
I found [this article](https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/ConfiguringSystemIntegrityProtection/ConfiguringSystemIntegrityProtection.html#//apple_ref/doc/uid/TP40016462-CH5-SW1) and just disabled SIP on my PC.

I got a huge output. Should I share it here?

**Comment by erychagov** [comment]
Surprisingly it was much faster.
Just sent the logs

**Comment by mcornella** [comment]
Looks like the copied binary wasn't right. Make sure to copy the exact git binary, I believe `/usr/bin/git` is a link to somewhere else:

```sh
cp "${commands[git]:P}" ~/git
```

Make sure that `${commands[git]:P}` points to a file inside a versioned folder by running it with `echo` first.

**Comment by mcornella** [comment]
Oh right, so Xcode's version is broken. Well at least we know that 🤷🏻
