### ISSUE TITLE
Completion highlighting broken after update to zsh 5.8.1

### ISSUE THREAD

**Issue by hood** [ohmyzsh/ohmyzsh#10692]
### Describe the bug

Completion suggestions are now being colored just like user-inserted text, instead of being a different highlight style.

### Steps to reproduce

1. Setup any completion source
2. Try to trigger completion after partially inserting a keyword

### Expected behavior

Completion suggestions should be highlighted differently than normal text, as they've always been.

### Screenshots and recordings

https://i.imgur.com/BOVjU0B.png

(White text should actually be dark gray by default)

### OS / Linux distribution

Linux arch 5.16.8-arch1-1

### Zsh version

5.8.1

### Terminal emulator

kitty, st

**Comment by hood** [comment]
Found a solution. Simply  update the `zsh-syntax-highlighting` to its latest version, as it contains a fix for this issue: https://github.com/zsh-users/zsh-syntax-highlighting/issues/857

**Comment by carlosala** [comment]
I think you are talking about [`zsh-autosuggestions`](https://github.com/zsh-users/zsh-autosuggestions), right?
You should post the issue there!
If not, please share your `.zshrc`!

**Comment by carlosala** [comment]
> Found a solution. Simply  update the `zsh-syntax-highlighting` to its latest version, as it contains a fix for this issue: https://github.com/zsh-users/zsh-syntax-highlighting/issues/857

Great! Thanks for linking it!
