### ISSUE TITLE
Errors after upgrading zsh from 5.8 to 5.8.1 in Fedora 35

### ISSUE THREAD

**Issue by mjcv** [ohmyzsh/ohmyzsh#10697]
### Describe the bug

After upgrading to zsh 5.8.1 the initialization scripts of oh-my-zsh started giving errors. Rolling back to 5.8 it worked fine.

Checking the release notes, https://zsh.sourceforge.io/releases.html I found "Incompatibilities
PROMPT_SUBST expansion is no longer performed on arguments to prompt-expansion sequences such as %F." which I think is widely used and may be related with the problem.

### Steps to reproduce

1 - In a Fedora 35 with zsh 5.8 and oh-my-zsh installed, upgrade to zsh 5.8.1
2 - start a shell
Displays messages like:
```
/home/jj/.oh-my-zsh/oh-my-zsh.sh:126: compinit: function definition file not found
/home/jj/.oh-my-zsh/lib/completion.zsh:78: bashcompinit: function definition file not found
zsh: compdef: command not found...
/home/jj/.oh-my-zsh/lib/termsupport.zsh:108: add-zsh-hook: function definition file not found
/home/jj/.oh-my-zsh/lib/termsupport.zsh:109: add-zsh-hook: function definition file not found
/home/jj/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
/home/jj/.oh-my-zsh/lib/vcs_info.zsh:3: is-at-least: function definition file not found
/home/jj/.oh-my-zsh/lib/vcs_info.zsh:3: is-at-least: function definition file not found
zsh: compdef: command not found...
zsh: compdef: command not found...
zsh: compdef: command not found...
zsh: compdef: command not found...
/home/jj/.oh-my-zsh/plugins/git/git.plugin.zsh:140: is-at-least: function definition file not found
zsh: compdef: command not found...
zsh: compdef: command not found...
zsh: compdef: command not found...
zsh: compdef: command not found...
zsh: compdef: command not found...
zsh: compdef: command not found...
/home/jj/.oh-my-zsh/plugins/git/git.plugin.zsh:282: is-at-least: function definition file not found
/home/jj/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh:23: is-at-least: function definition file not found
You are using ZSH version 5.8.1. The minimum required version for Powerlevel10k is 5.1.
Type 'echo $ZSH_VERSION' to see your current zsh version.
/home/jj/.nvm/bash_completion:94: bashcompinit: function definition file not found
/home/jj/.nvm/bash_completion:95: compinit: function definition file not found
zsh: complete: command not found...
(anon):8: is-at-least: function definition file not found
```

### Expected behavior

Shell should start without displaying error messages

### OS / Linux distribution

Fedora 35

### Zsh version

5.8

### Terminal emulator

Terminator

**Comment by mcornella** [comment]
The errors you get are not related to the changes made (the fix in 5.8.1 is only applied when displaying data in the prompt). It looks to me like your `$fpath` value is broken, can you confirm by running `echo $fpath`?

**Comment by mcornella** [comment]
Can't confirm that this is not reproducible in Fedora 35 Silverblue. Upgrading from 5.8 to 5.8.1 does not introduce any issues.

**Comment by mjcv** [comment]
I checked the fpath and was incorrect, as you said, but it only fixed after a reboot (probably a logout would work too), for whatever reason it was always using the 5.8 path instead of the 5.8.1 when building it.

thanks for your help

**Comment by mcornella** [comment]
> I checked the fpath and was incorrect, as you said, but it only fixed after a reboot (probably a logout would work too), for whatever reason it was always using the 5.8 path instead of the 5.8.1 when building it.
> 
> thanks for your help

Check for changes to `$fpath` or `$FPATH` in your zshrc or similar. It might be that somewhere something is doing `export FPATH`, which shouldn't happen (`$fpath` and `$FPATH` are tied variables and never should be exported).
