### ISSUE TITLE
A bug occurs when using the tab key

### ISSUE THREAD

**Issue by Shadow-XT** [ohmyzsh/ohmyzsh#10704]
### Describe the bug

When I use the Zsh with ohmyzsh installed under the root user, I use the tab key to complete the command. If I press the tab repeatedly, the first two or more letters of the command will appear repeatedly. For example, if I enter the clear command and press the tab key twice or three times, clclear will appear. If I press the backspace key to delete, only the five letters of ‘clear’ can be deleted, The previous ‘clea’ cannot be deleted, and pressing the Enter key cannot delete ’clea'

This situation occurs on both Pengwin and Debian of WSL, but not on other Linux distributions

### Steps to reproduce

1. Enter 'cle'
┌─[root@Shadow] - [~] - [43]
└─[$] cle

2. Press tab to complete the command
┌─[root@Shadow] - [~] - [43]
└─[$] cleaclear                                                                                        
clear          clear_console

3. Press backspace to clear the entire command
┌─[root@Shadow] - [~] - [43]
└─[$] clea                                                                             
clear          clear_console

Now the letter "clea" in front can't be cleared away

### Expected behavior

After pressing backspace normally, the CLE will also be cleared

When the tab key is normally pressed to complete the ‘cle’, the terminal will display ‘clear’ instead of ‘cleaclear’

### OS / Linux distribution

Pengwin on Windows 10 x86_64

### Zsh version

5.8

### Oh My Zsh version

master (ef3f7c4)

### Terminal emulator

Windows Terminal

### If using WSL on Windows, which version of WSL

WSL2

**Comment by mcornella** [comment]
See https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command.

**Comment by Shadow-XT** [comment]
OK，I have solved this problem，thank

**Comment by Shadow-XT** [comment]
> 请参阅 https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command。

OK，I have solved this problem，thank you
