### ISSUE TITLE
[nvm] sed: -e expression #1, char 264: unterminated address regex

### ISSUE THREAD

**Issue by pogopaule** [ohmyzsh/ohmyzsh#10709]
### Describe the bug

Adding the nvm plugin and setting `NVM_LAZY` to 1 causes

`sed: -e expression #1, char 264: unterminated address regex` when I start a new shell.

### Steps to reproduce

1. enable `nvm` plugin
2. add `export NVM_LAZY=1` before oh-my-zsh is sourced
3. start a new shell

### Expected behavior

The error message should not appear.

### OS / Linux distribution

Ubuntu 20.04.3 LTS (Focal Fossa)

### Zsh version

5.8

### Oh My Zsh version

master (3427da40)

### Terminal emulator

GNOME Terminal + tmux

**Comment by carlosala** [comment]
You can try to see what's going on by executing `zsh` in xtrace mode. Running `zsh -xvic exit 2>&1 | less` and searching the line that has that `sed` error. If you can't figure out what's happening, post it here the content of the file created by `zsh -xvic exit &> ~/omz-debug.log` and I'll take a look.
By the way, I can't reproduce that.

**Comment by pogopaule** [comment]
Thank you very much for your quick reply!I fixed the issue. I had some config in my .zshrc that replicated what the nvm plugin does and forgot to take it out. For some reason that caused this problem.
