### ISSUE TITLE
kubectl.plugin.zsh:2: parse error near `<<<

### ISSUE THREAD

**Issue by strowk** [ohmyzsh/ohmyzsh#10717]
### Describe the bug

i have recently updated oh-my-zsh and now I am getting this when terminal starts:
```
/home/tim/.oh-my-zsh/plugins/kubectl/kubectl.plugin.zsh:2: parse error near `<<<'
/home/tim/.zshrc:136: command not found: k
 tim@t480s  tim  Error: write /dev/stdout: permission denied
 ```
 

### Steps to reproduce

1. Enable kubectl plugin on latest oh-my-zsh
2. Start terminal

### Expected behavior

Should not be errors

### OS / Linux distribution

Ubuntu 20.04

### Zsh version

5.8

### Terminal emulator

Gnome Terminal

### Additional context

I'm running inside of tmux

**Comment by carlosala** [comment]
Could you post the output of `cd $ZSH; git status`?

**Comment by carlosala** [comment]
If it's not clean, see [here](https://github.com/ohmyzsh/ohmyzsh/issues/10281#issuecomment-939856460) for more information and how to fix it.

**Comment by strowk** [comment]
```
 ✘ tim@t480s  tim  cd $ZSH; git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   themes/agnoster.zsh-theme

Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add <file>..." to mark resolution)
        both modified:   plugins/kubectl/kubectl.plugin.zsh

```

**Comment by strowk** [comment]
Ok, I reset the content of $ZSH folder (git reset --hard HEAD), now kubectl error is gone, however `Error: write /dev/stdout: permission denied` is still there.. I make a new ticket for that one
