### ISSUE TITLE
A bug was found when using the tab key to complete

### ISSUE THREAD

**Issue by Shadow-XT** [ohmyzsh/ohmyzsh#10718]
### Describe the bug

When using tab key to complete in omz, there will be a bug that seems to call Python function.
And the command will also be split into two parts to another line, and if I use the tab key once, the command will be added to the next line
This does not happen when I use Zsh without omz installed
At present, this situation only occurs when using dnf related commands

## Press tab for the first time to complete
➜  ~ sudo dnf up_dnf:6: no such file or directory: /usr/bin/python3
     sudo dnf up
update      -- deprecated alias for upgrade
updateinfo  -- display advisories about packages
upgrade     -- upgrade a package or packages on your system
upgrade-to  -- upgrade a package on your system to the specified version

## Press tab a second time
➜  ~ sudo dnf up_dnf:6: no such file or directory: /usr/bin/python3
     sudo dnf up_dnf:6: no such file or directory: /usr/bin/python3
datetsudo dnf update
update      -- deprecated alias for upgrade
updateinfo  -- display advisories about packages
upgrade     -- upgrade a package or packages on your system
upgrade-to  -- upgrade a package on your system to the specified version

### Expected behavior

Under normal circumstances, it should be like this:
I input  ‘sudo dnf up’,    and then press the tab key to complete
➜  ~ sudo dnf update
update      -- deprecated alias for upgrade
updateinfo  -- display advisories about packages
upgrade     -- upgrade a package or packages on your system
upgrade-to  -- upgrade a package on your system to the specified version

### OS / Linux distribution

CentOS Stream 8 on Windows 10.0.22000 x86_64

### Zsh version

5.5.1

### Oh My Zsh version

master (914b639)

### Terminal emulator

Windows Terminal

### If using WSL on Windows, which version of WSL

WSL2

**Comment by mcornella** [comment]
That's Zsh default completion for `dnf`:
```sh
_dnf() {
  if [[ "$(readlink /usr/bin/dnf)" == "dnf-2" ]]; then
    local python_exec="/usr/bin/python2"
  else
    local python_exec="/usr/bin/python3"
  fi
  local helper=$(${python_exec} -c "import dnf.cli; print('{}/completion_helper.py'.format(dnf.cli.__path__[0]))")
  local cache_file="/var/cache/dnf/packages.db"

  _arguments -s \
    '(- *)'{-h,--help}'[show the help message]' \
    '--version[show dnf version]' \
    '(-v --verbose)'{-v,--verbose}'[set verbose, show debug messages]' \
    '(-q --quiet)'{-q,--quiet}'[show just the relevant content]' \
    '--allowerasing[allow erasing of installed  packages]' \
    '(-y --assumeyes)'{-y,--assumeyes}'[answer yes for all questions]' \
    '(-C --cacheonly)'{-C,--cacheonly}'[run entirely from cache]' \
    '(-c --config)'{-c,--config=}'[config file location]:config file:_files' \
    '(-R --randomwait)'{-R,--randomwait=}'[maximum command wait time (in minutes)]:max wait time' \
    '--releasever=[configure DNF for another release]:release' \
    '--refresh[set metadata as expired before running the command]' \
    '--nogpgcheck[skip checking GPG signatures on package]' \
    '--installroot=[set install root]:install root:_files -/' \
    '*--enablerepo=[enable one or more repositories]:repos to enable:_dnf_disabled_repos' \
    '*--disablerepo=[disable one or more repositories]:disable repos:_dnf_enabled_repos' \
    '*::dnf command:_dnf_command'
}
```
It uses `/usr/bin/python3` or `/usr/bin/python2` depending on the dnf version, to read the dnf packages database.

The solution is installing python3.
