### ISSUE TITLE
Error of cd command caused by ohmyzsh

### ISSUE THREAD

**Issue by wangmings** [ohmyzsh/ohmyzsh#10712]
## error
cd ter    
error:  No command cd found, did you mean:

### Expected behavior

on

### Screenshots and recordings

on

### OS / Linux distribution

android

### Zsh version

5.8

### Terminal emulator

termux

### Additional context

on

**Comment by rwmitchell** [comment]
What does ```type _cd``` report?

It should be in: SOMEPATH/share/zsh/VERSION/functions

if it isn't, your $FPATH is likely corrupt.

If this isn't it, what plugins are you using?

**Comment by mcornella** [comment]
Does this happen when running zsh with `zsh -f`? If it does, it wouldn't be an OMZ bug. Also the error you posted doesn't seem like it would trigger when tab-completing `cd`, did you run it instead?
