### ISSUE TITLE
Links not working in plugins overview

### ISSUE THREAD

**Issue by matheusfelipeog** [ohmyzsh/ohmyzsh#10716]
Hi

These plugins have been removed and their links, which no longer work, are in the plugins list:

- [zsh_reload](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/zsh_reload) in [Productivity category](https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins-Overview#productivity)
- [django](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/django) in [Python category](https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins-Overview#python)

I believe they should be removed from the list.

**Comment by carlosala** [comment]
Yes, they should be removed. Thanks for the report!

**Comment by mcornella** [comment]
Fixed, thanks!
