### ISSUE TITLE
michelebologna.zsh-theme is broken

### ISSUE THREAD

**Issue by InvisibleRasta** [ohmyzsh/ohmyzsh#10715]
### Describe the bug

https://github.com/ohmyzsh/ohmyzsh/blob/master/themes/michelebologna.zsh-theme
this theme is spitting out error:
~/.oh-my-zsh/themes/michelebologna.zsh-theme:43: command not found: hostname  

### Steps to reproduce

load the theme

### Expected behavior

no error

### OS / Linux distribution

archlinux

### Zsh version

extra/zsh 5.8.1-1

### Terminal emulator

alacritty

**Comment by carlosala** [comment]
`hostname` should be installed in your system to use this theme. In archlinux is part of the `inetutils` package, in core repository. You can install it using `sudo pacman -S inetutils`.

**Comment by mcornella** [comment]
The theme shouldn't depend on `hostname`, there are native Zsh alternatives.
