### ISSUE TITLE
Themes don't render correctly even with powerline fonts (WSL2 with ubuntu 20.04)

### ISSUE THREAD

**Issue by themoonmeetsthesun** [ohmyzsh/ohmyzsh#10711]
### Describe the bug

I just installed ohmyzsh on WSL2 with ubuntu 20.04 and set the theme after installing powerline fonts. But it still wasn't rendering properly. How do I fix it??

### Steps to reproduce

Setup ohmyzsh
Install the powerline fonts
Set the agnoster theme

### Expected behavior

It should render correctly

### OS / Linux distribution

WSL2 Ubuntu 20.04

### Zsh version

5.8

### Oh My Zsh version

master (3427da4)

### Terminal emulator

Windows Terminal with WSL

### If using WSL on Windows, which version of WSL

WSL2

**Comment by carlosala** [comment]
Hi! Could you post some screenshot?

**Comment by themoonmeetsthesun** [comment]
![image](https://user-images.githubusercontent.com/96462198/154854224-429d8904-b6de-4919-85c4-fb2d6dc72814.png)
There you go

**Comment by mcornella** [comment]
You need to change your terminal settings to use the installed Powerline font.

**Comment by themoonmeetsthesun** [comment]
How do i do that?

**Comment by mcornella** [comment]
This instruction is specific to Windows Terminal: there's a Settings option in the drop-down menu you get by pressing the little downward arrow, next to the Plus button to open a new tab. You should be able to find the section that contains the font setting.

**Comment by themoonmeetsthesun** [comment]
Sure. Thanks for your help!

**Comment by themoonmeetsthesun** [comment]
Ok, thanks for your help!
