### ISSUE TITLE
plugins/kubectl/kubectl.plugin.zsh:source:15: no such file or directory: /completions/_kubectl

### ISSUE THREAD

**Issue by joshuawhite929** [ohmyzsh/ohmyzsh#10728]
### Describe the bug

I am using antibody to load the following bundle:

ohmyzsh/ohmyzsh path:plugins/kubectl

When oh my zsh starts, it complains about the following:
```
mkdir: /completions: Read-only file system
tee: /completions/_kubectl: No such file or directory
/Users/josh/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-ohmyzsh-SLASH-ohmyzsh/plugins/kubectl/kubectl.plugin.zsh:source:15: no such file or directory: /completions/_kubectl
```

Looking at the following file:  [kubectl.plugin.zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/kubectl/kubectl.plugin.zsh) it doesn't appear that the $ZSH_CACHE_DIR variable is present or expanding properly.  I can echo $ZSH_CACHE_DIR without a problem.  Its value is /Users/josh/.oh-my-zsh/cache

### Steps to reproduce

Start a new terminal window

### Expected behavior

[kubectl.plugin.zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/kubectl/kubectl.plugin.zsh) would run without producing an error

### OS / Linux distribution

macOS 12.2

### Zsh version

5.8

### Oh My Zsh version

master (e934857)

### Terminal emulator

iTerm2

**Comment by carlosala** [comment]
If you export the variable before loading the plugin same happens?

**Comment by joshuawhite929** [comment]
Uncommenting the line with the export below fixes the problem.  Now the fun part.  Figuring out why that's necessary. = )

```
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
source <(antibody init)
#export ZSH_CACHE_DIR=/Users/josh/.oh-my-zsh/cache
antibody bundle ohmyzsh/ohmyzsh path:plugins/kubectl
```

**Comment by joshuawhite929** [comment]
ok, we can close this out...  user error.

When loading bundles, I have to load: `antibody bundle ohmyzsh/ohmyzsh` first.  Thats why the variable isn't getting set.

**Comment by amritpalnagrame** [comment]
> Make sure cache have **completions** sub-directory.
> 
> ```shell
> mkdir $ZSH_CACHE_DIR/completions
> ```
> 
> Then open new tab, and everything is working fine.
> [Comment on antigen issue](https://github.com/zsh-users/antigen/issues/701#issuecomment-1129781560)
