### ISSUE TITLE
Error: write /dev/stdout: permission denied

### ISSUE THREAD

**Issue by strowk** [ohmyzsh/ohmyzsh#10722]
### Describe the bug

The error "Error: write /dev/stdout: permission denied" started to appear after last ohmyzsh update. Following this - https://github.com/ohmyzsh/ohmyzsh/issues/10717#issuecomment-1048658936 I have reset $ZSH dir and now it looks like this 
```
 ✘ tim@t480s  ~  cd $ZSH; git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

### Steps to reproduce

1. install latest oh-my-zsh
2. you might get that error (or not?) when terminal starts

### Expected behavior

No errors

### OS / Linux distribution

Ubuntu 20.04

### Zsh version

5.8

### Terminal emulator

Gnome Terminal

**Comment by mcornella** [comment]
This was reported on [Discord some weeks ago](https://discord.com/channels/642496866407284746/809850295005741056/940948318815653948). The culprit were the `helm` and `kubectl` plugins. The workaround the user found was to install `helm` and `kubectl` with apt instead of using snap.

Here are the relevant parts of the chat:

> **danielmichaelis89 — 08/02/2022**
> Hi, I already tried my luck in the ohmyzsh channel but without any success, so I'll try again here:
> Whenever I open a new terminal or simply run zsh in an IDE like PyCharm or VS Code I'm getting the following error:
> Error: write /dev/stdout: permission denied
> error: write /dev/stdout: permission denied
> 
> I don't get this error in my standard terminal even though my standard shell is zsh in all cases. I found out that the error occurs when sourcing $ZSH/oh-my-zsh.sh from within .zshrc. The error started appearing a while ago, it wasn't there when I first installed oh-my-zsh and I can't connect it to any changes to my system I made recently. It's not a big problem but it gets a bit annoying to start every session with an error. Does anyone know how to solve it?

> **danielmichaelis89 — 08/02/2022**
> I'm using Ubuntu 20.04, the file is owned by my user and yes, I can source it manually but the same error occurs

> **danielmichaelis89 — 08/02/2022**
> lrwxrwxrwx 1 root root 15 Feb  8 09:08 /dev/stdout -> /proc/self/fd/1

> **danielmichaelis89 — 08/02/2022**
> I narrowed it down to the helm and kubectl plugins. helm leads to the first error message, kubectl to the second

> **danielmichaelis89 — 08/02/2022**
> It seems to be the following lines in helm.plugin.zsh and kubectl.plugin.zsh, respectively:
> 
> helm completion zsh >| "$ZSH_CACHE_DIR/completions/_helm" &|
> kubectl completion zsh >| "$ZSH_CACHE_DIR/completions/_kubectl" &|
> 
> Not sure what's causing the problem and the different behavior in Pycharm's or VSCode's terminals and in the standard terminal.

> **danielmichaelis89 — 09/02/2022**
> **I figured out a workaround. I had helm and kubectl installed via snap. Removing these installations and installing them via apt instead resolved the issue.** I can now activate the plugins and the completion scripts are written to the corresponding files without errors. Though I don't quite understand the underlying problem with the snaps and why it only occurred in certain terminals, that solved it for me. If anyone has a possible explanation it would be nice to learn, otherwise I think I'm happy with the way it works now

**Comment by strowk** [comment]
Thanks for quick answer!

I don't believe that changing package manager is a solution though, specifically if suggested change is degradation to less modern manager. Snap is superior to apt and I believe should be supported, therefore there is a bug in a plugins in this distribution. 

Would you please reopen this, so that the bug could be solved eventually? Thanks!

**Comment by strowk** [comment]
Aha, problems with at least helm plugin have started somewhere over here 
https://github.com/ohmyzsh/ohmyzsh/commit/875e7c4077c08b6cf5547929d403f70a52836388
with the goal of (as I understand this) to keep a cache of completions. However that commit breaks snap installations, as snap does not allow to write into hidden folders, which is what `$ZSH_CACHE_DIR` seems to be (~/.oh-my-zsh/cache). 

IMO, performance improvement, which breaks plugin for snap installation is not a good improvement and should be either reverted or at least changed in a way so that snap installations still work as expected.. Wouldn't you agree that this is a bug, which should be solved rather than ignored?

**Comment by carlosala** [comment]
@strowk I tried to add a workaround for that. By the way, I don't use snap, could you please test my PR? You can do it by executing `omz pr test 10723`. Let's see if works!

**Comment by mcornella** [comment]
@strowk I can't reproduce the error using snap's helm. Did you install it using `snap install helm --classic` or is there some other snap I'm not aware of?

**Comment by strowk** [comment]
That was some time ago @mcornella  , but yeah, I think I did install it like that. 

I tried `omz pr test 10723` @carlosala  and now I get a very long output with the completion script written to output when I start terminal.

**Comment by carlosala** [comment]
yes, that's a bug in my workaround. Does completion work?

**Comment by strowk** [comment]
Completion actually seem to work on master as well.. I think only caching does not work (and spawns the error message). 
However with your fix output of `cat "$ZSH_CACHE_DIR/completions/_helm"` is not empty, which probably means it works :)

**Comment by carlosala** [comment]
great!

**Comment by mcornella** [comment]
The only way completion works on master is if `"$ZSH_CACHE_DIR/completions/_helm"` is written, since the plugin `source`s that file: https://github.com/ohmyzsh/ohmyzsh/blob/dfaad779a9bbe1f83e30820d227d4b7870bdf33f/plugins/helm/helm.plugin.zsh#L14-L22

What's important is that the error is gone after the PR. After Carlo fixes the PR you can check for that (you'll have to run `omz pr test 10723` again).

**Comment by carlosala** [comment]
done!

**Comment by strowk** [comment]
Ok, I have no idea why completion does not seem to be affected in master for me, but I can confirm that `omz pr test 10723` now fixes the issue (error is gone, completion seems to be fine).

**Comment by mcornella** [comment]
Awesome, then we can do the same for `kubectl` which also had this problem (see https://github.com/ohmyzsh/ohmyzsh/issues/10722#issuecomment-1049767106). @carlosala can you take care of that?

**Comment by carlosala** [comment]
sure!
