### ISSUE TITLE
Wrong link on website for the Spotify plugin

### ISSUE THREAD

**Issue by thefirethirteen** [ohmyzsh/ohmyzsh#10738]
Under the `Got Plugins?` section of the website, the button for the Spotify plugin has the wrong link `https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/osx/spotify` (does not work). I think it should be `https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/macos/spotify` (this link does work, I'm unsure if this is the correct plugin).

That's it. Have a lovely day :)

**Comment by mcornella** [comment]
Thanks! I've forwarded the bug to Robby.
