### ISSUE TITLE
Update the spotify plugin link and copyright year on Website

### ISSUE THREAD

**Issue by AnilSeervi** [ohmyzsh/ohmyzsh#10740]
### Describe the bug

- The link to Spotify plugin leads to `osx` directory which was deprecated.
- The Copyright year says "©2009 - 2020"

### Steps to reproduce

1. Visit the https://ohmyz.sh/ site
2. Scroll down to **Got Plugins?** section
3. Visit _Spotify_ plugin site.
4. Also scroll way down to see copyright year

### Expected behavior

- The Spotify plugin must link to - https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/macos/spotify
- The copyright year should update automatically and say "©2009 - 2022"

### OS / Linux distribution

Web

### Zsh version

N/A

### Terminal emulator

N/A

**Comment by mcornella** [comment]
Hey thanks for the report, this was already notified in #10738.

**Comment by AnilSeervi** [comment]
What about the copyright year @mcornella? Is that also reported.
