### ISSUE TITLE
aws plugin doesn't allow empty ZSH_THEME_AWS_PREFIX or ZSH_THEME_AWS_SUFFIX

### ISSUE THREAD

**Issue by asharpe-squiz** [ohmyzsh/ohmyzsh#10744]
When writing a theme, if I specifically set `ZSH_THEME_AWS_SUFFIX` to an empty string, ie

```zsh
ZSH_THEME_AWS_SUFFIX=''
```

then I expect the output of `aws_prompt_info` to NOT finish with '>'

The issue appears to be caused by the use of `:=` in `aws_prompt_info()`, which is remedied by changing it to `-` (or `=`)

Here's the "fixed" `aws_prompt_info()`

```zsh
function aws_prompt_info() {
  [[ -n "$AWS_PROFILE" ]] || return
  echo "${ZSH_THEME_AWS_PREFIX-<aws:}${AWS_PROFILE:gs/%/%%}${ZSH_THEME_AWS_SUFFIX->}"
}
```

**Comment by mcornella** [comment]
Thanks for the report!
