### ISSUE TITLE
Automatic title is printing command to terminal

### ISSUE THREAD

**Issue by codebysandwich** [ohmyzsh/ohmyzsh#10742]
### Describe the bug

like neovim、vscode with zsh with occur:
>cd
cd%
>l
l ……
>java ……
java result
but in iterm2 omz work well

### Steps to reproduce

Third party applications error

### Expected behavior

Third party applications behavior error

### OS / Linux distribution

macOS 10.15.7

### Zsh version

master (c8180482)

### Terminal emulator

iTerm2

**Comment by codebysandwich** [comment]
![image](https://user-images.githubusercontent.com/32191093/155872430-6a7bac1f-bbb8-4831-b009-5ed422124419.png)

**Comment by codebysandwich** [comment]
- neovim 
![image](https://user-images.githubusercontent.com/32191093/155872488-0fa059d9-b3ad-4882-9c31-f2f69e991dd5.png)

**Comment by mcornella** [comment]
It looks like the automatic title feature is outputting the command to be displayed in the terminal title, but it's not getting caught and instead is being shown directly to the terminal.

Just to be clear, this only happens in the neovim terminal? Can you post the output of `echo $TERM` and `echo $TERM_PROGRAM`?

**Comment by codebysandwich** [comment]
> It looks like the automatic title feature is outputting the command to be displayed in the terminal title, but it's not getting caught and instead is being shown directly to the terminal.
> 
> Just to be clear, this only happens in the neovim terminal? Can you post the output of `echo $TERM` and `echo $TERM_PROGRAM`?

@mcornella Thanks very much, it happens in vim with iterm2 too,happens in vscode too.
echo $TERM = screen-256color
echo $TERM_PROGRAM = tmux

**Comment by codebysandwich** [comment]
it's happens in terminal.app too
![image](https://user-images.githubusercontent.com/32191093/155908743-bffd47ab-7294-491d-b9a0-b7906a6425e7.png)

**Comment by mcornella** [comment]
Can you post the output of `which $preexec_functions`?

**Comment by codebysandwich** [comment]
> Can you post the output of `which $preexec_functions`?

Thank you for your answer!
echo $preexec_functions
_p9k_preexec1 _zsh_highlight_preexec_hook omz_termsupport_preexec _p9k_preexec2

**Comment by codebysandwich** [comment]
more info:
_p9k_preexec1 () {
        _p9k_restore_special_params
        (( ${+functions[TRAPINT]} )) || trap - INT
}
_zsh_highlight_preexec_hook () {
        typeset -g _ZSH_HIGHLIGHT_PRIOR_BUFFER=
        typeset -gi _ZSH_HIGHLIGHT_PRIOR_CURSOR=
}
omz_termsupport_preexec () {
        [[ "${DISABLE_AUTO_TITLE:-}" != true ]] || return
        emulate -L zsh
        setopt extended_glob
        local -a cmdargs
        cmdargs=("${(z)2}")
        if [[ "${cmdargs[1]}" = fg ]]
        then
                local job_id jobspec="${cmdargs[2]#%}"
                case "$jobspec" in
                        (<->) job_id=${jobspec}  ;;
                        ("" | % | +) job_id=${(k)jobstates[(r)*:+:*]}  ;;
                        (-) job_id=${(k)jobstates[(r)*:-:*]}  ;;
                        ([?]*) job_id=${(k)jobtexts[(r)*${(Q)jobspec}*]}  ;;
                        (*) job_id=${(k)jobtexts[(r)${(Q)jobspec}*]}  ;;
                esac
                if [[ -n "${jobtexts[$job_id]}" ]]
                then
                        1="${jobtexts[$job_id]}"
                        2="${jobtexts[$job_id]}"
                fi
        fi
        local CMD="${1[(wr)^(*=*|sudo|ssh|mosh|rake|-*)]:gs/%/%%}"
        local LINE="${2:gs/%/%%}"
        title "$CMD" "%100>...>${LINE}%<<"
}
_p9k_preexec2 () {
        _p9k__preexec_cmd=$2
        _p9k__timer_start=EPOCHREALTIME
}

**Comment by mcornella** [comment]
Why do you have `$TERM` equal to `screen-256color`? That should only be necessary when using `screen`. Did you change it?

**Comment by codebysandwich** [comment]
> Why do you have `$TERM` equal to `screen-256color`? That should only be necessary when using `screen`. Did you change it?

I'm sorry about that I forgot change xterm-256color to screen-256color by Neovim's suggestion. everything is ok with xterm-256color.
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/32191093/156169352-0c4e7b4d-c66f-4f2e-9b94-4593d7356f22.png">
 
thanks your patience and your answer, I'm sorry about that again!  i need learn more about neovim. Thanks again!
