### ISSUE TITLE
prompt get duplicated when iTerm2 size is small

### ISSUE THREAD

**Issue by sgeektn** [ohmyzsh/ohmyzsh#10750]
### Describe the bug

prompt get duplicated when iTerm2 size is reduced ( MacOs ) 

### Steps to reproduce

Open iTerm2 with zsh with theme "bira"
reduce the size of the window until you get prompt doubled

### Expected behavior

The prompt get duplicated

### Screenshots and recordings

<img width="851" alt="Capture d’écran 2022-03-02 à 17 40 49" src="https://user-images.githubusercontent.com/22657755/156430150-7f0763e5-f804-41a6-9f25-28d6a7ae2084.png">
<img width="475" alt="Capture d’écran 2022-03-02 à 17 40 59" src="https://user-images.githubusercontent.com/22657755/156430156-3c6399b3-1237-4bdf-a401-89438906ed6b.png">

### OS / Linux distribution

mac os m1 12.0.1 (21A559)

### Zsh version

5.8

### Terminal emulator

iTerm2

**Comment by rwmitchell** [comment]
The previous screen display cannot be guaranteed after a resize. Does it continue to give a double prompt?

**Comment by mcornella** [comment]
That's normal zsh behavior, see https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window for a detailed explanation.

**Comment by mcornella** [comment]
If you press <kbd>CTRL-L</kbd> or run `clear` you'll get a clean terminal window.
