### ISSUE TITLE
dash plugin does not work (kLSApplicationNotFoundErr)

### ISSUE THREAD

**Issue by hidr0** [ohmyzsh/ohmyzsh#10767]
### Describe the bug

I get an error following the tutorial

### Steps to reproduce

```
dash python:tuple
No application knows how to open URL dash://python:tuple (Error Domain=NSOSStatusErrorDomain Code=-10814 "kLSApplicationNotFoundErr: E.g. no application claims the file" UserInfo={_LSLine=1489, _LSFunction=runEvaluator}).
```

### Expected behavior

Open dash and search in python for tuple

### OS / Linux distribution

Mac OS X 12.2.1 (21D62)

### Zsh version

5.8

### Oh My Zsh version

master (c10241f)

### Terminal emulator

Terminal.app

**Comment by mcornella** [comment]
Have you installed Dash? https://kapeli.com/dash

**Comment by hidr0** [comment]
Yes, sorry `dash python` works

**Comment by mcornella** [comment]
I can't reproduce your issue. `dash python:tuple` doesn't work but `dash python` does?

**Comment by hidr0** [comment]
![dash](https://user-images.githubusercontent.com/5238203/157718582-3310b3f1-3b9a-4cd3-8727-dadeb2dc2391.gif)

**Comment by mcornella** [comment]
If you run `open dash://python:tuple` it also fails right?

**Comment by mcornella** [comment]
If the above fails, try `open -a Dash.app dash://python:tuple`.

**Comment by hidr0** [comment]
Works, thanks!

**Comment by mcornella** [comment]
Can you test https://github.com/ohmyzsh/ohmyzsh/pull/10768? You can do that with `omz pr test 10768`, then try to complete and use `dash` normally.

**Comment by hidr0** [comment]
Works like a charm!
