### ISSUE TITLE
minikube completions won't fire

### ISSUE THREAD

**Issue by todd-dsm** [ohmyzsh/ohmyzsh#10763]
### Describe the bug

I have many plugins designated, so far only the [minikube plugin] won't produce completions like the rest.

I would expect to see something like: (ohmyzsh-style)

```sh
% kubectl
alpha          -- Commands for features in alpha
annotate       -- Update the annotations on a resource
api-resources  -- Print the supported API resources on the server
```

Instead I get this: (default, from brew install minikube)

```sh
% minikube
addons          config          delete          image           logs            options         profile         ssh-host        status          unpause         ...   
```

This style of completion is installed (with the programs that have them) by installing them via homebrew. Those completions go here:

```
% brew reinstall minikube
...
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
```

[minikube plugin]:https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/minikube

### Steps to reproduce

1. Install Oh My ZSH
2. Install minikube: `brew reinstall minikube`
3. Enable the plugin
```sh
% grep -A2 '^plugins' ~/.zshrc
plugins=(git ansible aws colorize colored-man-pages common-aliases \
	docker docker-compose encode64 gcloud genpass gitignore gradle helm \
	history kubectl minikube nmap pip rust terraform)
```
4. Spawn a new zsh shell and attempt a completion: `% minikube [TAB-TAB]

### Expected behavior

Completions should look like the ohmyzsh style noted above.

### OS / Linux distribution

macOS 11.6.4

### Zsh version

5.8

### Terminal emulator

Terminal.app

**Comment by roninhockley** [comment]
I had the same behavior on ubuntu 22.04 right after adding the plugin. A reboot fixed it though.

**Comment by carlosala** [comment]
It's really weird how this plugin is done. I'll update it. It doesn't work now because `$ZSH_CACHE_DIR` is not on `fpath`

**Comment by caerulescens** [comment]
I'm using the `minikube` plugin, and I'm having no issues with completions. Anyone having issues should retest, and probably could move to resolve this issue.
