### ISSUE TITLE
"xcrun: error: invalid active developer path" msg on shell start

### ISSUE THREAD

**Issue by wildeyes** [ohmyzsh/ohmyzsh#10760]
### Describe the bug

After upgrading to Monterey, I'm getting three `xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun` errors on shell start. ideas?

### Steps to reproduce

0. Have stock oh-my-zsh
1. Upgrade to Monterey
2. Open shell

### Expected behavior

No startup errors :)

### Screenshots and recordings

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1652108/156994117-af80bf0f-51e0-41d5-b513-af089143a8c6.png">

### OS / Linux distribution

macOS monterey 12.2.1

### Zsh version

zsh 5.8 (x86_64-apple-darwin20.1.0)

### Terminal emulator

iterm2

**Comment by mcornella** [comment]
https://github.com/ohmyzsh/ohmyzsh/issues/4829
