### ISSUE TITLE
Postgres plugin still use wrong Homebrew prefix (Apple Silicon)

### ISSUE THREAD

**Issue by ong-yinggao98** [ohmyzsh/ohmyzsh#10764]
### Describe the bug

As with #10612 this was supposedly fix to use `/opt/homebrew` on Apple Silicon, but I still get the reference to `/usr/local` instead. I thought it might be potentially Powerlevel 10k instant prompt causing issues but it still happens when I disable it.

### Steps to reproduce

1. Enable plugin
2. Use `startpost`

### Expected behavior

PostgreSQL should start normally

### Screenshots and recordings

<img width="429" alt="Screenshot 2022-03-08 at 6 36 59 PM" src="https://user-images.githubusercontent.com/52755148/157219902-0cefae4f-20d4-4638-be67-db9b1f8b8614.png">

### OS / Linux distribution

macOS 11.6

### Zsh version

5.8

### Oh My Zsh version

master (c8180482)

### Terminal emulator

Terminal.app

### Additional context

postgres plugin

**Comment by mcornella** [comment]
What do you get with `brew --prefix`?

**Comment by ong-yinggao98** [comment]
> What do you get with `brew --prefix`?
`/opt/homebrew`

But `PG_BREW_DIR` gives the wrong value

<img width="202" alt="Screenshot 2022-03-10 at 3 12 57 AM" src="https://user-images.githubusercontent.com/52755148/157514571-46f3d73b-ba71-42fb-ab57-a588e784176c.png">

**Comment by rwmitchell** [comment]
Are you setting PG_BREW_DIR manually elsewhere?  The plug-in sets it using the same brew command you are. Should be the same.

**Comment by ong-yinggao98** [comment]
> Are you setting PG_BREW_DIR manually elsewhere? The plug-in sets it using the same brew command you are. Should be the same.

Nope I'm not.

**Comment by mcornella** [comment]
Would be good to have a trace of the plugin running, so it's possible to see why `brew --prefix` returns the wrong thing. You can do that like so:

Edit file `$ZSH/plugins/postgres/postgres.plugin.zsh`:
```
set -xv # this line at the top

...

set +xv # this line at the bottom
```

It would be nice to know which `brew` command is getting called, maybe you have multiple ones? Run `which -a brew` to know for sure.

**Comment by ong-yinggao98** [comment]
> It would be nice to know which `brew` command is getting called, maybe you have multiple ones? Run `which -a brew` to know for sure.

Yes, I did use another version for use with Rosetta
<img width="242" alt="Screenshot 2022-03-24 at 3 15 07 AM" src="https://user-images.githubusercontent.com/52755148/159778366-629f8681-f31d-413e-98e3-65c395250128.png">

> Would be good to have a trace of the plugin running, so it's possible to see why `brew --prefix` returns the wrong thing. You can do that like so:

On it, here are the logs: 
<img width="1021" alt="Screenshot 2022-03-24 at 3 23 05 AM" src="https://user-images.githubusercontent.com/52755148/159779689-3cedeb40-bba6-40c9-b549-8ab99d671b42.png">

> Hi @ong-yinggao98! Could you test if #10793 solves the issue for you? You can do it by executing `omz pr test 10793`.

Sadly no :(
<img width="456" alt="Screenshot 2022-03-24 at 3 21 55 AM" src="https://user-images.githubusercontent.com/52755148/159779838-697fa3ae-2484-46e3-8fe5-8779f3f67cb1.png">

**Comment by carlosala** [comment]
This looks like it's the problem. You have multiple `brew` versions. Your fix for you would be to set `PG_BREW_DIR=<path desired>` after sourcing `oh-my-zsh.sh`. Try that and check if it's working for you.

**Comment by mcornella** [comment]
Hi @ong-yinggao98, I believe you should fix your setup so that `/opt/homebrew/bin` is first on `$PATH` (do that at the top of your zshrc file preferably, so that the change is active when the plugin runs). That should solve the issue with the plugin.

It's weird though to have multiple brew binaries, isn't it? I'm not that familiar with it, but it seems that you should only have the one specific to your Apple Silicon Mac.

If that's a setup common with other users, we could also change the plugin in such a way that you can configure where to look for Postgres (i.e. make the `PG_BREW_DIR` variable configurable).

**Comment by ong-yinggao98** [comment]
> It's weird though to have multiple brew binaries, isn't it? I'm not that familiar with it, but it seems that you should only have the one specific to your Apple Silicon Mac.

For the longest time ever there were formulae that were not compatible with Apple Silicon (even Cocoapods!) and I had a x64 binary to allow me to at least use them with Rosetta 2. This reminded me that I haven't used any such packages in ages and it is time to clean up :P 

That said, it still gave me the same problem (this time that there was no such `brew` command). As it turns out, I had left `eval "$(/opt/homebrew/bin/brew shellenv)"` in my script in `ZSH_CUSTOM` instead of on the top of `.zshrc` which probably resulted in `PG_BREW_DIR` being initialised before the brew environment was set. Moving that line back to `.zshrc` solved the problem. Thanks for the help!
