### ISSUE TITLE
upgrade.sh doesn't change "unauthenticated git protocol on port 9418

### ISSUE THREAD

**Issue by thinszx** [ohmyzsh/ohmyzsh#10778]
### Describe the bug

Due to [GitHub Blog about Git protocol security](https://github.blog/2021-09-01-improving-git-protocol-security-github/), the `unencrypted Git protocol` protocol is no longer supported since March 15, 2022. If users used `git` protocol to pull Oh-My-Zsh then fatal information will be triggered when he/she tries to upgrade now:
> fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

It's caused by the deprecated `git` protocol and `upgrade.sh` in Oh-My-Zsh won't change the protocol automatically.

### Steps to reproduce

1. Try `git clone git://github.com/ohmyzsh/ohmyzsh.git`, and the fatal information will show up.
2. If an old version ohmyzsh is used and the update information shows when opening a new shell, press `n` to cancel update, `cd $ZSH`, and change the remote repo url by `git remote set-url origin "git://github.com/ohmyzsh/ohmyzsh.git"`. Then close and reopen the shell, try to update ohmyzsh, the fatal information will show up.

### Expected behavior

ohmyzsh will automatically change protocol and update

### OS / Linux distribution

Ubuntu 20.04

### Zsh version

5.8

### Oh My Zsh version

master (511ed654)

### Terminal emulator

Windows Terminal

### If using WSL on Windows, which version of WSL

WSL2

**Comment by carlosala** [comment]
Oh-my-zsh uses as a default https protocol instead of git and ssh. So theorically nothing will change for default installs.
Thanks for the report!

**Comment by carlosala** [comment]
We can merge the PR for prevention, but omz don't use git:// for a long time👌🏻

**Comment by thinszx** [comment]
> We can merge the PR for prevention, but omz don't use git:// for a long time👌🏻

wow, I didn't notice that...I must have followed the [Manual Installation](https://github.com/ohmyzsh/ohmyzsh#manual-installation) guide, while TLS handshake always failed due to GFW in China so I changed default `https` protocol into `git` protocol to avoid the handshake process, maybe this only happens to few people, sorry🤣

**Comment by carlosala** [comment]
Don't worry, your contribution is really appreciated! I has been reading searching when has been changed and in commit 5f415c4, from Aug 2011. It's really improbable that someone that installed omz in 2011 hasn't updated its shell framework for 11 years xd.

**Comment by BladeWork** [comment]
@thinszx Thank you for your post, I faced the same issue. The only difference is I used ```git remote set-url origin "https://github.com/ohmyzsh/ohmyzsh.git"```

**Comment by SFantasy** [comment]
> @thinszx Thank you for your post, I faced the same issue. The only difference is I used `git remote set-url origin "https://github.com/ohmyzsh/ohmyzsh.git"`

`cd ~/.oh-my-zsh && git remote set-url origin "https://github.com/ohmyzsh/ohmyzsh.git" && omz update`

**Comment by zhongwutaos** [comment]
@SFantasy thanks for your solution,it work well

**Comment by andoks** [comment]
> Don't worry, your contribution is really appreciated! I has been reading searching when has been changed and in commit [5f415c4](https://github.com/ohmyzsh/ohmyzsh/commit/5f415c465a576a78d7e1577e472309fdd4c7621f), from Aug 2011. It's really improbable that someone that installed omz in 2011 hasn't updated its shell framework for 11 years xd.

I hit this snag today. The reason that I still am/was using git://... is that I have a setup.bash script that I wrote _years_ ago that I use to setup my environment, and in it I originally used git://.
