### ISSUE TITLE
git-prompt plugin doesn't work on macOS 12.3

### ISSUE THREAD

**Issue by anandb-ripencc** [ohmyzsh/ohmyzsh#10777]
### Describe the bug

The git-prompt plugin depends on python. Apple had deprecated python2 ages ago, and with the latest release of macOS 12.3, python2 is is gone, and so is the binary `/usr/bin/python`. In order to keep using the plugin, I've had to resort to hackery, by aliasing `python` to `python3` in my .zshrc. Other hacks of using symlinks from python3 to python somewhere in PATH also work. However, the plugin should use python3, instead of python.

### Steps to reproduce

1. Upgrade to macOS 12.3
2. Enable the "git-prompt" plugin
3. cd to a git checkout

### Expected behavior

I expect to see git status information in the prompt, but I don't.

### OS / Linux distribution

macOS 12.3

### Zsh version

5.8

### Terminal emulator

iTerm2

**Comment by carlosala** [comment]
Related: #10469

**Comment by anandb-ripencc** [comment]
The advice on what to do about the unversioned `python` command is vague, and there is no standard. The various OSes are doing different things. Therefore it is just not wise to depend on it. It's best to explicitly call `python3`.

**Comment by carlosala** [comment]
> The advice on what to do about the unversioned `python` command is vague, and there is no standard. The various OSes are doing different things. Therefore it is just not wise to depend on it. It's best to explicitly call `python3`.

Yeh, it's vague. But I think it SHOULD be the standard, as now there's only one major version non deprecated.

**Comment by Cyberbeni** [comment]
It has also been abandoned, forked and rewritten in zsh for better performance: https://github.com/zsh-git-prompt/zsh-git-prompt

**Comment by aldokkani** [comment]
A quick fix is to add an alias to your `~/.zshrc`;
```
alias python="python3"
...
# Make sure the alias is before loading omz!
source $ZSH/oh-my-zsh.sh
```

**Comment by Convolva** [comment]
This is still not resolved. I had to create an alias for python3 as python to make it work. I think there should be a better way to handle this.
