### ISSUE TITLE
:grey_question: Would you be OK to accept yamlfixer as a plugin :grey_question: 

### ISSUE THREAD

**Issue by adriens** [ohmyzsh/ohmyzsh#10788]
# :point_right: Context

We have recently released a tool called `yamlfixer` which aim is to automate [`yaml`](https://github.com/opt-nc/yamlfixer) fixing process. The tool is released as a `cli` and now I would like to get autocomplete and alias features.

Therefore I think  `Oh My Zsh` is the best way to handle that.

# :pray: Question

:arrow_right: If I make you a PR for a new dedicated plugin, would you be :ok: to merge it :grey_question:

**Comment by mcornella** [comment]
Thanks for asking before making the PR. I'd say that's a no for now, considering that at this point it's not really well-known nor used. Maybe in the future, but this looks more like the kind of tool that is run automatically instead of on the command line. So it's a soft no.
