### ISSUE TITLE
Odd borders on the bottom of the terminal window

### ISSUE THREAD

**Issue by Oman395** [ohmyzsh/ohmyzsh#10780]
### Describe the bug

On my terminal, there is a weird translucent border under my terminal when not in fullscreen.

### Steps to reproduce

Pretty much just exists stock on manjaro

### Expected behavior

Normal window sizing,

### Screenshots and recordings

![Screenshot from 2022-03-16 09-16-08](https://user-images.githubusercontent.com/77183348/158598043-fc00e3ac-cc51-48e8-9666-146a397ee1fa.png)

### OS / Linux distribution

Manjaro, Gnome, 41.3

### Zsh version

5.8.1

### Terminal emulator

Gnome probably? Whatever comes default with manjaro gnome

**Comment by mcornella** [comment]
This is a terminal emulator bug. I believe the one in the screenshot is GNOME Terminal. You should look for existing bugs there or file a new one.

**Comment by Oman395** [comment]
Thanks! Will do.
