### ISSUE TITLE
1Password plugin isn't working with 1Password CLI 2

### ISSUE THREAD

**Issue by moritzgvt** [ohmyzsh/ohmyzsh#10789]
### If the feature request is for a plugin or theme, specify it here.

1Password

### If the feature solves a problem you have, specify it here.

The new CLI of 1Password is breaking the `1password` plugin – it introduces a new command structure.

See Docs: [https://developer.1password.com/docs/cli/upgrade](https://developer.1password.com/docs/cli/upgrade)
> 1Password CLI 2 introduces a noun-verb command structure that groups commands by topic rather than by operation.

Therefore the list command that's currently used by the plugin isn't working anymore.

### Describe the proposed feature.

Use the "Update your scripts" table, to support 1password cli 2: [https://developer.1password.com/docs/cli/upgrade#step-2-update-your-scripts](https://developer.1password.com/docs/cli/upgrade#step-2-update-your-scripts).

### Describe alternatives you've considered

A workaround for now is not upgrading the 1Password CLI and stay with the predecessor for now. Though it would be nice to at least add a notice to the README.

**Comment by carlosala** [comment]
There's a PR in progress for that! Sorry for the delay! #10787

**Comment by carlosala** [comment]
Let's keep it open to track the issue 👍🏻
Thanks for your report!

**Comment by mcornella** [comment]
Fixed in https://github.com/ohmyzsh/ohmyzsh/commit/dbadfa0810c0be346b98c02cc802c33fa43bee11
