### ISSUE TITLE
The NVM plugin doesn't work when NVM installed via Homebrew on Apple Silicon Macs

### ISSUE THREAD

**Issue by hartbit** [ohmyzsh/ohmyzsh#10784]
### Describe the bug

The NVM plugin looks for nvm installed by Homebrew in the old location, which is not the location where it is installed on Homebrew 3 on Apple Silicon macs.

The following line is responsible:
https://github.com/hartbit/ohmyzsh/blob/master/plugins/nvm/nvm.plugin.zsh#L19

I attempted to fix the problem by using the `HOMEBREW_REPOSITORY` environment variable, but it's not present if Homebrew is loaded after zsh. The solution would probably be to check both locations then, but I don't feel proficient enough in Bash to fix the problem.

### Steps to reproduce

1. Install NVM via Homebrew on a Apple Silicon mac.
2. Enable the nvm plugin.
3. Notice that nvm is not loaded.

### Expected behavior

NVM should load.

### OS / Linux distribution

macOS Big Sur with Apple Silicon

### Zsh version

5.8

### Oh My Zsh version

master (4a988c4)

### Terminal emulator

iTerm2

**Comment by carlosala** [comment]
Could you please share where's NVM located in M1 homebrew? Let's see if we can solve it!

**Comment by hartbit** [comment]
It's located at `/opt/homebrew/opt/nvm/nvm.sh`, and the `HOMEBREW_PREFIX` environment variable is equal to `/opt/homebrew`.

**Comment by hartbit** [comment]
What might actually be even more useful is the result of `brew --prefix nvm`

**Comment by asharpe** [comment]
> What might actually be even more useful is the result of `brew --prefix nvm`

I'm on an m1...
```
$ brew --prefix nvm
/opt/homebrew/opt/nvm
```

Seems the readme is a bit lacking.  What are the expectations of this plugin when there are no node versions installed, at all?!

nvm help says

```
Node Version Manager (v0.39.1)

Note: <version> refers to any version-like string nvm understands. This includes:
  - full or partial version numbers, starting with an optional "v" (0.10, v0.1.2, v1)
  - default (built-in) aliases: node, stable, unstable, iojs, system
  - custom aliases you define with `nvm alias foo`
```

So "default" is already an alias of "system", so I'd expect [this alias not to be much help](https://stackoverflow.com/a/62221445)!

My issue is that this plugin is being noisy unless every directory has access to a node version or `.nvmrc`, which is absurd unless we're expecting everyone to create a `/.nvmrc` or install a global node version.  Assuming I'm on the right track, this is what should be documented.

**Comment by mcornella** [comment]
A workaround at the moment is to use `NVM_HOMEBREW` to set the right directory, before Oh My Zsh loads:
```sh
NVM_HOMEBREW="$(brew --prefix nvm)"
```
I support making the change though, and to be extra cautious about calls to `brew` we can check for the value of `HOMEBREW_PREFIX` before:
```patch
diff --git a/plugins/nvm/nvm.plugin.zsh b/plugins/nvm/nvm.plugin.zsh
index 3ef8cc1d..b8f28c27 100644
--- a/plugins/nvm/nvm.plugin.zsh
+++ b/plugins/nvm/nvm.plugin.zsh
@@ -16,7 +16,7 @@ if [[ -f "$NVM_DIR/nvm.sh" ]]; then
 else
   # Otherwise try to load nvm installed via Homebrew
   # User can set this if they have an unusual Homebrew setup
-  NVM_HOMEBREW="${NVM_HOMEBREW:-/usr/local/opt/nvm}"
+  NVM_HOMEBREW="${NVM_HOMEBREW:-${HOMEBREW_PREFIX:-$(brew --prefix)}/opt/nvm}"
   # Load nvm from Homebrew location if it exists
   if [[ -f "$NVM_HOMEBREW/nvm.sh" ]]; then
     source "$NVM_HOMEBREW/nvm.sh" ${NVM_LAZY+"--no-use"}
```
