### ISSUE TITLE
Aliases plugin not working

### ISSUE THREAD

**Issue by StigoSvK** [ohmyzsh/ohmyzsh#10796]
### Describe the bug

Hi. When I try to use aliases plugin I got `[error] No python executable detected` 

### Steps to reproduce

`acs git` -> `[error] No python executable detected`

### Expected behavior

Return list of available git aliases

### OS / Linux distribution

macOS Monterey 12.3

### Zsh version

5.8

### Terminal emulator

macOS terminal

**Comment by carlosala** [comment]
Could you share the output of `which python` and `which python3`?

**Comment by StigoSvK** [comment]
@carlosala sure. FYI I didn't do anything with python

```
❯ which python
python not found
```

```
❯ which python3
/usr/bin/python3
```

**Comment by carlosala** [comment]
Yes, we found the problem. `python` is not defined in your system. This is going to be solved very soon. Thanks for the report!

**Comment by carlosala** [comment]
Related: #10469

**Comment by StigoSvK** [comment]
Ok thanks for your quick response. Awesome support
