### ISSUE TITLE
oh-my-zsh enters to .oh-my-zsh catalogue after installation

### ISSUE THREAD

**Issue by musialny** [ohmyzsh/ohmyzsh#10798]
### Describe the bug

oh-my-zsh enters to .oh-my-zsh catalogue after installation

### Steps to reproduce

Just install it on (clean) system

### Expected behavior

Should be in home dir?

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/38112820/160008733-96aff84f-d214-4afd-b531-cde3cf3fd16b.png)

### OS / Linux distribution

Windows 10

### Zsh version

5.8

### Terminal emulator

Windows Terminal

### If using WSL on Windows, which version of WSL

WSL2

### Additional context

Commit hash: 4dce175e0e4a678b7f93be80c64247c8f5fbab3e

**Comment by mcornella** [comment]
Confirmed. This is a side-effect of https://github.com/ohmyzsh/ohmyzsh/commit/59c40eee8e9232f556e9d4c8c97eb1b866846af3. Should be easy to fix.

**Comment by carlosala** [comment]
Looks like a `cd` would do the job👌🏻

**Comment by mcornella** [comment]
@musialny can you check #10804? You can use the URL below to test the installer:
```
https://raw.githubusercontent.com/mcornella/ohmyzsh/fix/installer-cd/tools/install.sh
```
