### ISSUE TITLE
zsh is not enabled at launch with iTerm2's "Send text at start" setting 

### ISSUE THREAD

**Issue by OneUpWallStreet** [ohmyzsh/ohmyzsh#10802]
### Describe the bug

I just noticed that when I'm using ITerm2's "Send text at start" setting with a string that contains single quotes -> ', than iTerm's new window starts with a 

`quote>` 

Instead of 

 `~`

The string that I was using was "What's Up", therefore zsh thought that the single quote after "What" was not closed. 

So for me to use zsh I have to first close the quote with a single quotation mark "'".  After that zsh work's as it shoud!

### Steps to reproduce

1. Enable "Send text at start" setting in iTerm2's  which can be found at Preferences -> Profiles 
2. Set the text to a string which contains a open single quotation mark. For example "What's Up", "That's It"
3. Open a new window of ITerm2.

### Expected behavior

After you reproduce the problem, the new window should open with a  `quote>` instead of normal zsh. It's expecting me to close the single quotation mark in the string.

### Screenshots and recordings

iTerm2 Issue's Screenshot
![iTerm2 Issue's Screenshot](https://user-images.githubusercontent.com/76121542/160272197-8d725f65-3366-4e3b-a567-26a012fe92ac.png)

Preferences Screenshot
![Preferences Screenshot](https://user-images.githubusercontent.com/76121542/160272200-46e4e424-5b0b-4560-b592-918df0ff9139.png)

### OS / Linux distribution

MacOS 12.2.1

### Zsh version

5.8

### Terminal emulator

iTerm2

**Comment by OneUpWallStreet** [comment]
Just noticed that after removing the quotation mark, ohmyzsh runs the iTerm2's text at start string as if it's a launch option. 
![issueScreenshot](https://user-images.githubusercontent.com/76121542/160272436-0616a1bb-9767-46e6-b99a-a19212d1b370.png)

**Comment by rwmitchell** [comment]
Working as expected. You can’t do that. That isn’t what iTerm2’s send text is for.

**Comment by mcornella** [comment]
You need to add a second layer of quoting. `"\"What's up\""` should work. Not an Oh My Zsh's issue.

**Comment by OneUpWallStreet** [comment]
> Working as expected. You can’t do that. That isn’t what iTerm2’s send text is for.

My bad 😅, I'm still learning all this. Sorry about the spam. Also thank you for the tip @mcornella :D

**Comment by rwmitchell** [comment]
I don't think @mcornella's help is going to do much.  The text sent by ITerm2 is still going to the shell.  This:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/15944841/160280788-c1c48309-3715-424f-ad1f-0b6fa7e0ace2.png">
will result in:

```zsh: command not found: "What's up"```

after the window opens and you hit return.

You could precede it with ```print``` but then you'll see both the command and the output, which will just be ugly.

You could add the command to the end of .zshrc or better, .login - @mcornella  can certainly give better suggestions there.

Since you're on a mac, you could also use ```say``` and have the computer greet you with a little more personality.

**Comment by mcornella** [comment]
> I don't think @mcornella's help is going to do much.

Well yeah, I was only commenting on the quoting part 😁 

If you want to display a message on login (commonly referred as [MOTD](https://en.wikipedia.org/wiki/Motd_%28Unix%29)) you can use `/etc/motd` (will apply to all users). See this related guide: https://sixcolors.com/post/2020/03/quick-tip-customize-your-terminal-login-with-a-message-of-the-day/
