### ISSUE TITLE
Error message when attempting to run alias: omz update

### ISSUE THREAD

**Issue by technix64** [ohmyzsh/ohmyzsh#10809]
### Describe the bug

When I attempt to run the alias omz update, I get the following output:

```
_omz::update:cd:1: no such file or directory: 117
fatal: not a git repository (or any of the parent directories): .git
zsh: can't open input file: 117/tools/upgrade.sh
```

### Steps to reproduce

run command omz update

### Expected behavior

Normally Oh My ZSH will check with the master repository and update accordingly.

### OS / Linux distribution

Ubuntu 18.04.6 LTS Bionic Beaver

### Zsh version

5.8

### Oh My Zsh version

See "Additonal context"

### Terminal emulator

GNOME Terminal

### Additional context

Also when I run: omz version, I get the following output:

_omz::version:cd:2: no such file or directory: 117
<detached> ()

**Comment by mcornella** [comment]
What does `echo $ZSH` show?

**Comment by baptistecs** [comment]
I am having a similar issue when opening a new terminal tab:
<img width="538" alt="Screen Shot 2022-04-19 at 09 36 31" src="https://user-images.githubusercontent.com/50966051/163950486-cbfe2fcb-330a-4543-b0b3-68da1232cd55.png">

**Comment by rwmitchell** [comment]
How did you install OMZ?
Any reason the .git subdirectory would have gotten deleted or moved?

**Comment by baptistecs** [comment]
Probably by using curl (I don't recall).

It only when opening tab from a folder not having a parent folder with a .git folder.

I tried disabling all OMZ plugins without success.

It looks like this occurred since the last OMZ update, but it might be linked to me cleaning up some project folders 🤷

**Comment by mcornella** [comment]
Look at your `history` for commands that might have deleted the `$ZSH` folder. If you can't find it, open a new issue with more details. This one is subtly unrelated.
