### ISSUE TITLE
Auto Update Git Issue

### ISSUE THREAD

**Issue by dipayand** [ohmyzsh/ohmyzsh#10801]
[oh-my-zsh] Would you like to update? [Y/n] Y

Updating Oh My Zsh
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
There was an error updating. Try again later?

**Comment by mcornella** [comment]
See https://github.com/ohmyzsh/ohmyzsh/issues/10778
