### ISSUE TITLE
OpenWrt: Won't Install

### ISSUE THREAD

**Issue by Games-Crack** [ohmyzsh/ohmyzsh#10807]
### Describe the bug

Oh My ZSH Wont install

### Steps to reproduce

get a OpenWRT Router, install git and zsh and try to install Oh My Zsh

### Expected behavior

Oh My Zsh should install

### Screenshots and recordings

```
root@Router:~#  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
Cloning Oh My Zsh...
git: 'remote-https' is not a git command. See 'git --help'.
/root
Error: git clone of oh-my-zsh repo failed
```

### OS / Linux distribution

OpenWRT

### Zsh version

5.8

### Oh My Zsh version

current

### Terminal emulator

Windows Terminal

**Comment by mcornella** [comment]
See https://stackoverflow.com/a/52689882/5798232.
