### ISSUE TITLE
Install script doesn't work on Ubuntu 12.04

### ISSUE THREAD

**Issue by semirenko** [ohmyzsh/ohmyzsh#1081]
This is what I got running the install script: 

Looking for an existing zsh config...
Found ~/.zshrc. [0;32]Backing up to ~/.zshrc.pre-oh-my-zsh
Using the Oh My Zsh template file and adding it to ~/.zshrc
Copying your current PATH and adding it to the end of ~/.zshrc for you.
Time to change your default shell to zsh!
chsh: option requires an argument -- 's'
Usage: chsh [options] [LOGIN]

Options:
  -h, --help                    display this help message and exit
  -s, --shell SHELL             new login shell for the user account

 ....is now installed.
/usr/bin/env: zsh: No such file or directory
sh: 36: source: not found

Just can't start zsh to work. 
Log out didn't help.

Tried to change shell to zsh with chsh -s /bin/zsh
chsh: /bin/zsh is an invalid shell

**Comment by JamiesonWarner** [comment]
Fedora 22: `sudo dnf install zsh`

**Comment by tanchao90** [comment]
I got the same error. How to fix? Some one help me
```sh
chsh -s $which zsh
Password: 
chsh: zsh is an invalid shell

# Base system Debian GNU/Linux 8(jessie)64-bit
$ uname -a
Linux debian-xxx 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 
```

**Comment by mcornella** [comment]
@tanchao90 first install zsh: `sudo apt install zsh`; then run `chsh -s $(which zsh)`.

**Comment by tanchao90** [comment]
@mcornella ths
