### ISSUE TITLE
Weird environment/shell variables with commands handling when using Heredoc

### ISSUE THREAD

**Issue by nontw** [ohmyzsh/ohmyzsh#10821]
### Describe the bug

I expected a variable substitution in a heredoc.  For example:
``` sh
> a=helloworld
> cat <<EOF
> export a=$a
> EOF
```

This should print _export a=helloworld_.  Instead, it prints _export a=_  There's nothing after the equal sign.  And not only that, **_a_** is also changed to be blank.  That is, after the cat command with heredoc above, the value of _a_  becomes blank.

I tested this with sh and zsh with OMZ, both work as described in the expected behavior.

### Steps to reproduce
``` sh
prompt> abc=alpha
prompt> cat <<EOF
heredoc> export abc=$abc
heredoc> EOF
export abc=
prompt> echo $abc
_<<NOTHING>>_
```

### Expected behavior

```sh
sh-5.1$ abc=alpha
sh-5.1$ cat <<EOF
> export abc=$abc
> EOF
export abc=alpha
sh-5.1$ echo $abc
alpha
```

### OS / Linux distribution

Manjaro Linux

### Zsh version

5.8.1

### Oh My Zsh version

master (53863e7)

### Terminal emulator

Gnome Terminal

**Comment by mcornella** [comment]
I can't reproduce this. It's not clear, is this only happening with Oh My Zsh? Can you check if commenting out the `source $ZSH/oh-my-zsh.sh` line in the zshrc file makes it happen as well?

**Comment by mcornella** [comment]
Can you capture a trace of your configuration so I can help you debug this? This is a weird problem and I'd like to know the culprit.

You can capture the trace by running this command:
```sh
zsh -xvlic exit &> ~/omz-debug.log
```
Then send the `omz-debug.log` file to <marc@ohmyz.sh>, since it might have sensitive information. Thanks

**Comment by nontw** [comment]
@mcornella I think I found the root cause.  It looks like fasd is the culprit, both the plugin and the minimal setup.  Removing both resolves this issue for me.  

Thank you very much for the support!
