### ISSUE TITLE
jsontools not working on startup

### ISSUE THREAD

**Issue by IntelligentFunction** [ohmyzsh/ohmyzsh#10834]
### Describe the bug

jsontools plugin does not prettify json without first doing "omz reload"

### Steps to reproduce

open terminal
type "curl https://coderwall.com/bobwilliams.json | pp_json"

Json not formatted with curly braces
type "omz reload"
Json now formatted with curly braces

### Expected behavior

open new terminal session
type "curl https://coderwall.com/bobwilliams.json | pp_json"
Json is prettified correctly with curly braces

### Screenshots and recordings

<img width="1075" alt="Screenshot 2022-04-07 at 23 54 10" src="https://user-images.githubusercontent.com/18227317/162332556-a594cfa9-5cfc-4aaa-8932-bca308599c84.png">

### OS / Linux distribution

macOS

### Zsh version

5.8

### Terminal emulator

iTerm2

### Additional context

works properly after omz reload, but needs that every time. Should just work on starting terminal session

**Comment by rwmitchell** [comment]
I'm getting the expected behavior and have a similar environment to yours.

Are you adding jsontools to your plugins before sourcing oh-my-zsh.sh ?

**Comment by kuang22** [comment]
I met similar problem, after I update my macOS, the zsh-syntax-highlight is not working on startup, After reload it will work well.
My OS is also macOS, zsh version 5.8 and using kitty as terminal emulator.
Hope this issue could be resolved.

**Comment by mcornella** [comment]
Probably a `$PATH` issue. `node`, `ruby` or `python3` must be in `$PATH` before the `source $ZSH/oh-my-zsh.sh` line, otherwise the plugin exits and doesn't set up the functions.

This is how it should look like in your `.zshrc` file:

```
# Set up $PATH as needed
PATH="$PATH:/any/other/paths"

# Other configurations...

plugins=(... jsontools ...)

source $ZSH/oh-my-zsh.sh

# Other configurations...
```

I believe currently something like [`jq`](https://jqlang.github.io/jq/) or [`fx`](https://fx.wtf/) are more helpful for JSON data.
