### ISSUE TITLE
Error When Clicking `Tab` Button For Auto Completion.

### ISSUE THREAD

**Issue by createvi** [ohmyzsh/ohmyzsh#10837]
### Describe the bug

When i use `Tab` button to auto complete it returns an [error](https://imgur.com/F3wse9i0). I am using on kali linux.
There is no issue when using bash but this problem occurs when using zsh. 

### Steps to reproduce

Type `sudo apt upda` and press `Tab`

### Expected behavior

It Should auto fill.

### Screenshots and recordings

![error zsh](https://user-images.githubusercontent.com/93326280/162556223-c5840c4b-bcd4-4899-9094-d74d2195c9b7.png)

### OS / Linux distribution

Kali GNU/Linux Rolling. 64 bit. 

### Zsh version

5.8.1

### Terminal emulator

xterm

**Comment by carlosala** [comment]
Looks like your problem is that Zsh is trying to find those functions the 5.8 directory, and you have 5.8.1 installed. Try to reboot your computer and, if this doesn't work, please post here your `zshrc` to try to debug a little.

**Comment by createvi** [comment]
Rebooting worked, Thank you
