### ISSUE TITLE
update error: aborting 

### ISSUE THREAD

**Issue by fiver22** [ohmyzsh/ohmyzsh#10844]
### Describe the bug

on auto update: 
```
[oh-my-zsh] Would you like to update? [Y/n] 
Updating Oh My Zsh
error: The following untracked working tree files would be overwritten by merge:
        plugins/charm/README.md
        plugins/charm/charm.plugin.zsh
Please move or remove them before you merge.
Aborting
There was an error updating. Try again later?
```
similar occurs with git pull
```
git pull origin master
From https://github.com/ohmyzsh/ohmyzsh
 * branch            master     -> FETCH_HEAD
Updating 3f21432..846f417
error: The following untracked working tree files would be overwritten by merge:
        plugins/charm/README.md
        plugins/charm/charm.plugin.zsh
Please move or remove them before you merge.
Aborting


```
and 
```

omz update
Updating Oh My Zsh
error: The following untracked working tree files would be overwritten by merge:
        plugins/charm/README.md
        plugins/charm/charm.plugin.zsh
Please move or remove them before you merge.
Aborting
```
my .zshrc
```

export PATH=$HOME/bin:/usr/local/bin:/home/jayelem/spicetify-cli:$PATH

ZSH_THEME="maran"

plugins=(git sudo)

source $ZSH/oh-my-zsh.sh

((various aliases that don't seem related))

 
```

This is on a newish Fedora 35 install -I have the same .zshrc on various ubuntu and debian installs and the issue does not appear there. 

### Steps to reproduce

open terminal when omz is set to update
or
update omz with git pull origin master
or
run omz update

### Expected behavior

omz updates

### OS / Linux distribution

Fedora 35

### Zsh version

5.8.1

### Terminal emulator

konsole 21.12.2

**Comment by mcornella** [comment]
It looks like you added the charm plugin manually or via other means. The update cannot continue because it would overwrite those files. If you run `rm -r $ZSH/plugins/charm`, the update process will be able to resume.

**Comment by fiver22** [comment]
Thanks very much, mcornella -that solved it. I'm have no idea how the charm plugin could have been added -but I don't doubt you're correct.
Appreciate your help.
