### ISSUE TITLE
'defining function based on alias `dls' error when using both docker and systemadmin plugins

### ISSUE THREAD

**Issue by DmitrySandalov** [ohmyzsh/ohmyzsh#10851]
`oh-my-zsh` version: `[master c6f0504]`

Plugins in `~/.zshrc`
```
plugins=(
  docker
  systemadmin
)
```

Try opening new shell.

Expected: no errors
Observed: 
```
/home/myuser/.oh-my-zsh/plugins/systemadmin/systemadmin.plugin.zsh:37: defining function based on alias `dls'
/home/myuser/.oh-my-zsh/plugins/systemadmin/systemadmin.plugin.zsh:37: parse error near `()'
```

```
$ alias | grep 'dls='
dls='docker container ls'
$ declare -f dls
< blank >
```

https://github.com/ohmyzsh/ohmyzsh/blob/c6f0504cf0f75bc17cc422e82fdb84f0c994c461/plugins/systemadmin/systemadmin.plugin.zsh#L37
https://github.com/ohmyzsh/ohmyzsh/blob/c6f0504cf0f75bc17cc422e82fdb84f0c994c461/plugins/docker/docker.plugin.zsh#L8

**Comment by tunguyen9889** [comment]
The `dls` alias in docker plugin was introduced in this PR https://github.com/ohmyzsh/ohmyzsh/pull/6527, need to make another alias to avoid name conflict.

**Comment by mcornella** [comment]
@abhinavmanchanda can we rename the `dls` and `dlsa` aliases to avoid a conflict?

**Comment by abhinavmanchanda** [comment]
Sure, give me a couple of hours.

**Comment by abhinavmanchanda** [comment]
@mcornella I've created the following pull request - 

https://github.com/ohmyzsh/ohmyzsh/pull/10852

I noticed that you've already pushed a fix to the conflict. If you feel the PR is not needed, please reject it.

**Comment by abhinavmanchanda** [comment]
Got it.
