### ISSUE TITLE
[oh-my-zsh] Can't update: not a git repository.

### ISSUE THREAD

**Issue by RetroParody** [ohmyzsh/ohmyzsh#10861]
### Describe the bug

Every time I boot up the terminal I get the message `[oh-my-zsh] Can't update: not a git repository.`
Is there anything to do about this?

### Steps to reproduce

1.I open my terminal
2.`[oh-my-zsh] Can't update: not a git repository.` message pops up

### Expected behavior

Usually when I open terminal it asks if I would like to update

### Screenshots and recordings

<img width="360" alt="Screen Shot 2022-04-15 at 6 43 43 PM" src="https://user-images.githubusercontent.com/96367916/163584785-c8eebe17-df3a-4a4a-9ebe-0652dfb5bf2f.png">

### OS / Linux distribution

MacOS 12.3.1 

### Zsh version

5.8

### Oh My Zsh version

N/A

### Terminal emulator

terminal.app

### Additional context

Also when I try to check for Oh My Zsh version it says `<detached> ()`

<img width="337" alt="Screen Shot 2022-04-15 at 6 48 46 PM" src="https://user-images.githubusercontent.com/96367916/163585318-06f2cbf5-dc39-44b6-a5bd-0701eda2a824.png">

**Comment by mcornella** [comment]
How did you install OMZ?

**Comment by RetroParody** [comment]
> How did you install OMZ?

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

I used the curl command

**Comment by RetroParody** [comment]
<img width="708" alt="Screen Shot 2022-04-18 at 7 49 56 PM" src="https://user-images.githubusercontent.com/96367916/163834969-5fd7dbba-9aaa-4647-8669-d0001d4ea796.png">
 
I'm having issues running this command

**Comment by rwmitchell** [comment]
> 

That’s a lot of faith ZSH is set properly.

**Comment by RetroParody** [comment]
<img width="424" alt="Screen Shot 2022-04-18 at 8 06 12 PM" src="https://user-images.githubusercontent.com/96367916/163840480-7b725d5e-1e88-4d45-a927-e93ff1daf541.png">

**Comment by rwmitchell** [comment]
Of course. You deleted above and then it failed to install, so you no longer have it. 

Do you have the Xcode command line tools installed?

**Comment by RetroParody** [comment]
> Of course. You deleted it above and then it failed to install, so you no longer have it.
> 
> Do you have the Xcode command line tools installed?

Yes, I have Xcode command line tools installed

**Comment by rwmitchell** [comment]
Have you updated the OS since you installed the Xcode command line utilities?  If so, reinstall:

```xcode-select --install```

Even if you haven't, run that anyway just to verify they are current.

**Comment by mcornella** [comment]
The [missing xcrun error is solved](https://stackoverflow.com/a/52522566) by running the command posted by Richard above:
```sh
xcode-select --install
```

Then you can re-run the `git clone` command above:
```sh
git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git "${ZSH:-$HOME/.oh-my-zsh}"
```

After that, re-run zsh with `exec zsh` and you should be good to go.

**Comment by RetroParody** [comment]
Yup everything is working, thanks for the help

**Comment by raminf** [comment]
On a Mac, if the xcode command-line license agreement has been updated and needs to be accepted, any tool that has dependencies on it can fail. In this case, the 'git' command that does the oh-my-zsh update checking is failing. 

To solve, issue following and type 'agree' to accept the license terms:

`sudo xcodebuild -license`

This solved it for me.

**Comment by tomharrisonjr** [comment]
I had the same issue because I moved the location of the original git clone, and forgot to copy the `.` files.

To avoid redoing my custom changes, I just cloned into another directory and copied the `.` files over.  (No `rm -rf` involved :-) )

**Comment by noahsbwilliams** [comment]
If anyone else is running into issues after the macOS 12.6 update, this worked for me:

I kept getting an error loop prompting me to install the Xcode command line tools. It would say it succeeded but then running `git --version` would throw a bunch of unintelligible nonsense and prompt me to install them again.

I ultimately used [AppCleaner](https://freemacsoft.net/appcleaner/) to locate all of Xcode's settings folders and delete everything but the Xcode binary itself. I then opened the Xcode app and accepted the install prompts which fixed the CLI tools. 

Then I reran the usual oh-my-zsh installer script and everything was dandy!

**Comment by rwmitchell** [comment]
I had a similar problem this morning, seemed to be in a constant loop of wanting to install.  I eventually broke out of it with:

```xcodebuild -runFirstLaunch```

In my case, it needed to authenticate with PIV card, which it finally prompted for.

**Comment by YutoYasunaga** [comment]
I had same issue. Just updated Xcode worked for me.

**Comment by StarWars** [comment]
I've been using numerous instances of Xcode, and before the Xcode 14 update, I set the developer path in ZSH to be:
`/Applications/Xcode-13.3.1.app/Contents/Developer` and I forgot about it. So after the update when the name of Xcode got changed to simply `Xcode.app`, ZSH did not know where to look for the xcode tools.

Running the command suggested above in this thread, has hinted me how to resolve the issue, here's an excerpt:

`git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git "${ZSH:-$HOME/.oh-my-zsh}"`
`xcrun: error: active developer path ("/Applications/Xcode-13.3.1.app/Contents/Developer") does not exist`

And the solution was simple:
`sudo xcode-select --switch /Applications/Xcode.app/` - before running it, check how Xcode is called in the Applications folder on your machine :)

**Comment by tholu** [comment]
Starting Xcode after updating and agreeing to the license fixed it for me.

**Comment by ChristopherDavisUCI** [comment]
In case it's helpful to anyone else, typing capital `G` got me to the end of the license agreement.

**Comment by sobolevdmitry** [comment]
On a Mac use `sudo xcode-select -switch /Library/Developer/CommandLineTools` after update.

**Comment by vasco3** [comment]
I just had this error today in my MacBook.
I found out that I had to agree to the new Xcode license terms

1. `sudo xcodebuild -license  `
2. scroll down to the bottom of the license and type "agree"

then it still didn't work but it warned that I had to reinstall something from Xcode
`xcodebuild -runFirstLaunch`

that was the solution for me

**Comment by sidsarasvati** [comment]
> I just had this error today in my MacBook. I found out that I had to agree to the new Xcode license terms
> 
> 1. `sudo xcodebuild -license  `
> 2. scroll down to the bottom of the license and type "agree"
> 
> then it still didn't work but it warned that I had to reinstall something from Xcode `xcodebuild -runFirstLaunch`
> 
> that was the solution for me


Right. This might not be a git problem if you had things workings. 
One way to check is: 
$ cd $ZSH
$ git log 

<img width="588" alt="image" src="https://user-images.githubusercontent.com/2634859/191053473-8ab585d6-c5a1-49ef-b6d3-e0a60450406e.png">

**Comment by ulte** [comment]
adding additional notes to this:
that error flagged after oh-my-zsh.sh ran
```
source $ZSH/oh-my-zsh.sh
````
and as @sidsarasvati mentioned, checking the git log did indeed show
```
git: error: MacOSX.sdk -find git 2> /dev/null
[requesting installation of command line developer tools.](xcode-select: Failed to locate 'git', requesting installation of command line developer tools.)
```
thus following @vasco3's directions above nailed it for me as well. Thanks all!

**Comment by TXLogic** [comment]
@noahsbwilliams Thanks, was having exactly that problem after upgrading to MacOS 12.6. Your solution worked perfectly.

**Comment by srinathLN7** [comment]
> It looks like the OMZ folder is missing the `.git` directory. Maybe it got deleted or something. Try reinstalling it by removing the directory and cloning it back in the same place:
> 
> > **NOTE: before running `rm -rf "$ZSH"` make sure the value of `$ZSH` is correct. It should point to the directory where you installed Oh My Zsh, which by default is at `$HOME/.oh-my-zsh`**
> 
> ```shell
> rm -rf "$ZSH"
> git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git "$ZSH"
> ```
> 
> You should be able to update again after that.

As simple as it was. Thank you, it worked!
