### ISSUE TITLE
boot2docker deprecated

### ISSUE THREAD

**Issue by valdeirpsr** [ohmyzsh/ohmyzsh#10877]
### Describe the bug

The project boot2docker was discontinued in 2018 and abandoned in 2021 according to the project page

https://github.com/boot2docker/boot2docker

### Steps to reproduce

-

### Expected behavior

-

### OS / Linux distribution

All

### Zsh version

5.8

### Terminal emulator

Gnome Terminal

**Comment by carlosala** [comment]
Maybe we should soft-deprecate the plugin. @mcornella, do you agree?

**Comment by mcornella** [comment]
Definitely, I'll remove it this afternoon. It's been 2 years almost so we can just remove it entirely.
