### ISSUE TITLE
Themes should not show ".local" in prompts

### ISSUE THREAD

**Issue by reagle** [ohmyzsh/ohmyzsh#10871]
### If the feature request is for a plugin or theme, specify it here.

gnzh

### If the feature solves a problem you have, specify it here.

Mac hostnames end in ".local", which need not be shown at the shell prompt. I'm using gnzh now with this problem, but others may suffer with this as well.

### Describe the proposed feature.

As [discussed on Reddit](https://www.reddit.com/r/MacOS/comments/u7zfyd/how_to_remove_local_from_prompts_host/i5j4z3m/)

> [https://github.com/ohmyzsh/ohmyzsh/blob/master/themes/gnzh.zsh-theme#L22](https://github.com/ohmyzsh/ohmyzsh/blob/master/themes/gnzh.zsh-theme#L22) looks like they're using %M rather than %m. Maybe they'd like a patch to make that optional? Some extra variable that toggles between %m and %M on lines 22/24 of that file.
> 
> Maybe just open a github issue and request the feature. It shouldn't be hard to implement. 
> 
> Even simpler than toggling it, one could just use different logic in the two sides of that "is this an ssh connection?" conditional. Arguably, for SSH connections it should be fully qualified %M (you really don't want to mistake which machine you're on) and for non-SSH connections it should be just the local part %m. Do you see what I mean? Locally, %M is overkill and makes the prompt excessively long.
> 
> [https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html#Login-information](https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html#Login-information):
> 
> >%M  
> The full machine hostname.  
> %m  
> The hostname up to the first ‘.’. An integer may follow the ‘%’ to specify how many components of the hostname are desired. With a negative integer, trailing components of the hostname are shown.

**Comment by robbyrussell** [comment]
@reagle I went ahead and made this change to the theme for you. Sorry for the latency! :v:
