### ISSUE TITLE
Improper/Invalid installation command for Termux

### ISSUE THREAD

**Issue by scrazzz** [ohmyzsh/ohmyzsh#10880]
### Describe the bug

I tried installing zsh as per the [guide here for Termux](https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH#termux-android) and I get the following error when I try to make zsh the default shell.

### Steps to reproduce

```console
~ $ pkg install zsh
~ $ chsh -s $(which zsh) # attempt 1
/data/data/com.termux/files/usr/bin//data/data/com.termux/files/usr/bin/zsh is not an executable file!
~ $ chsh -s /data/data/com.termux/files/usr/bin/zsh # attempt 2
/data/data/com.termux/files/usr/bin//data/data/com.termux/files/usr/bin/zsh is not an executable file!
```

### Expected behavior

No errors should occur.

### OS / Linux distribution

Android 11 (aarch64)

### Zsh version

5.8.1

### Terminal emulator

Termux

**Comment by mcornella** [comment]
Looks like the path you're supplying gets prefixed with `/data/data/com.termux/files/usr/bin` (is that the value of `$PREFIX`?).
Try `chsh -s zsh`.

**Comment by mcornella** [comment]
In fact that's how the installer does it: https://github.com/ohmyzsh/ohmyzsh/commit/fd4571d1b02ac68833a5b5c166395434723b9128. You shouldn't need to make it manually yourself.

**Comment by mcornella** [comment]
Instructions on the wiki have been fixed as well.
