### ISSUE TITLE
Chinese search is not supported in web-search?

### ISSUE THREAD

**Issue by luojinghui** [ohmyzsh/ohmyzsh#10884]
### Describe the bug

I use web-search in iterm2 of oh my zsh, i already install web-search plugin, when i use web-search eg:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/12367406/165008676-af54ff5a-153e-4abe-8004-eb018190e7ad.png">
web-search can successfully open web pages and use google search：
<img width="380" alt="image" src="https://user-images.githubusercontent.com/12367406/165008756-8eb19b4a-456a-4839-ab0b-035cd6b8e499.png">

But, when I type in Chinese and search, nothing happens on the web，It looks like parsing Chinese characters encountered an exception:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/12367406/165008962-e8c1986d-c6dd-4459-83f3-22c98c3521e2.png">

### Steps to reproduce

Type Chinese and search:
```bash
$ google test中文搜索23
```

### Expected behavior

Can use google search in browser.

### OS / Linux distribution

macOS 11.6

### Zsh version

5.8

### Terminal emulator

iTerm2

**Comment by mcornella** [comment]
I can reproduce. I believe we should be using `omz_urlencode` to build the URL.
