### ISSUE TITLE
Unable to enter commands such as source in ohmyzsh

### ISSUE THREAD

**Issue by EricMzky** [ohmyzsh/ohmyzsh#10887]
### Describe the bug

Unable to enter commands such as source in ohmyzsh

### Steps to reproduce

Unable to enter commands such as source in ohmyzsh

### Expected behavior

Unable to enter commands such as source in ohmyzsh

### OS / Linux distribution

ubuntu20.04

### Zsh version

The latest version

### Terminal emulator

tabby

### Additional context

Unable to enter commands such as source in ohmyzsh

**Comment by rwmitchell** [comment]
Why don’t you show some screen texts of exactly what you’re doing?

**Comment by mcornella** [comment]
Without clarification on exactly what you run and the errors you get we have no way to help you. Please open a new issue with details and fields properly filled out.
