### ISSUE TITLE
omz plugin disable Command Tool Deletes .zshrc Symlink 

### ISSUE THREAD

**Issue by silver-cat-13** [ohmyzsh/ohmyzsh#10885]
### Describe the bug

I have my config file in a repo and I set a symlink from `~/.zshrc` to my repo

```
ll ~/.zshrc
lrwxrwxrwx 1 fernando fernando 45 Apr 25 22:32 /home/fernando/.zshrc -> /home/fernando/workspace/config/desktop/zshrc
```

After I run `omz plugin disable PLUGIN` the symlink is removed and my `/home/fernando/workspace/config/desktop/zshrc` moved into `~/.zshrc`

After a 5 min search on the repo. It seems the issue is how `omz` handles the `disable` [action](https://github.com/ohmyzsh/ohmyzsh/blob/30e23a643ba4f892c42e8d8d8a2ab31a6e68a9a6/lib/cli.zsh#L283) by creating a new `$zdot/.zshrc.new` file and then replacing `$zdot/.zshrc.new` with the original `$zdot/.zshrc` (`mv -f "$zdot/.zshrc.new" "$zdot/.zshrc"`)

I did not test this issue with other `omz plugins` commands. I do not know if `omz plugins enable` also fails but by looking into the code it should behave the same

### Steps to reproduce

Disable any plugin while the `zshrc` config file is a symlink 
```
❯ ls -l ~/.zshrc
lrwxrwxrwx 1 fernando fernando 45 Apr 25 22:32 /home/fernando/.zshrc -> /home/fernando/workspace/config/desktop/zshrc

❯ omz plugin disable fzf
omz::plugin::disable: plugins disabled: fzf.

❯ ls -l ~/.zshrc
-rw-rw-r-- 1 fernando fernando 5.0K Apr 25 22:38 /home/fernando/.zshrc
```

### Expected behavior

I expect the symlink to remain like:

```
❯ ls -l ~/.zshrc
lrwxrwxrwx 1 fernando fernando 45 Apr 25 22:32 /home/fernando/.zshrc -> /home/fernando/workspace/config/desktop/zshrc

❯ omz plugin disable fzf
omz::plugin::disable: plugins disabled: fzf.

❯ ls -l ~/.zshrc
lrwxrwxrwx 1 fernando fernando 45 Apr 25 22:32 /home/fernando/.zshrc -> /home/fernando/workspace/config/desktop/zshrc
```

Or get a warning/error message at least. This is silently replacing how I have my configuration with no easy way to find out

### OS / Linux distribution

POP OS 20.04

### Zsh version

5.8

### Oh My Zsh version

master (eb00b95)

### Terminal emulator

alacritty

**Comment by bdwalton** [comment]
Having this issue too and looked into it.

This patch fixes it, but not yet portably: https://github.com/ohmyzsh/ohmyzsh/compare/master...bdwalton:ohmyzsh:realpath-fixes.

It relies on coreutils and the realpath command. I need to find a more portable way to achieve that (and might need to rely on expecting perl to be available anywhere that matters or something. :( )...

**Comment by bdwalton** [comment]
Actually, I tweaked it to something that doesn't rely on realpath and should work on most modern platforms. For those lacking realpath(3), it should be no worse. Would this fix work for you?
