### ISSUE TITLE
Add new alias for deleting local git branches which are gone on remote

### ISSUE THREAD

**Issue by lukasbash** [ohmyzsh/ohmyzsh#10898]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### If the feature solves a problem you have, specify it here.

Too many local branches that are gone on remote.

### Describe the proposed feature.

Add a new alias to delete all local branches which are gone on remote.
Right now I am using this:
```
git fetch -p && for branch in `git branch -vv | grep ': gone]' | awk '{print $1}'`; do git branch -D $branch; done
```

**Comment by carlosala** [comment]
Closed in 8c808da23c9bafdc9d4b7b73934d6621d3a1f83e
