### ISSUE TITLE
Error: Failure while executing; git clone https://github.com/Homebrew/homebrew-cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask --origin=origin --template= exited with 128

### ISSUE THREAD

**Issue by studentofknowledge** [ohmyzsh/ohmyzsh#10899]
### Describe the bug

  I’m attempting to install gmp. When I first ran install gmp, I received this error: 

Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask --origin=origin --template=` exited with 128.

After that error, when I ran install gmp again, I received a different error. 

==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 635135, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 635135 (delta 31), reused 42 (delta 17), pack-reused 635078
Receiving objects: 100% (635135/635135), 300.30 MiB | 1.47 MiB/s, done.
Resolving deltas: 100% (449565/449565), done.
Tapped 3993 casks (4,065 files, 320.6MB).
Warning: No available formula with the name "gmp".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

I then ran several troubleshooting steps, and I will outline them below:

### Steps to reproduce

  Starting from the top:

  First I received this error running install gmp:
  
  ==> Tapping homebrew/cask
  Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
  remote: Enumerating objects: 634961, done.
  remote: Counting objects: 100% (23/23), done.
  remote: Compressing objects: 100% (11/11), done.
  error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly before end of the underlying stream
  error: 2130 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  fatal: early EOF
  fatal: fetch-pack: invalid index-pack output
  Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask --origin=origin --template=` exited with 128.
  
  Then I uninstalled Homebrew (when uninstalling Homebrew, some files were not deleted)
  Reinstalled Homebrew
  
  Then I tried to install gmp again, and received similar, but slightly different response:
  
  Running `brew update --preinstall`...
  ==> Tapping homebrew/cask
  Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
  remote: Enumerating objects: 634965, done.
  remote: Counting objects: 100% (27/27), done.
  remote: Compressing objects: 100% (15/15), done.
  error: RPC failed; curl 56 LibreSSL SSL_read: Operation timed out, errno 60
  error: 4715 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  fatal: early EOF
  fatal: fetch-pack: invalid index-pack output
  Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask --origin=origin --template=` exited with 128.
  
  I then tried again, and received a totally different response:
  
  ==> Tapping homebrew/cask
  Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
  remote: Enumerating objects: 635135, done.
  remote: Counting objects: 100% (57/57), done.
  remote: Compressing objects: 100% (40/40), done.
  remote: Total 635135 (delta 31), reused 42 (delta 17), pack-reused 635078
  Receiving objects: 100% (635135/635135), 300.30 MiB | 1.47 MiB/s, done.
  Resolving deltas: 100% (449565/449565), done.
  Tapped 3993 casks (4,065 files, 320.6MB).
  Warning: No available formula with the name "gmp".
  ==> Searching for similarly named formulae...
  Error: No similarly named formulae found.
  ==> Searching for a previously deleted formula (in the last month)...
  Error: No previously deleted formula found.
  ==> Searching taps on GitHub...
  Error: No formulae found in taps.
  
  I google searched specifically on the first error and found 
  
  https://github.com/Homebrew/homebrew-cask/issues/82273
  which indicates it’s a problem on the machine. 
  
  I followed the directions here: https://github.com/Homebrew/homebrew-cask#reporting-bugs
  
  I tried brew update-reset && brew update and received the following:
  
  ==> Fetching /usr/local/Homebrew...
  remote: Enumerating objects: 81, done.
  remote: Counting objects: 100% (36/36), done.
  remote: Total 81 (delta 36), reused 36 (delta 36), pack-reused 45
  Unpacking objects: 100% (81/81), 52.70 KiB | 574.00 KiB/s, done.
  From https://github.com/Homebrew/brew
   * [new branch]          dependabot/bundler/Library/Homebrew/rubocop-1.28.2 -> origin/dependabot/bundler/Library/Homebrew/rubocop-1.28.2
  
  ==> Resetting /usr/local/Homebrew...
  Branch 'master' set up to track remote branch 'master' from 'origin'.
  Reset branch 'master'
  Your branch is up to date with 'origin/master'.
  
  ==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
  remote: Enumerating objects: 20, done.
  remote: Counting objects: 100% (20/20), done.
  remote: Compressing objects: 100% (16/16), done.
  remote: Total 20 (delta 8), reused 16 (delta 4), pack-reused 0
  Unpacking objects: 100% (20/20), 121.84 KiB | 667.00 KiB/s, done.
  From https://github.com/Homebrew/homebrew-cask
     6012d33098..bb0d6f8129  master     -> origin/master
  
  ==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
  Branch 'master' set up to track remote branch 'master' from 'origin'.
  Reset branch 'master'
  Your branch is up to date with 'origin/master'.
  
  ==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
  
  ==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
  Branch 'master' set up to track remote branch 'master' from 'origin'.
  Reset branch 'master'
  Your branch is up to date with 'origin/master'.
  
  Already up-to-date.
  
  Then I ran brew install gmp again and received:
  
  Warning: No available formula with the name "gmp".
  ==> Searching for similarly named formulae...
  Error: No similarly named formulae found.
  ==> Searching for a previously deleted formula (in the last month)...
  Error: No previously deleted formula found.
  ==> Searching taps on GitHub...
  Error: No formulae found in taps.
  
  Then I ran brew doctor and received:
  
  Please note that these warnings are just used to help the Homebrew maintainers
  with debugging if you file an issue. If everything you use Homebrew for is
  working fine: please don't worry or file an issue; just ignore this. Thanks!
  
  Warning: Homebrew/homebrew-core was not tapped properly! Run:
    rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core"
    brew tap homebrew/core
  
  Warning: Homebrew's "sbin" was not found in your PATH but you have installed
  formulae that put executables in /usr/local/sbin.
  Consider setting your PATH for example like so:
    echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
  
  Warning: Broken symlinks were found. Remove them with `brew cleanup`:
    /usr/local/bin/prl_convert
    /usr/local/bin/prl_disk_tool
    /usr/local/bin/prl_perf_ctl
    /usr/local/bin/prlcore2dmp
    /usr/local/bin/prlctl
    /usr/local/bin/prlexec
    /usr/local/bin/prlsrvctl
    /usr/local/share/man/man8/prl_convert.8
    /usr/local/share/man/man8/prl_disk_tool.8
    /usr/local/share/man/man8/prlctl.8
    /usr/local/share/man/man8/prlexec.8
    /usr/local/share/man/man8/prlsrvctl.8
  
  then brew cleanup and received:
  
  Pruned 12 symbolic links and 1 directories from /usr/local
  
  Now, trying brew install gmp again, and getting the same second error:
  
  Warning: No available formula with the name "gmp".
  ==> Searching for similarly named formulae...
  Error: No similarly named formulae found.
  ==> Searching for a previously deleted formula (in the last month)...
  Error: No previously deleted formula found.
  ==> Searching taps on GitHub...
  Error: No formulae found in taps.
  
  
  next, brew config
  
  
  HOMEBREW_VERSION: 3.4.9-17-g80e5327
  ORIGIN: https://github.com/Homebrew/brew
  HEAD: 80e5327013c4eba4b60e2fccdc8df2762048757b
  Last commit: 5 hours ago
  Core tap ORIGIN: https://github.com/Homebrew/brew
  Core tap HEAD: 80e5327013c4eba4b60e2fccdc8df2762048757b
  Core tap last commit: 5 hours ago
  Core tap branch: master
  HOMEBREW_PREFIX: /usr/local
  HOMEBREW_CASK_OPTS: []
  HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
  HOMEBREW_MAKE_JOBS: 16
  Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  CPU: 16-core 64-bit kabylake
  Clang: 13.1.6 build 1316
  Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
  Curl: 7.77.0 => /usr/bin/curl
  macOS: 12.0.1-x86_64
  CLT: 13.3.0.0.1.1645755326
  Xcode: N/A
  
  
  after that, I closed the terminal, and tried to install gmp again
  
  Same error:
  
  Warning: No available formula with the name "gmp".
  ==> Searching for similarly named formulae...
  Error: No similarly named formulae found.
  ==> Searching for a previously deleted formula (in the last month)...
  Error: No previously deleted formula found.
  ==> Searching taps on GitHub...
  Error: No formulae found in taps.
  
  
  next tried brew install --verbose --debug FORMULA|CASK
  
  here’s the result:
  
  FORMULA|CASK
  zsh: command not found: CASK
  Warning: No available formula with the name "formula".
  Error: No similarly named formulae found.
  Error: Broken pipe
  /usr/local/Homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
  /usr/local/Homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
  /usr/local/Homebrew/Library/Homebrew/utils/popen.rb:9:in `popen_read'
  /usr/local/Homebrew/Library/Homebrew/missing_formula.rb:155:in `block in deleted_reason'
  /usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:303:in `block in cd'
  /usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:303:in `chdir'
  /usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:303:in `cd'
  /usr/local/Homebrew/Library/Homebrew/missing_formula.rb:139:in `deleted_reason'
  /usr/local/Homebrew/Library/Homebrew/missing_formula.rb:14:in `reason'
  /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:282:in `rescue in install'
  /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:140:in `install'
  /usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
  
  Then I tried again:
  
  Warning: No available formula with the name "gmp".
  ==> Searching for similarly named formulae...
  Error: No similarly named formulae found.
  ==> Searching for a previously deleted formula (in the last month)...
  Error: No previously deleted formula found.
  ==> Searching taps on GitHub...
  Error: No formulae found in taps.
  
  
  
  I noticed from the results of running brew install --verbose --debug FORMULA|CASK:
  
  This error:
  
  zsh: command not found: CASK 
  
  and I researched how to overcome that, referencing: https://github.com/ohmyzsh/ohmyzsh/issues/5611
  
  I ran:
  
  brew install cask
  
  and received:
  
  Running `brew update --preinstall`...
  Warning: No available formula with the name "cask".
  ==> Searching for similarly named formulae...
  Error: No similarly named formulae found.
  ==> Searching for a previously deleted formula (in the last month)...
  Error: No previously deleted formula found.
  ==> Searching taps on GitHub...
  Error: No formulae found in taps.
  
  
  It’s safe to say I am stumped. I’m probably going to put a request for help in github’s bug report section but want to run this by you first. Any help is greatly appreciated.
  
  Cheers
  
  Mac OS Monterey Version 12.01
  brew -v
  Homebrew 3.4.9-17-g80e5327
  Homebrew/homebrew-core (git revision 80e532701; last commit 2022-04-28)
  Homebrew/homebrew-cask (git revision bb0d6f8129; last commit 2022-04-28)
  
  

### Expected behavior

I would expect that I would receive Installation successful.

### OS / Linux distribution

MacOS Monterey 12.0.1

### Zsh version

5.8

### Terminal emulator

Terminal

**Comment by studentofknowledge** [comment]
Here's how I resolved:
Inside the brew doctor, looking specifically at this part:
Warning: Homebrew/homebrew-core was not tapped properly! Run:
 rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core"
 brew tap homebrew/core
 
Then I followed those steps:
 rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core"
 brew tap homebrew/core
then I closed the terminal and reopened it
then I was able to install gmp

**Comment by Malick44** [comment]
execute tis command and try again

rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" brew tap homebrew/core

**Comment by sapty** [comment]
tapping homebrew/core is no longer needed. if you really want to do that, use --force

**Comment by Ibtixam** [comment]
execute tis command and try again

rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" brew tap homebrew/core

Try this this is working....

**Comment by 0LING0** [comment]
> execute tis command and try again
> 
> rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" brew tap homebrew/core



> execute tis command and try again
> 
> rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" brew tap homebrew/core

great!!
