### ISSUE TITLE
Add new alias for `npm install-test`

### ISSUE THREAD

**Issue by denis-rossati** [ohmyzsh/ohmyzsh#10890]
### If the feature request is for a plugin or theme, specify it here.

npm plugin

### If the feature solves a problem you have, specify it here.

Once in a growing project (without CI/CD) I had a task that required me to go through some repos and assure that every test in the `main` branch were correct. At first I thought I could run `npm install` and `npm test` for each repo, but during the task I realized  that I could look for an `npm` command that do the same thing as me, and [it does exist!](https://docs.npmjs.com/cli/v7/commands/npm-install) So I looked for an alias in omz to be even quicker. Saddly, there is no alias for this.

### Describe the proposed feature.

Just create a alias (may `npmIt`) that runs `npm install-test`.

### Describe alternatives you've considered

In this same task I had problems with some packages that were solved using `npm install-test --force`. But I think this could be a desnecessary/forgotten alias since it solves a very specific problem.

### Additional context

 I created an alias myself in `zshrc` file, but I would like to add to the project to help anyone out there who passed the same situation as I did.

If I'm missing something, just let me know. But I already prepared a [PR](https://github.com/ohmyzsh/ohmyzsh/pull/10891) for this change.

**Comment by robbyrussell** [comment]
Tackled in https://github.com/ohmyzsh/ohmyzsh/pull/11654
