### ISSUE TITLE
File source powerlevel10k .zshrc

### ISSUE THREAD

**Issue by sergiojurcas** [ohmyzsh/ohmyzsh#10895]
### Describe the bug

Hello, do you have any open issue to fix this conflict? I was tapping the file a long ago `.zshrc` and I don’t know why I removed the source and now I get this error every time I open my hyper.js terminal

### Steps to reproduce

NOTHING HERE

### Expected behavior

A log error ocurred every time I open my terminal

### Screenshots and recordings

![Captura de pantalla 2022-04-27 a las 14 21 18](https://user-images.githubusercontent.com/22520811/165517489-11dd7e0d-ec99-430d-a6de-74018b13c385.png)

### OS / Linux distribution

MacOS 10.13 High Sierra 

### Zsh version

5.8.1

### Oh My Zsh version

master (a879ff15)

### Terminal emulator

Hyper.js

**Comment by mcornella** [comment]
It looks like you installed powerlevel10k and then removed it? You should either
1. Remove the lines that `source` it from your `.zshrc` file, **if you meant to uninstall p10k**, or
2. Install p10k again, fix the `source` lines in your `.zshrc` file so they point to the right location, **if you removed p10k by mistake**.

This is not an Oh My Zsh bug so I'll close the issue.
