### ISSUE TITLE
Weird cursor and text behaviour when tabbing through files in directory

### ISSUE THREAD

**Issue by BetweenBeltSizes** [ohmyzsh/ohmyzsh#10905]
### Describe the bug

The problem I have is when using the tab autocomplete for file / folder names: for example I have 2 files starting with "ba" ("baby" and "baby.c") if I type: "rm ba" and then hit tab, what I typed is appended again, so it shows: "rm barm baby.c". If I then hit backspace all the way, it should show nothing but "rm ba" still remains until I hit enter. I have attached my problem as a GIF below.

I tried the following tip from a forum adding something to ~/.zshrc but it had no effect:
https://apple.stackexchange.com/questions/269324/zsh-terminal-displaying-characters-and-cursor-in-the-wrong-place

Below is my ~/.zshrc file:

![Screenshot 2022-04-30 at 12 36 49](https://user-images.githubusercontent.com/40579020/166102128-44631cbb-1242-40c2-ac93-d6feb3eed89f.png)

![zshbug](https://user-images.githubusercontent.com/40579020/166102445-b6be735d-28e8-445c-97b6-7e24f19e9d4a.gif)

### Steps to reproduce

Trying to tab complete a file or directory causes everything typed to be duplicated.

### Expected behavior

Typed command should not be displayed twice and characters should disappear when deleting with backspace as well as being in right place.

### OS / Linux distribution

Mac OS Monterey 12.3.1

### Zsh version

5.8

### Terminal emulator

Terminal

**Comment by carlosala** [comment]
It looks like you have the locales problem, read further [here](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command)! If that is not your problem, feel free to reopen the issue!

**Comment by xenoplayed** [comment]
I had the same issue in an ubuntu container. The solution was to set another locale. The default locale was posix.
