### ISSUE TITLE
omz update failing

### ISSUE THREAD

**Issue by LightningRpper** [ohmyzsh/ohmyzsh#10900]
### Describe the bug

I'm trying to update Oh-my-Zsh so that all my github work can remain up to date. However, every time I run it, it gives me the following:
```
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: invalid reference: master 
```
I do not know what this means. What should I do to correct this?

### Steps to reproduce

1. Enter a folder in a github repository on the master branch.
2. Run omz update

### Expected behavior

Oh My ZSH should update with no problem

### OS / Linux distribution

Windows 10, Ubuntu

### Zsh version

()

### Terminal emulator

Windows Terminal

**Comment by Tylermarques** [comment]
For anyone else coming here. Check that your `$ZSH` directory (where ohmyzsh is installed) contains a `.git/` directory that has a valid `master` remote-url. If this has been deleted or removed somehow, reinstall ohmyzsh.

**Comment by carlosala** [comment]
What @Tylermarques says should be enough to fix it, probably the `.git` folder has been modified or something like that. Removing oh-my-zsh and reinstalling should fix your issues 👌🏻
