### ISSUE TITLE
Website Install section contains a `$` that users will copy

### ISSUE THREAD

**Issue by infn8** [ohmyzsh/ohmyzsh#10904]
### Describe the bug

On the public website in the install instructions there is a `$` to start the command.  Now, you know, and I know, that this `$` is not supposed to be copied and entered into the terminal but that will not stop people from doing just that.  

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/2447686/166072024-a76b5ce8-3b53-4523-9779-0be10b21f025.png">

I _know better_ and I just did that by not paying attention and just triple clicking to select the whole code block.

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/2447686/166072141-65418db3-f43e-4d27-9f75-690a1ee43ad7.png">

as you can see in the image above that text is selectable as is.  

### The Fix

Thankfully the fix is easy.  You can simply take the element that has the code snippet

<img width="634" alt="image" src="https://user-images.githubusercontent.com/2447686/166072358-cd3868ab-d459-4612-b1ed-4002169472bf.png">

remove the text `$ ` from the code block element 

<img width="639" alt="image" src="https://user-images.githubusercontent.com/2447686/166072387-0941f798-75d8-43d7-8913-a29ae2aab62f.png">
and that will remove it from the user selectable text on the page 
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/2447686/166072412-e91f508b-1e47-4858-833d-7ada884cce47.png">

Then you can add it back in in a non user selectable way with CSS.  This will do it

```css
p.code::before {
    content: "$ ";
}
```
That will add the `$` back as a visual cue but not make it user selectable text so that users can more easily select the text and paste what they selected directly into terminal

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/2447686/166072961-c5b431e2-b8db-489f-8d29-3fe51f5ddddd.png">

### Steps to reproduce

1. Open website
2. triple click code block
3. notice that the `$ ` is copied as well as the actual code snippet

### Expected behavior

the `$ ` should not be selectable so that users do not paste that into their terminal and get 
```
command not found: $
```

### OS / Linux distribution

MacOS 12.3.1 (21E258)

### Zsh version

latest (not actually installed yet because of the $) 

### Terminal emulator

warp.dev

**Comment by rwmitchell** [comment]
> Zsh version
> 
> latest (not actually installed yet because of the $)

Technically, it is OMZ that isn't the latest, not ZSH

**Comment by carlosala** [comment]
Most code snippets that should be shell commands have that `$` to understand that there's a command to execute.
It's a tipical issue that you copy the `$`, just do arrow up and delete it.

**Comment by rwmitchell** [comment]
I don't think @infn8 is denying it is a common, but his solution keeps the '$' on the line, just makes it separate from what gets copied which clicking the field.  It seems like a nice fix to make it easier for people.

**Comment by infn8** [comment]
That is correct. It is definitely common and this is definitely nicer. I
make the suggestion to anyone who will listen. If the website source code
is available in a repository I would be happy to generate a pull request.

**Comment by mcornella** [comment]
Let's reopen this and assign Robby's team.

**Comment by robbyrussell** [comment]
My favorite thing about this request is that it reminded me of how I originally had a designer create the Oh My Zsh logo with a `$` in it..which is a bash thing...not a zsh thing.  🤦🏻‍♂️

Anyhow, the website homepage has been updated and not longer has the '$' in it!
