### ISSUE TITLE
Strange characters in emacs-vterm

### ISSUE THREAD

**Issue by stephanoskomnenos** [ohmyzsh/ohmyzsh#10907]
### Describe the bug

2 extra lines before the first shell prompt.

## In emacs-vterm (error)

![image](https://user-images.githubusercontent.com/24674127/166229427-c04a8e5c-49ea-4227-a177-6f5a2cde162b.png)

These lines disappeared when zsh started without `.zshrc`. Also when commented `source $ZSH/oh-my-zsh.sh` in `.zshrc`.

![image](https://user-images.githubusercontent.com/24674127/166229717-6cf1ce58-a8e0-44dd-8ae6-6dcac56d8b46.png)

## In gnome-terminal (expected)

![image](https://user-images.githubusercontent.com/24674127/166230467-38a85101-6651-4348-a82e-600c9a13b07f.png)

### Steps to reproduce

1. Install ohmyzsh and set zsh as default shell
2. Install spacemacs and vterm ([https://develop.spacemacs.org/layers/+tools/shell/README.html#install](url))
3. Open vterm in spacemacs

### Expected behavior

Without these extra lines.

![image](https://user-images.githubusercontent.com/24674127/166231577-f6903bb8-d9c4-426e-8029-46aaf869d16f.png)

### OS / Linux distribution

Fedora 35

### Zsh version

5.8.1

### Oh My Zsh version

master (8f56a8bd)

### Terminal emulator

emacs-vterm

**Comment by pedrosoc** [comment]
@mcornella @robbyrussell, Can you please assign this issue to me?

I'm Brazilian, and I'm currently taking a university class with the goal of promoting open-source projects. I'm a regular user of `ohmyzsh`, and I'm highly interested in resolving this issue to contribute to the advancement of the framework!

Please add `hacktoberfest` label if it's possible :smile:

**Comment by sudh33ra** [comment]
@mcornella @robbyrussell can i pick this up please?

**Comment by carlosala** [comment]
Closing, it seems related to user configuration. Feel free to comment if someone else is able to reproduce!
