### ISSUE TITLE
vi-mode right prompt doesn't update unless window is resized

### ISSUE THREAD

**Issue by fterh** [ohmyzsh/ohmyzsh#10915]
### Describe the bug

I tried this with iTerm2 and Terminal, and it happens on both.

I enabled vi-mode plugin which is supposed to show a right prompt mode indicator. However, the indicator does not update unless the window is resized. 

https://user-images.githubusercontent.com/24870040/167272848-16541f74-ddf8-4ed9-8a4b-f97189f34fe5.mov

Here is a paste of my .zshrc: https://pastebin.com/Xs7a99U0

### Steps to reproduce

1. Enable plugin vi-mode
2. Source ~/.zshrc

### Expected behavior

The right prompt mode indicator should work without having to resize window.

### OS / Linux distribution

MacOS 12.3.1

### Zsh version

5.8

### Oh My Zsh version

master (8f56a8b)

### Terminal emulator

iTerm2

**Comment by x-delfino** [comment]
I'm experiencing the same with Alacritty instead of iTerm2. Same macOS, zsh and ohmhzsh versions

**Comment by fdelacruz** [comment]
Just noticed this here!!

**Comment by mcornella** [comment]
I have pushed a fix in #11547. Could you check it out by running `omz pr checkout 11547`, and testing out whether it works? Afterwards you can run `exit` and it will ask you whether you want to go back to `master`.
