### ISSUE TITLE
Completion support for docker compose (new Go implementation)

### ISSUE THREAD

**Issue by jasonthomasgray** [ohmyzsh/ohmyzsh#10912]
### If the feature request is for a plugin or theme, specify it here.

Docker plugin

### If the feature solves a problem you have, specify it here.

There is a new go implementation of docker-compose that is included with base docker.
This runs as a sub command of docker (`docker compose` vs `docker-compose`).

Completion works up to `docker compose` then it stops

### Describe the proposed feature.

It would be great if completion worked as it does with the docker-compose plugin but for the new subcommand implementation.

### Describe alternatives you've considered

I could continue using docker-compose but it looks like that is now [deprecated](https://www.docker.com/blog/announcing-compose-v2-general-availability/).

**Comment by aaccioly** [comment]
Looks like docker folks are working on it. https://github.com/docker/compose/issues/8550
I'm not sure of the current status of things.
One PR on the CLI side has already been merged: https://github.com/docker/cli/pull/3429
But it looks like the PR on Compose V2 sides of things haven't: https://github.com/docker/compose/pull/9462

**Comment by carlosala** [comment]
I agree, would be great to have it! Let's wait until docker guys finish it and see if it works out of the box with regular docker completion!

**Comment by layoaster** [comment]
Any news on this? Docker people already [added completions](https://github.com/docker/compose/issues/8550) for the compose plugin (v2 version)  but they are simply not working on OhMyZSH.

Apparently, completions are generated with `docker completion zsh > ~/.oh-my-zsh/completions/_docker` but somehow 
this is not working when used in conjunction with OhMyZSH. Apparently it's working well on zsh itself as reported [here](https://github.com/docker/docs/issues/16397#issuecomment-1475137268).

Keep using the v1 docker-compose is not viable as we loose any features implemented on the v2. Not having completions severely affects the adoption of the v2.

**Comment by carlosala** [comment]
I'll work on it, thanks for reporting that they already fixed it 👍👍

**Comment by layoaster** [comment]
FYI I've opened a separate [bug](https://github.com/ohmyzsh/ohmyzsh/issues/11751) that might be related but strictly refers to the native docker CLI completions and not the OhMyZSH completion provided by plugins for docker/docker-compose
