### ISSUE TITLE
install to /etc/skel

### ISSUE THREAD

**Issue by lizelive** [ohmyzsh/ohmyzsh#10920]
### If the feature solves a problem you have, specify it here.

I want new users to use zsh with ohmyzsh installed by default.

### Describe the proposed feature.

add a --skel flag or environment var that installs to skel directory so new users will get it by default

### Describe alternatives you've considered

I can install to root then copy/hardlink the relevent files to /etc/skel

### Additional context

this is for a docker image

**Comment by robbyrussell** [comment]
We'd consider a PR for something like this, but it's outside the scope of what we'll build ourselves for the project.
