### ISSUE TITLE
k3d plugin

### ISSUE THREAD

**Issue by protenhan** [ohmyzsh/ohmyzsh#10929]
### If the feature request is for a plugin or theme, specify it here.

new plugin

### If the feature solves a problem you have, specify it here.

Add auto completion for k3d CLI. 

### Describe the proposed feature.

A completion plugin for k3d

### Additional context

https://k3d.io

k3d CLI generates an [auto completion script](https://k3d.io/v5.4.1/usage/commands/k3d_completion/?h=completion) so it is easy to integrate.

**Comment by sgaist** [comment]
Hi,

I would like to implement it for Hacktober fest. Can you assign it to me ?

**Comment by mcornella** [comment]
We have decided to close this request because of a lack of user engagement. Consider reopening a new issue if there is more traction.
