### ISSUE TITLE
omz update fails for symlinked custom directory

### ISSUE THREAD

**Issue by rupkoe** [ohmyzsh/ohmyzsh#10928]
### Describe the bug

Update to latest OMZ version via `omz update` fails with:

```
error: 'custom/example.zsh' is beyond a symbolic link
fatal: Unable to process path custom/example.zsh
Cannot save the current worktree state
fatal: Cannot autostash
```

I moved the `custom/` directory to a different location and created a symlink instead. This worked w/o any problems for several updates, until the latest one.

### Steps to reproduce

1. move `$HOME/.oh-my-zsh/custom` to a different location
2. create symlink as replacement: `cd $HOME/.oh-my-zsh && ln -s <new-location-of-custom> custom`
3. try to update: `omz update`

### Expected behavior

Update completes without errors.

### OS / Linux distribution

macOS 12.3.1

### Zsh version

5.8

### Terminal emulator

Terminal (macOS built-in)

**Comment by mcornella** [comment]
Hi Rupert, that happens because you technically modified the git repository, and I believe symlinks outside a git repository are not supported. Instead, you can use the `ZSH_CUSTOM` setting to point it to wherever you moved the folder: https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#zsh_custom.

**Comment by JonathanWillitts** [comment]
> [...] Instead, you can use the `ZSH_CUSTOM` setting to point it to wherever you moved the folder: https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#zsh_custom.

It's worth noting that the symlink check is independent of the `ZSH_CUSTOM` setting. 

If the original symlink is still present, the error will persist regardless of the `ZSH_CUSTOM` value, so the symlink (quite rightly) also needs to be removed to get `omz update` working again.
