### ISSUE TITLE
Cannot update oh-my-zsh

### ISSUE THREAD

**Issue by josenafria** [ohmyzsh/ohmyzsh#10923]
### Describe the bug

I cannot update ohmyzsh since a couple of week ago and i hope you can help me.

Trying `omz update` this is the output:

```
.github/actions/spelling/README.md: needs merge
.github/actions/spelling/advice.md: needs merge
.github/actions/spelling/allow.txt: needs merge
.github/actions/spelling/excludes.txt: needs merge
.github/actions/spelling/expect.txt: needs merge
.github/actions/spelling/patterns.txt: needs merge
.github/actions/spelling/reject.txt: needs merge
error: you need to resolve your current index first
```

Having a look to oh-my-zsh repo status this is what i got (about unmerged paths) using `cd $ZSH && git status`:

```
Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add/rm <file>..." as appropriate to mark resolution)
	deleted by us:   .github/actions/spelling/README.md
	deleted by us:   .github/actions/spelling/advice.md
	deleted by us:   .github/actions/spelling/allow.txt
	deleted by us:   .github/actions/spelling/excludes.txt
	deleted by us:   .github/actions/spelling/expect.txt
	deleted by us:   .github/actions/spelling/patterns.txt
	deleted by us:   .github/actions/spelling/reject.txt
```

This repo is located at `~/.oh-my-zsh` and I am using MacOs BigSur with Apple M1 Chip

Thank you in advance! :)

### Steps to reproduce

`omz update` 

### Expected behavior

Expected to update omz

### OS / Linux distribution

macOs BigSur 11.3.1

### Zsh version

5.8

### Terminal emulator

iTerm2

**Comment by carlosala** [comment]
You have some merge conflicts, it looks like you edited those files. I'll recommend to do a `git reset --hard origin/master` and then `omz update`.
Do this in the omz folder (you can go there doing `cd $ZSH`).

Note that this commands are going to destroy every change you did in the `.oh-my-zsh` folder, so caution with that.

**Comment by mcornella** [comment]
See Carlo's solution above.

**Comment by victor-paredes** [comment]
> You have some merge conflicts, it looks like you edited those files. I'd recommend to do a `git reset --hard origin/master` and then `omz update`. Do this in the omz folder (you can go there doing `cd $ZSH`).
> 
> Note that this commands are going to destroy every change you did in the `.oh-my-zsh` folder, so caution with that.

This was helpful. Thank you.

**Comment by paulcushing** [comment]
If it helps anyone who comes across this, it's also possible to reconcile the merge conflict and then update without the reset. 
Running `git status` within the `.oh-my-zsh` directory will tell you what files might have a merge conflict. You can use your code editor of choice (I like VS Code) to fix it. When there is no longer a conflict, running `omz update` works like a charm. This will help you avoid potentially overwriting your customizations.

**Comment by aliostad** [comment]
as @paulcushing  mentioned, simply commit your changes in `.oh-my-zsh` without the need to push or anything. Then `omz update` works.

I had edited some files to change colour schemes of my prompt.
