### ISSUE TITLE
Agnoster theme looks weird in Ubuntu 22.04 terminal

### ISSUE THREAD

**Issue by yth1130** [ohmyzsh/ohmyzsh#10930]
### Describe the bug

It looks like there are squares at the back of the text.

Please check the screenshot.

### Steps to reproduce

1. Install zsh
2. Install oh-my-zsh
3. change theme to agnoster in ~/.zshrc
4. reboot
5. turn on the terminal

### Expected behavior

Agnoster looks pretty.

### Screenshots and recordings

![스크린샷, 2022-05-14 00-56-05](https://user-images.githubusercontent.com/19277858/168322799-902b4055-3a82-49cf-9a8e-7b34bea71ab6.PNG)

### OS / Linux distribution

Ubuntu 22.04

### Zsh version

5.8.1

### Terminal emulator

GNOME Terminal

**Comment by yth1130** [comment]
The font in screenshot is "Ubuntu Mono".

It's not "Ubuntu Mono derivative Powerline", but the fonts for "Powerline" look the same.

**Comment by yth1130** [comment]
Sorry.
This issue is due to Gnome Terminal.
I didn't find this issue with the VSCode built-in terminal.

Here is a [link](https://gitlab.gnome.org/GNOME/vte/-/issues/347) that discusses this issue.

**Comment by OwaliShawon** [comment]
sudo apt-get install fonts-powerline
