### ISSUE TITLE
How to people feel about adding Terraform Console to the Terraform plugin?

### ISSUE THREAD

**Issue by mikerossiter** [ohmyzsh/ohmyzsh#10933]
### If the feature request is for a plugin or theme, specify it here.

terraform

### If the feature solves a problem you have, specify it here.

I am just very lazy and would prefer to type "tfc" to enter the Terraform console to test commands.

### Describe the proposed feature.

Use the alias "tfc" for Terraform Console in addition to the others.

### Describe alternatives you've considered

I have used my own alias in my .zshrc but this seems a bit pointless when I can't be the only person who uses this feature.

**Comment by carlosala** [comment]
Closed in #10815
