### ISSUE TITLE
When globbing is used twice, "no match" in one can prevent the other from working

### ISSUE THREAD

**Issue by WGroleau** [ohmyzsh/ohmyzsh#10932]
### Describe the bug

Image shows the problem.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/5910274/168406952-a391db22-9e08-4fd6-bf05-681d4ff9ca7b.png">

### Steps to reproduce

Create a subdirectory.  Put in it a file with a name that does not occur in the parent directory.
Use `ls` **with a wildcard** to look for that name in the parent directory **and** in the subdirectory.
Error message says the first glob had no match and does not mention the second.
Switch to `sh` and repeat command.  File is found.

### Expected behavior

Globbing should combine all matches into one list and show them.

### Screenshots and recordings

<img width="500" alt="image" src="https://user-images.githubusercontent.com/5910274/168406952-a391db22-9e08-4fd6-bf05-681d4ff9ca7b.png">

### OS / Linux distribution

macOS 12.3.1 (21E258) — Darwin MBP.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

### Zsh version

5.8

### Terminal emulator

MacOS Terminal.app Version 2.12.5 (444)

**Comment by rwmitchell** [comment]
That’s a zsh issue, not OMZ. 

Use ```ls **/BMV*```

**Comment by mcornella** [comment]
You can use `(N)` to enable `NULL_GLOB` for a glob string, which turns off no match errors. Like this:
```sh
ls BMV*(N) P*/BMV*(N)
```
Note that all this does is to not add an argument to the command executed if the glob fails, so the `ls` command will still run without argument if no matches are found:
```console
$ ls BMV*(N)
# BMV* does not find matches, ls runs without arguments
# ls output
```
If you don't want that to happen, you can use another command that only shows the matches, like `print -l`.
