### ISSUE TITLE
zsh completion wrapper for Git fails in case KSH_ZERO_SUBSCRIPT is set

### ISSUE THREAD

**Issue by rmrnc** [ohmyzsh/ohmyzsh#10958]
### Describe the bug

Hi @felipec (assuming, you are still the maintainer for the zsh Git completion wrapper), 
First of all: thank you for the bash-completion wrapper, but, I am afraid, there appears to be an issue with its subsequent argument indexing and counting, when `KSH_ZERO_SUBSCRIPT` is set. 

As the completion script lacks comments, I wasn't able to figure it out exactly,  but it appears you are trying to adjust the indexing between zsh (base one) and bash (base zero) when passing arguments. Would it be possible to take the setting into account before adjusting an argument's index?

Thank you.

### Steps to reproduce

1. Unset `KSH_ZERO_SUBSCRIPT` and try `git checkout ma<TAB>` (should complete the branch's name to (at least) the `main` or `master` branch of a repository)
2. Set `KSH_ZERO_SUBSCRIPT` and try `git checkout ma<TAB>` (completion fails)

### Expected behavior

Completion should be successful, regardless of `KSH_ZERO_SUBSCRIPT`.

### OS / Linux distribution

macOS

### Zsh version

5.8.1

### Terminal emulator

Terminal.app

**Comment by felipec** [comment]
Actually this has nothing to do with git-completion, and it's a bug in zsh itself.

Try this:

setopt ksh_zero_subscript
typeset -A args
(( $+args[foo] )) && echo set

ksh_zero_subscript shouldn't be changing the behavior of the code, but it does.

I've [reported the bug](https://www.zsh.org/mla/workers/2022/msg00756.html), in the meantime you can just disable ksh_zero_subscript inside the script as a workaround.

**Comment by felipec** [comment]
The zsh developers have accepted this is probably a bug in zsh itself.

@robbyrussell this should be closed.
