### ISSUE TITLE
[nvm] NVM_LAZY & `nvm use <non-default-version>` does not switch node version

### ISSUE THREAD

**Issue by libinvarghese** [ohmyzsh/ohmyzsh#10951]
### Describe the bug

I have enabled `NVM_LAZY`, and when I execute `nvm use <non-default-version>` (eg: if default is v16, and try `nvm use v18`), it does not switch the node version to 18

After analysis of `nvm use <version>`, I figured that it executes `$(node --version)` followed by `$(npm --version)`. Since these are subshells, the [`unfunction`](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/nvm/nvm.plugin.zsh#L34) call - only undefines the [lazy loading wrapper function](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/nvm/nvm.plugin.zsh#L33-L37) in its specific subshell. It does not unfunction in parent context & in other subshell. This means that [`nvm use default`](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/nvm/nvm.plugin.zsh#L35) statement is executed everytime even though a different version (*v18*) is provided.

### Steps to reproduce

1. `export NVM_LAZY=1` in .zshrc
2. Enable plugin `nvm`
3. Pre-requistes: Launch terminal, and execute
  
    ```
    nvm install --lts=gallium
    nvm install v18
    # In my case the default is set to gallium
    ```
   close terminal
5. Launch terminal, and execute `nvm use v18`

### Expected behavior

The node version should be v18.x.x (In my case v18.2.0)

### Screenshots and recordings

```
❯ nvm ls
       v16.15.0
        v18.2.0
         system
default -> lts/gallium (-> v16.15.0)
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v18.2.0) (default)
stable -> 18.2 (-> v18.2.0) (default)
lts/* -> lts/gallium (-> v16.15.0)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.12 (-> N/A)
lts/fermium -> v14.19.3 (-> N/A)
lts/gallium -> v16.15.0
❯ nvm version
none
❯ nvm use v18
Now using node v18.2.0 (npm vNow using node v16.15.0 (npm v8.10.0)
8.10.0)
❯ nvm version
Now using node v16.15.0 (npm v8.10.0)
v16.15.0
```

### OS / Linux distribution

Ubuntu 22.04

### Zsh version

5.8.1

### Terminal emulator

Alacritty

**Comment by carlosala** [comment]
This was solved after the `nvm` plugin refactor here 6d5ba2d6c489d56fb34788ec128f98609e60b7be 🎉
