### ISSUE TITLE
Remove extra space inserted when typing asterisk

### ISSUE THREAD

**Issue by bishshoy** [ohmyzsh/ohmyzsh#10962]
### Describe the bug

Oh My Zsh automatically adds extra space when typing asterisk after selecting a file with the **tab** key.

### Steps to reproduce

Here is the scenario. Let's say I am in a directory ("Downloads")

<img width="353" alt="image" src="https://user-images.githubusercontent.com/18286974/170904411-fa347d5a-00c1-4be5-ba16-feda42e149d0.png">

Now I type `rm -rf` and press the **tab** key for the list of files to show up. So I get:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/18286974/170904443-dd13a742-a31e-4677-b2aa-803cf073af89.png">

I press **tab** again (three times) and select `file1`

<img width="365" alt="image" src="https://user-images.githubusercontent.com/18286974/170904471-41111999-2723-412e-a180-b1e8da637b58.png">

Notice that the cursor is just after last character of `file1`. Now I type `*` after it. What I get is this:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/18286974/170904509-b8fbba78-4468-47f5-9e5e-7448f3c3a22b.png">

oh-my-zsh automatically inserts an extra space between `file1` and `*`. This is disastrous because it will delete all files and folders in this directory. I have lost a bunch of files multiple times because of this behavior of oh-my-zsh. This does not exist in the default zsh shell. How can I fix this problem?

### Expected behavior

The default zsh behavior does not add the extra space after hitting the tab key. The space should be added only if the user hits the **space** button explicitly.

### OS / Linux distribution

macOS 11.6.5

### Zsh version

5.8

### Oh My Zsh version

master (e9e8c6b)

### Terminal emulator

Terminal.app

**Comment by rwmitchell** [comment]
This might be more of a zsh issue than OMZ, but there has to be better way than the barbaric method I offered - that breaks the menu from highlighting the current selection.

**Comment by bishshoy** [comment]
Indeed! With the change you suggested, I am not getting the background highlights anymore while browsing through the list of files (by pressing `tab`). I was wondering if a new flag (like `DISABLE_APPENDING_SPACE`) could be implemented. That's why I thought that I should submit a bug for it.

**Comment by mcornella** [comment]
This only happens in my testing when you select a file. If you select a directory, the behavior is not adding a space. I'll see if there's a zsh option to change this.

**Comment by rwmitchell** [comment]
A key point with the selection being a file, it is not unique at the point of selection, justifying the use of a wildcard.

**Comment by mcornella** [comment]
Yeah I have been testing this out and researching why it behaves this way, and IMO it is doing what is only logical with the key combinations pressed.

When you have selected one of the options of the menu, it is no longer logical to write a wildcard for the same argument because the full filename is already typed. IMO zsh is doing the correct thing here, taking into account that directories don't get the space.

If you disagree with this you can ask around on the zsh mailing list: https://zsh.org/mla/.

**Comment by bishshoy** [comment]
> Yeah I have been testing this out and researching why it behaves this way, and IMO it is doing what is only logical with the key combinations pressed.
> 
> When you have selected one of the options of the menu, it is no longer logical to write a wildcard for the same argument because the full filename is already typed. IMO zsh is doing the correct thing here, taking into account that directories don't get the space.
> 
> If you disagree with this you can ask around on the zsh mailing list: https://zsh.org/mla/.

Then I think it would be better to have the appending space included as a part of the tab completion itself. So while tabbing through the list of files and directories, the space at the end would be appended (and not when the user is typing the asterisk). This way things would be visually coherent. What’s happening now is that there a disconnect between what’s the programmer is expecting and what omz is doing.

**Comment by mcornella** [comment]
Oh My Zsh does not control that. Feel free to report this on the zsh mailing list.

**Comment by sisrnb** [comment]
Adding `ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;&|*'` to my `~/.zshrc` worked for me.

References:
https://unix.stackexchange.com/questions/681173/zsh-oh-my-zsh-how-to-make-tab-completion-add-no-trailing-space-for-non-folder-f
https://unix.stackexchange.com/questions/174630/keep-the-space-after-completion-for-some-characters-in-zsh
