### ISSUE TITLE
Too many aliases

### ISSUE THREAD

**Issue by mschuerig** [ohmyzsh/ohmyzsh#10969]
### If the feature solves a problem you have, specify it here.

I'm using a fair number of plugins (~17) and they add about 200 aliases to my shell. An overwhelming number given that I hardly use any of them. I prefer defining my own aliases. Actually, I've refrained from using a few plugins that would add even more aliases.

### Describe the proposed feature.

I would like to have a global switch, or per plugin switches, to disable aliases. This would give me a way to copy only the aliases I want to my custom aliases file.

**Comment by carlosala** [comment]
I absolutely agree with you. We have an issue discussing about that #10644

**Comment by mschuerig** [comment]
See #10644 instead.

**Comment by mcornella** [comment]
Can you post your feedback over there? Would the proposed solution be how you'd want to do things, are there any drawbacks, ...
