### ISSUE TITLE
no link to discord server

### ISSUE THREAD

**Issue by marafa** [ohmyzsh/ohmyzsh#10964]
### Describe the bug

the omz blurb says 
```
To keep up with the latest news and updates, follow us on Twitter: @ohmyzsh
Want to get involved in the community? Join our Discord: Discord server
Get your Oh My Zsh swag at: Planet Argon Shop
```
but then there is no link to the discord server (same for the swag shop but thats easily googled

### Steps to reproduce

i saw it in `omz update`

### Expected behavior

a url is provided too

### OS / Linux distribution

fedora 36

### Zsh version

5.8.1

### Terminal emulator

kontact

**Comment by mcornella** [comment]
That happens when you have a Terminal that supports hyperlinks, you should be able to hover over the text and see a link prompt. I haven't been able to find the kontact terminal emulator, is that a typo?

**Comment by marafa** [comment]
My bad. Konsole. Konsole is part of the KDE environment
