### ISSUE TITLE
Tab AutoCompletion not show directory

### ISSUE THREAD

**Issue by huyhoang8398** [ohmyzsh/ohmyzsh#10972]
### Describe the bug

Tab to autocomplete not show all directories

### Steps to reproduce

1. Enable ohmyzsh
2. Create two directories starting with adjacent letters:
   ```sh
   mkdir ccc
   mkdir ddd
   ```
3. Type `cd` then press TAB
4. Completion suggests D

The same happens with any two directories starting with adjacent letters: `aaa` and `bbb`, `hello` and `iris`.

### Expected behavior

suggest all files and folders

### Screenshots and recordings

https://user-images.githubusercontent.com/25379882/171906844-268c48b3-9252-4f39-8fae-9c74f87dbf3b.mp4

### OS / Linux distribution

Archlinux

### Zsh version

6.9

### Terminal emulator

kitty, alacritty

**Comment by huyhoang8398** [comment]
Fixed with CASE_SENSITIVE="true"

**Comment by huyhoang8398** [comment]
```
-)*.orig=00;90:(-default-)*.part=00;90:(-default-)*.rej=00;90:(-default-)*.swp=00;90:(-default-)*.tmp=00;90:(-default-)*.dpkg-dist=00;90:(-default-)*.dpkg-old=00;90:(-default-)*.ucf-dist=00;90:(-default-)*.ucf-new=00;90:(-default-)*.ucf-old=00;90:(-default-)*.rpmnew=00;90:(-default-)*.rpmorig=00;90:(-default-)*.rpmsave=00;90' 
  +_main_complete:405> funcs=( ) 
  +_main_complete:406> comppostfuncs=( ) 
  +_main_complete:411> _lastcomp=( list_lines 1 all_quotes '\' nmatches 2 restore auto context command vared '' unambiguous D list_max 100 unambiguous_cursor 2 list ambiguous insert_positions 4 unambiguous_positions 1 exact '' to_end match last_prompt yes pattern_insert menu ignored 0 insert automenu-unambiguous ) 
  +_main_complete:412> _lastcomp[nmatches]=2 
  +_main_complete:413> _lastcomp[completer]=complete 
  +_main_complete:414> _lastcomp[prefix]='' 
  +_main_complete:415> _lastcomp[suffix]='' 
  +_main_complete:416> _lastcomp[iprefix]='' 
  +_main_complete:417> _lastcomp[isuffix]='' 
  +_main_complete:418> _lastcomp[qiprefix]='' 
  +_main_complete:419> _lastcomp[qisuffix]='' 
  +_main_complete:420> _lastcomp[tags]=' local-directories ' 
  +_main_complete:422> return ret
 +_complete_debug:26> integer ret=0
 +_complete_debug:27> unsetopt xtrace
```

**Comment by gheritarish** [comment]
I had a similar problem when wanting to edit a file with another file of a similar name (*e.g* `tests.py` and `tests.queries.py`), the completion suggested `tests.Q`.
Updating the `CASE_SENSITIVE` variable fixed it, thanks!

**Comment by mcornella** [comment]
This is a regression in zsh 5.9: https://www.zsh.org/mla/workers/2022/msg00652.html. A workaround for now is to set `CASE_SENSITIVE=true` and avoid being in a situation where the only possible suggestions start with adjacent letters.

For example, this will trigger the error:
```console
$ ls
hello 		iris
$ cd [TAB]
$ cd I
```
while this doesn't
```console
$ ls
hello		iris		list
$ cd [TAB]
hello/		iris/		list/
```

This same thing happens on files, it doesn't need to be directories:
```console
$ touch hi.txt iris.txt
$ cat [TAB]
$ cat I
```

I will close it as not our fault, but update the issue when there are news about the patch.

**Comment by mozzieongit** [comment]
There is a different option to fixing this without deactivating case insensitive search altogether:
change `m:{a-zA-Z}={A-Za-z}` to `m:{[:lower:][:upper:]}={[:upper:][:lower:]}`. I created a PR for this (#11526).
