### ISSUE TITLE
I'm unable to run existing NPM packages even though they are installed.

### ISSUE THREAD

**Issue by HackPoint** [ohmyzsh/ohmyzsh#10979]
### Describe the bug

I've installed few npm packages globally.

I need to run all of them but it's not working.

```
/.nvm/versions/node/v16.14.2/lib
├── @microsoft/api-extractor@7.23.0
├── @storybook/cli@6.5.2
├── corepack@0.10.0
├── http-server@14.1.0
├── npm@8.5.0
├── nps@5.10.0
└── nx@14.1.6

➜  catalog git:(main) ✗ nps
zsh: command not found: nps
➜  catalog git:(main) ✗ 
```
How is that possible?

### Steps to reproduce

Just run the npm install -g nps 

### Expected behavior

To run and work

### OS / Linux distribution

macOS10.15.7

### Zsh version

5.9

### Terminal emulator

iTerm2

### Additional context

Can you please help?

**Comment by mcornella** [comment]
Closing as not in scope for Oh My Zsh.
