### ISSUE TITLE
Latest version doesnt recognize the commands

### ISSUE THREAD

**Issue by CaritoDaSilvaMeli** [ohmyzsh/ohmyzsh#10981]
### Describe the bug

Installing the latest version all my commands stop working. Appears in all cases zsh: command not found: <name_command>

### Steps to reproduce

`npm -v zsh: command not found: npm
`

### Expected behavior

I expect all the commands that I've been working for a year still working properly but all crash with last update

### OS / Linux distribution

MacOS Big Sur v11.6.6

### Zsh version

5.8

### Oh My Zsh version

master (d41ca84a)

### Terminal emulator

iTerm2

**Comment by rwmitchell** [comment]
I'm also on MacOS 11.6.6, iTerm2, and OMZ just updated, but my programs still work.

Does the output from ```echo $PATH``` look correct?
Have you tried ```ls``` it is in /bin/ls and part of standard pathing, whereas ```npm``` is a add-on program and it may be installed in a non-standard path.

**Comment by CaritoDaSilvaMeli** [comment]
Im gonna close the issue because I found the error and was efectively a problem in another path that have changes. Thanks!
