### ISSUE TITLE
Repeated problems with update: timed out

### ISSUE THREAD

**Issue by dheerajchand** [ohmyzsh/ohmyzsh#10985]
Whenever I try to update oh-my-zsh, I have an unexplained error from GitHub. Other GitHub projects update without problems.

I have an alias `zshreboot` that I use to restart oh-my-zsh.  I used it here to restart a shell so you could see, and have attached a screenshot of a different session updating a different GitHub project successfully. 

```
[oh-my-zsh] Would you like to update? [Y/n] y
Updating Oh My Zsh
fatal: unable to connect to github.com:
github.com[0: 140.82.112.3]: errno=Operation timed out

There was an error updating. Try again later?
```

Any suggestions?
<img width="582" alt="Screen Shot 2022-06-10 at 3 46 39 PM" src="https://user-images.githubusercontent.com/482844/173147763-9ce801da-e7cc-4a9d-aa2c-f84aa38d18a2.png">

<img width="588" alt="Screen Shot 2022-06-10 at 3 46 33 PM" src="https://user-images.githubusercontent.com/482844/173147774-820e8222-5cf8-4503-bdd9-8f9e57f1c119.png">

**Comment by mcornella** [comment]
Does this only happen on a new terminal / on `zshreboot`? i.e. can you update with `omz update`?

**Comment by dheerajchand** [comment]
It is on any attempt to update. 

`omz update` did not work.

<img width="583" alt="Screen Shot 2022-06-13 at 11 44 57 AM" src="https://user-images.githubusercontent.com/482844/173403705-d2b7ee8f-c7b7-4f83-ba67-7304f652b84b.png">

**Comment by LucasHBG** [comment]
Since he did not responded yet and im also with the same exact error(also tried the same steps). Here is the output:

![image](https://user-images.githubusercontent.com/31226269/174354265-25e53e3f-1e22-4515-94d9-959c9068f42d.png)

**Comment by mcornella** [comment]
Right, that's a result of GitHub removing support for the git protocol, see https://github.com/ohmyzsh/ohmyzsh/issues/10778#issuecomment-1074719012 for a fix.
