### ISSUE TITLE
broken rsync tab completion

### ISSUE THREAD

**Issue by mcandre** [ohmyzsh/ohmyzsh#10999]
### Describe the bug

Something in the Oh my Zsh ecosystem recently broke how rsync works. The tab completion continues to produce old style triple backslashes (`\\\`) for special characters in remote file paths, such as spaces. However, rsync requires the `--old-args` flag to handle this.

How can we configure zsh tab completion to use the new way, single backslashes (`\`) instead?

### Steps to reproduce

Rsync a remote file.

### Expected behavior

Zsh should tab complete remote paths with single backslashes for special characters.

### OS / Linux distribution

macOS 12

### Zsh version

5.8.1

### Terminal emulator

Terminal.app

**Comment by ro0mquy** [comment]
I am having the same problem. Did you find a solution?

**Comment by carlosala** [comment]
@ro0mquy could you please provide a minimal example where I can try to reproduce it? Thanks!
Btw, are you still in 5.8.1 or 5.9?
