### ISSUE TITLE
tab auto complete file name error cant match pas* files

### ISSUE THREAD

**Issue by samegek** [ohmyzsh/ohmyzsh#11000]
### Describe the bug

above title: tab auto complete file name error cant match pa* files

### Steps to reproduce

```bash
mkdir testdir
touch paska
touch parse
zsh --no-rcs
ls pa<tab>
# output:  pas parse ok
source ~/.oh-my-zsh/oh-my-zsh.sh 
ls pa<tab>
# output:  paS error
```

real: get ls paS 

### Expected behavior

get pas parse

### OS / Linux distribution

Linux 4.15.0-51-generic #55~16.04.1-Ubuntu

### Zsh version

5.8.1.3-test

### Oh My Zsh version

master (8168ec01)

### Terminal emulator

mintty

**Comment by mcornella** [comment]
Fixed in https://github.com/ohmyzsh/ohmyzsh/pull/11526. Get the fix with `omz update`.
