### ISSUE TITLE
Kubectl Plugins Tip information, use the colon separation, how to solve 

### ISSUE THREAD

**Issue by AlexFly666** [ohmyzsh/ohmyzsh#11003]
Kubectl Plugins Tip information, use the colon separation, how to solve
<img width="846" alt="Snipaste_2022-06-19_22-22-35" src="https://user-images.githubusercontent.com/15715975/174486303-e3cb31a6-06fb-4107-b9d8-2a6926fa1256.png">

**Comment by Fly0905** [comment]
zsh is latest version

**Comment by ticteam** [comment]
same for me! 

zsh --version
zsh 5.9 (x86_64-pc-linux-gnu)

I'm using the following plugins
plugins=(git aws kubectl helm zsh-autosuggestions kubectl-autocomplete) 

and 
ZSH_THEME="frisk"

kgp
  -- a:w:s:c:l:i
  -- h:a:p:r:o:x:y:-:7:7:7:7:7:4:8:4:5:-:q:2:4:6:2
  -- k:a:f:k:a:-:d:e:p:l:o:y:m:e:n:t:-:d:c:7:c:6:8:d:9:7:-:f:z:q:z:j
  -- k:a:f:k:a:-:p:r:o:d:u:c:e:r:-:6:9:6:9:7:5:f:7:9:b:-:f:k:r:c:g
  -- k:e:y:d:b:-:0
  -- k:e:y:d:b:-:1

**Comment by carlosala** [comment]
Doesn't seem to be an `oh my zsh` problem as far as I can see. Oh-my-zsh just enables `kubectl` official completions. Could you try disabling that `kubectl-autocomplete` plugin? I'm not sure where it comes from.
Closing this as I don't see a relation with oh-my-zsh.
