### ISSUE TITLE
.bashrc bets just deleted when installing myzsh?

### ISSUE THREAD

**Issue by faeb187** [ohmyzsh/ohmyzsh#11007]
### Describe the bug

I've installed MyZSH using curl command on official myzsh website.

Is it really a fact, that existing `.bashrc` file is just deleted without any warning or backup?
I mean that would be a hilarious joke no?

System info (probably the same everywhere)
- 💻 MacBook Pro, most recent OSX (Monterey 12.4)

### Steps to reproduce

1 open default terminal app of Mac
2 install using `sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`

### Expected behavior

existing `.bashrc` either moved to a backup folder or setup shows a warning with option to continue/abort

### OS / Linux distribution

MacOS Monterey 12.4

### Zsh version

5.8.1

### Terminal emulator

Terminal.app

**Comment by schuebel** [comment]
omz certainly doesn't touch your `.bashrc`. What it does though is backup your existing `.zshrc` to `.zshrc.pre-oh-my-zsh`.

You can check the install script [here](https://github.com/ohmyzsh/ohmyzsh/blob/master/tools/install.sh).
