### ISSUE TITLE
OMZ Logo .svg

### ISSUE THREAD

**Issue by SIMULATAN** [ohmyzsh/ohmyzsh#11019]
### If the feature solves a problem you have, specify it here.

I wanted to use the OMZ logo from the [devicons pack](https://github.com/devicons/devicon), but it turned out that OMZ is missing from the collection. I then wanted to open an issue there to include OMZ, but it turns out that there is no public svg logo available.

### Describe the proposed feature.

Publish an official svg file of "the" logo

### Additional context

I got told to open this issue on the discord server in [this](https://discord.com/channels/642496866407284746/809850042575093760/989852811481194498) message

**Comment by robbyrussell** [comment]
@SIMULATAN Thanks for asking about this! The designer who worked on this left me with some variation png files and the Adobe Illustrator file used. I just saved it as a SVG file. 

Does this get you what you're after?

![Oh My Zsh SVG logo](https://user-images.githubusercontent.com/257/178130144-264ef495-be6a-4824-8ca5-10cfcdcee68e.svg)

I'll also push this out on the website at the following URL:

* https://ohmyz.sh/img/ohmyzsh-original-logo.svg

**Comment by SIMULATAN** [comment]
Thanks a lot, that should do it. I'll edit this message when I made the devicons issue

**Comment by BenSouchet** [comment]
Hi, Devicon contributor here 😊

Thanks @robbyrussell for the SVG file ! 

For anyone in the future needing the logo as **PSD, EPS, AI, SVG** :
[OhMyZsh_Logo.zip](https://github.com/ohmyzsh/ohmyzsh/files/9183975/OhMyZsh_Logo.zip)

If you only need the SVG files (**Cleanup & Optimized**) : 
![OhMyZsh](https://user-images.githubusercontent.com/17025808/180850444-cb0fb24b-5dca-4c34-8dda-84eeee46c582.svg)
![OhMyZsh-transparent](https://user-images.githubusercontent.com/17025808/180850449-962dc009-877c-42fc-bd96-7d0bbc2a6615.svg)
