### ISSUE TITLE
After setting LC_CTYPE=C, RPROMPT return code causes cursor to position to be in prompt

### ISSUE THREAD

**Issue by spthiel** [ohmyzsh/ohmyzsh#11027]
### Describe the bug

Once LC_CTYPE is set to C:

When using a theme that puts the return code in the RPROMPT the cursor will be pushed into the PROMPT text whenever the error code is present

This does not appear to be an issue with a specific shell (since I can recreate it in gnome terminal and alacritty) nor an issue with a specific theme (as I can recreate it with obraun, lukerandall, flazz and a few more).

### Steps to reproduce

1. export LC_CTYPE=C
2. Enable a theme that adds the return code in the RPROMPT
3. Press ctrl+c to get a return code

### Expected behavior

The cursor is next to the prompt

### Screenshots and recordings

https://imgur.com/a/3MuPeOP

### OS / Linux distribution

Linux Mint 20.9

### Zsh version

5.8

### Oh My Zsh version

master (4c82a2ee)

### Terminal emulator

GNOME Terminal, Alacritty

### Additional context

This also causes tabulation to error as it tries to push the content of the command in the correct place but the curser stays with incorrect offset

**Comment by carlosala** [comment]
Hi! You should always use utf8, you can get further info [here](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command). You can also get how to change locales [here](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-change-my-locale). Thanks for the report!
