### ISSUE TITLE
Switching to ROOT - [oh-my-zsh] Can't update: not a git repository.

### ISSUE THREAD

**Issue by mrturcot** [ohmyzsh/ohmyzsh#11031]
### Describe the bug

In terminal when I su - into a root enviroment I get this `[oh-my-zsh] Can't update: not a git repository.` This doesnt happen when I open a terminal under any user.

### Steps to reproduce

Open terminal
su -
`[oh-my-zsh] Can't update: not a git repository.`

### Expected behavior

Not show ` [oh-my-zsh] Can't update: not a git repository.`

### OS / Linux distribution

Gentoo

### Zsh version

5.9

### Terminal emulator

Terminator, Konsole

**Comment by rwmitchell** [comment]
Does your root also use zsh?  When you switched using su -, I believe it would have also changed to root's normal shell which is more likely sh

**Comment by mrturcot** [comment]
> Does your root also use zsh? When you switched using su -, I believe it would have also changed to root's normal shell which is more likely sh

Yes I have switched my root shell to zsh. Its been fine since I switched zsh for months then al of a sudden I started gettingt that git message out of no where switching to su? Weird...

**Comment by rwmitchell** [comment]
Any reason the .git directory would have gone missing from .oh-my-zsh ?

**Comment by mrturcot** [comment]
Im not sure but seems I dont have it? Any way to get it? Thank alot btw

ls /usr/share/zsh/site-contrib/oh-my-zsh/                  
Permissions Size User Date Modified Name
drwxr-xr-x     - root 20 Jun 02:01  cache
drwxr-xr-x     - root 19 Jun 14:47  custom
drwxr-xr-x     - root 19 Jun 14:16  lib
drwxr-xr-x     - root  3 Jul 15:20  log
drwxr-xr-x     - root 19 Jun 14:16  plugins
drwxr-xr-x     - root 19 Jun 14:16  templates
drwxr-xr-x     - root 20 Jun 23:45  themes
drwxr-xr-x     - root 19 Jun 14:16  tools
.rw-r--r--  3.4k root 19 Jun 14:16  CODE_OF_CONDUCT.md
.rw-r--r--  8.3k root 19 Jun 14:16  CONTRIBUTING.md
.rw-r--r--  1.1k root 19 Jun 14:16  LICENSE.txt
.rw-r--r--  6.0k root 19 Jun 14:16  oh-my-zsh.sh
.rw-r--r--   15k root 19 Jun 14:16  README.md
.rw-r--r--  1.1k root 19 Jun 14:16  SECURITY.md

**Comment by rwmitchell** [comment]
You need to use ```ls -a``` to check

**Comment by mrturcot** [comment]
> You need to use `ls -a` to check

Yes I use an alias `alias ls="exa -alh --color=always --group-directories-first"`

That is the correct output I posted

**Comment by rwmitchell** [comment]
Do you remember how you initially installed OMZ?  There really should be .git subdirectory.

How long have you been using it?  Less than a month?  (about every 2 weeks tries to update). That would account for my why you are suddenly getting the error.

The safest way to get it back is to:

```
cd ~
mv .oh-my-zsh .oh-my-zsh-HOLD
git clone https://github.com/ohmyzsh/ohmyzsh.git
mv .oh-my-zsh-HOLD/custom .oh-my-zsh
```

That will allow you to refer back to the backup copy if you discover something unexpected has changed.
If you don't have a custom subdirectory and haven't made any changes to OMZ, you could simplify that with:

```
cd ~
rm -rf .oh-my-zsh
git clone https://github.com/ohmyzsh/ohmyzsh.git
```

**Comment by mrturcot** [comment]
That did the trick, You're absoutly correct. I installed oh-my-zsh with an ebuild from the Guru overlay exatly 14 days ago haha. So to keep it updated I should just clone the repo every so often and mv custom over and im good to go? Thanks!
