### ISSUE TITLE
Slow to open shell if internet connection is slow

### ISSUE THREAD

**Issue by fulldecent** [ohmyzsh/ohmyzsh#11036]
### Describe the bug

When internet connection is unreliable, it is slow to open terminal.

### Steps to reproduce

Go unplug the WAN cable on your router.

Open your shell.

### Expected behavior

Shell opens in < 100ms every single time.

### Screenshots and recordings

Shell opens over 5s or you need to interrupt it with CTRL-C

### OS / Linux distribution

macOS 10.15

### Zsh version

5.8.1

### Terminal emulator

Terminal.app

**Comment by hkbertoson** [comment]
I was unable to replicate this issue. I turned my internet off and it still loaded just fine. Are you loading a lot of plugins?

**Comment by fulldecent** [comment]
I believe this issue may be specifically related to the update mechanism. Still searching for the related circumstances to make this 100% repro. Currently only 10% repro.

**Comment by lnxd** [comment]
I experienced this issue when I used to work over VPN, any difference if you uncomment `DISABLE_AUTO_UPDATE="true"` in `.zshrc`?

**Comment by mcornella** [comment]
I believe we fixed this in #11617 plus adding connection timeouts on the API call. Feel free to raise a separate issue if this still happens.
