### ISSUE TITLE
Typing ``!*`` is autoreplaced by the last command starting with ``*`` even in contexts where you don't want that

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [ohmyzsh/ohmyzsh#11049]
### Describe the bug

Trying to create a commit message containing a ``!`` followed by a letter.

### Steps to reproduce

```bash
$ echo "toto"
$ git commit -am "[something] !e " 
```
The actual command that is launched is `` git ci -am "[something] echo "toto" "``

### Expected behavior

The command should not be changed.

### OS / Linux distribution

Ubuntu 22.04

### Zsh version

5.8.1

### Terminal emulator

GNOME Terminal

**Comment by carlosala** [comment]
That is solved using single quotes. With double quotes `zsh` tries to expand everything it can, and that includes `!` for previous commits.
Thanks for the report, it's going to be useful for other users!
