### ISSUE TITLE
nvm plugin awfully slow

### ISSUE THREAD

**Issue by morriswinkler** [ohmyzsh/ohmyzsh#11042]
### If the feature request is for a plugin or theme, specify it here.

nvm plugin

### If the feature solves a problem you have, specify it here.

Loading nvm plugin is awfully slow.  I set NVM_LAZY=1 but no difference.

My set up OSX Monteray and nvm 0.39.1 installed via brew 

### Describe the proposed feature.

solution for me was to disable it and go with a custom script found on:

https://www.reddit.com/r/node/comments/4tg5jg/lazy_load_nvm_for_faster_shell_start/d5ib9fs/?utm_term=28631259784&context=3&utm_medium=comment_embed&utm_source=embed&utm_name=null

```
declare -a NODE_GLOBALS=(`find ~/.nvm/versions/node -maxdepth 3 -type l -wholename '*/bin/*' | xargs -n1 basename | sort | uniq`)

NODE_GLOBALS+=("node")
NODE_GLOBALS+=("nvm")

load_nvm () {
    export NVM_DIR=~/.nvm
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
}

for cmd in "${NODE_GLOBALS[@]}"; do
    eval "${cmd}(){ unset -f ${NODE_GLOBALS}; load_nvm; ${cmd} \$@ }"
done
```

maybe you could add that snippet behind an other variable that loads it and discards the rest

**Comment by polothy** [comment]
Just FYI, I had same issues (nvm being slow) and switched to [asdf](https://asdf-vm.com). Seems to be working just fine.  The lazy loading of nvm didn't work all the time, EG: IDEs and other scripts could bypass the lazy loading.

**Comment by carlosala** [comment]
I opened a new PR #11202 that should solve this.
