### ISSUE TITLE
Unable to update omz on macOS: fetch-pack: invalid index-pack output

### ISSUE THREAD

**Issue by getangar** [ohmyzsh/ohmyzsh#11050]
### Describe the bug

When a new update is available, regardless if I try to update on demand or by replying "Y" when prompted, the update fails with the following error:

fatal: pack has 58 unresolved deltas
fatal: fetch-pack: invalid index-pack output
There was an error updating. Try again later?

### Steps to reproduce

1. Start the terminal (regardless if the native Terminal or iTerm2)
2. Give the command: "omz update"

### Expected behavior

I expect that omz is getting updated.

### Screenshots and recordings

<img width="503" alt="Screenshot 2022-07-15 at 10 35 22" src="https://user-images.githubusercontent.com/41167983/179186104-eba1364d-dfc3-47a9-a233-b75e7137e0f8.png">

### OS / Linux distribution

macOS Monterey (12.4)

### Zsh version

5.8.1

### Oh My Zsh version

master (846f417)

### Terminal emulator

iTerm2, Terminal

### Additional context

I have installed omz on both my Mac mini M1 and MacBook Air M1. The software configuration of the two computer is practically the same, but the issue can be reproduced on the Mac mini only.

**Comment by mcornella** [comment]
It looks like this is due to  regular network connectivity issue: https://stackoverflow.com/questions/68882027/git-error-fatal-fetch-pack-invalid-index-pack-output. If you are still having this issue
