### ISSUE TITLE
"omz update" fails with "brew plugin needs merge"

### ISSUE THREAD

**Issue by workflowsguy** [ohmyzsh/ohmyzsh#11058]
### Describe the bug

Previously (until about 4 days ago), `omz update` ran without issues on my machines.

Now, when I run the command, I get the following:
```
plugins/brew/brew.plugin.zsh: needs merge
error: you need to resolve your current index first
```

I don't know what this message is supposed to tell me

### Steps to reproduce

1. install/enable plugin `brew`
2. run `omz update`

### Expected behavior

Ideally, updating the plugin/omz should just work.
If there is an error, the message give clues how to solve this by the user, if possible

### OS / Linux distribution

macOS 10.13.6, 10.14, 11

### Zsh version

5.8

### Oh My Zsh version

master (4c82a2ee)

### Terminal emulator

iTerm2

**Comment by carlosala** [comment]
Maybe you did some changes to the plugin file. To come back to the official version, execute
```sh
cd $ZSH
git reset --hard origin/master
omz update
```

**CAUTION**: this is going to destroy all changes you did in omz directory!
