### ISSUE TITLE
Check for upgrade exits prematurely, thus auto-updates do not work

### ISSUE THREAD

**Issue by jcarroll3** [ohmyzsh/ohmyzsh#11061]
### Describe the bug

When I started my shell, I noticed that the auto-updates no longer appeared to run. After debugging, I noticed that the script exits somewhere inside the below block of code. I have curl installed and expect this should run just fine, but it always fails. Unfortunately, I'm not savvy enough in shell to figure out where exactly this is failing.

This behavior is happening on both my work and personal machines. 

```
local remote_head
  remote_head=$(
    if (( ${+commands[curl]} )); then
      curl --conect-timeout 2 -fsSL -H 'Accept: application/vnd.github.v3.sha' $api_url 2>/dev/null
    elif (( ${+commands[wget]} )); then
      wget -T 2 -O- --header='Accept: application/vnd.github.v3.sha' $api_url 2>/dev/null
    elif (( ${+commands[fetch]} )); then
      HTTP_ACCEPT='Accept: application/vnd.github.v3.sha' fetch -T 2 -o - $api_url 2>/dev/null
    else
      exit 0
    fi
  ) || return 1

// I never reach here

[[ "$local_head" != "$remote_head" ]] || return 1
```

### Steps to reproduce

1. Put a debug statement (echo or whatever) above the line `[[ "$local_head" != "$remote_head" ]] || return 1` in check_for_upgrade.sh
2. Open a new terminal

Notice that the debug statement is not printed

### Expected behavior

It is expected that every time the shell starts that the update scripts runs and checks to see if there are any updates.

### OS / Linux distribution

macOS 12.4

### Zsh version

5.8.1

### Oh My Zsh version

master (4c82a2e)

### Terminal emulator

iTerm2

**Comment by zedtools** [comment]
I'm seeing this too, with auto-update not running.

The problem appears to be a typo the curl command in the code above: `--conect-timeout` should be `--connect-timeout`

The typo causes curl to abort, which then executes `return 1`, aborting the update.

**Comment by mcornella** [comment]
If you are seeing this, please manually update with `omz update`. We fixed the issue in https://github.com/ohmyzsh/ohmyzsh/commit/bb6c14cdfd0b7d543d0d9c2e5f0c0a9409a82084, but it needs to be manually fetched, otherwise the auto update will always fail.

**Comment by jcarroll3** [comment]
Thanks! looks good to me
