### ISSUE TITLE
[feat] add an alias to sync with the current branch in upstream

### ISSUE THREAD

**Issue by Huang-Wei** [ohmyzsh/ohmyzsh#11087]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### If the feature solves a problem you have, specify it here.

`glum` which is aliased to `git pull upstream $(git_main_branch)` works well for most cases.

However, it'd be nice to have a `gluc` alias to sync with the **current branch** in upstream.

### Describe the proposed feature.

Add the following line to git plugin:

```
alias gluc=git pull upstream $(git_current_branch)
```

**Comment by carlosala** [comment]
I think that's a great alias and would be widely used. I'll approve your PR if you create it!

**Comment by Huang-Wei** [comment]
Sure thing, #11101 created.
