### ISSUE TITLE
cp, ls, wc inconsistencies

### ISSUE THREAD

**Issue by WGroleau** [ohmyzsh/ohmyzsh#11099]
### Describe the bug

Don't know whether the issue is in zsh or in Oh My Zsh.  All works in bash.
Details in https://apple.stackexchange.com/questions/444945/ghost-files-now-you-see-em-now-you-dont
Short version:
HOW is it possible in zsh+"oh-my-zsh" for cp to say the source doesn't exist, yet wc is able to read the destination in a path Finder says isn't there? And then for ls to agree that the destination doesn't exist?

### Steps to reproduce

Here's the script that failed, but you may not be able to reproduce my environment (external drive with corruption).
```
cat temp/3TB-file-list | while read LINE; do
echo $LINE
mkdir -p "~/3TB-files/$(dirname $LINE)"
cp "/Volumes/Seagate 3TB/$LINE" "~/3TB-files/$LINE"
wc "~/3TB-files/$LINE"
sleep 2
done
```

### Expected behavior

1. `mkdir -p `should create the path it is given.
2. files that can be opened by bash or by double-clicking should be copied by that script.  Finder and `ls` should see them.
3. Finder and `ls` should not say a file doesn't exist when `wc` has already shown its size.
4. script shown should behave the same in bash or zsh.

### Screenshots and recordings

System Version:	macOS 12.5 (21G72)
  Kernel Version:	Darwin 21.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	MBP
  User Name:	伟思礼 (WGroleau)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled

### OS / Linux distribution

macOS 12.5 (21G72) 

### Zsh version

5.8.1

### Terminal emulator

Terminal.app

### Additional context

See Q&A on stack exchange

**Comment by WGroleau** [comment]
1. I do not know why the strikethrough in the pasted copy of my script.
2. Although bash does not show the error messages for most of the files, `find` says that they have not been copied.  Perhaps a bug in Apple's filesystem code?

Dragging a folder with Finder works but the destination disk doesn't have enough space to do it that way.

**Comment by mcornella** [comment]
The issue here is the quoting of the `~` character, it must go outside quotes for the shell to properly expand it to the home directory. When you put it within quotes, the path created has a literal tilde, not the home directory. Then, when doing something such as `ls ~/3TB-files` you will not find it, as the shell expands the tilde to the home directory.

This is not OMZ-related, but rather normal behavior of shells. See https://unix.stackexchange.com/questions/146671/does-always-equal-home/146697#146697.
