### ISSUE TITLE
Add support for VSCode Remote SSH shell integration `$BROWSER` 

### ISSUE THREAD

**Issue by chneau** [ohmyzsh/ohmyzsh#11098]
### Describe the bug

`plugins/web-search` relies on `lib/functions.zsh`:`function open_command` to open the browser.

When using VSCode remote SSH on a Ubuntu server, VSCode will inject env var `$BROWSER` which can be used to open the browser locally from the remote server.

eg: `$BROWSER http://localhost:4000` will open my Google Chrome on my Windows 10 laptop, but the command is actually run remotely on a server I connect through VSCode remote SSH.

Using `plugins/web-search` it simply don't work on VSCode Remote SSH. I noticed one external plugin I use just work fine: https://github.com/paulirish/git-open/blob/master/git-open#L272 -> Which uses the env var `$BROWSER` 

I am using a fix on my side to make it work on my setup: https://github.com/chneau/dotfiles/blob/master/zsh/lib/functions.zsh#L19 

### Steps to reproduce

Enable plugin `web-search` and through a VSCode Remote SSH terminal type like `google ohmyzsh` to notice it does not work.

### Expected behavior

My local browser to open the page.

### OS / Linux distribution

Windows 10 + Ubuntu 22.04.1 LTS

### Zsh version

5.9

### Oh My Zsh version

None, using `zinit` to load OMZ plugins and libs

### Terminal emulator

`echo "$TERM_PROGRAM"` returns `vscode` 

### Additional context

`$BROWSER` is used on one of the OMZ plugin: https://github.com/ohmyzsh/ohmyzsh/blob/fcd7da3aec8315178991aa25d57dacfc6c331ac6/plugins/common-aliases/common-aliases.plugin.zsh#L58

**Comment by mcornella** [comment]
It should be fixed in #11532. Please test it out with `omz pr test 11532` and let me know if it works!

**Comment by chneau** [comment]
Hello @mcornella, it works perfectly, to test it on my side since I'm using zinit, I've updated the file on my repository with the one from the pull request you did, and it just works!
