### ISSUE TITLE
Duplicate Alias Command for Git

### ISSUE THREAD

**Issue by hmenorjr** [ohmyzsh/ohmyzsh#11104]
### Describe the bug

I wanted to know what the shorthand command for `git pull --rebase origin master` and typed `alias | grep 'git pull'` and noticed a duplicate command.

```
$ alias | grep 'git pull'
ggpull='git pull origin "$(git_current_branch)"'
gl='git pull'
glum='git pull upstream $(git_main_branch)'
gpr='git pull --rebase'
gup='git pull --rebase'
gupa='git pull --rebase --autostash'
gupav='git pull --rebase --autostash -v'
gupom='git pull --rebase origin $(git_main_branch)'
gupomi='git pull --rebase=interactive origin $(git_main_branch)'
gupv='git pull --rebase -v'
```
The command 'git pull --relbase' is duplicated.

### Steps to reproduce

1. Open terminal
2. type: alias | grep 'git pull --rebase'

### Expected behavior

Only one config for 'git pull --rebase'

### OS / Linux distribution

macOS 12.5

### Zsh version

5.8.1

### Oh My Zsh version

master (d41ca84)

### Terminal emulator

iTerm2, Terminal.app, VSCode integrated terminal

**Comment by tjarbo** [comment]
@zee-bit 
I like the idea, but as the alias for `git pull` is already `gl`, I would suggest to change the prefix from `gp` to `gl`. This would also align with the other `git pull`-aliases `gluc` and `glum`.

---
Link to #11224

**Comment by rwmitchell** [comment]
gl is non-logical - looks more appropriate for git log

**Comment by tjarbo** [comment]
@rwmitchell Yes, but `gp` is already used for (even every? - cannot check right now) `git push` commands - could be cause confusion if suddenly aliases with  a `gp` prefix refers to different commands.

**Comment by rwmitchell** [comment]
how about 'u' for update because that is what is happening.  The local source is getting updated from the repo.

**Comment by tjarbo** [comment]
@rwmitchell Because there is no `git update` command, afaik, using `gu` cloud be really an option 👍 This would remove the overlap with `git log` commands.

**Comment by rwmitchell** [comment]
It isn't going to happen.  It has been previously suggested, but the maintainers are not going to make it.  It would admit to not being careful during previous decisions on what to accept and might disrupt someone's workflow.

This really points to why only a few very basic aliases (if any) should be included in OMZ.  Aliases are mnemonics that only make sense to the fevered mind creating them.  Put them in Readme files to give people ideas and give examples of potentially better ways to do things, but don't actually enable them.  Everyone has different workflows and different things the do frequently enough to warrant using an alias.  The more aliases, the more likely a mistype could run something you don't want and some of the git aliases are the worse - any alias using --force is an example.
