### ISSUE TITLE
error: unknown option `local'

### ISSUE THREAD

**Issue by MeHelmy** [ohmyzsh/ohmyzsh#11126]
### Describe the bug

When I try to log in to a remote server or use `omz update` I get the following error:

```
error: unknown option `local'
usage: git config [options]
```
My git version is: `1.7.1` # Note, I can not update it.

Is there a fix to this issue?

Thanks

### Steps to reproduce

When I try to log in to a remote server or use `omz update`

### Expected behavior

No error

### OS / Linux distribution

Linux x86_64

### Zsh version

4.3.11

### Terminal emulator

Genome terminal

**Comment by mcornella** [comment]
Not supported configuration, and there are a lot more issues with these versions of git and zsh. CentOS 6 (which I presume was in use here) was EOL'd on November 2020.
