### ISSUE TITLE
Buggy completion in Docker

### ISSUE THREAD

**Issue by were** [ohmyzsh/ohmyzsh#11127]
### Describe the bug

I setup a Ubuntu 20.04 in Docker and have oh-my-zsh installed.

After that, if I use <tab> to complete, the chars I entered before <tab> will be doubled.

````
$ gi<tab>
$ gigi
# A bunch of candidates
````

### Steps to reproduce

In a docker, try to use <tab> to complete something.

### Expected behavior

No chars before <tab> should be doubled.

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/2356965/186017797-42e5cbf1-2faa-4c9f-83b0-fad274217103.png)
The first `gi` is doubled, and cannot be backspaced at all.

### OS / Linux distribution

Ubuntu 20.04 under Docker.

### Zsh version

5.4.2

### Terminal emulator

GNOME Terminal

**Comment by awh6al** [comment]
I think this is not related to any docker stuff
I'm using arch i3 with KDE konsole emulator but the bug is still reproducible
---
Linux 5.19.8-1-MANJARO
zsh 5.9
konsole 22.08.1

**Comment by mcornella** [comment]
Please see [the following FAQ entry](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command) to find how to fix this, which is related to using a non-UTF8 locale.
