### ISSUE TITLE
omz update with different remote name not working

### ISSUE THREAD

**Issue by robert-franz** [ohmyzsh/ohmyzsh#11135]
### Describe the bug

I'm using git with a different default naming of the git remotes. So my default ist not `origin` but `up`. When now updating the zsh with `omz update` this is not working.

My configuration in git config:
```
[clone]
        defaultRemoteName = up
```

In case I go to the cloned repository of oh-my-zsh and rename the git remote to `origin` then everything is working as expected.

### Steps to reproduce

set the git config clone.defaultRemoteName=anotherName

### Expected behavior

The update works the same like for `origin`.

### Screenshots and recordings

```sh
$ omz update
Updating Oh My Zsh
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
There was an error updating. Try again later?
```

### OS / Linux distribution

debian

### Zsh version

5.3.1

### Oh My Zsh version

29b5c182

### Terminal emulator

Konsole

**Comment by mcornella** [comment]
You can specify a different remote name for Oh My Zsh with the command below:
```zsh
cd $ZSH
git config --local oh-my-zsh.remote up
```
This variable is automatically set when the installer installs OMZ, but it names the remote `origin` directly. Did you perhaps clone the repository manually?

In any case, this is a bug in the installer, which does not use `git clone` but instead does it manually, so it should be aware of `clone.defaultRemoteName`.

**Comment by robert-franz** [comment]
@mcornella My setup using oh-my-zsh is having a home directory commited to a git repository. I can share scripts and aliases, configuration and so on different machines. So oh-my-zsh is a submodule in the git repository. So I'm definately not using the installer.

**Comment by mcornella** [comment]
Pushed a fix to automatically research the upstream remote name. You'll have to manually `git pull` to get the fix, then `omz update` will start working for this edge case.
