### ISSUE TITLE
`omz plugin disable` does not work

### ISSUE THREAD

**Issue by metya** [ohmyzsh/ohmyzsh#11146]
### Describe the bug

Command `omz plugin disable $plugin` does not work.
It just does not delete plugin from list plugins from `.zshrc` and from `$plugins` and plugins is continuing work.

### Steps to reproduce

For example:
1. `omz plugin enable github`
2. `echo $plugins`
github
3. `omz plugin disable github`
4. `echo $plugins`
github

### Expected behavior

For example:
1. `omz plugin enable github`
2. `echo $plugins`
github
3. `omz plugin disable github`
4. `echo $plugins`
empty line

### Screenshots and recordings

<img width="632" alt="изображение" src="https://user-images.githubusercontent.com/968934/188013996-8ae93958-6799-47d0-855c-fc94de5a1300.png">

### OS / Linux distribution

macOS 12.5.1 21G83 arm64

### Zsh version

5.8.1

### Oh My Zsh version

master (6d48309)

### Terminal emulator

macOS Treminal

**Comment by Adarsh-Liju** [comment]
`omz plugin disable github`  works for me , I am using ArcoLinux with ZSH

**Comment by carlosala** [comment]
Also works for me. Maybe you are in a subshell (using tmux or something like that)?

**Comment by mcornella** [comment]
It looks like you're using some kind of virtual environment judging by the `(base)` in the prompt. The CLI only reloads the changes when the shell is in interactive mode, so perhaps the virtual environment removed that option.

Run `setopt` and look for `interactive`, if its not there that is the reason it did not reload. In any case, you can manually reload the shell with `omz reload` to apply the changes.

**Comment by metya** [comment]
`(base)` is conda environment. It shouldn't affect on `omz` behavior.  But even if I turn off conda environment, `omz` behavior doesn't change.
And there is `interactive` in `setopt`. 

And even if I do `omz reload` manually, nothing happens.

**Comment by rwmitchell** [comment]
Can confirm.  Not doing any kind of virtual environment.  ```omz plugin enable github``` adds the plugin, but ```omz plugin disable github``` does not remove it.

I had assumed this was only changing my current session (quick way to try something without committing to it, but it changes ```.zshrc```.

Could it be because I have my plugins on multiple lines ? ie:

```
plugins=(
# battery   # disabled
  colorize
  gitfast
)
```

Doing it this way allows easily enabling/disabling while keeping a list of what has been tried (and rejected)

**Comment by carlosala** [comment]
With plugins in one line work, that should be the issue

**Comment by mcornella** [comment]
I designed the CLI to support multiline forms as this is my choice as well. Perhaps there is an incompatibility with the AWK script. Could you let me know the output of `awk --version`?

**Comment by rwmitchell** [comment]
20200816

I wondered if it was the embedded comment, but haven’t tested.

**Comment by metya** [comment]
> With plugins in one line work, that should be the issue

I have plugins in one line — it doesn't work for me.
