### ISSUE TITLE
Tab completion with prefix characters

### ISSUE THREAD

**Issue by StevenTang1998** [ohmyzsh/ohmyzsh#11147]
### Describe the proposed feature.

Can you support tab completion with prefix characters.
Such `--model=/path/...` with prefix characters `--model`.

**Comment by mcornella** [comment]
Can you explain further? Is this on a particular command?

**Comment by StevenTang1998** [comment]
I think it is not a particular command.

For example, this is the current directory tree:
```
(base) ➜  ~ ls *
aaa:
a.txt

bbb:
b.txt

test.py
```
I need to pass file path to the `test.py`. When I type `python test.py --path=aaa`, then I press tab, the tab completion does not work. However, it works in the default terminal. (maybe due to the character `-` or `=`)

**Comment by mcornella** [comment]
Commands that don't have a completion function get the generic one, which completes paths to the command.

This only works if you pass in the path in a single argument, if you use `--path=` then zsh doesn't know what to complete here and you won't get any suggestions.

Try either of these:
```
python test.py --path aaa[TAB]
python test.py aaa[TAB]
```
