### ISSUE TITLE
Cannot paste large text into zsh

### ISSUE THREAD

**Issue by sakaman** [ohmyzsh/ohmyzsh#11149]
### Describe the bug

Cannot paste large text fully (about more than 1000 characters) into ZSH in MAC using cmd + v that will miss lots of characters, but work in BASH.

### Steps to reproduce

1. disable plugin 'git zsh-autosuggestions zsh-syntax-highlighting history'
2. set DISABLE_MAGIC_FUNCTIONS="true" and no more other settings
3. paste large text(more than 1000 characters) from clipboard to zsh by cmd+v
4. zsh will lost characters beyond 1000
5. same actions to bash and work well

### Expected behavior

Paste large text fully into ZSH as BASH, especially for CURL statements.

### Screenshots and recordings

Original text:
<img width="1658" alt="image" src="https://user-images.githubusercontent.com/20101558/188321393-5e2f79c9-7986-48ab-b4c7-e40e6d8d4484.png">
ZSH: 
<img width="1819" alt="image" src="https://user-images.githubusercontent.com/20101558/188314580-2b802fb8-2c91-41bf-92e8-deaf85d685a0.png">
BASH:
<img width="1826" alt="image" src="https://user-images.githubusercontent.com/20101558/188314612-8d294b51-cf63-4eb6-8b4d-9cc7e272fea5.png">

### OS / Linux distribution

macOS 12.5.1

### Zsh version

7.8.1

### Oh My Zsh version

master (d41ca84)

### Terminal emulator

iTerm2

**Comment by rwmitchell** [comment]
If you are going to compare bash and zsh, you should do so with the same configuration - ie: disable all the fancy plugins.

**Comment by sakaman** [comment]
> If you are going to compare bash and zsh, you should do so with the same configuration - ie: disable all the fancy plugins.

Thanks for your tips, it still has same issue after disabling all plugins sadly.

**Comment by rwmitchell** [comment]
I put this in a file:

```printf "0bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST1bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST2bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST3bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST4bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST5bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST6bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST7bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST8bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST9bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST10cdefghijklmnopqrstABCDEFGHIJKLMNOPQRST11cdefghijklmnopqrstABCDEFGHIJKLMNOPQRST12cdefghijklmnopqrstABCDEFGHIJKLMNOPQRST#\n0bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST1bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST2bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST3bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST4bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST5bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST6bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST7bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST8bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST9bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST10cdefghijklmnopqrstABCDEFGHIJKLMNOPQRST11cdefghijklmnopqrstABCDEFGHIJKLMNOPQRST12cdefghijklmnopqrstABCDEFGHIJKLMNOPQRST#\n0bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST1bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST2bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST3bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST4bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST5bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST6bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST7bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST8bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST9bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST10cdefghijklmnopqrstABCDEFGHIJKLMNOPQRST11cdefghijklmnopqrstABCDEFGHIJKLMNOPQRST12cdefghijklmnopqrstABCDEFGHIJKLMNOPQRST#\n0bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST1bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST2bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST3bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST4bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST5bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST6bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST7bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST8bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST9bcdefghijklmnopqrstABCDEFGHIJKLMNOPQRST10cdefghijklmnopqrstABCDEFGHIJKLMNOPQRST11cdefghijklmnopqrstABCDEFGHIJKLMNOPQRST12cdefghijklmnopqrstABCDEFGHIJKLMNOPQRST#\n"```

Copied it into the cut buffer using pbcopy, then pasted it 3 iTerm2 windows, one with default zsh, default bash, and a more recent zsh I've compiled.  All three showed the entire output.  I then up-arrowed and take on "| wc".  All three returned "      4       4    2088"


<img width="747" alt="image" src="https://user-images.githubusercontent.com/15944841/188322692-8c57e5ee-0225-4a96-8bfe-baa92e229084.png">

**Comment by sakaman** [comment]
I just did same work but it didn't work as you.
1. echo large text into a file
![image](https://user-images.githubusercontent.com/20101558/188355159-3c28039c-2f47-44a1-90a1-3f80a9f9d0be.png)
2. paste into zsh
![image](https://user-images.githubusercontent.com/20101558/188355501-32eab4c7-f523-4829-b695-38876b15e6a9.png)
3. paste into bash
![image](https://user-images.githubusercontent.com/20101558/188355748-3b39369b-c15f-4042-a93a-b32ab83e4203.png)
4. same issue on mac default terminal

**Comment by sakaman** [comment]
Unstable issue
