### ISSUE TITLE
Filesystem tab autocompletion not working for multiple programs

### ISSUE THREAD

**Issue by TomKeyte** [ohmyzsh/ohmyzsh#11155]
### Describe the bug

tab autocompletion for multiple programs seems to have stopped working

I have reverted my `.zshrc` to the default  and still get the same behaviour. I've also ran a "clean" zsh via `zsh -d -f -i` and everything works as expected

### Steps to reproduce

* Install default oh-my-zsh
* Try to use `grep -R [tab]`

### Expected behavior

if I type `grep -R [tab]` I'd expect a list of directories, but nothing happens. I have [lsd](https://github.com/Peltoche/lsd) aliased to ls via `alias ls='lsd'` and would expect similar behaviour.

It does work however for the "default" ls if I type `\ls [tab]` or just remove the alias, I see the expected list of files/directories

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Terminal emulator

Terminator

**Comment by nmaggioni** [comment]
This should be fixed for `lsd` by Peltoche/lsd#741, and manually installing [v0.23.1](https://github.com/Peltoche/lsd/releases/tag/0.23.1) solved the problem for me.
