### ISSUE TITLE
brew plugin should not call brew shellenv if brew is already on the PATH.

### ISSUE THREAD

**Issue by tmoschou** [ohmyzsh/ohmyzsh#11166]
### Describe the bug

This PR change https://github.com/ohmyzsh/ohmyzsh/pull/10874 has caused the `brew` plugin to always call `eval $(brew shellenv)` regardless if the environment is already configured correctly. This has unintended consequences, for instance the brew bin directory (`/usr/local/bin` on MacOS Intel) is exported in `PATH` twice.

I would suggest this plugin mimic the behaviour of the brew [installer.sh](https://github.com/Homebrew/install/blob/eb943a56afc66244ff216a511058a89570440610/install.sh#L1017) to only require `eval $(brew shellenv)` if `brew` is not found in the path.

One other thing to note is the brew installer post-install steps says to modify `~/.zprofile` and not `~/.zshrc`. Perhaps this plugin should do what `pyenv` plugin does and [warn if the user did not run the post-install steps](https://github.com/ohmyzsh/ohmyzsh/blob/7dcabbe6826073ef6069c8a4b6f9a943f00d2df0/plugins/pyenv/pyenv.plugin.zsh#L1-L20) so that it may be called from non interactive scripts.

Other notes regarding the other environment variables exported by `shellenv`, specifically for MacOS Intel:

- `MANPATH` and `INFOPATH` are not required to add `/usr/local/share/man` and `/usr/local/share/info` - they are available in the search path by default.

- Neither is `HOMEBREW_PREFIX`, `HOMEBREW_CELLAR` and `HOMEBREW_REPOSITORY` required by brew to be exported. The `brew` command will ignore these environment variables and recalculate their values. Users should generally prefer `$(brew --prefix)` and not rely on or require `HOMEBREW_PREFIX` to be exported.

### Steps to reproduce

1. Enable plugin `brew`

2. `echo $PATH | tr ':' '\n'`

3. See `/usr/local/bin` listed twice

### Expected behavior

`PATH` should have `/usr/local/bin` listed once

### OS / Linux distribution

MacOS Intel 12.6 Monterey

### Zsh version

5.8.1

### Oh My Zsh version

7dcabbe6

### Terminal emulator

iTerm2

**Comment by carlosala** [comment]
`brew shellenv` is only called if `$HOMEBREW_PREFIX` is not defined. That variable is used in several places and we need to have it defined. If you define that properly then is not going to be called. Thanks for your contribution!

**Comment by tmoschou** [comment]
But why not `$(brew --prefix)` or `${HOMEBREW_PREFIX:-$(brew --prefix)}`. I can only see one place that uses `HOMEBREW_PREFIX` in oh-my-zsh, the nvm plugin, and its already does the latter to fall back. 

The problem is that change has now messed up my `PATH` with duplicate and out of order entries. The brew installation instructions and post install step for MacOS Intel do **not** tell you to set  `HOMEBREW_PREFIX` or call `brew shellenv`. So a normal user could not easily know that they need to manually set just `HOMEBREW_PREFIX` prior to loading the plugin, to by-pass their `PATH` getting duplicate entries.

**Comment by carlosala** [comment]
If you can make a pull request for that, we'd be happy to review and merge!
