### ISSUE TITLE
tab completion extends prompt temporarily when using flag emojis in the prompt

### ISSUE THREAD

**Issue by Ddfulton** [ohmyzsh/ohmyzsh#11170]
### Describe the bug

When there is flag emoji in the prompt and I am halfway through typing a command and I try to autocomplete it with <TAB>, the first word (space-delimited) of my half-baked command is duplicated and remains in the prompt even if try to I delete/backspace (I'm on MacOS) it away.

I think the examples will be more illustrative in this case.

### Steps to reproduce

1. Make a simple theme in `~/.oh-my-zsh/themes`
```
🇬🇧  cat ~/.oh-my-zsh/themes/derek.zsh-theme  # this line is the prompt, set theme only to what comes after cat
PROMPT="🇬🇧  "
RPROMPT=""
```
2. Go into a directory with some files you might want to edit, verify this with `ls`
```
🇬🇧  ls *.py
app.py  app2.py
```
3. Type `vim app<TAB>`. Before the tab your prompt and unfinished command should be `🇬🇧  vim app`. After the tab your prompt will be 
```
🇬🇧  vimvim app
app.py   app2.py  # These are the zsh suggestions
```
4. If you just type `vim ap<TAB>` it will autocomplete you to `vim app` without issue. It seems this issue only arises when the autocomplete is "stuck" and showing you the multiple options for autocomplete, which you can flip through by repeatedly hitting <TAB>.

### Expected behavior

Before the tab your prompt and unfinished command should be `🇬🇧  vim app`. After the tab your prompt will be 
```
🇬🇧  vimvim app
app.py   app2.py  # These are the zsh suggestions
```

### Screenshots and recordings

https://asciinema.org/a/CXs4W8xRe847R5LVODxmW5QFz
PLEASE IGNORE THE LAGGING CURSOR, THAT SEEMS TO BE A BUG IN asciinema BUT MY LOCAL CURSOR IS FINE

### OS / Linux distribution

MacOS 12.3.1 with Darwin Kernel 21.4.0

### Zsh version

5.8

### Oh My Zsh version

master (d41ca84)

### Terminal emulator

iTerm2

**Comment by carlosala** [comment]
Please see [the following FAQ entry](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command) to find how to fix this, which is related to using a non-UTF8 locale.
Thanks for your report! 😉

**Comment by Ddfulton** [comment]
@carlosala I am using a UTF-8 locale:

```
🇬🇧  locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by laozaoa** [comment]
iterm2:
Preferrences -> Profiles -> Text -> Unicode -> Use unicode version 9+ widths
