### ISSUE TITLE
issue for typing "/" after oh-my-zsh installation

### ISSUE THREAD

**Issue by alinaserinet** [ohmyzsh/ohmyzsh#11171]
### Describe the bug

Hi.
I can't type "/" (slash) in fedora terminal after oh-my-zsh installation!
I removed oh-my-zsh then I can type it correctly!
I don't know why this problem occurred.

### Steps to reproduce

1. install zsh by "sudo dnf install zsh"
2. I can type "/ (slash)" in terminal.
3. get oh-my-zsh via curl and use it
4. then I can't type "/"
5. remove ~/.zshrc 
6. I can type "/"

### Expected behavior

I don't know why after installation I can't type "/".

### OS / Linux distribution

Fedora 36

### Zsh version

zsh 5.8.1 (x86_64-redhat-linux-gnu)

### Oh My Zsh version

master (7dcabbe)

### Terminal emulator

GNOME Terminal (Version 3.44.1 for GNOME 42)

**Comment by rwmitchell** [comment]
Why did you close, is it resolved?
