### ISSUE TITLE
TAB autocomplete file/dir names doesn't suggest all files/dirs

### ISSUE THREAD

**Issue by kustodian** [ohmyzsh/ohmyzsh#11175]
### Describe the bug

TAB autocomplete doesn't show all files/dirs in some specific file/dir name combinations.

### Steps to reproduce

To recreate this issue:
```bash
mkdir zsh-tab-fail
cd zsh-tab-fail
mkdir s s1 t t1
cd <TAB> <TAB>
```
That's it.

### Expected behavior

I would expect that the first `TAB` would list all the directories instead of selecting `T`.

### Screenshots and recordings

List all files:
![image](https://user-images.githubusercontent.com/1949229/191455806-4e03fea8-164c-487e-91b8-897f6b2f1ba3.png)
type `cd ` and pres `TAB`:
![image](https://user-images.githubusercontent.com/1949229/191455912-31b349c0-5bf7-4967-8585-bf5ab1bae8f8.png)
press `TAB` again:
![image](https://user-images.githubusercontent.com/1949229/191455953-cd44731a-408a-4154-a45f-97584d60e1d1.png)
press `TAB` again:
![image](https://user-images.githubusercontent.com/1949229/191456016-7f20a2d8-e484-4d9c-ac89-ffaad30e5057.png)
As you can see pressing `TAB` for some reason first displays a capital `T` which then turns into a lower `t` and so on.

Here is a video showing this:
https://user-images.githubusercontent.com/1949229/191459233-c6c390dc-3da4-4aee-8044-9e8d73f5f8e2.mp4

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Terminal emulator

Konsole

### Additional context

This fails with the most basic config:
```
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
source $ZSH/oh-my-zsh.sh
```

**Comment by kustodian** [comment]
Here is one more repro:
```bash
mkdir dir1
cd dir1
touch d e
ls <TAB>
```

**Comment by carlosala** [comment]
This is a known regression introduced in zsh 5.9, it's actually not our issue. You can check more info [here](https://github.com/ohmyzsh/ohmyzsh/issues/10972#issuecomment-1146806099).
Duplicated #10972

**Comment by mcornella** [comment]
Fixed in https://github.com/ohmyzsh/ohmyzsh/pull/11526. Get the fix with `omz update`.
