### ISSUE TITLE
Autocomplete broken in very specific cases

### ISSUE THREAD

**Issue by cloudsftp** [ohmyzsh/ohmyzsh#11193]
### Describe the bug

Autocomplete behaves weird in very specific cases.

### Steps to reproduce

1. Create a new directory
2. Create two empty files `touch start submodules` (use these names others might not reproduce the bug)
3. Type `cat s` and then hit `<TAB>`

### Expected behavior

This output is to be expected:
```
> cat s
start             submodules
```

This is displayed:
```
> cat sUB
```

### OS / Linux distribution

OpenSUSE Tumbleweed

### Zsh version

5.9

### Oh My Zsh version

master (7dcabbe)

### Terminal emulator

Kitty, Konsole

### Additional context

I tested it with a fresh install of OpenSUSE and ZSH. The bug was not present.

I then installed OMZ and the bug appeared.
No plugins installed, "empty" `.zshrc` file.

**Comment by carlosala** [comment]
This is a known regression introduced in zsh 5.9, it's actually not our issue. You can check more info [here](https://github.com/ohmyzsh/ohmyzsh/issues/10972#issuecomment-1146806099).
Duplicated #10972

**Comment by mcornella** [comment]
Fixed in https://github.com/ohmyzsh/ohmyzsh/pull/11526. Get the fix with `omz update`.
