### ISSUE TITLE
Auto completion does not work for comparing 2 different files from 2 different branch

### ISSUE THREAD

**Issue by tmvkrpxl0** [ohmyzsh/ohmyzsh#11197]
### Describe the bug

I compare 2 different files from git remote like this:
`git diff origin/branch1:file.txt origin/branch2:file.txt`
However, auto completion only works until this point: `git diff origin/branch1:file.txt`, pressing tab afterward does not bring me list of usable remotes, branches in the said remote, and files in the said branch, unlike first one in branch1, which auto completion works fine.

### Steps to reproduce

1. Clone any repository with 2 or more branches
2. Try to get difference of 2 files using `git diff origin/branch1:path/to/file origin/branch2:path/to/file`
3. Observe that auto completion doesn't work for second one

### Expected behavior

I expected it to also auto complete second one

### Screenshots and recordings

https://user-images.githubusercontent.com/41675181/192280070-55a2f509-b33f-4f84-ad3b-8fe63fb2e401.mp4

I mashed tab at the end but it doesn't do anything

### OS / Linux distribution

KDE Neon 20.04

### Zsh version

5.8

### Terminal emulator

Yakuake

**Comment by carlosala** [comment]
That's actually issue from `git` completion, coming with `zsh`. Would be great to have it, I agree!
Thanks for your report!
