### ISSUE TITLE
ssh-agent quiet option apply to ssh-add 

### ISSUE THREAD

**Issue by sebtiz13** [ohmyzsh/ohmyzsh#11201]
### If the feature request is for a plugin or theme, specify it here.

ssh-agent 

### If the feature solves a problem you have, specify it here.

The option `zstyle :omz:plugins:ssh-agent quiet yes` is very interesting, but I think is not complete.
The command `ssh-add` have print like "Identity added: /home/<user>/.ssh/id_rsa (/home/<user>/.ssh/id_rsa)"

In certain case, `Powerlevel10k` with option "[Instant prompt](https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt)" can have problem this type of print.
Also I think is most coherent.

### Describe the proposed feature.

When the option quiet is enable, just add `>/dev/null 2>&1` to the `ssh-add` command

**Comment by mcornella** [comment]
Mea culpa, I see that we did not end up silencing the `ssh-add` command, which is what you were asking. LGTM

**Comment by sebtiz13** [comment]
Thanks that work perfectly
