### ISSUE TITLE
Terminal icons are missing 

### ISSUE THREAD

**Issue by jangdaon** [ohmyzsh/ohmyzsh#11206]
### Describe the bug

<img width="640" alt="Screen Shot 2022-10-01 at 5 57 23 PM" src="https://user-images.githubusercontent.com/84892575/193401671-7795a185-b98a-4bf1-b11b-6674a657cd00.png">
<img width="659" alt="Screen Shot 2022-10-01 at 5 59 01 PM" src="https://user-images.githubusercontent.com/84892575/193401747-bce8a7a0-6aaf-488a-8378-b11effdb3a2d.png">

My terminal's icons are missing after I installed 'Ohmyzsh'
I tried to change the font through visual studio art.
When I searched the internet, many people say to try to check the 'Use a different font for non-ASCII text'. 
But I should not find this in my preference. 
How can I solve this ... ?

### Steps to reproduce

My terminal's icons are missing after I installed 'Ohmyzsh'
I tried to change the font through visual studio art.
When I searched the internet, many people say to try to check the 'Use a different font for non-ASCII text'. 
But I should not find this in my preference. 

### Expected behavior

.

### OS / Linux distribution

M1 mac 

### Zsh version

5.8.1

### Terminal emulator

Terminal

**Comment by carlosala** [comment]
Hi! I don't know how MacOS terminal works, but for sure this is not a ohmyzsh issue. Maybe looking for something in stackoverflow would work.
Good luck out there! :)

**Comment by guptaashwanee** [comment]
> ### Describe the bug
> <img alt="Screen Shot 2022-10-01 at 5 57 23 PM" width="640" src="https://user-images.githubusercontent.com/84892575/193401671-7795a185-b98a-4bf1-b11b-6674a657cd00.png">
> 
> <img alt="Screen Shot 2022-10-01 at 5 59 01 PM" width="659" src="https://user-images.githubusercontent.com/84892575/193401747-bce8a7a0-6aaf-488a-8378-b11effdb3a2d.png">
> 
> My terminal's icons are missing after I installed 'Ohmyzsh' I tried to change the font through visual studio art. When I searched the internet, many people say to try to check the 'Use a different font for non-ASCII text'. But I should not find this in my preference. How can I solve this ... ?
> 
> ### Steps to reproduce
> My terminal's icons are missing after I installed 'Ohmyzsh' I tried to change the font through visual studio art. When I searched the internet, many people say to try to check the 'Use a different font for non-ASCII text'. But I should not find this in my preference.
> 
> ### Expected behavior
> .
> 
> ### Screenshots and recordings
> _No response_
> 
> ### OS / Linux distribution
> M1 mac
> 
> ### Zsh version
> 5.8.1
> 
> ### Terminal emulator
> Terminal
> 
> ### If using WSL on Windows, which version of WSL
> _No response_
> 
> ### Additional context
> _No response_

<img width="361" alt="Screenshot 2022-11-01 at 3 37 42 PM" src="https://user-images.githubusercontent.com/52340682/199210223-42d2e1f2-2cf9-4906-80c4-61ff1d7ce9de.png">

**Comment by guptaashwanee** [comment]
It's same in my Laptop also

**Comment by rwmitchell** [comment]
There are both powerline and nerd fonts.  P9K/P10K is particular about which is used, but they may only pertain to certain glyphs.  However, to test that,  I suggest getting/trying a nerd font (https://www.nerdfonts.com).  After installing it, set using the Font Change... button in your screenshot.

The non-ascii font is a setting in iTerm2, a very popular alternative to Apple's Terminal.

I'm using Sauce Code Pro Nerd Font Complete Mono 12.0 pt. in Terminal and glyphs work.
