### ISSUE TITLE
Virtual env not working

### ISSUE THREAD

**Issue by DogDad65** [ohmyzsh/ohmyzsh#11216]
Hello,
I'm new at this so apparently I'm doing something wrong.
 I get this message when I run python manage.py  migrate.
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

**Comment by destrex271** [comment]
Please first create a virtual environment for your project. for that you need to install the virtualenv package
`pip install virtualenv`
and then create the same in your  project folder as:
`python -m venv venv`
Activate the virtual environment as:
`source venv/bin/activate.sh`
and then install django as:
`pip install django`

To deactivate your virtaulenvironemnt:
`deactivate`

**Comment by DogDad65** [comment]
Copy that.Thank you!Sent from my iPhoneOn Oct 4, 2022, at 13:54, Akshat Jaimini ***@***.***> wrote:﻿
Please first create a virtual environment for your project. for that you need to install the virtualenv package
pip install virtualenv
and then create the same in your  project folder as:
python -m venv venv
Activate the virtual environment as:
source venv/bin/activate.sh
and then install django as:
pip install django
To deactivate your virtaulenvironemnt:
deactivate
