### ISSUE TITLE
zsh using 100% CPU

### ISSUE THREAD

**Issue by patrikkaprinay** [ohmyzsh/ohmyzsh#11248]
### Describe the bug

zsh is using 100% of my CPU, when no terminal windows open or anything running. My M1 MacBook Air was constantly on 80C+ while only surfing the web. Opened the activity monitor and zsh is using 100% CPU.

### Steps to reproduce

Opened the terminal yesterday, used for a few minutes, closed it and today noticed it uses 

### Expected behavior

Not run at 100% CPU usage

### Screenshots and recordings

![Screenshot 2022-10-08 at 22 22 00](https://user-images.githubusercontent.com/73066846/194726709-18bd4176-e6e0-4299-bcb0-807ea040d755.jpg)
![Screenshot 2022-10-08 at 22 22 22](https://user-images.githubusercontent.com/73066846/194726711-dfec3685-b218-4b20-94a6-0acabddb23fa.jpg)

### OS / Linux distribution

MacOS 12.5.1 (21G83)

### Zsh version

5.8.1

### Terminal emulator

iTerm2

**Comment by rwmitchell** [comment]
zsh is not OMZ and nothing you've shown shows you are even using OMZ. (ie: you're asking the wrong group)

Sometimes processes go rogue.  Without a lot more information than you've displayed here, it is impossible to say why.
Have a nice day.
