### ISSUE TITLE
feature: Switch Git_SSH-Account more easy!!

### ISSUE THREAD

**Issue by tw-yshuang** [ohmyzsh/ohmyzsh#11242]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### Describe the proposed feature.

Easily switch to the git account & ssh key when using the server, and use different accounts to manipulate the project on the server.

### Describe alternatives you've considered

Hi, I'm the author of the [Git_SSH-Account_Switch](https://github.com/tw-yshuang/Git_SSH-Account_Switch), I create a tool that can easy to switch the ssh account for the Github with `git-acc` command, I think this tool may contribute for `ohmyzsh`, I saw @mcornella was replied lots of issues & features that related with `git`, would you mind measuring my tool is a useful feature to contribute to this repo?

### Additional context

# [Git_SSH-Account_Switch](https://github.com/tw-yshuang/Git_SSH-Account_Switch)
please go to checkout the above link

```shell
        +---------------+
        |    git-acc    |
        +---------------+

SYNOPSIS

  git-acc [account]|[option]

OPTIONS

  [account]               use which accounts on this shell, type the account name that you register.
  -h, --help              print help information.
  -add, --add_account     build git_account info. & ssh-key.
      -t, --type          ssh-key types, follow `ssh-keygen` rule, 
                          types: dsa | ecdsa | ecdsa-sk | ed25519 | ed25519-sk | rsa(default)
  -rm, --remove_account   remove git_account info. & ssh-key from this device
  -out, --logout          logout your current ssh-acc.


EXAMPLES

  $ git-acc tw-yshuang
```

**Comment by mcornella** [comment]
This is a full tool that would be best distributed as a simple binary, and there is no reason to have it as a plugin as it does not need to be hooked into the zsh session.

Nevertheless, I wish you good luck in finding users for the project. Thanks!
