### ISSUE TITLE
omz update opens a new shell

### ISSUE THREAD

**Issue by marafa-sugarcrm** [ohmyzsh/ohmyzsh#11249]
### Describe the bug

every morning i run this script to update my mac. it is one of many scripts i run from a master script. there are scripts that run before and after this script. i call it `zsh_setup.sh` 
```sh
#!/bin/sh

[[ $SHELL == *"zsh" ]] || {
  echo "$(date) : $(hostname -f) : $(basename $0) : Changing default shell to zsh for $USER"
  chsh -s /bin/zsh
}

[ -d $HOME/.oh-my-zsh ] || sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

[ -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k ] || {
  echo "$(date) : $(hostname -f) : $(basename $0) : Installing powerlevel10k"
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
}

[ -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k ] && {
echo "$(date) : $(hostname -f) : $(basename $0) : Updating powerlevel10k"
git -C ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k pull
}

[ -f $HOME/.zshrc ] && sed -i 's,^ZSH_THEME.*,ZSH_THEME="powerlevel10k/powerlevel10k",g' $HOME/.zshrc

zsh -c '. ~/.zshrc; omz update'
```

the thing is `omz update` opens a new shell if there is an actual update. which interrupts the flow of my master script.

how do i get `omz update` to exit and return control to the master script?

### Steps to reproduce

1. write script `master.sh`
2. have commands before and after zsh_setup.sh
3. watch when an actual update interrupts flow

### Expected behavior

master.sh continues on its happy path

### OS / Linux distribution

mac 12.6

### Zsh version

5.8.1

### Terminal emulator

iterm2

**Comment by rwmitchell** [comment]
Just curious, how often is you shell getting changed to something non-zsh and all of your customizations are completely wiped out?

**Comment by marafa-sugarcrm** [comment]
it has never happened so far. the script tho is used by other users who want to use zsh as their default shell. so they just run this

**Comment by rwmitchell** [comment]
If it does happen, your system is screwed in ways that need to be investigated and not just glossed over.

Your script is great to run on initial setup and you should continue to use it as such, but it shouldn't need to be run beyond that.  OMZ automatically checks and updates itself every 2 weeks, which for the of changes that actually happen is way plenty often.

By waiting two weeks to update, you also increase the chances that a non-optimal update will get corrected before the automatic refresh.

That's my take.  You could also just go to your .oh-my-zsh directly and run ```git pull``` from there (after it has been installed) to avoid using ```omz update``` as you don't really care about tracking when to update (which is mostly what that does, nor do you want to auto restart zsh to pick up the changes, if there any.  You'll need to do a bit more digging in tools/upgrade.sh if you care about seeing the changes.
