### ISSUE TITLE
Don't use abbreviations for git alias flags

### ISSUE THREAD

**Issue by jdevries3133** [ohmyzsh/ohmyzsh#11244]
### If the feature request is for a plugin or theme, specify it here.

Git

### If the feature solves a problem you have, specify it here.

I often lookup oh-my-zsh aliases as follows:

```zsh
alias | grep git
alias | grep "git commit"
```

Here are the results of the latter command:

```
gcas='git commit -a -s'
gcasm='git commit -a -s -m'
gcmsg='git commit -m'
'gcn!'='git commit -v --no-edit --amend'
```

I'm wondering: What is the `-a` flag? What is the `-s` flag? I have to separately go and lookup this information.

### Describe the proposed feature.

I'd like aliases to stay away from using abbreviated flags, and to use the verbose versions instead where available. I'd like to implement this feature for the git plugin, at least, if this feature is desired.

### Describe alternatives you've considered

I think it's possible that there's a blind spot in my workflow as stated above; please let me know if that's the case!

**Comment by sevy2011** [comment]
man git
```
HIGH-LEVEL COMMANDS (PORCELAIN)
       We separate the porcelain commands into the main commands and some ancillary user utilities.

   Main porcelain commands
[...]
       git-commit(1)
           Record changes to the repository.
```

man git-commit
```
OPTIONS
       -a, --all
           Tell the command to automatically stage files that have been modified and deleted, but new files you have not told Git about are not affected.
[...]
       -s, --signoff, --no-signoff
           Add a Signed-off-by trailer by the committer at the end of the commit log message. The meaning of a signoff depends on the project to which you’re
           committing. For example, it may certify that the committer has the rights to submit the work under the project’s license or agrees to some contributor
           representation, such as a Developer Certificate of Origin. (See http://developercertificate.org for the one used by the Linux kernel and Git
           projects.) Consult the documentation or leadership of the project to which you’re contributing to understand how the signoffs are used in that
           project.

           The --no-signoff option can be used to countermand an earlier --signoff option on the command line.
```

**Comment by jdevries3133** [comment]
Absolutely, just wanted to hear if the idea was supported first. I'll get started!

**Comment by jdevries3133** [comment]
Absolutely, just wanted to hear if the idea was supported first. I'll get started!

**Comment by mcornella** [comment]
The only downside to this is to have the aliases documented in the README as well, which has limited space for the full-style arguments.

This difference makes it harder to write the documentation for plugins, and if this is something that we need to enforce as a style guide it should be also changed in other plugins, which is significantly more work.

In any case, at this stage I believe it is fine to make the change for just the git plugin.

**Comment by jdevries3133** [comment]
> The only downside to this is to have the aliases documented in the README as well

I will also update the readme and other documentation. I don't think it's exactly a downside – the readme will be more self-documenting when it includes the verbose flags. As far as the table becoming super wide, it seems like GitHub wraps very long cells, so the reading experience on GitHub should still be OK.

<img width="1017" alt="Screen Shot 2022-10-14 at 3 25 06 PM" src="https://user-images.githubusercontent.com/58614260/195926246-5f88dd83-18c1-4c0a-83a4-40bdc9502a7f.png">

> This difference makes it harder to write the documentation for plugins, and if this is something that we need to enforce as a style guide it should be also changed in other plugins, which is significantly more work.

I agree, but I'll always advocate for incrementalism. I do think that refactoring every plugin in this way would be an error-prone and time consuming effort, so maybe it's best to keep attention on the most used plugins, or just await feature requests like this instead of launching any larger initiative or sweeping style guide change.

**Comment by jdevries3133** [comment]
See https://github.com/ohmyzsh/ohmyzsh/pull/11259
