### ISSUE TITLE
Couldn't close git plugin

### ISSUE THREAD

**Issue by yinghaoyu** [ohmyzsh/ohmyzsh#11251]
### Describe the bug

I couldn't close git plugin after removing it from `plugins=()` in `.zshrc`

### Steps to reproduce

1. vim ~/.zshrc
2. remove git in `plugins=()`
3. reopen terminal

### Expected behavior

close git plugin

### OS / Linux distribution

Ubuntu 20.04

### Zsh version

5.8

### Oh My Zsh version

master (6622210d)

### Terminal emulator

windows terminal

### If using WSL on Windows, which version of WSL

WSL2

**Comment by rwmitchell** [comment]
What does ‘close git plugin’ mean? How is it supposed to close?  What verifies it is still open?

**Comment by robbyrussell** [comment]
@yinghaoyu  Are you referring to your prompt showing git branch information still?

If so, that's independent of the git plugin but a feature of the them you're using. 

The git plugin brings in additional aliases and functions:

* https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git

I'm going to assume that is what you're referring to (happy to re-open if you are experiencing something else)
