### ISSUE TITLE
zprofile.pre.zsh:1: no such file or directory: .local/bin/fig

### ISSUE THREAD

**Issue by iszhangsc** [ohmyzsh/ohmyzsh#11253]
### Describe the bug

/Users/zhangshichang/.fig/shell/zprofile.pre.zsh:1: no such file or directory: /Users/zhangshichang/.local/bin/fig
/Users/zhangshichang/.fig/shell/zprofile.post.zsh:1: no such file or directory: /Users/zhangshichang/.local/bin/fig
/Users/zhangshichang/.fig/shell/zshrc.pre.zsh:1: no such file or directory: /Users/zhangshichang/.local/bin/fig
/Users/zhangshichang/.fig/shell/bash_profile.pre.bash:1: no such file or directory: /Users/zhangshichang/.local/bin/fig

### Steps to reproduce

It happens when I open iTerm2

### Expected behavior

....

### OS / Linux distribution

mac os 10.13

### Zsh version

5.9

### Terminal emulator

iTerm2

**Comment by mcornella** [comment]
This has nothing to do with Oh My Zsh, it looks like Fig was uninstalled and there are still remnants of the old shell files. See https://fig.io/user-manual/other/uninstall for how to uninstall further, but try to force-quit iTerm before attempting anything else.

You can also ask on their Discord community: https://fig.io/community.
