### ISSUE TITLE
file stack same different with bash

### ISSUE THREAD

**Issue by blaoke** [ohmyzsh/ohmyzsh#11260]
### Describe the bug

```
$ cd wendang            

# bu @ blaoke in ~/wendang [13:04:02] 
$ dirs -v
0	~/wendang
1	~

# bu @ blaoke in ~/wendang [13:04:05] 
$ cd study  

# bu @ blaoke in ~/wendang/study [13:04:32] 
$ dirs -v
0	~/wendang/study
1	~/wendang
2	~
```

### Steps to reproduce

```
$ cd wendang            

# bu @ blaoke in ~/wendang [13:04:02] 
$ dirs -v
0	~/wendang
1	~

# bu @ blaoke in ~/wendang [13:04:05] 
$ cd study  

# bu @ blaoke in ~/wendang/study [13:04:32] 
$ dirs -v
0	~/wendang/study
1	~/wendang
2	~
```

### Expected behavior

```
# bu @ blaoke in ~ [13:03:48] 
$ bash
bu@blaoke:~$ cd wendang/
bu@blaoke:~/wendang$ dirs -v
 0  ~/wendang
bu@blaoke:~/wendang$ cd study
bu@blaoke:~/wendang/study$ dirs -v
 0  ~/wendang/study
bu@blaoke:~/wendang/study$ 
```

### OS / Linux distribution

20.04

### Zsh version

5.6

### Oh My Zsh version

master

### Terminal emulator

terminator

**Comment by mcornella** [comment]
OMZ sets the `setopt autopushd` which means all directories visited are pushed to the stack. This has no impact if you're not using the stack at all, but if you want to turn this off you can add
```
unsetopt autopushd
```
to your `.zshrc` file, after OMZ is sourced.

Not considering this a bug.

**Comment by blaoke** [comment]
Thanks bro! It's useful.



---Original---
From: ***@***.***&gt;
Date: Sat, Oct 15, 2022 18:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ohmyzsh/ohmyzsh] file stack same different with bash (Issue#11260)




 
OMZ sets the setopt autopushd which means all directories visited are pushed to the stack. This has no impact if you're not using the stack at all, but if you want to turn this off you can add
 unsetopt autopushd  
to your .zshrc file, after OMZ is sourced.
 
Not considering this a bug.
