### ISSUE TITLE
docs: broken link found in Themes page.

### ISSUE THREAD

**Issue by mdfaizanahmed786** [ohmyzsh/ohmyzsh#11267]
### What's this issue about?
There is a broken link in the themes page.

### Where's the actual broken link?
The link is in the [Themes page](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#dont-send-us-your-theme-for-now) under **Version 2013-04**. 

### Which link is broken?
[Screenshots](https://www.dropbox.com/sh/u532agyv1hyash1/LS9yNESRlQ?lst) is broken under **Version 2013-04**

**Comment by OyinOlamide** [comment]
Hi @mdfaizanahmed786 Can I take this up?

**Comment by mcornella** [comment]
This should be changed in the https://github.com/ohmyzsh/wiki page. Feel free to remove the link there.

**Comment by mcornella** [comment]
Issue fixed
