### ISSUE TITLE
New z plugin does not work by placing it into ~/.zshrc → plugins=(... z) array

### ISSUE THREAD

**Issue by dvakatsiienko** [ohmyzsh/ohmyzsh#11286]
### Describe the bug

At this moment [oh-my-zsh plugin docs](https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins) saying that any plugin listed is enabled by listing it in `plugins=(...)` array.

Doing so with [new version of z](https://github.com/agkozak/zsh-z) causes:

```sh
zsh: command not found: z
```

### Steps to reproduce

1. Upgrade to latest oh-my-zsh
2. in .zshrc put **z** into **plugins** array
3. reload terminal
4. navigate with **z**
5. `zsh: command not found: z`

### Expected behavior

I expect **z** to work once placed into **plugins** array.

### Screenshots and recordings

My `.zshrc`:

```sh
# Oh My Zsh
export ZSH=$HOME/.oh-my-zsh # Path to oh-my-zsh installation.
export ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST # Store zsh's completion cache inside oh-my-zsh cache folder

# Oh My Zsh config variables
ZSH_THEME=half-life
ENABLE_CORRECTION=true
ZSH_CUSTOM=~/.config/oh-my-zsh-custom # my oh-my-zsh customization folder. contains aliases, functions, plugins, etc.

plugins=(z)

# Init Oh My Zsh after its config variables are set
source $ZSH/oh-my-zsh.sh
```

### OS / Linux distribution

MacOS Monterey 12.6 (21G115)

### Zsh version

5.9

### Oh My Zsh version

master (0066280)

### Terminal emulator

iTerm2

### Additional context

**[agkozak](https://github.com/agkozak)** version of **z** installation section mentions to use a plugin manager to install it.
So **plugins** approach won't work with it and to install new **z** a plugin manager needs to be used?

**Comment by rwmitchell** [comment]
> At this moment [oh-my-zsh plugin docs](https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins) saying that any plugin listed is enabled by listing it in plugins=(...) array.

that is true, that is how a plugin is enabled.  however, some/many plugins also require external programs, for example 'git'.  The git plugin adds a lot of completions and aliases for git, but it does not provide git, you have to do that.

**Comment by carlosala** [comment]
I can't reproduce. For me it's working fine!

**Comment by agkozak** [comment]
> [agkozak](https://github.com/agkozak) version of z installation section mentions to use a plugin manager to install it.
So plugins approach won't work with it and to install new z a plugin manager needs to be used?

Oh My Zsh now includes a version of Zsh-z as `z`, so what you're trying to do should work; in fact, your `.zshrc` does work for me on Ubuntu.

**Comment by mcornella** [comment]
Please create a trace of the zsh startup with the command below, and attach the file (omz-debug.log) here for inspection
```
zsh -xvlic exit &> ~/omz-debug.log
```

**Comment by dvakatsiienko** [comment]
I've tried different approach by manually cloning a [zsh-z](https://github.com/agkozak/zsh-z) into Oh My Zsh Custom directory, by following [an instruction](https://github.com/agkozak/zsh-z#for-oh-my-zsh-users) — still having same output: `zsh: command not found: z`.

@mcornella here is a trace file.

[omz-debug.log](https://github.com/ohmyzsh/ohmyzsh/files/9868871/omz-debug.log)

**Comment by 0xSysR3ll** [comment]
I am on Manjaro and I remember having kind of the same issue.
You can try to install the package `z` through `brew`, see if it is better or not.

**Comment by dvakatsiienko** [comment]
None of the proposed fixes worked for me, so switched to `brew install z`.
It works, but seems to use old version of `z` which is not `zsh-z`.

Probably the issues is related to `M1` processor somehow?

**Comment by 0xSysR3ll** [comment]
> None of the proposed fixes worked for me, so switched to `brew install z`.
> 
> It works, but seems to use old version of `z` which is not `zsh-z`.
> 
> 
> 
> Probably the issues is related to `M1` processor somehow?

In fact, it seems to be using [this](https://github.com/rupa/z) version of `z`.

**Comment by dvakatsiienko** [comment]
> In fact, it seems to be using [this](https://github.com/rupa/z) version of `z`.

yes, it is.

**Comment by carlosala** [comment]
That should not happen, as `z` is defined inside the plugin, so adding the plugin should be enough. Even more, this new plugin has no dependencies as it's fully written in `zsh`.

**Comment by carlosala** [comment]
> I've tried different approach by manually cloning a [zsh-z](https://github.com/agkozak/zsh-z) into Oh My Zsh Custom directory, by following [an instruction](https://github.com/agkozak/zsh-z#for-oh-my-zsh-users) — still having same output: `zsh: command not found: z`.
> 
> @mcornella here is a trace file.
> 
> [omz-debug.log](https://github.com/ohmyzsh/ohmyzsh/files/9868871/omz-debug.log)

In the trace file I see that you are also loading a custom plugin called `zsh-z`. Could you try without that?

**Comment by dvakatsiienko** [comment]
@carlosala Yes, here is my `.zshrc` and new `omz-debug.log`.

[omz-debug.log](https://github.com/ohmyzsh/ohmyzsh/files/9937382/omz-debug.log)

```sh
# Oh My Zsh
export ZSH=$HOME/.oh-my-zsh # Path to oh-my-zsh installation.
export ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST # Store zsh's completion cache inside oh-my-zsh cache folder

# Oh My Zsh config variables
ZSH_THEME=half-life
ZSH_CUSTOM=~/.config/oh-my-zsh-custom # my oh-my-zsh customization folder. contains aliases, functions, plugins, etc.

# Oh My Zsh plugins
plugins=( z )

# Init Oh My Zsh after its config variables are set
source $ZSH/oh-my-zsh.sh

# User Configuration
export EDITOR=vim # Default editor
export BAT_THEME=gruvbox-dark # Set bat theme

# init nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# init iTerm2 shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
```

**Comment by mcornella** [comment]
You have a custom `aliases.zsh` file that deletes all aliases:
```
alias ${ZSHZ_CMD:-${_Z_CMD:-z}}='zshz 2>&1'
+/Users/furthur/.oh-my-zsh/plugins/z/z.plugin.zsh:845> alias 'z=zshz 2>&1'
...
# Delete all built-in aliases: system and oh-my-zsh
unalias -m '*'
+/Users/furthur/.config/oh-my-zsh-custom/aliases.zsh:2> unalias -m '*'
```

Without aliases, there is no alias named `z`, which is how the plugin works.

You can set `alias 'z=zshz 2>&1'` in the `oh-my-zsh-custom/aliases.zsh` file if you still want to keep the `unalias -m '*'` line.
