### ISSUE TITLE
Plugin 'z' broken after update

### ISSUE THREAD

**Issue by bipin-lekhak** [ohmyzsh/ohmyzsh#11282]
### Describe the bug

_This is the first time I am reporting bugs to OSS, apologies if I do not follow proper protocol or am not clear enough. Sorry :)_ 

Running plugin z was working perfectly before I updated ohmyzsh.

Running 'z' plugin throws the following error:
`_setup:37: compstate: assignment to invalid subscript range`

Oh my zsh's commit hash shows that the commit hash 7e3231b introduced some changes to the z plugin, which makes me suspect if that was the reason for this behavior. 

I was able to reproduce the same behavior in macOS as well as an Ubuntu machine. 

### Steps to reproduce

Enable plugin z

Try to use plugin z by pressing `z` key follwed by a `space key` and a `tab` 

Use arrow keys to cd into a folder and press enter

### Expected behavior

Should cd into selected folder without any error

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/52912520/197274067-0d21d80f-ee39-44d3-b34c-968c50d46a44.png)

### OS / Linux distribution

Ubuntu 22.04.1 LTS, macOS 12.6

### Zsh version

5.8.1

### Terminal emulator

iTerm2, xfce-terminal

**Comment by agkozak** [comment]
It looks to me as if [you're also using `changyuheng/fz`](https://github.com/bipin-lekhak/dotfiles/blob/4bc02ad1c0ba146642cf952931b687c299e0f819/zsh_plugins.txt) -- is that right?

Try adding

    FZ_HISTORY_CD_CMD=zshz

to your `.zshrc`.

**Comment by mcornella** [comment]
That's the issue, yes: the new plugin uses `zshz` instead of `_z`. See https://github.com/ohmyzsh/ohmyzsh/pull/11236#issuecomment-1284385881.

 Feel free to reopen if that does not fix it.

**Comment by bipin-lekhak** [comment]
That worked perfectly. Thank you so much. 
Cheers!!
