### ISSUE TITLE
Can't update: not a git repository.

### ISSUE THREAD

**Issue by racer1988** [ohmyzsh/ohmyzsh#11309]
### Describe the bug

```# Test if Oh My Zsh directory is a git repository
  if ! (builtin cd -q "$ZSH" && LANG= git rev-parse &>/dev/null); then
    echo >&2 "[oh-my-zsh] Can't update: not a git repository."
    return
  fi
```

This code triggers everytime I open a console

by having 

`source $ZSH/oh-my-zsh.sh`

in my 

`.zshrc`

### Steps to reproduce

Open a terminal after installing zsh

### Expected behavior

No output is triggered, and git is found

### Screenshots and recordings

-

### OS / Linux distribution

macOS

### Zsh version

5.8.1 

### Oh My Zsh version

master (50a526f) 

### Terminal emulator

iTerm 2 

### Additional context

Seems to be connected to not having Xcode installed

**Comment by racer1988** [comment]
Note:

running `omz update` fixed the issue..
seems to be due to Xcode Installation breaking command line tools.

**Comment by bowersjuan** [comment]
$xcode-select --install

Also resolves the issue. This happened to me after updating to the current Ventura 13.0 Mac OS update

**Comment by secfb** [comment]
https://www.rffuste.com/2022/11/07/fixed-oh-my-zsh-cant-update-not-a-git-repository/
