### ISSUE TITLE
OMZ have trouble with dolphin console

### ISSUE THREAD

**Issue by LenniPL** [ohmyzsh/ohmyzsh#11303]
### Describe the bug

When dolphin is on startup with console option, a zsh start without theme aliases. 
![Screenshot_20221029_083912](https://user-images.githubusercontent.com/111856179/198817951-65763e96-7a92-4dc3-9af3-4f74ecde0b1d.png)

It is very annoying. 

Theme: powerlevel10k
Aliases: alias ls="colorls"

It is all

### Steps to reproduce

We should check out a dependence between dolphin console and zsh. ( I dont know why this section is required...) 

### Expected behavior

It should be working normal. ( I dont know why this section is required...) 

### OS / Linux distribution

Arch linux

### Zsh version

5.9

### Oh My Zsh version

master (49691b5)

### Terminal emulator

xterm-256color

**Comment by carlosala** [comment]
I don't know how `dolfin` works, but it looks like it's running the shell without startup files, same as running `zsh -f`. Could you check if there are more options related to this console? It's not a `ohmyzsh` issue, that's sure.

**Comment by LenniPL** [comment]
> 

Many thanks for respond. Dolphin is based on Konsole emulator for KDE. I can change only default shell option, no more. Also, I found same reports about trouble with konsole dolphin (from 2020 year. ). Closed
