### ISSUE TITLE
Not working on centos 9

### ISSUE THREAD

**Issue by MyTestPerson** [ohmyzsh/ohmyzsh#11317]
### Describe the bug

Not working on centos 9

### Steps to reproduce

Installed on centos 7. Works.

### Expected behavior

style

### OS / Linux distribution

centos 9

### Zsh version

latest

### Oh My Zsh version

Installed on centos 7. Works.

### Terminal emulator

Installed on centos 7. Works.

### Additional context

Installed on centos 7. Works.

**Comment by carlosala** [comment]
Could you please give more details about what is not working?
