### ISSUE TITLE
ssh-agent plugin doesn't seem to respect zstyle arguments..

### ISSUE THREAD

**Issue by stevenroose** [ohmyzsh/ohmyzsh#11326]
### Describe the bug

I have this in my `~/.zshrc`

```
plugins=(git ssh-agent gitfast rust golang ipfs ripgrep)
zstyle :omz:plugins:ssh-agent lazy
```

But somehow it keeps asking for identity passwords when I open new windows.

### Steps to reproduce

Add above snippet to your config, probably only the `ssh-agent` plugin is relevant.

### Expected behavior

No ssh key prompts are shown.

### OS / Linux distribution

Guix

### Zsh version

5.8.1

### Terminal emulator

alacritty

**Comment by mcornella** [comment]
The full line to enable lazy mode is, see the extra `yes`. 
```
zstyle :omz:plugins:ssh-agent lazy yes
```


Note that you also need to configure SSH to `AddKeysToAgent`, as specified in https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/ssh-agent/README.md#lazy, or SSH keys won't be loaded when running `ssh`.

**Comment by stevenroose** [comment]
Yeah found out just now reading the plugin readme. Thanks.

**Comment by stevenroose** [comment]
> Note that you also need to configure SSH to AddKeysToAgent, as specified in https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/ssh-agent/README.md#lazy, or SSH keys won't be loaded when running ssh.

I use ssh-add explicitly to only add the keys I want to add.
