### ISSUE TITLE
Use native auto-completion feature provided by vendor on Terraform

### ISSUE THREAD

**Issue by mhalano** [ohmyzsh/ohmyzsh#11328]
### If the feature request is for a plugin or theme, specify it here.

terraform

### If the feature solves a problem you have, specify it here.

Terraform could be update with newer options and auto-complete delivered with ohmyzsh it would be old. It wouldn't be nice to miss the new options because the auto-complete is outdated.

### Describe the proposed feature.

My idea is to use this command to auto-complete automatically, if the binary is available on path (like using packaging to install): `complete -o nospace -C /usr/bin/terraform terraform`.
`kubectl` plugin has a similar feature when is used `kubectl completion zsh` to populate the auto-completion with the most recent options available.

### Describe alternatives you've considered

I'm using the command inside the `~/.zshrc` file directly, but it could be placed inside ohmyzsh so the feature could be use with minimum effort.

**Comment by carlosala** [comment]
Hi Marcos! Checking `terraform` binary docs, it looks like they don't bundle a completion script, so we need to add that manually. Even though, we could use the `complete` stuff from bash! Could you work on that and open a PR?
Thanks!

**Comment by carlosala** [comment]
Hi Marcos! Checking `terraform` binary docs, it looks like they don't bundle a completion script, so we need to add that manually. Even though, we could use the `complete` stuff from bash! Could you work on that and open a PR?
Thanks!

**Comment by mhalano** [comment]
@carlosala I just did a PR to fix that. I hope it's in a good shape. I came to the same code, because that's not a complex piece of code, as PR #6709.
