### ISSUE TITLE
Alias conflict in plugins (`ubuntu` and `aliases`)

### ISSUE THREAD

**Issue by Haltarys** [ohmyzsh/ohmyzsh#11331]
### Describe the bug

The `ubuntu` plugin defines an alias `acs`. See <https://github.com/ohmyzsh/ohmyzsh/blob/23de5d95285a6b119d7c99f777051d9c5ec69ef8/plugins/ubuntu/ubuntu.plugin.zsh#L3>.

The `aliases` plugin defines an `acs` shell function. See <https://github.com/ohmyzsh/ohmyzsh/blob/23de5d95285a6b119d7c99f777051d9c5ec69ef8/plugins/aliases/aliases.plugin.zsh#L7>.

The aliases overrides the function / prevents it from being defined (depending on which plugin is loaded first.)

### Steps to reproduce

1. Add `plugins+=(ubuntu aliases)` to your `.zshrc`.
2. Run `type acs` in your terminal to check the type of `acs` (always an alias)

### Expected behavior

I would like to use both plugins at once so I suggest the function from `aliases` be renamed to something else.

### OS / Linux distribution

Ubuntu 20.04.5 LTS

### Zsh version

5.8

### Oh My Zsh version

master (80fdbc9)

### Terminal emulator

Windows Terminal (1.15.2874.0)

### If using WSL on Windows, which version of WSL

WSL2

**Comment by carlosala** [comment]
I would say `acs` function should be priority as it's the most important thing in the aliases plugin. Could you open a PR fixing the alias? Probably `acse` would do the job.
It needs to be fixed in both `ubuntu` and `debian` plugins!
Thanks for the report!

**Comment by grimm26** [comment]
Wow. Do we have metrics on how many people use debian/ubuntu plugins vs aliases to gauge the impact? I guess we'll see if there is a reponse.

**Comment by carlosala** [comment]
@grimm26 nope, we don't have metrics. Even though `acs` is the key functionality of `aliases` plugin, and for `debian` and `ubuntu` is just one more. You can always redefine the alias!

**Comment by majick** [comment]
I have never heard of the `aliases` plugin nor do I particularly care what it is.  All I know is, one day, `acs` which I use all the time broke on a bunch of my machines while I was trying to work.  I see that the breaking change was in the changelog back there somewhere, along with the zillion other completely ignorable things that scroll past when omz updates.

It's debatable if breaking an interface to the OS is worth breaking an interface to whatever the other thing is.

**Comment by Haltarys** [comment]
@majick You can use `unalias acs` or `unset -f acs` (if it's a function) after `source $ZSH/oh-my-zsh.sh` to remove it.

**Comment by grimm26** [comment]
> I have never heard of the `aliases` plugin nor do I particularly care what it is. All I know is, one day, `acs` which I use all the time broke on a bunch of my machines while I was trying to work. I see that the breaking change was in the changelog back there somewhere, along with the zillion other completely ignorable things that scroll past when omz updates.
> 
> It's debatable if breaking an interface to the OS is worth breaking an interface to whatever the other thing is.

Yeah, I wanted this issue resolved by changing the aliases plugin. I have to say the solution favored the less important plugin for some reason.

**Comment by rwmitchell** [comment]
It is debatable if breaking an interface to a global tool is worth breaking an interface to whatever that other thing (ubuntu) is.

Oddly, I don't have acs defined at all, because I only load plugins I care about.  Do you load all the plugins?

**Comment by grimm26** [comment]
> It is debatable if breaking an interface to a global tool is worth breaking an interface to whatever that other thing (ubuntu) is.
> 
> Oddly, I don't have acs defined at all, because I only load plugins I care about. Do you load all the plugins?

Ubuntu is one of the most widely used Linux distributions. No, I don't load all the plugins. I do happen to use both aliases and ubuntu. The aliases plugin is less than 2 years old. The ubuntu plugin is 8 years old. The aliaases plugin broke the ubuntu plugin. Regardless of your knowledge of what ubuntu is, the aliases plugin should not have been allowed to be created with a conflicting alias.

**Comment by majick** [comment]
I ran into this issue, actually, because this thing broke the `debian` plugin.  That plugin is a handy user affordance to the operating system.  I still have no idea what the `aliases` plugin is, nor why it is considered "global", but I've been using the `debian` plugin since whenever I discovered omz to begin with.

`acs` likewise became defined for me, as of the breakage introduced as a result of the new plugin's collision.

The end user fix is fairly trivial other than needing to be applied on every debian-derived machine where omz is in use everywhere.  It'd make more sense to fix this upstream rather than in thousands or hundreds of thousands of rc files.

**Comment by tjnycum** [comment]
> I would say `acs` function should be priority as it's the most important thing in the aliases plugin.

> `acs` is the key functionality of `aliases` plugin, and for `debian` and `ubuntu` is just one more.

With respect, this seems like an odd primary consideration. It makes sense if the primary goal is balancing the feelings of two people, but we're not talking about the temporary feelings of two people. We're talking about something that affects whole groups of users, and will continue to do so indefinitely in some ways. The focus should be on maximizing overall utility for them, which requires weighing a lot of factors, almost all of which lean toward the `ubuntu` and `debian` plugins in this case.

I suggest that the first question that should've been asked in this situation is: how do `aliases`'s available alternatives compare to those of `debian` and `ubuntu`? `alist`, `aliases`, or `alcs` would be just as (or _more_) naturally evocative of `aliases`'s behavior (listing defined aliases) than `acs` is. Meanwhile, `acs` follows a clear pattern within the `debian` and `ubuntu` plugins that users use to easily remember it, while there is no pattern to break within the `aliases` plugin precisely _because_ it's all that that plugin consists of.

> It needs to be fixed in both `ubuntu` and `debian` plugins!

While I think it's less important than the above question of alternatives, the fact that two much older, more established plugins have to be altered to accommodate one younger one also weighs against the action taken. With `debian` and `ubuntu` having used the `acs` alias four times as long, it's likely to be more ingrained in their users' minds.

> The aliases plugin broke the ubuntu plugin. Regardless of your knowledge of what ubuntu is, the aliases plugin should not have been allowed to be created with a conflicting alias.

I strongly agree given that it would've been of basically no detriment to `aliases` to use a different one from the start.

It's not too late to correct it. Countless debian and ubuntu users will appreciate not having to either remember which alias breaks the pattern with an 'e' stuck on the end or (potentially) manually merge every time those plugins get updated (which is likely to be much more often given how much more is in them and their nature, notice).

**Comment by majick** [comment]
> I suggest that the first question that should've been asked in this situation is: how do `aliases`'s available alternatives compare to those of `debian` and `ubuntu`?

I would go so far as to argue that the first question is "what is `aliases` and why did it just leave completely undefined existing decade-old functionality for installing packages on one of the largest OSes on the planet?"

Breaking changes happen, but breaking the underlying infrastructure of most of the deployed planet for... I don't even know what this thing is?  Poking at the plugin It looks like it lists aliases in prettyprint, for which a better mnemonic would have been `als` in the first place.  The plugin is called `aliases` ("als") and it lists things ("als").

It's not even clear what that plugin's mnemonic is supposed to mean.

Meanwhile basically every person with a shell prompt is going to want to search apt.

**Comment by majick** [comment]
Submitted #11799 against this.  Please do not bog me down in debate about it.  Debian is large.  Your python script is not.  If you need a debate, please have it among yourselves.

**Comment by rwmitchell** [comment]
"Meanwhile basically every person with a LINUX shell prompt is going to want to search apt."

fixed that for you.

This is really just a symptom of a larger issue and that is the user base for OMZ, supporting a wide variety of OSes and tools, has grown too big and ultimately clashes with individual workflows.  Once something has made it into OMZ, the maintainers are reluctant to make any change that could disrupt someone's previous usage, even if that change is good.

I'm only getting this discussion because of making a snarky comment earlier, but the truth is, I haven't found anything recently new in OMZ terribly useful.  As a result, I've forked my own clone  where I can fix things for my usage instead of trying to come up with work-arounds.

My recommendation is to do the same, sharing your local repo with friends/co-workers with the same usage goals.

Or you can continue trying to get your changes forced onto everyone else.  I don't care anymore.
