### ISSUE TITLE
Nvm plugin lazy load settings not working

### ISSUE THREAD

**Issue by ldorigo** [ohmyzsh/ohmyzsh#11344]
### Describe the bug

I have the following lines in my .zshrc:

```
zstyle ':omz:plugins:nvm' lazy yes
zstyle ':omz:plugins:nvm' lazy-cmd eslint prettier typescript
plugins=(git zsh_codex autojump colored-man-pages colorize command-not-found cp dirhistory extract fd npm pip sprunge sudo thefuck timer web-search conda-zsh-completion nvm) 
```

However, the `zstyle` options have no impact on whether nvm is lazy-loaded or not. I profiled with and without them, and nvm is loaded in either case.

### Steps to reproduce

- Enable plugin nvm
- Profile zsh startup (e.g. https://stevenvanbael.com/profiling-zsh-startup)
- Notice how the startup time is identical with or without the zstyle options to lazy-load. 

### Expected behavior

Nvm should not be loaded (and thus not take startup time) when the settings are set.

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Terminal emulator

Konsole

**Comment by carlosala** [comment]
I cannot reproduce, for me it's not doing that.
Could it be because some other plugin is using node/npm/nvm/yarn for some other purpose during startup (for example npm plugin for the completion).
Are you able to see that in the profile startup?

**Comment by carlosala** [comment]
@ldorigo friendly ping :)
Did you tried only with nvm plugin?

**Comment by arboehme** [comment]
Hi @carlosala, have the same problem. Use only `nvm` and `themes` plugins

**Comment by arboehme** [comment]
Here is the snippet from `.zshrc`:

```
# used by nvm plugin (see https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/nvm)
NVM_HOMEBREW=$(brew --prefix nvm)
zstyle ':omz:plugins:nvm' lazy yes

plugins=(
  nvm
  themes
)

source $ZSH/oh-my-zsh.sh
```

**Comment by arboehme** [comment]
Solved the problem by updating the Oh My Zsh manually by running `omz update` (for whatever reason the omz didn't ask me for the update for the long time...). 

Previously I had the old version of the nvm plugin, which relied on the environment variables instead of `zstyle`

**Comment by carlosala** [comment]
Let's close then, I'm glad the new refactoring of the plugin is working well! 😊

**Comment by carlosala** [comment]
@ldorigo feel free to reopen if you have more relevant information!
Thanks for the report!

**Comment by learn2reid** [comment]
I'm getting this issue again 
`nvm:unfunction:1: no such hash table element: yarn`
`zstyle ':omz:plugins:nvm' lazy yes
zstyle ':omz:plugins:nvm' lazy-cmd npmlist npl squoosh-cli sq prettier typescript yarn`

**Comment by carlosala** [comment]
@learn2reid solved, thanks for the report! The problem was that `yarn` was already on the default `lazy-cmd`, and there was a duplicate issue.
