### ISSUE TITLE
[Plugin] The last-working-directory cant find directories

### ISSUE THREAD

**Issue by olivertzeng** [ohmyzsh/ohmyzsh#11343]
### Describe the bug

❯ cd dotfiles/
❯ cd
❯ lwd
lwd:cd:3: no such file or directory: \n/Users/mark

### Steps to reproduce

1. Enable Plugin
2. Run `cd somedir`
3. Run `cd`
4. Run `lwd`

### Expected behavior

after lwd should go into the last working directory

### OS / Linux distribution

macOS 10.15.7 Catalina

### Zsh version

5.8

### Terminal emulator

iTerm 2

**Comment by mcornella** [comment]
The `last-working-dir` plugin uses `pwd` to track the current working directory, is it possible that you have it aliased to something?

Run `which -a pwd` to know. Also, it's only useful when starting a new shell, as it will change to the last directory you were in the last session. 

If you run `lwd` in the middle of a shell session it will just send you to the current directory.

**Comment by rwmitchell** [comment]
In your use case above, what is the advantage of using lwd vs having ```setopt autopushd``` set and just typing ```1``` to go back to the previous directory ?

**Comment by olivertzeng** [comment]
> 

yes its not aliased
