### ISSUE TITLE
zrecompile race condition when opening several terminals at once

### ISSUE THREAD

**Issue by whxvd** [ohmyzsh/ohmyzsh#11341]
### Describe the bug

I use the i3 window manager.  I have autologin configured and automatically start six terminals (alacritty) with zsh on the start of i3.  In several of those terminals I often get

``` zrecompile:zcompile:99: invalid zwc file: /home/w/.zcompdump-huette-5.9.zwc ```

I suspect that it is some kind of race condition when multiple processes try to update the zwc file at once.

### Steps to reproduce

It can be reproduced more or less reliably with (something like) the following:

``` touch ~/.zcompdump-${HOST}-5.9; alacritty&; alacritty&; alacritty& ```

When I run the previous command with my usual configuration the error appears almost every time in at least one of the terminals spawned.  However, when I create a new user on my machine with a minimal configuration, then it happens far less often.  But it does happen.

It may be harder to reproduce on more recent hardware.  I am working on an about 10 years old system with an "Intel(R) Celeron(R) CPU N3150 @ 1.60GHz".

### Expected behavior

No error message. Maybe some kind of locking.

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Terminal emulator

alacritty

**Comment by carlosala** [comment]
Yeah, that might be an issue. It should only happen when zsh needs to recompile it, but it's for sure something that we can check. Maybe adding a lockfile would be enough. I'll check it, try to reproduce, and submit a fix.
Thanks for the report!

**Comment by carlosala** [comment]
@whxvd Hi! I submitted a fix for your report! Could you try that using `omz pr test 11345` and tell me in the comments of the PR if it fixes that for you?
Thanks for your report!
