### ISSUE TITLE
wrong completion for 'git rerere forget'

### ISSUE THREAD

**Issue by ronso0** [ohmyzsh/ohmyzsh#11358]
### Describe the bug

`git rerere forg<Tab>` completes to `git rerere forget=`

### Steps to reproduce

1. type `git rerere forg<Tab>` > completes to `git rerere forget=`
2. add path <Return> fails and prints rerere usage hint `usage: git rerere [clear | forget <path>... | ...`

### Expected behavior

`git rerere forg<Tab>` completes to `git rerere forget `

### OS / Linux distribution

Ubuntu 20.04

### Zsh version

5.8

### Oh My Zsh version

master (5bce72ef)

### Terminal emulator

xfce4-terminal

**Comment by carlosala** [comment]
This is an issue in `zsh` itself, we don't define completion for git. You can see [here](https://github.com/zsh-users/zsh/blob/291940bae6cc0471c35c73498e873bc58dae9a95/Completion/Unix/Command/_git#L4265) that there's a todo about it. You can try to send an email to the zsh users mailing list (zsh.org/mla) to see if they can fix it.
Thanks for the report! 😉

**Comment by ronso0** [comment]
oh, sorry then. thanks for the link.
