### ISSUE TITLE
kubectl: Annoying shell startup message when minikube isn't started

### ISSUE THREAD

**Issue by xandris** [ohmyzsh/ohmyzsh#11364]
### Describe the bug

This line prints at shell startup:

```
I1201 15:23:28.759712   14542 versioner.go:58] Get "https://127.0.0.1:6443/version?timeout=5s": dial tcp 127.0.0.1:6443: connect: connection refused
```

This is from running `kubectl completion zsh`.

### Steps to reproduce

1. Enable plugin `kubectl`
2. Have `kubectl` command available
3. Ensure kubernetes API is unavailable (e.g. stop minikube, Rancher Desktop, etc.)
4. Start zsh

### Expected behavior

Prompt appears.

### OS / Linux distribution

macOS 12.6.1

### Zsh version

5.8.1

### Oh My Zsh version

fc44c49

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

### Additional context

Using Rancher Desktop

**Comment by xandris** [comment]
The completion script produced by kubectl appears to be the same with or without a master node available, so if you feel like this is worth changing, you could redirect stderr.

**Comment by carlosala** [comment]
I'm not able to reproduce. I just installed the CLI and didn't have any kubernetes API available.
Maybe there's another execution of something related to kubernetes? Just disabling the plugin solves the issue for you?

**Comment by xandris** [comment]
Yes, just running `kubectl completion zsh > /dev/null` prints the message. Maybe this is a bug in Rancher Desktop.

**Comment by carlosala** [comment]
What about running `kubectl completion zsh 2> /dev/null`?

**Comment by xandris** [comment]
Yes, removing the plugin makes the error message disappear. And yes, redirecting stderr with `2>/dev/null` does hide the error message. It would hide other errors too but I don't know how important that is.

**Comment by carlosala** [comment]
@xandris could you try PR #11373? You can do it with `omz pr test 11373`, and then opening a new terminal.

**Comment by carlosala** [comment]
check if completion works after that change

**Comment by xandris** [comment]
@carlosala yes, completion still works with that change. It doesn't hide the error message, which makes sense given the changeset so far

**Comment by carlosala** [comment]
Thanks for your report! 😊

**Comment by robbyrussell** [comment]
@xandris another big thanks for reporting this and helping test things out
