### ISSUE TITLE
The prompt line disappears

### ISSUE THREAD

**Issue by bluestyle97** [ohmyzsh/ohmyzsh#11360]
### Describe the bug

For unknown reasons, the theme setting is invalid and the prompt line disappears, only showing the conda environment "(base)".

### Steps to reproduce

1. Open a new shell window
2. Find that there is no prompt but only "(base)" of the conda environment.

### Expected behavior

The prompt line should be shown as in the theme preview:
![image](https://user-images.githubusercontent.com/20635237/204464815-9433138e-b66d-4b05-802d-675e15f72923.png)

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/20635237/204465621-942f2ba3-ccc7-476f-8f2c-acd63e9bd328.png)

### OS / Linux distribution

CentOS 7

### Zsh version

5.0.2

### Terminal emulator

iTerm 2

**Comment by carlosala** [comment]
Could you please provide more information? In which `oh-my-zsh` version are you (`omz version`)? Which theme is these one?
Let's try to find the issue!

**Comment by bluestyle97** [comment]
Hi, the `oh-my-zsh` version is `master (4c82a2e)`, and I used the theme `ys`. And no matter which theme I set to, it has no influence and the prompt line does not appear.

**Comment by AntouanK** [comment]
Same issue here. Conda just overrides the whole prompt.

**Comment by carlosala** [comment]
Then it's `conda` issue. Let's close this as it's not our issue and probably the best would be to open an issue in https://github.com/conda/conda.
Thanks for the report!

**Comment by bluestyle97** [comment]
@AntouanK I have fixed this issue by running the command `conda config --set changeps1 False` according to [this link](https://unix.stackexchange.com/questions/656045/how-to-modify-the-anaconda-environment-prompt-in-zsh). I hope this would be helpful for those who meet the same problem. I will close this issue myself.
