### ISSUE TITLE
Plugin: zsh-script-prefix

### ISSUE THREAD

**Issue by tmiland** [ohmyzsh/ohmyzsh#11369]
Hello,

just wanted to share a custom plugin which prefixes a local script file name. 

Say you have typed a script name and forgot to add `./` in front:

```bash
$ somescript.sh
```

By pressing the <kbd>esc</kbd> key once, you will have the same command with `./` prefixed without typing:

```bash
$ ./somescript.sh
```

It's a stripped down version of [plugins/sudo](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/sudo)

You'll find the plugin here: [tmiland/zsh-script-prefix](https://github.com/tmiland/zsh-script-prefix)

Hope someone will find it useful. 🙏‍

_Please disregard if posted in the wrong place._

**Comment by carlosala** [comment]
It looks nice! Even though, closing this to prevent us to confuse this with an issue with the repo 😊 
Thanks for the contribution to the zsh community!
