### ISSUE TITLE
gb show branches in current terminal

### ISSUE THREAD

**Issue by aziyatali** [ohmyzsh/ohmyzsh#11377]
### If the feature request is for a plugin or theme, specify it here.

git branch alias gb

### If the feature solves a problem you have, specify it here.

Currently, gb open list of the new branches on new-terminal rather than showing list of the branches in current terminal. It feels pretty uncomfortable even tho abridging plugins were great feature. It is comfortable when you want to checkout to the branch while seeing the list of them. Of course we could copy the branch and gb to the copied branch however, exiting the terminal feel uneasy. 

### Describe the proposed feature.

Remain the gb in oh-my-zsh as it was in the zsh. Just showing the list of the branches in the current tab instead of opening new tab and exiting back. 

### Describe alternatives you've considered

Just copying the branch name while I am in the gb tab and pasting it later.

**Comment by carlosala** [comment]
I can't reproduce, in [`git` plugin `gb` is aliased to `git branch`](https://github.com/ohmyzsh/ohmyzsh/blob/b692ff2e1597816563cbdaeeedf0966ad9babeca/plugins/git/git.plugin.zsh#L71) and I get the list of branches as stdout in the same terminal.
Feel free to reopen if you have more information related!

**Comment by rwmitchell** [comment]
You’re using GIT_PAGER and have modified the settings

**Comment by aziyatali** [comment]
@rwmitchell  Can  you tell more specifically what do you mean?

**Comment by rwmitchell** [comment]
I'll google it for you:

https://stackoverflow.com/questions/2183900/how-do-i-prevent-git-diff-from-using-a-pager

**Comment by aziyatali** [comment]
@rwmitchell  Thank you a lot, it solved my issue. 
Just had to export `export LESS='-RFX'` to .zshrc

**Comment by mcornella** [comment]
See also https://stackoverflow.com/a/48370253.

**Comment by aziyatali** [comment]
@mcornella  Gotcha. Thank you!
