### ISSUE TITLE
Latency in cursor when moving to new line

### ISSUE THREAD

**Issue by Tsimopak** [ohmyzsh/ohmyzsh#11384]
### Describe the bug

I experience some latency in cursor in iTerm2 when moving to new line? Adding a recording screen that demonstrate it.
BTW it doesn't happen in native Terminal in mac, but it does in iTerm2 and Hype.

Note: I'm not sure this a zsh problem but it's definitely more aggressive using zsh as you could see in the recording screen.

### Steps to reproduce

Just use a lot of empty lines

### Expected behavior

I wouldn't expect the cursor to escape for several milli seconds to wrong location before correct itself

### Screenshots and recordings

![Screen Recording 2022-12-11 at 21 54 30](https://user-images.githubusercontent.com/70956665/206926863-fae033c4-2f3e-4008-926a-ad8aa0268eec.gif)

### OS / Linux distribution

macOS Ventura 13.0.1

### Zsh version

5.8.1

### Terminal emulator

I tried iTerm and Hyper

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
This is expected for certain themes that load lots of stuff before rendering (as I can see in your prompt). You can try `zsh -f` to see which is the maximum speed you'll be able to achieve.
Thanks for the report!

**Comment by Tsimopak** [comment]
@carlosala Thanks for your answer! using `zsh -f` or `bash --norc` does solve the problem!
Is there a way to improve the speed? I mean, even if I use the default ohmyzsh theme it happens.

**Comment by carlosala** [comment]
I can't tell you one method actually, omz should be fast out of the box, probably it's due to your computer spec. Just keep trying combinations of themes and plugins, and also cleaning your zshrc from unneeded stuff!
