### ISSUE TITLE
Support for docker compose v2 completion

### ISSUE THREAD

**Issue by smallify-click** [ohmyzsh/ohmyzsh#11386]
### Describe the bug

When you try to auto complete file path for command `docker compose -f ` nothing happens on the other hand the outdated docker compose v1 still has support for file completion that is file path can be auto completed for commad `docker-compose -f`

### Steps to reproduce

1. Enable docker plugin
2.  Try auto completing file path for command `docker compose -f`
3.  Try auto completing file path for command `docker-compose -f`

### Expected behavior

Command `docker compose -f <tab>` should result in auto completion file name or file path based on current directory as ti happens in for the command `docker-compose -f <tab>`

### OS / Linux distribution

Ubuntu 22.04

### Zsh version

5.8.1

### Terminal emulator

Mobaxterm, putty

### If using WSL on Windows, which version of WSL

None

**Comment by smallify-click** [comment]
Only work around I have found so far is to add a setting to enable bash file completion when zsh completions fails. it does have a lot of drawback but if someone know a better option please do let me know.

This is what I used if you are wondering

`zstyle ':completion:*' completer _complete _ignored _files`

**Comment by carlosala** [comment]
I have not seen any zsh completion for compose plugin. It looks like it's not there yet.

**Comment by carlosala** [comment]
Closing in favour of #10912
