### ISSUE TITLE
Please delete docker-compose from alias

### ISSUE THREAD

**Issue by hhlp** [ohmyzsh/ohmyzsh#11383]
### If the feature request is for a plugin or theme, specify it here.

docker

### If the feature solves a problem you have, specify it here.

actually docker-compose is not needed anymore because are include in docker via plug-in in more recient docker version.

``` 
docker -version
compose*    Docker Compose (Docker Inc., v2.12.0)
``` 

you can manage all tag's via

```
docker compose [command]
```

### Describe the proposed feature.

unable plug-in decrapeted

```
docker-compose=/usr/local/bin/docker-compose
```

### Describe alternatives you've considered

make better alias for docker compose via this plug-ins

**Comment by mcornella** [comment]
Hi Hector, the `docker` plugin does not define any `docker-compose` aliases, and the `docker-compose` plugin also supports using `docker compose`: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/docker-compose/docker-compose.plugin.zsh.

If you have a `docker-compose` alias you should find whether you have it enabled in your .zshrc file or similar place.

**Comment by hhlp** [comment]
ohh tnkx yo good to know
