### ISSUE TITLE
plugins/git: Safer `git push --force`

### ISSUE THREAD

**Issue by larvanitis** [ohmyzsh/ohmyzsh#11388]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### If the feature solves a problem you have, specify it here.

The `git push --force-with-lease` command can become safer by adding the new (May 2022) `--force-if-includes` flag.

### Describe the proposed feature.

Change `alias gpf='git push --force-with-lease'` to `alias gpf='git push --force-with-lease --force-if-includes'` in
https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git/git.plugin.zsh#L238

### Additional context

https://stackoverflow.com/questions/65837109/when-should-i-use-git-push-force-if-includes

**Comment by mcornella** [comment]
This improves the case when a separate system automatically fetches all commits in a repository (as VS Code does on the background for example).

We are already getting the `git --version` in the plugin and checking it for flags, see https://github.com/ohmyzsh/ohmyzsh/blob/0e5f27481d9c4400b0d069ed884238e1d08e215c/plugins/git/git.plugin.zsh#L140-L142

It shouldn't be that difficult to do the same for git 2.30 and the `gpf` alias! Good first PR if you come across this one!

**Comment by akorkos** [comment]
Hello, could I work on this issue?

**Comment by mcornella** [comment]
Sure, go ahead!

**Comment by UnnitMetaliya** [comment]
@mcornella 

I created a PR for this. Please review: https://github.com/ohmyzsh/ohmyzsh/pull/11481
