### ISSUE TITLE
Wrong download link at Homepage

### ISSUE THREAD

**Issue by PhilippGsell** [ohmyzsh/ohmyzsh#11394]
### Describe the bug

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" (Thats the Link on your Homepage) directs to a 404 Page.

Link needs to be changed to: 
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
to work correctly.

Same thing with the wget link

### Steps to reproduce

1. go to https://ohmyz.sh/#install
2. paste link into terminal
3. Response =>  curl: (22) The requested URL returned error: 503

### Expected behavior

The download link should not throw  a 503 ;)

### OS / Linux distribution

macOS 12.6

### Zsh version

5.8.1

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

### Additional context

Link Text should be: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" for curl and the same path should be applied for wget.

**Comment by mcornella** [comment]
It's fixed now, thanks for the report!

**Comment by yapcona** [comment]
hey,
I get a 404 with the updated link. 

![Image](https://github.com/user-attachments/assets/d77bce02-afc5-4776-b12b-2f488f154bd9)

**Comment by carlosala** [comment]
You can try to `i.ohmyz.sh` instead

**Comment by yapcona** [comment]
Same error. I just used the wget command. Worked perfectly fine.

**Comment by roeniss** [comment]
Is this GitHub issue? The link works fine now 😆
