### ISSUE TITLE
Have to resource ~/.zshrc to get docker completions working using docker plugin

### ISSUE THREAD

**Issue by sdondley** [ohmyzsh/ohmyzsh#11404]
### Describe the bug

Tab completions for the docker command do not work when a new shell is opened. I have to run `source ~/.zshrc` before they start working. Other plugins with tab completion work on a new shell.

### Steps to reproduce

1) use Docker plugin
1a) open fresh shell
2) type `docker `
3) type in `a`
4) hit <tab> key
5) does not complete on `attach` subcommand
6) run `source ~/.zshrc` 
7) Repeat steps 2 - 4, notice it now completes for `attach` command

### Expected behavior

A manual source of ~/.zshrc should not be required to get docker completions workng. 

### OS / Linux distribution

mac os 13.1

### Zsh version

5.8.1

### Terminal emulator

iterm2

### If using WSL on Windows, which version of WSL

None

**Comment by sdondley** [comment]
OK, this may have been due to my own ignorant hacks to some custom zsh code that I cargo culted. Dropping in an `fpath+=($ZSH/plugins/docker)` fixed the issue for me. I'll leave this issue open in case someone can confirm this occurs on a clean install.

**Comment by carlosala** [comment]
That should not be needed. Are you defining plugins array before loading oh my zsh?

**Comment by sdondley** [comment]
Yes.

**Comment by sdondley** [comment]
As mentioned, tab completions for other plugins worked fine and were loaded in same place as docker plugin. This is why I suspect it could be a docker plugin issue.

**Comment by sdondley** [comment]
I set up a minimal docker image with omz to test see if this is a bug. It worked fine. So it must be my custom config that is the problem. Closing.
