### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Hugo-Pereira-98** [ohmyzsh/ohmyzsh#11406]
### Describe the bug

My Mac suddenly stop working oh my zsh, I use Iterm with oh my zsh for a couple months now, but when I open my terminal the following error appears: "/Users/hugopereira/.zshrc:source:78: no such file or directory: /Users/hugopereira/.oh-my-zsh/oh-my-zsh.sh"

But looks like the file is there and when I've tried to reinstall it, it said that I already had the folder

hugopereira@hugo ~ % sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

The $ZSH folder already exists (/Users/hugopereira/.oh-my-zsh)

You ran the installer with the $ZSH setting or the $ZSH variable is
exported. You have 3 options:

1. Unset the ZSH variable when calling the installer:
   `ZSH= sh install.sh`
2. Install Oh My Zsh to a directory that doesn't exist yet:
   `ZSH=path/to/new/ohmyzsh/folder sh install.sh`
3. (Caution) If the folder doesn't contain important information,
   you can just remove it with `rm -r /Users/hugopereira/.oh-my-zsh`

And I can't use any of these suggestions

### Steps to reproduce

There is no steps, I've just opened the terminal

### Expected behavior

It should find my oh-my-zsh file 

### OS / Linux distribution

macOs Ventura 13.1

### Zsh version

5.8.1

### Oh My Zsh version

Command not found

### Terminal emulator

Iterm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Hi @Hugo-Pereira-98!
Could you do `cd $ZSH; git status`?
Thanks!

**Comment by Hugo-Pereira-98** [comment]
hugopereira@hugo ~ % cd $ZSH; git status
fatal: not a git repository (or any of the parent directories): .git

**Comment by rwmitchell** [comment]
while still in that same directory, what does:
```
pwd
ls -al
```
show ?

**Comment by Hugo-Pereira-98** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/82890773/209445235-70176ac4-04a5-44f2-94df-5556f80c87e7.png">

**Comment by Hugo-Pereira-98** [comment]
And I can't uninstall it

<img width="417" alt="image" src="https://user-images.githubusercontent.com/82890773/209445314-60cca8a7-f0b0-4e54-9e7c-a2d3a994054b.png">

**Comment by mcornella** [comment]
The repository is gone, you have to delete the folder manually and reinstall.

**Comment by Hugo-Pereira-98** [comment]
It worked brother, thank you. I thought that it could work doing this, but I was wondering why suddenly the repository disappeared. 

But that's ok now, thank you again.

Closing the issue

**Comment by samimcguire** [comment]
I'm sorry! But I'm having the same issue.  How do I delete the folder manually? I can't seem to find any folder at all.

**Comment by guillaumelhostis** [comment]
its in the hidden folders
