### ISSUE TITLE
add looking for configuration in .config/zsh directory by default

### ISSUE THREAD

**Issue by mohammadne** [ohmyzsh/ohmyzsh#11409]
### Describe the proposed feature.

I prefer to follow new linux convention of putting config files into .config directory but currently in zsh we have to create `.zshenv` in home directory and set `ZDOTDIR` variable to point to that location which is a mess and I want it to look for `.config/zsh/zshrc` by default if `.zshrc` is missing in `$HOME`.

I prefer like must of the plugins, if `$HOME` is missed, then it checks `.config/zsh` automatically without defining `$ZDOTDIR`, because I like to put all configs include my `.zshenv` which includes other logics all in `.config/zsh` directory.

thanks

**Comment by mohammadne** [comment]
this is also correct for `omz` to keep it in data directory `.local/share` directory by default. (cuurenly it's possible to do that with an export statement)

**Comment by carlosala** [comment]
Hi! Thanks for your idea! Even though, the first part is not related to oh my zsh, it's zsh itself. For the second part, it's recommended to just add an env variable in `.zshenv`, as it's not a huge change (just one/two lines of shell script) to choose where you want your config to be.
I also agree with your point, but we always try to make everything backwards compatible, and changing that default would be a huge change.
Thanks for your contribution!
