### ISSUE TITLE
Oh My Zsh is beeing deleted every time my Mac reboots

### ISSUE THREAD

**Issue by Hugo-Pereira-98** [ohmyzsh/ohmyzsh#11414]
### Describe the bug

Every time I shut down my Mac, when I start it again Oh My Zsh file get's deleted and it doesn't work.

### Steps to reproduce

1 - Turn my Mac off
2- Turn it back on

### Expected behavior

It should work with no problem

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/82890773/209845556-5d43eae5-c557-40b8-94a6-860969c38e1c.png)

### OS / Linux distribution

macOS Ventura 13.1

### Zsh version

5.8.1

### Oh My Zsh version

master (9c2d1af)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by Hugo-Pereira-98** [comment]
Just a quick comment, if I update Oh My Zsh it works. But every time I turn off my Mac it stops working again.

Not sure if this is the expected behavior, but I think this should be changed.

**Comment by rwmitchell** [comment]
Is the OMZ subdirectory actually getting deleted or it just stops working?

**Comment by mcornella** [comment]
In the screenshot you attached you CTRL-C the terminal. Does it load if you don't do that, or it does but it takes a long time?

Also does it load if you close the terminal window and open it back up?

**Comment by Hugo-Pereira-98** [comment]
Last time it did erased everything inside the directory, now I hadn't time to see it because when I updated it, it worked.


It doesn't load if I close and open the terminal. Only if I update or remove and reinstall

**Comment by rwmitchell** [comment]
What you are experiencing isn't normal, so you'll need to debug your setup.

You can open multiple iTerm2 windows - once it works, do all new windows work until you close them all?
Does closing a single window (with others still open) then break future new windows?

After it stops working, can you
```
echo $ZSH
cd $ZSH
git status
```

**Comment by rwmitchell** [comment]
We’re you able to solve it?  What was the issue?
