### ISSUE TITLE
Pressing TAB does not trigger autocomplete for the 2nd argument of diff

### ISSUE THREAD

**Issue by paritystsai8** [ohmyzsh/ohmyzsh#11416]
zsh 5.8.1 (x86_64-apple-darwin22.0)
master (4c82a2e)

Platform: iTerm2 on macOS Ventura Version 13.1

As title, pressing TAB for the 1st argument of diff triggers autocomplete, but not for the 2nd argument. vimdiff works just fine.

A workaround is to move the cursor back between diff and the 1st argument to trigger autocomplete by pressing TAB

**Comment by paritystsai8** [comment]
Another workaround is to declare a new function diff2 in .zshrc:

function diff2() { diff $1 $2 }

Then TAB triggers autocomplete for both arguments.

**Comment by carlosala** [comment]
I can't reproduce on Linux, and checking the [`_diff_options`](https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Type/_diff_options) file, it looks like didn't changed for a while, so being in 5.8.1 should not be a problem. Which variant of `diff` are you using? Post the output of `diff --version` to see what's going on?
Thanks!

**Comment by paritystsai8** [comment]
Here it is:
$diff --version
Apple diff (based on FreeBSD diff)

**Comment by raybaxter** [comment]
I'm having the same issue. It appears that `diff` is aliased to `diff --color`

```
which diff
diff: aliased to diff --color
```

If I `unalias diff` autocompletion works correctly. 

I'm not aliasing `diff`. It appears to come from here: https://github.com/ohmyzsh/ohmyzsh/blame/a3c579bf27b34942d4c6ad64e7cfd75788b05ea3/lib/theme-and-appearance.zsh#L44

**Comment by paritystsai8** [comment]
Awesome! Sounds like it's resolved!

**Comment by mcornella** [comment]
Let's keep it open until we figure out a way to fix the alias for this version of diff.

**Comment by carlosala** [comment]
@mcornella maybe we could switch to a function instead of an alias, and add `compdef _diff diff`. That should be enough I would say.

**Comment by raybaxter** [comment]
For an immediate fix I added this in my `~/.zshrc`

```
# Fix https://github.com/ohmyzsh/ohmyzsh/issues/11416
unalias diff
diff_path=`which diff`
function diff() {
  $diff_path --color $*
}
```

**Comment by rwmitchell** [comment]
I'm not seeing the problem.
No args:

<img width="179" alt="image" src="https://user-images.githubusercontent.com/15944841/210106308-278114a9-e40c-4aa4-8476-2fa141b734e0.png">

hyphen arg:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/15944841/210106445-48c03987-e57b-4f49-a3bf-5ae59bdf4ba3.png">

one arg + TAB:
<img width="164" alt="image" src="https://user-images.githubusercontent.com/15944841/210106505-bdcb7b23-c1d2-407b-a55e-4d06c67cee61.png">

one arg + hyper-TAB
<img width="526" alt="image" src="https://user-images.githubusercontent.com/15944841/210106610-1ba088c7-280e-460e-84ef-8f491f8c0104.png">

diff is defined as:
diff is an alias for diff --color=always

and _diff as:
_diff is a shell function from [somepath]/local/share/zsh/5.9.0.1-dev/functions/_diff

```
_diff () {
	_diff_options "$words[1]" ':original file:_files' ':new file:_files'
}
```

So, why is your system borked ?  Certainly can't be because macOS is better.

**Comment by gsakkis** [comment]
For the record `diff` completion is half-broken for me even without an alias and without `ohmyzsh`. Only a very small subset of available options are shown after `diff -<TAB>`:

```shell

~ % zsh --version
zsh 5.8.1 (x86_64-apple-darwin22.0)

~ % diff --version
Apple diff (based on FreeBSD diff)

~ % type diff
diff is /usr/bin/diff

~ % diff - <TAB>
-b  -- skip trailing white spaces
-c  -- output a context diff
-e  -- output an ed script
-f  -- output a reversed ed script
-r  -- recursively compare subdirectories
```

**Comment by mcornella** [comment]
The current code should define a `diff` function which should be seen in the `type diff` output.

This is not the case, but even so the issue is different: the flags seen are directly returned by the completion function, which is provided by zsh itself.

**Comment by tspearconquest** [comment]
I'm seeing this issue even after having just run `omz update`. The file contents of `~/.oh-my-zsh/lib/theme-and-appearance.sh` do not seem to have changed on my system when compared to here.

```
❯ omz update
Updating Oh My Zsh
master

BREAKING CHANGES:

 - 652037e [jump]

   Previously, `jump` would resolve the symlink to the mark directory and resolve again if the mark
   directory was also a symlink. It only resolves once after this commit.

Features:

 - 486e56a [autojump]                 Add path for nix per-user (#11935)
 - cb7ff9f [git]                      Add `gcann!` alias (#12041)
 - 8be4789 [git]                      Add `greva` and `grevc` aliases (#12042)
 - d93401c [history-substring-search] Update to upstream (#12164)
 - c007497 [history-substring-search] Update to version 8dd05bfc (#12167)
 - d2ffe83 [history-substring-search] Use new dependencies updater
 - f7b647e [spectrum]                 Add `FX[dim]` format (#12172)
 - 8b2ce98 [ssh]                      Add plugin (#12186)
 - 15479ca [terraform]                Add new terraform and helm aliases (#11923)
 - d43f03b [virtualenvwrapper]        Run function on startup (#12163)
 - c6ce22f [vscode]                   Add `vscp` alias (#12092)
 - 35a5357 [web-search]               Add `deepL` (#12165)

Bug fixes:

 - 80c114c [awesomepanda]             New line wrap
 - e195c7c [aws]                      Pass default region to fetch regions (#12175)
 - 530cd7f [history-substring-search] Source properly plugin
 - 652037e [jump]                     Only resolve mark symlink (#11074)
 - 11b0ea3 [python]                   Add support for cli args (#12159)
 - e656377 [web-search]               Encode spaces as `%20`

You can see the changelog with `omz changelog`
         __                                     __
  ____  / /_     ____ ___  __  __   ____  _____/ /_
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
                        /____/

Hooray! Oh My Zsh has been updated!

To keep up with the latest news and updates, follow us on Twitter: @ohmyzsh
Want to get involved in the community? Join our Discord: Discord server
Get your Oh My Zsh swag at: Planet Argon Shop
```

I am using powerlevel10k theme. Would that have anything to do with this issue? When I do `type diff` I get: `diff is a shell function from /Users/tspear/.oh-my-zsh/lib/theme-and-appearance.zsh` so it doesn't seem to be p10k to me, but I'm not 100% certain on that. Suggestions welcome, as this has bugged me for 3 years on my old work system but now also affecting my new work system which I just received and did install omz and p10k onto just a few days ago.

**Comment by tspearconquest** [comment]
Looking further, it seems that @rwmitchell is correct, 657ad05 was (essentially) reverted by 95d0c4b under #11529

Please reopen this issue. I will be happy to submit a PR to re-implement #11456

**Comment by brettdw-tamu** [comment]
If it helps troubleshoot this issue, I'm having this exact same problem and I'm not using Oh My ZSH at all. I'm just using vanilla ZSH with iTerm2 on OSX 14.3 -- identical problem. All versions below:

ZSH version: zsh 5.9 (arm-apple-darwin21.3.0)
iTerm2 version: 3.4.23
OSX version: Sonoma 14.3

**Comment by IakimLynnyk-TomTom** [comment]
Well I've figured out that if once specifies the options after the files it works as expected:
`diff -Nauw {TAB} file1 {TAB}` doesn't work but
`diff {TAB} file1 {TAB} file2 -Nauw` works.

**Comment by axqd** [comment]
Still happening on Mac. Quickest fix would be switching to GNU version of diff:
```
$ brew install diffutils
```

**Comment by tspearconquest** [comment]
I always install the gnu utilities but didn't realize diff was in a
separate package. Thank you! Install, restart shell, run diff --version and
it works.

**Comment by nicolasdespres** [comment]
Same problem here, with vanilla zsh 5.9 and iterm2 3.5.10 on macOS 15.2. It failed to complete the second file when there is a flag set:

ok: diff file1 file2
not ok: diff -u file1 file2

Installing diffutils as a workaround did the trick.
