### ISSUE TITLE
Not able to install with curl and wget commands

### ISSUE THREAD

**Issue by ArtistBanda** [ohmyzsh/ohmyzsh#11412]
Not able to access the raw file of install.sh using this [link](https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh).
![error](https://user-images.githubusercontent.com/36930204/209807641-092e6479-ad65-43d8-836d-9f38aed9c705.png)

So not able to run either of theses commands
```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
```

**Comment by ArtistBanda** [comment]
For workaround copied the content of install.sh and created a local install.sh file and ran it
```
chmod +x install.sh
./install.sh
```

**Comment by mcornella** [comment]
Can't reproduce. Where are you accessing this from (location, browser, operating system and version)?

Does it happen with another computer? Do you have the local certificates up-to-date (in Linux, `ca-certificates` package)?

**Comment by rizan21** [comment]
### curl
```shell
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```
```shell
curl: (35) OpenSSL/3.0.7: error:0A0003E8:SSL routines::reason(1000)
```
### wget
```shell
$ sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
--2022-12-29 16:12:33--  https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
```
```shell
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 202.83.21.14
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|202.83.21.14|:443... connected.
GnuTLS: A TLS fatal alert has been received.
GnuTLS: received alert [0]: Close notify
Unable to establish SSL connection.
```
### fetch
```shell
$ sh -c "$(fetch -o - https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```
```shell
40176732E97F0000:error:0A0003E8:SSL routines:ssl3_read_bytes:reason(1000):ssl/record/rec_layer_s3.c:1600:SSL alert number 0
https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh: Permission denied
```

OS: Manjaro Linux x86_64 
Kernel: 6.1.1-1-MANJARO
Shell: zsh 5.9

I'm also having the same issue with installing oh-my-zsh.

**Comment by Aksh627** [comment]
I am also facing the same issue.

**Comment by ArtistBanda** [comment]
> Can't reproduce. Where are you accessing this from (location, browser, operating system and version)?
> 
> Does it happen with another computer? Do you have the local certificates up-to-date (in Linux, `ca-certificates` package)?

I am using
OS: Endevour OS (Arch based) i3wm version
Browser: Firefox (though getting error in terminal too)
```
curl: (35) OpenSSL/3.0.7: error:0A0003E8:SSL routines::reason(1000)
```

I'll have to try on another computer
Ran `update-ca-trust` and rebooted, still the issue is there

**Comment by srijan-nayak** [comment]
Facing the same issue as well from Bengaluru, India.

**Comment by sivavarma111** [comment]
Facing the same issue as well from Hyderabad, India.
OS: Ubuntu 20.04.5 LTS

**Comment by mcornella** [comment]
Can you post the output of `curl -v -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh`?

**Comment by srijan-nayak** [comment]
Just realized, I can •t access any raw.github.com content from any repository when I am connected to my usual ISP's Wi-Fi (ACT ltd.). Switching to another carrier through hotspot fixed the issue.

**Comment by crux-abhishek** [comment]
Same is happening with me in India. My ISP is not allowing me to connect to this URL. When I connected using a mobile hotspot, it worked.

**Comment by ArtistBanda** [comment]
Looks like an issue with the ISP (ACT Ind.) and makes no sense to keep this issue open here, so closing.

If someone gets in contact regarding this issue to the ISP then please update here, thanks.
