### ISSUE TITLE
Check if git is installed before relying on it for autoupdate

### ISSUE THREAD

**Issue by edbennett** [ohmyzsh/ohmyzsh#11420]
### If the feature solves a problem you have, specify it here.

macOS updates frequently break the command line developer tools, so `git` becomes unavailable. This means that when the update check tries to use `git rev-parse`, it gets a non-zero return code, which is incorrectly interpreted as `git` complaining that the directory isn't a git repository. 

The message `"[oh-my-zsh] Can't update: not a git repository."` is then unnecessarily confusing. This has caused me to trip over multiple times—wading through various issues of "why is the `.git` directory missing?" (it wasn't) before stumbling across the solution when I ran `git` and saw the message it gave.

### Describe the proposed feature.

Add a check before calling `git rev-parse` to see if the `git` command is available. Ideally this would also give concrete steps on how to fix the error in the most common case(s). Something along the lines

```
if ! (git --version &>/dev/null); then
    echo >&2 "[oh-my-zsh] Can't update: git is not installed."
    if [[ "$(uname)" == "Darwin" ]]; then
        echo >&2 '[oh-my-zsh] Try using "xcode-select --install" to reinstall the Command-Line Developer Tools'
    fi
    return
fi
```

### Describe alternatives you've considered

`git grep` shows a similar message is emitted by the Git plugin; it would be nice if this check could be done once globally, and the Git plugin disabled if `git` isn't installed.

### Related Issues

#11309 and #10861 have both encountered this.

**Comment by carlosala** [comment]
Thanks for the idea! We were checking if there was a binary named `git` before checking for upgrade. Now I made the check more strict actually asking for `git --version`. It's really weird, and probably previous check should be enough, but maybe macOS is letting the binary there but breaking it somehow.
Thanks! 😉

**Comment by edbennett** [comment]
Many thanks Carlo!

> We were checking if there was a binary named git before checking for upgrade

Ah, I didn't spot that in my (admittedly cursory) hunt.

> but maybe macOS is letting the binary there but breaking it somehow

Yes, macOS has some indirection in its developer tools, so there's always "something" there, but by default that something just prompts you to install the developer tools, and if your installation is broken (e.g. by a macOS upgrade) then instead it complains about that to you. The actual `git` binary sits somewhere deep in the Xcode installation.

**Comment by carlosala** [comment]
Nice, then it should be solved!
