### ISSUE TITLE
Broken behaviour in git-extras completions due to bad function call

### ISSUE THREAD

**Issue by digoot** [ohmyzsh/ohmyzsh#11430]
### Describe the bug

There was a crash in git-extras completions due to a bad function call

For remotes, tags, branches... completions, as we can see in the code, the completions are calling a non-existent function:

[https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git-extras/git-extras.plugin.zsh#L62](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git-extras/git-extras.plugin.zsh#L62)

### Steps to reproduce

1. Enable plugin git-extras
2. Edit `.zprofile` by adding a custom function
3. Edit `.zshrc` to add the `__git_branch_names` completion to the previous custom function
4. Reload `.zprofile` and `.zshrc`
5. Go to a git directory
6. Type the custom function and press tab key.

### Expected behavior

These completions should call the correct function:

[https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git-extras/git-extras.plugin.zsh#L31](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git-extras/git-extras.plugin.zsh#L31)

### Screenshots and recordings

```
$ gdbb __gitex_branch_names:4: command not found: __git_command_successful
__gitex_branch_names:4: command not found: __git_command_successful
__gitex_branch_names:4: command not found: __git_command_successful
```

### OS / Linux distribution

MacOS 12.6.1

### Zsh version

5.8.1

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
The error was introduced in `7f2656c1`, when renaming `__git_command_successful` to `__gitex_command_successful` (to avoid conflicts with `git-flow` plugin). Renaming the usage to `__gitex` should be enough. Thanks for the report.
