### ISSUE TITLE
Emacs plugin won't work for emacs >= 28

### ISSUE THREAD

**Issue by vlebedev** [ohmyzsh/ohmyzsh#11441]
### Describe the bug

Emacs plugin cannot start emacs properly due to more strict syntax checking for emacsclient options starting from emacs version 28 and onwards.

Fix would be quite simple, replace each occurence of `emacsclient --alternate-editor ""` with `emacsclient --alternate-editor=""` in /plugins/emacs/emacsclient.sh.

### Steps to reproduce

- Install latest emacs (28.1)
- Try to launch emacs with `emacs` or `e` or `te`

### Expected behavior

No emacs window will be open, neither in GUI not in terminal

### OS / Linux distribution

Ubintu 22.04

### Zsh version

5.8.1

### Oh My Zsh version

master (6622210)

### Terminal emulator

Gnome Terminal Version 3.44.0

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Thanks for the report!

**Comment by vlebedev** [comment]
You are welcome :)
