### ISSUE TITLE
Current time added on oh-my-zsh theme gnzh not updaing

### ISSUE THREAD

**Issue by AnuragGupta93** [ohmyzsh/ohmyzsh#11443]
I have added Current Time in `oh-my-zsh gnzh theme`.
<img width="653" alt="image" src="https://user-images.githubusercontent.com/35900375/212638757-60c31ca9-d4f4-4ae0-9d84-641468b4709a.png">

Its looking great on the terminal. However, the time in not updating on the prompt.
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/35900375/212638821-500648b1-c59d-484d-910a-ff635334f91d.png">

I want to insert the date only in this position as giving date at starting with `PROMPT` will destroy the allignment of the arrows.

**Comment by carlosala** [comment]
Use single quotes instead of double quotes when defining `curr_time`. Double quotes expand variables and subshell executions during declaration, and single quotes simply store text.
