### ISSUE TITLE
`geteip` command not working for IPv6

### ISSUE THREAD

**Issue by Haltarys** [ohmyzsh/ohmyzsh#11457]
### Describe the bug

The shell function `geteip` from the plugin [`systemadmin`](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/systemadmin) returns the external IP address of the machine.

```bash
$ which geteip
geteip () {
        curl -s -S -4 https://icanhazip.com
        curl -s -S -6 https://icanhazip.com
}

$ geteip
123.123.123.123
curl: (7) Couldn't connect to server
```

When called, it makes a cURL request to <https://icanhazip.com> to get the IP address, first using IPv4 (which succeeds), second using IPv6 (which fails.) It seems the server isn't configured to handle IPv6. Therefore, the IPv6 request fails with : `curl: (7) Couldn't connect to server`.

### Steps to reproduce

1. Enable plugin `systemadmin`.
2. Run `geteip`.

### Expected behavior

I would expect the `geteip` command not to fail. The command should not display an error message or fail with a non-zero status code.
Ideally, I think there should be two commands `geteipv4` and `geteipv6`, and a third command `geteip` for backwards compatibility which should intelligently default to one or the other.

### OS / Linux distribution

Ubuntu 20.04 / Windows 10 (WSL2)

### Zsh version

5.8

### Oh My Zsh version

master (61dd368)

### Terminal emulator

Windows Terminal (1.15.2874.0)

### If using WSL on Windows, which version of WSL

WSL2

### Additional context

curl version 7.68.0

**Comment by mcornella** [comment]
This is probably happening because you don't have a public IPv6 address. Try going to https://test-ipv6.com and see whether you have one.

In my case, this website reports I don't and I get the same error as you.

**Comment by Haltarys** [comment]
You're right, I don't have one either. But if I did, I'm guessing I'd get a message like
```bash
$ geteip
12.1.1.123
2001:db8:3333:4444:5555:6666:7777:8888
```

I'm not sure how useful that would be, compared to having two separate commands, each with their own concern. Should I make a PR?

**Comment by mcornella** [comment]
This was done this way so that you don't need to make two separate calls. If you need to use it in a script, you can use `| sed -n 1p` for the IPv4 address or `| sed -n 2p` for the IPv6 address.

But most of the time you'll just use it to view the IP, so it does not hurt to have both. I have submitted #11458 for having a better error experience:

```sh
% geteip                                            
77.98.1.354
error: no IPv6 route to host
```

**Comment by Haltarys** [comment]
Thanks !
