### ISSUE TITLE
install.sh creates ~/.zshrc file regardless of ZSH variable

### ISSUE THREAD

**Issue by librick** [ohmyzsh/ohmyzsh#11453]
### Describe the bug

According to the README, custom .zshrc file locations should be specifed by setting the `ZSH` environment variable.
But the `install.sh` script ignores the `ZSH` variable, creating a `~/.zshrc` file in the user's home directory when it shouldn't.
See: https://github.com/ohmyzsh/ohmyzsh/blob/65a1e4edbe678cdac37ad96ca4bc4f6d77e27adf/tools/install.sh#L342

### Steps to reproduce

1. Start with a clean Linux install with zsh shell and non-root user $USER
2. Delete the file `$HOME/.zshrc` if it exists
3. Create a dotfiles directory: `mkdir -p $HOME/dotfiles`
4. Set the ZSH environment variable: `export ZSH=$HOME/dotfiles/omz`
5. Run the ZSH install script according to the README: `sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`
6. Note that the install script has created the file `$HOME/.zshrc` even though ZSH is set to a different directory
7. Note also that the repo has been pulled down as expected to `$HOME/dotfiles/omw`, it's just that the .zshrc file is in the wrong place

### Expected behavior

The `install.sh` script should follow the ZSH environment variable as specified in the README instructions; it shouldn't put the `.zshrc` file at the root of the user's home directory when the user specifies a different directory.

### OS / Linux distribution

Debian Testing

### Zsh version

5.9

### Oh My Zsh version

master (7de5584)

### Terminal emulator

Kitty

### If using WSL on Windows, which version of WSL

None

## What I Tried
I want to follow the freedesktop/XDG specs and store oh-my-zsh's configuration files (including `.zshrc`) in a directory called `$USER/.config/zsh/oh-my-zsh`. According to the oh-my-zsh README, I can do this by setting a `ZSH` environment variable for the install script.

I set the ZSH environment variable:
`export ZSH=$HOME/.config/zsh/oh-my-zsh`

I make sure a parent directory exists. This is important as, because I'm using the ZSH environment variable, I don't expect this file to exist or ever be created at this location.
`mkdir -p ~/.config/zsh`

Then I make sure my custom directory does *not* exist (otherwise the *main()* function in *install.sh* complains, as expected):
`rm -rf ~/.config/zsh/oh-my-zsh`

I also make sure that no ~/.zshrc file(s) exist:
`rm ~/.zshrc*`

Then I run the script (using a file rather than inline w/ curl):
`sh install.sh`

**Doing an `ls -la` shows that a `~/.zshrc` file has been created in my home directory, not in the directory specified by the ZSH environment variable.**

## Other Checks
I went through and added `echo` statements throughout my copy of the install script. I'm pretty sure my HOME, ZSH, and all other relevant variables are set correctly.

**Comment by mcornella** [comment]
Hi Eric, thanks for the report. There is a PR to introduce this option in https://github.com/ohmyzsh/ohmyzsh/pull/10622 but it is pending adding this case for the uninstaller.
