### ISSUE TITLE
oh-my-zsh won't update - Unsupported SSL backend channel

### ISSUE THREAD

**Issue by tivolinick** [ohmyzsh/ohmyzsh#11455]
On Mac OS: 13.1 (22C65)
I see the following:

[oh-my-zsh] Would you like to update? [Y/n] Y
Updating Oh My Zsh
fatal: Unsupported SSL backend 'channel'. Supported SSL backends:
	secure-transport
	openssl
There was an error updating. Try again later?

**Comment by carlosala** [comment]
It's weird, maybe related to some breaking macos stuff.
Try `xcode-select --install` and reboot the computer to see if it solves the issue also.

**Comment by tivolinick** [comment]
xcode select is already installed. Reboot didn't help.

**Comment by carlosala** [comment]
Look in your `.gitconfig` if you have http.sslBackend defined and remove those. If not, please go to `cd $ZSH` and `git config --unset-all http.sslBackend`.
It should work after.

**Comment by tivolinick** [comment]
yes, http.sslBackend was defined in .gitconfig. It's working now. Thanks
