### ISSUE TITLE
Git Plugin: alias for `git rebase -i $(git merge-base HEAD $(git_main_branch))`

### ISSUE THREAD

**Issue by jdevries3133** [ohmyzsh/ohmyzsh#11465]
### If the feature request is for a plugin or theme, specify it here.

Git

### If the feature solves a problem you have, specify it here.

I often run this command:

```bash
git rebase -i $(git merge-base HEAD master)
```

The use case is for evaluating the commits I've made on dev branch before opening a pull request.

I'd like an alias! I think others might too!

### Describe the proposed feature.

In oh-my-zsh, we have the `$(git_main_branch)` util, so the equivalent line in the plugin file would be:

```bash
alias ??='git rebase -i $(git merge-base HEAD $(git_main_branch))'
```

I'm not sure what the best name would be; here are some suggestions:

- `grbmbm`: git rebase merge-base main/master
- `grbpr`: git rebase (before a) pull-request
- `grbmr`: gitlab flavor of the above
- `grbeek`: git rebase; "eek," my work needs to be fixed up
- `grbbb`: git rebase merge base

I think my personal favorite is `grbpr`, but I'll try it on in my personal config for a big and can report back.

### Describe alternatives you've considered

Do other people do this? I'm not sure. Maybe this isn't a commonly used git operation.

**Comment by carlosala** [comment]
In my case I wouldn't use this feature that much, but let's wait for other people opinions!

**Comment by rwmitchell** [comment]
I concur carlosala!

**Comment by dhanaway** [comment]
I use my own version of this all the time! Very helpful for working on large projects and organizing commit history when  adding small fixes to older commits. Wide spread at our company as well

**Comment by jdevries3133** [comment]
(with the notable caveat that Dalton and I admittedly do work together
and we were admiring `grbpr` and discussing this GitHub issue lol)

Anyway, ping on this and looking forward to hearing your thoughts and
maybe answering some questions about why we love this alias so much!

**Comment by carlosala** [comment]
Closing this. It's a really great alias though! IMO too niche to be merged probably, but could be used as a personal alias.
Thanks @jdevries3133 and @dhanaway for the comments!

**Comment by timmyarch** [comment]
^ upvoting this feature
