### ISSUE TITLE
A web config like fish_config?

### ISSUE THREAD

**Issue by nbelakovski** [ohmyzsh/ohmyzsh#11468]
### Describe the proposed feature.

The FISH shell has this convenient web-based configuration utility. If you install FISH and then type fish_config it will host a web server and bring up a web page where you can customize your prompt and some other things. 

You can select from different prompts and it's really nice to see on the webpage what the prompt will look like ahead of putting it in, and I also really appreciate that if I want to change my prompt, I only have to remember to bring up fish_config, as opposed to looking up config files.

This could also be a great way to manage plugins!

Any chance something like this might be implemented for zsh?

**Comment by carlosala** [comment]
That looks like it's a feature from the shell itself, not from a configuration framework. `zsh` don't feature this kind of stuff normally, so I'd say it'll never get to `zsh`. Even though, it'd be really great!
Actually, except for the browser feature, `omz` CLI bundles most of the things!
Thanks for the idea!
