### ISSUE TITLE
Host installer on install.ohmyz.sh

### ISSUE THREAD

**Issue by mcornella** [ohmyzsh/ohmyzsh#11467]
### If the feature solves a problem you have, specify it here.

We get a lot of reports of issues accessing the GitHub URL to install OMZ, either because of temporary access issues or even because of outright blocking by GFW (Great Firewall of China).

### Describe the proposed feature.

Self-host installer on a CDN controlled by us, with the following considerations:

1. Automatically deploy the latest `install.sh` script on push events.
2. Make sure the installer is cached by a CDN so that we don't pay the price of bandwidth, as well as to put it close to the user geographically. I think Cloudflare would be good here.
3. Don't redirect to GitHub like in the old days, as it would defeat the purpose of moving from GitHub.
4. Make sure only HTTPS is used.

### Describe alternatives you've considered

To bypass GFW, gitee.com has been tried: https://gitee.com/mcornella/ohmyzsh.
Downsides: it's not hosted by us and is controlled by a Chinese company.

* * * *

```[tasklist]
### Tasks
- [x] Review options for static hosting (Cloudflare, AWS S3, GCP GCS), including pricing and automation
- [x] Review adding security measures such as sig files
```

**Comment by robbyrussell** [comment]
Keeping an eye on this one, let me know how I can be of assistance

**Comment by LunarWatcher** [comment]
For future reference, install URL this generates is https://install.ohmyz.sh
