### ISSUE TITLE
Shortcut command for coauthoring

### ISSUE THREAD

**Issue by 2manycooks** [ohmyzsh/ohmyzsh#11464]
### Describe the proposed feature.

an alias that shortens the required text input to indicate commit coauthoring. perhaps 'gccab <NAME@EXAMPLE.COM>'.

**Comment by carlosala** [comment]
I don't think it would be that useful actually, probably it's more a feature that you'd add to your editor, just as a snippet. For example, I do that in my [neovim config](https://github.com/carlosala/dotfiles/blob/main/nvim/snippets/gitcommit.snippets)!
What do you think about?

**Comment by mcornella** [comment]
It might be feasible using commit trailers [1] [2]. A possible function command would be

```sh
function gccab {
  local coauthor="$1"; shift $(( $# > 0 ))
  git commit --trailer "Co-authored-by: ${coauthor}" "$@"
}

gccab "John Doe <name@example.com>"
```

[1]: https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---trailerlttokengtltvaluegt
[2]: https://git-scm.com/docs/git-interpret-trailers

That said, this takes a while to type and it might be better as Carlo said to add an automatism to the editor you use to write commits.

Either way, feel free to use the solution above. In [2] you'll find some configuration options if you want to automate this further, such as automatically running a command to get the author from somewhere (a commit maybe).

But I don't see this being a thing that will be used by many people.
