### ISSUE TITLE
Emoji and accents support

### ISSUE THREAD

**Issue by Marty42780** [ohmyzsh/ohmyzsh#11477]
### Describe the bug

I use an Ubuntu Docker container or I connect in ssh, with zsh, the accents and eomji are not displayed correctly, they are first replaced by `<ffffffff>` (several in a row sometimes) and when I add a space after they turn into `??`.

### Steps to reproduce

- Create a Ubuntu Docker countainer
- Connect to it with ssh
- Install ZSH and Oh My Zsh

### Expected behavior

No accent, no emoji and no caracteres like `€` or `§`.

### OS / Linux distribution

Ubuntu on Docker

### Zsh version

5.8.1

### Terminal emulator

Windows terminal app

### If using WSL on Windows, which version of WSL

None

### Additional context

I have already tried a lot of local configuration command like:
```bash
export LC_ALL=en_US.UTF-8
# or 
export LC_ALL=fr_FR.UTF-8
```
without success.

Note: Sorry for my english

**Comment by carlosala** [comment]
That's for sure not related to OMZ, it's something that has to do with your terminal emulator and your font. Try to install a Powerline font, or try different ones. You have similar issues here: https://github.com/ohmyzsh/ohmyzsh/issues/6561 https://github.com/ohmyzsh/ohmyzsh/issues/8948 https://github.com/ohmyzsh/ohmyzsh/issues/7708

**Comment by Marty42780** [comment]
I have accents and emojis in IPython

**Comment by carlosala** [comment]
are you using WSL2?

**Comment by Marty42780** [comment]
My local computer:
- Windows 11
- [Windows terminal](https://github.com/microsoft/terminal)
- OpenSSH

Remote container I connect to with SSH:
- [Ubuntu Official Docker Image](https://hub.docker.com/_/ubuntu)
- Zsh with OMZ installed with basic plugins (zsh-autosuggestions and zsh-syntax-highlighting)

Ask if you want more details

**Comment by carlosala** [comment]
Could you try PuTTY to do the same connection, to be sure it's not Windows + ssh + docker (which seems to be a lot of steps though when thinking on windows)

**Comment by Marty42780** [comment]
With PuTTY, I have the same result
![putty](https://user-images.githubusercontent.com/59181926/217903407-43b0bb61-25bf-452f-a44b-ec68d093f8e4.png)

**Comment by carlosala** [comment]
Nice!
