### ISSUE TITLE
Pipenv plugin: Option to not auto-activate pipenv shell

### ISSUE THREAD

**Issue by hoylemd** [ohmyzsh/ohmyzsh#11472]
### If the feature request is for a plugin or theme, specify it here.

pipenv

### If the feature solves a problem you have, specify it here.

I don't always want to use a pipenv subshell when I cd into a directory with a Pipfile, so I'd like to be able to turn that feature on or off.

This also caused some problems when trying to debug code in VSCode.  As soon as the shell is opened to execute the debugger command, the pipenv subshell is started, and then that new shell just sits and waits for input forever, so the debugging command never actually runs (or at least I need to explicitly exit it first).

### Describe the proposed feature.

Just like something you can configure in .zshrc, kind of like the options for the `ssh-agent` plugin (`zstyle :omz:plugins:ssh-agend lazy yes`)

### Describe alternatives you've considered

I've worked around the above issues by disabling the plugin, or configuring VSCode to 'hide' the Pipfile when attempting to debug so that the plugin doesn't auto-start the subshell.  Unfortunately, the auto-completion parts are still installed, so if I try to run a pipenv command and hit tab, I get errors

```
$pipenv run test core…(eval):1: command not found: _pipenv 
(eval):1: command not found: _pipenv
(eval):1: command not found: _pipenv
(eval):1: command not found: _pipenv
```

(in this example, I hit tab right after typing "core")

So I'll probably have to uninstall the plugin entirely to fix that (or realistically, tweak the plugin file and disable the auto-activate part), but I still want that autocompletion.  It'd be nice if there were an indicator I could add to my prompt as well, like virtualenv or conda plugins

### Additional context

I would open a PR, but I don't know much about defining options for zstyle so I'd have to go learn about that first.

**Comment by Bugsbugme** [comment]
I'd like this feature as well.
It's causing problems in VS Code I think because when you open a new terminal, it opens directly into the folder with the pipfile and pipenv is trying to open the subshell too quickly.

For now I have just commented out these lines in the plugin:
```
# autoload -U add-zsh-hook
# add-zsh-hook chpwd _togglePipenvShell
# _togglePipenvShell
```
Can still use the completions and aliases without the auto activate function.

**Comment by carlosala** [comment]
it's a great idea! Do you want to make a similar PR using `zstyle`?
