### ISSUE TITLE
The install url does not work.

### ISSUE THREAD

**Issue by tanishqdaiya** [ohmyzsh/ohmyzsh#11476]
### Describe the bug

When I tried to install oh-my-zsh on my desktop via cURL and wget, I didn't get a response. On visiting [the download link](https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh), I still don't see the page loading.

I think the links have been updated and needs an update everywhere referenced (I have checked the website and the README.md, both of them have the old link).

### Steps to reproduce

In your browser:
1. Visit [the install url](https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)

### Expected behavior

A response of GitHub with `install.sh` script.

### OS / Linux distribution

Arch Linux

### Zsh version

Not Applicable

### Terminal emulator

xfce4-terminal

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
The links are all up to date. It might be an issue with you accessing the script from [India](https://news.ycombinator.com/item?id=34231553) or [China](http://www.chinafirewalltest.com/?siteurl=github.com).

To bypass that, you can for now use the gitee.com resource:
```
sh -c "$(curl -fsSL https://gitee.com/mcornella/ohmyzsh/raw/master/tools/install.sh)"
```

This is a temporary workaround. We are looking to move the script to a self-hosted option: #11467.

**Comment by tanishqdaiya** [comment]
Thank you for your response.
