### ISSUE TITLE
Git plugin: The action and function of alias `gpristine` differ from those of previous versions

### ISSUE THREAD

**Issue by FelixDai** [ohmyzsh/ohmyzsh#11483]
### Describe the bug

Alias `gpristine` was defined before:
```
alias gpristine='git reset --hard && git clean -dffx'
```
now:
```
alias gpristine='git reset --hard && git clean --force -dx'
```

### Steps to reproduce

```
alias | grep gpristine
```

### Expected behavior

`gpristine` should clean all untracked files and directories, making the local repo like the newly cloned one.
However, after the commit 35454190f6aeae9b9f16acdbdd0cf72c32610ee8, this alias have only one `--force` clean option.

> Git will refuse to modify untracked nested git repositories (directories with a .git subdirectory) unless a second `-f` is given.

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/34601037/217500200-20717726-32aa-468d-99e0-1c28fa05a2e4.png)

### OS / Linux distribution

Any

### Zsh version

5.6

### Oh My Zsh version

master

### Terminal emulator

Any

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Thanks for the point, good one! 😉
