### ISSUE TITLE
Tab completion duplicates command with multiple theme

### ISSUE THREAD

**Issue by chrbrnracn** [ohmyzsh/ohmyzsh#11484]
### Describe the bug

When trying to use tab-completion to complete file/folder names the already typed command is duplicated. The duplicate  is then the real command, the first/original stays in place and cannot be deleted.

I could track down the issue to the theme, agnoster in my case. I tried a few more but not all...
Affected themes: agnoster, apple, awesomepanda, evan, fox, josh
Unaffected themes: clean, simple, gentoo, mikeh

### Steps to reproduce

1. Open a new shell (home directory)
2. Type ``cd D<Tab>`` or ``cd Do<Tab>`` --> Command is duplicated (see below)
3. Type ``cd Dow<Tab>`` --> Works fine

The behavior seems to happen only when there's more than one candidate for auto-completion and it happens only on the first <Tab>.

### Expected behavior

The command is not duplicated.

### Screenshots and recordings

Before pressing <Tab>:
```
 ✘ chrbrnracn@AMAVNF44  ~  cd Do
```
After pressing <Tab> once:
```
 ✘ chrbrnracn@AMAVNF44  ~  cd Do cd Do
Documents/  Downloads/
```

After pressing <Tab> twice:
```
 ✘ chrbrnracn@AMAVNF44  ~  cd Do cd Documents/
Documents/  Downloads/
```

### OS / Linux distribution

macOS 13.2

### Zsh version

5.8.1

### Oh My Zsh version

master (f8bf8f0)

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

### Additional context

.zshrc content (removed comments and empty lines)
```
export PATH=$HOME/bin:/usr/local/bin:$PATH:/opt/homebrew/bin
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"
zstyle :omz:plugins:ssh-agent agent-forwarding yes
zstyle :omz:plugins:ssh-agent lazy yes
zstyle :omz:plugins:ssh-agent identities ~/.ssh/id_rsa
plugins=(
  ssh-agent
  git
)
source $ZSH/oh-my-zsh.sh
alias ls="ls --color=always"
alias ll="ls -l"
```

**Comment by carlosala** [comment]
Here you have more info related!
