### ISSUE TITLE
AWS Plugin: Enable support for SSO Sessions

### ISSUE THREAD

**Issue by LintonFisher-cnic** [ohmyzsh/ohmyzsh#11482]
### If the feature request is for a plugin or theme, specify it here.

AWS Plugin

### If the feature solves a problem you have, specify it here.

For working with multiple accounts, users no longer need to perform an `aws sso login` after changing the `AWS_PROFILE`. Instead, you can configure an SSO session in the `~/.aws/config` file:

```
[sso-session my-sso-session]
sso_start_url = https://myapp.awsapps.com/start
sso_region = eu-west-1
sso_registration_scopes = sso:account:access
```

Then login once using `aws sso login --sso-session my-sso-session`. Changing the AWS profile after this won't require another `aws sso login`.

### Describe the proposed feature.

Add a command to the `aws` plugin to allow performing an SSO session login.

### Describe alternatives you've considered

Adding an alias manually to the `~/.zshrc`.

### Additional context

[https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sso/login.html](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sso/login.html)

**Comment by akshatakulkarni25** [comment]
is this issue available to contribute to. i would like to work on it. Is this under hacktoberfest

**Comment by hamonangann** [comment]
I can help it, is it still available?
