### ISSUE TITLE
Azure plugin #8848 requires uninstalled dependency

### ISSUE THREAD

**Issue by timfallmk** [ohmyzsh/ohmyzsh#11497]
### Describe the bug

Attempting to enable [the new Azure plugin](#8848) will produce the following error:

```shell
/opt/homebrew/opt/azure-cli/libexec/bin/az.completion.sh:11: command not found: register-python-argcomplete
```

### Steps to reproduce

1. `omz plugin enable azure`
2. (`omz reload` to work out powerlevel10k startup race condition (optional))
3. Get error

### Expected behavior

No errors and functional plugin? I'm not entirely sure what the intended use of the plugin is, there doesn't seem to be clear documentation, but that's a different issue.

### OS / Linux distribution

macOS 13.2.1

### Zsh version

5.8.1

### Terminal emulator

iTerm2 `Build 3.5.0beta10`

### If using WSL on Windows, which version of WSL

None

**Comment by timfallmk** [comment]
breaks #8848

**Comment by timfallmk** [comment]
It may be worth noting that I have `az` autocompletion from the homebrew install of the azure cli already. This could be interferring, but that's a guess.

```shell
# Fuck it
 eval $(thefuck --alias)

 # Azure CLI only install bash completions
 autoload -U +X bashcompinit && bashcompinit
 source /opt/homebrew/etc/bash_completion.d/az

 # Syntax highlighting
 # Needs brew install zsh-syntax-highlighting
 # Must be last
 source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
 ```

**Comment by carlosala** [comment]
@timfallmk could you please test out #11499? You can do that by executing `omz pr test 11499`

**Comment by timfallmk** [comment]
I get the same error from that one @carlosala 
```shell
-- console output produced during zsh initialization follows --

/opt/homebrew/opt/azure-cli/libexec/bin/az.completion.sh:11: command not found: register-python-argcomplete
```

**Comment by carlosala** [comment]
Could you post both `/opt/homebrew/opt/azure-cli/libexec/bin/az.completion.sh` and `/opt/homebrew/etc/bash_completion.d/az`?

**Comment by timfallmk** [comment]
`/opt/homebrew/opt/azure-cli/libexec/bin/az.completion.sh`
```
case $SHELL in
*/zsh)
   # Enable ZSH compatibility mode
   autoload bashcompinit && bashcompinit
   ;;
*/bash)
   ;;
*)
esac

eval "$(register-python-argcomplete az)"
```
`/opt/homebrew/etc/bash_completion.d/az`
```shell
_az_python_argcomplete() {
    local IFS=$'\013'
    local SUPPRESS_SPACE=0
    if compopt +o nospace 2> /dev/null; then
        SUPPRESS_SPACE=1
    fi
    COMPREPLY=( $(IFS="$IFS" \
                  COMP_LINE="$COMP_LINE" \
                  COMP_POINT="$COMP_POINT" \
                  COMP_TYPE="$COMP_TYPE" \
                  _ARGCOMPLETE_COMP_WORDBREAKS="$COMP_WORDBREAKS" \
                  _ARGCOMPLETE=1 \
                  _ARGCOMPLETE_SUPPRESS_SPACE=$SUPPRESS_SPACE \
                  "$1" 8>&1 9>&2 1>/dev/null 2>/dev/null) )
    if [[ $? != 0 ]]; then
        unset COMPREPLY
    elif [[ $SUPPRESS_SPACE == 1 ]] && [[ "$COMPREPLY" =~ [=/:]$ ]]; then
        compopt -o nospace
    fi
}
complete -o nospace -o default -o bashdefault -F _az_python_argcomplete "az"
```

**Comment by carlosala** [comment]
you should not get that issue when using my PR. Using my branch, remove `~/.zcompdump...` and open a new terminal. I don't see where is it called to that python stuff bash completion file.

**Comment by timfallmk** [comment]
@carlosala 
1. Removed `.zcompdump`
2. `omz pr clean`
3. `omz pr test 11499`
4. `omz enable plugin azure`

Same error

**Comment by timfallmk** [comment]
Found the problem: `omz pr test` was failing due to merge conflicts.

Confirmed #11499 works.

**Comment by carlosala** [comment]
Nice! Merged☺️

**Comment by carlosala** [comment]
Thanks for the report!
