### ISSUE TITLE
Add a command to handle pad strings to a fixed width

### ISSUE THREAD

**Issue by rafaelribeiroo** [ohmyzsh/ohmyzsh#11498]
### If the feature request is for a plugin or theme, specify it here.

plugin

### If the feature solves a problem you have, specify it here.

It will solve my menu messages for automation scripts.

### Describe the proposed feature.

Its quite simple, basically its simillar to[ string-pad funcionality ](https://fishshell.com/docs/current/cmds/string-pad.html)in fish-shell. 

**Examples:**

![image](https://user-images.githubusercontent.com/19275140/218924009-0014e4f2-f3ab-45fa-982c-c83d9522fc37.png)

### Describe alternatives you've considered

I already try to do that with printf, but it seems not works properly.

**Comment by mcornella** [comment]
I can see this being helpful for a utility function on some script, but not for the general day-to-day use of the interactive shell. Thanks for the submission though.
