### ISSUE TITLE
loading theme-and-appearance takes a very long time if there are lots of files in the home directory

### ISSUE THREAD

**Issue by briansorahan** [ohmyzsh/ohmyzsh#11500]
### Describe the bug

As of yesterday I have a directory in $HOME with ~1.5M files .... for reasons
I dug into why I couldn't start a new shell, or why this was taking a very long time.
I narrowed it down to [this line](https://github.com/ohmyzsh/ohmyzsh/blob/574669da6b71462c1f92c75ad75f66476b92974c/lib/theme-and-appearance.zsh#L24) and there is an easy workaround i.e. I can set DISABLE_LS_COLORS
But I figured I'd open an issue since there is prob a better way to test if a `-G` flag exists on the system (guessing that's the intention behind that command)

### Steps to reproduce

* Install oh-my-zsh on mac
* Copy an unreasonable amount of files to your home directory
* Try to start a new shell

### Expected behavior

New shell starts very quickly

### OS / Linux distribution

Mac Ventura 13.2.1

### Zsh version

5.8.1

### Oh My Zsh version

master (50550c70eaa36e79fdf380bdc4ddad4a1ad581a0)

### Terminal emulator

iTerm

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Let's change that to `ls -G "$ZSH"`, which should be always there and has a fixed amount of files, and then fallback to `.` if it doesn't exist.

**Comment by carlosala** [comment]
Thanks for the report!

**Comment by briansorahan** [comment]
Thanks for the quick fix!

**Comment by carlosala** [comment]
you're welcome!
