### ISSUE TITLE
Git diff output showing after update

### ISSUE THREAD

**Issue by fferegrino** [ohmyzsh/ohmyzsh#11508]
### Describe the bug

Ever since I updated (21/FEB/2023) I see the output as if I was diffing a file.  Did I do something wrong?

### Steps to reproduce

1. Update to the latest version

### Expected behavior

A prompt without the Git diff output.

### Screenshots and recordings

![Screenshot 2023-02-21 at 08 30 28](https://user-images.githubusercontent.com/1820946/220303977-2d0a865b-0b18-4ab9-ac97-340b4e3ba76e.png)

### OS / Linux distribution

macOS Ventura 13.2

### Zsh version

5.8.1

### Terminal emulator

iTerm2 and Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by rwmitchell** [comment]
You modified a file in the OMZ directory then you told git to stash the changes.

**Comment by carlosala** [comment]
Follow the instructions [here](https://github.com/ohmyzsh/ohmyzsh/issues/11058#issuecomment-1190024382) and see if it works.
