### ISSUE TITLE
Terraform tab autocomplete not work for macOS 13.1 arm64

### ISSUE THREAD

**Issue by isokalau** [ohmyzsh/ohmyzsh#11506]
### Describe the bug

When I try to use Tab in zsh terminal for autocomplete, it doesn't work. Is there any way to workaround it? Default `terraform -install-autocomplete` command adds new lines in my .zshrc file but this is not useful because same lines are already included into terraform plugin. And if I try to keep this lines in one of this files, it doesn't work.
Autocompletion works only for 1st line suggestions (apply, destroy, plan, workspace etc.)

### Steps to reproduce

1. Enable plugin terraform
2. try `terraform apply -v` + Tab

### Expected behavior

You should see suggestions of `-var-file` and another option starts from `-v...`

### OS / Linux distribution

macOS 13.1 arm64

### Zsh version

5.8.1

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
We switched to default bash completion, that should be asked in terraform repo. Even though, let's switch back to custom zsh one, it seems it's giving less issues.

**Comment by isokalau** [comment]
Could you please help me with switching to this one? What I should do?

**Comment by carlosala** [comment]
I'll push a commit tomorrow, updating with `omz update` will be enough.

**Comment by isokalau** [comment]
Okay, thank you so much!

**Comment by carlosala** [comment]
Closed in c50bac7b42e7d24dd9ef314fa9bf17859e4218ed
