### ISSUE TITLE
command too long: ^@^@

### ISSUE THREAD

**Issue by Advaith3600** [ohmyzsh/ohmyzsh#11504]
Zsh version: zsh 5.9 (x86_64-pc-msys)
Platform: Windows

Zsh is installed through git bash. Whenever I open a new terminal I am getting such an error. 

![image](https://user-images.githubusercontent.com/21041099/219845356-d24895cb-5211-413c-a8a1-c1fe59df0702.png)

**Comment by Advaith3600** [comment]
When I tried opening the `git.plugin.zsh` file, it was replaced with `^@`. Is this something that happened during `omz update`? Because that is the only thing I have done before this error started appearing.

**Comment by carlosala** [comment]
That is really weird. Which is the output of `git diff` inside .oh-my-zsh directory?

**Comment by mcornella** [comment]
[`^@` is the caret representation for a null character](https://en.wikipedia.org/wiki/Null_character#:~:text=In%20caret%20notation%20the%20null,to%20get%20the%20%40%20sign). It is possible that the update failed and the file became corrupt. Try running `cd $ZSH; git reset --hard plugins/git/git.plugin.zsh`.

**Comment by mcornella** [comment]
You also report that you used git bash to update. I would suggest you to use a Linux `git` command instead of `git.exe` if this keeps happening after trying out the command above. You can check this out if `git.exe` is not the first command in the output of running `which -a git`.

**Comment by Advaith3600** [comment]
I'm sorry, I couldn't reply, I had to, unfortunately, wipe out my PC a couple of days back and couldn't produce the outputs as you guys asked. I resolved the issue with a simple `git stash` and reported it so that if the solution is straight forward can be resolved. Please feel free to close the issue.
