### ISSUE TITLE
zplug warns `Failed to load vcs_info.zsh` 

### ISSUE THREAD

**Issue by liushapku** [ohmyzsh/ohmyzsh#11524]
### Describe the bug

When using
```
zplug robbyrussell/oh-my-zsh, use:"lib/*.zsh"
zplug load --verbose
```
I see the following warning
```
WARNING:  Failed to load "~/.zplug/repos/robbyrussell/oh-my-zsh/lib/vcs_info.zsh" (robbyrussell/oh-my-zsh)
```
This is because the line 
```
autoload -Uz +X regexp-replace VCS_INFO_formats 2>/dev/null || return
```

Somehow the `return` generates exit status 1.

I tested a script with one line `return`, and then source it in the zsh and I also observe exit status 1. This is strange.

### Steps to reproduce

```
zplug robbyrussell/oh-my-zsh, use:"lib/*.zsh"
zplug load --verbose
```

### Expected behavior

Load `vcs_info.zsh` successfully

### OS / Linux distribution

ubuntu 22.04

### Zsh version

5.8.1

### Terminal emulator

xterm

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
That's a mistake from my part. When doing just `return`, the returned value is the same as the last command, so
```
false || return
```
is equivalent to `false`. I'll push a quick fix for this.
