### ISSUE TITLE
`omz update` stops script execution if updates are performed

### ISSUE THREAD

**Issue by dbhagen** [ohmyzsh/ohmyzsh#11522]
### Describe the bug

I wrote a command that does the following:
```bash
update_all () {
  omz update
  brew upgrade
  brew update -y
  mas upgrade
}
```
When `omz update` doesn't have anything to update, the rest of the commands run just fine. When there are omz updates performed, the command stops after the omz updates.

### Steps to reproduce

Setup the following command in your .zshrc file or similar on a MacOS device with Brew and MAS installed:
```bash
update_all () {
  omz update
  brew upgrade
  brew update -y
  mas upgrade
}
```

Run `update_all`. If OMZ has updates, it fails. If it doesn't, the following commands run.

### Expected behavior

All commands should run, regardless of OMZ updates.

### OS / Linux distribution

MacOS 13.2.1

### Zsh version

5.8.1

### Oh My Zsh version

master (aca0488)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by rwmitchell** [comment]
That’s because update re-execs the shell to reload the new settings

**Comment by mcornella** [comment]
Use `omz update --unattended`, but do note that its use is discouraged because it's not accesible via non-zsh processes, while using `$ZSH/tools/upgrade.sh` does.

**Comment by carlosala** [comment]
@mcornella should we close here?
