### ISSUE TITLE
Add resistance for OS update/upgrade

### ISSUE THREAD

**Issue by dsha256** [ohmyzsh/ohmyzsh#11542]
#### I have installed ZSH and everything was working smoothly. After updating my OS, some of the commands are not found anymore. I know there are a bunch of solutions available out there, but I suggest making your own like the universal one. Or maybe there is one, not mentioned in your doc and in the repo. Could you please let us know your decision or plans on this?

---

#### Error text in case of using Go:
```text
zsh: command not found: go
```

![image](https://user-images.githubusercontent.com/56347073/222960701-4e29bc16-da38-4257-8672-8fae1e103a15.png)

### Steps to reproduce

If you are using Ubuntu 22.04.2 LTS, after updating OS and, for example, just running the go command will give you the same bug.

### OS / Linux distribution

Ubuntu 22.04.2 LTS

### Zsh version

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### Terminal emulator

TERM=xterm-256color; GNOME_TERMINAL_SERVICE=:1.133

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
`omz` does not manage where your commands are located, and if that directory is (or not) in `$PATH`, that's out of scope for `omz`.
Even though, there are a bunch of plugins that add entries to `$PATH` for particular binaries, for example [fzf's one](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/fzf/fzf.plugin.zsh).
Thanks for your contribution!
