### ISSUE TITLE
ssh-agent quiet mode isn't working to me

### ISSUE THREAD

**Issue by usernamer-git** [ohmyzsh/ohmyzsh#11551]
### Describe the bug

Followed the https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/ssh-agent , but ssh-agent quiet mode isn't working to me

![za](https://user-images.githubusercontent.com/84246111/223992753-6ce2e991-fd74-4e6c-9dfa-1db224ac570e.png)

After reboot and opening the terminal:

![zb](https://user-images.githubusercontent.com/84246111/223994033-0cd06465-0d60-40de-8c2e-be82c491e4fa.png)

### Steps to reproduce

1. add "zstyle :omz:plugins:ssh-agent quiet yes" on ~/.zshrc and save
2. after reboot and open the terminal
3. the message from ssh-agent still showing

### Expected behavior

Expect to ssh-agent quiet mode, work to not showing "added ... key"  message

### OS / Linux distribution

Void Linux [glibc]

### Zsh version

5.9

### Oh My Zsh version

master (3ea0e0d2)

### Terminal emulator

xfce4-terminal

### If using WSL on Windows, which version of WSL

None

**Comment by usernamer-git** [comment]
I decided to uninstall and remove everything related to zsh and oh my zsh, i installed and configured everything again for peace of mind and it's working as expected now.

**Comment by carlosala** [comment]
nice, I'm glad is working!
