### ISSUE TITLE
Bar broken after OMZ update

### ISSUE THREAD

**Issue by Oman395** [ohmyzsh/ohmyzsh#11558]
### Describe the bug

Title says it. Updated omz, now this is what I get:
```
/home/oran/.oh-my-zsh/lib/theme-and-appearance.zsh:4: parse error near `<<<'
${ret_status}$fg_bold[green] $fg[cyan]~ $fg_bold[blue]$(git_prompt_info)$fg_bold[blue]$(svn_prompt_info)$reset_color
```
Using awesomepanda, when I switch to certain themes (jonathan is the most recent one I tested) it works fine except the right side of the jonathan theme still shows up. Based on my limited testing, it looks like any theme that has nothing on the right has this issue, but that could just be a coincidence. When I attempt to update manually, I get `lib/theme-and-appearance.zsh: needs merge`, so that might have something to do with it.

### Steps to reproduce

1. Update omz to latest
2. That's it.

### Expected behavior

The bar to display normally.

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Oh My Zsh version

master (92387d9f)

### Terminal emulator

Kitty and Konsole

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Follow the instructions here https://github.com/ohmyzsh/ohmyzsh/issues/11058#issuecomment-1190024382

**Comment by Oman395** [comment]
Thanks, that worked. Any idea why updating broke it like that, despite other updates not? It'd also be nice if there was just something in place to say "hey, if there's three random arrows, and the git repo is messed up, maybe we should warn the user". That's just a thought though, I don't have nearly enough experience with the omz code to know how hard that would be

**Comment by rwmitchell** [comment]
It means you or something not in OMZ that you ran updated at least one file under git control that was also getting updated by omz update. This is purely user error.
