### ISSUE TITLE
Red-Prompt on new line instead of replacing green one?

### ISSUE THREAD

**Issue by Gandalf1783** [ohmyzsh/ohmyzsh#11552]
### Describe the bug

When I enter a command, that returns an error, the line with that command is marked with a green arrow.
The next line, valid or not, gets marked red, which is confusing, since it was valid in my case.

### Steps to reproduce

Example: Installing something via apt without using sudo:

❯ apt-get install mosh
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
❯ sudo apt-get install mosh
[sudo] password for user:

The first line has a green arrow, while the thirds one is red.

### Expected behavior

Color the arrow red where the command actually failed.

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/46635221/224000635-d131e0d5-e84d-4acd-ac73-8c6a982c5688.png)

### OS / Linux distribution

Debian 11 (Bullseye) (using Windows Subsystem for Linux)

### Zsh version

5.8

### Terminal emulator

Windows Terminal

### If using WSL on Windows, which version of WSL

WSL2

### Additional context

I am using Oh My ZSH with powerlevel10k

**Comment by rwmitchell** [comment]
After a command is run, the new prompt shows the status of the previous exit status. 

It is at the new prompt you eyes are looking where you need feedback on what just happened. 

Changing the previous prompt makes no sense as many commands would’ve likely scrolled it if the screen.

**Comment by Gandalf1783** [comment]
It is just really confusing to me.
I agree with you that many commands will not be displayed anymore after executing.

However, it is not "sudo apt-get install... " that failed. It was the command above.
I personally think that this is misleading if you dont know what exactly happens. The current behaviour makes the arrow (for me) kind of obsolete.

**Comment by carlosala** [comment]
@Gandalf1783 there are a lot of different themes that doesn't bundle this feature! Personally, I think this feature is quite useful to know if `$?` is `0` or not!

**Comment by Gandalf1783** [comment]
I really like the idea. It is really useful. Thats also why I have the return-value indicator on the right side of the terminal (the number with the red x or the checkmark) configured for my prompt.

In my eyes, you can see the cli now as a kind of table.
At the beginning, you got your indicator, if a command returned with 0 or not. However, it is not related to the command right next to it.

I know what you mean, since of course you have the return value AFTER a command or programm finished executing, so it gives you feedback after something has completed (successfully or not).

But for commands like git, dhclient, cat, tail, cp, ls, mkdir, chown, chmod etc... which dont have a long console output (usually), the way its implemented does not make sense to me.

I dont want to push y'all into changing this, especially since people are using this for quite some time now. 

I just see e.g. the arrows to be a thing of "pointing" and conveying meaning. It looked to me as a "this line produced an error", similar to what an IDE would do if theres a bug, error that occured on a specific line of code. And since that line didnt threw the error, but the one above did, this seems wrong.

**Comment by carlosala** [comment]
I see your point, just a matter of preference!

**Comment by rwmitchell** [comment]
And the difficulty in trying to accomplish it. The prompt cmd  would have to know where the previous prompt was displayed and then go back to rewrite it, without affecting anything else.

**Comment by rwmitchell** [comment]
htop is using ncurses. Try your method, then submit it once you have it working with both static and scrolling output

**Comment by rwmitchell** [comment]
> Hm, I don't think thats an issue. Count the lines since the last command, write into the buffer at that location, done.
> 
> Applications like htop are constantly changing their buffer to provide "real-time" data, so a single rewrite in the buffer to display an icon shouldn't be hard.

As trivial as this is, I'm surprised you haven't submitted a patch yet.  If you're stuck on something, post it and maybe someone can help you out.

**Comment by rwmitchell** [comment]
> Hm, I don't think thats an issue. Count the lines since the last command, write into the buffer at that location, done.
> 
> Applications like htop are constantly changing their buffer to provide "real-time" data, so a single rewrite in the buffer to display an icon shouldn't be hard.

@Gandalf1783 Given your lack of response, I'm assuming you just wanted to gaslight someone (me in this case) without any actual knowledge of the problem?  You just wanted to sound like you knew more than someone else without knowing anything at all?

No program has enough knowledge (currently) to pull off what you think is trivial.

The terminal doesn't know the purpose of the text it displays, it can't do it.

zsh/omz/p10k doesn't know what happens in-between the prompts.  They can control what is displayed on the current prompt lines.   They can query where on the terminal they are, but once another program has run with unknown amount of text output and the screen scrolls, all for that previous knowledge is useless.  Terminal queries for row number only apply to the displayed screen, not relative to the top of the scroll back buffer.  

To be fair, I too was annoyed by this some time ago and solved it for myself by displaying green/red lines across the entire terminal width before the next prompt is displayed.  The color line is the status for everything above the line.  I've left the prompt symbol in, but rarely look it.  Here's an example:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/15944841/224548171-55aae1cb-8d04-4feb-af7a-20a90993c3ad.png">

Now, if you'll notice, iTerm2 does indeed update its prompt marker (which is outside the terminal text area).

**Comment by Gandalf1783** [comment]
Excuse me for not answering.

I haven't had a look on this for the last few days.

First of all, what I didn't notice is that this is written in shell scripts. I thought this was a C application that extended the zsh shell/passed all inputs to it and gave the user its own custom shell with custom themes.

In regards to the "No program has the knowledge...": I just said it was trivial to count lines, wait for the exit code to return and edit the first character (the prompt symbol) to the according color. Like I said, I wasn't aware that this is a shell script. Of course, without any external help this cant be done.

I've taken a look, and since e.g. Github-Repos and their branch can be displayed (e.g. master), I have noticed the extra github-helper program thats started in the background.

I assume that it is possible to pass the stdout/stdin from the session to another program, count lines/return code and just tell zsh what should happen or just modify the buffer directly.

I would've forked the repo and ran my own tests/integrations, but due to the lack of knowledge in shell-scripting im basically through the topic. I cant really contribute anything here, I was just curious if there was some option I was missing, since I only found some posts online that were interested in a similar solution / were bothered by this.

**Comment by rwmitchell** [comment]
> Excuse me for not answering.
> 
> I haven't had a look on this for the last few days.
> 
> First of all, what I didn't notice is that this is written in shell scripts. I thought this was a C application that extended the zsh shell/passed all inputs to it and gave the user its own custom shell with custom themes.

So you didn't even know what the topic was about?
 
> In regards to the "No program has the knowledge...": I just said it was trivial to count lines, wait for the exit code to return and edit the first character (the prompt symbol) to the according color. Like I said, I wasn't aware that this is a shell script. Of course, without any external help this cant be done.

Even that isn't trivial.  Count linefeeds?  What about lines that wrap to the next line?  Output from a PAGER, such as as less?  Output from htop?  How do you count those lines?

> I've taken a look, and since e.g. Github-Repos and their branch can be displayed (e.g. master), I have noticed the extra github-helper program thats started in the background.
> 
> I assume that it is possible to pass the stdout/stdin from the session to another program, count lines/return code and just tell zsh what should happen or just modify the buffer directly.

It would have to duplicate everything the terminal is already doing to accurately determine how much screen space has been used.  Not impossible, but hardly trivial.

> I would've forked the repo and ran my own tests/integrations, but due to the lack of knowledge in shell-scripting im basically through the topic. I cant really contribute anything here, I was just curious if there was some option I was missing, since I only found some posts online that were interested in a similar solution / were bothered by this.

Good for you telling others how trivial something is.

**Comment by mcornella** [comment]
It has been established already that this is not possible, and any further discussion is pointless.

Richard, I'm concerned about your tone. If you're not able to have a technical argument without getting offended, just don't engage and forget about it. I'd much rather that than have this kind of vitriol on our project.

**Comment by mcornella** [comment]
To be extra clear, the implementation of this is not feasible because of the *technical* reasons that Richard mentioned. He is 100% correct on that. It is difficult to understand why it's not just "counting lines" when you don't have a full understanding of how a terminal works. But my point about the tone still stands. End of discussion.
