### ISSUE TITLE
Git checkout previous alias

### ISSUE THREAD

**Issue by flippidippi** [ohmyzsh/ohmyzsh#11564]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### If the feature solves a problem you have, specify it here.

Being able to easily go back and forth between branches. We have `gcm` to easily go to main, but to make it easier to go back to a feature branch it would be nice to have a shortcut for `git checkout -`. This command goes to the previous checked out branch.

### Describe the proposed feature.

Add a new git alias like `gcw` that maps to `git checkout -`. 

### Describe alternatives you've considered

If there is a better shortcut that's fine. I thought `gcp` would make sense but that's already taken so `gcw` (git checkout working) makes sense to me.

**Comment by carlosala** [comment]
As stated in #11565, closing!
