### ISSUE TITLE
zsh auto package suggestions is disabled

### ISSUE THREAD

**Issue by ShubhamKumar89** [ohmyzsh/ohmyzsh#11562]
#### When we type a command into the Ubuntu bash terminal and instead of going `command not found: <package>`, we get something like this:

```
$ ag 
Command 'ag' not found, but can be installed with:
sudo apt-get install silversearcher-ag
```

#### Try to run any package that is not come pre-installed in your system, like

```
$ ag
zsh: command not found: ag
```

#### Must recommend package suggestions by default, like this:

```
$ ag
Command 'ag' not found, but can be installed with:
sudo apt-get install silversearcher-ag
```

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/97805339/225109888-9bdcd1bd-87e8-4c89-976d-8881c6fc26e4.png)

### OS / Linux distribution

Ubuntu 20.10

### Zsh version

5.9

### Oh My Zsh version

master (3ea0e0d)

### Terminal emulator

Tilix

### If using WSL on Windows, which version of WSL

None

#### Solved using the following commands:

```
sudo apt install command-not-found
echo "source /etc/zsh_command_not_found" >> ~/.zshrc
exec zsh
```

[Reference](https://askubuntu.com/questions/1226574/how-do-i-enable-zsh-package-suggestions-as-in-ubuntu-bash)

**Comment by carlosala** [comment]
That is something added to shell, it's not the default behaviour. Adding that line to `zshrc` seems to be the right approach.
Thanks for your contribution!

**Comment by rwmitchell** [comment]
Does the ```command-not-found``` plugin, already in OMZ, do the same thing?

**Comment by carlosala** [comment]
For some platforms, yas!

**Comment by carlosala** [comment]
For some platforms, yas!
