### ISSUE TITLE
Completion for md-to-clip tool

### ISSUE THREAD

**Issue by EmilySeville7cfg** [ohmyzsh/ohmyzsh#11576]
### Describe the proposed feature.

Hi! As a project author, I am requesting nu completion based on [Bash completion](https://github.com/command-line-interface-pages/v2-tooling/tree/main/md-to-clip#completions-pencil) for my CLI tool. What it does: basically, it converts TlDr pages to Command Line Interface Pages. The difference between them, that the last ones have [more expressive syntax](https://github.com/command-line-interface-pages/syntax/blob/main/type-specific/cli.md).

### Additional context

[Here](https://command-line-interface-pages.github.io/site.github.io/about/) is a project site.

**Comment by carlosala** [comment]
Hi @EmilySeville7cfg! Thanks for the suggestion! Even though, it seems the tool has not got traction yet, it'd be better to wait until there's a big chunk of users using it. In the meantime, it seems like a custom plugin would make the trick.
Thanks!

**Comment by EmilySeville7cfg** [comment]
How big this chunk of users expected to be?
