### ISSUE TITLE
aws plugin no longer shows region

### ISSUE THREAD

**Issue by vschum** [ohmyzsh/ohmyzsh#11589]
### Describe the bug

It seems like f9f01e48a890ad4359a6973d1b8a7039f57b2d08 introduced a bug, as the local `region` variable being displayed in the prompt is no longer set.

### Steps to reproduce

use `asr` to set a region and you'll see that the prompt only shows the delimiters.

### Expected behavior

region that was set using `asr` should be displayed in the prompt.

### OS / Linux distribution

macOS

### Zsh version

5.9

### Oh My Zsh version

master (8f6fbe23)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Good catch, sorry for the bug 😉
