### ISSUE TITLE
Add a new alias to git to refer to the last branch you were on

### ISSUE THREAD

**Issue by jessekalil** [ohmyzsh/ohmyzsh#11592]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### Describe the proposed feature.

That a new alias be added in the git plugin to refer to the last branch you were on

### Describe alternatives you've considered

`git checkout -` or `git checkout @{-1}` 

https://git-scm.com/docs/git-checkout#Documentation/git-checkout.txt-ltbranchgt

**Comment by carlosala** [comment]
we decided to not add that alias, you can use `gco -` as a short way with `git` plugin
