### ISSUE TITLE
Installer Script Hosted On The Oh My Zsh Site Domain

### ISSUE THREAD

**Issue by SX-9** [ohmyzsh/ohmyzsh#11595]
### If the feature solves a problem you have, specify it here.

why host the installer script on github with a long link to the installer when you can shorten it with your domain ohmyz.sh

### Describe the proposed feature.

the installer script link to be shorter, like ohmyz.sh/installer.sh

**Comment by carlosala** [comment]
refer to #11467

**Comment by carlosala** [comment]
By the way, in install.ohmyz.sh there's the installer, but it's just a redirect to githubraw
