### ISSUE TITLE
oh-my-zsh bug on tab

### ISSUE THREAD

**Issue by 20020389** [ohmyzsh/ohmyzsh#11604]
### Describe the bug

i get this bug after pressed tab if i entered "sudo dnf install " or "sudo dnf remove ". Please fix it

### Steps to reproduce

1. Enable plugin '...'
2. Type command 'sudo dnf install ' or try to complete command 'sudo dnf remove ' then press tab
3. See error sqlite3: command not found...

### Expected behavior

it trying excute sqlite3

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/81224217/230526066-01ec15d8-34e1-4ca8-94db-a1986ac2b231.png)

### OS / Linux distribution

Fedora 38

### Zsh version

5.9

### Terminal emulator

Gnome terminal

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
It's not an ohmyzsh issue. Dnf probably stores its packages in a sqlite database, and when completing a command you are just quering the database. Install the package and you are going to get rid of the error.

**Comment by 20020389** [comment]
@carlosala actually not, i tried installing sqlite and when i press tab the terminal tries to execute sqlite. if i turn off ohmyzsh no error occurs. sorry for the late reply.

**Comment by carlosala** [comment]
`omz` does not touch `dnf` completion, it's [this file here](https://github.com/zsh-users/zsh/blob/e5f8cc99f524db8db7c7fbe5957609db63869d0e/Completion/Redhat/Command/_dnf) from zsh itself. It uses sqlite to query the package database

**Comment by shinebayar-g** [comment]
Hi. Is this issue ever solved? Typing `sudo dnf remove m<PRESS TAB>` would result in this error.

```
❯ sudo dnf remove mzsh: sqlite3: command not found...
Install package 'sqlite' to provide command 'sqlite3'? [N/y] 
```

And If I install `sqlite` package and retry again, now I'm getting:

```
❯ sudo dnf remove mError: in prepare, no such table: installed                                                     
Error: in prepare, no such table: installed
Error: in prepare, no such table: installed
```
