### ISSUE TITLE
Missing icon in "agnoster" theme

### ISSUE THREAD

**Issue by jaiakash** [ohmyzsh/ohmyzsh#11600]
### Describe the bug

Missing icon in "agnoster" theme in vs code.

### Steps to reproduce

- Use "agnoster" theme in VS Code.
- Open terminal

### Expected behavior

It should show icons.

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/33419526/229910684-c7ea9d6b-1c42-4c19-990d-065e282d2178.png)

### OS / Linux distribution

Ubuntu 22.04

### Zsh version

5.9

### Terminal emulator

Gnome Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
This happens when you are using a `locale` that doesn't support UTF-8. See https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-change-my-locale for how to change that.
