### ISSUE TITLE
File not found / Reinstalling Ohmyzsh

### ISSUE THREAD

**Issue by samimcguire** [ohmyzsh/ohmyzsh#11603]
The repository is gone, you have to delete the folder manually and reinstall.

_Originally posted by @mcornella in https://github.com/ohmyzsh/ohmyzsh/issues/11406#issuecomment-1364557599_
            
Hi everyone!
I have exactly the same issue but I am unable to find the folder. Is there another way to manually delete and reinstall ohmyzsh?
Thanks!

**Comment by carlosala** [comment]
Which is the error you get when opening your terminal?

**Comment by samimcguire** [comment]
Hi Carlo!

I'm sorry. We can close the ticket. :) In walking through everything I was
able to find the folder and remove it manually.

I've got everything reinstalled and working great.

Thank you!
