### ISSUE TITLE
Tab completion for alias commands under mac osx not work

### ISSUE THREAD

**Issue by windless0530** [ohmyzsh/ohmyzsh#11605]
### Describe the bug

If some command is set as an alias, tab completion no longer works for command arguments.

### Steps to reproduce

Let's take the 'cd' command for example.

1. In order to list all files in the new folder after 'cd' automatically, set the 'cd' command as the following alias, in .zshrc file:
`_my_cd() { IFS=$'\n'; cd $1; ls -lah; };`
`alias cd='_my_cd'`

2. Source ~/.zshrc or open new terminal window.

3. Press 'cd' + 'space' + 'tab', expecting candidate folders to be completed, while no completion is made.
`cd `

### Expected behavior

Auto completion works.

### OS / Linux distribution

macOS Ventura 13.3

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

### Additional context

1. If 'cd' is not set as an alias, everything works fine.
2. Under Ubuntu 20.04.5, everything works fine even when 'cd' is set as an alias.
3. For OTHER alias commands, the same bug ALSO EXISTS.

This bug seems to be introduced by recent updates, for the mentioned alias has been working perfectly for years under osx as well as zsh, until latest oh-my-zsh update.

**Comment by rwmitchell** [comment]
Remove the leading underscore from your function and it’s use in the alias, then try it

**Comment by mcornella** [comment]
The issue is that you have defined a custom function that zsh doesn't know how to complete. As the expected arguments are the same as for `cd`, define the completion function as below
```sh
compdef _cd _my_cd
```
Here `_cd` is the completion function for cd and `_my_cd` is the function / command to be completed.

**Comment by windless0530** [comment]
> Remove the leading underscore from your function name and it’s use in the alias, then try it

Thanks! This is the simplest working solution for me!
