### ISSUE TITLE
azure plugin: wrong path when using AZURE_CONFIG_DIR?

### ISSUE THREAD

**Issue by Banchio** [ohmyzsh/ohmyzsh#11606]
In the azure plugin, when a custom AZURE_CONFIG_DIR is present, probably the path should not include .azure again since the env var should point to the folder containing the configuration file.

https://github.com/ohmyzsh/ohmyzsh/blob/49d34d00cdaf132f318700398bf42120ff1af8e7/plugins/azure/azure.plugin.zsh#L21

**Comment by carlosala** [comment]
@Banchio I'm not sure if I understand what are you saying. That syntax checks if `$AZURE_CONFIG_DIR` is a file or, in case it's not defined, if `$HOME/.azure/azureProfile.json` is a file.
The only error I see there is that probably `$AZURE_CONFIG_DIR` is a directory and not a file, and we should check if `${AZURE_CONFIG_DIR}/azureProfile.json` is a file instead. Am I right?

**Comment by Banchio** [comment]
Sorry I did not interpreted correctly the if condition. You are right $AZURE_CONFIG_DIR is a directory (btw this is exactly my case). Thanks!

**Comment by carlosala** [comment]
And do you have that `azureProfile.json` file inside?

**Comment by Banchio** [comment]
> And do you have that `azureProfile.json` file inside?

Yes I do, it is created by azure cli
