### ISSUE TITLE
`gbda` should delete squash-merged branches

### ISSUE THREAD

**Issue by Albert221** [ohmyzsh/ohmyzsh#11613]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### Describe the proposed feature.

Someone already did something similar: https://github.com/jmaroeder/plugin-git/blob/216723ef4f9e8dde399661c39c80bdf73f4076c4/functions/gbda.fish

**Comment by robbyrussell** [comment]
We'd welcome a PR for this
