### ISSUE TITLE
zsh: no matches found: --gtest_filter=*

### ISSUE THREAD

**Issue by mgoutham** [ohmyzsh/ohmyzsh#11615]
### Describe the bug

not able to run gtest using filter which used to work on bash

command: ./Executable-x.x.x_test --gtest_filter=ABC.*
output: zsh: no matches found: --gtest_filter=ABC.*

### Steps to reproduce

try to run google test using --gtest_filter argument

### Expected behavior

specific test case to be excuted

### OS / Linux distribution

Ubuntu 16.04.7 LTS

### Zsh version

5.1.1

### Terminal emulator

xterm-256color

### If using WSL on Windows, which version of WSL

None

**Comment by rwmitchell** [comment]
This isn’t bash.  Put a backslash before the asterisk.

**Comment by carlosala** [comment]
@mgoutham also adding `setopt nullglob` will make it behave as you expect :)
