### ISSUE TITLE
autocomplete doesn't work if path has extra /

### ISSUE THREAD

**Issue by awoodx** [ohmyzsh/ohmyzsh#11623]
### Describe the bug

Autocomplete does not work if the path contains extra '/'. I discovered this issue when my prompt would hang when attempting an autocompletion. I noticed it only happens when the path contains an extra '/'. When the path contains an extra '/', the completer was searching a bunch of directories on the system. One of these contained a broken NFS mount which would hang my terminal. I though it was strange because the broken NFS mount path was no where near where I was running the autocomplete.

### Steps to reproduce

1. open zsh prompt with oh-my-zsh enabled
2. `mkdir /tmp/test_dir`
3. `touch /tmp/test_dir/test_file`
4. `ls /tmp//test_dir/<TAB>`   <-- note extra /

### Expected behavior

It should suggest `test_file`. This works without oh-my-zsh enabled.

### OS / Linux distribution

Rocky Linux 8.7

### Zsh version

5.8.1

### Terminal emulator

alacritty

### If using WSL on Windows, which version of WSL

None

**Comment by rwmitchell** [comment]
The double / is not redundant, it is being auto-expanded into /tmp/*/test_dir
Or at least that is what it does on my system.

**Comment by carlosala** [comment]
@awoodx if you want to have that behaviour, you can add `zstyle ':completion:*' squeeze-slashes true` in your `zshrc.
