### ISSUE TITLE
libiconv icons not working with nix

### ISSUE THREAD

**Issue by ckt114** [ohmyzsh/ohmyzsh#11622]
### Describe the bug

In [nix](https://nixos.org/); when using any omz plugin such as `kube-ps1` that leverages libiconv like `\u2388` the plugin will throw error similar to error below. When running `which iconv` it returns the path to `iconv` like `/nix/store/ymqb5nah99qb21pv0x5nmhfrqnhsgdqv-libiconv-50/bin/iconv` but the error still persists. The error still occurs even when `KUBE_PS1_SYMBOL_ENABLE` is set to `false`.

`/Users/jdoe/.oh-my-zsh/plugins/kube-ps1/kube-ps1.plugin.zsh:27: cannot do charset conversion (iconv not available)`

### Steps to reproduce

1. [Install nix](https://nixos.org/download.html)
2. Copy content below and save as `~/shell.nix`
3. Enable `kube-ps1` in omz `plugins` variable
4. Run `nix-shell --command zsh`

_~/shell.nix_
```
{ pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/fda0d99c2cbbb5c89d8855d258cb0821bd9113ad.tar.gz") {} }:

pkgs.mkShell {
  packages = with pkgs; [
    curl
    git
    less
    libiconv
    locale
    more
    ps
    wget
    which
    zsh
  ];
}
```

### Expected behavior

The icon should work or not throw above error.

### OS / Linux distribution

Any

### Zsh version

5.9

### Terminal emulator

Any

### If using WSL on Windows, which version of WSL

None

### Additional context

When replaced the escaped icons with real terminal icons like on nerdfonts.com the error goes away.

**Comment by carlosala** [comment]
I am not familiar at all with Nix. If you think there's a solution for it, feel free to open a PR :)

**Comment by carlosala** [comment]
It doesn't seem like a good solution actually
