### ISSUE TITLE
add alias-finder option for ONLY_SHORTER

### ISSUE THREAD

**Issue by roeniss** [ohmyzsh/ohmyzsh#11624]
### If the feature request is for a plugin or theme, specify it here.

alias-finder

### Describe the proposed feature.

I believe that the main purpose of `alias-finder` is to find shorter command, not all aliases.

```sh
> alias AAAAAA=echo
> echo 1
AAAAAA=echo          << I think this is not good suggestion and should be skipped to show
1

>
```

Here's two ideas:
1. When there's `OH_MY_ZSH_ALIAS_FINDER_ONLY_SHORTER=true` env, show only shorter aliases.
2. Change the original behavior and show longer aliases when there's `OH_MY_ZSH_ALIAS_FINDER_INCLUDE_LONGER=true` env.

```[tasklist]
### Tasks
```

**Comment by carlosala** [comment]
Hi @roeniss! I think it's a great improvement, feel free to open a PR! Even though, I think it's better to use `zstyle` to customize omz behaviour, you can have a look, for example, at `nvm` plugin to see how to do it.
Thanks for the idea, I'll be happy to review it!

**Comment by roeniss** [comment]
Hi @carlosala! Thank you for suggesting `zstyle` with `nvm`. It really helps me think better

It turned out that it has a bug. `alias-finder` already has [`-l`](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/alias-finder/README.md#options) flag which can turn on "showing longer alias", **but it seems broken.**

> Use --longer or -l to allow the aliases to be longer than the input (match aliases if they contain the input).

```sh
$ alias AAAAAAAAAA="echo a"
$ alias-finder "echo a" # [1]
AAAAAAAAAA='echo a'
$ alias-finder -l "echo a" # [2]
AAAAAAAAAA='echo a'
```

According to README, [1] must not be shown.

**Comment by mcornella** [comment]
I'd like to take this, the plugin is in need of a big rewrite. I'll work on it this weekend.

**Comment by mcornella** [comment]
Ok, the -l argument is not actually for that but to show aliases even if the alias value is longer than the command (i.e. if the command is in the start of the alias value but is not the full thing).

Here's an example of how it would apply:

![IMG_20230421_194438.jpg](https://user-images.githubusercontent.com/1441704/233701470-5b59b96e-ddf1-4302-a957-3f87f30846ee.jpg)

So there is no bug here, but I also agree that what you're asking is sensible, so I'll still work on adding the parameter (I think moving to zstyle is a great idea Carlo).

**Comment by roeniss** [comment]
@mcornella if you don't mind, may I try on this issue?

If you allow it, I think these are the tasks:
- convert parameter into `zstyle` form
- add a parameter for ONLY_SHORTER
- polish the codebase a little (not sure)

**Comment by mcornella** [comment]
That would be great yeah! Ideally I'd love for the plugin to use pure zsh constructs so that we don't make so many forks. 

This would require using the `$aliases` associative array, and zsh parameter expansion. Let me know if you have any doubts about this or need guidance on particular coding problems.

Thank you for taking up this issue!

**Comment by roeniss** [comment]
Not urgent, but for personal tracking -- would you assign this to me, please?
