### ISSUE TITLE
Feature: Option to always show changelog on update

### ISSUE THREAD

**Issue by GuySartorelli** [ohmyzsh/ohmyzsh#11638]
### If the feature solves a problem you have, specify it here.

[This recent commit](https://github.com/ohmyzsh/ohmyzsh/commit/029a6d2de8681d52142129eb8b6ff0f20be9f0a6) fixed the `interactive` option for the `update` command - but it also made it so that when I update I can't just automagically get the changelog displayed unless I actively remember to use the interactive option. And lets face it, I'm never going to remember that :p

### Describe the proposed feature.

A new option to implicitly use interactive mode when I run the `update` command, so I don't have to remember to use the interactive mode explicitly

Something like `zstyle ':omz:update' interactive true` (and `zstyle ':omz:update' interactive false` to require explicitly setting it, which will remain the default)

### Describe alternatives you've considered

I could just create a local alias for my own setup, if you don't want this as a built-in feature.... but I feel like other people will have gotten used to seeing the changelog automatically when using `update` so it may be desirable by more than just me to have this as a feature.

**Comment by GuySartorelli** [comment]
I'll very happily implement this and submit a PR - just want some feedback as to whether it's something that has a good chance of being merged before I go ahead and do that.

**Comment by carlosala** [comment]
When would you like to show the changelog (taking into account that interactive is not true).
There are a lot of color codes and this kind of stuff, so redirecting the output to check it later would probably not work as expected, when opening the file with an editor.
Could you provide more info on the exact workflow in which you miss the changelog?
Thanks!

**Comment by GuySartorelli** [comment]
Basically, I never knew that the changelog appearing every time I run `omz update` was a bug. I got very used to seeing the changelog whenever I update without having to add an extra option or run the changelog command separately. I would like a way to have the changelog appear _as though I'd run it with `-i`_ without having to run it with `-i`.

My ideal solution would be a setting (like the `zstyle ':omz:update' interactive true` in the issue description) which, when set, means the `update` command runs as though `-i` is used even when it isn't used.
i.e. when the setting is true, `omz update` and `omz update -i` are identical.

Does that make sense?

**Comment by GuySartorelli** [comment]
It doesn't, but that's fine, I'll make an alias. It sounds like I've misunderstood the "interactive" option's purpose somehow. Though I must say that it doesn't seem to be automatically set. 

Regardless, I'll close this and do a one-off solution for my own uses.

**Comment by mcornella** [comment]
If you are running the `upgrade.sh` script directly, then you need to pass in the `--interactive` flag. This has been in place for 2 years and only recently it might have changed due to the typo you mentioned.

`omz update` has always been automatically setting the flag though, as Carlo explained.

**Comment by GuySartorelli** [comment]
> `omz update` has always been automatically setting the flag though, as Carlo explained.

That certainly didn't happen on my last update, which is what prompted this. But nevermind.
