### ISSUE TITLE
Blue triangle / artifact rendered after every `cd`

### ISSUE THREAD

**Issue by rri** [ohmyzsh/ohmyzsh#11637]
### Describe the bug

I am running Oh My Zsh (latest version: commit 5d3e86e2a48adf7a308773f8f1b725d187c7c5ef) on iTerm2.

I am seeing a bug / change in behavior only when I run `tmux`. Each time I execute `cd <dir>` I see an arrow-like character (a blue triangle) just before the prompt. The screenshot attached (`Screenshot 1`) shows this with an annotation. This artifact doesn't show up unless I'm running `tmux`. It also disappears when I detach and re-attach the same session, as you can see in `Screenshot 2` attached (but changing to another directory now again shows me the artifact on the next prompt).

I was able to test out different commits in Oh My Zsh to determine that the difference in behavior is caused by commit 25c2c3a4683be60c3526858be960ee6ce1249245 (*feat(lib): send OSC 7 on directory change for more supported terminals (#9914)*). Specifically, the following line in `lib/termsupport.zsh` seems to be the ostensible culprit, as commenting it out fixes the issue:

```
add-zsh-hook precmd omz_termsupport_cwd
```

It's not obvious to me whether this is a bug in Oh My Zsh, or caused by some specific configuration in `tmux` not playing well with the change (I use Oh my tmux!, which configures most of tmux for me).

### Steps to reproduce

1. Open iTerm2.
2. Run `tmux` with a new session, or attach to an existing session.
3. Change to a directory that isn't the current one.
4. Immediately after the change is successful, notice the character rendered before the next prompt.

### Expected behavior

Nothing surprising should be seen on Step 4 above.

### Screenshots and recordings

The "blue triangle" in the first screenshot is the bug. I shouldn't be seeing these at all.
<img width="1440" alt="Screenshot 1" src="https://user-images.githubusercontent.com/2095422/233856578-2f1e9ef0-921a-4d5a-892c-4d9f4dc81170.png">

This second screenshot shows the same terminal as above after I detached and re-attached the tmux session. The previously rendered "blue triangle"s have disappeared now. But if I change to another directory, it'll show up again before the subsequent prompt.
<img width="1440" alt="Screenshot 2" src="https://user-images.githubusercontent.com/2095422/233856588-69edb759-6827-4749-b7b9-97d2f1ada97f.png">

### OS / Linux distribution

macOS

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

### Additional context

* tmux 3.3a
* [Oh my tmux!](https://github.com/gpakosz/.tmux) (Apr 12 2022, latest version)

**Comment by rwmitchell** [comment]
It is neither an issue with zsh or omz, nor is it a bug.  It IS a feature in iterm2 as a part of shell integration.  It marks each prompt and allows you to use keyboard control to jump back to each prompt.  You can also create triggers that will add the blue triangle during any output.

**Comment by rri** [comment]
I see, thank you. Searching for "iTerm2 shell integration" helped me learn more about this iTerm2 feature, which I wasn't aware of. Closing this issue.

**Comment by kllmanu** [comment]
@rri Could you pls tell me how you got rid of them? I've them too and I don't like those blue triangles.
