### ISSUE TITLE
[oh-my-zsh] fzf plugin: Cannot find fzf installation directory.

### ISSUE THREAD

**Issue by matusaurio** [ohmyzsh/ohmyzsh#11639]
### Describe the bug

I started to get this error message a couple of weeks ago
```
[oh-my-zsh] fzf plugin: Cannot find fzf installation directory.
Please add `export FZF_BASE=/path/to/fzf/install/dir` to your .zshrc
```
I saw this was an issue in the past (#8001) and it was solved, but now it's happening again (at least to me).

### Steps to reproduce

1. Open a terminal with oh-my-zsh enabled.
or
2. Run `omz reload`

### Expected behavior

Clean output

### OS / Linux distribution

Ubuntu 22.04.2 LTS

### Zsh version

5.8.1

### Oh My Zsh version

master (5d3e86e)

### Terminal emulator

Alacritty, Gnome Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by rwmitchell** [comment]
Have you installed fzf? The plugin uses fzf and requires it to already be installed.

**Comment by matusaurio** [comment]
Yes of course, fzf is installed, and the export is on my .zshrc

**Comment by carlosala** [comment]
Could you share your `zshrc`, so we can see what's going on? Thanks!

**Comment by matusaurio** [comment]
```
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  bgnotify
  colorize
  cp
  docker
  extract
  fzf
  git
  golang
  helm
  kubectl
  kubetail
  pip
  python
  rsync
  safe-paste
  sudo
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-history-substring-search
)

# Plugins configuration
# docker
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes
# zsh-completion
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src

# User configuration
export JAVA_HOME='~/.jdks/openjdk-19.0.2'
export FZF_BASE='/usr/bin/fzf'
export FZF_DEFAULT_COMMAND='fd --type f'
export PATH=$PATH:/usr/local/go/bin

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

**Comment by carlosala** [comment]
Actually, your `FZF_BASE` is not right. Normally, if your `fzf` binary is at `/usr/bin/fzf` then your `FZF_BASE` will be `/usr/share/fzf`. I'd recommend to remove `FZF_BASE` and let plugin discover it. You can check the plugin docs to see what's going on https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/fzf

**Comment by carlosala** [comment]
Feel free to reopen if you still have issues :)

**Comment by yowainwright** [comment]
I just started having the same issue as @matusaurio fwiw.

**Comment by carlosala** [comment]
@yowainwright What do you get when executing `brew --prefix fzf`?

**Comment by yowainwright** [comment]
🫠 Thanks, @carlosala!

As instructed, I ran `brew --prefix fzf` which printed `/opt/homebrew/opt/fzf`.

I then added `FZF_BASE="/opt/homebrew/opt/fzf"` to my `.zshrc` and there is no more warning. 👍 🙏

**Comment by yowainwright** [comment]
@carlosala that's how I had it previously. 

I unset it just now again and I see the warning again.

```sh
[oh-my-zsh] fzf plugin: Cannot find fzf installation directory.
Please add `export FZF_BASE=/path/to/fzf/install/dir` to your .zshrc
```

**Comment by carlosala** [comment]
@yowainwright that's really weird, and it should not happen. Could I get tracing from your startup? Executing `zsh -xvic exit &>~/omz-debug.log` would do the trick. Please send that file to logs@ohmyz.sh.
Thanks!

**Comment by yowainwright** [comment]
@carlosala can I send some specific part of my logs? 🙏

**Comment by carlosala** [comment]
@yowainwright sure! The ones relevant to omz, or even only the initialisation of fzf plugin.

**Comment by charafau** [comment]
I know the issue is closed but I had the same problem and applied every solution provided here with no success. Finally I've found the right config. 
The key is to export `FZF_BASE`  *before* plugins section. Like this:

```
export FZF_BASE="/opt/homebrew/opt/fzf"
plugins=(... fzf)
```

hope it helpts

**Comment by carlosala** [comment]
Indeed! All `omz` settings typically go before sourcing `oh-my-zsh.sh`. In this case, this is the case! It's not important if it goes before the plugins array; it's important to appear before sourcing `oh-my-zsh.sh`. I saw that it's explained in `fzf` plugin [README](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/fzf#settings)!

**Comment by logoff** [comment]
Revamping this issue!

Homebrew can have a different installation folder. So, in the file `~/.zshrc`, before sourcing `oh-my-zsh.sh`, you need to initialize Homebrew, and the folder of `fzf` will be discovered, not needing to set `FZF_BASE`.

So, file `~/.zshrc`:

```zsh
...
plugins=(
  ...
  fzf
  ...
)

# Homebrew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fpath=($HOMEBREW_PREFIX/share/zsh/site-functions $fpath)

source $ZSH/oh-my-zsh.sh
...
```

Hope it helps!
