### ISSUE TITLE
why web-search not working on ipad M2

### ISSUE THREAD

**Issue by EdwardWong1994** [ohmyzsh/ohmyzsh#11640]
### Describe the bug

Why the plugin web-search not working on ipad M2. when i type `web_search google ***` , it did not give me errors and no webpage pop up.

This plugin can work on my mac except on my ipad

### Steps to reproduce

1.  first, put `web-search` into `plugin` in`~/.zshrc`
2. then `source ~/.zshrc`

 In the terminal, type `web_search google oh_my_zsh`, no response

### Expected behavior

I expect the webpage will pop up

### OS / Linux distribution

Apline Linux

### Zsh version

5.8.1

### Terminal emulator

ish

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
It is not possible to open external apps from within ish it seems: https://github.com/ish-app/ish/issues/1289.

Feel free to reopen if you find otherwise (for example you could try asking in that project).
