### ISSUE TITLE
Inconsistent `ls` alias, new window vs. omz reload; overwrites `alias ls='gls --color=tty'` only on reload

### ISSUE THREAD

**Issue by hwknsj** [ohmyzsh/ohmyzsh#11647]
### Describe the bug

relevant info:

- os: macOS `13.3.1`
- arch: `arm64`
- terminal application: iTerm2 3.5.0beta10
- shell: zsh 5.9, `/bin/zsh` (macOS built-in version)
- special config: using ["typewritten"](https://typewritten.dev) theme
- plugins: occurs with or without any plugins

---

Opening a new window vs. using `omz reload` (or entering the debug session with `zsh -xv 2> >(tee ~/omz-debug.log &>/dev/null)`, for that matter) creates inconsistent `ls` alias:

**new terminal window/tab**
```sh
> type -a ls
ls is an alias for ls -G
ls is /bin/ls
```

**after `omz reload`, `zsh`, `tmux` etc.**
```sh
> type -a ls
ls is an alias for gls --color=tty
ls is /bin/ls
```

this is problematic (at least on macOS) since there are several `ls` flags (such as `ls -@` which shows extended attributes) that result in error with `gls`.

I'm pretty sure the culprit is in [`lib/theme-and-appearance`,  lines 48-57](https://github.com/ohmyzsh/ohmyzsh/blob/5d3e86e2a48adf7a308773f8f1b725d187c7c5ef/lib/theme-and-appearance.zsh#L48-L57):
```sh
  (darwin|freebsd)*)
    # This alias works by default just using $LSCOLORS
    test-ls-args ls -G && alias ls='ls -G'
    # Only use GNU ls if installed and there are user defaults for $LS_COLORS,
    # as the default coloring scheme is not very pretty
    [[ -n "$LS_COLORS" || -f "$HOME/.dircolors" ]] \
      && test-ls-args gls --color \
      && alias ls='gls --color=tty'
    ;;
  *)
```

NOTE: this does **not** occur when `DISABLE_LS_COLORS="true"`

why does this seem to run after invoking `zsh` but _not_ when `zsh` is initialized for a new window/tab?
it would be cool if there were a flag to turn off overwriting of builtin commands with coreutils variants _but still be able to have nice LS\_COLORS_

### Steps to reproduce

1. open a new terminal
2. run `which ls` or `type -a ls` or whatever
3. note the result
4. run any of the following: `omz reload`, `exec zsh`, `zsh`, `tmux`, `asciinema`
5. note that now `ls is an alias for gls --color=tty`

### Expected behavior

either `type -a ls` should be consistent with new window / omz reload OR ideally `gls` wouldn't be used by default on macOS for the reason that `gls` is missing some features unique to the macOS implementation (e.g. `-@`)

### Screenshots and recordings

unfortunately, it's impossible to reproduce this using `asciinema` because it runs a new `zsh` instance and so the `gls` alias is already used. here is a regular-ass video

https://user-images.githubusercontent.com/8978069/234725142-bef44c40-cf09-4a36-8a58-a14d8f778ed8.mp4

### workaround

manually set in `.zshrc` before `source ${OMZ}/oh-my-zsh.sh` (`LS_COLORS` might be different on your system)
```sh
export LS_COLORS="di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
alias ls='ls -G'
DISABLE_LS_COLORS="true"
```

### OS / Linux distribution

macOS 13.3.1

### Zsh version

5.9

### Oh My Zsh version

master (5d3e86e)

### Terminal emulator

iTerm2 3.5.0beta10

### If using WSL on Windows, which version of WSL

None

### Additional context

using theme `typewritten` but doesn't seem to interfere.

**Comment by carlosala** [comment]
Totally reproducible, `LS_COLORS` is set up after that alias, that's why the second time you run the file it changes the alias.

**Comment by carlosala** [comment]
@mcornella what do you think if we remove the alias for `gls`? There's already a plugin `gnu-utils` if someone wants that.

**Comment by hwknsj** [comment]
@carlosala i think that's a great call. as you said, there's the `gnu-utils` plugin that does this _and_ on macOS, homebrew provides instructions on how to link the `coreutils` binaries (such as `gls`, `god`, `g*`etc.) if you really want to overwrite the built-in ones.

i could see maybe this makes sense on a `freebsd` system, but on `macOS` it is a hindrance. i don't think `gls` provides any additional features or benefit that the native `ls` doesn't already have, on the contrary, in fact.

**Comment by carlosala** [comment]
@hwknsj what do you think if the default behaviour is to use gnu-ls? I think if someone installed gnu-ls is because they really want to use it.
I was thinking on a zstyle setting. Could you try #11647 and tell me your thoughts!

**Comment by carlosala** [comment]
Yeh, it's what we have now. Just the addition of being able to not use gnu one (the default is to use gls)

**Comment by hwknsj** [comment]
> @hwknsj what do you think if the default behaviour is to use gnu-ls? I think if someone installed gnu-ls is because they really want to use it. I was thinking on a zstyle setting. Could you try #11647 and tell me your thoughts!

@carlosala I took [your branch (PR 11661)](https://github.com/ohmyzsh/ohmyzsh/pull/11661) for a spin and it works great using the `zstyle ':omz:lib:theme-and-appearance' gnu-ls no` setting!

I noticed that[ this commit not overwriting aliases](https://github.com/ohmyzsh/ohmyzsh/commit/b22593c) was included in the updates today–I'm wondering if that achieves the same thing? (but maybe only in the case that `ls` has been `aliased` 🤔 ... ?)

re: default setting `gnu-ls`–i don't know if i can answer that for anyone but myself. the way i encountered this was because i am using `macOS` and have `coreutils` installed via `homebrew` which includes `gls` etc. but i definitely _don't_ want to use `gls`, really ever. maybe others have a compelling reason to use that versus the macOS native version, but I would think that if they did, they would probably create the alias themselves (e.g. `alias ls='gls'`), right?

for the average user (and myself) on macOS it can really only cause mysterious issues like this one. that's probably why `homebrew` _does not_ automatically link all the gnu-utils by default (which would overwrite native versions) and prefixes `g*` to all of them–but, upon installation of `coreutils`, it provides instructions to link the non-g versions if one wishes.

thank you for giving this issue so much attention! i realize there are a million other open issues and your time is valuable!

**Comment by carlosala** [comment]
Commonly people that installs `coreutils` like to use gnu ls. If it works, let's merge it. Thanks for your contribution and help!

**Comment by carlosala** [comment]
@javasgl that was a regression introduced in the last commit. Running `omz update` should solve it.
@hwknsj to prevent this kind of regressions, now the default thing is to use BSD `ls`, so omz out of the box should work for you!

**Comment by javasgl** [comment]
@carlosala thx, Now it's normal after `omz update`, it won't clash with my own `gls` alias anymore

**Comment by hwknsj** [comment]
sounds like we all win! :-> thanks @carlosala !On May 9, 2023, at 7:14 PM, javasgl ***@***.***> wrote:﻿
@carlosala thx, Now it's normal after omz update, it won't clash with my own gls alias anymore
