### ISSUE TITLE
Add lazyshell as plugin

### ISSUE THREAD

**Issue by silvermind** [ohmyzsh/ohmyzsh#11643]
### If the feature request is for a plugin or theme, specify it here.

ChatGPT Plugin

### If the feature solves a problem you have, specify it here.

[lazyshell](https://github.com/not-poma/lazyshell) basically queries ChatGPT for commands. It is an insanely good command lookup tool. Think of all the silly little commands you muck up (find!!!!! I always forget find syntax. Or JSON parsing using jq!). It has some really neat features, such as being able to include the existing command into your ChatGPT query.

https://blog.billyc.io/chatgpt-and-zsh-how-i-learned-to-stop-worrying-and-love-the-ai/

### Describe the proposed feature.

allow to use lazyshell easily as ohmyzsh plugin

### Describe alternatives you've considered

tried to install it manually but no success, due to new to ohmyzsh :)

**Comment by carlosala** [comment]
Being a plugin that queries a service which is not controlled by us, and it's quite new, I'd for the moment postpone this and recommend anyone that uses it as a custom plugin, which is super easy to set up.
Thanks for the suggestion!
