### ISSUE TITLE
Extract plugin fails on compressed files that are not an archive (caused by #11596)

### ISSUE THREAD

**Issue by hwalinga** [ohmyzsh/ohmyzsh#11642]
### Describe the bug

When you have a compressed file you can decompress it with `extract` from the extract.plugin. However, with #11596 it creates a folder and then fails to extract the file, because there already is a folder with the same name. 

### Steps to reproduce

```sh
touch file
gzip file
extract file.gz
```

Errors:

```
/home/hielke/tmp/extract/file exists -- overwrite (y/n)? y
pigz: abort: write error on /home/hielke/tmp/extract/file (Is a directory)
gzip: /home/hielke/tmp/extract/file already exists; do you wish to overwrite (y or n)? y
gzip: /home/hielke/tmp/extract/file: Is a directory
```

### Expected behavior

The file and archive should just be extracted as is. I consider #11596 to be a bug, not a feature and would like that behavior to be reverted. 

### OS / Linux distribution

Debian 11

### Zsh version

5.8

### Oh My Zsh version

master (5d3e86e2)

### Terminal emulator

urxvt

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Implemented a fix in #11702. Please test it out with `omz pr test 11702`.

**Comment by hwalinga** [comment]
This does not fix the bug. This is because you test if a file with the directory name already exist, but you must test if the archive does not contain a file with the same name as the archive. (Which is the case of `gzip file`.

You might have been confused by the working of gzip, but it replaces the file by the archive. The file will not exist then in the directory. 

Preferably you just remove this feature as it introduces bugs and it is better if it was kept simple.

```sh
touch file
gzip file
ls
> file.gz
extract file.gz
> extract: extracting to file
> /home/hielke/tmp/extract/file exists -- overwrite (y/n)? y
> pigz: abort: write error on /home/hielke/tmp/extract/file (Is a directory)
> gzip: /home/hielke/tmp/extract/file already exists; do you wish to overwrite (y or n)? y
> gzip: /home/hielke/tmp/extract/file: Is a directory
```

**Comment by tw19941212** [comment]
Encountered the same bug，how did you solve it? @hwalinga

**Comment by hwalinga** [comment]
Hello @mcornella again, 

[c4d1ea4](https://github.com/nbaronov/oh-my-zsh/commit/c4d1ea4cb5460ed4fdce211f25348858406dfb79) also does not fix this bug. The problem is that _inside_ the archive there is a file that is equal to the name of the archive. `[[ -e "$extract_dir" ]]` does not check that, because it is a file _inside_ the archive, **not** inside the current directory.

And please just like actually test if your code changes work against the bug report, not just assume. 

```
touch file
gzip file
ls
> file.gz
extract file.gz
> extract: extracting to file
> /home/hielke/tmp/extract/file exists -- overwrite (y/n)? y
> pigz: abort: write error on /home/hielke/tmp/extract/file (Is a directory)
> gzip: /home/hielke/tmp/extract/file already exists; do you wish to overwrite (y or n)? y
> gzip: /home/hielke/tmp/extract/file: Is a directory
```

You can see that your added `echo` statement now, and it does not add the random string, because `file` does not exist in the directory, but _inside_ the archive.

**Comment by mcornella** [comment]
Sorry for the delay Hielke, I have not had much time to work on Oh My Zsh lately. Can you check if #11852 solves this with `omz pr test 11852`?
