### ISSUE TITLE
--mkdir flag for command "cd"

### ISSUE THREAD

**Issue by SX-9** [ohmyzsh/ohmyzsh#11655]
### If the feature solves a problem you have, specify it here.

im always creating new projects in my `Projects` dir and every time i start a new project ill have to do `mkdir Projects/NAME` then `cd Projects/NAME`, but thats a lot of typing ya know so why not make a flag to the existing cd command! also checked and this is a built-in shell command so you can modify this.

### Describe the proposed feature.

when we do `cd path/to/dir` with `--mkdir` flag then create the directory if it doesnt exists and cd into it, if it does exists then just cd in!

### Describe alternatives you've considered

making a bash script to do this for me

**Comment by rwmitchell** [comment]
OMZ has a mkcd alias for that

**Comment by SX-9** [comment]
> OMZ has a mkcd alias for that

oh i dint know about this command, ill close the issue then!
