### ISSUE TITLE
Apple theme broken with latest update

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [ohmyzsh/ohmyzsh#11662]
### Describe the bug

The little Apple logo in the Apple theme is broken in my Terminal.app (as well as the VSCode inline terminal) as of the latest update. Looking at the commit, the old `echo` works whereas the newer one doesn't.
![Screenshot 2023-05-02 at 12 11 30](https://user-images.githubusercontent.com/80696589/235650813-2e3300ad-4d15-47ac-a0ce-b4c8f8f71474.png)

![Screenshot 2023-05-02 at 12 12 26](https://user-images.githubusercontent.com/80696589/235650983-49c6a905-5c9e-44ce-bca4-8e8b6ee5cf9b.png)

This might be something that has changed since my older version of macOS but it's still a tad annoying.

### Steps to reproduce

Enable the Apple theme and look at the prompt. A `[?]` character is there in place of the Apple logo ``.

### Expected behavior

The Apple logo appears in the prompt.

### OS / Linux distribution

macOS 10.15.7

### Zsh version

5.7.1

### Oh My Zsh version

master (dab09cc)

### Terminal emulator

Terminal.app, VSCode inline

### If using WSL on Windows, which version of WSL

None

**Comment by rwmitchell** [comment]
Nerd Font updated the fonts on 04/30, making the old apple glyph obsolete. It’s been coming for a few months. Carlos was on it!  Blame the orig nerd font people 😛

**Comment by carlosala** [comment]
@Th3T3chn0G1t thanks for the report. Richard is, indeed, right. Nerd Fonts did a breaking release two days ago. To solve it and continue having same theme, I do recommend to you updating your font to its latest patched version, you'll find more info here. https://github.com/ryanoasis/nerd-fonts/

**Comment by rwmitchell** [comment]
The new apple glyph wasn’t in the previous “new” fonts that had both new and now obsolete glyphs.

**Comment by carlosala** [comment]
@Th3T3chn0G1t just for understanding, before the update, which was the icon shown there?

**Comment by Th3T3chn0G1t** [comment]
@carlosala the Apple symbol was correctly shown - from what I can tell the same one as shows up with `Shift + Alt + K`

**Comment by carlosala** [comment]
which font do you have enabled in your terminal?

**Comment by carlosala** [comment]
@Th3T3chn0G1t found that I misunderstood that icon. Commit reverted, more info in 85fdbfe21692a3fa7bdd7bc509163e23fb385279
