### ISSUE TITLE
apple.zsh-theme, broken apple () sign MacOS

### ISSUE THREAD

**Issue by cybernester** [ohmyzsh/ohmyzsh#11665]
### Describe the bug

in the latest version of apple.zsh-theme, the "deprecated" apple logo was replaced, and it doesn’t seem to show up properly. 

### Steps to reproduce

On my Mac it looks like so:
<img width="50" alt="image" src="https://user-images.githubusercontent.com/123403376/235865271-98fa1c95-3e19-4994-bcf8-a2e321b25f52.png">
Even when inspected on GitHub, there seems to be an issue:
![image](https://user-images.githubusercontent.com/123403376/235865014-b0c17d44-d284-401c-ba20-0c6e7a6f82f7.png)

### Expected behavior

Changing the code by using the Option+Shift+K shortcut to type the  logo fixes the issue for me:
<img width="136" alt="image" src="https://user-images.githubusercontent.com/123403376/235866345-c0bcc7ea-14db-4c7f-831d-3ee6629747b3.png">

### OS / Linux distribution

macOS 13.3.1 (a)

### Zsh version

5.9

### Oh My Zsh version

master (dab09cc)

### Terminal emulator

Default macOS Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by rwmitchell** [comment]
Did you even look for a similar issue?

#11662

**Comment by cybernester** [comment]
@carlosala Thank you and apologies for the duplicate
