### ISSUE TITLE
omz udate not working

### ISSUE THREAD

**Issue by dheerajchand** [ohmyzsh/ohmyzsh#11664]
### Describe the bug

I'm a big fan ! `omz update` is failing for me on MacOS. It's not clear why, but this is also after getting merge conflict notifications.  When I issue, `omz update`, I get the help instead.

Can someone assist?

<img width="815" alt="Screenshot 2023-05-02 at 10 54 21 AM" src="https://user-images.githubusercontent.com/482844/235720066-86d61724-c79d-4be3-83d5-18dd93504d58.png">

### Steps to reproduce

1. Open iTerm2 
2. `omz update`

### Expected behavior

I expect it to update, but but 

### OS / Linux distribution

MacOS

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by rwmitchell** [comment]
Move $ZSH to a backup name. 
Use git to get a fresh clone.
After that works, compare the two for any changes you’ve made. If any, they should be made somewhere else.

**Comment by carlosala** [comment]
@fabgat seems that something happened to your oh-my-zsh git clone. Could you try removing the directory, and recloning it?
Let's close this, feel free to comment if it doesn't solve it for you.
