### ISSUE TITLE
parse error near `)' after adding aliases to ~/.zshrc

### ISSUE THREAD

**Issue by LarryChiem** [ohmyzsh/ohmyzsh#11672]
https://www.engineeringwithutsav.com/articles/spice-up-your-macos-terminal
Following these instructions to install ohmyzsh and etc, when I begin adding aliases, then run `source ~/.zshrc` I get an error 

/Users/lchiem/.oh-my-zsh/oh-my-zsh.sh:21: parse error near `)'

**Comment by rwmitchell** [comment]
So what are on lines 19 thru 23?

**Comment by carlosala** [comment]
Check if your `zshrc` syntax is correct. Feel free to reopen if you have more issues!
