### ISSUE TITLE
virtualenvwrapper plugin: readlink: illegal option -- f

### ISSUE THREAD

**Issue by mbrochh** [ohmyzsh/ohmyzsh#1167]
I have just updated oh/my/zsh (or better, it was smart enough to update itself, how cool is that) and activated that plugin.

It seems to work but whenever cd into a git repository, I get the following error:

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

I'm on OSX 10.7

It seems to be related to this line:
https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh#L16

`man readlink` gives me this:

```
SYNOPSIS
     stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file ...]
     readlink [-n] [file ...]
```

So as it seems, -r really is not a valid flag...

Any ideas whats wrong here? Is i OSX again being a bitch?

**Comment by benlieb** [comment]
I was unable to copy / delete from /usr/bin (not permitted), but copying to `local` worked:

`ln -s /usr/local/bin/greadlink /usr/local/bin/readlink`

**Comment by mcornella** [comment]
The virtualenvwrapper plugin no longer relies on `readlink`, so there's no need to do that.
