### ISSUE TITLE
List available commands for wp-cli plugin

### ISSUE THREAD

**Issue by jordantrizz** [ohmyzsh/ohmyzsh#11679]
### If the feature request is for a plugin or theme, specify it here.

wp-cli

### If the feature solves a problem you have, specify it here.

Don't know all the commands available.

### Describe the proposed feature.

Create wpc alias or function that lists all available commands :)

### Describe alternatives you've considered

None.

**Comment by carlosala** [comment]
Hi! Your best option is to define yourself your own alias for that. You can use tab completion to understand better wp-cli, and to see all the aliases, you could use the following alias that will make the trick!

```zsh
alias wpc="alias | grep 'wp.*wp.*'"
```

**Comment by carlosala** [comment]
@jordantrizz I think it's too specific for an alias/function in oh my zsh. Also taking into account that we have `acs` function and you could just do `acs wp`.
Even though, thanks for the idea!
