### ISSUE TITLE
Better handling of ZSH in emulation mode

### ISSUE THREAD

**Issue by easyaspi314** [ohmyzsh/ohmyzsh#11686]
### If the feature solves a problem you have, specify it here.

ZSH has the ability to emulate bash/ksh/sh either by the `emulate` command or by argv[0] starting with sh, ksh, or bash. This causes omz to error constantly because the modules are not automatically loaded, the syntax is different, and various other issues.

When `oh-my-zsh.sh` is loaded with a non-ZSH shell, it gives a nice error message, but when zsh is in emulation mode and the script is manually loaded (since in emulation mode it won't load .zshrc) you get
```
$ exec -a bash zsh -l
$ . .oh-my-zsh/oh-my-zsh.sh
.oh-my-zsh/tools/check_for_upgrade.sh:13: command not found: zstyle
(anon):40: command not found: zstyle
compinit:141: parse error: condition expected: $1
_omz_source:10: command not found: zstyle
_omz_source:15: bad set of key/value pairs for associative array
```

### Describe the proposed feature.

A simple check for `[ "$(emulate)" = zsh ]` could give a nicer error message.

If it is detected when the script is loaded, it could say
```
Error: Oh My Zsh can't be loaded in emulation mode.
This can happen if the emulate command is run, or zsh is renamed to sh, bash, or ksh.
```

### Describe alternatives you've considered

Alternatively it could try to manually escape emulation mode, but that breaks other things.

**Comment by carlosala** [comment]
@easyaspi314 great catch! Feel free to submit a PR!

**Comment by denispavenko** [comment]
wery interesting

**Comment by toddjonker** [comment]
This would've saved me an hour of debugging today... I'm new to Zsh and OMZ, trying to integrate them with my existing shell-magic, and OMZ fails in really confusing ways.  Turns out my shell-magic is sourcing OMZ in emulation mode, which is easy-ish to fix but was very hard to diagnose.
