### ISSUE TITLE
robbyrussell multiline command messup when delete character in command

### ISSUE THREAD

**Issue by roodkcab** [ohmyzsh/ohmyzsh#11680]
### Describe the bug

![zsh](https://user-images.githubusercontent.com/1700820/236980575-06c02f94-a9dd-4280-8186-74abd937986e.gif)
the reason for this bug is PS1 got wrong with "
![image](https://user-images.githubusercontent.com/1700820/236980658-6ff04e62-233f-49a6-9704-3d230e4198e8.png)
as u can see the second part of PS1 messup
this can be easily fixed by put all %{} part into double quote
![zsh-fix](https://user-images.githubusercontent.com/1700820/236981183-62c1743b-2f8d-4992-9dd9-95ed7a5398d9.gif)
and PS1 looks like OK
![image](https://user-images.githubusercontent.com/1700820/236983624-73e73a7c-5672-48d7-bdc3-30818fd05a3a.png)

### Steps to reproduce

![zsh](https://user-images.githubusercontent.com/1700820/236980575-06c02f94-a9dd-4280-8186-74abd937986e.gif)

### Expected behavior

![zsh-fix](https://user-images.githubusercontent.com/1700820/236981183-62c1743b-2f8d-4992-9dd9-95ed7a5398d9.gif)

### OS / Linux distribution

Linux archlinux 6.1.27-1-lts #1 SMP PREEMPT_DYNAMIC Mon, 01 May 2023 18:18:27 +0000 x86_64 GNU/Linux

### Zsh version

5.9

### Terminal emulator

gnome terminal

### If using WSL on Windows, which version of WSL

None

**Comment by roodkcab** [comment]
related to https://github.com/ohmyzsh/ohmyzsh/issues/11389

**Comment by roodkcab** [comment]
related to https://github.com/ohmyzsh/ohmyzsh/issues/6606

**Comment by carlosala** [comment]
Hi @roodkcab! Good catch! Feel free to open a PR solving it and we'll review it!

**Comment by sebouh00** [comment]
I was having similar issues when I unchecked "Set local variables automatically" on iTerm2. This is under settings -> profile -> terminal -> environment.
