### ISSUE TITLE
web-search plugin is not working

### ISSUE THREAD

**Issue by kevingatp** [ohmyzsh/ohmyzsh#11694]
### Describe the bug

I'm trying to implement the [web-search](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/web-search/README.md) plugin. But it's not working at all.
<img width="563" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/20182181/6254c247-2fbe-479c-a2e0-68152834272d">

I've watched/read any sources and all of them show the exact usage steps in doc which only add `web-search` in config.

Here is my `.zshrc` file:
```
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jack/Codes/RnD/flutter/bin:$PATH
export PATH=/Users/jack/Library/Android/sdk:$PATH
export PATH=/Users/jack/Library/Android/sdk/tools:$PATH
export PATH=/Users/jack/Library/Android/sdk/platform-tools:$PATH

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
source /Users/jack/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme
source /Users/jack/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

ZSH_WEB_SEARCH_ENGINES=(google "https://www.google.com/search?q=")

plugins=(
web-search
zsh-autosuggestions
)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

unset ZLE_RPROMPT_INDENT
source /Users/jack/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

Wish anyone can help.

Thankyou in advance.

### Steps to reproduce

1. add `web-search` into `~/.zshrc` file,
2. exec `source ~/.zshrc`.
3. Try typing `google open github issues`.

### Expected behavior

Should redirect to browser.

### OS / Linux distribution

macOS Monterey

### Zsh version

5.8.1

### Terminal emulator

Mac Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by kevingatp** [comment]
Did you mean `/Users/jack/.oh-my-zsh`? but there's no any file named `oh-my-zsh.sh`. It's only containing `custom` directory.

**Comment by mcornella** [comment]
If that's so it doesn't look like you installed OMZ.

**Comment by kevingatp** [comment]
It's weird, I've install the OMZ. But I don't know why it's only containing `custom` folder.

**Comment by carlosala** [comment]
Probably you just installed p10k. Install ohmyzsh and you'll be good to go.Closing this, nice that we found the issue.
