### ISSUE TITLE
In one project the git status suddenly disappear

### ISSUE THREAD

**Issue by mdemori** [ohmyzsh/ohmyzsh#11699]
### Describe the bug

Hi,

In one single project, the git status don't appear anymore on any branch the prompt is always as you can see on screenshot.

![image](https://github.com/ohmyzsh/ohmyzsh/assets/2266315/1eb8613b-cb53-4114-b4bb-d63c1a292d7b)

### Steps to reproduce

I'm not able to reproduce the problem, happen only on one of my projects.. and I don't  have any clue to understand this problem..

### Expected behavior

current git status on prompt like below example:

![image](https://github.com/ohmyzsh/ohmyzsh/assets/2266315/5aea8ec2-2d65-4c83-9f2c-3b56a54d13d9)

### OS / Linux distribution

WSL2 On Windows 10 with Ubuntu 22.04.2 LTS Full updated

### Zsh version

5.8.1

### Terminal emulator

Windows Terminal

### If using WSL on Windows, which version of WSL

WSL2

### Additional context

Powerlevel10k Theme, git plugin installed

**Comment by carlosala** [comment]
This is something that is handled by p10k, please file the issue there.
