### ISSUE TITLE
pyclean function shadows pyclean executable(s)

### ISSUE THREAD

**Issue by bittner** [ohmyzsh/ohmyzsh#11704]
### Describe the bug

As reported in https://github.com/bittner/pyclean/issues/61 OMZ users may face irritating results from calling the `pyclean` command, e.g. after installing the `pyclean` Python package.

### Steps to reproduce

See https://github.com/bittner/pyclean/issues/61

### Expected behavior

OMZ might not declare a `pyclean` function and install/call the `pyclea` Python package instead.

### Screenshots and recordings

See https://github.com/bittner/pyclean/issues/61

### OS / Linux distribution

Ubuntu Linux 22.04.2 LTS

### Zsh version

(current latest)

### Oh My Zsh version

(current latest)

### Terminal emulator

GNOME Terminal, Bash

### If using WSL on Windows, which version of WSL

None

### Additional context

Related history of the OMZ pyclean implementation:
https://github.com/ohmyzsh/ohmyzsh/issues?q=pyclean

**Comment by carlosala** [comment]
Hi! I see that `pyclean` repo is not widely supported (<50 stars) which probably does not make an issue for a lot of people to have that alias. I wouldn't change the name of the alias at this point, even more taking into account that it seems to be used seeing that we had several issues for it.
Probably adding a note in install docs from `pyclean` would be great, to unalias omz one.
Thanks for the report!
