### ISSUE TITLE
rtx plugin

### ISSUE THREAD

**Issue by tenjaa** [ohmyzsh/ohmyzsh#11700]
### Describe the proposed feature.

I would love to see an official plugin for [rtx](https://github.com/jdxcode/rtx).

It is an alternative asdf written in rust.

**Comment by mcornella** [comment]
Looks great! Would you like to submit a PR?

**Comment by geckguy** [comment]
@mcornella can i work on this? Might need a little guidance but ill get the work done

**Comment by carlosala** [comment]
sure, feel free to submit a PR, we'll be happy to review it!

**Comment by sujalcodes3** [comment]
Is someone working on this or can I work on this issue ?
@carlosala

**Comment by Cioraz** [comment]
Hello, is this issue open? I would like to work on it 
@carlosala  @tenjaa

**Comment by tenjaa** [comment]
Go for it :)

**Comment by alienishi** [comment]
Hello @carlosala @tenjaa , is this issue still open ? I would like to work on it 
please assign it to me

**Comment by himanshuParashar0101** [comment]
okay we got it

**Comment by demonkillerr** [comment]
Submitted a PR, kindly have a look: #11932

**Comment by AlecRust** [comment]
Nice one for the plugin!

For me, [the new `rtx` plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/rtx) doesn't behave the same as the `eval "$(rtx activate zsh)"` I had in my `.zshrc` before, is this expected?

My installed Node version no longer displays in my Starship prompt, and commands like `npm` and `yarn` are no longer working. All the aforementioned things are loaded from OMZ:

https://github.com/AlecRust/dotfiles/blob/b3939525ea54dc397cb0c7223ba58979b7ccbc8e/dotfiles/.zsh_plugins.txt#L13-L14

**Before:**
![image](https://github.com/ohmyzsh/ohmyzsh/assets/247634/9a2ee421-3c52-4410-9146-538612b208b1)

**After:**
![image](https://github.com/ohmyzsh/ohmyzsh/assets/247634/2669c5fc-f437-4be3-91f3-526e4f9afd73)

**Comment by carlosala** [comment]
There's a PR fixing all the stuff #11949.
Closing this, it should be done!
