### ISSUE TITLE
Plugins link on https://ohmyz.sh/

### ISSUE THREAD

**Issue by kerolloz** [ohmyzsh/ohmyzsh#11716]
### Describe the bug

Clicking the `Plugins` link on the top of the https://ohmyz.sh/ website, it redirects to [https://github.com/ohmyzsh/ohmyzsh/wiki/**Themes**](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes) not [https://github.com/ohmyzsh/ohmyzsh/wiki/**Plugins**](https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins) 

### Steps to reproduce

1. go to ohmyz.sh
2. Click the `Plugins` Link 

### Expected behavior

Going to the Plugins page

**Comment by kerolloz** [comment]
I would love to fix it. Where shall I find the ohmyz.sh html page code?

**Comment by carlosala** [comment]
@robbyrussell could we get this fixed? Thanks🥰🥰

**Comment by robbyrussell** [comment]
Appreciate you catching and reporting this, @kerolloz!

This was a mistake I made recently when trying to make a few quick edits to the site. Eventually, I aim to make the website an open-source thing, but not been a top priority to sort out
