### ISSUE TITLE
Wrong cursor placement with `bureau` theme when inside git repository

### ISSUE THREAD

**Issue by sourproton** [ohmyzsh/ohmyzsh#11726]
### Describe the bug

When inside a git repository, the layout of the theme is off by 3 chars, putting the cursor before the `$` and misplacing the time.

See the comparison between a bug-less theme (`af-magic`) and `bureau` in the "screenshots" section below.

### Steps to reproduce

1. select `bureau` theme
2. cd to a git repository

### Expected behavior

Correct layout 

### Screenshots and recordings

`af-magic` with non-git repo:
![af-magic-non-git](https://github.com/ohmyzsh/ohmyzsh/assets/66533348/21c1aff0-6621-4a86-afbc-d9bd87984b00)

`af-magic` with git repo:
![af-magic-git](https://github.com/ohmyzsh/ohmyzsh/assets/66533348/2d4e5c21-54ec-499a-81e0-632ebd0b5c8f)

`bureau` with non-git repo:
![bureau-non-git](https://github.com/ohmyzsh/ohmyzsh/assets/66533348/b1c4bfcf-092a-4f90-8306-d962bfa086bc)

`bureau` with git repo:
![bureau-git](https://github.com/ohmyzsh/ohmyzsh/assets/66533348/48b53824-b46f-4574-bf47-aa00e9c12eb9)

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Oh My Zsh version

master (6101106)

### Terminal emulator

Alacritty

### If using WSL on Windows, which version of WSL

None

**Comment by rwmitchell** [comment]
had you either made a smaller terminal window or just grabbed a smaller screenshot, it would take so much scrolling back and forth to see what is actually relevant instead of all that empty space.

**Comment by sourproton** [comment]
Edited the issue. Will think about that next time.

**Comment by sourproton** [comment]
Additional info: I'm on KDE and the same happens inside Konsole.

**Comment by mcornella** [comment]
This is probably the same as https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-have-a-weird-character-in-my-prompt. Check that you have a UTF-8 locale.

**Comment by sourproton** [comment]
Well that is weird. I just installed arch on the machine so I'm sure I was using a UTF-8 locale. Either way, re-running `sudo locale-gen` and rebooting solved the problem. Thank you!
