### ISSUE TITLE
Type ahead broken when in screen session

### ISSUE THREAD

**Issue by c0d3m0nky** [ohmyzsh/ohmyzsh#11729]
### Describe the bug

When using screen while SSHed into my server the type ahead seems to be concatenating onto what I've already typed, although the shell itself still executes the correct command, ie if I type "exit" I end up with "eexxiexit" in my terminal, but it still exits

Screenshots as I type each character

e
![image](https://github.com/ohmyzsh/ohmyzsh/assets/4998029/b283d4ec-abad-4849-95b0-cb45b951c7f4)

x
![image](https://github.com/ohmyzsh/ohmyzsh/assets/4998029/148e9803-6d6d-470e-9d85-9f5f73bbed76)

i
![image](https://github.com/ohmyzsh/ohmyzsh/assets/4998029/02317107-1d42-4fc8-a37c-bc9885f9929b)

t
![image](https://github.com/ohmyzsh/ohmyzsh/assets/4998029/e15dd699-8af9-4f63-950f-31fbd52956ab)

This doesn't happen when I use screen locally and I have identical zsh setup on both my desktop and the server. I've tried with multiple terminal apps, including Unraid's web console; disabling zsh-autosuggestions; adding the screen plugin

I don't have this issue when using bash nor zsh with oh-my-zsh disabled

### Steps to reproduce

1. SSH into server
2. Enter zsh shell
3. run screen
4.Type command with history

### Expected behavior

Type ahead should behave in screen as it would under normal circumstances

### OS / Linux distribution

Unraid 6.11.5 / Slackware 15.0 x86_64 (post 15.0 -current)

### Zsh version

zsh 5.9 (x86_64-slackware-linux-gnu)

### Oh My Zsh version

master (ec369bb)

### Terminal emulator

Hyper.JS, Gnome Terminal, Konsole, Unraid Web Console

### If using WSL on Windows, which version of WSL

None

**Comment by c0d3m0nky** [comment]
Forgot to include my .zshrc contents, I don't think there's anything of note since I use a pretty bone stock setup, but it can't hurt

`ZSH_DISABLE_COMPFIX=true

export ZSH="/root/.oh-my-zsh"

ZSH_THEME="robbyrussell"

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=/root/.cache/zsh/history

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  screen
)

source $ZSH/oh-my-zsh.sh`

**Comment by mcornella** [comment]
Looks like a locale issue. Make sure you're using a UTF-8 locale: run `locale` (`locale -a` to know available ones).

**Comment by c0d3m0nky** [comment]
All the same locale in every context

# Local machine 
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

# Server in regular zsh session
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

# Server in screen session
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by leecha** [comment]
I also have this problem in a Mac OrdStack, like gif:

![Kapture 2023-06-12 at 10 18 34](https://github.com/ohmyzsh/ohmyzsh/assets/22087646/795aa5ab-aa97-483e-be01-763f13305ad6)

I use "Tab" for `cd` command，but "Backspace" not working.

#### zshrc config

```
export ZSH="/root/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=(git)
source $ZSH/oh-my-zsh.sh
```

#### locale

```
➜  ~ locale
LANG=zh_CN.UTF-8
LANGUAGE=
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=
```

**Comment by c0d3m0nky** [comment]
@mcornella As you can see in my locale -a output, it is set to UTF-8

Anything else it could be?

**Comment by mcornella** [comment]
You didn't post the `locale -a` output, only `locale`. Make sure the locale configured exists in `locale -a`, and if not, regenerate the locales so that it is properly installed.

If that's not it, perhaps you're seeing the output from `zsh-autosuggestions` and you should check if there's a related bug that does this.

**Comment by carlosala** [comment]
friendly ping @c0d3m0nky :)

**Comment by mcornella** [comment]
Reopen if this is still an issue with the suggestions in https://github.com/ohmyzsh/ohmyzsh/issues/11729#issuecomment-1678476891

**Comment by ftruzzi** [comment]
I encountered the same, adding `TERM=xterm` to my `.zshrc` seems to fix the issue.
