### ISSUE TITLE
Improve `gunwip` alias with recursive flow

### ISSUE THREAD

**Issue by kopach** [ohmyzsh/ohmyzsh#11721]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### If the feature solves a problem you have, specify it here.

I'm constantly making multiple commits with `gwip` command, resulting in multiple `--wip--` commits in history. Before submitting my feature, I prefer to refactor my commits, so I do `gunwip` multiple times. 

### Describe the proposed feature.

add `gunwipall` or `gunwipforce` or similar which would do `gunwip` in loop until there is anything to unwip

### Additional context

I'm willing to submit PR with proposed solution if this feature makes sense for authors

**Comment by carlosala** [comment]
I like the idea, could you work on a PR? Probably `gunwipall` makes much sense!

**Comment by kopach** [comment]
Yes, sure, I'll prepare PR shortly
