### ISSUE TITLE
Curl and Wget install script on https://ohmyz.sh/#install does'nt seem to work. 

### ISSUE THREAD

**Issue by rohannair11** [ohmyzsh/ohmyzsh#11720]
### Describe the bug

While trying to install ohmyzsh, the curl / wget command doesnt seem to work on my zsh terminal. 

### Steps to reproduce

Just try and run the install script from the homepage. It returns failed to connect, connection timed out on the particular port

### Expected behavior

Should install ohmyzsh

### Screenshots and recordings

![Screenshot 2023-06-01 152021](https://github.com/ohmyzsh/ohmyzsh/assets/42870265/ffaeb48a-dfc6-4372-b105-f09bba92dc25)

### OS / Linux distribution

WSL

### Zsh version

5.8

### Terminal emulator

zsh

### If using WSL on Windows, which version of WSL

WSL2

**Comment by carlosala** [comment]
It's working for me at this moment, retry to see if it works.
If you are in India or China it might happen that you can't access raw.githubusercontent.com
There are several issues about this in the repo 👌🏻

**Comment by rohannair11** [comment]
> It's working for me at this moment, retry to see if it works. If you are in India or China it might happen that you can't access raw.githubusercontent.com There are several issues about this in the repo 👌🏻

hey, It still doesnt seem to work in India. Is there any workaround for this issue currently?

**Comment by carlosala** [comment]
@rohannair11 you can copy the installer from [here](https://github.com/ohmyzsh/ohmyzsh/blob/master/tools/install.sh).
Paste the content in a file and execute it with `sh <file>`. We are working in a workaround, we'll post the updates [here](https://github.com/ohmyzsh/ohmyzsh/issues/11467).

**Comment by faisalmushtaq007** [comment]
not able to install (from india).  i even tried to use work around mentioned by @carlosala but still nothing

**Comment by carlosala** [comment]
Use https://install.ohmyz.sh to get the script!

**Comment by carlosala** [comment]
@Ryanjiena we don't recommend unoffical sources. In case raw GitHub does not work, our hosted one does.
