### ISSUE TITLE
New git aliases targeting develop branch

### ISSUE THREAD

**Issue by kopach** [ohmyzsh/ohmyzsh#11728]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### If the feature solves a problem you have, specify it here.

I'm using `develop` branch as main development branch instead of `main`

### Describe the proposed feature.

Add similar aliases as `grbom` & `grbm` but using `git_develop_branch` function

For example: 

- grbod - git rebase origin/$(git_develop_branch)
- grbd - git rebase $(git_develop_branch)

### Additional context

I'm willing to raise PR if code owners are OK with those new aliases

**Comment by carlosala** [comment]
Hi @kopach, thanks for your contribution!
We cannot accept your request I'm afraid. We are trying to only add new aliases to `git` plugin that are really game-changers. We already have a massive amount of them. Even though, I encourage you to add those to your own `zshrc`!
Thanks!
