### ISSUE TITLE
i can’t edit or change in vi ~/.zshrc

### ISSUE THREAD

**Issue by ahmad085210** [ohmyzsh/ohmyzsh#11735]
### Describe the bug

i can’t edit or change in vi ~/.zshrc, and i've been asking in chatgpt what the issues and when i try to recovery it’s dint help too

### Steps to reproduce

i just install my oh my zsh

### Expected behavior

it should be can edit on vi ~/.zshrc

### Screenshots and recordings

/
<img width="682" alt="Screenshot 2023-06-07 at 08 38 52" src="https://github.com/ohmyzsh/ohmyzsh/assets/133377812/42806806-bc95-40f0-84f5-669ed8be5f24">

### OS / Linux distribution

mac os ventura 13.3.1

### Zsh version

5.9

### Terminal emulator

iterm2

### If using WSL on Windows, which version of WSL

None

**Comment by rwmitchell** [comment]
This is nothing to do with OMZ, did you read and follow the instructions from vi?

**Comment by ahmad085210** [comment]
yeah, I've done several ways to recover, reinstall it and still it still same

**Comment by rwmitchell** [comment]
Have you killed process 3418?

**Comment by ahmad085210** [comment]
ok, I thought maybe I didn't really care about such problems, at least I can still use my terminal normally
