### ISSUE TITLE
commit 25c2c3a (Pull requests #9914) breaks KDE konsole Menu: "File"->"Open File Manager"

### ISSUE THREAD

**Issue by AlvinZhu** [ohmyzsh/ohmyzsh#11730]
### Describe the bug

can not open 'current/working directory' in dolphin by click konsole Menu: "File"->"Open File Manager".

### Steps to reproduce

1.
```bash
cd ~/.oh-my-zsh
git checkout 25c2c3a4683be60c3526858be960ee6ce1249245
```
2. click konsole Menu: "File"->"Open File Manager"
3. dolphin not open

### Expected behavior

click konsole Menu: "File"->"Open File Manager" to open pwd in dolphin.

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Oh My Zsh version

master(25c2c3a)

### Terminal emulator

Konsole

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
It should be now fixed. Get the fix with `omz update`.
