### ISSUE TITLE
The option to disable Oh My Zsh before running zshell

### ISSUE THREAD

**Issue by ono-max** [ohmyzsh/ohmyzsh#11738]
### If the feature solves a problem you have, specify it here.

I'm a member of [VS Code extension for Ruby debugger](https://github.com/ruby/vscode-rdbg). Currently, we have a problem of https://github.com/ruby/vscode-rdbg/issues/277. The problem is that we can't extract the result from stdout since Oh My Zsh outputs many strings to stdout. As a process, we get the result of running a command in the new process. Here is an example. In this case, we want to get the path, but it's hard to extract it. 

## Example Code
```ts
const p = child_process.exec(<command>);
let path: string;
p.stdout?.on("data", out => {
  console.log(out)
});
```

## Actual Outputs
```
"\u001b]1337;RemoteHost=miharekar@iMac-Pro.local\u0007\u001b]1337;CurrentDir=/Users/miharekar/Development/personal/rdbg\u0007\u001b]1337;ShellIntegrationVersion=6;shell=zsh\u0007/var/folders/x1/h2b59yq14cs6pv9r_x1_39lw0000gn/T/ruby-debug-sock-501/ruby-debug-miharekar-12243"
```

## Expected Outputs

```
"/var/folders/x1/h2b59yq14cs6pv9r_x1_39lw0000gn/T/ruby-debug-sock-501/ruby-debug-miharekar-12243"
```

### Describe the proposed feature.

It would be great to add the option to disable Oh My Zsh by setting environment variables, etc.

**Comment by ono-max** [comment]
Here is the actual command:

```
zsh -lic "rdbg --util=list-socks"
```

**Comment by carlosala** [comment]
You shouldn't run the command like that, if you are not going to use the shell in an interactive way, `-l` and `-i` should not be added.

**Comment by ono-max** [comment]
We need to run zshell as an interactive mode since we must load .zshrc before executing the command. In [rbenv](https://github.com/rbenv/rbenv), one of the well-known version managers for Ruby, the initial script is written in .zshrc.
Thus, we need to load .zshrc before running Ruby program to run the initial script of rbenv. That's a common practice in Ruby.

**Comment by carlosala** [comment]
Is it the configuration (not the script) in zshrc? You can for sure find the script outside of zshrc. I'd say that you might find some issues if you try to go this way, people might have some executions at the start of their login shells (neofetch, for example).

**Comment by carlosala** [comment]
@mcornella thoughts about this topic?

**Comment by rwmitchell** [comment]
Sounds like a ruby problem to me

**Comment by ono-max** [comment]
Sorry, we noticed that it's not the problem of Oh My Zsh, but Iterm2. When removing iterm2_shell_integration.zsh, we were able to remove a lot of noises in stdout. Thus, I'll close the issue. Thank you!

**Comment by rwmitchell** [comment]
Ding ding ding said that in my first response!!!
