### ISSUE TITLE
Tab completion appends

### ISSUE THREAD

**Issue by pvelesko** [ohmyzsh/ohmyzsh#11737]
### Describe the bug

Tab completion doesn't complete, but appends:

### Steps to reproduce

I type "cd ~[TAB]"
and this appears:
```
cd ~/cd ~/
mydir1 mydir2
```

whereas this is expected:
```
cd ~/
mydir1 mydir2
```

if I press enter, everything works as if the extraneous cd ~ wasn't there.

### Expected behavior

described above

### OS / Linux distribution

Linux cupcake 5.17.0-1019-oem

### Zsh version

5.8.1

### Oh My Zsh version

master (115cee1)

### Terminal emulator

Iterm2, MacOS terminal

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Which is your output when executing `locale`?

**Comment by carlosala** [comment]
It seems like you have some issues with the locale. Could you follow the instructions [here](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-change-my-locale)?

**Comment by pvelesko** [comment]
used this:
https://askubuntu.com/questions/599808/cannot-set-lc-ctype-to-default-locale-no-such-file-or-directory

locale issue is now resolved but still seeing the same behavior.

**Comment by carlosala** [comment]
Could you share your `zshrc`?

**Comment by pvelesko** [comment]
I think I found the issue. Commenting this out:
PROMPT="$fg[cyan]%}$USER@%{$fg[blue]%}%m
${PROMPT}" makes it work again.

The weird thing is that I had my zshrc unhcanged for months so something
happened in the last update.

I was using this to display ***@***.***:
