### ISSUE TITLE
Plugin z not working anymore

### ISSUE THREAD

**Issue by elchead** [ohmyzsh/ohmyzsh#11742]
### Describe the bug

when activating the z plugin i get the following alias:
'zshz 2>&1'

### Steps to reproduce

1. Enable plugin 'z'

### Expected behavior

use zsh-z plugin (https://github.com/agkozak/zsh-z)

### OS / Linux distribution

macOS 13.4

### Zsh version

5.9

### Oh My Zsh version

master (46c7040)

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

### Additional context

Manual installation of https://github.com/agkozak/zsh-z works as expected

**Comment by rwmitchell** [comment]
I get the same alias for z and it works as expected. Is zshz not defined for you?

**Comment by elchead** [comment]
yesterday it didn't work, but today it works indeed with zshz. Thanks for looking into it
