### ISSUE TITLE
docker compose up with -f flag

### ISSUE THREAD

**Issue by rhoitjadhav** [ohmyzsh/ohmyzsh#11743]
### If the feature request is for a plugin or theme, specify it here.

docker compose plugin

### If the feature solves a problem you have, specify it here.

I have to always use `docker compose -f <compose-file.yaml> up` command without having a shortcut in docker compose plugin

### Describe the proposed feature.

docker compose up with -f is not implemented yet and in some cases we may need to specify the different compose file rather than the default. Therefore, inclusion of this flag would be very helpful

**Comment by xila2** [comment]
sex

**Comment by hamonangann** [comment]
hi @mcornella may I work on this?

**Comment by carlosala** [comment]
It'd say it makes not so much difference to type `dcof` (which would be the natural alias for it) and `dco -f`. Taking into account that is a two strokes difference, if someone has the need to do it often could create a personal alias.
Thanks for the idea, and also thanks to @hamonangann!
