### ISSUE TITLE
New Docker update generates error

### ISSUE THREAD

**Issue by gerrymiller** [ohmyzsh/ohmyzsh#11753]
### Describe the bug

When loading Oh My Zsh, I'm getting the following error after the latest Docker plugin update (just started happening this morning):

```
╰─$ docker: 'completion' is not a docker command.
See 'docker --help'

```

### Steps to reproduce

1. Enable plugin Docker.
2. Open a ZSH terminal.
3. The error message mentioned above is displayed and I need to press CTRL-C to get back to the terminal prompt.
4. Disable the Docker plugin.
5. The error message no longer appears.

### Expected behavior

No error message as before :-)

### OS / Linux distribution

maxOS 13.4

### Zsh version

5.9

### Terminal emulator

Visual Studio Code

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Which `docker` version are you running? Get it with `docker --version`

**Comment by gerrymiller** [comment]
```
╰─$ docker --version                                   
Docker version 20.10.8, build 3967b7d
```

**Comment by mlachal** [comment]
Hi, I have the same error on Linux Mint 21.1 since today
```
docker --version
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
```

**Comment by gerrymiller** [comment]
Do you want me to close this issue, or leave it to you once you merge the PR?

**Comment by carlosala** [comment]
Merged! Thanks for the test!
