### ISSUE TITLE
Installation without git

### ISSUE THREAD

**Issue by Anonymous3-a** [ohmyzsh/ohmyzsh#11778]
### If the feature solves a problem you have, specify it here.

I've recently discovered https://sdf.org, so I made an account, verified, and it turns out that I don't have `git` access (yet).

### Describe the proposed feature.

Basically just add a flag to clone from the git repo using curl instead. From what I've seen, it's possible to request a source code tarball (or zip) so that would work too.

### Describe alternatives you've considered

I'm editing the `install.sh` script to try to remove `git` (and turn it into `curl`) but I've hit a roadblock on the `setup_ohmyzsh()` function, because I got this code (and can't figure out what it's cloning):
```
  # Manual clone with git config options to support git < v1.7. 2
  git init --quiet "$ZSH" && cd "$ ZSH" \
  && git config core.eol lf \
  && git config core.autocrlf false \
  && git config fsck.zeroPaddedFilemode ignore \
  && git config fetch.fsck.zeroPaddedFilemode ignore \
  && git config receive.fsck.zeroPaddedFilemode ignore \
  && git config oh-my-zsh.remote origin \
  && git config oh-my-zsh.branch "$BRANCH" \
  && git remote add origin "$REMOTE" \
  && git fetch --depth=1 origin \
  && git checkout -b "$BRANCH" "origin/$BRANCH" || {
    [ ! -d "$ZSH" ] || {
      cd -
      rm -rf "$ZSH" 2>/dev/null
    }
    fmt_error "git clone of oh-my-zsh repo failed"
    exit 1
  }
```

### Additional context

This *is* only a problem right now, because I will probably get git access later, but it's still annoying.

**Comment by quaxlyqueen** [comment]
[ohmyzsh.tar.gz](https://github.com/ohmyzsh/ohmyzsh/files/11898976/ohmyzsh.tar.gz)

If I'm understanding correct, you're looking for the attached tar.gz to be curl-able? As a note, I don't believe this method would allow for any ohmyzsh updates.

**Comment by mcornella** [comment]
You can manually download the zip file of the master branch and unzip it in the directory you want: https://github.com/ohmyzsh/ohmyzsh/archive/refs/heads/master.zip

**Comment by carlosala** [comment]
I think that's the best option, closing this :)
