### ISSUE TITLE
Completion is not working properly with Docker version 24.0.2

### ISSUE THREAD

**Issue by xvzc** [ohmyzsh/ohmyzsh#11789]
### If the feature request is for a plugin or theme, specify it here.

Docker plugin

### If the feature request is for a plugin or theme, specify it here.

Docker plugin

### If the feature solves a problem you have, specify it here.

[plugins/docker/docker.plugin.zsh](https://github.com/ohmyzsh/ohmyzsh/blob/fe4b5659863c388786986d70fa6d1bb66b00afb6/plugins/docker/docker.plugin.zsh#L49)
```zsh
# ...
  if is-at-least 23.0.0 $_docker_version; then
    # If the completion file doesn't exist yet, we need to autoload it and
    # bind it to `docker`. Otherwise, compinit will have already done that.
    if [[ ! -f "$ZSH_CACHE_DIR/completions/_docker" ]]; then
      typeset -g -A _comps
      autoload -Uz _docker
      _comps[docker]=_docker
    fi
    command docker completion zsh >| "$ZSH_CACHE_DIR/completions/_docker"
  else
    command cp "${0:h}/completions/_docker" "$ZSH_CACHE_DIR/completions/_docker"
  fi
# ...
```
Due to the line number 49 of `docker.plugin.zsh`, the file `~/.oh-my-zsh/cache/completions/_docker`  is overwritten with `$(docker completion zsh)` command which doesn't return many things as output (about 100 lines of zsh script). I simply just removed the condition above, so it seems to work now. I just want to ask if this condition is really necessary?

# For people who may get this issue:
 Try to modify the line number 49 of `~/.oh-my-zsh/cache/completions/plugins/docker/docker.plugin.zsh`

### Describe the proposed feature.

the file named `~/.oh-my-zsh/cache/completions/_docker ` should be written correctly

### Describe the proposed feature.

`~/.oh-my-zsh/cache/completions/plugins/docker/docker.plugin.zsh` should be written correctly

**Comment by carlosala** [comment]
Docker recommends this new way of generating completions, which will improve with time. At this point, what's good is that it completes cli plugins such as compose or buildx.
Thanks for your contribution!

**Comment by sdondley** [comment]
As I mentioned before, I think it's really a bad idea to degrade the user experience simply because it is the "official" way of doing things, especially when the "official" way isn't finished.

See https://github.com/ohmyzsh/ohmyzsh/pull/11754#issuecomment-1599105409

**Comment by sdondley** [comment]
I recommend giving people a choice of using the "official" way or the previous way.

**Comment by delfuego** [comment]
Completely agree; Docker autocompletion is totally broken for me with this. As in: I can type `docker` and hit tab and I get the docker sub-commands, but if I type `docker stop` and hit tab, I get a list of the current directory's documents.

I'm on macOS 13.4.1, running Docker 24.0.2.

Is there really no way to fix this?

**Comment by xvzc** [comment]
@delfuego As i mentioned above, you may try to modify or remove the line number 49 of ~/.oh-my-zsh/cache/completions/plugins/docker/docker.plugin.zsh which loads the docker built in auto completion when docker version is higher than 23.0.0

**Comment by delfuego** [comment]
I definitely got that — but then that'll get wiped out with the next OMZ update (or block the next update, I don't know how the updater's git pull works). I'd love if there were an option that didn't do that.

**Comment by xvzc** [comment]
@delfuego may be try to add below at the last line of your `~/.zshrc` ?
```
command cp ~/.oh-my-zsh/plugins/docker/completions/_docker $ZSH_CACHE_DIR/completions/_docker
```

**Comment by carlosala** [comment]
I'll add a setting to use the old completion system, even for docker >23. I'll do it as soon as I have time :)

**Comment by carlosala** [comment]
This has been added in 7d5e12500a2ba0b575ffafcbb516568973528730

**Comment by delfuego** [comment]
@carlosala This is amazing! I immediately added the relevant lines to my `.zshrc` file, and am back in my happy place.

Is there anything we can do to keep track of the "official" Docker way, so that when/if its functionality finally catches back up to the legacy way, we can switch back?

**Comment by carlosala** [comment]
I'd say you can try it each time you update the docker version!

**Comment by jaklan** [comment]
@carlosala I have also had an issue with non-working Docker v24 completion, but I was able to solve with the below command thanks to that comment: https://github.com/docker/cli/issues/4401#issuecomment-1786952072:
```bash
ln -s /Users/$USER/.oh-my-zsh/plugins/docker/completions/_docker /Users/$USER/.oh-my-zsh/plugins/docker/_docker
```

Isn't that OMZ-specific bug if creating a symlink within OMZ sub-directories is a solution?

**Comment by carlosala** [comment]
> This has been added in 7d5e12500a2ba0b575ffafcbb516568973528730

@jaklan refer to this commit's addition :)

**Comment by jaklan** [comment]
@carlosala yeah, I had tested:
`zstyle ':omz:plugins:docker' legacy-completion yes`
but it didn't work for me, but I have just noticed the reason was I placed it **after** `source $ZSH/oh-my-zsh.sh`, not **before**. Now it's fine 😉

**Comment by vmkalbskopf** [comment]
> @carlosala yeah, I had tested: `zstyle ':omz:plugins:docker' legacy-completion yes` but it didn't work for me, but I have just noticed the reason was I placed it **after** `source $ZSH/oh-my-zsh.sh`, not **before**. Now it's fine 😉

This fixed it for me as well. Thanks!
