### ISSUE TITLE
Docker autocompletion for containers not working on MacOS

### ISSUE THREAD

**Issue by Theiaz** [ohmyzsh/ohmyzsh#11786]
### Describe the bug

I'm migrating from Ubuntu to MacOS with my MacBook Pro (M2). I'm using ohmyzsh with the docker and docker-compose plugin. Docker has been installed with [Docker Desktop setup](https://docs.docker.com/desktop/install/mac-install/).

The docker plugin works fine except the autocompletion for the container names. 
- If I type `docker` and ⮕Tab it shows me a list of commands
- If I type `docker start` and ⮕Tab it just shows me the files of my current directory, but not the list of available containers.

I'm expecting the autosuggestion to work here and show me a list of all containers which could be started. This worked fine within Ubuntu.

What I did so far:
- ask google (obviously) 
- try the help sections for common problems on the [FAQ](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ)
- ask [apple stackexchange](https://apple.stackexchange.com/questions/461613/auto-suggestions-for-docker-container-names-with-ohmyzsh?noredirect=1#comment678856_461613) who referred me to ask this community
- ask ohmyzsh-discord chat (no answers)

### Steps to reproduce

 `docker start`+ ⮕Tab  

### Expected behavior

Show list of containers which are ready to start.

### Screenshots and recordings

`.zshrc`
```sh
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# history
SAVEHIST=10000

# ohmyzsh
ZSH_THEME="lukerandall"
zstyle ':omz:update' mode reminder  # just remind me to update when it's time
# docker autocompletion
#zstyle ':completion:*:*:docker:*' option-stacking yes
#zstyle ':completion:*:*:docker-*:*' option-stacking yes
plugins=(brew docker docker-compose git kubectl kubectx)
source $ZSH/oh-my-zsh.sh

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

autoload -U compinit && compinit

# kubectl
alias k="kubectl"
# krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
```
---
Screenshots:
![Screenshot 2023-07-05 at 16 41 19](https://github.com/ohmyzsh/ohmyzsh/assets/9378662/4ad1d3a9-9858-4f34-9a70-5f0fe42f2f4e)
![Screenshot 2023-07-05 at 16 41 38](https://github.com/ohmyzsh/ohmyzsh/assets/9378662/8a83df09-b156-4583-84d6-3d4471389e29)
![Screenshot 2023-07-05 at 16 42 11](https://github.com/ohmyzsh/ohmyzsh/assets/9378662/8a8ecc15-86fd-4775-8959-f1c94e868a64)

### OS / Linux distribution

macOS 13.14.1

### Zsh version

5.9

### Terminal emulator

-

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
This is something that should be submitted to https://github.com/docker/cli, we are just adding the completion from the official sources!
Thanks!
