### ISSUE TITLE
The 3rd installation option fails. Recommendation is to remove it

### ISSUE THREAD

**Issue by rails-smith** [ohmyzsh/ohmyzsh#11787]
### Describe the bug

This is about the 3rd installation method in the table in the ReadMe:

fetch | sh -c "$(fetch -o - https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
-- | --

I had not been aware of the `fetch` command, so I downloaded it via Homebrew (thinking it was from GNU)

This method fails. 
```
sh -c "$(fetch -o - https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```

yields this error output:
```
sh: Incorrect: command not found
sh: line 2: NAME:: command not found
ERRO[2023-07-05T21:13:00-07:00] The --repo flag is required. Run "fetch --help" for full usage info.  binary=fetch version=
sh: line 5: USAGE:: command not found
sh: -c: line 6: syntax error near unexpected token `newline'
sh: -c: line 6: `   fetch [global options] <local-download-path>'
```

Looking into this further I see the code is owned by [Gruntwork](https://www.gruntwork.io/)

Repo: [gruntwork-io/fetch](https://github.com/gruntwork-io/fetch)

The  [fetch examples](https://github.com/gruntwork-io/fetch#examples) that express the current way to use `fetch` is not reflected in the invocation in the installation table. 

Nearly every time I tried `fetch` I saw this:
```
The --repo flag is required.
```

And when I finally found syntax that began to work, I finally stopped at this last invocation which apparently downloaded the entire repo as if I had run `git clone`. 

```
# fetch --repo="https://github.com/ohmyzsh/ohmyzsh" --branch=master --ref="tools/install.sh" install.sh
INFO[2023-07-05T21:04:39-07:00] Downloading latest commit from branch "master" of https://github.com/ohmyzsh/ohmyzsh ...  binary=fetch version=
INFO[2023-07-05T21:04:39-07:00] Extracting files from <repo>/ to install.sh ...  binary=fetch version=
INFO[2023-07-05T21:04:40-07:00] 995 files extracted                           binary=fetch version=
INFO[2023-07-05T21:04:40-07:00] Download and file extraction complete.        binary=fetch version=

```
I could not find the exact correct invocation. Prolly too much trouble. :-)

This is another error or warning that notifies the User that they may be violating the owner's prescribed license for usage. I looked no further. 
```
Assuming GitHub Enterprise since the provided url (https://raw.githubusercontent.com/ohmyzsh/ohmyzsh) does not appear to be for GitHub.com
```

Perhaps it is a good idea to remove this open source wart. 

HTH!

### Steps to reproduce

```
sh -c "$(fetch -o - https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```

### Expected behavior

expected not to fail

### OS / Linux distribution

macOS 12.6.6

### Zsh version

n/a

### Oh My Zsh version

n/a

### Terminal emulator

n/a

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
The documented command is for freebsd fetch, for which you can refer to [https://man.freebsd.org/cgi/man.cgi?fetch(1)](https://man.freebsd.org/cgi/man.cgi?fetch(1)).

I haven't seen this available in Homebrew formulae or cask, but it is sure that what you downloaded isn't the freebsd command.

**Comment by neuromachina** [comment]
> The documented command is for freebsd fetch, for which you can refer to https://man.freebsd.org/cgi/man.cgi?fetch(1).
> 
> I haven't seen this available in Homebrew formulae or cask, but it is sure that what you downloaded isn't the freebsd command.

haha! I thought I was missing out on a new linux tool. 
Homebrew will summon it's doppelganger, for sure. 
Thanks for reminding me that FreeBSD is still running the matrix; nearly forgot.

**Comment by rails-smith** [comment]
> The documented command is for freebsd fetch, for which you can refer to https://man.freebsd.org/cgi/man.cgi?fetch(1).
> 
> I haven't seen this available in Homebrew formulae or cask, but it is sure that what you downloaded isn't the freebsd command.

haha! I thought I was missing out on a new linux tool.
Homebrew will summon it's doppelganger, for sure.
Thanks for reminding me that FreeBSD is still running the matrix; nearly forgot.
