### ISSUE TITLE
Error while updating Oh My Zsh.

### ISSUE THREAD

**Issue by Aniganesh** [ohmyzsh/ohmyzsh#11793]
### Describe the bug

Got this message while updating OMZ on my Ubuntu 22.04:
`internal error, please report: running "docker" failed: cannot find installed snap "docker" at revision 2285: missing file /snap/docker/2285/meta/snap.yaml`
However OMZ did get updated and I'm on the latest release from `master` branch: master (fe4b5659)

### Steps to reproduce

Not sure. I ran `omz update` and got this message.

### Expected behavior

omz update shouldn't show that message.

### Screenshots and recordings

![Screenshot_from_2023-07-11 22-17-02](https://github.com/ohmyzsh/ohmyzsh/assets/47713754/fbb21c7b-dd04-418d-8e88-99190aeb7da2)

### OS / Linux distribution

Ubuntu 22.04

### Zsh version

5.8.1

### Oh My Zsh version

master (fe4b5659)

### Terminal emulator

GNOME Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
It seems that you have `docker` binary accessible with snap, but it's not properly installed. I'd recommend you reinstalling `docker` using snap, and you'll get rid of that issue. Then you can uninstall without issues.
Thanks for the report!
