### ISSUE TITLE
Doesn't autoload when with `silent-autoload`

### ISSUE THREAD

**Issue by jclusso** [ohmyzsh/ohmyzsh#11796]
When I have `zstyle ':omz:plugins:nvm' autoload yes` it works fine, but if I use `zstyle ':omz:plugins:nvm' silent-autoload yes` as shown in the documentation, it does not autoload. I'm using Powerlevel10k if that matters.

https://github.com/ohmyzsh/ohmyzsh/blob/fe4b5659863c388786986d70fa6d1bb66b00afb6/plugins/nvm/README.md?plain=1#L60

**Comment by carlosala** [comment]
You need to have both enabled, not only silent-autoload

**Comment by jclusso** [comment]
@carlosala ahh, that was not clear to me. Maybe we should make it so the example has that?

**Comment by carlosala** [comment]
Make sense, yes. Do you mind preparing a PR?
