### ISSUE TITLE
Slow startup due to `git --version` in `check_for_upgrade.sh`

### ISSUE THREAD

**Issue by alexchandel** [ohmyzsh/ohmyzsh#11800]
### Describe the bug

ohmyzsh run `git --version` in its `check_for_upgrade.sh` startup script.  On recent versions of macOS, this command can hang for a very long time under certain circumstances (like after a reboot).

This isn't caused by a license that hasn't been accepted yet (as is the case after an update), and is not permanently fixed by `sudo xcodebuild -license accept`.  It can recur after a reboot, or after system updates that don't affect Xcode.  It's stupid, but that's how it is.

Can we skip the `git --version` check, or add some workaround for macOS/system `git`?

### Steps to reproduce

1. Install Xcode developer tools and accept license, so that system `zsh` and `git` work
2. Install `ohmyzsh`
3. Restart computer, open Terminal (sometimes)

### Expected behavior

`ohmyzsh` startup should never hang for 10s of seconds, because `git --version` should never hang for 10s of seconds.

### OS / Linux distribution

macOS 13 (latest)

### Zsh version

5.9

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
We needed to add that check due to some errors with Mac, specifically after a system upgrade. See #11420 and #11309.
