### ISSUE TITLE
mamba change the theme command prompt in zsh, how to fix?

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [ohmyzsh/ohmyzsh#11805]
### Describe the bug

machine: mac air m1

After I install Mambaforge-MacOSX-arm64, "base" in the command line like below
![image](https://github.com/ohmyzsh/ohmyzsh/assets/30332524/c329a23c-5151-485d-a3ee-2c414d96a791)

### Steps to reproduce

just install mambaforge

### Expected behavior

"base" in front of the command line 

### OS / Linux distribution

mac os 12.4

### Zsh version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Terminal emulator

terminal app

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Mamba (actually conda) seem to modify `$PS1` variable. Restore the original value of `$PS1` (the one you had before loading mamba) after you load it.
