### ISSUE TITLE
Hardcoded tmux config file

### ISSUE THREAD

**Issue by diegoroccia** [ohmyzsh/ohmyzsh#11803]
### Describe the bug

the tmux plugin harcoded the configuration file path to ~/.tmux.conf when not provided. this blocks tmux from using the [XDG Base Dirs spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) which was recently (and after long discussions) merged 

### Steps to reproduce

1. Enable the plugin 'tmux' 
2. set the plugin to autostart
3. create a tmux.conf file in $XDG_CONFIG_HOME/tmux/tmux.conf
4. start a shell 
5. 

### Expected behavior

tmux should pick up the file in $XDG_CONFIG_HOME/tmux/tmux.conf and apply that configuration

### OS / Linux distribution

Ubuntu 22.04.2 LTS (but this is not distro specific)

### Zsh version

5.8.1 (but it's not relevant)

### Terminal emulator

alacritty

### If using WSL on Windows, which version of WSL

None

### Additional context

Here

https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/tmux/tmux.plugin.zsh#L29

$ZSH_TMUX_CONFIG should be left empty when not provided by the user so that this condition

https://github.com/ohmyzsh/ohmyzsh/blob/8bdb5c959c9a5c74d3b59c05a3a0bca5e602c3cd/plugins/tmux/tmux.plugin.zsh#L86C7

is skipped and no `-f` option is added to the command line

adding 

```
export ZSH_TMUX_CONFIG=${HOME}/.config/tmux/tmux.conf
```

of course fixes the problem but this should not be necessary

**Comment by carlosala** [comment]
Sounds good! Do you want to create a PR that also checks `$XDG_CONFIG_HOME/tmux/tmux.conf` or, as a fallback, `$HOME/.config/tmux/tmux.conf`?
It'd be great to maintain `$HOME/.tmux.conf` as the default one!
