### ISSUE TITLE
Listable information showing with extra lines and with tilda (~)

### ISSUE THREAD

**Issue by TemurbekRuziyev** [ohmyzsh/ohmyzsh#11804]
### Describe the bug

When we use listable data like `git branch`, `git tag` or something like that it is not showing them correctly and adding extra lines 

### Steps to reproduce

I just installed and I tried with other themes

### Expected behavior

Not to show extra likes with tilda (~)

### Screenshots and recordings

![image](https://github.com/ohmyzsh/ohmyzsh/assets/68279922/ea61baf8-bad5-472c-a2ad-fae82691457d)

### OS / Linux distribution

MacOS M1Pro

### Zsh version

5.9

### Terminal emulator

Terminal, Git Bash

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
That is because your output is getting paged, has nothing to do with `omz`. You can find more information in SO about it https://stackoverflow.com/questions/2183900/how-do-i-prevent-git-diff-from-using-a-pager
