### ISSUE TITLE
Problem when oh-my-zsh getting current branch name

### ISSUE THREAD

**Issue by CloudyAnt** [ohmyzsh/ohmyzsh#11801]
### Describe the bug

I have a branch named *代码更新*, but oh-my-zsh display it as *代�*. The character '码' became '�' and all characters behind it disappered.

I think it might due to this code `ref=$(__git_prompt_git symbolic-ref --short HEAD 2> /dev/null)`  which was used in the `git_prompt_info` function in *.oh-my-zsh/lib/git.sh*.

When the branch name contains a character in unicode range 77A0 - 783F (from my testing) like '码', '砀', this problem happens,  the command `git symbolic-ref --short HEAD` seems cannot handle characters in this range.

Then I replaced the code to `ref=$(__git_prompt_git branch --show-current 2> /dev/null)`, it works well.

### Steps to reproduce

1. create a branch named *代码更新*
2. checkout the branch *代码更新*

### Expected behavior

oh-my-zsh was expected to display:
➜  my-awesome-project git:(代码更新)

### OS / Linux distribution

MacOs 13.4.1

### Zsh version

5.9

### Oh My Zsh version

master (fe4b565)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by CloudyAnt** [comment]
Further research:
1: git symbolic-ref HEAD (remove --short) also works fine.
2: my another mac with macOs 12.6.1 doesn't have this problem 😕...

**Comment by CloudyAnt** [comment]
I upgraded git to version 2.41.0, then the problem was fixed !
Through a unrigorous research with my colleagues, we found this problem might appear on macOs with git version 2.38 - 2.39.

**Comment by carlosala** [comment]
Nice! I'm glad it's something that git folks are aware of and fixed it!
