### ISSUE TITLE
Some themes cause phantom characters to be appended to the end of the prompt (temporarily) upon zsh doing the directory listing for autocomplete (only in some environments))

### ISSUE THREAD

**Issue by VoidAny** [ohmyzsh/ohmyzsh#11806]
### Describe the bug

When some themes are applied in OhMyZsh when it is run in certain environments, they can cause a bug that results in the duplication of some number of the first characters in the user typed command when zsh lists the files in the directory for the user to choose from for a completion. Here is an example of the behavior with the theme `refined` enabled:

1. The user types a command that will result in a directory listing by zsh: 
```
~
❯ ls /var/                                                               
```
2. The user presses tab:
```
~
❯ lsls /var/   
backups/  lib/      lock@     mail/     run@      tmp/
cache/    local/    log/      opt/      spool/    www/
```
3. The user backspaces as much as possible (the generated phantom characters can't be deleted):
```
~
❯ ls                                                                       
backups/  lib/      lock@     mail/     run@      tmp/
cache/    local/    log/      opt/      spool/    www/
```
4. The user presses enter (nothing happens, showing how the shell doesn't actually receive these characters):
```
~
❯ ls                                                                       

~
❯                                                                        
```

Some themes (such as fwalch, adben, and jreese to name a few I found using random) are not affected by this bug.

Some other themes, like agnoster, are affected worse with the first 5 characters being replicated as phantom characters!

My testing also reveled that this bug only occurs in some environments. I found this bug to be present when:
- Launching zsh within the chroot created by artix-chroot (but a normal chroot works fine)
- Launching zsh by suing to a user using doas (but sudo and normal su work fine)

### Steps to reproduce

1. Use the default OhMyZsh settings, but change the theme to an affected one (ex. refined)
2. Install opendoas and run `echo "permit nopass :root" | sudo tee /etc/doas.conf` to allow using doas from root without a password
3. Su to root somehow
4. From root, use doas to su to the user that has OhMyZsh installed (ex. `doas su user`)
5. Type `ls /var/` (or some other directory with sub-directories) and press tab
6. See the phantom characters

### Expected behavior

No phantom characters appear after pressing tab. 

### OS / Linux distribution

Both Void Linux and Artix Linux

### Zsh version

5.9

### Oh My Zsh version

master (7d5e125)

### Terminal emulator

Linux TTY

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
It seems to be a locale issue. See more here! https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command

**Comment by VoidAny** [comment]
It was! Thank you very much for your help!
