### ISSUE TITLE
Wrong usage for the 'als' command 

### ISSUE THREAD

**Issue by chfab** [ohmyzsh/ohmyzsh#11812]
### Describe the bug

The usage message of the command 'als -h' displays 'acs' as the command name instead of 'als'.

### Steps to reproduce

1. type the command : als -h
result: usage: acs [-h] [-g GROUP_LIST] [--groups] [<keyword> ...]

### Expected behavior

expected result: usage: als [-h] [-g GROUP_LIST] [--groups] [<keyword> ...]

### Screenshots and recordings

<img width="366" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/17162647/6133d07c-5e22-4306-9359-3ea8022a1981">

### OS / Linux distribution

macOS 13.4.1

### Zsh version

5.9

### Oh My Zsh version

master (338b9a6)

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Thanks for the report!
