### ISSUE TITLE
terraform plugin: show version

### ISSUE THREAD

**Issue by roeniss** [ohmyzsh/ohmyzsh#11811]
### If the feature request is for a plugin or theme, specify it here.

terraform plugin

### If the feature solves a problem you have, specify it here.

like p10k's terraform, omz terraform would be better to add version info to prompt.

Terraform is very sensitive to version changes. It's common to swap multiple version for each terraform module in a company.

### Describe the proposed feature.

Add terraform version info to prompt, as optional.

**Comment by carlosala** [comment]
It looks fine! Do you want to handle it and create a PR?
Thanks!

**Comment by roeniss** [comment]
@bik1111 he is my friend and he will handle this issue.

**Comment by bik1111** [comment]
plz assign this issue to me :)

**Comment by carlosala** [comment]
nice!
