### ISSUE TITLE
Social media other than twitter

### ISSUE THREAD

**Issue by coke** [ohmyzsh/ohmyzsh#11814]
### If the feature solves a problem you have, specify it here.

Announcements made on twitter now require a twitter account for users to even read.

### Describe the proposed feature.

Add mastodon (or something else) as an option.

**Comment by carlosala** [comment]
assigning to you @robbyrussell!

**Comment by robbyrussell** [comment]
Thanks, I'll look into getting things running on Mastadon, LinkedIn, Instagram, and the Facebook page... and/or focus on building out and using the mailing list.

**Comment by larson-carter** [comment]
@robbyrussell Any update to this?

Seems like X/Twitter is becoming less and less friendly which can be aggravating to some users.

**Comment by robbyrussell** [comment]
@larson-carter Step 1: https://mstdn.social/@ohmyzsh

Can you help tell folks on Discord and such?
