### ISSUE TITLE
zsh doesn't work

### ISSUE THREAD

**Issue by whitescent** [ohmyzsh/ohmyzsh#11818]
### Describe the bug

when I first installed zsh, and open a new terminal, the terminal becomes very strange (also after restarting the computer)

![image_2023-07-27_17-52-08](https://github.com/ohmyzsh/ohmyzsh/assets/31311826/af1c9f9f-f411-4aef-b487-c451525ce708)

### Steps to reproduce

1. sudo apt install zsh
2. sudo sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

and open a new terminal.

### Expected behavior

Expected behavior: the terminal should be consistent with the left。

### Screenshots and recordings

![image_2023-07-27_17-52-08](https://github.com/ohmyzsh/ohmyzsh/assets/31311826/af1c9f9f-f411-4aef-b487-c451525ce708)

### OS / Linux distribution

Ubuntu 23.04 x86_64

### Zsh version

5.9

### Terminal emulator

default system terminal, Terminlator

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
It looks like you installed OMZ for the root user, not your own.

OMZ is not installed system-wide but for the user that's running the installer. You need to install it for the user that's going to be using it.
