### ISSUE TITLE
Double free when correcting command substitution $(PWD)

### ISSUE THREAD

**Issue by kjughx** [ohmyzsh/ohmyzsh#11825]
### Describe the bug

When correcting the command substitution: $(PWD) to $(pwd) the shell crashes with SIGABRT:

~>$ $(PWD)
zsh: correct 'PWD' to 'pwd' [nyae]? y
double free or corruption (out)
fish: Job 1, 'zsh' terminated by signal SIGABRT (Abort)

### Steps to reproduce

1. Run $(PWD)
2. Press yes when prompted to correct
3. Watch as shell crashes

### Expected behavior

PWD should be corrected to pwd without crashing and the command should complete without errors.

### OS / Linux distribution

Debian 11 (bullseye)

### Zsh version

5.8

### Terminal emulator

alacritty,gnome-terminal,termit

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
I can reproduce it in zsh 5.8, but in zsh 5.9 the subshell does not inherit the `setopt completeall`, and it just says that the command is not found. It was a regression in `zsh` itself, there's a thread in the [workers mailing list](https://www.zsh.org/mla/workers/2020/msg00939.html) about it.
Thanks for the report!
