### ISSUE TITLE
Error : zsh: no matches found

### ISSUE THREAD

**Issue by slavag** [ohmyzsh/ohmyzsh#11828]
### Describe the bug

Trying to run command :
`python generate.py --base_model=llama --prompt_type=llama2 --score_model=None --langchain_modes=['TestData'] --langchain_mode='TestData'` in zsh and getting error zsh: no matches found: --langchain_modes=[TestData].

While running it in bash is working fine.

### Steps to reproduce

run command to get error:
`python generate.py --base_model=llama --prompt_type=llama2 --score_model=None --langchain_modes=['TestData'] --langchain_mode='TestData'

### Expected behavior

Working like in bash

### Screenshots and recordings

In ZSH :
<img width="1353" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/511540/2099d55b-223e-45f0-9e1e-74a079aa82fe">

In bash:
<img width="777" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/511540/fb60a85e-105c-43e7-a260-d36034a7e6fe">

### OS / Linux distribution

MacOS 13.5

### Zsh version

zsh 5.9 (x86_64-apple-darwin22.0)

### Terminal emulator

mac terminal

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Add quotes around `['TestData']`

**Comment by slavag** [comment]
@carlosala not helping a lot, tried this as well
<img width="1567" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/511540/68ed8102-27c0-4ce5-ba51-cee0d3ebc2c1">

**Comment by carlosala** [comment]
I mean `"['TestData']"`

**Comment by slavag** [comment]
@carlosala  Thanks, but why is there difference with bash ? shouldn't it behave in the same way ?

**Comment by carlosala** [comment]
Nope, because in Zsh square parentheses have special a special meaning. Bash and Zsh are not 100% equivalent
