### ISSUE TITLE
Alias `gm` conflicts with GraphicsMagick command `gm`

### ISSUE THREAD

**Issue by nesper8** [ohmyzsh/ohmyzsh#11832]
### Describe the bug

The alias for git merge `gm` conflicts with execution of the GraphicsMagick tool which also uses the binary named `gm`

Execution preview
```
nesper8@poweredbyarch ~/Pictures % gm
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

128 nesper8@poweredbyarch ~/Pictures % /usr/bin/gm
GraphicsMagick 1.3.40 2023-01-14 Q16 http://www.GraphicsMagick.org/
Copyright (C) 2002-2023 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.
Usage: /usr/bin/gm command [options ...]

Where commands include:
    animate - animate a sequence of images
      batch - issue multiple commands in interactive or batch mode
  benchmark - benchmark one of the other commands
    compare - compare two images
  composite - composite images together
    conjure - execute a Magick Scripting Language (MSL) XML script
    convert - convert an image or sequence of images
    display - display an image on a workstation running X
       help - obtain usage message for named command
   identify - describe an image or image sequence
     import - capture an application or X server screen
    mogrify - transform an image or sequence of images
    montage - create a composite image (in a grid) from separate images
       time - time one of the other commands
    version - obtain release version
```
Would it be possible to change the `git merge` alias to something else so that it is possible to execute GraphicsMagick normally through the terminal?

Thank you

### Steps to reproduce

1. Install omz and GraphicsMagick
2. Enable the `git` plugin
3. Try to execute GraphicsMagick through the terminal with the command `gm`

### Expected behavior

GraphicsMagick should execute instead of `git merge`

### Screenshots and recordings

![Screenshot from 2023-08-08 10-59-11](https://github.com/ohmyzsh/ohmyzsh/assets/57890520/b7894c5f-d547-46ec-9033-85c5d4027cc7)

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Terminal emulator

GNOME Console (kgx)

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
That's unfortunate. The `gm` alias is probably one of the most widely used by the users (speculation, it's a critical git command) and changing it would likely create an argument like the one we had [here](https://github.com/ohmyzsh/ohmyzsh/issues/11331).
I'd recommend you add `unalias gm` after sourcing `oh-my-zsh.sh` to remove the alias.
Thanks for the report!
