### ISSUE TITLE
git plugin is showing wrong git status for large monorepos

### ISSUE THREAD

**Issue by asharkhan3101** [ohmyzsh/ohmyzsh#11839]
### Describe the bug

I am working in a large monorepo and git plugin for oh my zsh is showing wrong status, For instance after a pull which includes a large number of changes, the plugin is showing that directory is dirty but running git status shows clean status.

I tried to cd out and back in the project it also does not helps, however restarting the shell does seems to fix the problem, but its annoying.

### Steps to reproduce

Described in the bug above

### Expected behavior

I expect that it should correctly report the git status

### OS / Linux distribution

macOS

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by vishal-sharma-369** [comment]
Would you please explain the steps how to reproduce the same issue.

**Comment by coder3101** [comment]
@vishal-sharma-369 there is no specific steps. I have a very large monorepo, I use powerlevel 10K theme which shows the git status.

In case of big mono repo the reported git status is incorrect.

**Comment by carlosala** [comment]
I see that you are using gitstatus from p10k. Could you please open the issue there?
Thanks!
https://github.com/romkatv/powerlevel10k
