### ISSUE TITLE
Easy customize of  branch name by git_ptompt_info color  in to state of repo in ZSH_THEME_GIT_PROMPT_DIRTY ZSH_THEME_GIT_PROMPT_CLEAN

### ISSUE THREAD

**Issue by chiddekel** [ohmyzsh/ohmyzsh#11842]
### If the feature solves a problem you have, specify it here.

Add support for easy customize color of branch name depend of git_ptompt_info color trigger by state of rep dirty either clean.

### Describe the proposed feature.

How to  change color of repo state using  git_ptompt_info easy customiazion.

**Comment by carlosala** [comment]
You can add some logic to tweak colours. For example, see [my theme](https://github.com/carlosala/dotfiles/blob/161f8f5d0201a5f6627d54be0f9d0c582f1ff1f6/zsh/custom/themes/carlosala.zsh-theme#L2). In `%(?:%F{6}:%F{1})` I choose colour 6 or 1 if `$?` is zero or not.
It seems a bit specific, so it's better to have it in your personal config.
Thanks!

**Comment by chiddekel** [comment]
Hey. I work around it by extend function git_prompt_info_color and add it as alias. In that way I can Control colors of the branch name.
