### ISSUE TITLE
web-serach plugin not working in Debian WSL 2 - Windows

### ISSUE THREAD

**Issue by Ajay-056** [ohmyzsh/ohmyzsh#11846]
### Describe the bug

I'm running Debian 12 - Bookworm inside WSL 2, Installed oh-my-zsh with plugins. When I tried to use web-search plugin, The command is running with exit code (126) and browser didn't launch with search term. The exit code 126 says "not having permission to execute the script or a command".

Note: I have tried WSLg and tried using the command with a brave (WSLg) instance opened as well, still didn't work

### Steps to reproduce

NA

### Expected behavior

Any web-search commands inside WSL should launch a browser with search term if not opened already and should open the search term in new browser in existing browser instance

### Screenshots and recordings

![image](https://github.com/ohmyzsh/ohmyzsh/assets/40629789/30cf3fef-a93f-4d19-9107-c75c63cc97ac)

### OS / Linux distribution

Debian 12 - Bookworm

### Zsh version

5.9

### Oh My Zsh version

master (fd219a9)

### Terminal emulator

WSL

### If using WSL on Windows, which version of WSL

WSL2

**Comment by Ajay-056** [comment]
Tried out the web-serach in OpenSuse Tumbleweed - WSL 2. It is working perfectly even without WSLg brave instance. (Search terms are launching in brave windows instance)

**Comment by carlosala** [comment]
Error `126` is, as you say, due to permissions in `open_command`, when it executes `cmd.exe`. Make sure you have WSL2 properly set up, and, as I see, with other distros is working well. Closing for the moment, feel free to reopen if you find anything else!
Thanks for the report!
