### ISSUE TITLE
asdf could not change version

### ISSUE THREAD

**Issue by lyb124553153** [ohmyzsh/ohmyzsh#11840]
### Describe the bug

could not switch ruby version

### Steps to reproduce

```
tail -f .zshrc
#___MY_VMOPTIONS_SHELL_FILE="${HOME}/.jetbrains.vmoptions.sh"; if [ -f "${___MY_VMOPTIONS_SHELL_FILE}" ]; then . "${___MY_VMOPTIONS_SHELL_FILE}"; fi


# Added by GDK bootstrap
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles



# Added by GDK bootstrap
. /usr/local/opt/asdf/libexec/asdf.sh
```

### Expected behavior

expect switch ruby 3

### Screenshots and recordings

OS:
Darwin liyongbodeMacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64

SHELL:
zsh 5.9 (x86_64-apple-darwin22.0)

ASDF VERSION:
v0.11.1-27c8a10

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
gitleaks                     https://github.com/jmcvetta/asdf-gitleaks.git main 0cc0d7e
golang                       https://github.com/asdf-community/asdf-golang.git master d8dec15
minio                        https://github.com/aeons/asdf-minio.git master 113b19d
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 4f8aa3d
postgres                     https://github.com/smashedtoatoms/asdf-postgres.git master f8cf805
redis                        https://github.com/smashedtoatoms/asdf-redis.git master 5e0a853
ruby                         https://github.com/asdf-vm/asdf-ruby.git master 8cb9721
rust                         https://github.com/code-lever/asdf-rust.git master 95acf4f
shellcheck                   https://github.com/luizm/asdf-shellcheck.git master b160a52
vale                         https://github.com/pdemagny/asdf-vale main 9a3b1c0

### OS / Linux distribution

macod

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
You seem to not use the `asdf` oh-my-zsh plugin. Try to remove any kind of `asdf` custom loading and use the plugin. Feel free to provide more information and we can check what's going on there!
Thanks for the report!
