### ISSUE TITLE
git cherry-pick parameter prompt is slow in a large repo

### ISSUE THREAD

**Issue by CacheUseOnly** [ohmyzsh/ohmyzsh#11849]
### Describe the bug

When tapping `Tab` for autocompletion or prompts for `git cherry-pick --`, it may take up to 1 or 2 seconds to respond, which is significantly slower than other git commands.

### Steps to reproduce

1. Enable plugin `git` by adding `plugins=(git)` in `~/.zshrc`
2. Enter a large git repository
3. Type `git cherry-pick --` and press Tab key

### Expected behavior

A quick response is expected.

### Screenshots and recordings

[Screencast from 08-16-2023 03:18:32 PM.webm](https://github.com/ohmyzsh/ohmyzsh/assets/48495167/3dc1a03c-4493-4308-8d0f-4af7e7bf971b)

### OS / Linux distribution

Ubuntu 22.04

### Zsh version

5.8.1

### Terminal emulator

GNOME Terminal 3.44.0 for GNOME 42

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
This is something that might happen depending on which completion, as in the end is just some code being executed.
We do not change `git` completion, that is something done by `zsh` itself.
Thanks for your report!
