### ISSUE TITLE
sprunge.us website and plugin seems to be dead.

### ISSUE THREAD

**Issue by InvisibleRasta** [ohmyzsh/ohmyzsh#11854]
### Describe the bug

Looks like the website does not work anymore. Plugin is failing aswell

### Steps to reproduce

sprunge "hello"

### Expected behavior

sprunge "hello"
http://sprunge.us/XxjnKz

### OS / Linux distribution

Any

### Zsh version

5.9

### Terminal emulator

Gnome Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
It seems that it has been down for over a month now. Maybe we should remove the plugin, soft-deprecating it first. Let's keep it as is for some time, and let's see what happens.

**Comment by carlosala** [comment]
`sprunge.us` is, once again, alive! 🎉
