### ISSUE TITLE
I have found many exports inside zshrc

### ISSUE THREAD

**Issue by Mahmoudgalalz** [ohmyzsh/ohmyzsh#11850]
### Describe the bug

export GPG_TTY=$(tty)

I have found thounds of this inside my .zshrc I don't know the reason?

I use wrap terminal

### Steps to reproduce

there's nothing

### Expected behavior

it should no generate this 

### Screenshots and recordings

![image](https://github.com/ohmyzsh/ohmyzsh/assets/42272376/97545aa8-ca44-4fbf-a8c2-1436b1b3a5bd)

### OS / Linux distribution

MacOS ventura

### Zsh version

5.9

### Terminal emulator

Wrap

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
You can remove them, and leave only one. If you sign your commits, it's nice to have that export once in your zshrc.

**Comment by chao-xian** [comment]
@Mahmoudgalalz in case it helps, I found this is my .zshrc:

```
if [ -r ~/.zshrc ]; then echo -e '\nexport GPG_TTY=$(tty)' >> ~/.zshrc; \
  else echo -e '\nexport GPG_TTY=$(tty)' >> ~/.zprofile; fi
```

which I have no recollection of adding, but this was the cause for me.
