### ISSUE TITLE
Battery Plugin: support for OpenBSD

### ISSUE THREAD

**Issue by im-notpua** [ohmyzsh/ohmyzsh#11857]
### If the feature request is for a plugin or theme, specify it here.

Battery plugin

### If the feature solves a problem you have, specify it here.

Extends battery plugin support for OpenBSD

### Describe the proposed feature.

The battery plugin has support for FreeBSD through the sysctl hw.acpi* commands. But similar approach can be taken to extend support for OpenBSD using the [hw.sensors.acpibat*](https://man.openbsd.org/acpibat.4) commands.

But in OpenBSD the [apm](https://man.openbsd.org/apm.8) tool is more user friendly and works out of the box unlike the former which requires us to calculate percentage from power usage.

**Comment by carlosala** [comment]
Hi! It's a super great idea! I don't use OpenBSD myself, could you create a PR for it? Thanks!

**Comment by im-notpua** [comment]
Yeah sure
