### ISSUE TITLE
docker.plugin.zsh no such file or directory

### ISSUE THREAD

**Issue by Jamesking56** [ohmyzsh/ohmyzsh#11866]
### Describe the bug

When I load up my terminal (WSL Ubuntu 22.04) I get this error appear:

```
/home/jamesking56/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker/docker.plugin.zsh:60: no such file or directory: /home/jamesking56/.antigen/bundles/robbyrussell/oh-my-zsh/cache//completions/_docker
```

### Steps to reproduce

Not sure how to reproduce, I would assume its just installing Antigen following their install instructions and enabling the `docker` plugin.

### Expected behavior

No error appears

### OS / Linux distribution

Ubuntu 22.04 inside WSL Windows 11

### Zsh version

5.8.1

### Terminal emulator

Windows Terminal

### If using WSL on Windows, which version of WSL

WSL2

### Additional context

Antigen v2.2.2

**Comment by Jamesking56** [comment]
I've just copied the missing file from here: https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker

and placed it in `~/.antigen/bundles/robbyrussell/oh-my-zsh/cache/completions` (I had to create the `completions` directory)

and the error message has now disappeared.

**Comment by DimaVIII** [comment]
If you come from google, here is the solution: 
```shell
mkdir ~/.antigen/bundles/robbyrussell/oh-my-zsh/cache/completions
```
(replace `robbyrussell`) with your theme. 

Doing `antigen update` and `omz update` did not fix the issue. @Jamesking56 @carlosala 

This issue still exists, for some reason my `completions/` dir was missing. After adding it, everything installed by itself and was fixed.
