### ISSUE TITLE
Secrets in History!

### ISSUE THREAD

**Issue by Paradoxer32** [ohmyzsh/ohmyzsh#11860]
### If the feature solves a problem you have, specify it here.

Hello, people.
Thank you for this great and fantastic shell !

Anyway, I've an idea for improve ZSH. It's little like security improve or something like this, but not exactly. 
Sometimes, we want to use a personal or secret phrase in our command line. For example: 
`[ZSH sample@host ]$  program --user IamUser --password 1234 --host 127.0.0.1 --port 7795  `
Here, I've a secret password. But ZSH like other shells adds this command in history.\
`[ZSH sample@host ]$  history`
`1    program --user IamUser --password 1234 --host 127.0.0.1 --port 7795`
And I want make my password hidden in my history.

### Describe the proposed feature.

Idea !
For example, we can use a 'secret' tag for hide password:
`[ZSH sample@host ]$  program --user IamUser --password <sec>1234<ret> --host 127.0.0.1 --port 7795  `
After that, history is like this:
`[ZSH sample@host ]$  history`
`1    program --user IamUser --password 1234 --host 127.0.0.1 --port 7795`
`2    program --user IamUser --password SECRET --host 127.0.0.1 --port 7795`

Have we had a tool or plugin do that? 
If we haven't, let's create it !

Have a nice time!

**Comment by carlosala** [comment]
You can tweak `zshaddhistory` hook to save, or not save, or save a modified text in hist file. [Here](https://zsh.sourceforge.io/Doc/Release/Functions.html#Hook-Functions) you have the docs!
This is something really personal I believe, so it's better to have it on your own config instead of here I'd say.
Thanks for the idea!
