### ISSUE TITLE
plugins/git-commit/git-commit.plugin.zsh:7: bad set of key/value pairs for associative array

### ISSUE THREAD

**Issue by hcharley** [ohmyzsh/ohmyzsh#11876]
### Describe the bug

When starting a new terminal session after enabling the `git-commit` plugin, this error occurs:

```
Last login: Tue Sep  5 11:52:40 on xxxxxxx
/Users/yyyyyyyy/.oh-my-zsh/plugins/git-commit/git-commit.plugin.zsh:7: bad set of key/value pairs for associative array
➜  zzzzzzzzzzzz git:(main) ✗
```

### Steps to reproduce

1. Enable `git-commit` plugin
2. Start a new terminal session
3. Observe error

### Expected behavior

`git-commit` plugin should work out of the box without reporting an error.

### OS / Linux distribution

Version 13.3.1 (a) (22E772610a)

### Zsh version

5.9

### Terminal emulator

iTerm 2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
It should be solved. Thanks for the report!
