### ISSUE TITLE
Fn 0 doesn't work for slash

### ISSUE THREAD

**Issue by pandasoli** [ohmyzsh/ohmyzsh#11877]
### Describe the bug

Maybe reopening [#8211](https://github.com/ohmyzsh/ohmyzsh/issues/8211).

I'm used to press `Fn + 0` to type `/` anywhere as I use a notebook.  
This is easier than:
1. Enabling NumLk
2. Pressing 0
3. Disabling NumLk

It works everywhere in any system.  
I've did it in **Bash**, _text boxes_, **Fish**, and also in **Zsh**.

But it doesn't work in oh-my-zsh.  
(And no, it's not about my terminal emulator)

The issue [#8211](https://github.com/ohmyzsh/ohmyzsh/issues/8211) was marked as `not our issue`, but I think that if it only happens in oh-my-zsh it is a unsupportable feature and should be supported even as a non-default feature.

I tried omz on Alacritty terminal and it worked fine.  
But anyway I think omz should support xfce-terminal.

### Steps to reproduce

Pressing `Fn + 0` (nothing happens...)

### Expected behavior

Appear `0` is pressed so, and appear `/` it pressed `Fn + 0`.

### OS / Linux distribution

Archcraft (6.4.12-arch1-1)

### Zsh version

5.9

### Oh My Zsh version

master (bae577d)

### Terminal emulator

xfce4-terminal

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
The' fn' key is handled outside of any terminal emulator. It's related to the keyboard; when pressed, it sends a single keycode to the terminal.
In both `alacritty` (which works) and `xfce4-terminal` (which doesn't work), could you press `Ctrl+v` and then `fn+0` and post the output here? We can debug it; let's see which keycode your keyboard sends to the terminal.

**Comment by pandasoli** [comment]
![Screenshot_2023-09-06-23-13-56_1366x768](https://github.com/ohmyzsh/ohmyzsh/assets/76575902/8240d184-0421-4109-b9c4-5ee08667cf7d)
The `xfce4-terminal` is on top.

> The' fn' key is handled outside of any terminal emulator.

It makes sense. It is handled by the hardware.  
But it doesn't explain why it works in the same terminal in **Bash** or in pure **Zsh**.

**Comment by carlosala** [comment]
Could you now repeat the same process, but executing previously `zsh -f` on each terminal?

**Comment by pandasoli** [comment]
![image](https://github.com/ohmyzsh/ohmyzsh/assets/76575902/6823cf37-20fa-45ee-8b0f-f319123eebc8)

**Alacritty**, **gnome-terminal**, **xfce4-terminal** and urxvt (from `rxvt-unicode` package).

I tried if before making this issue. The problem is not with zsh as it seems.

**Comment by carlosala** [comment]
That's extremely weird, being something that changes from term to term. I'd recommend you add `bindkey -s '^[0o' '/'`. It should solve your issues, and the terms that behave correctly should not be affected.

**Comment by pandasoli** [comment]
Solved! Thanks @carlosala.

Just put the following line in the `.zshrc`:
```bash
bindkey -s '^[Oo' '/'
```
> PS: It's a uppercase "o" letter, no a zero.
