### ISSUE TITLE
Allow use old gallois layout

### ISSUE THREAD

**Issue by Ostefanini** [ohmyzsh/ohmyzsh#11879]
### Describe the bug

It's the eigth year in a row that gallois is may day to day shell.

Iam very used to the layout with git branch on the right and no on the left.

Is there any chance to still have the possibility to use the old layout ? with a dedicated theme or a configuration ?

Thank you per avance

### Steps to reproduce

update ohmyzsh

### Expected behavior

ideally, bring back the old layout with a minimal configuration modification

### OS / Linux distribution

MacOS

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Hi Oscar!
Yes, there were significant changes to the `gallois` theme, done by @gallois, which I saw is the original creator of the theme. Feel free to submit a PR for both @Ostefanini and @gallois; I'll be happy to review it and eventually merge it!

**Comment by carlosala** [comment]
`oldgalois` theme has been added!

**Comment by leaf-potato** [comment]
> `oldgalois` theme has been added!

@carlosala It's `oldgallois` not `oldgalois`
