### ISSUE TITLE
feat(termsupport): Allow configurable terminal title patterns & cmdline truncation limits

### ISSUE THREAD

**Issue by trinitronx** [ohmyzsh/ohmyzsh#11875]
### If the feature request is for a plugin or theme, specify it here.

~_No response_~
N/A: Code is in core / [`lib/termsupport.zsh`](https://github.com/ohmyzsh/ohmyzsh/blob/ccce2e1cfdf5b9680f691a402e288d9cf6ce272a/lib/termsupport.zsh#L1-L110)

### Context for Use-Case:

Desktop environments that use tiling window managers (e.g. [i3][2], [sway][3], [hyprland][4], [river][5], and others) depend on window title for various things such as [window matching rules][6], [tab][7] & [workspace icons][8], [taskbar title rewriting][9], etc...  Adding icons based on window title makes it a lot easier and faster to visually pick out a window amongst many others.

Allowing for configurable window title would be a huge usability and UI/UX improvement for these desktop environments.  Given the above context, would you be willing to agree that allowing title customization would improve UI/UX for those environments?

### Describe the proposed feature.

Allow for configurable `ZSH_THEME_TERM_*TITLE*` settings, similar to proposal in #11870 

### Describe alternatives you've considered

Alternative feature proposal was in #11870

### Additional context

@mcornella:

Sorry for opening a new issue but GitHub would not allow me to respond in #11870 after it was closed.  So I'll try to respond to your comments here instead, and Thanks for the feedback!

> Doing so requires a level of hacky-ness that I don't really feel worth it or stylish, and is very coupled with the title logic.

Yeah, that's fair.  While I'd agree that POSIX shell syntax isn't the most stylish of languages in general... I'm not sure I'd agree that [setting a default if unset][1] is all that "hacky" per se...  Although I would agree that the "`${foo:-default-here}`" syntax when combined with ZSH's [Prompt Expansion / truncation behaviour][zsh-prompt-expansion] syntax together is rather esoteric.  It's a bit unfortunate that it starts to become less readable and look more like Perl than shell scripting 😂.  Perhaps another solution to make it more clear and readable might be to split it up into multiple lines?

For example:

```zsh
# Allow overriding these settings, but fallback to defaults if unset
...

_default_tab_title_idle='%15<..<%~%<<' #15 char left truncated PWD
ZSH_THEME_TERM_TAB_TITLE_IDLE="${ZSH_THEME_TERM_TAB_TITLE_IDLE:-$_default_tab_title_idle}"

...  # Do the same pattern for the rest
```

@mcornella, @carlosala:

> ... I think at this stage we are not looking at getting at such a fine-grained level of customization.
> ...
> We'll be looking in the future to revise this decision to see if we can improve this somehow.

I do hope this will be possible 😅

When I was looking at the `lib/termsupport.zsh` in #11868, I noticed that it seemed a bit strange for these variables being hard-coded and named `ZSH_THEME_TERM_*` as if the _original intent_ was to expose them as configurable theme settings.  I figured a quick fix would be to use the "set if unset" POSIX syntax, but maybe there's a better more stylish way? `¯\_(ツ)_/¯`

>  In the meantime, you can redefine the functions yourself in your zshrc file, or disable our solution by setting `DISABLE_AUTO_TITLE=true` and fully customize your logic while keeping compatibility with the title function.

Unfortunately, there are already [forked older versions of omz's title set behavior][manjaro-termsupport-fork] which are currently broken and don't actually set the title based on current running command.  Overriding both OMZ's `title` & `precmd` / `preexec` hooks and the copied & broken versions clutters and slows down the pre-installed Zsh hooks on these distros.  So far I've tried overriding both, but the result was not ideal.  My current workaround was to edit the OS-supplied file to disable their broken hooks, to get stock OMZ behavior only to find that this also didn't work for my use case requirements:

- Idle title with current working directory & longer truncation char limit
- Running command as title when not idle

It's rather unfortunate that the title setting behavior in OMZ isn't configurable and has a 15 character limit hard-coded by default.  Otherwise, this would have worked without modification to OMZ's internals.

[1]: https://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html#tag_02_06_02
[2]: https://i3wm.org/
[3]: https://swaywm.org/
[4]: https://hyprland.org/
[5]: https://github.com/riverwm/river
[6]: https://i3wm.org/docs/userguide.html#for_window
[7]: https://github.com/allie-wake-up/swaycons#why
[8]: https://github.com/Lyr-7D1h/swayest_workstyle#swayest-workstyle
[9]: https://github.com/Alexays/Waybar/wiki/Module:-Taskbar#rewrite-rules

[zsh-prompt-expansion]: https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html#Conditional-Substrings-in-Prompts
[manjaro-termsupport-fork]: https://github.com/Chrysostomus/manjaro-zsh-config/issues/46

### Related Issues

- #11870: Proposed PR for this feature implementation (Closed, but couldn't respond there)

**Comment by willenglishiv** [comment]
not to necro this thread but before I create a new one..

Is there a way to go back to the default title settings? Say like in ubuntu?

I tried to use one of the flags to disable title updates and it did not work as intended.
