### ISSUE TITLE
completion error with cargo command (rust)

### ISSUE THREAD

**Issue by keldonin** [ohmyzsh/ohmyzsh#11889]
### Describe the bug

On my computer (MacOS Monterey), calling completion with cargo by hitting on <TAB> triggers the following error:

```
$ cargo error: couldn't read +stable-x86_64-apple-darwin: No such file or directory (os error 2)

error: aborting due to previous error


_cargo:source:2: no such file or directory: /share/zsh/site-functions/_cargo
error: couldn't read +stable-x86_64-apple-darwin: No such file or directory (os error 2)

error: aborting due to previous error

_cargo:source:2: no such file or directory: /share/zsh/site-functions/_cargo
error: couldn't read +stable-x86_64-apple-darwin: No such file or directory (os error 2)

error: aborting due to previous error

_cargo:source:2: no such file or directory: /share/zsh/site-functions/_cargo
$ cargo
```

Note that this error occurs whether or not the `rust` plugin is loaded.

Obviously, the path `/share/zsh/site-functions/_cargo` does not exists.

Any clue?

### Steps to reproduce

1. Have rust deployed via `rustup` (default install, follow instructions on [https://rustup.rs/])
2. from ZSH+OMZ, invoke `cargo ` and press `<TAB>` for completion

### Expected behavior

ZSH should show the completion list.

### OS / Linux distribution

macOS 12.6.9

### Zsh version

5.8.1

### Oh My Zsh version

master (01f5512)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Could you post the output of `command -v cargo rustup rustc`?
In the meantime, try to do `rm -rf $ZSH_COMPDUMP $ZSH_CACHE_DIR/completions/_(cargo|rustup)`. It seems like your installation got corrupted or something like that.

**Comment by keldonin** [comment]
Here is the output:

```
command -v cargo rustup rustc
/Users/keldonin/homebrew/bin/cargo
/Users/keldonin/.cargo/bin/rustup
/Users/keldonin/homebrew/bin/rustc
```

Note that my brew install is a non-admin one, i.e. 
```
command -v brew
/Users/l203663/homebrew/bin/brew
```
Clearing the cache as suggested didn't solve the issue.

**Comment by carlosala** [comment]
It seems that you have some binaries installed with homebrew, but you still installed rustup. If you want to use `homebrew` to manage your rust installation, you should remove the `~/.cargo` directory and `~/.rustup` to make sure you reset the environment and it uses the `homebrew` installation. If you prefer to use rustup, then uninstall Rust packages from homebrew.
After using just one system, it should work out of the box. Feel free to reopen if you still have issues!

**Comment by keldonin** [comment]
Hi @carlosala , good spot, this was the issue. Thank you for your support!
