### ISSUE TITLE
Always trying to update although updates are turned of

### ISSUE THREAD

**Issue by cemkoker** [ohmyzsh/ohmyzsh#11906]
### Describe the bug

I have

`DISABLE_UPDATE_PROMPT=true
DISABLE_AUTO_UPDATE=true
`

in .zshrc; although it still keeps running xcodebuild at startup trying to find some update.

### Steps to reproduce

Add 
`DISABLE_UPDATE_PROMPT=true
DISABLE_AUTO_UPDATE=true
`

To .zshrc, open a few times, a few days - at some point it will trigger xcodebuild.

### Expected behavior

No update

### OS / Linux distribution

macOS 13.5.2 (22G91)

### Zsh version

5.9

### Terminal emulator

Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
I do recommend you use the new way to configure `omz`'s autoupdate, you can see the docs [here](https://github.com/ohmyzsh/ohmyzsh?tab=readme-ov-file#getting-updates).
Even though, `DISABLE_AUTO_UPDATE=true` only disables updates for `omz`, it has nothing to do with `xcode`.
Thanks!

**Comment by cemkoker** [comment]
Well. No.

Current .zshrc
<img width="299" alt="CleanShot 2023-10-03 at 19 03 36" src="https://github.com/ohmyzsh/ohmyzsh/assets/13544103/db8bef14-da35-49ed-9dd5-fd3fbf4b55ba">

Today's prompt:
<img width="416" alt="CleanShot 2023-10-03 at 19 04 10" src="https://github.com/ohmyzsh/ohmyzsh/assets/13544103/94f424ef-dc19-4ecb-afa4-e2544f89555d">

So indeed this parameters have absolutely no effect, it keeps asking for update. Please re-open.

**Comment by carlosala** [comment]
Make sure you define that before sourcing oh-my-zsh.sh

**Comment by cemkoker** [comment]
![CleanShot 2024-02-12 at 12 43 27@2x](https://github.com/ohmyzsh/ohmyzsh/assets/13544103/799b0917-038d-4792-8607-11046e6326fd)

**Comment by cemkoker** [comment]
Clearly no, and still not solved. Each time ohmzsh try to do somethng with xcodebuild although updates are off.

**Comment by carlosala** [comment]
We're indeed accessing `git` to see if anything has changed, and we need to rebuild the completion system. It shouldn't be slow, and it's indeed not our issue since we rely on `git` to do our checks. You can see [here](https://stackoverflow.com/questions/65846945/terminal-slow-to-start-first-time-due-to-xcodebuild) which solutions people give.
Thanks for your report!
