### ISSUE TITLE
Stucked after installation

### ISSUE THREAD

**Issue by Shiyang980713** [ohmyzsh/ohmyzsh#11905]
### Describe the bug

The installation is stucked. When I restart a session, the default shell is still bash. its in a docker instance.

### Steps to reproduce

I just follow the standard installation procedure

### Expected behavior

The installation should be success, and omz should be applied.

### Screenshots and recordings

<img width="830" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/57209725/b1ef47c8-0c90-41f9-84f3-a1dab4f1f1a1">

### OS / Linux distribution

Ubuntu 18.04.6 LTS (GNU/Linux 5.15.0-72-generic x86_64)

### Zsh version

5.4.2

### Terminal emulator

tabby.app

### If using WSL on Windows, which version of WSL

None

**Comment by sujalcodes3** [comment]
Can I work on this issue ? But i would need some guidance

**Comment by carlosala** [comment]
You need to log out and log in once again. Your shell should be `zsh` then. It's an expected behaviour.
Thanks for your report!
