### ISSUE TITLE
Gradle plugin should not lookup `settings.gradle` and `settings.gradle.kts`

### ISSUE THREAD

**Issue by piotrminkina** [ohmyzsh/ohmyzsh#11916]
Consider the following case:

```
gradle/
  wrapper/
plugin/
  build.gradle
  settings.gradle
build.gradle
gradlew
gradlew.bat
settings.gradle
```

```
# settings.gradle
pluginManagement {
    includeBuild('plugin/')
}
```

In the above case, it is not possible to call the `gradle` alias when I'm in the `plugin` directory, for the reason that the script breaks the search for the `gradlew` script because it has found the `settings.gradle` file. In the following condition, the script should only check for the existence of the `gradlew` file and possibly whether it has the executable bit set, but nothing more.

https://github.com/ohmyzsh/ohmyzsh/blob/0e1e877ea9182f87b3ab34cbc2ea944b34f5345e/plugins/gradle/gradle.plugin.zsh#L9

Greetings
Piotr Minkina

**Comment by mcornella** [comment]
Makes sense, thanks for the great explanation. You've already identified the fix, care to submit a quick PR?

**Comment by piotrminkina** [comment]
@mcornella done :)
