### ISSUE TITLE
Add zprofile support

### ISSUE THREAD

**Issue by HarryHeres** [ohmyzsh/ohmyzsh#11926]
### If the feature solves a problem you have, specify it here.

Wouldn’t it be great if the generated `.zshrc` file already contained an include of .zprofile files? 

### Describe the proposed feature.

Add following if statement to the generated `.zshrc`

```
if [ -f ~/.zprofile ]; then
	. ~/.zprofile
fi
```

**Comment by carlosala** [comment]
`.zprofile` is loaded by default if the shell is a login shell. You can see the docs [here](https://zsh.sourceforge.io/Doc/Release/Files.html#Startup_002fShutdown-Files)

**Comment by HarryHeres** [comment]
Oh sorry, missed that bit!
