### ISSUE TITLE
zoom in or out bug

### ISSUE THREAD

**Issue by abuhabban** [ohmyzsh/ohmyzsh#11936]
### Describe the bug

whenever i zoom in or zoom out an inch it gets disturbed. icons copied many times see screenshot 

### Steps to reproduce

noidea

### Expected behavior

clean

### Screenshots and recordings

![Screenshot_20231006_223853_Termux](https://github.com/ohmyzsh/ohmyzsh/assets/70461458/326fd39c-c9f5-4657-bd13-a6cf8e5c6be3)

### OS / Linux distribution

Device:- samsung a14 5g

### Zsh version

current

### Terminal emulator

termux

### If using WSL on Windows, which version of WSL

None

**Comment by robbyrussell** [comment]
I believe this might be more of a terminal emulator issue vs an Oh My Zsh issue (as OMZ doesn't redraw itself). 

If you change the theme to the default (mine), do you see similar behavior? and/or if you test without Oh My Zsh?

**Comment by carlosala** [comment]
Yep, it's expected if the terminal does not adjust it when resizing.

**Comment by mcornella** [comment]
Also this is expected behavior when resizing the terminal / changing zoom settings, please read https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window for full context.
