### ISSUE TITLE
Debian plugin variable override clarification

### ISSUE THREAD

**Issue by martinsolberg** [ohmyzsh/ohmyzsh#11959]
### Describe the bug

The readme for the debian plugin states:

>     $apt_pref: use aptitude or apt if installed, fallback is apt-get.
>     $apt_upgr: use upgrade or safe-upgrade (for aptitude).
> 
> Set $apt_pref and $apt_upgr to whatever command you want (before sourcing Oh My Zsh) to override this behavior.

If only one of the variables are set prior to sourcing, it will be overridden. Either explicitly state that both need to be set in the readme, or, preferably, change the behavior. E.g. like this:

```
if [[ -z $apt_pref || -z $apt_upgr ]]; then
    if [[ -z $apt_pref ]]; then	 
    	if [[ -e $commands[aptitude] ]]; then
      	  apt_pref='aptitude'
    	elif [[ -e $commands[apt] ]]; then
     	   apt_pref='apt'
    	else
      	  apt_pref='apt-get'
    	fi
    fi
    if [[ -z $apt_upgr ]]; then	 
    	if [[ -e $commands[aptitude] ]]; then
      	  apt_upgr='safe-upgrade'
    	elif [[ -e $commands[apt] ]]; then
     	   apt_upgr='upgrade'
    	else
      	  apt_upgr='upgrade'
    	fi
    fi
fi
```

### Steps to reproduce

1. Enable 'debian'
2. Set either _apt_pref_ OR _apt_upgr_ to something other than the default
3. Start zsh
4. The setting is now overridden

### Expected behavior

Readme should clarify that both variables need to be set, or plugin should respect the variable set

### OS / Linux distribution

MX Linux 23

### Zsh version

5.9

### Oh My Zsh version

master (6768906)

### Terminal emulator

xfce4-terminal

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Thanks for the report! I clarified the docs, as otherwise it would not be easy to explain what the defaults are for setting just one of the variables, because of the added complexity in checking commands.
