### ISSUE TITLE
performance regression in `gbda`

### ISSUE THREAD

**Issue by alicanb** [ohmyzsh/ohmyzsh#11985]
### Describe the bug

The implementation of `gbda` in https://github.com/ohmyzsh/ohmyzsh/pull/11948 is very slow. Here are some numbers, at least for my repo:
```zsh
$ time (gbda) 
( gbda; )  33.33s user 3.38s system 98% cpu 37.437 total
$ time (git branch --no-color --merged | command grep -vE "^([+*]|\s*($(git_main_branch)|$(git_develop_branch))\s*$)" | command xargs git branch --delete 2>/dev/null)
( git branch --no-color --merged | command grep -vE  | command xargs git   2>)  0.13s user 0.07s system 67% cpu 0.294 total
```

### Steps to reproduce

1. omz post https://github.com/ohmyzsh/ohmyzsh/pull/11948 version
2. enable git plugin
3. `time (gbda)`

### Expected behavior

new implementation should not be that slower (I am observing about ~120x difference)  

### OS / Linux distribution

macOS 13.6

### Zsh version

5.9

### Terminal emulator

iterm2

### If using WSL on Windows, which version of WSL

None

**Comment by alicanb** [comment]
Hello, thanks for the reply. It is indeed probably due to the size of my repo, it's a monorepo with ~40k commits. So there is no "hanging" per se, just too many refs. (that's what the tracing shows as well) 

Not sure what's the correct action to take here tbh, for my repo it looks like I have to use the old implementation, so I'm just gonna alias that in my zshrc and I'm ok with that. Maybe some optimization can be done like, "if number of commits > some number, use old implementation, else use the new one"?

**Comment by carlosala** [comment]
I still can't reproduce in a big repo. It would be great to get the tracing to try to debug it. Could you record an asciinema like [this one](https://asciinema.org/a/615188)?
Thanks!
