### ISSUE TITLE
.oh-my-zsh: No such file or directory

### ISSUE THREAD

**Issue by usuryadevara** [ohmyzsh/ohmyzsh#12009]
### Describe the bug

```
 sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
Cloning Oh My Zsh...
environment: line 299: cd: /c/Users/userprofile/.oh-my-zsh: No such file or directory
Error: git clone of oh-my-zsh repo failed
```

windows 11: 
 git -v
git version 2.42.0.windows.2

zsh --version
zsh 5.9 (x86_64-pc-msys)

### Steps to reproduce

i install git bash version 2.42.0.windows.2 then installed zsh 5.9 and then zssh terminal and running that  `sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`

### Expected behavior

it should install oh-my-zsh

### Screenshots and recordings

n/A

### OS / Linux distribution

windows 11

### Zsh version

5.9

### Oh My Zsh version

master

### Terminal emulator

git bash

### If using WSL on Windows, which version of WSL

None

### Additional context

```
 sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
Cloning Oh My Zsh...
environment: line 299: cd: /c/Users/userprofile/.oh-my-zsh: No such file or directory
Error: git clone of oh-my-zsh repo failed
```

windows 11: 
 git -v
git version 2.42.0.windows.2

zsh --version
zsh 5.9 (x86_64-pc-msys)

**Comment by usuryadevara** [comment]
I even tried creating a folder .oh-my-zsh and then it says 

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
The $ZSH folder already exists (/c/Users/userprofile/.oh-my-zsh).
You'll need to remove it if you want to reinstall.

**Comment by mcornella** [comment]
Hello @usuryadevara, unfortunately we are not in a position to support Git Bash or other less common Windows shells. I'd advise you to use WSL2 instead.
