### ISSUE TITLE
compinit:527: no such file or directory: /usr/local/share/zsh/site-functions/_docker_compose

### ISSUE THREAD

**Issue by Talljack** [ohmyzsh/ohmyzsh#12002]
### Describe the bug

When I open zsh on vs code terminal, the warning `compinit:527: no such file or directory: /usr/local/share/zsh/site-functions/_docker_compose` appear on it.
I saw [an issue](https://github.com/ohmyzsh/ohmyzsh/issues/9602) is the same as mine, but it doesn't work.

### Steps to reproduce

1. open vs code project
2. open terminal(default use zsh)
3. show `compinit:527: no such file or directory: /usr/local/share/zsh/site-functions/_docker_compose`

### Expected behavior

I want to don't show it on my terminal.
Thank you.

### OS / Linux distribution

macOS ventura 13.4.1

### Zsh version

5.9

### Oh My Zsh version

master (1c55a0fe)

### Terminal emulator

VS Code terminal

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Running `brew cleanup && rm -f $ZSH_COMPDUMP && omz reload` should solve the issue.

**Comment by Talljack** [comment]
> Running `brew cleanup && rm -f $ZSH_COMPDUMP && omz reload` should solve the issue.

When I run a command it appears, and a new terminal also has it.
<img width="983" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/34439652/d1f4cb4d-e357-41fe-8a9c-61b11d1e4df5">

**Comment by carlosala** [comment]
Could you post the output of `ls - l /usr/share/zsh/site-functions/_docker-compose`?

**Comment by mcornella** [comment]
Try `rm $_comp_dumpfile` as well.

**Comment by Talljack** [comment]
> rm $_comp_dumpfile

No
<img width="368" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/34439652/92029069-0798-45a8-ab37-4d1eebf8697a">

**Comment by Talljack** [comment]
> Try `rm $_comp_dumpfile` as well.

I did it, but when I opened a new terminal still appeared it.
<img width="367" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/34439652/814d1d3f-2743-46d1-8d3f-de7877e9e492">
<img width="1016" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/34439652/6506a13c-a741-4081-93f7-1e8d5eff81ba">

**Comment by carlosala** [comment]
Sorry, it's `ls - l /usr/local/share/zsh/site-functions/_docker-compose`

**Comment by Talljack** [comment]
No, the file or directory doesn't exists

**Comment by carlosala** [comment]
Could you share your zshrc?

**Comment by LuoJimmy** [comment]
I have a similar problem！

compinit:527: no such file or directory: /usr/local/share/zsh/site-functions/_brew_cask

<img width="980" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/7272363/b846cf88-29ae-4e77-ba02-f37f56a297b6">

**Comment by mcornella** [comment]
@Talljack try the code below and also tell us whether you changed your Homebrew setup from Intel to ARM as [this user found](https://stackoverflow.com/a/67808050):

```sh
ls -l /usr/local/share/zsh/site-functions/_docker_compose
ls -l /usr/local/share/zsh/site-functions/_docker_compose(:A)
```

@LuoJimmy try `brew cleanup` as in https://github.com/ohmyzsh/ohmyzsh/issues/9602#issuecomment-768663375.

**Comment by Talljack** [comment]
This is the result of execute code
<img width="1511" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/34439652/c6b9ad4d-a112-4466-a63a-57d080d5e1e5">
You are right, I updated my MAC system from Intel to ARM(change my MAC), but it was three months ago, and the problem only appeared recently.

**Comment by LuoJimmy** [comment]
> @Talljack try the code below and also tell us whether you changed your Homebrew setup from Intel to ARM as [this user found](https://stackoverflow.com/a/67808050):
> 
> ```shell
> ls -l /usr/local/share/zsh/site-functions/_docker_compose
> ls -l /usr/local/share/zsh/site-functions/_docker_compose(:A)
> ```
> 
> @LuoJimmy try `brew cleanup` as in [#9602 (comment)](https://github.com/ohmyzsh/ohmyzsh/issues/9602#issuecomment-768663375).

Thank you very much!
I solved it by this:
`
ln -fsv /opt/homebrew/completions/zsh/_brew /usr/local/share/zsh/site-functions/_brew_cask
ln -fsv /opt/homebrew/completions/zsh/_brew /usr/local/share/zsh/site-functions/_brew
`

**Comment by mcornella** [comment]
> This is the result of executing code <img alt="image" width="1511" src="https://user-images.githubusercontent.com/34439652/278180037-c6b9ad4d-a112-4466-a63a-57d080d5e1e5.png"> You are right, I updated my MAC system from Intel to ARM(change my MAC), but it was three months ago, and the problem only appeared recently.

Possibly you're hit by https://github.com/docker/for-mac/issues/6343 and you updated Docker recently. The right path should be in `/Applications/Docker.app/Contents/Resources/etc/docker` (try looking on that path and finding the right file), or otherwise not exist under that path (in which case, you should remove the symlink).

Confirmed not happening because of OMZ.

**Comment by ThisIsMissEm** [comment]
Just wanted to say that:
```sh
brew cleanup && rm -f $ZSH_COMPDUMP && omz reload
```

As suggested by @carlosala initially resolved this issue for me.

**Comment by wanqian-windrunner** [comment]
I'm having a similar problem on `wsl`, I'm getting the following error: `coinit:527: no such file or directory: /usr/share/zsh/vendor-completions/_docker`
The cause of my problem is that the file `/usr/share/zsh/vendor-completions/_docker` is softlinked to `/mnt/wsl/docker-desktop/cli-tools/usr/share/zsh/vendor-completions/_docker`, and my docker-desktop was uninstalled, when I looked at the directory /usr/share/zsh/vendor-completions/ I found the _docker file was red, so I just needed to delete this file and everything worked fine!
```zsh
sudo rm /usr/share/zsh/vendor-completions/_docker
```

**Comment by maximaging** [comment]
https://github.com/ohmyzsh/ohmyzsh/issues/12002#issuecomment-1913186028

Encountered the same issue following a Docker Desktop update. Your suggestion worked.

Reported error: `compinit:503: no such file or directory: /usr/share/zsh/vendor-completions/_docker`

The symbolic link `/mnt/wsl/docker-desktop/cli-tools/usr/share/zsh/vendor-completions/_docker` became broken after a Docker Desktop update (Docker Desktop 4.27.1, build 136059). I did not manage to find a new target in `/mnt/wsl/docker-desktop/cli-tools` so I removed the symlink.

**Comment by yaoliangcui** [comment]
遇到了类似问题，已解决；

# 报错
运行
`brew doctor && brew cleanup && source ~/.zshrc`
报错
`compinit:527: no such file or directory: /usr/local/share/zsh/site-functions/_brew`
`compinit:527: no such file or directory: /usr/local/share/zsh/site-functions/_brew_services`

# 定位
查看该文件指向的软链
`ls -l /usr/local/share/zsh/site-functions/_brew`
找到原因，'/site-functions/_brew'是指向了一个不存在的路径(不确定这里的软链是咋来的)
`/usr/local/share/zsh/site-functions/_brew -> ../../../Homebrew/completions/zsh/_brew`

# 解决
### 先找到brew安装目录'/opt/homebrew/'，再向下进入'/completions/zsh/'，ls发现有'_brew'文件，建立正确软链
`ln -fsv /opt/homebrew/completions/zsh/_brew /usr/local/share/zsh/site-functions/_brew`

### 至此第一个报错已解决，要想解决第二个，得先看下是否安装了'brew_services'
运行该命令，未安装会自动安装；
`brew services`
获取到安装路径
`Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-services'...`

### 再来一次找'_brew_services'，先cd到'/opt/homebrew/Library/Taps/homebrew/homebrew-services/'，再向下进入'/completions/zsh/'，ls发现有'_brew_services'文件，建立正确软链
`ln -fsv /opt/homebrew/Library/Taps/homebrew/homebrew-services/completions/zsh/_brew_services /usr/local/share/zsh/site-functions/_brew_services`

### 再次运行检查
`brew doctor && brew cleanup && source ~/.zshrc`
无报错
`Your system is ready to brew.`

**Comment by decoycircuit** [comment]
I'm on Windows10 using `WSL2` and have `Docker Desktop` installed.

If I start the terminal before Docker Desktop, I get the `compinit:527` error.

If I simply start `Docker Desktop` before the terminal, the error is not there.

**Comment by jyellow** [comment]
> 遇到了类似问题，已解决；
> 
> # 报错
> 运行 `brew doctor && brew cleanup && source ~/.zshrc` 报错 `compinit:527: no such file or directory: /usr/local/share/zsh/site-functions/_brew`
> 
> # 定位
> 查看该文件指向的软链 `ls -l /usr/local/share/zsh/site-functions/_brew` 找到原因，'/site-functions/_brew'是指向了一个不存在的路径(不确定这里的软链是咋来的) `/usr/local/share/zsh/site-functions/_brew -> ../../../Homebrew/completions/zsh/_brew`
> 
> # 解决
> ### 先找到brew安装目录'/opt/homebrew/'，再向下进入'/completions/zsh/'，ls发现有'_brew'文件，建立正确软链
> `ln -fsv /opt/homebrew/completions/zsh/_brew /usr/local/share/zsh/site-functions/_brew`
> 
> ### 至此第一个报错已解决，要想解决第二个，得先看下是否安装了'brew_services'
> 运行该命令，未安装会自动安装； `brew services` 获取到安装路径 `Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-services'...`

this work, thanks. @yaoliangcui

**Comment by mpurusottamc** [comment]
> 遇到了类似问题，已解决；
> 
> # 报错
> 运行 `brew doctor && brew cleanup && source ~/.zshrc` 报错 `compinit:527: no such file or directory: /usr/local/share/zsh/site-functions/_brew` `compinit:527: no such file or directory: /usr/local/share/zsh/site-functions/_brew_services`
> 
> # 定位
> 查看该文件指向的软链 `ls -l /usr/local/share/zsh/site-functions/_brew` 找到原因，'/site-functions/_brew'是指向了一个不存在的路径(不确定这里的软链是咋来的) `/usr/local/share/zsh/site-functions/_brew -> ../../../Homebrew/completions/zsh/_brew`
> 
> # 解决
> ### 先找到brew安装目录'/opt/homebrew/'，再向下进入'/completions/zsh/'，ls发现有'_brew'文件，建立正确软链
> `ln -fsv /opt/homebrew/completions/zsh/_brew /usr/local/share/zsh/site-functions/_brew`
> 
> ### 至此第一个报错已解决，要想解决第二个，得先看下是否安装了'brew_services'
> 运行该命令，未安装会自动安装； `brew services` 获取到安装路径 `Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-services'...`
> 
> ### 再来一次找'_brew_services'，先cd到'/opt/homebrew/Library/Taps/homebrew/homebrew-services/'，再向下进入'/completions/zsh/'，ls发现有'_brew_services'文件，建立正确软链
> `ln -fsv /opt/homebrew/Library/Taps/homebrew/homebrew-services/completions/zsh/_brew_services /usr/local/share/zsh/site-functions/_brew_services`
> 
> ### 再次运行检查
> `brew doctor && brew cleanup && source ~/.zshrc` 无报错 `Your system is ready to brew.`

This worked. Thanks @yaoliangcui

**Comment by hooiling513** [comment]
In my case, my `/opt/homebrew/Library/Taps/homebrew/homebrew-services/README.md` reads that `Homebrew Services (deprecated)` has been moved into brew, so i simply removed my `_brew_services` by 

```
rm /opt/homebrew/share/zsh/site-functions/_brew_services
```

**Comment by ThisIsMissEm** [comment]
> In my case, my `/opt/homebrew/Library/Taps/homebrew/homebrew-services/README.md` reads that `Homebrew Services (deprecated)` has been moved into brew, so i simply removed my `_brew_services` by
> 
> ```
> rm /opt/homebrew/share/zsh/site-functions/_brew_services
> ```

Also do `brew untap homebrew/services` but you've still got to remove that brew services file manually

**Comment by empeje** [comment]
> Just wanted to say that:
> 
> brew cleanup && rm -f $ZSH_COMPDUMP && omz reload
> As suggested by [@carlosala](https://github.com/carlosala?rgh-link-date=2023-11-05T17%3A03%3A45.000Z) initially resolved this issue for me.

If you're not using omz, it might just be

> `brew cleanup && rm -f $ZSH_COMPDUMP`

**Comment by shashinvision** [comment]
> brew cleanup && rm -f $ZSH_COMPDUMP && omz reload

Work for me on Mac M3, Thanks

**Comment by gthaka** [comment]
> brew cleanup && rm -f $ZSH_COMPDUMP && omz reload

This worked for me on MacBook M4 Pro, Thanks

**Comment by DG9Jww** [comment]
> brew cleanup && rm -f $ZSH_COMPDUMP

Work for me.

**Comment by Dowwie** [comment]
worked for me:  `brew reinstall zsh-completions`

**Comment by Jsmond2016** [comment]
This worked for me from the image below.

![Image](https://github.com/user-attachments/assets/bcff823c-2a27-4a05-8dc8-861ffed3ebf8)

https://stackoverflow.com/questions/65747286/zsh-problem-compinit503-no-such-file-or-directory-usr-local-share-zsh-site

**Comment by Cyame** [comment]
> Error: `compinit:527: no such file or directory: /usr/local/share/zsh/site-functions/_brew_services`
> 
> This worked for me from the image below.
> 
> ![Image](https://github.com/user-attachments/assets/bcff823c-2a27-4a05-8dc8-861ffed3ebf8)
> 
> https://stackoverflow.com/questions/65747286/zsh-problem-compinit503-no-such-file-or-directory-usr-local-share-zsh-site

same issue, use

```
brew cleanup && rm -f $ZSH_COMPDUMP && omz reload
```

solves everything, great thanks.

**Comment by euanguo** [comment]
> Running `brew cleanup && rm -f $ZSH_COMPDUMP && omz reload` should solve the issue.运行 `brew cleanup && rm -f $ZSH_COMPDUMP && omz reload` 应该可以解决该问题。

Work for me on Mac M3 Pro, Thanks

**Comment by DanHazard** [comment]
I have tried everything here and nothing is working.  Migrated from Intel to Apple Silicon.

**Comment by MatzeKitt** [comment]
For me, the symlink was wrong:

```
$ ls -l /usr/local/share/zsh/site-functions/
total 0
lrwxr-xr-x  1 matze  admin  39 Dec 29  2016 _brew -> ../../../Homebrew/completions/zsh/_brew
lrwxr-xr-x  1 matze  admin  88 Jun 11  2020 _brew_services -> ../../../Homebrew/Library/Taps/homebrew/homebrew-services/completions/zsh/_brew_services
```

Both files were not available in these paths.

I unlinked both:

```
unlink /usr/local/share/zsh/site-functions/_brew
unlink /usr/local/share/zsh/site-functions/_brew_services
```

… and linked the one manually that was available:

```
ln -s /opt/homebrew/completions/zsh/_brew /usr/local/share/zsh/site-functions/_brew
```
