### ISSUE TITLE
Directory Error

### ISSUE THREAD

**Issue by abhacker01** [ohmyzsh/ohmyzsh#12008]
### Describe the bug

It's not working with official packages installation of Kal linux

### Steps to reproduce

For Example:
1- make the update of directories 

### Expected behavior

It's not working 

### OS / Linux distribution

Kali Linux 

### Zsh version

5.6

### Terminal emulator

GNOME Terminal 

### If using WSL on Windows, which version of WSL

WSL1

**Comment by carlosala** [comment]
Could you please provide more information on how to reproduce the bug that you mentioned?

**Comment by abhacker01** [comment]
It's packages not completely working with Kali Linux root terminal
