### ISSUE TITLE
git-commit plugin's "revert" is in conflict with "git revert" command

### ISSUE THREAD

**Issue by yf-yang** [ohmyzsh/ohmyzsh#12007]
### Describe the bug

After enable git-commit, "git revert 'message'" won't work because "git revert" is a git command.

### Steps to reproduce

1. Enable plugin 'git-commit'
2. Add something by 'git add'
3. Try to make a commit with "git revert 'msg'"

### Expected behavior

By typing "git someAlternativeRevert 'msg'", it generates a commit message "revert: msg"

### OS / Linux distribution

Unrelated

### Zsh version

5.8.1

### Oh My Zsh version

master (01f55123)

### Terminal emulator

Unrelated

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Fixed in 048455cc, now you should use `git rev` instead, as [there is no way around the naming conflict](https://stackoverflow.com/a/3538791).

Thanks for reporting!
