### ISSUE TITLE
Vault plugin on macOS with Apple silicon CPU's

### ISSUE THREAD

**Issue by Szparki** [ohmyzsh/ohmyzsh#12004]
### Describe the bug

The Vault plugin is looking for vault's binary under`/usr/local/sbin/vault`. On Apple computers with M1/M2 processors if Vault was installed using Homebrew the location is `/opt/homebrew/bin/vault`
```
❯ source ~/.zshrc
❯ vault compgen:96: no such file or directory: /usr/local/sbin/vault
compgen:96: no such file or directory: /usr/local/sbin/vault
```
An easy workaround is:
```
❯ sudo mkdir /usr/local/sbin
❯ sudo ln -s /opt/homebrew/bin/vault /usr/local/sbin/vault
```

### Steps to reproduce

add vault to plugins in ~/.zshrc
source ~/.zshrc

### Expected behavior

If /usr/local/sbin/vault does not exists warn about it, suggest the above workaround, fix

### OS / Linux distribution

macOS Ventura 13.6

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by mkmkme** [comment]
I'd say it shouldn't suggest a workaround but rather search also in `/opt/homebrew/bin` because it's a standard location for homebrew binaries on Apple Silicon

**Comment by carlosala** [comment]
`vault` plugin does not search for anything, nor executes vault. `vault` plugin only adds completion statically. Even more, [it's actually deprecated](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/vault). Make sure you're not calling `/usr/local/sbin/vault` in your `zshrc`.
