### ISSUE TITLE
wd parse error near

### ISSUE THREAD

**Issue by matheus-ribeiro-azion** [ohmyzsh/ohmyzsh#12017]
### Describe the bug

When I type any wd command the error occurs.

### Steps to reproduce

1. Enable plugin wd
2. Run command wd
3. See error /path/.oh-my-zsh/plugins/wd/wd.sh:399: parse error near `]]'

### Expected behavior

It is expected that the plugin does not present an error when executed and allows its use.

### OS / Linux distribution

MacOs Sonoma / Linux Centos 7

### Zsh version

MacOs Sonoma = 5.9 / CentOS 7 = 5.0.2

### Oh My Zsh version

master (18e7e5d)

### Terminal emulator

MacOS = iTerm2 / CentOS 7 = bash

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
I can't reproduce on latest oh-my-zsh. Could you update your `oh-my-zsh` version? I see you are in a pretty old version. You can do it with `omz update`.

**Comment by matheus-ribeiro-azion** [comment]
`/dsv git:(dev) ✗ omz update
Updating Oh My Zsh
         __                                     __
  ____  / /_     ____ ___  __  __   ____  _____/ /_
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
                        /____/

Oh My Zsh is already at the latest version.

To keep up with the latest news and updates, follow us on Twitter: https://twitter.com/ohmyzsh
Want to get involved in the community? Join our Discord: https://discord.gg/ohmyzsh
Get your Oh My Zsh swag at: https://shop.planetargon.com/collections/oh-my-zsh
➜  /dsv git:(dev) ✗
➜  /dsv git:(dev) ✗
➜  /dsv git:(dev) ✗ wd
/root/.oh-my-zsh/plugins/wd/wd.sh:399: parse error near `]]'`

**Comment by carlosala** [comment]
Could you tell me what `cd $ZSH; pwd; git status; git rev-parse HEAD` outputs?

**Comment by matheus-ribeiro-azion** [comment]
cd $ZSH
pwd
/root/.oh-my-zsh

git status
# On branch master
nothing to commit, working directory clean

git rev-parse HEAD
38c01a235fef0d990be5ece0d62f94fd06b10571

**Comment by carlosala** [comment]
I am able to reproduce on `zsh` versions prior `5.0.6`. The problem is that the syntax `[[ 1 ]]` is invalid, that's why it is failing.
Could you `omz pr test 12019` and check if it's working there?
Then, when doing exit in your terminal, make sure to accept going back to the previous branch.
Thanks!

**Comment by matheus-ribeiro-azion** [comment]
omz pr test 12019
_omz::pr::test:27: read-only variable: _
omz::pr::test: running `zsh` to test the changes. Run `exit` to go back.

**Comment by matheus-ribeiro-azion** [comment]
This fix worked like a charm.

**Comment by carlosala** [comment]
Cool! Already merged on master, running `omz update` should fix it!
