### ISSUE TITLE
git branch command not working

### ISSUE THREAD

**Issue by vishal-sharma-369** [ohmyzsh/ohmyzsh#12022]
### Describe the bug

git branch gives nothing in response

### Steps to reproduce

On zsh
run: `git branch`

### Expected behavior

It should return a list of all the git branches in the git repository

### OS / Linux distribution

Linux fedora 6.5.7-200.fc38.x86_64

### Zsh version

5.9

### Terminal emulator

GNOME Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
What's the output that you get? Make sure you are in a git repo.

**Comment by carlosala** [comment]
Closing, since it's not our issue for sure.
