### ISSUE TITLE
% sign getting added at the end of print statements in rust program output

### ISSUE THREAD

**Issue by vishal-sharma-369** [ohmyzsh/ohmyzsh#12021]
### Describe the bug

When executing the code: 

`
fn main()
{
    let concat = format!("{} {}" , "first".to_string() , "name".to_string());
    print!("{}" , concat);
}
`

Output is: 
`
first name%                                                                           
`

As you can see, a % sign is getting appended at the end of the line

### Steps to reproduce

1. Create a new cargo project/package
2. In the main.rs file paste the given code
3. In the zsh terminal run the command `cargo run`

### Expected behavior

I should not print % sign at the end of the line

### OS / Linux distribution

Linux fedora 6.5.7-200.fc38.x86_64

### Zsh version

5.9

### Terminal emulator

GNOME Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
This is how zsh works by default when no newline character is printed between the output and the prompt line, see https://unix.stackexchange.com/q/167582.
