### ISSUE TITLE
brew completion doesn't work completely

### ISSUE THREAD

**Issue by yaroslavyaroslav** [ohmyzsh/ohmyzsh#12024]
### Describe the bug

Any package that I install and that are provides completion for `_completion` function in the following path.

```bash
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
```

For now I have 4 of them including `brew` itself, and none of them are working.

### Steps to reproduce

1. `brew install hub`
2. add `fpath=($fpath $(brew --prefix)/share/zsh/site-functions)` to `~/.zshrc`
3. try to run completion

It'll fails.

### Expected behavior

To perform a completion

### OS / Linux distribution

macOS 14.1 (23B74)

### Zsh version

5.9

### Terminal emulator

iTerm 2

### If using WSL on Windows, which version of WSL

None

### Additional context

- I use preinstalled zsh on my mac which is `zsh 5.9 (x86_64-apple-darwin23.0)`
- `for f in $fpath;do echo $f;done`

```bash
/Users/user/.oh-my-zsh/plugins/encode64
/Users/user/.oh-my-zsh/plugins/forklift
/Users/user/.oh-my-zsh/plugins/postgres
/Users/user/.oh-my-zsh/plugins/sublime
/Users/user/.oh-my-zsh/plugins/swiftpm
/Users/user/.oh-my-zsh/plugins/pip
/Users/user/.oh-my-zsh/plugins/docker-compose
/Users/user/.oh-my-zsh/plugins/docker
/Users/user/.oh-my-zsh/plugins/git
/Users/user/.oh-my-zsh/functions
/Users/user/.oh-my-zsh/completions
/Users/user/.oh-my-zsh/cache/completions
/usr/local/share/zsh/site-functions
/usr/share/zsh/site-functions
/usr/share/zsh/5.9/functions
/opt/homebrew/share/zsh/site-functions
```

Most of these `site-functions` are empty, but `5.9/site-functions` is full of preinstalled completions files, and [all|most|some] of them working, but none of `/opt/homebrew/share/zsh/site-functions` working meanwhile.

**Comment by carlosala** [comment]
Try to move the fpath addition before sourcing `oh-my-zsh.sh`, since completion is being initialized there.

**Comment by yaroslavyaroslav** [comment]
It worked, thanks!
