### ISSUE TITLE
Tab completion does not erase what is already typed

### ISSUE THREAD

**Issue by maximilianmordig** [ohmyzsh/ohmyzsh#12031]
### Describe the bug

After pressing tab, what was previously typed is not erased.

### Steps to reproduce

```
$ mkdir mydir
$ touch mydir/{a,b}.txt

$ ls my<TAB><TAB>
# gives selection of mydir/a.txt and mydir/b.txt, printing "lsls mydir/", i.e. duplicated "ls"
# select a.txt, then press enter
$ lsls mydir/a.txt
mydir/a.txt
```
So it executes `ls mydir/a.txt`.

### Expected behavior

Shell should display
`$ ls mydir/a.txt` instead of `$ lsls mydir/a.txt`

### OS / Linux distribution

Linux mikado 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Zsh version

5.8.1

### Terminal emulator

iTerm2 ssh session from Mac to linux machine

### If using WSL on Windows, which version of WSL

None

### Additional context

Activated plugins:
git
zsh-history-substring-search
colorize
zsh-syntax-highlighting
conda-zsh-completion

**Comment by carlosala** [comment]
It seems to be a locale issue. See more [here](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command)!

**Comment by maximilianmordig** [comment]
Thanks, I regenerated the locale and now it works.
