### ISSUE TITLE
slow startup: ohmyzsh accesses git despite update disabled

### ISSUE THREAD

**Issue by paaguti** [ohmyzsh/ohmyzsh#12036]
### Describe the bug

Currently, the update section in my .zshrc looks like this:
```
zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time
```
Despite this, zsh tries to access git.

My system
```
Darwin paag-MacBookAir 21.6.0 Darwin Kernel Version 21.6.0: Wed Oct  4 23:55:28 PDT 2023; root:xnu-8020.240.18.704.15~1/RELEASE_X86_64 x86_64
```

### Steps to reproduce

Set .zshrc as above and open a zsh after rebooting

### Expected behavior

With `zstyle ':omz:update' mode disabled ` in my .zshrc, I'd expect the shell to be ready faster.

### OS / Linux distribution

macOS (see uname above)

### Zsh version

5.8.1

### Oh My Zsh version

master (b6bb133)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

### Additional context

Seems to work on my Ubuntu 22.04 with same zsh version and omyzsh pull

**Comment by carlosala** [comment]
Hi @paaguti! `git` is accessed when checking if `$ZCOMPDUMP` needs to be rebuilt. In the update system there're no `git` calls if update is disabled.
Which is the actual issue, where do you see it slow?

**Comment by paaguti** [comment]
When I first fire my iTerm2, I see 'git' and then 'xcodebuild' on the title bar. The 'xcodebuild' stays there for some time and I see a lot of network activity.

**Comment by carlosala** [comment]
We're indeed accessing `git` to see if anything changed and we need to rebuild the completion system. It shouldn't be slow, and it's indeed not our issue since we rely on `git` to do our checks. You can see [here](https://stackoverflow.com/questions/65846945/terminal-slow-to-start-first-time-due-to-xcodebuild) which solutions people give.
Thanks for your report!
