### ISSUE TITLE
`grc` plugin does not source `grc.zsh` on Gentoo Linux

### ISSUE THREAD

**Issue by nexpspace** [ohmyzsh/ohmyzsh#12048]
### Describe the bug

The plugin uses the following paths for sourcing the `grc.zsh` file:

`plugins/grc/grc.plugin.zsh`:

```zsh
files=(
  /etc/grc.zsh               # default
  /usr/local/etc/grc.zsh     # homebrew darwin-x64
  /opt/homebrew/etc/grc.zsh  # homebrew darwin-arm64
)
```

The file `grc.zsh` is located at `/usr/share/grc/grc.zsh` for Gentoo Linux and thus not sourced.

### Steps to reproduce

1. Enable plugin `grc` on Gentoo Linux
2. Run command `ping 1.1`
3. Output is not colorized (and not called with grc)

### Expected behavior

Output should be colorized by grc (see `grc ping 1.1`).

### OS / Linux distribution

Gentoo Linux

### Zsh version

5.9

### Terminal emulator

Kitty, Alacritty

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Can you open a PR adding support for that! Should be just adding the line.
