### ISSUE TITLE
Docker autocompletion not working properly

### ISSUE THREAD

**Issue by dorinclisu** [ohmyzsh/ohmyzsh#12043]
### Describe the bug

The completion appears to work on a quick look, but it actually completes with strange commands that do not exist, or is simply missing completions.

### Steps to reproduce

The only customization I have on the fresh install is `plugins=(git docker aws)`. The git and aws plugins work as expected.

```zsh
# mixup of valid and invalid commands
➜  ~ docker
completion  context     exec        inspect     login       logs        ps          run         serve       stop        volume                                                                  
compose     ecs         help        kill        logout      prune       rm          secret      start       version 

# invalid command example
➜  ~ docker ecs 
docker: 'ecs' is not a docker command.

# complete not matching
➜  ~ docker inspect
Desktop/                      Downloads/                    Library/                      Music/                        Pictures/

# interestingly, complete works for compose subcommand
➜  ~ docker compose
build    cp       down     exec     kill     ls       port     pull     restart  run      stop     unpause  version                                                                        
convert  create   events   images   logs     pause    ps       push     rm       start    top      up
```

### Expected behavior

Self explanatory in the shell output above.

### OS / Linux distribution

macOS 14.1.1

### Zsh version

5.9

### Oh My Zsh version

master (c8e600f)

### Terminal emulator

Terminal.app

**Comment by carlosala** [comment]
Docker changed the completion of their tools, and it seems they're still catching up with all the features. You can revert to [old-style config](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/docker#use-old-style-completion).
