### ISSUE TITLE
bgnotify spam: bgnotify_appid:6: command not found: swaymsg

### ISSUE THREAD

**Issue by zsolt-donca** [ohmyzsh/ohmyzsh#12053]
### Describe the bug

I have the plugin `bgnotify` enabled. Whenever I open a new terminal, I get the following message printed:
```
bgnotify_appid:6: command not found: swaymsg
```

I am on Arch Linux using KDE, and using the package https://aur.archlinux.org/packages/oh-my-zsh-git. I don't have Sway nor it's related tools installed, such as swaymsg.

### Steps to reproduce

1. Enable plugin `bgnotify`
2. Open a new terminal

### Expected behavior

There should be no spam when using the plugin `bgnotify`.

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Terminal emulator

Konsole

### If using WSL on Windows, which version of WSL

None

**Comment by riccardv** [comment]
Same issue in KDE Neon

**Comment by zsolt-donca** [comment]
Thank you, @carlosala, I can confirm that it is indeed working as expected!
