### ISSUE TITLE
Word wrapping bug with github

### ISSUE THREAD

**Issue by makaveli0129** [ohmyzsh/ohmyzsh#12051]
### Describe the bug

When using ohmyzsh with Iterm2 the gihub branch is removed when utilizing tab complete. 

### Steps to reproduce

1. Enable github plugin
2. utilize theme attached
3. type `ls` and then `tab` should see screenshot

### Expected behavior

words will not be truncated

### Screenshots and recordings

![image](https://github.com/ohmyzsh/ohmyzsh/assets/5271952/b274f43c-62e5-4aed-bf07-4c02a73cfec0)

theme

```
PROMPT="%(?:%{$fg[yellow]%t $fg_bold[green]%}➜ :%{$fg[yellow]%t $fg_bold[red]%}➜ )"
PROMPT+=' %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
```

Locale

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

### OS / Linux distribution

macos 13.6.1

### Zsh version

5.9

### Oh My Zsh version

master (e6a1db2)

### Terminal emulator

ITerm2

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Try seeing if your `locale` is set to one with `UTF-8` support, as per [this FAQ entry](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command).

**Comment by mcornella** [comment]
Nevermind, I was able to test this on (was on phone).

The issue happens because you put `%t` inside `%{%}` (which tell the shell to effectively consider the content taking 0 characters of length in the prompt.

Since `%t` expands to a string like `HH:mm`, that takes 5 characters. When you press tab to complete, the prompt is not redrawn, but Zsh thinks it's 5 characters more to the left.

This is solved by putting it outside `%{%}`:
```sh
PROMPT="%(?:%{${fg[yellow]}%}%t %{${fg_bold[green]}%}➜ :%{${fg[yellow]}%}%t %{${fg_bold[red]}%}➜ )"
PROMPT+=' %{${fg[cyan]}%}%c%{$reset_color%} $(git_prompt_info)'

ZSH_THEME_GIT_PROMPT_PREFIX="%{${fg_bold[blue]}%}git:(%{${fg[red]}%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{${fg[blue]}%}) %{${fg[yellow]}%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%{${fg[blue]}%})"
```
