### ISSUE TITLE
No styling 

### ISSUE THREAD

**Issue by g1ronn1mo** [ohmyzsh/ohmyzsh#12054]
### Describe the bug

I get the promplt like this 

$(build_prompt)
${fg_bold[default]}$(prompt_chars)$reset_color

it is not styled, only text. 

I also deinstalled and installed zsh.

### Steps to reproduce

Just happend

### Expected behavior

Styling with color and so on

### Screenshots and recordings

![image](https://github.com/ohmyzsh/ohmyzsh/assets/85943218/f340776c-ffb1-4e2e-a7ca-38ff48b2b9ee)

### OS / Linux distribution

Ubuntu23.10

### Zsh version

5.9

### Terminal emulator

GnomeTerminal

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Could you try, for example, `omz theme use nanotech`? If it does not show colours, it's a terminal problem, not ours.

**Comment by g1ronn1mo** [comment]
> Could you try, for example, `omz theme use nanotech`? If it does not show colours, it's a terminal problem, not ours.

![image](https://github.com/ohmyzsh/ohmyzsh/assets/85943218/24259b22-21cb-4d09-938e-30075a892cf6)

I do not know why my zshrc is not running `source /usr/share/zsh-antigen/antigen.zsh`  but this seems to be the problem.

**Comment by carlosala** [comment]
Ooh I didn't understand you! Make sure you `setopt promptsubst` at some point in your zshrc.

**Comment by carlosala** [comment]
could you share your full zshrc?
