### ISSUE TITLE
unicode U+21B5 width from jonathan theme interpretes width incorrectly in iterm2

### ISSUE THREAD

**Issue by hackeysack01** [ohmyzsh/ohmyzsh#12052]
### Describe the bug

omz version: master (e6a1db2)
iTerm2 version: 3.5.0beta17
OS version: Sonoma 14.1.1

### Steps to reproduce

1.install oh my zsh
2.select jonathan theme in the .zshrc configuration
3.generate an error code, say try to run 'asdf'

### Expected behavior

width is calculated properly.

This works in mac terminal. Opening as awareness that this 

### OS / Linux distribution

macos 14.1.1

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

### Additional context

opened with iterm2
https://gitlab.com/gnachman/iterm2/-/issues/11231

By removing the character, my terminal displays correctly in iTerm2.

**Comment by mcornella** [comment]
Please check that you're using a `locale` with UTF8 enabled, see [this related FAQ entry](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command).
