### ISSUE TITLE
Optionally suppress per-directory-history mode change message

### ISSUE THREAD

**Issue by cohml** [ohmyzsh/ohmyzsh#12067]
### If the feature request is for a plugin or theme, specify it here.

per-directory-history

### If the feature solves a problem you have, specify it here.

Currently, with the plugin active, ^G echoes `using global history` or `using local history` to the terminal. This message can interfere with other configurations.

### Describe the proposed feature.

It would be nice to expose a way to suppress this message if desired.

**Comment by rwmitchell** [comment]
Can you demonstrate an example of it interfering?
That may shed light to a proper fix.

My prompt (p10k) apparently overwrites the msg very quickly, global/local is indicated in the prompt.  If I'm mid command when hitting ^G, the prompt is redrawn and the command line is then redisplayed as it was.

The text message, other than as debugging output, currently serves no purpose in my setup, so I'm all for it going away, but that may not be beneficial to everyone.
