### ISSUE TITLE
Removal of line buffer widgets swallows up useful signals

### ISSUE THREAD

**Issue by cohml** [ohmyzsh/ohmyzsh#12074]
### Describe the bug

With the per-directory-history plugin enabled and a Powerlevel10k-themed prompt, one can opt to display the current history mode via an indicator in the prompt. Previously this mode indicator updated in real time. However, after #10872, the real time updating seems to be broken, rendering the indicator static.

### Steps to reproduce

1. Install and enable Powerlevel10k (p10k) theme
2. Add per-directory-history segment to p10k prompt
3. Restart shell and change history mode with `^G`
4. Observe that the prompt segment does not update to reflect the current mode

### Expected behavior

Upon pressing `^G`, the prompt segment should update to reflect the current mode.

### OS / Linux distribution

macOS Ventura 13.4.1

### Zsh version

5.9

### Terminal emulator

iTerm2

**Comment by carlosala** [comment]
Could you share the full zshrc that would reproduce this issue?
Thanks!

**Comment by carlosala** [comment]
Hi! @cohml friendly ping, is this still reproducible?

**Comment by cohml** [comment]
Thanks for the ping, sorry for the delay.

I'm afraid I'm struggling to reproduce this in a simple manner, which suggests the issue may be on my end.

I will close this for now and reopen if it becomes reasonable to do so.
