### ISSUE TITLE
New file in `profile.d` not run

### ISSUE THREAD

**Issue by moritz-t-w** [ohmyzsh/ohmyzsh#12073]
### Describe the bug

I added a new file to `/etc/profile.d`, as required by miniconda but it doesn't get executed. Only when I do source /etc/profile.d/conda.sh, and then everything works. All the other files in `/etc/profile.d` get executed.

### Steps to reproduce

1. Create a file `/etc/profile/conda.sh` with the contents as pasted below

### Expected behavior

file gets executed and functions are available

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Terminal emulator

Tilix

### If using WSL on Windows, which version of WSL

None

### Additional context

The file in question:
`/etc/profile.d/conda.sh`
```sh
export CONDA_EXE='/opt/miniconda3/bin/conda'
export _CE_M=''
export _CE_CONDA=''
export CONDA_PYTHON_EXE='/opt/miniconda3/bin/python'

# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
__conda_exe() (
    "$CONDA_EXE" $_CE_M $_CE_CONDA "$@"
)

__conda_hashr() {
    if [ -n "${ZSH_VERSION:+x}" ]; then
        \rehash
    elif [ -n "${POSH_VERSION:+x}" ]; then
        :  # pass
    else
        \hash -r
    fi
}

__conda_activate() {
    if [ -n "${CONDA_PS1_BACKUP:+x}" ]; then
        # Handle transition from shell activated with conda <= 4.3 to a subsequent activation
        # after conda updated to >= 4.4. See issue #6173.
        PS1="$CONDA_PS1_BACKUP"
        \unset CONDA_PS1_BACKUP
    fi
    \local ask_conda
    ask_conda="$(PS1="${PS1:-}" __conda_exe shell.posix "$@")" || \return
    \eval "$ask_conda"
    __conda_hashr
}

__conda_reactivate() {
    \local ask_conda
    ask_conda="$(PS1="${PS1:-}" __conda_exe shell.posix reactivate)" || \return
    \eval "$ask_conda"
    __conda_hashr
}

conda() {
    \local cmd="${1-__missing__}"
    case "$cmd" in
        activate|deactivate)
            __conda_activate "$@"
            ;;
        install|update|upgrade|remove|uninstall)
            __conda_exe "$@" || \return
            __conda_reactivate
            ;;
        *)
            __conda_exe "$@"
            ;;
    esac
}

if [ -z "${CONDA_SHLVL+x}" ]; then
    \export CONDA_SHLVL=0
    # In dev-mode CONDA_EXE is python.exe and on Windows
    # it is in a different relative location to condabin.
    if [ -n "${_CE_CONDA:+x}" ] && [ -n "${WINDIR+x}" ]; then
        PATH="$(\dirname "$CONDA_EXE")/condabin${PATH:+":${PATH}"}"
    else
        PATH="$(\dirname "$(\dirname "$CONDA_EXE")")/condabin${PATH:+":${PATH}"}"
    fi
    \export PATH

    # We're not allowing PS1 to be unbound. It must at least be set.
    # However, we're not exporting it, which can cause problems when starting a second shell
    # via a first shell (i.e. starting zsh from bash).
    if [ -z "${PS1+x}" ]; then
        PS1=
    fi
fi
```

**Comment by mcornella** [comment]
This is not OMZ-related, but rather a difference in how the global zsh files are set up in the distribution you're using.

Effectively, either `/etc/zsh/zshrc` or `/etc/zsh/zshenv` should read and source the files under `/etc/profile.d/`. This doesn't need to be the case, since as a general rule these files might contain bash-only syntax.

If you're only going to use this with zsh, I'd suggest putting this in a different location and sourcing it from your .zshrc or .zshenv file. You can also put this in `$ZSH_CUSTOM/conda.zsh` if you're only going to use it with Oh My Zsh, but I'm not sure how miniconda runs.

You can check out [this doc about zsh startup files](https://zsh.sourceforge.io/Intro/intro_3.html) for more information.

**Comment by moritz-t-w** [comment]
Actually, now that you mention it, there were 2 places, one for bash and one for everything else, I must have chosen the wrong one. Thanks!
