### ISSUE TITLE
alias-finder: ignore specified aliases

### ISSUE THREAD

**Issue by qstrnd** [ohmyzsh/ohmyzsh#12086]
### If the feature request is for a plugin or theme, specify it here.

alias-finder

### If the feature solves a problem you have, specify it here.

Oh-my-zsh provides default aliases to navigate back in directory:

```
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'
```

Every time I type `..`, I see suggestions of these aliases and I'd like to hide them.

### Describe the proposed feature.

Provide a way to specify the aliases to be ignored. They can be set in an environment variable or, alternatively, using the zstyle configuration.

**Comment by carlosala** [comment]
I can't reproduce, which is your setup around alias-finder?

**Comment by carlosala** [comment]
Hi! Friendly ping @qstrnd :)

**Comment by carlosala** [comment]
Hi! Closing this since it got stale, feel free to reopen if it's still reproducible!
