### ISSUE TITLE
 In large GIT repositories, zsh is particularly slow.

### ISSUE THREAD

**Issue by llongint** [ohmyzsh/ohmyzsh#12088]
### Describe the bug

When working in a large GIT directory, such as llvm-project, using zsh is notably slow. Even simple actions like pressing Enter can incur delays of over 1 second, significantly impacting the user experience.

### Steps to reproduce

Reproduce the command: 
```bash
git clone https://github.com/llvm/llvm-project.git
cd llvm-project
ls
# Press Enter.
```

### Expected behavior

Feedback is exceptionally slow.

### Screenshots and recordings

![zsh slow](https://github.com/ohmyzsh/ohmyzsh/assets/28920187/efd4666b-9145-48b7-8fe1-8c1eadc531a5)

### OS / Linux distribution

Linux DESKTOP-435QPFV 4.4.0-19041-Microsoft #3636-Microsoft Thu Oct 19 17:41:00 PST 2023 x86_64 x86_64 x86_64 GNU/Linux

### Zsh version

5.6

### Oh My Zsh version

master(48ccc7b3)

### Terminal emulator

af-magic

### If using WSL on Windows, which version of WSL

None

**Comment by llongint** [comment]
![zsh slow](https://github.com/ohmyzsh/ohmyzsh/assets/28920187/bed59c72-5074-4b4c-8046-4bbee52cb3c0)

**Comment by llongint** [comment]
@HXWDW Thanks, Your patch resolved my issue.

**Comment by carlosala** [comment]
Hi! That is expected, other themes with other implementations might be faster (I personally use https://github.com/woefe/git-prompt.zsh in [my theme](https://github.com/carlosala/dotfiles/blob/main/zsh/custom/themes/carlosala.zsh-theme). We're tracking in #10869 to implement it in oh my zsh.
Thanks for the report!

**Comment by llongint** [comment]
Hi, @carlosala , Thank you for providing the configuration method for personal themes. Although I personally feel that checking if the working directory is dirty is not necessary, the ability to support it asynchronously sounds very good.
