### ISSUE TITLE
Cursor (in login prompt) moves to left after starting tmux

### ISSUE THREAD

**Issue by cmonty14** [ohmyzsh/ohmyzsh#12083]
### Describe the bug

After starting _tmux_ the cursor (in login prompt) moves left and the grey bar on the right sight increases.
![image](https://github.com/ohmyzsh/ohmyzsh/assets/12523591/29d6b4f2-aaf9-4b8a-933f-345a96dadc14)

Starting shell regularly it looks different:
![image](https://github.com/ohmyzsh/ohmyzsh/assets/12523591/c09c8ece-b64e-484d-9dc0-09c345ccaf1c)

 

### Steps to reproduce

1. Enable plugin "tmux"
2. Run command "tmux"

### Expected behavior

The prompt must not change after starting _tmux_.

### OS / Linux distribution

Debian 11

### Zsh version

5.8

### Oh My Zsh version

master (e6a1db2)

### Terminal emulator

Windows Terminal

### If using WSL on Windows, which version of WSL

WSL2

**Comment by mcornella** [comment]
Do you have any tmux configuration? Also what is the output of `locale` and `locale -a`?
