### ISSUE TITLE
Add `git checkout -B` to plugin

### ISSUE THREAD

**Issue by hamonangann** [ohmyzsh/ohmyzsh#12087]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### Describe the proposed feature.

I realised that we have `gcb` for `git checkout -b` but I often need to use `git checkout -B` (with B capital) to perform branch reset in my shell scripts. Wouldn't it be good if we have an alias for that? I can help to code, but I need suggestion about the alias. Is `gcbr` (git checkout -B with reset) good enough?

**Comment by hasecilu** [comment]
Maybe `gcB`, as reference `gbD` already exists (to force a delete) here you want to force a reset.

**Comment by hamonangann** [comment]
gcB should be fine, working on it. thanks @hasecilu !
