### ISSUE TITLE
Commands after `omz update` will not execute when update is successful

### ISSUE THREAD

**Issue by zzh1996** [ohmyzsh/ohmyzsh#12112]
### Describe the bug

I usually use a one-liner to update many tools including oh-my-zsh, just like this:

`foo && bar && omz update && buzz && ...`

Every time when the `omz update` step succeeds with updates available, the remaining part of my command will not execute at all. This will also happen if you change `&&` to `;`

### Steps to reproduce

1. Install oh-my-zsh on a fresh installed Debian 12 (or macOS or whatever)
2. `cd ~/.oh-my-zsh && git pull --unshallow && git reset HEAD^ --hard` to make updates available
3. `echo 1 && omz update && echo 2`

### Expected behavior

Both `1` and `2` should be printed

### OS / Linux distribution

Debian 12 / macOS

### Zsh version

5.9

### Oh My Zsh version

master (9004c177)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by gautamkrishnar** [comment]
I will take a look at this

**Comment by gautamkrishnar** [comment]
@zzh1996 you are running an interactive command in unattended mode. Please use:
```
$ echo 1 && omz update --unattended && echo 2
1
Updating Oh My Zsh
Created autostash: f2b443ae
Applied autostash.
You can see the changelog with `omz changelog`
         __                                     __
  ____  / /_     ____ ___  __  __   ____  _____/ /_
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
                        /____/

Hooray! Oh My Zsh has been updated!

To keep up with the latest news and updates, follow us on Twitter: @ohmyzsh
Want to get involved in the community? Join our Discord: Discord server
Get your Oh My Zsh swag at: Planet Argon Shop
2
```

**Comment by carlosala** [comment]
Indeed. `omz update` executes `omz reload` under the hood if the update is successful. `omz update --unattended` does not reload the shell.
Thanks Gautam!
