### ISSUE TITLE
sudo plugin should not use `sudo -e` where doing so changes behavior of `sudo <command>`

### ISSUE THREAD

**Issue by zwimer** [ohmyzsh/ohmyzsh#12149]
### If the feature solves a problem you have, specify it here.

Consider the command `vim ~/foo`. Using the sudo plugin, double tapping escape gives: `sudo -e ~/foo`. However, gives a noticeably different behavior than `sudo vim ~/foo`.
Specifically, `sudo -e ~/foo` errors with:
`sudo: /home/zwimer/foo: editing files in a writable directory is not permitted`

As a result, anytime I need to `sudo vim` I end up having to manually type `ctrl-a` `sudo` on my commands which defeats the purpose of this plugin.

### Describe the proposed feature.

Do not do translate `$EDITOR <args>` to `sudo -e <args>` where doing so would cause the command to fail

### Describe alternatives you've considered

Expose an ENV var that disables preferring `sudo -e <args>` to `sudo $EDITOR <args>`

### Additional context

`omz version`: `master (f74add6c)`

`zsh --version`: `zsh 5.9 (x86_64-redhat-linux-gnu)`

```
$ sudo --version
Sudo version 1.9.14p3
Sudoers policy plugin version 1.9.14p3
Sudoers file grammar version 50
Sudoers I/O plugin version 1.9.14p3
Sudoers audit plugin version 1.9.14p3
```

### Related Issues

https://github.com/ohmyzsh/ohmyzsh/issues/10509

**Comment by carlosala** [comment]
`sudo -e` is for sure preferred, since the permissions given to the user editing the file is specifically that one: to edit the file. Imagine a situation with `sudo vim` and some kind of malicious plugin that could potentially do whatever on your system.
Even though, I like the idea of making it configurable!
Could you submit a PR? Probably adding some zstyle-based config (you can check `nvm` plugin, for instance, to get some inspiration) would do the trick.
Thanks

**Comment by zwimer** [comment]
I agree with `sudo -e` as the default, but I like the idea of at least allowing that substitution to be disabled. How would you feel about something like a PR changing the swap logic from something like `do_swap_logic()` to
`if [ $OHMYZSH_DISABLE_SUDO_EDITOR_SWAP != 1 ]; then do_swap_logic(); fi`

(Env variable name very open to suggestions)

**Comment by carlosala** [comment]
I was thinking more of adding two zstyle-based configs just to modify the command that is used. For example, `zstyle ':omz:plugins:sudo cmd` and `zstyle 'omz:plugins:sudo editor-cmd`. Then it'd be useful as well if some user wants to use other kinds of superuser implementations (directly su, for instance?)

**Comment by zwimer** [comment]
I'll look into zstyle more. I will also look into seeing if there is a way to allow `sudo -e` to work in writable directories safely somehow since that'd be much nicer in my opinion since, as I recall, since `sudo -e` runs as the user you can keep your own editing setup rather than using root's. If I make progress on either I'll let you know.

Oh, and for the above, I forgot to mention this but sudo vim should use the root env so vim should root env; you'd need `sudo -E vim` for the malicious plugin situation, unless said plugins were installed for the root user I believe; that doesn't change the fact that I agree with you that `sudo -e` is greatly preferred in most situations though.

**Comment by zwimer** [comment]
Looking into sudoedit more, it seems the only way to permit writable dirs is to edit the sudoers file and override a global config options, and that's not acceptable; it seems this was prevented for security purposes so I guess I'll nix that idea.

The next two options are to use zstyle as config to:
1. Change what sudo $EDITOR transforms into
2. If the user prefers this, only for directories where sudo -e would fail, use sudo vim. I think this is acceptable since the user is intentionally invoking sudo presumably, given that the nature of this plugin is 'prepend sudo'; it could be a fallback if sudo -e will fail. Something like `if owner(dirname(args)) == user || is_writable((dirnames(args)) then`. Though thinking on this, that feels like a lot of engineering as you might have to parse args, ignore flags, etc; if someone else wants to put in that labor great but I don't know if I have the time for that. Not unless we are ok with it being a rudimentary logic that assumes all arguments not starting with a dash are filepaths and just checks the `dirname` of each? Which maybe is ok since that'd probably work 99% of the time and if it fails, we are just at the status quo.

Both have their strengths and weaknesses; though I'm leaning towards the second as the first would just disable `sudo -e` entirely which is a loss in my opinion. The by-default replacement `sudo -e` over `sudo vim` is very nice and I'd like to keep that whenever doing so wouldn't cause the command to fail.

**Comment by carlosala** [comment]
Actually, thinking about that, if the user already has permission to write on that directory, `sudo -e` shouldn't be needed at all, right? It's a weird corner case otherwise. We should leave it as is IMO

**Comment by zwimer** [comment]
This is very common issue for me, I hit it daily. For example, editing files of a docker container's user (maybe root; but maybe some other UID/GID). I often edit the config files of my containers and these are typically owned by other users (sometimes root, sometimes other users); yet because I mount these inside of containers they aren't in a directory owned by root but rather somewhere within my home directory.

I think files for container volumes is a perfect example of where the enclosing dir (on the host) is not owned by root despite the inner files being owned by root (or other users), as within the container likely the enclosing dir is owned by root.

If you dislike the idea of changing the default behavior, we could also make it a toggle using zstyle. I.e. 'if you enable this zstyle option it can allow editing files in writable directories'. I think it ought to be fine on by default, but having it off by default isn't really an issue as long as the zstyle config option is documented.

**Comment by carlosala** [comment]
My main concert is adding too much complexity to a simple plugin and keep bumping over corner cases, not sure which is the best option to proceed here...

**Comment by zwimer** [comment]
Another common failure mode is simply editing a link. `sudo -e` fails for all links, including those entirely owned by root, pointing to a root owned file, all in root owned directories. This has also bit me editing various files like systemd files and some config files in `etc`.

**Comment by zwimer** [comment]
> My main concert is adding too much complexity to a simple plugin and keep bumping over corner cases, not sure which is the best option to proceed here...

I do see your point. I'm a bit biased since this bug hits me often enough that I've just commented out the replacement code in my plugin, but this issue has made the plugin (as is default) unusable to me. I'll see if I can make a relatively simple PR that doesn't add much complexity. If I can't then I'll just stick with my edited plugin.

**Comment by carlosala** [comment]
let's see the PR👍

**Comment by zwimer** [comment]
I'll figure out how to convert this function into a PR in a bit, but right now I need to sleep.

I'm thinking running this function on the arguments is sufficient to catch at least the biggest offenders here:
```zsh
__sudo_e_ok() {  # Return 1 if we should not prefer sudo -e "$@" over sudo "$EDITOR" "$@"
    local FILE GRP GROUPS=( $(id -G) )
    for FILE in "$@"; do
        [[ -d "$FILE" || -L "$FILE" ]] && return 1  # Dirs and symlinks fail
        local DIR="$(dirname "$FILE")"
        [[ ! -d "$DIR" ]] && return 1  # Non-existent parent
        [[ "$(id -u)" -eq "$(ls -ldn "$DIR" | awk '{print $3}')" ]] && return 1  # We own the dir
        local OWNER=( $(ls -ldn "$DIR" | awk '{print $4}') )
        for GRP in "${GROUPS[@]}"; do
            [[ "$GRP" == "$OWNER" ]] && return 1  # A group we are in owns the dir
        done
    done
    return 0  # sudo -e is ok
}
```

As a simple test, the following all pass:
```zsh
# sudo -e
__sudo_e_ok /etc/hosts      && echo "Success 1" # File exists
__sudo_e_ok /foo            && echo "Success 2" # File does not exist
__sudo_e_ok /etc/hosts /foo && echo "Success 3" # All of the above
# no sudo -e
__sudo_e_ok /tmp                     || echo "Success 4" # Symlink
__sudo_e_ok "$HOME"                  || echo "Success 5" # Dir
__sudo_e_ok "$HOME/foo"              || echo "Success 6" # User owned
__sudo_e_ok /tmp "$HOME" "$HOME/foo" || echo "Success 7" # All of the above
```

**Comment by zwimer** [comment]
@carlosala The PR has been made, though it needs a config toggle still- but we should move that conversation onto the PR itself rather than this issue

**Comment by carlosala** [comment]
Closing, since #12152 was not merged in the end.
Thanks for the report!
