### ISSUE TITLE
Terminal hangs for sometime (30s or so) in big git directory in WSL2

### ISSUE THREAD

**Issue by mockfrank** [ohmyzsh/ohmyzsh#12142]
### Describe the bug

In WSL2 with oh my zsh, any command in the directory of a big git repository causes the terminal to hang for 30s or so. The command was executed well and quickly but hangs after that.

### Steps to reproduce

1. install zsh and ohmyzsh in WSL2
2. clone a relatively big git repository
3. type 'l' or 'ls -al' or other command in the same folder
4. The directory is listed and the terminal hangs for 30s, then new line appears

### Expected behavior

The directory is listed and next new input line appears

### Screenshots and recordings

[omz-debug.log](https://github.com/ohmyzsh/ohmyzsh/files/13808815/omz-debug.log)

https://asciinema.org/a/6auz0lkp0pJaUWlbdEz3Ny4sy

### OS / Linux distribution

 Ubuntu 22.04.3 LTS

### Zsh version

5.8.1

### Oh My Zsh version

master (f74add6)

### Terminal emulator

windows terminal

### If using WSL on Windows, which version of WSL

WSL2

**Comment by carlosala** [comment]
That's expected. Dup of #12088. We have that on our backlog, thanks for the report!
