### ISSUE TITLE
style(poetry-env): remove too long command line prefix

### ISSUE THREAD

**Issue by donBarbos** [ohmyzsh/ohmyzsh#12144]
### If the feature request is for a plugin or theme, specify it here.

poetry-env

### Describe the proposed feature.

Poetry generates long names for Python virtual environments.
The length of the entire command line prompt may be half the screen on laptop screen, which can cause inconvenience.

### Describe alternatives you've considered

It might be worth running `zsh` additionally so that the prefix disappears but the virtual environment remains

**Comment by donBarbos** [comment]
@ajatkj please respond to this issue

**Comment by ajatkj** [comment]
Hi @donBarbos, its probably got to do with the theme that you are using and other plugins that you are using. This plugin just activates the environment.

For ex. I use `bira` theme which displays all the information on the first line and prompt on the 2nd line.

**Comment by donBarbos** [comment]
I understand that this is related to my theme (as well as many other one-line themes)
Have you thought about removing the name of the environment, otherwise it is not very informative and takes up a lot of unnecessary space in such themes

**Comment by ajatkj** [comment]
That's what I am trying to say. 
This plugin has got nothing to do with the name of the environment or how its displayed on the prompt. This plugin merely activates your poetry environment when it finds a `pyproject.toml` file in current directory. 

The name is generated by poetry itself. If you don't want to see the name on the prompt you can probably remove `virtualenv` or `python` plugins from your list of plugins in `.zshrc`
