### ISSUE TITLE
suggestion to use only HTTPS for ohmyzsh update

### ISSUE THREAD

**Issue by peterbecich** [ohmyzsh/ohmyzsh#12141]
### If the feature solves a problem you have, specify it here.

- open a new ohmyzsh shell
- ohmyzsh checks for available update
  - (I assume this succeeds because `git fetch` without SSH key will succeed on a public repository, but `git pull` will fail)
- if update available, ohmyzsh asks to update. Yes.
- However, the SSH key agent has not yet started
- When ohmyzsh attempts to pull the update, it fails with this error: https://github.com/ohmyzsh/ohmyzsh/discussions/10373?sort=top
```
Updating Oh My Zsh
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
There was an error updating. Try again later?
```

- after this error, the shell loads successfully, and the SSH key agent starts
- `omz update` succeeds

### Describe the proposed feature.

The cause of the issue is probably that my key is not named `id_rsa.key`, it is named something else.

However, I believe this issue can be fixed a different way, which would solve it for all users with no key renaming needed.

If I understand this correctly: https://github.com/ohmyzsh/ohmyzsh/blob/fa770f9678477febe0ed99566d9f3331f3714eca/tools/check_for_upgrade.sh#L50-L51
`check_for_upgrade.sh` pulls updates with Git by either HTTPS or SSH.

Can the SSH option just be removed? If it is a public repository and the client is not pushing changes, is there any advantage to using SSH? Using HTTPS only would remove the need for the SSH key entirely.

Thank you

### Describe alternatives you've considered

The issue was fixed here https://github.com/ohmyzsh/ohmyzsh/discussions/10373?sort=top
by renaming or copying key to `id_rsa.key`

**Comment by carlosala** [comment]
By default, [omz installer](https://github.com/ohmyzsh/ohmyzsh/blob/fa770f9678477febe0ed99566d9f3331f3714eca/tools/install.sh#L24) uses Github over HTTPS remote. Even though, if someone wants to use SSH (like me, for example) is still able to update oh-my-zsh using `omz update`. Not a bad option IMO, but by default HTTPS will be used.
