### ISSUE TITLE
VS Code Can't split terminal

### ISSUE THREAD

**Issue by suchangv** [ohmyzsh/ohmyzsh#12151]
### Describe the bug

![image](https://github.com/ohmyzsh/ohmyzsh/assets/41581056/90c398f3-e989-4946-9b7c-81ac0cd7056d)

# Describe the bug

When I want to split a new terminal in VS Code, it report an error of `The terminal process failed to launch: Starting directory (cwd) "/c/Users/suchangv/.oh-my-zsh" does not exist.`, I couldn't find any similar issues from VS Code, Amazingly, When I disabled oh my zsh, it works ok. Through step-by-step debug, the final problem is `omz_termsupport_cwd` zsh hook, The more specific issue is `printf "\e]7;file://%s%s\e\\" "${URL_HOST}" "${URL_PATH}"`, when I comment out it, Everything is normal now.

**It is worth mentioning that I use zsh on windows(Git Bash, no WSL, no Virtual Machine)**

## Environment
Windows: Version 10.0.22631 Build 22631
VSCode: 1.85.1
git: git version 2.43.0.windows.1
zsh: 5.9 (x86_64-pc-msys)
oh-my-zsh: master (5ea2c68)

### Steps to reproduce

1. Open any directory using VS Code
2. Click `Split Terminal`

### Expected behavior

`Split Terminal` works ok

### OS / Linux distribution

Windows 11

### Zsh version

5.9

### Terminal emulator

VS Code builtin xterm-256color

### If using WSL on Windows, which version of WSL

None

**Comment by darianmorat** [comment]
It has problems with the terminal in VSCODE, in my case it sends the ~/ again and again if I toggle the sidebar, and that just happens with ZSH,

**Comment by carlosala** [comment]
Theoretically oh-my-zsh is not supported on Git bash, it's only supported in WSL2 under Windows. We do not assure the compatibility with git bash

**Comment by suchangv** [comment]
> Theoretically oh-my-zsh is not supported on Git bash, it's only supported in WSL2 under Windows. We do not assure the compatibility with git bash

In fact, it runs perfectly, thank you very much for your efforts!

**Comment by carlosala** [comment]
Closing since it's due to an incompatibility with git bash.
