### ISSUE TITLE
Aliasing ipython overrides command line arguments

### ISSUE THREAD

**Issue by stefanv** [ohmyzsh/ohmyzsh#12153]
### Describe the bug

[Here](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/python/python.plugin.zsh#L47C16-L47C89), oh-my-zsh overrides the command for IPython.

When IPython is installed in the current virtual environment, this is not necessary, since the ipython command is already correctly installed.

But adding this aliases changes behavior. It would be better not to create the alias, since it does not add any real advantage.

### Steps to reproduce

 To reproduce, run:

```
ipython --ignore-cwd
```

with, and without, the alias, and inside IPython print `sys.path`.

The flag is ignored when the alias is defined.

### Expected behavior

No alias should be created that impacts the behavior of the `ipython` command.

### OS / Linux distribution

Fedora 36

### Zsh version

5.9

### Terminal emulator

Alacritty

### If using WSL on Windows, which version of WSL

None

**Comment by gautamkrishnar** [comment]
I will take a look at this

**Comment by carlosala** [comment]
Thanks for the report, and thanks Gautam as well! It should be fixed now!
