### ISSUE TITLE
Error: git clone of oh-my-zsh repo failed

### ISSUE THREAD

**Issue by johnxie1225** [ohmyzsh/ohmyzsh#12173]
### Describe the bug

I'm in China and I am running OS Ventura 13.6.3. 
I  install oh-my-zsh with curl using the following command:
`sh -c "$(curl -fsSL https://install.ohmyz.sh/)"`
But it output:
`Error: git clone of oh-my-zsh repo failed`

### Steps to reproduce

I  install oh-my-zsh with curl using the following command:
`sh -c "$(curl -fsSL https://install.ohmyz.sh/)"`
But it output:
`Error: git clone of oh-my-zsh repo failed`

### Expected behavior

How to install the oh my zsh in my MacBook

### OS / Linux distribution

OS Ventura 13.6.3.

### Zsh version

5.9

### Oh My Zsh version

none

### Terminal emulator

none

### If using WSL on Windows, which version of WSL

None

### Additional context

1

**Comment by mcornella** [comment]
Can you print the whole output?

**Comment by johnxie1225** [comment]
<img width="978" alt="Screenshot 2024-01-23 at 12 51 02" src="https://github.com/ohmyzsh/ohmyzsh/assets/56942215/fde9634d-86ed-4450-920d-5d0ad08af0be">

**Comment by johnxie1225** [comment]
> Can you print the whole output?

<img width="978" alt="Screenshot 2024-01-23 at 12 51 02" src="https://github.com/ohmyzsh/ohmyzsh/assets/56942215/0c98b324-1430-4d5c-af49-dc74320deb8f">

**Comment by johnxie1225** [comment]
> > Can you print the whole output?
> 
> <img alt="Screenshot 2024-01-23 at 12 51 02" width="978" src="https://private-user-images.githubusercontent.com/56942215/299330612-0c98b324-1430-4d5c-af49-dc74320deb8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMDQ4NDcsIm5iZiI6MTcwNjEwNDU0NywicGF0aCI6Ii81Njk0MjIxNS8yOTkzMzA2MTItMGM5OGIzMjQtMTQzMC00ZDVjLWFmNDktZGM3NDMyMGRlYjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEzNTU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwOWFmMDZkYzhiODFjNDhkMzlmYzMxOTFjY2JlMDZmODU3YzEyNjU4MjlmMmJhZGE5NDI2NzUwYWE5MmQzODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A8ouSY1BkILmUXCuNmmLNM4Mb6DsROYJhHz_7LIr0nc">

if I close the VPN, then the output is like this attached 
![Uploading Screenshot 2024-01-24 at 05.55.04.png…]()
one

**Comment by mcornella** [comment]
This is a common issue, make sure to use the alternative download link as documented in the FAQ: https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-cant-access-the-installer--connection-timed-out.
