### ISSUE TITLE
customization part in .zshrc was overwritten after OMZ installation.

### ISSUE THREAD

**Issue by Giessen** [ohmyzsh/ohmyzsh#12177]
### Describe the bug

OS: winsows 11/wsl2
I added some content manually before the installation. They are gone after...........

### Steps to reproduce

...

### Expected behavior

...

### OS / Linux distribution

WSL2

### Zsh version

5.8

### Oh My Zsh version

master(e656377)

### Terminal emulator

wsl2 (xterm)

### If using WSL on Windows, which version of WSL

WSL2

**Comment by carlosala** [comment]
Hi! When installing, `.zshrc` is backed up at `.zshrc.pre-oh-my-zsh`. You should be able to find your file there.
Thanks!
