### ISSUE TITLE
OMZ why insert a slash charactor?

### ISSUE THREAD

**Issue by nicoxb** [ohmyzsh/ohmyzsh#12185]
### Describe the bug

When I copy some special string, and paste to terminal, OMZ will insert a slash charactor in some case.
It is normal after I annotation this line `source $ZSH/oh-my-zsh.sh`, or use other shell.

### Steps to reproduce

1. use omz
2. copy the string `http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13`
3. paste into terminal
4. a `\` will insert to charactor `a` and charactor `=`. The paste result is `http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na\=extmap:13`

### Expected behavior

Don't insert slash charactor

### OS / Linux distribution

macOS 14.2.1 (23C71)

### Zsh version

5.9

### Oh My Zsh version

master (80c114cb)

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
I can't reproduce, in my case it's just pasted between `''`. Even though, it's expected due to `=` being a reserved char if it's not quoted (it's the var assignment `foo=bar; echo $foo`).
It shouldn't be an issue since the terminal will interprete the regular url.

**Comment by nicoxb** [comment]
> I can't reproduce, in my case it's just pasted between `''`. Even though, it's expected due to `=` being a reserved char if it's not quoted (it's the var assignment `foo=bar; echo $foo`). It shouldn't be an issue since the terminal will interprete the regular url.

[This is the isuue video](https://github.com/ohmyzsh/ohmyzsh/assets/13716553/a2957c72-b079-4006-8193-e73ac7d6d3d0)
