### ISSUE TITLE
1password Plugin Not Working

### ISSUE THREAD

**Issue by hmenorjr** [ohmyzsh/ohmyzsh#12181]
### Describe the bug

After adding 1password to plugins and restarted the terminal. Running `opswd --help` displays an error:

```shell
$ opswd
zsh: command not found: opswd
``` 

### Steps to reproduce

1. Run: `zshconfig`
2. Add 1password:
```shell
plugins=(git 1password)
```  
3. Restart the terminal: `source ~/.zshrc`
4. Run command: `opswd`

### Expected behavior

A display of available commands or information will be displayed

### Screenshots and recordings

![image](https://github.com/ohmyzsh/ohmyzsh/assets/15950561/b31ca6e6-f81f-4a3d-9c51-feabc3fe1444)

### OS / Linux distribution

Windows 10 with WSL2 terminal

### Zsh version

5.8.1

### Terminal emulator

WSL2

### If using WSL on Windows, which version of WSL

WSL2

**Comment by carlosala** [comment]
To restart the terminal, use `omz reload` instead.
Are you sure you have 1password cli installed? You can verify it by executing `where op`.

**Comment by carlosala** [comment]
You're missing `1password` installation. Make sure to install it, then the plugin will work perfectly. https://developer.1password.com/docs/cli/
