### ISSUE TITLE
Java now supports passing a Java file but ohmyzsh doesn't autocomplete for it

### ISSUE THREAD

**Issue by henri-tremblay** [ohmyzsh/ohmyzsh#12198]
### If the feature request is for a plugin or theme, specify it here.

Java

### If the feature solves a problem you have, specify it here.

Java now supports command line like `java Math.java` or ` java src/main/java/org/me/Math.java`. It will then just compile and launch that java file. But ohmyzsh won't autocomplete for that. It only wants a jar, class file or whatever.

### Describe the proposed feature.

I would like normal completion on file and directories with a filter on .java files. Possibly on top of the classpath way (which I never use to just deactivating it would be fine with me)

**Comment by carlosala** [comment]
Java completion is defined in [zsh repo](https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_java), not here. You can send an email to the [zsh mailing list](https://zsh.org/mla), they'll for sure be proactive!
Thanks!

**Comment by henri-tremblay** [comment]
Thanks! Will do. I wasn't sure where the code was. Otherwise I would probably have tried to fix it myself.
