### ISSUE TITLE
With plugin kubectx, spaces in Kubernetes contexts are not mentioned.

### ISSUE THREAD

**Issue by lutra** [ohmyzsh/ohmyzsh#12190]
### Describe the bug

When a Kubernetes context contains spaces (such as `my context`), this context is not mentioned with custom context names. The variable `kubectx_mapping` of the kubectx plugin lacks of quotation marks.

### Steps to reproduce

1. Enable plugin kubectx (`source $ZSH/plugins/kubectx/kubectx.plugin.zsh`)
2. Add a Kubernetes context with a space in it: `kubectl config rename-context mini "my mini"`
3. Add that new context to variable `kubectx_mapping`, written in the [plugin readme](https://github.com/lutra/ohmyzsh/tree/master/plugins/kubectx#custom-ctx-names): `kubectx_mapping["my mini"]="workin mini"`
4. Place the Kubernetes context name at the right prompt: `export RPROMPT='$(kubectx_prompt_info)'

### Expected behavior

Output of above example should be _workin mini_ at right prompt.

Instead _my mini_ is written.

### OS / Linux distribution

Debian GNU/Linux trixie/sid

### Zsh version

5.9

### Oh My Zsh version

master (b5e6392f)

### Terminal emulator

Terminator

### If using WSL on Windows, which version of WSL

None

**Comment by DxMortem** [comment]
Guys the fix for this bug broke the normal function on the kubectx_mapping
Now all the mappings should have quotes 😅
