### ISSUE TITLE
ZSH plugins are not loading aliases properly

### ISSUE THREAD

**Issue by TheFelipeSantos** [ohmyzsh/ohmyzsh#12205]
### Describe the bug

My zsh is not loading some plugins' aliases. I recently added `kubectl` and `helm` to the plugin list and since then, I need to source my zshrc file for them to appear in my alias listing.

I don't know if there's anything wrong with my config, but there we go:

![image](https://github.com/ohmyzsh/ohmyzsh/assets/115845231/4bfaafa9-2e0b-42cb-b5d0-8e600ebb39df)

### Steps to reproduce

1. vim ~/.zshrc;
2. add kubectl to plugins list;
3. save the file;
4. quit terminal and reopen it;
5. try some kubernetes alias. Like `k` or `kccc` (kubectl config current-context);

### Expected behavior

When the terminal runs for the first time, it should already load all plugins' aliases

### Screenshots and recordings

![image](https://github.com/ohmyzsh/ohmyzsh/assets/115845231/d0f3706c-0ee9-452f-8a1f-1f6416e0b915)

![image](https://github.com/ohmyzsh/ohmyzsh/assets/115845231/3715253e-5851-4522-af6f-a7154b12dda8)

### OS / Linux distribution

22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Zsh version

5.8.1

### Oh My Zsh version

master (2124370)

### Terminal emulator

terminator

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
That's because you don't have `PATH` set up correctly before loading oh-my-zsh. Make sure you have `where kubectl` and `where helm` in your PATH before sourcing `oh-my-zsh.sh`.
