### ISSUE TITLE
OMZ  on Cygwin is preventing arrow support for FZF

### ISSUE THREAD

**Issue by purplefishies** [ohmyzsh/ohmyzsh#12200]
### Describe the bug

Using the latest version of OMZ , it intereferes with the arrow key scroll behaviour of fzf. 

### Steps to reproduce

1. cygwin system with zsh installed but not fzf
2. Install fzf from https://github.com/junegunn/fzf
3. Run standard fzf install ( installs both Bash and Zsh bindings to ~/.bashrc and ~/.zshrc )  
4. source ~/.zshrc
5. Type ctrl-r  to start searching  # triggers FZF
6. Arrow keys select works
7. Install oh-my-zsh
8. source $ZSH/oh-my-zsh.sh 
9. Type ctrl-r  to start searching
10. Up and Down arrow keys don't work
ControlP and ControlN allow you to move around .

### Expected behavior

The up and down arrow keys shouldn't affect ZSH's interaction  .  Bash works just fine and zsh does as well as long as you don't source OMZ.

### OS / Linux distribution

Windows 10 Cygwin 

### Zsh version

5.8

### Oh My Zsh version

master (212437090032)

### Terminal emulator

Microsoft Terminal and Cygwin mintty 

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
I'd recommend removing the `fzf` bindings that the installer adds to `zshrc` and using the `fzf` plugin instead. It'll set up the bindings for you.
