### ISSUE TITLE
Only some aliases from the git plugin works

### ISSUE THREAD

**Issue by mrbase** [ohmyzsh/ohmyzsh#12207]
### Describe the bug

I have a pretty bacis omz setup, mostly standard stuff in the .zshrc file and only `git` and `zsh-autosuggestions` plugins are enabled.
Then a couple of custom aliases at the bottom.

However, the alias `gbda` stopped working - it is not registering at all.
It have worked great in the past, but in the last 2-3 month it have stopped.

I have verified with a college of mine, and he have the same issue. Both on linux (Pop_OS)

I just updated omz this morning, so it should be up-2-date.

### Steps to reproduce

- enable the git plugin
- restart the terminal
- run `alias gbda`

### Expected behavior

The alias description

`git branch --no-color --merged | command grep ....`

### OS / Linux distribution

Pop!_OS 22.04 LTS

### Zsh version

5.8.1

### Terminal emulator

Terminal, Tilix both tested

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
`gbda` is not an alias, is a function. If you execute `functions gbda` you'll find the alias/function.
What is exactly not working for you?

**Comment by mrbase** [comment]
Woops, my bad - probably been an alias at some point, and I just missed the transition :-P
