### ISSUE TITLE
Unfeature request: Extra aliases - They aren't helping

### ISSUE THREAD

**Issue by murkku** [ohmyzsh/ohmyzsh#12213]
### If the feature request is for a plugin or theme, specify it here.

alias

### If the feature solves a problem you have, specify it here.

I don't like to get surprised by random aliases.
Unsanctioned aliases pollute the shell experience and shouldn't get set by default.

### Describe the proposed feature.

Disable all extra aliases by default, please make them opt-in.
`zstyle ':omz:*' aliases no` fixes this but it shouldn't be required to be set by users.

### Describe alternatives you've considered

I like to define my own aliases for `zsh` as needed.
Alternative for the alias-hungry might be creation of yet another shell, but please let's not pollute this one any further with _personal_ customizations. Oh My Zsh is great enhancement, but this force feeding of new "commands" is not the way to go.

### Additional context

Releases and `omz update` happen frequently enough, and I for one would like to be able to trust updates without worrying them polluting my env with n+1 spells that my next typo might trigger.

Changelogs filled by added aliases is just wrong.

**Comment by carlosala** [comment]
Hi! Most of the aliases are under plugins (which are opt-in for users). I'm sorry you're having such a bad experience. You can as well fine-grain choose your aliases as explained [here](https://github.com/ohmyzsh/ohmyzsh?tab=readme-ov-file#skip-aliases), but aliases are one of the main purpose of plugins. We're not adding any new aliases to the `lib/` directory, which is loaded for every user.
Thanks for your idea, but we're not willing to make such a breaking change for many users, taking into account that most aliases are opt-in with plugins.
