### ISSUE TITLE
FIXED THE NAVABAR POSITION AT TOP TO BETTER USER INTERFACE

### ISSUE THREAD

**Issue by kiranugale2o** [ohmyzsh/ohmyzsh#12220]
### Describe the proposed feature.

NAVBAR IS NOT A FIXED .

**Comment by mcornella** [comment]
Hello Kiran, thanks for the report. I assume this is related to the ohmyz.sh website.

We are currently working on refreshing it and we have taken note of your suggestion.

As this issue tracker is only related to Oh My Zsh itself (the framework), I'll be closing the issue.

Cheers
