### ISSUE TITLE
Plugin ssh-agent. Not found ssh-askpass

### ISSUE THREAD

**Issue by LonFas** [ohmyzsh/ohmyzsh#12233]
### Describe the bug

After logging into the console, a message appears
`ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory`

Enabled plugin ssh-agent. Latest version of oh my zsh (omz update). Updated by brew all packages. Checked by brew doctor.

### Steps to reproduce

0. Create ssh key with password
1. Make sure, in accordance with the plugin settings, that it will be added to the agent
2. Enable plugin ssh-agent `plugins=( ssh-agent )`
3. Try to use it

### Expected behavior

Must be suggested to enter passwords for encrypted ssh keys

### OS / Linux distribution

MacOS 14.3.1 (23D60)

### Zsh version

zsh 5.9 (x86_64-apple-darwin23.0)

### Terminal emulator

Iterm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Hi! A small ping here! @LonFas
Thanks!

**Comment by carlosala** [comment]
Hi! Is it still reproducible? @LonFas

**Comment by LonFas** [comment]
> Hi! Is it still reproducible? @LonFas

Sorry, emails went to spam. No. I disable ticket
