### ISSUE TITLE
When entering a directory containing large files, oh-my-zsh will freeze at this moment.

### ISSUE THREAD

**Issue by Zonax40** [ohmyzsh/ohmyzsh#12246]
### Describe the bug

When I try to enter a directory with a large model, oh-my-zsh just freezes without any outputs.

### Steps to reproduce

1. Get a folder with large files in it. In my case, I get the directory by cloning from https://huggingface.co/Salesforce/blip2-flan-t5-xxl/tree/main
2. cd that_folder

### Expected behavior

The shell just freezes for about 3 minutes before I could enter that folder. After I finally succeeded entering that folder and typed "ls" command, on-my-zsh just freezed again. 

### Screenshots and recordings

![ohmyzshfreeze](https://github.com/ohmyzsh/ohmyzsh/assets/54847576/2457ba53-3a94-47db-974c-43638cde238e)

### OS / Linux distribution

ubuntu 20.04

### Zsh version

5.8.1

### Oh My Zsh version

master (486e56a)

### Terminal emulator

zsh

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
If the directory is a git repo, it's expected! We're working on making the `git status` faster, soon the fix :)

**Comment by Zonax40** [comment]
> If the directory is a git repo, it's expected! We're working on making the `git status` faster, soon the fix :)

It is indeed a git repo. Thanks for your answer.
