### ISSUE TITLE
`omz reload` throws the error `stat: /Users/<username>/.zcompdump: stat: No such file or directory`

### ISSUE THREAD

**Issue by revolter** [ohmyzsh/ohmyzsh#12253]
### Describe the bug

Simply running `omz reload` throws the error `stat: /Users/revolt/.zcompdump: stat: No such file or directory`.

### Steps to reproduce

1. `omz reload`

### Expected behavior

No error should be thrown.

### OS / Linux distribution

macOS Ventura 13.6.3

### Zsh version

5.9

### Oh My Zsh version

master (458fc2e)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Hi! Could you please set the tracing, and send the logs to logs@ohmyz.sh?
Let's see what's going on! Thanks!

To get the trace:
```sh
# open a shell
set -x
omz update > omz-trace.log 2>&1
```

**Comment by carlosala** [comment]
In the meantime, you could try to remove all `.zcompdump` files with `cd ~; rm -f .zcompdump*`. They are generated files, it shouldn't be an issue since they'll be regenerated in the next shell startup!

**Comment by carlosala** [comment]
Hi! Friendly ping @revolter. Is it still reproducible?

**Comment by revolter** [comment]
> Hi! Could you please set the tracing, and send the logs to [logs@ohmyz.sh](mailto:logs@ohmyz.sh)?

Sent them now.

> In the meantime, you could try to remove all `.zcompdump` files with `cd ~; rm -f .zcompdump*`. They are generated files, it shouldn't be an issue since they'll be regenerated in the next shell startup!

I actually did try this, but forgot to mention it in the issue description. The weird thing is that running them one after the other still throws that error:

```sh
$ cd ~; rm -f .zcompdump*

$ omz reload
stat: /Users/revolt/.zcompdump: stat: No such file or directory
```

> Hi! Friendly ping @revolter. Is it still reproducible?

Really sorry for the late reply 🙈 I was busy these last days.

**Comment by mcornella** [comment]
OK we don't have visibility into what's making the stat:
```sh
+omz:1> [[ 1 -gt 0 ]]
+omz:6> local command=reload
+omz:7> shift
+omz:11> ((  1  ))
+omz:16> _omz::reload
+_omz::reload:2> rm -f /Users/revolt/.zcompdump /Users/revolt/.zcompdump-user-host-5.9
+_omz::reload:5> local zsh=-zsh
+_omz::reload:7> [[ -zsh = -* ]]
+_omz::reload:7> -zsh
stat: /Users/user/.zcompdump: stat: No such file or directory
```
Can you run just these lines and send the log file again?
```
cd
rm -f .zcompdump*
zsh -xvic exit &>omz-debug.log
```

**Comment by revolter** [comment]
Don't ask why, but I have a `.zshrc` of 1 605 lines of code 😅 so I wouldn't want to send the logs.

But I took a look myself, and found this:
```sh
# autoload -Uz compinit && compinit
autoload -Uz compinit
+/Users/revolt/.zshrc:1577> autoload -Uz compinit
if [[ $(date +'%j') != $(stat -f '%Sm' -t '%j' ~/.zcompdump) ]]; then
	compinit
else
	compinit -C
fi
+/Users/revolt/.zshrc:1578> [[+/Users/revolt/.zshrc:1578> date +%j
+/Users/revolt/.zshrc:1578> [[ 102 != +/Users/revolt/.zshrc:1578> stat -f %Sm -t %j /Users/revolt/.zcompdump
stat: /Users/revolt/.zcompdump: stat: No such file or directory
+/Users/revolt/.zshrc:1578> [[ 102 != +/Users/revolt/.zshrc:1578> stat -f %Sm -t %j /Users/revolt/.zcompdump
stat: /Users/revolt/.zcompdump: stat: No such file or directory
+/Users/revolt/.zshrc:1578> [[ 102 !=  ]]
+/Users/revolt/.zshrc:1579> compinit
```

So, these lines:
```sh
# The following lines were added by compinstall
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-suffixes true
zstyle :compinstall filename "${HOME}/.zshrc"

fpath+=~/.zfunc

# autoload -Uz compinit && compinit
autoload -Uz compinit
if [[ $(date +'%j') != $(stat -f '%Sm' -t '%j' ~/.zcompdump) ]]; then
	compinit
else
	compinit -C
fi
_comp_options+=(globdots)
# End of lines added by compinstall
```
got added to my `.zshrc` file when I ran `compinstall` some many years ago.

Should I just delete the part that calls `stat`? 🤔

**Comment by mcornella** [comment]
Thanks for the update, and it looks like you figured it out. Oh My Zsh is essentially doing the `compinit` itself, so indeed you are free to remove those lines (at least the `compinit` part).
