### ISSUE TITLE
Support for gh copilot

### ISSUE THREAD

**Issue by Khobalt** [ohmyzsh/ohmyzsh#12250]
### If the feature request is for a plugin or theme, specify it here.

Github

### If the feature solves a problem you have, specify it here.

Currently "gh c[tab]" doesn't autofill `gh copilot` as an option, nor does it fill in all the (many) supported features and flags of `gh copilot`

I currently can't tab through the options and have to manually type them.

### Describe the proposed feature.

I'd like the oh-my-zsh gh plugin to autofill `gh copilot` and its options.

**Comment by carlosala** [comment]
Hi @Khobalt, thanks for your report!
Unfortunately we source the official completion issued by `gh` command. I'd recommend opening an issue (previously looking for some related ones) in https://github.com/cli/cli repo.
Have a nice day!
