### ISSUE TITLE
Enable autoloading of .nvmrcs after first usage of lazyloaded nvm

### ISSUE THREAD

**Issue by johannesrave** [ohmyzsh/ohmyzsh#12255]
### If the feature request is for a plugin or theme, specify it here.

nvm plugin

### If the feature solves a problem you have, specify it here.

I rarely use nvm and tend to forget it's there - but when I need it, I need it and in particular the autoloading of the correct node-version on entering a directory with a `.nvmrc`.
I use the nvm-plugin of omz to manage my installation, however having it on permanently more than doubles the time to open my terminal. Lazyloading mitigates that, but at the moment is incompatible with autoloading.

So at the moment I have the option to either set the omz-nvm-plugin to load lazily, but then not get autoloading even after nvm was loaded (by eg. using pnpm), or to take the performance hit always and then profit from autoloading in the 5% of cases I'm on a node project.

### Describe the proposed feature.

The behaviour I would like is this:

- lazily load nvm just as with the lazy option, when calling eg. pnpm or other related tools
- from that moment on, so as soon as nvm has been loaded that way, autoload .nvmrcs when entering a directory

### Additional context

I asked for this functionality here:

### Related Issues

I asked for this functionality here and was asked to create an issue:
https://github.com/ohmyzsh/ohmyzsh/issues/11748

**Comment by carlosala** [comment]
Closed in 94aa49c0b96fed98d2751107301c16f32de13383!
Thanks for your idea!
