### ISSUE TITLE
git-commit is broken?

### ISSUE THREAD

**Issue by yf-yang** [ohmyzsh/ohmyzsh#12251]
### Describe the bug

Seems to be this commit: https://github.com/ohmyzsh/ohmyzsh/commit/3ee108ccb301dd4143080e8bfd8f9ae869957a2e

``` shell
git feat "test"
```

```
a() {
local _scope _attention _message
while [ $# -ne 0 ]; do
case $1 in
  -s | --scope )
    if [ -z $2 ]; then
      echo "Missing scope!"
      return 1
    fi
    _scope="$2"
    shift 2
    ;;
  -a | --attention )
    _attention="!"
    shift 1
    ;;
  * )
    _message+=" $1"
    shift 1
    ;;
esac
done
git commit -m "feat${_scope:+(${_scope})}${_attention}:${_message}"
}; a: 18: _message+= test: not found
```

### Steps to reproduce

Enable plugin git-commit
create any change
try to use git-commit to commit

### Expected behavior

Successfully commit

### OS / Linux distribution

Ubuntu 22.04.3 LTS

### Zsh version

5.8.1

### Terminal emulator

Unrelated

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
I can't reproduce, could run the same with `GIT_TRACE=1`?

**Comment by yf-yang** [comment]
With `GIT_TRACE=1`, run `git feat "abc"`

``` shell
09:52:40.338179 git.c:748               trace: exec: git-feat abc
09:52:40.338307 run-command.c:661       trace: run_command: git-feat abc
09:52:40.343128 run-command.c:661       trace: run_command: 'a() {
local _scope _attention _message
while [ $# -ne 0 ]; do
case $1 in
  -s | --scope )
    if [ -z $2 ]; then
      echo "Missing scope'\!'"
      return 1
    fi
    _scope="$2"
    shift 2
    ;;
  -a | --attention )
    _attention="'\!'"
    shift 1
    ;;
  * )
    _message+=" $1"
    shift 1
    ;;
esac
done
git commit -m "feat${_scope:+(${_scope})}${_attention}:${_message}"
}; a' abc
a() {
local _scope _attention _message
while [ $# -ne 0 ]; do
case $1 in
  -s | --scope )
    if [ -z $2 ]; then
      echo "Missing scope!"
      return 1
    fi
    _scope="$2"
    shift 2
    ;;
  -a | --attention )
    _attention="!"
    shift 1
    ;;
  * )
    _message+=" $1"
    shift 1
    ;;
esac
done
git commit -m "feat${_scope:+(${_scope})}${_attention}:${_message}"
}; a: 18: _message+= abc: not found
09:52:40.348725 git.c:462               trace: built-in: git commit -m feat:
```

BTW according to the log, I think that's a pure shell script problem.

For example, if I create a file called `test.zsh`
``` shell
while [ $# -ne 0 ]; do
_message=""
case $1 in
  * )
    echo "argument: $1"
    _message+=" $1"
    shift 1
    ;;
esac
done
echo $_message
```
Give the script `755` permission, then run `./test.zsh "abc"`

>argument: abc
./test.zsh: 6: _message+= abc: not found

**Comment by yf-yang** [comment]
Ah, let me give you a minimum reproducible code:
``` shell
_message=""
variable="abc"
_message+=" $variable"
echo $_message
```

Put the code to `test.zsh`, give permission 755, run `./test.zsh`, then
> ./test.zsh: 3: _message+= abc: not found

Instead, directly copy paste the code into zsh, it can run.

**Comment by yf-yang** [comment]
OK, I realize the problem, vscode telling me this is zsh but actually `$SHELL` is `/bin/bash`. I'll check it out.

**Comment by carlosala** [comment]
Nevertheless, I'm not 100% sure about the `+=` for assigning strings in POSIX shell. I changed it 👍🏻

**Comment by yf-yang** [comment]
Thanks a lot. Would you like to take a look of this:

By adding this line
``` shell
echo $(readlink /proc/$$/exe)
```
After some debugging, I found when the plugin is loaded, it is `/usr/bin/zsh`
However, when I am running `git feat "abc"`, it becomes `/usr/bin/dash`.

I am not a shell expert, do you know if this is working correctly?

**Comment by yf-yang** [comment]
Anyways, your latest fix does resolve the issue. I may leave it there, thank you for your help 😄
