### ISSUE TITLE
zshrc file overwritten automatically

### ISSUE THREAD

**Issue by gabemorris12** [ohmyzsh/ohmyzsh#12271]
When I ran `sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"` to install everything, it overwrote my zshrc file completely. I had things in there that were important. Not cool.

**Comment by mcornella** [comment]
The original is not deleted, but renamed. Please see https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#my-zshrc-file-was-deleted-on-install for how to access it.

**Comment by mcornella** [comment]
It's a tricky thing, because most times OMZ needs to be at the top in order to not override user settings. It is definitely on our radar though.
