### ISSUE TITLE
Allow setting plugins in the custom folder

### ISSUE THREAD

**Issue by tallen1983** [ohmyzsh/ohmyzsh#12279]
### If the feature solves a problem you have, specify it here.

I like to keep everything I configure in the `.oh-my-zsh/custom/` folder. That way I can keep those versioned and easy to move across machines.

If I try to put `plugins=(...)` in the custom folder it is ignored. It looks like it is set too late, and the plugins specified in the .zshrc are used instead. If I check the variable in the shell it returns back whatever I specify in the custom folder, but only the plugins specified in .zshrc are actually loaded.

### Describe the proposed feature.

Allow setting the plugins variable in the custom folder

### Describe alternatives you've considered

I have to edit the .zshrc file on each machine instead of simply installing zshrc and letting my custom folder specify the plugins.

**Comment by carlosala** [comment]
Hi! It's exactly the other way around! Make sure you place the plugins in `$ZSH/custom/plugins/<my-plugin>` and it will work!

**Comment by tallen1983** [comment]
@carlosala I think you misunderstood. I am not trying to add a custom plugin.

I am trying to pick the list of plugins to activate in a `.oh-my-zsh/custom/plugins.zsh` file but it is ignored. For example:

In `.zshrc`: `plugins=(git)`
Then in `.oh-my-zsh/custom/plugins.zsh`: `plugins=(git foo bar)`

I would expect git, foo, and bar plugins to be loaded. But only git is.

**Comment by carlosala** [comment]
I understand what you say; it's actually expected behavior. `.zsh` files under `$ZSH_CUSTOM` are loaded after plugins.
