### ISSUE TITLE
Split gwip alias into more and less aggressive ones

### ISSUE THREAD

**Issue by kopach** [ohmyzsh/ohmyzsh#12276]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### If the feature solves a problem you have, specify it here.

I often do `gwip` and push to PR. But I also want my CI pipelines to run. This way I can continue work and see if/which linters/build fails to fix them later

### Describe the proposed feature.

Add another, less "aggressive" command which would create `--wip--` comment but without `[skip ci]` part
> possibly also without `--no-gpg-sign` which in some cases would block push to repo which requires this

My proposal would be:
1. change current `wip` command to do not have `[skip ci]` part in commit message (and maybe also remove `--no-gpg-sign`)
2. add extra command `wip!` which would do same thing as current implementation of `wip` (so, has `[skip ci]` part in commit message and `--no-gpg-sign`)

---
I have this setup locally for a while, and it works for me

### Describe alternatives you've considered

Another option would be to keep current `wip` as is for backward compatibility and create extra command for commit without `[skip ci]` and GPG sign. I have no good naming for this command, though, please help here. Maybe again `wip!`, but it would be a bit counterintuitive, I guess `¯\_(ツ)_/¯`

### Additional context

I'm willing to contribute, just let me know if you like this idea

**Comment by carlosala** [comment]
Hi! We're not really looking forward to adding more aliases into git plugin if they're not "strictly necessary" (if it's a big amount of users requesting some workflow).
I encourage you to add your own aliases under your user's config!
Thanks for the idea!
