### ISSUE TITLE
Upgrade.sh fails "fatal: not a git repository (or any parent up to mount point /)

### ISSUE THREAD

**Issue by WorldTeacher** [ohmyzsh/ohmyzsh#12273]
### Describe the bug

Running `topgrade` to upgrade the system causes it to crash at the .oh-my-zsh step 
 This is the error i get:
 ```
 fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not in a git directory
fatal: not in a git directory
fatal: not in a git directory
fatal: not in a git directory
fatal: not in a git directory
fatal: not in a git directory
fatal: --local can only be used inside a git repository
fatal: --local can only be used inside a git repository
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
``` 

### Steps to reproduce

1. use topgrade
2. see .oh-my-zsh step
3. watch it fail after pulling extensions and confirming that they are up-to-date

### Expected behavior

The script should be able to update omz and plugins / themes

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Terminal emulator

Kitty

### If using WSL on Windows, which version of WSL

None

### Additional context

I have these plugins / themes:
powerlevel10k
zsh-autosuggestions
zsh-syntax-highlighting
zsh-completions

installed using the Oh-my-zsh method
example:
`git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions`

**Comment by mcornella** [comment]
Added a special case in `tools/upgrade.sh` in [c262ffb](https://github.com/ohmyzsh/ohmyzsh/commit/c262ffbb68e6dfc30b619e6ce6bdbd00f27b8a71) so that `$ZSH` is always defined.
