### ISSUE TITLE
ctrl+r reverse-i-search adds a big space next to $ prompt

### ISSUE THREAD

**Issue by bhcopeland** [ohmyzsh/ohmyzsh#12272]
### Describe the bug

Running theme agnoster, when using ctrl+r on latest ohmyzsh, I've suddenly noticed a big space gets added to the prompt

### Steps to reproduce

1. press ctrl+r 
2. a tab is inserted between the $prompt

### Expected behavior

No space to be added after the prompt

### Screenshots and recordings

![image](https://github.com/ohmyzsh/ohmyzsh/assets/3995595/5eb47afd-91aa-4ed8-9931-e65157a51dd3)

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Oh My Zsh version

r7155.32d4389aa-1

### Terminal emulator

GNOME Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by bhcopeland** [comment]
I have just fixed it by noticing by changing my locale file.

```
#LC_ALL=C
LC_ALL=en_GB.UTF-8
LANG=en_GB.UTF-8
```

Commented out LC_ALL=C was the issue.

**Comment by mcornella** [comment]
Non-UTF8 locales almost always come up with these kinds of prompt issues, see https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command.
