### ISSUE TITLE
Command to print all aliases in Kubectl

### ISSUE THREAD

**Issue by lautalom** [ohmyzsh/ohmyzsh#12296]
### If the feature request is for a plugin or theme, specify it here.

Kubectl

### If the feature solves a problem you have, specify it here.

This feature should be a standard in *all* "alias" plugins IMHO.

### Describe the proposed feature.

In a git plugin I use, I typically run something like `galias | grep rebase` to know all `git rebase` aliases of the plugin.

I would love the same feature here

**Comment by carlosala** [comment]
Hi! You can take advantage of [aliases plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/aliases). `als kubectl` will print all your aliases regarding it! You can as well search `als "git commit"` and it'll give only the ones that matter to commit, for example.
