### ISSUE TITLE
Typo found in templates/zshrc.zsh-template comments 

### ISSUE THREAD

**Issue by KohoolateSen** [ohmyzsh/ohmyzsh#12300]
### Describe the bug

I recently found  a weird spelling  at **templates/zshrc.zsh-template**

Here :
```
# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi
```
as you can see the second editor is **mvim** ,i think it's a typo 
and should be nvim instead ...

**(the only related editor i found to mvim was macvim which is obviously
built for MacOS not linux distros)**

and this may cause issues when people are uncommenting this section
they may not see it has  wrong spelling ...

### Steps to reproduce

1. make sure you have zsh installed
2. read **.zshrc** or **zshrc.zsh-template** like such : 
`cat -n /home/FOO/.zshrc`
or 
`cat -n  /home/FOO/ohmyzsh/templates/zshrc.zsh-template`
3. you'll see typo at line **88**
4. so if it was supposed to be nvim change the `mvim` to `nvim`

**NOTE :** this typo originates from `/home/FOO/ohmyzsh/templates/zshrc.zsh-template`
so to solve the problem the main template must be fixed.

### Expected behavior

I expect there be **nvim** instead of **mvim**

many people will not observe the issue when uncommenting this section 
for the sake of usage 

but rather after getting errors they know they must change mvim to nvim,

### OS / Linux distribution

Linux/Debian

### Zsh version

5.6

### Oh My Zsh version

master (bf303965)

### Terminal emulator

Terminator

### If using WSL on Windows, which version of WSL

None

**Comment by rwmitchell** [comment]
What makes you think MacOS users are not also using OMZ?

**Comment by carlosala** [comment]
Hey, thanks for the idea! Actually, that's more an "idea" of what to do in zshrc, it shouldn't be an issue to leave it as is.
Thanks!
