### ISSUE TITLE
TAB  auto-complete not work well

### ISSUE THREAD

**Issue by CCIE1024** [ohmyzsh/ohmyzsh#12317]
### Describe the bug

When I use the tab-complete command, the cursor moves forward, causing the cursor to stay in the wrong position.

### Steps to reproduce

When I hit the command gcc --ver and then use the TAB key to complete the commands that follow it, the cursor moves to the end of the first horizontal bar

### Expected behavior

Do not move the cursor forward

### OS / Linux distribution

macOS、Ubuntu22.04

### Zsh version

5.9 

### Terminal emulator

iTerm2、SecureCRT

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Please see if you are affected by `locale` issues as documented in https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command. If not, feel free to reopen.
