### ISSUE TITLE
Prompt string always showing [_omz_git_prompt_info] after update

### ISSUE THREAD

**Issue by lorenzotenti** [ohmyzsh/ohmyzsh#12321]
### Describe the bug

After updating to master (6d0362e), my prompt string looks like this:
```
➜  ~ [_omz_git_prompt_info]
```

If I enter a git project folder, it shows the git information correctly, and the `[_omz_git_prompt_info]` disappears, but as soon as I run another command, the `[_omz_git_prompt_info]` is back.  

### Steps to reproduce

Run omz update (master (6d0362e) on an Apple M2 Pro with macOS 14.2.1 (23C71)

### Expected behavior

The prompt string should behave as usual, showing no information in normal folders and git branches in git folders.

### OS / Linux distribution

macOS 14.2.1 (23C71)

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Hey! I'm not able to reproduce. I guess it comes from [here](https://github.com/ohmyzsh/ohmyzsh/blob/6d0362ef2f355a05cf945fae882ad1fa95428991/lib/git.zsh#L42-L52). Are you using `ksharrays`? You can figure it out by `echo $options[ksharrays]`.

**Comment by lorenzotenti** [comment]
Not sure, here's the output:

```
➜  ~ [_omz_git_prompt_info]echo $options[ksharrays]
zsh: no matches found: off[ksharrays]
➜  ~ [_omz_git_prompt_info]echo $options
off
```

**Comment by carlosala** [comment]
Could you share your `zshrc` and `zshenv` (if present)?

**Comment by carlosala** [comment]
I can reproduce the issue with `ksharrays` enabled. Let's see if there's any other option that triggers it.

**Comment by lorenzotenti** [comment]
The zshrc is basically the default one. But I just realised the problem get fixed if I remove a script that's sourced at the end of the zshrc.

In this script (which is based on https://github.com/samjsmart/bash-aws-helper/blob/master/zsh_aws_helper.sh) we enable ksharrays.

**Comment by carlosala** [comment]
Fixed! Thanks for the report (it should work now even if `ksharrays`) is enabled.

**Comment by lorenzotenti** [comment]
`omz update` fixed it indeed! Thanks a lot!
