### ISSUE TITLE
git information not appearing in rprompt

### ISSUE THREAD

**Issue by UlyssesZh** [ohmyzsh/ohmyzsh#12325]
### Describe the bug

The git information only appears if it is included in `PROMPT`. If it is only included in `RPROMPT`, it does not appear. If it is included in both `PROMPT` and `RPROMPT`, then it appears at both places as expected.

### Steps to reproduce

Use this theme:
```sh
RPROMPT='$(git_prompt_info)'
```

### Expected behavior

Shows git info aligned in the right.

### OS / Linux distribution

NixOS 23.11

### Zsh version

5.9

### Terminal emulator

GNOME

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Fixed in https://github.com/ohmyzsh/ohmyzsh/commit/038931039030911852d456215d6f39385d5b7a6e. You can get it by updating with `omz update`.

Thanks for the report!
