### ISSUE TITLE
add conda-zsh-completion plugin

### ISSUE THREAD

**Issue by xiaobili** [ohmyzsh/ohmyzsh#12320]
### If the feature request is for a plugin or theme, specify it here.

conda-zsh-completion

### If the feature solves a problem you have, specify it here.

the plugin `conda-zsh-completion` can provide the command prompt for conda
![CleanShot 2024-04-04 at 03 34 58](https://github.com/ohmyzsh/ohmyzsh/assets/25179891/9bd00d2a-8e44-4273-84c4-6e73d40d8236)

this is the plugin github addr: [conda-zsh-completion](https://github.com/conda-incubator/conda-zsh-completion)

### Describe the proposed feature.

this plugin can prompt command for conda

**Comment by carlosala** [comment]
Hey! Since there's already a repo for it, it can perfectly be a custom plugin. You can send a PR to https://github.com/ohmyzsh/wiki to add it to external plugins!
Thanks for the idea!
