### ISSUE TITLE
git async prompt does not appear

### ISSUE THREAD

**Issue by carlosala** [ohmyzsh/ohmyzsh#12328]
Same problems as OP:

Before:

![image](https://github.com/ohmyzsh/ohmyzsh/assets/13176356/0092068d-c639-45bd-bbea-3fbffcbabef9)

After:

![image](https://github.com/ohmyzsh/ohmyzsh/assets/13176356/8a8f5ec2-5f54-467f-a7a7-c1cd9a06cd03)

theme: https://github.com/sobolevn/sobole-zsh-theme
zsh version: 5.9 (x86_64-debian-linux-gnu)
git version: 2.39.2
Debian GNU/Linux 12

_Originally posted by @hwalinga in https://github.com/ohmyzsh/ohmyzsh/issues/12267#issuecomment-2040655456_

**Comment by carlosala** [comment]
I see, your theme uses a [custom function](https://github.com/sobolevn/sobole-zsh-theme/blob/40ef40c1fb5eb5c1e7bbab913a7dbfbf1f449aa9/sobole.zsh-theme#L49-L51) print git information. We didn't take into account this situation. It's reproducible as well with `minimal` theme bundled in `oh-my-zsh`.

**Comment by carlosala** [comment]
@mcornella we need to find a new way of discovering that it's indeed being used. Maybe with a fd or something like that?

**Comment by carlosala** [comment]
#12327 reports exactly the same regression

**Comment by 134130** [comment]
FYI: The third-party plugin 'bullet-train' is also in the same problem.

**Comment by LockonS** [comment]
> FYI: The third-party plugin 'bullet-train' is also in the same problem.

Encounter the same issue for bullet-train theme. There is a temporary work around for this.

```shell
# replace this line
BULLETTRAIN_GIT_PROMPT_CMD="\$(git_prompt_info)"
# to 
BULLETTRAIN_GIT_PROMPT_CMD="\$(_omz_git_prompt_info)"
```

**Comment by dintz** [comment]
> FYI: The third-party plugin 'bullet-train' is also in the same problem.

Yes, same problem here (also with bullet-train)!

**Comment by dintz** [comment]
> > FYI: The third-party plugin 'bullet-train' is also in the same problem.
> 
> Encounter the same issue for bullet-train theme. There is a temporary work around for this.
> 
> ```shell
> # replace this line
> BULLETTRAIN_GIT_PROMPT_CMD="\$(git_prompt_info)"
> # to 
> BULLETTRAIN_GIT_PROMPT_CMD="\$(_omz_git_prompt_info)"
> ```

I have the same problem with bullet-train, but the workaround is helping for the meantime! Thx

**Comment by groud** [comment]
I have the same issue with the pygmalion theme, but it seems the workaround (replacing `git_prompt_info` by `_omz_git_prompt_info`) does not work for me.

**Comment by stevenharman** [comment]
I'm hitting something similar, and I believe related. I updated `omz` today and started seeing an errant `then then` in my prompt. After then upgrade:

My standard config, using a custom theme which relies on `git_prompt_info`:

![zsh-async-git-asybc-enabled](https://github.com/ohmyzsh/ohmyzsh/assets/48658/1aaf228f-674b-4ec4-9f80-1887a638ff31)

If I switch `git_prompt_info` to use `_omz_git_prompt_info`, the `then then` no longer appear:

![zsh-async-git-omz-status](https://github.com/ohmyzsh/ohmyzsh/assets/48658/4fe28dce-656c-4dd5-8b19-50a401550be9)

Similarly, I can use the `git_prompt_info` as before, so long as I disable `async-prompt` via

```zsh
zstyle ':omz:alpha:lib:git' async-prompt no
```

![zsh-async-git-async-disabled](https://github.com/ohmyzsh/ohmyzsh/assets/48658/146c9684-bb15-43d3-89ed-19964e347eb4)

**Comment by mcornella** [comment]
Hi folks! This hasn't been suggested yet, and it's going to be the easier temporary fix while we figure out a cleaner transition path for themes dependent on the current functions.

Setting the code below in your `.zshrc` file, before Oh My Zsh is sourced:

```sh
zstyle ':omz:alpha:lib:git' async-prompt no 
```

https://github.com/ohmyzsh/ohmyzsh?tab=readme-ov-file#disable-async-git-prompt

Keep an eye on this issue for updates on improvements!

**Comment by greenchapter** [comment]
> Hi folks! This is going to be the easiest temporary fix while we figure out a cleaner transition path for themes dependent on the current functions.
> 
> Setting the code below in your `.zshrc` file, before Oh My Zsh is sourced:
> 
> ```shell
> zstyle ':omz:alpha:lib:git' async-prompt no 
> ```
> 
> https://github.com/ohmyzsh/ohmyzsh?tab=readme-ov-file#disable-async-git-prompt
> 
> Keep an eye on this issue for updates on improvements!

Unfortunately doesn't work for me 😞

**Comment by mcornella** [comment]
> Unfortunately doesn't work for me 😞

Did you put this line before the `source $ZSH/oh-my-zsh.sh` line?

**Comment by christian-heusel** [comment]
> Unfortunately doesn't work for me 😞

Also you need to reload your shell 😊

**Comment by greenchapter** [comment]
> > Unfortunately doesn't work for me 😞
> 
> Did you put this line before the `source $ZSH/oh-my-zsh.sh` line?

Ah good hint, now it works 🙏

**Comment by greenchapter** [comment]
> > Unfortunately doesn't work for me 😞
> 
> Also you need to reload your shell 😊

Yes of course, I did it. Thank you 😀

**Comment by guydunigo** [comment]
Hello,
To add on this issue, in `lib/git.sh` I see you only register the async function if you find find `$(git_prompt_info)` in PS1.
However, I wrap this text in another function that displays it conditionally so it doesn't directly appear in `echo $PS1`...

So I played dumb and added that after omz is loaded in my zshrc : `export PROMPT="${PROMPT}"'$(echo "$(git_prompt_info)" 1>/dev/null)'`

And it works ! Now I can see the git prompt appear async (slightly after the rest).

Maybe it is a similar issue noted above. So it is probably the detection mechanism that should be changed.
Quick idea : try to expand PS1 before testing if `git_prompt_info` is in it.

**Comment by TsubasaEX** [comment]
Have been encountering the same problem with theme "bullet-train".
There is no branch info attached in the prompt but just a flag icon.
I've tried zstyle ':omz:alpha:lib:git' async-prompt no and omz reload but it didn't work.

![image](https://github.com/ohmyzsh/ohmyzsh/assets/34151841/d7cdb238-3df6-4479-82b7-b8685fa5ff2e)

**Comment by mcornella** [comment]
That needs to be put in your `.zshrc` file, before Oh My Zsh is `source`d. We are working on getting this right, as there is a current mitigation. Will update in here when we have a definitive fix.

**Comment by sukhmel** [comment]
I will write here, too, because maybe someone happens to use NixOS and know a way to apply this recommendation:

> Setting the code below in your .zshrc file, before Oh My Zsh is sourced:
> ```
> zstyle ':omz:alpha:lib:git' async-prompt no 
> ```

NixOS seems to only allow a [very limited](https://search.nixos.org/options?channel=24.05&show=programs.zsh.ohMyZsh.custom&from=0&size=50&sort=relevance&type=packages&query=zsh) set of changes to zsh config. There is `initExtra` that would be the way to inject anything into `.zshrc`, but it goes down after everything and makes no difference, obviously.

**Comment by arobinson** [comment]
It seems that adding `zstyle ':omz:alpha:lib:git' async-prompt no` to my zshrc will cause the PTY integration of VS code to hang in the current versions of code. So if you are using VS code with the debugger, you may not want to use this as a work-around to the bug.

**Comment by carlosala** [comment]
If anyone finds that its git prompt does not appear they can set before `source oh-my-zsh.sh` the following snippet:

```sh
zstyle ':omz:alpha:lib:git' async-prompt force
```

This was introduced in `2a109d30afe4ab164a946c307abc3d2a444a42ad`
