### ISSUE TITLE
Last update git untracked status is gone within the prompt

### ISSUE THREAD

**Issue by greenchapter** [ohmyzsh/ohmyzsh#12327]
### Describe the bug

With one of the last updates of oh-my-zsh the git unstracked status is gone within my prompt.

Normally my prompt with untracked files looks like that 

```bash
* ~/.dotfiles (main %) »
```

but currently there is no more status indicator like that `%` or even the `+` when I staged some files

I think the change comes with this pull request https://github.com/ohmyzsh/ohmyzsh/pull/12319

### Steps to reproduce

1. Make a new git repository with `mkdir test` `cd test` and initialise a new repo with `git init`
2. Add a empty file with `touch test``

Now you should see that you don't see an indicator it looks like that 

```bash
* ~/.dotfiles (main) »
```

### Expected behavior

In my opinion the indicator for untracked files should be again in the prompt, like this

```bash
* ~/.dotfiles (main %) »
```

### OS / Linux distribution

Darwin machine.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

### Zsh version

5.9

### Terminal emulator

iTerm 2

### If using WSL on Windows, which version of WSL

None

### Additional context

Thank you for helping 💖

**Comment by carlosala** [comment]
Which theme are you using? I think it might be the same regression found in #12328

**Comment by greenchapter** [comment]
> Which theme are you using? I think it might be the same regression found in #12328

Have the same experience with `lukerandall`  and two others

**Comment by carlosala** [comment]
It's indeed the same regression. Let's close it and keep track of it in #12328. It's something that we really want to fix 👍🏻
