### ISSUE TITLE
WHY

### ISSUE THREAD

**Issue by IamJasonBoy** [ohmyzsh/ohmyzsh#12333]
### Describe the bug

WHY

### Steps to reproduce

WHY

### Expected behavior

WHY

### OS / Linux distribution

linux

### Zsh version

5.6

### Terminal emulator

no

### If using WSL on Windows, which version of WSL

None

### Additional context

![image](https://github.com/ohmyzsh/ohmyzsh/assets/131987857/dad66b9e-191d-4b5a-8b78-06a77e5a15d7)

**Comment by IamJasonBoy** [comment]
(aidisdk) (base) [v-pengfei.jia@ci-gpu006 aidisdk]$ zsh
(aidisdk) ➜  aidisdk Segmentation fault (core dumped)
(aidisdk) (base) [v-pengfei.jia@ci-gpu006 aidisdk]$

**Comment by mcornella** [comment]
Please reopen with relevant information filled.
