### ISSUE TITLE
omz_history -p doesn't work as expected

### ISSUE THREAD

**Issue by MoAlkhateeb** [ohmyzsh/ohmyzsh#12334]
### Describe the bug

- In bash, in order to not save the history for the current session you use `history -c`. To do the same in zsh you use `history -p` instead.
- Using ohmyzsh, `history -c` clears the history file completely instead of just not saving the history for the current session. 
- The history file path is stored in the `HISTFILE` environment variable. By default, it's the `$HOME/.zsh_history` file.
- When using oh-my-zsh, `history` is aliased to the `omz_history` function. which is defined as follows:
https://github.com/ohmyzsh/ohmyzsh/blob/bf713e2c112ee1f0daf10deffa1215c982513f9b/lib/history.zsh#L2-L18

- When attempting to clear the history completely, you run `history -c` or its equivalent `omz_history -c`. This clears the history file completely as intended.
- When attempting to **not** save history for the _current_ session but not tampering with the history file, you would run `history -p`.
- However, when attempting to run `history -p` with ohmyzsh this results in running `builtin fc -l "$@" 1`. Here `"$@"` is set to `-p` which results in `builtin fc -l -p 1`. This indeed does not save the current session history to the original history file. However:
- What this causes is that the `HISTFILE` environment variable is overwritten with the value `1`. A file named `1` is automatically created in the current working directory and the session history is stored in it. Any attempt to remove the file within the session will result in it being recreated whenever any interactive command is executed until the session is exited.
- When the session is exited, the file still exists.

References:
- https://zsh.sourceforge.io/Doc/Release/Shell-Builtin-Commands.html (zsh builtins)

### Steps to reproduce

1. Start a new session 
2. Navigate to a directory with no files called `1`.
3. `echo $HISTFILE` should result in `$HOME/.zsh_history` by default.
4. run `history -p`
5. `echo $HISTFILE` results in `1`.
6. `ls` you find a file called `1`.

### Expected behavior

1. `history -p` unsets the `HISTFILE` environment variable.
2. No file is created.
3. Current session history is not preserved beyond the session.

### Screenshots and recordings

[![asciicast](https://asciinema.org/a/6HQvRYH9WHoWIN0H5tYJa1CIC.svg)](https://asciinema.org/a/6HQvRYH9WHoWIN0H5tYJa1CIC)

### OS / Linux distribution

macOS  Sonoma 14.4.1

### Zsh version

5.9

### Oh My Zsh version

master (bf713e2)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
I absolutely agree. @mcornella what do you think about? I'd remove https://github.com/ohmyzsh/ohmyzsh/blob/5bff59f78e607e77f2ed924c1e93ccc09a6ccb7e/lib/history.zsh#L16 and directly call `fc -l "$@"` instead of printing the whole history.

**Comment by MoAlkhateeb** [comment]
I came up with the same conclusion, replacing the else block with `builtin fc -l "$@"`. That way the user can have some control over the underlying `fc` call and at the same time users executing just `history` are not left out. 

Should I submit a PR for this? I would love to.

**Comment by carlosala** [comment]
Sure! Let's discuss in the PR with @mcornella

**Comment by MoAlkhateeb** [comment]
Great! #12338

**Comment by mcornella** [comment]
Thanks @MoAlkhateeb!
