### ISSUE TITLE
Avoid cluttering main `~/.zshrc`file with lots of lines

### ISSUE THREAD

**Issue by kartikrajjj** [ohmyzsh/ohmyzsh#12330]
Guys, I appreciate your work, but what your installer should do is adding

```
echo "#Some silly comment
  export ZSH=/home/vganzin/.oh-my-zsh
  source $ZSH/oh-my-zsh.sh" >> .zshrc
```
And not rewriting my precious .zshrc with so many lines without even questioning about it.

**Comment by carlosala** [comment]
Hey! The zshrc file is always backed up! You can read about it [here](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#my-zshrc-file-was-deleted-on-install)

**Comment by kartikrajjj** [comment]
Hi @carlosala, I understand it's always backed up, however the request here is to avoid writing so many lines to `.zshrc`, and instead just add the 2 lines so it's cleaner.

**Comment by zorion** [comment]
This solution would be much better!
Very clever!
