### ISSUE TITLE
how to update ZSH_THEME_GIT_PROMPT_PREFIX when git status changed?

### ISSUE THREAD

**Issue by crazytaxi824** [ohmyzsh/ohmyzsh#12335]
### Describe the bug

It is possible to change ZSH_THEME_GIT_PROMPT_PREFIX based on git_current_branch or parse_git_dirty functions before. After omz update, it seems no way to make it work.

### Steps to reproduce

none

### Expected behavior

change ZSH_THEME_GIT_PROMPT_PREFIX based on git_current_branch or parse_git_dirty functions before.

### OS / Linux distribution

macOS 14.4

### Zsh version

5.9

### Terminal emulator

Alacritty

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Hi! I can change as expected my `ZSH_THEME_GIT_PROMPT_PREFIX`. Which value are you trying to set, and which theme are you using?

**Comment by crazytaxi824** [comment]
Hi, I am trying to change `ZSH_THEME_GIT_PROMPT_PREFIX` based on `$(git_current_branch)`.

```shell
function branch_color() {
  local current_branch=$(git_current_branch)

  if [[ $current_branch == master || $current_branch == main  ]]; then
    ZSH_THEME_GIT_PROMPT_PREFIX="%K{196}%F{15} %B"
  else
    ZSH_THEME_GIT_PROMPT_PREFIX="%K{35}%F{234} "
  fi
}
```

Without `zstyle ':omz:alpha:lib:git' async-prompt no`, it is not working.

Thanks.

**Comment by crazytaxi824** [comment]
Thanks!
