### ISSUE TITLE
装有Omz的mac机器上ssh登录到装有Omz的机器上时 不能按 ctrl-c 换行

### ISSUE THREAD

**Issue by intern** [ohmyzsh/ohmyzsh#12359]
### Describe the bug

装有Omz的mac机器上ssh登录到装有Omz的机器上时 不能按 ctrl-c 换行
<img width="673" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/265386/1fc03f8a-0b22-4ca1-97d9-ea5396a78879">

### Steps to reproduce

1. can't do `ctrl-C` and break newline

### Expected behavior

enter ctrl-C to break newline

### OS / Linux distribution

Mac os 13.52

### Zsh version

current master

### Oh My Zsh version

master

### Terminal emulator

iTerm2, ssh

### If using WSL on Windows, which version of WSL

None

### Additional context

Please fix that

**Comment by Aleda** [comment]
I have the same issue. When connectting to a remote server via iterm2+ssh and the server use the latest version of omz, ctrl+C behaves inconsistently compared to before the upgrade. 
I revert the commit to a previous 70bf12402ceb5599f209bd687d4ee9d9dbf1776a, this issue was fixed.
