### ISSUE TITLE
pygmalion.zsh-theme lost git branch naming and ⚡️emoji

### ISSUE THREAD

**Issue by d1Ng0** [ohmyzsh/ohmyzsh#12350]
### Describe the bug

pygmalion.zsh-theme lost git branch naming and ⚡️emoji ornaments.
I tried to completely uninstall and reinstall oh my zsh and verified by switching to other themes and reverting back. 
I also completely replaced the .zshrc with defaults but the ⚡️emoji and git branch name is gone.

### Steps to reproduce

* Fresh install oh-my-zsh.
* Set pygmalion.zsh-theme
* Cd into a repo folder on a branch or or main

### Expected behavior

The prompt should show the branch name and if there are uncommited changes you should see a lightning bolt

### Screenshots and recordings

The git ornaments have disappeared

### OS / Linux distribution

macoOS 14.1

### Zsh version

5.9

### Oh My Zsh version

master (31f2025)

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
We're indeed aware of it, and working on a fix. You can follow https://github.com/ohmyzsh/ohmyzsh/issues/12328#issuecomment-2043492331 as a temporary workaround.
Closing (duplicates #12328)
