### ISSUE TITLE
fzf plugin fails to "find fzf installation directory" (because of changes in fzf)

### ISSUE THREAD

**Issue by chfour** [ohmyzsh/ohmyzsh#12355]
### Describe the bug

I updated my nixos system yesterday and now after launching a shell I get the following message:

```
[oh-my-zsh] fzf plugin: Cannot find fzf installation directory.
Please add `export FZF_BASE=/path/to/fzf/install/dir` to your .zshrc
```

I tried specifying that env var, but after digging into the code it seems the plugin wants the completion.zsh and key-bindings.zsh files, which it can't find because [as of fzf 0.48.0](https://github.com/junegunn/fzf/releases/tag/0.48.0) they are included in the binary and returned concatenated together by `fzf --zsh`. I'm guessing the fix is to just `eval "$(fzf --zsh)"` as the changelog says, instead of trying to source the files?

### Steps to reproduce

1. Enable plugin `fzf` with the fzf package available in PATH as usual
2. Reload or launch new shell
3. See error message

### Expected behavior

the fzf plugin working i guess? lol

### OS / Linux distribution

NixOS 24.05 (nixos-unstable)

### Zsh version

5.9

### Terminal emulator

GNOME Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by dsh2dsh** [comment]
Same problem here. As a workaround I've created 2 files in `~/.fzf` dir:

`completion.zsh`:

```
eval "$(fzf --zsh)"
```

and empty `key-bindings.zsh`.

**Comment by mcornella** [comment]
Can you test whether #12367 resolves this? You can do so via `omz pr test 12367`. Thanks!

**Comment by dsh2dsh** [comment]
> `omz pr test 12367`

Thank you @mcornella , it fixed my issue.
