### ISSUE TITLE
Updating Oh My Zsh issues

### ISSUE THREAD

**Issue by ljcliu** [ohmyzsh/ohmyzsh#12361]
### Describe the bug

Auto-merging README.md
Auto-merging plugins/git-prompt/README.md
Auto-merging plugins/laravel/README.md
CONFLICT (content): Merge conflict in plugins/laravel/README.md
Auto-merging plugins/macos/README.md
error: could not apply 68f32c2... update
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 68f32c2... update
There was an error updating. Try again later?
plugins/laravel/README.md: needs merge
error: you need to resolve your current index first

### Steps to reproduce

omz update

### Expected behavior

it should update without any errors

### Screenshots and recordings

<img width="641" alt="Screenshot 2024-04-17 at 9 45 59 AM" src="https://github.com/ohmyzsh/ohmyzsh/assets/44239616/211043a0-9ea5-4c76-9669-0baf2d43ca14">

### OS / Linux distribution

macOS14.4.1

### Zsh version

5.9

### Terminal emulator

iterm2

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Hello, this error message means there are git conflicts within the OMZ folder, perhaps due to code changes you have made yourself. If you don't have anything of value or changes you want to keep, you can remove them by doing the commands below:
```sh
cd "$ZSH"
git status && git diff # CHECK THE GIT CONFLICT CHANGES
```
If everything looks right, or you're unaware of any changes done, just run:
```sh
cd "$ZSH"
git reset --hard HEAD # THIS WILL REMOVE ALL CHANGES
```

**Comment by ljcliu** [comment]
Thank you!

**Comment by ondrejzacha** [comment]
Thanks, this worked for me! I had the same issue running `omz update`, getting
```
➜ omz update                                                                               
plugins/shell-proxy/ssh-proxy.py: needs merge
error: you need to resolve your current index first
```
I'm unaware of any changes I made to the plugin itself, so this may be a more common issue. Adding the error message for discoverability
