### ISSUE TITLE
parse error near `then` in check_for_upgrade.sh

### ISSUE THREAD

**Issue by phuctm97** [ohmyzsh/ohmyzsh#12363]
### Describe the bug

I just updated Oh My Zsh then it had this error whenever I open my shell.

I check and saw that there was a missing `\`, I had to add that manually and it worked.

![CleanShot 2024-04-18 at 12 51 57@2x](https://github.com/ohmyzsh/ohmyzsh/assets/25026967/44c3f2ee-c335-4f34-a5da-28aed255ffe4)

### Steps to reproduce

Just update to `master (56cfcb4)` version and open the shell

### Expected behavior

It shouldn't error

### OS / Linux distribution

macOS 14.4.1

### Zsh version

5.9

### Oh My Zsh version

master (56cfcb4)

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

**Comment by phuctm97** [comment]
I saw the latest commit fixed this, updating to latest solved this issue 😄

**Comment by dyegoe** [comment]
I can confirm! Thanks @phuctm97
