### ISSUE TITLE
eval "$(fzf --zsh)" is failing

### ISSUE THREAD

**Issue by pvshingala1997** [ohmyzsh/ohmyzsh#12387]
### Describe the bug

changes made to file plugins/fzf/fzf.plugin.zsh is failing.

### Steps to reproduce

Adding fzf as a plugin which will give result as a invalid option of fzf --zsh

### Expected behavior

It should execute thouroughly

### Screenshots and recordings

![image](https://github.com/ohmyzsh/ohmyzsh/assets/16613915/1733525e-807d-4b64-93cd-288ba47899a9)
![image](https://github.com/ohmyzsh/ohmyzsh/assets/16613915/8fb5cf3a-5e36-4371-9f5b-7161d7221303)

### OS / Linux distribution

Windows 11

### Zsh version

5.8

### Oh My Zsh version

master (803e1a78)

### Terminal emulator

Windows Terminal Integrated with Cygwin which is configured with zsh

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Hi! What does `fzf --version` output for you?

**Comment by pvshingala1997** [comment]
![image](https://github.com/ohmyzsh/ohmyzsh/assets/16613915/4950298d-4bf5-4a21-b2d5-b32a4e246016)

**Comment by pvshingala1997** [comment]
It is in cygwin terminal

**Comment by carlosala** [comment]
Yep, your `fzf` version is really old, and the version formatting changed a bit.

**Comment by pvshingala1997** [comment]
Unable to see update on fzf for cygwin. Will you be releasing any package on cygwin?

**Comment by carlosala** [comment]
I'll submit a patch to cover your corner case, np 👍🏻
