### ISSUE TITLE
omz_urlencode:45: pcre_exec() error [-10] 

### ISSUE THREAD

**Issue by alps2006** [ohmyzsh/ohmyzsh#12388]
### Describe the bug

`omz_urlencode` cause `omz_urlencode:45: pcre_exec() error [-10]` when setting `setopt rematchpcre ` and entering a multi-byte directory.

The file `lib/termsupport.zsh` can call the function `omz_urlencode` of `lib/functions.zsh`.

### Steps to reproduce

```shell
~/scripts ❯ setopt rematchpcre ; omz_urlencode "你好"
omz_urlencode:45: pcre_exec() error [-10]
omz_urlencode:45: pcre_exec() error [-10]
omz_urlencode:45: pcre_exec() error [-10]
omz_urlencode:45: pcre_exec() error [-10]
omz_urlencode:45: pcre_exec() error [-10]
omz_urlencode:45: pcre_exec() error [-10]

```

### Expected behavior

none

### OS / Linux distribution

macOS 10.15

### Zsh version

5.9

### Oh My Zsh version

master (803e1a78)

### Terminal emulator

kitty

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
I can't reproduce it on my system, but I think we should `setopt localoptions norematchpcre`. We're heavily using regexes there and it'd be great to have that more controlled. @mcornella what do you think about it?

PS: this issue reminds me to #12202, I'd say there's some issue for sure with `rematchpcre` and macOS...

**Comment by mcornella** [comment]
LGTM, we can disable it for `omz_urlencode`. That said, I think if pcre_exec is broken in that case, any regex matching in zsh will fail for them, so it would also be advisable to not turn it on.
