### ISSUE TITLE
git plugin: please add commit & push alias

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ohmyzsh/ohmyzsh#12385]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### Describe the proposed feature.

Like

amp() {
    git commit -am "$1"
    git push
}

**Comment by carlosala** [comment]
Hi! We have two separate aliases for that! (`gcam` `gp`).
If you particularly need that alias, I recommend you define it in your zshrc. We're trying to avoid polluting more with aliases of the `git` plugin unless something is critical.
Thanks for the idea!
