### ISSUE TITLE
Alias Arguments Not Being Recognized

### ISSUE THREAD

**Issue by ChaseKolozsy** [ohmyzsh/ohmyzsh#12393]
### Describe the bug

The following is in my .zshrc file:

alias tn="(){tmux new -s $1}"
alias gc="(){git commit -m $1}"

NOTE: all the other aliases that do not have parameters work 
NOTE: source .zshrc has been executed in terminal

Outputs for alias commands in terminal:

```
chasekolozsy@Chases-MacBook-Pro ~ % tn Test
command new-session: -s expects an argument
chasekolozsy@Chases-MacBook-Pro ~ % gc "test commit"
error: switch `m' requires a value
chasekolozsy@Chases-MacBook-Pro ~ %
```

### Steps to reproduce

install ohmyzsh using the curl command
brew install tmux
install git

add the following aliases to the .zshrc file:

alias tn="(){tmux new -s $1}"
alias gc="(){git commit -m $1}"

execute in terminal:
source .zshrc

execute in terminal:

tn Test

gc "test commit"

### Expected behavior

tmux should run a new session called Test for tn Test
git should create a commit with commit message "test commit"

### OS / Linux distribution

MacOS 14 

### Zsh version

5.9

### Oh My Zsh version

master (529f77a)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

### Additional context

It has this issue right out of the box and after installing plugins autocomplete and syntax highlighting.

**Comment by carlosala** [comment]
Hi! I recommend you define those aliases as `alias tn="tmux new -s"` and `alias gc="git commit -m"`. You can pass arguments to regular aliases as if they were commands!

Note: both aliases already exist in the `tmux` and `git` plugins, respectively. `tn` alias will directly work if you enable tmux plugin and `gcmsg` do exactly what you want!

**Comment by ChaseKolozsy** [comment]
Thanks!
