### ISSUE TITLE
Unexpected backslash ( \ ) when opening in vscode terminal

### ISSUE THREAD

**Issue by prime0x2** [ohmyzsh/ohmyzsh#12398]
### Describe the bug

I have git in my Windows 10. I installed zsh and was trying to add oh my zsh to give it new look.
Everything is fine except when I open Git Bash in terminal it adds a backslash before my prompt. I've added a screenshot below for reference. 

![image](https://github.com/ohmyzsh/ohmyzsh/assets/48878200/8d10a3a4-1c61-4b0f-8f04-7f0613efc0bb)

Note: This is happening on my office laptop (windows 10). It also happened when I tried to do the same thing on my personal laptop (windows 10). Same scenario, same issue. This only happens when I open Git Bash in vscode terminal. It doesn't happen when I open Git Bash directly. Here is a screenshot of Git Bash opening directly

![image](https://github.com/ohmyzsh/ohmyzsh/assets/48878200/b10aca0c-307a-4fbc-8887-07a58f13a4ab)

This only happens in Git Bash. I installed WSL Ubuntu and did the same thing, but there is no problem. When I open WSL ubuntu in vscode terminal, there is no backslash (as it should be).

This was happening for a long time on my personal laptop. Tried to find any solution, but didn't find anything regarding this issue so I thought may be it's my machine. But I got a new job and got a new laptop, same problem appears. That's when I knew something is off.

So, I was hoping is there any solution to this?

### Steps to reproduce

OS: Windows 10

1. Install Git Bash to the system
2. Install ZSH, VS Code
3. Install Oh My ZSH
4. Open VS Code terminal (By default it opens powershell)
5. From VS Code terminal list, open Git Bash

### Expected behavior

This is WSL when opening in VS Code terminal

![image](https://github.com/ohmyzsh/ohmyzsh/assets/48878200/23a57af7-1dce-48c8-847b-699759bdba8f)

This is when I open Git Bash directly

![image](https://github.com/ohmyzsh/ohmyzsh/assets/48878200/b10aca0c-307a-4fbc-8887-07a58f13a4ab)

This is how it should be

### Screenshots and recordings

This is when I open Git Bash from VS Code terminal

![image](https://github.com/ohmyzsh/ohmyzsh/assets/48878200/8d10a3a4-1c61-4b0f-8f04-7f0613efc0bb)

### OS / Linux distribution

Windows 10

### Zsh version

5.9

### Oh My Zsh version

master (668ca3a)

### Terminal emulator

Git Bash

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Hi this is a bug in VS Code version, see #11765.
