### ISSUE TITLE
rsync-move has not delete directory.

### ISSUE THREAD

**Issue by jeffery9** [ohmyzsh/ohmyzsh#12403]
https://github.com/ohmyzsh/ohmyzsh/blob/8c5f64cc2f0e75399a1e906e39713ed25b65ece1/plugins/rsync/rsync.plugin.zsh#L2

need to delete directory also.

**Comment by jeroensmink98** [comment]
You could change the alias to include a `find` which can search and delete the empty directories. The first parameter of the is the source directory and the second the destination.

```bash
rsync -avz --progress -h --remove-source-files SOURCE DESTINATION && find SOURCE -type d -empty -delete
```

**Comment by mcornella** [comment]
You can also redefine the alias in your `.zshrc` file to include the `-m` argument, as per [[1]].

Changing the alias at this point is not feasible, as it constitutes a breaking change. 

[1]: https://explainshell.com/explain?cmd=rsync+-am+origin+destination#:~:text=You%20must%20separately%20specify%20%2DH,have%20no%20non%2Ddirectory%20children.
