### ISSUE TITLE
(eval):10: parse error near `^M'

### ISSUE THREAD

**Issue by iris-qq** [ohmyzsh/ohmyzsh#12416]
### Describe the bug

![企业微信截图_17155882991030](https://github.com/ohmyzsh/ohmyzsh/assets/32732041/3d4b82d3-eb3e-4cd6-a64c-a761b543a8d1)
windows11+git bash+ ohmyszah+conda

![企业微信截图_17155882121555](https://github.com/ohmyzsh/ohmyzsh/assets/32732041/43951e1c-969a-4401-b807-6ac3120777f3)
conda generate code into .zshrc 
![企业微信截图_17155882526898](https://github.com/ohmyzsh/ohmyzsh/assets/32732041/cd7420b5-8c05-44ab-a3f2-b5b9f01b7675)

### Steps to reproduce

conda init zsh

conda activate test

### Expected behavior

you can step into a env from conda

### Screenshots and recordings

help

### OS / Linux distribution

windows11

### Zsh version

5.9

### Terminal emulator

Terminal preview

### If using WSL on Windows, which version of WSL

None

### Additional context

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
if [ -f '/d/Softwares/anaconda3/Scripts/conda.exe' ]; then
    eval "$('/d/Softwares/anaconda3/Scripts/conda.exe' 'shell.zsh' 'hook')"
fi
# <<< conda initialize <<<
```

**Comment by carlosala** [comment]
You shouldn't source `zshrc`, just do `exec zsh` or `omz reload` if you want to restart your shell.
That seems a situation to report to `conda`, it seems like oh-my-zsh is not affecting here.

**Comment by iris-qq** [comment]
yes, I had report this to conda, `omz reload` not effect

```
➜  ~ omz reload
(eval):10: parse error near `^M'
➜  ~
```

**Comment by mcornella** [comment]
The issue here is that the `.zshrc` file has Windows line breaks (CRLF) instead of Unix line breaks (LF). The `^M` character in the error corresponds to the CR (Carriage Return) character (equivalent to `\r`).

To prevent this, first change the `.zshrc` file to Unix line breaks with command `dos2unix .zshrc`, and any modifications you make to it make sure to save with LF line breaks.

**Comment by mofanx** [comment]
try this : https://zhuanlan.zhihu.com/p/15554828279  or  https://hairlessvillager.github.io/2024/09/10/a-problem-in-windows-conda-zsh/

It works!
