### ISSUE TITLE
fzf_setup_using_fzf:6: command not found: is-at-least

### ISSUE THREAD

**Issue by sammcj** [ohmyzsh/ohmyzsh#12412]
### Describe the bug

After updating OMZ a week or two ago all my machines have been giving the following error whenever a new terminal session is created:

```
fzf_setup_using_fzf:6: command not found: is-at-least
```

This seems to be coming from the following line: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/fzf/fzf.plugin.zsh#L7

I'm not sure what `is-at-least` is supposed to be (function/program/alias?) but it's not a valid ZSH command.

### Steps to reproduce

1. Install OMZ (I use it with zgen)
2. Enable the fzf plugin (e.g. `zgen oh-my-zsh plugins/fzf`)
3. Start a new terminal session
4. Get error fzf_setup_using_fzf:6: command not found: is-at-least

### Expected behavior

No error?

### OS / Linux distribution

macOS 14.4.1

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Fixed, thanks for the report!

**Comment by sammcj** [comment]
Confirmed, Thanks for the quick fix.
