### ISSUE TITLE
kubectl plugin completions not working for kj, kjx, ky

### ISSUE THREAD

**Issue by JtMotoX** [ohmyzsh/ohmyzsh#12427]
### Describe the bug

The kj, kjx, and ky functions in the kubectl plugin are supposed to have completion but they are not working.

https://github.com/ohmyzsh/ohmyzsh/blob/a779d6563ffb2f0093b4b74c8d5ff0982fa3e930/plugins/kubectl/kubectl.plugin.zsh#L183C1-L192C3

### Steps to reproduce

1. Install jq and/or yh
2. `kubectl get pod ` [tab] = shows list of pods
3. `kj get pod ` [tab] = shows list of files and folders in my cwd
4. `ky get pod ` [tab] = shows strange ascii sequence

```bash
> kubectl get pod [tab]
apiservice-558d4678c8-rp4xx  docs-5d56b46dd5-qcrcn        uiservice-c6c947885-ghv8g

> kj get pod [tab]
CODE_OF_CONDUCT.md  README.md           completions/        log/                templates/                                              
CONTRIBUTING.md     SECURITY.md         custom/             oh-my-zsh.sh        themes/                                                 
LICENSE.txt         cache/              lib/                plugins/            tools/

> ky get pod [tab]
$'\033'\[30\;101m
```

### Expected behavior

```bash
> kubectl get pod [tab]
apiservice-558d4678c8-rp4xx  docs-5d56b46dd5-qcrcn        uiservice-c6c947885-ghv8g

> kj get pod [tab]
apiservice-558d4678c8-rp4xx  docs-5d56b46dd5-qcrcn        uiservice-c6c947885-ghv8g

> ky get pod [tab]
apiservice-558d4678c8-rp4xx  docs-5d56b46dd5-qcrcn        uiservice-c6c947885-ghv8g
```

### OS / Linux distribution

AlmaLinux

### Zsh version

5.8

### Terminal emulator

ssh

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Thanks for the report, it should be working now!

**Comment by JtMotoX** [comment]
Still not working

```bash
> omz version
master (189774c)
~ ------------------------------------------------------------------------------------------------------------------------- a-
> ky get deploy $'\033'\[30\;101m
```

**Comment by glasser** [comment]
I'm seeing this issue as well.

**Comment by JtMotoX** [comment]
> I'm seeing this issue as well.

@glasser Since this issue is closed, I have opened https://github.com/ohmyzsh/ohmyzsh/issues/12562. Would you mind heading over there and giving it a thumbs up if you are still seeing this issue?
