### ISSUE TITLE
Interface Bug

### ISSUE THREAD

**Issue by Shiroxzgod** [ohmyzsh/ohmyzsh#12424]
### Describe the bug

After installing the theme, figlet and directory view is a mess

### Steps to reproduce

I just setting the theme for preference color and install the ohmyzsh theme in my terminal and after that the figlet and directory view is a mess

### Expected behavior

;=;

### Screenshots and recordings

![gg](https://github.com/ohmyzsh/ohmyzsh/assets/58801545/17a5d4a8-1fd6-4732-86da-a24ee6e2b83e)

### OS / Linux distribution

Kali Linux 2022.1

### Zsh version

Lates

### Oh My Zsh version

Lates

### Terminal emulator

QTerminal

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Hi @Shiroxzgod, the issue is that the terminal is using a non-monospaced font. You have to change that in your terminal emulator settings. Oh My Zsh has no control over that.

**Comment by Shiroxzgod** [comment]
> Hi @Shiroxzgod, the issue is that the terminal is using a non-monospaced font. You have to change that in your terminal emulator settings. Oh My Zsh has no control over that.

but I've changed it to monospace to and it doesn't work ;-;
