### ISSUE TITLE
[Plugin] Salt error command not found: python2 when cache autocomplete does not exist

### ISSUE THREAD

**Issue by bahamut45** [ohmyzsh/ohmyzsh#12426]
**Describe the bug**

The following message appears when auto-completion is requested on a salt order `(anon):7: command not found: python2` 

**Steps to reproduce**

For example:

1. Enable plugin salt
2. Launch autocomplete after command salt, salt-call etc
3. See error

**Expected behavior**

No message should appear if this merge request is correctly apply => https://github.com/ohmyzsh/ohmyzsh/pull/10775

**Screenshots and recordings**

![image](https://github.com/ohmyzsh/ohmyzsh/assets/3422019/1b9417de-3b89-45f3-b656-a03e0eba1683)

**OS / Linux distribution**

all

**Zsh version**
all

**Oh My Zsh version**
current

**Terminal emulator**
all

**If using WSL on Windows, which version of WSL**
None

**Additional context**
No specify context.

**Comment by carlosala** [comment]
Hi! It seems like in upstream wasn't updated yet. Could you open the issue there? Thanks!
https://github.com/saltstack/salt/blob/master/pkg/common/salt.zsh
