### ISSUE TITLE
`anaconda` env information is displayed incorrectly after commit 309129f

### ISSUE THREAD

**Issue by antonovmaxim** [ohmyzsh/ohmyzsh#12438]
### Describe the bug

Text signing the current environment:
1) Displays on the line like if I had typed it in
2) Duplicated with the text in brackets at the beginning

(see image) 

![image](https://github.com/ohmyzsh/ohmyzsh/assets/99024963/1fb2f18a-42aa-4307-aa1b-28c3bdbc5102)

The problem occurred after commit 309129f.

### Steps to reproduce

1. Install miniconda3
2. Update oh-my-zsh
3. Execute `conda init zsh`

### Expected behavior

See "before commit 309129f"

### OS / Linux distribution

Arch linux

### Zsh version

5.9

### Oh My Zsh version

master (dfb436b)

### Terminal emulator

Kitty

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Ouch, I didn't know `conda` already displayed a text by itself. Does that always happen?

**Comment by carlosala** [comment]
Reverted, thanks for the report 👍🏻

**Comment by antonovmaxim** [comment]
Yes, my conda always shows itself which environment is active. After `conda init`, it modifies `./zshrc`, and runs the necessary scripts at startup. Anyway, the problem is fixed, thanks for the quick response!
