### ISSUE TITLE
omz update raises "upgrade.sh:186: bad pattern: ^[[31m"

### ISSUE THREAD

**Issue by MarArMar** [ohmyzsh/ohmyzsh#12430]
### Describe the bug

[oh-my-zsh] It's time to update! You can do that by running `omz update`

> omz update

/.oh-my-zsh/tools/upgrade.sh:186: bad pattern: ^[[31m

### Steps to reproduce

> omz update

/.oh-my-zsh/tools/upgrade.sh:186: bad pattern: ^[[31m

### Expected behavior

Works, updates omz

### OS / Linux distribution

TUXEDO OS 2 ; KDE Plasma Version: 5.27.10 ; Kernel Version: 6.5.0-10036-tuxedo (64-bit)

### Zsh version

5.8.1

### Terminal emulator

Konsole

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Looks like this is hitting the `printf` call as if `-m` was passed. Can you run
```sh
/usr/bin/env zsh -xv $ZSH/tools/upgrade.sh
```
to debug and post the logs?

**Comment by mcornella** [comment]
Do you have `command` aliased to `/opt/cursor.appimage`? If so, what is that and why?

**Comment by mcornella** [comment]
OK no, it looks like both `git` and `zsh` direct to `/opt/cursor.appimage` for some reason, you should check why that is.

**Comment by carlosala** [comment]
Make sure you don't have any alias/function/whatever redefining `git` and `zsh` command. Does that happen as well in a regular terminal, not inside cursor? In case it doesn't happen outside of cursor, open an issue to them since it'll for sure be their issue.
Thanks for the report!
