### ISSUE TITLE
Unable to run sh files

### ISSUE THREAD

**Issue by burntcookie90** [ohmyzsh/ohmyzsh#1245]
```
# ./oh-my-zsh.sh                                              [~/.oh-my-zsh]
zsh: can't open input file: /tools/check_for_upgrade.sh
```
Did not work in bash either.

Other .sh files return similar results. Any ideas?

**Comment by vilas777** [comment]
I recently started using ubantu 16.04. i had a same problem. i search everywhere but i was not getting anything to may script. then i tried some commands and i found it works for me.  so sharing this with you peoples.
1.open the terminal
2.apt-get install zsh
3. now run your script.
i hope that it will solve the issue for other users of this OS.

**Comment by xgqfrms** [comment]
# bug

> `.oh-my-zsh/oh-my-zsh.sh:14: command not found: env`

**Comment by mcornella** [comment]
You need to be install zsh, use `chsh -s $(which zsh)` and restart the terminal and maybe also your user session.
