### ISSUE TITLE
Some iconv_open error on running of every command in shell

### ISSUE THREAD

**Issue by niveshm** [ohmyzsh/ohmyzsh#12458]
### Describe the bug

I am getting the following error message after running any command.

```
iconv: iconv_open(, -t): Invalid argument
Error converting string from  to UTF-8
```

Not sure how to solve can you help me out?

### Steps to reproduce

used latest version of omz

### Expected behavior

There should not be any warning displayed

### OS / Linux distribution

macOS 14.5

### Zsh version

5.9

### Oh My Zsh version

master (5e59d21)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Duplicate of #12439
