### ISSUE TITLE
When trying to go back to other commands previously used on the terminal, it won't let me if I'm typing "git commit -m" command

### ISSUE THREAD

**Issue by IsabellaSampaio** [ohmyzsh/ohmyzsh#12453]
### Describe the bug

When typing the git command `git commit -m ""` and then trying to go back to a previous command that I've used on the terminal, it won't let me. 

https://github.com/ohmyzsh/ohmyzsh/assets/71940799/73c99059-225a-4b3c-9b94-223ca9fa77c4

### Steps to reproduce

1. Open zsh with oh-my-zsh working
2. Try to type the following git command -> git commit -m "Any message"
3. On your keyboard, try to use arrow up to go back to the previous commands used

### Expected behavior

When typing the git command `git commit -m ""` I should be able to go back to the previous commands used on the terminal, without facing any "block" from the terminal. Below is the video where I do it without oh-my-zsh sourced. 

https://github.com/ohmyzsh/ohmyzsh/assets/71940799/1e7995d7-8a15-4fa3-b848-88425d46988a

### OS / Linux distribution

Windows 10, WSL2 with Ubuntu 22.04 LTS. Also having this issue in macOS Sonoma 14.5

### Zsh version

5.8.1

### Oh My Zsh version

master (1b29fd3)

### Terminal emulator

Windows Terminal  

### If using WSL on Windows, which version of WSL

WSL2

### Additional context

If the bug above is not a bug and rather a feature and is something I can configure to turn on/off, please let me know :)

**Comment by carlosala** [comment]
That is expected in `oh-my-zsh`. We have a [custom keybinding](https://github.com/ohmyzsh/ohmyzsh/blob/1b29fd3a460e43d4a7581d6a6a7e5a1877a39068/lib/key-bindings.zsh#L38-L58) for it, when you click <kbd>up-arrow</kbd> it only shows the history commands that match what you have written already.

You can add the following snippet after sourcing `oh-my-zsh.sh` to have the default behavior of zsh:
```zsh
bindkey -M emacs "^[[A" up-line-or-history
bindkey -M viins "^[[A" up-line-or-history
bindkey -M vicmd "^[[A" up-line-or-history
if [[ -n "${terminfo[kcuu1]}" ]]; then
  bindkey -M emacs "${terminfo[kcuu1]}" up-line-or-history
  bindkey -M viins "${terminfo[kcuu1]}" up-line-or-history
  bindkey -M vicmd "${terminfo[kcuu1]}" up-line-or-history
fi

bindkey -M emacs "^[[B" down-line-or-history
bindkey -M viins "^[[B" down-line-or-history
bindkey -M vicmd "^[[B" down-line-or-history
if [[ -n "${terminfo[kcud1]}" ]]; then
  bindkey -M emacs "${terminfo[kcud1]}" down-line-or-history
  bindkey -M viins "${terminfo[kcud1]}" down-line-or-history
  bindkey -M vicmd "${terminfo[kcud1]}" down-line-or-history
fi
```

**Comment by IsabellaSampaio** [comment]
Thanks for the answer!!
