### ISSUE TITLE
parse error near `>&' in diagnostics.zsh

### ISSUE THREAD

**Issue by Moulick** [ohmyzsh/ohmyzsh#12457]
### Describe the bug

Loading `oh-my-zsh` is generating error as below

```bash
/Users/moulick.aggarwal/.oh-my-zsh/lib/diagnostics.zsh:134: parse error near `>&'
/Users/moulick.aggarwal/.oh-my-zsh/plugins/macos/music:103: parse error near `>&'
```

### Steps to reproduce

1. Run omz update to get the latest HEAD
2. run `source ~/.zshrc` 
3. See error below

```bash
/Users/moulick.aggarwal/.oh-my-zsh/lib/diagnostics.zsh:134: parse error near `>&'
/Users/moulick.aggarwal/.oh-my-zsh/plugins/macos/music:103: parse error near `>&'
```

### Expected behavior

No error

### OS / Linux distribution

MacOS 14.5 (23F79)

### Zsh version

5.9

### Oh My Zsh version

master (5e59d21e)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Hi! Could you execute `omz_diagnostic_dump` and send it to logs@ohmyz.sh? Let's see what's happening!

**Comment by Moulick** [comment]
> Hi! Could you execute `omz_diagnostic_dump` and send it to [logs@ohmyz.sh](mailto:logs@ohmyz.sh)? Let's see what's happening!

Sent!

**Comment by carlosala** [comment]
Thanks @Moulick! Could you send as well the initialization log? You can see how to get it from [here](https://github.com/ohmyzsh/ohmyzsh/wiki/Troubleshooting#other-problems)
By the way, does that happen as well if you don't `source .zshrc`? `.zshrc` shouldn't be sourced, in case you want to restart the shell `omz reload` or `exec zsh` do the trick

**Comment by Moulick** [comment]
@carlosala Sent! And the email bounced :( Attached again after compression, maybe works now

<img width="300" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/15780903/13ab7950-459b-4027-8c9e-2d44b0ef9818">


Yep, `~/.zshrc` should not be sourced. The issue does not happen while opening a new shell or `omz reload`. But I think doing a `source ~/.zshrc` should also not throw a parse error?

**Comment by mcornella** [comment]
The error happens here https://github.com/ohmyzsh/ohmyzsh/blob/071b8f8921cb2bbb1fcabbf3d271e77af0b12a7d/lib/diagnostics.zsh#L134
at the`-h` part, because you have a global alias named `-h` that expands to
```sh
alias -g -- -h='-h 2>&1 | bat --language=help --style=plain'
```
Only happens on the next `source .zshrc` because before init the alias is not yet defined.

Solution is to name the global alias something else (I have `:L` set to | less`) which you can then tack onto the command:
```sh
alias -g :B='-h 2>&1 | bat --language=help --style=plain'
# use like
git -h :B
```
