### ISSUE TITLE
git async handler not registered when using PROMPT?

### ISSUE THREAD

**Issue by rionda** [ohmyzsh/ohmyzsh#12461]
There is the comment:

https://github.com/ohmyzsh/ohmyzsh/blob/071b8f8921cb2bbb1fcabbf3d271e77af0b12a7d/lib/git.zsh#L56-L57

But then, the code does not check for $PROMPT specifically:

https://github.com/ohmyzsh/ohmyzsh/blob/071b8f8921cb2bbb1fcabbf3d271e77af0b12a7d/lib/git.zsh#L60

https://github.com/ohmyzsh/ohmyzsh/blob/071b8f8921cb2bbb1fcabbf3d271e77af0b12a7d/lib/git.zsh#L66

Should the lists of variables include $PROMPT ?

**Comment by carlosala** [comment]
Hi! `$PROMPT` is linked to `$PS1`. We're indeed checking `$PROMPT`!
