### ISSUE TITLE
When using the mouse, open iterm2 and the percent sign appears

### ISSUE THREAD

**Issue by tonywu-wyx** [ohmyzsh/ohmyzsh#12471]
### Describe the bug

<img width="304" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/141659100/e9e89606-a12b-47d9-8bac-f0ff0ce64b5e">

- When using the Mac default terminal, no problem
- When using iterm2, there is no problem if you do not install “on my zsh”
- The above all use the default configuration of “oh my zsh”

### Steps to reproduce

install iterm2，then install "oh my zsh"，this problem will happen when use mouse then open iterm2 default profile.

### Expected behavior

dont show % with open the frist default profile.

### OS / Linux distribution

macOS 14.5

### Zsh version

5.9

### Terminal emulator

iTerm2 3.5.0

### If using WSL on Windows, which version of WSL

None

### Additional context

no themes, plugins, custom settings...，system is new installed to check the reason of this problem.

**Comment by carlosala** [comment]
The `%s` means that that line does not end with `\n`. It's likely an iterm2 problem if it's working great with other terminal emulators.
