### ISSUE TITLE
Bundler plugin does not offer completions for bundler command

### ISSUE THREAD

**Issue by tastapod** [ohmyzsh/ohmyzsh#12482]
### Describe the bug

omz provides shell completion and aliases for Ruby's `bundle` command using a plugin called [bundler][].

Unfortunately, the plugin only works when the command is used as `bundle` rather than `bundler`, which is at odds with the plugin name, even though one is an alias for the other!

I see several options:
1. Enable completions for both `bundle` and `bundler`.
2. Rename the plugin to `bundle` and have a deprecated copy as `bundler` for a while.
3. Do nothing and live with the (mild) confusion!

I am happy to provide a PR for option 1 using [something like this][compdef], or to rename and deprecate if someone can point me to an example of this.

FWIW I'm not a big Ruby user, just a fan of omz and a bit OCD when it comes to plugins!

[bundler]: ../tree/master/plugins/bundler/bundler.plugin.zsh
[compdef]: https://stackoverflow.com/a/44037208/632259

### Steps to reproduce

1. Install the `bundler` plugin
2. Type `bundler` and hit tab
3. \<crickets\>
4. Delete the `r` so you have `bundle`
5. Hit tab
6. Profit!

### Expected behavior

Completions should work for both `bundler` and `bundle`.

### OS / Linux distribution

Any

### Zsh version

5.8

### Terminal emulator

Terminator, iTerm

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Fixed, thanks for the report!
