### ISSUE TITLE
Missing function in z plugin

### ISSUE THREAD

**Issue by jamnaughty** [ohmyzsh/ohmyzsh#12492]
### Describe the bug

Missing function in z plugin
The plugin z is missing _zshz function

### Steps to reproduce

Try z <tab>

### Expected behavior

z <tab> does not work

### OS / Linux distribution

MacOSx Sonoma

### Zsh version

zsh 5.9 (arm-apple-darwin23.0.0)

### Terminal emulator

Iterm2

### If using WSL on Windows, which version of WSL

None

### Additional context

(eval):1: command not found: _zshz

**Comment by mcornella** [comment]
Hi @jamnaughty, the z plugin uses the zsh version of the old z plugin. The current name of the underlying function is `zshz`, the plugin already sets the alias correctly. If you're using a customization on top of that, make sure to replace `_zshz` with `zshz`.
