### ISSUE TITLE
set - u break the timer plugin

### ISSUE THREAD

**Issue by dsauve-adsk** [ohmyzsh/ohmyzsh#12499]
### Describe the bug

when using the timer plugin, if I run the `set -u` command, 

### Steps to reproduce

1 - Enable plugin timer
2 - Run the command `set -u`
3 - Run the command `sleep 2`

After that, each command will display
`__timer_display_timer_precmd:5: TIMER_THRESHOLD: parameter not set`

### Expected behavior

No `parameter not set `warning
The command execution time to be display

### OS / Linux distribution

Mac 14.5

### Zsh version

5.9

### Oh My Zsh version

master (249c708)

### Terminal emulator

iterm2

### If using WSL on Windows, which version of WSL

None

**Comment by dsauve-adsk** [comment]
Sorry did not realized it was an external plugin... I'll use timer!

**Comment by dsauve-adsk** [comment]
Reopened, got the same issue with the timer plugin...

**Comment by carlosala** [comment]
Hi!
In general, if you `set -u` oh-my-zsh will start crying around (`omz` cli, for example, is not adapted for that).
While fixing it is easy in this instance, I'd rather recommend just avoiding using `set -u` or `setopt no_unset`. It'll then be more sustainable and will avoid other issues.
I'll close this, feel free to comment why you particularly need `set -u`.
Thanks for the report!
