### ISSUE TITLE
git plugin breaks aliases

### ISSUE THREAD

**Issue by Arinerron** [ohmyzsh/ohmyzsh#12513]
### Describe the bug

The `git` plugin seems to be messing with the args when you use an unrelated alias in omz. I don't understand why/how, but see the reproduction steps.

### Steps to reproduce

1. Enable plugin `git`.
2. Run the following commands in an empty directory (to save time)
    ```
    alias a='grep -rF -- '
    a gap
    ```
3. Observe the output error:
    ```
    grep: apply: No such file or directory
    ```

### Expected behavior

I would expect it to internally run:

```
grep -rF -- gap
```

After running `set -x`, I can see the command that it is internally running is in fact:

```
grep '--color=auto' '--exclude-dir=.git' -rF -- git apply
```

It seems like it evaluated the first `gap` arg:

```
$ which gap
gap: aliased to git apply
```

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Oh My Zsh version

31eca46ee3b94ca84a038628e0bf6089a7488908

### Terminal emulator

Kitty

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Hi Aaron, thanks for the report. The behavior you are seeing is a little known feature of zsh: when you define an alias, it is expected that anything that follows the alias name is just a regular argument, i.e.
```sh
alias cat='bat'
alias file='file -b'
cat file # runs `bat file`
```
If the alias you define ends in a space, the argument that follows it is interpreted by zsh as an alias, and also expands it:
```sh
alias cat='bat '
alias file='file -b'
cat file # runs `bat file -b`
```
This is documented in [^1]:
> If the replacement text ends with a space, the next word in the shell input is always eligible for purposes of alias expansion.

and a little bit better in [^2].

[^1]: https://zsh.sourceforge.io/Doc/Release/Shell-Grammar.html#Aliasing:~:text=If%20the%20replacement%20text%20ends%20with%20a%20space%2C%20the%20next%20word%20in%20the%20shell%20input%20is%20always%20eligible%20for%20purposes%20of%20alias%20expansion.

[^2]: https://github.com/rothgar/mastering-zsh/blob/master/docs/helpers/aliases.md#defining-aliases
