### ISSUE TITLE
The Oh My Zsh Read Me Section on Themes can be confusing RE: ps://github.com/ohmyzsh/ohmyzsh?tab=readme-ov-file#using-oh-my-zsh

### ISSUE THREAD

**Issue by OldSubSailor** [ohmyzsh/ohmyzsh#12510]
### If the feature request is for a plugin or theme, specify it here.

Changing to the agnoster theme is insufficiently referenced 

### If the feature solves a problem you have, specify it here.

I am speaking from Mac experience. There is a note that speaks to installing fonts and that is all. Opening a new terminal window will result in a prompt that is almost impossible to read in the blue area, and indeed, your example of the agnoster theme shows this.  If you go to the agnoster GitHub page: https://github.com/agnoster/agnoster-zsh-theme, you will see that the README opening section speaks to more, as does the Compatibility section.

Further if you read the agnoster.zsh-theme file you will find a detailed README section in it that specifies what the users need to do in order to make the them readable. 

### Describe the proposed feature.

I proprose two options:
1. Replace the agnoster theme with a more user friendly prompt.
2. Edit the section on Themes before the agnoster theme to provide further warning regarding what else is needed and a link to the agnoster GitHub page

### Describe alternatives you've considered

Include this README intro before the agnoster theme. NOTICE that agnoster was designed for people who _already_ have set up their terminals in a specific manner. 

### agnoster.zsh-theme

A ZSH theme optimized for people who use:

Solarized
Git
Unicode-compatible fonts and terminals (I use iTerm2 + Menlo)
For Mac users, I highly recommend iTerm 2 + Solarized Dark

### Additional context
Screenshot not set-up as per instructions
<img width="1695" alt="notsetupatall" src="https://github.com/ohmyzsh/ohmyzsh/assets/54075170/080324d4-fd60-4e85-bc44-83090654d361">

Screenshot set-up as per instructions 
<img width="1508" alt="asperinstructions" src="https://github.com/ohmyzsh/ohmyzsh/assets/54075170/520ee00e-34a2-4c35-8277-eabf2a61bd0e">

**Comment by mcornella** [comment]
Hi @OldSubSailor, I genuinely appreciate you taking the time to share your feedback, that is rare in these cases.

Let me share how we've worked to make these requirements more visible, and do let me know if you'd add something else:

- First, on the README section, where we showcase the `agnoster` theme, we added a **NOTE** below that explains to install Powerline or Nerd Fonts: https://github.com/ohmyzsh/ohmyzsh/blob/27ca0c915b4a6b29282502b2b36c7ffb4c56e32b/README.md?plain=1#L170
- This is also explained in the Themes wiki under the agnoster section, as it is a specific requirement for the agnoster theme: https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#agnoster.
- Finally, we also have a FAQ section devoted to this issue: https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-have-a-weird-character-in-my-prompt

I do agree that having a theme README would be an improvement over the docs we do have, although at the current state of the project this is more of a nice to have, as we have a lot of users and only 2 people working on it.

Please let me know if you'd like to change anything else.

**Comment by mcornella** [comment]
Documented this further in https://github.com/ohmyzsh/ohmyzsh#themes. Adding support for theme READMEs might be worth it or not, depending on how we eventually refactor themes. It is though something we'll consider.

![image](https://github.com/user-attachments/assets/76c9fe3c-13f2-4da0-b55a-2dfb75ebe971)
