### ISSUE TITLE
`previous_branch` similar to `current_branch`

### ISSUE THREAD

**Issue by aboqasem** [ohmyzsh/ohmyzsh#12538]
### If the feature request is for a plugin or theme, specify it here.

Git Plugin

### If the feature solves a problem you have, specify it here.

I regularly use `$(current_branch)`, sometimes to rename the branch or compare it to its remote origin.

`git switch` supports `-` to go to the previous branch. I wonder if we can add `previous_branch` so that we can use it with other commands.

### Describe the proposed feature.

`previous_branch`/`git_previous_branch` would get the previous branch / checked out commit.

**Comment by carlosala** [comment]
Done, thanks for the idea!
