### ISSUE TITLE
eval "$(fzf --zsh)" is failing

### ISSUE THREAD

**Issue by DataShalam** [ohmyzsh/ohmyzsh#12531]
### Describe the bug

For Shell Integrations I added this two line in my .zshrc if I remove first line, it doesn't give me given error in the screenshots

eval "$(fzf --zsh)"
eval "$(zoxide init --cmd cd zsh)"

### Steps to reproduce

Just Open Terminal

### Expected behavior

It should execute thouroughly

### Screenshots and recordings

![Screenshot from 2024-06-30 15-52-55](https://github.com/ohmyzsh/ohmyzsh/assets/124355970/6ebaa316-f4a8-427f-b0f8-437a035b1c91)

![Screenshot from 2024-06-30 15-49-38](https://github.com/ohmyzsh/ohmyzsh/assets/124355970/61e68c1c-0974-4f4d-8c75-1ac883e35f1a)

### OS / Linux distribution

Fedora 40

### Zsh version

zsh 5.9 (x86_64-redhat-linux-gnu)

### Terminal emulator

Gnome Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by DataShalam** [comment]
fzf --version
0.44.1 (Fedora)

**Comment by carlosala** [comment]
It shouldn't be hitting that. Could you share the output of `setopt`? Thanks!

**Comment by mcornella** [comment]
`fzf --zsh` was only added in 0.48.0 [^1], you should update `fzf` to the latest version.

[^1]: https://github.com/junegunn/fzf/releases/tag/0.48.0
