### ISSUE TITLE
[kubectl] Add shortcut for PersistentVolume

### ISSUE THREAD

**Issue by za** [ohmyzsh/ohmyzsh#12544]
### If the feature request is for a plugin or theme, specify it here.

kubectl

### Describe the proposed feature.

Add alias for getting `PersistentVolume`

### Describe alternatives you've considered

Refer to: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/kubectl/kubectl.plugin.zsh#L151

```
alias kgpv='kubectl get pv'
```

**Comment by za** [comment]
If this issue is accepted, I can prepare a PR for this.

**Comment by carlosala** [comment]
We're trying to keep small the number of aliases that we add to plugins. Since we didn't have others asking for the same, I'd say this alias could easily live in your `zshrc`. `kubectl` already has a big number of aliases.
Thanks for the idea!

**Comment by za** [comment]
Noted @carlosala 📝 Thanks!
