### ISSUE TITLE
"$ZSH_CACHE_DIR/completions" is always added to fpath

### ISSUE THREAD

**Issue by flash-me** [ohmyzsh/ohmyzsh#12551]
It's about this line: 
https://github.com/ohmyzsh/ohmyzsh/blob/fa583cfb87b80e3f7d7577c8b62b7d1385c01337/oh-my-zsh.sh#L68

`(( ${fpath[(Ie)"$ZSH_CACHE_DIR/completions"]} ))` will always evaluate to 0, even if `$ZSH_CACHE_DIR/completions` is already in `fpath`, **because of the quotes**.

Reproduction:
![Screenshot from 2024-07-12 18-37-24](https://github.com/user-attachments/assets/0d56566c-e2d8-4953-b16f-387fd2e4f3de)

**Comment by mcornella** [comment]
Thanks Adam! That was an oversight, it's now fixed in 0b27b15d0b08645bd995e13b8d69fcbe2ef7e8eb. I hope you don't mind I took the liberty of adding you as co-author. Cheers!

**Comment by flash-me** [comment]
Huh, that was fix. 

All fine, appreciate it! :) 

Best regards
A ⚡
