### ISSUE TITLE
docker-compose plugin selects wrong binary

### ISSUE THREAD

**Issue by den-is** [ohmyzsh/ohmyzsh#12553]
### Describe the bug

Running latest omz
Updated omz to latest using `omz update`
Running latest Docker Desktop on MacOS
But still getting:
```
❯ dcps
zsh: command not found: docker-compose


❯ docker-compose
zsh: command not found: docker-compose
❯ which docker-compose
docker-compose not found
```

It looks like this plugin line is not selecting correct binary
https://github.com/ohmyzsh/ohmyzsh/blob/fd8f72b27614d48ec06421fb80aff2eb10674a69/plugins/docker-compose/docker-compose.plugin.zsh#L2

### Steps to reproduce

- Run the lastest Docker Desktop version 4.32.0 (157355)
- Run the latest OMZ
- Enable docker-compose plugin
- Try to run provided docker-compose aliases
- Aliases would fail
- Edit `~/.oh-my-zsh/plugins/docker-compose/docker-compose.plugin.zsh` and set `dccmd='docker compose'` - This will fix the issue

### Expected behavior

Working docker-compose aliases

### OS / Linux distribution

MacOS Sonoma 14.5

### Zsh version

5.9

### Oh My Zsh version

master (fd8f72b2)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Can you post the output of the commands below?
```sh
which -a docker-compose
echo ${commands[docker-compose]}
```

**Comment by skalinets** [comment]
> Can you post the output of the commands below?

I have the same error. The output is 
```
/usr/local/bin/docker-compose
/usr/local/bin/docker-compose
```

**Comment by skalinets** [comment]
I remembered that I started docker desktop in the middle of this (after applying the fix from bug description), and it said something like "seems like the installation was changed by other program, lets fix it". So my guess is that docker fixed alias to `docker-compose` and everything is ok now. 

So fixing / reinstalling docker desktop might be a fix.

**Comment by mcornella** [comment]
If there is a command in path that is named `docker-compose`, that will be used first, as we understand that you probably still have the old one installed. The way to fix this would be to uninstall the `docker-compose` command.

I have no idea why zsh says command not found, I guess that it is actually a symlink to something that doesn't exist. Can you confirm with this?
```sh
ls -l /usr/local/bin/docker-compose
strace /usr/local/bin/docker-compose
```

**Comment by den-is** [comment]
Restarts and reinstalls did not work.
Why docker had to fix the docker-compose symlink and not to just deprecate it and move forward with `docker compose` plugin.

IMHO. omz docker-plugin requires a more robust check eliminating false positives.
And probably `docker compose` checked as a first option.

Indeed, I missed this trivial step:
```
❯ ls -l /usr/local/bin/docker-compose
lrwxr-xr-x - root admin 29 Nov  2022 /usr/local/bin/docker-compose -> /Applications/Docker.app/Contents/Resources/bin/docker-compose
```
Symlink pointing to a file which does not exist anymore.
Removing the symlink made the existing omz plugin logic work.

**Comment by skalinets** [comment]
in my case it is 
```
❯ ls -l /usr/local/bin/docker-compose
lrwxr-xr-x 1 root wheel 70 Jul 14 20:36 /usr/local/bin/docker-compose -> /Applications/Docker.app/Contents/Resources/cli-plugins/docker-compose
```
and it does exist ) Seems like some kind of docker desktop dark magic

**Comment by den-is** [comment]
Yea, my file was created in 2022, while your's just yesterday.
I have not done a complete reinstall yesterday, and not going to now, but have done complete reinstalls since 2022 several times for sure. (IIRC this year too).

Are you using brew to install/update Docker-Desktop? My is a manual install, and updates are done by Docker Desktop itself.

Thankfully it is not that "dark" to remain unfixable and that fragile :)))
Also, IMHO I don't need this symlink for `docker-compose` and prefer to finally cut bonds with it (the king is dead, long live the king) :)

**Comment by lazarust** [comment]
From the [Docker release notes](https://docs.docker.com/desktop/release-notes/#4320) creating the following symlink is a workaround:
> sudo ln -sf /Applications/Docker.app/Contents/Resources/cli-plugins/docker-compose /usr/local/bin/docker-compose

**Comment by den-is** [comment]
Yea cool. PR submitted.

**Comment by mcornella** [comment]
Ah, beat me to it. Merging in a minute.

**Comment by mcornella** [comment]
Thanks for the tests guys!
