### ISSUE TITLE
pass plugin doesn't work anymore with any FZF_COMPLETION_TRIGGER

### ISSUE THREAD

**Issue by michaeltraxler** [ohmyzsh/ohmyzsh#12564]
### Describe the bug

With an older version of oh-my-zsh I could see all my password-files with 
`pass **<tab><tab>` in fzf.
Now `pass **` shows in fzf all files recursively (by the way not like the `"**"` in zsh, which shows only the files in the current directory) .

### Steps to reproduce

New account:
```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
gpg --generate-key
pass init< username>
pass **<tab><tab>
```
will show the files in the current directory, instead of the files in .password-store

### Expected behavior

`pass **<tab><tab>`
will show the files in .password-store, instead of the current directory. 

### OS / Linux distribution

OpenSuSE Tumbleweed

### Zsh version

5.9

### Oh My Zsh version

master

### Terminal emulator

kitty

### If using WSL on Windows, which version of WSL

None

### Additional context

Might be unrelated:

This happened around the same time, this bug in fzf appeared (and is solved now):
https://github.com/junegunn/fzf/issues/3890

**Comment by carlosala** [comment]
Hi! We didn't change recently `fzf` plugin, and we source the completion file that comes bundled with `fzf`. This issue should probably go to https://github.com/junegunn/fzf.
Thanks!
