### ISSUE TITLE
After pressing Enter, an extra character "\" is produced. 

### ISSUE THREAD

**Issue by gaoming714** [ohmyzsh/ohmyzsh#12570]
### Describe the bug

After pressing Enter, an extra character "\" is produced.
on tabby or hyper, it shows.
on msys64 it doesn't show.

![image](https://github.com/user-attachments/assets/d019f4e6-cdc5-471f-b0ea-6abd3cf055cb)

### Steps to reproduce

on terminal tabby press "Enter"

### Expected behavior

as desc

### OS / Linux distribution

windows10 

### Zsh version

latest

### Terminal emulator

Tabby

### If using WSL on Windows, which version of WSL

None

### Additional context

as desc

**Comment by mcornella** [comment]
Maybe you're having an incompatible `$TERM` value, I believe it should be like `xterm*` or something like that. Perhaps in msys the keyboard sequence sent gets interpreted correctly, but in Hyper or Tabby it doesn't expect it.

You can check with `echo $TERM` the value you have set, and try this Hyper or Tabby for example
```sh
export TERM=xterm-256color
```

**Comment by gaoming714** [comment]
> ```shell
> TERM=xterm-256color
> ```

it only happens on win10, fixed on win11. 
It looks like something about platform changes.
