### ISSUE TITLE
Case-insensitive `cd` into directory should still show case-sensitive directory name

### ISSUE THREAD

**Issue by kamurani** [ohmyzsh/ohmyzsh#12586]
### Describe the bug

When navigating into a directory, one can conveniently type the directory's name case-insensitively.  

e.g. 

```zsh 
➜  ~ mkdir MyDir
➜  ~ cd mydir
➜  mydir pwd
/Users/me/mydir
```
However, the name of the directory is subsequently formatted in whichever way the user initially typed the `cd` command.  

### Steps to reproduce

As above 

### Expected behavior

Not sure if this is expected behaviour or not.  I think that the way in which a user types the directory name to conveniently navigate, should be uncoupled from how that directory is listed, either using `pwd` or displayed in the prompt.  I think this would remove ambiguity about which directory a user is currently in.  

For example: 
```zsh 
➜  ~ mkdir MyDir
➜  ~ cd mydir
➜  MyDir pwd
/Users/me/MyDir
```

### OS / Linux distribution

MacOS 14.5 (23F79)

### Zsh version

5.9

### Oh My Zsh version

master (67581c5)

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
That's probably caused by macOS having a case insensitive filesystem. I don't know if from the Oh My Zsh side we can do anything.

**Comment by mcornella** [comment]
Indeed this is a macOS issue that can't be avoided, see https://stackoverflow.com/q/68256020.
