### ISSUE TITLE
local configuration (~/.zshrc.local) not recognized/loaded 

### ISSUE THREAD

**Issue by peterlvno** [ohmyzsh/ohmyzsh#12588]
### Describe the bug

Oh My Zsh doesn't recognize/load local configuration in `~/.zshrc.local` on a fresh Manjaro GNOME installlation (which uses zsh by default).

Note:
This differs from my experience on macOS, where `~/.zshrc.local` is loaded by default without modifying the `~/.zshrc` file.

### Steps to reproduce

1. Install omz using the curl command:
`sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`
2. create a `.zshrc.local` file on home (`~`) directory:
`echo 'echo "importing .zshrc.local"' > ~/.zshrc.local`
3. Open terminal

### Expected behavior

The `~/.zshrc.local` file should be loaded by default without any changes to the original `~/.zshrc` file

### Screenshots and recordings

- Terminal recording [here](https://asciinema.org/a/rcWDpaJ5YffNPzieidFMb24KU)
- omz-debug file [here](https://gist.github.com/peterlvno/ea52d90e5936db98b0b6025eb84c33ee.js)

### OS / Linux distribution

Manjaro Gnome 24.0.5  (240730)

### Zsh version

5.9

### Oh My Zsh version

master (d525e80)

### Terminal emulator

GNOME Terminal (3.52.2), Alacritty 0.13.2 (bb8ea18e)

### If using WSL on Windows, which version of WSL

None

**Comment by rwmitchell** [comment]
According to phind.com, this is not true:

`phind does zsh load .zshrc.local`

`The .zshrc.local file is not inherently recognized or loaded by Zsh itself. This means that Zsh does not automatically execute commands or configurations placed in a .zshrc.local file upon startup. `

It also did not load on my macOS system when tested.

**Comment by rwmitchell** [comment]
I've been there so many times myself.
