### ISSUE TITLE
Homebrew cleanup message appearing after every command

### ISSUE THREAD

**Issue by p-fernandez** [ohmyzsh/ohmyzsh#12582]
### Describe the bug

After updating to the latest Oh My Zsh version, every time I execute a command in the terminal it gets printed:
```shell
Usage: brew cleanup [options] [formula|cask ...]                                                                                                                                                                                                     

Remove stale lock files and outdated downloads for all formulae and casks, and
remove old versions of installed formulae. If arguments are specified, only do
this for the given formulae and casks. Removes all downloads more than 120 days
old. This can be adjusted with HOMEBREW_CLEANUP_MAX_AGE_DAYS.

      --prune                      Remove all cache files older than specified
                                   days. If you want to remove everything, use
                                   --prune=all.
  -n, --dry-run                    Show what would be removed, but do not
                                   actually remove anything.
  -s, --scrub                      Scrub the cache, including downloads for even
                                   the latest versions. Note that downloads for
                                   any installed formulae or casks will still
                                   not be deleted. If you want to delete those
                                   too: rm -rf "$(brew --cache)"
      --prune-prefix               Only prune the symlinks and directories from
                                   the prefix and remove no other files.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.
Error: invalid option: -l
```

I can validate this only happens to me when Oh My Zsh is enabled. When I disable it by commenting out the line in `~/.zsrhc`:
```shell
#source $ZSH/oh-my-zsh.sh
```
I do not get the error anymore.

Seems other people are having the same problem but they are pointing out to Brew (mistakenly, in my opinion): https://github.com/Homebrew/brew/issues/17869

### Steps to reproduce

1. Open Terminal.app
2. Run any command, for example `ls -al`.
3. After its output the following command execution will be printed:
```
Usage: brew cleanup [options] [formula|cask ...]                                

Remove stale lock files and outdated downloads for all formulae and casks, and
remove old versions of installed formulae. If arguments are specified, only do
this for the given formulae and casks. Removes all downloads more than 120 days
old. This can be adjusted with HOMEBREW_CLEANUP_MAX_AGE_DAYS.

      --prune                      Remove all cache files older than specified
                                   days. If you want to remove everything, use
                                   --prune=all.
  -n, --dry-run                    Show what would be removed, but do not
                                   actually remove anything.
  -s, --scrub                      Scrub the cache, including downloads for even
                                   the latest versions. Note that downloads for
                                   any installed formulae or casks will still
                                   not be deleted. If you want to delete those
                                   too: rm -rf "$(brew --cache)"
      --prune-prefix               Only prune the symlinks and directories from
                                   the prefix and remove no other files.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.
Error: invalid option: -l
```

### Expected behavior

 No extra traces from brew commands should be executed when running different commands in the terminal.

### OS / Linux distribution

OS 14.5 - 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64

### Zsh version

5.9

### Oh My Zsh version

master (f70e691)

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Introduced `bc` alias is at fault: https://github.com/ohmyzsh/ohmyzsh/blob/f70e6916a1c9aca77e7bd1b976a3f6100752f0a5/plugins/brew/brew.plugin.zsh#L38

Need to change it to something else.

**Comment by tgaeta** [comment]
@mcornella 
> Seems other people are having the same problem but they are pointing out to Brew (mistakenly, in my opinion)

Nobody asked your opinion. And `brew update-reset` fixed my issue, so Brew was the problem.

**Comment by mcornella** [comment]
@tgaeta 

1. I don't know what you're talking about, I never said anything of that sort.

2. Your issue is entirely different from what was reported here, I should know, I fixed it.

3. I think you're just trolling, so enjoy the ban and learn some manners.

**Comment by mcornella** [comment]
Regarding the last comments, all has been cleared up offline and the ban has been removed.

As for the technical reason behind the error, it was caused by alias `bc` shadowing command `bc` which is frequently used to make arithmetic calculations. It's usually called with `bc -l` to load math functions. The issue probably appeared because of a `precmd` function running this command, and hitting the alias instead. 

@tgaeta if you hadn't updated OMZ and fixed it with `brew update-reset` then that's probably a separate issue, although it is very coincidental with the release of the "bc" alias.
