### ISSUE TITLE
[poetry-env] environment is not activated at shell start up

### ISSUE THREAD

**Issue by tim-hilde** [ohmyzsh/ohmyzsh#12589]
### Describe the bug

When starting a new shell inside a poetry project folder, the environment is not activated. The command `source "${venv_dir}/bin/activate"` is run, but somehow to no effect. Calling it manually activates the env.

### Steps to reproduce

1. Enable plugin `poetry-env`
2. Start a new shell inside a poetry project folder
3. Use `which python` to see which python version is being used
4. Realize that its not the one from the poetry project
5. Manually activate via `source $(poetry env info --path)/bin/activate`
6. `which python` shows correct path

### Expected behavior

Poetry env should be activated

### Screenshots and recordings

<img width="432" alt="image" src="https://github.com/user-attachments/assets/db1f7a94-62c1-4d5c-9157-75f3344e77df">

### OS / Linux distribution

macOS 14.5 

### Zsh version

5.9

### Terminal emulator

iTerm2, Vscode

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Which other plugins are you loading?

**Comment by tim-hilde** [comment]
```
plugins=(
    common-aliases
    copypath
    direnv
    dirhistory
    git
    gitfast
    history-substring-search
    jsontools
    last-working-dir
    poetry
    poetry-env
    pyenv
    python
    ssh-agent
    you-should-use
    virtualenv
    zsh-bat
    zsh-syntax-highlighting
)
```

**Comment by tim-hilde** [comment]
oh yes, that solves it. Is there a way to have both plugins enables?

**Comment by carlosala** [comment]
I'll look at it. Thanks for the report!

**Comment by tim-hilde** [comment]
Yes, it works now! Thank you!
