### ISSUE TITLE
Deno completions not working in VSCode

### ISSUE THREAD

**Issue by devsheva** [ohmyzsh/ohmyzsh#12581]
### Describe the bug

I correctly installed deno plugin in `.zshrc` file with antigen, but it doesn't load completions within VSCode.

### Steps to reproduce

1. Enable deno plugin
2. Try completions on VSCode

### Expected behavior

It should load completions as it does in Warp.

### Screenshots and recordings

<img width="567" alt="Screenshot 2024-07-27 at 14 01 26" src="https://github.com/user-attachments/assets/91bcd7af-8415-428b-a0a5-8d90222b6389">

### OS / Linux distribution

macOS Sonoma 14.5

### Zsh version

5.9

### Terminal emulator

Warp

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
This is probably related to this https://github.com/ohmyzsh/ohmyzsh/issues/10581#issuecomment-1129784542

i.e. that antigen does not run the init script from Oh My Zsh, so it's probable that `$ZSH_CACHE_DIR` does not exist or is undefined, and/or that `$ZSH_CACHE_DIR/completions` is not created.

Try
```zsh
echo $ZSH_CACHE_DIR 
```

It should return something like `/path/to/oh-my-zsh-folder/cache` or `$HOME/.cache/oh-my-zsh`.  
If not, set `ZSH_CACHE_DIR="$HOME/.cache/oh-my-zsh"` in your .zshrc file, before antigen loads stuff.

Then, also check
```zsh
ls -l "$ZSH_CACHE_DIR"
ls -l "$ZSH_CACHE_DIR/completions"
```

If this doesn't exist, run `mkdir -p $ZSH_CACHE_DIR/completions`.

After that everything should work again.

**Comment by mcornella** [comment]
Documented in the FAQ https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#completions-are-not-loaded-when-using-a-plugin-manager and opened https://github.com/ohmyzsh/ohmyzsh/issues/12583 to fix this common issue.

**Comment by devsheva** [comment]
I have all set though. 

```
❯ echo $ZSH_CACHE_DIR
/Users/mateo/.antigen/bundles/robbyrussell/oh-my-zsh/cache/
```

```
 ls -l "$ZSH_CACHE_DIR"
ls -l "$ZSH_CACHE_DIR/completions"
total 8
drwxr-xr-x  3 mateo  staff   96 Jul  8 22:56 completions
-rw-r--r--  1 mateo  staff  251 Jul 27 00:49 grep-alias
total 208
-rw-r--r--@ 1 mateo  staff  103458 Jul 27 13:58 _deno

```

**Comment by mcornella** [comment]
OK, then it must be a `$PATH` issue: `deno` needs to be in `$PATH` when the deno plugin is loaded, try adding checks [1] before and after plugin is loaded to confirm.

[1]  
```sh
which -a deno
```

**Comment by devsheva** [comment]
This is the output of 

`source ~/.zshrc`

```

Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems zsh-users/zsh-syntax-highlighting is already installed!
Seems zsh-users/zsh-autosuggestions is already installed!
Seems zsh-users/zsh-completions is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
/Users/mateo/.asdf/shims/deno
Seems robbyrussell/oh-my-zsh is already installed!
/Users/mateo/.asdf/shims/deno
```


This is my `.zshrc` config

```
source $HOME/antigen.zsh
    
# Load the oh-my-zsh's library
antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
    # Bundles from the default repo (robbyrussell's oh-my-zsh)
    git

    # Syntax highlighting bundle.
    zsh-users/zsh-syntax-highlighting

    # Fish-like auto suggestions
    zsh-users/zsh-autosuggestions

    # Extra zsh completions
    zsh-users/zsh-completions

    # Enable asdf
    asdf

EOBUNDLES

# Load the theme
antigen theme robbyrussell

which -a deno
antigen bundle deno

antigen apply

alias dev="cd ~/develop"

which -a deno
eval "$(starship init zsh)"

```

**Comment by mcornella** [comment]
OK, is `$ZSH_CACHE_DIR/completions` in `$fpath`?

**Comment by devsheva** [comment]
seems not, if this is the right way to check it

```
❯ echo $fpath | grep $ZSH_CACHE_DIR/completions

hn-telegram-bot on  feature/analyze-articles [!] via 🦕 v1.45.4 
❯ echo $fpath                                  
/usr/local/share/zsh/site-functions /usr/share/zsh/site-functions /usr/share/zsh/5.9/functions /Users/mateo/.antigen/bundles/robbyrussell/oh-my-zsh/lib /Users/mateo/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git /Users/mateo/.antigen/bundles/zsh-users/zsh-syntax-highlighting /Users/mateo/.antigen/bundles/zsh-users/zsh-autosuggestions /Users/mateo/.antigen/bundles/zsh-users/zsh-completions /Users/mateo/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/asdf /Users/mateo/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/deno /Users/mateo/.antigen/bundles/zsh-users/zsh-completions/src /Users/mateo/.asdf/completions

```

**Comment by devsheva** [comment]
the strange thing is that aliases are working, so at least the plugin script is executed

**Comment by mcornella** [comment]
OK that explains it, so you also need to add it to `$fpath`, I'm going to update the instructions.

Full setup in .zshrc would be this:
```sh
# put this before Oh My Zsh or its plugins are loaded
ZSH_CACHE_DIR="$HOME/.cache/oh-my-zsh"
mkdir -p "$ZSH_CACHE_DIR/completions"
fpath=("$ZSH_CACHE_DIR/completions" $fpath)
```

**Comment by devsheva** [comment]
this worked out, but shouldn't it be done by the plugin itself?

**Comment by mcornella** [comment]
The idea in #12853 is to make it easier for plugin managers to run the requirements for Oh My Zsh plugins.

There are quite a few of those for OMZ plugins and it wouldn't be clean to include it for all the plugins that need it.
