### ISSUE TITLE
Can't install OMZ in an IPv6 only environment using install.ohmyz.sh

### ISSUE THREAD

**Issue by litetex** [ohmyzsh/ohmyzsh#12609]
### Describe the bug

I just tried to install OMZ on an IPv6 only system using ``install.ohmyz.sh``...
and it fails because [the domain has no IPv6 support](https://toolbox.googleapps.com/apps/dig/#AAAA/)

So could you please enable IPv6 on the ``install.ohmyz.sh`` domain?

### Steps to reproduce

Try to install OMZ on an IPv6 only system from ``install.ohmyz.sh``

### Expected behavior

Install via IPv6 is supported

**Comment by litetex** [comment]
Further problem:
The install script also clones from github - which has no IPv6 support. 
Is there an alternative offically hosted repo somewhere that has IPv6 support and where one can clone from?

**Comment by carlosala** [comment]
Hi! We use Vercel as provider and [they don't support (yet) IPv6](https://vercel.com/docs/projects/domains/troubleshooting#ipv6-support). We hope this will change soon, but for now, we are not looking forward to changing providers.
Thanks for the idea!

**Comment by mcornella** [comment]
It wouldn't matter either, since GitHub does not yet support IPv6, although [it seems it's coming](https://www.reddit.com/r/ipv6/comments/1ajb7a5/github_is_working_on_ipv6_support/).

In the meantime you can download the zip file of the repo and upload it manually, but you won't get auto-updates.

**Comment by litetex** [comment]
I resolved my problems for now by [mirroring](https://codeberg.org/Recommendations/Mirror_to_Codeberg) the repo to [codeberg](https://codeberg.org/litetex/ohmyzsh).

Maybe you could create an official mirror there (or another Git Hosting service with IPv6 support) - so that not everyone has to create and update their own one...
