### ISSUE TITLE
Aliases for Python's Ruff Linter/Formatter

### ISSUE THREAD

**Issue by eoBattisti** [ohmyzsh/ohmyzsh#12604]
### If the feature request is for a plugin or theme, specify it here.

Ruff plugin

### If the feature solves a problem you have, specify it here.

I'm now more inclined to use more oh my zsh aliases than to write my own, searching through the plugin list I found quite a few aliases for [pylint](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/pylint) and [PEP8](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/pep8), but I did not see a plugin for [Ruff](https://docs.astral.sh/ruff/), a tool that I'm been using more in the last few days.

### Describe the proposed feature.

So to enrich the Python's plugin environment would it be possible to add this alias plugin?

### Describe alternatives you've considered

I've been thinking about writing this plugin and sending it out as a PR. But I do not know if there are more people who would like to have this new feature on oh my zsh.

So aliases that I'm considering are:
| alias  |  command | description |
|---|---|---|
|`rc`|`ruff check`| Lint all files in the current directory |
|`rcf`|`ruff check --fix`| Lint all files in the current directory, and fix any fixable errors |
|`rcw`|`ruff check --watch`| Lint all files in the current directory, and re-lint on change |
|`rf`|`ruff format`| Format all files in the current directory |

The is a much more cli flags that should be supported as we can see it [here](https://docs.astral.sh/ruff/configuration/#full-command-line-interface)

NOTE: I did not searched to the plugins list if the `r` or `rc*` aliases interfere with others plugins. This is just a recommendation of what would be nice to have.

### Additional context

I've not found any PR related to this topic.

### Related Issues

I've not found any Issue related to this topic.

**Comment by carlosala** [comment]
Hi Nicolas! While I find your proposition interesting, I would say the most common use case of a linter/formatter is to have it embedded in your development workflow, i.e. by running it on save in your editor, on CI in a repo, pre-commit hooks, etc.
Some users might still want to run it manually, but the flags and arguments for running the tool might differ significantly from user to user (e.g. run it on all files or only in the `src` directory).
Thanks for the idea, but I'm leaning towards not accepting this one.
Have a nice day!
