### ISSUE TITLE
Automatically fetch when cd'ing into a git repo

### ISSUE THREAD

**Issue by inspectorG4dget** [ohmyzsh/ohmyzsh#12600]
### If the feature request is for a plugin or theme, specify it here.

Git plugin

### If the feature solves a problem you have, specify it here.

I work on a ton of git repos. Sometimes my repos are out of sync with the remote. But I don't know this until I try to push. It would be super helpful if -- like the dotenv plugin -- the git plugin would fetch whenever I enter a directory that's also a git repo

### Describe the proposed feature.

`~/workspace/project/` is a git repository. So when I `cd` into `~/workspace/project/`, `git fetch` is automatically executed

### Describe alternatives you've considered

Echo a reminder to myself... but I can't trust myself to read that

**Comment by mcornella** [comment]
You are looking for the [git-auto-fetch plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git-auto-fetch) which does this.
