### ISSUE TITLE
Add PNPM plugin aliases and completions

### ISSUE THREAD

**Issue by thesobercoder** [ohmyzsh/ohmyzsh#12616]
### If the feature solves a problem you have, specify it here.

Currently, OMZ doesn't have an official plugin for PNPM which is a very popular package manager for Node. This is a petition to the maintainers to include PNPM as an official plugin.

### Describe the proposed feature.

Add a new plugin to enable aliases and completions for PNPM.

### Describe alternatives you've considered

Current workaround is to use a third party plugin like [omz-plugin-pnpm](https://github.com/ntnyq/omz-plugin-pnpm), but one could argue that if NPM/Bun/Deno has thier place in the official plugin list, then PNPM should also be included.

**Comment by carlosala** [comment]
Hi! If it has already its own repo it would be a great fit for our [External Plugins registry](https://github.com/ohmyzsh/wiki/blob/main/External-plugins.md)! Feel free to open a PR there.
Thanks for the idea!

**Comment by thesobercoder** [comment]
But I don't understand if NPM/Bun/Deno have official plugins, why not PNPM? Just curious.
