### ISSUE TITLE
Theme file changes after save

### ISSUE THREAD

**Issue by WillHonnold** [ohmyzsh/ohmyzsh#12613]
### zsh-theme odd behavior

Hello. Installed today to customize my terminal. whenever I change a .zsh-theme file and link it in .zshrc it changes again in an odder manner. Tried mainly to change %c% to %~% to show full filepath and change the color from cyan, but as mentioned earlier the changes I make don't save properly or something, and leads to weird behavior. Check the screenshots

### Steps to reproduce

1. Install
2. Change .zsh-theme file and link in .zshrc

### Expected behavior

.zsh-theme files should not change after I manually save them, but they are, leading to weird behavior.

### Screenshots and recordings

<img width="455" alt="image" src="https://github.com/user-attachments/assets/05016ee9-2afc-4d4e-b457-7362a5d55446">

Notice how the terminal color changes as well as the text before the filpath.

### OS / Linux distribution

MacOS Ventura 13.6.3

### Zsh version

5.9

### Oh My Zsh version

today

### Terminal emulator

Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by WillHonnold** [comment]
If I use vim it works fine. I have no idea why nano causes this.

**Comment by mcornella** [comment]
This is not an issue with Oh My Zsh, but with your custom theme. Make sure to edit the PROMPT variable so that color variables are properly applied and removed from the variable at the end.
