### ISSUE TITLE
`bubc` command is removed without any warning 

### ISSUE THREAD

**Issue by Zheaoli** [ohmyzsh/ohmyzsh#12611]
### Describe the bug

`bubc` is removed in https://github.com/ohmyzsh/ohmyzsh/commit/51d71e650c369a5c3805a629c1efd314b5628921 without any warning 

### Steps to reproduce

run `bubc`

### Expected behavior

The brew plugin is a ten-year-old plugin. Many commands in this plugin are widely used. I think it's necessary to add a deprecated warning before we remove a widely used command. Otherwise, removing a widely used command without any discussion or warning is more like irresponsible behavior...

### OS / Linux distribution

macOS

### Zsh version

5.9

### Oh My Zsh version

master (efafef8)

### Terminal emulator

Wezterm

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Hi @Zheaoli, this is what you would have seen when updating to a version containing 51d71e650c369a5c3805a629c1efd314b5628921, provided you have the update verbosity defaults:

![changelog showing breaking change](https://github.com/user-attachments/assets/cf8204d1-f60b-484a-8955-099bbfac0af0)

As you can we do provide warnings whenever we introduce breaking changes, which is inevitable in long-running plugins with aliases if the tools change their behavior. That is why I introduced the changelog feature. If for any reason you missed this, or disabled the changelog, it would've been easy to understand the culprit:

- The alias `bubc` is showing command not found, let's see if the alias is still there
- `alias | grep bubc` shows nothing, ok the alias seems to be gone
- The alias came from the `brew` plugin, let's check the README or the changelog (or if unaware of the feature, the commit list)

What else can we do here? We can add versioning #9216 and post the changelog's to GitHub releases. That is a work in progress, and as you'll see the big volume of issues and PRs, you'll understand why it's not yet done.

By the way, the reason why this was removed in favor of `bup` (`brew upgrade`) is that for a long time Homebrew has by default done the cleanup automatically, therefore the old alias was no longer needed.

**Comment by g-a-c** [comment]
> What else can we do here?

Given that nothing _harmful_ was happening, simply _wasteful_, having `bubc` just print some kind of deprecation warning before just running `bup` seems like it would have been a nicer way to handle this. Yes, I understand it's in the changelog but you've already acknowledged that can be hidden. In my case, I use the `tmux` plugin so anything I SSH into usually shows the changelog for a fraction of a second and then my `tmux` session resumes/starts so the changelog is simply lost.

Whereas making `bubc` a shim to `bup` seems like it would have been perfectly fine in this case and avoid some confusion, not breaking existing users who are used to `bubc`, removing the wasteful `brew cleanup` command, and giving people time to update their use of `bubc` to the correct `bup` before dropping `bubc` in several weeks/months.

I'm also confused why other documented aliases still exist that use `brew cleanup`, shouldn't they all have been removed at the same time?
