### ISSUE TITLE
Display Issue in Zsh Terminal When Using Ctrl + \ During top Command

### ISSUE THREAD

**Issue by S0nG0ku0** [ohmyzsh/ohmyzsh#12625]
### Describe the bug

When running the top command in the Zsh terminal and subsequently pressing Ctrl + \ (which sends a quit signal to the running process), the terminal display becomes garbled. Specifically, after pressing Ctrl + \.

### Steps to reproduce

1. Open a Zsh terminal.
2. Execute the top command.
3. While top is running, press Ctrl + \.

### Expected behavior

Pressing Ctrl + \ should terminate the top command cleanly and return the terminal to its normal state without displaying corrupted or unrelated content.

### OS / Linux distribution

macOS Catalina 10.15.7

### Zsh version

5.7.1

### Oh My Zsh version

master (d6f84f3)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

### Additional context

- The issue does not seem to occur with other commands
- The terminal may need to be cleared or reset to restore normal functionality after this issue occurs.

**Comment by GNUSheep** [comment]
Hi! I might be wrong, and not fully understand your problem, but I think it's more related to terminal itself not the shell. 

Function like zoom in and out, are handled by terminal. I tested this behavior on Alacritty, Gnome terminal, and kitty, using different shells, oh my zsh, bash, sh and the results are the same. I didn't get corrupted terminal only zoomed one.

Maybe it's something wrong with your term?

**Comment by S0nG0ku0** [comment]
I also use Zsh on Kitty, and it gives me the same behavior as if I ran top and pressed Enter (CTRL + \) to quit top. It looks like this:
<img width="934" alt="Screen Shot 2024-08-19 at 8 35 45 PM" src="https://github.com/user-attachments/assets/05819921-49d5-4e3a-bf8e-392cf14cbe05">

**Comment by GNUSheep** [comment]
Hmm very weird, I reproduced your steps and got normal output

![image](https://github.com/user-attachments/assets/873f1047-95a8-41ef-ac41-4b6865df17a7)

**Comment by carlosala** [comment]
That is completely normal, and it's due to how terminals render characters. If you resize, the characters' sizes no longer fit and appear messed up.
It is not due to Oh My Zsh at all.
