### ISSUE TITLE
Add a success/failure function to mvn plugin mvn-or-mvnw

### ISSUE THREAD

**Issue by joe-chambers** [ohmyzsh/ohmyzsh#12636]
### If the feature request is for a plugin or theme, specify it here.

mvn

### If the feature solves a problem you have, specify it here.

When I run builds, especially long running builds I start another task.  I have put a success/failure validator around mvn such that it calls 'say "Build Complete." on success and "Build Failed." on failure.  It would be useful if there was a way to configure mvn-or-mvnw to be decorated with a mvn-success function or mvn-failure function so that custom actions could be performed when the build is complete.  Or at least a mvn-complete function.

### Describe the proposed feature.

A way to configure a method to be called after the mvn or mvnw call in mvn-or-mvnw.  I can see 2 ways of doing this but I have limited shell/zsh skills so maybe this is not doable.

1. add a decorator such as mvn-run around mvn-or-mvnw that accepts the return state and uses that to determine whether to call mvn-success or mvn-failure depending on whether it is defined, potentially an alias of some sort...
2. add a decorator such as mvn-run around mvn-or-mvnw that just calls mvn-complete depending on whether it is defined, potentially on an anlias of some sort...

It would be good if the mechanism gave the user some way of turning it off, like a quiet flag for running builds during meetings so that it doesn't go off while your manager is talking.

### Describe alternatives you've considered

I changed the mvn-or-mvnw function to directly make the changes I wanted, but this is intelligent at best and provides no mechanism for the customization for each individual developer.

**Comment by mcornella** [comment]
The plugin directly calls `mvnw` or `mvn` and returns its exit code. I assume these return a 0 exit code on success, and non-zero on failure, as most commands.

Therefore, using simple shell practices it is straightforward to do this without any changes to the plugin:

```sh
your_func() {
  [[ $? -eq 0 ]] && say "build successful" || say 'failed!'
} 

mvn-or-mvnw; your_func
```

You can even add this as an alias to run it whenever you want. It might be a good idea to document this use case in the plugin README.

Thoughts?

**Comment by mcornella** [comment]
Closing because there is no interest on this and there is a clear shell-native option without having to change anything.
