### ISSUE TITLE
tmux 'ts' conflicts with moreutils 'ts'

### ISSUE THREAD

**Issue by bitozoid** [ohmyzsh/ohmyzsh#12649]
### If the feature request is for a plugin or theme, specify it here.

Tmux Plugin

### If the feature solves a problem you have, specify it here.

The 'ts' alias (tmux new-session) conflicts with the more common 'ts' (timestamp) utility from moreutils.

### Describe the proposed feature.

Just rename 'ts' to 'tns'.

### Describe alternatives you've considered

None

**Comment by carlosala** [comment]
Hi!
`ts` is actually very used in `tmux` plugin, and doing a deprecation now would surely be painful for some users. For the moment I'd recommend you add `unalias ts` at the end of your `zshrc` in case that's an issue for you, or just execute timestamp using `command ts`.
If there are more users affected we might consider renaming the alias in the future.
Thanks for the report!
