### ISSUE TITLE
Terminal hangs on sourcing .zshrc with Oh My Zsh enabled

### ISSUE THREAD

**Issue by Zhao2z** [ohmyzsh/ohmyzsh#12656]
### Describe the bug

When attempting to SSH into an Ubuntu 20.04 server and after setting the default shell to zsh with Oh My Zsh, the terminal hangs indefinitely during the sourcing of the ``.zshrc`` file, specifically at the 
``source $ZSH/oh-my-zsh.sh`` 
line. This issue does not occur when Oh My Zsh is not installed or when .zshrc is removed.

### Steps to reproduce

1. Install `zsh` and Oh My Zsh on the server.

2. Configure `.zshrc` with minimal settings:

   ```
   export ZSH=$HOME/.oh-my-zsh
   ZSH_THEME="robbyrussell"
   plugins=(git)
   source $ZSH/oh-my-zsh.sh
   ```

3. Attempt to SSH into the server or open the ``zsh``.

4. Observe that the terminal hangs without loading the shell.

### Expected behavior

The terminal should load `zsh` with the specified Oh My Zsh configuration without hanging.

### Screenshots and recordings

<img width="529" alt="image" src="https://github.com/user-attachments/assets/9bf790ab-b7e5-45e6-b965-65693e644fdd">
<img width="432" alt="image" src="https://github.com/user-attachments/assets/29947c53-4630-4899-ac1a-b32d59f2944a">
<img width="997" alt="image" src="https://github.com/user-attachments/assets/5ada998e-f3fb-459a-9f47-e021865f4c91">

### OS / Linux distribution

Ubuntu 20.04

### Zsh version

5.8 (x86_64-ubuntu-linux-gnu)

### Oh My Zsh version

Latest

### Terminal emulator

iTerm2, VS Code Terminal , cmd, PowerShell and more.

### If using WSL on Windows, which version of WSL

None

### Additional context

**Relevant logs and/or screenshots:**

```
+/home/zhao2z/.oh-my-zsh/oh-my-zsh.sh:11> [ -n 5.8 ']'  
# Protect against non-zsh execution of Oh My Zsh (use POSIX syntax here)
...
+/home/zhao2z/.oh-my-zsh/oh-my-zsh.sh:43> [[+/home/zhao2z/.oh-my-zsh/oh-my-zsh.sh:43> emulate
```

Error-related outputs are indicative of an issue with the `emulate` function, which might be related to Oh My Zsh’s compatibility or a misconfiguration.

I have checked related issues such as [[#11686](https://github.com/ohmyzsh/ohmyzsh/issues/11686)](https://github.com/ohmyzsh/ohmyzsh/issues/11686) but found that the problem seems unique to my setup as I have no explicit `emulate` settings.

**Comment by mcornella** [comment]
Check that your zsh works well making subshells, as inhttps://github.com/ohmyzsh/ohmyzsh/issues/12478#issuecomment-2220963558. To reproduce, you can leave the zshrc file empty and just replace it with
```sh
echo $(echo this should run)
```
If the shell hangs there, you'll have confirmed it's the same issue as #12478.

**Comment by Zhao2z** [comment]
Thank you, @mcornella, for the guidance. Following your suggestion, I've confirmed that my issue is related to the zsh command substitution problem, as seen in [#12478](https://github.com/ohmyzsh/ohmyzsh/issues/12478). Running the test command echo $(echo this should run) causes zsh to hang, indicating a similar underlying issue.

Unfortunately, I've searched extensively but haven't found a workable solution to this problem, either in the discussions of #12478 or elsewhere. If anyone has encountered and resolved this issue, could you share any insights or potential fixes? I am interested in both temporary workarounds and more permanent solutions.

Thank you for any further assistance you can provide!

**Comment by mcornella** [comment]
Nice @Zhao2z! So the next steps are checking where zsh comes from. I think you said this is Ubuntu 20.04, so the right project to hit will be the package maintainer for zsh. Again, if Ubuntu, this is launchpad: https://launchpad.net/ubuntu/+source/zsh.
