### ISSUE TITLE
Terminal prompts abnormal display.

### ISSUE THREAD

**Issue by BennettChina** [ohmyzsh/ohmyzsh#12672]
### Describe the bug

I use the OpenCloudOS in Tencent Cloud. I installed oh-my-zsh for it, and then the prompt was displayed abnormally.

### Steps to reproduce

- install git
- install `oh-my-zsh`

### Expected behavior

Normal display.

### Screenshots and recordings

<img width="856" alt="image" src="https://github.com/user-attachments/assets/22421be9-4468-4c85-9f30-a094eac68c9e">

The problem is the server in the window below.This should confirm that it is not a window size issue.

### OS / Linux distribution

OpenCloudOS 9

### Zsh version

5.8.1

### Oh My Zsh version

master (f6cd6a7)

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Hi! What do you have on `RPROMPT`? Could you try `unset RPROMPT`?
Since the default theme does not touch the right prompt, it might stick to what the distro added in the first time.

**Comment by BennettChina** [comment]
>  the `RPROMPT` print `%n@%m %1~ %# `.


Thanks, it solves the problem.
