### ISSUE TITLE
Remove `ipython` alias

### ISSUE THREAD

**Issue by adamchainz** [ohmyzsh/ohmyzsh#12676]
### Describe the bug

I installed IPython globally on my system as an [uv tool](https://docs.astral.sh/uv/concepts/tools/), and now running `ipython` fails like so:
 
```
$ ipython
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'IPython'
```

This happens because IPython isn't available on the default interpreter, instead it’s installed in an isolated environment. The same would happen with a [pipx install](https://pypi.org/project/pipx/).

### Steps to reproduce

1. have no global install of IPython
2. have oh-my-zsh python plugin installed
3. `uv tool install ipython`
4. run `ipython`

### Expected behavior

IPython opens

### OS / Linux distribution

macOS

### Zsh version

5.9

### Oh My Zsh version

master (ab3d42a)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

### Additional context

I think the alias should be removed. We don’t have similar aliases for the hundreds of other CLIs that users may wish to ensure run in their virtualenv.

**Comment by mcornella** [comment]
Confirmed, I have the same issue. It also does not solve anything that's not already provided by the virtual environment, I believe this is a relic of the past when venvs were more broken that they are now.

**Comment by adamchainz** [comment]
Thanks for the quick response! 🥳
