### ISSUE TITLE
jsontools plugin README links to casino website

### ISSUE THREAD

**Issue by ABCRic** [ohmyzsh/ohmyzsh#12671]
### Describe the bug

`plugins/jsontools/README.md` links to `ndjson DOT org` which at the time of writing is some kind of casino website and not the intended link.

### Steps to reproduce

Click link described above.

### Expected behavior

Should link to relevant documentation.

### OS / Linux distribution

N/A

### Zsh version

N/A

### Terminal emulator

N/A

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Fixed in e3e80b98b575ab75b9c7d182184faffc0b51c5f9. Thanks for the report!
