### ISSUE TITLE
(feat) terraform: Add tffl alias for terraform force-unlock

### ISSUE THREAD

**Issue by Arun1106** [ohmyzsh/ohmyzsh#12686]
### If the feature request is for a plugin or theme, specify it here.

terraform

### Describe the proposed feature.

what if we have one more alias for 
``` $terraform force-unlock ```
as tffu

**Comment by mcornella** [comment]
You are not providing usefulness or reasoning for adding this. If you want us to include a change you have to at least put a minimal amount of effort.

After reading what this command does, I don't think it'll be used widely enough or frequently enough to require an alias, and especially by users that know what it does.
