### ISSUE TITLE
Cannot change selection colour of command area on Molokai theme

### ISSUE THREAD

**Issue by yildizmy** [ohmyzsh/ohmyzsh#12692]
### Describe the bug

I am trying to change the colour of the selected command area when clicking on a line, but although I have tried to change colour of several options starting from "Selection" under Settings > Profiles > Colors menu in iTerm2, the selected area background colour is not changed. Selection option only changes the border of that area. 

So, is it possible to change the background of the corresponding command area?

### Steps to reproduce

Set Molokai theme and click on a command line, you will see the related area in gray 

### Expected behavior

The selected area colour could be changed via Selection or another setting under Profiles

### OS / Linux distribution

MacOS

### Zsh version

5.6

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by rwmitchell** [comment]
What does this have to do with OMZ?

You're probably better off trying over here: https://gitlab.com/gnachman/iterm2/-/issues

**Comment by yildizmy** [comment]
Reported via that page, thanks.
