### ISSUE TITLE
Getting error: "getting "iconv: iconv_open(, -t): Invalid argument Error converting string from to UTF-8" on OSX

### ISSUE THREAD

**Issue by RainerXE** [ohmyzsh/ohmyzsh#12703]
### Describe the bug

After the install of omyzsh i get the error:getting 
"iconv: iconv_open(, -t): 
Invalid argument Error converting string from to UTF-8"

### Steps to reproduce

Install on osx 14.7

### Expected behavior

No Error

### OS / Linux distribution

macos 14.7

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by beingPro007** [comment]
Can You tell particulary where in the codebase the error coming up
