### ISSUE TITLE
(feat) terraform: Add `--auto-approve` for destroy

### ISSUE THREAD

**Issue by za** [ohmyzsh/ohmyzsh#12709]
### If the feature request is for a plugin or theme, specify it here.

terraform

### If the feature solves a problem you have, specify it here.

When I am sure that I want to delete created resources without have to confirm.

### Describe the proposed feature.

What if we add one more alias:

```
$ terraform delete --auto-approve
```

as `tdaa`

### Related Issues

https://github.com/ohmyzsh/ohmyzsh/issues/12591

**Comment by mcornella** [comment]
Duplicate of #12704.
