### ISSUE TITLE
Oh My Zsh failed to Install

### ISSUE THREAD

**Issue by ifiok-akpan** [ohmyzsh/ohmyzsh#12724]
### Describe the bug

I got operation time out while trying to install Oh My Zsh.

ifiok@Ifiok-MacBook-Pro ~ % sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
curl: (35) Recv failure: Operation timed out
ifiok@Ifiok-MacBook-Pro ~ % sh -c "$(curl -fsSL https://install.ohmyz.sh)"
curl: (35) Recv failure: Operation timed out

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/38065c11-35b4-4fc0-b0d3-450963dd99d3)

ifiok@Ifiok-MacBook-Pro ~ % sh -c "$(curl -fsSL https://install.ohmyz.sh)"
curl: (35) Recv failure: Operation timed out

### Expected behavior

Successful installed

### OS / Linux distribution

MacOS Sonoma 14.6.1

### Zsh version

5.9

### Oh My Zsh version

none

### Terminal emulator

iTerm1

### If using WSL on Windows, which version of WSL

None

**Comment by siddxharth** [comment]
There seems to be an internet issue on your side. Please check your internet and firewall settings. 

And since you are on MacOS, consider installing **xcode-tools**. It will install some essential tools on your system.

Use this command to install **xcode-tools**: `xcode-select --install`

**Comment by codeslayed** [comment]
update curl

**Comment by carlosala** [comment]
Closing, seems not related to ohmyzsh itself.
Thanks for the report!

**Comment by ifiok-akpan** [comment]
working fine
