### ISSUE TITLE
Themes using ZSH_THEME_GIT_PROMPT_ADDED not working properly

### ISSUE THREAD

**Issue by shikibu-z** [ohmyzsh/ohmyzsh#12728]
### Describe the bug

Themes using `ZSH_THEME_GIT_PROMPT_ADDED` is not showing correspond prompt after `git add`.

### Steps to reproduce

1. Using an officially provided theme that support git added changes using `ZSH_THEME_GIT_PROMPT_ADDED`, for example, `adben`.
2. Add something in a git repo with `git add .`.
3. Press return to see the new prompt.

### Expected behavior

The prompt should reflect recent adds, for example, many themes use a `+` symbol to indicate added changes. However, this is not showing as expected.

### OS / Linux distribution

macOS 15.0.1

### Zsh version

5.9

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

### Additional context

This happened after an upgrade of git. My current git version is 2.46.2. Might because of a change in git that affected OMZ?

**Comment by krrish-sehgal** [comment]
I would like to work on this , Please assign me this issue under hacktoberfest 2024.
Thanks.

**Comment by mcornella** [comment]
As far as I can tell the `adben` theme has the variables defined, but doesn't actually use the `git_prompt_status` function that's required for this to show up.

Check out another theme such as `avit` or `jonathan`, you should see this show up (in a different way depending on the theme).

**Comment by fdelacruz** [comment]
I'm sorry, why was issue closed this still not working as intended.
