### ISSUE TITLE
PM2 autocompletion does not work

### ISSUE THREAD

**Issue by Knapoc** [ohmyzsh/ohmyzsh#12733]
### Describe the bug

When trying to auto complete pm2 using tab, no pm2 specific options or commands are listed to be used as arguments.

Maybe the following part gives a hint on why completion fails?
`   +_dispatch:53> comp='' `

### Steps to reproduce

1. Enable plugin `pm2`
2. Try to complete command `pm2`
3. see completion proposal where only folders and files of the current working directory are listed

[zsh30131pm21.txt](https://github.com/user-attachments/files/17276277/zsh30131pm21.txt)

### Expected behavior

Wenn completing `pm2` command the following completion proposals should be listed
- commands
- options
- files in the working directory(?)

### Screenshots and recordings

Actual output
![Image](https://github.com/user-attachments/assets/13327e5b-f446-471b-a61f-34e218b00e6c)

Output when using completion script installed via `pm2 completion install`
![Image](https://github.com/user-attachments/assets/575696ff-4eb8-45f3-8000-f0417956b360)

### OS / Linux distribution

Debian GNU/Linux 12 (bookworm) / RaspberryPi OS

### Zsh version

5.9

### Oh My Zsh version

master (a72a264)

### Terminal emulator

Terminal.app (ssh)

### If using WSL on Windows, which version of WSL

None

### Additional context

Official completion script:
```zsh
###-begin-pm2-completion-###
### credits to npm for the completion file model
#
# Installation: pm2 completion >> ~/.bashrc  (or ~/.zshrc)
#

COMP_WORDBREAKS=${COMP_WORDBREAKS/=/}
COMP_WORDBREAKS=${COMP_WORDBREAKS/@/}
export COMP_WORDBREAKS

if type complete &>/dev/null; then
  _pm2_completion () {
    local si="$IFS"
    IFS=$'\n' COMPREPLY=($(COMP_CWORD="$COMP_CWORD" \
                           COMP_LINE="$COMP_LINE" \
                           COMP_POINT="$COMP_POINT" \
                           pm2 completion -- "${COMP_WORDS[@]}" \
                           2>/dev/null)) || return $?
    IFS="$si"
  }
  complete -o default -F _pm2_completion pm2
elif type compctl &>/dev/null; then
  _pm2_completion () {
    local cword line point words si
    read -Ac words
    read -cn cword
    let cword-=1
    read -l line
    read -ln point
    si="$IFS"
    IFS=$'\n' reply=($(COMP_CWORD="$cword" \
                       COMP_LINE="$line" \
                       COMP_POINT="$point" \
                       pm2 completion -- "${words[@]}" \
                       2>/dev/null)) || return $?
    IFS="$si"
  }
  compctl -K _pm2_completion + -f + pm2
fi
###-end-pm2-completion-###
```

**Comment by krrish-sehgal** [comment]
I would like to work on this , Please assign me this issue under hacktoberfest 2024.
Thanks.
