### ISSUE TITLE
Error on update

### ISSUE THREAD

**Issue by AndresMpa** [ohmyzsh/ohmyzsh#12736]
### Describe the bug

Hey, I've been checking the issues on the repo and I've not seen anything about this. I was updating omz and I got an error about git

### Steps to reproduce

Open a new terminal

```
omz update
```

### Expected behavior

Update omz

### Screenshots and recordings

![Image](https://github.com/user-attachments/assets/c73199fe-c008-41d4-99a4-73a6d33be0fd)

### OS / Linux distribution

Arch Linux x86_64

### Zsh version

5.9

### Terminal emulator

Wezterm

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Hi! Ensure you are on a clean state of the repo (`git status` should show `clean`) and try again. If it still does not work, try `git update-index --refresh` and again, `omz update`.
It seems that your git repo got corrupted.
Feel free to comment if you are able to solve it!
Thanks for the report!

**Comment by AndresMpa** [comment]
Hey @carlosala thanks for your help, but I'm still getting the same error

**Comment by carlosala** [comment]
Reinstall ohmyzsh then, it'll be the easiest
