### ISSUE TITLE
Ohmyzsh_download_Win10_WSL_debian_SSL

### ISSUE THREAD

**Issue by HzFrancesca** [ohmyzsh/ohmyzsh#12739]
I am using Debian under win10 wsl2 and using the tun mode of clash verge rev for proxy. I encountered an SSL certificate problem when downloading ohmyzsh.
我在使用win10 wsl2下的debian，并使用clash verge rev的tun模式进行代理，我在下载ohmyzsh时遇到了ssl证书问题

➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

➜ ~ sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

➜ ~ sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
--2024-10-10 10:29:35-- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 198.18.0.198
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|198.18.0.198|:443... connected.
ERROR: The certificate of ‘raw.githubusercontent.com’ is not trusted.
ERROR: The certificate of ‘raw.githubusercontent.com’ doesn't have a known issuer.

I can indeed download normally using -k etc to bypass the ssl certificate check (which I did), but I'm still confused
我确实可以使用-k等避开ssl证书检查 来进行正常下载（我也确实这么做了），但我仍然感到困惑

sudo apt install ca-certificates
sudo update-ca-certificates
  
Doesn't solve my problem
并不能解决我的问题

**Comment by mcornella** [comment]
Use the alternative installer: https://github.com/ohmyzsh/ohmyzsh?tab=readme-ov-file#basic-installation

**Comment by HzFrancesca** [comment]
   ~ ❯ sh -c "$(curl -fsSL https://install.ohmyz.sh/)"                                                      14:50:39
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
