### ISSUE TITLE
_add_identities:16: regex matching error: illegal byte sequence

### ISSUE THREAD

**Issue by markwsljames** [ohmyzsh/ohmyzsh#12745]
### Describe the bug

After https://github.com/ohmyzsh/ohmyzsh/pull/12741, I get this error on startup:
_add_identities:16: regex matching error: illegal byte sequence

### Steps to reproduce

1. Enable the ssh-agent plugin
2. Create a binary file in $HOME/.ssh (In my case, it's random_seed).
3. Start zsh

### Expected behavior

No errors.

### Screenshots and recordings

```
Last login: Sat Oct 12 11:35:31 on ttys001
_add_identities:16: regex matching error: illegal byte sequence
$ 
```

### OS / Linux distribution

macOS 12.7.6

### Zsh version

5.8.1

### Oh My Zsh version

master (d2d5155)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

### Additional context

The issue seems to be that:
`   $(command head -n 1 "$file") =~ ^-----BEGIN\ OPENSSH\ PRIVATE\ KEY-----`
expects the output to be UTF-8, but the binary file is not UTF-8.

This diff fixes the issue for me, although I haven't tested with many key types:

```
diff --git a/plugins/ssh-agent/ssh-agent.plugin.zsh b/plugins/ssh-agent/ssh-agent.plugin.zsh
index becd5ea..14ab98d 100644
--- a/plugins/ssh-agent/ssh-agent.plugin.zsh
+++ b/plugins/ssh-agent/ssh-agent.plugin.zsh
@@ -45,7 +45,7 @@ function _add_identities() {
     # Iterate over files in .ssh folder.
     for file in "$HOME/.ssh"/*; do
       # Check if file is a regular file and starts with "-----BEGIN OPENSSH PRIVATE KEY-----".
-      if [[ -f "$file" && $(command head -n 1 "$file") =~ ^-----BEGIN\ OPENSSH\ PRIVATE\ KEY----- ]]; then
+      if [[ -f "$file" && $(command head -n 1 "$file") = -----BEGIN\ OPENSSH\ PRIVATE\ KEY----- ]]; then
         # Add filename (without path) to identities array.
         identities+=("${file##*/}")
       fi
```

**Comment by mikhailde** [comment]
@markwsljames Thanks for reporting this issue and the detailed analysis! You're right, the previous implementation had problems with binary files in the .ssh directory.

I've addressed this and broadened private key format support in a new pull request: #12758. This PR uses the `file` command to identify keys based on their content, which avoids the binary file issue and works with various key formats like PKCS#1, PKCS#8, and more.

Please check out #12758 and let me know if it resolves the issue for you. You can test it by updating your local repository with the changes from that PR and then restarting your shell.

I appreciate your contribution in highlighting this problem!

**Comment by markwsljames** [comment]
That PR fixes my issue, but creates new ones.
Specifically, my .ssh directory contains a bunch of old files, including old ssh keys:
```
➜ file identity.ancient
identity.ancient: OpenSSH RSA1 private key, version 1.1
➜ zsh
.../.ssh/identity.ancient is not a key file.
Error loading key ".../.ssh/identity.ancient": invalid format
```
If the goal is to emulate ```ssh-add``` with no arguments, then I think the original approach of hard-coding filenames is probably best, as that is what open-ssh does.

**Comment by markwsljames** [comment]
Sure, that's fine.
If that's the desired behaviour, I think this comment is misleading though:
'''# Mimics calling ssh-add with no arguments.'''
As is, this is much more permissive than ssh-add with no arguments.

**Comment by markwsljames** [comment]
Just to be clear about the behaviour change, the changes the valid keys that are loaded, not just the ancient ones.

For example, if I have a number of host-specific keys, ```host-a-id_dsa```, ```host-b-id_dsa```, etc., then the old behaviour would not load those keys.  I could add them the the zstyle identities, or choose to load them specifically.

I've used this pattern in the past in my ssh_config:
```
Host www.host-a.example
     User host-a-user
     IdentityFile ~/.ssh/host-a-key.pem

Host www.host-a.example
     User host-b-user
     IdentityFile ~/.ssh/host-b-key.pem
```

If I wanted to add those keys, I'd explicitly call ```ssh_add ~/.ssh/host-a-key.pem```.  More commonly though I'd expect a password to be needed for these hosts.

I'm not claiming the new behaviour is wrong, or worse than the old behaviour.  I am claiming that it's different, and that the comments in the code suggest that it isn't.

**Comment by mikhailde** [comment]
@markwsljames You're right, the previous comment was misleading. I've updated it to more accurately reflect the current behavior:

```zsh
# If no keys specified in zstyle, loads all private keys in ~/.ssh
```

Thanks for pointing this out!
