### ISSUE TITLE
Autocorrect is doing it too much

### ISSUE THREAD

**Issue by GogoFC** [ohmyzsh/ohmyzsh#12748]
### Describe the bug

Hello

Your autocorrect is good, but it's also guessing too much. 

I have 4 datasets which are 2 VMs plus a zvol for the disks.

```
marabou/vm/npm-cali                            2.62G   905G   116K  /marabou/vm/npm-cali
marabou/vm/npm-cali-broken                     4.63G   905G   160K  /marabou/vm/npm-cali-broken
marabou/vm/npm-cali-broken/disk0               4.62G   905G  2.62G  -
marabou/vm/npm-cali/disk0                      2.62G   905G  2.62G  -

```

So I was moving the disk from `npm-cali-broken` to `npm-cali` and all of the disks on these VMs are called disk0 if there's one disk. The names of these VMs are similar so I guess that's why autocorrect guessed wrong. It's very much possible to overwrite the wrong data. It wouldn't have  been possible in this case because it's the same file but still.

Before tab. This is where it should go.

![Image](https://github.com/user-attachments/assets/001cf1fc-02af-46c9-893b-9e1d98a853c3)

After tab. This is not where I want it to go.

![Image](https://github.com/user-attachments/assets/0d8ee138-0c45-45e0-8335-dfbdaf39a306)

### Steps to reproduce

above

### Expected behavior

above

### OS / Linux distribution

FreeBSD

### Zsh version

zsh 5.9 (amd64-portbld-freebsd14.0)

### Terminal emulator

GNOME on Ubuntu 24.04

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
I'm not that familiar with zfs, but I believe in the `zfs destroy`, the dataset no longer exists. The completion to `recv` therefore uses existing ones, if I am to interpret `zfs` completion [^1] [^2] correctly.

This is all zsh-side though, in Oh My Zsh we do nothing related to zfs completion.

[^1]: https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_zfs

[^2]: https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Type/_zfs_dataset

**Comment by Mattchew9009** [comment]
marabou/vm/npm-cali                            2.62G   905G   116K  /marabou/vm/npm-cali
marabou/vm/npm-cali-broken                     4.63G   905G   160K  /marabou/vm/npm-cali-broken
marabou/vm/npm-cali-broken/disk0               4.62G   905G  2.62G  -
marabou/vm/npm-cali/disk0                      2.62G   905G  2.62G  -

**Comment by Mattchew9009** [comment]
marabou/vm/npm-cali                            2.62G   905G   116K  /marabou/vm/npm-cali
marabou/vm/npm-cali-broken                     4.63G   905G   160K  /marabou/vm/npm-cali-broken
marabou/vm/npm-cali-broken/disk0               4.62G   905G  2.62G  -
marabou/vm/npm-cali/disk0                      2.62G   905G  2.62G  -

**Comment by Mattchew9009** [comment]
Duplicate of #12883

**Comment by Mattchew9009** [comment]
/https://github.com/ohmyzsh/ohmyzsh/issues/12748
