### ISSUE TITLE
add important alias

### ISSUE THREAD

**Issue by arynishere** [ohmyzsh/ohmyzsh#12785]
### If the feature solves a problem you have, specify it here.

user this alias to the [ohmyzsh](https://github.com/ohmyzsh/ohmyzsh/tree/master)/[templates](https://github.com/ohmyzsh/ohmyzsh/tree/master/templates)
/zshrc.zsh-template

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

### Describe the proposed feature.

add this alias is populer alias in the shell 
for template zshrc : 
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

**Comment by carlosala** [comment]
Closed in #12786
