### ISSUE TITLE
direnv plugin doesn't properly hook in direnv

### ISSUE THREAD

**Issue by ahvigil** [ohmyzsh/ohmyzsh#12798]
### Describe the bug

Adding `direnv` to my zshrc plugins doesn't properly activate direnv.

### Steps to reproduce

1. Activate `direnv` plugin in `.zshrc`
2. Restart shell
3. `cd` into a directory with an `.envrc` file
4. Nothing happens

### Expected behavior

direnv loads `.envrc` file for a directory

### OS / Linux distribution

macOS 14.6.1

### Zsh version

5.9

### Oh My Zsh version

master (7ed475c)

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

### Additional context

the only way I could figure to get this working is to disable the plugin and manually added `eval "$(direnv hook zsh)"` to the end of my `.zshrc` file which works fine, as documented at https://direnv.net/docs/hook.html#zsh

direnv version:
```
➜  ~ direnv --version
2.35.0
```

**Comment by mcornella** [comment]
Check that `direnv` is added to the `$PATH` before OMZ is loaded in your zshrc file. If not, move any `$PATH` changes to the top of the file.

**Comment by dbalabka** [comment]
@mcornella it helps. Thanks!

**Comment by dbalabka** [comment]
@carlosala , it would be great to add a warning message that `direnv` is not found:
https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/direnv/direnv.plugin.zsh#L2
