### ISSUE TITLE
External Theme - Heapbytes outdate info

### ISSUE THREAD

**Issue by kellyayong** [ohmyzsh/ohmyzsh#12816]
### Describe the bug

I installed the [Heapbytes Terminal](https://github.com/heapbytes/heapbytes-zsh) theme, which is one of the external themes listed on the [External Themes Wiki page](https://github.com/ohmyzsh/ohmyzsh/wiki/External-themes#heapbytes-terminal-theme), but I ran into two issues. One of the issue is that the prompt is showing a weird character, which could be a font issue but the wiki page mentioned not needing any external fonts: 

> **Features**
> - Fork/update/inspiration of rkj theme.
> - Prints the tun0 IP if connected to a VPN
> - Prints the wlan0 IP if you aren't connected to any VPN. (change the module name in .zsh-theme according to your wifi module)
> - Easy for pentesters who needs their ip for creating rev shells.
> - Git info.
> - Doesn't require any external fonts.

Second issue is that the `ls` command stopped working and this was returned: `zsh: command not found: exa`, which might be some issues with the alias. I tried downloading exa but it seems that [exa is no longer maintained and has been disabled by Homebrew](https://github.com/ogham/exa/issues/1243).

### Steps to reproduce

**Issue 1:**
Add the heapbytes-mac.zsh-theme file to my .oh-my-zsh/custom/themes folder
Updated ZSH_THEME="heapbytes" in the .zhrc file and included the changes seen in the .zshrc file for the heapbyte theme:
1. Updated plugins to include auto suggestion and highlights:
```
# Add wisely, as too many plugins slow down shell startup.
plugins=(git
  zsh-autosuggestions  
  zsh-syntax-highlighting
  )
```
2. Include other aliases and customization:
```
# On-demand rehash
zshcache_time="$(date +%s%N)"

autoload -Uz add-zsh-hook

rehash_precmd() {
  if [[ -a /var/cache/zsh/pacman ]]; then
    local paccache_time="$(date -r /var/cache/zsh/pacman +%s%N)"
    if (( zshcache_time < paccache_time )); then
      rehash
      zshcache_time="$paccache_time"
    fi
  fi
}

add-zsh-hook -Uz precmd rehash_precmd

# omz
alias zshconfig="geany ~/.zshrc"
alias ohmyzsh="thunar ~/.oh-my-zsh"

# exa --icons
# ls
alias ls='exa --icons'
alias l='exa --icons -lh'
alias ll='exa --icons -lah'
alias la='exa --icons -A'
alias lm='exa --icons -m'
alias lr='exa --icons -R'
alias lg='exa --icons -l --group-directories-first'

# git
alias gcl='git clone --depth 1'
alias gi='git init'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push origin master'

#my

#alias nvim='$HOME/.local/bin/lvim'
#alias lvim='$HOME/.local/bin/lvim'
alias pinstall='sudo pacman -S'
alias upinstall='sudo pacman -Sy'
alias yinstall='yay -S'

precmd(){
	precmd(){
		echo 
	}
} 
```
Then restarted zsh with `exec zsh`

**Issue 2:**
Tried downloading exa with`brew install exa` 

### Expected behavior

As shown in the image in the wiki page, the strange character should be a triangle and the `ls` command should list out all the files in the current directory.
![Image](https://github.com/user-attachments/assets/1233f0f6-d1a2-42ab-8e2f-3f520c920124)

### Screenshots and recordings

Strange character in place of a triangle and `ls` command not returning a list of files but: `zsh: command not found: exa`
![Image](https://github.com/user-attachments/assets/ea7a3ce1-159e-4fc1-8b87-171a296e5f2c)
(I slightly tweaked the heapbytes-mac.zsh-theme file to not show my ip address.)

`brew install exa` showed that it is unmaintained and has been disabled:
![Image](https://github.com/user-attachments/assets/2d580998-efe1-492b-b8e5-b569fc29d36c)

### OS / Linux distribution

macOS 12.6.7

### Zsh version

5.8.1

### Terminal emulator

iTerm2, Terminal.app

### If using WSL on Windows, which version of WSL

None

### Additional context

Hoping to update the info on the External Themes wiki page.

**Comment by carlosala** [comment]
Hi! That's an external theme, please open the issue at https://github.com/heapbytes/heapbytes-zsh.
Feel free to open a PR to https://github.com/ohmyzsh/wiki for fix the issues.
Thanks for the report!
