### ISSUE TITLE
The ➜ char messes up tab completion in iTerm2

### ISSUE THREAD

**Issue by eliasgs** [ohmyzsh/ohmyzsh#1282]
```
➜  ~  cdcd lol/
```

With  robbyrussell theme the first char (➜) is messing up my tab completion in iTerm2 (Build 1.0.0.20120203) - i.e. the first two chars of the command is prepended to the command, looks really strange!

Changing ➜ to eg. >  in the theme file, fixes this.

**Comment by Freyskeyd** [comment]
i'm experienced this bug in a container on `debian` and on `ubuntu`.

Exporting LC_ALL and LANG didn't do anything...

**Comment by Phrewfuf** [comment]
use dpkg-reconfigure locales and select the locale you need with UTF-8, then it works just fine.

**Comment by franklinyu** [comment]
I'm experiencing this bug in OS X Yosemite with theme agnoster. Exporting `LC_ALL` and `LANG` didn't do anything. I guess the environment trick does not work for Zsh 5 (mine is `zsh 5.0.5 (x86_64-apple-darwin14.0)`). @kevinxucs, did you come with a solution for Zsh 5?

**Comment by kjgfcdb** [comment]
For someone like me who suffers this bug in a Docker container, try this command:

```bash
sudo apt-get install locales
sudo locale-gen en_US.UTF-8
```

Then add 
```bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

in your `.zshrc`
