### ISSUE TITLE
toolbox prompt adds a new line in prompt

### ISSUE THREAD

**Issue by thanosz** [ohmyzsh/ohmyzsh#12824]
### Describe the bug

plugins/toolbox/toolbox.plugin.zsh
```
function toolbox_prompt_info() {
  [[ -f /run/.toolboxenv ]] && echo "⬢"
}
```
Shouldn't be `echo -n `?

### Steps to reproduce

- Enable plugin toolbox
- Add toolbox_prompt_info() in the prompt segment

### Expected behavior

The prompt should show character ⬢ when in toolbox without adding a new line

### OS / Linux distribution

Fedora Silverblue 

### Zsh version

5.9

### Oh My Zsh version

master (366d2543)

### Terminal emulator

ptyxis

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
This shouldn't be the case. Both `echo` and `echo -n` yield the same output in the prompt. This has to be a different issue with your theme.
Thanks for the report

**Comment by thanosz** [comment]
Ok, this happens in because I am using an out-of-tree version of agnoster theme. Thanks for checking it out though!
