### ISSUE TITLE
Unable to install tailscale plugin

### ISSUE THREAD

**Issue by tkm5** [ohmyzsh/ohmyzsh#12843]
### Describe the bug

Adding tailscale to the zsh plugin list results in a not found.

### Steps to reproduce

plugins=(
  tailscale
)

Add tailscale to plugins as above

### Expected behavior

The following errors occur

[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

[oh-my-zsh] plugin 'tailscale' not found

### OS / Linux distribution

macos 15.1.1

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Hi! Are you running the latest `omz` version? You can ensure it by running `omz update`, and ensure you are in branch `master` of `omz`, by `cd $ZSH && git branch`.

**Comment by tkm5** [comment]
After an omz update, the error no longer occurs. Thanks for letting me know !!
