### ISSUE TITLE
Consider changing the "news and updates" link

### ISSUE THREAD

**Issue by litetex** [ohmyzsh/ohmyzsh#12861]
### If the feature solves a problem you have, specify it here.

So I just updated and noticed the ``To keep up with the latest news and updates, follow us on X: https://x.com/ohmyzsh``

<details><summary>Clicked it and got this page:</summary>

![Image](https://github.com/user-attachments/assets/e488b74e-920c-4e10-91dd-120199892674)

Always nice to have half of the page blocked with banners and popups :(

</details>

<details><summary>When I scroll down a bit to get "news and updates" I see all posts in completely random order:</summary>

![Image](https://github.com/user-attachments/assets/73b2b6e6-e753-43b8-a949-4701344e797f)

</details>

So I can't really get "news and updates" information here...

### Describe the proposed feature.

Change https://github.com/ohmyzsh/ohmyzsh/blob/b9e73b44811becbdf24cff54441c73839a29c523/tools/upgrade.sh#L274 to your [mastodon account](https://mstdn.social/@ohmyzsh)  - as it is way more accessible than Twitter/X,

### Describe alternatives you've considered

Remove the link completely

**Comment by carlosala** [comment]
Hey! At the moment the social network that we update the most is https://x.com/ohmyzsh. If we start using other socials or cross-posting tools we'll revise it.
Thanks for the idea!

**Comment by bothyculture** [comment]
Please consider using bluesky instead!
