### ISSUE TITLE
Strange character inserted before result of each command

### ISSUE THREAD

**Issue by slhck** [ohmyzsh/ohmyzsh#1338]
I use the latest oh-my-zsh from today with zsh 4.3.17, just installed via `curl` on Ubuntu 12.04 with GNOME Terminal. Whenever I run a command, a strange character is printed before the result:

```
werner@satyr:~/.oh-my-zsh% ls
klscustom  lib  log  oh-my-zsh.sh  plugins  README.textile  templates  themes  tools
```

Actually, the real output should start at `custom`, not with `kls`. Here's a screenshot:

![](http://i.imgur.com/3oTuw.png)

The full `.zshrc` I use is [here](https://raw.github.com/slhck/dotfiles/master/.zshrc). Everything works fine without oh-my-zsh, but as soon as I source it, I get the problem mentioned above. Note that I primarily use this zshrc on OS X, but it has worked on Linux before.

Let me know if there is more information needed to get to the root of this issue.

**Comment by liangguohuan** [comment]
@rolfschr thanks. this is helpful.
ubuntu 14.04 is the same problom.

**Comment by flakrat** [comment]
Ha, I feel like an idiot. I was having this issue when using gnome-terminal and completely forgot to set the fonts in the Gnome Terminal profile prefs to use a Powerline font. Grr....

```shell
# If running in Gnome Terminal, set the default profile font to Powerline
if [ `echo $VTE_VERSION` -eq 3409 ]; then
  oldfont=$(gconftool-2 --get /apps/gnome-terminal/profiles/Default/font)
  newfont="Meslo LG M for Powerline 9"

  echo "Changing gnome-terminal Default profile font from: '$oldfont' to '$newfont'"
  gconftool-2 --set /apps/gnome-terminal/profiles/Default/font --type string "$newfont"
fi
```

**Comment by jenguidanos** [comment]
I get on this today. The problem starts after set "export TERM="screen-256color"" on .zshrc. Enable DISABLE_AUTO_TITLE="true" has resolved the problem to me (thanks @joseronierison)
