### ISSUE TITLE
/oh-my-zsh.sh:source:12: no such file or directory: /oh-my-zsh.sh

### ISSUE THREAD

**Issue by itsthatguy** [ohmyzsh/ohmyzsh#1339]
when trying to use `$ ~/.oh-my-zsh/tools/theme_chooser.sh` I get:

``` zsh
/oh-my-zsh.sh:source:12: no such file or directory: /oh-my-zsh.sh

╺━┓┏━┓╻ ╻   ╺┳╸╻ ╻┏━╸┏┳┓┏━╸   ┏━╸╻ ╻┏━┓┏━┓┏━┓┏━╸┏━┓
┏━┛┗━┓┣━┫    ┃ ┣━┫┣╸ ┃┃┃┣╸    ┃  ┣━┫┃ ┃┃ ┃┗━┓┣╸ ┣┳┛
┗━╸┗━┛╹ ╹    ╹ ╹ ╹┗━╸╹ ╹┗━╸   ┗━╸╹ ╹┗━┛┗━┛┗━┛┗━╸╹┗╸


ls: /themes: No such file or directory
```

**Comment by klday** [comment]
itsthatguy can you tell me how you "exported the path from your terminal"?

**Comment by mcornella** [comment]
The `theme_chooser.sh` file is old and doesn't work properly, we have have to fix and simplify the theme choosing process. I'd recommend [having a look at the wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes) instead.
