### ISSUE TITLE
 command not found: ^M on zsh start

### ISSUE THREAD

**Issue by sadfuzzy** [ohmyzsh/ohmyzsh#1363]
/home/savitsky/.zshrc:3: command not found: ^M
/home/savitsky/.zshrc:9: command not found: ^M
/home/savitsky/.zshrc:13: command not found: ^M
/home/savitsky/.zshrc:16: command not found: ^M
/home/savitsky/.zshrc:19: command not found: ^M
/home/savitsky/.zshrc:22: command not found: ^M
/home/savitsky/.zshrc:25: command not found: ^M
/home/savitsky/.zshrc:28: command not found: ^M
/home/savitsky/.zshrc:32: command not found: ^M
/home/savitsky/.zshrc:33: command not found: ^M
/home/savitsky/.zshrc:source:34: no such file or directory: /home/savitsky/.oh-my-zsh^M/oh-my-zsh.sh^M
/home/savitsky/.zshrc:35: command not found: ^M

After clean manual install (through git and template copy).

**Comment by wzyuliyang** [comment]
themgt  answer is helpful

**Comment by nephast** [comment]
Thanks themgt, your answer worked for me

**Comment by berdnikov** [comment]
Please, help. I have the same problem, but I can't solve it by your advices
`/home/nb/.zshrc:3: command not found: ^M
/home/nb/.zshrc:9: command not found: ^M
...
...
gateway% 
`
And defaul directory became gateway%  instead of ~

**Comment by ababushkin** [comment]
@themgt suggestion worked for me thanks mate!

**Comment by PinkiMittal** [comment]
I did almost similar to what @bradjenn did. Changed the line endings to unix. The above command did not work for me. so i opened particular file which was causing this issue using tool - (Sublime, notepad++ any such) and then choose view --> line ending --> unix.

**Comment by contracamilo** [comment]
I had to remove autocrlf = true from ~/.gitconfig

**Comment by MandeepSinghey** [comment]
I have to fix it manually by going to each file
by opening each file in vim and then

:e ++ff=dos 
The :e ++ff=dos command tells Vim to read the file again, forcing dos file format. Vim will remove CRLF and LF-only line endings, leaving only the text of each line in the buffer.

then

:set ff=unix 
and finally

:wq

**Comment by mcornella** [comment]
Make sure you have the `core.autocrlf` setting properly set up (as explained above), then you can reset the files following https://github.com/robbyrussell/oh-my-zsh/issues/1363#issuecomment-9811857
