### ISSUE TITLE
kolo theme breaks in new Git repo

### ISSUE THREAD

**Issue by mrkline** [ohmyzsh/ohmyzsh#1367]
Once a commit has been made to a Git repository the theme works fine, but on a new repository the theme complains about not finding HEAD on every command:

```
~ % mkdir test
~ % cd test
test % git init
Initialized empty Git repository in redacted/test/.git/
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
test [master●] % ls
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
```

**Comment by Alexntf** [comment]
Hello, have u solved your problem ? Thank you

**Comment by mcornella** [comment]
The kolo theme uses `vcs_info` which is a zsh tool to fetch information from vcs (e.g. git) repositories. If you're getting this error, I'd suggest using a newer zsh version.
