### ISSUE TITLE
git plugin conflicts with Graphics Magick

### ISSUE THREAD

**Issue by silentroach** [ohmyzsh/ohmyzsh#1432]
There is an alias in git plugin:

alias gm='git merge'

But gm is a binary for Graphics Magick :[

**Comment by slixurd** [comment]
The config of alias is in the ~/.oh-my-zsh/plugins/git/git.plugin.zsh 
You can delete the alias manually;

**Comment by flying-sheep** [comment]
except if it’s installed in a write only location…

**Comment by mcornella** [comment]
The correct solution is https://github.com/robbyrussell/oh-my-zsh/issues/1432#issuecomment-11110953

**Comment by flying-sheep** [comment]
> also the compdef should be reversed to allow for correct completion of graphicsmagick.

how to do that?

**Comment by santimacia** [comment]
Big issue! gm is very used on node environment

**Comment by martinheidegger** [comment]
I would also like to confirm that this is actually an issue.

**Comment by mcornella** [comment]
> Big issue! gm is very used on node environment 
> https://www.npmjs.com/package/gm

That doesn't seem to install a `gm` command, and a `gm` zsh alias won't affect how node calls the `gm` command. 

> I would also like to confirm that this is actually an issue.

We haven't found a solution yet that takes into account people's aliases not changing while not setting up aliases that may conflict with other commands. For the time being, an `unalias gm` at the end of your zshrc file is the best option, though we're working a better implementation that works for everybody. Subscribe to #4585 to get news about this.

**Comment by Qix-** [comment]
Wait a second. Why is `oh-my-zsh` aliasing things for me?
