### ISSUE TITLE
Autocompletion slow on OSX

### ISSUE THREAD

**Issue by jabalsad** [ohmyzsh/ohmyzsh#1469]
After I open a new terminal, my first auto-complete freezes for about a minute. After running "set -x", I see it is computing this line:

+_all_labels:39> compadd -F _comp_ignore -M 'm:{a-zA-Z}={A-Za-z}' -J -default- -qS@ -k -F _comp_ignore -M 'm:{a-zA-Z}={A-Za-z}' -J -default- - userdirs

What can I do to prevent this?

**Comment by viranch** [comment]
This happens to me as well 🙁 

```
» uname -r
3.10.0-514.6.1.el7.x86_64
» zsh --version
zsh 5.0.2 (x86_64-redhat-linux-gnu)
»
```
