### ISSUE TITLE
History completion broken

### ISSUE THREAD

**Issue by ivan-krukov** [ohmyzsh/ohmyzsh#1479]
Since my last merge (about 4 days ago now), the history completion with the up key is not working.
Instead of the ohmyzsh marvel, I get the bland bash "scroll one history item up" thing.
Trying to manually reset the key bindings in .zshrc does not work.
Affects both my machines with OSX and linux.
Any suggestions or finger-pointing on the guilty commiter are welcome.

**Comment by 4F2E4A2E** [comment]
I just replaced the broken plugin with `history-incremental-search-backward` and it worked.

```bash
# bindkey '^r' fzf-insert-history
bindkey '^r' history-incremental-search-backward
```
