### ISSUE TITLE
oh-my-zsh.sh:35: parse error near `elif'

### ISSUE THREAD

**Issue by artemeff** [ohmyzsh/ohmyzsh#1483]
After update I have this error:

```
$ zsh
~/.oh-my-zsh/oh-my-zsh.sh:35: parse error near `elif'
```

How can I resolve this?

**Comment by huang5556019** [comment]
me too...

**Comment by mcornella** [comment]
@huang5556019 this is an error of the sublime plugin. See #4411 for the solution
