### ISSUE TITLE
compinit fails with: bad math expression: illegal character: '

### ISSUE THREAD

**Issue by hdznrrd** [ohmyzsh/ohmyzsh#1495]
After the last autoupdate run oh-my-zsh is broken on my machine.
Even a fresh install of oh-my-zsh doesn't resolve the issue at this point.

Opening a new shell I get the following error:

> % zsh
> compinit:473: bad math expression: illegal character: '
> compinit:473: bad math expression: illegal character: '

The latest commit I've pulled is

> commit 397c085a19a22f6be515665835d09a2505cb3f23
> Merge: bc7157b 1b91c84
> Author: Robby Russell robby@planetargon.com
> Date:   Sun Dec 9 09:04:02 2012 -0800

Distribution info and zsh version:

> % lsb_release -a; zsh --version
> No LSB modules are available.
> Distributor ID:   Ubuntu
> Description:  Ubuntu 12.04.1 LTS
> Release:  12.04
> Codename: precise
> zsh 4.3.17 (x86_64-unknown-linux-gnu)

**Comment by thorian93** [comment]
For me it might have bin a permission issue, as I needed to backup my files to a filesystem which does not support Linux permissions (don't ask) and when I restored them they all had 0777 permissions. I deleted `.zcompdump` before realizing that so I don't know if that actually has to do anything with it, just leaving this information here.

**Comment by dragonchaser** [comment]
For me it was sufficient to just remove `~/.zcompdump`

**Comment by ikitayama** [comment]
> @topikito Your milage may vary, but try deleting just ~/.zcompdump for starters

Thank you so much! You saved me from wasting my time in the afternoon before the long weekend.
