### ISSUE TITLE
fork failed: resource temporarily unavailable

### ISSUE THREAD

**Issue by acarpe** [ohmyzsh/ohmyzsh#1509]
I'm on OS X 10.8.2
after upgrading to latest oh-my-zsh I started to have these errors:

```
Last login: Thu Dec 20 23:36:28 on ttys002
/Users/myuser/.oh-my-zsh/oh-my-zsh.sh:4: fork failed: resource temporarily unavailable
git_compare_version:4: fork failed: resource temporarily unavailable
/Users/myuser/.oh-my-zsh/oh-my-zsh.sh:4: fork failed: resource temporarily unavailable
git_compare_version:4: fork failed: resource temporarily unavailable
/Users/myuser/.zshrc.local:53: fork failed: resource temporarily unavailable
_current_epoch:1: fork failed: resource temporarily unavailable
```

it turns out the problem is in on-my.zsh.sh

```
  # Check for updates on initial load...
  if [ "$DISABLE_AUTO_UPDATE" != "true" ]
  then
    /usr/bin/env ZSH=$ZSH zsh $ZSH/tools/check_for_upgrade.sh
  fi
```

I have changed to use sh instead of zsh and everything started to work again:

```
  # Check for updates on initial load...
  if [ "$DISABLE_AUTO_UPDATE" != "true" ]
  then
    /usr/bin/env ZSH=$ZSH sh $ZSH/tools/check_for_upgrade.sh
  fi
```

**Comment by chrillewoodz** [comment]
This happens constantly when running an ios simulator..

**Comment by donnfelker** [comment]
Just ran into this problem when the Android emulator System UI crashed. Saw @chrillewoodz comment above about the iOS simulator and decided to kill the Android emulator. Sure enough, as soon as I killed the emulator, restarted the terminal all was fine. Very odd. Leaving a comment here for future folks who run across this issue.

**Comment by jomla97** [comment]
Closing both my iOS simulator and Android emulator solved this for me too. +1!

**Comment by elahmo** [comment]
Anyone figured out why is this happening?

I get this with VSCode, doing python development (regular project), with flake linting. And it always happens that python creates more than 500 threads (parent is VSCode), and I get this message across my terminals.

**Comment by LarryWachira** [comment]
Got this today too for the first time ever @elahmo, shortly after updating VSCode. Did you also update as well?

**Comment by elahmo** [comment]
@LarryWachira I got updated few days ago I think, I remember seeing that changelog but dont know which day was it.

I am on 1.30.0 (1.30.0).

**Comment by LarryWachira** [comment]
Same here @elahmo, I am on 1.30.0 and the error started showing up after I updated. Should probably look at all of the stuff that was changed, might be something in the settings we could turn off.

**Comment by xbtlin** [comment]
The same problem, reboot will solve.

**Comment by AdamKyle** [comment]
> The same problem, reboot will solve.

Ya try having to do that at least once a day with a hard reboot because of this issue.

**Comment by mcornella** [comment]
Try looking for long chained processes in `ps` command with a tree output (in my system, `ps axf` prints process trees; `pstree` also works if you can get it). Of course you won't be able to do that once you get the fork failed error, so you need to do that frequently enough that you catch the culprit. You can run [`watch`](https://linux.die.net/man/1/watch) in a separate terminal and take a snapshot of running processes every 5 seconds or something like that.

**Comment by chucklessmith** [comment]
I just found ~1000 instances of cron running on my machine, after having to restart it this morning due to this error. Reasonably sure that's related to the ongoing instability.

**Comment by yogithesymbian** [comment]
any other alternative ? instead of reboot machine / server ?
parse_git_dirty:18: fork failed: resource temporarily unavailable

**Comment by eduardo-lisboa-picpay** [comment]
Thank you very much. Just made this change here and it seems to have solved my problem as well. Cheers,
