### ISSUE TITLE
Tab completion not using dir_colors

### ISSUE THREAD

**Issue by andyleejordan** [ohmyzsh/ohmyzsh#1563]
## Environment

Oh-my-zsh in Ubuntu with terminal [Solarized colorscheme](https://github.com/sigurdga/gnome-terminal-colors-solarized) and [Solarized ANSI-dark dir_colors](https://github.com/seebi/dircolors-solarized). See my [dotfiles](https://github.com/andschwa/dotfiles).
## Issue

Tab auto completion in zsh is not using dir_colors.This line is before the oh-my-zsh.sh source:

```
eval `dircolors ~/.dir_colors`
```
## Example

Typing `vim TAB` lists the files, but not with the same directory colors that `ls` does.
## Workaround

Adding this line after sourcing:

```
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
```
## Fix

Somewhere, I'm guessing in `lib/completion.zsh`, a line like this needs to be fixed/added. But I'm not sure which or where, or what others. Interestingly, tab completion with this workaround also is acting like `ls -F` slash the --classify option. I'm thinking there should be a way to enable/disable this.

Thanks!

**Comment by alexmondaini** [comment]
I just placed ( eval `dircolors ~/.dircolors ) before exporting ZSH="/home/user/.oh-my-zsh" and it works like a charm. =)

So in your .zshrc file you would have (eval) before (export).

# sourcing ls colors
eval `dircolors ~/.dircolors`


# env variable
export ZSH="/home/your_username/.oh-my-zsh"
