### ISSUE TITLE
Please help! Cannot uninstall zsh.

### ISSUE THREAD

**Issue by matheuscandido** [ohmyzsh/ohmyzsh#1675]
I installed zsh on my mac but I want to get back to bash. None of the usual commands work on it, sudo, ls, cd, nothing. When i try to uninstall zsh with the uninstall_oh_my_zsh I get the following message:
   Removing ~/.oh-my-zsh
   /Users/Matheus/.oh-my-zsh/tools/uninstall.sh: line 4: rm: command not found
   Looking for original zsh config...
   Switching back to bash
   /Users/Matheus/.oh-my-zsh/tools/uninstall.sh: line 24: chsh: command not found
   Thanks for trying out Oh My Zsh. It's been uninstalled.
But it doesn`t unisntall, when I restart Terminal there`s zsh. I tried to run the command by its complete path, with the command:
   Users/Matheus/.oh-my-zsh/tools/uninstall.sh
But I get a "zsh: permission denied". I also can`t run it with sudo, because sudo doesn`t work.
Please guys help me restore my old and good bash.

**Comment by rbaindourov** [comment]
Removed zsh with apt-get.
Ran `apt-get --reinstall install bash`
Modified `/etc/passwd`
Ran `/usr/bin/chsh -s /bin/bash`

Help, how to get rid of this?

```
robert@superhost ~ $ sudo -s
[sudo] password for robert: 
sudo: /usr/bin/zsh: command not found
robert@superhost ~ $ 
```

**Comment by mcornella** [comment]
You need to logout of your current user session and log back in again.

**Comment by Mihara17** [comment]
Go into terminal 
Click on help
It explains everything

**Comment by DominicTobias** [comment]
Restoring bash works thanks, however installing zsh with brew and then uninstalling doesn't seem to actually remove zsh i.e. it's still at bin/zsh (and don't know what other residual files are around)

**Comment by mcornella** [comment]
`/bin/zsh` is provided by macOS according to [this StackExchange comment](https://apple.stackexchange.com/a/100476).

**Comment by DominicTobias** [comment]
Ah makes sense thanks, also I read earlier it will be the default next OS version

**Comment by bengrunfeld** [comment]
I am unable to uninstall Zsh. I don't mean "switch from zsh to bash". I mean get rid of it so that it no longer exists on my computer. Is there any way to do that?

**System:** macOS Sierra 10.12.6
**Version:** zsh 5.2 (x86_64-apple-darwin16.0)

Steps I tried:

```
~ $ uninstall_oh_my_zsh
-bash: uninstall_oh_my_zsh: command not found
~ $ chsh -s /bin/bash
Changing shell for USER.
Password for USER:
chsh: no changes made
~ $ which zsh
/bin/zsh
```

**Comment by nbedevi** [comment]
@bengrunfeld  I tried your solution but in the last command I can't delete `zsh` I got 
```
$ sudo rm -rf /bin/zsh
Password:
rm: /bin/zsh: Operation not permitted 
```

**Comment by mcornella** [comment]
That's what he said, that it doesn't work. I'd bet that Apple forbids that because the system uses it, even if you don't. Personally I don't see why you'd want to remove it, as long as you've set it up so that you use bash by default it shouldn't be a problem.

**Comment by robbyrussell** [comment]
What @mcornella said. This is likely an Apple restriction with the base operating system.

**Comment by lienista** [comment]
> can you try
> 
> ```
> /usr/bin/chsh -s /bin/bash
> ```

you would also have to close the terminal program and re-open it. It took me 15mins to figure this out.
