### ISSUE TITLE
The safe-paste plugin does not make pasting safe and breaks other features.

### ISSUE THREAD

**Issue by SushiDude** [ohmyzsh/ohmyzsh#1742]
The [safe-paste plugin was recently introduced](https://github.com/robbyrussell/oh-my-zsh/pull/1698) to provide protection from the copy-paste shell command attack as demonstrated at https://thejh.net/misc/website-terminal-copy-paste but fails to do so.
It is even stated on the page that the exact plugin does not work.

> Please note that Bracketed Paste Mode DOES NOT fix this because the end sequence can be inside the text you paste! For those of you who have installed the oh-my-zsh stuff, sorry, but the following variant (which includes an escape sequence) still works against you

Enabling this plugin also breaks the escaping of special characters that are pasted including those of URLs.

The safe-paste plugin should be ether removed or fixed immediately because it is giving users a false sense of security and breaks other important features.

**Comment by unphased** [comment]
I use PuTTY which does not support bracketed paste. Is there a capability of telling zsh to escape newlines (not immediately execute them) if they arrive within a very small amount of time?
