### ISSUE TITLE
fork failed: resource temporarily unavailable

### ISSUE THREAD

**Issue by itismadhan** [ohmyzsh/ohmyzsh#1898]
Hey guys all of a sudden I am getting the following
/etc/zshenv:3: fork failed: resource temporarily unavailable
/Users/XXX/.oh-my-zsh/tools/check_for_upgrade.sh:31: fork failed: resource temporarily unavailable
git_compare_version:4: fork failed: resource temporarily unavailable
getent:4: fork failed: resource temporarily unavailable
__rvm_has_opt:3: fork failed: resource temporarily unavailable
[5]    14246 done
git_prompt_info:1: fork failed: resource temporarily unavailable

**Comment by jasonleonhard** [comment]
#### To view all limits

    ulimit -a

or 

    ulimit -H -u

Notice the -u processes limit. To set to a higher number:

ulimit -S -u 1064

This will only last until a new terminal window is open so put it in your .bash_profile or equivalent 

Then run the previous command to verify 

Hope this helps.

**Comment by waterblues** [comment]
ps aux | grep "what you want to execute"
kill -9 pid

I think it's because there are already the same  processes running.

**Comment by nutandevjoshi** [comment]
Just close Zsh and open again
