### ISSUE TITLE
Autocomplete display bug

### ISSUE THREAD

**Issue by dkushnikov** [ohmyzsh/ohmyzsh#1905]
I have problem when I make autocomplete.
When I type some letters ("rub" for example) and press "Tab" then first and second symbols of my string ("ru") freeze before cursor and now in command line I see "ruruby" 
![2013-06-23 20 35 24](https://f.cloud.github.com/assets/1129911/692399/f755ff3e-dc22-11e2-9a91-bc0d0f6f9b8e.png)

What can I do to fix this?

**Comment by taghouti** [comment]
> Try this in your .zshrc file:
> 
> ```
> export LC_ALL=en_US.UTF-8
> export LANG=en_US.UTF-8
> ```
> 
> I had the same issue and this fixed it. See [this other issue](https://github.com/robbyrussell/oh-my-zsh/issues/1282) if you want more info.

Workd thnx <3

**Comment by tammoj** [comment]
Made my day :D

**Comment by satsaeid** [comment]
Made my day too!! thank you. <3
