### ISSUE TITLE
A few invalid symbols in 'agnoster.zsh-theme'

### ISSUE THREAD

**Issue by hitigon** [ohmyzsh/ohmyzsh#1906]
Like line 29. Please fix it. Thank you.

**Comment by xinput** [comment]
hello. 

i got a problem with the agnoster theme.
i want to use agnoster bit it looks like this 
![bildschirmfoto 2015-04-18 um 23 29 34](https://cloud.githubusercontent.com/assets/11652924/7217313/0423c2da-e623-11e4-9584-5e88d287e416.png)

when i tried a git checkout to an older agnoster front i get this error:
![bildschirmfoto 2015-04-18 um 23 29 53](https://cloud.githubusercontent.com/assets/11652924/7217317/21e0ea46-e623-11e4-8618-2fd15d3af1f5.png)


someone knows why i get an "too many arguments" error?

**Comment by mjbrender** [comment]
FYI -- seems like this is back in El Capitan: 

<img width="372" alt="screen shot 2015-10-01 at 8 06 23 pm" src="https://cloud.githubusercontent.com/assets/1744971/10236778/e95b7024-6877-11e5-9599-a857eaa8d2ef.png">

**Comment by DanielGGordon** [comment]
Kind of a side question, but has anyone ever gotten Agnoster/oh-my-zsh to work properly on Cygwin (Windows)? I'm wondering if it is even worth trying to accomplish.

**Comment by CyberLight** [comment]
If you has a problem on **El Capitan 10.11 El Capitan 10.11.1**,  please use fixed version of theme from my repo 
https://github.com/CyberLight/agnoster.zsh-theme

**Comment by scboffspring** [comment]
@DanielGGordon yup It works fine wiht cygwin :)

**Comment by mcduder** [comment]
@scboffspring what did you change to make it work?

**Comment by mcornella** [comment]
Use an updated powerline font. See github.com/powerline/fonts

**Comment by DanielGGordon** [comment]
@scboffspring So I didn't get the font working - but even if I got that working, another problem was it was slooooow. I'm talking about 5-7 seconds just to `cd` into my repo.

**Comment by mcduder** [comment]
@DanielGGordon I got it to work by using a [mod](https://gist.github.com/mcduder/d767808a2aa2942dd524) for agnoster that I tinkered around with a little bit. This should be faster and try to look for fonts in here https://github.com/powerline/fonts. Install the font and then restart cygwin and check in the options.

**Comment by DanielGGordon** [comment]
Oh interesting. I'll try that mod and then try installing the fonts again. I'm actually trying this on Babun now instead of full blown Cygwin (which seemed like an overkill for me). I'll report back with results

**Comment by DanielGGordon** [comment]
Still having trouble with those fonts. I ran the `install.ps1` script from [powerline](https://github.com/powerline/fonts), but no luck. For some reason, I only see Meslo fonts - and when I try to select them, it says they don't exist.

**Comment by mcduder** [comment]
@DanielGGordon don't run the install.ps1. Install whichever font you want individually.

**Comment by DanielGGordon** [comment]
Sweet! Good call. So right now I am using Inconsolata for Powerline and it looks like this. It seems a few things are still missing. I'll try a few other fonts and see if I can get it to work.
 Getting closer...

![image](https://cloud.githubusercontent.com/assets/11824880/11964792/a6945228-a8b5-11e5-85ae-bb230b5b703b.png)

**Comment by afilini** [comment]
As said [here](http://www.xplatform.rocks/2015/05/07/setting-up-iterm2-with-oh-my-zsh-and-powerline-on-osx/), the right font is probabily [Meslo](https://github.com/Lokaltog/powerline-fonts/blob/master/Meslo/Meslo%20LG%20M%20DZ%20Regular%20for%20Powerline.otf)

**Comment by DanielGGordon** [comment]
Lol... I've been trying to getting a Meslo font to work for days. It's the only font that doesn't work.

**Comment by base698** [comment]
This same thing is happening to me, do I install meslo fonts?

**Comment by DanielGGordon** [comment]
Hey there - you can install any powerline patched fonts. If you are using Windows, there are very few fonts that work as intended. 

What are you running this on? If Windows, I had success with DejaVu Sans Mono.

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/DejaVuSansMono/Regular/complete

Nerd-fonts contain all the symbols required for agnoster. You need to install it on your operating system, and then you have to go to your terminal (iTerm2, Gnome Terminal, Mintty) and enable that font there.

**Comment by base698** [comment]
I'm on a Mac.  Input Mono font works.

**Comment by DanielGGordon** [comment]
Ok cool! For anyone else who stumbles upon this, I had good success with the **DejaVu Sans Mono for Powerline Nerd Font Complete Mono Windows Compatible.ttf** from nerd fonts that I linked above.

Here is the direct link to that font:

[DejaVu Sans Mono complete for Windows](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/DejaVuSansMono/Regular/complete/DejaVu%20Sans%20Mono%20for%20Powerline%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf)

**Comment by tristobal** [comment]
In Ubuntu (16.05), this works:
 
```
sudo apt-get install fonts-powerline
```

**Comment by cjburkey01** [comment]
Use the Meslo LG L DZ Regular for Powerline font, it works for me.

**Comment by MohammedAl-Mahdawi** [comment]
@tristobal Thank you, it is worked for me(Ubuntu 16.04). I just restarted my computer after running

`sudo apt-get install fonts-powerline`

**Comment by norberto5757** [comment]
Don't more time sorry ai needed money don't party

look with deep sincerity do not know when or I receive your e'm just a
systems programmer with a very broad curriculum right through 37 years of
living today than my children offer me forgiveness if at any time
incosiente were taxed. my data but not. nothing to disturb my social
environment much less in a country that I admire ye visited for several
years my name is norberto gonzalez rojas and my mobile in mexico is
6645872021 my address from my home in Tijuana, Baja californa is Andador A
#, 31 elRubi apologies please delete my information from your database ever
and hurt anyone thanks blessings also I inform you that do not speak
English use the Google translator only thing that 100% are programming
terms what I do on social networks is to speak God does not send me anyone
is not charging its own initiative or annoying people tendencista'm not
religious and I am apolotitico only love God above all things blessings.
Me number is +526645872021

**Comment by cqcsobreyra** [comment]
Some of the above alluded to this, but I figured I'd clarify the solution that worked for me:
Under  ITerm2 -> Preferences -> Profiles -> Text, I unchecked the checkbox that says 'Use a different font for non-ASCII text'

or 

You can also set the font under the non-ASCII font selection that comes up when you have the checkbox checked.

**Comment by chucklor** [comment]
I've tried most of what's been posted here and it's not working for me. I'm using Mac OS El Capitan Version 10.11.5. I still see the question mark. The theme I'm using is Agnoster although I have tried several other themes and I still have the same issue. I've also tried different Powerline fonts as well and it's the same result.

![zsh-symobls](https://cloud.githubusercontent.com/assets/20845188/18849766/25736244-83fa-11e6-81ba-d36fa2b15e9c.png)

**Comment by ChavaSobreyra** [comment]
@chucklor which method did you use for installing the fonts? Did you uncheck the box that says 'Use different font for non-ASCII text' ?

**Comment by chucklor** [comment]
I have tried double click and FontBook to install the fonts. And  yes, I'v unchecked the "Use different font for non-ASCII" box.

**Comment by ChavaSobreyra** [comment]
@chucklor I believe you, but it seems it's still not working. Which powerline font are using? Maybe provide a screenshot of your ITerm2 -> Preferences -> Profiles -> Text options? 

Other suggestions: 
- Install the fonts using the install.sh at https://github.com/powerline/fonts
- Also try restarting iTerm and your Mac.

**Comment by chucklor** [comment]
Here's my screen shot. 
![screen shot 2016-09-28 at 11 39 48 am](https://cloud.githubusercontent.com/assets/20845188/18923039/8106492e-8570-11e6-9f31-9fe76b6b5a65.png)

**Comment by chucklor** [comment]
Any suggestion?

**Comment by wwwdata** [comment]
I had this problem as well. I think a year ago I had to upgrade to a new powerline font. How up to date are your fonts? As already mentioned look into the repo that was linked. 

I reinstalled my mac last week and everything is working with the newest Hack font. Maybe try that font and if it works for you it must be an outdated powerline font on your computer. http://sourcefoundry.org/hack/

**Comment by kode54** [comment]
Was a reboot or log out and log in cycle mandatory after installing the fonts? I just installed the latest Powerline fonts repository, which I notice no longer includes Menlo for Powerline, I assume because of copyright concerns.

**Comment by kode54** [comment]
Found the problem: The Wiki for Themes still links to:

https://github.com/powerline/fonts

Which seems to have pre-2012 mapping fonts, at least when I just git cloned it.

https://github.com/Lokaltog/powerline-fonts, however, works.

**Comment by mcornella** [comment]
@kode54 [Lokaltog/powerline-fonts](https://github.com/Lokaltog/powerline-fonts) redirects to [powerline/fonts](https://github.com/powerline/fonts). If you're trying to use Menlo just use Meslo which is open source.

**Comment by chrishough** [comment]
A strong recommendation I have to get around this is move to https://github.com/tonsky/FiraCode

**Comment by schmunk42** [comment]
I had the wrong encoding here ...

![bildschirmfoto 2016-12-08 um 14 37 59](https://cloud.githubusercontent.com/assets/649031/21011975/1a93786c-bd54-11e6-80e9-69b9a903ecf5.png)

*Maybe it helps someone else with a similar issue, I had i.e. no broken fonts or whatever.* Can't remember if I did change that accidentally or it was due to an update.

**Comment by kevinquillen** [comment]
lpredova's suggestion worked for me.

**Comment by fleed** [comment]
The there is working well for me in `iTerm2`, but I'm having issues with `terminal`. Any suggestion to fix it `terminal` too?

<img width="888" alt="terminal_issue" src="https://cloud.githubusercontent.com/assets/2131800/21837315/6d75db4c-d7cb-11e6-8bb9-49da81bfe73d.png">

**Comment by mlopezcoria** [comment]
I've got the same issue on Linux mint 18. I'm using Gnome Terminal and I've installed PowerLine Fonts from here https://github.com/powerline/fonts

![powerline_issue](https://cloud.githubusercontent.com/assets/15494802/22201132/142f3054-e141-11e6-8bdd-dea3d4571c5b.png)

**Comment by pradeepchaudharisc** [comment]
It's 2016 and I still see the same issue

**Comment by djsd123** [comment]
@pradeepchaudharisc Or at least add some steps to the README.md 👍

**Comment by pradeepchaudharisc** [comment]
@djsd123 I will send pull request soon 👯‍♂️

**Comment by pradeepchaudharisc** [comment]
https://github.com/robbyrussell/oh-my-zsh/pull/5822

**Comment by juandiego26** [comment]
@DanielGGordon thanks worked for me!!

**Comment by ismailhkose** [comment]
I followed the all instructions at Ubuntu 16.04 for agnostic theme, but they didnt work. I am seeing invalid symbols

![image](https://user-images.githubusercontent.com/353824/27888590-bfe28204-619b-11e7-92f7-1c8a82978d97.png)

https://gist.github.com/agnoster/3712874
https://powerline.readthedocs.io/en/latest/installation/linux.html#font-installation
https://github.com/agnoster/agnoster-zsh-theme#agnosterzsh-theme

I installed patched powerline fonts and solarized theme.

Any comment?

**Comment by ismailhkose** [comment]
echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"

![image](https://user-images.githubusercontent.com/353824/27888720-72f63e44-619c-11e7-989e-ad924c7a5c7b.png)

I dont not see all character in the following picture
https://gist.githubusercontent.com/agnoster/3712874/raw/characters.png
![image](https://user-images.githubusercontent.com/353824/27888735-a3052dd4-619c-11e7-9749-a3550d7d61ea.png)

**Comment by ismailhkose** [comment]
I noticed that It was cygwin displaying issue. It was working in Ubuntu. 
When I install powerline fonts to Windows, the problem was solved.

**Comment by primaveraentalca** [comment]
I was having this issue on Debian 9 with rxvt-unicode.
![This](https://stackoverflow.com/a/38475948/5905704) answer helped me.
I'm using Hack font (fonts-hack-ttf package on debian) on my .Xresources:
`URxvt.font: xft:Hack:size=8`

**Comment by danigosa** [comment]
For those poor bastards like me that had activated iTerm2's options _antialised_ and _non-Ascii fonts_, appart from using powerline fonts, uncheck them!

**Comment by willguxy** [comment]
(re)installing powerline fonts and change fonts in profile worked for me 
https://github.com/powerline/fonts

**Comment by fenek5** [comment]
If you are on macOS Sierra/ High Sierra you'll probably need this : http://powerline.readthedocs.io/en/master/installation/osx.html

Thank me later.

**Comment by karstengresch** [comment]
[lpredovas](https://github.com/robbyrussell/oh-my-zsh/issues/1906#issuecomment-252443982) and - regarding the steps I followed - [pradeepchaudharisc](https://github.com/robbyrussell/oh-my-zsh/issues/1906#issuecomment-275733922) worked for me on iTerm2 but 
**only for new tabs**. 

I.e. already opened tabs did not change which made me a bit crazy for a while.

**Comment by erikcaffrey** [comment]
if you are using **macOS Sierra/ High Sierra**, The problem can be solved installing   https://github.com/powerline/fonts, so  choose `Meslo for Powerline`.

**Comment by griffincox** [comment]
thanks @erikcaffrey, that did the trick for me.

**Comment by erikcaffrey** [comment]
@griffincox great!

**Comment by Oliverwong369** [comment]
iTerm2 users need to set **both** the Regular font and the Non-ASCII Font in "iTerm > Preferences > Profiles > Text" to use a [patched font](https://github.com/powerline/fonts) ( Non-ASCII Font seems to cause the problem )

BTW iTerm2 looks better by binding Zsh with [powerline plugin](https://powerline.readthedocs.io/en/latest/usage/shell-prompts.html#zsh-prompt).  

Preference: 
https://github.com/powerline/fonts
https://powerline.readthedocs.io/en/latest/usage/shell-prompts.html#zsh-prompt

**Comment by Javirln** [comment]
Hello guys, my problem is the following:
<img width="948" alt="screen shot 2018-05-06 at 20 42 20" src="https://user-images.githubusercontent.com/4128269/39676617-38b8d94a-516e-11e8-9252-9e394a4267de.png">
I cannot get rid of that little arrow at the beginning of the prompt. I have the latest version of agnoster and oh-my-zsh and my profile settings are the following:
<img width="1030" alt="screen shot 2018-05-06 at 20 45 36" src="https://user-images.githubusercontent.com/4128269/39676631-71f4c458-516e-11e8-8de9-0357d8feb526.png">

**Comment by euf** [comment]
@Javirln Hello, this little arrow is an indicator of the iTerm2 "Shell Integration" feature. 
> When shell integration is enabled, iTerm2 automatically adds a mark at each command prompt. Marks are indicated visually by a small blue triangle in the left margin.

See https://www.iterm2.com/documentation-shell-integration.html

**Comment by Hyped-247** [comment]
Ok, so here is how I solved it. 
![screen shot 2018-11-05 at 12 45 37 pm](https://user-images.githubusercontent.com/28418995/48025673-ef885280-e0f8-11e8-9a87-9d0fd85281f8.png)
Make sure to select the power line font that you can get from cloning [this](https://github.com/powerline/fonts.git). See the first circle in the picture. 
And once you change the font, play around with the colors until you get the desired result. See the second circle in the picture.

**Comment by gaddyya** [comment]
https://medium.com/vunamhung/disable-marks-in-iterm2-63f2d7340cb6

**Comment by GuganVignesh** [comment]
This need the Powerline fonts installed for the Mac, check here : https://github.com/powerline/fonts

Then if you find the colors to be little not suitable you can change in preferences > display > text > ANSI Colors (customise based on your vision)

**Comment by adrianmihalko** [comment]
I installed the suggested fins, but it is not working.

<img width="800" alt="screenshot 2019-02-15 at 18 30 28" src="https://user-images.githubusercontent.com/733361/52873689-e5daa600-314f-11e9-933e-9c1078bab559.png">

**Comment by ruslanguns** [comment]
I fixed it by changin my default font to DejaVu for e.g.

**Comment by mcornella** [comment]
One solution: https://github.com/robbyrussell/oh-my-zsh/issues/1906#issuecomment-275733922
Summary: install [Powerline fonts](https://github.com/powerline/fonts) and set one of the fonts in your terminal emulator. If it doesn't work try another font.
