### ISSUE TITLE
Update breaks Powerline font symbols with Agnoster theme

### ISSUE THREAD

**Issue by JDRomano2** [ohmyzsh/ohmyzsh#1948]
After running recent updates, Powerline font support seems to be broken (I use the Agnoster theme). For anyone not familiar with Powerline-patched fonts, it adds special characters that are used to render a "status line" (originally created as a Vim plugin). Look at the following image for reference:
![screenshot](https://f.cloud.github.com/assets/843449/750390/48f71416-e4c7-11e2-8c4f-442927103058.png)

With the most recent update, this is what it looks like:
![image](https://f.cloud.github.com/assets/843449/750379/c5e2d9de-e4c6-11e2-97a3-677035b3fbce.png)

I've verified that I'm still using UTF-8 encoding, and the issue occurred simultaneously on three different computers (one running Ubuntu 13.04, one running Ubuntu 13.10, and one running OS X 10.8).

Has anyone else seen this?

**Comment by TheMadCoder1** [comment]
Hi, I can't figure out how to solve this problem. I installed the patched powerline fonts, but the problem persists. What should I do?

**Comment by alanwillms** [comment]
Same thing here. Upgraded ElementaryOS 0.4 yesterday and those same weird characters appeared. Reinstalling the powerfonts didn't solve it.

**Comment by TheMadCoder1** [comment]
@alanwillms I figured out the problem, installing the fonts make it available but then you have to choose a powerline font. Open up your terminal emulator, gnome-terminal and guake for me, and find the profile settings, and edit them and find fonts. Then, select a font that you like with powerline in the name.

**Comment by alanwillms** [comment]
Hi @TheMadCoder1 sorry for taking so long to try it. Unfortunately it didn't work, I tested with Ubuntu Mono on Pantheon Terminal

**Comment by TheMadCoder1** [comment]
Did the font name say "Ubuntu Mono for Powerline"? You have to choose a font that explicitly says for Powerline. You did install the patched fonts above right?

**Comment by alanwillms** [comment]
@TheMadCoder1 it works! Thank you!

```bash
gsettings set org.pantheon.terminal.settings font 'Ubuntu Mono derivative Powerline 12'
# restart terminal app
```
