### ISSUE TITLE
unable to upgrade

### ISSUE THREAD

**Issue by brewster1134** [ohmyzsh/ohmyzsh#1984]
**[Go to solution](https://github.com/robbyrussell/oh-my-zsh/issues/1984#issuecomment-331808425)**

```
[Oh My Zsh] Would you like to check for updates?
Type Y to update oh-my-zsh: Y
Upgrading Oh My Zsh
Cannot pull with rebase: You have unstaged changes.
Please commit or stash them.
There was an error updating. Try again later?
```

**Comment by RussellBradley** [comment]
Same problem... One liner fix.
$ .oh-my-zsh && git stash && upgrade_oh_my_zsh

**Comment by kelthenoble** [comment]
Thanks russelBradley :+1:

**Comment by OrcunOtacioglu** [comment]
The one liner solved my issue. Thank you RussellBradley!

**Comment by dadocreate** [comment]
Thanks russelBradley :+1:

**Comment by cviebrock** [comment]
And don't forget to `git stash pop` after you upgrade to re-apply your changes (if desired).

**Comment by iamgoodbytes** [comment]
Thanks @RussellBradley - that works!

**Comment by jinga50334** [comment]
@ODelibalta It works! thank you!

**Comment by ylluminarious** [comment]
`$ sudo git reset --hard` fixed this for me.

**Comment by zhanghanyuan** [comment]
Thanks russelBradley :+1:

**Comment by QaziPython** [comment]
Thanks @RussellBradley :+1:

**Comment by kayoub5** [comment]
if any of the above does not work for you try this
```sh
cd ~/.oh-my-zsh
git config core.filemode false
```

**Comment by pksurecom** [comment]
Thanks russelBradley !

**Comment by gerson** [comment]
Thanks @RussellBradley

**Comment by Mark-Creeten** [comment]
Thanks russelBradley !

**Comment by Karthicksree** [comment]
Thanks @RussellBradley.

**Comment by eranhirs** [comment]
I happen to be working on a Windows 10 ubuntu bash, so the git changes I had were correlated to running `dos2unix` on the entire directory to fix the `^M` character problem.

After successfully updating, you might want to run
`cd $ZSH`
`find . -type f -print0 | xargs -0 dos2unix`
To fix errors correlated to the `^M` character.

Hope this helps someone.

**Comment by shahzeb1** [comment]
On Mac: 
```shell
cd .oh-my-zsh
git stash
upgrade_oh_my_zsh
git stash pop
```

**Comment by MrEmelianenko** [comment]
Improved one-line solution:

```bash
cd "$ZSH" && git stash && upgrade_oh_my_zsh && git stash pop
```

**Comment by vidyasagar-r** [comment]
Thanks @RussellBradley
+1

**Comment by bilge-Kagan** [comment]
@ODelibalta is right <b>if you concern</b> your changes..

**Comment by softlion** [comment]
Don't forget pop or you'll loose the changes to your themes.

```cd "$ZSH" && git stash && upgrade_oh_my_zsh && git stash pop```

**Comment by DiscipleOfShinku** [comment]
Why there is no option to do this automatically?

**Comment by paul-bjorkstrand** [comment]
For those who are getting here when using babun on Windows, I recommend using @kayoub5's [method for fixing this](https://github.com/robbyrussell/oh-my-zsh/issues/1984#issuecomment-192612396) (copied below):

```
cd ~/.oh-my-zsh
git config core.filemode false
```

Then just let it run the next update.

**Comment by testacode** [comment]
My issue on OSX was I had a `.DS_Store` file generated. removed that and then `upgrade_oh_my_zsh` and that's it.

**Comment by shandou** [comment]
Had similar experience with `oh_my_zsh`.  Did not realize that the installation and upgrade are tied to the repo. Because I changed the CLI prompt in `themes/agnoster.zsh-theme`, it is identified as untracked changes and cause upgrade pull to fail. For now, the following steps works for me:

```
# Step 1: stash the untracked change
cd ~/.oh-my-zsh && git stash

# Step 2: Update by typing the following line in terminal
upgrade_oh_my_zsh

# Step 3: stash pop to recover untracked change
git stash pop
```

**Comment by Natetronn** [comment]
The file `custom/example.zsh` was changed. Like many others, I stashed it and the update worked.

**Comment by mrsarm** [comment]
It just an opinion, but it would help if after the error message is added a new line with a text like _"(Oh My Zsh git repo): ~/.oh-my-zsh"_ so people like me and most people that like this project but are not maintainers nor *Zsh experts don't have to google it.

**Comment by RezaNurRochmat13** [comment]
Thanks is worked @RussellBradley

**Comment by dvmoomoodv** [comment]
> Same problem... One liner fix.
> 
> ```shell
> cd "$ZSH" && git stash && upgrade_oh_my_zsh
> ```

Thanks @RussellBradley

**Comment by bebignet** [comment]
Thanks @RussellBradley !!

**Comment by alanlunspace** [comment]
```
$ git stash    
error: 'custom/example.zsh' is beyond a symbolic link
fatal: Unable to process path custom/example.zsh
Cannot save the current worktree state
```

Caused by [mackup operation](https://github.com/lra/mackup/issues/1384).

If you confirm to ignore all changes mackup made.
`cd "$ZSH" && git reset --hard origin/HEAD && upgrade_oh_my_zsh` should resolve.

**Comment by andyatroam** [comment]
Have tried `cd "$ZSH" && git stash && upgrade_oh_my_zsh`, but it did work for me.
After that I tried follow the error to use `rm -fr ".git/rebase-merge"` and then `upgrade_oh_my_zsh`, resolved my issues.

**Comment by rwmitchell** [comment]
Where are putting your custom plugins that it causes a problem?
