### ISSUE TITLE
Can't update using upgrade_oh_my_zsh

### ISSUE THREAD

**Issue by ghost** [ohmyzsh/ohmyzsh#1991]
Whenever i try to use 'upgrade_oh_my_zsh' the following error occures :

<code>~ » upgrade_oh_my_zsh
Upgrading Oh My Zsh
Cannot pull with rebase: You have unstaged changes.
Please commit or stash them.
There was an error updating. Try again later?</code>

**Comment by simondavies** [comment]
though best let you know i had the same today but @emiscience work like a charm thanks

**Comment by igorapa** [comment]
@emiscience 
![tks](https://cldup.com/A82-qEQQfi.gif)

**Comment by petermumford** [comment]
@emiscience got me on the right track.

For me it was some changes within the `themes` directory

**Comment by RyanBalfanz** [comment]
This just happened to me too. I suspect, but have not yet confirmed, that it was caused by [lra/mackup](https://github.com/lra/mackup). I do have a custom theme, but it's been there for a while and I remember having run `upgrade_oh_my_zsh` successfully before installing mackup.


```shell
➜ ryan@lh .oh-my-zsh git:(master) ✗ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   plugins/bgnotify/bgnotify.plugin.zsh
	modified:   plugins/catimg/catimg.sh
	modified:   plugins/cloudapp/cloudapp.rb
	modified:   plugins/emacs/emacsclient.sh
	typechange: plugins/go/go.plugin.zsh
	typechange: plugins/per-directory-history/per-directory-history.plugin.zsh
	modified:   plugins/scd/scd
	modified:   plugins/wd/wd.sh
	modified:   tools/install.sh
	modified:   tools/require_tool.sh
	modified:   tools/theme_chooser.sh

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	themes/ryanbalfanz.zsh-theme

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by jdsiddon** [comment]
I had problems with this also but I was a doof and put a theme in the themes folder instead of the custom. Once I moved the theme and commited it worked fine.

**Comment by hcharif** [comment]
@emiscience  Tks

**Comment by malcomio** [comment]
I had a similar issue which was caused by one of the plugin files having different permissions. 

You can set your git config to ignore file permission differences:

```git config core.fileMode false```
