### ISSUE TITLE
How to set default user in zshrc

### ISSUE THREAD

**Issue by jbelmont** [ohmyzsh/ohmyzsh#2033]
Hello this is my first post here. I have oh-my-zsh installed and zsh as well. 
I am running Mac OS X 10.7 and using iterm2. I have installed the powerline font patch. I have set agnoster
for my oh my zsh theme. How do I set a DEFAULT_USER in my .zshrc so that user@hostname doesn't show
up.

**Comment by sakz** [comment]
DEFAULT_USERNAME='username'

**Comment by sakz** [comment]
For me worked with  DEFAULT_USER="username"

**Comment by ccharlton** [comment]
Adding ```export DEFAULT_USER=`whoami` ``` (requires backticks, not single-quote) in `~/.zshrc` did the trick for me.

**Comment by phantom7** [comment]
I have El Capitan, iTerm2 Build 2.1.3, powerline theme, and am still getting user@host. I've tried adding to my ~/.zshrc file (only one at a time and then starting a new shell, of course)
DEFAULT_USER=`whoami`
DEFAULT_USER= bobjones
DEFAULT_USER= "bobjones"

FWIW, I needed to add DEFAULT_USER as it wasn't even in the .zshrc (I was expecting to find it commented it out)

any help appreciated!!

**Comment by jbelmont** [comment]
DEFAULT_USER=`whoami` should do the trick remember that either `` or $()
will string interpolate and assign the variable.

**Comment by phantom7** [comment]
Hi....that's what I did. I forgot to markdown escape the backticks in my question (I fixed it) but they were always there. Any other ideas?

**Comment by mcornella** [comment]
Try with `DEFAULT_USER="$USER"`, and remember to put it way up in the zshrc file, at least above the `source oh-my-zsh.sh` line. If you put it below the `ZSH_THEME=agnoster` line you'll be ok.

**Comment by phantom7** [comment]
so strange. that doesn't seem to do it either. Maybe I'm misunderstanding....

My prompt says: bobjones@mbp instead of just bobjones. Isn't the point to just have `bobjones`?

Thanks!

**Comment by mcornella** [comment]
The way this feature works is that it won't print anything if it is the `DEFAULT_USER`, or it will print the whole `user@host` thing if it's not the DEFAULT_USER. If you want to only have `bobjones` printed you could redefine the `prompt_context` function in your `zshrc` file. Here's a working function:

```zsh
prompt_context() {
    local seq
    seq='%(!.{%F{yellow}%}.)%n'
    if [[ "$USER" != "$DEFAULT_USER" ]]; then
        seq="$seq@%m"
    fi
    prompt_segment black default $seq
}
```

**Comment by Decontra** [comment]
Thank you for that mcornella, I was able to change the default user@host to simply output user.

**Comment by Ayoub-Iken** [comment]
for those using *agnoster* theme.  Edit *agnoster.zsh-theme* and find *$user@%m* then delete @%m. save, open your terminal, it should do it now

Image sample:
![editago](https://cloud.githubusercontent.com/assets/5561757/11065198/df216526-87b9-11e5-9bb5-b3e4e904d4ed.png)

**Comment by xiaji** [comment]
@Ayoub-Iken thanks, it works for me.
OS: OS X 10.11.1
iTerm:2.14

**Comment by Ayoub-Iken** [comment]
you welcome happy i could help

**Comment by Frank-the-Obscure** [comment]
To further delete `$USER` for *agnoster* user, view [Ayoub-lken's answer](https://github.com/robbyrussell/oh-my-zsh/issues/2033#issuecomment-155439228) and delete more (line 77-85 by default):

It works at my OS X 10.11.2 and iTerm2 build 2.1.4

```
### Prompt components
# Each component will draw itself, and hide itself if no information needs to be shown

# Context: user@hostname (who am I and where am I)
prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)"
  fi
}
```

**Comment by AirieFenix** [comment]
@mofhu, where did you create $SSH_CLIENT and what did you assign to it? (I imagine the $HOSTNAME or $SHORT_HOST, am I right?)

**Comment by mofhu** [comment]
@AirieFenix, i didn't configure $SSH_CLIENT in `agnoster.zsh-theme` in my version of oh-my-zsh at that time, and it works by default.

**Comment by AirieFenix** [comment]
Yeah, sorry, it looks like it's a var created when a SSH client is connected or the SSH server is running. My Mac (client, top -> SSHd not running) doesn't have it, my Raspberry (host, top-> SSHd running) does show it.

**Comment by lilianmoraru** [comment]
The only way this worked for me was to overwrite the `prompt_context` function at the end of my `.zshrc`.

**Comment by bravist** [comment]
DEFAULT_USER=`whoami`

```shell
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

#chenghuiyong
export PATH=$HOME/.composer/vendor/bin:$PATH
DEFAULT_USER=`whoami`
#chenghuiyong

```

**Comment by taikahessu** [comment]
Remember NOT to use spaces in between:
`DEFAULT_USER=`whoami``

The wrong way:
`DEFAULT_USER = `whoami``

**Comment by she-dev** [comment]
Using what @mofhu said, I made it use the DEFAULT_USER by replacing $USER by $DEFAULT_USER and setting it at ~/.zshrc as `export DEFAULT_USER=desired_username`
```
# Context: user@hostname (who am I and where am I)
prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)$DEFAULT_USER"
  fi
}
```

**Comment by landtanin** [comment]
@taikahessu Your space suggestion saved me. `DEFAULT_USER = whoami` under the `ZSH_THEME` works for me.

**Comment by soulomoon** [comment]
Is there any different wether I put it under prompt_context() function or just under .zshrc

**Comment by praveenmukilan** [comment]
env : macOS sierra + oh my zsh + Solarized Dark Patched + Iterm2 Build 3.0.15
For me, setting the below two options  in **_~/.zshrc_** worked. 

**POWERLEVEL9K_ALWAYS_SHOW_USER=true
POWERLEVEL9K_CONTEXT_TEMPLATE="%n"**

note : no values in DEFAULT_USER worked for me.

**Comment by DuM4ll3** [comment]
The solution provided by @praveenmukilan  worked for me. But just needed the first line tho:
**POWERLEVEL9K_ALWAYS_SHOW_USER=true**

**Comment by steve-taylor** [comment]
This works:

```sh
DEFAULT_USER=$(whoami)
```

**Comment by dankhan-adl** [comment]
Remove `context` segment from left prompt and put `user` segment. 

`POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir vcs)`

**Comment by haccks** [comment]
Remove `context` segment from left prompt and put `user` segment. 

`POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir vcs)`

**Comment by mcornella** [comment]
Powerlevel9k is not supported by Oh My Zsh, find support at their official repo.
