### ISSUE TITLE
Add option to update ohmyzsh on background

### ISSUE THREAD

**Issue by brauliobo** [ohmyzsh/ohmyzsh#2041]
OhMyZsh update may take some time, so some users may want to activate an option to make the update on the background when auto-update option is enabled.

**Comment by alfuken** [comment]
2022, 7 years passed, still no background update.


Extremely frustrating when you urgently need a new tab, but instead you have to wait for 10 seconds while OMZ does it's chores and then barfs at you few screens of rainbow logs. "Can't you do your thing somewhere quietly in background, like any normal piece of tech??"

"Look, I'm updating, I'm all fine, look at me, LOOT AT ME I SAID!!!!111"

![omz_updating](https://user-images.githubusercontent.com/75377/161527777-7e9fc6ed-8284-42b1-832b-ced1ebb12277.png)

User should not be bothered when everything works as intended. What we now have instead, is an example of a bad UX. :/
Only if something happens that is NOT supposed to happen or user's input is unavoidably necessary, then and only then user should be disturbed. (Eternal glory to the person who's idea was to add `DISABLE_UPDATE_PROMPT`, may your days be long and warm, hero)

**Comment by mcornella** [comment]
Hey @alfuken, there are other ways to change the update behavior. One that was recently added was to only show a reminder, which is less disruptive than doing the whole update. You can find more about the settings here: https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#update-settings.

I'll take note of the suggestion to do the update in the backround. Thanks

**Comment by speedcell4** [comment]
Another one and a half years passed, any update?

**Comment by mcornella** [comment]
We have merged a preview version of this feature in #11928:

NOTE: this feature is in alpha / preview mode, it is not guaranteed to work 100% of the
time in all cases. If you experience any issues, open an issue or search for an open
one describing your same situation.

To use this, use the zstyle update mode settings [1] with the value `background-alpha`:

```sh
zstyle ':omz:update' mode background-alpha
```

[1] https://github.com/ohmyzsh/ohmyzsh#getting-updates
