### ISSUE TITLE
How to make oh-my-zsh use the latest zsh version?

### ISSUE THREAD

**Issue by AlexVPopov** [ohmyzsh/ohmyzsh#2141]
I am using zsh with oh-my-zsh in iTerm (OS X). I encounter the following problem:
1. `echo $ZSH_VERSION` returns 4.3.11.
2. I run `upgrade_oh_my_zsh` successfully.
3. `echo $ZSH_VERSION` still returns 4.3.11.
4. I run `brew install zsh` / `brew update zsh` and I get a Error: zsh-5.0.2 already installed.
5. Yet even after restart iTerm `echo $ZSH_VERSION` returns 4.3.11.

How do I make OMZ use the latest zsh version?

**Comment by FateLight** [comment]
first add `/usr/local/bin/zsh` in `/etc/shells`
and `chsh -s /usr/local/bin/zsh`
then `echo $ZSH_VERSION`
