### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by ghost** [ohmyzsh/ohmyzsh#2162]
hey, I installed zsh via oh-my-zsh on my macbook, and was wondering if their is a way to remove this annoying prompt from when I open the terminal: `etc/zprofile:source:2: not enough arguments`. Any help?

**Comment by Johnsalzarulo** [comment]
@tomhanlon - Thank you. Thank you.

**Comment by grayghostvisuals** [comment]
@tomhanlon :+1:  :100:  :fireworks:
