### ISSUE TITLE
Backticks evaluated twice 

### ISSUE THREAD

**Issue by junegunn** [ohmyzsh/ohmyzsh#2234]
See: junegunn/fzf#2

```
➜  ~  echo $TERM
xterm-256color
➜  ~  rm -f /tmp/doh
➜  ~  echo `echo doh >> /tmp/doh`

➜  ~  cat /tmp/doh
doh
doh
```

**Comment by fth86** [comment]
This is still a problem with the most recent oh-my-zsh version, and the fix in-place.

$echo `echo doh >> doh`
$cat doh
doh
doh

It also occurs with $():
$ rm doh
$(echo doh >> doh)
$ cat doh
doh 
doh

**Comment by mcornella** [comment]
That's just not the behavior I see. Please post the output of `setopt`.
