### ISSUE TITLE
-regex-match not available for regex

### ISSUE THREAD

**Issue by wolph** [ohmyzsh/ohmyzsh#227]
It seems that the FreeBSD version of ZSH compiles slightly different. I do have the `ZSH_PCRE` flag enabled but I still keep getting these errors:

```
title:3: failed to load module: zsh/regex
title:3: -regex-match not available for regex
```

I know I can disable it in `title`, but it looks like these regexes are integrated through the entire system so I'm not sure if that would help much.

I'm running:
- Zsh 4.3.10_4
- FreeBSD 7.2

**Comment by jerome-diver** [comment]
```
build_left_prompt:9: failed to load module `zsh/regex': Cannot open "/usr/local/lib/zsh/5.6.2/zsh/regex.so"                                                                                                          
build_left_prompt:9: -regex-match not available for regex
build_right_prompt:9: failed to load module `zsh/regex': Cannot open "/usr/local/lib/zsh/5.6.2/zsh/regex.so"
build_right_prompt:9: -regex-match not available for regex
```
this is happening on FreeBSD-12.1 when Synth try to use zsh for nextcloud
I miss-understand what i can do for fix the problem.

**Comment by jerome-diver** [comment]
@y2kbadbug thank you for your help. What is the "STATIC" use flag ? Where is this flag to remove from ?
