### ISSUE TITLE
Cannot create or switch to git branches with '#' symbol in branch name

### ISSUE THREAD

**Issue by jinmatt** [ohmyzsh/ohmyzsh#2284]
When I try to create or switch to a git branch which have a # symbol in its name, zsh gives the following error:

```
zsh: no matches found: iss#270
```

where `iss#270` is my branch name.

This is becoming extremely difficult for me since I work in a environment where issues are solved and pushed in this manner so they are automatically recognised and linked between the code review system and code repo.

**Comment by Isaiasdelahoz** [comment]
Try just wrapping the branch name with quotes ```git checkout "branch_name" ```

**Comment by lenary** [comment]
The correct fix is to either `unsetopt EXTENDED_GLOB` or, if you want the other features of extended globs but rarely use `#` as a glob character, `disable -p '#'` in your zshrc.

**Comment by biniyammoges** [comment]
adding git checkout 'your_branch_name' fixed mine
