### ISSUE TITLE
.ssh/config host autocompletion fails

### ISSUE THREAD

**Issue by binary132** [ohmyzsh/ohmyzsh#2288]
For every Host entry in my ~/.ssh/config file, when I do a tabbed autocompletion like the following:

(let's say the entry is "myhost")

ssh myh<tab>

The autocompletion becomes 

ssh myhost$'\r'

This does not work as it is not a known host in my ~/.ssh/config.

**Comment by dpatz** [comment]
I just did a clean install on my new Mac and I'm still having this issue. Was anybody ever able to resolve this? (Happens on both iTerm and Terminal)

**Comment by dpatz** [comment]
I finally managed to fix this. Add this to the bottom of your .zshrc file: https://superuser.com/a/1354860/37195

**Comment by wlonglade** [comment]
In my case it was just a line endind issue.
My ~/.ssh/config file contains "CRLF" (Windows style) lines ending. Switch to "LF" (Linux/Mac style) fixes the issue

**Comment by LukeTheProgrammer** [comment]
> In my case it was just a line endind issue. My ~/.ssh/config file contains "CRLF" (Windows style) lines ending. Switch to "LF" (Linux/Mac style) fixes the issue

Well... I won't get the hours back, but this is the solution. Thank you!!
