### ISSUE TITLE
Document $ZSH_CUSTOM

### ISSUE THREAD

**Issue by robbyrussell** [ohmyzsh/ohmyzsh#2295]
If someone has some time... can you write up a short tutorial on using $ZSH_CUSTOM for custom themes/plugins and toss that in the wiki for folks? It'd be great to direct folks to when they are curious about where to stick their custom themes going forward.

**Comment by EricSB** [comment]
I know this is a bit of an old issue so I apologize for adding a comment so late in the game, but wanted to say the content you added is fantastic!  The one thing I'd love to see added is perhaps an example of how to place custom aliases in the custom directory given it's mentioned in the .zshrc file.

Thanks in advance!
-Eric
