### ISSUE TITLE
Line Wrapping Bug

### ISSUE THREAD

**Issue by svkurowski** [ohmyzsh/ohmyzsh#2314]
First up: I guess this is a configuration problem and not a bug, yet I can't find out how to fix it.

When I write a long command (happens easily with longer git commit messages or long directory paths), the line wrapping does alot of unwanted things (the first line gets hidden, reverting the input places cursor at false place, so does going back in the command).

In ZSH without oh-my-zsh everything is working as intended.

I guess I'm really bad at describing this, so I created a [video](http://tinypic.com/r/205a980/5) to show you what is going on.
[This](http://pastebin.com/5hiVaURc) is the default oh-my-zsh configuration file shown in the video.

Environment details:
- Ubuntu 12.04
- zsh 5.0.2
- Newest oh-my-zsh (installed today)
- Accessed per SSH from my local iTerm2.app (Mac OS 10.9)
- Oh-My-Zsh works without any problems on local machine, just SSH'ing into the server starts those line wrapping problems

The OS etc was installed by the hoster of my virtual server, so I don't know If they changed something in comparison to a usual Ubuntu install, please tell me If you need any further information).

Thanks in Advance

**Comment by ncanceill** [comment]
@tam-vo, did you look into the `tmux` possibility mentioned above?

**Comment by arol** [comment]
I had the same problem and I solved it by wrapping with `%{…%}` the `ret_status` on the PROMPT.

`PROMPT='%{${ret_status}%} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'`

**Comment by kensupermen** [comment]
```bash
PROMT='%{${ret_status}%} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)' 
```
not reslove my problem. 
In Archlinux, I try edit like this:
```bash
PROMT="%{${ret_status}%} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)"
```
It's working, but have another problem, `promt` not show color

**Comment by bestreaction** [comment]
@arol Your solution worked for me.

**Comment by benoittgt** [comment]
Hello

I have also the issue. I have an edited sunrise theme.
```sh
# Sunrise theme for oh-my-zsh
# Intended to be used with Solarized: http://ethanschoonover.com/solarized

# Color shortcuts
R=$fg_no_bold[red]
G=$fg_no_bold[green]
M=$fg_no_bold[magenta]
Y=$fg_no_bold[yellow]
B=$fg_no_bold[blue]
RESET=$reset_color

if [ "$USER" = "root" ]; then
    PROMPTCOLOR="%{$R%}" PROMPTPREFIX="-!-";
else
    PROMPTCOLOR="" PROMPTPREFIX="%{ 🚴 %}";
fi

local return_code="%(?..%{$R%}%? ↵%{$RESET%})"

# Get the status of the working tree (copied and modified from git.zsh)
custom_git_prompt_status() {
  INDEX=$(git status --porcelain 2> /dev/null)
  STATUS=""
  # Non-staged
  if $(echo "$INDEX" | grep '^?? ' &> /dev/null); then
    STATUS="$ZSH_THEME_GIT_PROMPT_UNTRACKED$STATUS"
  fi
  if $(echo "$INDEX" | grep '^UU ' &> /dev/null); then
    STATUS="$ZSH_THEME_GIT_PROMPT_UNMERGED$STATUS"
  fi
  if $(echo "$INDEX" | grep '^ D ' &> /dev/null); then
    STATUS="$ZSH_THEME_GIT_PROMPT_DELETED$STATUS"
  fi
  if $(echo "$INDEX" | grep '^.M ' &> /dev/null); then
    STATUS="$ZSH_THEME_GIT_PROMPT_MODIFIED$STATUS"
  elif $(echo "$INDEX" | grep '^AM ' &> /dev/null); then
    STATUS="$ZSH_THEME_GIT_PROMPT_MODIFIED$STATUS"
  elif $(echo "$INDEX" | grep '^ T ' &> /dev/null); then
    STATUS="$ZSH_THEME_GIT_PROMPT_MODIFIED$STATUS"
  fi
  # Staged
  if $(echo "$INDEX" | grep '^D  ' &> /dev/null); then
    STATUS="$ZSH_THEME_GIT_PROMPT_STAGED_DELETED$STATUS"
  fi
  if $(echo "$INDEX" | grep '^R' &> /dev/null); then
    STATUS="$ZSH_THEME_GIT_PROMPT_STAGED_RENAMED$STATUS"
  fi
  if $(echo "$INDEX" | grep '^M' &> /dev/null); then
    STATUS="$ZSH_THEME_GIT_PROMPT_STAGED_MODIFIED$STATUS"
  fi
  if $(echo "$INDEX" | grep '^A' &> /dev/null); then
    STATUS="$ZSH_THEME_GIT_PROMPT_STAGED_ADDED$STATUS"
  fi

  if $(echo -n "$STATUS" | grep '.*' &> /dev/null); then
    STATUS="$ZSH_THEME_GIT_STATUS_PREFIX$STATUS"
  fi

  echo $STATUS
}

# get the name of the branch we are on (copied and modified from git.zsh)
function custom_git_prompt() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/}$(parse_git_dirty)$(git_prompt_ahead)$(custom_git_prompt_status)$ZSH_THEME_GIT_PROMPT_SUFFIX"
}

# %B sets bold text
PROMPT='%B$PROMPTPREFIX %c/ $(custom_git_prompt)%{$M%}%B»%b%{$RESET%} '
# RPS1="${return_code}"

ZSH_THEME_GIT_PROMPT_PREFIX="%{$Y%}‹"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$Y%}›%{$RESET%} "

ZSH_THEME_GIT_PROMPT_DIRTY="%{$R%}*"
ZSH_THEME_GIT_PROMPT_CLEAN=""

ZSH_THEME_GIT_PROMPT_AHEAD="%{$B%}➔"


ZSH_THEME_GIT_STATUS_PREFIX=" "

# Staged
ZSH_THEME_GIT_PROMPT_STAGED_ADDED="%{$G%}A"
ZSH_THEME_GIT_PROMPT_STAGED_MODIFIED="%{$G%}M"
ZSH_THEME_GIT_PROMPT_STAGED_RENAMED="%{$G%}R"
ZSH_THEME_GIT_PROMPT_STAGED_DELETED="%{$G%}D"

# Not-staged
ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$R%}?"
ZSH_THEME_GIT_PROMPT_MODIFIED="%{$R%}M"
ZSH_THEME_GIT_PROMPT_DELETED="%{$R%}D"
ZSH_THEME_GIT_PROMPT_UNMERGED="%{$R%}UU"
```

**Comment by dayuoba** [comment]
> ![screen shot 2014-11-30 at 1 35 22 pm](https://cloud.githubusercontent.com/assets/344684/5422519/e4237570-82b8-11e4-9619-ba82cdf2fa43.png)
> 
> I'm not sure how to reproduce that bug, but it's quite frequent to happen on my machine. Do you know how to resolve that bug?

i met same issue, how did you resolve it? thx

**Comment by jacdebug** [comment]
IMHO, `reset` command will fix in most cases.

**Comment by thomaskilian** [comment]
I reported a similar bug. Turns out, after uninstalling OMZ, that this is basically a ZSH issue.

**Comment by IdanCo** [comment]
This solved the issue for me -
https://github.com/zeit/hyper/issues/283#issuecomment-450988815
