### ISSUE TITLE
The pygmalion theme became odd since 4954335

### ISSUE THREAD

**Issue by richardtsai** [ohmyzsh/ohmyzsh#2317]
A two-year-old PR (#781) was merged recently (in 4954335b64e294923d64c4a9208e732bb9399268) and it makes the pygmalion theme odd especially in a wide terminal (e.g. guake). It limits the length of the prompt to 40 characters, which is improper in a normal terminal.

![example](http://ibin.co/14Fl2wtAs3S2)

**Comment by jounathaen** [comment]
This seems to be fixed as of today (I can't reproduce). I suggest closing the issue.

**Comment by robbyrussell** [comment]
We'll take your advice, @jounathaen. Thanks all

**Comment by dimensi0n** [comment]
Is it fixed ?
