### ISSUE TITLE
compdef: unknown command or service: rails after changing "rails3" plugin to "rails"

### ISSUE THREAD

**Issue by drakmail** [ohmyzsh/ohmyzsh#2337]
After changing rails3 to rails in my zshrc, I got this error:

```
compdef: unknown command or service: rails
```

PS. I'm using rbenv.

**Comment by jasonm23** [comment]
I'm getting this issue, have done 

```
rm -f ~/.zcompdump
compinit 
```

`compaudit` returns no output.

**Comment by jasonm23** [comment]
The offending lines are in `rails.plugin.zsh`

```
alias rails='_rails_command'
compdef _rails_command=rails
```

I don't know why though... (investigating.)

**Comment by magicalbanana** [comment]
@jasonm23 even figured it out? Trying to find out too but can't seem to make it work. Perhaps we should just remove it. :dancer:

**Comment by jasonm23** [comment]
I ended up removing it from my init.

**Comment by avstudio** [comment]
fix for me (rbenv)
rbenv rehash

**Comment by lynnegithub** [comment]
Thanks! @cmejo

**Comment by AlexVentura** [comment]
I'm working with `Rails 5.2.3` on `OS X Mojave 10.14.4` and this answer from @cmejo fixed the issue!

---

```
Fixed it by doing:

compaudit | xargs chmod g-w
compaudit | xargs chown root
rm -f ~/.zcompdump*; compinit

Any downsides to this method; am I okay permissions wise? Thanks!
``

**Comment by trejo08** [comment]
> On my machine at work `rm -f ~/.zcompdump*; compinit` fixed the issue. On my machine at home and on a colleagues machine that didn't help.

This command works fine for me
