### ISSUE TITLE
We need t-shirts

### ISSUE THREAD

**Issue by robbyrussell** [ohmyzsh/ohmyzsh#2343]
This is urgent.

**Comment by ryanhaney** [comment]
Reopening this issue.

![image](https://user-images.githubusercontent.com/1445619/36636585-3967e71e-197e-11e8-99b7-e02bdb140725.png)

**Comment by ryanhaney** [comment]
As a workaround, I've ordered this one for now.

![image](https://user-images.githubusercontent.com/1445619/36636639-604563a6-197f-11e8-9545-cfcb9cb8ae20.png)

**Comment by mcornella** [comment]
Please direct any further inquiries at https://twitter.com/ohmyzsh or at hello@planetargon.com making it clear in the subject that you're writing about the Oh My Zsh shop.

**Comment by robbyrussell** [comment]
Update: we have sizes available in L and XL, again.
