### ISSUE TITLE
Java completion painfully slow!

### ISSUE THREAD

**Issue by lindskogen** [ohmyzsh/ohmyzsh#2437]
I compiled a .java file with `javac Main.java`.

Next I typed `java M<TAB>` and then the prompt just froze. 2 minutes later it came back with all the java files in my home directory. I suspect this is a `zsh` bug?

**Comment by wiekern** [comment]
Has this bug been fixed? I have met this problem in zsh 5.1.1 (x86_64-apple-darwin15.0.0).

**Comment by NavinF** [comment]
Hey @robbyrussell, can we reopen this? Or is it a zsh bug?

Java completion is still painfully slow in any reasonably sized folder. The autocompleter should really give up after 100ms instead of hanging the shell.

**Comment by mcornella** [comment]
This is a bug in zsh's completion. I believe a workaround to that is prepending `./` to the filename, as to instruct the completion script to only complete files in the current directory. You'd have to test that though. 

You can also take a look at the [zsh mailing list](http://www.zsh.org/mla/) or ask yourself there for a fix.
