### ISSUE TITLE
changing zsrch file doesn't change anything in the terminal

### ISSUE THREAD

**Issue by Thermatix** [ohmyzsh/ohmyzsh#2461]
After moving from mac to Ubuntu, I want to use my favourite theme, the power-line one (yes, I have the fronts), but putting "'ZSH_THEME="agnoster"" doesn't do anything, I added "source "/etc/zsh/zshrc"" to my .profile following advice from: http://askubuntu.com/questions/132050/cant-change-theme-of-zsh-in-ubuntu-12-04?rq=1 but that doesn't do anything either. So what am I doing wrong? 
Also for future reference, since I can't seem to get themes working, what about plugins?

**Comment by victorurga** [comment]
I've got the same problem when I set a theme and run on the terminal `source ~/.zshrc` doesn't work at all, then I reboot my laptop but also it doesn't work.
I've searched a lot but I can't, Does anyone know why?

**Comment by hiroki-tkg** [comment]
@victorurga 
Hi, I could not refresh the setting of .zshrc. I searched and try all ways which i can imagine, but it doesn't work. I am using Mac. Did you fix this problem? :)
