### ISSUE TITLE
Cannot use zsh because of syntax error

### ISSUE THREAD

**Issue by ghost** [ohmyzsh/ohmyzsh#2527]
[sindhu@leh ~]$ source ~/.zshrc
bash: /home/sindhu/.oh-my-zsh/oh-my-zsh.sh: line 13: syntax error near unexpected token `('
bash: /home/sindhu/.oh-my-zsh/oh-my-zsh.sh: line 13:`for config_file ($ZSH/lib/*.zsh); do'

I just installed oh-my-zsh and when I source ~/.zshrc, I get the above error.

**Comment by webfd** [comment]
thanks

**Comment by chaliniu** [comment]
thanks alot

**Comment by mindcont** [comment]
thanks

**Comment by hellowords** [comment]
docker-compose exec -it workspace zsh
