### ISSUE TITLE
tmux not found

### ISSUE THREAD

**Issue by tanookiben** [ohmyzsh/ohmyzsh#2583]
I installed tmux with Homebrew and I added the tmux plugin to my zshrc file, but I get

```
zsh tmux plugin: tmux not found. Please install tmux before using this plugin.
```

which tmux returns

```
/usr/local/bin/tmux
```

Anything else I should check?

**Comment by mikeumus** [comment]
For any other troubled travelers that find themselves here, 
what worked for me was to uncomment the first `export` in `~/.zshrc`

```
 # If you come from bash you might have to change your $PATH.
 export PATH=$HOME/bin:/usr/local/bin:$PATH
```

🙇

**Comment by Youssef-Mak** [comment]
Some mac user might have the tmux binary stored in `/opt/homebrew/bin`, if that is the case then you should add that to the `PATH` in `~/zshrc` like this:

```
 # If you come from bash you might have to change your $PATH.
 export PATH=$HOME/bin:/usr/local/bin:/opt/homebrew/bin:$PATH
```
