### ISSUE TITLE
What does the yellow ballot sign ✗ mean?

### ISSUE THREAD

**Issue by 3rd3** [ohmyzsh/ohmyzsh#2623]
I just saw a yellow ballot sign next to the input prompt. I couldn’t find an explanation for what it is so I’m asking here.

**Comment by amir-m-sharabti** [comment]
> If your current directory is in a git repo, it indicates that it it isn't
> clean, eg: there are changes pending add/commit.
> 
> On Mon, Mar 17, 2014 at 2:39 PM, 3rd3 [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > I just saw a yellow ballot sign next to the input prompt and couldn't find
> > an explanation for what it is.
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/[/issues/2623](https://github.com/ohmyzsh/ohmyzsh/issues/2623)
> > .

Hi. i have a same problem and i according to your answer i just wanted to ask how to clean to make the yellow ballot appear?!

**Comment by mcornella** [comment]
Run `git status` for instructions.

**Comment by amir-m-sharabti** [comment]
> Run `git status` for instructions.



On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by mcornella** [comment]
What theme are you using?

**Comment by amir-m-sharabti** [comment]
> What theme are you using?

my problem got solved mate. thank you for your help

**Comment by sykul** [comment]
> > What theme are you using?
> 
> my problem got solved mate. thank you for your help

What was the solution?

**Comment by mcornella** [comment]
@sykul if you have this character it means there are changes in your git repo which should be visible by running `git status`.

In case you don't expect to be in a git repository, you can also see the root of the git repository with `git rev-parse --show-toplevel`.
