### ISSUE TITLE
New terminal tabs do not retain current directory (linux/ubuntu)

### ISSUE THREAD

**Issue by fearphage** [ohmyzsh/ohmyzsh#2887]
## Steps to repro
1. Open Terminal
2. Change directory (`cd ~/Downloads`)
3. Open a new tab (`ctrl-T`)
## Expected Results

New tab is opened from current directory (`~/Downloads`).
## Actual Results

New tab opens in home directory (`~`).

This affects all directories (git and otherwise). I'm using Ubuntu 14.04 although I saw similar behavior in 13.10.

Related to #1489, #1527, #2646. I've checked these issues, but all they all seem to be OS X specific.

**Comment by abhisheksoni27** [comment]
I am using `Ubuntu 17.04` and this problem is still there.

**Comment by XeniaSiskaki** [comment]
Issue is still there in Ubuntu 18.04 LTS

**Comment by XeniaSiskaki** [comment]
None of these worked for me

**Comment by fearphage** [comment]
I've been using that solution for 4 years now and I'm also on Ubuntu 18.04 currently. Have you tried moving that line earlier or later in your `.zshrc`? Also keep in mind that you have to make the change, source the updated file, and then open a new tab for it to take effect.

**Comment by mcornella** [comment]
Are there any vte files in `/etc/profile.d`?

**Comment by XeniaSiskaki** [comment]
@mcornella 
```
-rw-r--r-- 1 root root 1.9K Apr 10 19:58 vte-2.91.sh
lrwxrwxrwx 1 root root   26 Aug 31 16:19 vte.sh -> /etc/profile.d/vte-2.91.sh
```
@fearphage The only thing I didn't try was moving the line. I put it in the end

**Comment by mcornella** [comment]
You seem to have the file, I assume you're using gnome-terminal? If so, maybe there's a bug in there? What are the contents of `/etc/profile.d/vte.sh`?

**Comment by XeniaSiskaki** [comment]
@mcornella I'm using the [terminator terminal](https://gnometerminator.blogspot.com/p/introduction.html).  Here are the contents of `/etc/profile.d/vte-2.91.sh`

```
# Copyright © 2006 Shaun McCance <shaunm@gnome.org>
# Copyright © 2013 Peter De Wachter <pdewacht@gmail.com>
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Not bash or zsh?
[ -n "$BASH_VERSION" -o -n "$ZSH_VERSION" ] || return 0

# Not an interactive shell?
 $- == *i*  || return 0

# Not running under vte?
[ "${VTE_VERSION:-0}" -ge 3405 ] || return 0

__vte_urlencode() (
  # This is important to make sure string manipulation is handled
  # byte-by-byte.
  LC_ALL=C
  str="$1"
  while [ -n "$str" ]; do
	safe="${str%%[!a-zA-Z0-9/:_\.\-\!\'\(\)~]*}"
	printf "%s" "$safe"
	str="${str#"$safe"}"
	if [ -n "$str" ]; then
	  printf "%%%02X" "'$str"
	  str="${str#?}"
	fi
  done
)

# Print a warning so that anyone who's added this manually to his PS1 can adapt.
# The function will be removed in a later version.
__vte_ps1() {
  echo -n "(__vte_ps1 is obsolete)"
}

__vte_osc7 () {
  printf "\033]7;file://%s%s\007" "${HOSTNAME:-}" "$(__vte_urlencode "${PWD}")"
}

__vte_prompt_command() {
  local pwd='~'
  [ "$PWD" != "$HOME" ] && pwd=${PWD/#$HOME\//\~\/}
  printf "\033]0;%s@%s:%s\007%s" "${USER}" "${HOSTNAME%%.*}" "${pwd}" "$(__vte_osc7)"
}

case "$TERM" in
  xterm*|vte*)
	[ -n "$BASH_VERSION" ] && PROMPT_COMMAND="__vte_prompt_command"
	[ -n "$ZSH_VERSION"  ] && precmd_functions+=(__vte_osc7)
	;;
esac

true
```

**Comment by XeniaSiskaki** [comment]
I'm sorry for the noise. It is working indeed. I had a `cd` at the end of my `.zshrc` which was overriding the current directory I guess

**Comment by mcornella** [comment]
No worries
