### ISSUE TITLE
Add junegunn's fzf to plugins.

### ISSUE THREAD

**Issue by hoshsadiq** [ohmyzsh/ohmyzsh#3003]
It allows for `ctrl+r` to use fuzzy search and `ctrl+t` does fuzzy autocompletion: https://github.com/junegunn/fzf

**Comment by chenglou** [comment]
:+1: such a great plugin

**Comment by kalimar** [comment]
You can copy the .fzf.zsh file in your root directoyr into your .oh-my-zsh/custom/plugins folder.

**Comment by hoshsadiq** [comment]
Yup I know, I'm already using it, but I'm saying it should be part of `oh-my-zsh`

**Comment by uvaes** [comment]
Agreed! It would be great to add it!

**Comment by jchris** [comment]
I just started using it and it is dope. I would love to have it running on the bottom 5 to 10 lines of my shell by default, whenever I'm typing.

**Comment by diego898** [comment]
:+1:

**Comment by qwIvan** [comment]
:+1:

**Comment by simonbcn** [comment]
Same petition  :-1:

**Comment by oc243** [comment]
👍

**Comment by PMarci** [comment]
+1 👍

**Comment by maxbrunet** [comment]
Hello there, I opened the PR #6910 to add a `fzf` plugin.
As per the [contributing guidelines](https://github.com/robbyrussell/oh-my-zsh/blob/master/CONTRIBUTING.md#you-have-an-addition), it'll need +1 from testers.

**Comment by bjuergens** [comment]
This might be a stupid questions, but can anyone be a tester (e.g. me)?
