### ISSUE TITLE
Cygwin upgrade_oh_my_zsh broken

### ISSUE THREAD

**Issue by andrewpsy** [ohmyzsh/ohmyzsh#3079]
andrew@Win8  ~   $ upgrade_oh_my_zsh
Upgrading Oh My Zsh
: No such file or directory/upgrade.sh: line 2: cd: /home/andrew/.oh-my-zsh
/home/andrew/.oh-my-zsh/tools/upgrade.sh: line 17: syntax error: unexpected end of file

**Comment by tombujok** [comment]
If you want to have the global config core.autocrlf=true (it's recommended on cygwin) the following solution works too:
```
cd ~/.oh-my-zsh
git config core.trustctime false
git config core.autocrlf false
git rm --cached -r .
git reset --hard
````
