### ISSUE TITLE
 zsh: no matches found: -?

### ISSUE THREAD

**Issue by To1ne** [ohmyzsh/ohmyzsh#31]
Well, this is a real weird issue, and there might not be a solution to it.

Our VCS at work uses the parameter `-?` to get help.
But when in `zsh` when I type:
    vcsapp -?
I get the error:
    zsh: no matches found: -?

I know `zsh` interprets the `?` as a wildcard, which is good. But this one time it isn't.

**Comment by yianemail** [comment]
well. when i try "git add *.java" or "ga *.java"
it's doesn't work and remind "zsh: no matches found: *.java"
any result for this error ?

**Comment by christoga** [comment]
Man, I was in shock when I saw this issue was created on 2009

**Comment by jeeftor** [comment]
Just had this issue now - it should be fixed - i don't think you'd ever glob with curl would you?

**Comment by amukiza** [comment]
Happens with `mongo mongodb://localhost/my_db`  as well.

**Comment by arukavytsia** [comment]
This issue is reproducible with `curl` - I launched from zsh next command: ` curl -H "Content-type: application/json" http://localhost:8100/myendpoint` and it falls with `zsh: no matches found: http://localhost:8100/myendpoint` when I launched same in usual bash, it works, as it should.

**Comment by ctron** [comment]
You can also disable to `nomatch` handling and fixing this for all commands by adding the following to your `~/.zshrc`:

~~~
unsetopt nomatch
~~~

**Comment by MinerChAI** [comment]
How to make noglob work with sudo?

**Comment by ecbaldwin** [comment]
> How to make noglob work with sudo?

Zsh should look for matches before invoking sudo. So, preceding sudo with `noglob` should work.

```
❯ sudo echo *foo*
zsh: no matches found: *foo*
❯ noglob sudo echo *foo*
*foo*
```

**Comment by NightMachinary** [comment]
[**@ctron**](https://github.com/ctron) commented on [Jan 23, 2018, 12:48 PM GMT+3:30](https://github.com/ohmyzsh/ohmyzsh/issues/31#issuecomment-359728582 "2018-01-23T09:18:50Z - Replied by Github Reply Comments"):
> You can also disable to `nomatch` handling and fixing this for all commands by adding the following to your `~/.zshrc`:
> 
> ```
> unsetopt nomatch
> ```

What does this do exactly?

**Comment by comming-soon-official** [comment]
on zsh terminal it dosen't works
sudo apt-get remove --purge nvidia*

zsh: no matches found: nvidia*
but in bash terminal it works fine can u guys say what is the problem with zsh

**Comment by comming-soon-official** [comment]
on zsh terminal it dosen't works
sudo apt-get remove --purge nvidia*

zsh: no matches found: nvidia*
but in bash terminal it works fine can u guys say what is the problem with zsh
