### ISSUE TITLE
aws completion broken in latest release

### ISSUE THREAD

**Issue by MWers** [ohmyzsh/ohmyzsh#3100]
The commit f49220732904ed254400f14e621ea5ebe9e4a5f5 breaks aws cli completion for OSX users who have `awscli` and `brew` installed (but who did not install `awscli` via `brew`). This is the error I receive whenever I open a zsh shell:

`/Users/matt/.oh-my-zsh/plugins/aws/aws.plugin.zsh:source:27: no such file or directory: /usr/local/opt/awscli/libexec/bin/aws_zsh_completer.sh`

I've fixed this and submitted a pull request here:  

https://github.com/robbyrussell/oh-my-zsh/pull/3092

Thanks!

**Comment by abdennour** [comment]
The same error has appeared even I am using brew awscli. 2018-03-08
