### ISSUE TITLE
Can I change zsh to default shell when zsh is installed without root privilege?

### ISSUE THREAD

**Issue by peiyun** [ohmyzsh/ohmyzsh#3269]
I just installed zsh from source and want to make it my default shell. Since I do not have administrative privileges, I wonder if I could make it. 

Besides, if I use the tab-completion after typing in `$ chsh -s`, there is only options under `/bin/` and `/usr/bin/`. While, when I try to execute `chsh -s /home/phu/zsh/build/bin/zsh`, it says `chsh: /home/phu/zsh/build/bin/zsh is an invalid shell`. 

I did not find related instructions using Google. So I decided to give a try here. 

Thanks !

**Comment by zxdawn** [comment]
@peiyun @mcornella After adding `exec /path/to/zsh -l` to .profile, I got this when type `export ZSH="/path/to/oh-my-zsh"; sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"`:
```
Zsh is not installed! Please install zsh first!
```
Did you get this problem?

**Comment by mcornella** [comment]
@zxdawn the current installer fixed that issue.
