### ISSUE TITLE
ps1_fortune:2: command not found: fortune , use random theme

### ISSUE THREAD

**Issue by tomoat** [ohmyzsh/ohmyzsh#3271]
[oh-my-zsh] Random theme '/Users/tomato/.oh-my-zsh/themes/adben.zsh-theme' loaded...
ps1_fortune:2: command not found: fortune

**Comment by azulkipli** [comment]
I do as tomoat said, it is work

**Comment by hg8** [comment]
On Ubuntu : 

     sudo apt-get install fortune-mod

**Comment by jiangyewen** [comment]
what is fortune anyway?

**Comment by sunofsparda** [comment]
@jiangyewen it displays random text quotes on the command line
https://wiki.archlinux.org/index.php/Fortune
