### ISSUE TITLE
gcp executable collides with git cherrypick on autocomplete

### ISSUE THREAD

**Issue by m4l** [ohmyzsh/ohmyzsh#3272]
I have gcp installed:

```
sudo apt-get install gcp
```

which seems to collide with an zsh alias for git cherrypick.
I added "unalias gcp" to my .zshrc but when I type gcp and hit tab I still get scrambled output like:

```
[~]$ gcp zsh:12: command not found: __git-cherry-pick_main
 gcp
```

Sounds similar to #2095 but I don't have an alias for gcp.

**Comment by erikr** [comment]
Same issue; not ideal choice of alias.

`compdef -d gcp` did not work.

What worked for me is adding `unalias gcp` to my `~/.zshrc`.
