### ISSUE TITLE
Esc don't escape on tab completion menus

### ISSUE THREAD

**Issue by mhalano** [ohmyzsh/ohmyzsh#3287]
When I'm using tab completation for some command, sometimes I want to exit the menu and go back to the prompt. The only way I found is using ctrl-c. There's some option to use ESC key to escape tab completion menu?

**Comment by franzhuang** [comment]
It doesn't work for me.
What works for me is (just modified a little):

bindkey -M menuselect '\e' send-break

thank you

**Comment by silverqx** [comment]
Would be nice to have workaround for this, `bindkey '\e' send-break` is the same like ctrl+c, much better would be to only hide the autocomplete menu. But I don't know how to do that. :/
