### ISSUE TITLE
Permission denied when accessing .zshrc

### ISSUE THREAD

**Issue by kinsomicrote** [ohmyzsh/ohmyzsh#3291]
I just started using ubuntu last week Friday and i installed oh-my-zsh yesterday. I am learning Ruby and i need to set environment variables. Some links i found on google stated i access .zshrc but i get permission denied. How do i got about it?

Thanks.

**Comment by patomation** [comment]
Ha ha I was doing the same thing until I realize that I forgot to give it an editor command.

$ vim ~/.zshrc

**Comment by themerchantoff** [comment]
Patomation, Thank you! I also wasn't accessing with the editor comand.

**Comment by Ronaldoh1** [comment]
@patomation money!

**Comment by jpcmf** [comment]
Why I can't change .zshrc to .bashrc or vice versa using the command line?
```
➜  ~ ~/.bashrc
zsh: permission denied: /Users/joaopaulo/.bashrc
```
```
➜  ~ ~/.zshrc
zsh: permission denied: /Users/joaopaulo/.zshrc
```

**Comment by Chris-1101** [comment]
@jpcmf by typing the path without prefixing it with another command, your shell assumes you want to execute it. For that, the file would need to have its execute permission set (+x). If it doesn't, you'll get a permission denied message.

Neither `.bashrc` nor `.zshrc` are meant to be executed, so it makes sense for them not to be executable. They are instead sourced by their respective shells when they're run. This happens automatically.

---
To interactively swap between shells, which is what I'm assuming you mean by "change .zshrc to .bashrc", just type the command for that shell.
```
# we're in z-shell
$ bash
# we are now in bash
$ exit
# back in z-shell
```

PS: That's not the same as changing your default shell. To do that, look up the `chsh` command.

**Comment by ashish8796** [comment]
I m a beginner of learning python. I m using ubuntu 19.04. i m using z shell instead of bash shell. i downloaded anaconda3 through terminal. but the conda  init command not running. When i m trying ~/.zshrc it is showing this:   ~ ~/.zshrc          
zsh: permission denied: /home/ashish/.zshrc

Please help me

**Comment by mcornella** [comment]
You have to run zsh, not the zshrc file directly.

**Comment by Chris-1101** [comment]
Given that the error he's getting is prefixed with `zsh: `, his terminal must already be running it.

@ashish8796, I don't have any experience with anaconda, but from [one of the guides][1] I read, I suspect you might be trying to _source_ `.zshrc`? If so, you don't want to just type the path in the terminal, that just tries to execute it (see my previous reply here), the command for that would be `source ~/.zshrc`.

If not, [this SO question][2] might be what you need ¯\\\_(ツ)_/¯

ps: in Linux, a dot `.`, when used as a command, is an alias for `source`. If you were following a guide you might have missed it when they told you to run `. ~/.zshrc` which would also work.

[1]: https://www.digitalocean.com/community/tutorials/how-to-install-anaconda-on-ubuntu-18-04-quickstart
[2]: https://stackoverflow.com/questions/40370467/anaconda-not-found-in-zsh

**Comment by mcornella** [comment]
Great reply :+1:

**Comment by gmsmerch** [comment]
[!] There was an error parsing `Gemfile.local`: You cannot specify the same gem twice coming from different sources.                                           You specified that network_interface (>= 0) should come from an unspecified source and https://github.com/timwr/network_interface.git (at master)              . Bundler cannot continue.                                                                                 #  from /data/data/com.termux/files/home/metasploit-framework/Gemfile.local:30                            #  -------------------------------------------       #  group :local do                                   >    gem 'network_interface', :git => "https://github.com/timwr/network_interface.git", :branch => "master"                                                    #  end                                               #  -------------------------------------------


What I need to do???

**Comment by initiator26** [comment]
> ls -l $HOME/.zshrc

<img width="562" alt="Screenshot 2021-12-28 at 10 11 04 AM" src="https://user-images.githubusercontent.com/91682476/147528948-f1b46505-081f-4d9c-b405-e1e8d317ee59.png">

**Comment by rwmitchell** [comment]
You used root to install OMZ, just change the owner back to yourself

**Comment by smitpatel0305** [comment]
I am unable to change cd. I am using Mac tried to allowed permission from setting but didn't workout. 
Last login: Fri Feb  4 20:28:46 on ttys001
smitpatel@Smits-MacBook-Pro ~ % cd
smitpatel@Smits-MacBook-Pro ~ % /Users/smitpatel/Desktop/CS214
zsh: permission denied: /Users/smitpatel/Desktop/CS214
smitpatel@Smits-MacBook-Pro ~ %

**Comment by rwmitchell** [comment]
I'm a little unclear on what is going on.

It appears you ran 'cd' from your home directory and it left you in your home directory.  'cd'ing without an argument is a common default for going back to $HOME.

You then entered '/Users/smitpatel/Desktop/CS214' and got permission denied.'

It isn't clear, but I'm assuming CS214 is subdirectory?

Does the output of ```setopt``` show 'autocd' ?

If it doesn't, then you should have entered ```cd /Users/smitpatel/Desktop/CS214```

Although since you were already in your home directory ```cd Desktop/CS214``` would have been shorter.

if you set ```setopt autocd``` then it should have worked without the 'cd'.
