### ISSUE TITLE
git_custom_status:1: command not found: current_branch  

### ISSUE THREAD

**Issue by suryagaddipati** [ohmyzsh/ohmyzsh#331]
I added git plugin to my zshrc and removed it after a while and i started getting this.

**Comment by v6** [comment]
// , I keep getting this problem, too.

**Comment by v6** [comment]
// , My problem comes from the "gallois" theme. 

Maybe this is starting to get some cruft?

**Comment by AClavijo** [comment]
Hi,
Same problem with de "gallois" theme.

**Comment by v6** [comment]
// , Is this problem actually fixed?

**Comment by mcornella** [comment]
Yes, it was fixed in #4420.

**Comment by v6** [comment]
// , Well, then! 

I may actually start using this again.
