### ISSUE TITLE
"~/.oh-my-zsh/lib/spectrum.zsh:6: you have running jobs."

### ISSUE THREAD

**Issue by ThomasAdam** [ohmyzsh/ohmyzsh#332]
Hi,

Having installed Robby Russell's oh-my-zsh, every time I open a terminal
(i.e., launch a login shell), I see the following:

[4] 6039
/global/users/thomas/.oh-my-zsh/lib/spectrum.zsh:6: you have running jobs.
[4]  + 6039 done       typeset -Ag FX FG

Any ideas why this might be?  This is a default install of your
oh-my-zsh -- the only thing I've done is changed my theme to
"eastwood" in ~/.zshrc

Should it matter (and from my cursory glance at what this spectrum.zsh
file does, it might), I am launching a login shell of zsh via tmux
each time -- hence, my TERM is set to "screen-256color" -- and from a
quick glance at this script, it seems to try and make 256 colours
easier on the eye?

**Comment by dbitouze** [comment]
Issue still present with an up to date `oh-my-zsh`, namely each time I open a new session, I get something like:
```
Linux drums-bis 5.18.3-desktop-1.mga8 x86_64
[6] 3694939
/home/bitouze/.oh-my-zsh/lib/spectrum.zsh:5: you have running jobs.
[6]  + 3694939 done       typeset -AHg FX FG
```
