### ISSUE TITLE
two repeated characters before command when using tab completion

### ISSUE THREAD

**Issue by yittg** [ohmyzsh/ohmyzsh#3368]
when i use tab completion， two characters will appear before command line like moving to right

for example:

```
    ➜  xxx  
    ➜  xxx  ls
    a  b  c
```

when i input `./` and then `tab`, i got this

```
    ➜  xxx  ././
    a*  b*  c*
```

**Comment by Freyskeyd** [comment]
LC_CTYPE doesn't work for me... Any other suggestion? :/

**Comment by mcornella** [comment]
Can you post the output of `locale`?

**Comment by steadystatic** [comment]
I'm still having this issue, output of `locale`:

LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
