### ISSUE TITLE
no such file or directory error

### ISSUE THREAD

**Issue by gshankar** [ohmyzsh/ohmyzsh#35]
Hi,

I uninstalled using uninstall_oh_my_zsh but I keep getting this error in my terminal now:

Last login: Tue Feb 16 10:14:05 on ttys000
/Users/gshankar/.zshrc:source:17: no such file or directory: /Users/gshankar/.oh-my-zsh/oh-my-zsh.sh

My other errors also look like this:
zsh: no such user or named directory:

Any idea how to fix this? I also seem to have lost some of the custom formatting options I specified in ~/.profile (in fact I can't seem to open my profile file anymore either...)

**Comment by MarcSteven** [comment]
@robbyrussell But now the issue is still existing. Can you have solutions to solve it simply?
