### ISSUE TITLE
[IDEA] Auto-gen TOC for wiki pages like Plugins, using MediaWiki

### ISSUE THREAD

**Issue by apjanke** [ohmyzsh/ohmyzsh#3699]
What do folks think about making auto-generated Table of Contents for the [Plugins wiki page](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins) and similar wiki pages, by switching their page markup format to MediaWiki?

This would make it easier to find plugins and topics in the page. There's no auto-TOC functionality in Markdown, but if we converted the page to MediaWiki format (or one of a couple others), there's (unofficial) support for auto-TOC generation. I think this would be useful for [Themes](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes), [Coding Style Guide](https://github.com/robbyrussell/oh-my-zsh/wiki/Coding-style-guide) and maybe a couple other longer pages that have either long (>7) lists of items or complicated topic structures.

It would look like this: https://github.com/apjanke/omz-scratch/wiki/Plugins  – that's a quick mockup of a conversion to MediaWiki I did using `pandoc` and a little hand-adjustment. The conversion isn't perfect: in particular, there's an issue with displaying '`<`' or '`&`' inside code blocks. But if folks are interested in this, I bet that could be solved with a bit of investigation.

You can manually construct a TOC in Markdown, and there are tools like `tocdoc` that will help, but those aren't automatically updated if the rest of the content changes, and you need to manually splice the TOCs in to the full page. Fully automatic TOCs generated on the fly sound a lot more useful and reliable to me. And there's been [long-standing interest for support in Markdown](https://github.com/isaacs/github/issues/215), but I doubt that will happen any time soon.

**Comment by robbyrussell** [comment]
@apjanke sorry that this has lingered for so many years. Given that we have READMEs for all the projects, I think the approach of linking people to the repo's /plugins directory gets us to a place where people can explore. We'll close this for now

**Comment by apjanke** [comment]
Sounds good to me.
