### ISSUE TITLE
problem with multi-line prompts and vi-mode plugin

### ISSUE THREAD

**Issue by mgrubb** [ohmyzsh/ohmyzsh#387]
I'm a new to both zsh and oh-my-zsh.  I was working with a multi-line prompt:
```PROMPT='%m %~

> '
> 
>
```

I also had the vi-mode plugin enabled.  However, when I go into command mode by pressing Esc it eats the last line of output from the previous command.  I've tracked the problem down to the line in the plugin file: `zle -N zle-keymap-select`
I'm using zsh version 4.3.9 (the one that ships with Mac OS X 10.6).

**Comment by bezhermoso** [comment]
This is still happening to me with my multi-line prompt setup.

**Comment by justmytwospence** [comment]
[This line] (https://github.com/justmytwospence/dotfiles/blob/master/home/.zshrc#L175) fixed it for me, @bezhermoso. Maybe it will work for you if you are modifying zle-keymap-select or zle-line-init.

**Comment by bezhermoso** [comment]
Unfortunately it doesn't fix it, @justmytwospence. I'm just using the `vi-mode` plugin which has that fix but still having the problem.

**Comment by bezhermoso** [comment]
@justmytwospence Even an empty definition like this cause the same thing:

```
function zle-line-init zle-keymap-select {
  zle reset-prompt
  zle -R
}
```

Thoughts?

**Comment by justmytwospence** [comment]
I'm honestly in over my head with this stuff, sorry.

On Tue, Oct 27, 2015 at 8:06 PM, Bez Hermoso < notifications@github.com [notifications@github.com] > wrote:
@justmytwospence [https://github.com/justmytwospence] Even an empty definition like this cause the same thing:

function zle-line-init zle-keymap-select {
  zle reset-prompt
  zle -R
}


Thoughts?

—
Reply to this email directly or view it on GitHub
[https://github.com/robbyrussell/oh-my-zsh/issues/387#issuecomment-151707788] .[https://github.com/notifications/beacon/ACr-lk0c8nGkPUuq3chKMbK6zZzITQUDks5pADM_gaJpZM4AS2es.gif]
