### ISSUE TITLE
pip plugin completion should support multi -r argument

### ISSUE THREAD

**Issue by jeffrey4l** [ohmyzsh/ohmyzsh#3881]
the pip command support multi `-r` argument. like bellow

```
pip install -r requirements.txt -r test-requirements.txt
```

But the completion doesn't support that.

**Comment by ncanceill** [comment]
CC to: @robbyrussell (listed maintainer) @mrtazz (first committer) @wjlroe (author of c9c021478ea4a2b55aac8cda3cd0d05137443f36)

**Comment by mcornella** [comment]
`pip` completion should be available through the command itself, maybe we should make the plugin use that instead. See [command line completion docs](http://pip.readthedocs.org/en/0.6.1/#command-line-completion).

**Comment by robbyrussell** [comment]
We'll close this given how long it's been pending more details for quite some time.
