### ISSUE TITLE
Status Line Prompt

### ISSUE THREAD

**Issue by betawaffle** [ohmyzsh/ohmyzsh#394]
A few days ago, I got tired of my multi-line prompt, so I decided to try and add a status line (three lines actually) to my prompt. It sits at the bottom of the window and actually works quite well. However, in some cases it's not very reliable, and in others it breaks completely (when I use `less`).

Does anyone know if it's possible to do this well? I would like to see a good way to do this in our theme system.

Thoughts?

The way I'm doing right now is _extremely_ hacky. If you want to take a look at the [code](/betawaffle/oh-my-zsh/blob/custom/themes/betawaffle.zsh-theme), do so at your own risk!

Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/1441704/15754758/08b772fe-28fa-11e6-9989-cb91e2721043.png)

**Comment by sigmap** [comment]
I would have liked to see the work to be able to play with it because I've been looking for something like that.
