### ISSUE TITLE
zsh: no matches found

### ISSUE THREAD

**Issue by rajbeniwal** [ohmyzsh/ohmyzsh#433]
I got this message every time i ran my rake task.

zsh: no matches found: live:debug:cucumber:feature[features_file]

works fine in bash.

Any idea?

**Comment by sadfuzzy** [comment]
thanks!

**Comment by kelabang** [comment]
wow, thats working.. thanks

**Comment by kanavmalhotra** [comment]
on executing below command: 
nfs share -o anon=root,sec=sys,rw=*,ro=@172.17.111.63 p-C163616-cli/f-C163616-cli
I get the following error:
zsh:1: no matches found: anon=root,sec=sys,rw=*,ro=@<ip>
pls help?

**Comment by mcornella** [comment]
@kanavmalhotra quote the arguments so that `@` is not interpreted as [a globbing character](http://zsh.sourceforge.net/Intro/intro_2.html), which are used to pattern-match files.

```zsh
nfs share -o "anon=root,sec=sys,rw=,ro=@172.17.111.63" p-C163616-cli/f-C163616-cli
```

**Comment by kajatiger** [comment]
When I run 
`bundle exec rake plugin:spec["discourse-sync-*"]` 
I get 
`zsh: no matches found: plugin:spec[discourse-sync-*]`
although I added 
`alias rake="noglob bundle exec rake"`

**Comment by jpcmf** [comment]
I love zsh, but im getting some ridiculous error and i don't know where and how fix it 
When I run `➜  ~ sudo apt-get remove --purge *mysql\*`
zsh return `zsh: no matches found: *mysql*`

**Comment by mcornella** [comment]
@jpcmf quote the asterisks or zsh will try to expand the argument to files whose name contains mysql. Any parameter that contains `*`, `?` or other globbing chars have to be quoted.

**Comment by rodnertj** [comment]
um pouco tarde, mas funcionou pra mim, adicione esse cara no .zshrc:
unsetopt nomatch

**Comment by schinery** [comment]
Even later... you can also wrap the rake task call in single quotes and run using a regular rake call, like so:

```sh
rake 'my:task[var1,var2]'
```

The downside to this is that it will treat all your passed variables as strings.

**Comment by pabloamco** [comment]
@schinery This worked perfectly for me, thanks a lot!

**Comment by kixarinum** [comment]
@schinery yep, this also worked for me, thanks!

**Comment by mcornella** [comment]
If you need to pass in variables, use double quotes (`"`). Locking the issue since it's been resolved for a while.
