### ISSUE TITLE
gitfast is GPL

### ISSUE THREAD

**Issue by apjanke** [ohmyzsh/ohmyzsh#4413]
Some of the code in the `gitfast` plugin is GPL (GNU Public License). 

[git-prompt.sh](https://github.com/robbyrussell/oh-my-zsh/blob/b05ef1034fffd7b0c29f1558a8a357ccce7ae74b/plugins/gitfast/git-prompt.sh#L3-L4)

```
# Copyright (C) 2006,2007 Shawn O. Pearce <spearce@spearce.org>
# Distributed under the GNU General Public License, version 2.0.
```

[git-completion.bash](https://github.com/robbyrussell/oh-my-zsh/blob/b05ef1034fffd7b0c29f1558a8a357ccce7ae74b/plugins/gitfast/git-completion.bash#L3-L5)

```
# Copyright (C) 2006,2007 Shawn O. Pearce <spearce@spearce.org>
# Conceptually based on gitcompletion (http://gitweb.hawaga.org.uk/).
# Distributed under the GNU General Public License, version 2.0.
```

[_git](https://github.com/robbyrussell/oh-my-zsh/blob/b05ef1034fffd7b0c29f1558a8a357ccce7ae74b/plugins/gitfast/_git#L5)

```
# Copyright (c) 2012-2013 Felipe Contreras <felipe.contreras@gmail.com>
```

This is incompatible with the MIT License that Oh My Zsh is licensed under. Looks like this code should be pulled, or we should add a mechanism and doco about including code using other licenses.

Most of the stuff in `gitfast` appears to simply be a copy of the completion code shipped with the `git` distribution itself. (E.g. in my Homebrew-managed `git`, similar files are installed to `/usr/local/share/zsh/site-functions`.) You could probably change the plugin to load it from the `git` installation on the local machine instead of carrying the code around in OMZ, which would fix the licensing issue.

**Comment by felipec** [comment]
I'm the author of the `_git` script from Git anyway, and I don't have any problem with using an MIT license.

The other two are a problem.

The `git-completion.bash` script isn't actually needed, we could use whatever is installed in `/usr/share/bash-completion`. I'm fine with deleting it. I only put it in gitfast so we could have the latest that is actually tested.

But `git-prompt.sh` is trickier, because there is no standardized way of distributing such scripts. If this is a big deal we could ask the main authors if the file could be relicensed. I'm the main author, but there's at least one other.

**Comment by robbyrussell** [comment]
I'm going to "close" this for now as I will wait until one of the authors asks us to no longer distribute it. If someone has a good idea on how to sort this out, I'd welcome advice!

**Comment by apjanke** [comment]
That sounds reasonable.

I think my original concern here may have been overblown anyway. The GPL is incompatible with the MIT license in general, but in the specific way OMZ is using it, it may be fine? OMZ is shipped as source and not binary, and all the source for it and its components is available. So you're complying with the GPL's "must supply source code" part, and I dunno if this counts as "linking" code in a way that would require the rest of the code to be GPL-licensed per the GPL's "viral" mechanism. Might only be an issue if someone wants to further redistributed OMZ as a packaged binary? Question for a lawyer, not me.

My guess is it's 99% likely you'll never hear about this problem again. I'd still lean toward putting a one-line "some of the code redistributed with OMZ is under other Open Source licenses; see it for details" notice in the README's "License" section, for full disclosure.
