### ISSUE TITLE
zsh: no matches found: HEAD^

### ISSUE THREAD

**Issue by adamstac** [ohmyzsh/ohmyzsh#449]
When I run this git command, `git reset --soft HEAD^` I get this back `zsh: no matches found: HEAD^`

I have these plugins in place `plugins=(brew bundler git osx rails3 ruby textmate)`

**Comment by suniakalra** [comment]
Yes this line fixed the issue.. thanks

**Comment by cdekok** [comment]
Shouldn't this be the default behaviour ? took me some time to find the setopt NO_NOMATCH

**Comment by ZHThinker** [comment]
sweet! @nickmeharry
