### ISSUE TITLE
MVN plugin : -f doesn't filepath complete

### ISSUE THREAD

**Issue by wattazoum** [ohmyzsh/ohmyzsh#4590]
Hi, 

when using maven to build a project in a different folder than the current, one can use `-f path/to/pom.xml`. 
ZSH does't complete the path.

**Comment by apjanke** [comment]
Looks like our Maven completion definitions don't define completions for any of the arguments to `-f` and the other switches.

There are what look like more robust versions of `mvn` completion as part of the `zsh-completions` project (`_mvn` [here](https://github.com/zsh-users/zsh-completions/blob/master/src/_mvn)) and in [this dedicated `mvn` completion project](https://github.com/Echos/maven-zsh-completion). We might want to switch to supporting one of those.

**Comment by victornoel** [comment]
Yes, it would be great, because the current mvn plugins is really weak compared to the one for bash…

It can't complete submodules with -pl for example too… (actually, the one  from zsh-completions can't either…).

**Comment by wsdjeg** [comment]
i have install zsh completion 
and add 
plugins+=(zsh-completions)
autoload -U compinit && compinit

into my zshrc but still can not complete file path mvn -f

**Comment by alexeyts** [comment]
Same goes for `-s settings.xml` option too.

**Comment by robbyrussell** [comment]
⌛️ Closing due to how long this has been open. Happy to revisit if there is someone to help us build momentum on it. Sorry for not getting to it back in the day!
