### ISSUE TITLE
Vagrant plugin: completion for multiple boxes

### ISSUE THREAD

**Issue by sander-bol** [ohmyzsh/ohmyzsh#4735]
Some vagrant commands allow you to operate on an arbitrary number of Vagrant boxes, instead of just a single box. The autocomplete currently does not take this into account, only completing the box names for the first box.

`vagrant up myfirst<tab>` => autocompletes to myfirstproject, as expected.
`vagrant up myfirstproject mysecond<tab>` => does not autocomplete at all, expected mysecondproject.

(and thank you for all the work done on zsh and the vagrant plugin... really makes my life enjoyable every day!)

**Comment by robbyrussell** [comment]
Hey there, I'm doing a bit of housekeeping on the project. Thanks for raising this issue—we always love a good edge case! 😄

However, it's not gathering much community interest, so I'm going to close it for now. Don't let this discourage you! We're all for hearing about the weird things. We can't commit to spending too much time tracking each weird thing down ourselves.
