### ISSUE TITLE
ssh-agent plugin symlink not usable with su on newer Linux kernels

### ISSUE THREAD

**Issue by agross** [ohmyzsh/ohmyzsh#4763]
Reference: http://unix.stackexchange.com/questions/253959/

Newer Linux kernels (>= 3.6) support the `fs.protected_symlinks` `sysctl` and most distributions enable it by default (I checked with CentOS 7 and Fedora 23). The `fs.protected_symlinks` checks if a symlink and its _parent_ directory is owned by the same user as the one requesting access to the symlink target.

> When set to "1" symlinks are permitted to be followed only when outside
> a sticky world-writable directory, or when the uid of the symlink and
> follower match, or when the directory owner matches the symlink's owner.

Source: https://www.kernel.org/doc/Documentation/sysctl/fs.txt

`/tmp` is owned by root while `/tmp/ssh-agent-$USER-screen` as well as the symlink target `/tmp/ssh-<random>/agent.<numbers>` is owned by `$USER`. If `zstyle :omz:plugins:ssh-agent agent-forwarding` is enabled accessing the symlink `/tmp/ssh-agent-$USER-screen` works while you're logged in normally. But as soon as you `su` `fs.protected_symlinks` kicks in and rejects access to the symlink. Accessing the symlink target still works, but that would make creating the symlink with `:omz:plugins:ssh-agent agent-forwarding` moot in the first place.

I suggest the symlink is placed somewhere in `$HOME`, probably `$HOME/.ssh/ssh-agent-$USER-screen`, to allow access to the symlink on systems with `fs.protected_symlinks` enabled.

**Comment by chriscpritchard** [comment]
A solution could be to store in $XDG_RUNTIME_DIR

**Comment by robbyrussell** [comment]
Given how long this has been around without peers asking to address it, I will consider this an edge-case concern.
