### ISSUE TITLE
Vi-mode Plugin <c-j> Mapping

### ISSUE THREAD

**Issue by chunleng** [ohmyzsh/ohmyzsh#4898]
This happens in vi-mode, after `v (Vim edition)` mode is entered.

**Reproduced by**
1. Set insert or select mapping for `<c-j>` in vimrc
2. Go to terminal, escape to `normal` mode
3. Press `v`
4. Invoke `<c-j>` in insert mode.

vim: MacVim 7.4-97
The bug was found when using `<c-j>` for Ultisnips vim plugin

**Comment by robbyrussell** [comment]
Hey there, I'm doing a bit of housekeeping on the project. Thanks for raising this issue—we always love a good edge case! 😄

However, it's not gathering much community interest, so I'm going to close it for now. Don't let this discourage you! We're all for hearing about the weird things. We can't commit to spending too much time tracking each weird thing down ourselves.
