### ISSUE TITLE
Num Pad can't input

### ISSUE THREAD

**Issue by mrgaolei** [ohmyzsh/ohmyzsh#4916]
I'm using Mac + ZSH for developer and Gentoo + ZSH for server.
Both of those my Keyboard's num-pad can't input any char(1,2,3,4,5,6,7,8,9,0,.,=,/,*,-,+,enter)
But when I change to bash, those keys are OK.
In any other Applicatons, those keys are OK too.

I'm using Razer's BlackWidow keyboard.

**Comment by pmacey** [comment]
I tend to add this to my `~/.zshrc` file:

```
# Keypad
# 0 . Enter
bindkey -s "^[Op" "0"
bindkey -s "^[On" "."
bindkey -s "^[OM" "^M"
# 1 2 3
bindkey -s "^[Oq" "1"
bindkey -s "^[Or" "2"
bindkey -s "^[Os" "3"
# 4 5 6
bindkey -s "^[Ot" "4"
bindkey -s "^[Ou" "5"
bindkey -s "^[Ov" "6"
# 7 8 9
bindkey -s "^[Ow" "7"
bindkey -s "^[Ox" "8"
bindkey -s "^[Oy" "9"
# + -  * / =
bindkey -s "^[Ok" "+"
bindkey -s "^[Om" "-"
bindkey -s "^[Oj" "*"
bindkey -s "^[Oo" "/"
bindkey -s "^[OX" "="
```
Manual: https://www.gnu.org/software/screen/manual/html_node/Key-Binding.html#Key-Binding
Source: http://superuser.com/questions/742171/zsh-z-shell-numpad-numlock-doesnt-work

**Comment by jbsmith7741** [comment]
bindkey works nicely, but it would be nice to see it work natively.

**Comment by apjanke** [comment]
Looks like the same thing as #2654. It's due to the whole smkx/rmkx thing, which you can read about in #2735.

#5113 should fix it and make it work "natively".

**Comment by abnersouza** [comment]
Same happening for me.

**Comment by petr7555** [comment]
It was `bindkey` -s "^[Ol" "+"` with **l** instead of **k** for me.

**Comment by robbyrussell** [comment]
I am doing some project cleanup.

Closing this due to low peer activity. Considering this a weird edge-case concern.

**Comment by kgnfth** [comment]
I have this same issue 

`zsh 5.9 (x86_64-ubuntu-linux-gnu)`
