### ISSUE TITLE
upgrade does not respect $HOME - wrong ownership after upgrade

### ISSUE THREAD

**Issue by chthal** [ohmyzsh/ohmyzsh#4992]
Hello,

thank you for that great piece of software, I use it on all my computers!

One issue that occurs often, is that an upgrade does not respect $HOME. I always have a couple of opened screen sessions on my computers. Often I log in as user, then do a 
sudo /bin/zsh
 to become root but then stay in 
/home/user #
(I do not change directory) and logout. Now root is in "/home/user #". The session remains open. If I do a login a couple of days later, oh-my-zsh prompts for an update and – if YES – upgrades the installation in /home/user as root giving the files wrong permissions.

Instead upgrade.sh should respect $HOME and look, if there are changes in it's  installation in the homedir of the current user and upgrade that.

**Comment by bderrly** [comment]
Quick note: `sudo -s` is quicker to type. Also, do you really need a root shell sitting around for days on end?

What is your $HOME after switching to a root shell? Mine is `/root` as expected. I'm not sure how the auto-updater runs as root if you login again. I'm reading your description as you SSH into the machine, open screen and then sudo to a shell. Then, later, whereupon you login again with SSH, oh-my-zsh prompts you to upgrade.

**Comment by chthal** [comment]
Thanks for sudo -s :-). No, I don't need, but I like to and usually let my screen sessions open. I login as $User and have configured my .bash_profile and .zprofile so that an existing screen session is re-entered after login or a new one is created:

if [ "$TERM" != "screen" ] && [ "$SSH_CONNECTION" != "" ]; then
        /usr/bin/screen -U -S sshscreen -d -R && exit
fi

At each moment of the screen session I can logout with Ctrl-A-D and reenter the existing screen session with ssh login again. I always come back to the place where I left ... I like that.

Ok here's a session like that:

user@server ~ »
user@server ~ » I just entered
user@server ~ » echo $HOME
/home/user
user@server ~ » sudo -s
root@server /home/user # echo $HOME
/root
root@server /home/user #
root@server /home/user # now I leave with Ctrl-A-D
root@server /home/user # now I am back here again :-)
root@server /home/user # echo $HOME
/root
root@server /home/user #

So $HOME is always correct. But if I enter after a while and left the session in this state:
root@server /home/user #

Then oh-my-zsh prompts for an update and – if YES – upgrades the installation in /home/user as root.

**Comment by bderrly** [comment]
SSH will run an interactive login shell upon connecting. Do you happen to have something like the following in your ~/.zprofile: `[ -e ~/.zshrc ]; then source ~/.zshrc; fi`. When SSH connects it will read your ~/.zprofile (but not your ~/.zshrc). However, if you're sourcing it from ~/.zprofile then that is likely the cause of your issue.
