### ISSUE TITLE
case insensitive tab completion fails with üöä/ÜÖÄ

### ISSUE THREAD

**Issue by marcwil** [ohmyzsh/ohmyzsh#5013]
The case correcting tab completion does not work for 'umlauts'/'Umlaute'.

Reproducible example:
- create directory named e.g. Übung
- type in ü and the press TAB
- expected behaviour: Übung is one of the matched directories

EDIT:
I am sorry if this is an error of zsh and not of oh-my-zsh

**Comment by tsuflux** [comment]
Indeed this seems like an error of zsh as I am experiencing the same issue without using oh-my-zsh.

**Comment by robbyrussell** [comment]
Hey there, I'm doing a bit of housekeeping on the project. Thanks for raising this issue—we always love a good edge case! 😄

However, it's not gathering much community interest, so I'm going to close it for now. Don't let this discourage you! We're all for hearing about the weird things. We can't commit to spending too much time tracking each weird thing down ourselves.
