### ISSUE TITLE
git plugin startup time on large local clones

### ISSUE THREAD

**Issue by valentinrusu-movidius** [ohmyzsh/ohmyzsh#5038]
hello,

here at work I have local clones of our quite large git repo (more than 20 kfiles). upon starting-up, i use tmux continuum to restore my tmux sessions and inside them there are several zsh shells. some of these shells CWD are in the local clones directories. while restoring, the computer hangs making I/Os and I cannot use any shell terminal during this period. even if i'm using kernel-ck, with the I/O scheduler enhanced, my session would stuck for 3..5 minutes during this startup sequence. i'm using i3wm, so my session usually opens-up really fast. i traced-down my start-up latency into git zsh plugin and when removed, the startup time is ok.

is it possible for this plugin to perform it's initialization in an async manner?

thanks,

**Comment by mcornella** [comment]
This is old so I'm closing it.
