### ISSUE TITLE
Git plugin gm alias interferes with GraphicsMagick tool.

### ISSUE THREAD

**Issue by czAdamV** [ohmyzsh/ohmyzsh#5115]
As title says. GraphicsMagick cannot be used with git plugin enabled, because it uses "gm" as a name for its binary (at least when using the one from Arch repository).

**Comment by benjaoming** [comment]
Agreed, could it me moved to `gmg` ?

Solution, add this to your `.zshrc` (adjust accordingly)

    alias gm /usr/bin/gm

**Comment by axe312ger** [comment]
Same for OSX + brew

**Comment by noraj** [comment]
Ref for issue linking: https://github.com/robbyrussell/oh-my-zsh/issues/6832#issuecomment-390722815 https://github.com/robbyrussell/oh-my-zsh/issues/5721#issuecomment-290924482

Have you a wait to disable all git aliases without removing the git plugin?

**Comment by mcornella** [comment]
We can't rename or remove aliases since that breaks people's workflow. The whole purpose of having aliases in a plugin is that they simplify their work, and a `gm` alias for `git merge` is one that will be very frequently used. The only solution is to delete those aliases with `unalias`: `unalias gm`.

**Comment by noraj** [comment]
@mcornella 

> Have you a wait to disable all git aliases without removing the git plugin?

So I have to manually put `unalias` with all git aliases manually in my `.zshrc`? This is not a solution but a workaround.

Nobody is asking for removing those aliases but only to provide a way to disable them for those who don't need them and have conflict.

Please re-open the issue.

**Comment by benjaoming** [comment]
@mcornella 

I would rather try an approach like this in `.zshrc`:

```
for alias in $ALIASES_KNOWN
do
    which_alias=`which $alias`
    if [ $? == 0 ]
    then
        echo "WARNING: Overwriting $alias, was assigned to: $which_alias"
    fi
done
```

(sorry for pseudo-coding that)

**Comment by noraj** [comment]
Also there was #1432 #4900

**Comment by mcornella** [comment]
For now, a shortcut to disabling most of the aliases created by the git plugin:
```
unalias ${(k)aliases[(R)git *]}
```
This `unalias`-es all the aliases to commands starting with `git `, meaning if you've aliased other git commands those will be gone too. There may be other git aliases left out too (check with `alias | grep git`).

**Comment by noraj** [comment]
@mcornella That's very useful.
But I hope there will be a fix one day. Else it is config at each install and make zshrc heavy.

**Comment by kimown** [comment]
It's stupid to enable git plugin by default.

**Comment by benjaoming** [comment]
Here is a better version of the previos pseudo-code, use it to check if an alias is overwriting existing executables in your PATH:

```bash
alias | while read alias
do
    alias_base=`echo "$alias" | tr "=" "\n" | head -n 1`
    which_alias=`which "$alias_base"`
    if ! ( echo "$which_alias" | grep -q "aliased to" ) && ! (echo "$which_alias" | grep -q "\!")
    then
        echo "WARNING: Overwriting $alias_base, was assigned to: $which_alias"
    fi
done
```

**Comment by mcornella** [comment]
Here's a script that shows which aliases shadow an installed command.
```zsh
function alias_conflicts() {
  local alias value
  for alias value in ${(kv)aliases}; do
    if (( ${+commands[$alias]} )) && [[ "$value" != (|noglob |command |\\)${alias}* ]]; then
      echo "Conflict: alias $alias ('$value') <-> command $alias ('${commands[$alias]}')"
    fi
  done
}
```

This is what it returns in my system, for example:
```console
$ alias_conflicts
Conflict: alias gm ('git merge') <-> command gm ('/usr/bin/gm')
```

Note that this ignores aliases of the same name than the command they're aliasing (`alias ls='ls --color=auto'`, for example).

You can go further than that and automatically `unalias` them in the same if condition:
```zsh
function alias_conflicts() {
  local alias value
  for alias value in ${(kv)aliases}; do
    if (( ${+commands[$alias]} )) && [[ "$value" != (|noglob |command |\\)${alias}* ]]; then
      echo "Conflict: alias $alias ('$value') <-> command $alias ('${commands[$alias]}')"
      unalias $alias
    fi
  done
}
```

**Comment by mcornella** [comment]
This alias is very important for the git plugin and it isn't possible to rename it at this point.

The previous workaround of using `unalias` should be enough, and there is now also the option of [disabling aliases as documented here](https://github.com/ohmyzsh/ohmyzsh#skip-aliases).
