### ISSUE TITLE
failed to load module `zsh/datetime'

### ISSUE THREAD

**Issue by harshhpareek** [ohmyzsh/ohmyzsh#5162]
**TL;DR:** should be fixed by using the same zsh binary as the one being executed

----

I installed oh-my-zsh on a remote machine. It gives the following error every time a zsh shell starts:

```
.oh-my-zsh/tools/check_for_upgrade.sh:3: failed to load module `zsh/datetime': /local/p4clients/pkgbuild-ZgWJw/workspace/src/Zsh/build/private/install/lib/zsh/5.0.7/zsh/datetime.so: cannot open shared object file: No such file or directory
_current_epoch:1: bad math expression: operand expected at`/ 60 / 60 ...'
```

This is odd because when I run `zmodload zsh/datetime` in the shell, it works. What could be causing this?

**Comment by mcornella** [comment]
- Do you have more than one zsh? Run `which -a zsh` to know.
- What system is that and how did you install zsh on it?

**Comment by harshhpareek** [comment]
It seems it does have more than one zsh.

It's an Amazon EC2 machine which came with zsh installed

On Wed, Jun 15, 2016 at 11:24 AM Marc Cornellà <notifications@github.com>
wrote:

>
>    - Do you have more than one zsh? Run which -a zsh to know.
>    - What system is that and how did you install zsh on it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/robbyrussell/oh-my-zsh/issues/5162#issuecomment-226241367>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABBxmTAEeusLp2wxeR_B4BWpHPoJOYosks5qMCdEgaJpZM4I2fOC>
> .
>
-- 
Harsh Pareek | Graduate Student | Computer Science | UT Austin
http://www.cs.utexas.edu/~harshp | +1 (512) 994-5775

**Comment by mcornella** [comment]
How did you solve it? Was it a difference between the zsh used in `$SHELL` and the zsh used by respecting the `$PATH` order?

**Comment by harshhpareek** [comment]
Yes, that was the reason for the error. I tried editing
check-for-upgrade.sh but couldn't get it to work for me. It would also
likely be overwritten whenever zsh updates.

It turned out that upgrade_oh_my_zsh works fine, so I'm just disabling
automatic update and I'll update either manually or with a fortnightly cron
job.
Changes could be made to oh-my-zsh to avoid these issues but I don't have a
sufficient understanding of linux and oh-my-zsh to do this.

On Wed, Jun 15, 2016 at 11:51 AM Marc Cornellà <notifications@github.com>
wrote:

> How did you solve it? Was it a difference between the zsh used in $SHELL
> and the zsh used by respecting the $PATH order?
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/robbyrussell/oh-my-zsh/issues/5162#issuecomment-226248823>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABBxmfHg789jE8EvyPXG-CKsJ1OWph8lks5qMC2jgaJpZM4I2fOC>
> .
>
-- 
Harsh Pareek | Graduate Student | Computer Science | UT Austin
http://www.cs.utexas.edu/~harshp | +1 (512) 994-5775

**Comment by mcornella** [comment]
Ok thanks, this issue could be solved by having a pure zsh script to upgrade, instead of the mix of sh and zsh we have now. I'll let you know when this is fixed.

**Comment by shyukri** [comment]
I've hit this recently and the solution was to remove the `/usr/local/bin/zsh` file since it was not owned by any package.
```
/home/shyukri/.oh-my-zsh/tools/check_for_upgrade.sh:3: failed to load module `zsh/datetime': /usr/lib64/zsh/5.3.1/zsh/datetim[26/26]
annot open shared object file: No such file or directory                                                                            
_current_epoch:1: bad math expression: operand expected at `/ 60 / 60 ...'                                                          
➜  ~  which -a zsh                                                                                                                  
/usr/local/bin/zsh                                                                                                                  
/usr/bin/zsh                                                                                                                        
/bin/zsh                                                                                                                            
/usr/local/bin/zsh                                                                                                                  
/usr/bin/zsh                                                                                                                        
/bin/zsh                                                                                                                            
/usr/bin/X11/zsh                                                                                                                    
/usr/local/bin/zsh                                                                                                                  
/usr/bin/zsh                                                                                                                        
/bin/zsh                                                                                                                            
/usr/bin/X11/zsh                                                                                                                                                                                                        
➜  ~  lsb_release -a                                                                                                                
LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:de
sktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarc
h                                                                                                                                   
Distributor ID: openSUSE                                                                                                            
Description:    openSUSE Tumbleweed                                                                                                 
Release:        20180302
Codename:       n/a
➜  ~  which zsh
/usr/local/bin/zsh
➜  ~  echo $SHELL
/usr/bin/zsh
➜  ~  sudo rpm -qf /usr/local/bin/zsh
file /usr/local/bin/zsh is not owned by any package
➜  ~  sudo rm -rf /usr/local/bin/zsh
➜  ~  which zsh
/usr/bin/zsh
➜  ~  upgrade_oh_my_zsh
```

**Comment by japrogramer** [comment]
I have the same problem in my instance /usr/bin/zsh is owned by a package

```
▶ pacman -Qo /usr/bin/zsh                                                                                                                                                                                         ⍉
/usr/bin/zsh is owned by zsh 5.5.1-1
zsh: failed to load module `zsh/termcap': /usr/lib/zsh/5.5/zsh/termcap.so: cannot open shared object file: No such file or directory
zsh: failed to load module `zsh/termcap': /usr/lib/zsh/5.5/zsh/termcap.so: cannot open shared object file: No such file or directory

~
▶ which -a zsh                                                                                                                                                                                                     
/usr/bin/zsh
zsh: failed to load module `zsh/termcap': /usr/lib/zsh/5.5/zsh/termcap.so: cannot open shared object file: No such file or directory
zsh: failed to load module `zsh/termcap': /usr/lib/zsh/5.5/zsh/termcap.so: cannot open shared object file: No such file or directory

```

**Comment by mcornella** [comment]
@japrogramer try to reinstall your zsh package.

**Comment by pavanvora** [comment]
I had same problem. Just solved by reloading zsh with `exec zsh`.

**Comment by 108krohan** [comment]
Hi, for anyone coming back to the issue, here's what worked for me.

> This is due to module_path cannot be passed in implicitly when invoked into script. zmodload will try to find module from compile time setting. Unfortunately our zsh build will generate a different directory everything it built (/local/p4clients/pkgbuild-xxxx....).
> 
> I have to do following to fix it locally:
> 
>     Change ~/.oh-my-zsh/oh-my-zsh.sh (remove -f)
> 
> from
> 
> env ZSH=$ZSH DISABLE_UPDATE_PROMPT=$DISABLE_UPDATE_PROMPT zsh -f $ZSH/tools/check_for_upgrade.sh
> 
> to
> 
> env ZSH=$ZSH DISABLE_UPDATE_PROMPT=$DISABLE_UPDATE_PROMPT zsh $ZSH/tools/check_for_upgrade.sh
> 
> and commit it locally
> 
>     Create ~/.zshenv with following content:
> 
> my_path=/apollo/env/envImprovement/var/lib/zsh/5.0.7/
> if [[ -d $my_path && ${module_path[(I)$my_path]} -eq 0 ]]; then
>     module_path[$(($#module_path+1))]=$my_path
> fi
> 
> Our zsh is not built to source /etc/zshenv so we have to use ~/.zshenv and zsh -f ignores ~/.zshenv hence those changes.

**Comment by sheep-sheep** [comment]
I confirm @108krohan 's solution works for me, I also used apollo env and i updated the zsh version.

**Comment by lawrenceagles** [comment]
running `which zsh`  show me that I have two in my mac. `/bin/zsh` and `/usr/bin/zsh` simply removing `/usr/bin/zsh` solved this for me.

**Comment by mcornella** [comment]
#9019 finally solves this by running the update check in the same zsh process. Please test it with `omz pr test 9019` and +1 it if it works correctly.

**Comment by scyrizales** [comment]
be careful and don't remove /usr/bin/zsh as suggested earlier, it could break the entire system
