### ISSUE TITLE
_arguments:448: _vim_files: function definition file not found

### ISSUE THREAD

**Issue by juanpabloaj** [ohmyzsh/ohmyzsh#518]
when I try autocomplete a name of file for vim, example I try open .vimrc I get 

```
 $ vim ~/.vim<TAB>
 _arguments:448: _vim_files: function definition file not found
 _arguments:448: _vim_files: function definition file not found
 _arguments:448: _vim_files: function definition file not found
 $ vim ~/.vim
```

**Comment by rafmagana** [comment]
> Just run `exec zsh` to solve this.

This worked for me, thanks, @holys.

**Comment by stephanebachelier** [comment]
Thanks !

**Comment by tao12345666333** [comment]
Well, thanks!  @Kakadu I solved in the same way.

**Comment by egoens** [comment]
Thanks for the suggestion @Kakadu. This worked for me as well.

**Comment by victoryancn** [comment]
Thanks !@Kakadu, is works!

**Comment by Neraste** [comment]
@BigDSK: this solved my problem!

**Comment by sishuiliunian** [comment]
it works!

**Comment by sishuiliunian** [comment]
rm .zcompdump*
exec zsh

**Comment by ergouge** [comment]
Well, thanks a lot! @Kakadu

**Comment by cswanghan** [comment]
rm  ~/.zcondump*
exec zsh

works for me.

**Comment by hatakawas** [comment]
rm ~/.zcondump*
exec zsh

Yes！

**Comment by meowoodie** [comment]
thx @kcorcoran , your suggestion is helpful!

**Comment by runforprogram** [comment]
after  exec zsh ,the .zcondump* file recreate

**Comment by timercrack** [comment]
rm ~/.zcondump* works for me, thanks!

**Comment by xanview** [comment]
rm ~/.zcondump* worked for me too, thanks!

**Comment by diguage** [comment]
`rm ~/.zcondump*`, then restart the terminal, OK

**Comment by ev-agelos** [comment]
Except from ~/.zcondump, I had to delete zcondump from .zplug/ (the plugin manager i use).
So i guess if anyone else using a plugin manager or a different than mine, might want to check that too.

**Comment by liujb** [comment]
@BigDSK thanks

**Comment by jgillich** [comment]
I also get the error, even after `rm ~/.zcompdump* && exec zsh`, hmm.

**Comment by frederic-potvin** [comment]
@jgillich I just copy/pasted the command in your comment and it worked for me.

**Comment by dongkui0712** [comment]
@holys thanks

**Comment by tanchao90** [comment]
@jgillich thanks

**Comment by Luxame** [comment]
@jgillich thanks!

**Comment by chuckiefan** [comment]
rm ~/.zcondump* 
exec zsh

then it works, thanks!

**Comment by enozero** [comment]
Those instructions worked... Thanks!

**Comment by alex-bender** [comment]
```
rm ~/.zcondump* 
exec zsh
```
Doesn't work for me

**Comment by troy0820** [comment]
@alex-bender after you deleted the dump, type `zsh` in your terminal.  That should source the shell and should be fine.  That worked for me.

**Comment by mcornella** [comment]
@alex-bender it's:
```
rm ~/.zcomdump* 
exec zsh
```

You mispelled `zcompdump`.

**Comment by dmdque** [comment]
Anyone care to explain why this happens, and why removing `~/.zcompdump*` fixes it?

**Comment by nikitavoloboev** [comment]
I am not using oh my zsh and instead am using [prezto](https://github.com/sorin-ionescu/prezto). 

I have the same issue : 

![](http://i.imgur.com/MR10Udg.png)

Doing these commands : 

```Bash
rm ~/.zcompdump* 
exec zsh
```

Doesn't do anything for me. What can I do to fix this issue? Thank you.

**Comment by koromicha** [comment]
rm .zcompdump*
exec zsh
this works like a charm,thanks

**Comment by bierik** [comment]
```
rm ~/.zcompdump*
exec zsh
```

Solved my problem. Thx @sishuiliunian

**Comment by cyyyu** [comment]
`exec zsh` works. Thanks!

**Comment by Tonvin** [comment]
rm ~/.zcompdump*
exec zsh
Thanks very much.

**Comment by jamespullar** [comment]
@ev-agelos 
Did you ever resolve your issue with zplug?
https://github.com/robbyrussell/oh-my-zsh/issues/518#issuecomment-217710781

**Comment by ev-agelos** [comment]
@jamespullar Well months passed and I am not sure what fixed it, but I dont get the error anymore :|

**Comment by tarvos21** [comment]
Hi, I have tried the `rm ~/.zcompdump*; exec zsh`, this works good in terminal, but in tmux, the problem still exists.

**Comment by captainvera** [comment]
@jamespullar 
This is how I fixed it with nvim 0.1.7 and zplug 2.4.1

`rm -rf ~/.zcompdump*
# depending on where it's installed in your system
rm -rf /usr/local/opt/zplug/zcompdump
exec zsh`

**Comment by aadshalshihry** [comment]
rm -rf ~/.zcompdump* 
exec zsh

if you use tmux, you need to detach, and attach to the session. Then it will work.

**Comment by rackstar** [comment]
rm ~/.zcompdump* 
rm ~/.zplug/zcompdump* (if zplug is installed via the curl command)
exec zsh

**Comment by fedexyz** [comment]
thanks

**Comment by ssteinerx** [comment]
Just started having this problem today.  No changes I'm aware of.  

None of the solutions above have helped.

**Comment by iamkarlson** [comment]
for antigen users, it's also useful 

    rm ~/.antigen/.zcompdump*
    exec zsh

**Comment by ssteinerx** [comment]
@iamkarlson That one did it, thanks!

Sure would be handy to know what actually causes this issue and how to prevent/repair it automatically.

**Comment by jwhitmarsh** [comment]
This works for me, for a day, then I have to `rm ~/.antigen/.zcompdump*` again - anyone have _any_ idea what is causing this?

**Comment by gillchristian** [comment]
@iamkarlson thanks
```bash
rm ~/.antigen/.zcompdump*
exec zsh
```
that worked for me!

**Comment by nikitavoloboev** [comment]
This happens really often for me for some reason and the fix works but it is still super annoying.

Is there a reason why this happens?

**Comment by cbelth** [comment]
I don't know why it happens and I would _love_ to know that. The `.zcompdump` file appears every time I run `exec zsh`. I'm guessing something in my `.zshrc` is causing it. To fix this I added
```
rm ~/.zcompdump*
```
to the _end_ of my `.zshrc`.

**Comment by mronfim** [comment]
rm ~/.zcompdump*
rm ~/.zplug/zcompdump
exec zsh

I had to remove zcompdump in both locations to get it to work.

**Comment by sepiggy** [comment]
work for me on Mac

**Comment by faraco** [comment]
`rm $HOME/.zcompdump` works, however what caused it in the first place?

It seems, this issue keep happening to the users since 2011.

**Comment by ConstipatedNinja** [comment]
For future fellows, here's the simple explanation of why this happens:

When zsh runs, it saves completion data in .zcompdump to make for faster completion later. For those who are on multiple machines regularly with the same homedir exported to those machines, you'll also get .zcompdump-`hostname -s`-<zsh version number> files.

Since it's saving this data, it's effectively making a snapshot of what's there at that time. If the installed packages change, you can witness cases where the zcompdump data is not just out-of-date but will actually cause errors.

If you have this problem with a single machine in your environment, then you should delete the .zcompdump files specifically for that machine and either run `exec zsh` or simply log out and back in to have a new .zcompdump file created for that machine specifically. After this, the single machine should behave for any new sessions on that machine.

If you have a problem with many machines in your environment, or if it's something like all but one machine, delete your primary .zcompdump file and all of the host-specific zcompdump files for the problem hosts, and then ssh into one of the machines that was affected. After that, new sessions on any of the affected machines should behave.

**Comment by ben1iu** [comment]
rm ~/.zcondump*
exec zsh

It's  works for me.

**Comment by TyOverby** [comment]
How to find all ".zcompdump" files on your computer.

(zsh)
```
find / 2> /dev/null | grep "\.zcompdump" 
```

**Comment by barrykui** [comment]
rm ~/.zcondump*
exec zsh

works for me.
