### ISSUE TITLE
Prefix/suffix names of virtualenv prompt info

### ISSUE THREAD

**Issue by xueruini** [ohmyzsh/ohmyzsh#5186]
According to the naming convention for other plugins, the prefix and suffix names for virtualenv should be `ZSH_THEME_VIRTUALENV_PROMPT_PREFIX` and `ZSH_THEME_VIRTUALENV_PROMPT_SUFFIX`, respectively, instead of `ZSH_THEME_VIRTUAL_ENV_PREFIX` and `ZSH_THEME_VIRTUAL_ENV_SUFFIX` as in:
https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/prompt_info_functions.zsh#L13-L15

**Comment by mcornella** [comment]
Fixed by https://github.com/ohmyzsh/ohmyzsh/issues/9763.
