### ISSUE TITLE
Running date command outputs unwanted chars

### ISSUE THREAD

**Issue by psynaptic** [ohmyzsh/ohmyzsh#521]
Example:

```
date --date=2011/09/01 +%s
```

Output:

```
27m1314860400
```

The "27m" is not part of the output of the date command.

**Comment by toinfty** [comment]
I am still having this issue... runnning ` date +%s` gives me 
```
27m 1600051157
```

 - OS / Distro: Arch Linux
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: urxvt

**Comment by mcornella** [comment]
What's the value of `$TERM`?

**Comment by toinfty** [comment]
@mcornella Thanks for your reply. I am using the urxvt-unicode terminal, ` echo $TERM ` produces

```rxvt-unicode```

I tried setting `DISABLE_AUTO_TITLE="true"`. But it does not work for me.  I still get the `27m` chars when running `date +%s` in the urxvt-unicode terminal.

However, when I switch to the xterm terminal, running `date +%s` gives me

<code>&nbsp;1600086617</code>
(Note that there is a space char in front of the timestamp.)

I am happy to provide other information if you need.

**Comment by mcornella** [comment]
Maybe you have other preexec hooks that do this wrong. What does `which $preexec_functions` return?

**Comment by toinfty** [comment]
Running `which $preexec_functions` returns:

```
omz_termsupport_preexec () {
	[[ "${DISABLE_AUTO_TITLE:-}" == true ]] && return
	emulate -L zsh
	setopt extended_glob
	local -a cmdargs
	cmdargs=("${(z)2}") 
	if [[ "${cmdargs[1]}" = fg ]]
	then
		local job_id jobspec="${cmdargs[2]#%}" 
		case "$jobspec" in
			(<->) job_id=${jobspec}  ;;
			("" | % | +) job_id=${(k)jobstates[(r)*:+:*]}  ;;
			(-) job_id=${(k)jobstates[(r)*:-:*]}  ;;
			([?]*) job_id=${(k)jobtexts[(r)*${(Q)jobspec}*]}  ;;
			(*) job_id=${(k)jobtexts[(r)${(Q)jobspec}*]}  ;;
		esac
		if [[ -n "${jobtexts[$job_id]}" ]]
		then
			1="${jobtexts[$job_id]}" 
			2="${jobtexts[$job_id]}" 
		fi
	fi
	local CMD=${1[(wr)^(*=*|sudo|ssh|mosh|rake|-*)]:gs/%/%%} 
	local LINE="${2:gs/%/%%}" 
	title '$CMD' '%100>...>$LINE%<<'
}
```

I tried disabling all the oh-my-zsh plugins and the problem still exists...

**Comment by toinfty** [comment]
@mcornella I just overwrite my .zshrc file by `cp ~/.oh-my-zsh/templates/zshrc.zsh-template to ~/.zshrc`. The problem disappears!
Maybe there is something wrong in my old .zshrc. I will look into the issue and try to find the culprit. Thanks!

**Comment by mcornella** [comment]
Run `typeset -f -t omz_termsupport_preexec` and then run `date +%s`, and post the output of the terminal.

**Comment by toinfty** [comment]
@mcornella Thank you very much! I found the culprit!
It was caused by the following functions that I added (to disable the command echo back in xterm) very long time ago..
I just removed the functions and everything works normal now..
```
function precmd() {
if [[ $TERM != linux ]]; then
    print -Pn "\e]2;%~\a"
fi
}

preexec () {
if [[ $TERM != linux ]]; then
print -Pn "\e]2;%~ :  $1\a"
fi
}
```
