### ISSUE TITLE
Safe-paste plugin breaks Home/End keys

### ISSUE THREAD

**Issue by FuturePilot** [ohmyzsh/ohmyzsh#5237]
Enabling the safe-paste plugin breaks the Home/End keys for me. I can't move the the beginning or end of a line using Home/End. If I disable the plugin Home/End works again. I ran omz_diagnostic_dump and it shows that the bindkeys were the same value regardless of whether the plugin was enabled or disabled.
`"^A" beginning-of-line`
`"^[OH" beginning-of-line`

`"^E" end-of-line`
`"^[OF" end-of-line`

So I'm not sure what might be overriding this.

**Comment by HaleTom** [comment]
To prevent the clobbering of `zle-line-{init,finish}`, would you consider using [willghatch/zsh-hooks](https://github.com/willghatch/zsh-hooks#what)?

**Comment by simonbcn** [comment]
Same problem on Arch Linux, Konsole, zsh 5.8
