### ISSUE TITLE
Alternative to auto-update prompt

### ISSUE THREAD

**Issue by larvanitis** [ohmyzsh/ohmyzsh#5286]
Sometimes I start typing right after I open a new terminal. If oh-my-zsh decides to ask for an auto upgrade, it eats my input or worse it could possibly trigger a Y or N by mistake.

What I propose is an alternative way of handling automatic checks for updates by simply notifying the user of their availability.

eg:
- Check for updates every now and then **in the background** and persist the result.
- Every time a new session is started, iff there were pending updates, **notify the user with a non-interactive prompt** - something like _"There are pending oh-my-zsh updates. Use `upgrade_oh_my_zsh` to upgrade."_
- When `upgrade_oh_my_zsh` is run, clear the persisted "updates available" state.

This should be an option configurable along with `DISABLE_AUTO_UPDATE` on `.zshrc`. Maybe setting a) `DISABLE_UPDATE_PROMPT=notify` or b) `DISABLE_AUTO_UPDATE=true` and `ENABLE_UPDATE_CHECK=true`?

**Comment by dphilpot** [comment]
This sounds like a great solution. We've running into the same problems when performing system scans, the prompt blocks the input of the scanner software.

I would love to see a another option, somethink like silent_autoupdate=true/false where you can say it should get all updates automatically without prompt

**Comment by andreyvit** [comment]
Just another vote for silent autoupdates. The prompt is very annoying, esp when the terminal app restores an old session and all 10 tabs prompt for an update at the same time.

There's never been a case when I refused to update so far, so to me, the prompt is pointless and annoying.

**Comment by andreyvit** [comment]
Actually, looking at `tools/check_for_upgrade.sh`, this should do the trick:

    DISABLE_UPDATE_PROMPT="true"

**Comment by mcornella** [comment]
@andreyvit recently we pushed a fix where only one of the open tabs will ask to update instead of the multiple tab prompts, try updating with `upgrade_oh_my_zsh`.

**Comment by ssbarnea** [comment]
I am also annoyed by the auto-update prompt, I do want to update but I don't want a prompt, I want it automatically. Maybe a new option called "unattended" would do the trick?

**Comment by mcornella** [comment]
> Sometimes I start typing right after I open a new terminal. If oh-my-zsh decides to ask for an auto upgrade, it eats my input or worse it could possibly trigger a Y or N by mistake.

I can add an input sink where characters written before the update prompt are silently ignored. This is possible with code like the following:

```zsh
while read -t -k 1; do true; done
```

`-t` tests if there is input available, and `-k 1` reads one character at a time. I know this is really old but let me know if you'd find that useful and I'll put it in https://github.com/ohmyzsh/ohmyzsh/pull/8939.

> I am also annoyed by the auto-update prompt, I do want to update but I don't want a prompt, I want it automatically. Maybe a new option called "unattended" would do the trick?

This can be set up with `DISABLE_UPDATE_PROMPT=true`.

**Comment by larvanitis** [comment]
@mcornella 
I no longer use omz, but it sounds useful.
