### ISSUE TITLE
auto-correcting sucks hard

### ISSUE THREAD

**Issue by c2h2** [ohmyzsh/ohmyzsh#534]
the auto correcting always convert like ddd -> dd, very annoying, can we disable auto correcting by default?

**Comment by unphased** [comment]
@Drarok Ha, yeah looks like it. 

You know I would leave it on if it was actually *smart*. 

For example: 

`gitf etch` --> `git etch`

Dammit, be smarter!!

**Comment by geoyws** [comment]
> @hrj Hm. Hadn't known about `rehash`. Seems like a wrapper for various package managers that does a `rehash` afterward would be handy.
> 
> My point was more that @isimmons' problem with completion was because Zsh didn't know about the program he had just installed, so it was correcting him

Wished `rehash` could be run at some convenient hook someplace

**Comment by arpan20032009** [comment]
i like auto correct .
it helped me 1000s of time
