### ISSUE TITLE
candy-kingdom theme hg prompt error.

### ISSUE THREAD

**Issue by iamchanghyunpark** [ohmyzsh/ohmyzsh#5342]
I'm running Ubuntu 14.04 with mercurial straight off apt. 
Its currently at version 2.8.2

The candy-kingdom theme seems to be using a hg prompt that is not available with my hg version.
Thus for candy-kingdom, I always keep getting the git basic commands and global options outputs. Very annoying, and just destroys my user experience.

Also #5029 issue is on me as well. A lot of people will be using oh-my-zsh on desktops, or servers thus the battery plugin is just not an option.

**Comment by heartinpiece** [comment]
![image](https://cloud.githubusercontent.com/assets/1884011/17968767/2f663c0c-6b01-11e6-8376-2eb24c19bd5a.png)

**Comment by heartinpiece** [comment]
![image](https://cloud.githubusercontent.com/assets/1884011/17968785/44829f86-6b01-11e6-9b8c-74393ebf36db.png)

**Comment by Orsolino** [comment]
As we can see in source code, this theme uses "hg prompt" command, which is not available without prompt plugin for mercurial.
For installation look at - [http://sjl.bitbucket.org/hg-prompt/installation/](url)
+ to make your terminal clear from zsh: not found messages, I recommend you to enable battery plugin in .zshrc
