### ISSUE TITLE
Opening files with emacsclient, creates a second frame...

### ISSUE THREAD

**Issue by jakobadam** [ohmyzsh/ohmyzsh#5405]
When I open files with `e` from the command line emacs opens a second frame. Why not open the file in the main frame? 

https://github.com/jakobadam/oh-my-zsh/blob/master/plugins/emacs/emacsclient.sh#L8

kind regards,
Jakob

**Comment by PrestanceDesign** [comment]
Hi,

I have the same issue.
@jakobadam Have you found a solution ?

**Comment by lbolla** [comment]
I would like this merged, too.

**Comment by mimischi** [comment]
I experience a related problem: If `emacs` is opened by anything like `sudo -e`, `yoaurt` or whatever other process, it will open a new frame.

Running `e foo.bar` opens the file `foo.bar` in the same expected main frame for me.

Both `$VISUAL` and `$EDITOR` are set to `emacs` and the latter:

```bash
$ which emacs
emacs: aliased to /home/mischi/.oh-my-zsh/plugins/emacs/emacsclient.sh --no-wait
```

**Comment by mcornella** [comment]
This was recently fixed.

**Comment by akinnane** [comment]
@PrestanceDesign or @lbolla are you able to run emacsclient --eval '(frame-list)' with no emacs frames created and then with a frame created. Can you add the output of those commands to this ticket, please?

**Comment by lbolla** [comment]
With one frame:
``` » emacsclient --eval '(frame-list)'
(#<frame emacs26@lbolla-Latitude-7490 0x142ec30>)
```

With no frames:
```
~ » emacsclient --eval '(frame-list)'
(#<frame F1 0xc947b0>)
```

**Comment by lbolla** [comment]
This is still bugging me. Also, given the number of people that have forked `ohmyzsh` just to fix the emacsclient.sh function that checks for the existing frames I think it would be worth to make it configurable.
E.g.:
```
_emacsfun()
{
    # get list of emacs frames.
    frameslist=`emacsclient --alternate-editor '' --eval '(frame-list)' 2>/dev/null | egrep -o '(frame)+'`

    if [ "$(echo "$frameslist" | sed -n '$=')" -ge ${EMACS_FRAMELIST_MAX:1} ] ;then
...
```
Users could set `EMACS_FRAMELIST_MAX` to whatever they like, to indicate how many frames they want max (and open in existing frames otherwise).

**Comment by jokuha** [comment]
This is to describe the problem on Emacs Mac (https://bitbucket.org/mituharu/emacs-mac, installed through MacPorts as emacs-mac-app), to ask for a solution, and to support the suggestion of @lbolla to let the user set EMACS_FRAMELIST_MAX before opening a new frame – at least, as a intermediate workaround.

Indeed, using this current GNU Emacs the expected default number of frames is wrong. Here, there's always one frame open:

Emacs version:
```
± emacsclient --eval '(version)'   
"GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.3.0, Carbon Version 162 AppKit 1894.3)\n of 2020-03-24"
```

Output of frame-list with 1 and 2 frames open:
```
± emacsclient --eval '(frame-list)'
(#<frame hostname: *Messages* 0x10a28c438>)
± emacsclient --eval '(frame-list)'
(#<frame hostname: *Messages* 0x116855e30> #<frame hostname: *Messages* 0x10a28c438>)
```
Trying to close the last frame results in `funcall-interactively: Attempt to delete the sole visible or iconified frame`
Running the test command with the sole frame iconized (minimized) yields one frame but without a buffer specified
```
± emacsclient --eval '(frame-list)' 
(#<frame Emacs@hostname 0x10a28c438>)
```
But even in the last case I do not want a new frame, I want this iconized frame to be used and made visible – which is what the emacsclient command does automatically already.

**Comment by mcornella** [comment]
Hey, I've been revisiting this trying to find a working solution across all platforms, could you tell me what the code below outputs both for:
1. `emacs --daemon` not running
2. daemon running but no frames visible
3. one visible frame

```
emacsclient -n -e '(frame-list-z-order)'
```

Thanks

**Comment by mcornella** [comment]
I've submitted a PR which theoretically fixes this problem for both situations (one residual frame or none are available). Please test #10227 by running `omz pr test 10227`. It should work when requiring a graphical frame (`--no-wait`) or a tty frame (`-t`/`-nw`/`--tty`).
Whether it works or it doesn't, please comment in #10227.
