### ISSUE TITLE
Update not working (error with upgrade.sh)

### ISSUE THREAD

**Issue by ashmoran** [ohmyzsh/ohmyzsh#549]
I can't update Oh My Zsh from inside the shell. This is my shell session showing what goes wrong:

```
Last login: Sun Aug 14 09:42:19 on ttys002
[Oh My Zsh] Would you like to check for updates?
Type Y to update oh-my-zsh: y
/bin/sh: /tools/upgrade.sh: No such file or directory
```

Here is my .zshrc (zsh_app_switcher is just a simple function):

```
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(osx brew rvm gem bundler git rails3)
source $ZSH/oh-my-zsh.sh
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin
source /Users/ashleymoran/.dotfiles/zsh_app_switcher
export EDITOR="mate -w"
export SVN_EDITOR="mate -w"
alias nano="nano -w"
export DARCS_EMAIL=ash.moran@patchspace.co.uk
if [[ -s /Users/ashleymoran/.rvm/scripts/rvm ]] ; then source /Users/ashleymoran/.rvm/scripts/rvm ; fi
```

**Comment by wembernard** [comment]
should be merged here.

**Comment by yanghanyugithub** [comment]
old problems, but it works~ thank you! @toolbear

**Comment by abdennour** [comment]
If you upgraded you MAC OS & you have XCode already installed, you should open XCode & accept agreements &  install new components, then,, go back to terminal .. the issue will be resolved.

**Comment by da1z** [comment]
I am getting this error again, any fixes right now? I have exported oh-my-zsh from .zshrc
