### ISSUE TITLE
tmux prompt corruption with git_prompt_info

### ISSUE THREAD

**Issue by jhartikainen** [ohmyzsh/ohmyzsh#559]
Inside a tmux session, if you use zsh with oh-my-zsh themes that use the git_prompt_info, it causes corruption of the prompt/line when in a Git repository directory.

Steps:
1. Enable theme with git_prompt_info (I use flazz)
2. Go into a directory with .git
3. You should notice the prompt contains some extra spaces, and typing causes the characters to appear in the space. You should additionally notice that if you try editing a line from history, it will be shifted a few spaces forwards making it hard to edit it correctly.

Expected:

No issue in step 3

Possible cause:

Users on the zsh IRC channel said it was probably caused by the output of the git_prompt_info command, and not caused by tmux itself.

**Comment by moeabdol** [comment]
Thanks @kooothor this worked on my zsh tmux session on archlinux.
