### ISSUE TITLE
repo plugin doesn't complete multiple projects for 'repo forall'

### ISSUE THREAD

**Issue by ghost** [ohmyzsh/ohmyzsh#5598]
I expected 'repo forall' to assume directory name completion until I do -^I. Instead, only the first name is completed and zsh assumes option completion afterwards.

**Comment by robbyrussell** [comment]
Hey there, I'm doing a bit of housekeeping on the project. Thanks for raising this issue—we always love a good edge case! 😄

However, it's not gathering much community interest, so I'm going to close it for now. Don't let this discourage you! We're all for hearing about the weird things. We can't commit to spending too much time tracking each weird thing down ourselves.
