### ISSUE TITLE
Autoupdate git repos in custom/plugins

### ISSUE THREAD

**Issue by benwaffle** [ohmyzsh/ohmyzsh#5599]
It would be nice if ohmyzsh searched for .git folders in custom/plugins/* and ran `git pull` in those directories

personally, I have [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) and [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) in that directory

**Comment by benwaffle** [comment]
Adding something like this at the end of `tools/upgrade.sh` should work:


```zsh
printf "${BLUE}%s${NORMAL}\n" "Updating Custom Plugins"
cd "$ZSH/custom/plugins"
for dir in ./*; do
    if [[ -d $dir && -d $dir/.git ]]; then
        git -C $dir pull --rebase --stat origin master
    fi
done
```

**Comment by wonbyte** [comment]
@benwaffle is the code above still the best way to achieve updating custom plugins?

**Comment by benwaffle** [comment]
I've switched to https://github.com/zsh-users/antigen. It works great, and supports oh-my-zsh

**Comment by mattmc3** [comment]
This is an easy way to handle git pull updates for everything in your zsh_custom:

```zsh
find $ZSH_CUSTOM -type d -name .git -prune -execdir git pull -q \;
```

You can add a `-print` to the find command if you want a chatty update. You can also alias that to a command in your .zshrc like so:

```zsh
alias update_zsh_custom="find $ZSH_CUSTOM -type d -name .git -prune -execdir git pull --rebase -q \;"
```

**Comment by robbyrussell** [comment]
Thanks, I am going to close this as I don't believe OMZ should be responsible for auto-updating custom/3rd-party plugins (at least -- for now). There are some great suggestions above to use if you want that for your own setup.
