### ISSUE TITLE
git-prompt not honoring .gitmodules settings for --submodules-ignore

### ISSUE THREAD

**Issue by hador** [ohmyzsh/ohmyzsh#5617]
I have a dotfiles repository with a few submodules I use to include external repositories. I am not interested in the status of said submodules, so I set `ignore = all` in the proper `[submodule x]` section of the main repo's _.gitmodules_ file.
However, the git prompt from oh-my-zsh shows the working tree as dirty, because of these lines of code in _oh-my-zsh/lib/git.zsh_ :
```
if [[ $POST_1_7_2_GIT -gt 0 ]]; then
    FLAGS+='--ignore-submodules=dirty'
fi
```
which override the aforementioned settings. Is there any specific reason for this behavior? We also lose the ability to have different settings for different submodules.

**Comment by kevinquillen** [comment]
I have this same issue.

**Comment by kevinquillen** [comment]
Is there a better way to address this that does not require modifying git.zsh?

**Comment by mcornella** [comment]
We could get rid of it altogether but that would make it dirty on any changes if no ignore config was set up, which is the default in most repositories. Another option would be checking if `git config --list` has any `submodule.*.ignore` line, but options set up in `.gitmodules` don't show up in that list.

**Comment by mcornella** [comment]
This was fixed a long time ago by setting `GIT_STATUS_IGNORE_SUBMODULES=git`.
