### ISSUE TITLE
Please, add support of " " and ' ' text objects to vi-mode plugin 

### ISSUE THREAD

**Issue by srghma** [ohmyzsh/ohmyzsh#5708]
And many others text objects as I assume
I cant do `ci"`

zsh 5.2 (x86_64-unknown-linux-gnu)
oh-my-zsh-git r4257.26aae6b-1

**Comment by BjornMelgaard** [comment]
I cant do `ci"`

**Comment by okapia** [comment]
Note that the commands for enabling that text object are at the top of Functions/Zle/select-quoted. You can use them in `.zshrc` regardless of what the vi-mode plugin does:

```
     autoload -U select-quoted
     zle -N select-quoted
     for m in visual viopp; do
       for c in {a,i}{\',\",\`}; do
         bindkey -M $m $c select-quoted
       done
     done
```
You might also want to look at Functions/Zle/select-quoted and select-word-match (new in zsh 5.3).

**Comment by BjornMelgaard** [comment]
@okapia, That must be added in vi-mode

**Comment by okapia** [comment]
@BjornMelgaard: yes, it _ought_ to be added but I'm not an oh-my-zsh contributor so can't do that for you. I'm just trying to be helpful by pointing out _what_ would need to be added and that you can use it directly from your `.zshrc` as a (hopefully) short-term solution.

**Comment by BjornMelgaard** [comment]
@okapia , and I'm already using it, great thanks, I just note the obvious

**Comment by yangmillstheory** [comment]
I found a snippet that I'm including in my own patched `vi-mode.plugin.zsh` [here](https://www.linux.org.ru/forum/general/12280266). Looks like https://github.com/robbyrussell/oh-my-zsh/issues/5708#issuecomment-271066670 will only work for quotes, not brackets.

**Comment by BjornMelgaard** [comment]
Thanks @yangmillstheory

**Comment by softmoth** [comment]
By the way, this is supported in the [vim-mode](https://github.com/softmoth/zsh-vim-mode) plugin add-on.

**Comment by robbyrussell** [comment]
⌛️ Going to close this as it appears the vim-mode plugin satisfies this need. If I'm mistaken, please let us know and/or contribute a proposed PR
