### ISSUE TITLE
Add a "donate to oh-my-zsh" option

### ISSUE THREAD

**Issue by kevinburke** [ohmyzsh/ohmyzsh#5751]
I see you have stickers and shirts which are nice, but require work on your end to mail out the items and cap your max donation at the price of a shirt minus its cost. If it's all being handled via Paypal anyway, you might consider adding a "donate to sponsor oh-my-zsh development" option.

**Comment by tuxayo** [comment]
In the mean time on can pledge for recurring donations here: https://liberapay.com/on/github/robbyrussell/

If the the owner of the repo creates an account on Liberapay and link it's GitHub account, the pledges will automatically activate.

**Comment by mcornella** [comment]
There's now a donate button. You can donate to [opencollective](https://opencollective.com/ohmyzsh) or individually to each of us.
