### ISSUE TITLE
per-directory-history breaks bgnotify

### ISSUE THREAD

**Issue by adrianlzt** [ohmyzsh/ohmyzsh#5803]
If plugin per-directory-history is activated, bgnotify could not show the name of the command finished.

Setting the ``$1`` to ``$2`` [here](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/bgnotify/bgnotify.plugin.zsh#L56) works, but it has a little different [meaning](http://zsh.sourceforge.net/Doc/Release/Functions.html):
```
The actual command that will be executed (including expanded aliases) is passed in two
different forms: the second argument is a single-line, size-limited version of the
command (with things like function bodies elided)
```

**Comment by mcornella** [comment]
This is intended behavior documented by zsh:

> preexec
>
>    If the history mechanism is active (regardless of whether the line was discarded from the history buffer), **the string that the user typed is passed as the first argument, otherwise it is an empty string**.

The only option is to use `$2` if `$1` is empty.
