### ISSUE TITLE
gnu coreutils theme conflict

### ISSUE THREAD

**Issue by OAuthBringer** [ohmyzsh/ohmyzsh#5804]
I've been using oh my zsh for probably about three years now, and I recently updated to sierra.  My shell config is version controlled and it installs fine, but when I installed `coreutils` via `brew` and overwrote the default OSX utils  I lost all of the zsh LS configuration.  

I know that the `gdircolors` > `dircolors` conversion is the culprit, but I'm unsure of how to work around it.  Any advice?

**Comment by aespinoza** [comment]
I have this problem as well.

**Comment by Thrilleratplay** [comment]
@neolytics Ugh, that has been annoying me for a while and thank you for figuring out the culprit is `dircolors`.  

I was able to fix this by aliasing `gdircolors`:  
```bash
echo 'alias dircolors=gdircolors' >> ~/.zshrc && source ~/.zshrc
```

**Comment by robbyrussell** [comment]
Going to close this for now. If someone would like to submit a proposed PR, we'd welcome considering that

**Comment by LucienZhang** [comment]
Another workaround is to prioritize `/bin/ls` by
```bash
echo 'export PATH="/bin:${PATH//:\/bin:/:}"' >> ~/.zshrc && source  ~/.zshrc
```
