### ISSUE TITLE
nebirhos zsh-theme hostname is too long

### ISSUE THREAD

**Issue by cdavidowski** [ohmyzsh/ohmyzsh#6050]
Hello,

It appears for issue #6028 there was a change made to show the full hostname in the prompt.  The hostname for my machine is controlled by my work and is very long.  I think a better option for this prompt would be the short hostname.  This is populated in $SHORT_HOST.  This would solve the issue in #6028 and still work for people that have long full hostnames.

Thanks!

**Comment by mcornella** [comment]
Can you submit a PR?
