### ISSUE TITLE
extending HYPHEN_INSENSITIVE setting to cover more use cases

### ISSUE THREAD

**Issue by gasparch** [ohmyzsh/ohmyzsh#6057]
While changing from tcsh I found file completion configured by oh-my-zsh unfamiliar and inflexible.
Turns out that zsh provides huge flexibility in matching and expanding, but it requires digging into murky parts of documentation and lot's of experiments.

Should we make it easier with some predefined completion levels with increasing levels of flexility/greediness? If yes - I'll file PR with following changes. 

cc @mcornella @Gravemind @forivall 

Also tell me test cases which you would like to work on each level, so I'll test how it can be expressed in zsh completion logic.

FUZZY_COMPLETION=0 - to behave like HYPHEN_INSENSITIVE=false
FUZZY_COMPLETION=1 - to behave like HYPHEN_INSENSITIVE=true (big-file can be completed by big_file, but no fuziness)

For next levels imagine there is a directory with those files
```
another_file
any-big_file.sh
attributes.sh
```

FUZZY_COMPLETION=20 - to allow pattern matching 
- `a-b-f` or `a_b_f` competed by `any_big-file`
- `a-f` matched by `another_file`, but not the `any_big-file.sh`
- `a.sh` completed by `attributes.sh` and on next tab - by `any-big_file.sh`
FUZZY_COMPLETION=30 - to allow greedy pattern matching
- `a-b-f` competed by `any_big-file.sh`
- `a-f` matched by `another_file` and `any_big-file.sh`
- `a.sh` completed by `attributes.sh` and on next tab - by `any-big_file.sh`

Level 2 feels mostly like tcsh behavior with `set complete = enhance` options set.

FUZZY_COMPELTION=100 - to allow fully fuzzy completion as sugessested in [here](http://stackoverflow.com/a/25556544/6465543)

**Comment by forivall** [comment]
For further customization, I've since learned to [directly use the zstyle commands](https://github.com/forivall/dotfiles/blob/273e0ce3acd711ed987e35f0a77047c7e534f22f/zshrc#L123-L133) (although they're still kinda cryptic to me 😅 )
