### ISSUE TITLE
Feature: use `ls` colors in completion output

### ISSUE THREAD

**Issue by chuckdries** [ohmyzsh/ohmyzsh#6060]
Problem: tab completion is colored, but colors do not match other colors throughout the terminal.

1. How to reproduce the problem  
run `ls` then type `vim <tab>` with default color scheme/theme  
2. What the correct behavior should be
Colors displayed should match colors of output of `ls`
3. What the actual behavior is
Color of output is different than color of `ls` output  
(In my case I'm using the Smyck color scheme for iTerm, though that should not matter here)  
<img width="922" alt="screen shot 2017-05-01 at 6 08 19 pm" src="https://cloud.githubusercontent.com/assets/1351436/25600562/ccef3076-2e99-11e7-97b3-247dea8c8dbe.png">  

As you can see, all the colors are different and the `Adobe` entry is downright illegible.

I came across #1563 but I am new to this and don't know enough about zsh theming to know what dir_colors is or really understand what's going on in that thread. I tried the workaround listed in the thread: `zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}`, but it removes color from tab completion output completely. As I understand it, this behavior is to be expected as I am on a mac and macs use LSCOLORS, but when I use LSCOLORS in that line, I get the same broken result as I do omitting the line in question.

This seems like it should be a simple thing. Yes there are iTerm themes that make it legible, but they make my vim scheme illegible and I'd really rather solve this the right way.

As a workaround, can I manually override the tab completion colors? Where can I look to look up the LS output colors? `echo LSCOLORS` give me this insane string: `Gxfxcxdxbxegedabagacad`

**Comment by anticitizen4** [comment]
[This](https://superuser.com/questions/290500/zsh-completion-colors-and-os-x?rq=1) helped me a lot.

Basically zsh doesn't recognize `LSCOLORS` and can't understand its format. Zsh is responsible for printing  and painting completion strings. It does understand `LS_COLORS` though.

When you call `ls` it, being a standard native program of MacOS, uses `LSCOLORS`.

One thing you can do is use tool from the link to convert your `LSCOLORS` setup and define `LS_COLORS` with the same colors as `LSCOLORS`.

**Comment by cdonovick** [comment]
I have the same issue on Debian with a well formed LS_COLORS.

My LS_COLORS specifies di=01;34 (blue) but when I tab complete directories are shown in red  (best guess is 01;31)

**Comment by rarylson** [comment]
## Analysis of ohmyzsh source code

ohmyzsh defines `LSCOLORS` here:

https://github.com/ohmyzsh/ohmyzsh/blob/78b07e92fd4a3a5e1f92ee4e3d680c39b72c2245/lib/theme-and-appearance.zsh#L4-L5

- The `LSCOLORS` variable is always defined: for every OS, for every `ls` case (BSD `ls` or GNU `ls`)
- If `LSCOLORS` was already defined, it will be overridden

Ohmyzsh, in the same file, also handles `ls` color using this logic:

https://github.com/ohmyzsh/ohmyzsh/blob/78b07e92fd4a3a5e1f92ee4e3d680c39b72c2245/lib/theme-and-appearance.zsh#L22-L28

- Define `alias ls='ls -G'`, which uses `LSCOLORS`
- Or define `alias ls='gls --color=tty'`, which uses `LS_COLORS`

And, after this, ohmyzsh uses `LS_COLORS` in autocomplete:

https://github.com/ohmyzsh/ohmyzsh/blob/78b07e92fd4a3a5e1f92ee4e3d680c39b72c2245/lib/theme-and-appearance.zsh#L37-L38

- It doesn't handle the case where `LSCOLORS` exists, but `LS_COLORS` doesn't

### Summary

- Defines `LSCOLORS` using a default value
- Defines `ls` alias using default MacOS X `ls`
- If user have defined `LS_COLORS`, define `ls` alias using GNU `ls`
- Set autocomplete using `LS_COLORS`

This logic seems a little confuse to me. It doesn't handle the case where the user is using the BSD `ls` (example, in MacOS X), when `LSCOLORS` is defined by ohmyzsh, but there is no `LS_COLORS`.

## Possible solution

Without trying to refactor the logic, a simple solution could be:

```diff
  - Defines `LSCOLORS` using a default value
  - Defines `ls` alias using default MacOS X `ls`
  - If user have defined `LS_COLORS`, define `ls` alias using GNU `ls`
-  - Set autocomplete using `LS_COLORS` 
-  - Set autocomplete using `LS_COLORS` if `LS_COLORS` is defined
+ - If `LS_COLORS` is not defined, set completion to be compatible with `LSCOLORS`: `zstyle ':completion:*:default' list-colors "di=1;36" "ln=35" so=32" "pi=33" "ex=31" "bd=34;46" "cd=34;43"  "su=30;41" "sg=30;46" "tw=30;42" "ow=30;43"`
```

We can try to create a PR to see if the guys from ohmyzsh agree with this approach or if they have a better idea.

**Comment by rarylson** [comment]
## ohmyzsh behabior on Ubuntu

On Ubuntu, ohmyzsh sets the `LSCOLORS` var:

https://github.com/ohmyzsh/ohmyzsh/blob/78b07e92fd4a3a5e1f92ee4e3d680c39b72c2245/lib/theme-and-appearance.zsh#L4-L5

But, because Ubuntu uses the GNU `ls` implementation (not the BSD one) and `LS_COLORS` are also defined, the ZSH autocomplete is compatible with the `ls` output:

```plaintext
➜  / echo $LSCOLORS
Gxfxcxdxbxegedabagacad
➜  / echo $LS_COLORS
rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
➜  / alias ls
ls='ls --color=tty'
```

In other words, although ohmyzsh defines `LSCOLORS`, this is just ignored in the rest of the code logic.

**Comment by rarylson** [comment]
## Possible workaround

If you're using MacOS X using the default `ls` (BSD variation), OhMyZSH will automatically set the `LSCOLORS` variable to "Gxfxcxdxbxegedabagacad".

If you do NOT override it after, you can put this on your `.zshrc`:

```bash
# Autocomplete colors
#
# Based on OhMyZSH default `LSCOLORS`. Converted with the help of the Geoff
# Greer's lscolors project.
# See: https://geoff.greer.fm/lscolors/
zstyle ':completion:*:default' list-colors \
  "di=1;36" "ln=35" "so=32" "pi=33" "ex=31" "bd=34;46" "cd=34;43" \
  "su=30;41" "sg=30;46" "tw=30;42" "ow=30;43"
```

This will set autocomplete to use colors equivalent of the default `LSCOLORS`.

## Possible code improvements

Since `LSCOLORS` will ALWAYS be set by OhMyZSH, and keeping this as is, maybe we could use this logic:

- Set `LSCOLORS` to OhMyZSH default value
- If `LS_COLORS` is NOT set, set is using the equivalent of `LSCOLORS`
- Move the ZSH autocomplete using `LS_COLORS` to just after the `if` blockcode, so it'll be applied to all of the OSes.

So, ZSH will be able to use `gls` and ZSH autocomplete with compatible colors even in MacOS X.

Note that we'll be unnecessarily setting `LS_COLORS` when not using `gls`. But today we DO unnecessarily set `LSCOLORS` when using `gls`, so this shouldn't be a problem.

**Comment by rarylson** [comment]
I wasn't able to provide a full implementation of my previous idea, but I was able to implement an implrovement/workaround. My code handles only the MacOS X (and the solution is based on the same code that handles the Linux case - sorry for the duplicated code). Just sharing the idea here:

```diff
diff --git a/lib/theme-and-appearance.zsh b/lib/theme-and-appearance.zsh
index 5016d86c..89382a97 100644
--- a/lib/theme-and-appearance.zsh
+++ b/lib/theme-and-appearance.zsh
@@ -3,6 +3,8 @@ autoload -U colors && colors

 # Enable ls colors
 export LSCOLORS="Gxfxcxdxbxegedabagacad"
+# Same colors than BSD $LSCOLORS, but converted to GNU $LS_COLORS format
+g_lscolors="di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"

 # TODO organise this chaotic logic

@@ -20,12 +22,28 @@ if [[ "$DISABLE_LS_COLORS" != "true" ]]; then
     gls --color -d . &>/dev/null && alias ls='gls --color=tty'
     colorls -G -d . &>/dev/null && alias ls='colorls -G'
   elif [[ "$OSTYPE" == (darwin|freebsd)* ]]; then
-    # this is a good alias, it works by default just using $LSCOLORS
-    ls -G . &>/dev/null && alias ls='ls -G'
+    # On MacOS X, "gls" (ls from GNU coreutils) is available from ports and
+    # brew. We use the default BSD "ls" or GNU "gls", depending on the case.

-    # only use coreutils ls if there is a dircolors customization present ($LS_COLORS or .dircolors file)
-    # otherwise, gls will use the default color scheme which is ugly af
-    [[ -n "$LS_COLORS" || -f "$HOME/.dircolors" ]] && gls --color -d . &>/dev/null && alias ls='gls --color=tty'
+    # This is a good alias. It works by default just using $LSCOLORS.
+    ls -G . &>/dev/null
+    if [[ "$?" -eq 0 ]]; then
+      alias ls='ls -G'
+      # Set completion using $g_lscolors (same colors than $LSCOLORS)
+      zstyle ':completion:*' list-colors "${(s.:.)g_colors}"
+    fi
+
+    # Only use coreutils ls if there is a dircolors customization present ($LS_COLORS or .dircolors file)
+    # Otherwise, gls will use the default color scheme which is ugly af.
+    [[ -n "$LS_COLORS" || -f "$HOME/.dircolors" ]] && gls --color -d . &>/dev/null
+    if [[ "$?" -eq 0 ]]; then
+      alias ls='gls --color=tty'
+      if [[ -z "$LS_COLORS" ]]; then
+        (( $+commands[gdircolors] )) && eval "$(gdircolors -b "$HOME/.dircolors")" || eval "$(gdircolors -b)"
+      fi
+      # Take advantage of $LS_COLORS for completion as well.
+      zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
+    fi
   else
     # For GNU ls, we use the default ls color theme. They can later be overwritten by themes.
     if [[ -z "$LS_COLORS" ]]; then
@@ -52,3 +70,5 @@ ZSH_THEME_GIT_PROMPT_DIRTY="*"              # Text to display if the branch is d
 ZSH_THEME_GIT_PROMPT_CLEAN=""               # Text to display if the branch is clean
 ZSH_THEME_RUBY_PROMPT_PREFIX="("
 ZSH_THEME_RUBY_PROMPT_SUFFIX=")"
+
+unset g_lscolors
```

[theme-and-appearance.zsh.diff.zip](https://github.com/ohmyzsh/ohmyzsh/files/4044101/theme-and-appearance.zsh.diff.zip)

I think it's better to refactor the whole logic. Anyway, I'm sharing my code here because if may help when someone try to refactor the whole code.

**Comment by CRKatri** [comment]
I also encountered this issue on FreeBSD, but so I created [opendircolors](github.com/CRKatri/opendircolors) to generate my `LS_COLORS` for `fd`, `tree` and stuff but also a`LSCOLORS` for `ls`.

**Comment by ctype** [comment]
> If you have working `LS_COLORS`, this zstyle option will make completion and ls output be of the same color:
> 
> ```shell
> zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
> ```
> 
> We should make a note of doing that automatically in OMZ.

Just want to add that the command is missing quotes (for people who find this via google, like me. In the source file it's correct.
Should be:
`
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"`

**Comment by mcornella** [comment]
Thanks for the correction! I should mention that this is now done automatically in `lib/theme-and-appearance.zsh` unless `DISABLE_LS_COLORS=true`. See #11529.

**Comment by tdegeus** [comment]
This workaround by @rarylson did the job for me on OSX

> If you do NOT override it after, you can put this on your `.zshrc`:
> 
> ```shell
> # Autocomplete colors
> #
> # Based on OhMyZSH default `LSCOLORS`. Converted with the help of the Geoff
> # Greer's lscolors project.
> # See: https://geoff.greer.fm/lscolors/
> zstyle ':completion:*:default' list-colors \
>   "di=1;36" "ln=35" "so=32" "pi=33" "ex=31" "bd=34;46" "cd=34;43" \
>   "su=30;41" "sg=30;46" "tw=30;42" "ow=30;43"
> ```

However, what I don't get is that I have always had these colours. It has only been a few days that the colours after tab-completion became horrible. Was there previously some upstream workaround for this?
