### ISSUE TITLE
Deprecated Aliases

### ISSUE THREAD

**Issue by umpirsky** [ohmyzsh/ohmyzsh#6130]
On https://github.com/robbyrussell/oh-my-zsh/wiki/Plugin:git it says `ggpush` is alias and `ggp` is command. It also says: new alias `ggp` (`ggpush `still exists for now though).

Does that means that `ggp` will or replaces `ggpush`? Because they don't do same thing. Same with `ggu` and `ggpur`.

**Comment by mcornella** [comment]
They are the same, with the exception that you can pass a different branch.
