### ISSUE TITLE
Add mechanism for auto-update of custom folder 

### ISSUE THREAD

**Issue by mscalora** [ohmyzsh/ohmyzsh#6242]
A way is needed to tie custom folder contents updating to the OMZ update mechanism.

See: https://github.com/robbyrussell/oh-my-zsh/pull/5093

It's been a year since this PR was closed, I'm beginning to despair.

**Comment by archteck** [comment]
I think the idea is good but it feels like very complex approach the one done is that PR.
I do something very simple that was adding this lines in the end of upgrade.sh

`cd custom/plugins`
`printf "\n${BLUE}%s${RESET}\n" "Updating Custom Plugins"`
`for plugin in */; do`
`  if [ -d "$plugin/.git" ]; then`
`     printf "${YELLOW}%s${RESET}\n" "Updating ${plugin%/}"`
`     git -C "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/$plugin" pull`
`  fi`
`done`
`printf "\n${BLUE}%s${RESET}\n" "Updating Custom Themes"`
`cd ../themes`
`for theme in */; do`
  `if [ -d "$theme/.git" ]; then`
      `printf "${YELLOW}%s${RESET}\n" "Updating ${theme%/}"`
      `git -C "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/$theme" pull`
  `fi`
`done`


That works fast and i believe it works very good, and its simple.

Note: I could do it in only 1 For Loop, but in my case took almost double the time, in my machine (custom plugins: zsh-syntax-highlighting and zsh-autosuggestions, custom theme: powerlevel10k)  this approach run the upgrade in 25 sec. With a single For Loop it took 47 sec.

**Comment by polothy** [comment]
maybe close in favor of #9512 ?

**Comment by robbyrussell** [comment]
Closing with https://github.com/ohmyzsh/ohmyzsh/issues/9512 in mind
