### ISSUE TITLE
man page of z plugin doesn't end up in MANPATH

### ISSUE THREAD

**Issue by MoritzFago** [ohmyzsh/ohmyzsh#6283]
Steps to reproduce:
1. add z to plugins in .zshrc
2. `man z`

Expected result:
manpage of z

Current result:
No manual entry for z

Proposed fix:
add/copy z.1 to somewhere in the manpath

**Comment by mcornella** [comment]
Is there a way for us to modify `$MANPATH` to point to the z plugin folder?

**Comment by mcornella** [comment]
I don't think we'll support this use case.
