### ISSUE TITLE
Plugins: can I load them asynchronously, or on-demand?

### ISSUE THREAD

**Issue by sohocoke** [ohmyzsh/ohmyzsh#6292]
oh-my-zsh plugins like `pyenv` or `rbenv` are great, but many times I am forced not to use a plugin because it can bring my shell launch time to a crawl. It's why we get issues like #6017 . 

Is it possible to load some plugins asynchronously, so my shell prompt is not blocked until all the plugins launch? Failing this, can I load plugins on-demand?

**Comment by folixg** [comment]
I can't answer the part about asynchronously loading, but for manual loading you could add a function to your .zshrc that does that.

A basic example (only able to handle one plugin, no error checking)
```
function load-plugin() {
  source $ZSH/plugins/"$1"/"$1".plugin.zsh
}
```

Then run ```load-plugin pyenv```, whenever you need it.

**Comment by awinecki** [comment]
Just wanted to chime in that there's a very similar issue going on with NVM (Node.js version manager) right now: https://github.com/creationix/nvm/issues/1277.

@crenwick came up with a great way to load NVM on-demand:
```
alias load_nvm='export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"'
alias node='unalias node npm && load_nvm && node'
alias npm='unalias node npm && load_nvm && npm'
```

I'm hoping the same could be done with pyenv:
```
alias load_pyenv='eval "$(pyenv init -)"'
alias pyenv='unalias pyenv && load_pyenv && pyenv'
```

**Comment by sohocoke** [comment]
@awinecki thanks for that info.

It makes me wonder whether we can have another shell variable `lazy_plugins` which can be used to either automatically define aliases like the above, or perhaps use zsh `autoload` so the cost of actually loading the plugin is incurred when the user attempts to use the plugin, rather than at shell startup time.

Would love to hear what the scripting experts think about this idea.

**Comment by agoose77** [comment]
One "solution" to this is to use an async plugin manager like [`zinit`](https://github.com/zdharma/zinit). Its syntax is initially a little confusing as it is almost its own DSL, but it solves many of the problems outlined here. 

Here's [my dotfiles `.zshrc` script](https://github.com/agoose77/dotfiles/blob/master/oh-my-zsh/.zshrc.d/0300-omz.zsh) for loading OMZ. My pyenv plugin is [loaded separately](https://github.com/agoose77/dotfiles/blob/master/pyenv/.zshrc.d/0100-pyenv.zsh).

A user-defined `ZINIT_WAIT` environment variable can be set to `''` to prevent async loading in these scripts. This is useful in instances where one wants to force `zinit` to load everything in a synchronous call to zsh. I use this to install my dotfiles for the first time.

**Comment by mcornella** [comment]
This is now possible using the `omz` cli by using either `omz plugin load <plugin>`, which loads the plugin only on the current session, `omz plugin enable <plugin>`, which also adds it to the zshrc file, so it'll also be available in the next zsh session.
