### ISSUE TITLE
"^r" search not working

### ISSUE THREAD

**Issue by martinklepsch** [ohmyzsh/ohmyzsh#635]
For me the search is not working unless I manually do

```
  source ~/.zshrc
```

I have no idea why it is that way but actually the second line in [key-bindings.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh) does not make any sense to me.

I [already commented](https://github.com/robbyrussell/oh-my-zsh/commit/93af38f154174f8af9e2aa71a1a64bdc640c3655#commitcomment-576604) on the commit but no one noticed.

Please fix that as searching already executed commands is a very useful feature.

**Comment by liugaohua** [comment]
thanks close vi-mode well done

**Comment by ralphcallaway** [comment]
thanks to everyone on this thread, was very concerned when C-R spontaneously stopped working

at least on my system, i needed a slightly different syntax
`bindkey "^R" history-incremental-search-backward`

not sure why, but the following didn't work for me
`bindkey \C-R history-incremental-search-backward`

system is mac os x 10.14 (el capitan)
