### ISSUE TITLE
Arrow keys don't work properly in emacs mode

### ISSUE THREAD

**Issue by ax487** [ohmyzsh/ohmyzsh#6357]
When using a vanilla oh-my-zsh installation, pushing left / right arrow move words forward / backward rather than characters. If I switch to vim keybindings using `bindkey -v` the issue disappears.

I added also bound the up/down keys using
```

bindkey "^[[A" history-beginning-search-backward # Up
bindkey "^[[B" history-beginning-search-forward # Down
```

This binding works in emacs mode but not in vim mode.

**Comment by ljluestc** [comment]
To resolve the issue and ensure consistent behavior for keybindings in both modes, you can adjust your Zsh configuration with the following approach:

1. **Keybinding Mode Selection**: First, you need to ensure that you're consistently using the same keybinding mode (either emacs or vim) for both arrow keys and other custom keybindings.

2. **Keybinding Customization**: Depending on the keybinding mode you prefer (emacs or vim), customize the keybindings as needed.

For example, if you want to use emacs mode:

```zsh
# Set Zsh to emacs keybinding mode
bindkey -e

# Customize keybindings (example with Up and Down arrow keys)
bindkey "^[[A" history-beginning-search-backward # Up
bindkey "^[[B" history-beginning-search-forward # Down
```

If you want to use vim mode:

```zsh
# Set Zsh to vim keybinding mode
bindkey -v

# Customize keybindings (example with Up and Down arrow keys)
bindkey "^[[A" history-beginning-search-backward # Up
bindkey "^[[B" history-beginning-search-forward # Down
```

3. **Reload Your Shell Configuration**: After making changes to your Zsh configuration file (usually `~/.zshrc`), don't forget to reload your shell configuration for the changes to take effect:

```sh
source ~/.zshrc
```

By using either emacs or vim keybinding modes consistently, you can achieve the behavior you desire for arrow keys and other custom keybindings in your Zsh shell. Just make sure to choose the keybinding mode that suits your preferences.

**Comment by carlosala** [comment]
Thanks for the response! Just a tiny detail: to reload zsh, it's recommended to run `exec zsh` or `omz reload` in case you are in `omz`.
