### ISSUE TITLE
awk: invalid -v option [OS X Lion]

### ISSUE THREAD

**Issue by abh1nav** [ohmyzsh/ohmyzsh#640]
When attempting to auto-complete "./manage runserver" in a Django Project root folder, an awk error pops up:

(venv)➜  project git:(master) ./manage.py runs➜awk: invalid -v option

erver 

Although it manages to complete the option, it seems awk does not support the -v flag on OS X Lion.

**Comment by DingBowen123** [comment]
I fixed it by brew install gawk
