### ISSUE TITLE
Autocompletion isn't working with laravel5 plugin

### ISSUE THREAD

**Issue by cdarken** [ohmyzsh/ohmyzsh#6462]
The autocompletions for artisan from laravel5 plugin don't work in the current form. I think the issue is here: https://github.com/robbyrussell/oh-my-zsh/blob/e273cf004e1ff0510aee61416885f3003bcd15d9/plugins/laravel5/laravel5.plugin.zsh#L12-L16

I moved the compdef calls after the alias (also added another one for artisan) and now works.
It would help if somebody else is having this issue and can confirm.

**Comment by mcornella** [comment]
I can't reproduce this. Note that there has to be an `artisan` file found in the current working directory for the completion to work.
