### ISSUE TITLE
Respect ZDOTDIR across all Oh My Zsh

### ISSUE THREAD

**Issue by Shea690901** [ohmyzsh/ohmyzsh#6523]
I´ve noticed that **every** plugin referencing any zsh startup file assumes, that those are located in the users home directory, disregarding the possibility of setting ```ZDOTDIR``` to something else within ```/etc/zshenv```...
In fact there are only 3 files (lib/compfix.zsh, lib/diagnostics.zsh and oh-my-zsh.sh) that use ```ZDOTDIR```, while there are 45(!!!) files (not counting any readme's) referencing ```.zshrc```

**Comment by natemaia** [comment]
I would also like to see this addressed.

I've forked my own and patched a number of plugins for just this reason

**Comment by fox91** [comment]
Duplicate of #7052?

**Comment by Shea690901** [comment]
Not really, that's only 1 out of those 45 modules....

**Comment by robbyrussell** [comment]
Any chance someone would be keen to work on a PR for this?

**Comment by carlosala** [comment]
I'd say this is mostly done, at least in the `oh-my-zsh.sh`, `lib/` and `tools/`.
Plugins might still rely on `~/.zshrc`.
We'd kindly accept PRs fixing it!
Thanks!
