### ISSUE TITLE
Using putty, LEFT and RIGHT keys move cursor one word, instead of one char

### ISSUE THREAD

**Issue by guneemwelloeux** [ohmyzsh/ohmyzsh#6560]
Hello,

First things first: I like ZSH, and now I like it even more with Oh-my-zsh. Thanks for the great work!

I have looked for a solution to this for a few days now, but can't find a solution.
Admittedly, I do not understand how zle really works, same for bindkey. Same goes for the way terminal emulators send "control sequences", and what the "terminal type" means (xterm, versus xterm-256-color, and others). Same for the "Application mode"

### What I observe:
the left and right cursor keys move one whole word when I edit my command line. Home and End keys though, bring the cursro to the beginning and end of the line, as expected. This happens on putty running on Windows, but also on Terminator to that same machine running on Ubuntu 16.04

### What I would expect:
Left and right moves the cursor one single char. Home and end keys work fine.
Strangely enough, when I run Terminator on a local shell, the cursor keys work as I expect. The issue only happens when I ssh to another machine (where I have another user env)

### What I have found so far:
I think it is a bindkey issue. Zsh on my local machine works fine and is pretty clean, but on the remote machines I connect to, there is a lot of system-wide config that I inherit, including zshrc files.
Also, if I switch to vim mode using `bindkey -v`, rhe cursor keys behave as expected, but the Home and End keys now don't, they change letters to upper or lower case.

Any help that you could give would be greatly appreciated. If this is not the place for this question, could you please let me know where I can get the answers I'm looking for?

Many thanks
Will

**Comment by mcornella** [comment]
You can look up the bindkey sequence that left and right arrows produce by pressing `CTRL`+`V`, then the arrow. You can then use that sequence to look up what widget bindkey is set up to run.

For example, when I press `CTRL`+`V` followed by the left arrow, I get `^[OD`. If I run `bindkey '^[OD'` I get `"^[OD" backward-char`.

So once you have the bindkey sequences you can remap them to their proper widget:
```
bindkey LEFT-ARROW backward-char
bindkey RIGHT-ARROW forward-char
```

Post your results so I can look up why their not set up properly from the beginning.

**Comment by robbyrussell** [comment]
@guneemwelloeux might you have some time to help test @mcornella's recommended tests?
