### ISSUE TITLE
composer plugin is slow on startup

### ISSUE THREAD

**Issue by crhg** [ohmyzsh/ohmyzsh#6647]
I found that it takes more than 300ms on my mac to load composer plugin.

As a result of further examination, the composer command which is calling for path setting consumed most of the time.

```zsh
# Add Composer's global binaries to PATH
export PATH=$PATH:$(composer global config bin-dir --absolute 2>/dev/null)
```

```console
% time composer global config bin-dir --absolute >/dev/null 2>&1
composer global config bin-dir --absolute > /dev/null 2>&1  0.18s user 0.09s system 88% cpu 0.301 total
```

Since the output of `composer global config bin-dir --absolute` command does not change so frequently, I think that loading time can be shortened by caching.

**Comment by toby-griffiths** [comment]
I'm also having this issue this morning, after my Mac updated overnight.  Although my one is not loading at all (or at least taking > 1 minute).

**Comment by toby-griffiths** [comment]
It looks like the compose command is hanging for me.  I've tried re-installing using the install docs on the composer website but that's hanging too.

I've raised

**Comment by toby-griffiths** [comment]
Please ignore my last comment.  It turned out that my PHPStorm was listening for Xdebug requests, but didn't pop up to say it had intercepted the request.

I've updated my compose alias to include `-d xdebug.remote_autostart=0` to prevent this from happening.

Perhaps the `composer global config bin-dir --absolute` line mentioned by @crhg could be called with the `php -n` prefix to load without any extensions (although this is also without config… would this cause an issue?)?

**Comment by stucki** [comment]
It seems like a normal thing that `composer global config bin-dir --absolute` takes more than 1 second to run. For that reason I would consider reverting #5886.

As an alternative, I have created a PR #6664 which allows caching the output of this command.

**Comment by ricpelo** [comment]
I'm unable to reproduce this issue with Ubuntu 18.04.1 LTS and a very modest PC:

```sh 
$ time composer global config bin-dir --absolute >/dev/null 2>&1
composer global config bin-dir --absolute > /dev/null 2>&1  0,07s user 0,05s system 89% cpu 0,134 total
```

The command returns almost instantly, even the first time after reboot.

Maybe an installation/setup problem?

**Comment by CyrilMazur** [comment]
In my case the culprit was svn 🤷‍♂️ Turns out composer calls the `svn info --xml` command at startup, and svn is not installed on Catalina by default (and I don't use svn myself) and it took 1-2s for the OS to return. I installed svn via `brew install svn` and now composer is fast again.
