### ISSUE TITLE
Vagrant completion ignores `VAGRANT_CWD`

### ISSUE THREAD

**Issue by allanlewis** [ohmyzsh/ohmyzsh#6673]
Vagrant uses the value of the environment variable [`VAGRANT_CWD`][1] to determine its working directory; the default is the shell's working directory. `oh-my-zsh`'s completion doesn't appear to take account of this - the fix might be just to look for the `Vagrantfile` in `${VAGRANT_CWD:-.}`.

[1]: https://www.vagrantup.com/docs/other/environmental-variables.html#vagrant_cwd

**Comment by mcornella** [comment]
Can you submit a PR?

**Comment by allanlewis** [comment]
I'm still aware of this and I'd like to fix it, but I just don't have any time at the moment.

**Comment by unicolet** [comment]
let me give this a try, I have to fire up Vagrant anyways today :-)
