### ISSUE TITLE
.zsh_functions:161: defining function based on alias `chgext'

### ISSUE THREAD

**Issue by BrianGilbert** [ohmyzsh/ohmyzsh#6723]
I get the following error every time I open a terminal window
```
/Users/brian/.zsh_functions:161: defining function based on alias `chgext'
/Users/brian/.zsh_functions:161: parse error near `()'
```

Made the following change which seems to fix it, not sure yet if it causes any other issues:
```
# Batch change extension from $1 to $2
chgext() {
  for file in *.$1
  do
    mv $file $(echo $file | sed "s/\(.*\.\)$1/\1$2/")
  done
}
```
became
```
# Batch change extension from $1 to $2
function chgext {
  for file in *.$1
  do
    mv $file $(echo $file | sed "s/\(.*\.\)$1/\1$2/")
  done
}
```

**Comment by jhelblinghh** [comment]
Same here. Thanks for your workaround!

**Comment by rwaness** [comment]
This workaround does not register the new function `chgext` but keep in memory the previously registered alias also named `chgext` (because in bash alias have higher priority)
To fix this warning use `unalias chgext` above your function declaration
