### ISSUE TITLE
check_for_upgrade uses the wrong $PATH

### ISSUE THREAD

**Issue by thetrial** [ohmyzsh/ohmyzsh#6732]
# Updates broken – fatal: HTTP request failed

Hello,

since a while the update does not work when »[Oh My Zsh] Would you like to check for updates? [Y/n]:« comes:

> [Oh My Zsh] Would you like to check for updates? [Y/n]:
> Updating Oh My Zsh
> error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version while accessing https://github.com/robbyrussell/oh-my-zsh.git/info/refs?service=git-upload-pack
> fatal: HTTP request failed
> There was an error updating. Try again later?

This happens although I have a macports installed newer git (git version 2.17.0). OS is OSX 10.7.5.

If I then use »upgrade_oh_my_zsh« – everything works fine.

**Comment by mcornella** [comment]
Why does `upgrade_oh_my_zsh` work afterwards? Both ways run the same git command... Can you post what `env sh -c 'git --version'` shows?

**Comment by thetrial** [comment]
Output: git version 2.17.0 (as said before).

Well, I wonder, too … when this defect occured I updated git via macports. Before that I’d used the system’s git – that was too old. But now?

**Comment by mcornella** [comment]
Can you do a manual upgrade and see if it happens again? Just go to the OMZ directory (`cd $ZSH`) and run the git command: `git pull --rebase --stat origin master`.

**Comment by thetrial** [comment]
This is the output:

```
remote: Counting objects: 158, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 158 (delta 61), reused 63 (delta 61), pack-reused 94
Empfange Objekte: 100% (158/158), 42.46 KiB | 4.72 MiB/s, Fertig.
Löse Unterschiede auf: 100% (82/82), abgeschlossen mit 29 lokalen Objekten.
Von https://github.com/robbyrussell/oh-my-zsh
 * branch              master     -> FETCH_HEAD
   2ff9560a..4fec0a46  master     -> origin/master
Aktualisiere 2ff9560a..4fec0a46
Fast-forward
 README.md                                        |   2 +-
 lib/git.zsh                                      |   8 +--
 plugins/archlinux/README.md                      |  33 +++++++++++-
 plugins/archlinux/archlinux.plugin.zsh           |  66 ++++++++++++++++++++----
 plugins/django/django.plugin.zsh                 |   1 +
 plugins/docker-compose/_docker-compose           |  38 ++++++++++----
 plugins/docker-compose/docker-compose.plugin.zsh |   2 +
 plugins/emotty/emotty.plugin.zsh                 |   5 +-
 plugins/hanami/README.md                         |  32 ++++++++++++
 plugins/hanami/hanami.plugin.zsh                 |  19 +++++++
 plugins/jira/README.md                           |   1 +
 plugins/jira/_jira                               |   2 +-
 plugins/jira/jira.plugin.zsh                     |   2 +-
 plugins/kube-ps1/README.md                       |  76 ++++++++++++++++++++++++++++
 plugins/kube-ps1/kube-ps1.zsh                    | 123 +++++++++++++++++++++++++++++++++++++++++++++
 plugins/kubectl/kubectl.plugin.zsh               |   8 ++-
 plugins/npm/npm.plugin.zsh                       |   5 +-
 plugins/symfony2/symfony2.plugin.zsh             |   2 +
 plugins/vagrant/_vagrant                         |   4 +-
 plugins/web-search/web-search.plugin.zsh         |   2 +
 themes/avit.zsh-theme                            |   4 +-
 themes/cloud.zsh-theme                           |   4 +-
 themes/emotty.zsh-theme                          |   4 ++
 themes/rkj-repos.zsh-theme                       |  10 ++--
 tools/install.sh                                 |   2 +-
 25 files changed, 412 insertions(+), 43 deletions(-)
 create mode 100644 plugins/hanami/README.md
 create mode 100644 plugins/hanami/hanami.plugin.zsh
 create mode 100644 plugins/kube-ps1/README.md
 create mode 100644 plugins/kube-ps1/kube-ps1.zsh
Aktueller Branch master ist auf dem neuesten Stand.
```
It ran through without problems.

**Comment by mcornella** [comment]
This looks like the outcome of [GitHub's recent removal of weak crypto protocols](https://githubengineering.com/crypto-removal-notice/). Maybe they had some mixup on their end that made the error happen. If it still continues to occur even with the newer git version you should contact [the GitHub support team](https://github.com/contact?form[subject]=Crypto+removal+notice).

**Comment by thetrial** [comment]
This is the answer there. So, where can I find the exact scripts or – what script is running, what is the difference between automatic and manual?

> It looks like you need to make sure whatever script you're using has access to the latest version of Git. Can you clarify for me what specific Git command is run via the automated script that doesn't work versus what specific Git command you're running to manually update that does work?

**Comment by mcornella** [comment]
The script is [`tools/upgrade.sh`](https://github.com/robbyrussell/oh-my-zsh/blob/master/tools/upgrade.sh). You can add a `git --version` command by hand (remember to delete it after testing or you'll get git conflicts next time you update).

My guess is that it should return the newer version, since the PATH used is the same you have on your main shell. Regardless, let me know what you find.

**Comment by thetrial** [comment]
Now, this is interesting!

`Updating Oh My Zsh
error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version while accessing https://github.com/robbyrussell/oh-my-zsh.git/info/refs?service=git-upload-pack
fatal: HTTP request failed
There was an error updating. Try again later?`

And `git --version` gives:

`git version 1.7.12.4 (Apple Git-37)`

Huh?

**Comment by mcornella** [comment]
Ok try this one: `diff <(echo $PATH) <(echo 'echo $PATH' | env sh)`

**Comment by thetrial** [comment]
I don’t get any output with that.

**Comment by mcornella** [comment]
That means that your PATH and the one the script uses is the same, which is mindblowing. What does `which -a git` show? And what's your $PATH?

**Comment by thetrial** [comment]
$PATH:
`/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS`

`which -a git`:
```
/opt/local/bin/git
/usr/bin/git
```

**Comment by mcornella** [comment]
Ok let's try one more thing: `diff <(echo $PATH) <(zsh -fc 'echo $PATH')`. If that doesn't return anything I don't know what to tell you.

**Comment by thetrial** [comment]
I returns something, so you don’t have to leave me alone with my strange problem ;-)

```
1c1
< /opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS
---
> /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:/opt/local/bin:/opt/local/sbin
```

**Comment by mcornella** [comment]
Bingo!

So `/opt/local/bin` is added at the end of the `$PATH` when running the `check_for_upgrade.sh` script, which means that the old version of git is used.

```
/usr/bin:/bin:/usr/sbin:/sbin:[...]:/opt/local/bin:/opt/local/sbin
                                    ^^^^^^^^^^^^^^
```

This is a problem with the way we're running the update scripts. When running with `zsh -f`, we ignore the rc files and run zsh without customization, which makes it so that if `$PATH` is defined in one of the user rc files, zsh won't see it. We should probably fix that somehow, so I'm reopening this issue and marking it as a bug.

Nonetheless, we can still fix your problem by setting the right `$PATH` wherever it is that zsh reads when running with `-f`. Let's see what files are sourced: run `zsh -fv` and post the output.

**Comment by thetrial** [comment]
Output for `zsh -fv`:

```
# system-wide environment settings for zsh(1)
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
```

**Comment by thetrial** [comment]
Hm, spontaneously I don’t see the file here, too, but …

```
+/etc/zshenv:2> [ -x /usr/libexec/path_helper ']'
+/etc/zshenv:3> /usr/libexec/path_helper -s
+/etc/zshenv:3> eval 'PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:/opt/local/bin:/opt/local/sbin";' export 'PATH;'
+(eval):1> PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:/opt/local/bin:/opt/local/sbin
+(eval):1> export PATH
```

**Comment by mcornella** [comment]
Yeah, that's `/etc/zshenv`, so if you fix your PATH there you'll solve your particular case.

**Comment by mcornella** [comment]
You can add your modified PATH below those sentences:
```
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
```

**Comment by thetrial** [comment]
Thank you. But, due to there are several users per machine – before I switch all of them – is there plan to change the update mechanism of OMZ?

**Comment by thetrial** [comment]
Thank you. But, due to there are several users per machine – before I switch all of them – is there plan to change the update mechanism of OMZ?

**Comment by mcornella** [comment]
We're working on it but it won't be a fast process because it needs to be thoroughly tested.

**Comment by thetrial** [comment]
Though it’s strange that this happens … I put this sentence to these env-files on the machines … and it works now.

**Comment by mcornella** [comment]
Revisiting this: if `$PATH` is defined at the top of your zshrc file, then this bug shouldn't happen, since it is exported with the right value when running the upgrade script. That said, I think we can substitute the call with a simple `source $ZSH/tools/check_for_upgrade.sh` after #8939 has been merged.

**Comment by mcornella** [comment]
#9019 finally solves this by running the update check in the same zsh process. Please test it with `omz pr test 9019` and +1 it if it works correctly.
