### ISSUE TITLE
Label for the staged changes is missing in Avit theme

### ISSUE THREAD

**Issue by vstyle** [ohmyzsh/ohmyzsh#6735]
I like the Avit theme but one of the important for me feature is missing.
It would be great to see that I have staged changes in current git repository by marked it with some label and color, I have tried to add the following code lines to the theme file:

```
ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[white]%}$ "
ZSH_THEME_GIT_PROMPT_STASHED="%{$fg[white]%}$ "
```

but this didn't make the job.

**Comment by mcornella** [comment]
The avit theme uses `git_prompt_status` to get that information, and at the moment there is no feature to differentiate from staged to unstaged changes.

**Comment by mcornella** [comment]
I don't see a big need for differentiating staged files, at least in the near future. The stashed variable should work though, when there are stashed changes, wherever you put it in your zshrc file.
