### ISSUE TITLE
Propose to show `git log -p` before the upgrade

### ISSUE THREAD

**Issue by techtonik** [ohmyzsh/ohmyzsh#6989]
It is similar to #2971 but doesn't require any manual log housekeeping. Basically, modify:
```
[Oh My Zsh] Would you like to update? [Y/n]: 
```
to
```
[Oh My Zsh] Would you like to update? [Yng?]: ?
Yy - yes
Nn - no
Gg - show git log with patches
```

**Comment by robbyrussell** [comment]
Given that we've since replaced the updating process with a new formatting to show what changes have been made, I'm going to close this.

Would welcome some PR ideas for how we could, potentially, show what they _would_ be getting when they respond with Yes
