### ISSUE TITLE
Update prompt doesn't appear to work, or does and just repeatidly asks.

### ISSUE THREAD

**Issue by s3w47m88** [ohmyzsh/ohmyzsh#7042]
When I open iTerm on Mac and Terminal on Ubuntu, almost every time I get prompted "[Oh My Zsh] Would you like to update? [Y/n]:"

Every time I choose yes, but i continue to get the message.

I would expect this to only appear one time after installing OMZSH. Is this a bug?

This may be related to [this](https://github.com/robbyrussell/oh-my-zsh/issues/7036) issue.

**Comment by ccqpein** [comment]
We have different problems. Mine even do not appear update notification. OMZSH be designed update every two weeks (default) when you open new terminal after you updated.

It looks like `$UPDATE_ZSH_DAYS ` in you env be set too less. You can `echo $UPDATE_ZSH_DAYS` to check how many days of your duration.

**Comment by mcornella** [comment]
Is this still happening? Can you verify if after `upgrade_oh_my_zsh` and a restart of the shell the issue still persists?
