### ISSUE TITLE
gpg-agent plugin overwrites $SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by grawlinson** [ohmyzsh/ohmyzsh#7082]
https://github.com/robbyrussell/oh-my-zsh/blob/abca62add1a6d0ac34e697beac8682076d5c1dd7/plugins/gpg-agent/gpg-agent.plugin.zsh#L13
The above line doesn't check if `enable-ssh-agent` is actually enabled. It merely checks for the existence of the phrase.

The problem is if the phrase is present and commented out, it will trigger, e.g. `# enable-ssh-support allows gpg to act as a ssh agent`

Changing the grep command to `grep -qe '^enable-ssh-support' "$GNUPGCONFIG"` should eliminate this.

EDIT: I'd fork and open a PR, but the rate at which PRs are merged is a bit of a worry.

**Comment by mcornella** [comment]
Can you submit a PR? I'm going through issues faster now. There's also #7059 that could use a tester.
Thanks!
