### ISSUE TITLE
command-not-found-plugin: Doesn't print any error message for totally wrong commands on Ubuntu

### ISSUE THREAD

**Issue by ananthp** [ohmyzsh/ohmyzsh#7130]
I use `command-not-found` plugin. It prints helpful error messages as expected when a command is misspelled or if the necessary package is not installed. But, for totally wrong commands for which no suggested command/package is available, it prints no error messages at all.

Bash:
```
$ dklfjsldkfjs
dklfjsldkfjs: command not found
```
 
oh-my-zsh with command-not-found plugin:
```
$ dklfjsldkfjs
$ # no error message
```

**Comment by mcornella** [comment]
What system are you in?

**Comment by ananthp** [comment]
Ubuntu 18.04.1

**Comment by ananthp** [comment]
```
$ /usr/lib/command-not-found -- dklfjsldkfjs
dklfjsldkfjs: command not found

$ /usr/lib/command-not-found --no-failure-msg -- dklfjsldkfjs
$
```

**Comment by mcornella** [comment]
That's the issue then. You can report this as a bug [here](https://launchpad.net/ubuntu/+source/command-not-found/+bugs). In the meantime, disable the `command-not-found` plugin and copy-paste the code below at the end of your zshrc file:

```
if [[ -x /usr/lib/command-not-found ]] ; then
	if (( ! ${+functions[command_not_found_handler]} )) ; then
		function command_not_found_handler {
			[[ -x /usr/lib/command-not-found ]] || return 1
			/usr/lib/command-not-found -- ${1+"$1"} && :
		}
	fi
fi
```

**Comment by ananthp** [comment]
Fantastic! Your solution works. Thanks.

There's already a bug filed for this in [launchpad](https://bugs.launchpad.net/ubuntu/+source/command-not-found/+bug/1766068) with the same solution proposed as fix. Let's see where it goes.

**Comment by MoElaSec** [comment]
sadly this doesn't work with M1 ... having the exact same issue
