### ISSUE TITLE
[Good first PR] Add READMEs to undocumented plugins

### ISSUE THREAD

**Issue by mcornella** [ohmyzsh/ohmyzsh#7175]
_Register at [Hacktoberfest](https://hacktoberfest.digitalocean.com/) before submitting a Pull Request_

----

For some time we've had it in our minds to add a README to every plugin, as a way of documenting what the plugin does and what it requires, among other things. We have some READMEs already but most plugins lack one. That's why this issue exists, so you can take part in this effort.

You can have a look at [existing plugin READMEs](https://github.com/robbyrussell/oh-my-zsh/search?q=extension%3Amd+path%3Aplugins%2F) (the [yarn README is a great example](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/yarn/README.md)). Also you can find [a Markdown guide here](https://guides.github.com/features/mastering-markdown/).

The README should follow a very simple structure:

1. Name and brief description of what the plugin does. Links to relevant, essential websites.
   For example: the README for the `ant` plugin should link to the [ant project](https://ant.apache.org/).

2. How to enable the plugin. You can just copy-paste the excerpt below and substitute the word PLUGIN for the name of the plugin:<pre><code>To use it, add PLUGIN to the plugins array of your zshrc file:
\```
plugins=(... PLUGIN)
\```</code></pre>

3. Any other sections that document what the plugin does. Examples of that are: a l[ist of aliases, functions, or commands created](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/archlinux/README.md); a description of [settings that the plugin allows](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/ssh-agent/README.md#instructions); how to [build themes based on the plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/svn/README.md#usage-on-themes), ...

4. Optionally: a section with a list of contributors.

You'll need to read the `.plugin.zsh` file to know what the plugin does or, if there isn't one, the plugin will probably just add completion. You can also get what the plugin does by looking at the commits, or even the [plugins wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins).

If you want to work on the README for one of the following plugins, comment below and I'll mark it as such.

Thanks for your contribution and happy Hacktoberfest!

- [x] [ant](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/ant)
- [x] [autoenv](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/autoenv)
- [x] [autojump](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/autojump)
- [x] [autopep8](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/autopep8)
- [x] [aws](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/aws)
- [x] [battery](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/battery)
- [x] [bower](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/bower)
- [x] [brew](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/brew)
- [x] [bwana](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/bwana)
- [x] [cabal](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/cabal)
- [x] [cake](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/cake)
- [x] [cakephp3](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/cakephp3)
- [x] [capistrano](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/capistrano)
- [x] [catimg](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/catimg)
- [x] [celery](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/celery)
- [x] [chruby](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/chruby)
- [x] [chucknorris](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/chucknorris)
- [x] [cloudapp](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/cloudapp)
- [x] [codeclimate](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/codeclimate)
- [x] [colemak](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/colemak)
- [x] [colored-man-pages](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/colored-man-pages)
- [x] [colorize](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/colorize)
- [x] [command-not-found](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/command-not-found)
- [x] [common-aliases](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/common-aliases)
- [x] [compleat](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/compleat)
- [x] [composer](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/composer)
- [x] [cpanm](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/cpanm)
- [x] [dash](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/dash) ([website](https://kapeli.com/dash))
- [x] [debian](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/debian)
- [x] [dircycle](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/dircycle)
- [x] [dirhistory](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/dirhistory)
- [x] [dirpersist](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/dirpersist)
- [x] [django](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/django)
- [x] [doctl](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/doctl)
- [x] [eecms](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/eecms)
- [x] [emacs](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/emacs)
- [x] [emoji-clock](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/emoji-clock)
- [x] [emotty](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/emotty)
- [x] [encode64](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/encode64)
- [x] [fabric](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/fabric)
- [x] [fasd](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/fasd)
- [x] [fastfile](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/fastfile)
- [x] [fbterm](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/fbterm)
- [x] [fedora](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/fedora)
- [x] [gas](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gas)
- [x] [gem](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gem)
- [x] [gitfast](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gitfast)
- [x] [git-flow-avh](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/git-flow-avh)
- [x] [git-hubflow](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/git-hubflow)
- [x] [gitignore](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gitignore)
- [x] [git-prompt](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/git-prompt)
- [x] [git-remote-branch](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/git-remote-branch)
- [x] [glassfish](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/glassfish)
- [x] [gnu-utils](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gnu-utils)
- [x] [go](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/go)
- [x] [golang](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/golang)
- [x] [gpg-agent](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gpg-agent)
- [x] [gradle](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gradle)
- [x] [grails](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/grails)
- [x] [grunt](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/grunt)
- [x] [gulp](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gulp)
- [x] [helm](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/helm)
- [x] [heroku](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/heroku)
- [x] [homestead](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/homestead)
- [x] [iterm2](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/iterm2)
- [x] [iwhois](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/iwhois)
- [x] [jake-node](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/jake-node)
- [x] [jruby](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/jruby)
- [x] [jump](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/jump)
- [x] [kate](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/kate)
- [x] [kitchen](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/kitchen)
- [x] [knife](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/knife)
- [x] [knife_ssh](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/knife_ssh)
- [x] [kops](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/kops)
- [x] [kubectl](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/kubectl)
- [x] [laravel](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/laravel)
- [x] [laravel4](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/laravel4)
- [x] [laravel5](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/laravel5)
- [x] [lein](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/lein)
- [x] [lighthouse](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/lighthouse)
- [x] [lol](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/lol)
- [x] [macports](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/macports)
- [x] [magic-enter](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/magic-enter)
- [x] [man](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/man)
- [x] [minikube](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/minikube)
- [x] [mix](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/mix)
- [x] [mosh](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/mosh)
- [x] [mysql-macports](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/mysql-macports)
- [x] [n98-magerun](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/n98-magerun)
- [x] [nanoc](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/nanoc)
- [x] [node](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/node)
- [x] [nvm](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/nvm)
- [x] [nyan](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/nyan)
- [x] [oc](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/oc)
- [x] [otp](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/otp)
- [x] [pass](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/pass)
- [x] [paver](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/paver)
- [x] [pep8](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/pep8)
- [x] [perl](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/perl)
- [x] [phing](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/phing)
- [x] [pip](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/pip)
- [x] [pod](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/pod)
- [x] [postgres](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/postgres)
- [x] [pow](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/pow)
- [x] [powder](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/powder)
- [x] [powify](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/powify)
- [x] [profiles](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/profiles)
- [x] [pyenv](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/pyenv)
- [x] [pylint](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/pylint)
- [x] [python](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/python)
- [x] [rails](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/rails)
- [x] [rake](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/rake)
- [x] [rbenv](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/rbenv)
- [x] [rbfu](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/rbfu)
- [x] [rebar](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/rebar)
- [x] [redis-cli](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/redis-cli)
- [x] [rsync](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/rsync)
- [x] [ruby](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/ruby)
- [x] [rust](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/rust)
- [x] [rvm](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/rvm)
- [x] [safe-paste](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/safe-paste)
- [x] [sbt](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/sbt)
- [x] [scala](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/scala)
- [x] [screen](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/screen)
- [x] [sfffe](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/sfffe)
- [x] [singlechar](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/singlechar)
- [x] [sprunge](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/sprunge)
- [x] [stack](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/stack)
- [x] [sudo](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/sudo)
- [x] [supervisor](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/supervisor)
- [x] [suse](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/suse)
- [x] [svn-fast-info](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/svn-fast-info)
- [x] [symfony](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/symfony)
- [x] [symfony2](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/symfony2)
- [x] [systemadmin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/systemadmin)
- [x] [systemd](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/systemd)
- [x] [terminalapp](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/terminalapp)
- [x] [terminitor](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/terminitor)
- [x] [textmate](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/textmate)
- [x] [themes](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/themes)
- [x] [thor](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/thor)
- [x] [tmux](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/tmux)
- [x] [tmux-cssh](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/tmux-cssh)
- [x] [tmuxinator](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/tmuxinator)
- [x] [torrent](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/torrent)
- [x] [tugboat](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/tugboat)
- [x] [ubuntu](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/ubuntu)
- [x] [ufw](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/ufw)
- [x] [vagrant](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/vagrant)
- [x] [virtualenv](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/virtualenv)
- [x] [virtualenvwrapper](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/virtualenvwrapper)
- [x] [vundle](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/vundle)
- [x] [web-search](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/web-search)
- [x] [yii](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/yii)
- [x] [yum](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/yum)

**Comment by D-sha** [comment]
I submitted a template to ease this process, what do you think?
https://github.com/robbyrussell/oh-my-zsh/pull/7028

**Comment by grikomsn** [comment]
> I submitted a template to ease this process, what do you think?
> #7028

While having a template is great for most plugins, some doesn't even have any requirements or even configurations. Maybe if there's some kind of directory containing various readme templates for different kind of plugins, that'd be great. 😄

**Comment by mcornella** [comment]
> I'll give it a shot to the gitignore and aws ones!

Reserved!

> I have submitted a pull request about creating the readme for the `sudo` plugin

Thanks!

**Comment by grikomsn** [comment]
@mcornella, may I submit another pull request for other readmes? I'd love to complete two or more plugins. 😅

**Comment by mcornella** [comment]
You can do as many as you like :wink:

**Comment by mcornella** [comment]
> I would like to do python and tmux plugins.

Reserved

**Comment by alexandremjacques** [comment]
I can give a try on django plugin.

**Comment by mcornella** [comment]
Reserved.

**Comment by mcornella** [comment]
Don't hesitate to ask for directions!

**Comment by BrianMitchL** [comment]
I'll take the brew plugin

**Comment by denysdovhan** [comment]
Hi 👋 

I'd like to take `grunt`, `gulp`,  `node`, `nvm` and `web-search` plugins. Please, mark them as reserved.

**Comment by zwhitten** [comment]
I'll take the mix plugin

**Comment by mcornella** [comment]
> I'd like to take `grunt`, `gulp`, `node`, `nvm` and `web-search` plugins. Please, mark them as reserved.

Done! For the `web-search` plugin you can get inspiration from the `frontend-search` plugin.

> I'll take the mix plugin

Reserved.

**Comment by richardmoyer** [comment]
in an effort to get involved in open source and learn git i have completed README's for tmuxinator, chucknorris, suse, common-aliases and rsync. i am unsure how to proceed from here.

**Comment by mcornella** [comment]
> in an effort to get involved in open source and learn git i have completed README's for tmuxinator, chucknorris, suse, common-aliases and rsync. i am unsure how to proceed from here.

Reserved. You can create the READMEs from the github web interface. For example, you'd navigate to the chucknorris folder and create a new file named `README.md`, and paste your README in the box.

![image](https://user-images.githubusercontent.com/1441704/46367606-56d86000-c67e-11e8-9e54-07a6e47e7e90.png)

Then you commit it (make sure to preview first to check that it looks nice), and afterwards it'll give you the option of creating a pull request.

More resources:
- https://help.github.com/articles/creating-a-pull-request/
- https://help.github.com/articles/creating-a-pull-request-from-a-fork/

If you have made it using git, then [this guide](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) has a pretty comprehensive view of the steps you need to follow.

**Comment by mcornella** [comment]
One README per Pull Request please.

**Comment by zwhitten** [comment]
I can also update Ubuntu

**Comment by mcornella** [comment]
> I can also update Ubuntu

Reserved

**Comment by Byte7** [comment]
I can also update composer, debian, emoji-clock, pylint, virtualenv and pyenv. Please mar them as reserved.

**Comment by mcornella** [comment]
> I can also update composer, debian, emoji-clock, pylint, virtualenv and pyenv. Please mar them as reserved.

Done.

**Comment by grikomsn** [comment]
I have created a readme file for the `encode64` plugin (#7192).

**Comment by zwhitten** [comment]
I can also take gem and gradle

**Comment by sbmueller** [comment]
I'm going to have a look at macports 😊 please reserve for me

**Comment by soul-wish** [comment]
Hello! I'd like to take `encode64`. Please, reserve it for me 😉

**Comment by MasterOfTheTiger** [comment]
I am doing ruby.

**Comment by grikomsn** [comment]
I have created a readme file for `dircycle` plugin (#7213).

**Comment by soul-wish** [comment]
I've created PR's for `laravel`, `laravel4` and `laravel5` plugins.

**Comment by mcornella** [comment]
Merged all remaining. Thanks all!

**Comment by grikomsn** [comment]
\*sighs\* I have created a readme for the `lol` plugin, because why not. (#7231)

**Comment by sparsick** [comment]
I'll take kate and vagrant plugin.

**Comment by mcornella** [comment]
> *sighs* I have created a readme for the `lol` plugin, because why not. (#7231)
> 
> Edit: also made a readme for `catimg`. (#7232)

Merged.


> I will do dirhistory as well.

> I'll take kate and vagrant plugin.

Reserved. Godspeed!

**Comment by Anarcroth** [comment]
Hi! I can take on the emacs plugin

**Comment by ruduran** [comment]
I'll take the jump plugin.

**Comment by MasterOfTheTiger** [comment]
I just finished dirhistory in #7239.

**Comment by ForrestWeiswolf** [comment]
I'll make a readme for gitfast.

**Comment by sbmueller** [comment]
I can take over `vundle` as well.

**Comment by mjeromin** [comment]
I can take the pep8 and autopep8 plugins

**Comment by ivanovyordan** [comment]
I'll take the `autojump` plugin.

**Comment by kaltepeter** [comment]
I'll take the kubectl plugin

**Comment by mcornella** [comment]
> I've created PR's for `nyan` and `nanoc` plugins 😺

> I'll take the `autojump` plugin.

Merged.


> I'll take the kubectl plugin

Reserved.

**Comment by adri242** [comment]
I'll take the scala plugin

**Comment by ivanovyordan** [comment]
I'll take the `pass` plugin. I also misplaced my last README and will move it into the correct directory. Apologies for that.

**Comment by mcornella** [comment]
> I'll take the `pass` plugin. I also misplaced my last README and will move it into the correct directory. Apologies for that.

Reserved. And I just moved it, thanks for the heads up.

**Comment by mcornella** [comment]
Reminder that these READMEs are still pending:

@kashano:
- [aws](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/aws)
- [gitignore](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gitignore)

@Byte7:
- [composer](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/composer)
- [debian](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/debian)
- [pyenv](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/pyenv)
- [pylint](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/pylint)
- [tmux](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/tmux)
- [virtualenv](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/virtualenv)

@richardmoyer:
- [common-aliases](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/common-aliases)


Some of these plugins are hard to document. Remember that you can still get a quick thing done and submit the PR even if it's not totally done, just to ask for advice or clarification on particularities of the plugins.

**Comment by BrianMitchL** [comment]
Working on textmate

**Comment by jeff-chandler** [comment]
I can do the command-not-found plugin.  I plan on doing a few more, but I'll post more later.

**Comment by atchapcyp** [comment]
kitchen is on process.

**Comment by jeff-chandler** [comment]
I can do the systemadmin plugin

**Comment by Byte7** [comment]
> 
> 
> Reminder that these READMEs are still pending:
> 
> @kashano:
> 
>     * [aws](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/aws)
> 
>     * [gitignore](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gitignore)
> 
> 
> @Byte7:
> 
>     * [composer](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/composer)
> 
>     * [debian](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/debian)
> 
>     * [pyenv](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/pyenv)
> 
>     * [pylint](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/pylint)
> 
>     * [tmux](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/tmux)
> 
>     * [virtualenv](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/virtualenv)
> 
> 
> @richardmoyer:
> 
>     * [common-aliases](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/common-aliases)
> 
> 
> Some of these plugins are hard to document. Remember that you can still get a quick thing done and submit the PR even if it's not totally done, just to ask for advice or clarification on particularities of the plugins.

@mcornella Already sent PRs for pylint, virtualenv. I'll be doing the remaining ones too over this week.

**Comment by KaffDaddy** [comment]
Hi! For my first PR I would take the documentation of the gitignore-plugin. May you mark this as reserved for me? Thanks.

**Comment by ahaeber** [comment]
I've made PR #7325 with a brief description for the Helm plugin.

**Comment by dimensi0n** [comment]
I'll do the REAMDE.md for symfony2 ^^

**Comment by kashano** [comment]
Also minikube.

**Comment by dimensi0n** [comment]
You need to tick `þostgres` plugin

**Comment by jaythras** [comment]
Hi there! I will add the README for the  git-prompt plugin.

**Comment by Gopal9816** [comment]
Hi there! I'd like to take on the README for common-aliases

**Comment by revolter** [comment]
I added README for `colored-man-pages` in #7173.

**Comment by aakashjhawar** [comment]
I would like to work on pip.

**Comment by Kullsno2** [comment]
I am doing thor and pip.

**Comment by mcornella** [comment]
Reserved, go for it! Note that if you're doing this for Hacktoberfest, to qualify the PR should be submitted between October 1 and 31, and you should register at [Hacktoberfest](https://hacktoberfest.digitalocean.com) *before* opening the PR.

**Comment by Kullsno2** [comment]
> Reserved, go for it! Note that if you're doing this for Hacktoberfest, to qualify the PR should be submitted between October 1 and 31, and you should register at [Hacktoberfest](https://hacktoberfest.digitalocean.com) _before_ opening the PR.

Registered and will try to submit the PR on Oct 1st.

**Comment by dimensi0n** [comment]
I am doing redis-cli and perl

**Comment by Kullsno2** [comment]
> Reserved, go for it! Note that if you're doing this for Hacktoberfest, to qualify the PR should be submitted between October 1 and 31, and you should register at [Hacktoberfest](https://hacktoberfest.digitalocean.com) _before_ opening the PR.

https://github.com/robbyrussell/oh-my-zsh/pull/8185

**Comment by kennyheaton** [comment]
I'd like to work on the READMEs for the rake and rbenv plugins.

**Comment by vSanjo** [comment]
Can I claim `oc`?

**Comment by mcornella** [comment]
> I'd like to work on the READMEs for the rake and rbenv plugins.

Go ahead 😉

**Comment by mcornella** [comment]
> I am doing redis-cli and perl

All yours!

**Comment by zwhitten** [comment]
I can do `lein` and `jruby`

**Comment by zwhitten** [comment]
I can also do `rvm` and `rebar`

**Comment by Easybuoy** [comment]
I can do `yii`

**Comment by shubhaemk** [comment]
I can do for `terminitor`

**Comment by Rexben001** [comment]
I can do for `rust`

**Comment by shubhaemk** [comment]
>Added README to terminitor 

#8197

**Comment by shubhaemk** [comment]
> I can do for `terminitor`

Add README to terminitor plugin

#8197

**Comment by ajmorozoff** [comment]
I can take `ufw`

**Comment by flowin** [comment]
I'd like to do `knife`, `knife-ssh`, `minikube`, `pass` and `screen`.

**Comment by austinratcliff** [comment]
Hey there! 👋 I'll do `dash`.

**Comment by favorable-mutation** [comment]
Howdy! I've got one for Tugboat: https://github.com/robbyrussell/oh-my-zsh/pull/8207

**Comment by adityakaria** [comment]
Hey everyone! I'd like to work on the READMEs for the `paver` and `mysql-macports` plugins. Thanks!

**Comment by yunior05** [comment]
Hey there! I'd like to do `compleat`

**Comment by noahjacknichols** [comment]
I can do tugboat and textmate

**Comment by sk1u** [comment]
I can do Dash!

**Comment by dimensi0n** [comment]
Redis -> #8214 And Perl -> #8215

**Comment by sk1u** [comment]
Will also do `virtualenvwrapper`

**Comment by titusjaka** [comment]
I'll take `pow` and `powify`.

**Comment by joeratt** [comment]
Looked like pyenv was claimed last year but wasn't done. I did that in #8224 (sorry - backwards in claiming)

**Comment by mcornella** [comment]
> Hey there! 👋 I'll do `dash`.

@austinratcliff another user did it first. Choose another one.

**Comment by austinratcliff** [comment]
@mcornella Ah yeah that one got away from me. 😅 I'll do CloudApp today instead. 👍

**Comment by mcornella** [comment]
Reserved 😉

**Comment by otherpaco** [comment]
As both were copy and paste I took

- sprunge
- terminalapp

sorry for claiming afterwards and thanks for oh-my-zsh

**Comment by otherpaco** [comment]
I would do **singlechar** if not taken

**Comment by Chaitanya-Raj** [comment]
doing one for compleat if not taken

**Comment by noahjacknichols** [comment]
I can do sprunge.

**Comment by otherpaco** [comment]
@noahjacknichols I made a pull request for that 2 days ago. Mine was very basic, so maybe you want to check it out and improve it and make your pull request from there.

https://github.com/robbyrussell/oh-my-zsh/pull/8231

**Comment by KirillDemtchenko** [comment]
Hello. 

Create for **emotty** https://github.com/robbyrussell/oh-my-zsh/pull/8240

**Comment by KirillDemtchenko** [comment]
also, make for fbterm

**Comment by jotaro-sama** [comment]
Hi! I made one for the rust plugin at #8242

**Comment by flowin** [comment]
screen -> [#8256](https://github.com/robbyrussell/oh-my-zsh/pull/8256)

**Comment by sofiarivas** [comment]
I'll take `git-remote-branch`

**Comment by deltaclock** [comment]
eecms at #8277

**Comment by mzuehlke** [comment]
`magic-enter` -> #8284

**Comment by mzuehlke** [comment]
supervisor -> #8285

**Comment by lchrzaszcz** [comment]
Hi! I've added documentation for powder https://github.com/robbyrussell/oh-my-zsh/pull/8310

**Comment by lchrzaszcz** [comment]
I've added documentation for profiles https://github.com/robbyrussell/oh-my-zsh/pull/8311

**Comment by abitrolly** [comment]
`fasd` and `dirpersist` are fixed.

**Comment by mcornella** [comment]
Last README merged in d99ddab0cadfbb047f23b5d2037b54b4f4437ae4. This issue is now officially closed. Thanks everyone who chimed in! 🎉
