### ISSUE TITLE
Oh-my-zsh & tmux outputting unexpected messages 

### ISSUE THREAD

**Issue by RangerPzy** [ohmyzsh/ohmyzsh#7234]
I generated a ssh key by 'ssh-keygen' yesterday and later when I start new sessions for tmux, tmux output something related to SSH, but I know really know what that is. I used 'grep' to search and got this:

![image](https://user-images.githubusercontent.com/30824931/46526642-68f61080-c8c1-11e8-84f0-ba993423579a.png)

**My question:**
 1, Why this message is shown?
 2, How can I disable the message?

**Other info**
Running debian, it's WSL installed form Microsoft's store a few weeks ago, I think it's up to date:)

**Comment by mcornella** [comment]
To be clear, the message you're referring to is `Could not open a connection...` and the part above it? That looks like ssh-agent trying to start, you must have a line in your zshrc file running ssh-agent without `eval`-ing it. See https://stackoverflow.com/a/17848593/5798232

**Comment by RangerPzy** [comment]
Adding 'ssh-agent' to '.zshrc' simply causes zsh **prints the similar messages twice.** And I'm sure the first  3 lines are from 'ssh-agent'. I noticed that every time I start a new session in tmux, it starts 'ssh-agent' so I end up with a pile of ssh-agent when I type 'ps -e|grep ssh-agent'. 

**After reboot my Windows everything gets right.**

However, I'm curious about what happened-**it seems that neither the plugin 'ssh-agent.plugin.zsh' or tmux itself will try to start 'ssh-agent', and 'ssh-agent' never check if there is already a running agent.**

**New question:**

1. Why 'ssh-agent' is needed when I start a new session of tmux via zsh?
2. Why 'ssh-agent' never checks to avoid duplicate?

**Anyway thanks for your help:)**

**Comment by mcornella** [comment]
What I mean is that there must be some place in your zshrc file where you call ssh-agent. Look it up or post it here for reference.
