### ISSUE TITLE
django plugin - does not work with python2/python3

### ISSUE THREAD

**Issue by OranShuster** [ohmyzsh/ohmyzsh#7298]
~Using tab completion with `python manage.py <tab>` works but not with~
~`python2 manage.py <tab>` or~
~`python3 manage.py <tab>`~

~Debian 8~
~zsh version zsh 5.0.7 (x86_64-pc-linux-gnu)~
~oh-my-zsh version 489be24~

After updating to the latest zsh (zsh 5.6.2 (x86_64-pc-linux-gnu)
oh-my-zsh version 30125e1
`python manage.py <tab>` - works
`python2 manage.py <tab>` - works
`python3 manage.py <tab>` - **does not work**

**Comment by dimensi0n** [comment]
Django plugin only adds autocompletion for `python` command. That's why you don't have any autocompletion for python2 and python3. @OranShuster

**Comment by marcelogdeandrade** [comment]
I can try to change the plugin so it accepts `python2` and `python3` aswell.

**Comment by marcelogdeandrade** [comment]
Using `python2` and `python3` as prefixes seems to work with me.

zsh version : 5.4.2

**Comment by OranShuster** [comment]
marcelo is correct. it seems to be a bug with old zsh versions.
I installed the latest version from source since 5.0.7 was the newest for debian 8

**Comment by OranShuster** [comment]
reopening this and editing the OP - 
with the new zsh version, python and python2 works but not python3

**Comment by ikhomutov** [comment]
Works for me with fresh omz and zsh v.5.7.1 (arch linux). Should consider to close this issue.

**Comment by OranShuster** [comment]
tested it on zsh 5.7.1 and omz 664664f6 on a macos and it works. closing this issue
