### ISSUE TITLE
Wild Card not expanding. 

### ISSUE THREAD

**Issue by haccks** [ohmyzsh/ohmyzsh#7315]
On running   

```
port installed *jupyter*
```
I get this error
```
zsh: no matches found: *jupyter*
```

I tried quoting and backslashing the `*` and it worked and returns the following  

```
port installed '*jupyter*'

The following ports are currently installed:
  py27-jupyter @1.0.0_1 (active)
  py27-jupyter_client @5.2.3_1 (active)
  py27-jupyter_console @5.2.0_0 (active)
  py27-jupyter_core @4.4.0_0 (active)
  py36-jupyter @1.0.0_1 (active)
  py36-jupyter_client @5.2.3_1 (active)
  py36-jupyter_console @5.2.0_0 (active)
  py36-jupyter_core @4.4.0_0 (active)

**Comment by haccks** [comment]
Then one should expect the same behaviour with `ls *.txt`, but this works without quotes. In fact adding quotes gives the error  
```
ls: *.txt: No such file or directory
```

**Comment by mcornella** [comment]
ls doesn't accept wildcard arguments, that's why it's the shell's job to expand it and then pass the matched filenames to ls.
