### ISSUE TITLE
when typing history -c  the result is ➜  ~  history -c fc: event not found: -c

### ISSUE THREAD

**Issue by googya** [ohmyzsh/ohmyzsh#739]
when typing history -c  the result is 
➜  ~  history -c fc: event not found: -c

I donot understand the result . Is my oh-my-zsh setting wrong? 
I install the command with ➜  ~  wget --no-check-certificate https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sh  and change nothing...

It may be a bug!!

**Comment by mcornella** [comment]
Hi everyone, I pushed a solution at #3422, hopefully you can take a look and +1 if it works well

**Comment by miguelpalazzo** [comment]
I know this is very old, but had the same issue with `history -c` and login to `bash`, typing it and exit was more than enough for me.

**Comment by crsuarez** [comment]
you could to this as a workaround.
```
[csuarez@centosdev:~] % truncate -s 0 $HISTFILE 
[csuarez@centosdev:~] % echo $HISTFILE         
/home/csuarez/.zsh_history
[csuarez@centosdev:~] % cat /home/csuarez/.zsh_history
: 1443547857:0;echo $HISTFILE
: 1443547861:0;cat /home/csuarez/.zsh_history
[csuarez@centosdev:~] % 

```

**Comment by atooy** [comment]
fc: event not found :-c

**Comment by atooy** [comment]
fc: event not found: -c            and i can't delete the file .zsh_history...(didn't use sudo permission, afraid there will be something wrong if i delete this file.)

**Comment by mcornella** [comment]
You can safely delete the file, it will be recreated next time you start the terminal.

**Comment by atooy** [comment]
Appreciate ur reply! It did recreated and the history was cleared!

**Comment by nsarafa** [comment]
this bug still persists. anybody find a workaround?

**Comment by atooy** [comment]
Just delete the file .zsh_history and the history shall be gone.    (not so much a bug as a difference between bash and zsh...i think)

**Comment by KANGOD** [comment]
OMG, from Dec 11, 2011 to Nov 6, 2016, 5 years but the problem is still here!
At least, could you please provide equivalent arguments for `fc`? Something like `fc --reset` for `history --reset`, `fc --clear` for `history --clear`.
Must we deal with the .zsh_history file? This may be a solution for `history -c`, but obviously not for `history -r`.

**Comment by mcornella** [comment]
There's a PR pending to be tested by more people that fixes both `history -c` and `history -r`. Feel free to take a look: https://github.com/robbyrussell/oh-my-zsh/issues/739#issuecomment-68559653

**Comment by keeferrourke** [comment]
Fun fact: it's Sept 2017, and this is this still an issue. `history -c` does not work with oh-my-zsh.

**Comment by notmike-5** [comment]
can't you just `cat /dev/null >| $HISTFILE`?

**Comment by tholu** [comment]
It seems that this also causes a problem with `history -d`:
```
➜  ~ history -d 1
fc: event not found: -d
```

**Comment by anmolnagpal** [comment]
Seems it's still an issue on Sept 2018 :)

**Comment by mcornella** [comment]
`history -c` works, `history -d` might fail but that's a separate issue.

**Comment by tholu** [comment]
```
➜  ~ which history
history: aliased to fc -l 1
➜  ~ zsh --version
zsh 5.6.1 (x86_64-apple-darwin17.7.0)
➜  ~ ohmyzsh --version
1.28.0-insider
29e6dce4352db76d8956035990b8630580226588
x64
```

It worked after upgrading with `upgrade_oh_my_zsh`!

```
➜  ~ which history
history: aliased to omz_history
```

The `--version` flag still shows the same though, am I doing it wrong?

```
➜  ~ ohmyzsh --version
1.28.0-insider
29e6dce4352db76d8956035990b8630580226588
x64
```

**Comment by mcornella** [comment]
> `history -c` works, `history -d` might fail but that's a separate issue.

Confirmed that `history -d` also works with the latest version.

**Comment by andreamoro** [comment]
It doesn's seem to work on a Mac OS Catalina though. I receive the history output starting from the line number used as an offset.

**Comment by mcornella** [comment]
Can you open a new issue with details?

**Comment by John-JV** [comment]
rm ~/.zsh_history       
 
then close the terminal when you comeback it's gone
