### ISSUE TITLE
zle reset-prompt breaks tab completion for multi-line prompts

### ISSUE THREAD

**Issue by jonatan-ivanov** [ohmyzsh/ohmyzsh#7393]
I'm not sure if this is the issue with zle, zsh or oh-my-zsh but I'm getting a very weird behavior when I reset my prompt with `zle reset-prompt`.  I'm trying to asynchronously update my prompt so that I'm running `zle reset-prompt` quite frequently, this is an example `.zshrc` which reproduces the issue:
```
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME='avit'
source $ZSH/oh-my-zsh.sh

TMOUT=1
TRAPALRM() { zle reset-prompt }
```
When I try to use tab completion and navigate between the options, the cursor goes up and shows the actual completion option. I think it is easier to see this in action so I recorded it with asciinema:
[![asciicast](https://asciinema.org/a/210524.svg)](https://asciinema.org/a/210524)

It seems the issue only happens when I'm using a theme which has multi-line prompts which I would like to.

**Comment by mcornella** [comment]
This doesn't happen anymore in recent zsh versions (tested in 5.7.1), so I'll close this for now. Reopen if you don't agree.
