### ISSUE TITLE
add-zsh-hook: function definition file not found

### ISSUE THREAD

**Issue by wazum** [ohmyzsh/ohmyzsh#748]
_hiya!_
after the last update I get

/Users/hugo/.oh-my-zsh/lib/termsupport.zsh:32: add-zsh-hook: function definition file not found
/Users/hugo/.oh-my-zsh/lib/termsupport.zsh:33: add-zsh-hook: function definition file not found

kind regards
Wolfgang

**Comment by fanenr** [comment]
This is because your usr/share/zsh was deleted. You can solve it by reinstalling zsh. For example on ubuntu: sudo apt install --reinstall zsh。

**Comment by FullStackEmpire** [comment]
How to solve it?
I got a same issue
