### ISSUE TITLE
Ctrl Left/Right on different Terminals

### ISSUE THREAD

**Issue by HyP3r-** [ohmyzsh/ohmyzsh#7484]
I like to use `ctrl+left/right` for jumping between the words in the current command line.

Here is a list of different key codes `ctrl+left` and `ctrl+right` can look like in some of my enviroments:

- Native (just the Linux Kernel booted with `init=/bin/bash`): `^[[D` (ctrl+left), `^[[C` (ctrl-right)
- KDE Terminal: `^[[1;5D` (crtl-left), `^[[1;5C` (ctrl-right)
- Connected with PuTTy from Windows to a Linux Machine: `^[OD` (crtl-left), `^[OC` (ctrl-right)
- Connected with PuTTy from Windows to a Linux Machine running tmux: `^[[D` (crtl-left), `^[[C` (ctrl-right)

I don't know why those different terminals have such different key codes for the same thing. And more importantly: I often can not fix it (not my server, only connected once, ...).

The contributors of the ZIM - Zsh IMproved FrameWork have solved this problem by just binding all those key codes to the same method (backward-word/forward-word): https://github.com/zimfw/zimfw/blob/master/modules/input/init.zsh#L49

So can you please add those key codes to this project: https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh#L52

Update: to solve this problem @apjanke has implemented a function `omz_bindkey` which tries to set the correct keycode depending on the plattform (https://github.com/robbyrussell/oh-my-zsh/pull/5113/commits/a4fbf19a9eb1f3b9de3813c7dd4e5617347bae3e#diff-c546ebbd64ee74cd521ae613d82123a3R94). So please merge this pull request or copy those lines of the ZIM - Zsh IMproved FrameWork project.

**Comment by robbyrussell** [comment]
Hey there, I'm doing a bit of housekeeping on the project. Thanks for raising this issue—we always love a good edge case! 😄

However, it's not gathering much community interest, so I'm going to close it for now. Don't let this discourage you! We're all for hearing about the weird things. We can't commit to spending too much time tracking each weird thing down ourselves.

**Comment by HyP3r-** [comment]
It's okay that you're closing the ticket. For me, with the Remote Desktop Manager from Devolutions as an SSH client under Windows and a remote ZSH shell with Oh-My-Zsh, everything works perfectly in the meantime. The problem has resolved itself for me, so to speak. Unfortunately, I don't know exactly why.
