### ISSUE TITLE
Oh-my-zsh containers plug-ins (podman & buildah)

### ISSUE THREAD

**Issue by hhlp** [ohmyzsh/ohmyzsh#7489]
Could you please include the following plug-ins to your project:

1. Podman -> https://podman.io/
2. Buildah -> https://buildah.io/

Regards.,

**Comment by doblak** [comment]
@edsantiago added Podman completion to [containers/libpod](https://github.com/containers/libpod/blob/master/completions/zsh/_podman)

Should we add a copy in a similar manner as it's done for [docker](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/docker)? Not sure how to properly include license info though.

**Comment by Houuse** [comment]
any update here?

**Comment by sidahmed-malaoui** [comment]
I would love to see this in oh-my-zsh too.

**Comment by agilob** [comment]
I added PR with support for podman https://github.com/ohmyzsh/ohmyzsh/pull/9275

**Comment by mrcomoraes** [comment]
Workaround for podman:

```bash
mkdir -p $ZSH_CUSTOM/plugins/podman/
podman completion zsh -f $ZSH_CUSTOM/plugins/podman/_podman
```

**Comment by mhalano** [comment]
I think Podman plugin is easier to do, since it's almost a copy-paste-adapt from docker plugin. BTW, Docker auto-complete doesn't work if you are using the `podman-docker` tool because the version isn't compatible. Just a thing I noted and that's another reason to have a `podman` plugin.

**Comment by fatmalama** [comment]
podman's completion is excellent but FYI buildah's is totally broken or non existant 🥲
