### ISSUE TITLE
Hard to separate `ahead` or `behind` from `git_remote_status`

### ISSUE THREAD

**Issue by weiguoz** [ohmyzsh/ohmyzsh#7502]
git_remote_status => origin/develop2
we can't tell if there is a branch named `develop2` in remote
or local branch `develop` ahead 2 commits to `remote/develop`

**Comment by robbyrussell** [comment]
Hey there, I'm doing a bit of housekeeping on the project. Thanks for raising this issue—we always love a good edge case! 😄

However, it's not gathering much community interest, so I'm going to close it for now. Don't let this discourage you! We're all for hearing about the weird things. We can't commit to spending too much time tracking each weird thing down ourselves.
