### ISSUE TITLE
Suggestions pushes prompt to right

### ISSUE THREAD

**Issue by MarcLV** [ohmyzsh/ohmyzsh#7526]
When I for example start writing `ls -` and then press tab to see possible parameters etc, a space is created and everything is pushed a bit to the right and duplicates what I've already written (in this case `ls -    *BLANK SPACE*     ls -`)

![screenshot 2019-01-17 at 15 07 17](https://user-images.githubusercontent.com/1162046/51324250-86af4600-1a6a-11e9-9b8f-aeba86ff00b2.png)

I've tried this without any themes and its still an issue.. please help me! :) 
Its super annoying

**Comment by sago2k8** [comment]
I have the same issue 
<img width="1440" alt="screen shot 2019-01-27 at 10 59 52 pm" src="https://user-images.githubusercontent.com/15184213/51814045-60b64c80-2287-11e9-8339-cdaeac6e868c.png">

**Comment by qdoobp** [comment]
Same here. Also happens when typing `cd ` and pressing tab for folder selection/completion.

**Comment by iMouath** [comment]
https://github.com/robbyrussell/oh-my-zsh/issues/7426#issuecomment-456253584

**Comment by qdoobp** [comment]
Changing the LC_ALL locale sadly did not solve my problem.

**Comment by MarcLV** [comment]
Mine neither..

> Changing the LC_ALL locale sadly did not solve my problem.

**Comment by mcornella** [comment]
What `locale -a` do you have available, and what is your `locale`?

**Comment by qdoobp** [comment]
I have a lot of locales available (53 for UTF-8, I can add them all, if you like), but I have the following in my zshconfig:
```
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
```
I verified that those two are available

**Comment by mcornella** [comment]
Which theme are you using? Is it multiline? Can you modify your zshrc file to the minimal setup that still triggers this issue (disable plugins, config, other stuff that is irrelevant)?

**Comment by qdoobp** [comment]
Yes, I am using a multiline prompt with the spaceship theme (version 3.11.0).
I disabled everything and I am still experiencing the issue.
My configuration for this test is as follows:
```
export ZSH="/Users/me/.oh-my-zsh"

ZSH_THEME="spaceship"
SPACESHIP_NODE_SHOW="false"
SPACESHIP_DIR_TRUNC="5"
SPACESHIP_DIR_COLOR="004"
SPACESHIP_GIT_BRANCH_COLOR="011"

# Example aliases
alias zshconfig="vim ~/.zshrc"
alias zshsource="source ~/.zshrc"

COMPLETION_WAITING_DOTS="true"

HIST_STAMPS="dd.mm.yyyy"

source $ZSH/oh-my-zsh.sh

export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
```
I hope this helps in trackig down the issue.

**Comment by qdoobp** [comment]
I just tested it with the bira theme and had the same problem. Might be a general multiline issue.

**Comment by mcornella** [comment]
Can you check if commenting out `COMPLETION_WAITING_DOTS` fixes it?

**Comment by qdoobp** [comment]
Yes. That did it. Thank you for the help 😃

**Comment by mcornella** [comment]
This fell out of my radar. The `COMPLETION_WAITING_DOTS` setting now uses a different function which only prints a character. Try it out now.

**Comment by mcornella** [comment]
I'm going to close this now, but reopen or comment if the issue persists with the current version.
