### ISSUE TITLE
Line editing unusable near large directories

### ISSUE THREAD

**Issue by david-morris** [ohmyzsh/ohmyzsh#7549]
When I try to edit a history item which refers to a non-git directory with 242698 files in it, as soon as I type the `/`, zsh stops visually updating the line being edited.  By hitting enter with `-xv` set and waiting over a minute, I could get the following sequence of events:

```
~/t/a/recognition> ls -U img | head | xargs -I _ file img/_
ls -U img | head | xargs -I _ file img/_
+preexec:0> neatPwd
+neatPwd:1> pwd
+neatPwd:1> sed $'\ns#^/home/morris#~#\ns#\\([^/]\\)[^/]*/#\\1/#g'
+preexec:0> title 'ls -U img | head | xargs -I _ file img/_' '~/t/a/recognition'
+title:2> local a='ls -U img | head | xargs -I _ file img/_'
+title:5> a=+title:5> print -Pn '%40>...>ls -U img | head | xargs -I _ file img/_'
+title:5> a=+title:5> tr -d '\n'
+title:5> a='ls -U img | head | xargs -I _ file img/_'
+title:6> case screen-256color (screen*)
+title:8> print -Pn '\e]2;ls -U img | head | xargs -I _ file img/_ @ ~/t/a/recognition\a'
+title:9> print -Pn '\ekls -U img | head | xargs -I _ file img/_\e\'
+title:10> print -Pn '\e_~/t/a/recognition   \e\'
+_zsh_highlight_preexec_hook:2> typeset -g _ZSH_HIGHLIGHT_PRIOR_BUFFER=''
+_zsh_highlight_preexec_hook:3> typeset -gi _ZSH_HIGHLIGHT_PRIOR_CURSOR=''
+fizsh:22> ls '--color=auto' -U img
+fizsh:22> head
+fizsh:22> xargs -I _ file img/_
img/0710.0422-Figure-7_6.png: PNG image data, 12 x 15, 8-bit/color RGB, non-interlaced
img/1004.3467-Figure-5_27.png: PNG image data, 10 x 13, 8-bit/color RGB, non-interlaced
img/0909.5125-Figure-10_110.png: PNG image data, 9 x 7, 8-bit/color RGB, non-interlaced
img/0903.2138-Figure-2_37.png: PNG image data, 11 x 10, 8-bit/color RGB, non-interlaced
img/0803.0342-Figure-8_157.png: PNG image data, 14 x 11, 8-bit/color RGB, non-interlaced
img/1007.1014-Figure-2_1.png: PNG image data, 26 x 14, 8-bit/color RGB, non-interlaced
img/0910.5865-Figure-2_183.png: PNG image data, 3 x 7, 8-bit/color RGB, non-interlaced
img/1001.3270-Figure-13_166.png: PNG image data, 30 x 15, 8-bit/color RGB, non-interlaced
img/0707.0227-Figure-1_28.png: PNG image data, 16 x 17, 8-bit/color RGB, non-interlaced
img/0807.3014-Figure-6_77.png: PNG image data, 10 x 9, 8-bit/color RGB, non-interlaced
+precmd:1> neatPwd
+neatPwd:1> pwd
+neatPwd:1> sed $'\ns#^/home/morris#~#\ns#\\([^/]\\)[^/]*/#\\1/#g'
+precmd:1> title fizsh '~/t/a/recognition'
+title:2> local a=fizsh
+title:5> a=+title:5> print -Pn '%40>...>fizsh'
+title:5> a=+title:5> tr -d '\n'
+title:5> a=fizsh
+title:6> case screen-256color (screen*)
+title:8> print -Pn '\e]2;fizsh @ ~/t/a/recognition\a'
+title:9> print -Pn '\ekfizsh\e\'
+title:10> print -Pn '\e_~/t/a/recognition   \e\'
+_zsh_highlight_main__precmd_hook:1> _zsh_highlight_main__command_type_cache=( )
+fizsh:23> /home/morris/.fizsh/fizsh-prompt.zsh
```

I don't see information about line-editing here, is it possible to print debug information about that?

Being able to work without auto-complete in large directories would be a great feature for people working with big data.

**Comment by thomaskilian** [comment]
I simply have this issue in my Mac Terminal when I recall the last long command that runs over the end. When going back with the cursor the cursor position gets hick-ups (either it is one line too high or shifted some chars). Only way around is to make the window so wide that the command fits one one line. Also there's an issue with the long lines that in the very front it creates (two) zombie characters (duplicates of the first two chars in the command).

**Comment by mcornella** [comment]
It's possible zsh-syntax-highlighting is doing something under the hood. Try disabling that and see if the problem is gone.

**Comment by thomaskilian** [comment]
Would you give me a hand and show me me where/how to do that?

**Comment by mcornella** [comment]
Oh I was talking to the OP.

In your case, does your zsh stop updating the line? It sounds like the typical case of a prompt with utf8 characters while using a `locale` that is not utf8-enabled.

**Comment by thomaskilian** [comment]
Never mind :-) I working with a regular Mac Terminal program and using zsh just vanilla once I installed it. There is definitely no utf8 in my prompt. I was really wondering that (almost) nobody else sees this issue. It happens when a recalled line is too long and starts to wrap (and probably under other circumstances). If you can tell me how to disable the highlighting I'll test that.

**Comment by mcornella** [comment]
If you have enabled highlighting you should probably be able to see it in your zshrc file, see the install instructions at [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting). But I don't think that's it.

Could you maybe record an [asciinema](https://asciinema.org/) session so I can see exactly how it happens?

**Comment by thomaskilian** [comment]
Just shoot me. But once I started asciinema the recall just behaved as it should have. :-/

**Comment by mcornella** [comment]
[Here are the install instructions for OMZ](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md#oh-my-zsh), if you have zsh-syntax-highlighting in your plugins array then you have it. Otherwise you probably don't.

**Comment by thomaskilian** [comment]
Ah, ok. I had a git plugin which I disabled. But, as you said, it didn't stop the bugger.

**Comment by thomaskilian** [comment]
After uninstalling OMZ it turned out that this is basically a ZSH bug.

**Comment by mcornella** [comment]
Reopen if this is still an issue and can prove that it only happens with OMZ.
