### ISSUE TITLE
New NordVPN Plugin

### ISSUE THREAD

**Issue by alaeschaik** [ohmyzsh/ohmyzsh#7561]
This plugin should allow the user to easily connect to a VPN server through more concise aliases.

@robbyrussell let me know if you would be interested

**Comment by izaac** [comment]
Now NordVPN is way more popular than in 2019. This would be a good plugin addition

**Comment by robbyrussell** [comment]
We got this with https://github.com/ohmyzsh/ohmyzsh/pull/7902
