### ISSUE TITLE
Why don't Ctrl+Backspace and Ctrl+Delete work?

### ISSUE THREAD

**Issue by m93a** [ohmyzsh/ohmyzsh#7609]
It is standard in UI applications to have Ctrl+Backspace delete a word before the cursor (`backwards-kill-word`) and Ctrl+Delete delete a words after the cursor (`kill-word`). In Oh-My-ZSH I can use Alt+Backspace and Ctrl+W for the former and there doesn't seem to be an alternative for the latter. Why is that?

It is very easy to implement the standard behavior, I could just add these lines to `lib/key-bindings.zsh`:
```
bindkey '^H' backward-kill-word
bindkey '^[[3;5~' kill-word
```
But before doing so, I'm interested whether there is a reason not to add this.

**Comment by Pheric** [comment]
Just learned this, and I've been using computers for 13 years now. Thank you.

And now I'm wondering the same. Bump

**Comment by mcornella** [comment]
Note: `^H` is also the key binding for `CTRL-H` which is used frequently in vi keymaps to backward-delete-char. Removed the change from `viins` and `vicmd` in 39c00732.

**Comment by tjx666** [comment]
Why `alt + backspace` doesn't work in my terminal.

**Comment by sisrfeng** [comment]
Can terminal disinguish ctrl+backspace  vs ctrl+H?

**Comment by mcornella** [comment]
It can't, that's why the change was backtracked: https://github.com/ohmyzsh/ohmyzsh/issues/7609#issuecomment-669169358.

**Comment by gfukushima** [comment]
This still happens on macBooks, is there a fix for this?
