### ISSUE TITLE
Vi mode breaks special characters ( Home, End, Delete, Backspace)

### ISSUE THREAD

**Issue by gudrutis** [ohmyzsh/ohmyzsh#7610]
Experienced on: MacOs and Fedora26.
Zsh works fine untill I turn on Vi mode ( either by `set -o vi` or `bindkey -v`).

No `bindkey` solutions worked for me.

**Comment by aymanbagabas** [comment]
try using `-M vicmd` in your `bindkey`
I have the following in my config
```
# allow delete, home and end keys to work in normal mode
if [[ "${terminfo[khome]}" != "" ]]; then
  bindkey -M vicmd "${terminfo[khome]}" beginning-of-line      # [Home] - Go to beginning of line
fi
if [[ "${terminfo[kend]}" != "" ]]; then
  bindkey -M vicmd "${terminfo[kend]}"  end-of-line            # [End] - Go to end of line
fi
if [[ "${terminfo[kdch1]}" != "" ]]; then
  bindkey -M vicmd "${terminfo[kdch1]}" delete-char            # [Delete] - delete forward
fi
```

Backspace works fine for me

**Comment by mcornella** [comment]
I can no longer reproduce this. I think we fixed that in `lib/key-bindings.zsh` in ec70c0c393e53004b885d146dd77b9a3f136971a.
