### ISSUE TITLE
git aware prompt always incorrect

### ISSUE THREAD

**Issue by jamie-campbelll** [ohmyzsh/ohmyzsh#7638]
Hi,

I am using zsh running in terminator on WSL. I find that using any git aware oh-my-zsh prompt theme will give incorrect git status which constantly changes. Here is an example of some prompts in a new repo, all I have done is pressed <CR> again each time I have a new prompt.
![image](https://user-images.githubusercontent.com/25767561/53917279-167d7380-405c-11e9-8c43-8fb96dc584ff.png)

The git status shows a mixture of untracked, unstaged, staged and conflicted statuses. I will often get a 130 return code from doing nothing.

Jon

**Comment by mcornella** [comment]
In which themes does that happen?

**Comment by jonathancampbell-firsthelpline** [comment]
This happens in any theme that has a git prompt, the one pictured is "sunrise".

**Comment by mcornella** [comment]
Run `typeset -f -t custom_git_prompt` to enable tracing of the custom git prompt function and try to reproduce the same problem; then capture the output and post it here.

**Comment by jonathancampbell-firsthelpline** [comment]
This was from a clean working directory:

```
+custom_git_prompt:1> ref=+custom_git_prompt:1> git symbolic-ref HEAD                                                                                                                                              
+custom_git_prompt:1> ref=refs/heads/master 
+custom_git_prompt:2> parse_git_dirty
+parse_git_dirty:1> local STATUS=''
+parse_git_dirty:2> local -a FLAGS
+parse_git_dirty:3> FLAGS=( --porcelain ) 
+parse_git_dirty:4> [[+parse_git_dirty:4> git config --get oh-my-zsh.hide-dirty
+parse_git_dirty:4> [[ '' != 1 ]]
+parse_git_dirty:5> [[ 1 -gt 0 ]]
+parse_git_dirty:6> FLAGS+='--ignore-submodules=dirty' 
+parse_git_dirty:8> [[ '' == true ]]
+parse_git_dirty:11> STATUS=+parse_git_dirty:11> git status --porcelain '--ignore-submodules=dirty'
+parse_git_dirty:11> STATUS=+parse_git_dirty:11> tail -n1
+parse_git_dirty:11> STATUS='' 
+parse_git_dirty:13> [[ -n '' ]]
+parse_git_dirty:16> echo ''
+custom_git_prompt:2> git_prompt_ahead
+git_prompt_ahead:1> [[+git_prompt_ahead:1> git_current_branch
+git_current_branch:1> local ref
+git_current_branch:2> ref=+git_current_branch:2> git symbolic-ref --quiet HEAD
+git_current_branch:2> ref=refs/heads/master 
+git_current_branch:3> local ret=0
+git_current_branch:4> [[ 0 != 0 ]]
+git_current_branch:8> echo master
+git_prompt_ahead:1> [[+git_prompt_ahead:1> git rev-list origin/master..HEAD
+git_prompt_ahead:1> [[ -n '' ]]
+custom_git_prompt:2> custom_git_prompt_status
+custom_git_prompt_status:1> INDEX=+custom_git_prompt_status:1> git status --porcelain
+custom_git_prompt_status:1> INDEX='' 
+custom_git_prompt_status:2> STATUS='' 
+custom_git_prompt_status:4> echo ''
+custom_git_prompt_status:4> grep '--color=auto' '^?? '

+custom_git_prompt_status:7> echo ''
+custom_git_prompt_status:7> grep '--color=auto' '^UU '

+custom_git_prompt_status:10> echo ''
+custom_git_prompt_status:10> grep '--color=auto' '^ D '

+custom_git_prompt_status:13> echo ''
+custom_git_prompt_status:13> grep '--color=auto' '^.M '

+custom_git_prompt_status:15> echo ''
+custom_git_prompt_status:15> grep '--color=auto' '^AM '

+custom_git_prompt_status:16> STATUS=$'%{\C-[[22;31m%}M' 
+custom_git_prompt_status:21> echo ''
+custom_git_prompt_status:21> grep '--color=auto' '^D  '

+custom_git_prompt_status:24> echo ''
+custom_git_prompt_status:24> grep '--color=auto' '^R'

+custom_git_prompt_status:27> echo ''
+custom_git_prompt_status:27> grep '--color=auto' '^M'

+custom_git_prompt_status:30> echo ''
+custom_git_prompt_status:30> grep '--color=auto' '^A'

+custom_git_prompt_status:34> echo -n $'%{\C-[[22;31m%}M'
+custom_git_prompt_status:34> grep '--color=auto' '.*'

+custom_git_prompt_status:35> STATUS=$' %{\C-[[22;31m%}M' 
+custom_git_prompt_status:38> echo $' %{\C-[[22;31m%}M'
+custom_git_prompt:2> echo $'%{\C-[[22;33m%}‹master %{\C-[[22;31m%}M%{\C-[[22;33m%}›%{\C-[[00m%} '
```

**Comment by jonathancampbell-firsthelpline** [comment]
I have updated oh-my-zsh today and the issue seems to be gone. Thanks for the help anyway!

**Comment by jonathancampbell-firsthelpline** [comment]
I have been having this issue on and off for a few weeks again. The setup and symptoms are the same as before, I have updated oh my zsh with no luck. Here is the output from `typeset -f -t custom_git_prompt` on a clean state, with the prompt returning a green A for a staged new file where there was none.

--- code/api-load-test ‹feature/run-in-ec2-linux-box› » typeset -f -t custom_git_prompt
+custom_git_prompt:1> ref=+custom_git_prompt:1> git symbolic-ref HEAD                                                                                                                                              
+custom_git_prompt:1> ref=refs/heads/feature/run-in-ec2-linux-box 
+custom_git_prompt:2> parse_git_dirty
+parse_git_dirty:1> local STATUS
+parse_git_dirty:2> local -a FLAGS
+parse_git_dirty:3> FLAGS=( --porcelain '--ignore-submodules=dirty' ) 
+parse_git_dirty:4> [[+parse_git_dirty:4> git config --get oh-my-zsh.hide-dirty
+parse_git_dirty:4> [[ '' != 1 ]]
+parse_git_dirty:5> [[ '' == true ]]
+parse_git_dirty:8> STATUS=+parse_git_dirty:8> git status --porcelain '--ignore-submodules=dirty'
+parse_git_dirty:8> STATUS=+parse_git_dirty:8> tail -n1
+parse_git_dirty:8> STATUS='' 
+parse_git_dirty:10> [[ -n '' ]]
+parse_git_dirty:13> echo ''
+custom_git_prompt:2> git_prompt_ahead
+git_prompt_ahead:1> [[+git_prompt_ahead:1> git_current_branch
+git_current_branch:1> local ref
+git_current_branch:2> ref=+git_current_branch:2> git symbolic-ref --quiet HEAD
+git_current_branch:2> ref=refs/heads/feature/run-in-ec2-linux-box 
+git_current_branch:3> local ret=0
+git_current_branch:4> [[ 0 != 0 ]]
+git_current_branch:8> echo feature/run-in-ec2-linux-box
+git_prompt_ahead:1> [[+git_prompt_ahead:1> git rev-list origin/feature/run-in-ec2-linux-box..HEAD
+git_prompt_ahead:1> [[ -n '' ]]
+custom_git_prompt:2> custom_git_prompt_status
+custom_git_prompt_status:1> INDEX=+custom_git_prompt_status:1> git status --porcelain
+custom_git_prompt_status:1> INDEX='' 
+custom_git_prompt_status:2> STATUS='' 
+custom_git_prompt_status:4> echo ''
+custom_git_prompt_status:4> grep '--color=auto' '^?? '

+custom_git_prompt_status:7> echo ''
+custom_git_prompt_status:7> grep '--color=auto' '^UU '

+custom_git_prompt_status:10> echo ''
+custom_git_prompt_status:10> grep '--color=auto' '^ D '

+custom_git_prompt_status:13> echo ''
+custom_git_prompt_status:13> grep '--color=auto' '^.M '

+custom_git_prompt_status:15> echo ''
+custom_git_prompt_status:15> grep '--color=auto' '^AM '

+custom_git_prompt_status:17> echo ''
+custom_git_prompt_status:17> grep '--color=auto' '^ T '

+custom_git_prompt_status:21> echo ''
+custom_git_prompt_status:21> grep '--color=auto' '^D  '

+custom_git_prompt_status:24> echo ''
+custom_git_prompt_status:24> grep '--color=auto' '^R'

+custom_git_prompt_status:27> echo ''
+custom_git_prompt_status:27> grep '--color=auto' '^M'

+custom_git_prompt_status:30> echo ''
+custom_git_prompt_status:30> grep '--color=auto' '^A'

+custom_git_prompt_status:31> STATUS=$'%{\C-[[22;32m%}A' 
+custom_git_prompt_status:34> echo -n $'%{\C-[[22;32m%}A'
+custom_git_prompt_status:34> grep '--color=auto' '.*'

+custom_git_prompt_status:35> STATUS=$' %{\C-[[22;32m%}A' 
+custom_git_prompt_status:38> echo $' %{\C-[[22;32m%}A'
+custom_git_prompt:2> echo $'%{\C-[[22;33m%}‹feature/run-in-ec2-linux-box %{\C-[[22;32m%}A%{\C-[[22;33m%}›%{\C-[[00m%} '
--- code/api-load-test ‹feature/run-in-ec2-linux-box A› »

**Comment by mcornella** [comment]
Can you also post the output of `git status --porcelain` when that happens?

**Comment by jonathancampbell-firsthelpline** [comment]
To be clear this is still an ongoing issue, 
![image](https://user-images.githubusercontent.com/25767561/76115513-32558580-5fe0-11ea-85b3-c7a9652e3ab8.png)
![image](https://user-images.githubusercontent.com/25767561/76115559-48634600-5fe0-11ea-8d40-92db0eeab4cb.png)

**Comment by mcornella** [comment]
I don't see anything wrong in the second screenshot (btw, always post terminal contents in text form). Can you try to post the trace for an instance where the prompt info is incorrect?
