### ISSUE TITLE
git completion not working

### ISSUE THREAD

**Issue by cpojer** [ohmyzsh/ohmyzsh#766]
git completion is not working. "git checkout bTAB" always tries to complete file names instead of branches etc.

I'm using git via homebrew (brew install git), version 1.7.8. It is located in /usr/local/Cellar/git/1.7.8

My .zshrc is pretty standard, the only plugin I have activated is "git"

**Comment by bitoiu** [comment]
Same issue:

```
zsh 5.0.5 (x86_64-apple-darwin14.0)
```

**Comment by rockshandy** [comment]
I have been having similar issues very recently as @bitoiu after an update (same version string).

**Comment by mcornella** [comment]
Try #4444, there is a conflict with current `git-extras` completion. If you disable the `git-extras` plugin and it works, that's the problem.

**Comment by rockshandy** [comment]
That fixed it for me (actually just updated today)! Thanks.

**Comment by fiznool** [comment]
I've just experienced the same issue, using the `git` and `github` plugins (no `git-extras`).

My fix is to add this at the bottom of my `.zshrc`:

``` bash
# Fix hub alias
unalias git
function git() { hub $@; }
```

**Comment by anrao91** [comment]
My fix for this issue - 
1)Add this line in the ~/.zshrc file. 
2)source ~/git-completion.bash #Provided you have the git-completion.bash file saved and has contents
3)Then execute -
$~/.zshrc
4)$ZSH

**Comment by NicoSa** [comment]
@fiznool 

`# Fix hub alias
unalias git
function git() { hub $@; }`

This did it for me.
