### ISSUE TITLE
The position of caret is different when I type text and when I don't.

### ISSUE THREAD

**Issue by hwooo** [ohmyzsh/ohmyzsh#7725]
![pic1](https://user-images.githubusercontent.com/46282492/55425272-073b0880-55bd-11e9-9d56-1d378317c602.PNG)
![pic2](https://user-images.githubusercontent.com/46282492/55425275-099d6280-55bd-11e9-8b23-c62ad6842e51.PNG)

Is there any way to fix caret's position?

**Comment by mcornella** [comment]
What does running `locale` and `locale -a` show?

**Comment by NDelt** [comment]
locale:
```
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

locale -a:
```
C
C.UTF-8
POSIX
en_US.utf8
```

**Comment by mcornella** [comment]
Is it possible you're using `COMPLETION_WAITING_DOTS` set up? Can you post your zshrc file?

**Comment by NDelt** [comment]
Yes, I can use `COMPLETION_WAITING_DOTS` option. I'm not sure why, but after I enable that option, my issue has eased a little.

**Comment by mcornella** [comment]
Provide more information:
- terminal emulator
- `zsh --version`
- theme
- zshrc file

**Comment by NDelt** [comment]
* terminal emulator: Hyper (Windows Subsystem for Linux)
* `zsh --version`: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
* theme: agnoster
* zshrc file: https://gist.github.com/NDelt/0423dc7e3434889772fc607d78049e69

**Comment by mcornella** [comment]
Can you try the regular terminal emulator to rule out a Hyper issue? I can't reproduce your problem with the same setup.
