### ISSUE TITLE
[oh-my-zsh] plugin 'lwd' not found

### ISSUE THREAD

**Issue by madorb** [ohmyzsh/ohmyzsh#7751]
Starting this morning, i noticed that every new terminal started outputting `[oh-my-zsh] plugin 'lwd' not found`. I've run `upgrade_oh_my_zsh` and have the latest version.

**Comment by mcornella** [comment]
Exactly, the error message is new but the failure is old as time itself :wink:

**Comment by jordan-miguel** [comment]
Has anyone managed to fix this...seems like it wasn't from the comments. 
I am constantly seeing the below -

![Screenshot 2020-07-30 at 16 12 27](https://user-images.githubusercontent.com/14114089/88940282-7c851f00-d27f-11ea-95c8-55f833460c76.png)
