### ISSUE TITLE
Prefixing name of the currently activated  virtualenv to amuse theme. 

### ISSUE THREAD

**Issue by dkaushik94** [ohmyzsh/ohmyzsh#7766]
I have a suggestion for a minute change. In the amuse theme, which is pretty minimal, it doesn't show my current virtual environment name of if I have an environment activated. I  edited the theme file and it shows it now. This is my first attempt to contribute and I was wondering if I should go ahead and get a PR. Any hint and help would be great as to if and how I should proceed. Thanks! @robbyrussell 
<img width="342" alt="Screen Shot 2019-04-13 at 6 45 06 PM" src="https://user-images.githubusercontent.com/9155142/56086412-6cdc8f80-5e1c-11e9-8f1c-8a8661371a7a.png">

**Comment by mcornella** [comment]
It the modifications don't change the look when there is no virtualenv environment activated then go ahead and submit a PR; otherwise that would make it not backwards-compatible and therefore warrant a new theme.

**Comment by Ricocotam** [comment]
Hi, any news on this ?
I'm new here and I'd like to have my venv properly printed too. I can fix it but I don't even know where to begin

**Comment by mcornella** [comment]
You can edit the amuse theme yourself and submit a PR, @dkaushik94 isn't responding.

You'll want to edit [the PROMPT variable or RPROMPT](https://github.com/ohmyzsh/ohmyzsh/blob/01bfb57446fdc77e8b4ae696729688284392c0e6/themes/amuse.zsh-theme#L13-L17) if you want the virtualenv information to appear on the right side. To show the virtualenv, you can use `virtualenv_prompt_info` function that [the virtualenv plugin](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/virtualenv/virtualenv.plugin.zsh) provides, or you can make a specific function inside the amuse theme yourself. 

To understand what all these `%*` characters mean inside the PROMPT variable, see [Prompt Expansion](zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html). Let me know if I can be of further help.

**Comment by snugglej** [comment]
@mcornella is someone going to do this? If not, I would be happy to work on it.

**Comment by dkaushik94** [comment]
I am going to do a PR this week. If you are done before that please go-ahead and close this thread when you do. Thanks. :)

**Comment by snugglej** [comment]
@dkaushik94 I made a pull request for my version which should be a match to what you have in the opening comment. I tested it on my system and it seems to work fine with no problems and doesn't change the rendered text when not being used.

Without:
![image](https://user-images.githubusercontent.com/17776110/78746524-b7f48a00-792c-11ea-88c4-be366d8799ea.png)

With:
![image](https://user-images.githubusercontent.com/17776110/78746546-c8a50000-792c-11ea-994e-d5d41243e3e4.png)

**Comment by dkaushik94** [comment]
@snugglej If your PR gets approved, then please go ahead close this issue out!

**Comment by Ricocotam** [comment]
You can add an updated clock to the PR if you want. I coded it [here](https://gist.github.com/Ricocotam/7a102106f5ed4bcb663809fcb569ee52). If you know a better way of coding it feel free to adapt, I did it fast and crappy.
