### ISSUE TITLE
Cursor position

### ISSUE THREAD

**Issue by asunyer90** [ohmyzsh/ohmyzsh#7798]
Dear, I have problems with cursor position.
Sometimes, for example when I paste, if I put the cursor on the top of a letter, and I write something, it will not write on the position I have marked, it will write that one or two positions on the left. It's something very similar to https://github.com/robbyrussell/oh-my-zsh/issues/3325 but now only happens when pasting...

**Comment by mcornella** [comment]
Can you post an [asciinema recording](https://asciinema.org/) of this happening, as well as your zshrc file?

**Comment by cellcoresystems** [comment]
I also had a lot of trouble to set up Powerline on iTerm2 and also oh-my-zsh and just recently bought a Chromebook and I had the same issue like you.

SOLUTION:
Use the right fonts -> https://github.com/wernight/powerline-web-fonts

No Problem with hterm or iTerm or any other terminal emulator.
Use one of those fonts with zsh and you will be happy :o)

Cheers guys.
