### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by mattfordham** [ohmyzsh/ohmyzsh#786]
I can't seem to uninstall. I get this error:

zsh: command not found: uninstall_oh_my_zsh

Any ideas?

Thanks!

**Comment by alvinkatojr** [comment]
Was this issue ever fixed, am getting something similar: 

<code>-bash: uninstall_oh_my_zsh: command not found</code>

**Comment by mcornella** [comment]
@alvinkatojr it seems that you are running that from `bash`. You should be running zsh instead... Try running `zsh` and then `uninstall_oh_my_zsh`.

Notice though that @mattfordham's issue is very old, particularly from when OMZ was still very recent.

**Comment by alvinkatojr** [comment]
Hi @mcornella, thanks for the response. I have managed to get the issue fixed by deleting the ohmyzsh directory and reinstalling zsh. Everything is working fine now! 

Thanks for the clarification!

**Comment by mcornella** [comment]
Cool! Glad to be of service :smile:

**Comment by alvinkatojr** [comment]
:+1: :)
