### ISSUE TITLE
Problems with the cyrillic

### ISSUE THREAD

**Issue by galstudio** [ohmyzsh/ohmyzsh#7874]
After the last update, there were problems with the Cyrillic alphabet. And insert text with Cyrillic.
I have ubuntu 16.04 and until the last update there were no problems.

The text is inserted the second time:  `Ѓ<a3>идео^[[200~Ѓ<b2>идео~`

**Comment by galstudio** [comment]
Decided this is all due to zsh

**Comment by mcornella** [comment]
Have you enabled the `safe-paste` plugin?

**Comment by mcornella** [comment]
If running `zsh -f` the characters are correctly pasted, this might be traceable back to OMZ (check that you haven't enabled the `safe-paste` plugin). Otherwise this is possibly an issue with the terminal emulator app.
