### ISSUE TITLE
when typing history -r the result is ➜ ~ history -r fc: event not found: -r

### ISSUE THREAD

**Issue by greg0ire** [ohmyzsh/ohmyzsh#789]
I created this bug report because of this comment :
https://github.com/robbyrussell/oh-my-zsh/issues/739#issuecomment-3283206

**Comment by gkop** [comment]
Not sure why this is closed. Anyhow, I found it best to just forget about the history alias and drop to fc:

    $ fc -lr 1

Or for my purposes:

    $ fc -li 1

**Comment by nsarafa** [comment]
One workaround is to modify your ~/.zsh_history file directly and save your changes. Restart your terminal, and you should find your history has been modified per your changes to your ~/.zsh_history file
