### ISSUE TITLE
No spaces in command prompt when using tmux

### ISSUE THREAD

**Issue by seanM29** [ohmyzsh/ohmyzsh#7955]
I pulled **pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-runtime** from Docker Hub, and install tmux and zsh in this docker.

At first, after I start tmux, it displays an extra space in tmux, I added the following to ~/.zshrc:
```
export LC_ALL=en_US.UTF-8 
export LANG=en_US.UTF-8
```
and added the following to .tmux.conf:
```
set -g utf8
set-window-option -g utf8 on
```
However, after I start tmux, there is no space in command prompt:

![jQMQ3](https://user-images.githubusercontent.com/13976974/60084772-bb869e00-976a-11e9-9340-8f9433de00ea.png)

**Comment by mcornella** [comment]
Are those locales installed? Run `locale -a` to check.

**Comment by seanM29** [comment]
@mcornella 
The results of running locale show below:
![image](https://user-images.githubusercontent.com/13976974/60113876-3b315e80-97a5-11e9-9a80-49458fdcdd0f.png)

**Comment by mcornella** [comment]
Try with
```
export LANG=en_US.utf8
export LC_ALL=en_US.utf8
```

If that doesn't fix it, it could be an issue with your terminal emulator: https://github.com/robbyrussell/oh-my-zsh/issues/6007.
