### ISSUE TITLE
Symfony plugin not working with zsh-syntax-highlighting

### ISSUE THREAD

**Issue by lukepass** [ohmyzsh/ohmyzsh#7958]
**Describe the bug**
Hello, after the last update of all my Oh My Zsh plugins the Symfony plugin is not highlighted by zsh-syntax-highlighting. Please see my specific issue:

[Aliases are not highlighted #617](https://github.com/zsh-users/zsh-syntax-highlighting/issues/617)

**To Reproduce**
1. Enable plugin sf
2. Enable plugin zsh-syntax-highlighting
3. Write `sf [...]` in the root of a Symfony project

**Expected behavior**
When using `sf` in a symfony project the alias is highlighted in green.

**Screenshots or recordings**
![image](https://user-images.githubusercontent.com/6429961/60159603-df41f680-97f3-11e9-972a-3d6b1e8a1981.png)

In this post, the user @phy1729 suggested to rewrite the alias:

[https://github.com/zsh-users/zsh-syntax-highlighting/issues/617#issuecomment-505267091](https://github.com/zsh-users/zsh-syntax-highlighting/issues/617#issuecomment-505267091)

Thanks.

**Comment by robbyrussell** [comment]
Hey there, I'm doing a bit of housekeeping on the project. Thanks for raising this issue—we always love a good edge case! 😄

However, it's not gathering much community interest, so I'm going to close it for now. Don't let this discourage you! We're all for hearing about the weird things. We can't commit to spending too much time tracking each weird thing down ourselves.
