### ISSUE TITLE
Clear Command Not Working Properly

### ISSUE THREAD

**Issue by born-curious** [ohmyzsh/ohmyzsh#7959]
a. Describe the bug:
"clear" command is not working Properly on switching the tabs. 

b. To Reproduce:
Steps to reproduce the problem ( make sure you have only 1 tab in the terminal right now ):
1. Clear a tab. 
2. Add a new tab to the terminal - cmd + T
3. Switch back to the tab where you cleared the screen. 
4. See error, screen wont be cleared.

c. Expected behavior:
Screen should remain clear

d. System:
 - OS: macOS
 - Zsh version - 5.7.1
 - Terminal emulator - iTerm2

**Comment by mcornella** [comment]
I can't reproduce. Does the `clear` work before switching tabs? Also, what version of macOS and iTerm2 are you using? Can you also try pressing `CTRL`+`L` instead of running `clear`?

**Comment by larson-carter** [comment]
@born-curious I just tested this on my Mac, running Catalina 15.1, with latest ZSH version, this is no longer an issue, i'll be it I was never able to test with your exact setup, however it is functioning like it is supposed to now!
