### ISSUE TITLE
vi-mode / and ? override to search within current line

### ISSUE THREAD

**Issue by jessebett** [ohmyzsh/ohmyzsh#7976]
The primary reason I use the vi-mode plugin is to easily navigate and edit long commands. However, the default search behaviour for `/` and `?` is to search through the command history, which I already have through `FZF`. I'd like to override this current history search to instead search through the current command, moving the cursor to the result.

Further, can you provide what I need to include in the zshrc to override the default `/`, `?` , `n` and `N` to have vim-mode search achieve this behaviour.

**Comment by cognifloyd** [comment]
when I want to do this, I use `v` from normal mode to enter visual mode. That opens a vi editor where I can use all of the power of vi to edit my more complex command.

**Comment by jessebett** [comment]
Hi @cognifloyd 

Is that default behaviour? If I escape to normal mode and press `v` it italicizes the character I'm currently over (iterm). If I open another terminal client `v` has no effect.

**Comment by cognifloyd** [comment]
I'm on linux. I use Konsole and the linux console. In vi-editing-mode, in both zsh and bash, and in both Konsole terminal emulator and in the raw linux console, pressing `v` in normal (esc) mode has opened vim for as long as I can remember.
It does that when I'm connected to my local Gentoo linux machine, and to remote CentOS linux machines. If that doesn't work elsewhere, that's a surprise to me. :) I'll have to make sure to stay on linux so my finger muscle memory continues to serve me here.

**Comment by jessebett** [comment]
@cognifloyd I just checked and `v` has no effect on any of my other terminal clients including Alacritty or Kitty, so I do not suspect this is an issue with the emulator.

**Comment by mcornella** [comment]
> I'd like to override this current history search to instead search through the current command, moving the cursor to the result.

I don't know if a zle widget exists to search the current command and move the cursor to the result. Changing a key binding is just as easy as using `bindkey`, so the commands would be
```zsh
bindkey -M vicmd '/' name-of-the-widget
bindkey -M vicmd '?' name-of-the-widget
```

The thing to figure out is if the zle widget exist, or how to program one. You'll have a better experience if you ask in the [Zsh mailing list](https://www.zsh.org/mla/).

> Is that default behaviour? If I escape to normal mode and press v it italicizes the character I'm currently over (iterm). If I open another terminal client v has no effect.

That's the Zsh default, so unless there's something overriding the v key in vicmd you should be able to do it. Check if there's something overriding it by running `bindkey -M vicmd v`. The widget should be `visual-mode`.
