### ISSUE TITLE
Tmux Control Mode

### ISSUE THREAD

**Issue by dvd42** [ohmyzsh/ohmyzsh#7993]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
Tmux plugin

**Is your feature request related to a problem? Please describe.**
I usually work with images through ssh and sometimes I need to see a plot or something and I have XForwarding enabled so I can use the display over SSH, this works fine in ZSH, however tmux cannot display images unless its ran in control mode e.g: Tmux -CC. So It would be very nice if this feature was added. Is something related to this in the works? Thanks in advance!! :)

**Comment by robbyrussell** [comment]
Hey there, I'm doing a bit of housekeeping on the project. Thanks for raising this issue—we always love a good edge case! 😄

However, it's not gathering much community interest, so I'm going to close it for now. Don't let this discourage you! We're all for hearing about the weird things. We can't commit to spending too much time tracking each weird thing down ourselves.
