### ISSUE TITLE
vi-mode breaks smart history navigation

### ISSUE THREAD

**Issue by norm2782** [ohmyzsh/ohmyzsh#800]
As the title says, vi-mode breaks smart history navigation.

E.g., without vi-mode, typing `ssh` and then pressing the up key allows me to browse through my history of ssh commands.

With vi-mode enabled, pressing up just gives me the latest command I typed.

**Comment by JahBrewski** [comment]
+1, setting plugins=(git vi-mode history-substring-search) does not work for me either.

**Comment by javrasya** [comment]
+1, setting plugins=(git vi-mode history-substring-search) does not work for me either.

**Comment by ayberk** [comment]
Still broken on Mac OS X 10.11.2. However, [this comment] (https://github.com/robbyrussell/oh-my-zsh/issues/1479#issuecomment-42633554) fixed the issue for me.

**Comment by febaisi** [comment]
This - plugins=(vi-mode git git-flow github npm osx svn history-substring-search zsh-syntax-highlighting) - works perfectly. 
I had to just add it to my .zshrc file .. below plugin=(git) .. 
Now I have vi mode to edit terminal plus CLTR + R to search my history.. Thank you ..

**Comment by cgjosephlee** [comment]
For someone may need this:
put followings after `plugins=(vi-mode ...)`
```
bindkey "^[OA" up-line-or-beginning-search
bindkey "^[OB" down-line-or-beginning-search
bindkey -M vicmd "k" up-line-or-beginning-search
bindkey -M vicmd "j" down-line-or-beginning-search
```

**Comment by nullset2** [comment]
the `history-substring-search` plugin, I like, but it behaves a little bit different than the stock oh-my-zsh behavior, which is what I get if I use @cgjosephlee's comment
