### ISSUE TITLE
Make the upgrade command more easily discoverable

### ISSUE THREAD

**Issue by mwhitis** [ohmyzsh/ohmyzsh#8003]
**Is your feature request related to a problem? Please describe.**
As I move around various networks, auto upgrade sometimes doesn't work because of proxy settings.  As such, I like to perform a manual update when convenient.  It's frustrating, though, because the upgrade command isn't immediately discoverable because it's not an option to oh-my-zsh itself, and doesn't start with ohmyzsh, which are the first things I look for when trying to find a new command.

**Describe the solution you'd like**

I'd like an option (in addition to the existing upgrade_oh_my_zsh that is more easily discoverable from the command line, rather than me having to google it every 6 months or so. :)

**Describe alternatives you've considered**

I would think one of the following would be appropriate:
- Add an oh_my_zsh_upgrade (or ohmyzsh_upgrade) script along side the existing script 
- Add a --upgrade option to ohmyzsh 
- Add an install-time alias similar to the zshconfig alias
- Add some text to the ohmyzsh script listing the upgrade command

I know it's possible to create my own alias on my machines, but it would be nicer if I didn't have to remember to create it myself on each machine I install on. :)

**Comment by mcornella** [comment]
This will be fixed by https://github.com/ohmyzsh/ohmyzsh/pull/9094, which will enable running `omz update`.
