### ISSUE TITLE
Disable Aliases from plugins I didn't enable

### ISSUE THREAD

**Issue by DaniSpringer** [ohmyzsh/ohmyzsh#8015]
It appears that a bunch of aliases have been enabled upon installing `oh-my-zsh`, even though the plugin files in which they are declared were never included in my `.zshrc`

How can I disable all those aliases?

P.S.: I noticed several similar issues but none actually discussing this specific issue.

**Comment by mcornella** [comment]
`git` is by default enabled if that's the one you're referring to, check your `plugins=()` array. If that's not it post your zshrc file.
