### ISSUE TITLE
fetch option on ohmyz.sh

### ISSUE THREAD

**Issue by stratacast** [ohmyzsh/ohmyzsh#8016]
The website has installer options for both curl and wget. Neither of which are out of the box solutions on FreeBSD. This may sound silly since someone may end up installing curl anyways, but have you thought about adding an option for `fetch`?

It's very similar to the wget one:
``` bash


$ sh -c "$(fetch https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -o -)"

```

**Comment by mcornella** [comment]
I know this is old, but can you put together a PR? README and `tools/install.sh` comment header should be modified.
