### ISSUE TITLE
Problem create menu complement

### ISSUE THREAD

**Issue by fabianomenegidio** [ohmyzsh/ohmyzsh#8028]
I would like an aid, if possible.

I am configuring a tool in zsh and creating an Oh My Zsh plugin for my masters.

The idea is to set up a self-completion for the terminal, I have a menu A of the tool, a submenu B and a submenu C of B. I was able to make submenu B work, but I can not do submenu C.

My script looks like this:

[n-zsh.txt](https://github.com/robbyrussell/oh-my-zsh/files/3418934/n-zsh.txt)

**Comment by mcornella** [comment]
Closing due to age.
