### ISSUE TITLE
[vi-mode] start as normal mode instead of insert mode

### ISSUE THREAD

**Issue by RoXuS** [ohmyzsh/ohmyzsh#8030]
Hello everybody,

There is a way to start as normal mode instead of insert mode with `vi-mode` ?

**Comment by simono** [comment]
You can use
```zsh
zle-line-init() { zle -K vicmd; }
zle -N zle-line-init
```
See [`man zshzle`](https://linux.die.net/man/1/zshzle)

**Comment by mcornella** [comment]
Easier: put `bindkey -a` in your zshrc file, after OMZ is sourced.
