### ISSUE TITLE
Dotenv whitelist

### ISSUE THREAD

**Issue by caleb15** [ohmyzsh/ohmyzsh#8042]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
dotenv

**Is your feature request related to a problem? Please describe.**

Sourcing any file named .env leads to security concerns - what if you download a malicious script named .env?  It could be executed just by you going in the same directory as it.

**Describe the solution you'd like**

It would be nice if there was a whitelist variable so you could specify what folder you would want dotenv to look in. Dotenv would not activate on any .env file outside of that folder. Subfolders within the whitelisted folder would be fine. The security concern would still be there but it would not be as much of a problem.

**Describe alternatives you've considered**

Personally speaking, I could manually alter my python virtualenv to source the .env file when it gets activated.

An alternative solution would be to parse the .env file to make sure it only has the safe-ish `VARNAME=VALUE` syntax. The problem is I'm not sure if that's only syntax, people might do stuff like `VARNAME=$(foo)foo2` or who knows what. Maybe there could be a env variable for dotenv ALLOW_UNSAFE_SYNTAX

**Additional context**

**Comment by mcornella** [comment]
This functionality exists now in the current version.
