### ISSUE TITLE
Tmux Started with a smaller client

### ISSUE THREAD

**Issue by budimanjojo** [ohmyzsh/ohmyzsh#8049]
**Describe the bug**
Tmux started with smaller client.

**To Reproduce**

1. Enable plugins=(... tmux)
2. Set `ZSH_TMUX_AUTOSTART=true`
3. SSH into remote machine (that also have tmux plugin enabled)
4. Turn off computer, turn on again and open up terminal and it looks like this
![Screenshot from 2019-07-30 15-54-33](https://user-images.githubusercontent.com/13085918/62115608-e53f6180-b2e2-11e9-9562-b4f812a6f100.png)

Detaching doesn't do anything unless I do `pkill tmux:\ client`

**Expected behavior**

**Screenshots or recordings**

**System:**
 - OS: Ubuntu 18.04
 - Zsh version: 5.4.2
 - Terminal emulator: gnome-terminal

**Comment by robbyrussell** [comment]
Hey there, I'm doing a bit of housekeeping on the project. Thanks for raising this issue—we always love a good edge case! 😄

However, it's not gathering much community interest, so I'm going to close it for now. Don't let this discourage you! We're all for hearing about the weird things. We can't commit to spending too much time tracking each weird thing down ourselves.
