### ISSUE TITLE
iterm2 with Oh-My-zsh agnoster but can't display any git branch

### ISSUE THREAD

**Issue by amazingXiong** [ohmyzsh/ohmyzsh#8059]
1.  macbook pro 13
2. iterm2 version:Build 3.3.0
3. use oh-my-zsh and agnoster theme.
4. it can display very well an month ago  but sudden can show git branch

求救各位大神啊!!!

![image](https://user-images.githubusercontent.com/48853137/62437043-27015980-b774-11e9-8608-113e74ad074e.png)

**Comment by mcornella** [comment]
Reopen if this still happens.
