### ISSUE TITLE
Faulty behavior of the root shell with the Agnoster theme

### ISSUE THREAD

**Issue by HyP3r-** [ohmyzsh/ohmyzsh#8064]
**Describe the bug**
I use oh-my-zsh with the agnoster theme and tmux. Usually I administrate these Linux systems with a putty shell over ssh from my Windows system. The shell usually works fine if I stay in the user context of the user I used to connect to the server. But in many cases I switch to the root shell by starting it with "sudo -i tmux". There are some problems within this shell:
1. when scrolling history back and forth (ctrl+b page up/down) with tmux, single letters get stuck
2. in the root shell, there is an additional space between the prompt and the command line entry
3. errors occur during auto-completion: e.g. if you type "cp -" and then press "tab", the strings jump one letter to the left and you type one character at a time, the characters are offset

**To Reproduce**
1. start PuTTy and connect to the Linux system with a normal user (Debian 8, 9 or 10)
2. Start a root shell: "sudo -i tmux"
3. subdivide the window vertically with "ctrl+b %".
4. start the command line input and use the auto-complete function

**Expected behavior**
The auto-complete should work correctly. The history should not show any artifacts.

**Screenshots or recordings**
![RemoteDesktopManagerFree_2019-08-07_22-36-50](https://user-images.githubusercontent.com/8094242/62657668-4c09ee00-b967-11e9-9d2c-e8c7023c0cb3.png)
![RemoteDesktopManagerFree_2019-08-07_22-40-23](https://user-images.githubusercontent.com/8094242/62657674-4e6c4800-b967-11e9-9ba0-cc6feb2d08e1.png)

**System:**
- OS: Windows 10 1903 and Debian 10
- Zsh version: zsh 5.7.1 (x86_64-debian-linux-gnu)
- Terminal emulator: tmux 2.8

**Comment by HyP3r-** [comment]
After some research I found out that it's the lightning symbol: https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/agnoster.zsh-theme#L220

What do you think of this symbol being replaced by another one? Or do you know how this problem can be solved under Windows?

**Comment by HyP3r-** [comment]
I have observed the problem further and noticed that this effect also occurs on Ubuntu 18.04 and Debian 9 (Stretch) or 10 (Buster) when working directly with the terminal.

My suggestion would be to use this character:
`U+21AF (8623) ↯ DOWNWARDS ZIGZAG ARROW`

**Comment by mcornella** [comment]
What's your `locale` output?

**Comment by HyP3r-** [comment]
Here is my `locale` output:
```
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE=de_DE.UTF-8
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

**Comment by mcornella** [comment]
I assume UTF-8 is enabled in tmux?

**Comment by HyP3r-** [comment]
In all cases I use a standard Debian installation. To be on the safe side I checked again if UTF-8 is enabled. And it should be enabled.

**Comment by lukassausen** [comment]
i experience similar problems when ssh-ing into a root session from my windows system. See gif attached.

The behaviour occurs regardles of the used emulator. putty / conemu / windows 10 terminal all produce the same behaviour. 

Doing the same cd and tabbing command as a non root user works fine. Therefore, I think that @HyP3r- assumption about the lightning symbol being the culprit are correct. 

### My `locale`:

```
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE=de_DE.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES=en_US.UTF-8
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

### Screencast:

![bug](https://user-images.githubusercontent.com/31138084/66143276-303d6400-e607-11e9-9f27-c1b325bd7025.gif)

### System:

OS: Windows 10 1903 and Debian 10
Zsh version: zsh 5.7.1
Terminal emulator: [Windows 10 Terminal](https://github.com/microsoft/terminal) /  putty / conemu

**Comment by HyP3r-** [comment]
I am very pleased that others can also reproduce this mistake. But it is also important to me that this also happens with a newly installed Debian 10 or Ubuntu 18.04 in a local terminal. It is not absolutely necessary to connect to such a system with ssh to recreate this effect.

So as I said before: please remove this icon from the root shell. See this commit: https://github.com/HyP3r-/oh-my-zsh/commit/19289c79d785c3f3cc253288627e6348269c03a5

**Comment by mcornella** [comment]
Can you try with this modified function?
```zsh
prompt_status () {
        local -a symbols
        [[ $RETVAL -ne 0 ]] && symbols+="%{%F{red}%}✘"
        [[ $UID -eq 0 ]] && symbols+="%{%F{yellow}⚡%G%}"
        [[ $(jobs -l | wc -l) -gt 0 ]] && symbols+="%{%F{cyan}%}⚙"
        [[ -n "$symbols" ]] && prompt_segment black default "$symbols"
}
```
You can just copy-paste it into the terminal.

**Comment by HyP3r-** [comment]
The last months I have learned that PuTTy is not very modern. This results in Unicode characters not being displayed correctly and some keyboard shortcuts are not transferred to the shell correctly. So I wrote to Devolutions some time ago and asked them to improve their SSH client and not to base it on PuTTy anymore: 
https://forum.devolutions.net/messages.aspx?TopicID=32356
https://forum.devolutions.net/messages.aspx?TopicID=32357
https://forum.devolutions.net/messages.aspx?TopicID=32849
https://forum.devolutions.net/messages.aspx?TopicID=32854
Fortunately, they have implemented a completely new terminal which, as far as I can see, has fixed all these bugs.

The same goes for this problem, as well as this problem: 
https://github.com/ohmyzsh/ohmyzsh/issues/7484

So I have to say that no matter if you use the current version of the agnoster template or the suggestion you just posted: it all seems to be displayed correctly and works properly.

**Comment by lukassausen** [comment]
> Can you try with this modified function?

@mcornella thanks for the suggestion!

At least for the windows 10 terminal this does not solve the issue. 

However, with regards to @HyP3r- comment I am not sure ifthe fault is with agnoster or rather some outdated ssh client. 

![bug](https://user-images.githubusercontent.com/31138084/74283383-0ff28400-4d22-11ea-9c8d-a0125036e39c.gif)

**Comment by mcornella** [comment]
I'm going to close this as being a fault in the terminal emulator but you in particular can use a modified `prompt_status` function that doesn't contain the lightning symbol:

> ```shell
> prompt_status () {
>         local -a symbols
>         [[ $RETVAL -ne 0 ]] && symbols+="%{%F{red}%}✘"
>         [[ $UID -eq 0 ]] && symbols+="%{%F{yellow}%}#"
>         [[ $(jobs -l | wc -l) -gt 0 ]] && symbols+="%{%F{cyan}%}⚙"
>         [[ -n "$symbols" ]] && prompt_segment black default "$symbols"
> }
> ```
