### ISSUE TITLE
RFC: add rustup completion to plugins

### ISSUE THREAD

**Issue by chasewalden** [ohmyzsh/ohmyzsh#8072]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
`rustup` completion (similar to existing `rust` and `cargo` plugins)

**Describe the solution you'd like**
There are already completion plugins for `rust` and `cargo`. `rustup` also provides completion. This should be added to the standard plugins as there are already plugins for `rust` and `cargo`. `rustup` is also considered a part of the standard toolkit, so it should be included if the plugins exist for `cargo` and `rust`. 

**Describe alternatives you've considered**
I see there was a closed issue #6514 regarding the same topic. There was no description on the issue, nor was there a reason why the PR was closed. If this is not in scope for the future, then that's ok, but I was unsure why this previous was closed.

Alternatively, the user can install the completions themselves, but it can be misleading that there are already two existing plugins for the rest of the Rust toolchain.

**Additional context**
The completion can be generated with
```bash
mkdir $HOME/.oh-my-zsh/plugins &&\
rustup completion zsh > $HOME/.oh-my-zsh/plugins/rustup/_rustup
```

**Comment by alexanderkogan** [comment]
The more correct command for creating the context is:
`mkdir -p $HOME/.oh-my-zsh/plugins/rustup &&\
rustup completions zsh > $HOME/.oh-my-zsh/plugins/rustup/_rustup`
