### ISSUE TITLE
af-magic and python environment variables creates line overflow

### ISSUE THREAD

**Issue by devinmatte** [ohmyzsh/ohmyzsh#8081]
**Describe the bug**
If using Python Virtual environments, `af-magic` theme puts the virtualenv at the front of the line separator and pushes the line into the next terminal line

**To Reproduce**
1. Have zsh running with the `af-magic` theme
2. Activate a python virtual environment
3. It should display immediately

**Expected behavior**
The environment name should display on the command line or the line should justify properly to not create overflow

**Screenshots or recordings**
![Screen Shot 2019-08-15 at 9 12 00 AM](https://user-images.githubusercontent.com/9310513/63096782-cbd22280-bf3c-11e9-8297-3607452fb585.png)

**System:**
 - OS: macOS and Fedora 30
 - Zsh version: 5.7.1
 - Terminal emulator: Hyper and Gnome Terminal

**Comment by edge0701** [comment]
Same here on ArchLinux, Termite v13-11-g3e2c10f, Zsh 5.7.1

**Comment by AchmadGozali8** [comment]
you need to add virtualenv to your plugins on .zshrc file.
in my zshrc config look like this `plugins=(git virtualenv)`

**Comment by abogushov** [comment]
> you need to add virtualenv to your plugins on .zshrc file.
> in my zshrc config look like this `plugins=(git virtualenv)`

Thanks!

**Comment by npel-21** [comment]
I'm still having this issue even with the virtualenv plugin. My .zshrc plugin line looks like:
plugins=(git virtualenv)

I have my conda initialization at the end of the file. Could that be causing the issue?

<img width="146" alt="Screen Shot 2020-05-20 at 11 13 07 AM" src="https://user-images.githubusercontent.com/58576257/82463514-ebc5e200-9a8a-11ea-847d-889d9ea3b3ba.png">

**Comment by mcornella** [comment]
Do you have the latest ohmyzsh version? (run `upgrade_oh_my_zsh`)

**Comment by npel-21** [comment]
I only recently installed since my laptop is new but I did just run upgrade and it updated a few things. I'm still seeing the dashed line issue running into a new line though. I did a source on my .zshrc and tried quitting and opening Terminal, but it's still having the issue.

**Comment by mcornella** [comment]
Can you post the output of `typeset PS1` when the virtualenv info appears?

**Comment by npel-21** [comment]
~ » typeset PS1

PS1=$'(base) $FG[237]${(l.$(afmagic_dashes)..-.)}%{$reset_color%}\n$FG[032]%~$(git_prompt_info)$(hg_prompt_info) $FG[105]%(!.#.»)%{$reset_color%} '

**Comment by mcornella** [comment]
Run `typeset -f -t afmagic_dashes` and post the trace generated when the virtualenv info appears.

**Comment by npel-21** [comment]
~ » typeset -f -t afmagic_dashes
+afmagic_dashes:1> [[ -n '' ]]                                                  
+afmagic_dashes:3> echo 80

**Comment by mcornella** [comment]
It looks like `$VIRTUAL_ENV` isn't defined, I don't understand where the `(base)` part comes from in the prompt come from. How did you activate the virtualenv?

**Comment by npel-21** [comment]
The base is coming from Conda (base conda environment). Sorry if I didn't make that clear. I'll repost what I said earlier since it's probably something to do with Anaconda causing issues.
I have my conda initialization at the end of the .zshrc file. Could that be causing the issue?

**Comment by mcornella** [comment]
I'm not familiar with Conda, what's the command to activate the virtual environment?

**Comment by npel-21** [comment]
`conda activate env_name` to activate an env_name
`conda deactivate` to go back to base

<img width="721" alt="Screen Shot 2020-05-21 at 12 10 58 PM" src="https://user-images.githubusercontent.com/58576257/82579760-43804e00-9b5c-11ea-9724-78cd511a181d.png">

**Comment by mcornella** [comment]
Do any `*CONDA*` environment variables show up? Post the output of `typeset -m '*CONDA*'`.

**Comment by mcornella** [comment]
BTW you can [disable showing the conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#determining-your-current-environment) with `conda config --set changeps1 false`.

**Comment by npel-21** [comment]
Good to know. I like having it shown so you keep track of what your environment is but that's useful if you're not using anything to do with conda that terminal session.

Here's the typset info:
~/Documents » typeset -m '*CONDA*'

CONDA_PROMPT_MODIFIER='(pynova) '
CONDA_INTERNAL_OLDPATH=/Users/nick/anaconda3/bin:/Users/nick/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
CONDA_PREFIX_1=/Users/nick/anaconda3
CONDA_PYTHON_EXE=/Users/nick/anaconda3/bin/python
_CE_CONDA=''
CONDA_SHLVL=2
CONDA_EXE=/Users/nick/anaconda3/bin/conda
CONDA_DEFAULT_ENV=pynova
CONDA_PREFIX=/Users/nick/anaconda3/envs/pynova

**Comment by mcornella** [comment]
In this case, the active environment is `pynova`, so we could check for `$CONDA_DEFAULT_ENV` as well as for `$VIRTUAL_ENV` in the af-magic theme.

**Comment by npel-21** [comment]
I put those changes in my local theme and it seems to work with the two Conda environments I have! Awesome thanks!
