### ISSUE TITLE
Terminal closes when type "git commit -m"

### ISSUE THREAD

**Issue by SamuelPinho** [ohmyzsh/ohmyzsh#8093]
**Describe the bug**
When I'm trying to commit a project with "git commit -m" the terminal suddenly closes when I reach the "-" character.
Vscode gives me the error `The terminal process terminated with exit code: 139`

**To Reproduce**
I'm working on a personal project, I just added some files with the command `git add .` and then when I was going to type "git commit -m" the terminal suddenly closes when I type the character "-".
_This is only happening with the git commands._

**System:**
 - OS: Windows 10
 - Zsh version: 5.4.2
 - Terminal emulator: Hyper

**Comment by kkkasio** [comment]
I have the same problem, the terminal closes when I type "git commit -m"

**Comment by eullercdr** [comment]
I have the same problem too, the terminal closes when I type "git commit -m"!

**Comment by mcornella** [comment]
Does this all happen with VS Code or in any terminal emulator? And in what zsh version and operating system? What about the git version? Everyone post this information please.

**Comment by mcornella** [comment]
Also, does this happen outside Oh My Zsh (run `zsh -f`), and if not, what plugins do you have enabled?

**Comment by SamuelPinho** [comment]
Hi.

In any terminal that I run zsh i got an error. Even on cmd it gives me `382 segmentation fault (core dumped) zsh`.

I'm also using oh-my-zsh.

- Git: version 2.17.1

**Comment by mcornella** [comment]
Hi Samuel, normally after a segmentation fault a file named `core` is generated in the current working directory of the crashed process (if the core dump is small enough). If it's too big it isn't saved, but you can change that by running `ulimit -c unlimited`. 

After having run that, trigger the crash again, locate the core dump and [use `gdb` to obtain a stacktrace](https://stackoverflow.com/questions/5745215/getting-stacktrace-from-core-dump) of the moment of the crash. The gdb command would probably be `gdb $(which zsh) core`. After that you can post the stacktrace here.

> And in what zsh version and operating system? What about the git version? Everyone post this information please.

Also post this information and a minimal zshrc file to reproduce this.

**Comment by jackysee** [comment]
If you happen to use `zdharma/fast-syntax-highlighting`,  maybe this issue:
https://github.com/zdharma/fast-syntax-highlighting/issues/146

**Comment by mcornella** [comment]
What plugins are you using? May it have something to do with syntax highlighting?
