### ISSUE TITLE
Undocumented Terminal.app-specific control sequence is printed from inside vim

### ISSUE THREAD

**Issue by timjstewart** [ohmyzsh/ohmyzsh#8096]
**Describe the bug**
In lib/termsupport.zsh, this code:

```if [[ "$TERM_PROGRAM" == "Apple_Terminal" ]] && [[ -z "$INSIDE_EMACS" ]]; then```

should read:

```
if [[ "$TERM_PROGRAM" == "Apple_Terminal" ]] && [[ -z "$INSIDE_EMACS" ]] && [[ -z "$VIM" ]]; then
```

so that when I run shell commands from vim (e.g. `:!ls`) the control sequence is not included in command output.

**To Reproduce**

1. start a new session in tmux
2. Within tmux run vim
3. Type, `:!ls` and hit `ENTER`.

**Expected behavior**
The shell executes the ls command and returns a listing of files in the current directory

**Expected behavior**
The shell executes the ls command and returns the following:

```
^[]7;file://XYZ/Users/ME/src/directory/directory
Makefile
Pipfile
README.md
__pycache__
tags
tests
```

**System:**
 - OS: macOS
 - Zsh version: zsh 5.7.1 (x86_64-apple-darwin17.7.0)
 - Terminal emulator: Terminal

**Comment by mcornella** [comment]
Can you put together a PR if you confirm that that solves it?

**Comment by floam** [comment]
> Undocumented Terminal.app-specific control sequence 

The control sequence is documented in the help viewer for Terminal.app. And the preferences window. See also `/etc/bashrc_Apple_Terminal `.

<img width="505" alt="terminalapp" src="https://user-images.githubusercontent.com/291142/67464962-205ae380-f5f9-11e9-8e1f-d11ccf91cdb4.png">

Also it's not specific to Terminal.app - iTerm2 implements OSC 7, and VTE-based terminals on Linux use the same sequence for the same purpose.

**Comment by mcornella** [comment]
I don't have a macOS machine to test this but I need to know before I commit code that doesn't do anything: does the above fix work?

**Comment by deadlysyn** [comment]
I don't have that fix, and don't see the issue... `!ls` inside vim does not show any escape sequence. 🤔 

Tested both NVIM v0.4.4 and VIM 8.2.1450 in tmux 3.1b / zsh 5.8 on MacOS 10.15.6.

**Comment by mcornella** [comment]
Ok I'll close the issue then, until someone can reproduce this problem.
