### ISSUE TITLE
svn tab completion for files does not work

### ISSUE THREAD

**Issue by cridemichel** [ohmyzsh/ohmyzsh#8099]
**Describe the bug**

Let's assume that there is a file called 'rescheduler.py' and a directory
called 'RESCHEDULE_EXAMPLE' in a svn repository 

```zsh
> svn diff r<TAB> 
```
does not complete it as expected since it suggests only the directory 'RESCHEDULE_EXAMPLE'.
The same odd behavior can be also experienced with 'log' argument (i.e. svn log).
If I disable oh-my-zsh by removing the source command in the .zshrc file
svn tab completion works as expected.

**To Reproduce**

see above

**Expected behavior**

**Screenshots or recordings**

**System:**
 - OS: [e.g. macOS] mac osx mojave 10.14.6
 - Zsh version  zsh 5.7.1 (x86_64-apple-darwin18.2.0)
 - Terminal emulator  iTerm2 3.3.2

**Additional context**

**Comment by cridemichel** [comment]
> **Describe the bug**
> 
> Let's assume that there is a file called 'rescheduler.py' and a directory
> called 'RESCHEDULE_EXAMPLE' in a svn repository
> 
> ```shell
> > svn diff r<TAB> 
> ```
> 
> does not complete it as expected since it suggests only the directory 'RESCHEDULE_EXAMPLE'.
> The same odd behavior can be also experienced with 'log' argument (i.e. svn log).
> If I disable oh-my-zsh by removing the source command in the .zshrc file
> svn tab completion works as expected.
> 
> **To Reproduce**
> 
> see above
> 
> **Expected behavior**
> 
> **Screenshots or recordings**
> 
> **System:**
> 
>     * OS: [e.g. macOS] mac osx mojave 10.14.6
> 
>     * Zsh version  zsh 5.7.1 (x86_64-apple-darwin18.2.0)
> 
>     * Terminal emulator  iTerm2 3.3.2
> 
> 
> **Additional context**

I further investigated the issue and I found the the subversion function provided by zsh are obsolete since the latest subversions store all files in the folder .svn of the root directory of the repository. Hence, I patched a bit the original file making svn completion work again, except that 
it is less smart than before. In particular.E.g. if you do 'svn diff <tab>' it will suggest all files in the folder you are in and not only the ones under revision control.


[_subversion_patched.gz](https://github.com/robbyrussell/oh-my-zsh/files/3535117/_subversion_patched.gz)

**Comment by mcornella** [comment]
Since this is a temporary patch I'd suggest asking the people on the [zsh mailing list](http://zsh.org/mla) to arrive at a permanent solution. What svn version are you using, so that we know?

**Comment by cridemichel** [comment]
yes maybe it is a good to idea to post on the zsh mailing list, I am using svn 1.12.2 and zsh 5.7.1
best C.

**Comment by larson-carter** [comment]
@cridemichel I'll admit I don't know enough about SVN, however can you look into this?  

https://stackoverflow.com/questions/1493472/subversion-repository-autocomplete

**Comment by girgen** [comment]
Hi,

This seems to fixed in zsh. Upgraded from 5.3 -> 5.8 and now it works.
