### ISSUE TITLE
Last character of file name randomly added after cursor when pressing tab

### ISSUE THREAD

**Issue by xdavidhu** [ohmyzsh/ohmyzsh#8123]
**Describe the bug**

When activating autocomplete in a specific case, the last char of the file name will be added after the cursor.

**To Reproduce**
1. Create a directory
2. Create 2 files in the directory: `test_cert.sh` and `test_a.sh`
3. Type in `./test_.sh` and move the cursor after the underscore (so that the cursor is flashing on the dot)
4. Press tab to activate autocomplete
5. See that an `h` is added after the cursor

**Expected behavior**

No character should be added after the cursor and the autocomplete chooser should appear, letting the user select a file.

**System:**
 - OS: macOS 10.12.6
 - Zsh version 5.2
 - Terminal emulator iTerm2

**Comment by PapsOu** [comment]
I've got a pretty similar issue than you @xdavidhu but it's always the first char of the command `cd ./` will be printed as `ccd ./` when using tab to autocomplete paths.

**Comment by PapsOu** [comment]
Hum, I've found that for my special case, setting `ZLE_RPROMPT_INDENT=1` instead of `ZLE_RPROMPT_INDENT=0` fixes the problem.

**Comment by mcornella** [comment]
We've found that this frequently has to do with special characters in the prompt with a locale that doesn't support UTF-8. See https://github.com/robbyrussell/oh-my-zsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command

**Comment by paulcsiki** [comment]
Maybe detect this issue and print a message so people will know?
