### ISSUE TITLE
emacs ansi-term having issues with rendering output of a command

### ISSUE THREAD

**Issue by CsBigDataHub** [ohmyzsh/ohmyzsh#8135]
I am trying to use oh-my-zsh in emacs with M-x term or M-x ansi-term.
I am having same issue with both modes.
Eliminator return the output of the command but the out disappears.

Using Emacs 26.2
ZSH version is 5.3

![2019-09-06_23-33-07 (1)](https://user-images.githubusercontent.com/23665525/64470047-1d1b9f00-d102-11e9-9c2e-f696a72776a6.gif)

**Comment by mcornella** [comment]
Does this happen with a normal terminal emulator? What is your zshrc file?

**Comment by CsBigDataHub** [comment]
> Does this happen with a normal terminal emulator? What is your zshrc file?

Nope just in emacs. Its been a while but I think I have fixed. Do not remember the fix but the fix was in emacs. Closing the issue now.
