### ISSUE TITLE
git-flow plugin doesn't support the "bugfix" flow

### ISSUE THREAD

**Issue by Edo78** [ohmyzsh/ohmyzsh#8154]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
It's related to the git-flow plugin

**Is your feature request related to a problem? Please describe.**
The plugin doesn't provide autocompletion for the 'bugfix' flow

**Describe the solution you'd like**
It should be nice if the plugin can provide autocompletion for all the git-flow flows

Id doesn't look too complicated to add this flow to the plugin so I can be able to make a PR if you are open to consider it (obviously after reading your guideline for collaboration).

**Comment by mcornella** [comment]
See https://github.com/ohmyzsh/ohmyzsh/pull/8176#issuecomment-582040288.
