### ISSUE TITLE
Update problem with git config core.autocrlf=true on WSL

### ISSUE THREAD

**Issue by vegansk** [ohmyzsh/ohmyzsh#8158]
**Is your feature request related to a problem? Please describe.**

I'm using git under WSL on Windows 10 and I need to translate all line endings to CRLF globally to work with my projects from Windows version of IDEA for example. But it breaks oh-my-zsh updates:

```
/home/vega/.oh-my-zsh/lib/functions.zsh:21: parse error near `in^M' 
/home/vega/.oh-my-zsh/lib/misc.zsh:21: command not found: env_default
/home/vega/.oh-my-zsh/lib/misc.zsh:22: command not found: env_default
/home/vega/.oh-my-zsh/plugins/git/git.plugin.zsh:4: command not found: ^M
/home/vega/.oh-my-zsh/plugins/git/git.plugin.zsh:230: parse error near `&&'
/home/vega/.oh-my-zsh/themes/robbyrussell.zsh-theme:3: command not found: ^M
```

**Describe the solution you'd like**

Add `.gitattributes` file with following content to disable global settings:

```
* -text
```

**Comment by rm-bergmann** [comment]
I have the same problem here. @vegansk any idea how I can temporarily access wsl as my terminal is stuck now. CTRL + C does not cancel the current process. Can I temporarily add the .gitattributes file locally and where should it live?

**Comment by vegansk** [comment]
@rm-bergmann , after adding .gitattributes, you need to overwrite local files in ~/.oh-my-zsh that are already corrupted: `git ls-files -z | xargs -0 rm; git checkout .` . See https://stackoverflow.com/questions/1125968/how-do-i-force-git-pull-to-overwrite-local-files#comment95282177_1125968

**Comment by mcornella** [comment]
As well as the solutions provided here, OMZ now has an automatic feature that sets the right git configs so that it doesn't happen again, see https://github.com/ohmyzsh/ohmyzsh/blob/671d21ac5305e815668500563a6b7ef61057b659/tools/upgrade.sh#L25-L32
