### ISSUE TITLE
Abnormal auto-reply to ssh information

### ISSUE THREAD

**Issue by zzf-technion** [ohmyzsh/ohmyzsh#8172]
When I use zsh and disabled oh-my-zsh, everything is right, the screenshot as follows:

![The right information](https://user-images.githubusercontent.com/1441704/66499881-f239b780-eac0-11e9-9922-6fbe296a527e.png)
 and waiting for my response.

However, when enabled oh-my-zsh, the abnormal occurs  it seems some settings are auto-reply to ssh information and can't display the information properly from the server, and when I press ctrl+d to exit, the zsh keep repeating this command, always exit again and again, can't stop unless I close zsh.

![The abnormal screenshot](https://user-images.githubusercontent.com/1441704/66499916-fe257980-eac0-11e9-8ddd-0b2e3f460e2b.png)

It will be great appreciated if someone can help. Thanks

**Comment by mcornella** [comment]
Reopen if this still happens.
