### ISSUE TITLE
fzf plugin use fd if installed.

### ISSUE THREAD

**Issue by mikeslattery** [ohmyzsh/ohmyzsh#8187]
I'd be happy to implement this myself and submit a pull request.  However, first I wanted to see if there was interest in using it.

**Is your feature request related to a particular plugin or theme? If so, specify it.**
fzf

**Is your feature request related to a problem? Please describe.**
When using the fzf plugin _and_ when fd is installed, I still have to do some .zshrc customization as described in the [fzf github project](https://github.com/junegunn/fzf)

**Describe the solution you'd like**
I'd like the fzf plugin to add fd specific configuration.   The most important line would be:
`export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git`

**Describe alternatives you've considered**
A separate fzf-fd plugin.

**Additional context**
Add an if block:  `if which fd &>/dev/null; then`
Part of this: https://github.com/junegunn/fzf#settings
And: https://github.com/junegunn/fzf#respecting-gitignore

**Comment by mcornella** [comment]
Go ahead, if this is a documented feature I don't see why we wouldn't support it.
Use `if (( $+commands[fd] )); then` instead to check if fd is installed.

**Comment by mcornella** [comment]
Did this ever make it into a PR?

**Comment by mcornella** [comment]
Closing due to lack of interest.
