### ISSUE TITLE
Messed up last few lines when using oh-my-zsh + tmux in centos with multi-line prompt

### ISSUE THREAD

**Issue by dragonxlwang** [ohmyzsh/ohmyzsh#8195]
**Describe the bug**

I am not able to blame this bug as caused by oh-my-zsh, but it's more likely to be a locale issue from incompatibly between multiple packages that I was using.

Messed up last few lines when using oh-my-zsh + tmux in centos with multi-line prompt

**To Reproduce**
in any directory with longer items than the screen height, list files 
```
ls -al
```
and the final few lines format is messed

**Expected behavior**

The multi-line prompt are output after the command `ls -al` fully output

**Screenshots or recordings**

![image](https://user-images.githubusercontent.com/15812510/66074623-7793f980-e50e-11e9-97c5-3352157f8cf4.png)

Note the last file for listing is .zshrc, but the prompt has started at the same line, with overlapping to the end output to the `ls -al` cmd;

The problem does not produce when in mac OS with same tmux/zsh/oh-my-zsh/iterm2; In addition, in the ys template, if I change the first character from `#` to `➜` (or any other uncommon symbols), the problem will not produce:

```
49 PROMPT="
50 %{$terminfo[bold]$fg[blue]%}➜ %{$reset_color%} \
51 %(#,%{$bg[yellow]%}%{$fg[black]%}%n%{$reset_color%},%{$fg[cyan]%}%n) \
52 %{$fg[white]%}@ \
53 %{$fg[green]%}%m \
54 %{$fg[white]%}in \
55 %{$terminfo[bold]$fg[yellow]%}%~%{$reset_color%}\
56 ${hg_info}\
57 ${git_info}\
58  \
59 %{$fg[white]%}[%*] $exit_code
60 %{$terminfo[bold]$fg[red]%}$ %{$reset_color%}"
```

![image](https://user-images.githubusercontent.com/15812510/66074970-597ac900-e50f-11e9-9c8f-f5e722ec2650.png)

In above, the expected output is 
```
output from last command line
prompt1: empty line
prompt2: info defined in prompt, starting with ➜, and ending in time
prompt3: $ followed by user input
```

In addition, the problem does not show if any themes with only 1-line prompt is used:
```
11 ZSH_THEME="robbyrussell"
```
![image](https://user-images.githubusercontent.com/15812510/66075166-d9a12e80-e50f-11e9-8f8c-f8091e98ed42.png)

**System:**

* oh-my-zsh: 4b8f4d529ef1965a9f6a233579ea432374f817dd (10/02 master)
* ZSH_THEME="ys"
* zsh 5.2 (x86_64-redhat-linux-gnu)
* CentOS Linux release 7.6.1810 (Core)
* tmux 2.8
* iTerm2 Build 3.3.5beta3

all the packages are used with default configs, only oh-my-zsh changed the ZSH_THEME to `ys`

**Comment by mcornella** [comment]
Can you update your zsh version? [I think in CentOS 7 you need to manually compile it](https://github.com/Powerlevel9k/powerlevel9k/issues/1355#issuecomment-522494257).

**Comment by dragonxlwang** [comment]
Thanks! just realized that i'm already on 5.2 now and the problem is no longer persists.

**Comment by mcornella** [comment]
Cool, closing then.
