### ISSUE TITLE
Allow install without replacing .zshrc

### ISSUE THREAD

**Issue by mfdorst** [ohmyzsh/ohmyzsh#8208]
**Is your feature request related to a problem? Please describe.**

I have an install script which installs my dotfiles for me on new machines. When extending it to install OMZ I realized that there is no option in the OMZ installer to disable replacing `.zshrc`.

**Describe the solution you'd like**

I would like there to be either:
1. A command line option, perhaps `--noreplace-zshrc`, or
2. An environment variable, perhaps `REPLACE_ZSHRC`, which could be set to `no`

...or both, which would disable the backup and replacement of `.zshrc`.

**Describe alternatives you've considered**

The best workaround I have is to simply overwrite the generated `.zshrc` script after the fact, but since the OMZ installer prints a message about backing up and replacing `.zshrc`, it'll be confusing to anyone who uses the script. I could hide the output of the OMZ installer, but frankly I really like the way it looks and it'd be a shame to hide it.

**Comment by cakraww** [comment]
my existing `.zshrc` seems lost when I installed oh-my-zsh, without it notifying.

**Comment by mfdorst** [comment]
@cakraww you should create your own issue to file a bug report. This is a feature request.
