### ISSUE TITLE
Add a git alias to clone and change directory

### ISSUE THREAD

**Issue by cueo** [ohmyzsh/ohmyzsh#8216]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
git

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add an alias which clones a repo and then `cd`s into it.

**Describe alternatives you've considered**

Manually `cd` into the directory after `git clone` or `gcl`.

**Additional context**

**Comment by cueo** [comment]
I can take this up if it looks like something worth doing.

**Comment by mcornella** [comment]
Still interested in this?
