### ISSUE TITLE
Breezy causes zsh to hang

### ISSUE THREAD

**Issue by Robert-Obermeier** [ohmyzsh/ohmyzsh#8237]
**Describe the bug**
With Breezy installed on Debian Bullseye the zsh prompt might hang while waiting for breezy to show the commit revision. (git-status)

Additionally within bigger git repositories breezy will hang for enormous amounts of time and produce a git revision like this:

`  master  bzr@revision-id: git-v1:0xvery_long_shasum`

**To Reproduce**

1. Either use a theme with git status or enable git-prompt (bzr-prompt)
2. Clone a bigger repository or use oh-my-zsh
3. Chdir into that folder
4. Wait for the prompt
5. Bonus: see some useless information

**Expected behavior**
within a git repository do not call bzr and do not show its output

**Screenshots or recordings**

**System:**
 - OS: Linux (Debian Bullseye)
 - Zsh version 5.7.1
 - Gnome-Terminal

**Additional context**
It seems that breezy will provide a bzr and brz binary. I guess it is a drop in replacement for Bazar that additionally supports git.

I could fix the issue with uninstalling breezy, but there might be people out there who use that versioning tool and their experience will be really bad.

**Comment by jmkim** [comment]
+1, same bug occurs here with bundled `agnoster.zsh-theme`.

Agnoster theme runs `prompt_bzr` even for non-bzr git repository. If that git repo huge, Agnoster do `bzr status` and wait, which could be hung up more than 10 mins. (When `bzr status` done, Agnoster shows me the proper zsh prompt anyway.)

Didn't try with other themes, but if they use `bzr status` in their bzr procedure, they will also hang.

**Comment by acepukas** [comment]
This just started happening to me as well. My Arch install updated `breezy` (replaced a conflicting module) than suddenly `/usr/bin/bzr` was on the system `PATH` and I got the hanging prompt when `cd`'ing to a directory that contains a git repo. I'm using a slightly modified version of the Agnoster theme that I keep in sync with the original. By removing the `prompt_bzr` routine from the theme I can avoid the hanging. Anyone using Agnoster out of the box will be affected by this Breezy bug.

**Comment by Youngsie1997** [comment]
+1 same bug here arch updated breezy and replaced it with bzr and since then the agnoster theme causes hanging. 

Not the ideal situation but for now I have removed the bzr package as I don't use it and wasn't aware it was installed on my system until now!(Installed as a depend).

**Comment by mcornella** [comment]
What do you expect the solution to be? In my view, breezy should fix their end of the problem to stop being so slow.

Otherwise we might be able to detect breezy and disable the bzr prompt in that case, but that would be papering over the problem IMO.

**Comment by alucryd** [comment]
Why run bzr status inside a git repository in the first place?

**Comment by Ten0** [comment]
> What do you expect the solution to be? In my view, breezy should fix their end of the problem to stop being so slow.

Considering I had never heard about breezy until it started crashing my shell, and unless an for a significant portion of zsh users this particular integration is more than a useless python process waited for at each prompt, this option seems reasonable to me:
> within a git repository do not call bzr and do not show its output

That is, only try and run `bzr` if `git` did not run. Or make it an opt-in rather than an opt-out.

**Comment by Ten0** [comment]
> Why run bzr status inside a git repository in the first place?

It is actually ran everywhere, just like git. All integrations run independently. It just isn't so slow when not in a git repository.

**Comment by alucryd** [comment]
> > Why run bzr status inside a git repository in the first place?
> 
> From what I see in the agnoster theme source, it is actually run everywhere, just like git. All integrations run independently. It just isn't so slow when not in a git repository.

Sounds like a huge waste of resources to me, surely a simple `if [ -d .git ]` would be lighter (and certainly smarter) than running `git status` everywhere. For instance prezto only runs git and bzr commands where it makes sense, haven't had any issue with git repositories since the breezy switch.

**Comment by mcornella** [comment]
The agnoster theme bundled in OMZ strays very far from the [official one](https://github.com/agnoster/agnoster-zsh-theme) and is in need of a big revamp. That said, this changed `prompt_bzr` function may fix your issue until we refactor the agnoster theme (copy-paste it to the terminal and enter a git repository):
```zsh
prompt_bzr() {
  (( $+commands[bzr] )) || return

  # Test if bzr repository in directory hierarchy
  local dir="$PWD"
  while [[ ! -d "$dir/.bzr" ]]; do
    [[ "$dir" = "/" ]] && return
    dir=${dir:h}
  done

  local bzr_status status_mod status_all revision
  if bzr_status=$(bzr status >/dev/null 2>&1); then
    status_mod=$(head -n1 <<< $bzr_status | grep "modified" | wc -m)
    status_all=$(head -n1 <<< $bzr_status | wc -m)
    revision=$(bzr log | head -n2 | tail -n1 | sed 's/^revno: //')
    if [[ $status_mod -gt 0 ]] ; then
      prompt_segment yellow black "bzr@$revision ✚ "
    else
      if [[ $status_all -gt 0 ]] ; then
        prompt_segment yellow black "bzr@$revision"
      else
        prompt_segment green black "bzr@$revision"
      fi
    fi
  fi
}
```

**Comment by mcornella** [comment]
Updated the code to work as before on bzr repositories, see above.

**Comment by aral** [comment]
Just ran into this after upgrading to Pop!_OS 20.04.

Commenting out `prompt_bzr` in the `build_prompt()` function seems to have solved it. (I also commented out `prompt_hg`.

**Comment by mcornella** [comment]
#8646 should have fixed it. Do you have the latest ohmyzsh revision?

**Comment by jaimealsilva** [comment]
I'm having this problem since upgraded to Pop!_OS 20.04.

Ran upgrade_oh_my_zsh yesterday (May 7) rebooted, today, after reading this, ran upgrade_oh_my_zsh again but no luck, problem persists.

**Comment by mcornella** [comment]
What's the output of `which prompt_bzr`?

**Comment by joeybronzoni** [comment]
Thanks @mcornella nice. This had me pulling my hair out.

**Comment by luxumbra** [comment]
Stumbling across this has saved me what hair I have left! I upgraded to Pop!_OS 20.04 today and had the same issue with Agnoster. Switched theme and it's nice and snappy.

**Comment by mcornella** [comment]
The agnoster theme should be fixed, please go back to agnoster, run `typeset -f -t prompt_bzr`, and try to reproduce the problem again and post the output.

**Comment by joeybronzoni** [comment]
Hey @mcornella, Thanks. So I had gone back to agnoster and it still looks like a problem. It just hangs when I cd into a git repo. 
Here is the output from the terminal. Let me know if there is anything else you need and I'll be quick about replying. Work had all my attention this past 2 weeks. 

`(base)  arcarius@archBoxHero  ~  typeset -f -t prompt_bzr
+prompt_bzr:1> ((  1  ))                                   
+prompt_bzr:2> bzr status        
(base)  arcarius@archBoxHero  ~  cd AUR_Packages 
+prompt_bzr:1> ((  1  ))                                                                                               
+prompt_bzr:2> bzr status                                
(base)  arcarius@archBoxHero  ~/AUR_Packages  +prompt_bzr:1> ((  1  ))
+prompt_bzr:2> bzr status      
(base)  arcarius@archBoxHero  ~/AUR_Packages  +prompt_bzr:1> ((  1  ))
+prompt_bzr:2> bzr status                                                                                              
(base)  arcarius@archBoxHero  ~/AUR_Packages  cd icaclient 
+prompt_bzr:1> ((  1  ))                                   
+prompt_bzr:2> bzr status                        
+prompt_bzr:3> status_mod=+prompt_bzr:3> bzr status                                                                                                                                                                                            
+prompt_bzr:3> status_mod=+prompt_bzr:3> head -n1
+prompt_bzr:3> status_mod=+prompt_bzr:3> grep '--color=auto' '--exclude-dir=.bzr' '--exclude-dir=CVS' '--exclude-dir=.git' '--exclude-dir=.hg' '--exclude-dir=.svn' modified
+prompt_bzr:3> status_mod=+prompt_bzr:3> wc -m     
+prompt_bzr:3> status_mod=0                      
+prompt_bzr:4> status_all=+prompt_bzr:4> bzr status
+prompt_bzr:4> status_all=+prompt_bzr:4> head -n1
+prompt_bzr:4> status_all=+prompt_bzr:4> wc -m
+prompt_bzr:4> status_all=9                    
+prompt_bzr:5> revision=+prompt_bzr:5> bzr log 
+prompt_bzr:5> revision=+prompt_bzr:5> head -n2          
+prompt_bzr:5> revision=+prompt_bzr:5> tail -n1
+prompt_bzr:5> revision=+prompt_bzr:5> sed 's/^revno: //'
+prompt_bzr:5> revision=25   
+prompt_bzr:6> [[ 0 -gt 0 ]]               
+prompt_bzr:10> [[ 9 -gt 0 ]] 
+prompt_bzr:11> prompt_segment yellow black
+prompt_segment:1> local bg fg     
+prompt_segment:2> [[ -n yellow ]]
+prompt_segment:2> bg='%K{yellow}' 
+prompt_segment:3> [[ -n black ]]                                                                                      
+prompt_segment:3> fg='%F{black}'                        
+prompt_segment:4> [[ yellow != NONE && yellow != yellow ]] 
+prompt_segment:7> echo -n '%{%K{yellow}%}%{%F{black}%} '
+prompt_segment:9> CURRENT_BG=yellow 
+prompt_segment:10> [[ -n '' ]]                                                                               
+prompt_bzr:12> echo -n bzr@25                                                                                         
(base)  arcarius@archBoxHero  ~/AUR_Packages/icaclient   master bzr@25  +prompt_bzr:1> ((  1  ))                   
+prompt_bzr:2> bzr status                                                                                              
+prompt_bzr:3> status_mod=+prompt_bzr:3> bzr status        
+prompt_bzr:3> status_mod=+prompt_bzr:3> head -n1
+prompt_bzr:3> status_mod=+prompt_bzr:3> grep '--color=auto' '--exclude-dir=.bzr' '--exclude-dir=CVS' '--exclude-dir=.git' '--exclude-dir=.hg' '--exclude-dir=.svn' modified                                                                   
+prompt_bzr:3> status_mod=+prompt_bzr:3> wc -m   
+prompt_bzr:3> status_mod=0                                                                                                                                                                                                                    
+prompt_bzr:4> status_all=+prompt_bzr:4> bzr status
+prompt_bzr:4> status_all=+prompt_bzr:4> head -n1
+prompt_bzr:4> status_all=+prompt_bzr:4> wc -m     
+prompt_bzr:4> status_all=9                      
+prompt_bzr:5> revision=+prompt_bzr:5> bzr log
+prompt_bzr:5> revision=+prompt_bzr:5> head -n2
+prompt_bzr:5> revision=+prompt_bzr:5> tail -n1
+prompt_bzr:5> revision=+prompt_bzr:5> sed 's/^revno: //'
+prompt_bzr:5> revision=25                     
+prompt_bzr:6> [[ 0 -gt 0 ]]                             
+prompt_bzr:10> [[ 9 -gt 0 ]]
+prompt_bzr:11> prompt_segment yellow black
+prompt_segment:1> local bg fg
+prompt_segment:2> [[ -n yellow ]]         
+prompt_segment:2> bg='%K{yellow}' 
+prompt_segment:3> [[ -n black ]] 
+prompt_segment:3> fg='%F{black}'  
+prompt_segment:4> [[ yellow != NONE && yellow != yellow ]]                                                            
+prompt_segment:7> echo -n '%{%K{yellow}%}%{%F{black}%} '
+prompt_segment:9> CURRENT_BG=yellow                                                                                   
+prompt_segment:10> [[ -n '' ]]                          
+prompt_bzr:12> echo -n bzr@25       
(base)  arcarius@archBoxHero  ~/AUR_Packages/icaclient   master bzr@25  cd ../android-studio                       
+prompt_bzr:1> ((  1  ))                                   
+prompt_bzr:2> bzr status                                                                                              
   `
And from here it just hangs. Sometimes it will change the directory but sometimes it does not.

**Comment by mcornella** [comment]
It doesn't seem like you have the latest update. Try `upgrade_oh_my_zsh`.

**Comment by joeybronzoni** [comment]
Yup, facepalm. That was it thanks. Its smooth like butter.
