### ISSUE TITLE
TaskWarrior: tab-completion does not work for project names with spaces

### ISSUE THREAD

**Issue by dbogdanov** [ohmyzsh/ohmyzsh#8249]
**Describe the bug**
Tab-completion does not for for project names that contain spaces

**To Reproduce**
`task add TEST project:"Test Project"`
`task project:"Test Project"  list` works.
However, I cant tab-complete `task project:`

**System:**
macOS, iTerm2, zsh 5.3 (x86_64-apple-darwin17.0)

**Comment by mcornella** [comment]
This was a bug upstream, I've submitted https://github.com/GothenburgBitFactory/taskwarrior/pull/2228 to fix it.
