### ISSUE TITLE
Folders and files all display the same color

### ISSUE THREAD

**Issue by MrYbo** [ohmyzsh/ohmyzsh#8265]
# 文件夹和文件都显示同一种颜色
之前文件和文件夹可以是通过不同的颜色来区分，更新之后就不行了，文件夹和文件都是同一种颜色

**System:**
 - OS: [macOS10.15]
 - Zsh version [最新]
 - Terminal emulator [iTerm2]

**Comment by mcornella** [comment]
Google Translate says:
> ## Folders and files all display the same color
> Previous files and folders could be distinguished by different colors. After updating, they will not work. Folders and files are the same color.
> Zsh version: latest

Is that accurate?

If so, post the output of the following:
* `which ls`
* `echo $LS_COLORS`

Also, tell me: when you say "after updating", do you mean you updated Oh My Zsh or to macOS Catalina?

**Comment by pureyb** [comment]
> Google翻译说：
> 
> > ## 文件夹和文件都显示相同的颜色
> > 以前的文件和文件夹可以用不同的颜色区分。更新后，它们将不起作用。文件夹和文件的颜色相同。
> > Zsh版本：最新
> 
> 准确吗？
> 
> 如果是这样，请发布以下输出：
> 
> * `which ls`
> * `echo $LS_COLORS`

![image](https://user-images.githubusercontent.com/23352300/67139109-c962b080-f27e-11e9-9f36-a0243ba5f700.png)

> 
> 另外，请告诉我：当您说“更新后”时，您是说您将Oh My Zsh或macOS Catalina更新了吗？

yes , updated Oh My Zsh or to macOS Catalina

**Comment by mcornella** [comment]
If you run `unset LSCOLORS` does that fix it?

**Comment by pureyb** [comment]
> If you run `unset LSCOLORS` does that fix it?

no

**Comment by mcornella** [comment]
Did you figure it out? If not, reopen the issue.
