### ISSUE TITLE
kubectl plugin does not start at boot terminal

### ISSUE THREAD

**Issue by pela7** [ohmyzsh/ohmyzsh#8267]
kubectl plugin does not start when booting the terminal, I must run `source ~/.zshrc` to detect the plugin

**Comment by mcornella** [comment]
Do you have the `plugins` definition *before* Oh My Zsh is sourced?

**Comment by pela7** [comment]
In my ``.zshrc`` file I have the following configuration

```
export ZSH="/Users/<username>/.oh-my-zsh"
ZSH_THEME="powerlevel9k/powerlevel9k"
plugins=( git laravel5 composer kubectl )

source $ZSH/oh-my-zsh.sh


for file in ~/.{path,bash_prompt,exports,aliases,functions,extra}; do
  [ -r "$file" ] && source "$file"
done
unset file


autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/mc mc
```

**Comment by mcornella** [comment]
What do you understand for "starting up"? What do you think should happen? It should just load completion for `kubectl` and the aliases it defines should be defined. Does that not happen?

**Comment by pela7** [comment]
On my machine I have run kubectl and it doesn't show me the available commands or the pods I have raised.

When I execute `` source ~ / .zshrc`` when I put kiubectl in the terminal and press tab it returns the available commands or in case I have any command and the next value is a pod it returns the pods.

![https://i.ibb.co/dL3mtyy/Screenshot-at-Oct-20-12-26-25.png](https://i.ibb.co/dL3mtyy/Screenshot-at-Oct-20-12-26-25.png)

![https://i.ibb.co/ZJFNTsj/Screenshot-at-Oct-20-12-27-18.png](https://i.ibb.co/ZJFNTsj/Screenshot-at-Oct-20-12-27-18.png)

![https://i.ibb.co/kcn8Q5k/Screenshot-at-Oct-20-12-28-00.png](https://i.ibb.co/kcn8Q5k/Screenshot-at-Oct-20-12-28-00.png)

**Comment by mcornella** [comment]
What does `which k` return before sourcing zshrc?

**Comment by pela7** [comment]
``k: aliased to kubectl``

**Comment by mcornella** [comment]
Can it be the bashcompinit call? Try to move it before sourcing OMZ.
