### ISSUE TITLE
Add git-completion compatibility for git v2.23 commands

### ISSUE THREAD

**Issue by apeluffo** [ohmyzsh/ohmyzsh#8302]
**Plugin**
git-completion

**Current Behavior**
Git branch name autocompletion does not work when using `git switch` or `git restore -s`.

**Expected Behavior**
Tabbing on incomplete branch names using the aforementioned commands should autocomplete or display a list of possible branches.

**Comment by bryango** [comment]
I am able to fix this by adding the latest `_git` completion file from zsh upstream source: 
https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_git
Hope OMZ can pre-integrate this before zsh's next release!

**Comment by nonZero** [comment]
As a workaround, you can meanwhile use [gitfast](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gitfast) which currently supports `git switch`

**Comment by mcornella** [comment]
Official zsh completions can't be integrated within OMZ, we would have to manually test each completion and also there would be duplicate efforts. My advice is that you either bundle the completion in `$ZSH_CUSTOM` or you update your zsh version.
