### ISSUE TITLE
Alias gl in conflict with gitless, change request: gl to gpl

### ISSUE THREAD

**Issue by mikebranderhorst** [ohmyzsh/ohmyzsh#8306]
**Describe the bug**
Alias gl conflicts with gitless

**To Reproduce**
Install gitless and see that it gl references the alias instead

**System:**
 - OS: macOS
 - Zsh version 5.7.1
 - Terminal emulator iTerm2

**Additional context**
gpl for git pull makes more sense because l is reserved for log and not pull

**Comment by robbyrussell** [comment]
Hey there, I'm doing a bit of housekeeping on the project. Thanks for raising this issue—we always love a good edge case! 😄

However, it's not gathering much community interest, so I'm going to close it for now. Don't let this discourage you! We're all for hearing about the weird things. We can't commit to spending too much time tracking each weird thing down ourselves.
