### ISSUE TITLE
OMZ starts only for interactive shells

### ISSUE THREAD

**Issue by MisterDA** [ohmyzsh/ohmyzsh#8320]
With a graphical login, `.zshrc` is not sourced, and thus if plugins like ssh-agent want to export environment variables, they won't be picked. Of course, if I spawn a shell and a tty and launch X or my Wayland compositor from here, it's ok.
Basically I think that the problem is that `.zshrc` (= OMZ) is only sourced for _interactive_ shells, but the shell that starts my environment isn't interactive.

The plugin _ssh-agent_ is not that clearly non-interactive, since users are required to unlock their keys at some point, but my use case is that I use a password manager, which, once unlocked, talks to the ssh-agent process found with the environment variables to unlock my keys. If `.zshrc` is not sourced (which is the case here since the graphical login is non-interactive), the ssh-agent process is never started.

Symlinking `.zprofile` to `.zshrc` would be cheating.

Could something be done to split OMZ into an _non-interactive_ part sourced in `.zshenv` or `.zprofile`, and an _interactive_ part sourced in `.zshrc`?

I find this diagram pretty neat to understand the startup order.
![zsh startup order](https://blog.flowblok.id.au/static/images/shell-startup.png) ([source](https://blog.flowblok.id.au/2013-02/shell-startup-scripts.html#implementation))

**Comment by MisterDA** [comment]
In the end my real problem was that gnome wayland sessions don't start with a login shell. The replacement seems to be systemd generators.
- https://lwn.net/Articles/709769/
- https://unix.stackexchange.com/a/403196
- https://wiki.archlinux.org/index.php/Systemd/User#Environment_variables
- https://jlk.fjfi.cvut.cz/arch/manpages/man/systemd.environment-generator.7.en

OMZ could still benefit from interactive/non-interactive split.

**Comment by mcornella** [comment]
This is not trivial and, from what I understand, needed only for the ssh-agent. It isn't clear that we can make it run in non-interactive sessions though, sometimes the plugin requires asking for key passphrases.

My advice to you is that you manually source the plugin zshenv or zprofile.

**Comment by MisterDA** [comment]
Ok, thanks!
Seems right anyway, I don’t see a use-case for non-interactive OMZ.
Should the issue I had be documented somewhere? It could happen to somebody else, and in that case the plugin is somewhat unusable.

**Comment by mcornella** [comment]
There's an FAQ in the wiki, if you think it should be there go ahead.
