### ISSUE TITLE
Character not in range in ssh session

### ISSUE THREAD

**Issue by Hero9909** [ohmyzsh/ohmyzsh#8325]
Ive installed oh-my-zsh into /usr/share on my server(ubuntu 18.04 fresh) and set zsh as my default shell from my user alf. But when i log into my server i get an character out of range on my ssh client (android-termux). If i type issue sudo su , everything is fine and works.

 I noticed it may have some connections to the theme im using... 
I changed from default to agnoster. Then the issues was shown. ive changed back to default and everything is fine.

As the theme is working in root shell why wont this work in a unprivileged shell?

**Comment by mcornella** [comment]
Can you post the exact error? Also, make sure that the folder `$ZSH/cache` is writable for non-root users since it is used sometimes by ohmyzsh.
