### ISSUE TITLE
Reverse search breaks with vi-mode

### ISSUE THREAD

**Issue by flaviosakakibara** [ohmyzsh/ohmyzsh#8329]
**Describe the bug**

After upgrade my workstation to fedora 31, when I use reverse-search with ^r, after the first search, apparently a buffer error occurs and the characters appears all messed up (like the following image).

![image](https://user-images.githubusercontent.com/35695404/67725336-c4110e80-f9c0-11e9-8714-613dc0e4f199.png)

**To Reproduce**

1. Enabled plugins:
```
plugins=(
  dnf
  docker
  extract
  git
  git-extras
  kubectl
  sudo
  tmux
  tmuxinator
  vi-mode
  zsh-autosuggestions
  zsh-navigation-tools
  zsh-syntax-highlighting
)
```

2. Run command '...', _or_ try to complete command '...', _etc._
```
^r
```
3. Search some command that returns some lines;
4. Erase the searched command.
5. See error from the image above.

**Expected behavior**
I expect that when a searched command gets erased, all the results should be erased as well. 

**System:**
 - OS: 
Fedora 31
```
[~]: uname -r
5.3.7-301.fc31.x86_64
[~]: cat /etc/fedora-release
Fedora release 31 (Thirty One)
```
 - Zsh version: 5.7.1
 - Terminal emulator: gnome-terminal (GNOME Terminal 3.34.2 using VTE 0.58.1 +BIDI +GNUTLS)

**Additional context**
oh-my-zsh version:
```
[~/.oh-my-zsh, master]: git rev-parse HEAD
e363109a6d3367d8be1dd66f05a38eb38b4257d7
```

**Comment by mcornella** [comment]
Did you ever solve this?

**Comment by flaviosakakibara** [comment]
Nope =/. End up I’m not using the reverse search feature anymore.
