### ISSUE TITLE
Old update.lock will block update

### ISSUE THREAD

**Issue by empire** [ohmyzsh/ohmyzsh#8332]
**Describe the bug**
If update was interrupted, lock will not be removed and block future updates.

**To Reproduce**

1. Wait for update prompt
2. Close terminal
3. Update will be block forever and update.lock will not removed

**Expected behavior**
Lock must be removed next time (or after some time)

**Screenshots or recordings**
https://asciinema.org/a/7KhfLzsSPWZgxK19npv6qiGmc

**System:**
 - OS: Manjaro (linux)
 - Zsh version zsh 5.7.1 (x86_64-pc-linux-gnu
 - Terminal emulator xterm

**Additional context**

**Comment by empire** [comment]
Hi @mcornella
I like to work on this bug, could you please give some feedback on my pull request.

Thanks

**Comment by mcornella** [comment]
https://github.com/ohmyzsh/ohmyzsh/commit/40b013f5f119be27bd2fdece431cf4979193bd25 gives a different solution, which is to run `upgrade_oh_my_zsh` and that will force a removal of the update.lock directory.

**Comment by empire** [comment]
@mcornella, the problem is not solved by that commit (that just removes the lock directory) and needs some manual fix from a user but I think it can be handled automatically (without users notice).

**Comment by jwarkentin** [comment]
Something needs to be done. I've had this issue for such a long time and only just discovered it was the `update.lock` directory preventing update prompts. Unfortunately, for anyone experiencing the issue they will simply have to eventually notice that it's not auto-updating and figure out how to force it manually before they can even get a future fix, assuming one is eventually made.

**Comment by empire** [comment]
Another solution is to change the path of update.lock to a temporary location (/tmp as an example). This way we sure the last lock will be removed on reboot.

**Comment by mcornella** [comment]
That won't work because `/tmp` isn't always volatile in all systems.

The bug in the auto-update code was already fixed, and a manual upgrade means that the code is fixed and the `update.lock` folder is removed. That said, I think we can also add a check to see if it is a day old and remove it in that case.

**Comment by empire** [comment]
I change the locking strategy in the pull request and use the flock command instead.
