### ISSUE TITLE
Error connecting to agent: Connection refused

### ISSUE THREAD

**Issue by panosru** [ohmyzsh/ohmyzsh#8336]
Hello, I started to get `Error connecting to agent: Connection refused` when I launch my terminal.

![image](https://user-images.githubusercontent.com/400362/67861528-0d7c6d80-fb29-11e9-8312-27a3d806fef6.png)

If I remove the line `zstyle :omz:plugins:ssh-agent agent-forwarding on` I stop getting the error but I'm getting prompted to enter the passphrase of the identities.

```
$ ssh-agent -l
launch_activate_socket(): No such process

$ ssh-add -L
Error connecting to agent: Connection refused

$ env | fgrep SSH_AUTH_SOCK
SSH_AUTH_SOCK=/Users/panosru/.gnupg/S.gpg-agent.ssh
```

I have to manually run `eval "$(ssh-agent)"` in order to get ssh commands to work even though I have `ssh-agent` in my zsh plugins...

Any idea why this happening?

Thanks!

**Comment by panosru** [comment]
For now I have set `zstyle :omz:plugins:ssh-agent agent-forwarding off` until the issue will be resolved.

**Comment by mcornella** [comment]
Closing for being old. Reopen if this still happens and can provide further details.
