### ISSUE TITLE
Allow customization of the COMPLETION_WAITING_DOTS dots

### ISSUE THREAD

**Issue by bananastalktome** [ohmyzsh/ohmyzsh#8342]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
Completion

**Is your feature request related to a problem? Please describe.**
It would be nice if it was possible to customize the dots that appear when `COMPLETION_WAITING_DOTS` is enabled.

**Describe the solution you'd like**
Maybe a `COMPLETION_WAITING_DOTS_PROMPT` variable that defaults to the current `"%{%F{red}......%f%}"` value.

**Comment by mcornella** [comment]
What would you change it to?

**Comment by bananastalktome** [comment]
Personally, I am not a fan of the 6 red dots and would like to use an uncolored ellipsis `…` (or `...` depending on how well my terminal font renders an actual ellipsis).

**Comment by mcornella** [comment]
Maybe it's time to just use an ellipsis; it only uses one character which let's us remove the buggy rmam/smam logic. I'm not a fan of complicating it by adding a variable, the function is called `-with-dots` for a reason and it is simple enough that it can be overwritten in your zshrc file.

**Comment by mcornella** [comment]
I substituted the dots for an ellipsis. If you still want to change it, you can redefine the `expand-or-complete-with-dots` function from `lib/completion.zsh` in your zshrc file.

**Comment by LucasLarson** [comment]
> in your zshrc file

How do you do it from `.zshrc` without editing `lib/completion.zsh`?

**Comment by mcornella** [comment]
You can redefine it in the zshrc file after OMZ is sourced. It's all the
same.
