### ISSUE TITLE
aussiegeek color options

### ISSUE THREAD

**Issue by ylluminate** [ohmyzsh/ohmyzsh#8350]
I find `aussiegeek` to be about the best quick theme for all of my server needs and routinely deploy it to each new machine I manage or deploy.

There are two things that would make it better:

1) if the red color were reserved only for `root` user instances so that it automatically switched the username to red in those cases, that would be great.

2) if there were an easy to control auto coloring mechanism for the default colors, that would be useful.  For example `aussiegeek-blue` as the name definition in `.zshrc` would colorize the text elements blue.  Essentially every color could be defined in this way and it would be incredibly useful.

These things are incredibly powerful at giving instant context and visual organizational / grouping functionality to `oh-my-zsh`.

**Comment by mcornella** [comment]
> 2\. if there were an easy to control auto coloring mechanism for the default colors, that would be useful.  For example `aussiegeek-blue` as the name definition in `.zshrc` would colorize the text elements blue.  Essentially every color could be defined in this way and it would be incredibly useful.

I didn't understand this.

Essentially what you're asking for is a different theme ([this is how it looks like in the original](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#aussiegeek)). I don't think we can change a theme that much and still call it the same, so what I'm suggesting is to modify it yourself and call it something else. You can then set it up as a custom theme, see [customization](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization).
