### ISSUE TITLE
different themes for different terminals

### ISSUE THREAD

**Issue by joe23reptiles** [ohmyzsh/ohmyzsh#8354]
hi- first off- love this project. very well done. but now to my feature request (maybe its possible even now but i havent seen how yet).

i have the issue that the konsole program cant display certain glyphs from the nerd fonts. all other terminals i tested can but konsole cant. wouldnt be a big deal if dolphin hadnt hardcoded konsole as its terminal app. 

so since i really like the theme im using i dont want to change it- but konsole cant display it. so wouldnt it be great if one could use different themes in different terminals. in tilix for example the standart one and in urxvt the powerlevel10k. 

maybe u can find a way to make this happen. for example that way that u could have a tilix.zshrc file and a terminator.zshrc file etc

**Comment by romkatv** [comment]
Is powerlevel10k using a symbol that cannot be displayed by Konsole? What is this symbol?

**Comment by mcornella** [comment]
Disregarding the p10k, this is a simple change that you can do yourself in your zshrc file:
```zsh
# Here be code to detect the terminal emulator and
# then set the $TERMINAL_EMULATOR variable accordingly
# Then, set ZSH_THEME based on that:
case "$TERMINAL_EMULATOR" in
  tilix) ZSH_THEME=robbyrussell ;;
  urxvt) ZSH_THEME=powerlevel10k ;; # if installed in the OMZ custom directory
esac
````
Detecting the terminal emulator is where the hard part is. Some set a special variable that you can test for; if you can't find it in the documentation ask their respective projects.
