### ISSUE TITLE
Agnoster not properly displaying on tmux

### ISSUE THREAD

**Issue by kNgF** [ohmyzsh/ohmyzsh#8358]
While I switch to tmux , my agnoster looks like this
![image](https://user-images.githubusercontent.com/38097025/68267851-d43c8400-0079-11ea-9fe6-17a6b9668653.png)

but all this is perfect in normal terminal like shown below

![image](https://user-images.githubusercontent.com/38097025/68267872-e9191780-0079-11ea-8f1f-668e2b7eb07a.png)

Is there any way to make it look proper in tmux session too , I have added the tmux plugin too , but still this problem occurs

**Comment by mcornella** [comment]
Is utf8 enabled in tmux?

**Comment by kNgF** [comment]
yes i have provided the following command in my .tmux.conf file 
"set -g utf8 on"

**Comment by ceso** [comment]
Have you configured which fonts the terminal emulator should use? For example, with terminator you need to do it.

**Comment by kNgF** [comment]
The solution for this issue has been found

Solution: Use the command "tmux -u" to start the tmux session and it works fine
