### ISSUE TITLE
git-flow autocompletions question

### ISSUE THREAD

**Issue by hbarylskyi** [ohmyzsh/ohmyzsh#8365]
Hi. I've found the git-flow autocompletions plugin (https://github.com/bobthecow/git-flow-completion) for oh-my-zsh. 
As to my understanding, it just adds a couple of aliases to my shell. 

What I actually have been looking for is some kind of plugin which would autocomplete words for me while I type, so: `git flow fe` + TAB would be completed into `git flow feature`. Is there anything like that available?

**Comment by GokhanPolat** [comment]
Hello @hbarylskyi
Try to add git-flow or git-flow-avh to the zshrc plugin.

If you manually installed git with tools like package managers, please unlink **_git** file in **/usr/local/share/zsh/site-functions/** directory.

**Comment by mcornella** [comment]
Reminder to also [reset the completion cache](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-reset-the-completion-cache) (#7642) after enabling the plugin.
