### ISSUE TITLE
Add lrz format please

### ISSUE THREAD

**Issue by akimdi** [ohmyzsh/ohmyzsh#8383]
please add [lrz](https://github.com/ckolivas/lrzip) [format](https://wiki.archlinux.org/index.php/Lrzip) in plugin [extract](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/extract)

**Comment by mcornella** [comment]
I've never heard of it, can you provide the file extension and the command to extract the file?

**Comment by akimdi** [comment]
[for example](https://asciinema.org/a/8Rs8yk3JBLKebEJSmbmeObihS)

the resulting file has an extension ***.lrz**
in my example file test.**tar.bzip2.lrz**

**Comment by mcornella** [comment]
TODO: use example commands from https://github.com/ckolivas/lrzip#lrzip-101

**Comment by akimdi** [comment]
planning to add the zpaq format?
[https://github.com/zpaq/zpaq](https://github.com/zpaq/zpaq)

**Comment by mcornella** [comment]
zpaq doesn't seem to be actively maintained.

**Comment by mcornella** [comment]
Test #8500 for lrz support and +1 it if it works.

**Comment by akimdi** [comment]
Thank you very much. My laptop was under repair. I could not answer on time.

Everything works fine 👍
