### ISSUE TITLE
Update offer without any available update

### ISSUE THREAD

**Issue by ackbyte** [ohmyzsh/ohmyzsh#8387]
**Describe the bug**

**To Reproduce**
1. Open iTerm app or your terminal app of your choice 
2. You will receive sporadically the offer to update
3. Accept the update by **Y** or running **upgrade_oh_my_zsh**

**Expected behavior**
Only show the update reminder if any updates are really available.

**Screenshots or recordings**
![Screenshot 2019-11-12 at 11 45 31](https://user-images.githubusercontent.com/683434/68873309-b917e700-06ff-11ea-8f73-4c73fcc8082c.png)

**System:**
 - OS: macOS
 - Zsh version 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal: iTerm2

**Comment by mcornella** [comment]
We can use the [GitHub API](https://developer.github.com/v3/repos/commits/#get-a-single-commit) to get the latest master commit SHA. Something like
```zsh
curl -fsSL -H 'Accept: application/vnd.github.v3.sha' https://api.github.com/repos/robbyrussell/oh-my-zsh/commits/master
```
