### ISSUE TITLE
Python invocations are not secure

### ISSUE THREAD

**Issue by saleemrashid** [ohmyzsh/ohmyzsh#8400]
`python -c` invocations in plugins are not secure, because Python will include the current working directory in `sys.path`. As such, Python files in the current directory could be imported and executed, instead of the expected module. This does not apply to some built-in modules, such as `os` or `sys` (as these are imported before `sys.path` is configured), but is still applicable to a number of Oh My Zsh plugins.

In the following case, any Python code in a file named `json.py` in the current directory would be executed.

https://github.com/robbyrussell/oh-my-zsh/blob/451fb257032a37a7d9cae4631c03f65fd3aa7f1c/plugins/jsontools/jsontools.plugin.zsh#L13-L31

In this example, any Python code in a file named `urllib.py` (or its dependencies, e.g. `re.py` or `enum.py`) would be executed.

https://github.com/robbyrussell/oh-my-zsh/blob/451fb257032a37a7d9cae4631c03f65fd3aa7f1c/plugins/urltools/urltools.plugin.zsh#L14-L19

Ditto, but for `salt.py`.

https://github.com/robbyrussell/oh-my-zsh/blob/451fb257032a37a7d9cae4631c03f65fd3aa7f1c/plugins/salt/_salt#L274

**Comment by mcornella** [comment]
We could follow [this solution](https://bugs.python.org/issue33053#msg313966) or use [the `-I` option](https://docs.python.org/3/using/cmdline.html#id2) (which was only added in Python 3.4). So I'd go with the first option, prefixing them with:
```python
import sys; sys.path.remove("");
```

**Comment by saleemrashid** [comment]
@mcornella That makes me feel uneasy but, as the link you provided shows, I'm not sure if there is a more robust solution.

I don't use Oh My Zsh, so I don't have skin in the game here, but I'm wondering if there are any common configurations where this issue is present despite removing the empty string from `sys.path` :thinking:

**Comment by mcornella** [comment]
According to [the command line interface options](https://docs.python.org/3/using/cmdline.html#interface-options) docs, this is the only thing we need to check for.

**Comment by mcornella** [comment]
I've submitted #8408, I think I covered all our cases.
