### ISSUE TITLE
non-compliant posix code in tools/upgrade.sh

### ISSUE THREAD

**Issue by seanbreckenridge** [ohmyzsh/ohmyzsh#8416]
**Describe the bug**

Related to the recently merged #8394 

Since `upgrade_oh_my_zsh` uses `sh` instead of `bash`, and the code on line 36 [here](https://github.com/ohmyzsh/ohmyzsh/blob/b80b1a1e8b30e5f2a7c4977019cf56e72c434037/tools/upgrade.sh#L36) is somewhat `bash` specific, the command may fail if `sh` is linked to some other POSIX-compliant implementation.

```
$ upgrade_oh_my_zsh
/home/sean/.oh-my-zsh/tools/upgrade.sh: 36: /home/sean/.oh-my-zsh/tools/upgrade.sh: [[: not found
```

**To Reproduce**

- Have `sh` linked to something other than bash (I have it linked to [dash](http://gondor.apana.org.au/~herbert/dash/))
- call `upgrade_oh_my_zsh`

**Expected behavior**

calling `upgrade_oh_my_zsh` to not throw any errors.

**System:**
 - OS: [e.g. macOS]: Linux (Arch)
 - Zsh version [e.g. 5.6]: zsh 5.7.1 (x86_64-pc-linux-gnu)
 - Terminal emulator [e.g. iTerm2]: Termite v15

I believe this could be fixed by simply changing:

`[[ -n "$remote" ]]` to `[ -n "$remote" ]`, but edge cases in shell conditional statements are not my forte.

**Comment by mrvon** [comment]
Yes, same problem after upgrade to lastest version

**Comment by mcornella** [comment]
Well-spotted thanks! We should probably transfer that to using zsh instead. Try to run `upgrade_oh_my_zsh` again, if it fails again due to the syntax error just enter the `$ZSH` folder and run `git pull --rebase --stat origin master`.

**Comment by seanbreckenridge** [comment]
Thanks!

calling `upgrade_oh_my_zsh` to pull from the repo worked fine (which updated tools/upgrade.sh), `upgrade_oh_my_zsh` now works fine
