### ISSUE TITLE
Always show symbol "~%" after command when logging in remote PC with my local PC

### ISSUE THREAD

**Issue by MichaelDiao** [ohmyzsh/ohmyzsh#8421]
I use ohmyzsh in my local PC and remote server PC, and when logging in remote PC with my local PC in Terminal, every command inputted always follows a symbol "~%".  Curiously，Each time you execute this command, there is one more symbol in the terminal。

eg. 
  In my local PC, log in remote PC: ssh work@11.22.33.44
 
![image](https://user-images.githubusercontent.com/19757545/69472156-82b62800-0de1-11ea-840c-9b38d3ab2d68.png)

But, there is not the situation in Iterm2. It works well like this:
![image](https://user-images.githubusercontent.com/19757545/69472226-3c14fd80-0de2-11ea-8344-8a3db64d2d58.png)

How to fix it? Please give me some advice, thanks.

**Comment by mcornella** [comment]
Can you post the zshrc file of the PC where it happens?

**Comment by larson-carter** [comment]
@MichaelDiao Can you give me your complete setup on both ends? ZSH versions, terminal (appears to be macOS), and any other useful information?

**Comment by MichaelDiao** [comment]
Sorry, because the configure file has been modified by me carelessly. Now I get rid of it. Thanks again!
