### ISSUE TITLE
Vscode integrated terminal locale command not found

### ISSUE THREAD

**Issue by rjzheng** [ohmyzsh/ohmyzsh#8423]
I'm getting `/etc/zshrc:7: command not found: locale` at the beginning of every debug session when I try to debug in Vscode using the "integratedTerminal" console option.

I made sure to include all of my PATHs and checked that `locale` does exist.

```sh
> $ which locale
/usr/bin/locale
> $ echo $PATH
..:/usr/bin:/usr/local/bin:..
```
I checked out `/etc/zshrc` and indeed it calls `locale`
```zsh
# System-wide profile for interactive zsh(1) shells.

# Setup user specific overrides for this in ~/.zhsrc. See zshbuiltins(1)
# and zshoptions(1) for more details.

# Correctly display UTF-8 with combining characters.
if [[ "$(locale LC_CTYPE)" == "UTF-8" ]]; then
    setopt COMBINING_CHARS
fi
```

I wonder if this is because `/etc/zshrc` is run before `~/.zshrc` since i am exporting PATH in `~/.zshrc`. If so how would I go about fixing this? This only happens within Vscode when I try to debug using "integratedTerminal".

Here's my settings in Vscode
```json
...
"terminal.integrated.shell.osx": "/bin/zsh",
"terminal.integrated.shellArgs.osx": []
```

Any help is appreciated, thank you!

**Comment by mcornella** [comment]
`/usr/bin` must not be in `$PATH` when it is called in `/etc/zshrc`. Add an `echo $PATH` to it to check.

**Comment by rjzheng** [comment]
I tried it with and without, still causes the same issue. Also if `locale` is at `/usr/bin` why would we not want to include it in PATH?

**Comment by mcornella** [comment]
By `must not be` I meant that that was probably the problem, not that it shouldn't be there. It definitely needs to be in `$PATH`.

**Comment by rjzheng** [comment]
Gotcha, well I was able to give myself read-write permission for `/etc/zshrc` and exported `/usr/bin` before  `locale` was called and it solved my problem. Not sure if I was suppose to edit that file since it was read-only but got the job done.

**Comment by mcornella** [comment]
It is weird that /usr/bin wasn't in $PATH but glad you solved it.

**Comment by OguzhanPolatNwc** [comment]
Would you please say me how you made it ? I mean the steps @rjzheng
