### ISSUE TITLE
history command times bug

### ISSUE THREAD

**Issue by RokasUrbelis** [ohmyzsh/ohmyzsh#8424]
When the number of commands reaches 10001, it will return to this number every time it is reconnected

![image](https://user-images.githubusercontent.com/48517501/69481107-2555c180-0e49-11ea-8b63-9b3a63908c85.png)

**Comment by mcornella** [comment]
This is because you reached the limit of stored commands in the history. You need to modify the `SAVEHIST` variable to be greater than 10000 if you want to store more. You can redefine it in your zshrc file after OMZ is sourced.

**Comment by RokasUrbelis** [comment]
![image](https://user-images.githubusercontent.com/48517501/69493945-78cf1a80-0ef0-11ea-8fec-9a1161334e47.png)
not work

**Comment by RokasUrbelis** [comment]
solved，thanks
![image](https://user-images.githubusercontent.com/48517501/69494031-c009db00-0ef1-11ea-9a92-b0e62a6aa66c.png)
