### ISSUE TITLE
ls display both directories and files with the same color

### ISSUE THREAD

**Issue by chawkichalladia** [ohmyzsh/ohmyzsh#8429]
as the title said, when i installed zsh for my terminal on ubuntu i found that the ls command displays the results using the same color for both files and folders.
i'm using zsh with powerline and powerlevel9k theme but didn't find any mention to a similar problem with the issues section for their git repos.

i saw an already posted issue with the same problem but was in chinese so i couldn't fully follow what was being said but i saw that some information was requested so i'll post this image bellow.

![Screenshot from 2019-11-25 11-00-28](https://user-images.githubusercontent.com/39971257/69531059-7d88e280-0f73-11ea-8103-6c33f3002f3a.png)

environment:

- OS: ubuntu (18.04 LTS) 
- zsh: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

**Comment by mcornella** [comment]
`ls` needs to be passed `--color=auto` or some other `--color` option. OMZ normally aliases ls already to pass that option.
