### ISSUE TITLE
~d (tilde d) expands to a path. Why and what feature of zsh or omz is it?

### ISSUE THREAD

**Issue by unphased** [ohmyzsh/ohmyzsh#8431]
```
% echo ~d                    
/usr/share/zsh/functions/Zle 
```

I found this by accident, it seems like there are many expansions that start with tilde, and have something to do with users' home directories (e.g. `~root` is `/root`), but there exists no user `d` on this system...

**Comment by mcornella** [comment]
See [Filename Expansion](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Filename-Expansion), specifically the static named directories section. Is very possible that there exists a variable named d with the value of that directory, probably left over from a
```zsh
for d in ...; do ...; done
```
construct.
