### ISSUE TITLE
Autocompletion for apt-get doesn't show packages

### ISSUE THREAD

**Issue by junkdeck** [ohmyzsh/ohmyzsh#8433]
**Describe the bug**

Partially filling a `sudo apt install` command and tabbing doesn't print out a list of matches.
This works fine if I remove `source $ZSH/oh-my-zsh.sh` from my `.zshrc`.

**To Reproduce**

Install zsh, oh-my-zsh, use my [.zshrc](https://gist.github.com/junkdeck/68f7037697540e366f4a77aea5f73f0d)

**Expected behavior**

Hitting tab should show a list of matches when installing a package from `apt` or `apt-get`.

**Screenshots or recordings**

ZSH, nothing happens when hitting tab
![image](https://user-images.githubusercontent.com/2787758/69710199-39c2e400-10ff-11ea-8eca-3ef18acd52b0.png)

BASH, shows expected list of matching packages.
![image](https://user-images.githubusercontent.com/2787758/69710216-46dfd300-10ff-11ea-9f20-bf3151bff0dd.png)

**System:**
 - OS: Debian 10 (buster)
 - Zsh version: zsh 5.7.1
 - Terminal emulator: rxvt-unicode v9.22

**Comment by mcornella** [comment]
Can you try removing the compdump cache (`rm $ZSH_COMPDUMP`) and restarting zsh with `exec zsh`?

**Comment by junkdeck** [comment]
Sorry - I switched from oh-my-zsh to antibody and "solved" the issue.
