### ISSUE TITLE
$ZSH/lib/grep.zsh is too slow for what it does - proposal to use $ZSH_CACHE_DIR

### ISSUE THREAD

**Issue by mattmc3** [ohmyzsh/ohmyzsh#8444]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
$ZSH/lib/grep.zsh

**Is your feature request related to a problem? Please describe.**
$ZSH/lib/grep.zsh is way too slow for its simple function - namely to generate a single grep alias.

Running this script highlights how inefficient $ZSH/lib/grep.zsh is compared to the rest of the scripts in lib:

```zsh
#!/usr/bin/env zsh
zmodload zsh/zprof
for config_file ($ZSH/lib/*.zsh); do
  source $config_file
done
zprof
```

This is the profiler output:
```
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    2           9.95     4.97   62.36%      9.95     4.97   62.36%  grep-flag-available
 2)    2           2.81     1.41   17.65%      2.81     1.41   17.65%  env_default
 3)    1           1.72     1.72   10.80%      1.72     1.72   10.80%  colors
 4)    2           0.94     0.47    5.88%      0.94     0.47    5.88%  add-zsh-hook
 5)    1           0.29     0.29    1.81%      0.29     0.29    1.81%  is-at-least
 6)    1           0.24     0.24    1.52%      0.15     0.15    0.97%  omz_termsupport_preexec
 7)    1           0.09     0.09    0.55%      0.09     0.09    0.55%  title
```

**Describe the solution you'd like**
I'd propose the following simple change to $ZSH/lib/grep.zsh, which would cache the results of calculating the grep alias for one day and source those.

```zsh
# get any cached grep alias file if it's less than 24 hours old
_grep_alias_cache=($ZSH_CACHE_DIR/grep_alias.zsh(Nm-24))
if (( $#_grep_alias_cache )); then
    source $ZSH_CACHE_DIR/grep_alias.zsh
else
    # ... do all the same things $ZSH/lib/grep.zsh already does in the else part
    # then cache the result
    echo "alias grep=\"grep $GREP_OPTIONS\"" > $ZSH_CACHE_DIR/grep_alias.zsh
fi
unset _grep_alias_cache
```

After implementing this, the performance profile looks much better (after the first run of the day obviously):

```zsh
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    2           2.29     1.14   56.40%      2.29     1.14   56.40%  env_default
 2)    1           0.96     0.96   23.73%      0.96     0.96   23.73%  colors
 3)    2           0.34     0.17    8.37%      0.34     0.17    8.37%  add-zsh-hook
 4)    1           0.32     0.32    7.90%      0.32     0.32    7.90%  is-at-least
 5)    1           0.15     0.15    3.60%      0.08     0.08    2.05%  omz_termsupport_preexec
 6)    1           0.06     0.06    1.55%      0.06     0.06    1.55%  title
```

**Describe alternatives you've considered**
You could also do if/else statements for OSes like MacOS, Cygwin, etc. to make known grep aliases with supported features, but that's convoluted. There's really nothing wrong with asking grep which features it supports - it's just wasteful to do it on every single shell invocation when it's never really going to change on you.

**Additional context**
I am willing to submit a PR with this simple change, but felt it was worth opening it to discussion in case there's other input to consider. Namely:
- Is 24 hours the right time to cache the result? Longer?
- Is there some reason you wouldn't want to see the `$ZSH_CACHE_DIR` used like this. Right now it's only used for updating omz (EDIT: whoops, looks like it's also used for completions and other things too - just nothing quite like this)
- Any other implementation proposals or considerations?

Thanks for considering!

**Comment by mattmc3** [comment]
For completeness, I submitted a PR with this proposed change: https://github.com/ohmyzsh/ohmyzsh/pull/8445

Also, be sure to view the diff without whitespace b/c of the indention change in putting the existing code in an else block:
https://github.com/ohmyzsh/ohmyzsh/pull/8445/files?w=1

**Comment by joeycozza** [comment]
I like this change. In my own personal .oh-my-zsh directory, I just deleted the lib/grep.zsh file because it was so slow.

**Comment by mattmc3** [comment]
This is a pretty benign change and has been out here for a couple months now. Any chance of getting a merge or at least some activity on the PR?
