### ISSUE TITLE
Stop oh-my-zsh from resetting screen window titles

### ISSUE THREAD

**Issue by KihongHeo** [ohmyzsh/ohmyzsh#8449]
Hi,

How can I stop oh-my-zsh from resetting screen window titles? I set a title of my screen window. Whenever I run a command, it reset the title to the current directory name. How can I turn off this feature?

**Comment by mattmc3** [comment]
@KihongHeo - Add this line to your .zshrc:

`DISABLE_AUTO_TITLE=true`

You could also customize it by doing this:
```zsh
# copy omz's term support.zsh to your custom area
cp $ZSH/lib/termsupport.zsh $ZSH_CUSTOM/lib/termsupport.zsh
# edit until your heart's content
${VISUAL:$EDITOR} $ZSH_CUSTOM/lib/termsupport.zsh
```

**Comment by KihongHeo** [comment]
Thanks a lot. Actually `screen` plugin was a blocker that ignores `DISABLE_AUTO_TITLE=true`.
It works fine now.
