### ISSUE TITLE
cd command sometimes hangs

### ISSUE THREAD

**Issue by m77can** [ohmyzsh/ohmyzsh#8452]
**Describe the bug**
when I input cd command , the cursor stays at the start of line  , then type any key can  make it continue working. it happens sometimes.
when I  set  ZSH_THEME to "",  cd command works well .

**To Reproduce**
hard to reproduce, it happens randomly

**Screenshots or recordings**
the cursor stays at the start of line
![image](https://user-images.githubusercontent.com/4841386/70144096-281da580-16d8-11ea-8f48-7e6cddacbb8d.png)

**System:**
 - OS: macOS
 - Zsh version:  5.7.1
 - Terminal emulator: Term2

**Comment by mcornella** [comment]
Can you explain more? It's not clear what you mean by stopped, or what it's supposed to happen in that screenshot.

**Comment by m77can** [comment]
@mcornella when I input cd  command , the cursor stays  at the start of line

**Comment by jtotoole** [comment]
if you're using zsh you don't need the `cd` command to change directories. for example, if you're in directory `foo` and you want to change to `foo/bar`, just type `bar`.

**Comment by m77can** [comment]
@jtotoole It doesn't matter which directory it is in. The problem now is that after I enter the cd command, the cursor jumps to the next line and then it doesn't move. The normal situation should be to jump to the directory I want to enter correctly. I just entered the cd command in the screenshot just to reproduce the problem.

**Comment by mcornella** [comment]
Does it stay that way forever? This has happened to me with the beta version of Windows Terminal, where the enter registers as a "soft enter", where it just moves the cursor one line below so you can write another command. I think that's bound to `ALT`+`ENTER` in some cases.

**Comment by m77can** [comment]
@mcornella As long as  press any key, the command can continue to execute. The cd command in my screenshot is just an example. In my actual use, this problem will also occur in other commands.

**Comment by mcornella** [comment]
Let's see what's being executed then, by running zsh in trace mode. To enable it, run `set -xv`, then run the `cd` command. To disable trace mode, run `set +xv`.

For example, this is me trying to debug `cd somewhere`:
```
$ set -xv; cd somewhere; set +xv
+-zsh:5> cd somewhere
cd: no such file or directory: somewhere
+-zsh:5> set +xv
$ |
```

It should print something. If not, it means zsh hasn't actually ingested the command yet and is still in the command prompt waiting to be feed a command. Let me know what you get.

**Comment by m77can** [comment]
@mcornella This may be caused by the command to get git information in the theme, the following is the information during execution.
![oh-my-zsh-error](https://user-images.githubusercontent.com/4841386/70844373-30fe3c00-1e7b-11ea-8a79-37574e7cba0b.jpg)

**Comment by mcornella** [comment]
I can't see the prompt where you run `cd`. Run the command above `set -xv; cd; set +xv` and it shouldn't display these theme (prompt) functions.

**Comment by m77can** [comment]
@mcornella  I run the set -xv command first, then run the cd command continuously, and then the screenshots I send will appear. If I run it according to the command you set -xv; cd; set + xv, it is normal and there will be no problems and it did not display these prompts

**Comment by mcornella** [comment]
Yeah, run only `set -xv; cd; set +xv`, repeatedly until you get to a point where cd hangs.

**Comment by m77can** [comment]
@mcornella  this the screenshots.
![error_20191215](https://user-images.githubusercontent.com/4841386/70859589-39c14180-1f51-11ea-99c1-2eced5e7559a.jpg)

**Comment by rememberYou** [comment]
I have the same problem, when I load any theme with `ZSH_THEME`, I can't get to a large folder anymore (e.g., my courses).

Has the concern been resolved? If necessary I can make a GIF so that you can have a better visualization of the problem.

**Comment by mcornella** [comment]
Are those git repositories? You might be encountering that the git prompt function doing its thing. If not, try the commands above (https://github.com/ohmyzsh/ohmyzsh/issues/8452#issuecomment-565730086) and if you want, you can record an [asciinema](https://asciinema.org/) session instead of a gif.

**Comment by rememberYou** [comment]
Thank you. Indeed, my courses are in a git repository. I didn't try to move all the files to a normal folder and give a try.

**Comment by mcornella** [comment]
> @mcornella this the screenshots.
> ![error_20191215](https://user-images.githubusercontent.com/4841386/70859589-39c14180-1f51-11ea-99c1-2eced5e7559a.jpg)

This didn't provide a satisfactory trace, since the command didn't hang (it got to execute `set +xv` which happens after running `cd`). Repeat the process and reopen if the issue still happens.

**Comment by snowman** [comment]
In my case, 
```sh
$ git clone https://github.com/kkevsekk1/AutoX
$ set -xv
$ cd AutoX
...omit lines
+parse_git_dirty:1> local STATUS
+parse_git_dirty:2> local -a FLAGS
+parse_git_dirty:3> FLAGS=( --porcelain )
+parse_git_dirty:4> [[+parse_git_dirty:4> __git_prompt_git config --get oh-my-zsh.hide-dirty
+__git_prompt_git:1> GIT_OPTIONAL_LOCKS=0 git config --get oh-my-zsh.hide-dirty
+parse_git_dirty:4> [[ '' != 1 ]]
+parse_git_dirty:5> [[ '' == true ]]
+parse_git_dirty:8> case  (git)
+parse_git_dirty:8> case  (*)
+parse_git_dirty:15> FLAGS+='--ignore-submodules=dirty'
+parse_git_dirty:18> STATUS=+parse_git_dirty:18> __git_prompt_git status --porcelain '--ignore-submodules=dirty'
+parse_git_dirty:18> STATUS=+parse_git_dirty:18> tail -n 1
```

so simply comment out file `/home/my/.oh-my-zsh/lib/git.zsh`
```diff
-    STATUS=$(__git_prompt_git status ${FLAGS} 2> /dev/null | tail -n 1)
+    # STATUS=$(__git_prompt_git status ${FLAGS} 2> /dev/null | tail -n 1)
```
