### ISSUE TITLE
Profanity

### ISSUE THREAD

**Issue by dearingc** [ohmyzsh/ohmyzsh#8455]
Is there a way to avoid filenames and readme file content that include objective profanity?  This can complicate use on monitored networks.

Specific example:
plugins/thef***/README.md

**Comment by mcornella** [comment]
[We're not ashamed of using "bad" words](https://github.com/ohmyzsh/ohmyzsh/pull/4170#issuecomment-122640094). The FBI agent checking your logs will surely understand the nuance here.
