### ISSUE TITLE
Add support for tig completion to gitfast 

### ISSUE THREAD

**Issue by arekfu** [ohmyzsh/ohmyzsh#8465]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
gitfast

**Is your feature request related to a problem? Please describe.**
Autocompletion for the [`tig`](https://github.com/jonas/tig) command is not included in gitfast. zsh's default git completion script just uses the same completion function as for git-log, which I think is fine.

**Describe the solution you'd like**
I would like gitfast to provide a `_tig` completion function that should behave like the one for git-log.

**Describe alternatives you've considered**
I have tried to define the completion function myself, but I have not succeeded,

**Comment by mcornella** [comment]
That's an upstream issue (i.e. of the official git repository). You can either stop using gitfast and use zsh's official completion, or suggest this change in the official git repository.
