### ISSUE TITLE
Shift+Tab with vi-mode doesn't cycle completion suggestions

### ISSUE THREAD

**Issue by jorgeOmurillo** [ohmyzsh/ohmyzsh#8468]
**Describe the bug**

When `vi-mode` is enabled, `shift+tab` does not cycle backwards through the autocomplete suggestions.
If `vi-mode` is removed from the plugins, `shift+tab` works as it should.

**To Reproduce**
1. Enable plugin 'vi-mode'.
2. When an autocomplete suggestion is available, shift+tab does not cycle backwards.

**System:**
 - OS: [macOS Catalina]
 - Zsh version [5.7]
 - Terminal emulator [iTerm2]

**Comment by mcornella** [comment]
In my system, `shift`+`tab` corresponds to the bindkey sequence `^[[Z`, so if I run
```zsh
bindkey '^[[Z' reverse-menu-complete
```

I get the correct behavior, try it yourself. If not, get the bindkey sequence like so (from the [Troubleshooting section of the wiki](https://github.com/ohmyzsh/ohmyzsh/wiki/Troubleshooting#keyboard-shortcut-problems)):
> You can see the exact sequence a keyboard shortcut sents by pressing CTRL+V and then the keyboard shortcut. For example: CTRL+V, CTRL+L will output ^L (^ represents the Control key).

If you get the same command we can edit the `vi-mode` plugin to make it work for all users.

**Comment by jorgeOmurillo** [comment]
After running `bindkey '^[[Z' reverse-menu-complete`, `shift+tab` works correctly.
That fixes the issue.

**Comment by mcornella** [comment]
We should fix that in `lib/key-bindings.zsh`: 
https://github.com/ohmyzsh/ohmyzsh/blob/664664f6cd8a1c02a38063c8f2104f0515a19399/lib/key-bindings.zsh#L55-L57

Something like
```zsh
bindkey -M viins '^[[Z' reverse-menu-complete
bindkey -M vicmd '^[[Z' reverse-menu-complete
```
