### ISSUE TITLE
[yarn plugin] Add 'yl' alias for 'yarn lint'

### ISSUE THREAD

**Issue by MikeSuiter** [ohmyzsh/ohmyzsh#8470]
I always run `yarn lint` before committing and now that I'm used the Yarn plugin hate all that typing 😂

**Is your feature request related to a particular plugin or theme? If so, specify it.**
Yarn plugin

**Describe the solution you'd like**
Typing `yl` would execute `yarn lint`

**Comment by giovanepadawan** [comment]
Hi, I would like to implement this feature.
What about using `yln` instead of `yl`?
`yl` could be confused for `yarn list` command, and would be in conflict with the alias for `yum list`

**Comment by yooouuri** [comment]
Pro tip: use husky (git hooks) to automatically run yarn lint before you commit.

**Comment by MikeSuiter** [comment]
@giovanepadawan `yln` sounds good to me.

@yooouuri We do use Husky but a 5 second `yarn lint` is a quick check to make sure Husky won't fail and its output is a lot more readable than what Husky pukes out in the IDE.
