### ISSUE TITLE
Global CLI Utilities Not Visible After Install of Oh My Zsh

### ISSUE THREAD

**Issue by RHieger** [ohmyzsh/ohmyzsh#8473]
Hi,

I am new to Oh My Zsh and definitely like what I see. Unfortunately, the moment I installed the framework, all global commands ceased working. Most notably, I had nvm installed and two different versions of node.js. I also had at least one version of Angular installed.

My system is a late 2018 Mac Book Pro with Touchbar and 32GB RAM, an i9 processor and 1TB SSD (nearly top of the line at the time).

I am running Mac OS Catalina, which automatically switched over to using the zsh shell. The problems actually began then. I was able to get nvm back up and running using another set of instructions in a Github Gist&mdash;[install-nvm-zsh](https://gist.github.com/mike-casas/6d489bebf48d89f5109cd1395aabe150).

Once I installed Oh My Zsh, everything fiixed by the above gist ceased to work.

I've been reading around the net, and there seems to be much conflicting information, and my development studies are now at a standstill.

Any insights you can provide are greatly appreciated.

Thanks,

Robert Hieger

**Comment by mattmc3** [comment]
Can you run `echo $PATH` under both configs? I suspect you didn't properly set your `$PATH` in you .zshrc after installing oh-my-zsh. Make sure `/usr/local/bin` is in you `$PATH`, usually you'll want it to be before `/usr/bin`.

**Comment by mcornella** [comment]
Note that OMZ substitutes the zshrc file for another when installing. You should see a `.zshrc.pre-oh-my-zsh` or similar file with your settings prior to installing ohmyzsh. Try porting these to the newly created zshrc file.
