### ISSUE TITLE
iTerm2 terminal output colors do not seem to be displaying properly

### ISSUE THREAD

**Issue by tgreen7** [ohmyzsh/ohmyzsh#8475]
**Describe the bug**
iTerm2 terminal output colors do not seem to be displaying properly

**Screenshots or recordings**
Here are some screenshots of running in a zsh terminal:
<img width="823" alt="Screen Shot 2019-12-14 at 1 11 33 AM" src="https://user-images.githubusercontent.com/10415101/70846572-6705d680-1e0f-11ea-947d-f6cb9e5f225e.png">
<img width="822" alt="Screen Shot 2019-12-14 at 1 10 07 AM" src="https://user-images.githubusercontent.com/10415101/70846573-679e6d00-1e0f-11ea-8e20-0801a6a2a450.png">

And here are the same places while running in bash:
<img width="844" alt="Screen Shot 2019-12-14 at 1 12 52 AM" src="https://user-images.githubusercontent.com/10415101/70846576-6f5e1180-1e0f-11ea-9a6f-23a56453ebec.png">
<img width="836" alt="Screen Shot 2019-12-14 at 1 12 30 AM" src="https://user-images.githubusercontent.com/10415101/70846577-6f5e1180-1e0f-11ea-9012-c052bff4fb7d.png">

**System:**
 - OS: MacOS 10.14.6 
 - Zsh version 5.3
 - Terminal emulator: iTerm2

**Additional context**
This used to not be an issue but I am not sure what has changed.

**Comment by mcornella** [comment]
What's the value of `$TERM`?

**Comment by tgreen7** [comment]
@mcornella it is `xterm-256color`

**Comment by mcornella** [comment]
Do other commands show colors, like `ls` or `git log`? If they do, you could trace back the problem to what the tools in those screenshots do to figure out whether to use colors or not. It's difficult to debug this without more information.

**Comment by tgreen7** [comment]
Ok I found out it was because I was running those commands with shelljs and this is a known issue
https://github.com/shelljs/shelljs/issues/86
