### ISSUE TITLE
zsh-navigation-tools : ncurses broken in n-* commands (unwanted identations)

### ISSUE THREAD

**Issue by Maxzor** [ohmyzsh/ohmyzsh#8476]
Hello,
I have znt from oh-my zsh all installed today,
When I run n-* commands, There is jitter on the terminal when moving the cursor, something akin "moving to a line not visited yet adds 2 spaces to it":
https://framapic.org/gallery#HtPmvngUBE9r/gxDYQNJze4gH.png&gid=1&pid=1
![image](https://user-images.githubusercontent.com/1441704/71024474-4dada480-2105-11ea-8f83-2f1dcb40eafb.png)

Any clue? BR
https://github.com/psprint/zsh-navigation-tools/issues/29

**Comment by Maxzor** [comment]
Note that this does not look like a znt-tool issue, but rather an oh-my-zsh integration and ncurses related.
I have not the issue when sourcing the plugin outside ohmyzsh.
Here is my .[zshrc](https://framabin.org/p/?958cbb280828cf5b#iKwdHJo1xMrtip0QO3/hFin7UCV3onbL4hFxDDO3HFI=)

My prompt is 

PROMPT='%{$fg_bold[green]%}%n@%m%{$reset_color%}:%B%F{75}%~%{$reset_color%}$ '
5   RPROMPT='%{$fg_bold[blue]%}$(git_prompt_info)%{$fg_bold[blue]%}% %'
  1 ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
  2 ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
  3 ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
  4 ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"

See printenv in [znt thread](https://github.com/psprint/zsh-navigation-tools/issues/29).

**Comment by mcornella** [comment]
> I have not the issue when sourcing the plugin outside ohmyzsh.

Can you expand on this? When saying outside ohmyzsh, do you mean *without loading ohmyzsh* or _loading OMZ **and** the version [from the upstream repo](https://github.com/psprint/zsh-navigation-tools)_?

**Comment by Maxzor** [comment]
It is an "and" indeed, will try to not load ohmy on the side, but I expect the same result

**Comment by YoungCatChen** [comment]
I've got the same issue with oh-my-zsh.

**Comment by jcrsilva** [comment]
This is happening to me aswell. Oh-my-zsh with the powerlevel-10k theme.

@YoungCatChen 's suggestion of changing border to 1 worked for me.

**Comment by jcrsilva** [comment]
Seems like this is fixed on master.
