### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by ghost** [ohmyzsh/ohmyzsh#848]
I can't seem to uninstall. I get this error:

zsh: command not found: uninstall_oh_my_zsh

Any help please?

Thanks!

**Comment by TheSeventhLion** [comment]
I still have zsh as my default in my integrated terminal in VSCode

**Comment by julien-leroy** [comment]
sudo sh ~/.oh-my-zsh/tools/uninstall.sh

**Comment by ulayera** [comment]
> Delete `~/.oh-my-zsh` and `~/.zshrc`.

this is the way, i actually used the uninstaller script before and didn't worked

the only weird leftover is i had to manually change the default bash from `/bin/zsh` to `/bin/bash`
