### ISSUE TITLE
git: Permission denied

### ISSUE THREAD

**Issue by chrisdrackett** [ohmyzsh/ohmyzsh#849]
After installing I get the following on startup:

git: Permission denied

I do have the git plugin installed, but I'm not sure what is throwing this error :\

**Comment by chenkai** [comment]
i got same problem when set  theme in zhsrc file. just make sure you are owned the base directory. problem resolved.

**Comment by clydiscope** [comment]
vontobel 's solution worked for me

**Comment by ilala1** [comment]
vontobel's solution didn't work for me. How do you set the permissions so you own the directory?

**Comment by tylerssn** [comment]
I resolved this on a Centos 7 machine by...

1. Downloading install.sh: `wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh`
2. Removing the if parameters (oh-my-zsh was trying to install to /root/.oh-my-zsh) so that only `ZSH=~/.oh-my-zsh` remained:
```
  if [ ! -n "$ZSH" ]; then
    ZSH=~/.oh-my-zsh
  fi
```
3. Executing: `$ ./install.sh`

**Comment by russmack** [comment]
This can also happen if your ssh-agent is stopped:`eval "$(ssh-agent -s)"`
Then ensure required key is added: `cd ~/.ssh` eg `ssh-add id_rsa`
Then either `upgrade_oh_my_zsh`
or `cd $ZSH` `git pull --rebase --stat origin master`

**Comment by Zullybur** [comment]
I was able to resolve this by making sure I assigned the correct ownership to **all** the files in `$ZSH` including all subdirs:
`sudo chown -R <your_user>:<your_group> $ZSH/.git`

**Comment by clementohNZ** [comment]
For me, the environment variable `$ZSH` was pointing to a non-existent directory. I just ran `unset ZSH` and reinstalled it. Worked fine afterwards :)

**Comment by milosmns** [comment]
Tried all of the above and still failing today.
On my side it looks like there's a git hook or something constantly changing `tools/install.sh`... it changes even after `git status`
