### ISSUE TITLE
Tmux.conf no longer functions

### ISSUE THREAD

**Issue by DataRepository** [ohmyzsh/ohmyzsh#8491]
I've tried over and over again to get Tmux to cooperate with ZSH but unfortunately I can't find the tmux.conf folder since switching from BASH.

When I switch back to bash, I'm able to edit the file with no issues at all whatsoever. However, when I switch back to ZSH the ~/.tmux.conf file is empty. 

Has anyone else experienced this issue? I've looked for solutions for the past 2 days and have hit a wall.

Here's what I come across: https://thumbs.gfycat.com/ShockingCalmLice-mobile.mp4

**Comment by mcornella** [comment]
Can you post a screenshot of what the path using bash is? You may be using different users.

**Comment by DataRepository** [comment]
> Can you post a screenshot of what the path using bash is? You may be using different users.

I switched to bash and unfortunately I can't access the ~/.tmux.conf file. A bit odd since there were no issues when I was using bash but the switch to ZSH has me a little perplexed. 

I tried reverting back to bash just now and the file itself is non-existent. This might perhaps be a Tmux issue better suited for Tmux support but it's just odd.

**Comment by mcornella** [comment]
Alright I'll close this as it doesn't seem to be OMZ's fault. Thanks
