### ISSUE TITLE
zero-padded file modes in the repository

### ISSUE THREAD

**Issue by progovoy** [ohmyzsh/ohmyzsh#8493]
The ohmyzsh repository contains "zero-padded file modes" when running git fsck.

**Bug description**

The ohmyzsh repository contains "zero-padded file modes" when running git fsck.
This prevents pushes to other repositories and in general it's best not to have a corrupted repository.

A possible fix can be running:
https://stackoverflow.com/questions/14700502/how-to-fix-git-zero-padded-file-modes-warning

**To Reproduce**
1. Run git fsck
2. See error

**Expected behavior**
No output from git fsck

**System:**
 - OS: All

**Comment by mcornella** [comment]
This has been reported before. The permanent solution would imply rewriting the git history starting from 2009: https://github.com/ohmyzsh/ohmyzsh/issues/4963#issuecomment-204040739. So I chose to change the local git-config of the OMZ folder, see: https://github.com/ohmyzsh/ohmyzsh/blob/38929084f98684b9267d7f0cfe3e7f9aa5f861d2/tools/upgrade.sh#L29-L32

Running these inside the ZSH folder should be enough to fix any problems you have.
