### ISSUE TITLE
Use current color them in colored-man-pages

### ISSUE THREAD

**Issue by leoheck** [ohmyzsh/ohmyzsh#8496]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
`colored-man-pages`

**Is your feature request related to a problem? Please describe.**
The `colored-man-pages` plugin is a great thing to read and find information fast, however, I am not able to distinguish the hardcoded colors well.

**Describe the solution you'd like**
I just would like to ask, if possible, that the plugin uses the default terminal colors. So, the manpages will fit better for the different users.

**Describe alternatives you've considered**
I can just override the hardcoded values by myself, but if it could use the current theme colors it will be much more pleasant.

**Additional context**
_null_

**Comment by mcornella** [comment]
What do you mean with default terminal colors? The plugin uses the default red, green and blue (this last one for background). The color the terminal app gives to these depends on the color scheme chosen in the terminal settings.

**Comment by mcornella** [comment]
This is what I see in the Windows Terminal with a Campbell color scheme
![image](https://user-images.githubusercontent.com/1441704/71484696-0b274e80-280e-11ea-9177-df13733483aa.png)
The exact shade of red, green and blue will depend on your chosen color scheme.

**Comment by mcornella** [comment]
Disregard my previous comment, these aren't truly default. The default ones would be '\e[31m', '\e[32m' and '\e[44m' for red, green and bg blue respectively.

**Comment by mcornella** [comment]
How about this selection of colors? (copy-paste into the terminal)
```zsh
function colored() {
	local RED=$(printf '\e[31m')
	local GREEN=$(printf '\e[32m')
	local BG_BLUE=$(printf '\e[1;44m')
	local RESET=$(printf '\e[0m')

	env \
		LESS_TERMCAP_mb=$RED \
		LESS_TERMCAP_md=$RED \
		LESS_TERMCAP_me=$RESET \
		LESS_TERMCAP_so=$BG_BLUE \
		LESS_TERMCAP_se=$RESET \
		LESS_TERMCAP_us=$GREEN \
		LESS_TERMCAP_ue=$RESET \
		PAGER="${commands[less]:-$PAGER}" \
		_NROFF_U=1 \
		PATH="$HOME/bin:$PATH" \
			"$@"
}
```

**Comment by leoheck** [comment]
My terminal has these colors as the current color theme (color scheme, actually).
However, if I change something there, like, for example, if I change the color code for the Red it has no effect on the colors in the `colored-man-pages plugin`.
 
For example, Tilix terminal has these themes as default but user can also customize colors. https://gnunn1.github.io/tilix-web/manual/themes/

I was thinking that if this plugin could use on default color schemes, it would be great.

![image](https://user-images.githubusercontent.com/1277920/71518184-67cb4d80-2890-11ea-81f2-88845b99a004.png)

**Comment by mcornella** [comment]
Does the function above work better?

**Comment by leoheck** [comment]
The output is the same for me, but maybe I am wrong. Do these codes `\e[31m` change the RGB color based on the terminal color scheme?

**Comment by mcornella** [comment]
These codes tell the terminal to print a default red, green and blue. Then the terminal sees this and prints a shade of red, green and blue depending on the color scheme set in the terminal settings. There is no way from the shell to display a particular color (i.e. a color specifying rgb values).
