### ISSUE TITLE
FEEDBACK: Windows Subsystem for Linux

### ISSUE THREAD

**Issue by larson-carter** [ohmyzsh/ohmyzsh#8505]
Can I have a few people give me the latest status on WSL?

EDIT: Can I have some people let me know if it is still slow, laggy, or if it is causing weird bugs. I just want to see if we are going to need to make some patches.

**Comment by gcoakes** [comment]
There's approximately a 3 second delay between the end of a process and when the prompt appears for me when using 'agnoster' theme. This is running the VS Codium terminal.

**Comment by mcornella** [comment]
Do you have perhaps enabled automatic rehash of commands from `$path`? These options would do it:
```
zstyle ':completion:*' rehash true
setopt hashexecutablesonly
```
I disabled them after upgrading to WSL 2 and have been much better off.

**Comment by larson-carter** [comment]
@gcoakes Interesting. I've been doing research trying to determine if it is because Microsoft made the subsystem so High level. Compared to it being native. Very similar to a virtual machine. I'll continue to do some more digging to see if there is anything software wise that we can do to improve the performance out of the box.

**Comment by nickdesaulniers** [comment]
I noticed that the symbol used for the return status isn't rendered correctly.  Looks like a question mark in a box. Like some kind of unicode error, or missing font.  The color is correct based on the return code.  I think it's normally a right arrow?  Default theme, fresh install of oh-my-zsh on WSL1 Debian.

**Comment by AlefCS** [comment]
> I noticed that the symbol used for the return status isn't rendered correctly. Looks like a question mark in a box. Like some kind of unicode error, or missing font. The color is correct based on the return code. I think it's normally a right arrow? Default theme, fresh install of oh-my-zsh on WSL1 Debian.

I was fixing the same problem today and what worked for me was to use WSL through Windows Terminal instead of the default terminal. Now all my themes icons are rendered as expected.

**Comment by saadanerdetbare** [comment]
Windows side:
build: 22000.100 (Windows 11 Insider Preview)
WSL:
RELEASE:  Ubuntu 20.04.2 LTS
KERNEL:   Linux 5.10.43.3-microsoft-standard-WSL2
oh-my-zsh plugin list: git zsh_reload extract sudo colorize command-not-found zsh-autosuggestions copydir copyfile dirhistory history
Danish keyboard
I get nothing, no reaction to Alt + Arrow keystrokes

**Comment by mcornella** [comment]
> This comment should be directed at the Dirhistory plugin

Documented in the README (that's as far as we can do in this case).

----

I'll close this issue since it seems that WSL is quite stable, if anyone has another issue that we can fix in Oh My Zsh please add it here and we'll do our best to solve it.
