### ISSUE TITLE
Django auto-complete plugins not working for custom commands

### ISSUE THREAD

**Issue by mhyousefi** [ohmyzsh/ohmyzsh#8509]
**Describe the bug**
I have added `django` to the plugins list in `~/.zshrc` (`plugins=(git django)`). But my custom commands do not auto-load on pressing `Tab`. I have tried this with my Python `virtualenv` sourced.

**System:**
 - OS: macOS
 - Zsh version 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator [e.g. iTerm2]

**Additional context**
https://docs.djangoproject.com/en/3.0/howto/custom-management-commands/

**Comment by mhyousefi** [comment]
Any one?

**Comment by hegelocampus** [comment]
Have you already tried deleting the `.zcompdump` file as is suggested in the pinned issue  #7642 ?

**Comment by mhyousefi** [comment]
I just did `mv ~/.zcompdump* ~/Desktop` and re-launched my terminal, but still no luck.
Don't get me wrong, the auto-completion works perfectly fine for all built-in Django commands. It's just that the custom commands I add to my Django app, are NOT included in the auto-completion. This was NOT the case with my previous Mac.

ps. I am currently employing [this plugin](https://github.com/zsh-users/zsh-autosuggestions) to get me going.

**Comment by mcornella** [comment]
Plugin removed in 73001e9382db99ebd6effcf0bdcd227985109142. Zsh provides a better `django` completion.
