### ISSUE TITLE
virtualenvwrapper plugin should search default location for virtualenvwrapper.sh on Debian

### ISSUE THREAD

**Issue by randomphrase** [ohmyzsh/ohmyzsh#8513]
**Describe the bug**
The Debian virtualenvwrapper package installs the virtualenvwrapper.sh script into `/usr/share/virtualenvwrapper`. Unfortunately this location is not searched by the virtualenvwrapper plugin.

Adding this location to the path before invoking oh-my-zsh does not fix the problem because these scripts are installed without execute permission, hence are not located by the plugin.

Also, the bash completion lookup does not work either because again the wrong location is searched. On debian at least, bash completions are installed into `/usr/share/bash-completion/completions`.

From looking at the script I was unable to determine another workaround.

**To Reproduce**

1. Install virtualenvwrapper via `sudo apt-get install virtualenvwrapper`
2. Enable virtualenvwrapper plugin
3. Observe error when new shell opened

**Expected behavior**
Plugin should locate virtualenvwrapper.sh file and load it without issuing an error.

**System:**
 - OS: Ubuntu 19.10 (virtualenvwrapper 4.8.4-4)
 - Zsh version 5.7.1
 - Terminal emulator GNOME Terminal

**Comment by randomphrase** [comment]
I think #8521 is still worth merging because it is a more thorough search and more succinctly written. However I can confirm that the issue is fixed for me with #8451 .

**Comment by mcornella** [comment]
I didn't realize #8521 was there, looks a lot cleaner thanks!
