### ISSUE TITLE
Agnoster theme icon issue

### ISSUE THREAD

**Issue by bellizio** [ohmyzsh/ohmyzsh#8520]
**Describe the bug**

There is an issue with the +- (PLUSMINUS) icon when using the agnoster theme. In cases where the +- icon should be shown, a dot (or bullet point) is instead displayed in its place.

**To Reproduce**
1. Enable theme 'agnoster' by setting `ZSH_THEME="agnoster"` in your `~/.zshrc`
2. Download/select/enable an available [powerline font](https://github.com/powerline/fonts/tree/2015-12-04) for your terminal
3. Using your terminal, step into a directory that is tracked via git which has uncommitted changes
4. Observe that a dot instead of the +- icon is displayed to the right of the git branch name

**Expected behavior**
The +- icon should be displayed next the git branch name when there are uncommitted changes.

**Screenshots or recordings**
Screenshot of unexpected behavior:
<img width="619" alt="Screen Shot 2020-01-05 at 10 33 59 AM" src="https://user-images.githubusercontent.com/2282499/71782348-00578100-2fa7-11ea-98f2-32ee5eb9e612.png">

Screenshot of expected behavior:
<img width="619" alt="Screen Shot 2020-01-05 at 10 34 12 AM" src="https://user-images.githubusercontent.com/2282499/71782352-051c3500-2fa7-11ea-9d8b-83d72174b112.png">

**System:**
 - OS: MacOS 10.15.2 (Catalina)
 - Zsh version: 5.7.1
 - Terminal emulator: iTerm2

**Additional context**
There has been ongoing discussion about the issue in the comments of an [open issue in the agnoster-zsh-theme repo](https://github.com/agnoster/agnoster-zsh-theme/issues/103).

The cause of the issue appears to be due to the fact that [ohmyzsh's fork of the theme](https://github.com/ohmyzsh/ohmyzsh/blob/master/themes/agnoster.zsh-theme) has diverged from the [original agnoster theme](https://github.com/agnoster/agnoster-zsh-theme/blob/master/agnoster.zsh-theme). Specifically, the ohmyzsh version does not include the [PLUSMINUS shell variable](https://github.com/agnoster/agnoster-zsh-theme/blob/master/agnoster.zsh-theme#L46), which holds the value for the +- icon.

After some troubleshooting, I was able to verify what the cause was by adding the [agnoster theme](https://github.com/agnoster/agnoster-zsh-theme/blob/master/agnoster.zsh-theme) to the `~/.oh-my-zsh/custom/themes` folder to override the ohmyzsh's version of the theme. Doing so resulted in the +- icon being displayed (see expected behavior screenshot above).

**Comment by ssreekanth** [comment]
Much better fix would be -

Replace this line
```zstyle ':vcs_info:*' unstagedstr '●'```
with
```zstyle ':vcs_info:*' unstagedstr '±'```

**Comment by rushvora** [comment]
How can I go back to the dot? 🙈
