### ISSUE TITLE
The `jump` anchor link in the plugin list is broken

### ISSUE THREAD

**Issue by jakemalachowski** [ohmyzsh/ohmyzsh#8522]
**Describe the bug**
The `jump` link does not link to anything in the list of plugins.

**To Reproduce**
Click the `jump` link on the page: https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins

**Expected behavior**
Link doesn't exist or links to the relevant section

**Comment by mcornella** [comment]
Fixed: https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#jump.
