### ISSUE TITLE
agnoster not working on ssh

### ISSUE THREAD

**Issue by OmegaRogue** [ohmyzsh/ohmyzsh#8524]
I have zsh setup on a bunch of raspberry pis i connect to via ssh, on both my dualboot desktop using windows and my windows laptop with wsl it works fine, but on my dualboot desktop in ubuntu i get the error `(anon):12: character not in range` when starting an ssh connection to one of the raspberry pis, the locales are set correctly, zsh works in the normal ubuntu terminal correctly:
```
 omegarogue@omegarogue-DESKTOP-GUUD6NH  ~  
```
but in ssh it looks like this:
```
Last login: Mon Jan  6 21:18:33 2020 from 192.168.0.49
(anon):12: character not in range
omegapi% 
```

**Comment by mcornella** [comment]
Are you using a UTF-8 locale in your raspberry? I seem to recall it using C or POSIX by default. Run `locale` to check. For available locales run `locale -a`.
