### ISSUE TITLE
problem when editing with cloud theme.

### ISSUE THREAD

**Issue by qinggniq** [ohmyzsh/ohmyzsh#8528]
**Describe the bug**

Hello, when I enter a directory with flash icon when using cloud-theme, if I go to the begin of end and delete, the editing become wired. 

**Screenshots or recordings**
Here is the gif.
![](https://github.com/qinggniq/Note/blob/master/IMAGE/cloud_theme_bug.gif?raw=true)

**System:**
 - OS: macOS Catalina 10.15.2
 - Zsh version  5.7.1
 - Terminal emulator iterm2

**Additional context**
If there is not flash icon at the promote, editing normally.

**Comment by mcornella** [comment]
This might be an issue with the lightning icon not being properly recognized as a single character. Look if you have a UTF-8 locale or not, see [the FAQ](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-change-my-locale).
