### ISSUE TITLE
Weird behaviour with auto_complete plugin

### ISSUE THREAD

**Issue by kalpaj12** [ohmyzsh/ohmyzsh#8529]
**Version**: zsh 5.7.1 (x86_64-ubuntu-linux-gnu)

For some reason, this started to happen after a recent update.
![Screenshot_20200110_214628](https://user-images.githubusercontent.com/41864755/72168260-c812d100-33f2-11ea-9bd6-c3a3448df413.png)

**Comment by mcornella** [comment]
See https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command. Similar issues: #6985, #3932, #4529, #4632.
