### ISSUE TITLE
Move .oh-my-zsh out from $HOME directory

### ISSUE THREAD

**Issue by unInstance** [ohmyzsh/ohmyzsh#8531]
How to move ~/.oh-my-zsh out to a different directory

**Comment by hegelocampus** [comment]
I'm not sure exactly what you mean, but its likely you just need to move the `.oh-my-zsh` directory and then make sure that your `.zshrc` has the `ZSH` variable pointing to where you moved the `.oh-my-zsh` directory.
For example my `oh-my-zsh` directory is located at the following path `~/.dotfiles/zsh/oh-my-zsh`, and my `.zshrc` then has the following line added to set-up `oh-my-zsh`:
```zsh
export ZSH="$HOME/.dotfiles/zsh/oh-my-zsh"
```
