### ISSUE TITLE
Update Pull Request Template

### ISSUE THREAD

**Issue by Kazaf123** [ohmyzsh/ohmyzsh#8535]
**Is your feature request related to a particular plugin or theme? If so, specify it.**

Pull Request
**Is your feature request related to a problem? Please describe.**

I'm always read the pull request, and find that it is hard to read when the pull request has no format.
**Describe the solution you'd like**

I suggest that it can update a pull request template to improve this problem.
**Describe alternatives you've considered**

**Additional context**

**Comment by mihaimaruseac** [comment]
Seems to be spam
![VCA6DzWKgeZ](https://user-images.githubusercontent.com/323199/72463619-84202300-3788-11ea-9d4b-08ac8683f524.png)
