### ISSUE TITLE
Why my Oh My Zsh startup is slow. It take mostly 4-5s

### ISSUE THREAD

**Issue by cellardoorver** [ohmyzsh/ohmyzsh#8536]

**Comment by ikesau** [comment]
Yeah, something weird's going on. I updated to 4e45e12d and things appear broken.

**Comment by mcornella** [comment]
Can you post your zshrc files? Can you consistenly reproduce the issue by doing a checkout of the previous commit (should be fast) and the last commit (should be slow)?

**Comment by ikesau** [comment]
```
export ZSH="/Users/ike/.oh-my-zsh"

ZSH_THEME="typewritten"

ENABLE_CORRECTION="true"

plugins=(git)

source $ZSH/oh-my-zsh.sh

eval "$(pyenv init -)"
```

I can reproduce by repeatedly running `source ~/.zshrc`

Eventually the shell outputs `pyenv:11: argument list too long: pyenv` and becomes non-responsive. This may be a separate issue than the one OP was talking about, though. 🤷‍♂

**Comment by mcornella** [comment]
> I can reproduce by repeatedly running `source ~/.zshrc`. It appears to take longer to succeed each time, until eventually the shell outputs `pyenv:11: argument list too long: pyenv` and becomes non-responsive.

You're running `pyenv init` again and again, that is why you eventually get an error. The proper way to restart the shell is `exec zsh`, or restarting the terminal, not using `source ~/.zshrc`.

**Comment by ikesau** [comment]
Ah, okay good to know.

However, I've removed the pyenv line, and have tried repeatedly running `exec zsh`. I get the same behaviour (after the fourth attempt it hangs)

**Comment by mcornella** [comment]
Look if `pyenv` is creating a new process instead of using an already running one. I'm not familiar with it but that could be a probable cause.

**Comment by hgedia** [comment]
Noticing the same issue, is there a way to downgrade to earlier commits to validate ?

**Comment by mcornella** [comment]
You can `git checkout` older commits to test. You can speed up the process of testing the performance with the command `time zsh -ic exit &>/dev/null`.

**Comment by kareemkasem** [comment]
same here and I'm not  running pyenv
`
export ZSH="/home/kareem/.oh-my-zsh"

ZSH_THEME="dracula/dracula"

plugins=(git sudo autojump zsh-syntax-highlighting zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

function fgit(){
git add .
git commit -m "$1"
git push
}

function kill-port(){
lsof -i :"$1" -t | xargs kill
}

function papirus-color(){	
	echo "what color do you want ?"
	read color	
	papirus-folders -C "$color" --theme Papirus
	papirus-folders -C "$color" --theme Papirus-Dark	
	papirus-folders -C "$color" --theme Papirus-Light
}

alias open="xdg-open"
alias code="code-oss"
alias sudo="sudo "
alias sol="eopkg"
alias re="gnome-terminal || tilix; exit"
alias x="exit"
alias c="clear"
alias figma="figma-linux"
alias cra="create-react-app"
alias post="sudo -u postgres psql"
alias monet="sudo iftop -i wlp2s0"
`

**Comment by mcornella** [comment]
Remove plugins one by one and measure the effect that has on zsh startup time with the command above (`time zsh -ic exit &>/dev/null`), until you find the one that has the biggest impact. You can also run `zsh -xv` and see if the zsh process hangs on a particular command, or on the contrary, it just runs through the whole thing.

**Comment by risingtiger** [comment]
> ~Noticing the same issue, is there a way to downgrade to earlier commits to validate ?~
> 
> nvm , it was nvm.

mcornella, How do you know it was nvm? Seems might be my problem as well, since my terminal has been slow to start since installing nvm. Any ideas of how to to address it?

**Comment by hgedia** [comment]
@risingtiger  , this really was self inflicted. I was calling 
`source /usr/share/nvm/init-nvm.sh`

Inside the zshrc , which was slowing it down. Your issue might be different

**Comment by iNoSec2** [comment]
git plugins slow mine, since i removed it, it start so much faster

**Comment by andresdotsh** [comment]
This worked for me.
With `macOS Big Sur 11.3`, `Xcode 12.5`, `Command Line Tools`, and `iTerm2` fresh installation.

### 1. Uninstall oh-my-zsh
Instructions [here](https://github.com/ohmyzsh/ohmyzsh#uninstalling-oh-my-zsh).

### 2. Install homebrew
Instructions [here](https://brew.sh/).

### 3. Install git (but with homebrew)
`brew install git`

### 4. Install oh-my-zsh again
Instructions [here](https://github.com/ohmyzsh/ohmyzsh#basic-installation).

### That's all!

In my case, the thing was that when I installed the Command Line Tools, a git version was installed.
And apparently there is an issue between that git version and oh-my-zsh.
That was causing a slow startup with the `xcodebuild` title in the iTerm2 window.

**Comment by liushuaikobe** [comment]
> This worked for me.
> With `macOS Big Sur 11.3`, `Xcode 12.5`, `Command Line Tools`, and `iTerm2` fresh installation.
> 
> ### 1. Uninstall oh-my-zsh
> Instructions [here](https://github.com/ohmyzsh/ohmyzsh#uninstalling-oh-my-zsh).
> 
> ### 2. Install homebrew
> Instructions [here](https://brew.sh/).
> 
> ### 3. Install git (but with homebrew)
> `brew install git`
> 
> ### 4. Install oh-my-zsh again
> Instructions [here](https://github.com/ohmyzsh/ohmyzsh#basic-installation).
> 
> ### That's all!
> In my case, the thing was that when I installed the Command Line Tools, a git version was installed.
> And apparently there is an issue between that git version and oh-my-zsh.
> That was causing a slow startup with the `xcodebuild` title in the iTerm2 window.

May I know how to prove it's the cause?
