### ISSUE TITLE
kubectl plugin error

### ISSUE THREAD

**Issue by Cjwpython** [ohmyzsh/ohmyzsh#8540]
### When I use the kubectl plugin alone, the command line is correct, but after I use autosuggestion, I get this kind of error. I ca n’t delete it
- os type :mac 10.13
![image](https://user-images.githubusercontent.com/59188420/72435753-d0e01a00-37d9-11ea-9355-69dac18090b5.png)

**Comment by mcornella** [comment]
Can you post your zshrc file?
