### ISSUE TITLE
Oh my zsh update broke sshfs folder

### ISSUE THREAD

**Issue by NofelYaseen** [ohmyzsh/ohmyzsh#8541]
I am using macOS Catalina.

Everything worked fine until the latest update.
zsh version: zsh 5.7.1 (x86_64-apple-darwin19.0.0)

Everything looks okay for normal folder. However, for remote file systems, it is stuck, until I press Ctrl +C and then type`cd ..`

I am attaching the screenshot below:

<img width="1440" alt="Screen Shot 2020-01-15 at 10 40 01 AM" src="https://user-images.githubusercontent.com/14984329/72447577-977cbf80-3783-11ea-81d4-c2855f0a88fd.png">

**Comment by mcornella** [comment]
Can you post your zshrc file?

**Comment by NofelYaseen** [comment]
```
export ZSH="/Users/nofelyaseen/.oh-my-zsh"
ZSH_THEME="af-magic"

plugins=(git)

source $ZSH/oh-my-zsh.sh
```

All other lines are commented out.
I only changed the theme from default.

**Comment by ronnieissa** [comment]
Not sure if you have the same issue, but I had this as well.
I troubleshot the issue by setting LogLevel DEBUG3 in the sshd_config file and monitoring the /var/log/auth.log file

In my situation, Im running debian 10, kernel 4.19.0-6

The error I was getting was that the /root/ssh/authorized_keys file could not be found, but as we all know that is NOT the correct path. It should be /root/.ssh/authorized_keys

Im not sure how or why this changed, but to confirm the validity, I ran mv .ssh ssh and everything started working again. Im thinking of setting up tripwire on a clean image and installing ohmyzsh again to see how this got changed.

**Comment by NofelYaseen** [comment]
It does not resolve the underlying issue with ohmyzsh.
I don't want to rename .ssh as it could disrupt other things.
There has to be an alternative.

**Comment by mcornella** [comment]
Does `setopt promptsubst` solve it?

**Comment by jcatala** [comment]
Suffering the same issue, `zsh hangs` on `cd ing` into `sshfs mounted dir` :+1: 
`bash/sh` works fine on navigation .

![image](https://user-images.githubusercontent.com/23392306/81348077-65bd9a80-908b-11ea-9d97-e7359e49baa8.png)

cheers, :smile: !

**Comment by marcoiai** [comment]
I think I have found the origin of the problem, so I'm posting here. For some reason, when you do a git command on a sshfs directory, it takes forever, so is more of a GIT -> sshfs problem than zsh or ohmyszh. Since ohmyszh automatically git status and some other commands for git directories, if you have this setup like mine, this is the problem, there's any config to ohmyszh avoid read GIT info on certain directories?

**Comment by NofelYaseen** [comment]
There is a way to do, but we will have to run it in each subdirectory:

`git config oh-my-zsh.hide-status 1`

Ideally, I want to do it for all subdirectories.

**Comment by mcornella** [comment]
So this is just `git` breaking in sshfs directories, if I understand correctly? If that is the case, this should be fixed by async-ing the git calls in git prompts (work in progress).

**Comment by marcoiai** [comment]
Yes that is exactly what it happens. For now I'm just. not using it because
i have to use a SSHFS drive all day, just thought to give you a warning,
thanks for the response.

atenciosamente,
Marco Aurélio Simão

**Comment by adrienauriol** [comment]
> So this is just `git` breaking in sshfs directories, if I understand correctly? If that is the case, this should be fixed by async-ing the git calls in git prompts (work in progress).

Hi, 
I'm having the same issue. Did you manage to fix the problem ? :)
Cheers, 
Adrien

**Comment by jcwatson11** [comment]
I am also experiencing the same issue. Thank you for your work. Please fix. :)

**Comment by marcoiai** [comment]
I think it is.

**Comment by mcornella** [comment]
This should be fixed by the async git prompt. Closing
