### ISSUE TITLE
Agnoster Theme with AWS Prompt How To Remove Trailing Prompt

### ISSUE THREAD

**Issue by richardwlu** [ohmyzsh/ohmyzsh#8543]
![image](https://user-images.githubusercontent.com/8405384/72468013-d457af00-37a1-11ea-8b32-334df7596cf5.png)

Is there a way to remove the trailing AWS prompt? I'm not sure if that is supposed to be there at all.

**Comment by apjanke** [comment]
Doesn't look like this is customizable in the theme as is.

Shameless plug: Come try [my AgnosterJ fork](https://github.com/apjanke/agnosterj-zsh-theme/commits/master) of the theme, which adds the ability to customize your prompt segments, e.g. removing the AWS segment.

**Comment by richardlu-vf** [comment]
Per the documentation, I just needed to set `SHOW_AWS_PROMPT=false` in `~/.zshrc`.

**Comment by richardwlu** [comment]
Per the documentation, I just needed to set `SHOW_AWS_PROMPT=false` in `~/.zshrc`.

**Comment by russomi** [comment]
FYI ... `SHOW_AWS_PROMPT=true` in `~/.zshrc` has resolved this issue for me.  🤷

**Comment by mcornella** [comment]
@russomi it should be `false`, `SHOW_AWS_PROMPT=false`.
