### ISSUE TITLE
MobaXterm cannot start Windows Subsystem for Linux (WSL) with zsh

### ISSUE THREAD

**Issue by fengyuentau** [ohmyzsh/ohmyzsh#8544]
Sorry for this not related issue which I had during using oh-my-zsh.

Here is my environment:
1. OS: Windows 10 Enterprise, 1809
2. WSL: Ubuntu 18.04 LTS
3. MobaXterm: Personal Edition v12.4 Build 4248

Problem:
`zsh` and `oh-my-zsh` are installed successfully without errors. Default shell has been changed to `zsh` by `chsh -s $(which zsh)` (also tried `chsh -s /bin/zsh` which did not work also). When I start WSL from MobaXterm, it starts with `sh` instead of  `zsh`. But I can manually change to `zsh` by execute `zsh` command where `oh-my-zsh` is working really well. How do I know I am not using `zsh`? I have changed the theme to `agnoster` which is very obvious to tell. Also I have double checked that the default shell is set to `zsh` by `echo $SHELL`.

Has anybody come to similar problems?

**Comment by fengyuentau** [comment]
Correct: The shell started by WSL using MobaXterm is bash instead of zsh. It seems the command to change default shell does not work for booting WSL from MobaXterm.

Temporary solutuion: Adding a command `zsh` in `.bashrc` can start WSL in MobaXterm by default. But it will stop commands like `scp` working.

**Comment by kanghuanyao** [comment]
![image](https://user-images.githubusercontent.com/5291302/117468559-64b59680-af87-11eb-85cf-ae74a527020b.png)

Hi, I found that use the "Run method", sepcify "Localhost connection" in MobaXterm 21.1 could resolve this question.

**Comment by cyicz123** [comment]
You can add the following commands in `.bashrc`
~~~bash
zsh
~~~

**Comment by LeonardAB** [comment]
add `zsh` command at startup (not sure if this has the same side effect as adding `zsh` in `.bashrc `

![image](https://user-images.githubusercontent.com/14308605/235477011-673bedbe-6f39-41c5-bda0-b22d601e7fb8.png)
