### ISSUE TITLE
Command not found yarn when using yvm

### ISSUE THREAD

**Issue by tgreen7** [ohmyzsh/ohmyzsh#8545]
**Describe the bug**
When I try to source my config I get the following error:
```
source ~/.zshrc                         
is_plugin:3: command not found: yarn
is_plugin:4: command not found: yarn
is_plugin:3: command not found: yarn
is_plugin:4: command not found: yarn
[oh-my-zsh] plugin 'z' not found
```

**To Reproduce**

1. Enable plugin 'z'
2. Download yvm with brew
3. add yvm export to zshrc
```
export YVM_DIR=/usr/local/Cellar/yvm/3.6.1
[ -r $YVM_DIR/yvm.sh ] && . $YVM_DIR/yvm.sh
```
3. See error
-->

**Expected behavior**

I should be able to source my zshrc with no errors and the z plugin should work as expected.

**System:**
 - OS: macOS 10.14.6
 - Zsh version: zsh 5.7.1 (x86_64-apple-darwin18.2.0)
 - Terminal emulator"  iTerm2

**Comment by mcornella** [comment]
Can you post your zshrc file and the output of `cd $ZSH; git rev-parse HEAD; git status`?

**Comment by mcornella** [comment]
I suspect this is due to overriding the `test` builtin with something else. What do you get when running `which -a test`?

**Comment by tgreen7** [comment]
@mcornella Yes i think it is the test alias. Thank you!

**Comment by mcornella** [comment]
It's important to note that other programs might use `test`, it is a common command, so having an alias of the same name might break other stuff.
