### ISSUE TITLE
Imajes theme problem

### ISSUE THREAD

**Issue by exorcist365** [ohmyzsh/ohmyzsh#8553]
The imajes theme shows \[\e[1;37m\]joan:\w \[\]$ \[\e[0m\]

**Comment by silas84** [comment]
JoanM1lev <notifications@github.com> schrieb am So., 19. Jan. 2020, 18:14:

**Comment by mcornella** [comment]
I can't reproduce this. Are you sure you're using zsh? Run `echo $ZSH_VERSION` and post what you get. Also, post your zshrc file.
