### ISSUE TITLE
rvm plugin fails when autocompleting gemsets

### ISSUE THREAD

**Issue by binford2k** [ohmyzsh/ohmyzsh#8559]
When tab completing a ruby with a gemset, it fails with an argument error. See a demonstration of the error below. The 2.6.3 Ruby is installed and it has a gemset called `showoff`. Rvm can address this gemset as `2.6.3@showoff` and the autocomplete should show that. `rvm gemset list_all` can retrieve the gemsets for all rubies. I'm sure there's probably a better way.

```
[~/Projects]$ rvm use 2.6.3@shoUnrecognized command line argument: 2.6.3
_values:compvalues:11: not enough arguments
Unrecognized command line argument: 2.6.3
_values:compvalues:11: not enough arguments
Unrecognized command line argument: 2.6.3
_values:compvalues:11: not enough arguments

[~/Projects]$ rvm use 2.6.3@showoff
Using /Users/ben/.rvm/gems/ruby-2.6.3 with gemset showoff
[~/Projects]$
```

**System:**
 - OS: macOS Catalina
 - Zsh version: 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator: iTerm2
 - rvm version: 1.29.9-next

**Comment by mcornella** [comment]
Are you using the rvm plugin?

**Comment by binford2k** [comment]
Yes, `plugins=(git rvm kubectl)`

**Comment by mcornella** [comment]
The `rvm` plugin sources the upstream rvm completion file (though it does it in a weird way). What do you get with `echo $_comps[rvm]`?

**Comment by mcornella** [comment]
Looks like the rvm completion doesn't work for latest releases: https://github.com/rvm/rvm/issues/3925. I'll mark this as closed, subscribe to that issue instead.
