### ISSUE TITLE
nvm plugin completion isn't exhaustive

### ISSUE THREAD

**Issue by chris-orchard** [ohmyzsh/ohmyzsh#8560]
I have enabled the nvm plugin: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/nvm but auto completion doesn't appear to work.

If I type `nvm use ` and press <kbd>Tab</kbd> I get a list of the current directory contents.

**Expected behavior**
Completion options for the command are listed.

**System:**
 - OS: Ubuntu 18.04.3
 - Zsh version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu) 
 - nvm version: 0.35.2

**Additional context**
I have already tried removing my completion cache as suggested here: https://github.com/ohmyzsh/ohmyzsh/issues/7741#issuecomment-481433618
and here: https://github.com/ohmyzsh/ohmyzsh/wiki/Troubleshooting#completion-problems

I then tried the following step _2. If you still have problems, try fully resetting the completion system,_ but that gave me the following error:
```
 ✘  ~  compaudit | xargs chmod g-w,o-w
chmod: missing operand after ‘g-w,o-w’
```

**Comment by mcornella** [comment]
That's as far as the completion from the nvm plugin goes, it just completes up to the first argument.

**Comment by mcornella** [comment]
Try updating (`omz update`). The plugin now uses the nvm bash completion if it finds it.
