### ISSUE TITLE
Using prezto theme with Oh My Zsh

### ISSUE THREAD

**Issue by privacyguy123** [ohmyzsh/ohmyzsh#8567]
Specifically the Paradox theme - how do I port this over?

**Comment by mcornella** [comment]
This is more of a prezto issue, but here's what I've found: [prezto runs this code](https://github.com/sorin-ionescu/prezto/blob/66b9ea7d44740be0d8185b4623398f27fed8104d/modules/prompt/init.zsh#L8-L17) to load a theme (which they call prompt). Specifically, the important bits are:

```zsh
autoload -Uz promptinit && promptinit
prompt "theme-name"
```

The theme (prompt) file has to be in a directory in `$fpath` with the name pattern `prompt_<theme-name>_setup`, then the above code has to run.

The easiest (but hackish) way to accomplish this in OMZ is to make a plugin folder inside `$ZSH_CUSTOM` that has the above code in `<theme-name>.plugin.zsh` and the `prompt_<theme-name>_setup` inside the plugin folder, then adding `<theme-name>` to the plugins array in the zshrc folder.
