### ISSUE TITLE
Modifying a command and adding pipe character clears the rest of the line

### ISSUE THREAD

**Issue by mmahmoudian** [ohmyzsh/ohmyzsh#8572]
**Describe the bug**

During modifying an existing command, when I add pipe character (`|`) the characters following the pipe disappear!

**To Reproduce**

1. type something similar to the following:
`$( jabija ) ujaboiuabf oauboa v oabova`
2. move your cursor to the end of the word inside paranthesis
3. type one space, then a pipe, then space
4. everything after the parenthesis is gone!

You can use this more meaningful command if you wish (put the space pipe space after the "date"):
```
echo $(date) | cat
```

**Expected behavior**
Modifying the command should not remove the rest of the command

**Screenshots or recordings**
![Peek 2020-01-28 14-40](https://user-images.githubusercontent.com/390889/73264774-379f0380-41dc-11ea-8ff8-d4e7772a9f7b.gif)

**System:**
 - OS: CentOS Linux release 7.7.1908 (Core)
 - Zsh version: 5.0.2
 - Terminal emulator: Konsole Version 19.12.1

I have a very basic ohmyzsh setup on my machine where only the following lines are not commented in the `.zshrc` file:

```
export ZSH=/home/user/.oh-my-zsh
plugins=(git tmux)
source $ZSH/oh-my-zsh.sh
```

**Comment by mcornella** [comment]
Have you tried using a different terminal or not running tmux?

**Comment by mmahmoudian** [comment]
@mcornella Yes, I get the same behavior on Tmux. I should also say that the machine I'm running zsh on is a remote machine that I'm connected to via ssh. So to test your hypothesis I did both of the following:
1. open Konsole (KDE terminal) > ssh to remote > try the [steps I explained](https://github.com/ohmyzsh/ohmyzsh/issues/8572#issue-556184916) > defected behavior

2. open Konsole (KDE terminal) > ssh to remote > **open a tmux session** > try the [steps I explained](https://github.com/ohmyzsh/ohmyzsh/issues/8572#issue-556184916) > defected behavior

3. open Konsole (KDE terminal) > **open a tmux session** > ssh to remote > try the [steps I explained](https://github.com/ohmyzsh/ohmyzsh/issues/8572#issue-556184916) > defected behavior

The "defected behavior" seems consistent regardless of terminal.

**Comment by mcornella** [comment]
I can reproduce this with your CentOS version and zsh 5.0.2 (the default one) but can't on the same zsh version on another system, **even without OMZ**. I also checked that Konsole is not at fault here, the same happens in a tty.
I suggest you upgrade the zsh version and file a bug in CentOS.
