### ISSUE TITLE
Pass plugin doesn't work on MacOS Catalina

### ISSUE THREAD

**Issue by webcoderkz** [ohmyzsh/ohmyzsh#8573]
**Describe the bug**
pass plugin: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/pass
Doesn't provide autocompletion for the pass commands, like `pass in` should autocomplete by tab to `pass insert` and so on.

**To Reproduce**
1. Enable plugin in ~/.zshrc:
```
plugins=(git pass)
```

2. Run `pass in` or `pass l` no autocompletion.

**Expected behavior**
Should autocomplete every commands, stores, etc.

**System:**
 - OS: MacOS Catalina
 - zsh 5.7.1 (x86_64-apple-darwin19.0)
 - iTerm2

**Comment by mcornella** [comment]
Have you tried deleting the zcompdump cache file (`rm $ZSH_COMPDUMP`, then restarting the terminal) as https://github.com/ohmyzsh/ohmyzsh/issues/7642 says?

**Comment by webcoderkz** [comment]
God, this works! Thanks, is there any chance to have this info on a README of pass plugin or any plugin at all?

**Comment by mcornella** [comment]
It's [in the FAQ](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-have-enabled-a-completion-plugin-but-the-completion-doesnt-work).
