### ISSUE TITLE
Clear screen command(cmd+K) not displaying directory/repository details.

### ISSUE THREAD

**Issue by sathishbabu96** [ohmyzsh/ohmyzsh#8575]
**Describe the bug**
Clear screen command `cmd+K` not displaying current directory details in `avit` theme.

**To Reproduce**
1. Enable `avit` theme.
2. `cd` into a directory.
3. Clear screen using `cmd+K`

**Expected behavior**
The directory details must be displayed above the terminal cursor.
<img width="2560" alt="Screenshot 2020-01-29 at 10 34 51 AM" src="https://user-images.githubusercontent.com/22419483/73329289-1d6c3080-4283-11ea-983a-0b0d2550d251.png">

**Screenshots or recordings**
Before clearing screen
<img width="2560" alt="Screenshot 2020-01-29 at 10 34 51 AM" src="https://user-images.githubusercontent.com/22419483/73329289-1d6c3080-4283-11ea-983a-0b0d2550d251.png">
After clearing screen
<img width="2560" alt="Screenshot 2020-01-29 at 10 34 56 AM" src="https://user-images.githubusercontent.com/22419483/73329297-25c46b80-4283-11ea-8635-48a18e733d92.png">

**System:**
 - OS - macOS
 - Zsh - zsh 5.6.2 (x86_64-apple-darwin18.2.0)
 - Terminal

**Comment by mcornella** [comment]
Looks like only the last line of the prompt is shown. Does this happen with `CTRL`+`L`?

**Comment by sathishbabu96** [comment]
Yes it happens with `cmd` + `K` as well.

**Comment by mcornella** [comment]
Have you tried on another terminal emulator?

**Comment by sathishbabu96** [comment]
No, I have not.

**Comment by mcornella** [comment]
Well, go ahead and try another one, don't be shy.

**Comment by sathishbabu96** [comment]
I tried in iterm2. The problem persists there as well

**Comment by mcornella** [comment]
I'm able to reproduce this but I don't know a solution. `CONTROL`+`L` works though (not `CMD`+`L`).

**Comment by sathishbabu96** [comment]
Since `CONTROL` + `L` does what I need, I will go with it. I am closing this issue now.
