### ISSUE TITLE
Identified "~" directory as git repo

### ISSUE THREAD

**Issue by Yufeng-L** [ohmyzsh/ohmyzsh#8577]
hello, when I installed ohmyzsh, it identified "~" directory as git repos.
Can anyone tell me how to fix it? Thanks!
![image](https://user-images.githubusercontent.com/55221020/73370266-f3663e80-4281-11ea-9257-f23ec9510cf4.png)

**Comment by mcornella** [comment]
That's your home directory, and you probably have a `.git` folder in it from some other time you might have run `git init` when inside the home folder. If you don't have anything of value in there (run `git status` and `git log` to check), you can safely `rm` the `.git` folder.
