### ISSUE TITLE
tab completion for music (osx plugin)

### ISSUE THREAD

**Issue by nullmem** [ohmyzsh/ohmyzsh#8578]
**Is your feature request related to a particular plugin or theme? If so, specify it.**

osx

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

music tab completion would be very useful.

**Comment by bartekpacia** [comment]
Hi @nullmem , please fill all the required sections of the template and provide a more exhaustive description of your proposal.
