### ISSUE TITLE
username@hostname Same background and foreground color

### ISSUE THREAD

**Issue by nmweizi** [ohmyzsh/ohmyzsh#8579]
After copying and pasting, can't see username@hostname.
![图片](https://user-images.githubusercontent.com/1232444/73417176-2a0b8a00-4352-11ea-83c4-80ccdf4a3965.png)

- debian_version lsb_release -a
```
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
```
- oh my zsh
```
origin/master
```
- zsh  version
```
5.7.1 (x86_64-debian-linux-gnu)
```
- .zshrc
```
ZSH_THEME="agnoster"
```
- echo $prompt     
``` 
%{%f%b%k%}$(build_prompt) 

```

https://github.com/agnoster/agnoster-zsh-theme/issues/131#issue-556928752

**Comment by mcornella** [comment]
Does that happen every time a command errors? i.e. run `false` to trigger a command error, `true` for a command success.

**Comment by nmweizi** [comment]
wherever

**Comment by mcornella** [comment]
You're not giving me much to work with. Have you made any modifications to the theme? Are there more changes in your zshrc file? Copying and pasting what?

**Comment by nmweizi** [comment]
There are no other changes. Other topics work.

**Comment by mcornella** [comment]
I know this is old, but if this still happens reopen the issue and run `functions -t prompt_context`, and post the trace both when you can see it and when you can't.
