### ISSUE TITLE
Kubectl autocomplete doesn't work

### ISSUE THREAD

**Issue by tomjohnburton** [ohmyzsh/ohmyzsh#8583]
**Describe the bug**

I have added the kubectl autocomplete plugin. About 3 days ago I could use it as expected. I could write `kubectl get <tab>` and all of the possible resources I could get would show up. Then we switched clusters to EKS with k8s v1.14 and now for some reason when I press tab all it does is give me a list of the files that currently exist in my `pwd`.
![image](https://user-images.githubusercontent.com/39559415/73467026-ff85f500-4382-11ea-8c9b-74ec51c41929.png)

I have got it down to a potential problem with the EKS cluster/k8s version I am using. I know that when I run the commands on a KOPS cluster using k8s v1.12 it works fine:
![image](https://user-images.githubusercontent.com/39559415/73466986-f3019c80-4382-11ea-84a0-0fc82eadb703.png)

**To Reproduce**
Try running autocomplete on a cluster with k8s version 1.14

**System:**
 - OS: [e.g. macOS] macOS 10.15.2
 - Zsh version [e.g. 5.6] 5.7.1
 - Terminal emulator [e.g. iTerm2] ITerm2
 - Kubectl version 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platfo
rm:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler
:"gc", Platform:"linux/amd64"}
``` 

**Additional context**

**Comment by mcornella** [comment]
Have you tried to [reset the completion cache](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-reset-the-completion-cache) and restarting the terminal?

**Comment by tomjohnburton** [comment]
Wow, just quitting ITerm2 and starting it again fixed it. I feel stupid. Thanks @mcornella
