### ISSUE TITLE
Show current git tag in prompts (if there is one on the currently checked out commit)

### ISSUE THREAD

**Issue by fridtjof** [ohmyzsh/ohmyzsh#8587]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
Not really, but it seems that acquiring VCS information is implemented in themes, not centrally :/ I'm using agnoster.

**Describe the solution you'd like**
I'd love if there was a config flag to display a tag instead of a commit hash, if the current commit is exactly on a tag.

**What I tried so far**
I searched a bit for how I would get the current tag conveniently, but there does not seem to be a "stable" git command that only outputs the current tag's name. So there would be some string parsing involved.

**Additional context**
My use case for this is for quickly seeing which version of projects I'm only building/using (not developing) I checked out. I like using tags if they're available to stay on marked releases instead of whatever HEAD is.

**Comment by dan1994** [comment]
I also ran across this issue. You can use `tag=$(git describe --tags --exact-match 2> /dev/null)`. The return value will indicate there is a tag pointing to the current commit, and the content of `tag` will be the tag name if it exists.

Apparently the `zsh` `vcs_info` can also extract the tag as is being done in the official `agnoster` repo, and if you have a branch and a tag pointing to the same commit, it will choose smartly based on how you checked out the commit. I see it is used in `ohmyzsh`'s version of `agnoster` as well, but for some reason it doesn't work the same.

Anyways, I intend to submit a patch for `ohmyzsh`'s `agnoster` specifically.

**Comment by dan1994** [comment]
I found this [PR](https://github.com/ohmyzsh/ohmyzsh/pull/8417) that patches this for `agnoster`.
