### ISSUE TITLE
extended_glob cannot be disabled in zshrc

### ISSUE THREAD

**Issue by januszm** [ohmyzsh/ohmyzsh#8588]
**Describe the bug**
It should be possible to permanently disable `extendedglob` opt, it interrupts work with programs such as `git` (e.g. `git show HEAD^`) or even grep , e.g. `ps -ef | grep [r]uby` (shows `zsh: no matches found: [r]uby`)

**To Reproduce**
add `unsetopt extended_glob` to `~/.zshrc` , run `ps -ef | grep [b]ash` or `git show HEAD^` in any GIt repository

**Expected behavior**
It should be possible to disable `extended_glob` with a simple `unsetopt` setting in `~/.zshrc` or via ENV var.

**System:**
 - OS: macOS 10.15
 - Zsh version 5.7.1
 - Terminal emulator  iTerm2

**Additional context**
There's a bunch of files in `~/.oh-my-zsh` in `lib`, `plugins` and `themes` directories which do `setopt extended_glob` or `setopt extendedglob`

**Comment by mcornella** [comment]
Have you tried putting it *after* OMZ is sourced?

**Comment by januszm** [comment]
It is the very last line in my `~/.zshrc`

**Comment by mcornella** [comment]
Does it appear in the output of `setopt`?

> run `ps -ef | grep [b]ash`

Note that `extended_glob` only affects `#`, `~` and `^`. `[]` are still treated like wildcard characters unless you disable `glob`.

**Comment by AlexWillisson** [comment]
This is an issue for me, if I `unsetopt extended_glob` manually, it works. If I put it as the last line in my `.zshrc`, it doesn't. I opened a new terminal in MacOS and copy/pasted everything from it here to show what I mean. I regularly use `^` for looking at git commits referenced relatively, I'm aware that `~` works too but I prefer `^`

```Last login: Wed Jun  1 11:50:21 on ttys008
awillisson@awillisson ~ » tail -5 .zshrc
export PATH=$PATH:$HOME/bin

unsetopt share_history
unsetopt EXTENDED_GLOB
awillisson@awillisson ~ » echo ^
#.ata-conf.yaml# AWSCLIV2.pkg Applications Desktop Documents Downloads Library Movies Music Pictures Public a ata-kt ata-kt-HourlyCampginCostDownloadJob.log bin cargurus cg-ruby-sem company-party-2022 diversity-report-2022.pdf intersected-grammys-albums.csv mysql-workbench-queries tmp work-options.json work_options x~
awillisson@awillisson ~ » unsetopt EXTENDED_GLOB
awillisson@awillisson ~ » echo ^
^
awillisson@awillisson ~ » 
```

I copy pasted `unsetopt EXTENDED_GLOB` to be 100% sure I didn't typo it in my `.zshrc`
