### ISSUE TITLE
kubectl plugin add daemonset aliases

### ISSUE THREAD

**Issue by Zaitsev** [ohmyzsh/ohmyzsh#8589]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
kubectl

**Describe the solution you'd like**
daemonsets are quite popular, so it would be nice to have them aliased

**Describe alternatives you've considered**
alias kg - kubectl get

**Comment by robbyrussell** [comment]
I think this has already been done. There are some kg(*) aliases?
