### ISSUE TITLE
command-not-found silent if package not found

### ISSUE THREAD

**Issue by oriolarcas** [ohmyzsh/ohmyzsh#8596]
In Ubuntu 19.10, the `command-not-found` plugin will print nothing if no package suggestion is found:

```
$> foobar
$>
```

This behavior can be traced back to the `command-not-found` package, in particular the `--no-failure-msg` flag in its `/etc/zsh_command_not_found` file:

```
$> /usr/lib/command-not-found -- foobar
foobar: command not found
$> /usr/lib/command-not-found --no-failure-msg -- foobar
$>
```

The logic thing is to remove the flag. However, I am not sure if this is the expected behavior and it should be `zsh` who prints the message if `command-not-found` fails.

cc @robbyrussell

**Comment by mcornella** [comment]
That's not a bug in OMZ, but a bug in the command-not-found package. These are the ones to track:
https://bugs.launchpad.net/ubuntu/+source/command-not-found/+bug/1766068
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927876

**Comment by oriolarcas** [comment]
Thanks for the comprehensive reply.
