### ISSUE TITLE
Create shortcuts for Git LFS commands

### ISSUE THREAD

**Issue by billyromano** [ohmyzsh/ohmyzsh#8598]
Git LFS is helpful for reducing the file size of your repository when including assets like videos, and high resolution files by storing them in another cloud solution. Let's include some shortcuts for the commands we have to repeat on a normal basis for creating new repositories and migrating existing repositories to use LFS.

**Is your feature request related to a particular plugin or theme? If so, specify it.**
git-lfs | brew install git-lfs
https://www.atlassian.com/git/tutorials/git-lfs
https://github.com/git-lfs/git-lfs/wiki/Tutorial

**Is your feature request related to a problem? Please describe.**
Typing commands manually instead of using pre-defined shortcuts.

**Describe the solution you'd like**
Proposed Shortcuts:
glfsi | git lfs install
glfst | git lfs track
glfsls | git lfs ls-files
grmca | git rm --cached
glfsmi | git lfs migrate import --include=
grfe | git reflog expire --expire-unreachable=now --all
ggc | git gc --prune=now
gplfs | git lfs push origin $(current_branch) --all

**Describe alternatives you've considered**
None.

**Comment by vietduc01100001** [comment]
I would like to take this one. Is this just simply aliases?

**Comment by billyromano** [comment]
Yep! Just aliases : )

**Comment by vietduc01100001** [comment]
@billyromano I have some questions to ask before creating a PR:

1. Some of your aliases proposed above don't belong to the git lfs command, but git itself. So should I put them in the git plugin or in this git lfs plugin?
2. Is there a standard way to test the plugin before I send a PR?

**Comment by billyromano** [comment]
Hey @vietduc01100001, thanks for your help with this btw : )

1. The aliases that are just git related, should be in the git plugin and the git lfs aliases should be in the git lfs plugin.
2. Yes. If you commit your changes in a feature branch, we can test it easily based on where you sourced/installed your ohmyzsh setup. The setup install is basically cloning the ohmyzsh repo, so you can just change your branch on that repo and run the terminal commands locally to test.

**Comment by vietduc01100001** [comment]
Thanks @billyromano for making that clear for me. I'm going to submit an PR soon ;)

**Comment by vietduc01100001** [comment]
@billyromano I don't see any branch other than master. It says creating a PR from the default branch is an anti-pattern.

**Comment by billyromano** [comment]
@vietduc01100001 take a look at their [contributing documentation](https://github.com/ohmyzsh/ohmyzsh/blob/master/CONTRIBUTING.md) to figure out how to fork the repo.

**Comment by mcornella** [comment]
#9077 added git-lfs aliases.
