### ISSUE TITLE
Using '~' in the ZSH env variable breaks things

### ISSUE THREAD

**Issue by Nokel81** [ohmyzsh/ohmyzsh#8599]
**Describe the bug**

I wanted to make my `.zshrc` file more portable (between users) so I did 
```
export ZSH="~/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh
```
but somewhere along the line the folder `~` was created in my `$HOME`

**Expected behavior**

Use `$HOME` instead of creating one.

**System:**
 - OS: macOS 10.15.2 & Ubuntu 18.04.1
 - Zsh version: 5.7.1
 - Terminal emulator: iTerm2 (and iterm2 over ssh)

**Comment by mcornella** [comment]
Use ~ without quotes, otherwise there's no tilde expansion: `export ZSH=~/.oh-my-zsh`.

**Comment by TriMoon** [comment]
@Nokel81 you need to keep in mind that all shells not only zsh do tilde-expansion on `~` when it is **outside** strings only :wink: 

So you could use either:
- `export ZSH=~/.oh-my-zsh` as pointed out by mcornella.
- `export ZSH=~/".oh-my-zsh"` note the placement of the quotes, in case you need to use a path containing spaces etc.
