### ISSUE TITLE
Claim the project on https://opencollective.com/

### ISSUE THREAD

**Issue by Clausinho** [ohmyzsh/ohmyzsh#8600]
Hey there,

First of all, I am not affiliated with OpenCollective and just stumbled upon it.
There seems to be 14 backers willing to pay $1,928 on https://opencollective.com/zsh/claim
I don't know if you accept donations, but you could also accept them over this platform.

@robbyrussell 
@larson-carter 
@mcornella

I hope I found the right way of telling you this.

Best Wishes

**Comment by mcornella** [comment]
Related: https://github.com/ohmyzsh/ohmyzsh/issues/5751
We're talking about it, thanks!

**Comment by robbyrussell** [comment]
That's very nice of everyone. o.0
