### ISSUE TITLE
some commands are duplicated after typing tab!

### ISSUE THREAD

**Issue by nijkah** [ohmyzsh/ohmyzsh#8602]
**Describe the bug**
When the shell shows lists for suggestions, characters before cursor duplicate.

*Before Tab*
![image](https://user-images.githubusercontent.com/25769408/73935567-28c6f800-4924-11ea-8402-be313bdae096.png)

*After Tab*
![image](https://user-images.githubusercontent.com/25769408/73935592-38464100-4924-11ea-9d3f-094dc2a45301.png)

**System:**
 - OS: Ubuntu 18.04.2 LTS, 
 - zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
 - Terminal emulator: WSL(v1) on Windows 10
 - Plugins I use: zsh-autosuggestions, fast-syntax-highlighting

**Additional context**
plugins seem to have no effect on this issue.
This bug doesn't appear when I use bash shell.

You can see my zshrc file here
(https://github.com/nijkah/my_settings)

**Comment by mcornella** [comment]
Try [this FAQ section](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command).

**Comment by nijkah** [comment]
![image](https://user-images.githubusercontent.com/25769408/73989974-0ddb9e80-498b-11ea-855a-3ecdde2099b5.png)

It doesn't work. (I re-opened terminal.)

**Comment by mcornella** [comment]
It has to be a problem with utf8 characters. I bet it's a bug in Windows Terminal, which is still in beta. Try using the other WSL terminal, see if you can reproduce this.

**Comment by mcornella** [comment]
Confirmed to be a problem in Windows Terminal. The same happens to me with prompts that contain UTF-8 glyphs. I couldn't find a [dedicated issue in the GitHub project](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), perhaps you'll have better luck.
