### ISSUE TITLE
Changing the color of directories when pressing tab (suggestion)

### ISSUE THREAD

**Issue by floatingpurr** [ohmyzsh/ohmyzsh#8603]
When I type `cd` or `ls` and then I press *tab* directories are listed in red.
Is there a way to change this color to, let's say, blue?

I'm using robbyrussell theme (even if I think this color is not strictly related to the theme)

**Comment by jeffmhubbard** [comment]
You could `man 5 dir_colors`, or use https://github.com/trapd00r/LS_COLORS

**Comment by mcornella** [comment]
This may be also a case of a completion widget setting the color red and bleeding into the completion entries. Are you using `COMPLETION_WAITING_DOTS=true` maybe?

**Comment by floatingpurr** [comment]
> COMPLETION_WAITING_DOTS

No I'm not. This is commented in my `.zshrc`

**Comment by floatingpurr** [comment]
> dir_colors

I'm on macOS and `dir_colors` is not available. I'll try with https://github.com/trapd00r/LS_COLORS.

Do I need those tools even if I'd just like to have exactly the same colors that I visualize when I type `ls`?

**Comment by mcornella** [comment]
If you're using `$LS_COLORS` already (check if it's defined) you can use
```zsh
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
```
to have it show exactly as ls does. Otherwise, you can paste the `LSCOLORS` variable contents [here](https://geoff.greer.fm/lscolors/) and it'll show the equivalent `LS_COLORS` variable content you should define for the above snippet to work.

**Comment by floatingpurr** [comment]
Hi, yes try with:

```
# colors for autocomplete (such as ls)
export LS_COLORS="di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
```

in your `.zshrc`

**Comment by scholar7r** [comment]
I use zinit to load plugins and my dirs red

```
autoload -Uz colors && colors
zmodload zsh/complist
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
```
