### ISSUE TITLE
Can't Access ~/.zshrc File

### ISSUE THREAD

**Issue by Flames13** [ohmyzsh/ohmyzsh#8608]
Whenever I try to access my ~/.zshrc file, through any means it always just brings me to my home folder and nothing else. Do I not have the correct permissions, I am admin on my computer. Oh and BTW I am on a mac on MacOS Catalina (10.15.1).

**Comment by mcornella** [comment]
I can't think of a command that would "bring me to my home folder". Can you explain how are you trying to "access" the zshrc file? Also, if you're worried about correct permissions you should post what permissions the file has? (run `ls -l ~/.zshrc`).

**Comment by Flames13** [comment]
Sorry I've already figured out my issue, I was trying to access the file in the entirely wrong way, sorry about the trouble!

**Comment by mcornella** [comment]
That's ok. Note that it's important to post as much information as possible both for us and for people reading this issue in the future. For future issues also, it's nice to go back to issues you open and close them when they're not relevant anymore. And welcome to GitHub, I hope you have as much fun as we do!
