### ISSUE TITLE
Korean language is broken on ZSH.

### ISSUE THREAD

**Issue by LOGANLEEE** [ohmyzsh/ohmyzsh#8609]
**Describe the bug**

**To Reproduce**
1. Type korean
2. See broken text

**Expected behavior**
well formatted korean

**Screenshots or recordings**
<img width="1310" alt="Screen Shot 2020-02-10 at 17 35 11" src="https://user-images.githubusercontent.com/26853553/74133335-b60f9280-4c2b-11ea-9efa-aa4bf189cc16.png">
![Feb-10-2020 17-34-30](https://user-images.githubusercontent.com/26853553/74133357-c162be00-4c2b-11ea-9618-9da1186b0893.gif)

**System:**
 - OS: macOS Catalina version 10.15.3 (19D76)
 - Zsh version: zsh 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator:  Terminal Version 2.10 (433)
- Termial font :  Maslo LG S for Powerline

**Additional context**

**Comment by mcornella** [comment]
[Check that you have a working `locale`](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-change-my-locale) first.

**Comment by LOGANLEEE** [comment]
I've change locale values as 'ko_KR.UTF-8'

`LANG="ko_KR.UTF-8"
LC_COLLATE="ko_KR.UTF-8"
LC_CTYPE="ko_KR.UTF-8"
LC_MESSAGES="ko_KR.UTF-8"
LC_MONETARY="ko_KR.UTF-8"
LC_NUMERIC="ko_KR.UTF-8"
LC_TIME="ko_KR.UTF-8"
LC_ALL="ko_KR.UTF-8"`

And now i'm getting this...;;
<img width="547" alt="Screen Shot 2020-02-11 at 1 36 07" src="https://user-images.githubusercontent.com/26853553/74169588-e167a100-4c6e-11ea-9db1-a6e85ba16d55.png">

Korean character is changing to <ffffffff> now..

**Comment by mcornella** [comment]
Perhaps you need to run `setopt combiningchars`

**Comment by LOGANLEEE** [comment]
<img width="553" alt="Screen Shot 2020-02-11 at 9 40 42" src="https://user-images.githubusercontent.com/26853553/74203329-94a5b980-4cb2-11ea-8829-0770f724f3f0.png">
I've typed and same symptoms..;;

**Comment by LOGANLEEE** [comment]
<img width="551" alt="Screen Shot 2020-02-11 at 9 42 12" src="https://user-images.githubusercontent.com/26853553/74203386-cae33900-4cb2-11ea-9d95-a7c8b08b0892.png">
I've added to .zshrc and sourced it. still same

**Comment by mcornella** [comment]
Does the locale you use exist in your system? Run `locale -a` for valid values.

**Comment by LOGANLEEE** [comment]
[local_output.txt](https://github.com/ohmyzsh/ohmyzsh/files/4183828/local_output.txt)

any problem with it...?

**Comment by LOGANLEEE** [comment]
<img width="556" alt="Screen Shot 2020-02-11 at 10 45 38" src="https://user-images.githubusercontent.com/26853553/74205661-a50e6200-4cbb-11ea-9d1a-32452defe6d6.png">


yup it is exist!

**Comment by mcornella** [comment]
I'm sorry I'm not more helpful. Have you tried setting the "Unicode East Asian Ambiguous characters are wide" in the Terminal settings screenshot you posted?

**Comment by LOGANLEEE** [comment]
I've moved from Terminal to Iterm2 from this lesson.
So far, everything is fine..

BTW, Thank you for your help!

**Comment by mcornella** [comment]
Ok, thanks for the response.
