### ISSUE TITLE
All 256 colors are outputted on initialization

### ISSUE THREAD

**Issue by lumaxis** [ohmyzsh/ohmyzsh#8613]
Whenever `source $ZSH/oh-my-zsh.sh` is run, a long list of all available 256 colors is output to the terminal, see screenshot below.

Any idea what would cause this?

![image](https://user-images.githubusercontent.com/406937/74236308-363c0380-4cd1-11ea-8175-b260ced77d2c.png)

**Comment by mcornella** [comment]
Can you post your zshrc file?

**Comment by lumaxis** [comment]
Figured it out. I had recently added a script that adds a function called `colors` which was then triggered this:
https://github.com/ohmyzsh/ohmyzsh/blob/83aa984d1a11199d5bb23fb1e462f48e9b4edc88/lib/theme-and-appearance.zsh#L2

Thanks either way though!
