### ISSUE TITLE
shopt and complete commands should work out of the box in the zsh

### ISSUE THREAD

**Issue by musamaanjum** [ohmyzsh/ohmyzsh#8614]
Bash supports shopt command. Many programs like west of Zephyr use shopt for commands competition. It is very frustrated that shopt isn't supported in ZSH.

I don't want to leave ZSH while working on Zephyr. 

Something like https://github.com/larz258/Zshopt can also be done by default for supporting shopt.
Following lines can be added to the top of the .zshrc for supporting complete.
autoload bashcompinit
bashcompinit

**Comment by mcornella** [comment]
Supporting `shopt` is not possible. Zsh has `setopt`, which is similar. [Here are a list of supported options](http://zsh.sourceforge.net/Doc/Release/Options.html).

Regarding bash completions, the lines you posted are enough to support them. Better write it like so:
```zsh
autoload -Uz bashcompinit && bashcompinit
```
You can put that in your zshrc file for now; maybe we can put it in the init script, but it's better to be safe and run that whenever we're loading a bash completion file.
