### ISSUE TITLE
Keep agnoster prompt but change zsh themes?

### ISSUE THREAD

**Issue by ridhwaans** [ohmyzsh/ohmyzsh#8615]
Using: 
`zsh 5.4.2 (x86_64-ubuntu-linux-gnu)`
`antigen (latest)`
`hyperterm 3.0.2 on WSL`

https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
![image](https://user-images.githubusercontent.com/1103336/74253580-19d5a200-4ca4-11ea-9d7e-00b9ea8aa3c3.png)
(credit: https://github.com/agnoster/agnoster-zsh-theme)

As seen above the agnoster theme features a CLI prompt similar to powerlevel9k which disappears when the theme is changed to anything else. Is there a way to preserve the prompt rendering as a separate plugin while reloading different themes/color schemes?

**Comment by mcornella** [comment]
`agnoster` is also a theme; if you change the theme, you won't have the agnoster theme anymore. What do you expect to happen when changing the theme?

[Note that themes don't include color schemes or fonts](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#what-is-a-zsh-theme), those need to be set up in your terminal emulator. Perhaps that's what you want to change?
