### ISSUE TITLE
autoload: command not found

### ISSUE THREAD

**Issue by NizarETH** [ohmyzsh/ohmyzsh#8616]
Hi all,

I execut this command : `~/.zshrc` and I get this response : `/Users/nizar/.oh-my-zsh/oh-my-zsh.sh: line 23: autoload: command not found
/Users/nizar/.oh-my-zsh/oh-my-zsh.sh: line 41: syntax error near unexpected token `('
/Users/nizar/.oh-my-zsh/oh-my-zsh.sh: line 41: `for plugin ($plugins); do'`

could you help me, please ?

**Comment by mcornella** [comment]
You don't have to execute the zshrc file, you have to run `zsh` and it will read the file. Afterwards, you can set zsh as the default shell with `chsh` (look at the wiki FAQ for instructions).
