### ISSUE TITLE
Convert sshrc into a plugin

### ISSUE THREAD

**Issue by Cyberbeni** [ohmyzsh/ohmyzsh#8619]
sshrc is a small command line tool that wraps the ssh command to also transfer maximum 64kB of files to be used as zshrc. Initially I got down to the required size by just copying the stuff I need from the current version of oh-my-zsh but I think it would be better to convert this tool to a built in plugin that selects the files to transfer every time you use the command, so they only have to be kept up to date in 1 place.

The original source of this tool has been deleted (github.com/Russell91/sshrc) but I reuploaded the last version with a sample oh-my-zsh installation here: https://github.com/Cyberbeni/sshrc

The file to send should be allowed to be parametrised in case someone wants to use different stuff for different remote hosts (like one for your other computer and one for CI slaves)

**Comment by mcornella** [comment]
If I understand it correctly, the sshrc command opens an ssh connection to a remote host and pushes the "dotfiles" of the local host, so that you can use them in the remote host?

**Comment by Cyberbeni** [comment]
Yes, that is correct. The current `bin/sshrc` is a more generic tool and `.sshrc` is responsible for making sure zsh is installed and then setting `.sshrc.d` as the ZDOTDIR

**Comment by Cyberbeni** [comment]
Ah, I guess xxh does what I'm suggesting.

**Comment by Cyberbeni** [comment]
I had time to try out xxh since then and I have to say that it is not good. If you are authenticating with password, it needs sshpass and it also doesn't work on macOS because the XDG env vars are not defined out of the box.

I have deleted my original repo and moved the script to my private dotfiles repo, this is another mirror of the original script: https://github.com/cdown/sshrc

I took out a bunch of unnecessary parts in my version and added a copy phase, which copies the appropriate parts of ohmyzsh (skipping any plugins/themes that are not needed because ARG_MAX is currently 1M on macOS 12 and the plugins alone require more space), the iterm2 shell integration script and the current zshrc file, so you can just split on an env var existing in it instead of having to maintain 2 zshrc files.

There are for sure some stuff that needs to be generalized (for example I don't respect ZDOTDIR and always search for zshrc in home), should I make a pull request or do you think nobody else would want to use it? @mcornella
