### ISSUE TITLE
Can't disable the dotenv confirmation prompt

### ISSUE THREAD

**Issue by fredfortier** [ohmyzsh/ohmyzsh#8626]
After the latest ohmyzsh upgrade, I get prompted `dotenv: source '.env' file in the directory? (Y/n) y` which breaks my scripts.

I added `ZSH_DOTENV_PROMPT=false` to `~/.zshrc` but it has no effect.

I expect to assume Y by default without prompt

 - OS / Distro: Arch
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: zsh 5.7.1 (x86_64-pc-linux-gnu)
 - Terminal emulator: Termite

**Comment by mcornella** [comment]
Are you sure you have the latest version of OMZ? This was a recent change and I personally tested it.

**Comment by archlemon** [comment]
Did you add `export` to the beginning of the line?

**Comment by mcornella** [comment]
You don't need `export`.

**Comment by archlemon** [comment]
@mcornella Ah, okay. It didn't work without export for me on OSX, but I may have failed to reload my config correctly the first time.

**Comment by mcornella** [comment]
@fredfortier did you manage to get it to work?

**Comment by rubenyoko** [comment]
Put it on top of your .zshrc, before loading the plugins. Works for me

`ZSH_DOTENV_PROMPT=false`

**Comment by fredfortier** [comment]
Upgrading worked
