### ISSUE TITLE
ZSH_THEME to continue when connecting to a gcloud instance

### ISSUE THREAD

**Issue by anarchy89** [ohmyzsh/ohmyzsh#8627]
**Describe the bug**
I'm using oh my zsh and I have the default theme set to powerlevel10k and it works fine. When I connect to SSH servers I also enabled the SSH_CONNECTION to have the ZSH_THEME to be powerlevel10k and it works fine when I connect to my own ssh servers.

However, whenever I connect to a gcloud instance using SSH, the same way, the theme doesn't follow in the ssh connection.

**To Reproduce**
1. set the ZSH_THEME="powerlevel10k/powerlevel10k" in .zshrc
2. also set add the following:
`
if [[ -n $SSH_CONNECTION ]]; then
  export ZSH_THEME='powerlevel10k/powerlevel10k'
else
  export ZSH_THEME='powerlevel10k/powerlevel10k'
fi
`
3. ssh -i /path/to/privatekey user@instanceip
4. the theme is gone

**Expected behavior**
I expected the theme to carry over during the connection.

**Desktop (please complete the following information):**
 - OS / Distro: [Manjaro]
 - Latest ohmyzsh Update?: [Yes]
 - ZSH Version: [e.g. 5.7.1]
 - Terminal emulator [XFCE terminal emulator]

**Comment by mcornella** [comment]
The theme (plus dotfiles, OMZ installation, etc.) live in the host. If you need to have the same theme in another host, you need to have the same setup, i.e. install OMZ, the powerlevel10k theme, etc.
