### ISSUE TITLE
Wiki plugin terraform listed in TOC but missing documentation section

### ISSUE THREAD

**Issue by jeffvandyke** [ohmyzsh/ohmyzsh#8628]
I'm wondering if the terraform plugin is in usable shape, and where I might find documentation for how to use it. I saw it listed on the [wiki plugin page](https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins), but the documentation section is missing.

Any info or help would be great, I don't have a lot of GitHub wiki practice. Thanks!

**Comment by mcornella** [comment]
We moved the documentation to plugin READMEs, but still it should be a section in the wiki. Thanks for noticing

PS. The wiki uses Markdown as a formatting language, [you can learn more here](https://guides.github.com/features/mastering-markdown/).
