### ISSUE TITLE
Formatting problems for auto-completions or long commands

### ISSUE THREAD

**Issue by kutoga** [ohmyzsh/ohmyzsh#8631]
If I input commands which are longer than one line or if there is an auto-completion available, the formatting of the command line is destroyed (sometimes some huge whitespaces are added). This is shown in the following GIF:

![screen2](https://user-images.githubusercontent.com/19676199/74642826-f8792800-5173-11ea-9bd9-f35ea55a67e7.gif)

I use the "Windows Terminal" (the same effect happens in the vscode terminal) and the following plugins:
git, wd, zsh-autosuggestions, alias-tips, forgit, zsh-syntax-highlighting

Maybe someone has an idea why this happens? It is sometimes really annoying, especially in combination with tmux.

Thank you very much :) !

**Comment by mcornella** [comment]
What you're showing are suggestions, not autocompletion (there's a difference). 

Try disabling zsh-autosuggestions, it should stop happening. If that's so, report the bug at the zsh-autosuggestions repository.

You can also try with zsh-autosuggestions enabled on a terminal other than Windows Terminal. If the problems stops occurring, it is a bug in Windows Terminal.

**Comment by kutoga** [comment]
Disabling "zsh-autosuggestions" works :)! I will report the bug in their repo.
