### ISSUE TITLE
Repeated characters in front of command robbyrussell

### ISSUE THREAD

**Issue by johnny88** [ohmyzsh/ohmyzsh#8640]
**Describe the bug**
When using the robbyrussell theme and using tab complete extra characters are added to the beginning of the command. Specifically the first two characters. This does not seem to effect the command itself (i.e. it still runs).

**To Reproduce**
1. Enable robbyrussell theme. 
2. Write ls and the beginning of a folder name.
3. Press the tab key twice.
4. See two extra characters at the beginning

**Expected behavior**
No extra characters at the beginning of the command.

**Screenshots and/or Recordings**
Here is a gif:
![Screen Recording 2020-02-18 at 09 15 50](https://user-images.githubusercontent.com/6550688/74717267-68e57f00-5230-11ea-967a-551cf1da41c9.gif)

**Desktop (please complete the following information):**
 - OS / Distro: macOS
 - Latest ohmyzsh Update: Yes
 - ZSH Version: 5.7.1
 - Terminal emulator Alacritty, Tmux + Iterm

**Additional context**
This seems to happen with the robbyrussell theme but not the simple theme. As well as it didn't happen with Iterm but I could get it happening in Tmux with Iterm. Let me know if you need anymore information.

**Comment by mcornella** [comment]
There is a section in the FAQ for this: https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command. Reopen if that doesn't fix it.

**Comment by johnny88** [comment]
Thanks for the quick response, that was exactly the problem. I couldn't find this in the issues so I made a ticket. Sorry if I wasted your time. Thanks again!
