### ISSUE TITLE
OSX plugin throws "compdef" error

### ISSUE THREAD

**Issue by nedludd** [ohmyzsh/ohmyzsh#8648]
Using the `osx` plugin I get this on startup:

```
(HOME).zgen/robbyrussell/oh-my-zsh-master/plugins/osx/osx.plugin.zsh:215: command not found: compdef
```
Race condition maybe?  I'm using `zgen` with the powerlevel10K plugin.  

**Desktop:**
 - OS MacOS Catalina
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator iTerm2

**Comment by mcornella** [comment]
OMZ runs `compinit` when starting. If you're using `zgen`, zgen is in charge of running compinit. Try asking over there as I'm not familiar with it.
