### ISSUE TITLE
zsh: no such file or directory: /home/username/.rvm/bin/rvm-prompt 

### ISSUE THREAD

**Issue by noraj** [ohmyzsh/ohmyzsh#8671]
Related old issue: https://github.com/ohmyzsh/ohmyzsh/issues/5627

**Describe the bug**

When loading 3den.zsh-theme

```
zsh: no such file or directory: /home/username/.rvm/bin/rvm-prompt 
```

This error will appear after each command run.

**To Reproduce**

Use 3den theme.

**Expected behavior**

The theme should no require rvm.

**Desktop (please complete the following information):**
 - OS / Distro: Arch Linux
 - Latest ohmyzsh Update?: Yes
- ZSH Version: 5.8
 - Terminal emulator Konsole

**Solution**

Remove 3den from the default theme list. It can be added in the external non-default theme list.

**Comment by mcornella** [comment]
That's weird, are you sure you're using the latest version? Run `echo $PS1` so I can see what's going on.

**Comment by noraj** [comment]
I was using 'random', no problem with all other theme, just with 3den.

But if I use 3den:

![image](https://user-images.githubusercontent.com/16578570/75113410-1a7c1a00-564e-11ea-8f80-befbf53d5193.png)

**Comment by noraj** [comment]
Ok I needed to use `pikaur -Syu --devel` and not only `pikaur -Syu` to update git packages so it wasn't up to date.

![image](https://user-images.githubusercontent.com/16578570/75113743-99725200-5650-11ea-922b-813865a7d3d7.png)
