### ISSUE TITLE
Recent update has extra stuff in git prompt, and is tediously slow

### ISSUE THREAD

**Issue by ashic** [ohmyzsh/ohmyzsh#8673]
I'm running omz on archlinux. It's been working fine. I just updated the packages, and I see a new part in my prompt that wasn't previously there, and it seems very very slow after each operation. 

```
 ~/project >> master >> bzr@44 ✚  >>
```

Previously, my prompt ended at master, but now it includes bzr@44+. I don't know what that bit is. It it's a branch or a tag. The working directory is clean and up to date with master. 

I do use powerlevel9k. 

Some of my relevant settings:

```
export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs anaconda todo)

plugins=(git scala sbt aws mvn pip python ssh-agent kubetail kubectl)

```
Any ideas?

**Comment by wreighn** [comment]
Manjaro switched from bzr to breezy (arch too most likely). My issue was solved with a simple omz update. Hopefully the same fix worked for you, and anyone else who sees this.

**Comment by ashic** [comment]
Yes, I can confirm that with an omz update, the issue is gone.
