### ISSUE TITLE
After recent Update getting Command not found line printed after running every command.

### ISSUE THREAD

**Issue by sagarchoudhary96** [ohmyzsh/ohmyzsh#8675]
**Describe the bug**
After updating zsh to `5.7.1 (x86_64-apple-darwin19.0)` after running every command I'm getting 
`zsh: command not found: _ruby_version ` printed in the terminal.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Update to latest version
2. Run any command .
3. See the line printed in the terminal.

**Expected behavior**
It should not be printed.

**Screenshots and/or Recordings**
<img width="350" alt="Screenshot 2020-02-24 at 8 34 54 PM" src="https://user-images.githubusercontent.com/16102594/75163388-23034c00-5745-11ea-9b52-028b0f1e5aab.png">

**Desktop (please complete the following information):**
 - OS / Distro:  macOS
 - Latest ohmyzsh Update?: yes
 - ZSH Version: 5.7.1
 - Terminal emulator : terminal.app

**Comment by mcornella** [comment]
Are you using the avit theme? If so, run `upgrade_oh_my_zsh` to get the latest changes and restart the terminal.

PS. the terminal emulator is the program you use to open a terminal, e.g. iTerm2 or Terminal.app. `bash` is not a terminal emulator, it's a shell (just like zsh).

**Comment by sagarchoudhary96** [comment]
Thanks for responding. I’m not using avit theme also i ran upgrade_oh_my_zsh too . It the latest version only which caused this, before it was working fine.

**Comment by mcornella** [comment]
What theme are you using?

**Comment by sagarchoudhary96** [comment]
Hey @mcornella, it's avit theme only being used.

**Comment by mcornella** [comment]
Do you have it customized? The default avit theme doesn't use `_ruby_version` now. Have you made any modifications to it, like redefining the `PROMPT` variable in your zshrc file?

**Comment by sagarchoudhary96** [comment]
the prompt variable was having $(_ruby_version) in it. i removed it, it's working fine now. Thanks for the help 🙂
