### ISSUE TITLE
trying to find cause for unwanted characters + how to fix them

### ISSUE THREAD

**Issue by Popl7** [ohmyzsh/ohmyzsh#8682]
hi,

I am really happy with oh-my-zsh! :-)

Now I also want to use it from within Emacs.
Sadly I get 2 strange characters just after the prompt.
I have looked into color codes, terminal settings, utf8 support but I have not found a solution yet.

Finding the nature or cause of these characters might help me resolve this.

I am running Emacs 26, now 27 with Spacemacs config.
The terminal I use is multi-term, but term and ansi-term behave the same way.
The font I use is MesloLGS NF, which is suggested by powerlevel10k.
The theme I use has no influence on the issue (robbyrussell, jnrowe, agnoster, powerlevelXk)

This is how it looks:
<img width="388" alt="Screenshot 2020-02-26 at 15 47 00" src="https://user-images.githubusercontent.com/4224518/75355746-41855680-58af-11ea-8837-8ea15f8b3dcf.png">

This is a minimum .zshrc which still has the problem:
export TERM="xterm-256color"
export ZSH="/Users/steven/.oh-my-zsh"
ZSH_THEME="jnrowe"
plugins=()
source $ZSH/oh-my-zsh.sh
export LANG=en_US.UTF-8

<img width="191" alt="Screenshot 2020-02-26 at 15 55 48" src="https://user-images.githubusercontent.com/4224518/75356620-7d6ceb80-58b0-11ea-9485-67753ca91469.png">

**Comment by mcornella** [comment]
1. Does this happen when running without rc files (run `zsh -f`)?
2. *If it doesn't happen*, does this happen only because of the zshrc file or are there other init scripts like `/etc/zsh/zshrc` and others. Test that by running `zsh -f`, then `source ~/.zshrc`.
3. *If it still doesn't happen*, then the issue is in one of the other init scripts. You would have to run `zsh -xvic exit &> ~/omz-debug.log` and post the generated file so I can take a look at the whole configuration.

Let me know what you find, I suspect (1) will be a yes, in which case it would be a problem of the terminal emulator.

**Comment by Popl7** [comment]
thx for the quick reply!

1. with zsh -f the terminal looks clean: 'Stevens-MacBook-Pro%'
2. after source ~/.zshrc the character are back as before.
3. I ran this. Does this log contain any useful info in this case?

I have checked for settings in .profile, .zshenv but found nothing special.

**Comment by mcornella** [comment]
Maybe this is the automatic title function at work. Try running `DISABLE_AUTO_TITLE=true`, see if the characters stop appearing.

**Comment by Popl7** [comment]
I have tried this but there is no change.
I checked with echoes in the termsupport.sh and the DISABLE_AUTO_TITLE does return early in 2 functions there.

**Comment by Popl7** [comment]
I have tried the lib files part by part and it happens when I load key-bindings.zsh

**Comment by Popl7** [comment]
It seems that 'zle -N zle-line-init' causes my issue.

**Comment by Popl7** [comment]
I found this code example:
```function zle-line-init () {
	if (( ${+terminfo[smkx]} )); then
		echoti smkx
	fi
}
function zle-line-finish () {
	if (( ${+terminfo[rmkx]} )); then
		echoti rmkx
	fi
}
```
to replace
```
if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
  function zle-line-init() {
    echoti smkx
  }
  function zle-line-finish() {
    echoti rmkx
  }
  # zle -N zle-line-init
  zle -N zle-line-finish
fi
```

Does that make any sense?

**Comment by Popl7** [comment]
I have pushed the code to #8683

**Comment by Popl7** [comment]
Hmm, I am still looking into this.
I don't think my MR fixes anything so I have closed it.

**Comment by mcornella** [comment]
In principle both versions do the same, if smkx is available, rmkx will also be. But it is important that you narrowed that down, try making the functions empty:
```zsh
function zle-line-init zle-line-finish { }
```
If that's the culprit, it might be that you're using a `$TERM` value that isn't supported by the terminal; the `$TERM` value is where you get whether `smkx` and `rmkx` are supported. Try without setting `TERM` and see which `$TERM` value it has.

**Comment by Popl7** [comment]
:-) ah, this works.
With an empty function (but we don't do anything with the numpad? smkx rmkx codes then)
When I leave TERM out, it gets set to eterm-color and the terminal works nicely.
Also with the functions zle-line-xxx intact.
So working for me is:
```
if [[ -n "$INSIDE_EMACS" ]]; then
   # export TERM=
else
  export TERM="xterm-256color"
fi
```
in my .zshrc

**Comment by Popl7** [comment]
Thank you for the great support!
It was not a problem with oh-my-zsh but this does fix it.
Without your tips I probably wouldn't have found it.

Also:
Hopefully this answers the question for more people.
I couldn't a way to solve this on Google.
