### ISSUE TITLE
Load themes/plugins installed by Homebrew

### ISSUE THREAD

**Issue by lbenicio** [ohmyzsh/ohmyzsh#8691]
Hey folks,

I just formatted my macOS and fresh installed oh-my-zsh. 

I installed a couple of themes though homebrew and some plugins too But zsh cant recognize then. 

If I manually source the theme file I got an error from init script that it can't find the theme on the zsh theme folder.

Any way to make zsh load everything I install through homebrew?

**Comment by mcornella** [comment]
Which themes and plugins did you install? Isn't there a README for how to load them?
