### ISSUE TITLE
After the grep.zsh refactor update (roughly 6 hrs ago), ohmyzsh now reports error if installed with sudo

### ISSUE THREAD

**Issue by circlecrystal** [ohmyzsh/ohmyzsh#8693]
**Describe the bug**
Clean installation of ohmyzsh, then restart the shell...

> ~/.oh-my-zsh/lib/grep.zsh:22: permission denied: ~/.oh-my-zsh/cache/grep-alias
~/.oh-my-zsh/lib/grep.zsh:source:36: no such file or directory: ~/.oh-my-zsh/cache/grep-alias

**To Reproduce**
Install ohmyzsh with
`sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended`

**Expected behavior**
There should be no error reported (Before the update, installing ohmyzsh with sudo works).

**Desktop (please complete the following information):**
Ubuntu 18.04LTS

**Comment by mcornella** [comment]
The `ZSH_CACHE_DIR` should always be writable by the user, it's weird to me that you're only seeing it fail now. That said, I have changed grep.zsh to check for that. A more future-proof change is to point `ZSH_CACHE_DIR` to a directory the user has control over, like `$HOME/.cache/`.
