### ISSUE TITLE
PLUGIN/terraform I'm using tfenv and nothing seems to work, expected?

### ISSUE THREAD

**Issue by dynnamitt** [ohmyzsh/ohmyzsh#8700]
**Describe the bug**
terraform <tab> will only show files in current dir

**To Reproduce**
terraform <tab> 

**Desktop (please complete the following information):**
 week old Mint

**Comment by mcornella** [comment]
Can you explain more what's happening and the commands you're running? This gives us nothing to work with. Bear in mind that I have zero terraform experience.

**Comment by dhaugli** [comment]
I believe I have the same problem, before I upgraded to Ubuntu 20.04 I had no issue. 

But after the upgrade if I want to say run terraform apply and then use a variable file not in the same folder so I will do, terraform apply -var-file ../somefolder/terraform.tfvars to grab that var file it wont autocomplete the path anymore. really annoying having to type it in manually.

**Comment by mcornella** [comment]
Try `rm $ZSH_COMPDUMP` and restarting the zsh session with `exec zsh`. Comment if this still didn't fix it.
