### ISSUE TITLE
Can't install oh-my-zsh if not root

### ISSUE THREAD

**Issue by FelixStumvoll** [ohmyzsh/ohmyzsh#8708]
as the title suggest im not able to install oh-my-zsh if im not root
it says `could not create work tree dir '/usr/share/oh-my-zsh': permission denied` 
when i execute it with sudo it only installs it for the root user

**Comment by larson-carter** [comment]
@FelixStumvoll 

Hello. Can you please tell me of what the permissions of the non root user is. 

Is it allowed to create a folder in /usr/share directory? Or is it not available to read/write to the directory after it is created?

More details pertaining to the non root user will be very beneficial.

Thank You.

**Comment by mcornella** [comment]
How are you running the installer? Did you set `$ZSH` to be `/usr/share/oh-my-zsh`?

**Comment by fwarmuth** [comment]
I gues this can be closed?
