### ISSUE TITLE
Dead link in wiki

### ISSUE THREAD

**Issue by shika-blyat** [ohmyzsh/ohmyzsh#8711]
In the wiki, in the [plugin section](https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins), the `stack` link links to nowhere.
EDIT:
I tried to add stack in my zshrc, and it didn't work, even if all other plugins works
Error:
```
shika-blyat@shika-blyat  ~  source ~/.zshrc           
/home/shika-blyat/.oh-my-zsh/plugins/stack/stack.plugin.zsh:2: command not found: stack
```
zshrc involved line:
`plugins=(git archlinux cabal cargo cp docker man pip stack rust sublime sudo vscode)`
full zshrc in case it's useful:
https://bin.drlazor.be/holarclump.zsh

**Comment by larson-carter** [comment]
@shika-blyat 

Hello. Thank you for bringing this to my attention. We are currently under the process of revising the Wiki. Can you please confirm what exactly is happening then you try to go the the link. Possibly a screenshot would be best..

Thanks, Larson

**Comment by mcornella** [comment]
> I tried to add stack in my zshrc, and it didn't work, even if all other plugins works
> Error:
> 
> ```
> shika-blyat@shika-blyat  ~  source ~/.zshrc           
> /home/shika-blyat/.oh-my-zsh/plugins/stack/stack.plugin.zsh:2: command not found: stack
> ```

You need to have [stack](https://docs.haskellstack.org/en/stable/README/) installed.

[The stack section has been added](https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#stack).
