### ISSUE TITLE
Colorize tool not discovered by colorize plugin

### ISSUE THREAD

**Issue by siliconmeadow** [ohmyzsh/ohmyzsh#8713]
**Describe the bug**
With pygments installed, and `which pygmentize` showing the tool available in the user's `$path`, the plugin still produces the message

```Neither 'pygments' nor 'chroma' is installed!```

when using `ccat` or `cless`.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin: `colorize`;
2. Run command `ccat <filename>` or `cless <filename>`
3. See error:  ```Neither 'pygments' nor 'chroma' is installed!```

**Expected behavior**
The `README.md` file implies that that `pygmentize` works by default.

**Desktop (please complete the following information):**
 - OS / Distro: OS X Catalina & Manjaro 19
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: zsh 5.7.1 (x86_64-apple-darwin19.0) & zsh 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator: iTerm2 & Guake

**Comment by mcornella** [comment]
I believe this is a problem with the `$commands` variable not containing the latest commands from the PATH, can you try doing a `rehash` and trying again? If that's the issue, then this patch would solve it:
```patch
diff --git a/plugins/colorize/colorize.plugin.zsh b/plugins/colorize/colorize.plugin.zsh
index 6ed9739f..eb4ea73d 100644
--- a/plugins/colorize/colorize.plugin.zsh
+++ b/plugins/colorize/colorize.plugin.zsh
@@ -9,12 +9,12 @@ colorize_check_requirements() {
     local available_tools=("chroma" "pygmentize")
 
     if [ -z "$ZSH_COLORIZE_TOOL" ]; then
-        if (( $+commands[pygmentize] )); then
+        if command -v pygmentize &>/dev/null; then
             ZSH_COLORIZE_TOOL="pygmentize"
-        elif (( $+commands[chroma] )); then
+        elif command -v chroma &>/dev/null; then
             ZSH_COLORIZE_TOOL="chroma"
         else
-            echo "Neither 'pygments' nor 'chroma' is installed!" >&2
+            echo "Neither 'pygments' nor 'chroma' is installed" >&2
             return 1
         fi
     fi
@@ -22,8 +22,8 @@ colorize_check_requirements() {
     if [[ ${available_tools[(Ie)$ZSH_COLORIZE_TOOL]} -eq 0 ]]; then
         echo "ZSH_COLORIZE_TOOL '$ZSH_COLORIZE_TOOL' not recognized. Available options are 'pygmentize' and 'chroma'." >&2
         return 1
-    elif (( $+commands["$ZSH_COLORIZE_TOOL"] )); then
-        echo "Package '$ZSH_COLORIZE_TOOL' is not installed!" >&2
+    elif command -v "$ZSH_COLORIZE_TOOL" &>/dev/null; then
+        echo "Package '$ZSH_COLORIZE_TOOL' is not installed" >&2
         return 1
     fi
 }
```

**Comment by siliconmeadow** [comment]
I tried your patch @mcornella but then it didn't work at all. Since I provided my fix, I found that I didn't need to specify `ZSH_COLORIZE_TOOL` in `.zshrc`. I'm starting to go mad. Could it be due to me restarting my machines in the meantime? I've checked it both on Mac and Linux. It seems that nothing needed to be done after all.
