### ISSUE TITLE
Gradle plugin: autocompletion suggests "Pattern:"

### ISSUE THREAD

**Issue by SimonMonecke** [ohmyzsh/ohmyzsh#8717]
**Describe the bug**
The regex to extract the task names out of the `gradle tasks --all` output matches the rules pattern help lines.

**To Reproduce**
1. Enable this plugin 'gradle'
2. Try the autocomplete command './gradlew ...'
3. The suggestions list includes "Pattern:"

**Expected behavior**
The autocompletion should suggest tasks only.
The section
```
Rules
-----
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to a configuration.
```
should be ignored. `Pattern:` isn't a task.

**Desktop (please complete the following information):**
 - OS / Distro: Arch Linux
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator Alacritty

**Comment by orafaaraujo** [comment]
I'm having the same issue.

I guess is because Gradle remove project tasks from `./gradlew tasks -all`

```
➜  MyProject git:(develop) ✗ ./gradlew tasks | grep clean
clean - Deletes the build directory.
cleanBuildCache - Deletes the build cache directory.


➜  MyProject git:(develop) ✗ ./gradlew tasks --all | grep clean
app:clean - Deletes the build directory.
base:clean - Deletes the build directory.
````

Is there a way to move back the project tasks?

Thanks

**Comment by mcornella** [comment]
Are you on the latest OMZ version? Manually upgrade with `upgrade_oh_my_zsh`.

**Comment by orafaaraujo** [comment]
Hi, @mcornella 
Yes, I'm using the latest.
To confirm the behavior I reinstall OMZ as well.

To "fix" the issue, I edit the Gradle script `oh-my-zsh/plugins/gradle/_gradle` to run `./gradlew tasks` instead `./gradlew tasks --all`, so this way I could get only the project tasks and not each module task.

I also need to delete the cache of my project, deleting the content of `.gradle/completion/`

Let me know if I could help with something else. :)

**Comment by mcornella** [comment]
Can you post this in https://github.com/gradle/gradle-completion and/or look to see if your issue is covered in there? I'm not well versed in gradle so I don't know how to fix this nor whether your proposed change would break other stuff.

**Comment by orafaaraujo** [comment]
Sure, I can.

Thank you for your attention, mate. :)
