### ISSUE TITLE
bira theme prompt is not assigning proper hostname

### ISSUE THREAD

**Issue by slaffcheff** [ohmyzsh/ohmyzsh#8720]
Hello, I had strange issue with some other softwares which took hostname from my prompt and it appeared to be faulty and I spent a lot of hours debugging wrong stuff.

Long story short: my hostname is firstname.secondname-mbp. Everywhere I check this is it.
My prompt looked like this: firstname.secondname@firstname.

After hardcodded another prompt everything went back to normal and my proper hostname was displayed in the terminal as it follows from above.

I used the following prompt to verify the issue:
`PROMPT='%(!.%{%F{yellow}%}.)$USER @ %{$fg[white]%}%M %{$fg_bold[red]%}➜ %{$fg_bold[green]%}%p %{$fg[cyan]%}%c %{$fg_bold[blue]%}$(git_prompt_info)%{$fg_bold[blue]%} % %{$reset_color%}'`

Can you please help me to modify bira prompt so that it can take my whole hostname? The final target is bira visual appearance + whole length hostname.

**Comment by mcornella** [comment]
In a prompt, `%M` is prompt-expanded to the full hostname, and `%m` is expanded to the short hostname. So you can subtitute `%m` in the bira theme for `%M` and you'll get what you want. See [Customization](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization) for how to set up a custom theme.
