### ISSUE TITLE
Use HIST_REDUCE_BLANKS 

### ISSUE THREAD

**Issue by curusarn** [ohmyzsh/ohmyzsh#8722]
**Is your feature request related to a problem? Please describe.**
Lines that only differ in whitespace are not deduplicated out of my shell history. For example, commands `cd ` and `cd` are both saved in the history despite being semantically and almost syntactically same.

**Describe the solution you'd like**
Enable `HIST_REDUCE_BLANKS` zsh option.
Docs:
> HIST_REDUCE_BLANKS
> Remove superfluous blanks from each command line being added to the history list.

**Describe alternatives you've considered**
Enabling `HIST_REDUCE_BLANKS` in my local configuration but I think this might be useful to many people without having any negative effects on people who don't care.

I'm wondering what everyone thinks.

**Comment by mcornella** [comment]
:+1: in principle, I'll run this for a month to see if I have any problems. The option exists since the beginning, according to the repository.
