### ISSUE TITLE
zsh consumes 30% CPU resources in WSL when my laptop is in sleep mode

### ISSUE THREAD

**Issue by misadrik** [ohmyzsh/ohmyzsh#8723]
**Describe the bug**
My XPS's lid is closed and the  computer is in sleep mode. The power is plug in and I heard the fan's noise quite loud. I open the computer and see the task manager. It shows that the zsh is taking 30% CPU resources constantly. After I end this the fan noise gone.
My WSL windows is shut down and only open 2 Edge tabs.

I am using oh my zsh.
plugins are git, zsh autohighting, auto suggestions and jump.

**Desktop (please complete the following information):**
 - OS / Distro: Win 10 WSL
 - Latest ohmyzsh Update? Yes

**Comment by mcornella** [comment]
More information is needed: 

- Which Windows build (run `ver` in a cmd prompt)?
- Which zsh version?
- What's your zshrc file?
- Can you make this happen consistently?
- Does it happen without OMZ (run `zsh -f`)?
- Do you have a terminal window open with zsh running when putting your laptop to sleep?

**Comment by mcornella** [comment]
Also this issue might be related: https://github.com/microsoft/WSL/issues/3940

**Comment by mcornella** [comment]
Knowing which WSL version you're running would also be helpful:

```
$ wsl.exe -l -v
  NAME         STATE           VERSION
* Ubuntu       Running         2
  Alpine       Stopped         2
  AlpineOne    Stopped         1
```

**Comment by noxxxxxxxx** [comment]
when I type `open ./ -a visual` then press tab key try to select the 'Visual \Studio \Code ' 
zsh consumes 94% CPU resources... So I have to kill the thread...

I  uninstall ohmyzsh, then use the Terminal app do such thing, it won't block.

System: macOs Catalina 10.15.3

![Screen Shot 2020-03-10 at 9 19 21 PM](https://user-images.githubusercontent.com/37919656/76316156-0fdfa700-6315-11ea-8303-3fb503916404.png)

![Screen Shot 2020-03-10 at 9 25 13 PM](https://user-images.githubusercontent.com/37919656/76316489-a90ebd80-6315-11ea-885d-3abe0c9752cf.png)

**Comment by mcornella** [comment]
@noxxxxxxxx your issue doesn't belong in this thread, open a separate issue.

**Comment by misadrik** [comment]
> More information is needed:
> 
> * Which Windows build (run `ver` in a cmd prompt)?
Windows 10.0.18363.693
> * Which zsh version?
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
> * What's your zshrc file?
I install the powerlevel 10K and use plugins like git, auto-suggestions, autohighlighting and jump, besides, only add some alias and nothing else.
> * Can you make this happen consistently?
After I use the windows terminal and Open the WSL(ubuntu 18.04), use oh-my-zsh to cd some file and use jump, and auto-suggestions, and close windows terminal. zsh still takes 30% resources.
When I kill it in the task Manager and redo those, it won't happen again, for now.
> * Does it happen without OMZ (run `zsh -f`)?
I think it still constantly take about 30% CPU resource.
> * Do you have a terminal window open with zsh running when putting your laptop to sleep?
The windows terminal is closed.

**Comment by misadrik** [comment]
> Knowing which WSL version you're running would also be helpful:
> 
> ```
> $ wsl.exe -l -v
>   NAME         STATE           VERSION
> * Ubuntu       Running         2
>   Alpine       Stopped         2
>   AlpineOne    Stopped         1
> ```
I am using Ubuntu18.04 installed from Windows Store, just update and upgrade. I have another PC also using oh-my-zsh. Same thing won't happen. It's also very strange that I have at least two process in my XPS's task manager every time I open WSL with windows terminal, while only one in another PC.

**Comment by mcornella** [comment]
This looks very much like https://github.com/microsoft/WSL/issues/3940. Try to upgrade to a newer insiders build or post your issue in the WSL repository with the information you've given me so they can help you.
