### ISSUE TITLE
django plugin: _values:compvalues:11: not enough arguments

### ISSUE THREAD

**Issue by ikhomutov** [ohmyzsh/ohmyzsh#8726]
**Describe the bug**
Autocompletion for certain commands in django plugin doesn't work

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'django'
2. Install django and generate simple project with `django-admin startproject`
3. From the folder contains manage.py file try the autocomplete commands like `manage.py dumpdata` or `manage.py test`

**Expected behavior**
It must display list of applications specified in INSTALLED_APPS section in settings.

**Desktop (please complete the following information):**
 - OS / Distro: Ubuntu 19.10
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.7.1
 - Terminal emulator GNOME Terminal

**Additional context**
- The autocompletion for 'celery' plugin that also evaluates `_values` command works just fine.
- I already removed ~/.zcompdump* files

**Comment by mcornella** [comment]
What do you get when running this (part of the completion functions of the django plugin):
```zsh
python -c "import sys; del sys.path[0]; import os.path as op, re, django.conf; bn=op.basename(op.abspath(op.curdir));[sys.stdout.write(str(re.sub(r'^%s\.(.*?)$' % bn, r'\1', i)) + '\n') for i in django.conf.settings.INSTALLED_APPS if re.match(r'^%s' % bn, i)]"
```

**Comment by ikhomutov** [comment]
Yep, I get an error:

> django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

Specifically, I get this error when I try to access django.conf.settings.INSTALLED_APPS from python cli.
If I export DJANGO_SETTINGS_MODULE as an environment variable, I have no error from python cli, but from zsh I get ModuleNotFoundError. I assume this is because of this line `del sys.path[0]` as I'm working inside virtualenv. If I delete it, the error has gone. Can you tell me what the purpose of this line is?

**Comment by ikhomutov** [comment]
Also, accessing the INSTALLED_APPS parameter is not exactly correct in this case, as it contains list of modules but the management commands expect app name.
More info: https://docs.djangoproject.com/en/3.0/ref/django-admin/#app-names

**Comment by mcornella** [comment]
> I assume this is because of this line `del sys.path[0]` as I'm working inside virtualenv. If I delete it, the error has gone, but I have nothing in output. Can you tell me what the purpose of this line is?

This was added because of https://github.com/ohmyzsh/ohmyzsh/issues/8400.

> If I delete it, the error has gone, but I have nothing in output

What should be the output?

**Comment by ikhomutov** [comment]
Ideally, the output should be a list of app labels, in my case: `[admin, auth, contenttypes, sessions, messages, staticfiles, example]` as it will be used in the completion later.
This list can be displayed by calling `django.apps.apps.get_app_configs()` inside `manage.py shell`

**Comment by ikhomutov** [comment]
From my perspective, the plugin should operate manage.py --help output for better experience, as there is a difference in the output for different versions of django. For instance, `syncdb` is no longer used as a management command.
I'm not very strong in zsh and sh itself, but I can try to rewrite this plugin in this way.

**Comment by mcornella** [comment]
Plugin removed in 73001e9382db99ebd6effcf0bdcd227985109142. Zsh provides a better `django` completion.

**Comment by abcnow** [comment]
question fro @ikhomutov ->how were you able to enable django plugin with ohmyzsh? When I added the django plugin to my zshrc .. I got an error that such plugin doesn't exist..thanks in advance for your help mate!
