### ISSUE TITLE
Files missing shebangs

### ISSUE THREAD

**Issue by rgoldberg** [ohmyzsh/ohmyzsh#8727]
Many files are missing shebangs, or have hard-coded path shebangs (e.g., `#! /bin/zsh`).

Should correct shebangs of the following form be prepended to every applicable file (and hard-coded path shebangs replace with the following form)?

```bash
#!/usr/bin/env <language name>
```

Where `<language name>` can be `zsh`, `ruby`, `bash`, etc…

**Comment by jeffmhubbard** [comment]
The shebang isn't needed, because the files are being sourced not executed. You only need the shebang if you want to execute a script like a program (like `./script`). You also don't need the shebang if calling the script with the interpreter (like `zsh script` or `python script.py`)

**Comment by mcornella** [comment]
What Jeff said, thanks.
