### ISSUE TITLE
Gradle tasks autocompletion fails if org.gradle.console isn't plain or auto

### ISSUE THREAD

**Issue by grossws** [ohmyzsh/ohmyzsh#8730]
**Describe the bug**
`__gradle-generate-tasks-cache` fails to generate task list if `org.gradle.console` is set to `rich` or `verbose` in `gradle.properties` because lines in `gradle_tasks_output` starts with `^[[32` or something similar.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin gradle
2. Set `org.gradle.console=verbose` in `gradle.properties` (local or in `GRADLE_HOME`)
2. Try the autocomplete command `gradle cle`
3. Autocompletion doesn't work for `clean` task

**Expected behavior**
Command completes to `gradle clean`

**Desktop (please complete the following information):**
 - OS / Distro: Arch Linux
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.8-1
 - Terminal emulator: konsole/yakuake

**Additional context**
Autocompletion for options works fine, issue is with parsing colored output from `gradle_tasks_output="$($gradle_cmd --daemon --build-file $gradle_build_file -q tasks --all 2>/dev/null)"`

I'll create PR to fix it soon.

**Comment by orafaaraujo** [comment]
I'm having the same issue.

Any news about it?
