### ISSUE TITLE
Unknown option: -c with git 1.7.1

### ISSUE THREAD

**Issue by nodesocket** [ohmyzsh/ohmyzsh#8732]
I just manually updated `tools/upgade.sh` to the latest version in master (see https://github.com/ohmyzsh/ohmyzsh/commit/14b4f62e65b3d94c275ea8892f252deae9ce619a), but now I am getting:

```
sh upgrade.sh
Updating Oh My Zsh
Unknown option: -c
usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
           [-p|--paginate|--no-pager] [--no-replace-objects]
           [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
           [--help] COMMAND [ARGS]
There was an error updating. Try again later?
```

Running CentOS with Git 1.7.1. Is there really no way to upgrade when running git 1.7.1?

**Comment by mcornella** [comment]
Upgrade manually with `cd "$ZSH"; git pull --rebase --stat origin master` and on further upgrades you won't get the error again.
