### ISSUE TITLE
No "thefuck" plugin description

### ISSUE THREAD

**Issue by ldorigo** [ohmyzsh/ohmyzsh#8733]
Not really a bug but for a lack of a better category, I'm posting it as such. 

On the Wiki "plugins" page, there is a link to a "thefuck" plugin, but it appears to be dead. Searching the page doesn't yield any results other than the table of contents. 

Sorry but I don't have time to investigate now - just signaling it in case you want to fix it !

Edit: apparently it labeled the issue as support rather than bug? pretty sure I selected bug. anyhow :)

**Comment by mcornella** [comment]
> Edit: apparently it labeled the issue as support rather than bug? pretty sure I selected bug. anyhow :)

Bugs are only marked as bugs when we confirm it's a problem in OMZ.

I'm currently editing the Plugins page so that all links point to the plugins' READMEs.

**Comment by mcornella** [comment]
Fixed.
