### ISSUE TITLE
Dreaded complete:13: command not found: compdef

### ISSUE THREAD

**Issue by NotSoCleverLogin** [ohmyzsh/ohmyzsh#8734]
I've read through the other issues on here with this error and have tried all of the solutions that I've Googled through and the solutions presented here to no avail.  I'll attach my zsh debug log shortly.  

I install OMZ yesterday and this message appeared after installation when it ran through its setup.

complete:13: command not found: compdef

Not sure what is causing it.  I've checked for references to anything I used to have in my old BASH stuff for autocomplete for kubectl, etc. but I've basically archived/removed all of it.
[omz-debug.log](https://github.com/ohmyzsh/ohmyzsh/files/4318626/omz-debug.log)

**Comment by NotSoCleverLogin** [comment]
Also, I'm on a Mac, Mojave 10.14.6, using zsh 5.3 (x86_64-apple-darwin18.0)

**Comment by mcornella** [comment]
There is no error in the trace you posted, are you sure it's still happening?

**Comment by NotSoCleverLogin** [comment]
Yep, I noticed that as well.

Copy/paste from iterm2 when I opened it just now:

Last login: Tue Mar 10 18:16:06 on ttys003
complete:13: command not found: compdef
➜  ~ zsh --version
zsh 5.3 (x86_64-apple-darwin18.0)
➜  ~

**Comment by mcornella** [comment]
It might be only run when in a login shell, try to capture the trace with
```
zsh -l -xvic exit ~/omz-debug.log
```
(notice the extra `-l` argument).

**Comment by NotSoCleverLogin** [comment]
Found it.

`if [[ $(__kubectl_type -t __kubectl_compopt) = "builtin" ]]; then
    complete -o default -F __start_kubectl kubectl
else
    complete -o default -o nospace -F __start_kubectl kubectl
fi
+/dev/fd/15:12296> [[+/dev/fd/15:12296> __kubectl_type -t __kubectl_compopt
+__kubectl_type:2> [ -t '==' -t ']'
 -t == -t+__kubectl_type:3> shift
+__kubectl_type:9> [ __kubectl_compopt '=' __kubectl_compopt ']'
 __kubectl_compopt = __kubectl_compopt+__kubectl_type:10> echo builtin
+__kubectl_type:11> return 0
+/dev/fd/15:12296> [[ builtin = builtin ]]
+/dev/fd/15:12297> complete -o default -F __start_kubectl kubectl
+complete:1> emulate -L zsh
+complete:2> local args void cmd print remove
+complete:3> args=( -o default -F __start_kubectl kubectl )
+complete:4> zparseopts -D -a void o: A: G: W: C: F: P: S: X: a b c d e f g j k u v 'p=print' 'r=remove'
+complete:6> [[ -n '' ]]
+complete:8> [[ -n '' ]]
+complete:13> compdef '_bash_complete -o default -F __start_kubectl' kubectl
complete:13: command not found: compdef`

**Comment by NotSoCleverLogin** [comment]
Ironically, I have kubectl installed on my Mac but don't use auto-completion.  Also, I don't have the plugin in omz, the only plugin there is for git.  This is weird.

**Comment by mcornella** [comment]
It's being loaded probably in `/etc/zsh/zshenv` or similar. Look for the specific path in the log you generated.

**Comment by NotSoCleverLogin** [comment]
Thanks for the help.  It was in my .zprofile, which I had totally missed.
