### ISSUE TITLE
git clone: error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number

### ISSUE THREAD

**Issue by wealthgod** [ohmyzsh/ohmyzsh#8739]
```
houtin@ZhoudeMacBook-Pro ~ % sh -c "$(curl -fsSL raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
Cloning Oh My Zsh...
Cloning into '/Users/zhoutin/.oh-my-zsh'...
fatal: unable to access 'ohmyzsh/ohmyzsh.git': error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: git clone of oh-my-zsh repo failed
```

**Comment by wealthgod** [comment]
houtin@ZhoudeMacBook-Pro ~ % sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
Cloning Oh My Zsh...
Cloning into '/Users/zhoutin/.oh-my-zsh'...
fatal: unable to access 'https://github.com/ohmyzsh/ohmyzsh.git/': error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: git clone of oh-my-zsh repo failed

**Comment by mcornella** [comment]
May be a proxy error, try running the installer again, and if it doesn't work try to download the zip instead: https://github.com/ohmyzsh/ohmyzsh/issues/8515#issuecomment-575254057.

**Comment by jcranston** [comment]
You can try including `-x localhost:<port>` within your curl command if you are using local port-forwarding to a proxy server. Otherwise, you can also try disconnecting from the proxy, issuing the regular install command, and then reconnecting again.
