### ISSUE TITLE
Have a way to display aliases

### ISSUE THREAD

**Issue by ajr-dev** [ohmyzsh/ohmyzsh#8740]
**Is your feature request related to a problem? Please describe.**
It's difficult to get used to all the aliases at one or having to open the configuration files or the repository when you want to remember the aliases.

**Describe the solution you'd like**
Have an alias that tells you the different commands to display the aliases for more specific things like directory aliases, git aliases etc. For example, `aliases` would show:
`git-aliases => displays aliases for git`
`dir-aliases => displays directory aliases for zsh`
`tmux-aliases => displays tmux custom bindings`
`...`
and `dr-aliases` would show:
`md => make directory`
`cd - => shows the last visited directories`
`...`

**Describe alternatives you've considered**
The possible solution I can think of is having a `#alias` comment for each alias and displaying each of the comments that begin with that string when calling the alias command.

**Comment by mcornella** [comment]
Running `alias` lists all the aliases in effect; you can pipe that into grep to look for specific git aliases. You can also `less` the README for the specific plugin you want to look at, like `less $ZSH/plugins/git/README.md`. There is a plugin as well that adds more ways to search for aliases: [alias-finder](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/alias-finder).
