### ISSUE TITLE
detect-clipboard:33: command not found: uname 

### ISSUE THREAD

**Issue by sc0ttwad3** [ohmyzsh/ohmyzsh#8742]
After the March 2020 update to Oh-My-Zsh, the following message is displayed before the initial shell prompt (every time a new zsh is launched):

```
detect-clipboard:33: command not found: uname
[12:09:33] username:~ $
```

It seems to be generated by [ohmyzsh/lib/clipboard.zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/clipboard.zsh) line 84 (without the 50 lines of comments this would be line 33):

```
  84 elif [[ $(uname -r) = *icrosoft* ]]; then
  85   function clipcopy() { clip.exe < "${1:-/dev/stdin}"; }
  86   function clippaste() { powershell.exe -noprofile -command Get-Clipboard; }
```

`uname` seems fine, I can't spot an error, and monthly updates to Oh-My-Zsh have never caused an issue until now. 

```
$ uname -r
4.19.84-microsoft-standard
```

I tried updating oh-my-zsh manually to very latest, and still the same message. Clipboard copy and paste functionality remains working correctly to/from from Windows. So is this just an annoyance?

**Comment by mcornella** [comment]
`uname` should be available in `/bin`, which is always included in a normally generated `$PATH`. Is it possible you're doing something weird with `$PATH` or `$path` before OMZ is sourced?

**Comment by sc0ttwad3** [comment]
I refactored my ```.zshenv``` file to include ```/bin``` in ```$PATH```. Problem resolved.

Even though it was in ```$PATH``` set in ```.zshrc``` within a running zsh session ```/usr/local/bin /usr/bin /usr/local/sbin /usr/sbin /sbin /bin``` and ```uname`` worked fine.

Thx. Problem must have exist between chair and keyboard. ;-)
