### ISSUE TITLE
kill word (werase) with `ctrl-w` considers `-` as separator instead of space

### ISSUE THREAD

**Issue by chinmayb** [ohmyzsh/ohmyzsh#8743]
**Describe the bug**
When using ctrl w to kill the word it  consides `-` as separator instead of space.  

**To Reproduce**
* lets say we have this in the zsh terminal
  ➜  ~ this is a word-with-hyphen
   pressing `ctrl + w` deletes the word `hyphen` first and then `with`. i.e considering the `-` as the delimiter. However i'd like to use space as the delimiter instead. so that pressing ctrl-W 
deletes the whole word `word-with-hyphen`. If i dont use `Oh My Zsh` settings it deletes the whole word ignoring `-`, which is expected.

**Expected behavior**
ctrl-W should delete the whole word ignoring `-`

**Screenshots and/or Recordings**
N/A

**Desktop (please complete the following information):**
 - OS / Distro:  macOS
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.7.1
 -  iTerm2

**Comment by mcornella** [comment]
[OMZ removes all characters from the `$WORDCHARS` variable](https://github.com/ohmyzsh/ohmyzsh/blob/07e3236bc5c8dbf9d818a4f0145f09bdb4bec6f0/lib/completion.zsh#L4) which is used to test whether a special character is part of a word or not. I don't know the reason behind it, but if you don't want it that way you can redefine the `WORDCHARS` variable to contain characters that should be treated as part of a word. The default (when running `zsh -f`) is `WORDCHARS='*?_-.[]~=/&;!#$%^(){}<>'`.

**Comment by piegamesde** [comment]
I wonder, what is the motivation behind this? I'd agree on some characters, but not having at least `WORDCHARS=_-` seems like a bad default to me.

**Comment by mcornella** [comment]
[This was set up from the very beginning](https://github.com/ohmyzsh/ohmyzsh/commit/5da20b9dddb1f7a9110675ded5df59c4c3ed1b83#diff-1cf34d3b138a6c8f242856c85478a390R7), I don't know the reasoning. I'd maybe think about adding underscore in there to match what other desktop programs do (tested on Chrome, for example), but hyphens aren't part of words in there.

Of course, the desktop and the CLI are very different and I could see a reasoning behind adding hyphens; for example when deleting dash options. For comparison, the default value is:
```zsh
WORDCHARS='*?_-.[]~=/&;!#$%^(){}<>'
```

**Comment by piegamesde** [comment]
CLI arguments are the main reason I got to this. Without `-` in `WORDCHARS`, Pressing ^W on command line arguments will do the following:

```sh
foo --bar --baz
foo --bar --
foo --

```

Whereas if `-` is contained, it'll do:

```sh
foo --bar --baz
foo --bar 
foo 

```

**Comment by mcornella** [comment]
Fixed in 50dc4ab3.

**Comment by matheusgiuliano** [comment]
I couldn't figure out why my zsh was deleting the whole word after I came back from vacation. So glad I found this issue :heart_eyes: :joy: 
For those who come from Google like me and want to keep the old behaviour, simply change the value of 
`WORDCHARS='_-'` to `WORDCHARS=''` on the file  `~/.oh-my-zsh/lib/completion.zsh`

**Comment by mcornella** [comment]
We might have to document this in the FAQ.

**Comment by AnatomicJC** [comment]
Instead editing `~/.oh-my-zsh/lib/completion.zsh` who is part of the git repo, I added this to my `~/.zshrc`:
```
export WORDCHARS=''
```
Because I prefer the old behavior.

**Comment by OneTone** [comment]
> Fixed in [50dc4ab](https://github.com/ohmyzsh/ohmyzsh/commit/50dc4ab3574f4e265dff816d8d9a0195cd260152).

OMZ! This "fix" just ruined my life.
It would be greatly appreciated if you could revert it. @mcornella 

For those who prefer the "expected" behavior of `Ctrl-W`, here the magic is:

```sh
unix-word-rubout() {
  local WORDCHARS=$'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'
  zle backward-kill-word
}

zle -N unix-word-rubout
bindkey '^W' unix-word-rubout
```

**Comment by mcornella** [comment]
The zsh default is:
```zsh
WORDCHARS='*?_-.[]~=/&;!#$%^(){}<>'
```
You can just set that, no need to redefine `^W`, but maybe you have another use case that requires making that change local.

Also, as [I say here](https://github.com/ohmyzsh/ohmyzsh/issues/8743#issuecomment-598417345), `WORDCHARS` was always set to empty string, meaning all non-alphanumeric characters were treated as line separators. This "fix" only added hyphen and underscore, meaning that the previous version was even worse in your case.

**Comment by mcornella** [comment]
> We might have to document this in the FAQ.

Documented [here](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#kill-word-or-backward-kill-word-do--dont-delete-a-symbol-wordchars).

**Comment by mcornella** [comment]
After https://github.com/ohmyzsh/ohmyzsh/issues/9367 and the massive support for the old behavior, I've reverted the commit. The FAQ still has the documentation for how to change it yourself.

**Comment by Moshem123** [comment]
Thanks @mcornella  for listening to the community!
