### ISSUE TITLE
'safe-paste' plugin breaks 'history-substring-search' plugin

### ISSUE THREAD

**Issue by mcurly** [ohmyzsh/ohmyzsh#8749]
**Bug**
Every time the 'safe-paste' plugin is activated it breaks 'history-substring-search' plugin

**To Reproduce**
1. Enable this plugin 'safe-paste' along with 'history-substring-search'
2. Try to use the normal keybindings of history-substring-search to autocomplete any given command in the zsh-history (up key)
3. Always get latest command in history (which is the previous one which is 'source ~/.zshrc' even if there is no equivalent character/string in the current line that would match that previous one) 

**Expected behavior**
To fetch the latest command with matching character/string.

**Desktop**
 - Operating System: Manjaro-ARM 
 - KDE Plasma Version: 5.18.3
 - KDE Frameworks Version: 5.67.0
 - Qt Version: 5.14.1
 - Kernel Version: 4.19.97-1-MANJARO-ARM
 - OS Type: 64-bit
 - Processors: 4 × 
 - Memory: 3.7 GiB of RAM
 - Latest ohmyzsh from distro.
 - ZSH 5.8
 - Terminal emulator: konsole

**Comment by muriiloandrade** [comment]
Same problem here...

**Desktop**
OS: Arch Linux
Kernel: x86_64 Linux 5.6.15-arch1-1
Shell: zsh 5.8
DE: KDE 5.70.0 / Plasma 5.18.5
CPU: Intel Core i5-3210M @ 4x 3.1GHz [59.0°C]
RAM: 11,6GB

**Comment by carlocab** [comment]
Same problem:
 - OS: 64bit Mac OS X 10.15.6 19G2021
 - Kernel: x86_64 Darwin 19.6.0
 - Shell: zsh 5.8
 - Latest version of OMZ
