### ISSUE TITLE
Custom theme not listed using lstheme

### ISSUE THREAD

**Issue by zain910128** [ohmyzsh/ohmyzsh#8755]
Hello,

I have installed the powerlevel10k theme and am able to use it by setting it in zshrc file.
I then added "themes" as a plugin and then tried `lstheme`
Upon doing that, the custom theme was not listed in the list of themes, eventhough i was able to navigate into zsh custom theme folder and locate the theme.

How do i see my custom theme in the list of themes ?

**Comment by mcornella** [comment]
If a `.zsh-theme` file is not installed directly under `$ZSH_CUSTOM` or `$ZSH_CUSTOM/themes` it won't be found. I suspect you installed p10k inside a folder, like their guide says, right?
