### ISSUE TITLE
ZSH composer plugin stuck

### ISSUE THREAD

**Issue by Jamesking56** [ohmyzsh/ohmyzsh#8756]
**Describe the bug**
When running zsh via PHPStorm's built-in terminal, ZSH freezes whilst running `composer global config bin-dir --absolute`

This doesn't happen when running zsh outside of PHPStorm.

**To Reproduce**
Not sure

**Expected behavior**
Zsh should load as normal

**Screenshots and/or Recordings**
N/A

**Desktop (please complete the following information):**
 - OS / Distro: Ubuntu 18.04.4
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.4.2
 - Terminal emulator PHPStorm terminal

**Additional context**
N/A

**Comment by Jamesking56** [comment]
Managed to fix this locally by installing Node to my system (making `/usr/bin/node` available in `$PATH`).

Although this solves the issue, I find it really strange that the `composer` plugin would require Node to be installed?!

**Comment by hacfi** [comment]
@Jamesking56 Just by having a quick look at the Composer internals I think it's unlikely that `node` is relevant here. But what happens to me every now and then is that I have PhpStorm listening for Debug Connections which makes composer seem unresponsive. You can test if this might be the issue here as well!

**Comment by Jamesking56** [comment]
@hacfi PHPStorm is not listening for debug connections when it happens, very odd!

**Comment by larson-carter** [comment]
This appears to be a ZSH issue and not a ohmyzsh issue. Since zsh is having issues loading inside of phpstorm. Or it could be a phpstorm issue having troubles launching zsh?

Can someone attach a log file for us to look at?

**Comment by Jamesking56** [comment]
I doubt its a PHPStorm issue since it works as soon as I create a `/usr/bin/node` file - I symlinked mine to the node version in NVM and it fixed the issue.

What log file do you need specifically?

**Comment by larson-carter** [comment]
@Jamesking56 

Is there any way you can give me a zsh history file, and a node log file?

**Comment by Jamesking56** [comment]
I decided to create a DigitalOcean instance to try and replicate the bug for better debugging without screwing up my machine and I don't seem to be able to reproduce it...

**Comment by mcornella** [comment]
I'm going to close this as not OMZ related. Regardless, you can try to disable the composer plugin and put the `composer` call in your zshrc file. The plugin was updated recently so try to update as well with `upgrade_oh_my_zsh`.
