### ISSUE TITLE
Message on startup `rm: remove fifo?` when common-aliases is enabled

### ISSUE THREAD

**Issue by rolandg** [ohmyzsh/ohmyzsh#8763]
**Describe the bug**
I'm getting this message on zsh startup when common-aliases plugin is enabled.
```
rm: remove fifo '/tmp/tmp.PdjRP3xhFC'? 
```

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'common-aliases'
2. start zsh
3. See error

**Expected behavior**
No message

**Desktop (please complete the following information):**
 - OS / Distro: Arch Linux
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: termite

**Comment by mcornella** [comment]
The common-aliases plugin defines an alias to rm so that it is interactive:
```zsh
alias rm='rm -i'
```
There must be some point after OMZ is sourced where there's a `rm` without the `-f`, or without `command rm` which would bypass any aliases and functions named `rm`.

**Comment by rolandg** [comment]
Thanks for the pointer. Had rm in my history plugin.
