### ISSUE TITLE
Sort list of git refs in most recently used (committed) order

### ISSUE THREAD

**Issue by thomaseizinger** [ohmyzsh/ohmyzsh#8767]
**Is your feature request related to a particular plugin or theme? If so, specify it.**

gitfast

**Is your feature request related to a problem? Please describe.**

Having to exactly remember branch names is cumbersome, I would much more prefer if the result of `gco <TAB>` would list branches I (or possible someone else if remote branches are included) recently committed to.

**Describe the solution you'd like**

Make use of the `--sort` option of `git-for-each-ref` command to sort by committer date. (Source: https://stackoverflow.com/a/5188364/2489334) I think, the following function would need to be changed: https://github.com/ohmyzsh/ohmyzsh/blob/2a3a940a4553a271d45722538697a667f9b55293/plugins/gitfast/git-completion.bash#L637-L745

Unfortunately, I have not idea how to write completion scripts or ZSH scripts in general so I couldn't make it work. If I try to add the `--sort` argument, it just seems to be ignored. The completion values of `gco <TAB>` seem to be sorted alphabetically.

**Describe alternatives you've considered**

Setting the `branch.sort` git config value but it doesn't seem to have an effect.

**Additional context**

refs are sorted alphabetically:

![image](https://user-images.githubusercontent.com/5486389/77396544-103d6f00-6df8-11ea-8cff-c7e4faff8ac2.png)

**Comment by mcornella** [comment]
Two things should change for that:
- The `__git_refs` function should echo the refs in MRU order
- The `__gitcomp_direct` function should run [`compadd` with `-V something` to specify unordered display](https://www.zsh.org/mla/users//2014/msg01270.html). Otherwise, `compadd` prints the entries in alphabetical order no matter the order in which the arguments were passed to it.

**Comment by thomaseizinger** [comment]
Do you think it makes sense to change the default behaviour here and make a PR to these changes?

If not, what is your advice on patching these files locally that are compatible with updates?

**Comment by thomaseizinger** [comment]
@mcornella I submitted a PR here: https://github.com/ohmyzsh/ohmyzsh/pull/8860

**Comment by mcornella** [comment]
These should be pushed upstream, i.e. on the git repository. Meanwhile, you can set up a custom plugin, see [adding a new plugin](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#adding-a-new-plugin).

cc @felipec
