### ISSUE TITLE
No such file or directory: zsh-history-substring-search.zsh

### ISSUE THREAD

**Issue by IgWod** [ohmyzsh/ohmyzsh#8768]
**Describe the bug**
After updating oh-my-zsh to the the newest version whenever the terminal is opened following message appears:

```
/home/-/.oh-my-zsh/plugins/history-substring-search/history-substring-search.plugin.zsh:source:2: no such file or directory: /home/-/.oh-my-zsh/plugins/history-substring-search/zsh-history-substring-search.zsh
```

Then when the up or down arrow is pressed following messages appear:

```
No such widget `history-substring-search-up'
```

and

```
No such widget `history-substring-search-down
```

Everything works fine when the commit `fd534eb979aa296dd94a78040e77559a4c4dcdde` (current master) is reversed to `2a3a940a4553a271d45722538697a667f9b55293`.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Checkout `fd534eb979aa296dd94a78040e77559a4c4dcdde` (current master)
2. Restart terminal
3. Press up/down arrow

**Desktop (please complete the following information):**
 - OS / Distro: Fedora
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: zsh 5.7.1 (x86_64-redhat-linux-gnu)
 - Terminal emulator GNOME Terminal

**Comment by IgWod** [comment]
**Probable root cause**
It seems like change to the file `plugins/history-substring-search/history-substring-search.plugin.zsh` causes the problem. Keeping the repository on master and reversing just this one file fixes the problem.

The exact offending change is this one:

```
- source "${0:r:r}.zsh"
+ source ${0:A:h}/zsh-history-substring-search.zsh
```

The correct source path is: ` source ${0:A:h}/history-substring-search.zsh` (no zsh- before the history).

I hope it should be an easy fix from now on.

**Comment by mcornella** [comment]
Should be fixed now. My bad sorry 🙏
