### ISSUE TITLE
zsh: command not found: next, zsh: command not found: now

### ISSUE THREAD

**Issue by ScottAgirs** [ohmyzsh/ohmyzsh#8770]
Hey there, this worked before, however, at one point some commands stopped working.

For example `now` and `next` is installed, but when I try to run them, it shows `zsh: command not found: next (or now)`

I tried re-installing the packages, this didn't help. 
Running on macOS Catalina 10.15.3, with iTerm2 (Build 3.3.9), Now @17.1.1 (works via bash).

I did mess around with $PATH, so maybe I need to reset this or?

**Comment by mcornella** [comment]
On bash, run `which next now` to see the path to these commands, then add that folder to PATH in your zshrc file.

**Comment by ScottAgirs** [comment]
hey @mcornella thanks for the reply, sadly this didn't work for me :/ 

Via terminal v zsh:
<img width="185" alt="Screen Shot 2020-03-24 at 3 55 23 PM" src="https://user-images.githubusercontent.com/11737572/77470946-e0866b00-6de7-11ea-86c2-1bdbe46f0f14.png">

Via bash:
<img width="310" alt="Screen Shot 2020-03-24 at 3 56 24 PM" src="https://user-images.githubusercontent.com/11737572/77471041-04e24780-6de8-11ea-8f73-07355d9c2ab7.png">

**Comment by mcornella** [comment]
Try `command -v next now` in bash.

**Comment by ScottAgirs** [comment]
<img width="572" alt="Screen Shot 2020-03-24 at 3 59 33 PM" src="https://user-images.githubusercontent.com/11737572/77471337-78845480-6de8-11ea-87f7-e3f1c2c408d0.png">
