### ISSUE TITLE
yolo in lol plugin is inserting Microsoft copyright messages into commit messages

### ISSUE THREAD

**Issue by MikeyBeez** [ohmyzsh/ohmyzsh#8771]
I don't know if this means anything.  I don't know if MS can make any ownership claims 
because of this copyright message.  

 - OS / Distro: Ubuntu 18,04
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
 - Terminal emulator Terminator

**Comment by mcornella** [comment]
Can you post an example of such commit messages? I have been looking at what whatthecommit.com returns (the website behind the yolo alias) and I haven't seen any copyright messages at all.

**Comment by mcornella** [comment]
Nevermind, found [the culprit](https://github.com/ngerakines/commitment/blob/master/commit_messages.txt#L8). You can complain over there to have it removed, though I don't see the point: it is obviously a jest at Microsoft.

**Comment by MikeyBeez** [comment]
Okay.  Thanks.  I tend to be a bit paranoid.  Thank you.  Stay well.
