### ISSUE TITLE
zsh:1: command not found: tmux

### ISSUE THREAD

**Issue by hisnawi** [ohmyzsh/ohmyzsh#8773]
Trying to run a tmux session over ssh which works for bash but not zsh

I am simply trying to do:
`ssh userx@hostx -t "tmux attach"`

But I get this error:
zsh:1: command not found: tmux

However, if I ssh into the machine and run that command it runs fine.

**Comment by jdguzman** [comment]
@hisnawi did you figure this out?

**Comment by hisnawi** [comment]
@jdguzman yes, I used the full path of tmux on that remote machine

**Comment by mcornella** [comment]
Make sure the path to the tmux binary is in `$PATH`, preferably putting that at the top of your zshrc file.

**Comment by jabofh** [comment]
For anyone running across this after the fact:

The SSH server in macOS has been pre-compiled with `with PATH=/usr/bin:/bin:/usr/sbin:/sbin`.  On macOS, if you install `tmux` using `brew`, it will install in `/usr/local/bin`.

To resolve this, add `PermitUserEnvironment yes` to a file like `/etc/ssh/sshd_config.d/512-userenv.conf`, and then create (or edit) `~/.ssh/environment` and add `PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` to it.

**Comment by rwmitchell** [comment]
Just to clarify, are you ssh'ing from or into a MacOS system?
