### ISSUE TITLE
upgrade_oh_my_zsh fails: error: unknown option `autostash'

### ISSUE THREAD

**Issue by LorenzoAlluminio** [ohmyzsh/ohmyzsh#8774]
As the title says when I try to upgrade oh my zsh, the upgrade fails with the error
```
error: unknown option `autostash'
```

**Comment by mcornella** [comment]
Similar to https://github.com/ohmyzsh/ohmyzsh/issues/8732#issuecomment-597635555, see instructions for manual upgrade.
