### ISSUE TITLE
Support completions from external tools in the ZSH fpath/compinit lifecycle 

### ISSUE THREAD

**Issue by jthegedus** [ohmyzsh/ohmyzsh#8779]
**Is your feature request related to a particular plugin or theme? If so, specify it.**

My feature request is related to all plugins, but I am particularly interested in the `asdf` plugin.

**Is your feature request related to a problem? Please describe.**

Currently, the `asdf` plugin sources the tool's Bash completions. We (maintainer here) recently added [native ZSH completions to the tools codebase](https://github.com/asdf-vm/asdf/tree/master/completions). It would be great to be able to simply symlink the existing ZSH completions to the `plugins/asdf` dir in place of sourcing the Bash completions. However, given all additions to `fpath` and the call to `compinit` are performed before the `*.plugin.zsh` scripts are executed it means any symlink or copy of the actual ZSH files within the plugin's script will not take affect until https://github.com/ohmyzsh/ohmyzsh/issues/7642 is performed.

**Describe the solution you'd like**

1st party support for 3rd party tools to have their completions added to fpath within the oh-my-zsh lifecycle. 

I don't want each `asdf` user to have to learn about `fpath` if this could be automated (as it currently is but with bash completions). Now macOS ships with ZSH as it's default shell we will have many users migrated from Bash to ZSH and so I see this becoming an increasingly large problem. 

**Describe alternatives you've considered**

Manually sourcing the completions from `asdf` before sourcing `oh-my-zsh` so I do not have to rerun compinit.

Relevant parts of my `.zshrc`: 

```shell
fpath=(${HOME}/.asdf/completions $fpath)
plugins=(
  asdf
)
. "$ZSH/oh-my-zsh.sh"
```

**Additional context**

Notably, https://github.com/ohmyzsh/ohmyzsh/pull/8777 will not resolve this issue.

Past work on the asdf plugin:
- https://github.com/ohmyzsh/ohmyzsh/pull/4956
- https://github.com/ohmyzsh/ohmyzsh/pull/6046
- https://github.com/ohmyzsh/ohmyzsh/pull/6456
- https://github.com/ohmyzsh/ohmyzsh/pull/6749
- https://github.com/ohmyzsh/ohmyzsh/pull/7582

Tagging listed Maintainer of OMZ asdf plugin: @RobLoach

Externally relevant:
- https://github.com/zsh-users/zsh-completions/issues/603

**Comment by RobLoach** [comment]
You're correct, it looks like it uses the bash:
https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/asdf/asdf.plugin.zsh

To adapt this, would it instead reference _asdf?

**Comment by jthegedus** [comment]
Yes, the asdf completions are under `asdf/completions/_asdf`. I am unsure there's a better way to do it than the Bash completions given the lifecycle of oh-my-zsh.

**Comment by mcornella** [comment]
In the plugin, we could add to fpath, force-load with autoload, then compdef to add it as a completion function. Changing the lifecycle to allow fpath modifications is hard given the current system, but there are a few plugins that would make use of it.

**Comment by jthegedus** [comment]
A short term solution to the `asdf` specific problem is welcome, thanks for the suggestion @mcornella 

>Changing the lifecycle to allow fpath modifications is hard given the current system, but there are a few plugins that would make use of it.

Food for thought during future development of the tool.

**Comment by carlosala** [comment]
After a lot of time, this should be fixed! The way of autoloading the completion function that `asdf` plugin uses now (see [here](https://github.com/ohmyzsh/ohmyzsh/blob/278bcfc93bed91d1095a9ea7981c4a1109da7abd/plugins/asdf/asdf.plugin.zsh#L25-L29)) should be a good way to autoload completion functions after the compinit.
