### ISSUE TITLE
Use ZSH_THEME if previously defined.

### ISSUE THREAD

**Issue by BlackthornYugen** [ohmyzsh/ohmyzsh#8782]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
Kind of related to robbyrussell but not really. 

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to make different shells with a default theme. The first thing I do when I clone ohmyzsh is change ZSH_THEME="robbyrussell" to "${ZSH_THEME:-robbyrussell}"

**Describe the solution you'd like**
Would like the default profile to use ZSH_THEME if already defined.

**Describe alternatives you've considered**
I haven't really considerd any alternatives.

**Additional context**
With this change you can do this:
![image](https://user-images.githubusercontent.com/3138467/77853858-82c19c80-71b4-11ea-8146-26cb1ae62c9c.png)

**Comment by mcornella** [comment]
See the PR comment.
