### ISSUE TITLE
kube-ps1 not update when change context

### ISSUE THREAD

**Issue by zyf0330** [ohmyzsh/ohmyzsh#8786]
**Describe the bug**
after using `kubectl` change context, kube_ps1 doesn't show updated info.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin '...'
2. Run command 'kubectl config use-context context'
3. kube_ps1 command result is old.

**Expected behavior**
expect result is new context

**Screenshots and/or Recordings**
You can also record an asciinema session: https://asciinema.org/

**Desktop (please complete the following information):**
 - OS / Distro: [e.g. Arch Linux, macOS] ubuntu 19.10
 - Latest ohmyzsh Update?: [e.g. Yes/No] yes
 - ZSH Version: 5.4.2
 - Terminal emulator: tmux

**Additional context**
Add any other context about the problem here. This can be themes, plugins, custom configs.

**Comment by zyf0330** [comment]
I find 93a2ba6b cause this problem.

**Comment by mcornella** [comment]
That commit just pulled the latest changes from upstream (https://github.com/jonmosco/kube-ps1/commit/c685ac80c14605f47a440018e2d03aff58683c81), so open a new issue on the official project.
cc @jonmosco

**Comment by zyf0330** [comment]
@jonmosco 
https://github.com/jonmosco/kube-ps1/commit/db50c18dc4e923de77fa5527320139067b7c48d5
caused this problem. `zstat -L` is the opposite of `stat -L`.

**Comment by mcornella** [comment]
So removing `-L` it works again?
```diff
diff --git a/plugins/kube-ps1/kube-ps1.plugin.zsh b/plugins/kube-ps1/kube-ps1.plugin.zsh
index 0f68ca93..9e77cbc1 100644
--- a/plugins/kube-ps1/kube-ps1.plugin.zsh
+++ b/plugins/kube-ps1/kube-ps1.plugin.zsh
@@ -184,7 +184,7 @@ _kube_ps1_file_newer_than() {
   local check_time=$2

   if [[ "${KUBE_PS1_SHELL}" == "zsh" ]]; then
-    mtime=$(zstat -L +mtime "${file}")
+    mtime=$(zstat +mtime "${file}")
   elif stat -c "%s" /dev/null &> /dev/null; then
     # GNU stat
     mtime=$(stat -L -c %Y "${file}")
```

**Comment by zyf0330** [comment]
yes

**Comment by mcornella** [comment]
Can you submit the PR yourself since you found the solution?

**Comment by zyf0330** [comment]
Hello,  when is this change released?
