### ISSUE TITLE
Alias cp as cp --reflink=auto if possible

### ISSUE THREAD

**Issue by holymonson** [ohmyzsh/ohmyzsh#8791]
**Describe the solution you'd like**
Many systems and FS support `cp --reflink=auto`, we could make it enable by default like `ls` and `grep` enable `--color`.

**Describe alternatives you've considered**
If globally enable is inappropriate, at least make it happens in the _cp_ plugin.

**Comment by mcornella** [comment]
See https://github.com/ohmyzsh/ohmyzsh/pull/8805#issuecomment-632232439
