### ISSUE TITLE
alias "glp" in git plugin isn't actually an alias

### ISSUE THREAD

**Issue by aabdnn** [ohmyzsh/ohmyzsh#8792]
**Describe the bug**
In the "git" plugin, there's an alias defined called "glp". I expected it to be an alias for "git log -p", a rather commonly used git command. Instead, it contains the string "_git_log_prettily", so this alias does not do anything.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin "git"
2. Go into a git repository
3. Type "glp"
4. Nothing happens

**Expected behavior**
I expected zsh to run "git log -p" and show me a git log with diffs.

**Desktop (please complete the following information):**
 - OS / Distro: MacOS Catalina 10.15.4
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.7.1
 - Terminal emulator iTerm2

**Comment by qckzr** [comment]
@aabdnn 

alias `glp` calls function `_git_log_prettily` which executes `git log --pretty=` (it expects to have an argument like `oneline`):

`glp oneline`
 
I'd suggest to use alias `glgp` instead, so you will have `git log --stat -p`

**Comment by mcornella** [comment]
You can define custom aliases in your zshrc file, after OMZ is sourced.
