### ISSUE TITLE
(WSL2) Enabling autojump plugin via plugins=(autojump) gives [oh-my-zsh] autojump script not found

### ISSUE THREAD

**Issue by MostHated** [ohmyzsh/ohmyzsh#8806]
**Describe the bug**
Enabling autojump plugin via plugins=(autojump) gives [oh-my-zsh] autojump script not found

**To Reproduce**
Enable autojump plugin in .zshrc plugins=(autojump) 

**Desktop (please complete the following information):**
WSL2 - Ubuntu 18.04
Latest ohmyzsh (as of today)
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
ExtraTerm 0.49.2

I was originally using antibody plugin manager and kept trying to get autojump to work, but it kept doing the above-mentioned thing, so then I tried it the default way of adding a plugin and saw it did the same thing, so I figured it was a good idea to come here. I tried first in antibody with robbyrussell/ohmyzsh, but then also tried ohmyzsh/ohmyzsh with same results.

**Comment by mcornella** [comment]
What do you get when running `(cd $ZSH; git rev-parse HEAD; git status)`?

**Comment by MostHated** [comment]
Here is the output.

```bash
~ » (cd $ZSH; git rev-parse HEAD; git status)                                                                                                                                             mosthated@DESKTOP-3N4N314
d6474237b823448b3a1dd176a246ed73a30494f9
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by mcornella** [comment]
Oh, right. You need to have autojump installed, see [installation](https://github.com/wting/autojump#installation).

**Comment by MostHated** [comment]
Well shoot, my bad. When I saw autojump in the list of available addons, I assumed that by adding it, it would install the addon. I would definitely like to request that perhaps the error message could add that bit in, something like "Please ensure autojump is installed on your system prior to using this integration".

Thanks,
-MH
