### ISSUE TITLE
Custom Background

### ISSUE THREAD

**Issue by nxtexe** [ohmyzsh/ohmyzsh#8811]
Hey guys. I just found out about wsl and immediately found out about ohmyzsh since I like customizing my terminal. In windows terminal setting the backgroundImage field in the profiles.json file will let you set an image of your choice as your background instead of a solid color. This doesn't work for wsl however. I didn't know what theme to use so I set my theme to random then started opening loads of tabs until I started seeing some themes like rixius had my background image I tried setting in the profiles.json. However I decided on using xiong-chiamiov theme and I was wondering if there was some code I could add to the ~/.zshrc for the theme that would give me the background image.

**Comment by mcornella** [comment]
You're probably seeing a bug in Windows Terminal, the shell isn't concerned with how the background is shown.
