### ISSUE TITLE
Problem with highlighting of Selected texts

### ISSUE THREAD

**Issue by anandnkhl** [ohmyzsh/ohmyzsh#8813]
Whenever I seclect any text (for copying that text) on Zsh it gets highlighted as white text, but when the text is already white in color, then I am not able to view what is selected (Highlighted) what is not.

**Is your feature request related to a particular plugin or theme? If so, specify it.**
No.

**Is your feature request related to a problem? Please describe.**
Whenever I seclect any text on Zsh it gets highlighted as white text, but when the text is already white in color, then I am not able to view what is selected (Highlighted) what is not.

**Describe the solution you'd like**
A better way of highlighting would be, along with making the text white, you can also change the background of the text. That would differentiate between what is selected what isn't selcted.

**Describe alternatives you've considered**
Alternative would be just to change the background of the text instead of changing it's color.

**Additional context**
Here you can see that when I selected some part of red text, it turned white (which indicates that I've selected it.
![image](https://user-images.githubusercontent.com/36640498/78659106-b6a16e00-78e8-11ea-9ac7-5d1a69324359.png)

But Here I've selected some portion of already white colored text, which you can't figure out, since white text is highlighed to white again.
![image](https://user-images.githubusercontent.com/36640498/78659364-10099d00-78e9-11ea-90bb-15c23d8b6f9d.png)

**Comment by mcornella** [comment]
This has to be a problem in your terminal emulator color scheme settings.
