### ISSUE TITLE
Starting command w/ space and pasting preserves old completion

### ISSUE THREAD

**Issue by own2pwn** [ohmyzsh/ohmyzsh#8822]
**Describe the bug**
If execute a command that begins with space and pasting text thereafter, previous command is appended to that text.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable plugin `zsh-autosuggestions`
2. Start command with space, e.g. `_echo '1'` where `_` means space
3. paste text, starting with space, e.g. `_CMD+V`
4. move cursor to the right(right arrow)

**Expected behavior**
To have pasted text only, without previous command being appended

**Screenshots and/or Recordings**
<details><summary> screens</summary>

![image](https://user-images.githubusercontent.com/7850039/79028492-d363cd00-7b98-11ea-927f-e12473f8e739.png)

![image](https://user-images.githubusercontent.com/7850039/79028500-d8c11780-7b98-11ea-8078-c790b1446539.png)

</details>

**Desktop (please complete the following information):**
 - OS / Distro: macOS Catalina 10.15.4 (19E287)
 - Latest ohmyzsh Update?: yes
 - ZSH Version: 5.7.1
 - Terminal emulator iTerm2 3.3.9

**Additional context**
The problems seems to be in `MAGIC_FUNCTIONS`, but I couldn't get in what exactly. Also, seems to run just fine on High Sierra (though zsh version is 5.3)

Related https://github.com/zsh-users/zsh-autosuggestions/issues/521

**Comment by mcornella** [comment]
Ask for support on the zsh-autosuggestions project.
