### ISSUE TITLE
Gentoo new install error bash: autoload: command not found

### ISSUE THREAD

**Issue by InvisibleRasta** [ohmyzsh/ohmyzsh#8826]
Just installed oh my zsh with the cur command on my new gentoo install... trying to source .zshrc i get this error before even touching any config file

bash: autoload: command not found
bash: /home/user/.oh-my-zsh/oh-my-zsh.sh: line 41: syntax error near unexpected token `('
bash: /home/user/.oh-my-zsh/oh-my-zsh.sh: line 41: `for plugin ($plugins); do'

**Comment by mcornella** [comment]
You're using bash, not zsh. You don't have to `source` .zshrc from bash, just run `zsh` (and [make it the default shell if you want](https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH#install-and-set-up-zsh-as-default)) which automatically reads the zshrc file.
