### ISSUE TITLE
Prepend letters on tab completion

### ISSUE THREAD

**Issue by ryckowski** [ohmyzsh/ohmyzsh#8829]
**Describe the bug**
On tab completion always the origin command prepended by 2 letters
If COMPLETION_WAITING_DOTS="true" uncommented  then it's working as expected. I wasted a lot of time to find it how to fix it so by design it should uncommented or fix in another way

**To Reproduce**
1. Type less .zsh and press Tab
Then  'leless .zsh' is displayed which is confusing and is still visible after the command is executed
**Expected behavior**
Do not modify the command there'd been already typed

**Screenshots and/or Recordings**

**Desktop (please complete the following information):**
 - OS / Distro: Arch
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator kitty, termite

**Additional context**

**Comment by mcornella** [comment]
Try this: https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command

**Comment by ryckowski** [comment]
Thanks, it was strange for me that nobody had that issue and google was not helpful here
