### ISSUE TITLE
What does the '-g' mean in 'alias -g ...'?

### ISSUE THREAD

**Issue by aQuaYi** [ohmyzsh/ohmyzsh#8832]
https://github.com/ohmyzsh/ohmyzsh/blob/31eca46ee3b94ca84a038628e0bf6089a7488908/lib/directories.zsh#L6

Thanks first!

**Comment by manfredlotz** [comment]
You can type what you defined as `alias -g` and it gets expanded no matter where you are in the command line. 

I use it much. Here an example:
`alias -g L='|less'`

Now I can type:   `ls -l L ` and get `ls -l | less`. It is important to note that you have to type a blank after the `L`. 

I also should note that I also have defined:

```
zle -N globalias

bindkey " " globalias
bindkey "^ " magic-space           # control-space to bypass completion
```

**Comment by aQuaYi** [comment]
@manfredlotz Thanks.
