### ISSUE TITLE
zsh hook runs git command to delay the command execution

### ISSUE THREAD

**Issue by zxkane** [ohmyzsh/ohmyzsh#8833]
**Describe the bug**
I'm using oh-my-zsh with built-in themes(such as `robbyrussell`, `agnoster` or `ys`). I find that the git command is executed for every command I typed in zsh.

The problem still exists though disabled all plug-ins. Also the problem always happens when using above three themes(I didn't try more built-in themes). 

The problem is gone after disabling the built-in theme or using third party theme `pure`.

**To Reproduce**

See below screen records,

**Expected behavior**

Disable the zsh hook to run git command. Or the command can exit quickly after it exits.

**Screenshots and/or Recordings**

https://asciinema.org/a/H9oBLracs5pm6YhDRLMG1TlXU

https://streamable.com/kem8kb with the process name changes in iTerm2 tab bar

**Desktop (please complete the following information):**
 - OS / Distro:  macOS
 - Latest ohmyzsh Update?: Yes
 - ZSH Version:  zsh 5.8 (x86_64-apple-darwin18.7.0)
 - Terminal emulator : iTerm2

**Additional context**

My zshrc config,
```.zshrc
#zmodload zsh/zprof
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# runs an npm script via lerna for a the current module
alias lr='lerna run --stream --scope $(node -p "require(\"./package.json\").name")'

# runs "npm run build" (build + test) for the current module
alias lb='lr build'
alias lt='lr test'

# runs "npm run watch" for the current module (recommended to run in a separate terminal session):
alias lw='lr watch'

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(
	git 
	osx 
##	gradle 
	brew 
##	command-not-found 
	github 
#	gnu-utils 
##	mvn 
	python 
	pip 
#	screen 
	vi-mode 
	docker 
##	docker-compose 
	node 
##	spring 
	mosh 
#	httpie 
##	sudo 
	tmux 
##	kubectl 
##	helm 
	golang
	history
	history-substring-search
	zsh-autosuggestions
	zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH="$HOME/.toolbox/bin:${KREW_ROOT:-$HOME/.krew}/bin:/Users/kane/bin:/usr/local/sbin:$PATH"
export GOPATH="/Users/kane/git/go-projects/"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
DISABLE_AUTO_TITLE="true"

#zmodload zsh/terminfo
bindkey "$terminfo[cuu1]" history-substring-search-up
bindkey "$terminfo[cud1]" history-substring-search-down

export LANG=en_US.UTF-8

export PATH="/usr/local/opt/ruby/bin:$PATH"
```

**Comment by mcornella** [comment]
It should take that long to run the git command, but that's something the `git_prompt_info` function does to know if it should try to get git information:
```zsh
git_prompt_info () {
	local ref
	if [[ "$(command git config --get oh-my-zsh.hide-status 2>/dev/null)" != "1" ]]
	then
		ref=$(command git symbolic-ref HEAD 2> /dev/null)  || ref=$(command git rev-parse --short HEAD 2> /dev/null)  || return 0
		echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/}$(parse_git_dirty)$ZSH_THEME_GIT_PROMPT_SUFFIX"
	fi
}
```
If you don't want git information, you can override the function by putting this in your zshrc file, after OMZ is sourced:
```zsh
git_prompt_info() {}
```
