### ISSUE TITLE
Color prompt based on exit code of command

### ISSUE THREAD

**Issue by AckslD** [ohmyzsh/ohmyzsh#8842]
I started using zsh and oh-my-zsh this week and am trying to modify the muse theme to indicate whether the last command failed or not. I've been trying find if this issue has already been answered somewhere but couldn't find it. Feel free to point me to an answer if it exists somewhere else.

I've managed to color the first part of the prompt based on the exit code of the last command as follows:
```sh
prompt_color() {
    [[ $? -eq 0 ]] && echo $PROMPT_SUCCESS_COLOR || echo $PROMPT_FAILURE_COLOR
}

PROMPT='%{$(prompt_color)%}%~%{$reset_color%}%{$GIT_PROMPT_INFO%}$(git_prompt_info)$(virtualenv_prompt_info)%{$GIT_DIRTY_COLOR%}$(git_prompt_status) %{$reset_color%}
%{$PROMPT_PROMPT%}ᐅ%{$reset_color%} '
```
which does work. But what I actually want is to color the last `ᐅ` symbol. However, if I replace the `$PROMPT_PROMPT` with `${prompt_color}` at the end of the prompt it does not work (note the newline before `%{$PROMPT_PROMPT%}`). I've also tried to put `$?` at the start of the prompt and by the end. The first one shows a `1` if the command fails but the latter one shows a `0`. I've also tried to save the exit code in a variable before setting `PROMPT` as for example
```sh
RET_VAL=$?
```
but that doesn't seem to be updated for each command but only once.

Any help is highly appreciated, thanks in advance!

(ps, really liking zsh so far :) )

**Comment by manfredlotz** [comment]
Not sure if it helps. Here is a copy of the prompt I use

https://gist.github.com/manfredlotz/8d2098f7670425a7537c032e633c4afe

Of course, I have copied from others to get it done.

**Comment by mcornella** [comment]
You can use the `%(x.true-text.false-text)` prompt sequence using `?` as the `x`, see [Conditional Substrings in Prompts](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Conditional-Substrings-in-Prompts). This removes the need for an extra function:

```zsh
PROMPT='...%{%(?.$PROMPT_SUCCESS_COLOR.$PROMPT_FAILURE_COLOR)%}ᐅ%{$reset_color%} '
```

BTW `${prompt_color}` doesn't actually call the `prompt_color` function, you need to use `$()` (parentheses).

**Comment by AckslD** [comment]
Thanks @mcornella! This worked for me!
