### ISSUE TITLE
React Native  gradlew clean command

### ISSUE THREAD

**Issue by Bayramito** [ohmyzsh/ohmyzsh#8846]
Hi,

i usualy using win for coding but today i got a ubuntu OS, and just installed zsh with some tutorials on the web. So how can i manage to run basic react native commands like `gradlew clean` in android folder ? 

Thank you

**Comment by mcornella** [comment]
I'm not familiar with React Native to answer this, but `gradlew` is normally a file inside the project folder, which needs to be called directly (with a relative path). For example, if there is a `gradlew` file in the `project` directory and you're inside this directory, you would do `./gradlew`.
