### ISSUE TITLE
Support for Azure cli

### ISSUE THREAD

**Issue by jrottenberg** [ohmyzsh/ohmyzsh#8847]
**Is your feature request related to a problem? Please describe.**
ohmyzsh is missing support for the tool azure-cli
https://docs.microsoft.com/en-us/cli/azure/

**Describe the solution you'd like**
A plugin like the one in https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/aws with similar utilities (profiles --> subscriptions)

**Describe alternatives you've considered**
It looks like people have been living without a plugin for azure for a while, but is that fun ?

**Comment by oviliz** [comment]
Looks like someone did something similar 2 years ago, https://github.com/dmakeienko/azcli (haven't tried it though).

**Comment by danarth** [comment]
> Looks like someone did something similar 2 years ago, https://github.com/dmakeienko/azcli (haven't tried it though).

This repo just adds some aliases but doesn't provide the completion. I have thrown something together in order to provide the completion: [danarth/azure-cli.zsh](https://github.com/danarth/azure-cli.zsh)

I have tested this on MacOS and Ubuntu and works ok for me - hope it helps!
