### ISSUE TITLE
git-prompt doesnt support 'stashed' changes

### ISSUE THREAD

**Issue by AdamBD** [ohmyzsh/ohmyzsh#8849]
The git-prompt plugin is excellent but there is no support for 'stashed' changes. Can this be added?

**Comment by devrelm** [comment]
What exact information are you trying to surface?
* Number of stash entries?
* Number of stash entries originating from HEAD?
* Number of stash entries originating from the current branch?
* Something else?

**Comment by AdamBD** [comment]
Hi,

Not sure the difference between these two?
> Number of stash entries?
> Number of stash entries originating from HEAD?

I think however the total number of stash entries for the repo as a whole would be great!

**Comment by ArmCM** [comment]
> Hi,
> 
> Not sure the difference between these two?
> 
> > Number of stash entries?
> > Number of stash entries originating from HEAD?
> 
> I think however the total number of stash entries for the repo as a whole would be great!

Like this

![bla](https://user-images.githubusercontent.com/10622846/82832167-f663eb00-9e7f-11ea-8008-ef71651764ad.png)

**Comment by AdamBD** [comment]
Yeah the above screenshot is from the powerline prompt. I havent ever dug in to see what specific stash implementation they use, but the outcome as I understand it is simply the total count of stash changes related to the current git repo in that directory.

This would be an awesome addition!

**Comment by himat** [comment]
+1
I'm surprised this feature is only being requested now. I would've wanted this years ago.

**Comment by AdamBD** [comment]
@devrelm any feedback on if this might become a thing?

**Comment by mcornella** [comment]
This can be achieved using [`git rev-list --walk-reflogs --count refs/stash`](https://stackoverflow.com/a/53823705/5798232). The `git-prompt` plugin was a bundle of https://github.com/olivierverdier/zsh-git-prompt but there's no more activity over there, so if you want this in someone will have to step up and make the change.

**Comment by mcornella** [comment]
#4880 implemented this. Merged in 47c04d92.
