### ISSUE TITLE
Gentoo errors when sourcing .zshrc

### ISSUE THREAD

**Issue by InvisibleRasta** [ohmyzsh/ohmyzsh#8853]
i have been getting this error on my gentoo box and i cant figure out why. I use the same zshrc on arch and i get no errors:

>  source .zshrc 
bash: autoload: command not found
bash: /home/invra/.oh-my-zsh/oh-my-zsh.sh: line 41: syntax error near unexpected token `('
bash: /home/invra/.oh-my-zsh/oh-my-zsh.sh: line 41: `for plugin ($plugins); do'
>
i found this post and i alredy changed my shell..to zsh
https://github.com/ohmyzsh/ohmyzsh/issues/6405
 
apparently it needed a relogin.. weird... as i tyoed /bin/zsh before sourcing i should of have been in a zsh shell

**Comment by mcornella** [comment]
If it says bash, you're not really in zsh. You'll know you're in zsh because `echo $ZSH_VERSION` will give you the zsh version.
