### ISSUE TITLE
Fedora 31 /bin/usr/zsh already exists and it's a not empty directory

### ISSUE THREAD

**Issue by LearningProcesss** [ohmyzsh/ohmyzsh#8855]
Hi,
this is what i done on a new fresh fedora 31 installation:
- sudo dnf install zsh
- which zsh: /usr/bin/zsh
- configured zsh with minimal option
- chsh -s $(which zsh)
- $shell --version: zsh 5.7.1 (x86_64-redhat-linux-gnu)
- /etc/shells:                                                    
/bin/sh
/bin/bash
/usr/bin/sh
/usr/bin/bash
/usr/bin/tmux
/bin/tmux
/usr/bin/zsh
/bin/zsh

Now, using 
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
give me fatal error: /bin/usr/zsh already exists and it's a not empty directory.

Am i missing something?

**Comment by mcornella** [comment]
You've set $ZSH to /usr/bin/zsh, that's a variable used by the installer to determine were to install OMZ. Run `unset ZSH` and try again.
