### ISSUE TITLE
jsontools README shows incorrect description of is_json

### ISSUE THREAD

**Issue by tapankavasthi** [ohmyzsh/ohmyzsh#8858]
**Describe the bug**
The section in README that describes is_json usage is follows:

```
• is_json:
# pretty print the contents of an existing json file
less data.json | is_json
```

Clearly, there's a documentation bug as is_json is not for pretty print, but for validation.

**To Reproduce**
1. Check [README for jsontools](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/jsontools/README.md)

**Expected behavior**
The description about is_json shall mention that it can be used to check if data conforms to a JSON schema or not

**Screenshots and/or Recordings**
Preview Fix:
![Screenshot 2020-04-26 at 3 35 19 AM](https://user-images.githubusercontent.com/38013895/80291865-f7193c80-876e-11ea-8b53-cb489aee80bc.png)

**Desktop (please complete the following information):**
Not applicable, it's a documentation bug

**Comment by mcornella** [comment]
Please don't open an issue if you have a PR.
