### ISSUE TITLE
Stops colorizing at asterisk symbol *

### ISSUE THREAD

**Issue by turkeyphant** [ohmyzsh/ohmyzsh#8861]
**Describe the bug**
Stops colorizing at asterisk symbol *

**To Reproduce**
Steps to reproduce the behavior, for example:
1. `ccat ~/.zshrc`
2. Color stops after line `# Standard plugins can be found in ~/.oh-my-zsh/plugins/*`

**Expected behavior**
Colorize whole file

**Screenshots and/or Recordings**
![image](https://user-images.githubusercontent.com/8129583/80356785-e2719d00-8871-11ea-8f3a-ae814feb9e78.png)

**Desktop (please complete the following information):**
 - OS / Distro: unRAID
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.6.2
 - Terminal emulator: webterminal

edit actually it seems to stop at the ```/*``` which could just be escaping something.

**Comment by mcornella** [comment]
That has to be a pygmentize bug. Try with `ccat --lexer=sh < ~/.zshrc`.

**Comment by turkeyphant** [comment]
> That has to be a pygmentize bug. Try with `ccat --lexer=sh < ~/.zshrc`.

Am sure you're right.

But I can't work out how to use the lexer option:

```
# ccat --lexer=sh < ~/.zshrc
Error: unknown flag: --lexer
Run 'ccat help' for usage.
```

```
# cat --help
Colorize FILE(s), or standard input, to standard output.

Usage:
  ccat [OPTION]... [FILE]...

Flags:
      --bg="light": set to "light" or "dark" depending on the terminal's background
  -C, --color="auto": colorize the output; value can be "never", "always" or "auto"
  -G, --color-code=: set color codes
  -h, --help=false: help for ccat
      --html=false: output html
      --palette=false: show color palettes
  -v, --version=false: show version
```

**Comment by mcornella** [comment]
This isn't using the `colorize` plugin, so this issue doesn't belong here. Ask wherever you got the `ccat` tool from ([is this it?](https://github.com/jingweno/ccat)).

**Comment by turkeyphant** [comment]
My bad. I uninstalled ccat and tried colorize and it wouldn't work at all.

**Comment by turkeyphant** [comment]
Sorry, my bad.

**Comment by mcornella** [comment]
No worries
