### ISSUE TITLE
It is very difficult to see.

### ISSUE THREAD

**Issue by TyNguyen2001** [ohmyzsh/ohmyzsh#8863]
![Annotation 2020-04-28 005028](https://user-images.githubusercontent.com/64082226/80404488-76cc1600-88eb-11ea-849f-7f98549a0fdf.png)
How do I turn it off? It is very difficult to see.

**Comment by sanjeev-at-runnertech** [comment]
yes

**Comment by mcornella** [comment]
Look up `dircolors` on Google to see how to select another `ls` color scheme.
