### ISSUE TITLE
chsh command unsuccessful. Change your default shell manually.

### ISSUE THREAD

**Issue by nouraellm** [ohmyzsh/ohmyzsh#8865]
**Describe the bug**
The authentication failed, but the changes were made! I guess the process shouldn't pass without making sure of the credentials, I mean the shell shouldn't change to zsh if user's password is incorrect!

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Installation

**Expected behavior**
Ask for the correct password.

**Screenshots and/or Recordings**
<a href="https://ibb.co/kSBbT4X"><img src="https://i.ibb.co/kSBbT4X/Screenshot-from-2020-04-28-16-51-29.png" alt="Screenshot-from-2020-04-28-16-51-29" border="0"></a>

**Desktop (please complete the following information):**
 - OS / Distro: Kali Linux
 - Latest ohmyzsh Update?:  Yes
 - ZSH Version: zsh 5.7.1 (x86_64-debian-linux-gnu)
 - Terminal emulator: bash

**Comment by jeffmhubbard** [comment]
`chsh` changes login shell, but doesn't prevent you from starting any shell installed system-wide.

**Comment by nouraellm** [comment]
So in this case, asking for root privilieges is kind of useless! :-/

**Comment by jeffmhubbard** [comment]
Not really, it's trying to set `zsh` as the default shell. This is probably what most people want, but isn't required.

The install script calls `chsh` for you, as a convenience. But that doesn't take effect until next login. So the script then starts `zsh` for you. But if `chsh` fails, like it did for you, you will need to run it manually to make `zsh` the default (if that's what you want).

**Comment by nouraellm** [comment]
Now I see, thanks for the clarification!
