### ISSUE TITLE
Additional aliases for brew plugin

### ISSUE THREAD

**Issue by gvelasq** [ohmyzsh/ohmyzsh#8871]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
brew plugin

**Describe the solution you'd like**
I suggest adding the following aliases to the brew plugin:

alias bc="brew cleanup"
alias bci="brew cask info"
alias bcl="brew cask list"
alias bco="brew cask outdated"
alias bcu="brew cask upgrade"
alias bl="brew list"
alias bo="brew outdated"
alias bu="brew update"
alias bubco="brew update && brew cask outdated"
alias bubobco="brew update && brew outdated && brew cask outdated"

**Update 2020-05-02:** Added aliases bcl and bl to list above.

**Comment by alessandroagnelli** [comment]
`brew update && brew cask outdated` is already defined as `bcubo`

**Comment by gvelasq** [comment]
Thank you, @alessandroagnelli. I noted the default definition of `bcubo` as you mentioned. I decided to propose `bubco` as a potentially redundant alternative because:

1. It may decrease [surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) for those who might surmise that the order of homebrew commands matches the order of letters in the alias, as it does for most other aliases; and

2. `bubco` would harmonize with `bubobco` if the latter were also to be accepted.

Thanks again for considering.

**Comment by alessandroagnelli** [comment]
@gvelasq I understand the harmony of the commands you are think of. But that would mean having two alias for the same command or change the current one. It's also not easy to change an alias and I don't think it's getting considered atm (@mcornella will confirm).
Meanwhile i have implemented the other aliases.

**Comment by giovanepadawan** [comment]
@gvelasq Hello, what about instead of `bcr` use `bcrin` so that keep the logic and doesn't get confused with brew cask remove?

**Comment by gvelasq** [comment]
@giovanepadawan that sounds great, I agree. Thank you. In that case we might consider harmonizing the upgrade commands as well by changing the proposed `bcu` to `bcup`:

info/install/reinstall/remove disambiguation:
alias bci="brew cask info"
alias bcin="brew cask install"
alias bcrin="brew cask reinstall"
alias brc="brew cask remove"

update/upgrade disambiguation:
alias bu="brew update"
alias bup="brew upgrade"
alias bcup="brew cask upgrade"
