### ISSUE TITLE
Oh-my-Zsh is trying to access other users' home directory

### ISSUE THREAD

**Issue by ZhangTianrong** [ohmyzsh/ohmyzsh#8872]
Hi, I am trying to get Oh-my-Zsh on an HPC of my university. The problem is it is trying to access other users' home, which I don't know which line in the .zsh is doing. I am seeing output like
```
../../*****: Permission denied                                                                                                                                                                
../../********: Permission denied
../../*******: Permission denied
../../*******: Permission denied
../../*****: Permission denied
../../*****: Permission denied
../../****: Permission denied
```
I remember this used to work. I tried reinstalling it but it doesn't help. I also tried to comment out some line in the .zsh file and set ZSH manually but I failed to figure out the problem. JFYI, with no Oh-my-Zsh, zsh runs without a problem.

**Comment by mcornella** [comment]
Post the output of your zshrc file and a general, censored view of the folder structure. I suspect a faulty `$ZSH` definition but it can be many other things.
