### ISSUE TITLE
command completioin for docker

### ISSUE THREAD

**Issue by InvisibleRasta** [ohmyzsh/ohmyzsh#8873]
hello, how do i use the command completion for docker? i actually enabled it in the plugins section of my .zshrc.. sourced .zshrc but when i actually type docker and press tab it will just print out the current directory content

http://ix.io/2kfz

**Comment by Jemaz** [comment]
I'm not sure _why_ it's not working (same as my case), maybe Docker's documentation is missing some information or some problem with the plugin.

Anyways, I've fixed mine by adding `autoload -U compinit && compinit` in the `.zshrc` file, right after `source $ZSH/oh-my-zsh.sh`.

Please give it a try and let me know if it works.

**Comment by panzelva** [comment]
@Jemaz this solution worked for me (for yarn and docker plugins). Thx!

**Comment by mcornella** [comment]
See https://github.com/ohmyzsh/ohmyzsh/issues/7642#issuecomment-623101520, this is the same issue and will be fixed by the referenced PR.
