### ISSUE TITLE
File completion not active when running a python command

### ISSUE THREAD

**Issue by skyflyer** [ohmyzsh/ohmyzsh#8874]
I can not get file completion to work when running python scripts such as `./manage.py`.

### Expected behaviour

`./manage.py loaddata fixt<TAB>` and it would complete the folder name `fixtures`

### Actual behaviour

`./manage.py loaddata fixt<TAB>` and it does nothing

### More information

This is no Mac OS Catalina. If I run `zsh -f` and then try it, it works. Configured plugins:

```
❯ echo $plugins
git
```

(but I guess python plugins get loaded as well, as it completes the `./manage.py` commands as well.)

**Comment by mcornella** [comment]
This is [zsh's django completion](https://github.com/zsh-users/zsh/blob/b3148194d12064878bf55c6e37e24200cf93d9b8/Completion/Unix/Command/_django). What `zsh --version` do you have?

**Comment by skyflyer** [comment]
```
❯ zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

I understand I can use special django completion. Is this the only option I have? I assumed that if I'm not using special plugins/completions, that file completion should always work as it does in plain zsh?

If I disable oh-my-zsh, then it works (with plain zsh).

**Comment by mcornella** [comment]
When you use completion (which needs to be turned on), if there is a completion function for the command your trying to autocomplete it'll use that, otherwise it will default to suggesting filenames. Since we are using the django completion, it should be modified to suggest filenames when completing `loaddata`. That is an upstream issue, ask over on the mailing list: https://zsh.org/mla.

**Comment by skyflyer** [comment]
Thanks! Can I trouble you for an explanation of where I might find which autocompletions are active? I.e., how to disable such autocompletions?

My plugins (configured) are only `git`, as shown by `echo $plugins`, but it seems that django is loaded is loaded as well.
