### ISSUE TITLE
Lost existing .zshrc file after oh my zsh install

### ISSUE THREAD

**Issue by amplicity** [ohmyzsh/ohmyzsh#8877]
Hi there, after installing oh my zsh my existing `.zshrc` file seems to be deleted. I had a `.zshrc` file before installation (with no backups, unfortunately). I'm running OSX, are there any other innate directories that my previous `.zshrc` file may be stored in/found?

Thank you!

**Comment by mcornella** [comment]
The installer copies the existing zshrc to `~/.zshrc.pre-oh-my-zsh.`. You should be able to find it in the home directory.

**Comment by amplicity** [comment]
Thank you @mcornella !

**Comment by mcornella** [comment]
You're welcome

**Comment by ohboyd** [comment]
> The installer copies the existing zshrc to `~/.zshrc.pre-oh-my-zsh.`. You should be able to find it in the home directory.

Only one detail here, which is that there shouldn't be a "." at the end of that command. It should be 
```
~/.zshrc.pre-oh-my-zsh
```

but it was absolutely the solution to my problem otherwise. Thanks @mcornella!

**Comment by vin0010** [comment]
Its cool, I thought I lost it.

**Comment by jarrettalexander77** [comment]
`cat .zshrc.pre-oh-my-zsh >> .zshrc` even set mine all the way back up without any extra work.

**Comment by jagajastic** [comment]
> Its cool, I thought I lost it.

Me too. thanks to @mcornella

**Comment by doem97** [comment]
So the solution is quite simple - One question: why oh-my-zsh do such thing to remove user history??

**Comment by antoniopresto** [comment]
WTF!!!

**Comment by antoniopresto** [comment]
Why not just append??

**Comment by donchuru** [comment]
> Why not just append??

Yeah ikr, seems like such a simple fix. I don't know why that's not the case.

**Comment by georgekolasa** [comment]
> Why not just append??

Yeah why can't it just append? Wasted a time re-adding half of the unknown missing variables before I ended up searching up this article.
