### ISSUE TITLE
Shell prompt is broken after activating asciinema 

### ISSUE THREAD

**Issue by deepaerial** [ohmyzsh/ohmyzsh#8879]
**Describe the bug**
After executing `asciinema rec` prompt cursor shifts few characters left. 

**To Reproduce**
1. Start recording shell using 
```
$ asciinema rec
```
2. Cursor is misplaced after starting recording

**Expected behavior**
Command line cursor does not shift.

**Screenshots and/or Recordings**
[![asciicast](https://asciinema.org/a/xK05XQll1FLKLPJp3T9PQ9kIm.svg)](https://asciinema.org/a/xK05XQll1FLKLPJp3T9PQ9kIm)

**Desktop (please complete the following information):**
 - OS / Distro: macOS Catalina 10.15.4
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: zsh 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator iTerm2 3.3.9

**Additional context**
I tried to reproduce this bug turning off different antigen plugins and changing themes. Bug was still reproducible. Same bug occurs when using Poetry's `poetry shell`

**Comment by mcornella** [comment]
Check that you have correctly set up a UTF-8 locale, see the FAQ section in the wiki.

**Comment by deepaerial** [comment]
Thanks, as you said I didn't have locale set in .`zshrc` file.
