### ISSUE TITLE
Gentoo ohmyzsh error

### ISSUE THREAD

**Issue by InvisibleRasta** [ohmyzsh/ohmyzsh#8883]
I have oh-my-zsh installed and i am trying to add the gentoo zsh completions as well. When i add at the bottom of my zshrc the following as described by the gentoo wiki i get an error:
```
autoload -U compinit promptinit
compinit
promptinit; prompt gentoo
```

The error is:
`(eval):zle:1: not enough arguments for -C`

**Source:**
https://wiki.gentoo.org/wiki/Zsh#app-shells.2Fgentoo-zsh-completions

**Comment by mcornella** [comment]
Try to comment out the `prompt gentoo` part. If the problem doesn't happen, there must be a problem with that theme (prompt). Also, loading `compinit` isn't necessary since that is handled by OMZ.
