### ISSUE TITLE
git plugin shortcut for `git pull origin master`

### ISSUE THREAD

**Issue by raghuramos1987** [ohmyzsh/ohmyzsh#8887]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
git

**Is your feature request related to a problem? Please describe.**
We've glum in the git plugin to pull from upstream. If the upstream is named origin then this is not useful. (In cases when I do not have access to rename the origin to upstream in the repo).

**Describe the solution you'd like**
Would it be okay if I added a glom shortcut to cover origin?

**Describe alternatives you've considered**
The alternative would be to not use the shortcut and type out `gl origin master`

**Additional context**
I can put up a PR if you think this would be a good addition.

**Comment by dimh** [comment]
hi, if you are in `master` you can use `ggl`, this alias execute this command `git pull origin $(current_branch)`

**Comment by raghuramos1987** [comment]
I would like to do this when I'm not on master actually.

**Comment by mcornella** [comment]
You could make your own alias and put it in your zshrc file.
