### ISSUE TITLE
After updated to OSX macOS Catalina, the terminal reported some wrong like failed to load module `zsh/terminfo'

### ISSUE THREAD

**Issue by 993318936** [ohmyzsh/ohmyzsh#8893]
**Describe the bug**
After updated the system, when I press ↑ it should show the last command instead of `^[[A`.Also press the key "tab" after '/et' will show a real "tab", instead of `/etc/` .Even if I have uninstalled OMZ, it will show the same wrong.Besides, after I run the script 'uninstall.sh', the `zsh  --version` got `zsh 5.3 (x86_64-apple-darwin18.0)` .Is it right?Do I uninstall completely?
<img width="1060" alt="78501DBB-10F6-4ADC-BB69-7306C527FB8E" src="https://user-images.githubusercontent.com/14232061/81314201-6a01ac00-90bb-11ea-81e8-cc60c1f1230f.png">

**To Reproduce**
After I updated my system to macOS Catalina(version 10.15.4), every time I start my iTerm2, i got the error:

**Screenshots and/or Recordings**
<img width="1060" alt="8AFB5C53-090B-4C44-8547-03AB5DDC287D" src="https://user-images.githubusercontent.com/14232061/81311708-4f7a0380-90b8-11ea-98a6-b01e0bbe4c84.png">
<img width="1060" alt="CF60B899-4CF1-4B5E-A4B9-24B63C118BA1" src="https://user-images.githubusercontent.com/14232061/81311743-5d2f8900-90b8-11ea-89d1-cbdd1074d3ed.png">
<img width="611" alt="2FA7983B-B79A-4B91-A2F2-B22236C38697" src="https://user-images.githubusercontent.com/14232061/81313760-ddef8480-90ba-11ea-830b-16d1b0f6bc79.png">

**Desktop (please complete the following information):**
 - OS / Distro: [macOS Catalina(version 10.15.4)]
 - Latest ohmyzsh Update?: [No]
 - ZSH Version: [5.3]
 - Terminal emulator [iTerm2]

**Additional context**
What should I do to fix my OMZ?

**Comment by jaxon-hub** [comment]
brew install zsh
