### ISSUE TITLE
git switch and git restore completions removed from gitfast

### ISSUE THREAD

**Issue by davidsierradz** [ohmyzsh/ohmyzsh#8894]
**Describe the bug**
PR #8550 removed `git switch` and `git restore` completions (maybe others as well)

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'gitfast'
2. Run `git switch ...`
3. File completions

**Expected behavior**
I should complete branches.

Thanks!

**Comment by mcornella** [comment]
Which version of git do you have installed?

**Comment by mcornella** [comment]
@felipec would just bundling the [current `git-completion.bash` file](https://github.com/git/git/blob/07d8ea56f2ecb64b75b92264770c0a664231ce17/contrib/completion/git-completion.bash) be enough?

**Comment by davidsierradz** [comment]
> Which version of git do you have installed?

OS: ArchLinux
GIT: 2.26.2
ZSH: 5.8-1
OMZ: r5636.f6a03b239-1

**Comment by RealSkeptic** [comment]
Same issue here.

OS: Linux Mint 18.1
Git version: 2.27.0
Zsh: 5.1.1

Copying the latest git-completion.bash to plugins/git-completion.bash and starting a new shell causes zsh to crash with a segmentation fault when pressing tab. So it probably requires more refined modification.

**Comment by mcornella** [comment]
Try `rm ~/.zcompdump*` before restarting zsh.

**Comment by setu4993** [comment]
I tried creating a custom plugin with the updated `git-completion.bash` while using everything else from the current version of `gitfast` and that didn't work. Is there any other workaround / update on fixing this?

**Comment by mcornella** [comment]
> I tried creating a custom plugin with the updated `git-completion.bash` while using everything else from the current version of `gitfast` and that didn't work.

You can't use both your custom plugin and gitfast, there will be a clash between both `git-completion.bash` files.

> Copying the latest git-completion.bash to plugins/git-completion.bash and starting a new shell causes zsh to crash with a segmentation fault when pressing tab.

The location should be `plugins/gitfast/git-completion.bash`, but don't bother because that will cause git conflicts.

Here's the recommended way to use another git completion:
```
# If your script is somewhere else, you can configure it on your ~/.zshrc:
#
#  zstyle ':completion:*:*:git:*' script ~/.git-completion.zsh
```

So put the file somewhere, then add 
```
zstyle ':completion:*:*:git:*' script path-to-git-completion.bash
```
in your zshrc file. Then, do `rm ~/.zcompdump*` and restart the shell with `exec zsh`.

**Comment by setu4993** [comment]
> You can't use both your custom plugin and gitfast, there will be a clash between both git-completion.bash files.

I created a new plugin and disabled the old one by removing it from my `.zshrc` :).

Anyway, I tried what you recommended and it causes an error that crashes the terminal.
```
/Users/setu/.git-completion.bash:378: read-only variable: QISUFFIX
_git:17: _default: function definition file not found
_dispatch:70: bad math expression: operand expected at `/usr/local...'
```

**Comment by setu4993** [comment]
I guess 1 (possibly naive) question I have is why `git-completion.bash` cannot just be updated in the plugins directory? Would that cause other issues?

**Comment by tantegerda1** [comment]
Heads up: this PR might be a little bit naive … I'm not too much into the OMZ internals and know nothing about e.g. possible conflicts of this PRs changes with other git plugins, assumptions about installed git versions etc…

**Comment by mightyiam** [comment]
@tantegerda1 you may have intended to comment that on the PR instead of on the issue.

**Comment by tantegerda1** [comment]
> @tantegerda1 you may have intended to comment that on the PR instead of on the issue.

yes, indeed, that would have been wiser. I'll post it there too and leave it here for clarity.

**Comment by setu4993** [comment]
Following up on this, I see the PR has been closed without merging. Why is keeping supporting completions for git pre-v2.17, a version >2 years old, more valuable than supporting changes that are supported by more recent versions?

**Comment by keckelt** [comment]
I've removed the gitfast plugin and basically followed the instructions in this medium article: https://medium.com/@oliverspryn/adding-git-completion-to-zsh-60f3b0e7ffbc

**Comment by setu4993** [comment]
@mcornella : Any update on this? Keeping compatibility with a >2 year old version at the cost of supporting more recent versions is not ideal.

**Comment by mightyiam** [comment]
The [readme](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/gitfast) says:

"Not only is it faster, it should be more robust, and updated regularly to the latest git upstream version."

**Comment by felipec** [comment]
> Why is keeping supporting completions for git pre-v2.17, a version >2 years old, more valuable than supporting changes that are supported by more recent versions?

Because people do use old versions of Git, and for them using the latest `git-completion.bash` breaks **everything**. For you only a couple of commands don't work.

Anyway, the latest pull request ensures the commands work for everyone.

**Comment by felipec** [comment]
> "Not only is it faster, it should be more robust, and updated regularly to the latest git upstream version."

Yes, that was true **until** upstream decided to make massive changes that broke backwards compatibility, and they didn't even consider older versions of Git.

Anyway, it should work now.

**Comment by frank-west-iii** [comment]
@felipec , I was going to open a new ticket and still can, but the latest version is causing issues with older versions of Git. After reading through this issue it seemed that this was not the goal. I updated both my system's git versions and the errors go away.  Let me know if you'd like a new issue opened or any other details.

Ubuntu (git version 2.17.1)

fcb6fa78:
![bad](https://user-images.githubusercontent.com/329205/97209198-47eb0b80-1779-11eb-8cd5-eb7c6c123dbc.gif)

3b1699b59527ee8095397b9909a37d55689a0481:
![good](https://user-images.githubusercontent.com/329205/97209226-4de0ec80-1779-11eb-9685-3cdfda0064b1.gif)

macOS (git version 2.24.3)
![osx-bad](https://user-images.githubusercontent.com/329205/97211318-1aec2800-177c-11eb-9fac-c3f385e5198a.gif)

**Comment by mcornella** [comment]
If you run this modified `__git` function does it work correctly?
```zsh
__git ()
{
	case "$1" in
	--list-cmds=*)
		IFS=, read -r -A cmds <<< "${1##--list-cmds=}"
		for x in ${cmds[@]}; do
			case "$x" in
			nohelpers)
				;;
			alias)
				;;
			config)
				;;
			*)
				echo ${__git_cmds[$x]}
				;;
			esac
		done
		return
		;;
	esac
	git ${__git_C_args:+"${__git_C_args[@]}"} \
		${__git_dir:+--git-dir="$__git_dir"} "$@" 2>/dev/null
}
```

**Comment by felipec** [comment]
I'll take a look in a bit. At first instance it seems one issue might be at the top of the `_git` file, in the pkg-config line.

**Comment by felipec** [comment]
@frank-west-iii OK, I think I found one issue:

```diff
--- a/plugins/gitfast/git-completion.bash
+++ b/plugins/gitfast/git-completion.bash
@@ -3607,7 +3607,7 @@ if ! git --list-cmds=main >/dev/null 2>&1; then
        {
                case "$1" in
                --list-cmds=*)
-                       IFS=, read -r -a cmds <<< "${1##--list-cmds=}"
+                       IFS=, cmds=(${1##--list-cmds=})
                        for x in ${cmds[@]}; do
                                case "$x" in
                                nohelpers)
```

The second issue about pkg-config I don't know. The `$(dirname ${funcsourcetrace[1]%:*})` should be returning the location where the `_git` script is, and the `git-completion.bash` should be in the same directory. I don't know why it's checking with `pkg-config`.

**Comment by mcornella** [comment]
The call to pig-config is done at the definition of the location array. Perhaps there should be a check to only add it if the pkg-config call succeeds, and/or silence stderr.

**Comment by felipec** [comment]
@mcornella The check of the exit status is already there. My point is that it should not attempt to run the third location if the first one succeeds.

**Comment by frank-west-iii** [comment]
@felipec, I just loaded up another ubuntu system that has an older git version and the above change you proposed does fix the issue I was seeing on ubuntu.

The output from local osx

```
➜  .oh-my-zsh git:(master) pkg-config --variable=completionsdir bash-completion
Package bash-completion was not found in the pkg-config search path.
Perhaps you should add the directory containing `bash-completion.pc'
to the PKG_CONFIG_PATH environment variable
No package 'bash-completion' found
```

Absolutely don't know enough about the plugin, but this seems to make it go away

```
diff --git a/plugins/gitfast/_git b/plugins/gitfast/_git
index 6ca63ed8..e8ae57a4 100644
--- a/plugins/gitfast/_git
+++ b/plugins/gitfast/_git
@@ -31,7 +31,7 @@ if [ -z "$script" ]; then
        locations=(
                "$(dirname ${funcsourcetrace[1]%:*})"/git-completion.bash
                "$HOME/.local/share/bash-completion/completions/git"
-               "$(pkg-config --variable=completionsdir bash-completion)"/git
+               "$(pkg-config --silence-errors --variable=completionsdir bash-completion)"/git
                '/usr/share/bash-completion/completions/git'
                '/etc/bash_completion.d/git' # old debian
                )
```

**Comment by felipec** [comment]
@frank-west-iii Cool. I'll send a fix for that soon.

Can you try this other change?

```diff
--- a/plugins/gitfast/_git
+++ b/plugins/gitfast/_git
@@ -36,6 +36,7 @@ if [ -z "$script" ]; then
                '/etc/bash_completion.d/git' # old debian
                )
        for e in $locations; do
+               echo "$e" >> /tmp/locations.txt
                test -f $e && script="$e" && break
        done
 fi
```

Check the locations in `/tmp/locations.txt` and see which one is the one you have (and the script is using).

**Comment by frank-west-iii** [comment]
Here you go @felipec 

```
➜  .oh-my-zsh git:(master) ✗ cat /tmp/locations.txt
/Users/frank/.oh-my-zsh/plugins/gitfast/git-completion.bash
➜  .oh-my-zsh git:(master) ✗
```

**Comment by felipec** [comment]
@frank-west-iii Thanks.

I'm so dumb. The pkg-config command is executed **before**! (when the `locations` array is filled). I'll send another patch with `--silence-errors`. That should do it.

**Comment by mcornella** [comment]
> Absolutely don't know enough about the plugin, but this seems to make it go away

Note that on systems that don't have `pkg-config`, this will still error with a command not found error. I'd go for a `2>/dev/null`, but even then, if the `pkg-config` call fails, the third path in the `location` array will be `/git`.

**Comment by felipec** [comment]
@mcornella Right. Defining a fallback variable should deal with those cases, even though I don't think they are common

```sh
bash_completion=$(pkg-config --variable=completionsdir bash-completion 2>/dev/null) ||
  bash_completion='/usr/share/bash-completion/completions/'
```

**Comment by felipec** [comment]
@mcornella @frank-west-iii OK. I've sent these and other fixes on pull #9390.

**Comment by mcornella** [comment]
Merged. @frank-west-iii run `omz update` to get the changes and restart the zsh session with `exec zsh`.

**Comment by frank-west-iii** [comment]
Thanks for helping out and for the quick response.

**Comment by Redmega** [comment]
After updating everything I still see files instead of branches on my git switch completion. I've cleared out .`.zcompdump*` et al to no avail. Any pointers?

**Comment by felipec** [comment]
@Redmega You probably should open a new ticket, and provide as much information as possible.
