### ISSUE TITLE
Oh-my-zsh + zsh-autosuggestions include spaces on command line

### ISSUE THREAD

**Issue by sgondala** [ohmyzsh/ohmyzsh#8896]
I have a strange problem using oh-my-zsh where there are spaces when accepting autocomplete sometimes. How to resolve this?

Some .zshrc information

```
plugins=(git zsh-autosuggestions)
ZSH_THEME="agnoster"

```

![Screenshot from 2020-05-06 19-46-11](https://user-images.githubusercontent.com/6552560/81334475-1881fe80-9074-11ea-9a7f-ef8dead4dd09.png)

**Comment by mcornella** [comment]
Ask on the zsh-autosuggestions project.
