### ISSUE TITLE
command-not-found plugin issue after typing random string

### ISSUE THREAD

**Issue by otis-maia** [ohmyzsh/ohmyzsh#8898]
**Describe the bug**
Could not find the database of available applications, run update-command-not-found as root to fix this
Sorry, command-not-found has crashed! Please file a bug report at:
http://www.debian.org/Bugs/Reporting
Please include the following information with the report:

command-not-found version: 0.3
Python version: 3.7.3 final 0
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
Exception information:

local variable 'cnf' referenced before assignment
Traceback (most recent call last):
  File "/usr/share/command-not-found/CommandNotFound/util.py", line 23, in crash_guard
    callback()
  File "/usr/lib/command-not-found", line 93, in main
    if not cnf.advise(args[0], options.ignore_installed) and not options.no_failure_msg:
UnboundLocalError: local variable 'cnf' referenced before assignment

**Comment by mcornella** [comment]
This is a bug in the `command-not-found` Debian package: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954249
