### ISSUE TITLE
Problem after Arch Linux update

### ISSUE THREAD

**Issue by Ergus** [ohmyzsh/ohmyzsh#8904]
**Describe the bug**
A clear description of what the bug is.
After a yesterday zsh update in arch linux nothing works (completion, history-search, anything)

**To Reproduce**
1. I just copied the default config to assert the problem was not in my config.

2. When starting there are these errors showed.

3. See error
```
~/oh-my-zsh/oh-my-zsh.sh:81: compinit: function definition file not found
~/oh-my-zsh/lib/cli.zsh:41: command not found: compdef
~/oh-my-zsh/lib/completion.zsh:76: bashcompinit: function definition file not found
~/oh-my-zsh/lib/directories.zsh:32: command not found: compdef
~/oh-my-zsh/lib/termsupport.zsh:109: add-zsh-hook: function definition file not found
~/oh-my-zsh/lib/termsupport.zsh:110: add-zsh-hook: function definition file not found
~/oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
~/oh-my-zsh/plugins/git/git.plugin.zsh:19: command not found: compdef
~/oh-my-zsh/plugins/git/git.plugin.zsh:89: command not found: compdef
~/oh-my-zsh/plugins/git/git.plugin.zsh:104: command not found: compdef
~/oh-my-zsh/plugins/git/git.plugin.zsh:109: command not found: compdef
~/oh-my-zsh/plugins/git/git.plugin.zsh:119: command not found: compdef
~/oh-my-zsh/plugins/git/git.plugin.zsh:129: command not found: compdef
~/oh-my-zsh/plugins/git/git.plugin.zsh:138: command not found: compdef
~/oh-my-zsh/plugins/git/git.plugin.zsh:144: command not found: compdef
~/oh-my-zsh/plugins/git/git.plugin.zsh:229: is-at-least: function definition file not found
```

**Expected behavior**
A brief description of what should happen.

**Screenshots and/or Recordings**
You can also record an asciinema session: https://asciinema.org/

![image](https://user-images.githubusercontent.com/6975176/81426575-ad125c80-9159-11ea-875e-5885fd19d575.png)

**Desktop (please complete the following information):**
 - OS / Distro: Arch Linux
 - Latest ohmyzsh Update?:  Yes
 - ZSH Version: 5.8
 - Terminal emulator: Xterm + Tmux

**Additional context**
Add any other context about the problem here. This can be themes, plugins, custom configs.

**Comment by NanoNabla** [comment]
I have the same issue. Did you find a way to fix it?

**Comment by mcornella** [comment]
It seems that it can't find `autoload`-ed functions, like `compinit`, `add-zsh-hook` and `is-at-least`. Did you modify `$fpath` perhaps? What's the output of `typeset fpath`?

**Comment by NanoNabla** [comment]
It seems since the update
`FPATH` lacks of 
`/usr/local/share/zsh/site-functions:/usr/share/zsh/site-functions:/usr/share/zsh/functions/Calendar:/usr/share/zsh/functions/Chpwd:/usr/share/zsh/functions/Completion:/usr/share/zsh/functions/Completion/Base:/usr/share/zsh/functions/Completion/Linux:/usr/share/zsh/functions/Completion/Unix:/usr/share/zsh/functions/Completion/X:/usr/share/zsh/functions/Completion/Zsh:/usr/share/zsh/functions/Exceptions:/usr/share/zsh/functions/Math:/usr/share/zsh/functions/MIME:/usr/share/zsh/functions/Misc:/usr/share/zsh/functions/Newuser:/usr/share/zsh/functions/Prompts:/usr/share/zsh/functions/TCP:/usr/share/zsh/functions/VCS_Info:/usr/share/zsh/functions/VCS_Info/Backends:/usr/share/zsh/functions/Zftp:/usr/share/zsh/functions/Zle` 

For user root which has an equal `.zshrc` file `FPATH` is set correct and no error occured.

Where is the right way to set `FPATH`?

**Comment by ketan0** [comment]
I'm having a very similar issue that started after updating! currently unsure what I should add to PATH, since I don't know where these functions are defined.

**Comment by mcornella** [comment]
When you run `zsh -f`, what's the output of `typeset fpath`? Are the missing directories in there? If so, there could be a problem with your rc files where `FPATH` is overwritten.

**Comment by Ergus** [comment]
The fpath was empty without any reason I could explain; but also all the autoloads were failing even with pure zsh without any config. 
So I decided to use bash from now on. You are free to close this issue when you fix it. But I can't try any fix or new change.

**Comment by mcornella** [comment]
I'd open a bug report in the Arch Linux package, but in the meantime you can add the directories above to fpath at the top of the zshrc file, and it should work correctly.

**Comment by mcornella** [comment]
Maybe there's a system file being run that modifies `$fpath`. Try running the command below and see if there's an instruction that modifies it (post output if unsure):
```zsh
zsh -xvifc exit
```
(explanation: `-xv` enables xtrace and verbose mode, `-i` for interactive, `-f` for no rc files`, `-c exit` for run the exit command after init).
