### ISSUE TITLE
permission denied in popOS(debian)

### ISSUE THREAD

**Issue by ehrktia** [ohmyzsh/ohmyzsh#8907]
As explained in title when trying to install using curl statement provided, getting permission denied to create folder under /Users/XXXXX.oh-my-zsh.
Installation succeeds for root user with elevated root privileges.
checked and followed already provided suggestions.
- assign $ZSH variable to user/oh-my-zsh.
-  tried updating /root folder with read permission.
- checked $SHELL --version command to ensure using zsh as shell.

2. Include as much relevant information as possible
linux - popOS 20.0.4 (debian based).
```console
echo $SHELL
/usr/bin/zsh
echo $ZSH
/Users/karthick/oh-my-zsh
sudo -l
User karthick may run following commands
(ALL:ALL)ALL
```
3. Try to make sure the issue is due to Oh My Zsh
installation support required.Please let me know if you require more details.

**Comment by mcornella** [comment]
> * tried updating /root folder with read permission.

Undo this, this is a really bad idea.

> permission denied to create folder under /Users/XXXXX.oh-my-zsh.

Post the command you're running to install OMZ and the output, and whether `$ZSH` is `export`ed or just set (you can see if it appears in `export | grep ZSH`).

**Comment by ehrktia** [comment]
thanks for quick turn around. I did undo read access to root folder.
Created new user and tried from new user to install oh-my-zsh using the curl command provided. This worked without any issues.
thanks.
