### ISSUE TITLE
zsh is showing the arrows weird

### ISSUE THREAD

**Issue by Royal-lobster** [ohmyzsh/ohmyzsh#8909]
first of all I am new to using terminal and shell. i installed zsh and Oh My Zsh with power-line fonts,removed the user details shown at the start of commands and changed my default theme to agnoster which i liked the appearance. but after installation the arrows are shown weird like in the given picture 
![Screenshot from 2020-05-09 21 10 19](https://user-images.githubusercontent.com/52039218/81478237-a0653580-9239-11ea-9c70-340bdddfded7.png)

**Comment by Royal-lobster** [comment]
I got it, I did not used the powerline fonts.

**Comment by vinid223** [comment]
I have the same issue, but I do have the powerline fonts installed
Did you do something more?

**Comment by Royal-lobster** [comment]
Yeah. you have to change the font of your terminal to Powerline font. check out your terminal font settings. I figured that out after a day of installing it 😅️
