### ISSUE TITLE
Plugins not working as expected (docker, docker-compose, command-not-found)

### ISSUE THREAD

**Issue by Arkemlar** [ohmyzsh/ohmyzsh#8910]
Docker and docker-compose autocompletion not works. And command-not-found plugin doesn't work.
I added them to plugins:
`plugins=(git docker docker-compose command-not-found history-substring-search)`
but here only `git` and `history-substring-search`plugins work as expected. Docker-compose only added its aliases which I dont need really, but I need autocompletion. Also `command-not-found` seems not working as shell not started to give me any suggestions.

**Comment by Arkemlar** [comment]
I made it work by adding `autoload -Uz compinit && compinit -i` to my .zshrc file at the end. But it still seems missing documentation or bug because it is not mentioned in this repo wiki or readme. This command is found at https://docs.docker.com/compose/completion/ in the `Without oh-my-zsh shell` section.

**Comment by Arkemlar** [comment]
`Command-not-found` plugin is still doesn't work.

**Comment by MenkeTechnologies** [comment]
you should not be calling compinit in your zshrc.  OMZ already calls compinit in oh-my-zsh.sh.  make sure your plugins array is setup before sourcing this file and that any addittional compsys completion dirs are added to fpath

**Comment by Arkemlar** [comment]
Thats how it looks like in my .zshrc file (comments removed)
```bash
export ZSH="/Users/arkemlar/.oh-my-zsh"
ZSH_THEME="agnoster"
DEFAULT_USER=$(whoami)

plugins=(git docker docker-compose command-not-found zsh-autosuggestions zsh-syntax-highlighting history-substring-search)
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#626262"

source $ZSH/oh-my-zsh.sh

autoload -Uz compinit && compinit -i # hack to make autocomplete for docker and docker-compose working
```

**Comment by mcornella** [comment]
For completion plugins, see the FAQ: https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-have-enabled-a-completion-plugin-but-the-completion-doesnt-work.
For `command-not-found`, note that you still need to install a `command-not-found` package according to your operating system: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/command-not-found#supported-platforms.

**Comment by Arkemlar** [comment]
That helped, problem solved. But I wondering why the need of completion cache deletion is'n noted in main page when talking about plugins. All that written about plugin installation is that you need to add its name to plugins list in .zshrc.

**Comment by mcornella** [comment]
As the FAQ says, this isn't needed anymore in the latest version, so it doesn't make sense to document it in the README. Run `upgrade_oh_my_zsh` to get it.

**Comment by Arkemlar** [comment]
Then, seems like OMZ updated right after I downloaded it in previous week. But was reading master readme so got confused.
