### ISSUE TITLE
gcloud and zsh: correct 'ssh' to '.ssh' [nyae]?

### ISSUE THREAD

**Issue by metacogni** [ohmyzsh/ohmyzsh#8911]
**Describe the bug**
Recently moved to zsh from bash.
Using gcloud SDK to access remote systems on Google Cloud and you will always get:

gcloud compute ssh $username@$instance_name --zone us-central1-c --project $project
zsh: correct 'ssh' to '.ssh' [nyae]? n

Doesn't happen when aliased.

**To Reproduce**

Provision a GCP instance without OS Login and try to ssh with this:

gcloud compute ssh $username@$instance_name --zone us-central1-c --project $project

**Expected behavior**
Normal login without the prompt.

**Desktop (please complete the following information):**
 - OS / Distro: MacOS Catalina 10.15.4
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.7.1

**Additional context**
Default .zshrc. Added a couple of aliases and nothing more.

**Comment by mcornella** [comment]
Do you have `setopt correct_all` or `ENABLE_CORRECTION=true` in your zshrc file? If so, that might be the problem.

**Comment by metacogni** [comment]
> Do you have `setopt correct_all` or `ENABLE_CORRECTION=true` in your zshrc file? If so, that might be the problem.

Yes.

`ENABLE_CORRECTION=true` is enabled as one may sometimes in a haste mis-type a  command.

But even when that parameter is commented, it stops the behavior but you will still get:

zsh: command not found: $instance_name

My assumption (_probably wrong_) is that by default, it should have been able to recognize this as a valid command.

Once again, thanks for your input.

**Comment by mcornella** [comment]
`setopt correct_all` is a bit too smart for its own good sometimes, as it
tries to correct arguments, not only commands. `setopt correct` only
corrects commands, so it's probably what you want here.
