### ISSUE TITLE
Upgrade error "insufficient permission"

### ISSUE THREAD

**Issue by vrufine** [ohmyzsh/ohmyzsh#8915]
**Describe the bug**

When I try to update OhMyZsh, the same error occurs all the time:
```
error: insufficient permission for adding an object to repository database .git/objects
```

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Open your term using ohmyzsh
2. Run command 'upgrade_oh_my_zsh'
3. See error:
```
~
▶ upgrade_oh_my_zsh
Updating Oh My Zsh
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 66 (delta 38), reused 53 (delta 26), pack-reused 0
error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed
There was an error updating. Try again later?
```

**Expected behavior**
Upgrade ohmyzsh flawlessly.

**Screenshots and/or Recordings**
![Screen Shot 2020-05-11 at 5 55 36 PM](https://user-images.githubusercontent.com/6686490/81610934-a598c080-93b0-11ea-99d7-45f921ad4707.png)

**Desktop (please complete the following information):**
 - OS / Distro: macOS
 - Latest ohmyzsh Update?: No 😢
 - ZSH Version: zsh 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator iTerm2

**Additional context**
My .oh-my-zsh folder does not have uncommited or unstaged changes, its a clean repo.
![Screen Shot 2020-05-11 at 5 57 46 PM](https://user-images.githubusercontent.com/6686490/81611147-ee507980-93b0-11ea-9bae-63ce451beff3.png)

**Comment by mcornella** [comment]
Check that you're the owner of the `.git` folder inside `$ZSH`, and if not, do a `chown -R`.

**Comment by vrufine** [comment]
> Check that you're the owner of the `.git` folder inside `$ZSH`, and if not, do a `chown -R`.

Damn @mcornella 😍 

You got that right! ❤️ ❤️ 

1. I navigated to "~/.oh-my-zsh"
2. Ran "sudo chown -R <myuser> .git"
3. Then tryed to run "upgrade_oh_my_zsh"
4. 🎉 Tada! Worked like a charm 😄 

Thank you for the help!

I just don't understand why I had to do this after so many months using ohmyzsh and upgrading it with no problems at all 🤔 

Anyway! Thanks :-D
