### ISSUE TITLE
git diff alias with lock files excluded (package-lock.json)

### ISSUE THREAD

**Issue by TvrtkoM** [ohmyzsh/ohmyzsh#8923]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
git plugin

**Is your feature request related to a problem? Please describe.**
git diff shows me changes in package-lock.json

**Describe the solution you'd like**
I would like alias that e.g. gdnopl or gdnolock or similar that would exclude lock files from diff. It doesn't need to be just for npm (package-lock.json)

**Describe alternatives you've considered**
Did a quick grep in plugins directory, think no such alias exists

**Additional context**
If it's ok idea, I can submit a pull request

**Comment by mcornella** [comment]
According to [this StackOverflow answer](https://stackoverflow.com/a/39943727/5798232), since git 1.9 you can do that with
```zsh
git diff ':(exclude)package-lock.json'
```
If you want to be able to provide more arguments to the `git diff` command, you can turn it into a function:
```zsh
gdnolock() { git diff "$@" ":(exclude)package-lock.json"; }
```

**Comment by TvrtkoM** [comment]
i knew about that first feature, thanks for the function snippet.
the question is do we want this in git plugin or no?
already have it in my zshrc
