### ISSUE TITLE
current_gemset returns empty string

### ISSUE THREAD

**Issue by inopinatus** [ohmyzsh/ohmyzsh#8925]
**Describe the bug**

current_gemset returns empty string.

**To Reproduce**

Enable rbenv plugin on machine with rbenv and rbenv-gemset installed and working correctly, and attempt to use current_gemset. Version is fine:

    [22:41] (master) inopinatus@coltrane:~/src/flails$ echo $plugins
    git rbenv
    [22:41] (master) inopinatus@coltrane:~/src/flails$ rbenv version-name
    2.7.1
    [22:41] (master) inopinatus@coltrane:~/src/flails$ current_ruby
    2.7.1

but gemset is not (misparsed?):

    [22:41] (master) inopinatus@coltrane:~/src/flails$ rbenv gemset active
    flails global
    [22:42] (master) inopinatus@coltrane:~/src/flails$ current_gemset

    [22:42] (master) inopinatus@coltrane:~/src/flails$ 

**Expected behavior**

Should give current gemset in some fashion.

**Desktop**

 - OS / Distro: macOS
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.7.1
 - Terminal emulator: iTerm2

**Additional context**

Probably related to #4688.

**Comment by mcornella** [comment]
Does this work?
```zsh
echo "$(rbenv gemset active 2>/dev/null | sed -e ":a" -e '$ s/\n/+/gp;N;b a' | head -n1)"
```

**Comment by inopinatus** [comment]
@mcornella no - that gives the same empty output.

The problem doesn't seem to be stderr redirection; I think it's the sed expression. I'm unsure of the intention, but it _looks_ like it's trying to flatten multiline output into a single `+` separated line.

This is failing in two ways:

* Relying on a GNU-specific sed behaviour. When exiting due to input exhaustion on `N`, GNU sed will print the remaining pattern space; POSIX standard sed does not. The BSD sed on macOS is POSIX compliant.
* `rbenv gemset active` hasn't produced multiline output since 2012; since then it produces a space-separated list.

Back when it _was_ potentially working with multiline output, that `p` on the end of the substitute command could've caused GNU sed to print the pattern space twice. My guess is the oddball `head -n1` was meant as a workaround.

A less messy, and cross-platform alternative might've been

    sed -e :a -e '$ s/\n/+/g;$q;N;b a'

or not using sed at all, because the shell is perfectly capable of flattening multi-line output into one.

Since the format has changed, the point is largely now moot. There's maybe still an argument for flattening the output e.g. for compatibility, but the function could perhaps be simplified to something like:

    function current_gemset() {
        echo $(rbenv gemset active) | tr ' ' '+'
    }

**Comment by mcornella** [comment]
That sounds good. If that's all it takes, you can omit the `echo $()` syntax and just use
```zsh
function current_gemset() {
    rbenv gemset active | tr ' ' '+'

```

**Comment by mcornella** [comment]
Disregard the previous comment, the `echo $()` does put the output of `rbenv gemset active` in a single line, so my alternative isn't the same. Can you provide sample output of `current_gemset` and the equivalent output of `rbenv_prompt_info`?

**Comment by inopinatus** [comment]
This produces:

    [16:37] (master*) inopinatus@hendrix:~/src/gritpub$ rbenv gemset active
    gritpub global
    [16:37] (master*) inopinatus@hendrix:~/src/gritpub$ current_gemset
    gritpub+global
    [16:37] (master*) inopinatus@hendrix:~/src/gritpub$ rbenv_prompt_info
    (2.7.1@gritpub+global)

I can't speak for everyone but it's definitely what I'm after.

**Comment by mcornella** [comment]
Ok, I've been able to reproduce what the sed plugin does, and your proposed change doesn't do the same. I don't have `rbenv` installed, but let's suppose `rbenv gemset active` returns multiple lines
```
gemname1 global
gemname2 global
gritpub global
```

This is what the `sed` command changes it to:
```
gemname1 global+gemname2 global+gritpub global
gemname1 global+gemname2 global+gritpub global
```

Instead, we could use `tr` like in your solution, but using it to replace newlines:
```zsh
function current_gemset() {
    echo $(rbenv gemset active | tr '\n' '+' | head -c -1)
}
```
The `head` is to remove the last `+`.

I'm not sure if we should remove `global` from the output though, maybe using awk would get us better results:
```zsh
function current_gemset() {
    rbenv gemset active | awk '{ printf "%s%s", (NR > 1) ? "+" : "", $1 }'
}
```

**Comment by inopinatus** [comment]
> let's suppose rbenv gemset active returns multiple lines

It doesn’t.

**Comment by mcornella** [comment]
Ok that's fair. The command was added in #671, 9 years ago. Maybe at the time that made sense. My `tr` command would do the same as the current one while being portable (btw, this issue was [already reported in 2015](https://github.com/ohmyzsh/ohmyzsh/pull/671#commitcomment-14929643)), but if there never are multiple lines it doesn't make sense to keep it like that. I can't gage either way by looking at the [`rbenv-gemset-active` command source](https://github.com/jf/rbenv-gemset/blob/0b7b010ea7683518fe143c5fc085dce94c23492e/libexec/rbenv-gemset-active#L8-L15) though.

Also, what do you think about removing the `global` part of the output? Is that something important?

**Comment by inopinatus** [comment]
I'd be uneasy about suppressing `global`. This isn't (as sometimes incorrectly assumed) a reference to the underlying Ruby installation; even when empty, it's a real gemset and therefore significant. The name is purely by convention, and it's hard-coded into rbenv to append `global` by default. A typical use case for the global gemset is to isolate locally installed shared gems from the system location, by `echo global >~/.rbenv-gemsets`. The default behaviour can also be suppressed per directory by including `-global`, in which case it is omitted from the active list.

If it was simply a placeholder name for the standard library then we could save a few characters, but in practice it's a meaningful and variable element of the gem search path, so I'd counsel leaving it in.

My dry read through `rbenv-gemset-active` suggests that results are by always by unquoted echo, and therefore collapsed into one line by IFS splitting during shell parameter expansion. The best way to be sure is to ask, of course, so I've opened https://github.com/jf/rbenv-gemset/issues/92.

**Comment by mcornella** [comment]
Ok, so if nothing changes, I'll use the `tr` version (with attribution to you):
```zsh
function current_gemset() {
    echo $(rbenv gemset active 2>/dev/null | tr '\n' '+' | head -c -1)
}
```

**Comment by inopinatus** [comment]
Well .... since the output of `rbenv gemset active` is a single line, that `tr` is only translating the single newline on the end, making the combination of it and `head -c -1` redundant (and also broken on some platforms; negative args to head are a nonportable GNU extension). I've got

    function current_gemset() {
        echo $(rbenv gemset active) | tr ' ' '+'
    }

in my own dotfiles now and I'll personally be sticking with it, this does the defensive splitting expansion in the right place and only translates separated spaces. No attribution required.
