### ISSUE TITLE
robbyrussell: Possible clash of git and git-prompt plugin

### ISSUE THREAD

**Issue by realdadfish** [ohmyzsh/ohmyzsh#8936]
The current version of the git-prompt plugin defines these - amongst many other - environment variables:

```zsh
ZSH_THEME_GIT_PROMPT_PREFIX="("
ZSH_THEME_GIT_PROMPT_SUFFIX=")"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[green]%}%{✔%G%}"
...
```

while in the `robbyrussel` default theme (and many others) define these

```zsh
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
```

I suspect the environment variables from the theme stem from the default `git` plugin and sadly conflict with the namespace of the `git-prompt` plugin, insofar that the closing bracket is removed from the suffix if there are local changes in the workspace and also in case the workspace is clean, a single blue `)` is printed out, instead of the green checkmark as defined by the plugin.

**Comment by mcornella** [comment]
Those are kinda standard names so a new theme overrides the previous customisation. If you want to use `git-prompt`, you'd want to customise the theme to use it anyway. See [the guide here](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes).
