### ISSUE TITLE
custom $ZSH_COMPDUMP causing error message on init

### ISSUE THREAD

**Issue by katchy3132** [ohmyzsh/ohmyzsh#8938]
**Describe the bug**
On starting a new shell I get 
`rm: cannot remove '/home/<user>/.oh-my-zsh/cache': Is a directory`

**To Reproduce**
It seems to have something to do with my custom $ZSH_COMPDUMP
from my .zshrc :
`export ZSH_COMPDUMP="$ZSH/cache"`
commenting out that line causes the error message to disappear 

**Expected behavior**
no error message

**Desktop (please complete the following information):**
Latest Oh My Zsh updates . Multiple Debian based systems.

**Comment by mcornella** [comment]
`ZSH_COMPDUMP` must be the path to the zcompdump file, not the directory it's in.

**Comment by katchy3132** [comment]
Is this a recent change? I have had this option set for a long time and it seemed to work fine.

**Comment by mcornella** [comment]
It's always been the path to the file. Before it must have silently failed, now there's an error because we also use it to keep track of enabled plugins.
