### ISSUE TITLE
"is not a clone of .../ohmyzsh.git"

### ISSUE THREAD

**Issue by GiuseppeMon** [ohmyzsh/ohmyzsh#8950]
**Problem**:
when i try to upgrade zsh this is the message that i receive. I tried to clear yay cache or to wait thinking that was an error with some upgrade, but i'm receiving this problem from a month.
Maybe was changed something and i didn't noticed. Can someone help me? I love too much this shell!
![toGit](https://user-images.githubusercontent.com/46976701/82465627-ca331d80-9abf-11ea-8809-30d3ec96f083.png)

**Comment by larson-carter** [comment]
How did you initially install it?

**Comment by GiuseppeMon** [comment]
> How did you initially install it?

If i remember correctly from yay. I search for it and install it.

**Comment by larson-carter** [comment]
Ah so maybe this could be the issue?: https://forum.manjaro.org/t/oh-my-zsh-doesnt-work-after-installing-from-yay/76512

Do you have to wait for it to be updated via yay. You can't use our upgrade system. As you can tell I'm not familiar with yay.

**Comment by GiuseppeMon** [comment]
If i re-install it not from yay could that fix it?

**Comment by larson-carter** [comment]
I would uninstall it from yay. Then install it via our [Readme.md](https://github.com/ohmyzsh/ohmyzsh/blob/master/README.md)

**Comment by GiuseppeMon** [comment]
> I would uninstall it from yay. Then install it via our [Readme.md](https://github.com/ohmyzsh/ohmyzsh/blob/master/README.md)

Do i have to customize it again if i did that?

**Comment by larson-carter** [comment]
You can just make a backup of your .zshrc file? Then paste the contents into your new install file.

**Comment by GiuseppeMon** [comment]
I'll try it, ty!
