### ISSUE TITLE
Avit Tab Completion Color Issues

### ISSUE THREAD

**Issue by 6etacat** [ohmyzsh/ohmyzsh#8952]
**Describe the bug**
When using the avit theme, triggering tab completion options will render the already input characters to be grey (prompt triangle color, color 8) while newer characters are white (normal text color, color 16). This does not happen in other themes like the default robbyrussell theme. 

**To Reproduce**
Steps to reproduce the behavior, for example:
Use a color scheme that has a contrasty different color 8 and color 16. 
Type "ec" and then tab, you should see a list of options, and also your previously typed text changes color. If you type on, you will go back to the original default color (color 16). 

**Expected behavior**
The colors should be consistent. 

**Screenshots and/or Recordings**
![Screenshot from 2020-05-20 19-26-59](https://user-images.githubusercontent.com/15188392/82507359-01a9c600-9ad0-11ea-9e31-23205262a930.png)

**Desktop (please complete the following information):**
 - OS / Distro: Manjaro
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: gnome-terminal

**Additional context**
This may be the theme forgetting to add "\e[39m" or "\e[0m" to reset colors in the end.

**Comment by mcornella** [comment]
Can you check if this patch fixes it?
```patch
diff --git a/themes/avit.zsh-theme b/themes/avit.zsh-theme
index 0261f0ff..05b3fb21 100644
--- a/themes/avit.zsh-theme
+++ b/themes/avit.zsh-theme
@@ -7,7 +7,7 @@ typeset +H _hist_no="%{$fg[grey]%}%h%{$reset_color%}"
 
 PROMPT='
 $(_user_host)${_current_dir} $(git_prompt_info) $(ruby_prompt_info)
-%{%(!.%F{red}.%F{white})%}▶%{$resetcolor%} '
+%{%(!.%F{red}.%F{white})%}▶%{$reset_color%} '
 
 PROMPT2='%{%(!.%F{red}.%F{white})%}◀%{$reset_color%} '
```

**Comment by 6etacat** [comment]
Ran `upgrade_oh_my_zsh`, still encountering this problem. Any way I can help debug? Not super familiar with shell prompts though, tbh.

**Comment by mcornella** [comment]
Hmm do you have zsh-autosuggestions or other plugins that might change the prompt line?

**Comment by 6etacat** [comment]
I do have autosuggestions. I'll try turning it off.

**Comment by 6etacat** [comment]
Turning off zsh-autosuggestions did not help.
