### ISSUE TITLE
How to add custom alias for flutter?

### ISSUE THREAD

**Issue by vinothvino42** [ohmyzsh/ohmyzsh#8953]
I'm interested to add custom alias for flutter in `flutter.plugin.zsh` for generating files and releasing the apk.

```
alias flbr = "flutter pub run build_runner build"
alias flbar = "flutter build apk --release"
```

How can I add one?

**Comment by mcornella** [comment]
The equal sign in the alias needs to not have spaces around it:
```zsh
alias flbr="flutter pub run build_runner build"
alias flbar="flutter build apk --release"
```
Put these in your zshrc file so that you don't get merge conflicts when updating OMZ.

**Comment by vinothvino42** [comment]
Yeah it's working. Thank you so much!
