### ISSUE TITLE
zsh: command not found (despite setting PATH)

### ISSUE THREAD

**Issue by RainmakerRaw** [ohmyzsh/ohmyzsh#8955]
I have zsh (installed via Brew) and ohmyzsh (installed from shell as per the website) on my MacBook Pro, which runs macOS Catalina. I also have installed iproute2mac via Brew. In my .zshrc I have
```
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
```
which matches the entries in my .bash_profile. I also spotted the first commented entry in .zshrc and uncommented it: 

`export PATH=$HOME/bin:/usr/local/bin:$PATH`

When I try to use iproute2mac (for example by issuing `ip a`), in Bash the program runs and I get the output requested by the command. In ZSH I get 

`zsh: command not found: ip.py`

I've confirmed that /usr/local/bin/ip exists and indeed, as I said, it executes fine in bash. Could anyone please point me in the right direction? Is it perhaps an issue with calling Python (also installed via Brew) rather than (ohmy)zsh directly? Or something else? Sorry if this isn't the right place to ask but since it only happens on zsh where my beloved ohmyzsh lives, it seemed the logical place to start.

**Comment by mcornella** [comment]
Try `set -xv; ip a; set +xv` and post the output.

**Comment by RainmakerRaw** [comment]
```
+-zsh:1> ip.py a
zsh: command not found: ip.py
+-zsh:1> set +xv
```

**Comment by RainmakerRaw** [comment]
And the same command in bash, just to show it works:
```

bash-5.0$ ip a
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
        inet 127.0.0.1/8 lo0
        inet6 ::1/128
        inet6 fe80::1/64 scopeid 0x1
```
(etc)...

**Comment by mcornella** [comment]
Try `ls -l $commands[ip]`

**Comment by RainmakerRaw** [comment]
Ah.

`lrwxr-xr-x  1 myusername  admin  34 20 May 03:04 /usr/local/bin/ip -> ../Cellar/iproute2mac/1.2.3/bin/ip
`
So it's a symlink. I tried adding /usr/local/Cellar to path but it wasn't having that either. I'm assuming from this little revelation you know the answer, however? :)  Things were much more straightforward when I was running MacPorts. It used a single logical directory instead of doing funky things with links and aliases like this.

**Comment by RainmakerRaw** [comment]
It has been set as an alias (not by me, but by Brew), however it points to a location that does work if I run it manually - just not by name. Like so:

```
user@Users-MacBook-Pro ~ which -a ip        
ip: aliased to ip.py
/usr/local/bin/ip
/usr/local/bin/ip
 user@Users-MacBook-Pro ~ ip a
zsh: command not found: ip.py
 ✘ user@Users-MacBook-Pro ~ /usr/local/bin/ip a                         
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
        inet 127.0.0.1/8 lo0
        inet6 ::1/128
        inet6 fe80::1/64 scopeid 0x1
(snipped for privacy)
 user@Users-MacBook-Pro ~
``` 
While I greatly appreciate your assistance, I think it'd be easier all round to go back to MacPorts where they don't play silly directory/alias games like this lol.

**Comment by mcornella** [comment]
Homebrew doesn't actually set aliases, you must have `alias ip=ip.py` in one of your rc files (zshrc, zshenv, .profile, etc...). Remove that and it'll work again (you can test with `unalias ip`).
