### ISSUE TITLE
Add .nvmrc loading to nvm plugin

### ISSUE THREAD

**Issue by endquote** [ohmyzsh/ohmyzsh#8959]
Can we add [this bit](https://github.com/nvm-sh/nvm#zsh) to the [nvm plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/nvm), to auto-load `.nvmrc` files?

I added it to my `.zshrc` file with the `nvm` plugin enabled, and it seems to work correctly.

I could do a PR, but wanted to make sure I wasn't missing something.

@nicholasjpaterno

**Comment by nicholasjpaterno** [comment]
@endquote I'm not actually a maintainer of ohmyzsh, sorry for the confusion. Definitely make a PR! :smile:

**Comment by endquote** [comment]
@nicholasjpaterno Gotcha, I just tagged you since it looked like you did the `nvm` plugin.

**Comment by endquote** [comment]
Actually it looks like @drGrove did it already in #5782 in 2017, but it was never merged.
