### ISSUE TITLE
"jira branch" does not take into account duplicated JIRA_PREFIX

### ISSUE THREAD

**Issue by JoannaFalkowska** [ohmyzsh/ohmyzsh#8963]
**Describe the bug**
When on branch `ABC-2137__my-feature`, if `$JIRA_PREFIX` is set to `ABC-`, running `jira branch` opens `{my-jira-url}/ABC-ABC-2137` instead of `{my-jira-url}/ABC-2137`.

That makes it impossible to make use of `$JIRA_PREFIX="ABC-"` for other commands, if you want to be able to run `jira branch` and have the correct page open.

(Note that `ABC-2137__my-feature` branch name format is the one recognized by GitHub/Jira integration.)

**To Reproduce**
1. Enable `jira` plugin
2. Set `$JIRA_PREFIX="ABC-"`
3. Check out to branch starting with `ABC-`, e.g. `ABC-2137__my-feature`
4. Run `jira branch`
5. `{my-jira-url}/ABC-ABC-2137` url is opened

**Expected behavior**
`{my-jira-url}/ABC-2137` url is opened (duplicated prefix is recognized and removed)

**Desktop (please complete the following information):**
 - ZSH Version: zsh 5.3 (x86_64-apple-darwin18.0)

**Comment by robbyrussell** [comment]
@JoannaFalkowska Sorry for the delay but I believe we might have fixed this with #8799

Can you confirm on your end?
