### ISSUE TITLE
Getting error `env: ‘zsh’: Permission denied` when using Windows 10 WSL2.

### ISSUE THREAD

**Issue by mastrauckas** [ohmyzsh/ohmyzsh#8964]
I am getting `env: ‘zsh’: Permission denied` when using `oh my zsh` .  The problem occurs when using WSL2 on Ubuntu 20.04 distro, installing `zsh` with `brew` and installing 'oh my zsh`.

**To Reproduce**
Here is the order of what I'm doing that is causing the issue:
1. install `zsh` using `apt-get`.  
2. install `oh-my-zsh`.
3. Install `zsh` using `brew`.
4. Switch default shell from `apt-get` version of  `zsh`  to `brew` version of `zsh`.  Changing it by editing`/etc/passwd`.
5. Start a new terminal session to make sure everything works, which it does.
6. use `echo $SHELL` to make sure it's using the `brew` version of `zsh`, which it is.
7. Remove `apt-get` version of `zsh`.
8. Start a new terminal session to make sure everything is working.  I get  `env: ‘zsh’: Permission denied`
9. Use  `echo $SHELL` to see what shell is being used, which is still the `brew` version of `zsh`.
10. Install `apt-get` version of `zsh` again. 
11.  Start a new terminal session,   `env: ‘zsh’: Permission denied` goes away.
12.  Use  `echo $SHELL` to see what shell is being used, which is still the `brew` version of `zsh`.

**Expected behavior**
So if `apt-get` version of `zsh` is installed, everything works.  Even if it's not the shell being used.  The expected behavior is not getting `env: ‘zsh’: Permission denied`.

**Desktop (please complete the following information):**
 - Windows 10 Version 2004 using WSL2.  WS2 is using Distro Ubuntu 20.04
 - Latest ohmyzsh Update?:  YES
 - ZSH Version:
     `Brew` version of zsh:     zsh 5.8 (x86_64-pc-linux-gnu)
     `apt-get` version of zsh: zsh 5.8 (x86_64-ubuntu-linux-gnu)
 - Terminal emulator [e.g. iTerm2]: Windows Terminal v1.0.1401.0

**Additional context**
So I start to dig into why I'm getting `env: ‘zsh’: Permission denied`.  It appears line `env ZSH=$ZSH ZSH_CACHE_DIR=$ZSH_CACHE_DIR DISABLE_UPDATE_PROMPT=$DISABLE_UPDATE_PROMPT zsh -f $ZSH/tools/check_for_upgrade.sh` in file  `~/.oh-my-zsh/oh-my-zsh.sh` is cuasing the error.

So now I try running  `zsh -f $ZSH/tools/check_for_upgrade.sh` and I get error `_update_zsh_update:1: permission denied: /.zsh-update`

Thanks,
   Michael

**Comment by mcornella** [comment]
If you comment that part of the `oh-my-zsh.sh` file, does it work? What does `which -a zsh` show when that happens?

**Comment by mastrauckas** [comment]
> If you comment that part of the `oh-my-zsh.sh` file, does it work? What does `which -a zsh` show when that happens?

which command with `apt-get` `zsh` installed
```
 ~ $  which -a zsh
/home/linuxbrew/.linuxbrew/bin/zsh
/usr/bin/zsh
/bin/zsh
/home/linuxbrew/.linuxbrew/bin/zsh
```

`which` command without `apt-get` `zsh` installed
``` 
~ $ which -a zsh
/home/linuxbrew/.linuxbrew/bin/zsh
/home/linuxbrew/.linuxbrew/bin/zsh
```

if I comment out
```
env ZSH=$ZSH ZSH_CACHE_DIR=$ZSH_CACHE_DIR DISABLE_UPDATE_PROMPT=$DISABLE_UPDATE_PROMPT zsh -f $ZSH/tools/check_for_upgrade.sh
```
It works

If I replace
```
env ZSH=$ZSH ZSH_CACHE_DIR=$ZSH_CACHE_DIR DISABLE_UPDATE_PROMPT=$DISABLE_UPDATE_PROMPT zsh -f $ZSH/tools/check_for_upgrade.sh
```
with
```
env ZSH=$ZSH ZSH_CACHE_DIR=$ZSH_CACHE_DIR DISABLE_UPDATE_PROMPT=$DISABLE_UPDATE_PROMPT ""
```
I get `env: ‘#zsh’: Permission denied`

**Comment by mcornella** [comment]
It seems you have a broken `$PATH` because the linuxbrew directory appears twice. Maybe try fixing that and the problem will solve itself, though I don't think that's likely.

**Comment by mcornella** [comment]
You might also try to delete `env` from the offending line:
```diff
-env ZSH=$ZSH ZSH_CACHE_DIR=$ZSH_CACHE_DIR DISABLE_UPDATE_PROMPT=$DISABLE_UPDATE_PROMPT zsh -f $ZSH/tools/check_for_upgrade.sh
+ZSH=$ZSH ZSH_CACHE_DIR=$ZSH_CACHE_DIR DISABLE_UPDATE_PROMPT=$DISABLE_UPDATE_PROMPT zsh -f $ZSH/tools/check_for_upgrade.sh
```

**Comment by mastrauckas** [comment]
Now instead of 
```
env: ‘#zsh’: Permission denied
```
I get
```
/home/michael/.oh-my-zsh/oh-my-zsh.sh:15: command not found: zsh
```

**Comment by mcornella** [comment]
Then the problem must be that the linuxbrew path is not added to `$PATH` at the moment OMZ is sourced. Put the PATH modification at the top of the zshrc file and it should work without changes.

**Comment by mastrauckas** [comment]
> Then the problem must be that the linuxbrew path is not added to `$PATH` at the moment OMZ is sourced. Put the PATH modification at the top of the zshrc file and it should work without changes.

You're correct.  I sourced it before `source $ZSH/oh-my-zsh.sh` and now everything is working.  

Thanks,
   Michael
