### ISSUE TITLE
ohmyzsh plugins cloudapp error: unexpected token at 'HTTP Digest: Access denied. (JSON::ParserError)

### ISSUE THREAD

**Issue by alemens** [ohmyzsh/ohmyzsh#8966]
**Bug description**
I take error `unexpected token at 'HTTP Digest: Access denied. (JSON::ParserError)` while I am trying to upload an image to cloudapp by using cloudapp ohmyzsh plugin 

**To Reproduce**
1. `sudo gem install cloudapp_api`
2. Enable this plugin ['cloudapp'](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/cloudapp)
3. set your CloudApp credentials in ~/.cloudapp as a simple text file like below:
```
email
password
```
4. Run command `cloudapp <filename>`
5. See error

**Expected behavior**
Upload `<filename>` to CloudApp

**Desktop env**
 - OS => macOS
 - Latest ohmyzsh
 - ZSH version => zsh 5.7.1 (x86_64-apple-darwin19.0) 
 - Terminal version => 2.10 (433)

**Comment by mcornella** [comment]
Looks to me like CloudApp changed some APIs and now the cloudapp_api gem is obsolete (it hasn't been maintained since 2015). See https://github.com/cloudapp/api/commit/d8363e2cb8d088c13f3ea7a72f439bc5845f9a37.

**Comment by alemens** [comment]
Oh yes I see the API is no longer supported, thanks for enlightening me

So why such deprecate it is still appearing as official plugins?

**Comment by mcornella** [comment]
The plugin will be deprecated when I get confirmation that the API won't ever work again: https://github.com/cloudapp/api/commit/d8363e2cb8d088c13f3ea7a72f439bc5845f9a37#commitcomment-39470912.

**Comment by larson-carter** [comment]
@mcornella In their readme - "NOTE: The API is no longer supported"

I'm assuming that is deprecated, and that it is safe to say that it won't ever work again!

**Comment by mcornella** [comment]
Alright, I got official confirmation that the API is gone for good. I'll deprecate the plugin.
