### ISSUE TITLE
`docker container run --g[TAB]` no `--gpus` completion for `zsh`

### ISSUE THREAD

**Issue by yantaozhao** [ohmyzsh/ohmyzsh#8972]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
The name of the plugin that you would like us to improve: `docker`

**Is your feature request related to a problem? Please describe.**
In `zsh` shell prompt, input `docker container run --g[TAB][TAB]`, there's no `--gpus` completion shows in the candidates.

**Describe the solution you'd like**
the `docker` plugin [in ohmyzsh](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/docker) comes from [`docker-cli`](https://github.com/docker/cli/tree/master/contrib/completion/zsh) , and the upstreaming `docker cli` seems not work properly with `docker container run --gpus ...`  completion too. I've already file an [issue](https://github.com/docker/cli/issues/2549) in the docker cli official repo.
Perhaps it should update the docker cli official repo, and then sync the ohmyzsh docker plugin.

**Comment by mcornella** [comment]
I'll close this until there's a fix upstream.

**Comment by yantaozhao** [comment]
> I'll close this until there's a fix upstream.

the upstream has been updated.

**Comment by mcornella** [comment]
Updated in #9470.
