### ISSUE TITLE
Not installing on Win10 with cygwin,gitbash or other

### ISSUE THREAD

**Issue by MichaelsTestchamber** [ohmyzsh/ohmyzsh#8973]
Getting, "Zsh not installed, please install zsh first.", when trying to install zsh with the curl command: $ sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

This happens no matter what terminal i try and use in win10.

![image](https://user-images.githubusercontent.com/35957164/83240669-05a5aa00-a19a-11ea-8293-b6e698982c78.png)

**Comment by mcornella** [comment]
You need to install `zsh` first.

**Comment by MichaelsTestchamber** [comment]
I was trying to install zsh when it said the following!

This is directly from the webpage!

Install oh-my-zsh now
Oh My Zsh is installed by running one of the following commands in your terminal. You can install this via the command-line with either curl or wget.

Install oh-my-zsh via curl Install oh-my-zsh via wget
$ sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

**Comment by zebapy** [comment]
@mcornella I think you skipped over what they said. I'm getting the same problem. 

Attemping to use `sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"` on WSL and it returns the error
`Zsh is not installed. Please install zsh first`

The command is to install zsh.... unless we're both gravely mistaken.

**Comment by mcornella** [comment]
The `which` command found no zsh binary, that means it's not installed or not in `$PATH`. The OMZ wiki has a section for how to install zsh in a number of systems.

**Comment by MichaelsTestchamber** [comment]
I thought i had installed zsh, i had not, or at least cygwin did not install correctly. There is zsh and then there is oh my zsh which is layered on top of zsh.
Problem could also be that zsh is not in your windows PATH, make sure to copy zsh's path to the system variables.

**Comment by mcornella** [comment]
Zsh is the shell, it's not the same as OMZ.

**Comment by MichaelsTestchamber** [comment]
And make sure to restart shell after adding path.
