### ISSUE TITLE
How to insert new line (\n) in PROMPT? Bug?

### ISSUE THREAD

**Issue by ProgrammingLife** [ohmyzsh/ohmyzsh#8979]
My attempt is: `PROMPT='$(echo "\n\n")%i » '` 
Why does it not work?
But "works" following command: `PROMPT='$(echo "\r\n\r\n")%i » '`

Why Windows newline works in Linux? Works but not almost work. It doubles a first letter of my input command if I press tab, for example here: `ls <tab>`
You can try this inserting my PROMPT-line in your terminal and type `ls <tab>`.
I've also tried this with `print "\n\n"` (doesn't work) and `printf "\r\n\r\n"` - works with the same bug.

How to properly insert newline? I've been trying to do it for about 5 hours. It just blows my mind.

ENV:
- 
- **Linux Mint 19.1** 
- **gnome-terminal, tilix**
- **.oh-my-zsh** is up to date
- **zsh**: 5.4.2 (x86_64-ubuntu-linux-gnu)

**Comment by mcornella** [comment]
You can span multiple lines inside a quoted string:
```zsh
PROMPT='

%i » '
```
Another option is using `$''` and `\n` (btw, `\r` is never used in a UNIX environment). The `$''` construct converts the printf escape codes inside it to its equivalent in ASCII, so if you do
```zsh
PROMPT=$'\n\n%i » '
```
You'll get the equivalent newline characters inside it.
