### ISSUE TITLE
How to fix - It's Showing additional line prompt !!!

### ISSUE THREAD

**Issue by dlj2019** [ohmyzsh/ohmyzsh#8982]
Hi folks ... the only issue i am facing is with 2 lines prompt instead 1.

Do you know how i would be able to fix this ?

Thanks in advance !

![Additional line](https://user-images.githubusercontent.com/30886694/83476119-d0c97980-a45d-11ea-97eb-b29b921301bd.png)

**Comment by mcornella** [comment]
Please post your zshrc file.

**Comment by dlj2019** [comment]
> Please post your zshrc file.

Sure !  here we go ...
[zshrc.txt](https://github.com/ohmyzsh/ohmyzsh/files/4717941/zshrc.txt)
