### ISSUE TITLE
Unable to install through curl

### ISSUE THREAD

**Issue by maliangm** [ohmyzsh/ohmyzsh#8990]
Hi Team,
When I tried to install using the curl approach:
```sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"```
I got the following error:
```curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused```

I would appreciate it a lot if any one can give me a solution.
Thanks!

**Comment by mcornella** [comment]
This is a GFW (Great Firewall of China) issue. Please look for proxy solutions.

**Comment by winkerwinker** [comment]
if you use proxy software like shadowSocks . you  should config proxy in your terminal .

**Comment by winkerwinker** [comment]
if you use proxy software like shadowSocks. you should configure the proxy in your terminal too.

**Comment by mcornella** [comment]
Try to download the installer from this gitee.com mirror I've created:
```
sh -c "$(curl -fsSL https://gitee.com/mcornella/ohmyzsh/raw/master/tools/install.sh)"
```

**Comment by StephanS13** [comment]
> Try to download the installer from this gitee.com mirror I've created:
> 
> ```
> sh -c "$(curl -fsSL https://gitee.com/mcornella/ohmyzsh/raw/master/tools/install.sh)"
> ```

Thanks a lot! You rock!

**Comment by CHANCYstone** [comment]
man! what can i say
