### ISSUE TITLE
I have a problem and need help

### ISSUE THREAD

**Issue by SamoZ** [ohmyzsh/ohmyzsh#8994]
**Describe the bug**
The git is not what I want:

![Jun-04-2020 10-22-45](https://user-images.githubusercontent.com/25240164/83707785-69721c00-a64d-11ea-93a4-44e61402156d.gif)

I hope it looks like the following. What should I do？

<img width="371" alt="871A100EA7343D09310C62FB1A41AEFE" src="https://user-images.githubusercontent.com/25240164/83707797-7131c080-a64d-11ea-91b5-e53aead5b383.png">

**Comment by SamoZ** [comment]
![Jun-04-2020 10-22-45](https://user-images.githubusercontent.com/25240164/83707891-ab9b5d80-a64d-11ea-8c4f-2623a144a72f.gif)

**Comment by mcornella** [comment]
See https://stackoverflow.com/a/48370253/5798232.
