### ISSUE TITLE
Path shows "wd" points instead of paths

### ISSUE THREAD

**Issue by pro-sumer** [ohmyzsh/ohmyzsh#8996]
After a recent update my prompt shows the wd "point" instead of the "path" on macOS Catalina (10.15.4).

Example:

```
wd add dl ~/Downloads
wd dl
```

* Expected path (as a few days ago) in prompt: `~/Downloads`
* Actual path (now) in prompt: `~dl`

It does not seem to be a [Powerlevel10k issue](https://github.com/romkatv/powerlevel10k/issues/798) and its author explained me that I now have "named directories".

The behaviour is still as I expected on my old Mac (also running macOS Catalina 10.15.4, but with older versions of both Oh My Zsh and Powerlevel10k)

What changed? How can I get the old behaviour back?

**Comment by pro-sumer** [comment]
Hm, [looks like](https://github.com/mfaerevaag/wd/search?q=WD_SKIP_EXPORT&unscoped_q=WD_SKIP_EXPORT) I need to set `WD_SKIP_EXPORT` (to any value, to make it defined)?

**Comment by pro-sumer** [comment]
Ah, yes: https://github.com/mfaerevaag/wd/pull/64

**Comment by benjezzy** [comment]
@pro-sumer Having the same issue are you, did you manage to resolve it? If so, how? Thanks!

**Comment by mcornella** [comment]
From what I understood, it seems just adding `WD_SKIP_EXPORT=1` to your zshrc file will be enough.

**Comment by pro-sumer** [comment]
Yes, `WD_SKIP_EXPORT` needs to be set.
