### ISSUE TITLE
De-duplicate chucknorris quotes

### ISSUE THREAD

**Issue by ddugovic** [ohmyzsh/ohmyzsh#8998]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
chucknorris

**Is your feature request related to a problem? Please describe.**
Quote about 45-11 seems to appear more frequently than other quotes.

**Describe the solution you'd like**
De-duplicate chucknorris quotes.

**Describe alternatives you've considered**
* Remove 45-11 quote altogether
* Have some way to load quotes from OS-bundled fortune

**Additional context**
https://github.com/ohmyzsh/ohmyzsh/blob/547a6ce260362b06e86a9c366dc29984c0954124/plugins/chucknorris/fortunes/chucknorris#L93
https://github.com/ohmyzsh/ohmyzsh/blob/547a6ce260362b06e86a9c366dc29984c0954124/plugins/chucknorris/fortunes/chucknorris#L223
https://github.com/ohmyzsh/ohmyzsh/blob/547a6ce260362b06e86a9c366dc29984c0954124/plugins/chucknorris/fortunes/chucknorris#L353
etc.

**Comment by mcornella** [comment]
Thanks for the report!
