### ISSUE TITLE
kubectl autocompletion doesn't apply namespace context

### ISSUE THREAD

**Issue by datenzar** [ohmyzsh/ohmyzsh#8999]
**Describe the bug**
When I want to use autocompletion in kubectl, the suggested results are taken from the current context instead of the namespace. E.g. when current namespace is set to `default` and I type `kubectl get pods -n development `, after hitting tab I only get the results of `default` but not `development`.  

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'kubectl'
2. Run command try the autocomplete command 'kubectl get pods -n development'
3. See results from `default` namespace

**Expected behavior**
Suggested result should be the pods in `development` namespace

**Screenshots and/or Recordings**
n/a

**Desktop (please complete the following information):**
 - OS / Distro: Manjaro Linux
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: zsh 5.8 (x86_64-pc-linux-gnu)
 - Terminal emulator Terminator

**Additional context**
n/a

**Comment by naveen-kumar-r** [comment]
I tried reproducing the issue without luck. Setting current context to `default` and able to view pods from other namespace `kube-system`. Can you please add additional details or try clearing completion cache.

![Screenshot from 2020-09-26 21-13-59](https://user-images.githubusercontent.com/28789859/94345132-74f4b300-0041-11eb-9793-55f6af2b7493.png)

**Comment by mcornella** [comment]
Can you provide a trace of the completion function? You can do that by writing the command you want to complete, then pressing <kbd>CTRL</kbd>+<kbd>X</kbd> followed by <kbd>?</kbd>. Afterwards please post the generated file.

**Comment by datenzar** [comment]
Thx for the suggestion @mcornella, here's the file
[zsh18969kubectl5.zip](https://github.com/ohmyzsh/ohmyzsh/files/5361533/zsh18969kubectl5.zip)

**Comment by mcornella** [comment]
Sorry for the late respone, but this was submitted in #10581 and we kinda got the culprit, see https://github.com/ohmyzsh/ohmyzsh/issues/10581#issuecomment-1016768252.
