### ISSUE TITLE
Remove extra whitespace after kubectl folder autocompletion

### ISSUE THREAD

**Issue by datenzar** [ohmyzsh/ohmyzsh#9000]
When using autocompletion in kubectl and try to specify a file in a folder, the autocompletion allways adds a whitespace after completing a folder.

E.g. I want to apply a yml file located at `test/deployment.yml`. After entering `kubectl apply -f tes` and hitting `TAB` the autocompletion gives me `kubectl apply -f test/ ` instead of `kubectl apply -f test/`. Hence in order to continue, I always need to remove the whitespace first. In all other cases I have observed so far, the autocomplete doesn't add the whitespace character. I'm not sure if this is a bug or intentionally built that way. If so, is there a way to configure the extra whitespace-creation for this plugin?

Thx

**Comment by robbyrussell** [comment]
Hey there, I'm doing a bit of housekeeping on the project. Thanks for raising this issue—we always love a good edge case! 😄

However, it's not gathering much community interest, so I'm going to close it for now. Don't let this discourage you! We're all for hearing about the weird things. We can't commit to spending too much time tracking each weird thing down ourselves.
