### ISSUE TITLE
Installer does not respect $ZDOTDIR

### ISSUE THREAD

**Issue by marlonrichert** [ohmyzsh/ohmyzsh#9001]
**Describe the bug**
`tools/install.sh` installs into `~` even when `$ZDOTDIR` is set.

**To Reproduce**
1. `cd "$(mktemp -d)"`
2. `ZDOTDIR=$PWD zsh -d`
3. `sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`

**Expected behavior**
OMZ installs into `$ZDOTDIR`.

**Actual behavior**
OMZ installs into `~`.

**Desktop (please complete the following information):**
 - OS / Distro: macOS
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: Apple Terminal

**Comment by CouldBeThis** [comment]
Hi, is this forthcoming or should I just plan to work around it? 

thanks for omz I <3 it either way
