### ISSUE TITLE
wd warp showing wd_export_static_named_directories:hash:invalid character in directory name

### ISSUE THREAD

**Issue by xxKeith20xx** [ohmyzsh/ohmyzsh#9002]
After updating with https://github.com/ohmyzsh/ohmyzsh/commit/82f02e80a669d099d79a531cf8fb6a0e34d4478c , I get this error on wd list:

```
wd list
wd_export_static_named_directories:hash:4: invalid character in directory name: ^[[01;31m^[[Kwarp
wd_export_static_named_directories:hash:4: invalid character in directory name: ^[[01;31m^[[Karchivedbackups
wd_export_static_named_directories:hash:4: invalid character in directory name: ^[[01;31m^[[Kaudio
wd_export_static_named_directories:hash:4: invalid character in directory name: ^[[01;31m^[[Kbooks
wd_export_static_named_directories:hash:4: invalid character in directory name: ^[[01;31m^[[Kgitroot
wd_export_static_named_directories:hash:4: invalid character in directory name: ^[[01;31m^[[Kgitcoderepo
[...]
```

It then shows my wd list below the error. 

wd clean says `No warp points to clean, carry on!`

 - OS / Distro: debian testing
 - Latest ohmyzsh Update?:  yes
 - ZSH Version: zsh 5.8 (x86_64-debian-linux-gnu)
 - Terminal emulator: iterm2

**Comment by mcornella** [comment]
@mfaerevaag any ideas?

**Comment by xxKeith20xx** [comment]
I was trying to see why this was failing in my one install and not another. I see I do have ~ and - in the .warprc but this exists on the working install too. Running wd --debug crashes the terminal. When I output to a file / pager I just see the same `invalid character in directory name:`.

**Comment by xxKeith20xx** [comment]
Turns out it's due to a function/alias in my .zshrc conflicting with wd

:)

**Comment by mcornella** [comment]
What was the function/alias in question, just for curiosity's sake?

**Comment by xxKeith20xx** [comment]
Seems it was this one:

```
alias grep="grep -i --color=always"
```

But the real reason may be due to some overlapping alias/function/plugin functionality I think.

**Comment by mcornella** [comment]
That's exactly the problem. `wd` should prefix `grep` calls with `command` to bypass aliases. That said, `--color=always` is a bad setting and will cause other problems, use `--color=auto` instead so that piped grep calls don't add coloring sequences.

**Comment by xxKeith20xx** [comment]
oh that's good to know - thanks!
