### ISSUE TITLE
tab completion broken after parameter with two dashes

### ISSUE THREAD

**Issue by carlocaione** [ohmyzsh/ohmyzsh#9003]
Ok, this is a weird issue. I'm not even sure if the problem here is ZSH or not.

For the sake of example let's say that I want to do something like this (the flag `--width` I'm using is not important, the important thing is that it has two dashes):
```
$ ls --width=1 <TAB>
```
After pressing `<TAB>` I get the usual list of files and directories. So far so good.

I know want to do something similar using `lsd` (from https://github.com/Peltoche/lsd). For example:
```
$ lsd --tree --depth=1 <TAB>
```
What happens is that ZSH doesn't present the usual list of files and directories but instead it just add one more dash and nothing else:
```
lsd --tree --depth=1 -
```
Even more weirdly this is not reproducible with all the flags. For example this is working correctly:
```
lsd --tree --size=short <TAB>
```
Any idea what's the problem here?

**Comment by mcornella** [comment]
This is an issue with `lsd`'s completion. File an issue there and be sure to post the tree of the directory in which you're trying to complete that.
