### ISSUE TITLE
"git clone of oh-my-zsh repo failed" When installing 

### ISSUE THREAD

**Issue by Suraj-Ram** [ohmyzsh/ohmyzsh#9004]
I tried installing Oh My Zsh on a fresh install of WSL 2 running Ubuntu 20.04 LTS

After I installed zsh using apt-get, I tried to install Oh My Zsh using curl and was presented with the below error.

```
suraj@WIN-PC-456:~$ sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
Cloning Oh My Zsh...
Cloning into '/home/suraj/.oh-my-zsh'...
fatal: unable to access 'https://github.com/ohmyzsh/ohmyzsh.git/': gnutls_handshake() failed: Error in the pull function.
Error: git clone of oh-my-zsh repo failed
```

**Comment by mcornella** [comment]
Try https://stackoverflow.com/questions/52379234/gnutls-handshake-failed-error-in-the-pull-function

**Comment by royninja** [comment]
Try Executing
 `$ sudo apt-get -y install build-essential nghttp2 libnghttp2-dev libssl-dev`

**Comment by Sofar1994** [comment]
DNS pollution

**Comment by gezichenshan** [comment]
> DNS pollution

you are right
