### ISSUE TITLE
per-directory-history plugin incorrectly uses global history in newly created shell

### ISSUE THREAD

**Issue by smarsching** [ohmyzsh/ohmyzsh#9007]
**Describe the bug**
The per-directory-history plugin does not use the per-directory history immediately after creating a new shell. The per-directory history is only used when changing to global and back to per-directory mode (by pressing Ctrl+G twice) or when changing directories (e.g. `cd .`).

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable the per-directory-history plugin.
2. Create a new directory for the experiments (`/tmp/test` in this example).
3. Change to the test directory (`cd /tmp/test`).
4. Run several commands in the test directory in order to create a history:
  `echo 1`
  `echo 2`
  `echo 3`
5. Close the shell and open a new one in a different directory.
6. In that directory, run a few other commands:
  `echo 4`
  `echo 5`
7. Open a new shell in the test directory.
  **Caution:** The bug will only appear when the new shell is opened while already in that directory. It will not appear when changing to the directory *after* creating the shell.
8. Browse through the history using the Arrow Up key. The commands that were run in the other directory will be visible in the history.

**Expected behavior**
Instead of using the global history, the newly created shell should use the history of the directory in which it was created.

**Desktop**
 - OS / Distro: macOS 10.15.5
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: zsh 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator: iTerm2

**Additional context**
Theme: powerlevel10k
Other active plugins: bgnotify command-not-found copydir dirhistory git safe-paste z

**Comment by smarsching** [comment]
I just wanted to add that this problem also appears when using the "robbyrussell" theme, so it isn’t related to the theme.

The cause of the problem seems to be that zsh reads the history from `$HISTFILE` after the plugin is initialized. Unsetting `$HISTFILE` during plugin initialization resolves the problem, but then the global history is not written any longer, which isn’t good either.

**Comment by mcornella** [comment]
I'm assuming when you say in the first step "enable the plugin", you add it to the plugins array and then apply the changes, i.e. rerun zsh (`exec zsh`), before doing the next steps?

**Comment by smarsching** [comment]
Yes, that’s exactly what I meant.
