### ISSUE TITLE
compgen gives wrong results

### ISSUE THREAD

**Issue by RonLek** [ohmyzsh/ohmyzsh#9010]
**Describe the bug**
compgen gives wrong results.

**To Reproduce**

`compgen -W "--help --verbose --version" -- --h`

**On bash gives**

`--help`

**On zsh gives**

```
--help
--verbose
--version
```
**Expected behavior**
Similar to bash zsh should give only `--help` on `compgen -W "--help --verbose --version" -- --h`

**Screenshots**
![zsh-error](https://user-images.githubusercontent.com/28918901/84010797-c98cf900-a992-11ea-8dea-0d6a21676de4.png)

**Desktop**
 - OS / Distro: Linux Ubuntu 18.04
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

**Comment by mcornella** [comment]
This is a zsh issue, confirmed to also happen under the latest version. Report the bug to the [mailing list](https://zsh.org/mla).
