### ISSUE TITLE
(eval):35: parse error near `elif' after installing conda on cygwin windows

### ISSUE THREAD

**Issue by ahmedkhalf** [ohmyzsh/ohmyzsh#9016]
Platform: Cygwin/windows

zsh was working just fine until I ran `conda init zsh`.

I restarted my terminal and it now gives me this error:
`(eval):35: parse error near 'elif'`

I still can't activate my conda environment, because it thinks I have not initialized the shell.

*edit*

Using `source activate base` works but I feel this is a hacky solution... Furthermore, it does not fix the error message.

**Comment by 8secz-johndpope** [comment]
in ~/.zshrc
comment out the line
# eval "$('/c/Users/jp/miniconda3/Scripts/conda.exe' 'shell.zsh' 'hook')"

replace with
. /C/Users/jp/Miniconda3/etc/profile.d/conda.sh


(conda still not working - but python is accessible.)

**Comment by ICHx** [comment]
> 
> 
> in ~/.zshrc
> comment out the line
> # eval "$('/c/Users/jp/miniconda3/Scripts/conda.exe' 'shell.zsh' 'hook')"
> 
> replace with
> . /C/Users/jp/Miniconda3/etc/profile.d/conda.sh
> 
> (conda still not working - but python is accessible.)

in this way conda only fail to work after 'conda activate', with error 

```
conda
__conda_exe:2: no such file or directory: /c/Users/.../Miniconda3/Scripts/conda.exe^M
```

**Comment by ICHx** [comment]
```
python
Python 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z

```

The error is gone but `conda activate` STILL doesn't work

**Comment by 8secz-johndpope** [comment]
that's correct.

**Comment by thorn-jmh** [comment]
this issue might help 
https://github.com/conda/conda/issues/9922
