### ISSUE TITLE
Ignore carriage return in ZSH

### ISSUE THREAD

**Issue by ahmedkhalf** [ohmyzsh/ohmyzsh#9017]
I'm trying to ignore carriage returns in ZSH in order to use Conda.

In bash, we can ignore carriage return (^M) by adding this to .bashrc file:
```bash
export SHELLOPTS
set -o igncr
```

In ZSH adding to .zshrc doesn't work as we get an error: `set: no such option: igncr`

Conda uses windows style endings in windows and is constantly updating file endings when updating or initializing, this is why I can't use dos2unix, as it is only a temporary solution.

Is there any way we can get ZSH to ignore file endings?

**Platform:** Cygwin/windows

**Comment by mcornella** [comment]
A similar option doesn't exist in zsh. Make sure to edit files in LF mode instead.
