### ISSUE TITLE
git plugin functions completion not working with gitfast plugin

### ISSUE THREAD

**Issue by jessrosenfield** [ohmyzsh/ohmyzsh#9018]
1. Look for similar issues already posted (including closed ones)
I [posted](https://github.com/ohmyzsh/ohmyzsh/issues/2394#issuecomment-623514184) on a similar issue a few weeks ago, and after updating I got a different issue, which I will describe below.

Git completions are not working for aliased commands.

```
❯ which gb
gb: aliased to git branch
❯ gb [TAB]
```
![Screen Shot 2020-06-09 at 2 49 36 PM](https://user-images.githubusercontent.com/1537213/84187861-a892d980-aa60-11ea-87e6-65b1e2213230.png)

2. Include as much relevant information as possible
Oh My Zsh: 3c777ebf1b24826363bea6bc29afa9ba038b10e8
zsh: zsh 5.8 (x86_64-apple-darwin19.3.0)
git: git version 2.26.1
```
❯ which _git
_git () {
	# undefined
	builtin autoload -XUz
}
```
.zshrc (abridged)
```
setopt complete_aliases
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git gitfast nvm pyenv pipenv)
source $ZSH/oh-my-zsh.sh
```

3. Try to make sure the issue is due to Oh My Zsh

**Comment by mcornella** [comment]
Remove the `setopt complete_aliases` option from zshrc and it should work again. Otherwise, when completing the `gb` alias, zsh looks for a completion function for `gb`, not `git branch`.

**Comment by jessrosenfield** [comment]
@mcornella This solution fixed the problem for explicitly defined aliases, but not for the plugin's functions with such as `ggl` with `compdef _git ggp=git-checkout`.

**Comment by felipec** [comment]
@jessrosenfield You need to run `which git` after you've tried to complete a command.

As for the compdef command you need to use **underscore**: `compdef _git ggp=git_checkout`.

I created a new [separate project](https://github.com/felipec/git-completion) where I tried to explain as much as I can.

**Comment by jessrosenfield** [comment]
@felipec I'm not sure I understand your response. This `compdef` I outlined is part of the git plugin [here](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git/git.plugin.zsh#L135), not my own command.

**Comment by felipec** [comment]
@jessrosenfield That's for the zsh git completion, not the git zsh completion (which I developed).

They are two completely different completion systems.

**Comment by jessrosenfield** [comment]
@felipec thanks for clarifying, if I understand you correctly you're saying #2394 (the issue I originally posted on) was for a your system whereas my actual issue is for a different system (my bad).

Following your other piece of advice, I ran `which git` after completing `gb` (an aliased command) and got 
```
_git () {
	local _ret=1
	local cur cword prev
	cur=${words[CURRENT]}
	prev=${words[CURRENT-1]}
	let cword=CURRENT-1
	if (( $+functions[__${service}_zsh_main] ))
	then
		__${service}_zsh_main
	elif (( $+functions[__${service}_main] ))
	then
		emulate ksh -c __${service}_main
	elif (( $+functions[_${service}] ))
	then
		emulate ksh -c _${service}
	fi
	let _ret && _default && _ret=0
	return _ret
}
```

Aliased **functions** from [git.plugin.zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git/git.plugin.zsh) with `compdef _git [func]=[git_command]` still do not complete. The functions (eg: `ggp`) work, but there are no completions.

@mcornella if you have any suggestions or know of anyone else that might know something about this issue. Please let me know!

**Comment by mcornella** [comment]
To recap: the compdef lines should use the `git_command` form when using the gitfast plugin. I can't find a way to test that programmatically, so in the meantime try adding the lines below in your zshrc file, *after* OMZ is sourced:
```zsh
compdef _git _git_log_prettily=git_log
compdef _git gdnolock=git_diff
compdef _git gdv=git_diff
compdef _git ggf=git_checkout
compdef _git ggfl=git_checkout
compdef _git ggl=git_checkout
compdef _git ggp=git_checkout
compdef _git ggpnp=git_checkout
compdef _git ggu=git_checkout
```

**Comment by felipec** [comment]
@jessrosenfield Another possibility is that you are using `setopt complete_aliases`, in which case the `compdef` commands don't do anything.

If so, simply unset that.

**Comment by mcornella** [comment]
This was already fixed: https://github.com/ohmyzsh/ohmyzsh/issues/9018#issuecomment-644897791

**Comment by felipec** [comment]
> This was already fixed: [#9018 (comment)](https://github.com/ohmyzsh/ohmyzsh/issues/9018#issuecomment-644897791)

Yes, she fixed it before, but it has to be checked again.

Basically everything has to be checked:

1. Unset complete_aliases

`echo $options[complete_aliases]`

2. Correct completion

`git branch<tab>
`type -f _git_branch`

3. Correct version of the completion

`type -f _git`

It should contain `emulate ksh -c _${service}`.

4. Correct compdefs

`compdef _git ggp=git_checkout`

Not: `compdef _git ggp=git-checkout`

If all these are checked, it **must** work, there's no reason it shouldn't.

**Comment by felipec** [comment]
@mcornella I am thinking there should be an exception in the code so that people don't have to manually set these, and the same `compdef` can work for both completion systems.

```diff
--- a/git-completion.zsh
+++ b/git-completion.zsh
@@ -275,6 +275,8 @@ _git ()
 		emulate ksh -c __${service}_main
 	elif (( $+functions[_${service}] )); then
 		emulate ksh -c _${service}
+	elif ((	$+functions[_${service//-/_}] )); then
+		emulate ksh -c _${service//-/_}
 	fi
 
 	let _ret && _default && _ret=0
```

**Comment by mcornella** [comment]
Hey @jessrosenfield the current version should work without doing any extra work. Just `omz update` and restart the zsh session. Make sure `completealiases` is disabled though!
