### ISSUE TITLE
"find: paths must precede expression: `1'" with -depth 1

### ISSUE THREAD

**Issue by petrmvala** [ohmyzsh/ohmyzsh#9022]
**Describe the bug**
Find outputs error message when used with -depth 1
Since this is not the first time I have been kicked in the butt by ZSH, I verified whether this is ZSH or oh-my-zsh. Vanilla zsh does not show this behavior.
Also I suspected the `1` alias for directory browsing history, which I did unalias, but to no avail.

**To Reproduce**
1. Run `find . -depth 1`
2. See error

**Expected behavior**
Standard find output.

**Screenshots and/or Recordings**
![Screenshot 2020-06-11 at 11 36 32](https://user-images.githubusercontent.com/13413601/84370507-a3589a80-abd8-11ea-9e8c-928119625072.png)

**Desktop:**
 - OS / Distro: macOS, 10.14.6 (18G5033)
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: zsh 5.3 (x86_64-apple-darwin18.0)
 - Terminal emulator: iTerm2

**Comment by mcornella** [comment]
I think you meant to use `-maxdepth 1`, `-depth` is a flag that takes no arguments. This is not OMZ related, your command throws an error in bash as well.

**Comment by petrmvala** [comment]
Oh man! Sorry, you're right. Thank you.
Just out of curiosity: Do you have any idea why didn't it error out in pure zsh (when I logged in as root, check down on the print screen).

**Comment by mcornella** [comment]
:man_shrugging:

**Comment by ic** [comment]
Just a side note, there is a difference between GNU find and BSD find. In BSD find, the depth flag accepts a parameter. So to get "portable" commands, better to use `-maxdepth` as suggested.

GNU find man page:

> -depth Process each directory's contents before the directory itself.  The -delete action also implies -depth.

BSD find man page:

> -depth  Always true; same as the -d option.
>
> -depth n
>              True if the depth of the file relative to the starting point of the traversal is n.
