### ISSUE TITLE
fzf plugin not aware of openbsd package

### ISSUE THREAD

**Issue by fredg0** [ohmyzsh/ohmyzsh#9023]
Hello,

fzf is installed via the openbsd package manager like this :
```
> % pkg_info -L fzf
Information for inst:fzf-0.21.1

Files:
/usr/local/bin/fzf
/usr/local/bin/fzf-tmux
/usr/local/man/man1/fzf-tmux.1
/usr/local/man/man1/fzf.1
/usr/local/share/doc/pkg-readmes/fzf
/usr/local/share/fish/functions/fzf-key-bindings.fish
/usr/local/share/fzf/bash/completion.bash
/usr/local/share/fzf/bash/key-bindings.bash
/usr/local/share/vim/vimfiles/doc/fzf.txt
/usr/local/share/vim/vimfiles/plugin/fzf.vim
/usr/local/share/zsh/site-functions/_fzf_completion
/usr/local/share/zsh/site-functions/_fzf_key_bindings
```
so, the fzf zsh part is : 
```
/usr/local/share/zsh/site-functions/_fzf_completion
/usr/local/share/zsh/site-functions/_fzf_key_bindings
```

**Describe the bug**
I've got this warning each time I open a terminal : 
```
[oh-my-zsh] fzf plugin: Cannot find fzf installation directory.
 Please add `export FZF_BASE=/path/to/fzf/install/dir` to your .zshrc
```
I have tried adding those below to .zshrc with no luck : 
1/
```
autoload _fzf_key_bindings _fzf_completion
_fzf_key_bindings
_fzf_completion
```
2/
```
export FZF_BASE=/usr/local/share/zsh/site-functions/
```

**Desktop (please complete the following information):**
 - OS / Distro: OpenBSD -current
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator : xterm, sakura

Best regards.

**Comment by ModdedGamers** [comment]
I'm no expert in this, but I would suggest trying setting `FZF_BASE` to `/usr/local/bin` or `/usr/local`. IDK if it will work, but it's worth a try.

My reasoning: It may be looking for the binary.

**Comment by fredg0** [comment]
I have already tried with no success.

By taking a look at the fzf plugin script, I think it is more like the debian
case where the binary is also installed by the package manager in system $PATH.

Anyway, thank you :)

fredg

**Comment by mcornella** [comment]
Does `/usr/local/share/zsh/site-functions` appear in `$fpath`? If not, that's why the `autoload` code you tried doesn't work. I think just using `source` with those paths should work. Can you check if these do the trick?
```zsh
source /usr/local/share/zsh/site-functions/_fzf_completion
source /usr/local/share/zsh/site-functions/_fzf_key_bindings
```

If so, let me work on supporting OpenBSD in the plugin. What's your `$OSTYPE` value?

**Comment by fredg0** [comment]
Yes,  `/usr/local/share/zsh/site-functions` appear in `$fpath`

The `source` commands didn't do the trick.

`$OSTYPE` is `openbsd6.7` (I am using -current (mean the dev branch after 6.7 was released)

++

**Comment by mcornella** [comment]
Can you post the content of these files?

**Comment by fredg0** [comment]
`_fzf_completion`
https://clbin.com/Rf4tl

`_fzf_key_bindings`
https://clbin.com/CSAcr

++

**Comment by abualo** [comment]
> Hello,
> 
> fzf is installed via the openbsd package manager like this :
> 
> ```
> > % pkg_info -L fzf
> Information for inst:fzf-0.21.1
> 
> Files:
> /usr/local/bin/fzf
> /usr/local/bin/fzf-tmux
> /usr/local/man/man1/fzf-tmux.1
> /usr/local/man/man1/fzf.1
> /usr/local/share/doc/pkg-readmes/fzf
> /usr/local/share/fish/functions/fzf-key-bindings.fish
> /usr/local/share/fzf/bash/completion.bash
> /usr/local/share/fzf/bash/key-bindings.bash
> /usr/local/share/vim/vimfiles/doc/fzf.txt
> /usr/local/share/vim/vimfiles/plugin/fzf.vim
> /usr/local/share/zsh/site-functions/_fzf_completion
> /usr/local/share/zsh/site-functions/_fzf_key_bindings
> ```
> 
> so, the fzf zsh part is :
> 
> ```
> /usr/local/share/zsh/site-functions/_fzf_completion
> /usr/local/share/zsh/site-functions/_fzf_key_bindings
> ```
> 
> **Describe the bug**
> I've got this warning each time I open a terminal :
> 
> ```
> [oh-my-zsh] fzf plugin: Cannot find fzf installation directory.
>  Please add `export FZF_BASE=/path/to/fzf/install/dir` to your .zshrc
> ```
> 
> I have tried adding those below to .zshrc with no luck :
> 1/
> 
> ```
> autoload _fzf_key_bindings _fzf_completion
> _fzf_key_bindings
> _fzf_completion
> ```
> 
> 2/
> 
> ```
> export FZF_BASE=/usr/local/share/zsh/site-functions/
> ```
> 
> **Desktop (please complete the following information):**
> 
> * OS / Distro: OpenBSD -current
> * Latest ohmyzsh Update?: Yes
> * ZSH Version: 5.8
> * Terminal emulator : xterm, sakura
> 
> Best regards.

> 
https://clbin.com/Rf4tl

**Comment by mcornella** [comment]
I submitted https://github.com/ohmyzsh/ohmyzsh/pull/9327 to fix this. Try it out with `omz pr test 9327`.
