### ISSUE TITLE
How to disable Shift+Tab shortcut?

### ISSUE THREAD

**Issue by ProgrammingLife** [ohmyzsh/ohmyzsh#9024]
When I press Shift+Tab shortcut it opens me a list of files in the current directory. What is it and how to disable this feature? Or to change the shortcut to some another one.

**Comment by mcornella** [comment]
Tab is used to activate the completion mechanism, or to change from one completion entry to another from top-left to bottom-right. Shift+Tab does the same, but changing from bottom-right to top-left.

You can disable that if you want, but it's really a useful feature once you're used to it. To disable it, you can run `bindkey -r "^[[Z"`. Put it in your zshrc file if you want the change to stick every new session. To reenable it, run `bindkey "^[[Z" reverse-menu-complete`.

**Comment by ProgrammingLife** [comment]
@mcornella Thanks a lot, man!
