### ISSUE TITLE
pipenv plugin causing terminals to crash for no apparent reason

### ISSUE THREAD

**Issue by demeralde** [ohmyzsh/ohmyzsh#9032]
**Describe the bug**
Whenever I `cd` into certain directories or do certain things with the `pipenv` zsh plugin enabled, it crashes those terminal windows. It seems to do it randomly, but it's always for certain commands and directories. I don't know why.

See this issue for some more info on the behaviour: https://github.com/tmuxinator/tmuxinator/issues/777

**To Reproduce**
I'm not sure how to exactly reproduce this, or what's even causing it.

In some cases, certain commands won't run, like in the link to the issue above. In other cases, I can't even `cd` into certain directories (even if those directories don't have a `Pipfile` or `.venv` in them). 

**Expected behavior**
It shouldn't be causing things to crash. And if it does, it should say why so it can be debugged.

**Desktop (please complete the following information):**
 - OS / Distro: Ubuntu 20.04 LTS
 - Latest ohmyzsh Update?: yes
 - ZSH Version: zsh 5.8 (x86_64-ubuntu-linux-gnu)
 - Terminal emulator: Gnome Terminal

**Comment by robbyrussell** [comment]
@demeralde Not sure if you're still around to test/reproduce, but could you see if the changes made for https://github.com/ohmyzsh/ohmyzsh/issues/11472 help resolve this for you?

**Comment by demeralde** [comment]
@robbyrussell sorry I've long lost the environment I was using and also switched to Fish shell, so I can't help anymore

**Comment by carlosala** [comment]
closing, thanks for the report!
