### ISSUE TITLE
Remove Zsh from Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by fariasmateuss** [ohmyzsh/ohmyzsh#9033]
Please help! Cannot uninstall zsh.
I installed zsh on my Ubuntu 20.04 LTS but I want to get back to bash.  I tried `` ~ / .oh-my-zsh / tools / uninstall.sh '' but says `` zsh: permission denied ''

**Comment by ggrebert** [comment]
You can have multiple shell on your system.

To use `bash` as default shell, just run the following command:

```bash
chsh -s /bin/bash
```

**Comment by mcornella** [comment]
To uninstall zsh, you need to run `apt purge zsh`, but if what you really want is to uninstall ohmyzsh, you need to run `uninstall_oh_my_zsh`.

**Comment by corinthian13** [comment]
The command    uninstall_oh_my_zsh  just isn't recognized.
![Screenshot from 2021-01-21 20-11-03](https://user-images.githubusercontent.com/7750275/105406820-da8a3200-5c24-11eb-8fc5-df5a48ca580e.png)

Any attempts I make to remove zsh via

$  sudo apt purge zsh 

only cause failure of my PC to offer admin login on the boot-up screen.
So I have to login to my user account and use TimeShift to restore my system before my faulty attempt to remove zsh.

**Comment by mcornella** [comment]
You have to change your default shell back to what it was. `uninstall_oh_my_zsh` should have done that, but if it didn't, try `chsh -s $(which bash)` and log out of your user session.

**Comment by corinthian13** [comment]
Yes that just changes the default shell.
Ideally I'd like to clear zsh and oh-my-zsh entirely from my PC.
Installing it on the back of some piece in Linux Mag was just to see if color made things more efficient.
It made things more interesting but like so many apps for Ubuntu it just ran on the admin account (the only one of two accounts on my PC that has root password access). This is infuriating as we have long been advised to do all app work on a plain user account and system admin or an admin/root account. I know that somewhere we can configure things to run for alll users on the PC - but I feel that the software authors should default a package use to all users.

**Comment by mcornella** [comment]
If you installed OMZ in your admin user you're gonna need to run `uninstall_oh_my_zsh` as the admin user. The same `chsh -s $(which bash)` should be run as admin if zsh is its default shell (`getent passwd <user>` shows the `/etc/passwd` file entry for that user, which will show the default shell).

**Comment by corinthian13** [comment]
_tk@inspiron-5567:~$ sudo -i
[sudo] password for tk: 
root@inspiron-5567:~# uninstall_oh_my_zsh 
uninstall_oh_my_zsh: command not found
root@inspiron-5567:~# chsh -s $(which bash)
root@inspiron-5567:~# getent passwd root
root:x:0:0:root:/root:/usr/bin/bash_

**Comment by mcornella** [comment]
You can manually edit your `.zshrc` file to remove all references to OMZ, or delete the file entirely if you didn't add any custom settings in it. As far as zsh goes, you can remove it, but note that you can have it without OMZ, zsh is not dependent on OMZ.

**Comment by IbrahimGithub** [comment]
just paste  **chsh -s $(which bash)** enter the logout. it will work.

**Comment by corinthian13** [comment]
@IbrahimGithub 

Maybe it will work.
But I don't want the hassle just now.
I'll stick with the bash shell.

**Comment by rkumar18** [comment]
Try this `sudo apt-get --purge remove zsh` for unistall zsh from Ubuntu 20.04 LTS
