### ISSUE TITLE
Can't useTab to autocomplete directories/folders that start with a symbol like #, $ or &

### ISSUE THREAD

**Issue by kamalneckolas** [ohmyzsh/ohmyzsh#9038]
**Describe the bug**
Can't use Tab to autocomplete directories/folders that start with a symbol like #, $ or &

**To Reproduce**
1. Create a directory like $projects
2. Run command 'cd $p' then press Tab.

**Expected behavior**
The default behavior when disabling OMZ the terminal autocomplete the directory name correctly and adds \ before the symbol like: \$projects

**Comment by mcornella** [comment]
All these symbols have a different meaning inside the shell (`#` is for comments, `$` is for variables and `&` is for running a command in the background). So if you want to complete them you have to quote them, either with quotes (`"` or `'`) or with a backslash (`\`):

```console
$ cd \$p[TAB] # this works
$ cd '$p[TAB] # this also works
```
