### ISSUE TITLE
Check for $DISABLE_AUTO_UPDATE before updating

### ISSUE THREAD

**Issue by yechs** [ohmyzsh/ohmyzsh#9039]
**Describe the bug**
With `DISABLE_AUTO_UPDATE="true"`, oh-my-zsh still checks for updating by sourcing `$ZSH/tools/check_for_upgrade.sh`

This is a new change introduced by https://github.com/ohmyzsh/ohmyzsh/commit/3f6e87df15104484219c04828b2eddd6d09ee065

This would be undesirable in many cases, as the DISABLE_AUTO_UPDATE exists for a reason. For example, some people would prefer to use other means (e.g. AUR for archlinux) for versioning. 

**To Reproduce**

1. Add `DISABLE_AUTO_UPDATE="true"` to your `.zshrc`
2. Run `source ~/.zshrc`
3. oh-my-zsh tries to update itself

On my environment (Arch Linux, installed `oh-my-zsh-git` from a third-party repository [archlinuxcn](https://github.com/archlinuxcn/repo)), an error would occur since the `check_for_upgrade.sh` is [not included with the package](https://github.com/archlinuxcn/repo/blob/54ea18e1563e73000b3da9926922593c75d9cbb5/archlinuxcn/oh-my-zsh-git/PKGBUILD#L48).

```
/usr/share/oh-my-zsh/oh-my-zsh.sh:source:8: no such file or directory: /usr/share/oh-my-zsh/tools/check_for_upgrade.sh
```

**Expected behavior**

oh-my-zsh checks for the `DISABLE_AUTO_UPDATE` environment variable before upgrading itself.

**Screenshots and/or Recordings**

![image](https://user-images.githubusercontent.com/49149993/84973449-9ecc3e80-b110-11ea-830f-d2455dba09ec.png)

![image](https://user-images.githubusercontent.com/49149993/84973394-79d7cb80-b110-11ea-836e-576b7670a9aa.png)

**Desktop (please complete the following information):**
 - OS / Distro: Arch Linux
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: zsh 5.8 (x86_64-pc-linux-gnu)
 - Terminal emulator Konsole

**Comment by mcornella** [comment]
This is done in the `check_for_upgrade.sh` file, why isn't it available?

**Comment by yechs** [comment]
> This is done in the `check_for_upgrade.sh` file, why isn't it available?

Since archlinuxcn packages take a different approach to track versions and update packages, the `check_for_upgrade.sh` script is considered unneeded and is thus removed during the packaging process.

The corresponding codes are: 
https://github.com/archlinuxcn/repo/blob/54ea18e1563e73000b3da9926922593c75d9cbb5/archlinuxcn/oh-my-zsh-git/PKGBUILD#L48
