### ISSUE TITLE
COMPLETION_WAITING_DOTS don't work when $EDITOR is set in zprofile

### ISSUE THREAD

**Issue by balamurali27** [ohmyzsh/ohmyzsh#9050]
The red dots that appear when you press tab for auto completion work fine when the $EDITOR variable is not set in my .zprofile. When I set EDITOR=nvim in .zprofile, the red dots stop working.

**To Reproduce**
1. Set COMPLETION_WAITING_DOTS="true"
2. Red dots appear
3. Set $EDITOR=nvim (or any other editor) in .zprofile
4. Log out & log in
5. Red dots don't appear

 - OS / Distro:  Arch Linux
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.8-1 (as shown in pacman)
 - Terminal emulator: Termite, urxvt

**Comment by mcornella** [comment]
Did you write `EDITOR=nvim` or `$EDITOR=nvim` in the zprofile file? (the latter syntax is wrong)

**Comment by balamurali27** [comment]
> Did you write `EDITOR=nvim` or `$EDITOR=nvim` in the zprofile file? (the latter syntax is wrong)

Nope, I got it right. Thing is, setting other env variables work fine. Its the EDITOR variable that seems to be causing the problem

**Comment by balamurali27** [comment]
```
export EDITOR=nvim
export FZF_DEFAULT_COMMAND='rg --files'
PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
```
This is my current zprofile

**Comment by jZhangTk** [comment]
I have exactly the same issue. After commenting out `export EDITOR=nvim`, the dots start to show up.

**Comment by mcornella** [comment]
Is it possible it's interacting with another setting? Like, if you only set up your zshrc file to load OMZ, enable `COMPLETION_WAITING_DOTS` and `export EDITOR=nvim`, does it still happen?

**Comment by balamurali27** [comment]
Yeah, just checked. Same problem

**Comment by mcornella** [comment]
Do you both use Arch Linux? I can't reproduce it with zsh 5.8.

**Comment by balamurali27** [comment]
I use arch, yes

**Comment by jZhangTk** [comment]
I'm on MacOS.

**Comment by mcornella** [comment]
Can you run `typeset -f -t expand-or-complete-with-dots` and post the output when pressing TAB to complete?

**Comment by balamurali27** [comment]
> Can you run `typeset -f -t expand-or-complete-with-dots` and post the output when pressing TAB to complete?

I get no output
Ran the command. No output
Pressed tab to complete and it works like normal. No special output

**Comment by mcornella** [comment]
What about `bindkey '^I'`?

**Comment by balamurali27** [comment]
> What about `bindkey '^I'`?

`"^I" fzf-completion`

**Comment by mcornella** [comment]
It's bound to fzf instead. That overwrites the COMPLETION_WAITING_DOTS setting. Is that happening to everyone else?

**Comment by balamurali27** [comment]
> It's bound to fzf instead. That overwrites the COMPLETION_WAITING_DOTS setting. Is that happening to everyone else? 

But it works when EDITOR is not set.

`bindkey ^I` still gives fzf-completion and the dots appear too

Also, I tried disabling fzf completion and still no dots

**Comment by mcornella** [comment]
If running `bindkey '^I' expand-or-complete-with-dots` works, then it has to be an fzf issue. Otherwise there something else happening that I can't find.

**Comment by balamurali27** [comment]
> If running `bindkey '^I' expand-or-complete-with-dots` works, then it has to be an fzf issue. Otherwise there something else happening that I can't find. 

Oh that worked. I guess a workaround is to add this to zshrc

**Comment by balamurali27** [comment]
But now fzf tab completion doesn't work 😅

**Comment by mcornella** [comment]
So they're incompatible settings I'm afraid.

**Comment by balamurali27** [comment]
Still doesn't answer why setting EDITOR breaks the dots though

**Comment by jZhangTk** [comment]
I have the same results with the above commands. But then I found if I move `export EDITOR=nvim` to `.zhsrc` (instead of `.zshenv`), the dots show up fine (`bindkey ^I` still gives fzf-completion). I wonder if this is related to the order of the files being loaded or something.

**Comment by mcornella** [comment]
`.zshenv` is loaded first. This tells me there might be some logic in fzf that is affected by the `$EDITOR` env variable when loading fzf.

**Comment by mcornella** [comment]
I don't see any `$EDITOR`-specific logic, but here's the fzf completion binding logic: https://github.com/junegunn/fzf/blob/c329279339a5f49020f6cb43c714d54e68424700/shell/completion.zsh#L316-L320

This only relies on the order of loading, so if OMZ is loaded before fzf, the completion with dots will work.

**Comment by mcornella** [comment]
Hi folks, I found the solution perusing old issues. [Zsh sets a different keymap based on the `$EDITOR` value](https://github.com/ohmyzsh/ohmyzsh/issues/2750#issuecomment-212579543), so if `$EDITOR` is vim, the bindkey keymap is set to `viins` instead of `emacs`.

When the COMPLETION_WAITING_DOTS setting is reached (`lib/completion.zsh`), the keymap is still `viins`, but then it's changed to `emacs` in `lib/key-bindings.zsh`. The solution is to set the `expand-or-complete-with-dots` in all keymaps. I'll push a fix soon.

**Comment by balamurali27** [comment]
Thanks😄

**Comment by jZhangTk** [comment]
Yeah, same here. I'm really glad that the dots are showing up. I'm not too concerned about the cosmetic.
