### ISSUE TITLE
Update defaults to Yes on any input other than N or n

### ISSUE THREAD

**Issue by goodcodeguy** [ohmyzsh/ohmyzsh#9057]
**Describe the bug**
When prompted to update Oh-My-Zsh the prompt defaults to Yes for any keypress other than `N` or `n`. 

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Start shell when there is an update available.
2. At the update prompt type `b`
3. Oh My Zsh begins to update.

**Expected behavior**
Oh My Zsh should only update when I've explicitly told it to by selecting `Y`, `y` or pressing enter to select the default value of `Y`.

**Desktop (please complete the following information):**
 - OS / Distro: macOS
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator iTerm2

**Comment by alexagnelli** [comment]
Hi, I will take this.
