### ISSUE TITLE
Unable to clone the repository

### ISSUE THREAD

**Issue by vikasrawal** [ohmyzsh/ohmyzsh#9058]
**Describe the bug**
Unable to clone the git repository

**To Reproduce**
Steps to reproduce the behavior, for example:
1. git clone git@github.com:ohmyzsh/ohmyzsh.git or git clone https://github.com/ohmyzsh/ohmyzsh.git
2. See error

Cloning into 'ohmyzsh'...
remote: Enumerating objects: 24497, done.
error: object 2b7227859263b6aabcc28355b0b994995b7148b6: zeroPaddedFilemode: contains zero-padded file modes
fatal: fsck error in packed object
fatal: index-pack failed

**Expected behavior**
Should clone the repository.

**Desktop (please complete the following information):**
 - OS / Distro: Manjaro
 - Latest ohmyzsh Update?: Yes
 - Terminal emulator: urxvt

**Comment by lutzhorn** [comment]
Since I can not reproduce this I wonder if it was just temporary problem. Can you still not clone the repository?

**Comment by vikasrawal** [comment]
This does not work for me still:

git clone git@github.com:ohmyzsh/ohmyzsh.git

Is it by design?

Vikas

**Comment by lutzhorn** [comment]
Please check if your Git is configured to [check all fetched objects](https://git-scm.com/docs/git-config#Documentation/git-config.txt-fetchfsckObjects):

```bash
git config fetch.fsckObjects
``` 

If this prints `true`, please set it to `false` and try to clone the repository again.

```bash
git config --unset fetch.fsckObjects
git clone ...
```

**Comment by vikasrawal** [comment]
Thanks. Just realised, install.sh does something like this. Wonder why is this an issue!

**Comment by lutzhorn** [comment]
This may be a problem with legacy content inside the repository. See https://git-scm.com/docs/git-config#Documentation/git-config.txt-fsckltmsg-idgt

**Comment by mcornella** [comment]
Yep, see https://github.com/ohmyzsh/ohmyzsh/issues/4963#issuecomment-204040739 as to why this isn't fixed.
