### ISSUE TITLE
Cannot use an user profile with a "@" character

### ISSUE THREAD

**Issue by freuds** [ohmyzsh/ohmyzsh#9060]
https://github.com/ohmyzsh/ohmyzsh/blob/b706a919172955e16a1ab97f36a95b9ee4d9f1dc/plugins/aws/aws.plugin.zsh#L44

Please can you add a "@" in the sed's regex ?

**Comment by lutzhorn** [comment]
Can you give an example for a valid user profile that contains an `@`? Where should the `@` be added to the regular expression?

**Comment by freuds** [comment]
yes sure, see my current aws profile file. My profile names are using the same format than email, based on this syntax : username@customer-env

`[profile devops@customer-qa]
region = eu-west-1
output = json

[profile root@customer2-prod]
region = eu-west-1
output = json
`
and of course, my credential file use the same profile name

`[devops@customer-qa]
aws_access_key_id = xxxxxxx
aws_secret_access_key = xxxxx

[profile root@customer2-prod]
aws_access_key_id = xxxxxxx
aws_secret_access_key = xxxxx
`

Without the @ character into the regular expression, your function asp_profiles() truncate the profile names.
And after that, the profile name set in my environment don't match profile name of the credential file.

That's work for me, if i place the '@' just after the 0-9:
` grep '\[profile' "${AWS_CONFIG_FILE:-$HOME/.aws/config}"|sed -e 's/.*profile \([a-zA-Z0-9@_\.-]*\).*/\1/'`
