### ISSUE TITLE
Conda gone after installing Oh My Zsh

### ISSUE THREAD

**Issue by peflanag** [ohmyzsh/ohmyzsh#9061]
Hi,

I wanted to make command on my macOS system look more like ubuntu with the colours rather than white on black and I installed Oh My Zsh. But now when I type conda activate X to activate any environment I had it says the command conda doesn't exist. 

I'm very much a novice to command and assume its cause Oh My Zsh runs in a different environment to the mach zsh? Can I merge them or do I have to go through installing conda all over again and all the env and programs I have?

Cheers,

P

**Comment by peflanag** [comment]
Oh never mind! I was being stupid and realised I have to do conda init zsh


P

**Comment by myounus96** [comment]
Whats the solution, can you please explain...?

**Comment by jonzivku** [comment]
> Whats the solution, can you please explain...?

`conda init` initializes Anaconda/Miniconda for bash shell. To intialize other shells, use `conda init <shell>`
With zsh it would be `conda init zsh`

**Comment by sheep94lion** [comment]
Go to the anaconda directory, enter /bin, execute ./conda init zsh

**Comment by aliciaoberholzer** [comment]
I'm running into this and wondering whether the solution still remains the same? Thank you for any support!

**Comment by rwmitchell** [comment]
Did you the offered solution?

**Comment by iamyifan** [comment]
> Did you try the offered solution? Did it work?
> 
> * yes?  Solution remains the same.
> * no? What issue did you have?

I reckon @peflanag has already solved it by initiating `conda`.

**Comment by rwmitchell** [comment]
I was responding to Alicia above my post, but thanks for playing.

**Comment by rwmitchell** [comment]
> > Did you try the offered solution? Did it work?
> > 
> > * yes?  Solution remains the same.
> > * no? What issue did you have?
> 
> I reckon @peflanag has already solved it by initiating `conda`.

I was responding to aliciaobeholzer above my post, but thanks for playing.
