### ISSUE TITLE
Syntax highlighting for bash/zsh command keywords

### ISSUE THREAD

**Issue by rishabh96b** [ohmyzsh/ohmyzsh#9071]
Hey,

I wanted to know that is there any plugin available that lets us highlight the commands like `sudo`, `apt`, `ls`, `grep` etc. I have a reference of themes here that I found while doing some search [here](https://mayccoll.github.io/Gogh/).

Thanks!

**Comment by mcornella** [comment]
The [`zsh-syntax-highlighting` plugin](https://github.com/zsh-users/zsh-syntax-highlighting) does what you need.
