### ISSUE TITLE
Error when rendering agnoster theme arrows

### ISSUE THREAD

**Issue by ArthurFleischman** [ohmyzsh/ohmyzsh#9076]
**Describe the bug**
the regular arrows after the path are not rendering correctlly

**To Reproduce**
Steps to reproduce the behavior, for example:
1. I just installed the agnoster theme

![Screenshot from 2020-07-02 18-40-18](https://user-images.githubusercontent.com/33187588/86411561-807b4c80-bc93-11ea-9024-c6eebadeea2b.png)

**Desktop (please complete the following information):**
 - linux/Popos
 - Latest ohmyzsh Update?: [e.g. Yes/No]
 - ZSH Version: 5.8
 - Terminal emulator gnome-terminal

**Comment by ArthurFleischman** [comment]
I searched and the problem is the compatibility with the font... thanks for the awesome themes.

**Comment by mcornella** [comment]
You need to install a Powerline font and set your terminal emulator to use it.
