### ISSUE TITLE
How do I remove second command prompt?

### ISSUE THREAD

**Issue by LeSploosh** [ohmyzsh/ohmyzsh#9083]
![Screenshot 2020-07-04 at 15 50 04](https://user-images.githubusercontent.com/37665909/86515678-a713c180-be12-11ea-88da-4fb84109b5a2.png)
I am using iterm2 and ohmyzsh with a limited understanding of my settings, but I want to remove the second command prompt on the right hand side of the terminal, shown in the screenshot. The prompt appears with some themes but not others. I set the theme to random in the screenshot and kept reloading to show how it differs between themes.

I can see that dpoggi.zsh-theme doesn't have this 2nd prompt, but I cant see what makes it special when looking at its file.

**If i want to use a different theme e.g. robbyrussell, but without this second prompt, what do I change?**

I kinda suspect that its some other line/script in my zshrc file thats adding this second prompt in, but commenting out these other lines doesn't remove it, so Im not sure:
`source ~/Documents/scripts/git-prompt.sh 
source ~/Documents/scripts/zsh-git-prompt/zshrc.sh
PROMPT='%~%b$(git_super_status) %# '`

**Comment by jamespeapen** [comment]
Can you link your zshrc? 
What themes show the second prompt and what does `echo $PS1` give?
