### ISSUE TITLE
Remap up and down history to home row keys

### ISSUE THREAD

**Issue by himat** [ohmyzsh/ohmyzsh#9084]
Just curious - does someone have keys on/near their keyboard home row that they mapped to go up and down the history?
Reaching over to the arrow keys which are the default for going up and down history is a lot more annoying. Thanks.

I wanted to know what the best key mappings are. I wanted to use `<C-I>` and `<C-U>` but unfortunately `<C-I>` is also mapped as the tab key in terminals, so I can't use it for this purpose as well. So I'm looking for alternative, easy to use keys.

**Comment by mcornella** [comment]
To remap a key to a widget (a little function that runs when you press a key sequence), you need to use [`bindkey`](http://zsh.sourceforge.net/Intro/intro_11.html). 

To map CTRL+I, you'd use `^I` (CTRL is specified with `^`), but as you said, that mirrors TAB. You can map other keys in the same row, for example `^O` (CTRL+O) and `^P` (CTRL+P). You can run `bindkey` with no arguments to see which key bindings are set.

If you want them to do the same as arrow keys, you need to figure out which widgets are assigned to arrow keys. To know the key sequence of arrow keys, you can run press CTRL+V, and then press either Up Arrow or Down arrow, which will print their associated key sequence. You can then pass that to bindkey.

For example, when I press CTRL+V then Up Arrow, I get `^[OA`. If I run `bindkey '^[OA'`, I get the widget associated to Up Arrow, which is `history-substring-search-up`. You can follow the same steps to get the widget, then associate it to your desired keys:

```
bindkey '^O' history-substring-search-up
bindkey '^P' history-substring-search-down
```
