### ISSUE TITLE
option to have a quieter upgrade

### ISSUE THREAD

**Issue by rsperl** [ohmyzsh/ohmyzsh#9086]
**Describe the solution you'd like**
I would like an option to have a quieter upgrade. Just seeing the files changed is enough. The banner, links, etc. could be optionally printed or hidden. 

**Describe alternatives you've considered**
I considered disabling autoupgrade and have a cron update in the background, but then I never know what's changed or when.

**Comment by mcornella** [comment]
It's literally 9 lines and it only happens every so often. As I said before in another issue, I'm not going to complicate the upgrade script for such a small change.
