### ISSUE TITLE
Problem with bgnotify

### ISSUE THREAD

**Issue by AlefCS** [ohmyzsh/ohmyzsh#9096]
Hey guys, I was trying to customize `bgnotify` and it didn't work. I got this error:
`bgnotify_end:5: condition expected: 0x0`

So I tried to restore the file with `git restore` and even to made a `git pull` but nothing works. I'm still getting the same error. Already reboot my computer and got the same result.

**Comment by bartekpacia** [comment]
Hi @AlefCS 
If you messed up the plugin, you can copy its content [from here](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/bgnotify/bgnotify.plugin.zsh) and paste it into your file.

**Comment by AlefCS** [comment]
I don't know what happened but it start working again. Maybe I had some env variable with wrong value, really don't know. Anyway, thank you for your time. I'm closing the issue.
