### ISSUE TITLE
Getting Compinit error every time I start an instance of Terminal

### ISSUE THREAD

**Issue by pnpninja** [ohmyzsh/ohmyzsh#9100]
Every time I open my Terminal, I see this error - 

`compinit:503: no such file or directory: /usr/local/share/zsh/site-functions/_brew_services`

I am not sure what this issue is. How do I get rid of it?

**Comment by mcornella** [comment]
What's the output of `ls -l /usr/local/share/zsh/site-functions/_brew_services`?

**Comment by pnpninja** [comment]
`lrwxr-xr-x  1 prateek  staff  88 Dec 10  2017 /usr/local/share/zsh/site-functions/_brew_services -> ../../../Homebrew/Library/Taps/homebrew/homebrew-services/completions/zsh/_brew_services`

**Comment by mcornella** [comment]
What are the permissions of the pointed file? `ls -l $(readlink /usr/local/share/zsh/site-functions/_brew_services)`

**Comment by pnpninja** [comment]
`ls: ../../../Homebrew/Library/Taps/homebrew/homebrew-services/completions/zsh/_brew_services: No such file or directory`

**Comment by pnpninja** [comment]
How do I safely reinstall it?

**Comment by adamroyjones** [comment]
Have you tried `brew services` and `brew install zsh-completions`?

**Comment by pnpninja** [comment]
I did.. I still see the error

**Comment by mcornella** [comment]
You should post this as a Homebrew issue, I don't have the expertise to help you.
