### ISSUE TITLE
DISABLE_LS_COLORS equivalent for cd command?

### ISSUE THREAD

**Issue by Andrea-Arguello** [ohmyzsh/ohmyzsh#9104]
Hello, I am new here. I was trying to customize the colors on the amuse theme, and I for the life of me cannot find how to customize the ls and cd + tab colors command, because they look, well, very un-aesthetically pleasing to say the least...
![image](https://user-images.githubusercontent.com/31134106/87238342-a48b0c00-c3be-11ea-93ab-e0d25efc1c3c.png)
![image](https://user-images.githubusercontent.com/31134106/87238347-b5d41880-c3be-11ea-867a-2e8a65ac04d7.png)

I am unaware if I can customize this colors, at all, and if this is a ZSH issue or a theme issue, so I had opted for the DISABLE_LS_COLORS. However, I'd also like to disable the colors when doing a cd + autocompletion command. Either that, or find a way to change the colors altogether.

As a sidenote, I am using Ubuntu's command line on Windows. Although I don't think that's relevant to this issue.

**Comment by mcornella** [comment]
I believe you're seeing the default `LS_COLORS` settings. For completion, you can turn that off with
```
zstyle -d ':completion:*' list-colors
zstyle -d ':completion:*:default' list-colors
```
in case there are any zstyles set up (you can see that with `zstyle -L ':completion:*' list-colors`). You can also use `dircolors` to change the `LS_COLORS` variable.
