### ISSUE TITLE
Oh My Zsh lags in terminal when using themes, git license agreement was culprit

### ISSUE THREAD

**Issue by apzlo** [ohmyzsh/ohmyzsh#9106]
**Describe the bug**
After updating my OSX (to catalina), oh my zsh started to lag on startup and between completing commands. By working on the .zshrc file, I noticed the problem had to do with using themes.

While inspecting themes, I noticed a few git related lines (other posts here and elsewhere also described issues with git)

I then just ran the command "git" and noticed the license agreement had not been completed (could be from upgrading my OS, as I had done this in the past). 

I had to sudo as directed to complete/accept the git license agreement.

After this, the problem was completely solved. I hope this helps others

**Comment by mcornella** [comment]
Hey, thanks Alejandro. I'll close it since this is solved now.
