### ISSUE TITLE
Upgrade fails to delete lock file with rm alias

### ISSUE THREAD

**Issue by Timmmm** [ohmyzsh/ohmyzsh#9109]
On Mac, I have `alias rm="rmtrash"` in my `.zprofile`. Sometimes when I start a shell and ohmyzsh tries to upgrade it prints an error like this:

    rmtrash: illegal option -- r
    USAGE: rmtrash [-h] [-v] [-u USERNAME] FILENAME

This is because it runs this command:

    rm -rf ~/.oh-my-zsh/log/update.lock

It should do something more robust than using `rm` directly.

**To Reproduce**

1. Add `alias rm="rmtrash"` to `.zprofile`
2. Start a sufficient number of shells to have oh my zsh update. Maybe there's a way to force this.

**Expected behavior**
I believe there is a way to ignore aliases when running a command, something like `\rm`. Alternatively it should use a proper programming language to do updates.

**Desktop (please complete the following information):**

 - OS / Distro: MacOS
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.7.1
 - Terminal emulator: iTerm2

**Comment by mcornella** [comment]
Fixed in #9107, thanks for reporting.

> Alternatively it should use a proper programming language to do updates.

Shell scripting is a proper programming language 😉

**Comment by Timmmm** [comment]
> Shell scripting is a proper programming language

Debatable!

Thanks for fixing it anyway :-)
