### ISSUE TITLE
Add font-size option in zsh-theme syntax

### ISSUE THREAD

**Issue by kockok** [ohmyzsh/ohmyzsh#9110]
![Screenshot 2020-07-13 at 7 13 05 PM](https://user-images.githubusercontent.com/232541/87298800-623c0900-c53d-11ea-9c60-6501babbd044.png)

As shown on the screen cap, the system symbol is dwarfed by the text.

**Is your feature request related to a particular plugin or theme?**
no

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Add a font-size option in zsh-theme syntax to adjust the size of mac system symbols.

Thanks.

**Comment by mcornella** [comment]
This is something the shell has no control over. You can try another font or looking at the terminal emulator settings to see if you can change the size for icons.
