### ISSUE TITLE
After update on WSL(Ubuntu 20.04).My command line displays abnormally

### ISSUE THREAD

**Issue by nextkara** [ohmyzsh/ohmyzsh#9111]
**Describe the bug**
after i update my oh-my-zsh to lastest.. my zsh not like before

**To Reproduce**
1. auto update oh my zsh
2. my command line abnormal.. like this
```
$fg[magenta]nextkara$reset_color at $fg[yellow]Aurora$reset_color in $fg_bold[green]~$reset_color$(git_prompt_info)
$(virtualenv_info)$(prompt_char)
```
**Expected behavior**
it should be show like theme af-magic picture in your github wiki...

**Screenshots and/or Recordings**
my zsh appears like this when I update to latest version in today..
![pic](https://lh3.googleusercontent.com/pw/ACtC-3cNIrwJ6Ql2ut7YFFJoz7uvy4RlK_0_MHM3MawO8Pt15s8MQT3U_gKt29Gfj82G6ELmSXDdjCCiDIEtG1sST3zZA7OZmR3PJqVq2u1A-WkyxJ1Gh7KxHPAoQLi6Fb3Pg5WFE9pu_NqbQDNlCHXcIHiq=w1083-h57-no?authuser=0)

**Desktop (please complete the following information):**

 - OS / Distro: windows
 - If on Windows what version of WSL: WSL2
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: wsl
 - Theme name: af-magic

**Additional context**
i used theme named zhann, and it work well, but others seems not work good

**Comment by mcornella** [comment]
Have you added anything to your zshrc file (please post it)? It seems like `promptsubst` is not enabled, enable it by running
```
setopt promptsubst
```

**Comment by nextkara** [comment]
> Have you added anything to your zshrc file (please post it)? It seems like `promptsubst` is not enabled, enable it by running
> 
> ```
> setopt promptsubst
> ```

this is my config in .zshrc 
ZSH_THEME="zhann"
alias vm='ssh root@centos7'
cd ~
export PATH=$PATH:~/.local/bin
export ZSH="/home/nextkara/.oh-my-zsh"
plugins=(git)
source $ZSH/oh-my-zsh.sh

**Comment by nextkara** [comment]
> Have you added anything to your zshrc file (please post it)? It seems like `promptsubst` is not enabled, enable it by running
> 
> ```
> setopt promptsubst
> ```
after I run your command , result like this ...

[oh-my-zsh] Random theme 'terminalparty' loaded
$fg[green] %                                                                                                                                                                                    $fg[white]~$(git_prompt_info) $fg_bold[blue]Aurora$reset_color
$fg[green] %                                                                                                                                                                                    $fg[white]~$(git_setopt promptsubstold[blue]Aurora$reset_color
zsh: command not found: git_prompt_info
 %                                                                                                                                                                                                      ~ Aurora
zsh: command not found: git_prompt_info
 %                                                                                                                                                                                                      ~ Aurora
zsh: command not found: git_prompt_info
 %

**Comment by mcornella** [comment]
Can you run this and post the generated file? `zsh -xvic exit &> ~/omz-debug.log`

**Comment by radiovisual** [comment]
I am getting similar behaviors to this, but it only happens for me when I open a new terminal Tab. If I open a new terminal Window, my theme loads as expected.

**Comment by sysdl132** [comment]
Uh oh:I'm screwed in this problem too

**Comment by sysdl132** [comment]
@mcornella

**Comment by mcornella** [comment]
> Can you run this and post the generated file? `zsh -xvic exit &> ~/omz-debug.log`

Please post this.

**Comment by sysdl132** [comment]
This happen on mac os x 10.10 ( #9130 )
```
{20-07-23 18:27}$(ruby_prompt_info)USERNAME:~$(git_prompt_info)$(parse_git_dirty) dallas%
```
but on my another machine(ubuntu 18.04) it works fine?

**Comment by sysdl132** [comment]
![123](https://user-images.githubusercontent.com/54708046/88277298-121a2f00-cd13-11ea-82ac-94fe13c09878.jpg)

**Comment by mcornella** [comment]
See https://github.com/ohmyzsh/ohmyzsh/issues/9111#issuecomment-658819082

**Comment by nextkara** [comment]
> Can you run this and post the generated file? `zsh -xvic exit &> ~/omz-debug.log`

ok, got it

[debug.log](https://drive.google.com/file/d/1_kGuFrWALodx0T5Q6Ua65gMLnYcoyhv3/view?usp=sharing)

**Comment by mcornella** [comment]
I can't find anything wrong. Can you run `setopt` and post the output?

**Comment by mcornella** [comment]
Also, go to the ohmyzsh folder and run a `git status`:
```zsh
cd $ZSH
git status
```

**Comment by nextkara** [comment]
> Also, go to the ohmyzsh folder and run a `git status`:
> 
> ```shell
> cd $ZSH
> git status
> ```

https://drive.google.com/file/d/1_kGuFrWALodx0T5Q6Ua65gMLnYcoyhv3/view?usp=sharing

**Comment by mcornella** [comment]
It would have been interesting to know the git status of the OMZ folder (that's a link to the omz-debug.log file), but glad you solved it.
