### ISSUE TITLE
(eval):1: command not found: Chrome

### ISSUE THREAD

**Issue by mockingcode** [ohmyzsh/ohmyzsh#9112]
Installed _tmux_. Every time I run a new tmux session, it prints `eval):1: command not found: Chrome` along side with some _echo_ lines from the `.zshrc`.  I already deleted .zcompdump* files, updated zsh, and OMZ.

 - OS / Distro: macOS X
 - Latest ohmyzsh update
 - ZSH Version: 5.8
 - Terminal emulator: iTerm2

**Comment by mcornella** [comment]
What's your zshrc file?

**Comment by mockingcode** [comment]
It's the standard .zshrc file. I do added some plugins though. Removed all the .zcompdump* as suggested in the other issues and it's still there. Here are the list of plugins:

`plugins=(
    git
    urltools
    bgnotify
    zsh-autosuggestions
    osx
    zsh-syntax-highlighting
)`

**Comment by mcornella** [comment]
You can run `zsh -xvic exit &>~/omz-debug.log` and inspect the omz-debug.log file to see which command generates this error.

**Comment by mcornella** [comment]
You can also post this file so I can help you debug it.

**Comment by mockingcode** [comment]
Apparently, I was too ignorant to look at the `$PATH` variable. I didn't escape a path referring to Chrome's path. Searched the source of error from the logs but I could've just `echo $PATH`. It was there the whole time. Forgive me for not replying for a long time as I'm not a usual user of GitHub.

**Comment by mcornella** [comment]
No worries, I'm just glad you caught it.

**Comment by zyyoo** [comment]
@mcornella

**Comment by ColaMint** [comment]
> @mcornella ![image](https://user-images.githubusercontent.com/40783859/122326456-e9200f80-cf5e-11eb-9092-104c6e23c155.png)
> 
> * I have a similar problem, can you help me take a look at this log
>   https://raw.githubusercontent.com/zyyoo/fuke/main/omz-debug.log

me too

**Comment by ColaMint** [comment]
> @mcornella ![image](https://user-images.githubusercontent.com/40783859/122326456-e9200f80-cf5e-11eb-9092-104c6e23c155.png)
> 
> * I have a similar problem, can you help me take a look at this log
>   https://raw.githubusercontent.com/zyyoo/fuke/main/omz-debug.log

I have the same problem, but after updating zsh, it disapeared.

**Comment by zyyoo** [comment]
> ###
> [Mar 3, 2023](#issuecomment-1453169032)

有用有用!

**Comment by ColaMint** [comment]
> > @mcornella ![image](https://user-images.githubusercontent.com/40783859/122326456-e9200f80-cf5e-11eb-9092-104c6e23c155.png)
> > 
> > * I have a similar problem, can you help me take a look at this log
> >   https://raw.githubusercontent.com/zyyoo/fuke/main/omz-debug.log
> 
> I have the same problem, but after updating zsh, it disapeared.


This problem keeps recurring and every time I need to fix it with the command "omz update"

**Comment by ColaMint** [comment]
> > > @mcornella ![image](https://user-images.githubusercontent.com/40783859/122326456-e9200f80-cf5e-11eb-9092-104c6e23c155.png)
> > > 
> > > * I have a similar problem, can you help me take a look at this log
> > >   https://raw.githubusercontent.com/zyyoo/fuke/main/omz-debug.log
> > 
> > 
> > I have the same problem, but after updating zsh, it disapeared.
> 
> This problem keeps recurring and every time I need to fix it with the command "omz update"

I commented out some of the contents of ~/.zshrc, and finally found that zplug caused this problem. I reinstalled zplug and hope this problem doesn't recur.

**Comment by ColaMint** [comment]
> > [Mar 3, 2023](#issuecomment-1453169032)
> 
> 有用有用!

@zyyoo 请问你完全解决掉这个问题了吗? 这边还是反复出现！

**Comment by ColaMint** [comment]
> > > > @mcornella ![image](https://user-images.githubusercontent.com/40783859/122326456-e9200f80-cf5e-11eb-9092-104c6e23c155.png)
> > > > 
> > > > * I have a similar problem, can you help me take a look at this log
> > > >   https://raw.githubusercontent.com/zyyoo/fuke/main/omz-debug.log
> > > 
> > > 
> > > I have the same problem, but after updating zsh, it disapeared.
> > 
> > 
> > This problem keeps recurring and every time I need to fix it with the command "omz update"
> 
> I commented out some of the contents of ~/.zshrc, and finally found that zplug caused this problem. I reinstalled zplug and hope this problem doesn't recur.

Switching from zplug, the plugin manager, to another plugin manager ultimately solved my problem.
