### ISSUE TITLE
Remove Google Analytics from website

### ISSUE THREAD

**Issue by resynth1943** [ohmyzsh/ohmyzsh#9113]
## Remove Google Analytics

If you must have an analytics system, might I suggest either:
- Plausible: https://plausible.io (offers a 50% discount for FOSS projects)
- Goatcounter: https://goatcounter.com
- Matomo: https://matomo.org
- Fathom: https://usefathom.org

These solutions are all well-tested and open-source. This, of course, means they
can be independently audited for privacy and security. Instead of using a proprietary
nonfree system such as Google Analytics, perhaps we could work together to replace
it with something slightly more ethical?

Furthermore, the majority of privacy features in evergreen browsers *block* Google
Analytics from being run. I can not say the same for solutions such as Plausible,
which suggests they are trusted for their privacy by independent persons.

If you need any more information, please contact me!

**Comment by TriMoon** [comment]
Can i ask in what part of OMZ google analytics is embeded at moment?
(So i can zap it on my machine immediately)

**Comment by resynth1943** [comment]
@TriMoon it's embedded into the website.

**Comment by bartekpacia** [comment]
Is the website open-source? I can't find it under `https://github.com/ohmyzsh`

**Comment by resynth1943** [comment]
I'm not 100% sure, dude. I remember just giving up and opening the issue here, as I couldn't find anything like what you're suggesting.

**Comment by mcornella** [comment]
The website is run entirely by Planet Argon, @robbyrussell's company. I'll pass along the suggestion, thanks.

**Comment by resynth1943** [comment]
Thanks, @mcornella! Am I to expect a response here?

Alternatively, my email is resynth1943@tutanota.com

**Comment by TheEvilSkeleton** [comment]
@mcornella any update?
