### ISSUE TITLE
An error is reported when executing source ~ /. Zshrc

### ISSUE THREAD

**Issue by maxuesong1990** [ohmyzsh/ohmyzsh#9115]
-bash: /Users/oh-my-zsh/tools/check_for_upgrade.sh: line 31: syntax error near unexpected token `)'
-bash: /Users/.oh-my-zsh/tools/check_for_upgrade.sh: line 31: `() {'
-bash: autoload: command not found
-bash: /Users/.oh-my-zsh/oh-my-zsh.sh: line 36: syntax error near unexpected token `('
-bash: /Users/.oh-my-zsh/oh-my-zsh.sh: line 36: `for plugin ($plugins); do'

**Comment by mcornella** [comment]
This problem has been asked many times: you're not running zsh, you're running bash. You need to run zsh.

**Comment by stark-ace-1891** [comment]
I run zsh and then source .zshrc, executed without problems, but the theme doesn't update
