### ISSUE TITLE
git commit -m "add !empty check" event not found: empty

### ISSUE THREAD

**Issue by jagadeshanh** [ohmyzsh/ohmyzsh#9118]
**Describe the bug**
commit message should not be parsed

**To Reproduce**
Steps to reproduce the behavior, for example:
1. git add .
2. git commit -m "add !empty check"
3. See error (zsh: event not found: empty)

**Expected behavior**
git should commit the message without error

**Comment by bartekpacia** [comment]
Replacing `"` with `'` fixes this for me.

**Comment by mcornella** [comment]
See [History expansion](http://zsh.sourceforge.net/Doc/Release/Expansion.html#History-Expansion):
> A history expansion begins with the first character of the histchars parameter, which is ‘!’ by default, and may occur anywhere on the command line, **including inside double quotes (but not inside single quotes ’...’ or C-style quotes $’...’ nor when escaped with a backslash)**.
