### ISSUE TITLE
Text is beeing automatically selected after I paste it on Hyper

### ISSUE THREAD

**Issue by matheusranzani** [ohmyzsh/ohmyzsh#9119]
Whenever I paste some text on Hyper it is selected automatically. I'm using Hyper with Oh My Zsh on Linux right now. I also use them on Windows and the same problem doesn't happen. 

Steps to reproduce the problem:
1. Copy a browser URL, for example: https://github.com/matheusranzani/reactive-native-rocketseat (this is a private repo of mine, just to example the problem)
2. Paste it on Hyper
3. See that the URL text is selected

I don't want the text I paste be selected automatically, because I'm using the plugin 'fast-syntax-highlighting' and it doesn't work correctly after the text is auto selected.

Screenshot of the error:
![hyper-issue-1](https://user-images.githubusercontent.com/59764547/87677367-0f866b00-c750-11ea-8773-149a20c64f72.png)

Screenshot of the normal plugin behavior (writting manually the URL):
![hyper-issue-2](https://user-images.githubusercontent.com/59764547/87677968-bf5bd880-c750-11ea-98ca-4d13257280e6.png)

 - OS / Distro: Zorin OS
 - Latest ohmyzsh update?: Yes
 - ZSH Version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
 - Terminal emulator: Hyper

**Comment by mcornella** [comment]
I think when you press space (or any other character) the pasted input gets de-selected automatically, no?

**Comment by matheusranzani** [comment]
> 
> 
> I think when you press space (or any other character) the pasted input gets de-selected automatically, no?

Yes, but I think select the text pasted is not a normal behaviour. And I was looking for a solution to stop selecting.
But thanks anyway :)

**Comment by mcornella** [comment]
Did you figure it out?

**Comment by matheusranzani** [comment]
> Did you figure it out?

No :(

I'm following what you said about spacing after pasting the text.

**Comment by mcornella** [comment]
This looks like a Hyper issue, see https://github.com/vercel/hyper/issues/819. If you run `zsh -f` (without OMZ) I can see that the same happens, but not if you run `bash`.

**Comment by mcornella** [comment]
You can [disable this by running `unset zle_bracketed_paste`](https://github.com/vercel/hyper/issues/819#issuecomment-489421786). You can put this in your zshrc file for a permanent solution.

**Comment by matheusranzani** [comment]
> You can [disable this by running `unset zle_bracketed_paste`](https://github.com/vercel/hyper/issues/819#issuecomment-489421786). You can put this in your zshrc file for a permanent solution.

Thanks dude. This worked out :)
