### ISSUE TITLE
I have `using ☁️  default/` showing by default

### ISSUE THREAD

**Issue by codevski** [ohmyzsh/ohmyzsh#9120]
So not sure why this is showing. I seem to have "using ☁️  default/" showing no matter what folder I am at. I have no idea what it is referencing I thought it might have been AWS, but i set a particular profile by exporting it and it creates another cloud profile in front of the using default...

root example: 
![image](https://user-images.githubusercontent.com/1435321/87844195-54e89b00-c8fe-11ea-8988-2aec99bd0ae5.png)

git folder example:
![image](https://user-images.githubusercontent.com/1435321/87844522-2cae6b80-c901-11ea-8e0d-af1c58c7cd73.png)

Happy to share any configs / logs if needed.

**Comment by mcornella** [comment]
What theme are you using?

**Comment by codevski** [comment]
Spaceship-prompt https://github.com/denysdovhan/spaceship-prompt

**Comment by codevski** [comment]
Well I just cleared my zshrc file and started fresh and its working fine so not sure what was the issue but its working now. Might of been just a bad config file.
