### ISSUE TITLE
snapd plugin

### ISSUE THREAD

**Issue by fkromer** [ohmyzsh/ohmyzsh#9125]
**Is your feature request related to a particular plugin or theme? If so, specify it.**

Not existing yet.

**Is your feature request related to a problem? Please describe.**

I'd like to have autocompletion and aliases for the snapd command line tool `snap`.

**Describe the solution you'd like**

A plugin for the snapd daemon CLI `snap`.

**Describe alternatives you've considered**

Shell aliases and functions. I am interested in contributing my aliases and functions.

**Additional context**
- [snapd command line intro](https://snapcraft.io/docs/getting-started)

**Related Issues**

Nothing related found.

**Comment by kapilpau** [comment]
Added plugin, in PR #9357

**Comment by robbyrussell** [comment]
Added in #9357
