### ISSUE TITLE
ubuntu-image plugin

### ISSUE THREAD

**Issue by fkromer** [ohmyzsh/ohmyzsh#9127]
**Is your feature request related to a particular plugin or theme? If so, specify it.**

**Is your feature request related to a problem? Please describe.**
I'd like to have auto completion for the [ubuntu-image](http://manpages.ubuntu.com/manpages/bionic/man1/ubuntu-image.1.html) command. I've aliases and shell functions but lack interactivity.

**Describe the solution you'd like**

A plugin "ubuntu-image".

**Describe alternatives you've considered**

**Additional context**

**Related Issues**

Nothing found.

**Comment by TriMoon** [comment]
I'm not sure but i think auto completion of options for a command is the responsibility of that command's package, so i suggest to file an issue with the ubuntu team that's responsible for that package.
Or mail the author directly barry@ubuntu.com

**Comment by fkromer** [comment]
@TriMoon I don't know the mechanism/integration of ohmyzsh not well enough. When I was looking into some plugins, e.g. the [fabric plugin](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/fabric/_fab) it seemed like the autocompletion part is implemented in the plugin itself, not the command line tool. However in case you are an plugin author please prove me wrong :slightly_smiling_face:

**Comment by TriMoon** [comment]
Well most plugins enhance the functionality already provided by the tool/command 's author, and auto-completion for most used shells (bash,zsh,etc) is normally done by the author of it.
I never used that command so i don't know if they include auto-completion (yet)...
That's why i suggested to contact the author of that command :wink:

**Comment by mcornella** [comment]
Agree with TriMoon here, as has been reported before in #10401, Oh My Zsh shouldn't be the place to bundle completions.
