### ISSUE TITLE
Theme not working properly (shows `$(git_prompt_info)` and `$(ruby_prompt-info)`)

### ISSUE THREAD

**Issue by sysdl132** [ohmyzsh/ohmyzsh#9130]
`` shell=zsh,theme=dallas,os=OSX yosemite,zsh=unknown ``
![135](https://user-images.githubusercontent.com/54708046/88005916-0bd25a00-cb3d-11ea-90af-22b3238b84a0.jpg)
compare:
![531](https://user-images.githubusercontent.com/54708046/88006267-d1b58800-cb3d-11ea-994e-6c8ed2a1b3d4.png)

**Comment by sysdl132** [comment]
```
$ ruby -v
ruby 2.0.0p481
$ git clone
(squeezed text,53 lines)
$
```

**Comment by sysdl132** [comment]
Who can answer...

**Comment by mcornella** [comment]
Try running `setopt promptsubst`, which should be automatically set by OMZ.

**Comment by sysdl132** [comment]
I returned to my windows computer and the oh-my-zsh runs properly.But... 
![image](https://user-images.githubusercontent.com/54708046/88298204-70efa080-cd33-11ea-93d2-7082ea6b769c.png)
...how to fix this?

**Comment by mcornella** [comment]
Post the output of `locale` and `locale -a`, also what terminal emulator are you using?

**Comment by sysdl132** [comment]
```
~ $ setopt promptsubst
setopt: command not found
```

**Comment by sysdl132** [comment]
> Post the output of `locale` and `locale -a`, also what terminal emulator are you using?

I'm using windows wsl(debian 10) and the problem was solved(font error)
Also,the osx problem still not resolved.``setopt`` isn't work properly?

**Comment by mcornella** [comment]
> ```
> ~ $ setopt promptsubst
> setopt: command not found
> ```

Isn't this bash? Zsh does have `setopt` enabled.

**Comment by mcornella** [comment]
> Also,the osx problem still not resolved.`setopt` isn't work properly?

Post the output of `git status` in the OMZ folder:
```
cd $ZSH
git status
```

**Comment by sysdl132** [comment]
Hey @mcornella 
I did these changes and OMZ on my mac can work properly:
- 1.uninstall OMZ
- 2.upgrade macos from 10.10.5 yosemite to 10.15.6 catalina
- 3.reinstall OMZ
then,the OMZ works fine on my mac now.thanks 👍
