### ISSUE TITLE
Pipenv not activated in a new window

### ISSUE THREAD

**Issue by craiga** [ohmyzsh/ohmyzsh#9136]
**Describe the bug**

When opening a new terminal window in a directory with a Pipfile, a sub shell is not activated in the same way as if I cd into that directory.

**To Reproduce**

1. `cd /some/dir/with/pipenv`. Note that pipenv shell is activated.
2. Open a new terminal window in that same directory. Note that pipenv shell is *not* activated.
3. `cd ../pipenv`. Note that the shell is now activated.

**Expected behavior**

The shell should be activated when a new terminal window is opened.

**Desktop**

 - OS / Distro: macOS 10.15.5 (19F101)
 - Latest ohmyzsh update?: Yes
 - ZSH Version: zsh 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator: Apple Terminal.app

**Comment by mcornella** [comment]
Thanks for reporting, it should be fixed now.
