### ISSUE TITLE
[dotnet] Tab Completion don't working

### ISSUE THREAD

**Issue by archteck** [ohmyzsh/ohmyzsh#9139]
**Describe the bug**
Tab completion don't work for dotnet, with the dotnet plugin enabled.
The plugin is suppose to do it but is not working,  tab suggest files/folder, not commands as it should.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'dotnet'
2. Try the autocomplete command 'dotnet  '
3. Will suggest files or folders

**Expected behavior**
It should suggest 

add              -d               --help           --list-runtimes  nuget            restore          test           
build            --diagnostics    help             --list-sdks      pack             run              tool           
build-server     fsi              --info           msbuild          publish          sln              --version      
clean            -h               list             new              remove           store            vstest  

I have a suggestion of how to fix it, just replace the code in the plugin of _dotnet_zsh_complete() by the one in the  in [ Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete) for Zsh.
I did that then it worked fine, but maybe you expect more than that so i hope it can help you in the fixing.

**Screenshots and/or Recordings**

**Self Check**

I search there was no issues for this problem open, i don't have discord.

**Desktop (please complete the following information):**

 - OS / Distro: [Kubuntu]
 - Latest ohmyzsh update?: [Yes]
 - ZSH Version: [5.8]
 - Terminal emulator: [Konsole]

**Additional context**
I don't believe that others plugins can be the problem where but i will send my list.

plugins from oh-my-zsh
dotnet
ng
npm
ubuntu
zsh-history-substring-search

from zsh-users
zsh-syntax-highlighting
zsh-autosuggestions

theme
romkatv/powerlevel10k

**Comment by mcornella** [comment]
I could not reproduce it. I did have an initial problem: the `dotnet` tool prints a message on the first run about telemetry, even if the call to `dotnet` is using the `dotnet complete` command. After that, all completion tries do work correctly. Can you post a screenshot or textgrab of the command failing?

**Comment by archteck** [comment]
I will try to help you with screenshots.
About the telemetry, it will appear in the first run, i use "export DOTNET_CLI_TELEMETRY_OPTOUT=1" on my .zshrc to disable telemetry so I don't get that message, maybe after that you don't get that message.
Ok know lets go to prints:

This is with dotnet plugin current version

**dotnet and pressed Tab**
![dotnet_current_tab_simple](https://user-images.githubusercontent.com/20408355/88867243-d4327480-d204-11ea-8810-2a9a228c22a5.png)

**dotnet new and pressed Tab**
![dotnet_current_tab_new](https://user-images.githubusercontent.com/20408355/88867201-afd69800-d204-11ea-9345-a7a6fd6bcc93.png)

This is with my alteration that came from Microsoft Docs:

**dotnet and pressed Tab**
![dotnet_modified_tab_simple](https://user-images.githubusercontent.com/20408355/88867280-f2987000-d204-11ea-8b78-008d8a3d4684.png)


**dotnet new and pressed Tab**
![dotnet_modified_tab_new](https://user-images.githubusercontent.com/20408355/88867294-fc21d800-d204-11ea-8da1-3d264772dc7b.png)

The dotnet new with my modification adds and - then shows whats printed.

Hope it helps you, if you need anything more feel free to ask.

Many thanks

**Comment by mcornella** [comment]
When it doesn't work, can you run `which $_comps[dotnet]`, and also try to get a completion trace by writing the command you want to complete, then pressing `CTRL`+`X` followed by `?`. It'll generate a trace file which you can see after pressing the key binding.

**Comment by archteck** [comment]
I run `which $_comps[dotnet]` , don't print anything. Am I missing anything?
The trace file:
[zsh20904dotnet1.txt](https://github.com/ohmyzsh/ohmyzsh/files/5001082/zsh20904dotnet1.txt)

**Comment by mcornella** [comment]
When you enable the plugin, do you restart the zsh session either by reopening the terminal or running `exec zsh`? Sorry if this is a stupid question but it's very weird that `$_comps[dotnet]` is not defined.

**Comment by archteck** [comment]
There is no stupid questions, they are all necessary. Yes I reopen the terminal.
 when you ask me that, I started to think that I was the problem, and well i find the problem.
I use Antigen, that was my flaw, i should have told it but I didn't think it was the problem, well that's stupid -> me.
So I remove Antigen, use Oh My Zsh and everything is fine.
I never thought Antigen affected the way plugins work, once again sorry for my stupidity.

**Comment by mcornella** [comment]
Hey that's not stupid at all, I don't want to hear such nonsense because then other people might think they're stupid too.

As I see it, even if you're loading it with Antigen, the plugin should work the same. Let me try to help you here, are you up for that? If so, what was your zshrc file when using antigen? I want to try to reproduce the issue.

**Comment by archteck** [comment]
Yes let's do it!
Antigen version 2.2.3
I send you my .zshrc , .antigenrc and .p10k.zsh (not needed I believe but to be sure)

[files.zip](https://github.com/ohmyzsh/ohmyzsh/files/5003196/files.zip)

**Comment by mcornella** [comment]
Ok this is an antigen bug. See https://github.com/zsh-users/antigen/issues/698.

**Comment by archteck** [comment]
I hope they fix it, but it almost feels like antigen is abandoned.
Thank you so much for your time.
