### ISSUE TITLE
Cursor resets to the wrong column after terminal error

### ISSUE THREAD

**Issue by Roulbac** [ohmyzsh/ohmyzsh#9141]
Here is the problem I am facing

```
(base) ----------------------------------------------------------------------------------
~  || <---------- cursor here                                               reda@razer15
```
Then if I press Ctrl+C or any command that doesn't return successfully, the cursor will be reset to the wrong column

```
(base) ----------------------------------------------------------------------------------
|~| <---------- cursor here                                           130 reda@razer15
```
If the command returned successfully, like for an example ls, the cursor is reset to the right column

**Comment by mcornella** [comment]
Try [this FAQ answer](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command).
