### ISSUE TITLE
gitfast plugin: tab completion broken on filenames containing spaces (expected automatic quote/backslash)

### ISSUE THREAD

**Issue by kevin-foster** [ohmyzsh/ohmyzsh#9142]
**Describe the bug**
With 'gitfast' plugin enabled, if I try to add a file named (e.g.) `aaaa bbbb cccc` (i.e., anything with spaces) to repository `git add aa[Tab]`, the filename is expanded but with no backslashes or quotes to handle the spaces. Git then thinks I'm asking to add several items (the first being a file named `aaaa`) and complains.

If I disable gitfast, the problem goes away.

The problem seems to be on my laptop (bash version 4.4.20, zsh version 5.4.2), but not on my desktop (newer versions: bash v5.0.17, zsh 5.8). Both laptop and desktop have freshest version of oh-my-zsh as of today (confirmed by running upgrade_oh_my_zsh on both).

**To Reproduce**
1. Enable gitfast plugin
2. `mkdir gittest`
3. `cd gittest`
3. `git init`
4. `touch 'aaaa bbbb cccc'` (a single filename that contains spaces).
3. `git add aa[Tab]`
3. This expands to: `git add aaaa bbbb cccc`. Hit enter.
3. Problem: `fatal: pathspec 'aaaa' did not match any files`

**Expected behavior**
If the same steps above are repeated but gitfast is disabled, then hitting `[Tab]` results in filename being expanded with backslashes protecting the spaces. This is the expected behavior with gitfast enabled.

**Desktop (please complete the following information):**

 - OS / Distro: Linux Mint Cinnamon
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.4.2
 - Terminal emulator: gnome-terminal

**Additional context**

As mentioned above---I did notice that the problem doesn't occur with my desktop machine, which has newer versions of zsh and bash. (Upgrading bash or zsh isn't my preferred solution since I want to stick with the repository versions). I know the gitfast plugin uses elements of the bash completion tool behind the scenes, but I wouldn't know how/which components are used. I hope this context is enough for you to go on.

Thanks!

**Comment by mcornella** [comment]
This is fixed in the v2.21.0 completion function: https://github.com/git/git/commit/7a478b36aa1f202aed207a230def66563227f30e, while we're using the v2.16 version for backwards compatibility. @felipec can we do something here? Some time has passed since https://github.com/ohmyzsh/ohmyzsh/pull/7918, has git completion improved since then? Can we upgrade the version yet?

**Comment by setu4993** [comment]
Checking in here (related: #8894). Can the completions please be updated to the latest version?

**Comment by felipec** [comment]
@mcornella Sorry about the delay.

It should have been possible to backport that specific fix, and update the custom patch accordingly.

I did that [one commit](https://github.com/ohmyzsh/ohmyzsh/pull/9382/commits/142d290ef28c6b8dbf96599b2bd63d3329e9241c) in the latest pull request, however, it is quickly replaced by updating to the latest upstream.
