### ISSUE TITLE
Is it possible to remove specific lines from shell history? [feature-requested]

### ISSUE THREAD

**Issue by avatar-lavventura** [ohmyzsh/ohmyzsh#9149]
Please see the [discussion](https://unix.stackexchange.com/q/598709/198423) in stackoverflow. On the comments I have been recommended to ask the developers if they're interested in adding the feature.

Basically in `bash` we have following feature:

> If you want to run a command without saving it in history, prepend it with an extra space

```
prompt$ echo saved
prompt$  echo not saved \
> #     ^ extra space
```

------

I have following [answer for How to remove a single line from history?](https://unix.stackexchange.com/a/49216/198423) . When I do following, the line(` echo hello_world`) is not saved into history. Please note that I am using `ZSH` shell.

```
prompt$  echo hello_world
> #     ^ extra space
```

----

```
$ history | tail -n1
 1280  history | tail -n
$  echo hello_world
hello_world
$ history | tail -n1
 1280  history | tail -n
```

- But when I do run a command having a space at the beginning and right after do `CTRL-p`, I can see it on the shell history, even though it is not save in `history`. Is it possible to prevent it? On bash shell: this works with `HISTCONTROL= ignorespace`.

```
$  echo hello_world
$ # Press `CTRL-p` => " echo hello_world" shows up again
```

[Q] Is it possible to apply same feature into `zsh`?

**Comment by sysdl132** [comment]
...Maybe you can open this feature request on zsh repository or take a look of https://wiki.archlinux.org/index.php/Zsh @avatar-lavventura 🔍

**Comment by mcornella** [comment]
So the command doesn't end up in the history, it only appears immediately after running it and then pressing up-arrow or CTRL+P in your case. This might be a feature, meaning that sometimes the command you just ran has an error and you desire to use the previous command again to fix it, even if it had a space before it to keep it out of history. **The command still isn't logged**, it's just a temporary convenience. If you think this is a bug, you can tell the folks from Zsh in their [mailing list](https://www.zsh.org/mla/).

**Comment by avatar-lavventura** [comment]
@mcaserta I don't think it is a bug, just different behavior than `bash` provides, which brings confussion.  I believe it is not implemented or avaible option to enable on `zsh`'s end.

> @KGIII : I [checked](https://linux.die.net/man/1/zshoptions) and it doesn't seem to be an available option. 

---

Possible cases you can face it:

> `it only appears immediately after running it and then pressing up-arrow or CTRL+P in your case. `: Yes, if I do ` echo "hello"` than ` echo world` , ` echo "hello"` won't be accessible by `CTRL+p` so the most recent commad is recorded no matter there is space or not. Seems like a unnessesary case but it becomes pretty useful in some unique cases.

- I put space before `fg` so , when I am using `emacs` I suspend it and run `./run.sh` and run ` fg` to get back. 
Afterwards, when I suspend emacs again, and when I do `CTRL-p` it brings ` fg` , even it is not recored in the `zsh_history`. So I have to press two times CTRL-p to reach `./run.sh`. In `bash` since `fg` wont be in the `CTRL-p` s histroy with one click I can reach to `./runs.sh`. When you do this hunderds of times, it becomes an important case for some users like me.
