### ISSUE TITLE
fastfile_ls outputs nothing although I have several shortcuts in ~/.fastfile

### ISSUE THREAD

**Issue by benlieb** [ohmyzsh/ohmyzsh#9151]
I believe this used to work fine, but I've recently tried to use them again after several months and `ffls` / `fastfile_ls` has no output.

**Comment by mcornella** [comment]
Run `typeset -f -t fastfile_ls` and try again, and post the debug output.

**Comment by benlieb** [comment]
Not sure that worked

![image](https://user-images.githubusercontent.com/634562/94727579-ce940080-0313-11eb-818d-30f84d40059d.png)

**Comment by mcornella** [comment]
The files in `~/.fastfile` start with `.`? If not, can you post a redacted `ls` of that directory?
