### ISSUE TITLE
The gmt alias clashes with the gmt application

### ISSUE THREAD

**Issue by PaulWessel** [ohmyzsh/ohmyzsh#9154]
We are receiving notices from people using [gmt](https://www.generic-mapping-tools.org) that your alias gmt trips them up.  Since gmt is available on most distros and have been around since the late 1980s we recommend you modify you alias so that more can benefit from your aliases.

**Comment by seisman** [comment]
Just provide more information here.

1. The `gmt` alias is provided by the [git](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git) plugin. 
2. The [git](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git) plugin also provides another alias **gm**, which is conflicting with the **gm** command from GraphicsMagick.

**Comment by joa-quim** [comment]
A good option would be to prefix all the aliases with *z_*. Short and and still close to current names, because these name clashes are not nice.

**Comment by mcornella** [comment]
Could be rename to `gmtl`.

**Comment by seisman** [comment]
For anyone who has the issue, the temporary workaround is commenting out the `gmt` alias in the git plugin:

https://github.com/ohmyzsh/ohmyzsh/blob/dac3314c76e799cddbbe5cf63870d31861626059/plugins/git/git.plugin.zsh#L211
