### ISSUE TITLE
A second alias for `git stash pop`

### ISSUE THREAD

**Issue by AnatoleLucet** [ohmyzsh/ohmyzsh#9168]
**Is your feature request related to a problem? Please describe.**
I'm a bit bored by typing the entire id of a stash when doing a stash pop using `gstp`.

**Describe the solution you'd like**
Is it possible to have an alias for `stash@{...}` ?
For example, `gstpi() { git stash pop "stash@{$@}"; }`. Used like so: `gstpi 2` instead of the current `gstp stash@{2}`.

Thank you all for this great tool! :heart:

**Comment by mcornella** [comment]
Did you know that you can use tab completion to complete the `stash@{` part? That also gives you a description of the stashed changes:

![image](https://user-images.githubusercontent.com/1441704/90987591-5b68d300-e58c-11ea-9b21-10c946d05363.png)

The proposed change would mean you lose the completion benefits.

**Comment by AnatoleLucet** [comment]
@mcornella indeed I didn't know. That's perfect, thanks.
I let you decide to close this issue or not, but for me, the auto completion did the trick.

**Comment by mcornella** [comment]
Alright I'll close this then. Cheers
