### ISSUE TITLE
Trouble Updating oh-my-zsh

### ISSUE THREAD

**Issue by Xen0neX** [ohmyzsh/ohmyzsh#9170]
Running a mac host, iterm2, oh-my-zsh, powerlevel10k setup

-- console output produced during zsh initialization follows --

Updating Oh My Zsh
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
There was an error updating. Try again later?

Upon running git diff in .oh-my-zsh I get the following output:

* Unmerged path plugins/git-remote-branch/README.md
* Unmerged path plugins/git-remote-branch/git-remote-branch.plugin.zsh
* Unmerged path plugins/nyan/README.md
* Unmerged path plugins/nyan/nyan.plugin.zsh

Sorry I am new to git and am unsure how to resolve these issues. Are they related to my powerlevel10k installation?

Any help would be greatly appreciated

**Comment by Xen0neX** [comment]
I used git reset -- <file> To revert the changes to the files causing the issues while upgrading and that let me upgrade. I am still unsure as to what caused this anomaly however

**Comment by mcornella** [comment]
It's possible you modified some of these files. Without a `git diff` or `git status` it's impossible to tell.

**Comment by mesmerx** [comment]
cd $ZSH/ ( if this variable is not set you discover the path for your zsh with  `which update_ohmyzsh`)
git reset --hard HEAD~1
git pull

should fix your issue

**Comment by sananbadalov** [comment]
> cd $ZSH/ ( if this variable is not set you discover the path for your zsh with `which update_ohmyzsh`)
> git reset --hard HEAD~1
> git pull
> 
> should fix your issue

Thanks man. Worked for me.

**Comment by averyfreeman** [comment]
> I used git reset -- To revert the changes to the files causing the issues while upgrading and that let me upgrade. I am still unsure as to what caused this anomaly however

This worked for me - 
```
cd .oh-my-zsh
git reset

exit terminal - re open terminal
Greeted by update message, hit 'y'

update performed normally
```

**Comment by guanqin-123** [comment]
> cd $ZSH/ ( if this variable is not set you discover the path for your zsh with `which update_ohmyzsh`)
> git reset --hard HEAD~1
> git pull
> 
> should fix your issue

Make sense.

**Comment by minaaaayk** [comment]
> cd $ZSH/ ( if this variable is not set you discover the path for your zsh with `which update_ohmyzsh`) git reset --hard HEAD~1 git pull
> 
> should fix your issue

It's work. Thank You
