### ISSUE TITLE
Why doesn't the `omz update` command work?

### ISSUE THREAD

**Issue by liby** [ohmyzsh/ohmyzsh#9175]
**Describe the bug**
When I ran the `upgrade_oh_my_zsh` command on my iMac the other day, I was prompted that this command has been abandoned. Please use `omz update` instead.

But today I used the `upgrade_oh_my_zsh` command on MBP and ran it many times without seeing similar prompts again, and directly running `omz update` doesn't work either.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. After running the `upgrade_oh_my_zsh` command
2. You are prompted to use the `omz update` command instead
3. Try to run the `omz update` command

**Expected behavior**
If you try to run the `omz update` command, you will upgrade and update normally as usual.
But in fact, there is no similar prompt, and the `omz` command does not work.

**Screenshots and/or Recordings**
![image](https://user-images.githubusercontent.com/38807139/90153919-1c809380-ddbc-11ea-9e0c-38b4f69f08dd.png)

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro: [macOS]
 - Latest ohmyzsh update?: [Yes]
 - ZSH Version: [5.7.1 (x86_64-apple-darwin19.0)]
 - Terminal emulator: [iTerm2]

**Additional context**
As for the `omz update` command support and the replacement tip, I've found the relevant [commit](https://github.com/ohmyzsh/ohmyzsh/commit/3935ccce647c722bcfdaa771b01613079db20935#diff-395fc7e22b4a6ef8aacc81bee65def01) and [PR](https://github.com/ohmyzsh/ohmyzsh/pull/9094).

**Comment by liby** [comment]
![demo](https://user-images.githubusercontent.com/38807139/90155660-2905eb80-ddbe-11ea-9bb6-25c643de1b0e.gif)
It's really inexplicable. I went into the local folder of `oh my zsh`, and tries running the `_omz::update` command in a terminal. 
This is the function seen in the `cli.zsh` file.
As shown in the motion picture, after that, the `omz update` command is available, and I don't know what's going on.

**Comment by mcornella** [comment]
I'm going to mark this as solved then.

**Comment by TriMoon** [comment]
@liby maybe you have more than one version of omz installed in your path in different places?

**Comment by liby** [comment]
> @liby maybe you have more than one version of omz installed in your path in different places?

At the end of the demo.gif, you can see that I left the directory of `Oh my zsh` with the `cd` command, and I can still use the `omz update` command at this time.

**Comment by TriMoon** [comment]
You could try to provide the output of `alias zsh` and `command -v zsh` to be complete.
I think we both agree that there is something wrong going on...
Oh wait a second....hahaha
You are trying to execute `omz::update` which does not exist because the actual command should be `_omz::update` which zsh already tells you it corrected, but you need to be using `omz update` which omz should then translate internally to `_omz::update` which it actually does as seen in your last command...

So it seems your problem is that you started by trying to execute `omz::update` instead of `omz update`...

**Comment by liby** [comment]
@TriMoon 
Thank you for telling me so much.

> You could try to provide the output of alias zsh and command -v zsh to be complete.

![image](https://user-images.githubusercontent.com/38807139/90461138-141bb600-e138-11ea-93ec-1ec4bf9f4822.png)


> So it seems your problem is that you started by trying to execute omz::update instead of omz update...

Before I execute the `_omz::update:` command, I executed the `omz update` command and got the following output.
![image](https://user-images.githubusercontent.com/38807139/90460894-8213ad80-e137-11ea-9564-af0c8db20352.png)

After I executed the `_omz::update` command, I executed the `omz` command again, and the output changed.
![image](https://user-images.githubusercontent.com/38807139/90461055-e59ddb00-e137-11ea-8110-948f77354b5d.png)

So in that sense, the question is why `omz update` is available after the `_omz::update` command is executed？

**Comment by TriMoon** [comment]
Ah that was not clear, maybe change title of issue.
Have fun as i can not help further in this case...

**Comment by liby** [comment]
> maybe change title of issue.

Well, the title is named mainly because executing the `omz update` command at first had no effect. 
In the console output, it also shows that the commands available for `omz` do not include `omz update`.

It's weird to find it available again somehow after posting this issue.

> Have fun as i can not help further in this case.

I think we can ignore this for now, as I don't know how to reproduce it.

Finally, thank you.

**Comment by FFdhorkin** [comment]
looks like the reason `_omz::update` fixed it is because that restarts the shell. I was having the same result running `omz  update` until i restarted my shell after I manually ran upgrade_oh_my_zsh today. now `omz update` works
