### ISSUE TITLE
Awful directory listing colors

### ISSUE THREAD

**Issue by pavrip** [ohmyzsh/ohmyzsh#9179]
Hi
I am sorry about asking this lame question. I have looked everywhere and I am bashing my head against the wall.

I cant understand why so many amazing features are present but I cant make basic changes.

Basically I hate that cyan color with directory listing, it comes with the Oh my zsh terminal.

I want to completely change it to a dark red, 

How can I do this?

I have tried almost every theme but the directory listing is always a dark blue or that horrible cyan,

I want to customise the theme completely

**Comment by jamespeapen** [comment]
Could you share a screenshot and the theme you're using?

**Comment by pavrip** [comment]
Hi Yes, I deleted the whole thing.
It is practically in each and every theme, either the ugly cyan or a dark blue in arrow theme,
Please bare with me as I have been so busy with project deadlines, I will download again just to send it to you but will send on Monday, 

Thanks

**Comment by mcornella** [comment]
You need to change the `LSCOLORS` variable if using macOS or BSD, or the `LS_COLORS` variable if using other systems. You can use [this website](https://geoff.greer.fm/lscolors/) to generate a different color scheme.
