### ISSUE TITLE
Can user disable the echo of random.zsh-themes?

### ISSUE THREAD

**Issue by Freed-Wu** [ohmyzsh/ohmyzsh#9180]
in `themes/random.zsh-themes`, in the last line, there exists
```{.zsh}
echo "[oh-my-zsh] Random theme '${RANDOM_THEME}' loaded"
```
Can user disable the echo? i recommend to add a variable to allow user to disable or enable it?
it is a little advice... thanks!

**Comment by jamespeapen** [comment]
Instead of ```ZSH_THEME='random'``` use:
```
source $ZSH/themes/random.zsh-theme &>/dev/null
```

A similar issue was found in this pull request: #8011. 

If you want to use a variable in your zshrc, add ```ZSH_ECHO_THEME=false``` to your zshrc and replace that line in ```themes/random.zsh-themes``` with:
```
# echo theme name unless disabled
if [ -z "$ZSH_ECHO_THEME" ] || [ "$ZSH_ECHO_THEME" != false ]; then
    echo "[oh-my-zsh] Random theme '${RANDOM_THEME}' loaded"
fi
```

**Comment by Freed-Wu** [comment]
```{.zsh}
# echo theme name unless disabled
if [ -z "$ZSH_ECHO_THEME" ] || [ "$ZSH_ECHO_THEME" != false ]; then
    echo "[oh-my-zsh] Random theme '${RANDOM_THEME}' loaded"
fi
```
looks like good because it gives user a right to choose whether to echo the prompt information. can add it to oh-my-zsh?

**Comment by sysdl132** [comment]
@jamespeapen the quick way is :
```shell
if [ -z "$ZSH_ECHO_THEME" ] || [ "$ZSH_ECHO_THEME" != false ]; then
    # echo "[oh-my-zsh] Random theme '${RANDOM_THEME}' loaded"
fi
```

**Comment by jamespeapen** [comment]
@sysdl132 without the echo statement, the theme name will not be displayed regardless of the setting

**Comment by mcornella** [comment]
A way to fix this while the random theme isn't modified is to add a random theme in `$ZSH_CUSTOM` that sources the main random theme silently. Here's a oneliner that does this:
```zsh
echo 'source "$ZSH/themes/random.zsh-theme" &>/dev/null' > "$ZSH_CUSTOM/themes/random.zsh-theme"
```

**Comment by mcornella** [comment]
You can now set `ZSH_THEME_RANDOM_QUIET=true` to silence this message.
