### ISSUE TITLE
Use full path to avoid aliases or other overrides

### ISSUE THREAD

**Issue by dhanak** [ohmyzsh/ohmyzsh#9183]
https://github.com/ohmyzsh/ohmyzsh/blob/079e7bb5e0a79171f3356d55d3f6302a82645a39/plugins/wd/wd.sh#L217

Greetings! I'm using cp, mv and rm aliases in my shell to override default behavior (namely, I alias them to `cp -i`, `mv -i` and `rm -i` respectively, to avoid accidental overwrites), which kind of breaks this update script. It is always good practice to use such commands with their full path (`/bin/cp`, `/bin/rm`), to avoid being overridden. Thanks in advance for the fix, and keep up the good work! I really enjoy using oh-my-zsh!

**Comment by mcornella** [comment]
The wd plugin is a bundle of the upstream project. Post this in https://github.com/mfaerevaag/wd.

**Comment by dhanak** [comment]
Okay, thanks for the info. I'll do that.
