### ISSUE TITLE
command not found: omz

### ISSUE THREAD

**Issue by TheSolly** [ohmyzsh/ohmyzsh#9184]
**Describe the bug**
I used to update my ohmyzsh periodically through the `upgrade_oh_my_zsh` with no issues, from a while i begin to get the message that this method will be deprecated and one should use `omz update`. but when i run this command i get the below error message. looking through the documentation, it is still mentioning `upgrade_oh_my_zsh` as the upgrade method.

**Screenshots and/or Recordings**
![image](https://user-images.githubusercontent.com/31882844/90403304-11ba4d00-e0a1-11ea-9de2-65aaff5b847a.png)

**Desktop (please complete the following information):**

 - OS / Distro: [macOS]
 - Latest ohmyzsh update?: [Yes]
 - ZSH Version: [5.8]
 - Terminal emulator: [iTerm2]

**Comment by mcornella** [comment]
Are you using `antigen`, `zgen` or another plugin manager, or is this a standard OMZ installation? If the latter, run `git -C $ZSH rev-parse HEAD` and post the output.

**Comment by mcornella** [comment]
I haven't been able to reproduce this problem, can you do both of these and post the output?
1. `git -C "$ZSH" reflog --abbrev master | head -20`.
2. `zsh -xvic exit &> ~/omz-debug.log` and post the omz-debug.log file generated in the home directory.

**Comment by TheSolly** [comment]
> Are you using antigen, zgen or another plugin manager
I am using zplug...

> git -C "$ZSH" reflog --abbrev master | head -20.

![image](https://user-images.githubusercontent.com/31882844/90488299-036d3f00-e13c-11ea-8275-6d858ee9b018.png)

> zsh -xvic exit &> ~/omz-debug.log
[Uploading omz-debug.log…](omz-debug.log)

**Comment by mcornella** [comment]
This seems to be an issue with zplug, I can't find out why it doesn't source the cli.zsh file. Can you submit a bug report in their repo?

**Comment by mcornella** [comment]
Seeing as there's no answer from zplug, try `zplug clear` and restart the zsh session with `exec zsh`.

**Comment by mcornella** [comment]
Is the file at `$ZSH/lib/cli.zsh` empty?

**Comment by TheSolly** [comment]
@mcornella No it is not empty, filled with `omz::` functions.

**Comment by mcornella** [comment]
I don't know zplug specifics, you might get better luck giving more details in the zplug issue.

**Comment by mcornella** [comment]
It looks like you're not loading files from inside the lib folder. Use
```zsh
zplug "lib/*",   from:oh-my-zsh
```

**Comment by TheSolly** [comment]
@mcornella ^ this line in `.zshrc` file fixed it. Thanks for your support.

**Comment by Kiisso** [comment]
Hello, what kind of software is used in the terminal of your blue interface?

**Comment by mcornella** [comment]
Looks like they have their dotfiles synced with github at https://github.com/TheSolly/env-setup. They are using powerlevel10k with this configuration: https://github.com/TheSolly/env-setup/blob/master/.p10k.zsh.
