### ISSUE TITLE
No option to open a bug report on GH

### ISSUE THREAD

**Issue by Gvald** [ohmyzsh/ohmyzsh#9190]
**Describe the bug**
(Kind of oxymoron, because this **is** a bug report. ~~But this one created with a hack, which will be described later...~~)

**To Reproduce**
1. Click on [![](https://img.shields.io/badge/-New%20issue-2ea44f)](https://github.com/ohmyzsh/ohmyzsh/issues/new/choose)
2. Click on [![](https://img.shields.io/badge/-Get%20Started-2ea44f)](https://github.com/ohmyzsh/ohmyzsh/issues/new?labels=Type%3support&template=bug_report.md) in the `Bug report` section. 
3. Fill out the bug report, and click on ![](https://img.shields.io/badge/-Submit%20new%20issue-2ea44f)
4. Observe the tag of the opened issue: the issue will be tagged as [![](https://img.shields.io/badge/-Type%3A%20support-2ea44f)](../labels/Type:%20support) instead of [![](https://img.shields.io/badge/-Type%3A%20bug-f00)](../labels/Type:%20bug)

**Expected behavior**
Issue should opened as [![](https://img.shields.io/badge/-Type%3A%20bug-f00)](../labels/Type:%20bug) type.

**Cause for this misbehave**
The link of [![](https://img.shields.io/badge/-Get%20Started-2ea44f)](https://github.com/ohmyzsh/ohmyzsh/issues/new?labels=Type%3A+support&template=bug_report.md) in the `Bug report` is broken.
Hover on the `Get Started` button will reveal `labels=Type%3A+support` in the link address, whilst it should be `labels=Type%3A+bug`.

~~**How did this issue opened as 'Type: bug' then?**~~
~~As described above, I just changed the `labels=Type%3A+support` to `labels=Type%3A+bug`, paste the new address in the browser, and that's it... 😄~~

**Comment by Gvald** [comment]
Obviously, the 'hack' didn't work... 😢 
Issue is still opened up as `support`

**Comment by mcornella** [comment]
This is by design. A lot of users were using the bug report form for things that weren't bugs, or weren't bugs in OMZ. This way only a maintainer can apply the label once it's verified to be a bug in OMZ.
