### ISSUE TITLE
docker plugin error

### ISSUE THREAD

**Issue by OscarSotoSanchez** [ohmyzsh/ohmyzsh#9191]
**Describe the bug**
I added the docker plugin to enable autocompletion. However when i pulse double tab only i can autocomplete the commands `daemon and help` the other commands not autocomplete well. 

**Screenshots and/or Recordings**
![Screenshot from 2020-08-20 12-33-27](https://user-images.githubusercontent.com/12794770/90760701-90ea9380-e2e2-11ea-8d66-fd0e807be941.png)

**Desktop (please complete the following information):**

 - OS / Distro: [Ubuntu 20.04]
 - Latest ohmyzsh update?: [Yes]
 - ZSH Version: [5.8]
 - Terminal emulator: [Terminator]

**Comment by naveen-kumar-r** [comment]
Please try clearing completion [cache](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-reset-the-completion-cache).

```
# Delete the completion cache
rm "$ZSH_COMPDUMP"
# Restart the zsh session
exec zsh
```

Completion errors FAQ [here](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#completion-issues)

~ Naveen

**Comment by mcornella** [comment]
What docker version do you have? Also, follow step 3 in https://github.com/ohmyzsh/ohmyzsh/wiki/Troubleshooting#completion-problems to capture a trace of the completion function and post the generated file.

**Comment by thatnerdjosh** [comment]
@OscarSotoSanchez on your exact environment (except I don't know what ohmyzsh version you were on), I can't reproduce this. Try updating to the latest ohmyzsh version, and also try @naveen-kumar-r suggestion

Let us know, thanks!
