### ISSUE TITLE
I have error after the last update: parse error near `<<<'

### ISSUE THREAD

**Issue by ProgrammingLife** [ohmyzsh/ohmyzsh#9192]
After the last update of oh-my-zsh I always receive the following error on every terminal start:

> /home/prolife/.oh-my-zsh/lib/key-bindings.zsh:18: parse error near `<<<'

At that line of key-bindings.zsh I have the following code:
```
<<<<<<< Updated upstream
# Use emacs key bindings
bindkey -e
=======
#bindkey -e                                            # Use emacs key bindings
>>>>>>> Stashed changes
```

How to repair it?

 - OS / Distro: Linux Mint 19.1
 - Latest ohmyzsh update?: Yes
 - ZSH Version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
 - Terminal emulator: urxvt

**Comment by mcornella** [comment]
It looks like it failed to resolve a conflict with your local modification of lib/key-bindings.zsh. You have to resolve it first yourself.

**Comment by mcornella** [comment]
Probably what you want is to just change all ofn that to just commenting the line `bindkey -e`.
