### ISSUE TITLE
C-r History copying 2 characters on navigation

### ISSUE THREAD

**Issue by danthegoodman1** [ohmyzsh/ohmyzsh#9197]
When ever I use the C-r history, and use the up/down arrows (or type), the first 2 characters from the line I am interactive with seem to prepend the rest of the line (see images below). I've tried updating my ZSH, which hasn't seem to have changed anything. This did just start happening out of nowhere as well.

 Not sure where to go from here, any help would be super appreciated!

![image](https://user-images.githubusercontent.com/17806508/90955820-b4325180-e44e-11ea-80a8-fc723a4e11c6.png)

![image](https://user-images.githubusercontent.com/17806508/90955854-0a9f9000-e44f-11ea-9324-c86e20472f3f.png)

**Comment by mcornella** [comment]
> I wonder if it has something to do with the `znt-history-widget`, `n-history`, or `znt-usetty-wrapper` since that is what ^R triggers.

It might be that yes. Try to disable it and see if the bug stops. If so, look up the upstream project for solutions: https://github.com/psprint/zsh-navigation-tools.

**Comment by danthegoodman1** [comment]
Disabling it? Not sure how to do that in ZSH. Will I not have history then? I'll open an issue there in the mean time.

**Comment by danthegoodman1** [comment]
Looks like I'm not the only one! https://github.com/psprint/zsh-navigation-tools/issues/31

**Comment by mcornella** [comment]
> Disabling it? Not sure how to do that in ZSH. Will I not have history then? I'll open an issue there in the mean time.

You're sourcing zsh-navigation-tools in your zshrc file. I was suggesting commenting that out.

I'll close this since this is not really OMZ's fault.

**Comment by danthegoodman1** [comment]
Thanks for the help, turns out using 5.7.1 instead of 5.8 fixes the issue!

**Comment by mbenatti** [comment]
anyone managed to downgrade on ubuntu 20 ?
