### ISSUE TITLE
Why are the outputs of `ls` not aligned?

### ISSUE THREAD

**Issue by couragelfyang** [ohmyzsh/ohmyzsh#9200]
**Describe the bug**
The outputs of `ls` are not aligned. The first tab is often replaced by a space.

**To Reproduce**
run `ls` in any directory

**Expected behavior**
The gaps between items should be either spaces or tabs.

**Screenshots and/or Recordings**
<img width="821" alt="Screen Shot 2020-08-22 at 23 03 31" src="https://user-images.githubusercontent.com/9023177/90958006-357bf980-e4cc-11ea-98f0-f2e34bb11bc0.png">
<img width="793" alt="Screen Shot 2020-08-22 at 23 03 36" src="https://user-images.githubusercontent.com/9023177/90958007-3745bd00-e4cc-11ea-92a0-7d72027cba96.png">

**Desktop (please complete the following information):**

 - OS / Distro: macOS Catalina 10.15.6
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.7.1
 - Terminal emulator: latest iterm2

I have also tried `ls` on default terminal and it does as well.

**Comment by mcornella** [comment]
This is not an OMZ issue.

**Comment by jasonjacinth** [comment]
@mcornella so this spacing issue is basically because of how MacOS handles colored ls command (ls -G)?

**Comment by mcornella** [comment]
It's because of how it computes the width of each column. If there is a very long cell (directory/file name), the column width is going to be very large, and shorter files will appear with more padding.
