### ISSUE TITLE
Font error

### ISSUE THREAD

**Issue by Windslab** [ohmyzsh/ohmyzsh#9201]
Hi after installing I got this:

![image](https://user-images.githubusercontent.com/60715874/90964581-87238480-e4ca-11ea-9264-4704f09de6ce.png)

What wrong?

**Comment by mcornella** [comment]
Look in the settings of your terminal, that's the program in the screenshot you posted first.

**Comment by mcornella** [comment]
In the terminal program above, the settins probably are in the File or Edit menus.

**Comment by Windslab** [comment]
Can you write me a command?

вс, 23 авг. 2020 г., 23:07 Marc Cornellà <notifications@github.com>:

**Comment by mcornella** [comment]
It's not a command problem, you need to change the settings in the GUI of the terminal program, using your mouse.
