### ISSUE TITLE
I recorded a scenario on a website.Is it right.

### ISSUE THREAD

**Issue by sysdl132** [ohmyzsh/ohmyzsh#9202]
# About install oh my zsh and use

Go to the scenario bu this link -> [I'm a link](https://katacoda.com/sysdl132/scenarios/zsh)

So is it have any bugs?

- [ ] intro bugs
- [ ] Command bugs
- [ ] Describe bugs
- [ ] Other bugs(comment what bug in a new reply)

**Note** : If you want to see source code,view it in [sysdl132/katacoda-scenarios](https://github.com/sysdl132/katacoda-scenarios)  

**Note 2** : My session is running on ubuntu 18.04, not 20.04

**Comment by mcornella** [comment]
It looks fine, though the website itself is really hard to use. Thanks
