### ISSUE TITLE
Fresh Arch Linux setup

### ISSUE THREAD

**Issue by Windslab** [ohmyzsh/ohmyzsh#9204]
Please help to fix the font:

![image](https://user-images.githubusercontent.com/60715874/90987386-565b5200-e593-11ea-98a0-941214ea7ddd.png)

Installing the neded font does't give me a positive dynamics. :(

**Comment by mcornella** [comment]
You already opened https://github.com/ohmyzsh/ohmyzsh/issues/9201, why are you opening a new one? Comment on that issue instead.
