### ISSUE TITLE
Plugin vagrant-prompt does not work on macOS (due to BSD vs GNU grep behavior)

### ISSUE THREAD

**Issue by programmer04** [ohmyzsh/ohmyzsh#9207]
Howdy!

Plugin [vagrant-prompt](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/vagrant-prompt) does not work on any system which has `BSD` utils by default e.g. `macOS`. `BSD grep` does not support flag `-P` which stands for PCRE (Perl Compatible Regular Expressions). An attempt to use this plugin on `macOS` ends with:

```
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
```
The line from the plugin which uses feature specific to `GNU grep` and causes a crash:

https://github.com/ohmyzsh/ohmyzsh/blob/cfb86cd08d3b24fd4b59d0d35b3af1f589c891fa/plugins/vagrant-prompt/vagrant-prompt.plugin.zsh#L21

rewriting the above line to `Perl` fixes an issue. `Perl` supports this regex syntax and is available on various `Linux` distributions and `macOS`. Suggested change:

```
statuses=$(vagrant status 2> /dev/null | perl -nle'print if m{\w+\s+[\w\s]+\s\(\w+\)}')
```

Tested with this change on `macOS` and works as expected. Please @alberto-re let me know what do you think about this change, I'll be happy to make a PR with it 🙂

**Comment by flokli** [comment]
Hmm… I'm not sure if requiring `perl` in more places is a good idea - see https://github.com/ohmyzsh/ohmyzsh/pull/9210 where relying on `perl` being in `$PATH` did bite me.

Maybe this can be solved by `sed` instead?

**Comment by mcornella** [comment]
Can you submit sample output from `vagrant status` so I can iterate on a better alternative? It doesn't have to be accurate, it can just be placeholders.

**Comment by programmer04** [comment]
Here you are @mcornella 
```zsh
λ ~/D/m/c-fun> vagrant status                                                                                                                       
==> vagrant: A new version of Vagrant is available: 2.2.10 (installed version: 2.2.9)!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

Current machine states:

default                   saved (virtualbox)

To resume this VM, simply run `vagrant up`.
```

**Comment by mcornella** [comment]
Though I have pretty much an idea, just to be sure, now only stdout, so `vagrant status 2>/dev/null`.

**Comment by programmer04** [comment]
```zsh
λ ~/D/m/c-fun> vagrant status 2>/dev/null                                                                                                           
Current machine states:

default                   saved (virtualbox)

To resume this VM, simply run `vagrant up`.
```

**Comment by mcornella** [comment]
Can you try this modification?
```zsh
function vagrant_prompt_info() {
  local vm_states vm_state
  if [[ -d .vagrant && -f Vagrantfile ]]; then
    vm_states=(${(f)"$(vagrant status 2> /dev/null | sed -nE 's/^.*(saved|poweroff|running|not created) \([[:alnum:]_]+\)$/\1/p')"})
    printf '%s' $ZSH_THEME_VAGRANT_PROMPT_PREFIX
    for vm_state in $vm_states; do
      case "$vm_state" in
        saved) printf '%s' $ZSH_THEME_VAGRANT_PROMPT_SUSPENDED ;;
        running) printf '%s' $ZSH_THEME_VAGRANT_PROMPT_RUNNING ;;
        poweroff) printf '%s' $ZSH_THEME_VAGRANT_PROMPT_POWEROFF ;;
        "not created") printf '%s' $ZSH_THEME_VAGRANT_PROMPT_NOT_CREATED ;;
      esac
    done
    printf '%s' $ZSH_THEME_VAGRANT_PROMPT_SUFFIX
  fi
}
```

**Comment by programmer04** [comment]
I tested you snippet @mcornella and it works as expected 👏
