### ISSUE TITLE
terminal issue

### ISSUE THREAD

**Issue by abdoulayegk** [ohmyzsh/ohmyzsh#9208]
Hey I am having this issue I would like help it is showing like this .oh-my-zsh git:(master) but I don't like it I want to it to look like -> only
![Screenshot from 2020-08-28 04-40-10](https://user-images.githubusercontent.com/51192943/91503691-c7c73780-e8e8-11ea-895f-d004313ab0ed.png)

how can I solve this issue?

**Comment by mcornella** [comment]
If what you mean is you want it to only show the arrow, like this:
![image](https://user-images.githubusercontent.com/1441704/91563395-0e478100-e93f-11ea-97de-61f56197f8d2.png)
then you can skip setting a theme and only add this line at the bottom of your zshrc file:
```zsh
PROMPT="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )%{$reset_color%} "
```

**Comment by abdoulayegk** [comment]
All right thanks
