### ISSUE TITLE
Make a suggestion,  change  YS_VCS_PROMPT_PREFIX2

### ISSUE THREAD

**Issue by wyh1791** [ohmyzsh/ohmyzsh#9209]
https://github.com/ohmyzsh/ohmyzsh/blob/8d08f1634a7b9782e3722ce770e8630f569afe3f/themes/ys.zsh-theme#L10

Make a suggestion, change 

YS_VCS_PROMPT_PREFIX2=":%{$fg[cyan]%}"

as

YS_VCS_PROMPT_PREFIX2=" %{$fg[cyan]%}"

becase, in some cases, double-clicking cannot select the git branch name, the selected one is "git:master", but the one you want to select is "master"

**Comment by mcornella** [comment]
Conversation continues in #9221.
