### ISSUE TITLE
Move pip plugin's cache file to $XDG_CACHE_HOME/pip which is ~/.cache/pip by default 

### ISSUE THREAD

**Issue by rekaerst** [ohmyzsh/ohmyzsh#9213]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
pip

**Is your feature request related to a problem? Please describe.**
Python-pip doesn't put its cache files into ~/.pip since a long time ago. They move cache files in $XDG_CONFIG_HOME/pip which is ~/.cache/pip by default. 
```bash
arthur@streaker:~$tree .cache/pip
.cache/pip
├── http
│   └── 8
│       └── 2
│           └── f
│               └── d
│                   └── 8
│                       └── 82fd835af304644b417e2e805b44d1181077da8bd78fad2fb38eb199
└── selfcheck
    └── 241e69162522ccf5846a2f42ebc24b17464915a155679666b89a9f31
```
but oh-my-zsh pip plugin still put zsh-cache into the old place which is ~/.pip. UNIX-like already had to many dotfiles in the user's home folder. It would be nice if we could reduce some.
**Describe the solution you'd like**
check if $XDG_CACHE_HOME/pip exists before fallback to ~/.pip
```bash
if [[ -d $XDG_CACHE_HOME/pip ]]
then
	ZSH_PIP_CACHE_FILE=$XDG_CACHE_HOME/pip/zsh-cache
else
	ZSH_PIP_CACHE_FILE=~/.pip/zsh-cache
fi
```
**reference**
https://pip.pypa.io/en/latest/reference/pip_install/#caching

**Comment by mcornella** [comment]
Nice! Can you submit a PR?

**Comment by mcornella** [comment]
Also, I believe `$XDG_CACHE_HOME` might not be defined and should default to `$HOME/.cache`, can you use this instead?
```zsh
if [[ -d "${XDG_CACHE_HOME:-$HOME/.cache}/pip" ]]; then
	ZSH_PIP_CACHE_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/pip/zsh-cache"
else
	ZSH_PIP_CACHE_FILE=~/.pip/zsh-cache
fi
```

**Comment by rekaerst** [comment]
Thanks for your suggestion. RP created #9299
