### ISSUE TITLE
complete:13: command not found: compdef and it cannot be solved by any mehod mentioned before

### ISSUE THREAD

**Issue by Stevenyyi** [ohmyzsh/ohmyzsh#9215]
Hi team, 
I met this error from ytd. I saw there was an issue with the same question. but I tried every method mentioned in that issue and it didn't help at all. 
my zsh version : zsh 5.7.1 (x86_64-apple-darwin19.0)
when I tired to delete zcompdump files, it's said cannot find that file:
$ rm ~/.zcompdump*
rm: /Users/yangyi/.zcompdump*: No such file or directory

**Comment by mcornella** [comment]
Did you fix this?
