### ISSUE TITLE
The wrong font sumbols

### ISSUE THREAD

**Issue by Windslab** [ohmyzsh/ohmyzsh#9222]
Hi I got an this:

![image](https://user-images.githubusercontent.com/60715874/91711131-0df0f500-eb8e-11ea-9605-d8b05ebaab49.png)

Let me please understand what is font uses ohmyzsh, I been installed an Powerline font like this:

```
# clone
git clone https://github.com/powerline/fonts.git --depth=1
# install
cd fonts
./install.sh
# clean-up a bit
cd ..
rm -rf fonts
```

And like this:
`pacman -S powerline powerline-fonts`

Also I did a:
`sudo fc-cache -f -v`

Before `startx` a shell looks like this:

![image](https://user-images.githubusercontent.com/60715874/91711442-9079b480-eb8e-11ea-8161-89dd48f4d085.png)

Please see my dotfiles:
https://github.com/Windslab/dotfiles

**Comment by mcornella** [comment]
What terminal are you using in the first image?

**Comment by Windslab** [comment]
> What terminal are you using in the first image?

![image](https://user-images.githubusercontent.com/60715874/91767088-46232280-ebe4-11ea-913e-1292ce2669bc.png)

**Comment by mcornella** [comment]
Look up `powerline font for urxvt`. This is something that came up: https://powerline.readthedocs.io/en/master/tips-and-tricks.html#rxvt-unicode
