### ISSUE TITLE
Git pull and push ask credentials

### ISSUE THREAD

**Issue by HasanLisbon** [ohmyzsh/ohmyzsh#9224]
Hello there I am using oh my zsh as a terminal shell on windows 10. Before I used git bash. On git bash when I trying to push or pull code it was not prompting to put user name and password of my company. But on oh my zsh it is asking the credentials. Why is that? Is there any solution to that?

**Comment by mcornella** [comment]
`git bash` uses a different system than (presumably) WSL. You need to add git credentials (using ssh) to the system you're using Oh My Zsh on, which is probably WSL. For example: https://docs.github.com/es/github/authenticating-to-github/connecting-to-github-with-ssh
