### ISSUE TITLE
pipenv plugin fails with _togglePipenvShell:14: command not found: pipenv on NEW TAB

### ISSUE THREAD

**Issue by januszm** [ohmyzsh/ohmyzsh#9225]
**Describe the bug**
For a while now, when I start a new terminal **tab** (with CMD-T on mac OS X) with both Mac OS X Terminal and ITerm2, I see:

```bash
_togglePipenvShell: 14: command not found: pipenv
```
and pipenv shell is not started.

pipenv is obviously installed, the error only shows up after starting a new tab, not when `cd project_directory`.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable plugin `pipenv`
2. Start terminal
3. `cd` into project directory with Pipenv
4. Confirm that `pipenv shell` is initialized `Launching subshell in virtual environment… .../bin/activate`
5. Start new Tab with Cmd+T

**Expected behavior**
pipenv shell should be initialized, there shouldn't be any error message

**Desktop (please complete the following information):**

 - OS / Distro: Mac OS X 10.15.6 Catalina
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.7.1
 - Terminal emulator: iTerm2 and standard Mac OS X Terminal

**Additional context**
Dotrcs:

```
plugins=(
  git
  bundler
  kubectl
  nvm
  osx
  pipenv
  pyenv
  python
  rake
  rvm
  ruby
)
PIPENV_VENV_IN_PROJECT=1
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
```

**Comment by shuhikari** [comment]
Maybe this post should help

https://github.com/pypa/pipenv/issues/1058

**Comment by januszm** [comment]
It only happens when I start new Terminal tab/shell (while being inside the project directory set up with pipenv). 
It seems to me that the issue you mentioned applies to the pipenv shell command in general.

Nevertheless, reinstalling pipenv (`pip install --upgrade pipenv`) + `pyenv rehash` helped.
Since I haven't touched pipenv or pyenv for a while, I was suspecting either ohmyzsh or ohmyzsh's pipenv plugin to cause this issue.

**Comment by julioselva** [comment]
I had the same issue. The cause was having the PATH env loading the `~/.local/bin/` after the plugin, so the command was not being found and then ignoring the rest of the script.

Updating my `~/.zshrc` to have the PATH being overwritten on the first line fixed the issue.
