### ISSUE TITLE
shrink-path change view using shortcut

### ISSUE THREAD

**Issue by debek** [ohmyzsh/ohmyzsh#9227]
Hi!
My path uses not the full path of my current directory.
For example: ~/Dow/test/test-124-12424-fsfs-232442-fsf-/forum/something

Like you can see instead "Download" is "Dow".
I would like to use keyboard shortcut which will show me the original path and undo this using the same shortcut.

How can I achieve that?

**Comment by mcornella** [comment]
Fixed in https://github.com/ohmyzsh/ohmyzsh/pull/9794. Please try it out with `omz pr test 9764` and then following the instructions for setting up the keyboard shortcut documented in the README.
