### ISSUE TITLE
I want to modify my zsh prompt

### ISSUE THREAD

**Issue by codingonsteroid** [ohmyzsh/ohmyzsh#9229]
I like robbyrussell theme by I don't want it to show my PC username. I'm using WSL2 and terminal(with Ubuntu). And I want it to say `codingonsteroid💉💉💉 ➜ _(yes I want to use emoji)_

Instead of my `PC_USER_NAME ➜`

**robbyrussell.zsh-theme file**
```
PROMPT="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
PROMPT+=' %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
```

**Comment by ibnjunaid** [comment]
Can you post a screenshot of where it shows you PC_USER_NAME .

**Comment by codingonsteroid** [comment]
![test](https://user-images.githubusercontent.com/69804298/92073680-eb4f1e00-edd1-11ea-9e80-5a04173bde44.PNG)
@ibnjunaid

**Comment by ibnjunaid** [comment]
So you wanna change you name appearing at the shell header

**Comment by codingonsteroid** [comment]
no, I want to change my shell prompt name. I mentioned that clearly

**Comment by mcornella** [comment]
You can prefix that in the first PROMPT assignment:
```zsh
PROMPT="codingonsteroid💉💉💉 %(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
PROMPT+=' %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
```
Put this in your own custom theme file, see [adding themes](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes) for more info.

**Comment by codingonsteroid** [comment]
@mcornella where can I learn about zsh's syntax. I hacked the colour code like some code monkey. Want to understand it better. Like some quick guide and stuff
```
PROMPT="$fg_bold[green]codingonsteroid💉💉💉 %(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
PROMPT+=' %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"```


added green colour ```$fg_bold[green]codingonsteroid```

**Comment by mcornella** [comment]
See [Prompt expansion](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html) to understand what does `%` sequences mean. And as for color, you can either use prompt expansion (see previous link) or the `$fg`, `$bg`, `$fg_bold` and other variables that the [colors function](https://github.com/zsh-users/zsh/blob/17ee9c5f68d18ef48c1ef99ae6162a06675104f2/Functions/Misc/colors) provides (see comments).

**Comment by codingonsteroid** [comment]
Thanks
