### ISSUE TITLE
vi-mode: Shell hotkeys to jump forward words no longer work

### ISSUE THREAD

**Issue by ecbrodie** [ohmyzsh/ohmyzsh#9230]
**Describe the bug**

Escape sequence hotkeys to jump forward words no longer work when the `vi-mode` plugin is enabled.

In iTerm, I typically map option-left and option-right to jump backwards and forward words, respectively, via escape sequences, [as documented here](https://coderwall.com/p/h6yfda/use-and-to-jump-forwards-backwards-words-in-iterm-2-on-os-x). With `vi-mode` enabled, only the jump back will work and not the jump forwards.

I know that these hotkeys are not quite necessary when I have vi/vim enabled on a shell command because I can just use vim keystrokes instead of hotkeys to jump between words. However, these hotkeys are universally used across Mac OS and old habits die hard. It would be ideal for `vi-mode` to continue to support this escape sequence.

**To Reproduce**

1. Ensure the above documentation is followed to map option-left and option-right to escape sequences for jumping words
1. Enable plugin 'vi-mode`
1. Enter in a shell command that has multiple words
1. Try using option + arrow keys to jump between words

**Expected behaviour**

I can jump between words as expected

**Actual behaviour**

Only jump backwards works. When I try jumping forwards, the shell does nothing, but it seems to wait for me to enter in another prompt. When I do, the command moves to a line below and a single ASCII character appears in the current line. There must be a different way that `vi-mode` is handling the `^f` escape sequence.

**Desktop (please complete the following information):**

 - OS / Distro: Mac OS 10.15.6
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: iTerm2 3.3.12

**Comment by mcornella** [comment]
What does `bindkey '^[f'` return? Can you say since when this started happening, most preferably a commit that used to work correctly?
