### ISSUE TITLE
Font color change sticks after tab completion

### ISSUE THREAD

**Issue by tschaub** [ohmyzsh/ohmyzsh#9232]
**Describe the bug**

When I click `tab` to complete (a file path for example), the font color of my previously entered text changes.  This new color "sticks" - it applies not only to new text that I enter, but output of the next command that runs.

Here is a movie that demonstrates the behavior.

The unexpected part is that the lighter font color applies to the `ls` output and the characters that I type after `tab`.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Set `ZSH_THEME="avit"` in `~/.zshrc`
2. Type `ls -al ~/.zsh` + `tab`
3. See the font color change
4. Type some more text like `*` and then `enter`

**Expected behavior**
I expected the font color of the output to return to normal.

**Movie**

![dim](https://user-images.githubusercontent.com/41094/92190203-bec0f380-ee1d-11ea-864c-ed69bf24e913.gif)

The unexpected part is that the output of the `ls` command is the lighter font color after `tab` completion.

**Desktop (please complete the following information):**

 - OS / Distro: macOS
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator: Terminal.app

**Additional context**

I just found #8952 which might have some overlap, but that was fixed with 8cb449ee2068a52fd386a9426b70b8f89f100e7c.

**Comment by mcornella** [comment]
Can you try commit f96d18ca to see if the same happened before?

**Comment by tschaub** [comment]
@mcornella according to `git bisect`: 77813a330bbc716503dcc4d8d98b6d8ae6f74d03 is the first bad commit.

**Comment by mcornella** [comment]
Update with `omz update` to get the fix. I've tested it works in your environment but let me know if there's a problem.

**Comment by tschaub** [comment]
Thanks for the fix, @mcornella!
