### ISSUE TITLE
Brew cask uninstall autocompletion uses deprecated command

### ISSUE THREAD

**Issue by PythonCoderAS** [ohmyzsh/ohmyzsh#9233]
**Describe the bug**

The autocompletions for `brew cask uninstall <...>` uses a deprecated command. 

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Type `brew cask uninstall`
2. Hit tab
3. Hit tab again

**Expected behavior**

The correct command should be used.

**Screenshots and/or Recordings**
Warning displayed: `Warning: Calling brew cask list is deprecated! Use brew list --cask instead.`

https://asciinema.org/a/sQgmLxEeYQEbqZemIem9P2JoH

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro: [e.g. Arch Linux, macOS] MacOS
 - If on Windows what version of WSL: [e.g. WSL1, WSL2]
 - Latest ohmyzsh update?: [e.g. Yes/No] Yes
 - ZSH Version: [e.g. 5.6] zsh 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator: [e.g. iTerm2] iTerm2

**Additional context**
Add any other context about the problem here. This can be themes, plugins, custom configs.
~/.zshrc: `COMPLETION_WAITING_DOTS="true"`

**Comment by danielfalbo** [comment]
+1

**Comment by mcornella** [comment]
`brew` completion is provided by Homebrew itself, this is an issue in Homebrew: https://github.com/Homebrew/brew/issues/8709.

**Comment by Akylzhan** [comment]
That's strange, I use zsh and autocompletion does not display the warnings
