### ISSUE TITLE
omz update - Listed in Readme.md for manual updating but is not available

### ISSUE THREAD

**Issue by justinbacle** [ohmyzsh/ohmyzsh#9240]
**Describe the bug**
`omz update` is the expected way to manually update (from README.md) but is not available as a command

**To Reproduce**
`omz update`
outputs : 

```
Usage: omz <command> [options]

Available commands:

    help                Print this help message
    pr <command>        Commands for Oh My Zsh Pull Requests
```

**Expected behavior**
update script should launch ?
`update_ohmyzsh` works as expected though

**Desktop (please complete the following information):**

 - OS / Distro: Ubuntu 
 - If on Windows what version of WSL: WSL1
 - Latest ohmyzsh update?: (how to check ?)
 - ZSH Version: 5.8
 - Terminal emulator: Windows Terminal

**Comment by mcornella** [comment]
You need the latest update of OMZ for that to apply. Run `upgrade_oh_my_zsh` to update.
