### ISSUE TITLE
MacOS /usr/local/share/zsh folder permissions

### ISSUE THREAD

**Issue by raxetul** [ohmyzsh/ohmyzsh#9242]
**Describe the bug**
Abstract: Permissions for user is ok but for the group seems not to be right.

When I set users of these folders as chown my-user:admin and their permissions as chmod 755 seem to be ok.
But when I set users as chown root:admin and chmod 775 gives this error.

It doesn't make sense providing security by giving "write rights" to a user but not giving to a group, especially if the group is admin.

`[oh-my-zsh] Insecure completion-dependent directories detected:
drwxrwxr-x  3 root  admin   96 Nov 21  2018 /usr/local/share/zsh
drwxrwxr-x  5 root  admin  160 Aug 18 14:27 /usr/local/share/zsh/site-functions

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.`

**To Reproduce**
1. Add user to a group
2. Set owner of folders under /usr/local (not /usr/local but /usr/local/*) as root:admin by using chown
3. Set mod of folders under /usr/local (not /usr/local but /usr/local/*) as 775 by using chmod
4. Start a shell

**Expected behavior**
Giving write permission for /usr/local/share/zsh to the admin group should not be a problem.

**Desktop (please complete the following information):**
 - OS / Distro: macOS
 - If on Windows what version of WSL: Catallina 10.15.6
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.7.1
 - Terminal emulator: iTerm2

**Comment by mcornella** [comment]
If the group isn't root, the compaudit call complains about that. The admin group isn't seen as the same as the root group. Since there isn't a way to make the compaudit call ignore that, you can bypass the compaudit call directly by setting `ZSH_DISABLE_COMPFIX=true` in your zshrc file, before OMZ is sourced.
