### ISSUE TITLE
git - repo's current master branch displays as "*1 !1 ?1"

### ISSUE THREAD

**Issue by ttntm** [ohmyzsh/ohmyzsh#9247]
Hi all, I spent some time researching this issue and looking at the docs, but unfortunately I couldn't find anything helpful out there.

I have one specific GitHub repository that's current (last commit + push was yesterday), yet still displays as `master *1 !1 ?1`. All other repositories I work with don't display any markers when `master` is clean (see screenshot for a comparison).

`git status` doesn't help, just says that everything's current and working tree is clean; `git log` doesn't tell me anything else either.

I'd really appreciate it if someone could either explain what those markers mean or point me to some resource where that's documented so I can find out why they're being displayed for that repo in the first place.

![Screenshot_20200910_102012](https://user-images.githubusercontent.com/41571384/92700569-43949b80-f34f-11ea-8dc0-5b4f14c918c1.png)

**Comment by mcornella** [comment]
Those are set up by the zsh theme, what theme are you using?

**Comment by ttntm** [comment]
I'm using powerlevel10k: `ZSH_THEME="powerlevel10k/powerlevel10k"`

Enabled plugins:
```
plugins=(
  git
  colored-man-pages
  history-substring-search
  sudo
  zsh-autosuggestions
  zsh-syntax-highlighting
)
```

I didn't change anything manually in `~/.p10k.zsh`, but in there is a function called `my_git_formatter` that seems to be responsible for the markers. Based on that, `*1 !1 ?1` would translate to 1 stash, 1 unstaged file and 1 untracked file - that's clearly not in accordance with what `git status` reports (and also not the case as far as I can tell).

**Comment by ttntm** [comment]
Yup, it was `git indeed` - `*1 !1 ?1` was correct, even though nothing showed up in `git status`.

Had to find the stash with `git stash list` and pop it, `git status -u` showed the untracked file and somehow `git add --all` caught the unstaged file that the alias `gaa` somehow didn't catch.

To sum it up: p10k work correctly and the symbols/markers are explained in `~/.p10k.zsh`.

**Comment by romkatv** [comment]
These symbols are documented here: https://github.com/romkatv/powerlevel10k/#what-do-different-symbols-in-git-status-mean
