### ISSUE TITLE
update_ohmyzsh fails because of missing git credentials

### ISSUE THREAD

**Issue by myxor** [ohmyzsh/ohmyzsh#9249]
**Describe the bug**
When i run `update_ohmyzsh` it fails as follows:

```➜ update_ohmyzsh                
Updating Oh My Zsh
From https://github.com/ohmyzsh/ohmyzsh
 * branch              master     -> FETCH_HEAD

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got '$username@$hostname.(none)')
Cannot save the current index state
Cannot autostash
There was an error updating. Try again later?
```

**To Reproduce**
I am not sure how to reproduce this behavior. It happens on only one of my machines.

**Expected behavior**
Update should proceed as designed and be successful.

**Desktop (please complete the following information):**

 - OS / Distro: Ubuntu 18.04
 - Latest ohmyzsh update?: No, because can't update
 - ZSH Version:  zsh 5.4.2 (aarch64-unknown-linux-gnu)
 - Terminal emulator:  xfce4-terminal

**Comment by mcornella** [comment]
Do you have local modifications to the repo, i.e. does `git status` report any modified files?

**Comment by myxor** [comment]
Yes sure, that was it - how stupid from me to not check this.
I reverted the local changes and now the update runs fine. 
I am closing this issue. Thanks @mcornella.
