### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by shubuu97** [ohmyzsh/ohmyzsh#9252]
I've recently installed oh-my-zsh and I noticed that after installing it I'm unable to use npm commands, it is unable to find node. 

I've also not recently switched from bash to zsh, I've been using zsh from past 7-8 months. 

Here is the screenshot of .zshrc file
![Screenshot 2020-09-13 at 4 17 22 PM](https://user-images.githubusercontent.com/33938128/93016807-76ee5900-f5e1-11ea-8776-804dc13574a0.png)
![Screenshot 2020-09-13 at 4 17 36 PM](https://user-images.githubusercontent.com/33938128/93016808-79e94980-f5e1-11ea-9ffe-839d8d3ade5c.png)

**Comment by mcornella** [comment]
Did you have a previous zshrc file with your `$PATH` modification? If so, try to find it with `ls -Al ~/.zshrc*`.

**Comment by shubuu97** [comment]
Thanks, I copied $PATH, $NVM_DIR, $ANDROID_HOME variables from my previous .zshrc file (uninstalled oh-my-zsh to get previous ./zshrc file) and then pasted into new /.zshrc file(after re-installing oh-my-zsh). It worked
