### ISSUE TITLE
How can I start zsh with different environments?

### ISSUE THREAD

**Issue by jondb** [ohmyzsh/ohmyzsh#9254]
Looking to emulate `/bin/bash -l --init-script '/path'` with zsh.

Specifically, I'm starting a number of python virtualenv or nodeenv. These require sourcing environment into the current shell.

Eg `source penv/bin/activate` which sets a bunch of stuff to relocate package search directories and updates PATH.

I need to start 4 of them with different environments, and am trying to automate iterm to do this and start the apps. 

I found a solution somewhere where I've added this to my ZSHRC

Let's say there's no direct way to execute zsh with an --init-script like bash does. How can I manually kickoff executing the full login startup?

So far, I have this...

add the following to .zshrc
```
if [[ $1 == eval ]]
then
    "$@"
    set --
fi
```
Then, I call zsh like this: `/bin/zsh -s eval "source path/to/bin/activate; python -c 'print(\'it works\')`

I don't know why it runs .zshrc, but doesn't set ALL my normal PATH variables, but it is missing some.

If there isn't a way to emulate bash, then is there a way to execute the missing startup scripts?

**Comment by mcornella** [comment]
You could define an env variable, for example, you put this in your zshrc file:
```zsh
if [[ -n "$PYTHONENV" ]]; then
  eval "$PYTHONENV"
fi

# rest of the zshrc file
```
and then you call it like so:
```console
$ PYTHONENV="source penv/bin/activate" zsh
```
If all the commands you need are `source <path>` you could go one step further and just
```zsh
if [[ -n "$PYTHONENV" ]]; then
  source "$PYTHONENV"
fi

# rest of the zshrc file
```
and call it with `PYTHONENV="penv/bin/activate" zsh`.

**Comment by jondb** [comment]
This works great. Keeps the environment! 

It works from the command line. Having trouble getting Iterm's python API to take the PYTHONENV=... /bin/zsh. Will update if I figure that part out - but otherwise, this works great!

**Comment by mcornella** [comment]
Alright glad to help. If you want you can document the solution you come up with to integrate this with iTerm's python API.
