### ISSUE TITLE
 Insecure completion-dependent directories detected

### ISSUE THREAD

**Issue by numan-hussain** [ohmyzsh/ohmyzsh#9262]
After installing it on my mac, I'm facing these messages / errors. 

```
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxr-xr-x  3 502  admin   96 Jul 25 23:13 /usr/local/share/zsh
drwxr-xr-x  4 502  admin  128 Jul 26 03:38 /usr/local/share/zsh/site-functions
lrwxr-xr-x  1 502  admin   39 Jul 26 03:38 /usr/local/share/zsh/site-functions/_brew -> ../../../Homebrew/completions/zsh/_brew
lrwxr-xr-x  1 502  admin   44 Jul 26 03:38 /usr/local/share/zsh/site-functions/_brew_cask -> ../../../Homebrew/completions/zsh/_brew_cask

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.
```

**Comment by ericcaclewis** [comment]
If you linked yours and you haven't take a looky look at mines

**Comment by mcornella** [comment]
The permission of those directories looks fine, I think the problem is that they're owned by the `admin` group. You can ignore this error by setting `ZSH_DISABLE_COMPFIX=true` in your zshrc file, before OMZ is sourced.

**Comment by numan-hussain** [comment]
> The permission of those directories looks fine, I think the problem is that they're owned by the `admin` group. You can ignore this error by setting `ZSH_DISABLE_COMPFIX=true` in your zshrc file, before OMZ is sourced.

It's working... Thank you, bro

**Comment by mcornella** [comment]
Cool, glad to help.

**Comment by abergsneider** [comment]
I run the command `compaudit | xargs chmod g-w,o-w` and it did it for me. Also glad to know either way it was fine. Thanks all.

**Comment by mehdibenzadi** [comment]
> I run the command `compaudit | xargs chmod g-w,o-w` and it did it for me. Also glad to know either way it was fine. Thanks all.

Yep, it worked for me too, thank you !

**Comment by Sebas0ne** [comment]
Yes, it worked for me too, thank you so much !

**Comment by Sebas0ne** [comment]
> I run the command `compaudit | xargs chmod g-w,o-w` and it did it for me. Also glad to know either way it was fine. Thanks all.

Yes, it worked for me too, thank you so much !
