### ISSUE TITLE
Missing Check whether home path changed when installing with old .zshrc

### ISSUE THREAD

**Issue by lquenti** [ohmyzsh/ohmyzsh#9263]
**Describe the bug**

When installing under another user with the same `.zshrc`, the installer breaks since the wrong `$ZSH` variable is set and set setup fails due to missing permissions to another persons home folder.

**To Reproduce**
1. Change from user A to user B
2. Copy `.zshrc` from user A
2.5. Don't have permission to the home folder of A
3. Start installation

**Expected behavior**

Some kind of warning, maybe a fallback

**Desktop (please complete the following information):**

 - OS / Distro: Ubuntu 18.04.5 LTS Server
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.4.2
 - Terminal emulator: xfce4-terminal via ssh

**Additional context**
Could reproduce it on arch.

If you have an idea what the preferred behaviour is, I'd love to implement and pr it myself!

Thanks a lot for your time.

**Comment by mcornella** [comment]
The installer uses the `$ZSH` variable to determine where to put ohmyzsh. Since this variable is exported, you need to explicitly unset it or point it somewhere else when calling the installer:
```zsh
ZSH= sh -c $(...)
```

**Comment by mcornella** [comment]
Note also that when copying the zshrc file from user A to user B, you need to change the `ZSH=` line of the zshrc.
