### ISSUE TITLE
docker container autocompletion does not work with -it

### ISSUE THREAD

**Issue by alkatar21** [ohmyzsh/ohmyzsh#9266]
**Describe the bug**
The docker plugin container autocompletion does not work in all cases.
In detail `docker exec -i` + tab works as expected, but `docker exec -it` + tab does not show up the available container.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable plugin `docker`
2. Run a container and try the autocomplete command `docker exec -it` + tab
3. container autocompletion does not work

**Expected behavior**
The container should be autocompletable like with only `-i` for example

**Self Check**
- [ ] Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)?
- [x] Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro: [ubuntu18.08 server]
 - Latest ohmyzsh update?: [Yes]
 - ZSH Version: [5.4.2]

**Additional context**
- Is something missing?

**Comment by mcornella** [comment]
[This is disabled by default](https://github.com/docker/cli/commit/b10fb430481574b34997e4b0e00b703cfcd6669e) but you can enable it, see the commit description:
> This enables Zsh to understand commands like "docker run -it ubuntu". However, by enabling this, this also makes Zsh completes "docker run -u<tab>" with "docker run -uapprox" which is not valid. The
users have to put the space or the equal sign themselves before trying to complete.
> 
> Therefore, this behavior is disabled by default. To enable it:
> 
> ```
> zstyle ':completion:*:*:docker:*' option-stacking yes
> zstyle ':completion:*:*:docker-*:*' option-stacking yes
> ```

I added this documentation to the docker plugin's README.
