### ISSUE TITLE
web-search gh command is conflict with GitHub cli gh 

### ISSUE THREAD

**Issue by JamesHopbourn** [ohmyzsh/ohmyzsh#9269]
**Describe the bug**
web-search gh command is conflict with GitHub cli gh 

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin web-search
2. Run command gh
3. See error

**Expected behavior**
run GitHub cli command gh

**Screenshots and/or Recordings**
You can also record an asciinema session: https://asciinema.org/

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro: [e.g. Arch Linux, macOS]
 - If on Windows what version of WSL: [e.g. WSL1, WSL2]
 - Latest ohmyzsh update?: [e.g. Yes/No]
 - ZSH Version: [e.g. 5.6]
 - Terminal emulator: [e.g. iTerm2]

**Additional context**
Add any other context about the problem here. This can be themes, plugins, custom configs.

**Comment by mcornella** [comment]
The `web-search` plugin doesn't define any `gh` command, you must have another configuration that does this. Also, you say `see error` but there's no error attached.
