### ISSUE TITLE
Permission denied for ~/.zshrc

### ISSUE THREAD

**Issue by rutikore** [ohmyzsh/ohmyzsh#9271]
I am always getting permission denied on using the command `~/.zshrc` , in zsh and also in bash. 
To solve this problem I followed the issue post such as https://github.com/ohmyzsh/ohmyzsh/issues/3291 and many more but cant seem to solve my problem. 
I am doing this to add a theme powerlevel9k to Oh-my-Zsh on Ubuntu.
I have tried using `vim ~/.zshrc` and quite confused to solve this problem using Vscode.
The outcome of `ls -l $HOME/.zshrc ` is `-rw-r--r-- 1 rack rack 3535 Sep 20 19:20 /home/rack/.zshrc` if it helps in any way.
Thank You
P.S. Total Noob in terminal and linux please help😢😢😢

**Comment by mcornella** [comment]
If you're trying to apply the changes you've made to the `.zshrc` file, you need to restart the terminal or restart the zsh session with `exec zsh`.

**Comment by mcornella** [comment]
Have you followed the [powerlevel9k installation instructions for ohmyzsh](https://github.com/Powerlevel9k/powerlevel9k/wiki/Install-Instructions#option-2-install-for-oh-my-zsh)?

**Comment by rutikore** [comment]
yes i have, am i doing something wrong while configuring zsh?

**Comment by rutikore** [comment]
ok i got my problem, i needed to install vim to access zshrc. Now it seems to be working, thank you for looking into my problem.

**Comment by mcornella** [comment]
Ok glad it's sorted now.
