### ISSUE TITLE
git CLI output not visible

### ISSUE THREAD

**Issue by klsetzer** [ohmyzsh/ohmyzsh#9276]
**Describe the bug**
As of the most recent update, output from `git` CLI commands that are paged is not visible.

**To Reproduce**
Steps to reproduce the behavior, for example:
`git diff`
_command runs, but no visible output_

**Expected behavior**
A diff should be displayed

**Desktop (please complete the following information):**

 - macOS 10.15.4 (19E287)
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.7.1
 - Terminal emulator: iterm2

**Additional context**
The workaround is to use the `--no-pager` command-line option to git.

**Comment by mcornella** [comment]
Have you made any changes to the `$LESS` environment variable or to git config? OMZ didn't touch anything related.

**Comment by klsetzer** [comment]
> Have you made any changes to the `$LESS` environment variable or to git config? OMZ didn't touch anything related.

Not recently. I've also held off on the last round of macOS updates.  Please leave this issue for a little bit. I'll try to debug, and update if it relates to a recent OMZ update.

**Comment by klsetzer** [comment]
It was PEBCAC!

Sorry folks.  Thank you @mcornella for the response.  I'm closing this with a small amount of embarrassment.

**Comment by mcornella** [comment]
How did you solve this, just curious?

**Comment by klsetzer** [comment]
You had to ask...

I had run `exec bash` and forgotten about it.  I was running bash.  Yep.  That was the problem.  Not even in the right shell.  Totally didn't see my cool p10k prompt.  Didn't think to open a new terminal window.  Just blamed OMZ.  I blame Monday.  And cabbage.  Cabbage is bad.
