### ISSUE TITLE
Unix commands not found

### ISSUE THREAD

**Issue by 25shmeckles** [ohmyzsh/ohmyzsh#9278]
I tryed to install ho-my-zsh in my user space on a HPC server running the install.sh script as instructed in the readme.
The installation succeded but when I run zsh, I can't get any of the common Unix commands working.

```
[xxx@hpcs04 /]$ zsh
/usr/bin/lsb_release: line 159: sed: command not found
/usr/bin/lsb_release: line 162: getopt: command not found
/etc/profile.d/modules.sh:12: command not found: sed
/etc/profile.d/modules.sh:16: command not found: id
/hpc/local/CentOS7/common/system/lmod/lmod/init/bash:81: command not found: tr
/usr/bin/lsb_release: line 159: sed: command not found
/usr/bin/lsb_release: line 162: getopt: command not found
/hpc/abc/users/xxx/.oh-my-zsh/oh-my-zsh.sh:69: command not found: rm
compdump:135: command not found: mv
detect-clipboard:33: command not found: uname
/hpc/abc/users/xxx/.oh-my-zsh/plugins/git/git.plugin.zsh:244: command not found: awk
➜  / ls
zsh: command not found: ls
➜  / help
zsh: command not found: help
➜  / exit
[xxx@hpcs04 /]$ ls
bin   data  dev  gnu   hpc  lib64  mnt  proc  run   srv  tmp  var
boot  db    etc  home  lib  media  opt  root  sbin  sys  usr
```

Any solution?

**Comment by mcornella** [comment]
Is `$PATH` correct? This could possible be the result of using a variable called `$path`, which in zsh is a copy of `$PATH`.

**Comment by 25shmeckles** [comment]
$PATH is not correct indeed, it ends with PATH, the dollar has been skipped during an export operation I guess. The variable looks bugged in the preinstalled zsh as well. Maybe it is not a oh-my-zsh related issue. I will investigate further.

**Comment by 25shmeckles** [comment]
It appears to be an internal bug due to the wrong configuration of ZSH
