### ISSUE TITLE
How to disable some commands?

### ISSUE THREAD

**Issue by DengJianShen** [ohmyzsh/ohmyzsh#9279]
For example, I want to disable the Linux command "CP" and "SCP".

**Comment by naveen-kumar-r** [comment]
from my understanding, there are no options to disable system commands. we can still try mask underlying commands in zsh. 
we could something below, but this doesn't guarantee from someone invoking binaries directly. (ex. /bin/cp ..)

```
 naveen@Naveen-HomePC $ alias cp=false
 naveen@Naveen-HomePC $ false
 ✘ naveen@Naveen-HomePC $

```

zsh allows builtin being disabled with `disable ` command, but it doesn't span across system binaries for obvious reasons.

**Comment by mcornella** [comment]
What Naveen said. Thanks Naveen.

Another option, if this is for other users, is to place a dummy binary somewhere in `$PATH` which has more precedence in the `$PATH` variable. So, for instance, if `/usr/local/bin` is before `/usr/bin` in `$PATH`, you could put a dummy binary in `/usr/local/bin` that does nothing, like symlinking it to `/bin/false`:
```
ln -s /bin/false /usr/local/bin/cp
ln -s /bin/false /usr/local/bin/scp
```

Though, again:

> but this doesn't guarantee from someone invoking binaries directly. (ex. /bin/cp ..)
