### ISSUE TITLE
Battery plugin not updating symbol/percentage

### ISSUE THREAD

**Issue by meredrica** [ohmyzsh/ohmyzsh#9281]
**Describe the bug**
I have the ``battery`` plugin activated and the battery prompt in my right hand promt.
If I open my terminal and have a charger connected, I get the infinity symbol, as expected.
However, if I disconnect the charger then the symbol does not update.
Opening a new terminal correctly shows the percentage for the time when the terminal was opened, which does not update either.

**To Reproduce**
1. enable the battery plugin and add ``battery_pct_prompt`` to the righthand prompt
2. connect the charger
3. open a terminal and see the infinity sign
4. disconnect the charger
5. use some battery
6. still see the infinity sign.
Works with percentage too.

**Expected behavior**
Sign/ percentage should update

**Desktop (please complete the following information):**

 - OS / Distro: Arch Linux
 - Latest ohmyzsh update?: yes. commit 93c837fec8e9fe61509b9dff9e909e84f7ebe32d
 - ZSH Version: zsh 5.8 (x86_64-pc-linux-gnu)
 - Terminal emulator: lilyterm

**Additional context**
Prompt variable I use. the time works fine.
```
 # current time in 24hh:mm:ss, battery status
RPROMPT="%* $(battery_pct_prompt)" 
```
my theme: https://github.com/meredrica/system/blob/master/h/.oh-my-zsh/themes/meredrica.zsh-theme
my zsh.rc: https://github.com/meredrica/system/blob/master/h/.zshrc

**Comment by meredrica** [comment]
ACPI output works fine too. I couldn't find any obvious problems in the battery plugin but I am not that good in zsh scripting

**Comment by mcornella** [comment]
You should use single quotes in the RPROMPT variable so that the function is run every time the RPROMPT needs to be displayed. Otherwise you're just running the one time and setting it to the value it returns on startup.

**Comment by meredrica** [comment]
@mcornella thank you!
