### ISSUE TITLE
[tmux plugin] set "ZSH_TMUX_AUTOSTART=true" will closes my terminal at first, but the seconds will be normal.

### ISSUE THREAD

**Issue by HideOnLie** [ohmyzsh/ohmyzsh#9289]
**Describe the bug**
set "ZSH_TMUX_AUTOSTART=true" will closes my terminal at first, but the seconds will be normal.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin
```
  plugins=(
       tmux
      )
export ZSH_TMUX_AUTOSTART=true
export ZSH_TMUX_AUTOSTART_ONCE=false
export ZSH_TMUX_AUTOCONNECT=false
#export ZSH_TMUX_AUTOQUIT=true

source $ZSH/oh-my-zsh.sh
```

2. Open the terminal, check the feature if normal, it will be close at first time
3. Open the second time the terminal, this feature can run. 
4. when I set ZSH_TMUX_AUTOQUIT to true
```
  plugins=(
       tmux
      )
export ZSH_TMUX_AUTOSTART=true
export ZSH_TMUX_AUTOSTART_ONCE=false
export ZSH_TMUX_AUTOCONNECT=false
export ZSH_TMUX_AUTOQUIT=false

source $ZSH/oh-my-zsh.sh
```
will output this log :`open terminal failed: not a terminal`, and the second time and more open the terminal also do not work

**Expected behavior**
at the first time, it  run normal when I open the terminal 

**Self Check**

 - I checked issuse and there seems to be no problem with this

**Desktop:**

 - OS / Distro: [Arch Linux]
 - WM: [DWM]
 - Latest ohmyzsh update?: [Yes]
 - ZSH Version: [5.8]
 - Terminal emulator: [st]

**Additional context**

It's annoying to have to open it twice every time. My English is not very good. I'm sorry if it caused any trouble.

**Comment by alexmndzdev** [comment]
I have the same proble, have you able to solved it @HideOnLie ?

**Comment by alexmndzdev** [comment]
I've already find the solution to my case, actually is an incompatibility between powerlevel10k theme, if you remove the theme then the autostart is working fine! :smile:

**Comment by HideOnLie** [comment]
> I've already find the solution to my case, actually is an incompatibility between powerlevel10k theme, if you remove the theme then the autostart is working fine!

Oh yes, you are right. If I remove powerlevel10k , it will be normal. I very surprised that you discovered the solution so quickly. It seems that this is a way for me to experience other themes. hhhhh

**Comment by kevinclark** [comment]
I ran into the same issue. Is there any lead on why this happens?

**Comment by HideOnLie** [comment]
> I ran into the same issue. Is there any lead on why this happens?

Sorry, I am also very troubled by this problem. It seems that this question should be fed back to the powerlevel10k project?

**Comment by HideOnLie** [comment]
> I ran into the same issue. Is there any lead on why this happens?

In my case, I update the powerlevel10k from github. it can run normally now. You can try it and see if it can help you.

**Comment by romkatv** [comment]
> I ran into the same issue. Is there any lead on why this happens?

This has been fixed in https://github.com/romkatv/powerlevel10k/issues/1099. Please update powerlevel10k to the latest version.

**Comment by kevinclark** [comment]
Thanks! Resolved for me too.

**Comment by 3nricoMarinelli** [comment]
I still had the same issue today with latest versions https://github.com/ohmyzsh/ohmyzsh/commit/e7aa0c56e68348afefdd6af4c5bdb314a2bd6640 https://github.com/romkatv/powerlevel10k/commit/604f19a9eaa18e76db2e60b8d446d5f879065f90.

**Issue**: conflict due to a race condition between p10k "Instant Prompt" and the tmux commands (or tmux oh-my-zsh plugin). 

**Solution worked for me**: deactivate / postpone the p10k "Instant Prompt"
