### ISSUE TITLE
Background doesn't change

### ISSUE THREAD

**Issue by danielepolencic** [ohmyzsh/ohmyzsh#929]
Hi there,
My Term stays white backgrounded, colors change, but not all,
only if I switch the theme in OS X Terminal Settings to another term,
then the theme switches to the text and terminal color of OS X choice.

anyone knows, why colors are not switched properly?

I deleted / reinstalled oh-my-zsh and deleted the term preferences, but nothing changed.

Thanks.

**Comment by shreyabhandare** [comment]
same issue !!!

**Comment by mcornella** [comment]
Hi @shreyabhandare, the background color is a setting in your terminal (for example Terminal.app, iTerm2, Gnome terminal, Hyper...), so look in its settings to change it.

**Comment by seriousFace-Ian** [comment]
It seem like can't change color in terminal.app

**Comment by mcornella** [comment]
See if this helps https://support.apple.com/en-lk/guide/terminal/trml107/mac

**Comment by talglobus** [comment]
Same issue, 12 years  after this thread was opened.

Light mode on top, dark mode on bottom.
<img width="340" alt="Light Mode" src="https://github.com/user-attachments/assets/47e50509-ac5c-45fc-a03f-e90bfb5c4e06">
<img width="340" alt="Dark Mode" src="https://github.com/user-attachments/assets/d5707b31-1751-48ed-ba74-3305a390dbf9">

**Comment by mcornella** [comment]
And since 12 years ago, the issue has nothing to do with Oh My Zsh but with your terminal configuration: https://github.com/ohmyzsh/ohmyzsh/issues/929#issuecomment-695040782
