### ISSUE TITLE
fzf plugin doesn't pick up fzf installation on OpenSUSE

### ISSUE THREAD

**Issue by GHF** [ohmyzsh/ohmyzsh#9290]
**Describe the bug**
On OpenSUSE, the `fzf` package and its supporting `fzf-zsh-completion` package don't follow the same directory structure as expected by [fzf.plugin.zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/fzf/fzf.plugin.zsh).

There's no self contained `FZF_BASE` directory, and even if that were overridden to `/usr`, the OpenSUSE RPM renames `key-bindings.zsh` to `fzf-key-bindings`:

```
> rpm -ql fzf-zsh-completion
/etc/zsh_completion.d
/etc/zsh_completion.d/fzf-key-bindings
/usr/share/zsh
/usr/share/zsh/site-functions
/usr/share/zsh/site-functions/_fzf
> rpm -ql fzf
/usr/bin/fzf
/usr/share/doc/packages/fzf
/usr/share/doc/packages/fzf/README.md
/usr/share/licenses/fzf
/usr/share/licenses/fzf/LICENSE
/usr/share/man/man1/fzf.1.gz
```

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'fzf'
2. Start shell
3. See error
  a.
```
[oh-my-zsh] fzf plugin: Cannot find fzf installation directory.
 Please add `export FZF_BASE=/path/to/fzf/install/dir` to your .zshrc
```
  b. CTRL-T and `cd ~/**<TAB>` integrations don't work even if I have `export FZF_BASE=/usr` because of the different structure.

**Expected behavior**
`fzf` plugin loads fzf key bindings and completions installed by the `fzf-zsh-completion` package.

**Screenshots and/or Recordings**
You can also record an asciinema session: https://asciinema.org/

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro: OpenSUSE Tumbleweed
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.7.1
 - Terminal emulator: tmux + iTerm2

**Additional context**
Add any other context about the problem here. This can be themes, plugins, custom configs.

**Comment by mcornella** [comment]
I submitted https://github.com/ohmyzsh/ohmyzsh/pull/9327 to fix this. Try it out with `omz pr test 9327`.

**Comment by GHF** [comment]
nice! I'm away from that machine right now without remote access, so I probably won't try this for another week. Thanks for tackling it!

**Comment by GHF** [comment]
#9327 works great for me on OpenSUSE Tumbleweed.

**Comment by mcornella** [comment]
OK I'll merge it in the hope that it also fixes #9023. There's always time to fix it if it doesn't.

**Comment by crazy-matt** [comment]
Hi @GHF ,
It would be kind if you could sum-up how you achieved to sort it out. I struggle to make this FZF plugin work and searching for some info led me here.
I'm on Tumbleweed like you, I loaded it using `zinit snippet OMZ::plugins/fzf/fzf.plugin.zsh`. I have the last release of FZF being installed with zypper `fzf-0.25.1-1.2.x86_64`. And I still get this message you reported. I tried with several FZF_BASE values with no luck. Is this env var still required?
I noticed that `/usr/share/zsh/site-functions/_fzf` and `/etc/zsh_completion.d/fzf-key-bindings` does not exists though.

**Comment by crazy-matt** [comment]
Zypper deploys only the files below in my case:
```
/usr/bin/fzf
/usr/share/licenses/fzf
/usr/share/licenses/fzf/LICENSE
```

**Comment by GHF** [comment]
@crazy-matt do you have the `fzf-zsh-completion` package installed?

**Comment by crazy-matt** [comment]
> @crazy-matt do you have the `fzf-zsh-completion` package installed?

Nope. That was the missing bit. It worked straight away. Thanks for pointing it out to me, because I was not really keen on installing just fzf by cloning its repo.
