### ISSUE TITLE
How to press Esc+. shortcut in vi-mode?

### ISSUE THREAD

**Issue by ProgrammingLife** [ohmyzsh/ohmyzsh#9292]
The problem is that Esc key exits to normal mode so Esc+. doesn't work in my case. How to solve it?

**Comment by mcornella** [comment]
Are you sure there's a key binding for ESC+. in vi-mode? Run `bindkey '^[.'` to find out.

In emacs mode there is one bound to `insert-last-word`, but I couldn't find it for `vicmd` nor `viins`. If you're missing the key binding and you want it bound to `insert-last-word`, these commands will do:
```zsh
bindkey -M vicmd '^[.' insert-last-word
bindkey -M viins '^[.' insert-last-word
```

If you want it bound to another widget just replace `insert-last-word` in the commands above.
