### ISSUE TITLE
kubectl plugin add set context namespace aliases

### ISSUE THREAD

**Issue by gutorc92** [ohmyzsh/ohmyzsh#9293]
Is your feature request related to a particular plugin or theme? If so, specify it.
kubectl

Describe the solution you'd like
Use alias like kgp, kgs most of the time need the flag ```-n```, who works as support in companies it became a tedious task. To avoid it a default namespace can be set using ```kubectl config set-context --current --namespace=teste```.  This command also could be an alias.

Describe alternatives you've considered
alias kcsn - kubectl config set-context --current --namespace=teste

**Comment by robbyrussell** [comment]
Think this might be already done?
