### ISSUE TITLE
Support for dvtm, similarly to tmux

### ISSUE THREAD

**Issue by robcsi** [ohmyzsh/ohmyzsh#9296]
**Plugin for dvtm**
I'd like to have a plugin, which enables the use of dvtm (dynamic virtual terminal manager) the same way one exists for tmux.

dvtm: https://github.com/martanne/dvtm

**Additional context**
It's very easy to enable tmux integration at the moment, just by setting some variables (ZSH_TMUX_AUTOSTART, ZSH_TMUX_AUTOCONNECT, etc.), so I'd like to have a similar approach to dvtm as well. Even if it's just enabling it, in the first step. I see tmux plugin defines some aliases as well, which is also nice to have for dvtm as well, but I could live without those.

Thanks,
Robert

**Comment by robbyrussell** [comment]
Hey there, I'm doing a bit of housekeeping on the project. Thanks for raising this issue—we always love a good edge case! 😄

However, it's not gathering much community interest, so I'm going to close it for now. Don't let this discourage you! We're all for hearing about the weird things. We can't commit to spending too much time tracking each weird thing down ourselves.
