### ISSUE TITLE
command not found: ^M

### ISSUE THREAD

**Issue by kkoziol** [ohmyzsh/ohmyzsh#9298]
I just updated my ohmyzsh and during update there was massive amount of similar errors:

: command not found...
/home/iid/.oh-my-zsh/oh-my-zsh.sh:3: command not found: ^M
/home/iid/.oh-my-zsh/oh-my-zsh.sh:34: parse error near `||'

Nothing works now... completions, schemes... on my centos linux.
Somebody commited some strange line endings?

**Comment by kkoziol** [comment]
Ok, fixed with.

`
cd $ZSH
git config core.autocrlf false
git rm --cached -r .
git reset --hard
`

**Comment by mcornella** [comment]
>  git config core.autocrlf false

This is done automatically by the upgrade tool. Did you update OMZ manually?
