### ISSUE TITLE
Git Clone totally freezes the shell

### ISSUE THREAD

**Issue by Morantxu** [ohmyzsh/ohmyzsh#9302]
**Describe the bug**
When trying to write the path to a git repository with git clone <path>, after one or two seconds the shell completely freezes.

**To Reproduce**
1. Enable this plugin : ohmyzsh
2. Run command git clone htpps://github.com/_user_/...
3. The shell totally freezes

**Desktop (please complete the following information):**

 - OS / Distro: Ubuntu
 - Latest ohmyzsh update? Yes
 - ZSH Version: 5.8
 - Terminal emulator: Default ubuntu terminal

**Comment by romkatv** [comment]
This was cross-posted to /r/zsh. It doesn't reproduce ([link](https://www.reddit.com/r/zsh/comments/j3icfe/something_with_ohmyzsh_makes_the_shell_freeze/g7drmdx/)).

**Comment by mcornella** [comment]
Hi @Morantxu, can you post specific instructions for how to reproduce this?

1. By "enable this plugin ohmyzsh", do you mean just install ohmyzsh with the default settings?
2. What's the full `git clone` command?
3. What `git --version` are you using?
4. Does this still happen without OMZ, meaning if you run `zsh -f`?
5. Have you tried another terminal?

Thanks
