### ISSUE TITLE
debian plugin shadows ar archiver

### ISSUE THREAD

**Issue by matsievskiysv** [ohmyzsh/ohmyzsh#9304]
**Describe the bug**

debian plugin sets up alias `ar` which shadows `ar` archiver from `binutils` package.
This program is used for creating libraries and deb archives, shadowing it would introduce problems.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable `debian` plugin
2. Run command `which ar`
3. See `ar: aliased to sudo apt remove`

**Expected behavior**
`ar` must not be shadowed

**Desktop:**

 - OS / Distro: Gnu/Linux Debian bullseye
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: [`st`](https://st.suckless.org/)

**Comment by glerroo** [comment]
This alias must be changed because causes a lot of problems on GNU/Linux Debian and derivatives.

**Comment by rwmitchell** [comment]
Egads!  Someone was insane to create that!

I also don’t approve of any plugins using aliases with sudo. Sure, create your own but don’t have them in OMZ.

**Comment by carlosala** [comment]
oh, we didn't notice it! I'll remove that alias, thanks for the report!

**Comment by rwmitchell** [comment]
You're still being very careless leaving in all the 'sudo' commands!

Someone knowingly runs sudo for something they're doing, starting the 'don't re-ask for the password' timer, then accidentally mistypes a command, running one of these aliases with ZERO indication they're using sudo and suddenly does a lot more damage than they were expecting.

**Comment by tmiland** [comment]
Could this be re-implemented but with a different cmd? Like `apr`or something?

Was just finished adding all these cmd's to my terminal, and updated oh my zsh 🤦‍♂️
