### ISSUE TITLE
af-magic: how to remove username@computer from prompt?

### ISSUE THREAD

**Issue by haifengkao** [ohmyzsh/ohmyzsh#9317]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
`af-magic`

**Is your feature request related to a problem? Please describe.**
I don't want the right prompt

**Describe the solution you'd like**
Something like agnoster. Hide the right prompt when "$USER" == "$DEFAULT_USER"
https://github.com/ohmyzsh/ohmyzsh/blob/6ebf27b8d34c760e25749790ea78dcb0c220d76b/themes/agnoster.zsh-theme#L91

**Related Issues**
https://github.com/ohmyzsh/ohmyzsh/issues/5581 agnoster: how to remove username@computer from prompt?

**Comment by mcornella** [comment]
First you'll have to copy the theme file to the custom directory, see [Overriding and adding themes](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes). Then, you'll need to remove line 31:
https://github.com/ohmyzsh/ohmyzsh/blob/6ebf27b8d34c760e25749790ea78dcb0c220d76b/themes/af-magic.zsh-theme#L31
