### ISSUE TITLE
ohmyzsh is terribly slow on chromium folder

### ISSUE THREAD

**Issue by asurkov** [ohmyzsh/ohmyzsh#9322]
**Describe the bug**
Each and every operation in chromium sources folder seems to be terribly slow, it may take a sec or two on macpro.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Download chromium source code https://www.chromium.org/developers/how-tos/get-the-code
2. enter sources folder and press ctrl+c
3. it takes a sec or two+ to complete

**Expected behavior**
It should take no time

**Desktop (please complete the following information):**

 - OS / Distro: macOS
 - Latest ohmyzsh update?: Yes
 - ZSH Version: [e.g. 5.7.1]
 - Terminal emulator: [e.g. Terminal]

**Additional context**
I suspect chromium sources are just huge which makes certain zsh operations a bottleneck.

**Comment by mcornella** [comment]
Which theme are you using? Can you also post the commit you're using on OMZ? (`git -C $ZSH rev-parse HEAD`)

**Comment by asurkov** [comment]
git -C $ZSH rev-parse HEAD
fc6c9ca4b40ee1c9ba7fb4b1c8862fb54a8cb1f6

theme has to be default one, how do I check this?

**Comment by asurkov** [comment]
just to clarify: ctrl+c is specifically slow, command substitution like and search seems working ok, perhaps it's worth to reword the bug. bash btw seems works just fine, ctrl+c takes no time.

**Comment by mcornella** [comment]
Yeah, it looks like what you mean is that the prompt takes a long time to print. Can you check if checking out 297238b7 works better? (restart zsh with `exec zsh`)

**Comment by sylvestre** [comment]
Same issue with Firefox on hg: https://github.com/ohmyzsh/ohmyzsh/issues/4116

**Comment by jatin-code777** [comment]
Although I'm not sure this is the issue, this is worth a shot

@asurkov Could you tell which theme you are using? 
There is a git dirty parsing which is done before printing the prompt every time.

Try this and let us know if it improves performance

```
$ cd /path/to/chromium/source
$ git config oh-my-zsh.hide-dirty 1
```

**Comment by asurkov** [comment]
> Although I'm not sure this is the issue, this is worth a shot
> 
> @asurkov Could you tell which theme you are using?

I suppose I have robbyrussell

> cat ~/.zshrc | grep ZSH_THEME
ZSH_THEME="robbyrussell"
# Setting this variable when ZSH_THEME=random will cause zsh to load
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

> There is a git dirty parsing which is done before printing the prompt every time.
> 
> Try this and let us know if it improves performance
> 
> ```
> $ cd /path/to/chromium/source
> $ git config oh-my-zsh.hide-dirty 1
> ```

It definitely helps, it's fast now!

**Comment by jatin-code777** [comment]
@asurkov Glad it helped :)
@mcornella I guess this can be closed now then. It would be nice to mention this somewhere visibly in the documentation for new users. This issue occurs on a lot of big repos, like tensorflow, LLVM, Chromium, to name a few

**Comment by Gondnat** [comment]
> Although I'm not sure this is the issue, this is worth a shot
> 
> [@asurkov](https://github.com/asurkov) Could you tell which theme you are using? There is a git dirty parsing which is done before printing the prompt every time.
> 
> Try this and let us know if it improves performance
> 
> ```
> $ cd /path/to/chromium/source
> $ git config oh-my-zsh.hide-dirty 1
> ```

Hide status is also a good choice, if you don't care it.

```
$ git config oh-my-zsh.hide-status 1 
```
