### ISSUE TITLE
The shell console is cleared when exit from the vi editor.

### ISSUE THREAD

**Issue by FavonianKong** [ohmyzsh/ohmyzsh#9325]
When I work in vi and exit vi, all the original output on the shell console is flushed and only the blank page is left. Is there any setting that won't let it refresh, or am I setting something wrong? All my changes to `~/.zshrc` are limited to theme, I changed the default theme to `ys`.

**Comment by naveen-kumar-r** [comment]
This sounds like vi not recognising the "alternate screen". Are there any customisation done on vi (.vimrc) because following FAQ sights setting t_ti, t_te makes vi to flush the screen buffer.

http://vimdoc.sourceforge.net/cgi-bin/vimfaq2html3.pl
```
32.4. I am using Vim in a xterm. When I quit Vim, the screen contents are
      restored back to the original contents. How do I disable this?

The xterm has a capability called "alternate screen".  If this capability
is present, vim switches to that alternate screen upon startup and back on
exit, thus restoring the original screen contents.  To disable this
feature, add the following line to your .vimrc file:

    :set t_ti= t_te=
```

**Comment by mcornella** [comment]
If this still happens in default zsh this is not an OMZ bug. Try opening vi after running `zsh -f`. To me this looks more like a terminal emulator bug.

**Comment by FavonianKong** [comment]
> If this still happens in default zsh this is not an OMZ bug. Try opening vi after running `zsh -f`. To me this looks more like a terminal emulator bug.

As you said, it's the terminal emulator's fault. Sorry for taking so long to reply because the mailbox is blocked : )
