### ISSUE TITLE
git_prompt_status broken because of regexp

### ISSUE THREAD

**Issue by rionda** [ohmyzsh/ohmyzsh#9326]
https://github.com/ohmyzsh/ohmyzsh/blob/23760228908d14a4644718869d5ebfb7b0dde6a7/lib/git.zsh#L229

This regexp does not seem to match, at least on my MacOS. 
If I change it to `local status_regex="$status_prefix"` then it works again.

**Comment by mcornella** [comment]
What about `local status_regex=$'(^|\n)'"$status_prefix"`?

**Comment by rionda** [comment]
@mcornella : that seems to work, and preserves the intention of your original one.

**Comment by mcornella** [comment]
Thanks for the bug report!
