### ISSUE TITLE
"zsh: command not found: upgrade_oh_my_zsh" on zsh installed via brew

### ISSUE THREAD

**Issue by Tusenka** [ohmyzsh/ohmyzsh#9329]
I installed zsh via brew.
`brew install zsh`
I can't run update zsh:
`omz update  
zsh: command not found: omz`
Is it an expected behavior?
Are plugins need to be auto-installed from plugin section in .zshc? 
~/.oh-my-zsh  doesn't contain tools, it contains only 3 plugins:
```
% find $ZSH:
/Users/igracheva/.oh-my-zsh
/Users/igracheva/.oh-my-zsh/.zsh_history
/Users/igracheva/.oh-my-zsh/custom
```
..
/Users/igracheva/.oh-my-zsh/custom/plugins/zsh-completions/src/_git-flow

I am just wandering how can I do best.

**Comment by mcornella** [comment]
Try to reinstall Oh My Zsh by removing the `~/.oh-my-zsh` directory and running the installer again.

**Comment by mcornella** [comment]
Any updates? You can find the installer here: https://github.com/ohmyzsh/ohmyzsh#basic-installation. Note that Oh My Zsh isn't installed automatically when installing zsh, those are separate things.

**Comment by Tusenka** [comment]
@mcornella , thank you! I've clean folder zsh which i have from previous mac, uninstalled the zsh. And perfectly installed via curl.
