### ISSUE TITLE
Why the theme changed ? maran theme

### ISSUE THREAD

**Issue by myxss** [ohmyzsh/ohmyzsh#9332]
![image](https://user-images.githubusercontent.com/33475775/95694259-a08fb400-0c63-11eb-904e-31e9672cb469.png)
![image](https://user-images.githubusercontent.com/33475775/95694264-a84f5880-0c63-11eb-9037-c4807f5f0098.png)

no ssh ,when i open the iterm 
It was @localhost before,update zsh changed

**Comment by myxss** [comment]
![image](https://user-images.githubusercontent.com/33475775/95694340-26abfa80-0c64-11eb-8beb-82ae3f362cc7.png)

and my hostname changed

**Comment by mcornella** [comment]
The theme didn't change, your hostname did. Look up why it changed, probably due to a system configuration change.
