### ISSUE TITLE
psql tool under oh-my-zsh clears output from the screen

### ISSUE THREAD

**Issue by SemyenSoldatenko** [ohmyzsh/ohmyzsh#9334]
**Describe the bug**
psql tool from PostgreSQL removes long output from the screen when user exit pager.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. open terminal (with oh-my-zsh default configuration)
2. run `psql <your_database>`
3. run any sql query that produces long output (to trigger pager)
4. You can see query result on the screen
5. press `q` to quit pager
6. query result disappears from the screen

**Expected behavior**
Query result stays on the screen.

**Screenshots and/or Recordings**
Demo and workaround
https://asciinema.org/a/fj1Ax8qNd4lXhHfUNSi9A1Yjd

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? No
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support Yes

**Desktop (please complete the following information):**

 - OS / Distro: [macOS 10.15.7 (19H2)]
 - If on Windows what version of WSL: [e.g. WSL1, WSL2]
 - Latest ohmyzsh update?: [e.g. Yes/No] Yes (2657c87f0aa1fe7f66062bc3452ad68347be356f)
 - ZSH Version: [e.g. 5.6] zsh 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator: [e.g. iTerm2] Apple_Terminal version 433, TERM=xterm-256color

**Additional context**
Add any other context about the problem here. This can be themes, plugins, custom configs.

**Comment by mcornella** [comment]
This looks like you need to setup the pager options (normally `less`) to not use alternate screen (on `less`, that's `less -FRX`. Look up how to set up pager options for `psql`. Note: if the same behavior happens under `zsh -f` (run zsh without zshrc), this is not an Oh My Zsh problem.
