### ISSUE TITLE
command-not-found not always being triggered

### ISSUE THREAD

**Issue by Kristof-Mattei** [ohmyzsh/ohmyzsh#9341]
**Describe the bug**
A clear description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin '`command-not-found`'
2. Type in `fffff` and hit `<return>`.
3. Observe nothing being thrown about error not found.

**Expected behavior**
Command being passed on to the actual `command-not-found` binary, so that it prints something like: 

```
Command 'fffff' not found, did you mean:

  command 'ffe' from deb ffe (0.3.9-1)
  command 'ftff' from deb whichman (2.4-9)
  command 'fzf' from deb fzf (0.20.0-1)
  command '2ff' from deb farbfeld (4-2)
  command 'ffc' from deb python3-ffc (2019.1.0.post0-4)

Try: sudo apt install <deb name>
```

**Screenshots and/or Recordings**
https://asciinema.org/a/fwBSLlIDOUATef8GU8IJaUL41

**Desktop (please complete the following information):**

 - OS / Distro: Ubuntu-20.04
 - If on Windows what version of WSL: WSL2
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: Windows Terminal

**Additional context**

**Comment by mcornella** [comment]
Hey there, this is a bug in the command-not-found package, see https://github.com/ohmyzsh/ohmyzsh/issues/8596.
