### ISSUE TITLE
unable to install oh my zsh. Developer tools are not installing

### ISSUE THREAD

**Issue by raghavendrakumars** [ohmyzsh/ohmyzsh#9342]
Using curl I tried to install oh my zsh. But a pop up came to install developer tools. When I proceed further it searched for software and filed with "This software cannot install the software because it is not currently available from the software update server". 

this is what i am getting 

xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.

Appreciate your help me on this. 

Thanks 
Raghu

**Comment by mcornella** [comment]
This seems like a recent, common problem. See https://developer.apple.com/forums/thread/110552 for how to manually download the command line tools.
