### ISSUE TITLE
kubectl plugin: compdef: unknown command or service: kubectl

### ISSUE THREAD

**Issue by causalityloop** [ohmyzsh/ohmyzsh#9345]
**Describe the bug**
recent [PR](https://github.com/ohmyzsh/ohmyzsh/pull/9316) introduced syntax coloring but implementation expects kubectl is installed prior - which may not always be the case. In a fresh deployment, kubectl may not be installed prior to configure the shell environment - or the user may not have kubectl installed at all (in my case, i have enabled the same plugins from host to host and only some have kubectl installed (rest of the plugins enabled have no issue).

In this case, if we check for kubectl, prior to running 'compdef' (which triggers the error output), that will alleviate the messages getting printed at shell init.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. enable the kubectl plugin
2. make sure kubectl is not installed
3. open a new shell

**Expected behavior**
no error messages are printed on shell login/init

**Screenshots and/or Recordings**

![image](https://user-images.githubusercontent.com/46820823/96154817-384c0700-0edd-11eb-8d0b-39564ea5d277.png)

**Comment by causalityloop** [comment]
here is the pr for the above https://github.com/ohmyzsh/ohmyzsh/pull/9346

**Comment by swapsCAPS** [comment]
FWIW I have `kubectl` installed and in my `$PATH`, but still getting this error.
![image](https://user-images.githubusercontent.com/1317131/96224784-68081700-0f90-11eb-9fa7-c3ee787e2707.png)

**Comment by mcornella** [comment]
Is this really the latest version? (`omz update`). Do you have other configs that might cause this?

**Comment by FuzzyAzurik** [comment]
Thanks :+1:  
ran "omz update" and no errors are now present.

**Comment by swapsCAPS** [comment]
> Is this really the latest version? (`omz update`). Do you have other configs that might cause this?

Pulled `master`. Still hapens with stripped down `.zshrc`:
```
export ZSH=~/.oh-my-zsh

ZSH_THEME="avit"

plugins=(git kubectl)

source $ZSH/oh-my-zsh.sh
```

**Comment by mcornella** [comment]
Try `rm $ZSH_COMPDUMP` and restarting with `exec zsh`.

**Comment by swapsCAPS** [comment]
Still not working unfortunately.
![image](https://user-images.githubusercontent.com/1317131/96352945-f92dd980-10c7-11eb-878e-ee1a78dc4afb.png)

**Comment by mcornella** [comment]
Which commit are you on? `git -C $ZSH rev-parse HEAD`

**Comment by swapsCAPS** [comment]
`5b717ab3e4bfb627a936d7c04367a39867734d63`
```
commit 5b717ab3e4bfb627a936d7c04367a39867734d63 (HEAD -> master, origin/master, origin/HEAD)
Author: IsThisTheMatrix <46820823+causalityloop@users.noreply.github.com>
Date:   Thu Oct 15 18:52:34 2020 -0400

    kubectl: verify kubectl is installed before running compdef (#9346)
```

**Comment by mcornella** [comment]
What about `echo $_comps[kubectl]`?

**Comment by swapsCAPS** [comment]
Very much nothing
![image](https://user-images.githubusercontent.com/1317131/96353092-41013080-10c9-11eb-85f8-9ce1631e7cd1.png)

**Comment by mcornella** [comment]
It looks like kubectl completion isn't working. Try `rm ${ZSH_CACHE_DIR}/kubectl_completion` and restarting zsh.

**Comment by mcornella** [comment]
But before you do that, post the content of that file (basically whether it's empty or has content is enough).

**Comment by swapsCAPS** [comment]
Ahw crap, too late! Sorry about that!
No more errors now though!
![Peek 2020-10-17 23-05](https://user-images.githubusercontent.com/1317131/96353528-42ccf300-10cd-11eb-9b77-d407bfc2f348.gif)

**Comment by swapsCAPS** [comment]
non stripped down `.zshrc` had following line. Did something perhaps get stuck in bad state because of it?
```
# kubectl completion
source <(kubectl completion zsh)
```

**Comment by mcornella** [comment]
If that was called before OMZ maybe the call that the plugin makes didn't return anything? I have no idea, but glad it's solved.
