### ISSUE TITLE
GIT Shortcut: `gai` for `git add -i`

### ISSUE THREAD

**Issue by jrista** [ohmyzsh/ohmyzsh#9347]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
git

**Is your feature request related to a problem? Please describe.**
Not a problem, just a "missing" shortcut for git! ;)

**Describe the solution you'd like**
Would like to see a shortcut added for `git add --interactive` or `git add -i`. This shortcut could be called `gai`, as I do not currently see that used for any other shortcut. 

**Describe alternatives you've considered**
The only real alternative is to use the full git command `git add -i`.

**Comment by mcornella** [comment]
[The git plugin already has many aliases](https://github.com/ohmyzsh/ohmyzsh/issues/5721). You can already use `ga` for `git add`, so you'd only need to run `ga -i`. Plus, you can add the alias yourself in your zshrc file.
