### ISSUE TITLE
Histignorealldups doesn't work

### ISSUE THREAD

**Issue by Mystic8b** [ohmyzsh/ohmyzsh#9359]
**Describe the bug**
`histignorealldups` doesn't work when `incappendhistory` is on

**To Reproduce**
1. setopt INC_APPEND_HISTORY
2. setopt HIST_IGNORE_ALL_DUPS
3. execute multiple alternating commands
4. cat ~/.zsh_history

**Expected behavior**
Previous matches should be deleted

**Screenshots and/or Recordings**
![image](https://user-images.githubusercontent.com/35394377/96367578-6ccaf780-1157-11eb-9df9-d9642c5655ac.png)

**Desktop (please complete the following information):**

 - OS / Distro: [e.g. Arch Linux, macOS]: Ubuntu 20.04
 - If on Windows what version of WSL: WSL2
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: Windows Terminal

**Comment by Mystic8b** [comment]
ps I'm not sure if this is about omz, but maybe there is someone here who can provide an answer. Maybe this is the expected behavior.

**Comment by mcornella** [comment]
I could reproduce the issue, both with and without OMZ. I don't know if this is a documentation problem or a bug, ask over at the [Zsh mailing list](http://zsh.org/mla).
