### ISSUE TITLE
npx plugin is broken

### ISSUE THREAD

**Issue by assapir** [ohmyzsh/ohmyzsh#9366]
**Describe the bug**
After upgrading to node 15 / npm 7, there is an error while loading the shell:
```
npx: the --shell-auto-fallback argument has been removed
```

**To Reproduce**
Steps to reproduce the behavior, for example:
0. Install latest node 15
1. Enable this plugin `npx`
2. Start a shell
3. See error

**Expected behavior**
No error and npx plugin works as expected

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro: MacOs
 - If on Windows what version of WSL: [e.g. WSL1, WSL2]
 - Latest ohmyzsh update?: Yap
 - ZSH Version: zsh 5.8 (x86_64-apple-darwin19.3.0)
 - Terminal emulator:iTerm2

**Comment by mcornella** [comment]
The `--shell-auto-fallback` argument has been removed in the move from `npx` to `npm exec`: https://github.com/npm/cli/blob/latest/docs/content/cli-commands/npm-exec.md#compatibility-with-older-npx-versions
> Shell fallback functionality is removed, as it is not advisable.

The only thing to do is to deprecate this plugin and disable it when running npm v7.
