### ISSUE TITLE
Feedback request: WORDCHARS change makes usability REALLY BAD

### ISSUE THREAD

**Issue by Moshem123** [ohmyzsh/ohmyzsh#9367]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
no

**Is your feature request related to a problem? Please describe.**
Introduced by this commit: https://github.com/ohmyzsh/ohmyzsh/commit/50dc4ab3574f4e265dff816d8d9a0195cd260152
The usability is really bad when jumping between words. I found it extremely useful to jump between dashes (`-`) and underscores (`_`), and this commit just eliminates this capability which was crucial for fast work with the terminal.

**Describe the solution you'd like**
Of course I could set my own `WORDCHARS`, but I don't think this behaviour is something the majority would enjoy using.

**Comment by mcornella** [comment]
Thanks for the feedback folks, the change has been reverted (use `omz update` and restart the shell for the update).
