### ISSUE TITLE
Lags during typing in emacs when git-auto-fetch plugin is enabled

### ISSUE THREAD

**Issue by avatar-lavventura** [ohmyzsh/ohmyzsh#9370]
Related to `ohmyzsh/plugins/git-auto-fetch/`

Once in a while there are lags when typing in the shell or using `emacs`. 

=> I was wondering is it a normal case that occured before? Is there any way to prevent any lag that occurs due to

**Comment by mcornella** [comment]
Follow #9416.

**Comment by mcornella** [comment]
Please try the function in https://github.com/ohmyzsh/ohmyzsh/issues/9416#issuecomment-733172596 and report whether you see performance improvements.
