### ISSUE TITLE
Right prompt often corrupts in Windows Terminal

### ISSUE THREAD

**Issue by mcandre** [ohmyzsh/ohmyzsh#9375]
**Describe the bug**

Right prompts are often misplaced when using Windows Terminal.

**To Reproduce**

1. Configure a right prompt. Example: https://github.com/mcandre/dotfiles/tree/16def7697a9d9ee64316c9aa4096e94e3ab61987
2. Launch your zsh in WSL in Windows Terminal.
3. Tile Windows Terminal to the right half of the screen.

**Expected behavior**

The right prompt sticks to the right of Windows Terminal.

Windows 10.

**Comment by mcornella** [comment]
This should be posted in https://github.com/microsoft/terminal. Be sure to search for existing issues, and if it hasn't yet been posted, include sample code to "configure a right prompt" and post a screenshot.
