### ISSUE TITLE
Installing system-wide

### ISSUE THREAD

**Issue by TriMoon** [ohmyzsh/ohmyzsh#9380]
What is needed to install this as an system-wide extension to Zsh?
This would allow distro's to make a package that install's it system-wide.

When installed system-wide the update to the local git-clone would require root ofcourse.
But the per user customization could be left in the `~/.zshrc` in the users homedir.

**Comment by TriMoon** [comment]
For my current ongoing attempt(s) see [here](https://forum.manjaro.org/t/zsh-with-oh-my-zsh/33735).

**Comment by ybrhue** [comment]
Any Updates?

**Comment by TriMoon** [comment]
@ybrhue i am still using what i wrote there, and have not havd a chance to create a poll about it (which was suggested in that forum thread)

**Comment by mcornella** [comment]
The basic summary of what needs to happen to install system-wide:

1. The root of the folder needs to be installed somewhere global, like `/opt/ohmyzsh`, or `/usr/share/ohmyzsh`.
2. The autoupdate is already skipped if there's no write access to the global directory, or it is not a git repository, so it is not needed to turn it off manually in each .zshrc file.
3. The user's `.zshrc` file needs to reference the $ZSH installation, and add the settings there.
4. `ZSH_CACHE_DIR` is automatically changed to `$HOME/.cache/oh-my-zsh` if `$ZSH/cache` is not writable, so changing it is not needed.
5. `ZSH_CUSTOM` is set as `$ZSH/custom`, so if the user wants to add custom files they should redefine it.

A reference of the minimal `.zshrc` file is below:

```sh
export ZSH="/usr/share/ohmyzsh"
ZSH_THEME=...
plugins=(...)
source "$ZSH/oh-my-zsh.sh"
```

Sorry this took so long. I've also added this information in the FAQ: https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-install-oh-my-zsh-globally.
