### ISSUE TITLE
Can't unset alias with bang even with NO_BANG_HIST

### ISSUE THREAD

**Issue by MiCkSoftware** [ohmyzsh/ohmyzsh#9383]
**Describe the bug**
A clear description of what the bug is.
Can't unset alias with bang even with NO_BANG_HIST

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'git'
2. Run command 'unset 'gca!''
3. See error
unset: gca!: invalid parameter name

**Expected behavior**
alias is deleted
**Desktop (please complete the following information):**

 - OS / Distro: macOS
 - Latest ohmyzsh update?: Yes
 - ZSH Version: zsh 5.3 (x86_64-apple-darwin18.0)
 - Terminal emulator:Terminal

**Comment by mcornella** [comment]
To remove aliases the command is `unalias`. `unalias gca!` should work without even having to quote the exclamation point.

**Comment by MiCkSoftware** [comment]
> To remove aliases the command is `unalias`. `unalias gca!` should work without even having to quote the exclamation point.

OMG that was stupid. Thanks.
