### ISSUE TITLE
Add compatibility of colorize plugin for zsh<5.1

### ISSUE THREAD

**Issue by spreiter** [ohmyzsh/ohmyzsh#9389]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
Plugin: colorize

**Is your feature request related to a problem? Please describe.**
CentOS7 / SL7 still used zsh 5.0.3, which does not support `local var=name` directly with arrays. See documentation of _"Changes between versions 5.0.8 and 5.1"_ at http://zsh.sourceforge.net/releases.html .

With zsh 5.0.3 running `cless` or `ccat` fails with the following message:
```
colorize_check_requirements:1: number expected
```

**Describe the solution you'd like**
Change the definition to the old way. (tested)
```
 colorize_check_requirements() {
-    local available_tools=("chroma" "pygmentize")
+    local -a available_tools
+    available_tools=("chroma" "pygmentize")
```

**Comment by mcornella** [comment]
Great, can you submit a PR?

**Comment by spreiter** [comment]
Sorry, no. I tried to push a branch, but it was not possible. Feel free to handle it.

**Comment by mcornella** [comment]
You need to create a fork of the project and then push a branch to your fork. Then you'll be able to submit a Pull Request. Here is this process detailed: https://opensource.com/article/19/7/create-pull-request-github.

For this change though, you can just use the GitHub web editor and it'll create the fork and submit the PR for you. Just go to the [colorize plugin file](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/colorize/colorize.plugin.zsh) and click on the pencil to make your edit, and then follow the steps to create the Pull Request.

Of course, if you're still not sure how to do it I can just do it for you, but I'd like you to try first. Thanks!

**Comment by spreiter** [comment]
Thanks, this worked.
