### ISSUE TITLE
解决国内被墙，安装比较慢的问题

### ISSUE THREAD

**Issue by wsdo** [ohmyzsh/ohmyzsh#9391]
打开这个网址：https://ohmyz.sh/，安装官网的方式比较慢，使用下面的 国内cdn方式。

解决mac安装zsh  被墙 方案，或者比较慢的方案

cdn地址：https://www.devland.cn/snippet/mac/env/5f97935a898f2

如何，安装飞速吧！

**Comment by mcornella** [comment]
Can you translate in English? I can't help you if I don't understand you.

**Comment by lydhr** [comment]
### Translation:
The download speed might be slow because of the Great Firewall. 
Try CDN: https://www.devland.cn/snippet/mac/env/5f97935a898f2
