### ISSUE TITLE
Enhancement by Giving option to keep history limit on 'command not found' commands.

### ISSUE THREAD

**Issue by PrajjwalDatir** [ohmyzsh/ohmyzsh#9392]
### **Why?**
We get frustuated when we either mistakenly pastes something on the terminal and gives out 10-15 command not found errors and worse all this gets stored in history so we have to hit Up key 10 times to see our previous 'good' command.
- eg. In Competitive Coding we have to paste test cases ( inputs) from their website to terminal. Sometimes interpreter driven (python) codes fail in between and all the inputs after that gets passed as a command line argument
[Link to screenshot](https://imgur.com/a/QXtSd0k)
- eg. When I am making small grammetical mistakes in writing command so I end up trying few times before I get correct. So now I don't need those other misspelled command in my history.

### Basic idea
The simple solution to this I can think of is maintaining 2 history type. 
- 'good' commands history : commands who actually did something and didn't throw command not found error.
- 'bad' commands : commands who gave 'command not found' error.

### How to classify?
- Simplest solution I think is limiting the number of bad commands getting saved which is indeed user configurable. For example if I misspelled a command I am only gonna hit Up once.  
So having just bad command' **history limit** to 5 is enough for me.
- Indeed there can be better ways to manage this. If you have any suggest please.

### Extra
if you can guide me to the code which takes care of history I might be able to code/pseudo-code a solution

** Sorry if this issue/enhancement is already mentioned as I only read 30-40 issues to crosscheck **

**If there's already solution to this I am unaware of please show me**

**Comment by mcornella** [comment]
You can achieve that in the following way:

```zsh
precmd_history() {
	# Inserts into history only if the exit code is 0
	[[ $? -eq 0 ]] || return
	# If you want to only skip command-not-found errors, you'd do 
	# [[ $? -ne 127 ]] || return
	print -sr -- "$_zsh_hist_command"
}

add-zsh-hook precmd precmd_history

zshaddhistory() {
	# Record command for use in precmd_history
	_zsh_hist_command="${1%%$'\n'}"
	# Prevent all commands from being recorded in history
	return 1
}
```

This is very rough and might have bugs in edge cases, but you can try it and let me know if it works.

One more thing: I know this was your proposed solution to your problem, but another way you can avoid command not found errors when pasting commands is to use the command editor with `CTRL`+`X` followed by `e`. This way you can paste into the command prompt and modify it before you're sure you want to run. It also has the effect that all lines will be run at once, so you only have one history entry and not a hundred.

**Comment by PrajjwalDatir** [comment]
Just for the record
- I am discussing solution to this with my collegues will get back here once we decide something.
- we tried your code snippet, Yeah it works but we are not yet satisfied.

What we have discuss so far?
- To create an external script(like a plugin/extension) which we just have to put on top of the .zshrc.
- This will make history into 2 types
- history stored in normal way in .zhistory
- 1. second it'll create a folder named let's say zhistoryFolder.
  2. it'll then redirect the history into different files depending on the exit code ( like you did but for more cases ).
  3. Like the ctrl-r ( search feature accessible from terminal itself ) we are thinking about giving a key binding to switch between accesing 'good commands' to 'bad commands' etc.
  4. like we switch the modes[Normal, Insert, Visual] in vim we are thinking to have modes which will fetch history from corresponding files in zhistoryFolder.
  5. By default it'll be reading from .zhistory and can be configured on/off from the ohmyzsh configure so no issues for people who don't prefer this.
  6. It'll *NOT* redirect history into zhistoryFolder, rather it'll make 2 copies of command each time so that it won't conflict with original functionality.

#### - is there anything like this already?
#### - if No : can we (my team) work on this from January?
#### - We would love to hear about your response regarding this.

**Comment by PrajjwalDatir** [comment]
I'm waiting for the reply ☺️

**Comment by mcornella** [comment]
I find that too convoluted, but if your use case requires that go ahead with it. You can look up the `per-directory-history` plugin for ideas on how to maintain the different history files.

**Comment by mcornella** [comment]
I'm going to close this since this is not something we're going to work on, but you're free to try it out yourself.

**Comment by PrajjwalDatir** [comment]
Yeah sure! Thanks for the support :)
