### ISSUE TITLE
git-prompt plugin doesn't display properly

### ISSUE THREAD

**Issue by TyMick** [ohmyzsh/ohmyzsh#9395]
### Describe the bug

The [`git-prompt` plugin](https://github.com/ohmyzsh/ohmyzsh/tree/d05544562532fdf4d5f4a4d4eba01f4263e17cc7/plugins/git-prompt) isn't replacing my theme's default git prompt. Depending on the theme, it either adds an extra `git-prompt` prompt on the right side of the terminal (but missing a closing parethsesis) or it doesn't show up altogether.

After seeing #8936 (which this might be a duplicate of), I tried disabling the `git` plugin, but it turns out themes display git prompts independently of whether or not the `git` plugin is enabled. I also tried several different themes (that's `robbyrussell` and `arrow` in the screenshots below), but `git-prompt` didn't work with any of them.

### To Reproduce

1. Add `git-plugin` to the `plugins` array in `.zshrc`.
2. `exec zsh`
3. `cd` into any git repository.

### Expected behavior

I should see a git prompt matching [`git-prompt`'s examples](https://github.com/ohmyzsh/ohmyzsh/tree/d05544562532fdf4d5f4a4d4eba01f4263e17cc7/plugins/git-prompt#examples) in the correct location for my theme.

### Screenshots and/or Recordings

<img width="570" alt="Screen Shot 2020-10-28 at 11 02 11 AM" src="https://user-images.githubusercontent.com/5317080/97470385-77cf1600-1915-11eb-85a6-20726b6fee95.png">
<img width="570" alt="Screen Shot 2020-10-28 at 11 14 22 AM" src="https://user-images.githubusercontent.com/5317080/97470397-7998d980-1915-11eb-8421-fbad6d55750a.png">

### Desktop (please complete the following information):

- OS / Distro: macOS 10.15.7 (19H2)
- Latest ohmyzsh update?: Yes
- ZSH Version: 5.7.1 (x86_64-apple-darwin19.0)
- Terminal emulator: Mac Terminal, VSCodium

### Additional context

Here's my `.zshrc` (excluding comments):

```sh
export ZSH="/Users/tymick/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(
    alias-finder brew colored-man-pages command-not-found common-aliases
    copybuffer copydir copyfile git git-auto-fetch git-prompt safe-paste sudo
    vscode web-search
)
source $ZSH/oh-my-zsh.sh
```

And here's my `.oh-my-zsh/custom`: [https://github.com/tywmick/ohmyzsh-custom](https://github.com/tywmick/ohmyzsh-custom/tree/b755d24aae5b81cbb5d127ff132edf38da766373)

**Comment by jerome-benoit** [comment]
Same issue here.

**Comment by mcornella** [comment]
As noted by Jérôme, to use the plugin you need to customise your theme to use the `git-prompt` function instead. See [the guide here](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes).
