### ISSUE TITLE
Show the command attached to the alias when executing it

### ISSUE THREAD

**Issue by fcappi-ciandt** [ohmyzsh/ohmyzsh#9399]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
no, should be applied to all the plugins

**Is your feature request related to a problem? Please describe.**
If you are showing your terminal to another person who is not familiar with the ohmyzsh aliases, she can get a little bit confused cause she does not know what you are doing and then you have to explain the alias or do not use it.

**Describe the solution you'd like**
I think it would be great if you could enable an option to show the command that is really being executed just before the command output.

Example:
`k get namespaces`

output:
```
[!] kubectl get namespaces
<kubectl output>
```

**Comment by mcornella** [comment]
This is really easy, just a two-line change:
```zsh
preexec_show_aliases() { echo '[!] '"$2"; }
add-zsh-hook preexec preexec_show_aliases
```

A preexec hook receives several parameters: `$1` is the exact command typed in the command line and `$2` is that command alias-expanded. You can play further with the `preexec_show_aliases` function to get it to print exactly how you want it to.
