### ISSUE TITLE
Add optional support to mercurial in agnoster theme

### ISSUE THREAD

**Issue by lromor** [ohmyzsh/ohmyzsh#9404]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
agnoster

**Is your feature request related to a problem? Please describe.**
agnoster becomes really have when dealing with large VCS projects. By debugging, I noticed that often, in a git repository, 
the prompt doesn't newline and gets stuck at hg id even though the folder is not a mercurial repository making the overall
oh my zsh agnoster theme really slow. By removing mercurial from my system, I already notice a huge difference.

**Describe the solution you'd like**
Add some sort of configuration flag to disable mercurial checks.

**Describe alternatives you've considered**
I removed mercurial which is a bit extreme.

**Comment by Cyberbeni** [comment]
You could just override [build_prompt](https://github.com/ohmyzsh/ohmyzsh/blob/852a44094a3bb4df39f8f778bc7ada2ddda09727/themes/agnoster.zsh-theme#L246) to only include the useful segments. (Make sure you do it after you source `oh-my-zsh.sh`)

For example current version without the mercurial part.

```
ZSH_THEME="agnoster"
...
source $ZSH/oh-my-zsh.sh
...
build_prompt() {
  RETVAL=$?
  prompt_status
  prompt_virtualenv
  prompt_aws
  prompt_context
  prompt_dir
  prompt_git
  prompt_bzr
  prompt_end
}
```

For my own personal prompt, I copied some useful parts from agnoster, set up git status based on [this](https://github.com/romkatv/gitstatus/blob/master/gitstatus.prompt.zsh) (it is faster and also includes number of changes) and added a couple other customizations relevant to my current work environment.

**Comment by lromor** [comment]
Hi, yes I could do that, but I'm not sure how that would interact with the auto-update feature.

**Comment by mcornella** [comment]
You can just run `prompt_hg(){}` in your zshrc file. That said, `hg` shouldn't take long to know it's not in a mercurial repo, can you post the output of `hg id` in a repository where you find it to be slow? You could also post a trace of the `prompt_hg` function by running `functions -t prompt_hg` and going to a repository you find it to be slow.

**Comment by lromor** [comment]
I just found that the difference is more noticeable when issuing newlines/SIGINTs. With hg, the new prompt is not rendered after a bunch of ENTERs. Without hg, it seems to respond much quicker. 

Anyways, after a fresh restart, It's much more bearable.

These are the outputs you requested:
`hg id`:
```
abort: there is no Mercurial repository here (.hg not found)
```

 and `functions -t prompt_hg` prints nothing.

**Comment by lromor** [comment]
Ok, I noticed that I was wrong, it's not just a mercurial problem. Not sure who's the culprit, but it's such a minor issue which I don't think I will try to investigate it more. Thank you for answering and sorry for the fuss :)

**Comment by mcornella** [comment]
Normally the problem is in the git status prompt. You can prove that's the case by noop-ing the `prompt_git` function: `prompt_git(){}`.
