### ISSUE TITLE
AWS plugin MFA for source profiles

### ISSUE THREAD

**Issue by robvadai** [ohmyzsh/ohmyzsh#9408]
Originator: https://github.com/ohmyzsh/ohmyzsh/issues/9394

Hi @maksyms ,

it works fine when I use a role but it doesn't prompt for MFA for the source profile anymore.

I added mfa_serial to my source profile.

So this source profile has mfa_serial but not role_arn and source_profile obviously.

I fixed it but the code has some duplications, need to tidy it up: https://github.com/ohmyzsh/ohmyzsh/compare/master...robvadai:bugfix/aws-mfa-with-source?expand=1

**Comment by maksyms** [comment]
@robvadai Could yo please share your anonymised `.aws/config` and `.aws/credentials`? I want to understand your setup please.

**Comment by robvadai** [comment]
`~/.aws/credentials`

```
[myprofile]
aws_access_key_id = ...
aws_secret_access_key = ...
```


`~/.aws/config`

```
[profile myprofile]
mfa_serial = arn:aws:iam::11111111111111:mfa/myuser
region = eu-west-1
output = json

[profile other_profile]
role_arn = arn:aws:iam::9999999999:role/user-myuser
mfa_serial = arn:aws:iam::11111111111111:mfa/myuser
source_profile = myprofile
region = eu-west-1
output = json
```



So my issue was when I wanted to authenticate with MFA for `myprofile`

**Comment by maksyms** [comment]
Ok, so you want MFA to happen when you change to both `myprofile` and `other_profile`, not only `other_profile`, right? If so - yes, I can see why it might not work, fair point.

**Comment by robvadai** [comment]
Yep exactly, for one company this is the set up. The other company merely uses the source profile to allow other roles' access.

**Comment by maksyms** [comment]
@robvadai understood. I've only come across "the other company" setups, hence "one company" use case wasn't catered for. I'll check your suggestions later, thanks again! 👍

**Comment by maksyms** [comment]
@robvadai I've added this feature to the plugin. I have a suspicion it will also affect #9409 . 

Could you please test before I go ahead with a pull request?

The updated version of the plugin is here:

https://github.com/maksyms/oh-my-zsh/blob/mfa_for_source_profile/plugins/aws/aws.plugin.zsh

**Comment by robvadai** [comment]
MFA for 'source profile' works; what still doesn't work is here: https://github.com/ohmyzsh/ohmyzsh/issues/9409#issuecomment-720502633

**Comment by robvadai** [comment]
The problem described in this issue is solved with your changes, shall we merge it to move on?
