### ISSUE TITLE
AWS plugin omitting MFA session time results in error

### ISSUE THREAD

**Issue by robvadai** [ohmyzsh/ohmyzsh#9409]
```
acp myprofile
Please enter your MFA token for arn:aws:iam::1111111111:mfa/myuser:
123456
Please enter the session duration in seconds (900-43200; default: 3600, which is the default maximum for a role):


An error occurred (AccessDenied) when calling the GetSessionToken operation: MultiFactorAuthentication failed, unable to validate MFA code.  Please verify your MFA serial number is valid and associated with this user.
Switched to AWS Profile: myprofile
```

**Comment by robvadai** [comment]
@maksyms

**Comment by maksyms** [comment]
Thanks, @robvadai . The error in the message hints at it: the problem is that you get AccessDenied due to your MFA failing because, it seems, it cannot find your `mfa_serial`. Still need the anonymised config files please.

**Comment by maksyms** [comment]
I can see your config in #9408. I will check and revert, thanks for the reports!

**Comment by robvadai** [comment]
After the changes in https://github.com/ohmyzsh/ohmyzsh/issues/9408#issuecomment-719959274 I still get:

```
An error occurred (AccessDenied) when calling the GetSessionToken operation: MultiFactorAuthentication failed, unable to validate MFA code.  Please verify your MFA serial number is valid and associated with this user.
```

if I'm using the 'source profile'; for a role'd profile, it works with default value

**Comment by maksyms** [comment]
@robvadai 

Hang on, so let me understand this:

1. You run `acp source_profile`
2. You *enter* the MFA code and session length
3. It works

Then:

1. You run `acp source_profile`
2. You *enter* the MFA code, but *don't enter* session length
3. It doesn't work

Is that correct? Is that the only difference?

Your error indicates that the issue has nothing to do with the timeout, but has something to do with MFA serial number of MFA code.

Can you try running something like:

`aws sts get-session-token --profile=your_source_profile --serial-number your_mfa_serial --token-code your_mfa_code --duration-seconds 3600`

It should still give you the same error as above - and if it does, then it is your setup, not the plugin. If it doesn't, I'm puzzled.

It works perfectly fine for me:

![image](https://user-images.githubusercontent.com/595059/97894476-709b7400-1d2a-11eb-9cfb-815c8ea69ead.png)

**Comment by robvadai** [comment]
The problem statement is correct

**Comment by robvadai** [comment]
I can confirm the command `aws sts get-session-token` works fine, no error

**Comment by maksyms** [comment]
Then I'm puzzled.

I'll prepare a more verbose version that prints the complete command that's being executed and share here. I cannot currently understand why the manual command works and exactly the same command from a script doesn't. I can imagine a few unlikely reasons (globbing, environment, chroot, etc), but none that would explain different results under the same circumstances.

**Comment by robvadai** [comment]
maybe put it on a branch and send me a PR: https://github.com/robvadai/oh-my-zsh
so I can test it

**Comment by maksyms** [comment]
@robvadai Added logging, let me know the output please. A screenshot with the sensitive bits blanked out would be preferable.

**Comment by mcornella** [comment]
I refactor the acp function and fixed a few zsh quirks in https://github.com/ohmyzsh/ohmyzsh/pull/9426. You can test it with `omz pr test 9426`.
