### ISSUE TITLE
Offline installation package

### ISSUE THREAD

**Issue by EricMzky** [ohmyzsh/ohmyzsh#9415]
When my device has no way to connect to the Internet, and there is no offline package to install this software?

**Comment by mcornella** [comment]
You can [download a copy of the repository](https://github.com/ohmyzsh/ohmyzsh/archive/master.zip) separately, extract it wherever you want and then copy the `templates/zshrc.zsh-template` file to `~/.zshrc` and change the `$ZSH` variable to point to the folder where you extracted the zip file.

**Comment by Rogerff48** [comment]
Stop
