### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by gajahduduk** [ohmyzsh/ohmyzsh#9419]
I'm trying to get my commonly-used aliases to work in zsh.   I'm a total zsh noob, and just a basic user of bash. I just upgraded to MacOS Catalina and switched shells to .zsh as instructed (by Apple). I quickly installed ohmyzsh in the hopes of speeding up configuration.

**Problem:** Simple aliases don't work.  What am I doing wrong?

Also, the sole function shown at the top I used all the time in bash. (I didn't write it.) Should that work too? (And if not how can I modify it to work as an alias?)

Here's a representation of what I'm doing:

````
~ » cd .oh-my-zsh  
                                                                                                                                                                     
~/.oh-my-zsh(master*) » more aliases.zsh                                                                                                                                                      

function zfp { ps axcru | grep -i "$@" | grep -v "[p ]grep" ; }
alias testalias="echo 'test this alias'"
alias ztp='top -u -s3 10'

~/.oh-my-zsh(master*) » ztp                                                                                                                                                                   user@compuer
zsh: command not found: ztp

~/.oh-my-zsh(master*) » testalias                                                                                                                                                       127 ↵ user@compuer
zsh: command not found: testalias

~/.oh-my-zsh(master*) » source ~/.zshrc                                                                                                                                                 127 ↵ user@compuer
[oh-my-zsh] Random theme 'eastwood' loaded

*[master][~/.oh-my-zsh]$ testalias                                                                                                                                                            user@compuer
zsh: command not found: testalias

*[master][~/.oh-my-zsh]$ ztp                                                                                                                                                            127 ↵ user@compuer
zsh: command not found: ztp
```

**Comment by mcornella** [comment]
[It's not very well documented](https://github.com/ohmyzsh/ohmyzsh#custom-plugins-and-themes), but you need to put the `aliases.zsh` file inside `$ZSH_CUSTOM` for OMZ to load it:
> If you want to override any of the default behaviors, just add a new file (ending in .zsh) in the custom/ directory.

**Comment by gajahduduk** [comment]
Thank you, but where is $ZSH_CUSTOM?  I thought I read elsewhere that it is ~/.oh-my-zsh by default, which is why I put it there (and showed it there above).

**Comment by mcornella** [comment]
To refresh it's better to use `exec zsh`. `source ~/.zshrc` might have side effects because you're executing .zshrc twice in the same zsh session.
