### ISSUE TITLE
fatal: could not create leading directories error on macOS

### ISSUE THREAD

**Issue by dfontenot** [ohmyzsh/ohmyzsh#9427]
When I run `sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"` on macOS, I get the following error

```
Cloning Oh My Zsh...
fatal: could not create leading directories of '/home/me/.oh-my-zsh': Operation not supported
Error: git clone of oh-my-zsh repo failed
```

This is for a fresh install. My home directory is `/Users/mydomainlogin`. I'm running macOS on a computer managed by my work, so not only is the OMZ installer trying to install OMZ in the standard Linux home directory, it's also thinking that my firstname is my username (whereas whoami reports `mydomainlogin`). I also tried running bash and then invoking the install script, but I still get the same error.

Does anyone know what may be causing this issue?

macOS version: 10.15.7, Catalina
ZSH: 5.8 (from Homebrew)
Terminal: tried iTerm2 and the stock Terminal app

**Comment by mcornella** [comment]
Have you perhaps changed the `$ZSH` variable? Run `echo $ZSH` to check. If so, run `unset ZSH` and call the installer again.

**Comment by mcornella** [comment]
Another option is that `$HOME` points to `/home/me`.

**Comment by dfontenot** [comment]
@mcornella yep `$ZSH` was set to `/home/me/.oh-my-zsh` and `$HOME` was set correctly. `unset ZSH` worked.

**Comment by devjasim** [comment]
> Have you perhaps changed the `$ZSH` variable? Run `echo $ZSH` to check. If so, run `unset ZSH` and call the installer again.

And how to set the path again??

**Comment by mcornella** [comment]
> > Have you perhaps changed the `$ZSH` variable? Run `echo $ZSH` to check. If so, run `unset ZSH` and call the installer again.
> 
> And how to set the path again??

Open a new issue with the details of your problem, it's not clear what you're asking.

**Comment by aaronArinder** [comment]
thank you, @mcornella!
