### ISSUE TITLE
Have no history in new tabs

### ISSUE THREAD

**Issue by svitovyda** [ohmyzsh/ohmyzsh#9430]
I understand from the similar issues, in latest release was implemented possibility to have separate history of commands. I used `unsetopt no_share_history` and `setopt share_history` in all console tabs, but after restart of my PC some of consoles now have absolutely no history, which kinda blocks me from normal effective work.
Can I set somewhere that i want always and everywhere have all my history shared among every tab ever and never ever lose it unless I explicitly configure it?

**Comment by svitovyda** [comment]
@mcornella , once more: i added `setopt share_history` and `unsetopt no_share_history` to the `~/.zshrc` but i still have only today's story in bunch of my tabs. I want my global history everywhere and i want the separate tabs history to be destroyed / merged to global one. Is that possible? Please add any comment aside from just close my support!

**Comment by mcornella** [comment]
I pushed an update reenabling `share_history` back. You can get it by running `omz update` and restarting the zsh session with `exec zsh`. If that still doesn't get you your global history back, post the output of `setopt` here.

**Comment by svitovyda** [comment]
My terminal (in MacOS) new windows/tabs give me the full history, but for some reason the terminal in Intellij Idea doesn't pick even yesterdays full history. Here is setopt from Idea terminal:

```
alwaystoend
autocd
autopushd
completeinword
extendedhistory
noflowcontrol
histexpiredupsfirst
histignoredups
histignorespace
histverify
incappendhistory
interactive
interactivecomments
login
longlistjobs
monitor
promptsubst
pushdignoredups
pushdminus
sharehistory
shinstdin
zle
```

Mac Terminal contains the same, plus `completeinword`

**Comment by mcornella** [comment]
Can you post the output of `typeset -m '*HIST*'` in both the working terminal and the non-working one?
