### ISSUE TITLE
I cannot print a single minus character

### ISSUE THREAD

**Issue by leoheck** [ohmyzsh/ohmyzsh#9434]
**Describe the bug** && **To Reproduce**
I cannot print a single minus character
![image](https://user-images.githubusercontent.com/1277920/98738125-fe5c0c80-2385-11eb-8e44-b9051969ac84.png)

 - OS / Distro: Ubuntu 20.04
 - Latest ohmyzsh update? Yes
 - ZSH Version: zsh 5.8 (x86_64-ubuntu-linux-gnu)
 - Terminal emulator: [e.g. Tilix]

**Comment by mcornella** [comment]
`echo` is weird when interpreting dash arguments. Use `print` with `--` or `printf`:
```
print -- -
printf "-\n"
```

**Comment by leoheck** [comment]
Alright, I know how to workaround, thanks anyway.
I am not aking for a workaround. I am reporting an issue.

![image](https://user-images.githubusercontent.com/1277920/98849132-80553f80-2431-11eb-8724-89214300e700.png)
