### ISSUE TITLE
Cannot create a new branch

### ISSUE THREAD

**Issue by edgellheather795** [ohmyzsh/ohmyzsh#9435]
I cannot create a new branch

**Describe the bug**
A clear description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin '...'
2. Run command '...' or try the autocomplete command '...'
3. See error

**Expected behavior**
A brief description of what should happen.

**Screenshots and/or Recordings**
You can also record an asciinema session: https://asciinema.org/

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro: [e.g. Arch Linux, macOS]
 - If on Windows what version of WSL: [e.g. WSL1, WSL2]
 - Latest ohmyzsh update?: [e.g. Yes/No]
 - ZSH Version: [e.g. 5.6]
 - Terminal emulator: [e.g. iTerm2]

**Additional context**
Add any other context about the problem here. This can be themes, plugins, custom configs.

**Comment by mcornella** [comment]
You provide no information and you didn't fill out the fields. I see you're a new GitHub user so you might not be familiar with it, but it's important to provide as much information as you can so we don't have to guess.

What commands are you running and in which directory? Is the directory a git repository? Are you seeing any errors? What errors are you seeing? Is this happening without Oh My Zsh?

**Comment by PrajjwalDatir** [comment]
@edgellheather795 If you meant, **you can't create new branch on this repositary.**
then
- You must first Fork this repositary from the Top Right button on the page.
- Then go to your profile, there you will be able to see this repositary cloned on to your profile.
- Create a new branch there.
I hope you were talking about this.
