### ISSUE TITLE
[Enhancement] colored-man-pages plugin

### ISSUE THREAD

**Issue by ratijas** [ohmyzsh/ohmyzsh#9436]
**Is your feature request related to a particular plugin or theme? If so, specify it.**

The [colored-man-pages](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/colored-man-pages) plugin.

**Is your feature request related to a problem? Please describe.**

Plugin code is needlessly complicated and undocumented. And I know how to make it better!

Also, unless someone can provide me with a reason for turning on Nroff Unsafe mode (`_NROFF_U=1`), I'm in favor of removing it. I'm not an expert in Groff/Nroff, but it just sounds dangerous.

And what's the deal with silently creating executable scripts in `$HOME/bin`? Thanks God, it does not affect me — only solaris users. But that is certainly **not** what I would expect from a plugin like this. At the very least, it should ship that executable script with the plugin, and extend PATH to its parent directory. It's not like plugins aren't allowed to provide additional supporting files, do they?

**Describe the solution you'd like**

Please, take a look at [my rewrite](https://github.com/ratijas/dotfiles/commit/81e83202c2a852c2e53f1727f87652054645874a) @ my personal dotfiles repository! Sure, I stripped down parts I don't need on my system, but otherwise it can be copy-patched into oh-my-zsh.

My solution requires `autoload colors` for named colors, which is loaded by `lib/theme-and-appearance.zsh` anyway. I'm looking forward to any feedback.

**Additional context**

None

**Related Issues**

None

**Comment by mcornella** [comment]
> Also, unless someone can provide me with a reason for turning on Nroff Unsafe mode (`_NROFF_U=1`), I'm in favor of removing it. I'm not an expert in Groff/Nroff, but it just sounds dangerous.

If you look at the `nroff` binary put in `$HOME/bin`, that variable is used to pass in `-u1` to `nroff`, which [sets the "emboldening factor"](https://docs.oracle.com/cd/E36784_01/html/E36870/nroff-1.html). This just means that bold text will be made more bold, if that makes sense. Apparently in Solaris, `nroff` is called with `-u0` which means bold text is not printed bold, but I'm going to look at whether we can get rid of it. If not, I agree on moving it to the plugin folder.

As for the rest, +1 on using `colors` variables, -1 on putting them outside the function. So I made them local and removed the whole array setting thing: 5e8f2d5b.

What do you think?

**Comment by ratijas** [comment]
@mcornella Thanks! Yeah, I already figured it out. It is exactly as you said. I'm already building a branch to fix it here: https://github.com/ratijas/ohmyzsh/commit/2129fc6838aaf07ca869866638bc91b295ebcd36

However, I'll force push later, so the link is likely to expire.

**Comment by ratijas** [comment]
Here goes nothing... #9437
