### ISSUE TITLE
APP Snaps icon packs a few after using On My ZSH with KDE

### ISSUE THREAD

**Issue by ediano** [ohmyzsh/ohmyzsh#9445]
I'm using KDE Neon 5.20, after installing ZSH the icons of the snaps packages are no longer available in the released Plasma, so the only way to access the APP is by searching for its name, I noticed that this also happens with Kubuntu, Xubuntu, and other derivatives with KDE.

I was able to correct the problem by adding the following line `emulate sh -c 'source /etc/profile.d/apps-bin-path.sh'` in the file `/etc/zsh/zprofile`.

But this is a bit of a pain to keep doing, are there any other alternatives, or any predictions for correcting the problem?

NOTE: I am not using plugs with ZSH.

**Comment by mcornella** [comment]
This is not an OMZ bug. I think you should track this issue: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1640514.
