### ISSUE TITLE
possible to share configs between users and in sudo? (mac)

### ISSUE THREAD

**Issue by CouldBeThis** [ohmyzsh/ohmyzsh#9449]
Hi, 

I just installed zsh and omz on Mac OS 10.14 using iterm. For context I am a person with a rudimentary grasp of *nix. 

I think this is pretty spiffy and I would like to

1. share plugin, theme and other configurations between users on my machine. So for example if I install and enable a theme for user1, user2 will be the same. 

2. for above, also include sudo/su/root. 

For (1) some possible ways of doing this might be
a. tell zsh that instead of looking for it's configuration files in  `~/.oh-my-zsh`, it should look elsewhere and specify a location outside any home directory (to avoid permissions issues I guess). 
b. use some sort of syncing program to watch for changes in any of the relevant files/directories and automatically update all the others as needed

I am not able to locate any zsh/omz config files in home directory for root which `/var/root` so even if I had to do it manually I am not sure how. 

Also I will say that even though I have multiple users on my computer, I am actually the only person who uses it. So any solution need not be comprehensible to anyone else, and there would be no possibility of the same file being actively edited by multiple people simultaneously. 

i'm sure someone else has already thought of this and figured it out.. unfortunately it's the kind of problem whose keywords are so vague as to make finding info difficult

any thoughts aoppreciated

**Comment by mcornella** [comment]
You can manually install OMZ in a common folder, like `/usr/share/ohmyzsh`, and then add the relevant configuration to `/etc/zshrc` (macOS-specific path) (`ZSH=/usr/share/ohmyzsh`, `ZSH_THEME`, `plugins` and other OMZ settings, and the `source $ZSH/oh-my-zsh.sh` line).

> there would be no possibility of the same file being actively edited by multiple people simultaneously.

I understand here that you can't use the same file for all, but I think that makes it unnecessarily difficult. In fact, this clashes with the requirement

> b. use some sort of syncing program to watch for changes in any of the relevant files/directories and automatically update all the others as needed
