### ISSUE TITLE
symlink is expanded in prompt after using sudo

### ISSUE THREAD

**Issue by zhanglongqi** [ohmyzsh/ohmyzsh#9454]
`.oh-mu-zsh` commit id is `9b11986`

`Linux bbe-0 4.14.108-ti-r137 #1bionic SMP PREEMPT Tue Aug 25 02:46:55 UTC 2020 armv7l armv7l armv7l GNU/Linux`

`zsh 5.4.2 (arm-unknown-linux-gnueabihf)`

![image](https://user-images.githubusercontent.com/956693/99504265-400a3a00-29ba-11eb-9ec3-85ad6508c03e.png)

**Comment by mcornella** [comment]
What theme is that?

**Comment by zhanglongqi** [comment]
The theme is `ys`

**Comment by mcornella** [comment]
I can reproduce this when doing `sudo -s` and the root user has the proper configuration (OMZ installed, theme which shows the full path).

I couldn't reproduce this when running `sudo -E -s`, which doesn't require root to have OMZ installed and keeps the environment the same as in the session of the previous user.

This, unfortunately, is a "bug" in how sudo works: it `cd`s to the target if `$PWD` is a symlink. This happens with or without OMZ, you just need to `echo $PWD` before and after changing to root. If you want to keep the same directory you can use `sudo -E -s`, like I said above.
