### ISSUE TITLE
I reported an error when I installed zsh-autosuggestions

### ISSUE THREAD

**Issue by icexk** [ohmyzsh/ohmyzsh#9455]
hi：I reported an error when I installed zsh-autosuggestions

The error message is as follows：
/Users/ice/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh:source:1: no such file or directory: /Users/ice/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh^M

macOS: 10.13.6
zsh --verison
zsh 5.8 (x86_64-apple-darwin17.7.0)

I installed it
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

vim  ~./.zshrc

plugins=(git zsh-autosuggestions)

source ~/.zshrc 

Then report the error

**Comment by mcornella** [comment]
Looks like you cloned the zsh-autosuggestions with git's `core.autocrlf` setting turned on. Try going into the zsh-autosuggestions folder and run the following:
```zsh
git config core.autocrlf false    
git rm --cached -r .    
git reset --hard 
```
