### ISSUE TITLE
Vertical allign in zsh.

### ISSUE THREAD

**Issue by arijitAD** [ohmyzsh/ohmyzsh#9456]
I am using iterm+zsh. Is there any way to vertically allign(center) after the command is executed?

**Comment by mcornella** [comment]
You mean making the prompt line be at the vertical center of the terminal, like this?
![image](https://user-images.githubusercontent.com/1441704/99882120-7d6f0180-2c1e-11eb-9270-0e3fc7556ca9.png)

**Comment by arijitAD** [comment]
> You mean making the prompt line be at the vertical center of the terminal, like this?
> ![image](https://user-images.githubusercontent.com/1441704/99882120-7d6f0180-2c1e-11eb-9270-0e3fc7556ca9.png)

Yes

**Comment by mcornella** [comment]
This seems to work:
```zsh
precmd_center() {
  local CENTER=$(( LINES / 2))
  # print as many lines necessary so that content moves upward past half-screen
  printf '%.0s\n' {1..$(( LINES - CENTER ))}
  # move the cursor upward as many lines where printed to put it back where it was
  tput cuu $(( LINES - CENTER ))
}
add-zsh-hook precmd precmd_center
```

**Comment by arijitAD** [comment]
Thanks.
