### ISSUE TITLE
plugin pyenv does not work or I don't know How use it ?

### ISSUE THREAD

**Issue by mnekkach** [ohmyzsh/ohmyzsh#9461]
Hi,

I just install a fresh version of ohmyzsh and I want to use pyenv plugin.

so I have add the plugin in my .zshrc 

`plugin=(git pyenv)`

I have restart my shell, but when I am in a directory with a pyenv local python version (I have .python-version in my folder) they are nothing in my prompt.

Normaly the version of python should be write in my prompt ?

thanks for your help

**Comment by mcornella** [comment]
I assume `pyenv` is installed? Does `pyenv` automatically add the version to the prompt? If not, then you'd have to manually add the `pyenv_prompt_info` function to `$PROMPT` or `$RPROMPT` so that it is shown.

**Comment by mnekkach** [comment]
I don't know what I do but now I have the python version in the right prompt. I have just install virtualenv in the pyenv/plugins folder. I'm going to make an over test in a new virtual machine to understand what's happened. Thanks for your answer.

**Comment by CmdQ** [comment]
Isn't the pyenv plugin mainly about finding pyenv and setting up its completion?

If you want the prompt you'll also have to look for a theme that supports it. Or try [starship](starship.rs/).

**Comment by agoose77** [comment]
@mnekkach it might be unrelated, but what happens if you add `eval "$(pyenv virtualenv-init -)"` to your `bashrc`?

See #8467 for more

**Comment by agirorn** [comment]
There seems to have been a fundamental change on how this plugin works in [8efcf27](https://github.com/ohmyzsh/ohmyzsh/commit/8efcf2776b2e7e00c073b149f76c04715aa695d3#diff-b6865657813739f9d07639d70642974ef35ff2b72529eefa76e1b9bc08852d84). It used to set the PYENV_ROOT and PATH environment variables that are required by pyenv see `pyenv init` output below.

To fix this you could add this to your RC file (.bashrc, .zshrc, ...)

```shell
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/shims:$PATH"
```

*pyenv init output*
```shell
# (The below instructions are intended for common
# shell setups. See the README for more guidance
# if they don't apply and/or don't work for you.)

# Add pyenv executable to PATH and
# enable shims by adding the following
# to ~/.profile and ~/.zprofile:

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# Load pyenv into the shell by adding
# the following to ~/.zshrc:

eval "$(pyenv init -)"

# Make sure to restart your entire logon session
# for changes to profile files to take effect.
```

I'd really like to know if this fix is the correct one or if pyenv plugins should completely manage this for me, like the nvm plugin does for node?

**Comment by mcornella** [comment]
As the plugin now says, you should do what you posted and add those lines to `.profile` and `.zprofile`.

**Comment by mcornella** [comment]
It should be fixed now. It still complains when pyenv isn't properly configured in `.profile` or `.zprofile`, but it does update the `$PATH` correctly. If you're OK with having it work only for interactive shells (won't work on scripts) then you can silence the warning with `ZSH_PYENV_QUIET=true` in your zshrc file, before OMZ is sourced.
