### ISSUE TITLE
ZSH issues after a known bug occurrence

### ISSUE THREAD

**Issue by tsecore** [ohmyzsh/ohmyzsh#9462]
Soon after installing Brew then NVM, I got the `Insecure completion-dependent directories detected:` error in Iterm2 on MAC Catalina (which comes installed with zsh) and after doing research, I stumbled upon https://github.com/ohmyzsh/ohmyzsh/issues/6835.  

Ran:
`chmod 755 /usr/local/share/zsh`
`chmod 755 /usr/local/share/zsh/site-functions`

and also did the following:

> Set ZSH_DISABLE_COMPFIX=true in your zshrc file, before oh-my-zsh.sh is sourced, and update OMZ to the latest version. It should ignore these permission issues and load the completion system normally.

Relaunched Iterm2, but it takes forever to load and all the commands run about 5 seconds slower than before.  Also gets stuck on `git` during the load - once it's fully loaded and in usable state, I get this error:

<img width="774" alt="Screen Shot 2020-11-20 at 1 16 59 PM" src="https://user-images.githubusercontent.com/13421938/99846884-62c05e00-2b34-11eb-8fd5-152d80dc5213.png">

After running the git diagnostics command as instructed got a long slew of errors which I'm filing an issue at:

>  https://github.com/romkatv/gitstatus/issues/new

I think `gitstatus` doesn't play nicely with POWERLEVEL9K

**Comment by mcornella** [comment]
I'm closing this issue because it's not related to Oh My Zsh.
