### ISSUE TITLE
Various bugs in magic-enter plugin

### ISSUE THREAD

**Issue by foxale** [ohmyzsh/ohmyzsh#9464]
**Describe the bug**
When using magic-enter together with zsh-autosuggestions, a displayed executed command contains an autosuggestion part, as if the suggestion was accepted and run, even if that's not the case. 

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Start with the following:
```
$ cd "$(mktemp -d)"
$ ZDOTDIR=$PWD HOME=$PWD zsh -f
% source path/to/ohmyzsh/plugins/magic-enter/magic-enter.plugin.zsh; source path/to/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
% touch foo
% ls foo
foo
% ls 
```
2. On the last line, make sure you press Space after ls, so you get the suggestion foo.
3. Then, press Enter.

**Expected behavior**
The suggestion should be cleared, as it is without `magic-enter`.

**Actual Result** 
The suggestion remains.

**Desktop (please complete the following information):**

 - OS / Distro: macOS
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.6
 - Terminal emulator: iTerm2

**Related**
https://github.com/marlonrichert/zsh-autocomplete/issues/131

**Comment by mcornella** [comment]
Confirmed bug, thanks for the reproduction test.

**Comment by mcornella** [comment]
This should do it: `ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(magic-enter)`.

**Comment by mcornella** [comment]
That only works if zsh-autosuggestions is loaded first. This fix will always work no matter the order of loading:
```zsh
magic-enter () {
  # If commands are not already set, use the defaults
  [ -z "$MAGIC_ENTER_GIT_COMMAND" ] && MAGIC_ENTER_GIT_COMMAND="git status -u ."
  [ -z "$MAGIC_ENTER_OTHER_COMMAND" ] && MAGIC_ENTER_OTHER_COMMAND="ls -lh ."

  if [[ -z $BUFFER ]]; then
    echo ""
    if git rev-parse --is-inside-work-tree &>/dev/null; then
      eval "$MAGIC_ENTER_GIT_COMMAND"
    else
      eval "$MAGIC_ENTER_OTHER_COMMAND"
    fi
    zle redisplay
  else
    # Call wrapped accept-line widget if wrapped. Fixes suggestions
    # not cleared when using the zsh-autosuggestions plugin.
    case "$widgets[accept-line]" in
    user:*) ${widgets[accept-line]#*:} ;;
    *) zle accept-line ;;
    esac
  fi
}
```

**Comment by mcornella** [comment]
Nevermind, we don't need all that crap, we can just wrap the `accept-line` widget and zsh-autosuggestions will understand that that's a "clear suggestions" widget:
```zsh
magic-enter () {
  # If commands are not already set, use the defaults
  [ -z "$MAGIC_ENTER_GIT_COMMAND" ] && MAGIC_ENTER_GIT_COMMAND="git status -u ."
  [ -z "$MAGIC_ENTER_OTHER_COMMAND" ] && MAGIC_ENTER_OTHER_COMMAND="ls -lh ."

  if [[ -z $BUFFER ]]; then
    echo ""
    if git rev-parse --is-inside-work-tree &>/dev/null; then
      eval "$MAGIC_ENTER_GIT_COMMAND"
    else
      eval "$MAGIC_ENTER_OTHER_COMMAND"
    fi
    zle redisplay
  else
    zle .accept-line
  fi
}

# Tell zsh that this is a wrapper for accept-line, the
# zle widget run by default when pressing Enter
zle -N -- accept-line magic-enter
```

We don't even need the `bindkey` lines anymore.

**Comment by mcornella** [comment]
Pushed the solution in #9466, please test it with `omz pr test 9466` and +1 it if it works.

**Comment by foxale** [comment]
The behaviour discribed in the issue is gone, but take a look at this: 
![image](https://user-images.githubusercontent.com/14327763/100012725-04190f80-2dd4-11eb-9f73-e84ee116cf2e.png)
Both executions should give the same result, yet when magic-enter executes the "git status -u ." command, one line of output is missing.

**Comment by mcornella** [comment]
I didn't change the branch where `$BUFFER` is empty so this shouldn't be a cause of my patch.

I can't reproduce this even with p10k. It must be an incompatibility with your exact configuration. Make sure though that before and after applying the patch the behavior is different. If so, post your p10k settings so I can try to reproduce the problem.

**Comment by foxale** [comment]
That's correct, after commenting out `source ~/.p10k.zsh` the problem disappears. 
My p10k settings: https://github.com/foxale/dotfiles/blob/master/powerline10k/.p10k.zsh

**Comment by mcornella** [comment]
Confirmed that this is a bug that already happened before my patch, and the setting you mention triggers it. @romkatv any idea on where to start to make the plugin compatible with p10k?

**Comment by romkatv** [comment]
> @romkatv any idea on where to start to make the plugin compatible with p10k?

If you make it compatible with plain zsh, that would be a good start. I haven't tried it but from looking at the code I think there are a few issues.

1. Type `echo '` (note the trailing quote) and press <kbd>Enter</kbd> twice. Expected: the same as in plain `zsh`. Actual: something weird.
2. Set `MAGIC_ENTER_GIT_COMMAND='sleep 3 && git status -u .' (to emulate slow `git status`). Type `ls -` and press <kbd>Tab</kbd> enough times for the completion menu to show up. Press <kbd>Ctrl+U</kbd> and <kbd>Enter</kbd>. Expected: the same as <kbd>Enter</kbd>. Actual: something weird.

**Comment by mcornella** [comment]
Alright I think I've fixed everything. @foxale please try it out with `omz pr test 9466` and let me know if it works now.

> 2\. Set `MAGIC_ENTER_GIT_COMMAND='sleep 3 && git status -u .'` (to emulate slow `git status`). Type `ls -` and press Tab enough times for the completion menu to show up. Press Ctrl+U and Enter. Expected: the same as Enter. Actual: something weird.

I couldn't reproduce this but hopefully #9466 makes it go away. Just to make sure though, <kbd>CTRL+U</kbd> being bound to the default `kill-whole-line` right? A screenshot of the weirdness would be great, but you obviously don't have to.

**Comment by romkatv** [comment]
That PR should fix these issues. It'll also now display the command being executed, which is a good think IMO.

There is only one issue that I can see -- if `accept-line` was a user-defined widget, it won't be called. Usually you should call the original widget when you wrap something. OMZ has the same problem in other places (e.g., `zle-line-finish` also wipes user-defined hooks), so maybe it's your policy to do it this way.

**Comment by mcornella** [comment]
I think I covered all cases. I'm basing on the zsh-autosuggestions code so apologies if there's some edge case I'm not aware of. I tested that it works even if the magic-enter plugin is loaded twice (which could happen when users incorrectly call `source .zshrc` to reload any zshrc file changes: 45bad460.

Thanks for the feedback!
