### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by zhangyupy** [ohmyzsh/ohmyzsh#9465]
sh -c "$(curl -fsSL http://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

curl: (7) Failed connect to raw.github.com:443; Connection refused

**Comment by sulizieiao** [comment]
I got same error and success installed by run:
```
git clone git://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh 
cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
```
then change theme or other config in .zshrc:
`ZSH_THEME='ys'  ##the theme you like`

finally, run:
`source ~/.zshrc`

**Comment by mcornella** [comment]
[This seemed to work for one user](https://github.com/ohmyzsh/ohmyzsh/issues/9391). NOTE: I can't guarantee the safety of using an install script other than the official one.

**Comment by mcornella** [comment]
Try to download the installer from this gitee.com mirror I've created:
```
sh -c "$(curl -fsSL https://gitee.com/mcornella/ohmyzsh/raw/master/tools/install.sh)"
```

**Comment by leafney** [comment]
The method of modifying the hosts file is better.

Get the following domain from  https://www.ipaddress.com/  and add to hosts file, just like:

```
140.82.113.3 github.com
185.199.110.133 raw.githubusercontent.com
```

Then just re-execute the official installation command.

**Comment by praabindh** [comment]
The Same Happened For But It Was Due To The GIT SSH Configuration

git config --global user.name "FIRST_NAME LAST_NAME"
git config --global user.email "MY_NAME@example.com"
