### ISSUE TITLE
oh-my-zsh may be setting `sharehistory`

### ISSUE THREAD

**Issue by PEConn** [ohmyzsh/ohmyzsh#9471]
**Describe the bug**
oh-my-zsh updated itself recently - I don't know how to find the version, but if I do `cd ~/.oh-my-zsh; git log` it shows `7a76afd61` as the most recent commit.

I noticed that history was getting shared between my terminals, and found that if I ran `setopt`, the output included `sharehistory`.

I added `unsetopt sharehistory` to my `.zshrc` and continued happily, but I'm unsure what caused it to be set in the first place. Could it be something to do with the `oh-my-zsh` update?

 - OS / Distro: Linux
 - Latest ohmyzsh update?: Yes
 - ZSH Version: zsh 5.8 (x86_64-debian-linux-gnu)
 - Terminal emulator: Gnome terminal 3.36.2

**Comment by mcornella** [comment]
The removal was reverted in 28ed2880 due to user complaints. It'll probably be replaced with `inc_append_history` after the "breaking change" notification via the changelog is more widely spread in users' local setups.
