### ISSUE TITLE
Git autocompletion seems to be broken.

### ISSUE THREAD

**Issue by sobiodarlington** [ohmyzsh/ohmyzsh#9472]
**Describe the bug**
Git plugin autocompletion seems to be broken.
Using tab to get suggestions for branches suggests my root dir

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Run git checkout /<tab>
2. Press [tab] to get suggestions
3. My root dir is suggested instead of branches/tags

**Expected behavior**
A list of branches/tags should be suggested

**Desktop (please complete the following information):**

 - OS / Distro: macOS Catalina
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: iTerm2

**Comment by mcornella** [comment]
After trying to tab-complete, please run this and post the output: `which _git`.

**Comment by sobiodarlington** [comment]
This is the output from `which _git` command

```
$ which _git

_git () {
	local _ret=1
	local cur cword prev
	cur=${words[CURRENT]}
	prev=${words[CURRENT-1]}
	let cword=CURRENT-1
	if (( $+functions[__${service}_zsh_main] ))
	then
		__${service}_zsh_main
	else
		emulate ksh -c __${service}_main
	fi
	let _ret && _default && _ret=0
	return _ret
}
```

**Comment by mcornella** [comment]
Can you run `whence -v _git`, as well as post your zshrc file?
