### ISSUE TITLE
Cannot source .zshrc.   autoload - command not found and errors with .oh-my-zsh/tools/

### ISSUE THREAD

**Issue by Cloufish** [ohmyzsh/ohmyzsh#9478]
Hey, There are many things to add at the beginning:
1. I am sourcing .zshrc in Dockerfile (blackarch-zsh found on my dockerfiles [repo](https://github.com/Cloufish/dockerfiles)  so you can I think reproduce this issue)
2. I think I've installed properly oh-my-zsh with get oneliner, though if not, then I'm really sorry!
3. I'm using Luke Smiths wget .zshrc here [.zshrc](https://raw.githubusercontent.com/Cloufish/voidrice/master/.config/zsh/.zshrc)
4. The OS is Arch Linux

![image](https://user-images.githubusercontent.com/32965886/100478374-4cde0a80-30eb-11eb-90fe-10640111858a.png)

If there's more to add, let me know!

**Comment by Cloufish** [comment]
Sorry, I see that parts of my problem are in this issue https://github.com/ohmyzsh/ohmyzsh/issues/8904 
I'll apply the fix for $FPATH

**Comment by mcornella** [comment]
Docker runs `sh` when building the Dockerfile, you can't `source .zshrc` (you need to be running zsh to do that). Why do you want to do that? It doesn't seem like a requirement for the rest of the Dockerfile instructions. When running the docker container, which runs `zsh -i`, it'll automatically load the .zshrc file.

**Comment by Cloufish** [comment]
... You probably are right about unnecessary sourcing in Dockerfile... I'll try that tomorrow
