### ISSUE TITLE
_shellhistory_parents:[:4: integer expression expected: file

### ISSUE THREAD

**Issue by erlisdhima** [ohmyzsh/ohmyzsh#9481]
On Ubuntu 20.04, when I open a new shell, I get the following error:
```_shellhistory_parents:[:4: integer expression expected: file```

After some digging, I found this function on `~/.local/lib/python3.8/site-packages/shellhistory/shellhistory.sh`
```
_shellhistory_parents() {
  local list pid
  list="$(ps -eo pid,ppid,command | tr -s ' ' | sed 's/^ //g')"
  pid=$$
  while [ "${pid}" -ne 0 ]; do
    echo "${list}" | grep "^${pid} " | cut -d' ' -f3-
    pid=$(echo "${list}" | grep "^${pid} " | cut -d' ' -f2)
  done
}
```

Now if I run this commands manually, I get the following:
```
$ pid=$$
$ list="$(ps -eo pid,ppid,command | tr -s ' ' | sed 's/^ //g')"
$ echo "${list}" | grep "^${pid} "
Binary file (standard input) matches
```

After searching for different binary text, I found there was a command with a null value
```
$ echo "${list}" | grep -Pa '\x00'
1060809 1 /sbin/agetty -o -p --  --noclear tty3 linux
```

In `/lib/systemd/system/serial-getty@.service` there is the following line:
`ExecStart=-/sbin/agetty -o '-p -- \\u' --keep-baud 115200,38400,9600 %I $TERM`

And indeed `\\u` will be interpolated into a null value. 
```
printf "\\u" | hexdump
0000000 0000                                   
0000001
```

I don't know if there's been some update to this file via kernel updates, or was there some update done to the shellhistory package?

By adding -a in the grep command it fixes the issue, however this is obviously not the correct way to fix this.

**Comment by mcornella** [comment]
[Wrong project](https://github.com/pawamoy/shell-history), and apparently it was already fixed https://github.com/pawamoy/shell-history/commit/283c5db8d354e9ec4edfd0a94bc222ae09f9c6a8.

**Comment by erlisdhima** [comment]
Sorry about that! Thanks - makes sense!
