### ISSUE TITLE
upgrade.sh:36: read-only variable: _

### ISSUE THREAD

**Issue by soliujing** [ohmyzsh/ohmyzsh#9482]
**Describe the bug**
Update failed after run `omz update`
Error show up as `/root/.oh-my-zsh/tools/upgrade.sh:36: read-only variable: _`

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Run `omz update`
2. See error `/root/.oh-my-zsh/tools/upgrade.sh:36: read-only variable: _`

**Desktop (please complete the following information):**

 - OS / Distro: [CentOS 7 on VPS] Linux x64 3.10.0-1062.1.1.el7.x86_64
 - Latest ohmyzsh update?: [Yes]
 - ZSH Version: [zsh 5.0.2 (x86_64-redhat-linux-gnu)]
 - Terminal emulator: [RoyalTSX]

**Comment by mcornella** [comment]
Try running it again after restarting the zsh session with `exec zsh`.

**Comment by manolofont** [comment]
Same on:

- OS / Distro: [Ubuntu 14.04.5 LTS] Linux 3.13.0-153-generic x86_64
- Latest ohmyzsh update?: [Yes]
- ZSH Version: [zsh 5.0.2 (x86_64-pc-linux-gnu)]
- Terminal emulator: [Guake 3.0.5]

**Comment by mcornella** [comment]
Right, this fails on versions older than 5.0.6, let me push a quick fix.
```console
$ zsh_test_versions '*' 'echo remote url extra | while read remote url _; do echo correct; done'
4.3.11: zsh:1: read-only variable: _
4.3.12: zsh:1: read-only variable: _
4.3.13: zsh:1: read-only variable: _
4.3.14: zsh:1: read-only variable: _
4.3.15: zsh:1: read-only variable: _
4.3.16: zsh:1: read-only variable: _
4.3.17: zsh:1: read-only variable: _
5.0.0: zsh:1: read-only variable: _
5.0.1: zsh:1: read-only variable: _
5.0.2: zsh:1: read-only variable: _
5.0.3: zsh:1: read-only variable: _
5.0.4: zsh:1: read-only variable: _
5.0.5: zsh:1: read-only variable: _
5.0.6: correct
...
```

**Comment by mcornella** [comment]
Try upgrading again. If the upgrade script fails, manually run a `git pull --rebase` inside the `$ZSH` folder.

**Comment by soliujing** [comment]
it works now:)

**Comment by PapayaMedia** [comment]
To manually fix this issue you must edit the file `.oh-my-zsh/tools/upgrade.sh`

Edit the line 32 from:

`git remote -v | while read remote url _; do`

to:

`git remote -v | while read remote url extra; do`

**Comment by mcornella** [comment]
https://github.com/ohmyzsh/ohmyzsh/issues/9482#issuecomment-737158196 this is faster and more reliable
