### ISSUE TITLE
Add option (ENV variable) to customize how ohmyzsh upgrades

### ISSUE THREAD

**Issue by janniks** [ohmyzsh/ohmyzsh#9485]
**Is your feature request related to a particular plugin or theme?**
No.

**Is your feature request related to a problem?**
By the very nature of the ohmyzsh developer's setups will vary greatly. Some decide to manage their ohmyzsh along their dotfiles, others symlink only the `custom` directory, etc. especially in the case of symlinks the current upgrades don't work nicely. When the `custom` folder, for example, is symlinked somewhere else, the upgrade will fail. This is due to the ohmyzsh upgrade using a rebase with auto-stashing (which in general is a great idea for setups that change some of the the actual repo content, i.e. stashes any changes, pulls, un-stashes; but unfortunately does not work when symlinks are involved). However, pulling without stashing works fine, (if only files were changed that didn't update; e.g. `custom` examples do not change often). This (or similar hacky approaches) is how many users (e.g. mackup users) update ohmyzsh. This is not horrible as it's easy to do so (if you know how), but is still not a nice UX every time ohmyzsh wants to auto-update and fails.

**Describe the solution you'd like**
The introduction of an ENV variable (or similar flag) that can enable/disable stashing in the upgrade script. This way users could set e.g. OHMYZSH_UPGRADE_STASH=false in their setup and forget about the annoyance.

**Describe alternatives you've considered**
The current working alternative (how I upgrade ohmyzsh) is simple: hope that the files in `custom` haven't changed and run `cd ~/.oh-my-zsh; git pull` (assuming the user does not have auto-stashing enabled). Then forget about the problem until auto-update fails again.

**Comment by janniks** [comment]
I'd be glad to submit a PR if somebody gives me guidance on naming/conventions of ENV variables etc. for current ohmyzsh flags.

**Comment by mcornella** [comment]
> When the `custom` folder, for example, is symlinked somewhere else, the upgrade will fail.

The proper way to do that is to modify the [`ZSH_CUSTOM` variable](https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#zsh_custom) to point to your target path (needs to be set before OMZ is sourced).

If this is the only problem you have, then the above is not required.

**Comment by janniks** [comment]
Got it, that makes sense! Thanks for the quick response 😊
