### ISSUE TITLE
loses track of current folder info

### ISSUE THREAD

**Issue by dincer-cci** [ohmyzsh/ohmyzsh#9487]
**Describe the bug**
When you are inside a deleted folder/directory, if you try to get into the parent directory, current directory value gets confused and shows somewhere else.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this theme "xxf"
2. `mkdir example`
3. `cd example`
4. open another window and delete the example folder
5. get back to the first window and run `cd ..`
6. you will see the current folder/directory info is not true.

**Expected behavior**
`pwd` command output and current folder info doesn't match.

**Screenshots and/or Recordings**
--

**Desktop (please complete the following information):**

 - OS / Distro: macOS
 - Latest ohmyzsh update?: Yes -- commit: 93cc3964e2d265ab0571298d69d2eed0a65d13f2
 - ZSH Version: zsh 5.8 (x86_64-apple-darwin20.0)
 - Terminal emulator: iTerm2 Build 3.4.1

**Comment by mcornella** [comment]
There is no `xxf` theme in OMZ, can you point to which one you're using?
