### ISSUE TITLE
How can I source a script before a theme?

### ISSUE THREAD

**Issue by Moshem123** [ohmyzsh/ohmyzsh#9488]
Hi, I want to add [kube_ps1](https://github.com/jonmosco/kube-ps1) to my custom PROMPT,
In order to use the function `kube_ps1` I need to source the `sh` file before.
Is there any way to source the sh before loading the theme?
Because sourcing from the theme just doesn't work (:
Thanks.

**Comment by mcornella** [comment]
The `kube-ps1` is also an OMZ plugin, so you can just enable it.
