### ISSUE TITLE
Windows Subsystem for Linux (V2) Colors and Git Slow

### ISSUE THREAD

**Issue by maquejp** [ohmyzsh/ohmyzsh#9489]
Hello,
I have setup OMZ on a new laptop W10 with WSL2.
I is within the Windows Terminal.
The colors are not displayed as demoed here : https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
e.g. the folders have a green background (what ever the theme, Robby, agnoster, Bira)

**Comment by mcornella** [comment]
You need to modify the `LS_COLORS` variable. You can use [this app](https://geoff.greer.fm/lscolors/) to set up the colors you want. Once you have it how you like, you need to copy the `linux LS_COLORS` value and put it at the end of your zshrc file, like so:
```
export LS_COLORS="<value-here>"
```

You can also use `dircolors`, if you look for `dircolors color scheme` you'll find a few options.

**Comment by mcornella** [comment]
When you mention `git slow`, can you be more specific?

**Comment by maquejp** [comment]
I think it is due to large repo on WSL due to the filesystem...

**Comment by mcornella** [comment]
In that case, this is tracked in #5066.
