### ISSUE TITLE
zsh isn't aware of new installations

### ISSUE THREAD

**Issue by ennozdd** [ohmyzsh/ohmyzsh#9492]
➜  zsh --version
zsh 5.8 (x86_64-ubuntu-linux-gnu)

$ sudo apt install xxxyyyzzz
$ xxx(TAB)

It doesn't auto complete, `source ~/.zshrc` doesn't work either.

When I open another terminal,however, it works fine.

**Comment by mcornella** [comment]
See https://wiki.archlinux.org/index.php/Zsh#Persistent_rehash.
