### ISSUE TITLE
Don't pipe changelog.sh output through less if "--unattended" was used with "omz update".

### ISSUE THREAD

**Issue by draenan** [ohmyzsh/ohmyzsh#9495]
**Describe the bug**

`changelog.sh` can pipe output through `less` requiring user intervention to close.  This is unexpected if `omz update` was called with the `--unattended` option.

**To Reproduce**

Of course only triggers if any updates were pulled down, so I need to run a `git reset` first.

1. `git reset HEAD^ --hard`
2. `omz update --unattended` 

**Expected behavior**

For `--unattended` I'd expect `less` to not be used, or perhaps no display of the changelog.

**Desktop (please complete the following information):**

 - OS / Distro: **macOS 10.14.6**
 - Latest ohmyzsh update?: **Yes**
 - ZSH Version: **5.8 (via Homebrew)**
 - Terminal emulator: **iTerm2**

**Additional context**

Perhaps not context for this actual bug, but note that I had to upgrade ZSH in order for the `changelog.sh` script to even work.  The default version of ZSH in macOS 10.14.6 (version 5.3) produces the error `./changelog.sh:10: no matches found: [build]=Build system`.  As mentioned, I fixed this by upgrading my installed version of ZSH.

**Comment by mcornella** [comment]
Thanks for the report, both issues should be fixed, but let me know if you find anything else.
