### ISSUE TITLE
I just installed OMZ and my command prompt is just an arrow with no information?

### ISSUE THREAD

**Issue by mathewtd87** [ohmyzsh/ohmyzsh#9496]
<img width="567" alt="Screen Shot 2020-12-08 at 7 16 00 pm" src="https://user-images.githubusercontent.com/19885532/101464406-53417180-398a-11eb-8e42-0bad1d3c5eae.png">

I've tried unistalling and reinstalling zsh with homebrew. I've also tried updating OMZ. I have no idea what the issue is because I can't find anyone else who's had this issue. I also have checked the .zshrc file and the default theme is there? Why can't I see what folder I am in? I am on Mac OS Mojave. Please Help!

**Comment by mcornella** [comment]
That's the default theme, `robbyrussell`. You can try out other themes. See [themes wiki](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes) and [README information about themes](https://github.com/ohmyzsh/ohmyzsh#themes).
