### ISSUE TITLE
tab autocompletion doesn't work after equal sign (=)

### ISSUE THREAD

**Issue by cyang31** [ohmyzsh/ohmyzsh#9497]
Hi, my zsh can auto complete the path when using tab after regular commands like "cd $directory". However, when I try to fill out a command using "some function input=$directory" it can not auto complete the directory. Could you please help me understand what's going on here? Thanks!

**Comment by mcornella** [comment]
Zsh is not smart enough to know that after `input=` it should complete a path. For that to work, the "some function" in question needs to have a dedicated completion function to tell Zsh that after `input=` there should be a path.

**Comment by mcornella** [comment]
Did that make sense? I could help you further if you post the exact command you're trying to complete.

**Comment by mcornella** [comment]
Hey thanks for sharing! That does actually work :)
