### ISSUE TITLE
Windows WSL2 Ubuntu terminal abnormal color block on some file name/dir

### ISSUE THREAD

**Issue by LeeOHzzZ** [ohmyzsh/ohmyzsh#9499]
Hi, I am using WSL2 ubuntu on Windows Terminal version 1.4.3243.0, and my zsh version is zsh 5.4.2 (x86_64-ubuntu-linux-gnu). I recently updated both my Windows Terminal and my zsh, and now zsh theme doesn't work correctly as there are color boxes on some of the file names. I am using theme dracula, and I have the same problem with other themes, such as robbyrussell.
![image](https://user-images.githubusercontent.com/47999440/101697283-8d237e00-3a45-11eb-8cb9-c4a02f81fadf.png)
![image](https://user-images.githubusercontent.com/47999440/101697425-cf4cbf80-3a45-11eb-9aad-3d844d7b4ac9.png)

**Comment by mcornella** [comment]
That's a `LS_COLORS` variable thing, which is read by `ls` to decide how to color the output. It does so based on file extension and permission bits. If you do `ls -l`, you'll see that all the folders that have this box have the same permissions (probably they're all-writable). If you undo the permission bit that's doing this you'll get a different coloring.

**Comment by LeeOHzzZ** [comment]
Thank you. Problem fixed now.
