### ISSUE TITLE
Add option to view the last changelog on command

### ISSUE THREAD

**Issue by R0LA1mRifcF8yAkk** [ohmyzsh/ohmyzsh#9505]
**Is your feature request related to a problem? Please describe.**
I have an automated update script that calls `omz update` and the script gets stuck because `less` opens with the changelog (a welcome addition but not needed in my case). Also the latest changelog maybe should be viewable somehow, with some command?

**Describe the solution you'd like**
An option is added to `omz update` for silencing the changelog.

**Comment by mcornella** [comment]
You can run `omz update --unattended` or call `$ZSH/tools/upgrade.sh` directly.

**Comment by R0LA1mRifcF8yAkk** [comment]
Oh this is great, thanks so much!

Can we convert this feature request to add a command to view the latest changelog entry on demand? Since it was mentioned in the OP I hope it's not too forward.

**Comment by R0LA1mRifcF8yAkk** [comment]
Thank you!
