### ISSUE TITLE
Auto update ZSH shows changelog

### ISSUE THREAD

**Issue by jasmeet2dhiman** [ohmyzsh/ohmyzsh#9509]
Every time the auto-update of ZSH happens I can see the changelog. I hit 'q' to get out of it. How can I stop entering into this changelog?

**Comment by mcornella** [comment]
Would you prefer if the changelog was displayed without a pager or to hide the changelog altogether?

**Comment by greenchapter** [comment]
@jasmeet2dhiman thank you for opening this issue. I have the same request as you. Especially when you would like to automate `omz update` than the opening of the editor can be a little bit difficult.

@mcornella I would recommend something like a `-y` option, that you can run automatically through `omz update`

**Comment by mcornella** [comment]
You can use `omz update --unattended` or run `$ZSH/tools/upgrade.sh` directly. `omz update` is more suited to be run by a user, not a script.

**Comment by greenchapter** [comment]
> You can use `omz update --unattended` or run `$ZSH/tools/upgrade.sh` directly. `omz update` is more suited to be run by a user, not a script.

Thank you, thats exactly what I need. Is there any documentation?

**Comment by mcornella** [comment]
Should I put it in the [FAQ](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ)?

**Comment by mcornella** [comment]
[Here](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-manually-update-oh-my-zsh-from-a-script).

**Comment by jasmeet2dhiman** [comment]
`# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=1`

How do I use the above with `omz update`?

**Comment by mcornella** [comment]
I was replying Thomas. `omz update` is to trigger manual updates so it doesn't apply to you. Can you reply to https://github.com/ohmyzsh/ohmyzsh/issues/9509#issuecomment-744039847?

**Comment by jasmeet2dhiman** [comment]
> Would you prefer if the changelog was displayed without a pager or to hide the changelog altogether?

I don't want to press "q" to get out of the auto process to update.
either it prints to screen or I have an option to suppress it when using, `export UPDATE_ZSH_DAYS=1`

**Comment by CodeBrotha** [comment]
Just chiming in on this issue too, can the changelog on auto-update be turned off/hidden or at least optional?
