### ISSUE TITLE
genpass-xkcd does not work

### ISSUE THREAD

**Issue by MattLewin** [ohmyzsh/ohmyzsh#9513]
**Describe the bug**
While `genpass-apple` and `genpass-monkey` work properly, `genpass-xkcd` outputs the following:
```
$ genpass-xkcd
0-
```

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'genpass'
2. Run command 'genpass-xkcd'
3. See error

**Expected behavior**
It should produce output of the form 
```
$ genpass-xkcd
9-ditty-sugi-length-glove-warped-gadder-ganton-hibbin-spyer`
```

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

[x] Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro: macOS Big Sur 11.0.1
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8 (x86_64-apple-darwin20.1.0)
 - Terminal emulator: iTerm 2 3.4.2
 - GNU coreutils version: 8.32

**Comment by mcornella** [comment]
Do you have GNU coreutils (for `shuf`) and a wordlist at `/usr/share/dict/words`?

**Comment by mcornella** [comment]
Closing since there's a PR ready.
