### ISSUE TITLE
Change auto-update prompt to not require input

### ISSUE THREAD

**Issue by Altreus** [ohmyzsh/ohmyzsh#9518]
**Is your feature request related to a problem? Please describe.**
I regularly log into a remote workstation running omzsh and it asks me if I want to update, but I've anticipated pressing up+enter to reconnect my tmux session. As a result, garbage is entered into the "Do you want to update? [Y/n]" prompt, which picks no and dumps me at the usual prompt. It's too much effort to log out and in again just to update omz, so I never do.

**Describe the solution you'd like**
Instead of asking me if I'd like to update, simply remind me to check for an update. Then after I've reconnected tmux and my brain's processed what happened, I can just run the command.

**Describe alternatives you've considered**
I thought maybe this was customisable but I couldn't easily find an answer for it.

**Comment by mcornella** [comment]
There's already an option for this, see the Settings section in the wiki.

**Comment by mcornella** [comment]
Here: [`DISABLE_UPDATE_PROMPT`](https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#disable_update_prompt). Make sure to set it before OMZ is sourced.
