### ISSUE TITLE
Delete Key with empty line exits iTerm2

### ISSUE THREAD

**Issue by BadDoggie** [ohmyzsh/ohmyzsh#9522]
Hi All, 
Been using OMZ for a while, and loving it - thanks for all the hard work. 
My setup is (I think) relatively simple: 
- MacOS Catalina 10.15.7
- iTerm2 3.4.3
- zsh 5.8 (x86_64-apple-darwin19.6.0)
- OhMyZsh - latest (upgrade_oh_my_zsh run today)
- PowerLevel10k theme

My issue is that when I press the "Del" key on a blank line in a terminal session, the session ends.  If I have text on the line to the left of the cursor, then I get a system bell. If I have text to the right of the cursor then it deletes this text as expected. 

I can't see an exit command being sent (am only checking .zsh_history), and don't have any custom key mappings in OMZ.  Tested in standard Terminal app, and it doesn't happen.  Also tested in iTerm with a bash session and it doesn't happen. 

The issue has only started relatively recently - I've tried reversing all the changes I can remember, but hasn't helped.  I've removed all plugins and changed to robbyrussell theme, but still happening. 

I'm sure it's a configuration somewhere, but don't know where to look next. Appreciate any suggestions.

**Comment by mcornella** [comment]
iTerm2 has a setting that changes what sequence the Delete key sends. Have a look at its settings.

**Comment by BadDoggie** [comment]
Thanks @mcornella.  iTerm2's "Natural Text Editing" keys preset includes "Send Hex Codes: 0x4" for "Del->".  Removing this and it works OK. 
I'm not quite sure what this "0x4" does, and whether it's better to change that, or to change a key binding from OMZ.. I guess it doesn't matter as long as I'm back working OK! :). Off to do some more research!
Thanks again.

**Comment by the-corp-mark** [comment]
Is there a good way to fix this? The solution above prevents the footgun but at the cost of the delete key not working.

**Comment by colinbr96** [comment]
As a workaround you can use `setopt IGNORE_EOF` in your .zshrc config to prevent Del (which sends EOF) from exiting iTerm.

**Comment by the-corp-mark** [comment]
> As a workaround you can use `setopt IGNORE_EOF` in your .zshrc config to prevent Del (which sends EOF) from exiting iTerm.

But then CTRL + D doesn't work anymore. It's a different solution with the same side effect as

> "Send Hex Codes: 0x4" for "Del->". Removing this
