### ISSUE TITLE
unable to establish SSL connection

### ISSUE THREAD

**Issue by RoseAlice2018** [ohmyzsh/ohmyzsh#9528]
`Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.76.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.76.133|:443... connected.
Unable to establish SSL connection.`

wget version 1.20.3
even use --no-check-certificate can't solve the problem.
Hope for help .thanks

**Comment by mcornella** [comment]
Try my unofficial mirror in mainland China: substitute the URL in the command with `https://gitee.com/mcornella/ohmyzsh/raw/master/tools/install.sh`.

**Comment by RoseAlice2018** [comment]
Thanks the problem is solved
