### ISSUE TITLE
[macOS] lib/theme-and-appearance.zsh#L24 breaks GNU ls

### ISSUE THREAD

**Issue by yurikoles** [ohmyzsh/ohmyzsh#9531]
**Describe the bug**
I have a GNU coreutils installed and added unprefixed binaries to a `PATH` variable. There is a following line:
https://github.com/ohmyzsh/ohmyzsh/blob/b28665aebb4c1b07a57890eb59551bc51d0acf37/lib/theme-and-appearance.zsh#L23-L24

But the `-G` option has another behavior in [GNU `ls`](https://github.com/coreutils/coreutils/blob/08b59f31a582ec7bc8eabab9cfc508bf1d5e5288/src/ls.c#L5389): 

```
  -G, --no-group  in a long listing, don't print group names\n\
```

And there is no check is `ls` stock or GNU one:

**To Reproduce**
1. Install coreutils via `brew install coreutils`.
2. Follow `brew` [caveat](https://github.com/Homebrew/homebrew-core/blob/171c7c8bb350b272d534f39241704f4bafd81d8d/Formula/coreutils.rb#L75) and add them to a `PATH` by putting line `PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"` to a zsh config.
3. Open a new shell session.
4. Invoke `ls -l`.
5. See that there is no group column.

**Expected behavior**
I suggest adding some sanity check is `ls` a stock or GNU one, so `-G` option shouldn't be added to a GNU `ls`.

**Desktop (please complete the following information):**

 - OS / Distro: macOS 11.1 (20C69)
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: macOS stock 

**Additional context**
I don't see this issue with official `gnu-utils` plugin which is an alternative to aforementioned `brew` caveat.
Another workaround is to generate colors config by `dircolors -b > "${HOME}/.dircolors"` to pass the following check:
https://github.com/ohmyzsh/ohmyzsh/blob/b28665aebb4c1b07a57890eb59551bc51d0acf37/lib/theme-and-appearance.zsh#L28

**Comment by mcornella** [comment]
I don't have a macOS system to check. Can you look for a reliable check to detect whether `ls` is from `coreutils` or not?

**Comment by yurikoles** [comment]
Sorry, I forgot to mention, that there is a comment above:
https://github.com/ohmyzsh/ohmyzsh/blob/b28665aebb4c1b07a57890eb59551bc51d0acf37/lib/theme-and-appearance.zsh#L26-L28

So developers (git blame shows that this was you :)) are forcing users to use stock `ls` on macOS, which may be against user intention.

About your question: stock macOS `ls` comes from some old BSD code, [here](https://www.unix.com/man-page/osx/1/ls/) is a man. `/bin/ls --version` exits with code `1`, `gls --version` works fine and shows standard GNU coreutils staff. So here is a script that I had developed and checked:

```
ls_version_output=$(ls --version 2>&1)
ls_version_code=$?
ls_gnu_string="GNU coreutils"
if [[ "${ls_version_code}" -eq 1 ]];
then
	echo "BSD";
elif [[ "${ls_version_output}" == *"${ls_gnu_string}"* ]]; then
  	echo "GNU"
else
	echo "Dunno"
fi
```

**Comment by LucienZhang** [comment]
Duplicated with #5804, and a workaround is to prioritize `/bin/ls` by
```bash
echo 'export PATH="/bin:${PATH//:\/bin:/:}"' >> ~/.zshrc && source  ~/.zshrc
```
