### ISSUE TITLE
Cannot execute zshrc anymore

### ISSUE THREAD

**Issue by AminMe** [ohmyzsh/ohmyzsh#9535]
Hi guys I have an issue I was following some [tutorial](https://www.codeprocess.io/set-mac-terminal-shell-with-proper-GNU-bash-version-v4/) to make works ` shoot globstar` on my zsh.
And suddenly my zsh, my theme disappeared.

I tried several solutions I found on internet but none is working (i.e using csh + restarting computer).

This is the proof that I have zsh setup as shell
```
bash-5.1$ echo $SHELL
/bin/zsh
```

My iterm2 app is using `/bin/zsh` also in `Preferences > Profile` 

But weirdly I have bash-5.1 displayed instead of my zsh config

## Problem
For now I am not able to run `source ~/.zshrc` (I am on macOS btw)
I have this error (I translated some part from French to English):
```
bash-5.1$ source ~/.zshrc
bash: autoload : command not found
bash: /Users/xxx/.oh-my-zsh/oh-my-zsh.sh: line 34: syntax error expected symbol « ( »
bash: /Users/xxx/.oh-my-zsh/oh-my-zsh.sh: line 34: `for config_file ($ZSH/lib/*.zsh); do'
```
Here is my zsh file which I never touched since a long time. I think the article quoted above just destroyed something on my shell and I don't know what.
[zshrc_issue.txt](https://github.com/ohmyzsh/ohmyzsh/files/5735586/zshrc_issue.txt)

Do you have any idea what happened and how to solve it ? Thx

**Comment by AminMe** [comment]
I just wanted to add. some logs that validate I am using zsh:

```
bash-5.1$ chsh -s $(which zsh)
Changing shell for xxx.
Password for xxx:
chsh: no changes made
bash-5.1$
```

**Comment by mcornella** [comment]
I'm sorry to say this, because you tried really hard to verify that you're running zsh, but you're not in fact running zsh. The tests you made only tell you that zsh is your default shell, but that is only applied once you restart your user session (log out and log back in).

The proper way to check if you're running zsh is to run `echo $ZSH_VERSION`. If that doesn't show anything you're not running zsh. Also the fact that it says `bash` in your prompt, and that these errors happen (and they're prefixed with `bash: `):
```
bash: autoload : command not found
bash: /Users/xxx/.oh-my-zsh/oh-my-zsh.sh: line 34: syntax error expected symbol « ( »
bash: /Users/xxx/.oh-my-zsh/oh-my-zsh.sh: line 34: `for config_file ($ZSH/lib/*.zsh); do'
```

To run zsh, you can make it the default shell (and restart the user session, as I said above). Also, just run `zsh`. `source ~/.zshrc` doesn't run zsh, and also it's not a good way to reload the zshrc file (for that you need to run `exec zsh`). Hope this helps!

**Comment by AminMe** [comment]
Hi thank your for you quick answer :)

> (and they're prefixed with bash: ):

Yes that is what I am trying to understand, and I tried all the solution you give in other closed issues :( 

You are right my `$ZSH_VERSION` is not set but I tried what is suggested above but it did not work.
So I typed `chsh -s $(which zsh)` this command and I loged out / loged in my session.
```
For info this is the content of which wsh
bash-5.1$ which zsh
/bin/zsh
```

Then I open iTerm2 which is by default configured to run `/bin/zsh` and typed:


```
bash-5.1$ echo $ZSH_VERSION

bash-5.1$ zsh
bash-5.1$ echo $ZSH_VERSION

bash-5.1$ exec zsh
bash-5.1$ echo $ZSH_VERSION

bash-5.1$
```

Weirdly running `zsh` does not change `$ZSH_VERSION` and exec does not run the `~/.zshrc`.
I think something is misconfigured.

I tried also to resinstall zsh from brew + ohmyzsh from curl nothing worked.

**Comment by AminMe** [comment]
Also I saw in one of your [answers](https://github.com/ohmyzsh/ohmyzsh/issues/3233#issuecomment-60719880) that `$PATH` can be containing duplicates. Mmaybe it is my case or mine is wrong. But I tried yesterday to reset my `$PATH` with no success.

```
(my_pyenv) bash-5.1$ echo $ZSH
/Users/xxx/.oh-my-zsh
(my_pyenv) bash-5.1$ echo $PATH
/usr/local/opt/postgresql@9.6/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/xxx/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin:/Library/Apple/usr/bin:/usr/local/opt/fzf/bin
```

**Comment by AminMe** [comment]
@mcornella ok I found the problem

When I followed the tutorial, linked above, I installed `bash` with home-brew with `brew install bash`, which installed bash 5.1.
But my bash on my Mac was still on version 3.2.

So I just `brew uninstall bash` and started new terminal (without login logout) and it worked again :D 
I don't know exactly what is the problem with brew installing bash

Now:
```
~|°Dev°|⇒ echo $ZSH_VERSION
5.8
```

**Comment by AminMe** [comment]
Update: So it seems now I have an error saying 

```
~|°Dev°|⇒ exec zsh
/etc/zshrc:74: no such file or directory: /usr/local/bin/bash
~|°Dev°|⇒ echo $PATH
/usr/local/opt/postgresql@9.6/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/amin/.pyenv/shims:/Users/amin/bin:/usr/local/bin:/usr/local/opt/postgresql@9.6/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/amin/.pyenv/shims:/Users/amin/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/fzf/bin
~|°Dev°|⇒
```

I tried to copy `/bin/bash` to `/usr/local/bin/bash` by using `cp /bin/bash /usr/local/bin/bash`
And when I executed zsh my terminal was showing `bash-3.2` and I came back to same story as yesterday.

Sooo I removed `/usr/local/bin/bash` and zsh worked again.

I think I have an issue on my $PATH.

**Comment by AminMe** [comment]
The error comes from those line in`/etc/zshrc`. Why is bash executed here ?
```
  72   │ # Useful support for interacting with Terminal.app or other terminal programs
  73   │ [ -r "/etc/zshrc_$TERM_PROGRAM" ] && . "/etc/zshrc_$TERM_PROGRAM"
  74   │ /usr/local/bin/bash
```
