### ISSUE TITLE
Support for entering numbers via numpad

### ISSUE THREAD

**Issue by rrgahan** [ohmyzsh/ohmyzsh#9536]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
For sure the git autocomplete stuff, but from what I understand it's a zsh problem in general. 

**Is your feature request related to a problem? Please describe.**
I try to type my branch names in git using the numpad on my Apple magic keyboard, but it doesn't except the numbers from there

**Describe the solution you'd like**
Use my numpad to type in command line

**Describe alternatives you've considered**
I've seen this [post](https://superuser.com/questions/742171/zsh-z-shell-numpad-numlock-doesnt-work)

**Related Issues**
Haven't looked, but know it's a reproducible and felt problem

**Comment by mcornella** [comment]
Duplicate of #4916.
