### ISSUE TITLE
./zshrc unmatched 

### ISSUE THREAD

**Issue by tush23** [ohmyzsh/ohmyzsh#9539]
still facing this issue  ./zshrc unmatched..

my .zshrc

[zshrc.txt](https://github.com/ohmyzsh/ohmyzsh/files/5738774/zshrc.txt)

**Comment by AminMe** [comment]
You miss a double quote after `/bin`:
```
# flutter path
export PATH="$PATH:/Users/tushardubey/Flutter Sdk/flutter/bin
```

It should be 
```
# flutter path
export PATH="$PATH:/Users/tushardubey/Flutter Sdk/flutter/bin"
```

**Comment by tush23** [comment]
thanks for help
