### ISSUE TITLE
Highlight current theme in use with omz tool

### ISSUE THREAD

**Issue by leoheck** [ohmyzsh/ohmyzsh#9540]
`omz theme list` could mark the current theme in use, so it is easier to set it back to the previous one while experimenting with new themes. Or at least one command to do that would be nice, lets say `omz theme current`

**Comment by SukkaW** [comment]
`echo $ZSH_THEME` will show the current theme you are using. But it might be a good idea to add `omz theme current`.

**Comment by leoheck** [comment]
For instance, if you do the `omz theme list` the default theme could be in another color or with a small mark at the end like this

Here, for instance, I am indicating that `3den*` is the theme in use.

```
Custom themes:
example

Built-in themes:
3den*			gallois			nicoulaj
adben			garyblessington		norm
af-magic		gentoo			obraun
afowler			geoffgarside		peepcode
agnoster		gianu			philips
alanpeabody		gnzh			pmcgee
amuse			gozilla			pygmalion
apple			half-life		pygmalion-virtualenv
arrow			humza			random
aussiegeek		imajes			re5et
avit			intheloop		refined
awesomepanda		itchy			rgm
bira			jaischeema		risto
blinks			jbergantine		rixius
bureau			jispwoso		rkj
candy			jnrowe			rkj-repos
candy-kingdom		jonathan		robbyrussell
clean			josh			sammy
cloud			jreese			simonoff
crcandy			jtriley			simple
crunch			juanghurtado		skaro
cypher			junkfood		smt
dallas			kafeitu			Soliah
darkblood		kardan			sonicradish
daveverwer		kennethreitz		sorin
dieter			kiwi			sporty_256
dogenpunk		kolo			steeef
dpoggi			kphoen			strug
dst			lambda			sunaku
dstufft			linuxonly		sunrise
duellj			lukerandall		superjarin
eastwood		macovsky		suvash
edvardm			maran			takashiyoshida
emotty			mgutz			terminalparty
essembeh		mh			theunraveler
evan			michelebologna		tjkirch
fino			mikeh			tjkirch_mod
fino-time		miloshadzic		tonotdo
fishy			minimal			trapd00r
flazz			mira			wedisagree
fletcherm		mlh			wezm
fox			mortalscumbag		wezm+
frisk			mrtazz			wuffers
frontcube		murilasso		xiong-chiamiov
funky			muse			xiong-chiamiov-plus
fwalch			nanotech		ys
gallifrey		nebirhos		zhann
```

**Comment by leoheck** [comment]
Actually, I am using something else. But this is not even listed there.

```
➜ echo $ZSH_THEME 
spaceship
```

So, is it possible to have these 3rdparty themes integrated into this command as well?

**Comment by mcornella** [comment]
> So, is it possible to have these 3rdparty themes integrated into this command as well?

We can only check for themes installed inside `$ZSH_CUSTOM`, doing otherwise is impossible. If you followed [the oh-my-zsh instructions](https://github.com/denysdovhan/spaceship-prompt#oh-my-zsh) it should appear in `omz theme list`, under the `Custom themes` section.

----

I like the subtle way to indicate used theme. This shouldn't be that hard to implement, I'll give it a shot soon.

**Comment by ttrezren** [comment]
Is there a way to display which theme is currently displayed when the $ZSH_THEME value is "random"? I'm using random to audition a few themes.

**Comment by mcornella** [comment]
The random theme should display the chosen theme on startup, unless you set the [`ZSH_THEME_RANDOM_QUIET`](https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#zsh_theme_random_quiet) setting. You can `echo $RANDOM_THEME` any other time to check.

This should be checked by the CLI tool as well though. Mental note.

**Comment by leoheck** [comment]
Now my `spaceship` theme is being shown there, but it looks like something is not right there. 
There is this `example`, and the text on the right is not for the example I guess.
![image](https://user-images.githubusercontent.com/1277920/107822729-562b5a80-6d5d-11eb-99b1-6a3114815fcf.png)

**Comment by mcornella** [comment]
Looks like on is a symlink to the other. `example` is a theme file that has nothing in it.

**Comment by leoheck** [comment]
Ah, so this is the meaning! Got it, thanks.
