### ISSUE TITLE
why i installed the oh-my-zsh doesn't create the folder /usr/local/share/zsh

### ISSUE THREAD

**Issue by youaremywind** [ohmyzsh/ohmyzsh#9545]
why i installed the oh-my-zsh doesn't create the folder /usr/local/share/zsh

 - OS / Distro:  macOS m1 11.0.1
 - Latest ohmyzsh update?: [Yes]
 - ZSH Version: [5.6]
 - Terminal emulator: [iTerm2]
![image](https://user-images.githubusercontent.com/18423358/103127040-41223b80-46cb-11eb-8c78-3d6362201c82.png)

**Comment by mcornella** [comment]
OMZ installs by default in `$HOME/.oh-my-zsh`. If you want it to install in `/usr/local/share/zsh` (I'm not sure if that's a good idea, since in my system that path might contain completion functions), you need to specify it when calling the install script:

```sh
ZSH=/usr/local/share/zsh sudo sh -c "$(wget ...)"
```
