### ISSUE TITLE
genpass-zkcd is not working for me.

### ISSUE THREAD

**Issue by Taiger** [ohmyzsh/ohmyzsh#9548]
Genpass works great except for my favorite one: genpass-xkcd

**Describe the bug**
`➜  ~ genpass-xkcd`
`genpass-xkcd:46: unknown function: log2`
`➜  ~ genpass-xkcd 3`
`genpass-xkcd:46: unknown function: log2`
`➜  ~ genpass-monkey`
`1fw6q52acbmqhjwcf5t05qdcvn`
`➜  ~ genpass-apple`
`gecwox-wyVpem-qivwar-kompat-hyqtox-kysmu2`

**To Reproduce**

1. Added plugin to my ~/.zshrc  here
`plugins=(git genpass)`
2. Run command 'genpass-xkcd '
3. Error is `unknown function: log2`

**Desktop:**

 -  Linux Mint 19.2 Cinnamon

**Comment by mcornella** [comment]
`log2(x)` was introduced in [zsh v5.6](https://github.com/zsh-users/zsh/commit/b21a641d4c63fce45736b635314e079ae360e5b2). We should use `log(x)/log(2)`.

Remember to provide the zsh version in future bug reports.

**Comment by Taiger** [comment]
Ok thank you. I am still on zsh 5.4.2. Will do!
