### ISSUE TITLE
Use ohmyz.sh domain to deliver installer script

### ISSUE THREAD

**Issue by RakeshChowdhury** [ohmyzsh/ohmyzsh#9556]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
No. It's about the installation and regarding a faster installation technique.

**Is your feature request related to a problem? Please describe.**
It's not a huge problem, yet just a feature id like the team to add. Running the installer script after running `curl https://ohmyz.sh | grep "sh -c"` involves using the mouse and a bit of copy paste.

**Describe the solution you'd like**
I would like if the team would redirect ohmyz.sh curl http connections to a static text. The text can include comments and echo commands to help the user and the installer command itself too. So the user would just run `sh -c $(curl ohmyz.sh)` to install ohmyzsh. Just like hashbang.sh community does.

**Describe alternatives you've considered**
Another alternative would be to redirect curl users to the script itself instead of the websites http server.

**Additional context**

**Related Issues**

**Comment by mcornella** [comment]
This exists at `install.ohmyz.sh`, though it's served over HTTP so we discouraged its use. We'll discuss this on the next meeting.

**Comment by RakeshChowdhury** [comment]
Sure Thanks for the reply. Also, Have a Great New Year :)

_Stay Safe_

**Comment by mcornella** [comment]
Tracking in #11467.
