### ISSUE TITLE
install script completely destroys existing .zshrc

### ISSUE THREAD

**Issue by abhoriel** [ohmyzsh/ohmyzsh#9560]
**Describe the bug**
The ohmyzsh install script completely destroys any existing .zshrc without allowing any means of recovery

**To Reproduce**
execute install script 
eg. sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

**Expected behavior**
Any existing .zshrc should not be trashed, at the very least, it should be renamed or otherwise backed up.

**Comment by mcornella** [comment]
It is renamed, you should see a message saying where it's backed up but normally it's [`.zshrc.pre-oh-my-zsh`](https://github.com/ohmyzsh/ohmyzsh/blob/4b2431e8b1c08a2dc14fe31bf07a5e5f08eaa87e/tools/install.sh#L130).

**Comment by abhoriel** [comment]
Oh yes, thanks very much
