### ISSUE TITLE
set -a brokes paste with zsh

### ISSUE THREAD

**Issue by uvu9Ba** [ohmyzsh/ohmyzsh#9562]
**Describe the bug**
Paste is not working when using `set -a`

**To Reproduce**
Steps to reproduce the behavior, for example:
1. In Terminal: `set -a`
2. Try Paste something
3. It will overwrite the whole line and double paste the content

**Expected behavior**
Only paste the content once without overwrite the already written line 

**Screenshots and/or Recordings**
![example](https://i.imgur.com/5kR0pKP.png)

**Desktop (please complete the following information):**

 - OS / Distro: Fedora 33
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: Tilix, guake

**Additional context**
Tested with no plugins

**Comment by mcornella** [comment]
See if `DISABLE_MAGIC_FUNCTIONS=true` fixes it (in your zshrc file, before OMZ is sourced). Possible duplicate: https://github.com/ohmyzsh/ohmyzsh/issues/6255.

**Comment by uvu9Ba** [comment]
@mcornella yes this helped.

**Comment by mcornella** [comment]
Thanks!
