### ISSUE TITLE
finding the docker daemon launch script in MacOS

### ISSUE THREAD

**Issue by AdamBD** [ohmyzsh/ohmyzsh#9563]
Hi all,

I have docker for mac installed and each time I run a Zsh session and docker for mac is not running I see
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

I cannot for the life of me find where this daemon is trying to run from, anyone have an idea how I can find this and stop it from running on startup?

**Comment by mcornella** [comment]
Please post your zshrc file.

**Comment by BDL70** [comment]
I have downloaded Docker onto a Mac that was previously running Docker on the High Sierra iOS. I upgraded the iOS to Catalina and the Docker icon disappeared from the top and now the error says the daemon isn't running? Going out of my head trying wrap my mind around how to fix this. 
HELP ?!

**Comment by mcornella** [comment]
This is not OMZ-related. Try https://github.com/docker/for-mac/.
