### ISSUE TITLE
When pressing "Shift" + "TAB", all the tab-completions appear

### ISSUE THREAD

**Issue by wantyapps** [ohmyzsh/ohmyzsh#9564]
**Describe the bug**
I pressed shift + tab because I wanted to check what would happen. Then, all the completions appeared!

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Press Shift + TAB

**Expected behavior**
Nothing

**Screenshots and/or Recordings**
https://asciinema.org/a/NQG3hiVfVmuKr6QbNlcN4VYsi

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro: macOS 11.1
 - If on Windows what version of WSL: [e.g. WSL1, WSL2]
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: Alacritty

**Additional context**
Add any other context about the problem here. This can be themes, plugins, custom configs.
I use my own `$PROMPT`

**Comment by mcornella** [comment]
Answered on Discord:
> yep, when pressing tab a literal tab is inserted because there's nothing typed to complete, but shift+tab doesn't have an alternative function, so you enter completion mode and select the last completion entry (shift+tab means select the previous completion entry in the completion menu)
