### ISSUE TITLE
The updater should also source zshrc

### ISSUE THREAD

**Issue by hjpotter92** [ohmyzsh/ohmyzsh#9565]
When doing the updation of local installation using `omz update`, at the end; it should also source the updated changes in current shell.

This or, as an additional feature to have `omz source` or `omz reload` sub commands to reload the changes (if any).

**Comment by mcornella** [comment]
`omz update` runs `exec zsh` when updates have been pulled, which does what you're asking. `source ~/.zshrc` isn't actually the proper way to reload zsh, since may have side effects resulting from running the same thing twice in the same zsh process.
