### ISSUE TITLE
Crash , when I input Chinese text , sometimes. 

### ISSUE THREAD

**Issue by finscn** [ohmyzsh/ohmyzsh#9567]
Crash , when I input Chinese text , sometimes. 

**Describe the bug**
when I input chinese in  git's commit string, like this: 
`git commit -m '输入了很多中文中文中文中文....'`

the terminal will crash sometimes.

**To Reproduce**
when I input chinese in  git's commit string, like this: 
`git commit -m '输入了很多中文中文中文中文....'`

the terminal will crash sometimes.

**Desktop (please complete the following information):**

 - OS / Distro:  macOS 11
 - Latest ohmyzsh update?: Yes
 - ZSH Version: zsh 5.8 (x86_64-apple-darwin20.1.0)
 - Terminal emulator: macOS's builtin

**Comment by mcornella** [comment]
What's the output of `locale` and `locale -a`?

**Comment by finscn** [comment]
➜  ~ locale   
LANG="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_CTYPE="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_ALL=

**Comment by mcornella** [comment]
Does this happen in `bash` or in another terminal app (like iTerm2)?

**Comment by finscn** [comment]
no. it's just in zsh. 
but , in fact , I don't know  is this issue cased by zsh or oh-my-zsh .

**Comment by mcornella** [comment]
> I don't know is this issue cased by zsh or oh-my-zsh .

Try running `zsh -f` to bypass OMZ.

**Comment by mcornella** [comment]
Try also a different terminal app, maybe it doesn't happen in iTerm2.
