### ISSUE TITLE
Output GIT information on current sheet

### ISSUE THREAD

**Issue by AlexanderZhirov** [ohmyzsh/ohmyzsh#9568]
For some reason, each GIT command, when viewing the list, displays them in a blank sheet, which is not very convenient. How can I disable this setting? 

![image](https://user-images.githubusercontent.com/37277056/103453691-7a6f3280-4ced-11eb-8e4b-b39f489b5d69.png)

After entering the command, the information is displayed in a new list, on a clean terminal. It is not comfortable.

![image](https://user-images.githubusercontent.com/37277056/103453682-6c211680-4ced-11eb-9e0d-e59f3282b187.png)

I want the information to be displayed on the current list of entered commands

**Comment by mcornella** [comment]
Look up "disable git pager". There are different config options for different git commands.
