### ISSUE TITLE
vi-mode changed the cursor shape; how do I disable it?

### ISSUE THREAD

**Issue by thomergil** [ohmyzsh/ohmyzsh#9570]
The most recent commit to the vi-mode plugin changes the cursor shape to a vertical bar in insert mode. How do I disable this? I prefer a block cursor, always. Thank you.

**Comment by kuntau** [comment]
Just about to ask about this #8004, definitely my least favourite change so far.

**Comment by LoLei** [comment]
While it apparently can't be configured dynamically right now, what works is changing the cursor shapes in the vi-mode.plugin.zsh code.

https://github.com/rwe/oh-my-zsh/blob/7cf783a6a63bc08e00110c6171e0196679bd8337/plugins/vi-mode/vi-mode.plugin.zsh#L18

Simply change all the `_shape=6` to `_shape=2`.

**Comment by kuntau** [comment]
Yeah, that's one way, but I prefer some option flag than to mess with the source code that will conflict with an update in the future.

**Comment by thomergil** [comment]
Moreover, I'd like to argue to leave the cursor unchanged, by default, and to enable this behavior optionally. (This is a very visible and unsettling change to the unsuspecting user. It took me a long time to figure out this wasn't my terminal application that was going rogue on me.)

**Comment by aantonello** [comment]
May I add one more reason to disable this _feature_ by default?
When using the Terminal buffer inside GVim (MacVim, actually), the "insert" cursor shape simply disapear. It is not shown at all.

**Comment by ecbrodie** [comment]
I would propose that ideally there is an environment that can be set to toggle the cursor type.

**Comment by mcornella** [comment]
Added a setting to turn it off, if you all agree I'll make the change.
```zsh
function _vi-mode-set-cursor-shape-for-keymap() {
  [[ "$VI_MODE_SET_CURSOR" = true ]] || return

  # https://vt100.net/docs/vt510-rm/DECSCUSR
  local _shape=0
  case "${1:-${VI_KEYMAP:-main}}" in
    main)    _shape=6 ;; # vi insert: line
    viins)   _shape=6 ;; # vi insert: line
    isearch) _shape=6 ;; # inc search: line
    command) _shape=6 ;; # read a command name
    vicmd)   _shape=2 ;; # vi cmd: block
    visual)  _shape=2 ;; # vi visual mode: block
    viopp)   _shape=0 ;; # vi operation pending: blinking block
    *)       _shape=0 ;;
  esac
  printf $'\e[%d q' "${_shape}"
}
```

**Comment by thomergil** [comment]
I would argue this is a setting to turn it on. But, yes, great work. Thank you.

**Comment by mcornella** [comment]
> I would argue this is a setting to turn it on. But, yes, great work. Thank you.

That's what it does, unless `VI_MODE_SET_CURSOR=true` the function will return, so you need to explicitly set it to true. I'm working on the `vi-mode` plugin README and when that's done I'll make a PR.

**Comment by mcornella** [comment]
Alright here it is #9572. Test it with `omz pr test 9572`.
