### ISSUE TITLE
vi-mode: command line editing in external editor is broken

### ISSUE THREAD

**Issue by csabahenk** [ohmyzsh/ohmyzsh#9573]
**Describe the bug**

The standard shell vi-mode normal mode keybinding for editing the command line externally, `v`, stopped working.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin: 'vi-mode'
2. Hit `<esc>`, then `v`
3. See error: nothing happens

**Expected behavior**
Getting dropped to `$EDITOR` with command line content loaded into buffer.

**Additional context**
98762fa is the culprit, with [this deletion](https://github.com/ohmyzsh/ohmyzsh/commit/98762faa0762e1f0ede05149c1f6b3a9db93e074#diff-81cbdecab907e2ac16557ff858078dfacdcd6af30fd8168606515052c9679a70L26-L29) in particular.

**Comment by mcornella** [comment]
The key binding is now `vv`. This is also now notified as a breaking change, while preserving the original intention of #6332 and #8004.

**Comment by rwmitchell** [comment]
I'm playing with new "_vi-mode-set-cursor-shape-for-keymap"

My personal preference is for a non-blinking underline as my normal cursor.  I like the switch to a block cursor when switching to vicmd mode and I'd like the cursor to be a vertical bar in insert mode, which I had wrongly assumed was viins.

In testing, the default is main, escaping from main goes to vicmd and that seems to be my only two options.  'i', 'I', 'a', 'A' all go back to 'main.

What do I need to configure to enable the other modes mentioned in _vi-mode-set-cursor-shape-for-keymap ?

Thanks!

**Comment by mcornella** [comment]
If you want that, as is now, there's no way to personalize the cursor style. You should override the whole function and modify the values in the `_shape` variable. You can do that by [copy-pasting the function](https://github.com/ohmyzsh/ohmyzsh/blob/2118d35e017eb8c599f3c25863c8263aca307541/plugins/vi-mode/vi-mode.plugin.zsh#L19-L35) in your zshrc file, after OMZ is sourced, and changing `_shape=` to a value that works for you.

Should you need that, you can play around with `printf $'\e[%d q' <shape-value>` to find the shape value according to the cursor shape you want.

**Comment by rwmitchell** [comment]
Yes, can change the vertical bar to an underline using a 4 for the shape.

The issue, as I see it, is the function lists several case options that are not available, giving the impression they can be set uniquely when they can't.   viins and main are the same.  I could trigger vicmd, but none of the others (having put in a print statement in my local copy of the function to show which mode was triggered).   Again, a false impression a different cursor could be set for those modes.
