### ISSUE TITLE
The config oh-my-zsh.hide-status no longer works

### ISSUE THREAD

**Issue by domfarolino** [ohmyzsh/ohmyzsh#9576]
Many people including myself and @bcho use the `hide-status` config to stop `git status` from running after every terminal command. I work on Chromium and having `git status` constantly run on such a large repository absolutely kills productivity, so I followed the instructions in https://www.stevenrombauts.be/2018/04/disable-git-prompt-in-oh-my-zsh/ to fix this.

I use the theme "maran", which by default shows me my path, my git branch, as well as the status of the tree:

<img width="1006" alt="Screen Shot 2021-01-05 at 19 02 09" src="https://user-images.githubusercontent.com/9669289/103720460-fe951480-4f90-11eb-92a6-c135e279e3fe.png">

It is the latter that takes forever, and that I disabled via `git config oh-my-zsh.hide-status 1`. However, recently this stopped working:

<img width="1175" alt="Screen Shot 2021-01-05 at 19 03 42" src="https://user-images.githubusercontent.com/9669289/103720626-664b5f80-4f91-11eb-9c6e-acfa12495fc1.png">

I think I've tracked the issue down to the following commits by @mcornella and @brunoborges:
 - https://github.com/ohmyzsh/ohmyzsh/commit/2f39c68ab0157b55413de74e579d1787f26e58b6
 - https://github.com/ohmyzsh/ohmyzsh/commit/28265812f8fb923788d74409cef3e5635793b38e

It appears this is entirely intentional, as per the commit desc in the second commit above. We're now supposed to use `hide-info`. I have no problem with the breaking change here being that we need to use a different config name to get the same result, but what seems to be inconveniencing me is the behavior change. At least on my ZSH theme "maran", I can no longer hide the git status while still showing the branch info. I have to choose between branch info && `git status` always, or neither, which is pretty annoying for me.

Now https://github.com/ohmyzsh/ohmyzsh/pull/9188#issuecomment-678031544 indicates that there is a `classic-info` config that can presumably enable the previous "classic" behavior, however from running `git grep "classic-info"` in the repository gives nothing, so it appears this was not actually added.

Is there any chance I could convince you to bring back the old granularity between hiding branch info and status, by introducing the `classic-info` config option or something? The two states provide very different info and lumping them all together has been pretty inconvenient for me, and presumably some other folks.

**Desktop (please complete the following information):**
 - OS / Distro: macOS
 - Latest ohmyzsh update?: I think so
 - ZSH Version: [e.g. 5.6]
 - Terminal emulator: just the normal macOS Terminal

**Comment by brunoborges** [comment]
We did not move forward with the idea of 'classic-info' because in the end we did not change the default info/status data. 

One must opt-in to get the name of the remote do also be displayed along with the prompt_info.

I believe that to fix your issue, you need to enable both hide-status and hide-info.

**Comment by brunoborges** [comment]
I'd be curious to see how this particular theme grabs the git info/status, and if they check for these flags or not.

**Comment by domfarolino** [comment]
> I believe that to fix your issue, you need to enable both hide-status and hide-info.

Hmm, I don't understand. The issue with hiding info is that it hides the branch info and the status altogether, where as I want to show the branch info, but hide the git status.

> We did not move forward with the idea of 'classic-info' because in the end we did not change the default info/status data.
...
> I'd be curious to see how this particular theme grabs the git info/status, and if they check for these flags or not.

After trying `afowler` and some other themes that have a `*` to indicate a dirty tree, these all seem to have the same problem after the commits I mentioned above. When I run `git config oh-my-zsh.hide-status 1` git status still runs after every command (taking sometimes 20 seconds in the Chromium repository on a high-end Mac). The only way to stop this is to run `git config oh-my-zsh.hide-info 1`, which of course removes branch info which I still want.

So the question remains,

> Is there any chance I could convince you to bring back the old granularity between hiding branch info and status, by introducing the classic-info config option or something? The two states provide very different info and lumping them all together has been pretty inconvenient for me, and presumably some other folks.

**Comment by domfarolino** [comment]
Just to be clear, the specific problem I'm referring to is here: https://github.com/ohmyzsh/ohmyzsh/commit/2f39c68ab0157b55413de74e579d1787f26e58b6#r45680637, the fact that you cannot show the branch info but skip `git status`

**Comment by domfarolino** [comment]
> We did not move forward with the idea of 'classic-info' because in the end we did not change the default info/status data.

Hmm, I may have been mistaken about the previous behavior. I may have been wrong in thinking that I used to be able to show the branch information without the tree status. After reverting my locally-installed oh-my-zsh version to before these "problematic" commits, it seems that there was never the ability to view the branch info without tree status, so I may have been misremebering my use case seeing as how I haven't opened by terminal since before the holidays :) Wow it's been a while, sorry for the noise.

I think this can be closed.

**Comment by mcornella** [comment]
Note the "status" call in the `git_prompt_info` function comes from running `parse_git_dirty`, which you can hide with `git config oh-my-zsh.hide-dirty 1`. That, combined with `git config oh-my-zsh.hide-status 1` should give you what you need.

**Comment by polatouche6** [comment]
i have used `git config oh-my-zsh.hide-dirty 1`. but it don't works. i resolve it with `export GIT_TRACE=0` finally
```
tdl@slava-u1➜ oh-my-zsh: (master) ls
cache  CODE_OF_CONDUCT.md  CONTRIBUTING.md  custom  lib  LICENSE.txt  log  oh-my-zsh.sh  plugins  README.md  SECURITY.md  templates  themes  tools
10:46:40.877030 git.c:439               trace: built-in: git config --get oh-my-zsh.hide-dirty                                                                                                                                                                                
tdl@slava-u1➜ oh-my-zsh: (master) 
10:46:46.261629 git.c:439               trace: built-in: git config --get oh-my-zsh.hide-dirty                                                                                                                                                                                
tdl@slava-u1➜ oh-my-zsh: (master) git config oh-my-zsh.hide-dirty 1
10:46:54.766695 git.c:439               trace: built-in: git config oh-my-zsh.hide-dirty 1
10:46:54.813979 git.c:439               trace: built-in: git config --get oh-my-zsh.hide-dirty                                                                                                                                                                                
tdl@slava-u1➜ oh-my-zsh: (master) export GIT_TRACE=0
tdl@slava-u1➜ oh-my-zsh: (master) ls
cache  CODE_OF_CONDUCT.md  CONTRIBUTING.md  custom  lib  LICENSE.txt  log  oh-my-zsh.sh  plugins  README.md  SECURITY.md  templates  themes  tools
tdl@slava-u1➜ oh-my-zsh: (master) 



```

**Comment by aguynamedben** [comment]
Is the behavior of "oh-my-zsh.hide-dirty" and "oh-my-zsh.hide-status" documented anywhere? I see people commenting that it's possible, but can't find it in the oh-my-zsh docs.
