### ISSUE TITLE
Apply style to git's error message

### ISSUE THREAD

**Issue by behnammodi** [ohmyzsh/ohmyzsh#9582]
Hi there, I don't know exactly this is related to `ohmyzsh` or `git`, anyway my question is how to show this error message with another color such as red:

![Screen Shot 2021-01-09 at 12 09 05 PM](https://user-images.githubusercontent.com/1549069/104088592-5b3c4c00-527d-11eb-9821-add6e6dae7f5.png)

**Comment by mcornella** [comment]
This is a git issue. [This seems like it might work](https://stackoverflow.com/a/50440338/5798232); haven't tested it.

**Comment by behnammodi** [comment]
Thanks a lot @mcornella
