### ISSUE TITLE
OSX plugin:  unsupported terminal app: Terminal error when using split_tab or vsplit_tab

### ISSUE THREAD

**Issue by belgoros** [ohmyzsh/ohmyzsh#9583]
I enabled the [osx](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/osx) plugin by adding it to the existing ones in the `~/.zshrc` file as follows:
```
plugins=(git rails docker textmate ruby kubectl osx)
```
When restarting the Terminal and hitting `split_tab`followed by `Enter`I got the error:
<img width="333" alt="Screenshot 2021-01-09 at 12 48 47" src="https://user-images.githubusercontent.com/83579/104091010-dc461400-527a-11eb-8655-6bbec441a17e.png">

The same when calling `vsplit_tab`.
Reproduced at macOS `11.1`(Big Sur).

**Comment by mcornella** [comment]
Terminal.app doesn't support split panes, that's why you get this error ([it kind does, but it's not the same thing](https://apple.stackexchange.com/a/342933)).

**Comment by matthiasroder** [comment]
@mcornella can one use a different "terminal" app instead on mac?

**Comment by rwmitchell** [comment]
Looking at the plugin, it appears to support both iTerm2 and Hyper

tested in iTerm2 and it worked.

**Comment by matthiasroder** [comment]
Awesome, thanks!
