### ISSUE TITLE
Border color white

### ISSUE THREAD

**Issue by devilmen80** [ohmyzsh/ohmyzsh#9585]
Hello I don't know as but now I have white color in the bord of my terminal.
Someone can help me to back again with black color in the bord?
Thanks.

**Comment by mcornella** [comment]
Provide more details and a screenshot.

**Comment by devilmen80** [comment]
Hello this is screenshot where there are white bord..and I want to back again with black color...i try many options but I cannot change.
https://imgur.com/a/nLDAdPf

**Comment by mcornella** [comment]
I don't see a white border, I see a grey border on the terminal app and that's not an issue with OMZ.
