### ISSUE TITLE
Initial startup delay after installing Xcode

### ISSUE THREAD

**Issue by trick77** [ohmyzsh/ohmyzsh#9587]
This isn't really a Omz bug but maybe something that can be documented so others can easily find the workaround?

After installing Xcode on my Mac (OS 11) I've noticed that there was this annoying delay (about 10 seconds) the first time I opened a Omz-enhanced zsh after every reboot. There are some pointers that this is caused by nvm but I don't have nvm installed. The culprit in my case is Apple's git implementation which - for some reason - takes a lot of time to execute ```git rev-parse HEAD``` in the Omz directory. It's part of 
```zcompdump_revision="#omz revision: $(builtin cd -q "$ZSH"; git rev-parse HEAD 2>/dev/null)"```

The workaround is to install the Git implementation from Homebrew using brew install git. No more startup delays.

**Comment by mcornella** [comment]
This happened to a user on the Discord server, I think they solved it by installing Homebrew's git.

**Comment by trick77** [comment]
My best guess is that Apple installs a git wrapper in /usr/bin which tries to find out which of Apple's git versions to use since every Xcode version and every Xcode CLI tools version (which doesn't require the Xcode app) brings it's own git binary.
```
$ GIT_TRACE=true /usr/bin/git --version
17:28:33.207322 exec-cmd.c:139          trace: resolved executable path from Darwin stack: /Applications/Xcode.app/Contents/Developer/usr/bin/git
17:28:33.207845 exec-cmd.c:238          trace: resolved executable dir: /Applications/Xcode.app/Contents/Developer/usr/bin
17:28:33.208729 git.c:439               trace: built-in: git version
```

Interestingly, even with brew's git version, the delay came back after installing Node version manager. However, this is a different issue and can be solved with lazing loading nvm.sh:
https://gist.github.com/trick77/7e933d3710b8d756f4347de4a0b34c59#file-nvm-lazy-loading-macos-zsh

Obviously, this just delegates the delay to the first call of nvm/node/npm.

Since this definitely is not an Omz issue I'm closing this, hopefully Google will index it and people will be ably to find this workaround.
