### ISSUE TITLE
zsh: command not found: git_prompt_info after today's update

### ISSUE THREAD

**Issue by phudgins** [ohmyzsh/ohmyzsh#959]
After update today, from 3629270 to 631e3d8, I received the following errors:

``` bash
/home/phudgins/.oh-my-zsh/lib/git.zsh:48: parse error near `elif'
zsh: command not found: git_prompt_info
```

**Comment by gauravmm** [comment]
I had the same problem with zsh on Cygwin (x64, Windows 8.1, fresh install of Cygwin), and replacing `.../lib/git.zsh` with the file contents posted by @phudgins worked. 

Thanks for the tip @baskuis
