### ISSUE TITLE
globalias enhancement

### ISSUE THREAD

**Issue by webberpuma** [ohmyzsh/ohmyzsh#9590]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
globalias

**Is your feature request related to a problem? Please describe.**
i would like to have
1. more control on the expansion trigger. 
2. easier mechanism to toggle the expansion functionality

**Describe the solution you'd like**
1. i would like to use `tab` (or better yet, use a customized key) instead of `space` to expand the alias.
2. i would like to press `ctrl+shift+alt+g` (or better yet, use a customized key combo) to enable the expansionality, then press the same key combo again to disable the expansion functionality

**Additional context**
i have the above request because during my daily usage with the plugin, most of times it functions great. but in some cases, i just don't want it to expand.

**Comment by remino** [comment]
I'm not too knowledgeable of the ZLE and how to manipulate it, so I haven't been able to edit the plugin. But I agree it would be nice if the entire command would only be expanded when hitting a certain key combination rather than have it automatic on every space key press.

**Comment by robbyrussell** [comment]
Hey there, I'm doing a bit of housekeeping on the project. Thanks for raising this issue—we always love a good edge case! 😄

However, it's not gathering much community interest so that I will close it for now. Don't let this discourage you! We're all for hearing about the weird things. We can't commit to spending too much time tracking each weird thing down ourselves.

**Comment by mattmc3** [comment]
The easiest way to do something like this is to [leverage your own `$ZSH_CUSTOM`](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization) implementation of this plugin. It would as simple as adding custom plugin file at `$ZSH_CUSTOM/plugins/globalias/globalias.plugin.zsh`, and adding these contents:

```zsh
# first, source the main plugin
source $ZSH/plugins/globalias/globalias.plugin.zsh

# next, restore space to its normal behavior
bindkey -M emacs " " magic-space
bindkey -M viins " " magic-space

# and finally, make control-space (or whatever you want) execute globalias
bindkey -M emacs "^ " globalias
bindkey -M viins "^ " globalias
```

**Comment by webberpuma** [comment]
> The easiest way to do something like this is to [leverage your own `$ZSH_CUSTOM`](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization) implementation of this plugin. It's as simple as adding a custom plugin file at `$ZSH_CUSTOM/plugins/globalias/globalias.plugin.zsh`, with the following contents:
> 
> ```shell
> # first, source the main plugin
> source $ZSH/plugins/globalias/globalias.plugin.zsh
> 
> # next, restore space to its normal behavior
> bindkey -M emacs " " magic-space
> bindkey -M viins " " magic-space
> 
> # and finally, make control-space (or whatever you want) execute globalias
> bindkey -M emacs "^ " globalias
> bindkey -M viins "^ " globalias
> ```

Thanks for your response! This approach seems good to me, thanks.
