### ISSUE TITLE
Insecure completion-dependent directories detected

### ISSUE THREAD

**Issue by diogoeichert** [ohmyzsh/ohmyzsh#9592]
**Describe the bug**
On new installs and upon opening a new Terminal, ohmyzsh complains about directory group permissions.

**To Reproduce**
Steps to reproduce the behavior, for example:
Just install ohmyzsh on a standard macOS system and open the Terminal.

**Expected behavior**
It should not complain about admin group permissions, i.e. the system might have more than one admin account.

**Screenshots and/or Recordings**
```
[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.
```

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  No.

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support
  Yes, none found.

**Desktop (please complete the following information):**

 - OS / Distro: macOS
 - Latest ohmyzsh update?: Yes
 - ZSH Version: zsh 5.8 (x86_64-apple-darwin20.0)
 - Terminal emulator: Terminal (native)

**Comment by tachun** [comment]
Have you tried this https://github.com/ohmyzsh/ohmyzsh/issues/9262#issuecomment-695199196?

**Comment by diogoeichert** [comment]
But that's not a solution, is it? I mean, please look at this:

```
➜  ~ compaudit | xargs ls -ld
There are insecure directories:
drwxrwxr-x  3 diogoeichert  admin   96 Jan 12 17:45 /usr/local/share/zsh
drwxrwxr-x  4 diogoeichert  admin  128 Jan 12 18:19 /usr/local/share/zsh/site-functions
```

Which should be fine, because I need group writing permissions for other `admin` users in a `shared` directory. And if I simply suppress the message with `ZSH_DISABLE_COMPFIX=true`, I won't get warnings if `others` get write access, which then would be a legit system exposure.

My suggestion is that `group` writing privileges in those directories should not be considered insecure, instead.

**Comment by mcornella** [comment]
> My suggestion is that `group` writing privileges in those directories should not be considered insecure, instead.

Well that would be the same hole, wouldn't it? If the group is changed then the group-writability would be ignored. I think the right approach is that the admin group is considered secure in Darwin systems. This would need to be changed in Zsh itself, since compaudit is bundled with zsh.

[They already have some exceptions per system](https://github.com/zsh-users/zsh/blob/62e86515e79e57e791bc9f5ed815e8020d1dcf6b/Completion/compaudit#L128-L146), so it shouldn't be hard to convince maintainers once a working solution is submitted.

**Comment by diogoeichert** [comment]
> Well that would be the same hole, wouldn't it? If the group is changed then the group-writability would be ignored. I think the right approach is that the admin group is considered secure in Darwin systems. This would need to be changed in Zsh itself, since compaudit is bundled with zsh.

Why would the group change? And why should brew care which group is being used?

> [They already have some exceptions per system](https://github.com/zsh-users/zsh/blob/62e86515e79e57e791bc9f5ed815e8020d1dcf6b/Completion/compaudit#L128-L146), so it shouldn't be hard to convince maintainers once a working solution is submitted.

That's something they could improve on, indeed.

**Comment by laurafTX** [comment]
ZSH_DISABLE_COMPFIX=true in your zshrc file, before OMZ is sourced.

So, can someone explain that to a newbie?  I have no idea how to go about doing that.  Where is my zshrc file on my Mac?  Where and what is the OMZ?

**Comment by rwmitchell** [comment]
You Mac is Unix. Your.zshrc file is or should be in your home directory.

**Comment by diogoeichert** [comment]
> So, can someone explain that to a newbie? I have no idea how to go about doing that. Where is my zshrc file on my Mac? Where and what is the OMZ?

OMZ stands for "Oh My ZSH" and the file should be a hidden file found in your home directory, most likely in `~/.zshrc`.

**Comment by Aisuko** [comment]
Hello guys, I  have two accounts on macOS, one is admin and another one is standard. Everything is working well under the first account but the standard account live is so hard. Because of the permission issue, both of change permission of the folders and `compaudit` will not work. Finally, I need to set the parameter to false. But I believe that will bring risk to the system. So, after a long time using it, every time I opened the Termina I feel it so awesome, right?
<img width="587" alt="Screen Shot 2021-05-05 at 6 03 01 PM" src="https://user-images.githubusercontent.com/8053949/117125470-232cbc00-adcc-11eb-8a0e-a54630dca9d5.png">

**Comment by diogoeichert** [comment]
@Aisuko The standard account should not be expected to be able to add / remove software at all.

**Comment by Aisuko** [comment]
> @Aisuko The standard account should not be expected to be able to add / remove software at all. Those are administrative tasks.

Of course it should be, but `oh-my-zsh` also check these folders permission.

**Comment by Aisuko** [comment]
The iterm2 was installed bu admin account and the standard account need to install `oh-my-zsh` to itself terminal environment.

**Comment by rwmitchell** [comment]
You can install apps without admin if it is for one person.  I have an ```Applications``` folder/directory in my my $HOME where I keep things, including iTerm2.  I also have my own ```local``` where gnu and other outside code goes.  I like having TimeMachine backup my entire home, to make migrating to a new machine easier, but you could also exclude those directories.  Very seldom is admin actually needed.

**Comment by Aisuko** [comment]
Thanks, I create new account and install `Homebrew` `oh-my-zsh` etc. Looks good.
