### ISSUE TITLE
aliasing package-management for quick updates/refresh/search and or install

### ISSUE THREAD

**Issue by oldkingcone** [ohmyzsh/ohmyzsh#9596]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
I have seen plugins for aliases that relate to things like pgsql,git,docker,Kubernetes, etc. But i have not seen one for package management, which for every linux distro, is a mysterious and ominous task for anyone starting a new OS. This can be global

**Describe the solution you'd like**
```
#a typical goto for my distros is i alias all of my apt/dnf/yum/emerge commands
alias install='clear; dnf -y -b install'
alias search='clear; dnf search'
alias whoP='clear; dnf provides'
alias up='clear;echo "Unlocking /etc/passwd";chattr -i /etc/passwd;dnf -y -b upgrade;echo "Re-locking /etc/passwd";chattr +i /etc/passwd'
```
**Additional context**
Not sure if this is something you would want, I can assist in writing a few of the scripts to detect OS if needed, and apply the aliases as needed.

**Comment by robbyrussell** [comment]
We'd consider a PR for something like this but are unlikely to build it ourselves. ✌🏻
