### ISSUE TITLE
[Hang]: Shell getting stuck during empty file content by redirecting to Null

### ISSUE THREAD

**Issue by SushilG96** [ohmyzsh/ohmyzsh#9597]
**Describe the bug**
Facing a hang/stuck during empty file content by redirecting to Null, shell getting stuck at that position.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Create a file and add some content to it.
2. Redirecting to Null, in order to empty the file.

Leetcode|master⚡ ⇒ vim tem.txt
Leetcode|master⚡ ⇒ cat tem.txt 
Check for operation
Leetcode|master⚡ ⇒ > tem.txt 

**Expected behavior**
The command should successfully be executed and would return back the shell 

**Desktop (please complete the following information):**

 - OS / Distro: Fedora 33
 - Latest ohmyzsh update?: Yes
 - ZSH Version: zsh-5.8-3

**Comment by mcornella** [comment]
It's not hanged, it's waiting for input (if you press <kbd>CTRL+D</kbd> it'll stop reading input). `> file` is like saying `cat > file`. If you want to overwrite the file, you should use a command that returns no input, like `:` or `true`:
```sh
: > file    # : is a special builtin that does nothing
true > file # true also has no output, so it also works
```
