### ISSUE TITLE
ZSH ask password every new shell opened

### ISSUE THREAD

**Issue by MorpheusH3x** [ohmyzsh/ohmyzsh#9604]
I first look at  the [issue 7509](https://github.com/ohmyzsh/ohmyzsh/issues/7509) but it did not resolve my bad behavior.
2. Include as much relevant information as possible
I'm using Tmux, oh-my-zsh (my dotfiles are available [here](https://github.com/MorpheusH3x/dotfiles-linux).
Every time I just create a new windows, I am asked for my password.
It ask me one first opening terminal (I have AUTOSTART_TMUX on), when I create a new window in the current session, in another session and in another terminal.
I would like to just know what ask me to enter my passwd so I could that issue.

**Comment by mcornella** [comment]
[This is the culprit](https://github.com/MorpheusH3x/dotfiles-linux/blob/master/.zshrc#L156), you used backticks instead of quotes, which means the command inside gets run.

**Comment by MorpheusH3x** [comment]
Ok
Thank you.
And keep making Oh My Zsh up to date, that is an awesome shell !
