### ISSUE TITLE
deactivate or hide changelog overview post on ssh login

### ISSUE THREAD

**Issue by ghost** [ohmyzsh/ohmyzsh#9608]
request to hide (quiet) the changelog overview post as i login into ssh session. Is this possible via config or variable? I only managed to see this in the update.sh which would be to hardcoded for my interests.

**Comment by mcornella** [comment]
Can you explain specifically what part of displaying the changelog you're having trouble with? You said previously `i login into ssh session via variable`, what does that mean?

**Comment by cbaczynski** [comment]
[https://miro.medium.com/max/679/1*QrPTCyo_olmyjhxtTjO3fA.jpeg](url)

Is it possible to hide this "update post" ?

**Comment by mcornella** [comment]
It looks like you still have the old version that used `less`, in the next update you'll just see the whole changelog without having to quit `less`. Are you ok with that or do you still need to hide the changelog? If so, would you prefer only seeing breaking changes or seeing nothing at all?

**Comment by cbaczynski** [comment]
Ah ok, how would the hiding all option look like?

**Comment by mcornella** [comment]
You'd just see the regular update screen, pre-changelog times:
![image](https://user-images.githubusercontent.com/1441704/106137265-c2596c00-616a-11eb-8d93-4288102c1aae.png)

**Comment by cbaczynski** [comment]
Would it be possible to hide this as well? Dont get me wrong, the first idea would be nice though bug now im curious.

**Comment by mcornella** [comment]
You can disable updating with `DISABLE_AUTO_UPDATE=true` in your zshrc file, before OMZ is sourced. That would prevent any messages at all. Your use case is a bit weird, why do you want to do that?

**Comment by cbaczynski** [comment]
Thank You for your help. We are looking forward to do so. Yeah, i know it's kinda weird question. We were brainstorming and troubleshooting some ideas to our projects and this came up. Possibly it isnt really a technical interest therefore more on the comfort side when youre working on multiple instances.

**Comment by mcornella** [comment]
This fell through the cracks. Since then we added verbosity settings for the update mechanism [^1], as well as the options to change mode (auto / disable / others) and frequency of updates [^2]. 

[^1]: https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#omzupdate-verbosity
[^2]: https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#update-settings
