### ISSUE TITLE
Regression with `dw` in vim mode

### ISSUE THREAD

**Issue by qiuwei** [ohmyzsh/ohmyzsh#9610]
**Describe the bug**
using lastest master branch[c9bf8b4a84d4], dw(delete a word), dd  in vim mode gives error:

```
clipcopy: Platform linux-gnu not supported or xclip/xsel not installed
```

However, commit[ bc9fe7423f5d8c639b2 ] does not have this problem

**To Reproduce**
Steps to reproduce the behavior, for example:
1.  input any command and enter vim mode, press "dw" to delete a word in the command
3. See error

**Expected behavior**
No error should be thrown and the word under cursor should be deleted.

**Screenshots and/or Recordings**
![image](https://user-images.githubusercontent.com/1304505/104980653-09947e00-5a42-11eb-94fc-219b57aa6f79.png)

**Self Check**
**Desktop (please complete the following information):**

 - OS / Distro: Ubuntu 20.04
 - If on Windows what version of WSL: [e.g. WSL1, WSL2]
 - Latest ohmyzsh update?:  yes
 - ZSH Version: 5.8
 - Terminal emulator: Item2

**Additional context**
I am using ssh to log in to the Ubuntu server from MacOS. The Ubuntu server does not have an X server running.

**Comment by mcornella** [comment]
Hi there, this was fixed recently. Try `omz update` and let me know!

**Comment by qiuwei** [comment]
Confirm that it is fixed! Thanks!
