### ISSUE TITLE
Uninstall changes account to system account.

### ISSUE THREAD

**Issue by saurabh-kushwah** [ohmyzsh/ohmyzsh#9616]
Brief:
If the `chsh` fails in unistall zsh script then it changes my account to system account.

Steps to reproduce the behavior, for example:
Run uninstall_oh_my_zsh
Accidently hit C-c when requested for password prompt. ( I think in `sudo chsh` )

Got to revert back by changing the SystemAccount value to false by following this [post](https://askubuntu.com/a/1263662/1175204)

**Desktop**

 - OS / Distro: Ubuntu 20.04
 - Latest ohmyzsh update?: Yes
 - Terminal emulator: Alacritty

When I was trying to uninstall oh my zsh before uninstalling zsh i accidently hit C-c during password prompt which might be in process of changing default shell to other shell. When I unistall zsh and also explicitly run `chsh` to change to bash.

After logoff when I try to login I requested to create new user.

**Comment by mcornella** [comment]
This is a bug in Ubuntu, not OMZ. For the bug where OMZ should abort the uninstallation on CTRL+C follow #6581.
