### ISSUE TITLE
kubectl completion not working

### ISSUE THREAD

**Issue by cannfoddr** [ohmyzsh/ohmyzsh#9622]
I have installed on a MacBook Air M1 running big-sur and am trying to get kubectl completion working.  I have enabled the plugin and can see that 'git' completion is running fine.

'kubectl' or 'kc' attempts at completion just result in a list of files and directories.  I found a closed issue around a very similar problem and have tried all the steps mentioned there including deleting my completions file and restarting item.

Not sure where to go next with this

kubectl version:
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.2-dirty", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"dirty", BuildDate:"2021-01-30T13:00:28Z", GoVersion:"go1.16rc1", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/arm64"}

MacOS: BigSur 11.1

zsh version: zsh 5.8 (x86_64-apple-darwin20.0)

**Comment by crazy-matt** [comment]
while `source <(kubectl completion zsh)` works like a charm...

**Comment by razvan-tudosa** [comment]
I had the same issue, I just move `source <(kubectl completion zsh)` to be the last thing in `.zshrc` and it started working.

**Comment by rmgpinto** [comment]
I have a similar issue.
Actually if I do `k -n <TAB>` it shows the namespaces and the completion works for the namespace.
But if I do `k exec -it <TAB>` then I get directories output.
Any ideas?
Thanks

**Comment by mcornella** [comment]
> But if I do `k exec -it <TAB>` then I get directories output.

I believe kubectl completion doesn't support joining flags, try `k exec -i -t`.

**Comment by mcornella** [comment]
If you're using the `kubectl` plugin, try `rm $ZSH_CACHE_DIR/kubectl_completion` and restart the shell with `exec zsh` or `omz reload`.

Otherwise, https://github.com/ohmyzsh/ohmyzsh/issues/9622#issuecomment-862148845.

**Comment by rmgpinto** [comment]
> If you're using the `kubectl` plugin, try `rm $ZSH_CACHE_DIR/kubectl_completion` and restart the shell with `exec zsh` or `omz reload`.
> 
> Otherwise, [#9622 (comment)](https://github.com/ohmyzsh/ohmyzsh/issues/9622#issuecomment-862148845).

Worked perfectly.
Also `k -n <NAMESPACE> -it` is working.
Thank you very much!
