### ISSUE TITLE
"for" sentences not working properly

### ISSUE THREAD

**Issue by eum602** [ohmyzsh/ohmyzsh#9624]
**Describe the bug**
When running a command that uses a "for" loop the terminal seems to not delete the containers properly.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Execute:
```shell
dockers=`docker ps -a | awk '{print $1}'`
for container in $dockers; do docker rm $container;done
```
2. Check if containers have been deleted with docker ps -a
3. See the error

**Expected behavior**
When executing "docker rm ..." in a "for" loop the involved containers should be deleted. I executed the same sentence in "bash" and successfully deleted all the indicated containers.

**Desktop (please complete the following information):**

 - OS / Distro: Ubuntu 16.07
  - Latest ohmyzsh update?: automatically updated
 - ZSH Version: [e.g. 5.1.1]

**Comment by eum602** [comment]
@mcornella I clearly posted that when executing "for container in $dockers; do docker rm $container;done"  the containers are not deleted. In bash executing the exact same command all the mentioned containers are deleted.

Also only  the first iteration shows "Error: No such container: CONTAINER" but it does not throw the entire loop.

**Comment by mcornella** [comment]
Well, I try really hard to break it (both with and without [`SH_WORD_SPLIT`](http://zsh.sourceforge.net/Doc/Release/Options.html#index-SHWORDSPLIT)) but that's the only error I get:
```
$ dockers=`docker ps -a | awk '{print $1}'`
for container in $dockers; do docker rm $container;done
Error: No such container: CONTAINER
b42989698605
c663b866aab6
b848a34bbd00
e050a4c79043
d9d389b61aae
```

You might have better luck adding an `echo $container` inside the for loop, or using `set -xv` to trace the execution (`set +xv` turns it off):
```zsh
set -xv
dockers=`docker ps -a | awk '{print $1}'`                                                            {1}
for container in $dockers; do docker rm $container;done
set +xv
```
