### ISSUE TITLE
Problems installing  Oh My Zsh using curl [WSL2]

### ISSUE THREAD

**Issue by thedonator** [ohmyzsh/ohmyzsh#9625]
**Describe the bug**
installing with curl command inside ohmyzsh official site `sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`

gives this error `curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs`

**To Reproduce**
1. install wsl2 with ubuntu 20.04 lts
2. Run copi command from https://ohmyz.sh/#install  `sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`
3. outputs this error `curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs`

**Screenshots and/or Recordings**
![screenshot](https://user-images.githubusercontent.com/46758053/106456010-47a39000-648d-11eb-84a6-ac5a8df8cec3.jpg)

**Desktop (please complete the following information):**

 - OS / Distro: [Windows]
 - If on Windows what version of WSL: [WSL2]

**Comment by mcornella** [comment]
Make sure you have the `ca-certificates` package installed. Try reinstalling it if it's already installed.
