### ISSUE TITLE
gitignore plugin is broken because of Cloudflare protection

### ISSUE THREAD

**Issue by henry40408** [ohmyzsh/ohmyzsh#9628]
**Describe the bug**
gitignore plugin is broken because of Cloudflare DDoS protection

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'gitignore'
2. Run command 'gi rust'
3. See error

```
# the status code is returned by Cloudflare
curl: (22) The requested URL returned error: 503
```

**Expected behavior**
Generate a `.gitignore` based on argument

**Screenshots and/or Recordings**
N/A

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? _Yes. No relevant discussions found_
- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support _Yes. No relevant discussions found_

**Desktop (please complete the following information):**

 - OS / Distro: macOS
 - If on Windows what version of WSL: N/A
 - Latest ohmyzsh update?: Yes, https://github.com/ohmyzsh/ohmyzsh/commit/c52e646bb7b109e15f6dc4047b29ca8c8e029433
 - ZSH Version: zsh 5.8 (x86_64-apple-darwin20.1.0)
 - Terminal emulator: iTerm2 Build 3.4.3

**Additional context**
N/A

**Comment by mcornella** [comment]
Looks fine from here. The plugin relies on gitignore.io, how would you want it to handle service issues?

**Comment by henry40408** [comment]
Run the command (`gi rust`) this morning. .gitignore is successfully generated. Maybe it's a temporary issue.
