### ISSUE TITLE
relative path doesn't get tab-completion

### ISSUE THREAD

**Issue by rustiever** [ohmyzsh/ohmyzsh#9631]
**Describe the bug**
When I issue `vi .../` I can't do tab-completion

**To Reproduce**
Steps to reproduce the behavior, for example:
1. type this `vi .../` 
2. press <tab> key
3. there will be visual bell (in my case)

**Expected behavior**
It should give the tab-completion

 - OS / Distro: [macOS]
 - Latest ohmyzsh update?: [Yes]
 - ZSH Version: [e.g. 5.8]
 - Terminal emulator: [Alacritty]

**Comment by mcornella** [comment]
You can use the globalias plugin to automatically expand the dots to their value. After they are expanded to `../..` the path completion will work correctly.

There's also [this plugin](https://github.com/knu/zsh-manydots-magic/blob/master/manydots-magic) that does the same thing only for dots, and my [less tested alternative](https://github.com/mcornella/dotfiles/blob/main/ohmyzsh-custom/magic-dot.zsh) based off [this SO answer](https://stackoverflow.com/questions/23456873/multi-dot-paths-in-zsh-like-cd/23471915#23471915).

**Comment by rustiever** [comment]
Thanks, but I couldn't set the plugin(many dots-magic) can you please help me
