### ISSUE TITLE
We can't visit the url in China https://raw.githubusercontent.com, where can we get the install.sh?

### ISSUE THREAD

**Issue by llqgit** [ohmyzsh/ohmyzsh#9634]
1. Look for similar issues already posted (including closed ones)
2. Include as much relevant information as possible
3. Try to make sure the issue is due to Oh My Zsh

**Comment by mcornella** [comment]
You can use the unofficial mirror at gitee.com: use  https://gitee.com/mcornella/ohmyzsh/raw/master/tools/install.sh instead of the github URL.
