### ISSUE TITLE
`compinit:141: parse error: condition expected: $1` when opening new terminal

### ISSUE THREAD

**Issue by jcollum** [ohmyzsh/ohmyzsh#9635]
Searched, didn't find any similar issues. 

This started happening after a recent update, when opening a new window: 

```
bashcompinit:75: parse error near `('
compinit:141: parse error: condition expected: $1
```

```
✗ zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

I found a script to list my plugins and all i have is git. But I am running nvm and the last time I ran into a problem like this it was related to nvm. But I don't have an nvm plugin installed in zsh. 

Sometimes zsh and brew don't get along so here's my brew version: 

```
✗ brew --version
Homebrew 2.7.7
Homebrew/homebrew-core (git revision ca1d3; last commit 2021-02-03)
Homebrew/homebrew-cask (git revision 8d1ea; last commit 2021-02-03)
```

**Comment by jcollum** [comment]
Been a few days, anyone have any input on this? Need more info?

**Comment by wendajiang** [comment]
i have the same problem
OS version : centos 6
zsh version : 5.7.1 (x86_64-pc-linux-gnu)

and after compinit:141: parse error: condition expected: $1
there is 
![image](https://user-images.githubusercontent.com/13445879/108678623-47dffa00-7526-11eb-86e3-e43004281011.png)

**Comment by jcollum** [comment]
Happening still after the update to 6fbad5bf72fad4ecf30ba4d4ffee62bac582f0ed today

**Comment by jcollum** [comment]
I think this is actually not related to OMZ but instead is an issue with zshell

**Comment by MikeKnowles** [comment]
For me, this issue was resolved once I removed `setopt SH_GLOB`. This only seems to be an issue on zshell 5.7.1

**Comment by jrp2014** [comment]
Still an issue for me under MacOS 12.1

**Comment by rwmitchell** [comment]
What do the following commands output?:
```
echo $SHELL
$(echo $SHELL) --version
```

**Comment by mcornella** [comment]
Locking the thread. Open a new bug report with details if you're having the same problem.
