### ISSUE TITLE
? symbol in CLI charts

### ISSUE THREAD

**Issue by pranshuchittora** [ohmyzsh/ohmyzsh#9636]
![Screenshot from 2021-02-04 01-14-44](https://user-images.githubusercontent.com/32242596/106800435-73d63100-6686-11eb-9d20-7766948e360a.png)

-> gnome-terminator
-> Powerline font
-> Updated ZSH and other deps
-> OS : Ubuntu

**Comment by mcornella** [comment]
That depends on the command that's outputting those characters. Read on its manual to see which font you need.
