### ISSUE TITLE
Better UX when zsh specific parsing breaks

### ISSUE THREAD

**Issue by eugene-kulak** [ohmyzsh/ohmyzsh#9641]
**Is your feature request related to a problem? Please describe.**
```bash
(.venv) ➜  service git:(develop) ✗ pip install fastapi[all]
zsh: no matches found: fastapi[all]
```
Nevertheless, in a regular `bash` it will work.
Taking into account that most snippets on the internet are for bash-like CLI it is very frustrating.

**Describe the solution you'd like**
I see two directions to fix this:

1. better error message, advice to enclose `fastapi[all]` in double quotes, etc
2. smarter approach, try to guess expected behaviour

**Describe alternatives you've considered**
fix it manually

**Comment by mahmoudhossam** [comment]
I think this is a problem in zsh itself, not in ohmyzsh.

**Comment by eugene-kulak** [comment]
@mahmoudhossam I agree. I'm sorry I was under impression that two projects are connected and didn't notice that I choose the wrong one.
