### ISSUE TITLE
jonathan Theme Broken on Arch Linux

### ISSUE THREAD

**Issue by iAwesome404** [ohmyzsh/ohmyzsh#9644]
The ZSH theme jonathan is not working right. It prints out "$PR_SHIFT_IN${altchar[l]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT(~)$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUTHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT(centurylink@archlinux:pts/1)$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[k]:--}$PR_SHIFT_OUT
$PR_SHIFT_IN${altchar[m]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT(16:30:13)$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT> " for the prompt.

Arch Linux, Linux Zen. Doesn't appear on Ubuntu/Debian, OpenSuse.

**Comment by iAwesome404** [comment]
Also, When using oh-my-zsh, the terminal glitches out and messes up the current command.

**Comment by AYiXi** [comment]
change a theme

**Comment by mcornella** [comment]
Make sure you haven't disabled `setopt promptsubst`.

**Comment by ssepi0l-pv** [comment]
Hey, I added `setopt PROMPT_SUBST` in my .zshrc file, but it stills shows improperly: https://imgur.com/a/Fath7OF
Also tried adding it like `setopt promptsubst`which didn't worked either. Here is a dumplog:
https://ghostbin.com/paste/DqXFZ

And here is how I see the zsh: https://imgur.com/a/Fath7OF

**Comment by mcornella** [comment]
Try disabling the `base16` thing, maybe that's conflicting with the theme.

**Comment by ssepi0l-pv** [comment]
Didn't work. Base16 it's a colortheme manager, it really doesn't change anything else more than the colours of my terminal. 

I'll give some context from when this started happening: I broke my distro installing bad drivers for my GPU. So I arch-chrooted inside my pc and made a new and fresh install. Before the new install, my zshrc was working flawlessly. Never ever had a problem. But now, well, it's this thing. Also, might I add, Jonathan is the only theme (that I've found) that doesn't works. I don't know if you can see it inside the dumplog, but I have like four more themes in case that I want to change them. Every other theme works, but Jonathan doesn't. 

If any other info needed, feel free to ask for it. Will happily give it out :)

![image](https://user-images.githubusercontent.com/64175868/114317837-0efce400-9ad8-11eb-8560-0eac046245d1.png)
(Above I was using the Darkblood-theme. I changed it to Jonathan, and it shows up like that.

**Comment by mcornella** [comment]
Can you post the output of `typeset -p PROMPT`? Maybe the dollar signs were quoted, since `promptsubst` appears to be set.

**Comment by mcornella** [comment]
Also look up your messages on Discord, I private-messaged you there.

**Comment by ssepi0l-pv** [comment]
> Also look up your messages on Discord, I private-messaged you there.

Just saw that, thank you!

And talking about Jonathan, well now it works. Yesterday I installed Powerlevel10k theme into Zsh. Just now I tried the Jonathan theme, and now it works!! 

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
setopt PROMPT_SUBST

After this was added, it started to work. Although, I'd say that the problem had to do with some font. I installed `nerd-fonts-complete` for simple customization, but it may have done the trick. Anyway, this issue shall be closed! Thank you m8s!

**Comment by maxbbender** [comment]
I'm running into this again on Ubuntu 22.04

```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
```

Same output as on Arch Linux

```
$PR_SHIFT_IN${altchar[l]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT(~)$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT(bender@bendermain:pts/0)$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[k]:--}$PR_SHIFT_OUT
$PR_SHIFT_IN${altchar[m]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT(09:59:24)$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT>
```

I tried the `typeset` command as referenced in https://github.com/ohmyzsh/ohmyzsh/issues/9644#issuecomment-818769586 but to no avail. Any ideas?

**Comment by maxbbender** [comment]
> I'm running into this again on Ubuntu 22.04
> 
> ```
> PRETTY_NAME="Ubuntu 22.04.1 LTS"
> NAME="Ubuntu"
> VERSION_ID="22.04"
> VERSION="22.04.1 LTS (Jammy Jellyfish)"
> VERSION_CODENAME=jammy
> ```
> 
> Same output as on Arch Linux
> 
> ```
> $PR_SHIFT_IN${altchar[l]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT(~)$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT(bender@main:pts/0)$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[k]:--}$PR_SHIFT_OUT
> $PR_SHIFT_IN${altchar[m]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT(09:59:24)$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT$PR_SHIFT_IN${altchar[q]:--}$PR_SHIFT_OUT>
> ```
> 
> I tried the `typeset` command as referenced in [#9644 (comment)](https://github.com/ohmyzsh/ohmyzsh/issues/9644#issuecomment-818769586) but to no avail. Any ideas?

Now it works today. Not sure but I assume something to restarted and picked up the right font set? /shrug
