### ISSUE TITLE
Text Misaligned in the terminal window

### ISSUE THREAD

**Issue by prashant8530** [ohmyzsh/ohmyzsh#9645]
Has anyone ever encountered this issue while using ohmyzsh ?

![image](https://user-images.githubusercontent.com/7425921/107161681-507fee80-69c4-11eb-8f61-779b68932a8b.png)

I have to start a new terminal session whenver this issue is encountered.

I am using MacOS Big Sur, iTerm2

**Comment by rwmitchell** [comment]
Looks like you have an incorrect stty setting.  Is this something new or has the output always looked like this?

**Comment by prashant8530** [comment]
@rwmitchell This happens randomly after sometime the current session is open, I have to close the current tab and reopen a new tab everytime this happens.

**Comment by rwmitchell** [comment]
Try entering: ```stty sane```  in the terminal the next time this happens.  If that doesn't work, try going to iTerm2 menu bar, select ```Session->Reset```

If this fixes it, start making a note of what you're during prior to the problem.

**Comment by prashant8530** [comment]
@rwmitchell Do I have to do this everytime when this happens?

**Comment by rwmitchell** [comment]
Yes.  First is to see if this fixes the problem.  Next is to determine what is causing it, then fix that.  This could come from improperly exiting a program that has modified the terminal settings and didn't get a chance to restore them.

Are the settings above from when the terminal is working properly, or not working.
And those aren't all of the settings.  Use ```stty -a``` to see everything.

**Comment by prashant8530** [comment]
The setting mentioned are when the terminal is working properly.

speed 38400 baud; 72 rows; 272 columns;
lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl
        -echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
        -extproc
iflags: -istrip icrnl -inlcr -igncr ixon -ixoff -ixany imaxbel -iutf8
        -ignbrk brkint -inpck ignpar -parmrk
oflags: opost onlcr oxtabs onocr onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
        -dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
        eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
        min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
        stop = ^S; susp = ^Z; time = 0; werase = ^W;

**Comment by rwmitchell** [comment]
I don't really need to see your settings, except they look normal and that's because the are.

Doing ```stty sane``` should fix the problem the next time it happens.  If not, try the reset menu option.
This is to help you fix it without having to close and open a new terminal.  Next is for you to figure out why it is happening, which is a result of a program you're running.  It isn't the fault of zsh, omz, or even iTerm2.  It is being caused by a command you are running. ```cat```ing a binary program to the terminal can also cause it.  You have to figure what that is.

**Comment by mcornella** [comment]
Thanks for the support!
