### ISSUE TITLE
Vi-mode custom key macros?

### ISSUE THREAD

**Issue by mcondren** [ohmyzsh/ohmyzsh#9647]
Hello,

I am trying to set some custom key remaps in ZSH vi-mode that would be useful on the command line. Like binding ‘bb’ to ‘0ciw’ basically a shortcut to go to beginning of line, remove the first word and go into insert mode. This would allow me to sub out cat for ls, for example, quickly. That key string works fine manually but is 4 keystrokes. Can you nnoremap similar to in a .vimrc file?

Thanks

**Comment by mcornella** [comment]
Old issue, but you can use `bindkey -s`, for example:
```zsh
bindkey -a "gu" vi-down-case
bindkey -s -a "guu" "gugu"
```

In your case that will be
```zsh
bindkey -a -s "bb" "0ciw"
```

The `-a` is for `vicmd`.
