### ISSUE TITLE
No native ls colours when using grc plugin

### ISSUE THREAD

**Issue by piefel** [ohmyzsh/ohmyzsh#9648]
**Describe the bug**

When using the `grc` plugin (and possibly others), the ‘native’ colours from `ls` will be ignored.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin `grc`
2. Run command `ls -l` in a directory with some stuff in it like sub-directories and executable files
3. We see the colours from `grc` (permissions, date), but not the colours from `ls` (highlighted executables or directories)

**Expected behavior**

I want both the original colours from `ls` and the new colours from `grc`

**Additional context**

I am using GNU `ls` (Ubuntu). The `grc` plugin only loads the `grc.zsh` from the system.

The final resulting alias of Oh My Zsh and applied plugin is `grc --colour=auto ls --color=tty`. The problem is that with the prefixed `grc`, `ls` does not consider itself running in a TTY anymore, meaning it will decide not to show its colours anymore. Changing the alias definition in `lib/theme-and-appearance.zsh` (line 35) fixes this for me, but that is not the general fix, I assume.

Adding `alias ls='grc --colour=auto ls --color=always'` in `plugins/grc/grc.plugin.zsh` also fixes this quite nicely, this may be a better place for colour-hungry people.

**Comment by mcornella** [comment]
This is a grc issue. It's really a difficult problem though. If you want old ls colors just remove the ls function / alias that grc creates.

**Comment by piefel** [comment]
Is it really a grc problem? Look, I even proposed a change within the ZSH plugin that works for me (at least for the last 6 weeks). And note I want _both_ colours…

Anyway, I have my own setup working now.
