### ISSUE TITLE
Allow tmux binary name to be changed

### ISSUE THREAD

**Issue by wac-** [ohmyzsh/ohmyzsh#9652]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
tmux

**Is your feature request related to a problem? Please describe.**
I'm unable to use a `tmux` binary that has been renamed to something else for development or configuration reasons (e.g. tmx2, tmux-stable).

**Describe the solution you'd like**
Make the name of the `tmux` binary configurable.

**Describe alternatives you've considered**
I could have an alias that masks a system provided `tmux`, but this winds up confusing other things.

**Additional context**
PR is inbound momentarily.

**Related Issues**
None.

**Comment by mcornella** [comment]
See https://github.com/ohmyzsh/ohmyzsh/pull/9653#issuecomment-2150618833.
