### ISSUE TITLE
Issue with z command on latest ohmyzsh

### ISSUE THREAD

**Issue by johnalanwoods** [ohmyzsh/ohmyzsh#9656]
**Describe the bug**
`z` command no longer works

**To Reproduce**
* Update to latest ohmyzsh
* type `z` 
* notice command not found

**Expected behavior**
Previously, on macOS with latest ohmyzsh and zsh 5.8, `z` worked without plugins or issues

**Self Check**

* googled a lot.

**Desktop (please complete the following information):**

 - macOS 11.2
 - Latest ohmyzsh update?: YES
 - ZSH Version: 5.8
 - Terminal emulator: iTerm2

I read folks suggesting adding `z` to plugins section, didn't have to do this before and when I do now, it prints this unusual output:

```
common:    /Users/john/tmp
4          /Users/john/tmp/iterm2-Aug2020
40         /Users/John/tmp
```

Was `z` removed?

**Comment by mcornella** [comment]
Can you post your zshrc file?
