### ISSUE TITLE
Optimize images for themes page in wiki

### ISSUE THREAD

**Issue by airdry** [ohmyzsh/ohmyzsh#9664]
When you open this page https://github.com/ohmyzsh/ohmyzsh/wiki/Themes, the browser is forced to download ~ 69MB of content.Most images are 590KB in size.
Can I compress these images, put them in this issue and create a merge request for the updated wiki page with the already compressed content in the https://github.com/ohmyzsh/ohmyzsh project?
I have no rights to edit the wiki. But the mantainer will be able to subtract my updated file on the wiki.
I will try to do this. On average, the image will weigh 110Kb.

**Comment by TheTechRobo** [comment]
you don't have rights to edit wiki ? How not? Can you Not click Edit button in TOp right ?

**Comment by airdry** [comment]
![62960429-ebf9c880-bdfa-11e9-9d26-193d50ea34de_optimized](https://user-images.githubusercontent.com/49100982/108254738-764b8700-716c-11eb-9a59-4deb8c8c6193.jpg)
![62960494-09c72d80-bdfb-11e9-8f5c-1c0149ef453b_optimized](https://user-images.githubusercontent.com/49100982/108254742-76e41d80-716c-11eb-89b0-09445ce76ff0.jpg)
![62960517-177cb300-bdfb-11e9-942f-e6f6e9383246_optimized](https://user-images.githubusercontent.com/49100982/108254744-777cb400-716c-11eb-9407-1463775bbc25.jpg)
![62960553-295e5600-bdfb-11e9-86f3-8cdfe5bbe947_optimized](https://user-images.githubusercontent.com/49100982/108254745-777cb400-716c-11eb-800a-a8cfa612253f.jpg)
![62960555-29f6ec80-bdfb-11e9-9011-29fe69bc058a_optimized](https://user-images.githubusercontent.com/49100982/108254746-78154a80-716c-11eb-873a-6500b9d54219.jpg)
![62960556-29f6ec80-bdfb-11e9-9ad7-63cd1181fc53_optimized](https://user-images.githubusercontent.com/49100982/108254748-78ade100-716c-11eb-8f61-0a2bec4f671c.jpg)
![62960559-29f6ec80-bdfb-11e9-8661-3a50d911d494_optimized](https://user-images.githubusercontent.com/49100982/108254750-78ade100-716c-11eb-8c3b-7d529b7b4e25.jpg)
![62960560-2a8f8300-bdfb-11e9-8367-44c397bb7a9e_optimized](https://user-images.githubusercontent.com/49100982/108254751-78ade100-716c-11eb-9135-39cbffcf406e.jpg)
![62960561-2a8f8300-bdfb-11e9-82ba-0bf2dfa95671_optimized](https://user-images.githubusercontent.com/49100982/108254752-79467780-716c-11eb-82d4-304d04bf35bf.jpg)
![62960742-9ffb5380-bdfb-11e9-81d2-da12212829b0_optimized](https://user-images.githubusercontent.com/49100982/108254755-79df0e00-716c-11eb-9069-da947bd4a3dc.jpg)
![62960743-9ffb5380-bdfb-11e9-91bc-866a9bda2106_optimized](https://user-images.githubusercontent.com/49100982/108254758-79df0e00-716c-11eb-8990-62f456ddd785.jpg)
![62960744-9ffb5380-bdfb-11e9-8167-1dc4dbf1b835_optimized](https://user-images.githubusercontent.com/49100982/108254762-7a77a480-716c-11eb-8665-b4f459fd8920.jpg)
![62960747-9ffb5380-bdfb-11e9-848c-26372f7b690d_optimized](https://user-images.githubusercontent.com/49100982/108254767-7b103b00-716c-11eb-9bdd-426643a53722.jpg)
![62960748-a093ea00-bdfb-11e9-93e0-9d945d0cbe13_optimized](https://user-images.githubusercontent.com/49100982/108254768-7b103b00-716c-11eb-92e1-ebd7486d6f13.jpg)
![62960749-a093ea00-bdfb-11e9-9bbf-04ce2a6fd6a0_optimized](https://user-images.githubusercontent.com/49100982/108254770-7ba8d180-716c-11eb-965f-63b9ce0efe15.jpg)
![62960752-a093ea00-bdfb-11e9-89d4-0d6ae616db94_optimized](https://user-images.githubusercontent.com/49100982/108254772-7ba8d180-716c-11eb-9d96-f54d13acde5b.jpg)
![62960753-a093ea00-bdfb-11e9-9922-a72495b2b06a_optimized](https://user-images.githubusercontent.com/49100982/108254774-7c416800-716c-11eb-9ea8-8f8cbac82922.jpg)
![62961066-56f7cf00-bdfc-11e9-9c5b-10044d622f61_optimized](https://user-images.githubusercontent.com/49100982/108254775-7c416800-716c-11eb-8e54-fa40ccb0d519.jpg)
![62961067-56f7cf00-bdfc-11e9-911b-0316a41b7779_optimized](https://user-images.githubusercontent.com/49100982/108254776-7cd9fe80-716c-11eb-889a-84d7b26df847.jpg)
![62961068-56f7cf00-bdfc-11e9-951e-a2e06d21ae3c_optimized](https://user-images.githubusercontent.com/49100982/108254777-7d729500-716c-11eb-9ab2-232ed00e30aa.jpg)
![62961138-7e4e9c00-bdfc-11e9-8530-5e0d386ada0c_optimized](https://user-images.githubusercontent.com/49100982/108254779-7d729500-716c-11eb-98b9-ef343be7a8fe.jpg)
![62961141-7e4e9c00-bdfc-11e9-9a9f-d8b858ad6f8d_optimized](https://user-images.githubusercontent.com/49100982/108254782-7e0b2b80-716c-11eb-95db-b149bc1c0032.jpg)
![62961143-7e4e9c00-bdfc-11e9-9777-ce1f230de9d7_optimized](https://user-images.githubusercontent.com/49100982/108254784-7e0b2b80-716c-11eb-9363-b1e587e1d199.jpg)
![62961144-7e4e9c00-bdfc-11e9-9693-4270c50e2031_optimized](https://user-images.githubusercontent.com/49100982/108254786-7ea3c200-716c-11eb-9c33-d24d404d4e25.jpg)
![62961146-7e4e9c00-bdfc-11e9-9e29-aae8d5f74b8f_optimized](https://user-images.githubusercontent.com/49100982/108254788-7f3c5880-716c-11eb-96e3-27cc0d6297d3.jpg)
![62961147-7e4e9c00-bdfc-11e9-8ac3-ef4d49178357_optimized](https://user-images.githubusercontent.com/49100982/108254790-7fd4ef00-716c-11eb-821e-d11fba0c4f10.jpg)
![62961148-7ee73280-bdfc-11e9-9b12-0719b80046fb_optimized](https://user-images.githubusercontent.com/49100982/108254792-7fd4ef00-716c-11eb-8fa7-67d845b771be.jpg)
![62961149-7ee73280-bdfc-11e9-89c5-8bcd02d0097a_optimized](https://user-images.githubusercontent.com/49100982/108254797-806d8580-716c-11eb-9ec5-ae1b23d0a7cd.jpg)
![62961151-7ee73280-bdfc-11e9-860d-dab928179199_optimized](https://user-images.githubusercontent.com/49100982/108254799-806d8580-716c-11eb-9f1e-2634dc9309d3.jpg)
![62961289-ca99dc00-bdfc-11e9-9965-27d49bf087c7_optimized](https://user-images.githubusercontent.com/49100982/108254800-81061c00-716c-11eb-858e-aa17d4c5e07e.jpg)
![62961290-ca99dc00-bdfc-11e9-8016-93e12a40d42e_optimized](https://user-images.githubusercontent.com/49100982/108254801-819eb280-716c-11eb-9279-01b8ef95c734.jpg)
![62961291-ca99dc00-bdfc-11e9-8998-6f50cc06c200_optimized](https://user-images.githubusercontent.com/49100982/108254802-819eb280-716c-11eb-9d66-d21bb1e7196c.jpg)
![62961292-ca99dc00-bdfc-11e9-8c5e-a1f356ceef07_optimized](https://user-images.githubusercontent.com/49100982/108254803-82374900-716c-11eb-9510-ef560d31e7e7.jpg)
![62961293-ca99dc00-bdfc-11e9-91f1-de80272be791_optimized](https://user-images.githubusercontent.com/49100982/108254804-82374900-716c-11eb-9636-71abb16053df.jpg)
![62961370-eb623180-bdfc-11e9-87c7-cd557f08cbe3_optimized](https://user-images.githubusercontent.com/49100982/108254806-82cfdf80-716c-11eb-9bbc-2d9648109b31.jpg)
![62961371-ebfac800-bdfc-11e9-9c37-64aa5117259c_optimized](https://user-images.githubusercontent.com/49100982/108254809-82cfdf80-716c-11eb-8d66-027fe4ecfd55.jpg)
![62961373-ebfac800-bdfc-11e9-93fd-77b12b608953_optimized](https://user-images.githubusercontent.com/49100982/108254811-83687600-716c-11eb-88df-2d1fb721a62b.jpg)
![62961375-ebfac800-bdfc-11e9-81ab-9c87c1c629ad_optimized](https://user-images.githubusercontent.com/49100982/108254813-83687600-716c-11eb-98dc-083a14aae6e1.jpg)
![62961376-ebfac800-bdfc-11e9-8629-801812f3cef3_optimized](https://user-images.githubusercontent.com/49100982/108254817-84010c80-716c-11eb-8d56-81bc95a46ef5.jpg)
![62961377-ebfac800-bdfc-11e9-9e6e-ddf4fa38699f_optimized](https://user-images.githubusercontent.com/49100982/108254819-8499a300-716c-11eb-9c13-c6fd49d72a6c.jpg)
![62961379-ec935e80-bdfc-11e9-9a8c-c605ccf0f281_optimized](https://user-images.githubusercontent.com/49100982/108254820-8499a300-716c-11eb-922d-5cc6ffa08fc1.jpg)
![62961380-ec935e80-bdfc-11e9-8f80-d77e8adc42d6_optimized](https://user-images.githubusercontent.com/49100982/108254821-85323980-716c-11eb-90b9-fc0b4b014f36.jpg)
![62961381-ec935e80-bdfc-11e9-92fb-b8bb9e6078b8_optimized](https://user-images.githubusercontent.com/49100982/108254822-85323980-716c-11eb-8422-69480dce0f62.jpg)
![62961382-ec935e80-bdfc-11e9-84e4-0785ea308284_optimized](https://user-images.githubusercontent.com/49100982/108254824-85cad000-716c-11eb-9b7a-fe9e24131df7.jpg)
![62961508-2f553680-bdfd-11e9-98f9-898b8d418ea2_optimized](https://user-images.githubusercontent.com/49100982/108254827-86636680-716c-11eb-94e2-64318cb21f3b.jpg)
![62961509-2f553680-bdfd-11e9-8abc-9faaefebe0f7_optimized](https://user-images.githubusercontent.com/49100982/108254828-86636680-716c-11eb-8d3a-146431df149f.jpg)
![62961510-2f553680-bdfd-11e9-961c-e126714e2bed_optimized](https://user-images.githubusercontent.com/49100982/108254830-86fbfd00-716c-11eb-8e9e-57cb190cd35b.jpg)
![62961511-2f553680-bdfd-11e9-944f-18b9a65d8c28_optimized](https://user-images.githubusercontent.com/49100982/108254832-86fbfd00-716c-11eb-8bbf-7840e84b4c44.jpg)
![62961512-2fedcd00-bdfd-11e9-8e44-f4ad6be47ce2_optimized](https://user-images.githubusercontent.com/49100982/108254834-87949380-716c-11eb-8ff7-9a494c650852.jpg)
![62961514-2fedcd00-bdfd-11e9-8433-9d0fb5eaa5e8_optimized](https://user-images.githubusercontent.com/49100982/108254836-87949380-716c-11eb-8d5b-a4b24ea53f67.jpg)
![62961515-2fedcd00-bdfd-11e9-995b-59b42041c8f0_optimized](https://user-images.githubusercontent.com/49100982/108254837-882d2a00-716c-11eb-9f49-3b5e6e62eb52.jpg)
![62961517-2fedcd00-bdfd-11e9-8ba6-1d508c8460c8_optimized](https://user-images.githubusercontent.com/49100982/108254838-88c5c080-716c-11eb-9bd9-4d88b870f04f.jpg)
![62961593-5a3f8a80-bdfd-11e9-912f-ca3e2a4aa9e5_optimized](https://user-images.githubusercontent.com/49100982/108254840-88c5c080-716c-11eb-9971-f2cfbf54f91a.jpg)
![62961595-5a3f8a80-bdfd-11e9-9526-20eeccc3b3f2_optimized](https://user-images.githubusercontent.com/49100982/108254841-895e5700-716c-11eb-9984-ab8ec70ad92e.jpg)
![62961597-5ad82100-bdfd-11e9-8459-ca1fd31dd43c_optimized](https://user-images.githubusercontent.com/49100982/108254845-895e5700-716c-11eb-807f-0ecb0aa4db00.jpg)
![62961599-5ad82100-bdfd-11e9-810a-2349233ca712_optimized](https://user-images.githubusercontent.com/49100982/108254849-89f6ed80-716c-11eb-8e92-dcf5e576df64.jpg)
![62961600-5ad82100-bdfd-11e9-969a-43e034065c1c_optimized](https://user-images.githubusercontent.com/49100982/108254851-89f6ed80-716c-11eb-9922-185b952b24db.jpg)
![62961660-79d6b300-bdfd-11e9-8d69-2ea44ed22bac_optimized](https://user-images.githubusercontent.com/49100982/108254853-8a8f8400-716c-11eb-9775-780e00c3f680.jpg)
![62961661-79d6b300-bdfd-11e9-872e-b51a40bb3c7d_optimized](https://user-images.githubusercontent.com/49100982/108254855-8b281a80-716c-11eb-960d-2f2cf8e5153f.jpg)
![62961663-79d6b300-bdfd-11e9-96ad-76bf2c061ab2_optimized](https://user-images.githubusercontent.com/49100982/108254857-8bc0b100-716c-11eb-808f-d0b6f1a16774.jpg)
![62961664-7a6f4980-bdfd-11e9-8933-7d3e3d2a5ded_optimized](https://user-images.githubusercontent.com/49100982/108254859-8bc0b100-716c-11eb-998b-4ee8bb6c1f3f.jpg)
![62961665-7a6f4980-bdfd-11e9-8b93-b9c41b11cd8e_optimized](https://user-images.githubusercontent.com/49100982/108254860-8c594780-716c-11eb-8f8b-be04d4943216.jpg)
![62961666-7a6f4980-bdfd-11e9-8fa5-394d4319ad2f_optimized](https://user-images.githubusercontent.com/49100982/108254862-8cf1de00-716c-11eb-8bfe-f2e46376a10f.jpg)
![62961667-7a6f4980-bdfd-11e9-9866-7094a8988f72_optimized](https://user-images.githubusercontent.com/49100982/108254863-8cf1de00-716c-11eb-935f-87cc85ef6ed7.jpg)
![62961668-7a6f4980-bdfd-11e9-8da6-644379f1c18a_optimized](https://user-images.githubusercontent.com/49100982/108254869-8d8a7480-716c-11eb-8857-ee82b1fe4023.jpg)
![62961669-7a6f4980-bdfd-11e9-99fe-09f2559f153a_optimized](https://user-images.githubusercontent.com/49100982/108254872-8d8a7480-716c-11eb-9782-4a37a851ce1f.jpg)
![62961670-7b07e000-bdfd-11e9-9aef-87128aa769c3_optimized](https://user-images.githubusercontent.com/49100982/108254874-8e230b00-716c-11eb-90ea-e4f66c9a3dd6.jpg)
![62965888-36cd0d80-be06-11e9-83c6-836228a04a48_optimized](https://user-images.githubusercontent.com/49100982/108254876-8e230b00-716c-11eb-9adb-50d695796563.jpg)
![62965889-36cd0d80-be06-11e9-8ab1-a9d56aae78a7_optimized](https://user-images.githubusercontent.com/49100982/108254877-8ebba180-716c-11eb-9fb5-9b0437433305.jpg)
![62965891-36cd0d80-be06-11e9-9ad2-ed2e9fb3f345_optimized](https://user-images.githubusercontent.com/49100982/108254878-8f543800-716c-11eb-9373-a3e4e19b58ae.jpg)
![62965893-36cd0d80-be06-11e9-8c24-e5d21a03b9a7_optimized](https://user-images.githubusercontent.com/49100982/108254881-8f543800-716c-11eb-8115-2232727264d6.jpg)
![62965895-3765a400-be06-11e9-9f8f-53cd2ee8224b_optimized](https://user-images.githubusercontent.com/49100982/108254883-8fecce80-716c-11eb-9a4d-ad5c465af835.jpg)
![62965896-3765a400-be06-11e9-9eb8-e5e04f772ae7_optimized](https://user-images.githubusercontent.com/49100982/108254885-8fecce80-716c-11eb-8012-aabac630c475.jpg)
![62965897-3765a400-be06-11e9-94a8-e8ee994b72e7_optimized](https://user-images.githubusercontent.com/49100982/108254886-90856500-716c-11eb-81e8-8ba2b7ea922f.jpg)
![62965898-37fe3a80-be06-11e9-8872-a5dc726d3693_optimized](https://user-images.githubusercontent.com/49100982/108254887-911dfb80-716c-11eb-99a0-275b35afd9ce.jpg)
![62965990-62e88e80-be06-11e9-8fb7-d219b0042f0f_optimized](https://user-images.githubusercontent.com/49100982/108254888-911dfb80-716c-11eb-9595-b08415fb1c17.jpg)
![62965991-62e88e80-be06-11e9-989c-3c8fdc2f0b3f_optimized](https://user-images.githubusercontent.com/49100982/108254890-91b69200-716c-11eb-8fa3-108c8692087c.jpg)
![62965992-62e88e80-be06-11e9-8c0c-7654e97f6b37_optimized](https://user-images.githubusercontent.com/49100982/108254893-91b69200-716c-11eb-9f6c-221967f1adc6.jpg)
![62965993-63812500-be06-11e9-99f3-c5b44934fab0_optimized](https://user-images.githubusercontent.com/49100982/108254896-924f2880-716c-11eb-83fe-be8f732f46da.jpg)
![62965994-63812500-be06-11e9-9f6f-3d36e3cc4fa3_optimized](https://user-images.githubusercontent.com/49100982/108254897-92e7bf00-716c-11eb-86b8-bf00a43d6a43.jpg)
![62965995-63812500-be06-11e9-9739-5877d641a269_optimized](https://user-images.githubusercontent.com/49100982/108254898-92e7bf00-716c-11eb-92af-e6cd875f7ba5.jpg)
![62965997-63812500-be06-11e9-904d-352b78cd4408_optimized](https://user-images.githubusercontent.com/49100982/108254899-93805580-716c-11eb-84d6-822e33ad5ffb.jpg)
![62965998-63812500-be06-11e9-97a0-34cac4e5b0df_optimized](https://user-images.githubusercontent.com/49100982/108254900-93805580-716c-11eb-9e39-5e8dda6c2308.jpg)
![62966000-63812500-be06-11e9-8ba7-0d8f7fbea464_optimized](https://user-images.githubusercontent.com/49100982/108254901-9418ec00-716c-11eb-9439-6dd4621e6784.jpg)
![62966001-6419bb80-be06-11e9-9d41-b2632295e445_optimized](https://user-images.githubusercontent.com/49100982/108254902-9418ec00-716c-11eb-9001-6a5abecf0aa1.jpg)
![62966002-6419bb80-be06-11e9-90f0-7ef55042e6e9_optimized](https://user-images.githubusercontent.com/49100982/108254903-94b18280-716c-11eb-9961-6797e45b98af.jpg)
![62966003-6419bb80-be06-11e9-9d0a-db4f1eb096e8_optimized](https://user-images.githubusercontent.com/49100982/108254905-954a1900-716c-11eb-820c-15814dd13a7d.jpg)
![62966128-b22ebf00-be06-11e9-928b-0c0e86142eef_optimized](https://user-images.githubusercontent.com/49100982/108254907-954a1900-716c-11eb-8be4-d8accb5a2a44.jpg)
![62966129-b22ebf00-be06-11e9-8b42-fd00e20e12a8_optimized](https://user-images.githubusercontent.com/49100982/108254909-95e2af80-716c-11eb-8d16-d78875d9263a.jpg)
![62966130-b22ebf00-be06-11e9-94f2-9f692d31aedf_optimized](https://user-images.githubusercontent.com/49100982/108254911-95e2af80-716c-11eb-811d-e8ea16f6ee0c.jpg)
![62966131-b2c75580-be06-11e9-9b0c-de2100cdd437_optimized](https://user-images.githubusercontent.com/49100982/108254912-967b4600-716c-11eb-8e3e-eb5487570074.jpg)
![62966132-b2c75580-be06-11e9-9d58-70e9f15876a7_optimized](https://user-images.githubusercontent.com/49100982/108254914-967b4600-716c-11eb-8c11-830bc97f274e.jpg)
![62966133-b2c75580-be06-11e9-890e-e2cd14c79e52_optimized](https://user-images.githubusercontent.com/49100982/108254917-9713dc80-716c-11eb-8f73-69c67ced32a7.jpg)
![62966134-b2c75580-be06-11e9-9ee2-c56eb03f0220_optimized](https://user-images.githubusercontent.com/49100982/108254919-97ac7300-716c-11eb-9338-cb7009d3a5ea.jpg)
![62966135-b35fec00-be06-11e9-8318-9ae8fdb6ca4c_optimized](https://user-images.githubusercontent.com/49100982/108254920-97ac7300-716c-11eb-80d5-301ba10cf969.jpg)
![62966137-b35fec00-be06-11e9-85a8-2d90d395c304_optimized](https://user-images.githubusercontent.com/49100982/108254921-98450980-716c-11eb-9d27-18562610887f.jpg)
![62966419-4a2ca880-be07-11e9-8b32-2266fc1c09da_optimized](https://user-images.githubusercontent.com/49100982/108254922-98450980-716c-11eb-88af-2e1c1ba5c5fe.jpg)

**Comment by airdry** [comment]
![62966420-4ac53f00-be07-11e9-9b62-7816a65871bb_optimized](https://user-images.githubusercontent.com/49100982/108255729-b2cbb280-716d-11eb-8869-d612e2344ef5.jpg)
![62966421-4ac53f00-be07-11e9-87de-99ea008be104_optimized](https://user-images.githubusercontent.com/49100982/108255732-b2cbb280-716d-11eb-8587-f8b412c48907.jpg)
![62966422-4ac53f00-be07-11e9-88cf-740f1ad2edde_optimized](https://user-images.githubusercontent.com/49100982/108255733-b3644900-716d-11eb-8fea-4ce136198782.jpg)
![62966423-4ac53f00-be07-11e9-9f02-32b02c25d4a9_optimized](https://user-images.githubusercontent.com/49100982/108255734-b3fcdf80-716d-11eb-8e9b-b8c7c7546e75.jpg)
![62966424-4ac53f00-be07-11e9-8b4a-3de59e7bb806_optimized](https://user-images.githubusercontent.com/49100982/108255735-b3fcdf80-716d-11eb-92ee-678fd1bff92f.jpg)
![62966495-76e0c000-be07-11e9-9f16-f381afe686f5_optimized](https://user-images.githubusercontent.com/49100982/108255736-b4957600-716d-11eb-848a-f4b9a83a58c7.jpg)
![62966496-77795680-be07-11e9-9985-4d813573fdd6_optimized](https://user-images.githubusercontent.com/49100982/108255738-b4957600-716d-11eb-8dea-87c1764d7e35.jpg)
![62966497-77795680-be07-11e9-9ffe-73b34b4b14a2_optimized](https://user-images.githubusercontent.com/49100982/108255740-b52e0c80-716d-11eb-8645-d1ed285204f9.jpg)
![62966498-77795680-be07-11e9-8a25-e728a89e7981_optimized](https://user-images.githubusercontent.com/49100982/108255742-b52e0c80-716d-11eb-8ea1-8a6aa361fe96.jpg)
![62966499-77795680-be07-11e9-98b0-e3e9ab9cdff9_optimized](https://user-images.githubusercontent.com/49100982/108255743-b5c6a300-716d-11eb-9f64-185f288c1364.jpg)
![62966500-77795680-be07-11e9-89af-905723509f87_optimized](https://user-images.githubusercontent.com/49100982/108255747-b65f3980-716d-11eb-8e12-1ce6cf4d009f.jpg)
![62966501-7811ed00-be07-11e9-9a0a-37cc64cf7e54_optimized](https://user-images.githubusercontent.com/49100982/108255750-b65f3980-716d-11eb-9dfc-620748a03844.jpg)
![62966502-7811ed00-be07-11e9-8348-5de10312557b_optimized](https://user-images.githubusercontent.com/49100982/108255752-b6f7d000-716d-11eb-8415-3d5d18839646.jpg)
![62966503-7811ed00-be07-11e9-9d86-2f26d90155ab_optimized](https://user-images.githubusercontent.com/49100982/108255753-b6f7d000-716d-11eb-96b7-7448b890a583.jpg)
![62966504-7811ed00-be07-11e9-81a2-2df843640210_optimized](https://user-images.githubusercontent.com/49100982/108255754-b7906680-716d-11eb-9e70-4d79fdd62a2a.jpg)
![62966505-7811ed00-be07-11e9-965b-6cef987101d0_optimized](https://user-images.githubusercontent.com/49100982/108255755-b828fd00-716d-11eb-8dee-2d981777a2b3.jpg)
![62966506-78aa8380-be07-11e9-80e2-67931ebe397a_optimized](https://user-images.githubusercontent.com/49100982/108255759-b828fd00-716d-11eb-8951-0af2c0ac1297.jpg)
![62966507-78aa8380-be07-11e9-91f5-a9ebae6bd88e_optimized](https://user-images.githubusercontent.com/49100982/108255761-b8c19380-716d-11eb-8c73-02da22b53021.jpg)
![62966509-78aa8380-be07-11e9-903f-5bd3cd836d21_optimized](https://user-images.githubusercontent.com/49100982/108255762-b8c19380-716d-11eb-8ab2-de382c6dd78e.jpg)
![62966510-78aa8380-be07-11e9-9e27-f77fcde6bae2_optimized](https://user-images.githubusercontent.com/49100982/108255766-b95a2a00-716d-11eb-905e-bad027eacc41.jpg)
![62967268-ec995b80-be08-11e9-9b86-bf3d728dd9fa_optimized](https://user-images.githubusercontent.com/49100982/108255767-b95a2a00-716d-11eb-9750-41c3b6036529.jpg)
![62967270-ec995b80-be08-11e9-87df-9096ba428583_optimized](https://user-images.githubusercontent.com/49100982/108255770-b9f2c080-716d-11eb-8e79-068a5ed7ee7a.jpg)
![62967271-ec995b80-be08-11e9-9d49-efe6d6a677a8_optimized](https://user-images.githubusercontent.com/49100982/108255772-ba8b5700-716d-11eb-99cc-53d05b5bf20c.jpg)
![62967272-ec995b80-be08-11e9-9ac5-8fd135a74248_optimized](https://user-images.githubusercontent.com/49100982/108255774-ba8b5700-716d-11eb-80f2-213a9932fb0a.jpg)
![62967273-ec995b80-be08-11e9-9349-8d910a629227_optimized](https://user-images.githubusercontent.com/49100982/108255775-bb23ed80-716d-11eb-9ec4-ea00690300bb.jpg)
![62967441-3eda7c80-be09-11e9-9c4d-1cae5871e000_optimized](https://user-images.githubusercontent.com/49100982/108255776-bb23ed80-716d-11eb-9ada-24b61a3d4afe.jpg)
![62967478-54e83d00-be09-11e9-849c-ed463ac9b0dd_optimized](https://user-images.githubusercontent.com/49100982/108255779-bbbc8400-716d-11eb-98e9-3d0993efe2c3.jpg)
![62967479-54e83d00-be09-11e9-8905-95a366fe7081_optimized](https://user-images.githubusercontent.com/49100982/108255780-bbbc8400-716d-11eb-83b2-b9a4ba63bdbf.jpg)
![62967480-54e83d00-be09-11e9-8968-e71024c3d03e_optimized](https://user-images.githubusercontent.com/49100982/108255782-bc551a80-716d-11eb-9347-c841028b8c1a.jpg)
![62967481-54e83d00-be09-11e9-94e0-f47139d586a7_optimized](https://user-images.githubusercontent.com/49100982/108255783-bcedb100-716d-11eb-9330-e1d16aeaf994.jpg)
![62967483-54e83d00-be09-11e9-8ccd-b5f376d65b75_optimized](https://user-images.githubusercontent.com/49100982/108255786-bcedb100-716d-11eb-9f4d-540b75cc62c2.jpg)
![62967485-54e83d00-be09-11e9-8646-fd420eba3647_optimized](https://user-images.githubusercontent.com/49100982/108255788-bd864780-716d-11eb-87b1-01cab8ee3f93.jpg)
![62967487-5580d380-be09-11e9-8589-f2e245f4a22e_optimized](https://user-images.githubusercontent.com/49100982/108255792-be1ede00-716d-11eb-8c26-f7ad7ab3c4f2.jpg)
![62967488-5580d380-be09-11e9-9d71-ab15c0742b3e_optimized](https://user-images.githubusercontent.com/49100982/108255796-be1ede00-716d-11eb-8b61-9a419ebe7a4a.jpg)

**Comment by TheTechRobo** [comment]
I asked, how do you not have priveleges to edit wiki? I do. Everyone should have them.

**Comment by airdry** [comment]
I'm sorry I didn't pay attention to this button right away - I was busy with the images themselves. The button is available - I can edit it - but it will take some time to figure out the correspondence of all images and descriptions

**Comment by TheTechRobo** [comment]
How much total is it now?

**Comment by airdry** [comment]
After processing the images take up 13MB

**Comment by TheTechRobo** [comment]
Nice!

**Comment by airdry** [comment]
Update all images in wiki, this issue can close. Now page will be load faster - you can see it

**Comment by TheTechRobo** [comment]
Doesn't feel any faster to me, but that's because of my 3mbps internet, lol.

**Comment by mcornella** [comment]
### Before
![image](https://user-images.githubusercontent.com/1441704/108632140-a1382280-746d-11eb-90f7-6480b35cd8dc.png)

### After
![image](https://user-images.githubusercontent.com/1441704/108632138-9ed5c880-746d-11eb-8732-63e7bdb73222.png)

70MB vs 17MB. Great improvement, thanks!

**Comment by andreasabel** [comment]
Still very slow from the German countryside...  Takes minutes to load.

**Comment by TheTechRobo** [comment]
prolly a github mirror issue?

**Comment by andreasabel** [comment]
Well, download speed is only 0.25MB/sec... neglected countryside...
