### ISSUE TITLE
Git fsck fails

### ISSUE THREAD

**Issue by linus-gates** [ohmyzsh/ohmyzsh#9665]
**Describe the bug**
Git fsck fails which is not place you really want to be in. It can cause future problems.

**To Reproduce**
run `git fsck`

**Expected behavior**
No errors or warnings.

**Screenshots and/or Recordings**
`
Checking object directories: 100% (256/256), done.
warning in tree 2b7227859263b6aabcc28355b0b994995b7148b6: zeroPaddedFilemode: contains zero-padded file modes
warning in tree a18c4d13c2a5fa2d4ecd5346c50e119b999b807d: zeroPaddedFilemode: contains zero-padded file modes
warning in tree 84df066176c8da3fd59b13731a86d90f4f1e5c9d: zeroPaddedFilemode: contains zero-padded file modes
Checking objects: 100% (25839/25839), done.
`

**Possible fixes**
From some research I did, I understand there's no easy fix for this.
A possible option is to fast-export/fast-import

**Desktop (please complete the following information):**

 - OS / Distro: Ubuntu 20.04
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: iTerm2

**Comment by cheriimoya** [comment]
this is a known bug, see #4963 and especially [this answer why there won't be a fix](https://github.com/ohmyzsh/ohmyzsh/issues/5168#issuecomment-226501245).
i am also annoyed by this error, but i guess there really is no easy fix (also looking at the 21.7k forks and local repos that would need to be rebased...)

**Comment by 704KC** [comment]
The error is a no joke imagine two days no solution so far
