### ISSUE TITLE
!! shortcut no longer works properly after installing Oh My Zsh

### ISSUE THREAD

**Issue by evprkr** [ohmyzsh/ohmyzsh#9668]
I use this shortcut frequently when testing scripts and whatnot. Usually, typing `!!` and hitting `Enter` in my prompt will execute the previous command.

After installing Oh My Zsh last night, I noticed that typing `!!` and hitting `Enter` instead expands the `!!` to show what my previous command was, and I have to hit `Enter` a second time to execute the command.

I know this seems super minor, but muscle memory is a pain to overwrite.

Here are my system details:
```
OS: Mac OS 11.2 Big Sur
Chip: M1
Term: iTerm2
```

**Comment by rwmitchell** [comment]
You need to (un)set:

```setopt nohistverify```

It's covered in the manual.  Lots of interesting things to toggle on/off to increase your pleasure.

**Comment by evprkr** [comment]
Ah, took me quite a bit of digging but I found what you were talking about. More details would have been helpful, but you sent me in the right direction.

I can't seem to find a manual other than the wiki, and I can't find any info about setting options on the wiki, so I'm not totally sure what you're talking about.

I did however find the History plugin, which is what I think I need to use that option, but how do I actually set options for a plugin, or modify the plugin itself?

**Comment by michaeltwofish** [comment]
> I can't seem to find a manual other than the wiki, and I can't find any info about setting options on the wiki, so I'm not totally sure what you're talking about.

The manual referred to is the [zsh manual](https://zsh.sourceforge.io/Doc/Release/Options.html). 

> HIST_VERIFY
> Whenever the user enters a line with history expansion, don’t execute the line directly; instead, perform history expansion and reload the line into the editing buffer.
