### ISSUE TITLE
Terminal hangs when doing `java --ver` then hitting TAB twice.

### ISSUE THREAD

**Issue by obtusedev** [ohmyzsh/ohmyzsh#9671]
**Describe the bug**
Doing `java --ver` and hitting TAB twice hangs the terminal on macOS and Linux Mint.

**To Reproduce**
1. type `java --ver` into terminal and hit TAB twice for autocomplete.
2. Terminal hangs.

**Expected behavior**
Terminal should attempt to autocomplete and not hang terminal.

**Desktop (please complete the following information):**

 - OS / Distro: macOS Big Sur 11.2.1, Linux Mint (latest)
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: None

**Comment by rishisy** [comment]
How did you fix this ?????

**Comment by jdecuirm** [comment]
Same issue with Java 21 LTS... How did you solved it?

**Comment by mcornella** [comment]
Check out https://github.com/ohmyzsh/ohmyzsh/issues/2437#issuecomment-32577842. Should still be pretty much applicable today.
