### ISSUE TITLE
command-not-found plugin does not detect correct homebrew prefix

### ISSUE THREAD

**Issue by Mellbourn** [ohmyzsh/ohmyzsh#9673]
https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/command-not-found/command-not-found.plugin.zsh assumes homebrew to be in `/usr/local` but it should probably check `brew --prefix` since it can be set to other paths. In particular, `/opt/homebrew` is becoming common since it is the [recommended path for Apple Silicon](https://docs.brew.sh/Installation)

**Comment by mcornella** [comment]
Fixed in #9797.
