### ISSUE TITLE
How to manage my custom ohmyzsh config including plugins with git?

### ISSUE THREAD

**Issue by wAuner** [ohmyzsh/ohmyzsh#9675]
I find myself often reinstalling my ohmyzsh config with plugins and themes on multiple machines.
Is there a good way how I can manage my custom ready to use installation such that I can still get updates?
Maybe a fork and adding the plugins and themes under custom/ as submodules? Assuming that zsh is already the standard shell on the target machine.

**Comment by mahmoudhossam** [comment]
I think [chezmoi](https://github.com/twpayne/chezmoi/blob/master/docs/QUICKSTART.md) might be helpful to you, assuming you have your dotfiles hosted somewhere you can access over the internet.

**Comment by wAuner** [comment]
@mahmoudhossam thanks. If possible I'd like to stick to standard git. wouldn't it be possible to use submodules and that I can clone my forked (+ added submodules) ohmyzsh-dir and get going?
