### ISSUE TITLE
giving editor permission, non-vim

### ISSUE THREAD

**Issue by MishalAshraf** [ohmyzsh/ohmyzsh#9687]
Ha ha I was doing the same thing until I realize that I forgot to give it an editor command.

$ vim ~/.zshrc

_Originally posted by @patomation in https://github.com/ohmyzsh/ohmyzsh/issues/3291#issuecomment-89832678_

Hello I have basically the same error as this! My question is: 
What happens if I am not using Vim, but another editor like VSC?

**Comment by mcornella** [comment]
You're approaching this wrong: you don't have to give the editor permission, you need to open the file with your editor. For VS Code, that's normally `code <file>`, being code the command to open VS Code.
