### ISSUE TITLE
Autocompletion stop working in alias

### ISSUE THREAD

**Issue by kaldown** [ohmyzsh/ohmyzsh#9693]
Adding `alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'` to `~/.zshrc` disabled autocompletion of files.

No plugins installed.
`plugins=()`

 - OS / Distro: Arch
 - Latest ohmyzsh update?: Yes
 - ZSH Version: zsh 5.8 (x86_64-pc-linux-gnu)
 - Terminal emulator: alacritty 0.7.2 (5ac8060b)

**Comment by mcornella** [comment]
When completing that command I assume? You can turn that into a function instead, otherwise zsh tries to complete it as a git command so it might not work if the completion function doesn't work correctly.

**Comment by kaldown** [comment]
Thanks @mcornella.
But in order to turn it to a function it should be complete command?
Could you please point out to an example of that methodic?

**Comment by mcornella** [comment]
Something like this:
```zsh
dotfiles() {
  git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME "$@"
}
```

You can put this in your zshrc file, after OMZ is sourced. Remember to delete the alias.

**Comment by kaldown** [comment]
Worked like a charm!
Thanks
