### ISSUE TITLE
% sign on emacs vterm

### ISSUE THREAD

**Issue by rm-rf-r00t** [ohmyzsh/ohmyzsh#9694]
i have vterm installed on emacs and using zsh as default on it. but when the vterm is loaded first using zsh there is a % sign on the beginning line. but when I open another vterm , it doesn't have any problem

Steps to reproduce the behavior, for example:
1.install emacs
2.install vterm
3.install zsh
4.open vterm inside emacs

![image](https://user-images.githubusercontent.com/76902855/109408998-e7810a80-79b4-11eb-8829-2dce0a8bc66e.png)

I'm using artix linux and both emacs and the zsh on the latest version

**Comment by mcornella** [comment]
This is a emacs/vterm issue. The same [happens with Hyper terminal](https://github.com/vercel/hyper/issues/2144) (or used to happen). The workaround is to add `unsetopt promptsp` at the top of your zshrc file and reenable it afterwards at the end of the file with `setopt promptsp`.
