### ISSUE TITLE
Not all completion options showing for git?

### ISSUE THREAD

**Issue by josh-byster** [ohmyzsh/ohmyzsh#9695]
My issue seems to be exactly opposite to #7523—I currently have just `git` installed as a plugin, though I tried adding `gitfast` as well and the same happens.
When I type `git c` and press tab, I only get 3 completion settings. I'm wondering why commands such as `cherry-pick` don't appear. The same with `stash` as well. I was expecting it to show as in the above issue, but I'm not sure what I have misconfigured. I did a clean reinstall of OMZ and wiped my zshrc to make sure nothing else I could tell was interfering. 

```
❯ git c
checkout  -- checkout a branch or paths to the working tree
clone     -- clone a repository into a new directory
commit    -- record changes to the repository
```

Any guidance would be much appreciated!

**Comment by mcornella** [comment]
What's the content of your zshrc file? What does `which $_comps[git]` show?

**Comment by josh-byster** [comment]
To get a minimal working example, I removed all but the basics:

```
export ZSH="/Users/joshbyster/.oh-my-zsh"
ZSH_THEME=""
plugins=(git)
source $ZSH/oh-my-zsh.sh
```

```
~ % which $_comps[git]
_git () {
	# undefined
	builtin autoload -XUz
}
```

Running on MacOS Big Sur 11.2.2, iTerm 2 build 3.4.4, OMZ up-to-date:
```
.oh-my-zsh % git log --pretty=format:"%ad" | head -n 1
Sun Feb 21 06:29:54 2021 +0000
```

**Comment by mcornella** [comment]
Post `which $_comps[git]` after trying to complete a git command.

**Comment by dpithon** [comment]
unsubscribe

**Comment by mcornella** [comment]
@dpithon there's an unsubscribe link right in the email shown, writing unsubscribe does nothing.

**Comment by josh-byster** [comment]
Ah, apologies. Here it is (output seems to differ from my other Mac running Catalina and OMZ where it works just fine):

```
_git () {
	local _ret=1
	local cur cword prev
	cur=${words[CURRENT]}
	prev=${words[CURRENT-1]}
	let cword=CURRENT-1
	if (( $+functions[__${service}_zsh_main] ))
	then
		__${service}_zsh_main
	elif (( $+functions[__${service}_main] ))
	then
		emulate ksh -c __${service}_main
	elif (( $+functions[_${service}] ))
	then
		emulate ksh -c _${service}
	elif ((	$+functions[_${service//-/_}] ))
	then
		emulate ksh -c _${service//-/_}
	fi
	let _ret && _default && _ret=0
	return _ret
}
```

**Comment by mcornella** [comment]
Can you post the output of `whence -v _git` after trying to complete a git command?

**Comment by josh-byster** [comment]
@mcornella I think we're very close to figuring this out—I get the following:
```
_git is a shell function from /usr/local/share/zsh/site-functions/_git
```

But it looks like the contents of this `_git` file is the same as the `gitfast` plugin, which I may have installed long ago...however, `gitfast` is no longer a plugin mentioned in my `.zshrc`. Rather, only `git` is mentioned as a plugin in my `.zshrc`.

I tried running different commands such as `rm -rf ~/.zcompdump && compinit` but I can't get it to use the standard OMZ git rather than `gitfast`. I believe it's due to `gitfast` that I'm getting only some completions.

**Comment by mcornella** [comment]
That file must be installed by git. I don't know what system you're using but most with a package manager have a command to verify which package put that there. As a workaround, you can chmod that file to make it unreadable and reset the compdump cache file, and it should pick up the zsh one.

**Comment by josh-byster** [comment]
@mcornella Thank you so much for the support on this—it was a symlink to Homebrew's installation of Git. Uninstalling `git` from Homebrew and defaulting to the default macOS installation by Xcode brought back the autocomplete. Thank you again!

**Comment by felipec** [comment]
@josh-byster By default the git zsh completion shows only common commands, if you want all commands you can do:

```
zstyle ':completion:*:*:git:*' tag-order 'all-commands'
```

**Comment by mrleblanc101** [comment]
I have git suggestions even if i dont load the git plugin for oh-my-zsh. Any idea why ?
On one computer `git che<TAB>` autocomplete as `checkout`. On another it open a menu with `check-attr, cherry-pick, checkout, [...]` and i dont know why.
They both have zsh 5.8, master (ef3f7c4), nearly same config.

<img width="762" alt="Capture d’écran, le 2022-02-15 à 01 22 10" src="https://user-images.githubusercontent.com/17392251/154004326-09baf65f-0ff0-49ec-a6de-07ebb1e379ec.png">

**Comment by mcornella** [comment]
@mrleblanc101 that's zsh-autosuggestions `history` strategy, meaning it takes the suggestion from your previous ran commands. See https://github.com/zsh-users/zsh-autosuggestions#suggestion-strategy for how to change that.

Offtopic.
