### ISSUE TITLE
/usr/local/Cellar/fortune/9708/share/games/fortunes/off: No such file or directory

### ISSUE THREAD

**Issue by dwaxe** [ohmyzsh/ohmyzsh#9698]
I experienced the issue raised [here](https://github.com/ohmyzsh/ohmyzsh/issues/3271), which prompted me to `brew install fortune`.

A new error occurs now, presumably because `brew` [has removed offensive quotes](https://github.com/Homebrew/brew/issues/8811):

```/usr/local/Cellar/fortune/9708/share/games/fortunes/off: No such file or directory```

How can one edit the `adben` to ignore missing quotes?

Reproduction steps (on Mac):
1. Set theme to `adben`
2. Experience error `ps1_fortune:2: command not found: fortune`
3. `brew install fortune`
4. Error `/usr/local/Cellar/fortune/9708/share/games/fortunes/off: No such file or directory`

Ideal scenario:
1. Set theme to `adben`
2. Experience no errors

**Comment by mcornella** [comment]
This is a bug probably in how Homebrew compiled fortune. I don't have that directory and still experience no errors. Still, I'll refactor the adben theme to remove the dependency on fortune if not installed, and on offensive quotes if installed.

**Comment by mcornella** [comment]
#9734 submitted. It doesn't error when `fortune` is missing and it removes the dependency on offensive quotes. Try it out with `omz pr test 9734`.

**Comment by realAbitbol** [comment]
Hi,

Still getting this error as of today after installing fortune and running `fortune -a`

**Comment by BlaineOmega** [comment]
Still getting error as of June 2, 2022

**Comment by mcornella** [comment]
If you're not using the `adben` theme this is not an OMZ error. You should post the error in the Homebrew project or find an open issue and track it there.

**Comment by mcornella** [comment]
The tracker for this issue on Homebrew is at https://github.com/Homebrew/homebrew-core/issues/69672, but it was closed as an upstream bug in fortune.

I've been able to add a workaround, which is to create an empty `off` file and generate the `off.dat` with `strfile`. This code will fix it:
```sh
cd /usr/local/Cellar/fortune/9708/share/games/fortunes
touch off
strfile off off.dat
```

**Comment by marktani** [comment]
FWIW, I fixed my issue by replacing `fortune -a` with `fortune`.
