### ISSUE TITLE
OMZ has broken my look-ahead-typing

### ISSUE THREAD

**Issue by msimerson** [ohmyzsh/ohmyzsh#9699]
**Describe the bug**
When opening a new Terminal, there's sometimes a pause while some background tasks are happening, including I presume a network request by ohmyzsh to see if a new version is available. Prior to ohmyzsh, I would begin typing during this pause knowing that my keystrokes would get queued and then applied properly when the command prompt appeared. Now, because I've been conditioned by ohmyzsh often swallowing my keystrokes with a [Y/n] prompt, I sit pitifully and wait until I see a command prompt before typing. I hate the wait.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable ohmyzsh
2. Use regularly
3. Become conditioned to seeing your keystrokes swallowed

**Expected behavior**
- taste STDIN. If a burst of keystrokes is pending before the [Y/n] prompt is presented, replace the [Y/n] prompt with a "an update is available" notice.
- If the keystrokes aren't a [Y/n], then dismiss the prompt and display a notice that an update is available.

**Desktop (please complete the following information):**

 - OS / Distro: macOS
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: Terminal

**Comment by carlosala** [comment]
HI!
First of all, sorry for the delay in this issue.
This continues to happen?
Thanks!

**Comment by msimerson** [comment]
Yes it does, I had it happen a few days ago when an update was released.

**Comment by carlosala** [comment]
You can disable auto-updates by setting `zstyle ':omz:update' mode disabled` in your `.zshrc` before sourcing `oh-my-zsh.sh` and update manually executing `omz update`

**Comment by carlosala** [comment]
You can also enable auto-updates without prompt confirmation, setting `zstyle ':omz:update' mode auto`

**Comment by mcornella** [comment]
> * taste STDIN. If a burst of keystrokes is pending before the [Y/n] prompt is presented, replace the [Y/n] prompt with a "an update is available" notice.

I'd just like to say that there is an input sink to swallow characters before the prompt: https://github.com/ohmyzsh/ohmyzsh/blob/4ee0cf3cb4c64568430f9af5b1edca2602ab5807/tools/check_for_upgrade.sh#L155-L158

Also, if the answer to the prompt is not Y/N we also show a prompt for how to update.

What we don't do is the last part: just showing that there's an update available without asking anything when there's input before the prompt. That seems like a smart solution.

Of course you can also just have the update reminder by setting
```sh
zstyle ':omz:update' mode reminder
```
in your zshrc file, before OMZ is sourced.
