### ISSUE TITLE
ZSH ignoring DEFAULT_USER in VS Code

### ISSUE THREAD

**Issue by jessdwitch** [ohmyzsh/ohmyzsh#9701]
**Describe the bug**
After the most recent ZSH update, ZSH is ignoring my DEFAULT_USER setting and displaying the `user@host` at the beginning of each prompt in the VS Code integrated terminal. In .zshrc, I have tried:

* `DEFAULT_USER="jessica"` (what I had and was working before)
* ``DEFAULT_USER=`whoami` ``
* `DEFAULT_USER=$(whoami)`

All of them still display the `user@host`, and my host is pretty long making it a pain to use. I have confirmed that the environment variable is set and correct with `ECHO $DEFAULT_USER`. To be clear, this setting is still working in my basic terminal, but not in the integrated VS Code terminal (which is was before).

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Set DEFAULT_USER in .zshrc
2. Start a new terminal
3. `user@host` is displayed at the beginning of every line.

**Expected behavior**
The `user@host` should not be displayed when the user matches `DEFAULT_USER`

**Self Check**

I have searched for existing bugs regarding this, but they seem to be about unset `DEFAULT_USER`, and weren't working previously.

**Desktop (please complete the following information):**

 - OS / Distro: macOS (Catalina)
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: VS Code Integrated Terminal

**Comment by mcornella** [comment]
I presume you're running agnoster but it'd help being sure of that (also that it's the one from this project).

If it's our agnoster, the `prompt_context` function will print on two conditions:

1. `$USER` != `$DEFAULT_USER`
2. `$SSH_CLIENT` is not empty

So check both of those conditions and let me know. If you really want to nuke this, you can also override the `prompt_context` with an empty body like so:
```zsh
prompt_context(){}
```

**Comment by jessdwitch** [comment]
I am using y'all's version of Agnoster. It looks like its option 1: `$USER` isn't set in the VSCode terminal for some reason and when I try to force it with `export USER=jessica` the prompt drops the name as expected. I can have it populate that environment variable when it instantiates a new terminal, but I'm curious if you've got any ideas why that might suddenly be empty?

**Comment by mcornella** [comment]
Hmm I thought `$USER` was set by zsh but it turns out [it's `$USERNAME`](http://zsh.sourceforge.net/Doc/Release/Parameters.html#index-USERNAME). Does that exist in vsc?

**Comment by jessdwitch** [comment]
Ya, `$USERNAME` exists and is correctly set.

**Comment by mcornella** [comment]
Apologies for the delay. It should work correctly now after `omz update`.

**Comment by jessdwitch** [comment]
This got lost in my notifs, but after taking my cludge out, things are working correctly once more 😄

**Comment by robbyrussell** [comment]
@jessdwitch yay!
