### ISSUE TITLE
Latest dotnet core version/path renders oddly in macos terminal

### ISSUE THREAD

**Issue by wonbyte** [ohmyzsh/ohmyzsh#9705]
**Describe the bug**
The latest version of `dotnet` sdk displays odd spacing between the version number and binary path in `oh-my-zsh` terminal

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Download the latest `dotnet sdk - 5.0.200`
2. cd into a `dotnet` project
3. See issue / odd spacing being rendered

**Expected behavior**
The terminal should display with the path next to the version.

**Screenshots and/or Recordings**
<img width="731" alt="Screen Shot 2021-03-03 at 11 59 54 AM" src="https://user-images.githubusercontent.com/681965/109850314-fb787680-7c17-11eb-88fa-ccecf99ec92f.png">

`Node/NVM` works fine.

<img width="817" alt="Screen Shot 2021-03-03 at 12 29 19 PM" src="https://user-images.githubusercontent.com/681965/109854008-28c72380-7c1c-11eb-912a-4a2e92c15a71.png">

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro:  MacOS 10.15.7
 - Latest ohmyzsh update?: up to date
 - ZSH Version: [e.g. 5.6] 5.8_1
 - Terminal emulator: Default MacOS

**Additional context**
`.zshrc` settings using defaults for all plugins

```
source /usr/local/share/antigen/antigen.zsh	

# Load the oh-my-zsh's library.	
antigen use oh-my-zsh	

# Load the theme	
antigen theme https://github.com/denysdovhan/spaceship-prompt spaceship	

# Bundles from the default repo (robbyrussell's oh-my-zsh).	
antigen bundle git	
antigen bundle nvm	

# Autoload nvmrc	
antigen bundle Sparragus/zsh-auto-nvm-use	

# Bundles from zsh-users	
antigen bundle zsh-users/zsh-syntax-highlighting	
antigen bundle zsh-users/zsh-history-substring-search	
antigen bundle zsh-users/zsh-autosuggestions	

# Tell Antigen that you're done.	
antigen apply

# Custom
alias clr='clear'	
alias hist='history 1 | less'	
alias vi='vim'	
```

**Comment by mcornella** [comment]
This is a spaceship-prompt issue. Looks like [they run `dotnet --version`](https://github.com/denysdovhan/spaceship-prompt/blob/master/sections/dotnet.zsh#L33) so that should be parsed further to only get the version string.
