### ISSUE TITLE
add command for pruning local branches that have been merged

### ISSUE THREAD

**Issue by BigMichi1** [ohmyzsh/ohmyzsh#9710]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
`git`

**Is your feature request related to a problem? Please describe.**
when I'm working on a lot of branches my local git copy contains a lot of already merged branches which I need to clean manually

**Describe the solution you'd like**
i would like to propose a "gbp" command which removes all already merged branches

**Describe alternatives you've considered**
currently, I'm using this inside my global `.gitconfig`
```
[alias]
	branch-prune = "!git fetch -p && for b in $(git for-each-ref --format='%(if:equals=[gone])%(upstream:track)%(then)%(refname:short)%(end)' refs/heads); do git branch -d $b; done"
```

**Additional context**
the command removes all branches that are merged and do not contain additional changes locally

**Related Issues**
None

**Comment by robbyrussell** [comment]
Think this was referenced in #9973
