### ISSUE TITLE
Update on Transfer Plugin

### ISSUE THREAD

**Issue by luizfelipevbll** [ohmyzsh/ohmyzsh#9712]
Hello devs, encryptation auth on files could be implemented on the [transfer plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/transfer).

The encrypted upload is already enabled on the transfer.sh project
https://github.com/dutchcoders/transfer.sh/#encrypt--upload

### Encrypt & upload:
```bash
$ cat /tmp/hello.txt|gpg -ac -o-|curl -X PUT --upload-file "-" https://transfer.sh/test.txt
````

Thanks for your attention ;)

**Comment by mcornella** [comment]
Can you make a PR for it?

**Comment by luizfelipevbll** [comment]
> Can you make a PR for it?

Shure, I just did it,
https://github.com/ohmyzsh/ohmyzsh/pull/9739
