### ISSUE TITLE
Run *.sh file has if statement in oh my zsh has error

### ISSUE THREAD

**Issue by TranBaNgoc** [ohmyzsh/ohmyzsh#9716]
Hi everyone,
I am using oh my zsh and has a .sh file below 
```
cover="-coverprofile=cover -coverpkg=./handlers"

export BOOKING_SERVICE_CONFIG="../config"

case $1 in

  "1")

    if [[ -z $2 ]] ;

    then

      go test -v ./testing ${cover}/airConditioner -run Booking_AirConditioner

    else

      go test -v ./testing ${cover}/airConditioner -run Booking_AirConditioner/^$2$

    fi

    ;;

  *)

    go test -v ./testing ${cover}/... -timeout 1h

    ;;

esac
```

When i ran command "./test.sh 1", I received error "./test.sh: 5: ./test.sh: [[: not found"

How can i fix this with oh my zsh?

Thank you!

**Comment by mcornella** [comment]
You need to add a shebang to run the script with zsh, i.e. put this at the top:
```sh
#!/usr/bin/env zsh
```

**Comment by rwmitchell** [comment]
His issue is that the if is checking $2 but he only provided one arg.
The fact he doesn't understand where he should be asking for help in scripting (OMZ is just a collection of tools, not a language and hence this is completely off topic) shows he lacks basic understanding of what he's doing.

**Comment by mcornella** [comment]
Too clarify the previous deleted comment: `[[` is not posix compatible (it's available in bash and zsh). When you run without a shebang (the `#!` line at the first line of the file) the default shell is `sh` which doesn't have that, only `[`.
