### ISSUE TITLE
add a golang alias to recursively test directory

### ISSUE THREAD

**Issue by eng618** [ohmyzsh/ohmyzsh#9719]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
The name of the plugin, theme or alias that you would like us to improve. [...]

golang plugin

**Is your feature request related to a problem? Please describe.**
A description of what the problem is. Ex. I'm always frustrated when [...]

No problem, just enhanced functionality

**Describe the solution you'd like**
A description of what you want to happen. [...]

add an alias for `gota` (go test all) `go test ./...`. 

Similar to how `fmt` has a base `gof` (`go fmt`) and `gofa` (`go fmt ./...`)

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered. This can also include other plugins or themes.

Simply add the alias local to my environment.

**Additional context**
Add any other context, screenshots or discord conversations about the feature request here. Also if you have any PRs related to this issue that are already open that you would like us to look at.

Opened PR: https://github.com/ohmyzsh/ohmyzsh/pull/9720

**Comment by mcornella** [comment]
Fixed in https://github.com/ohmyzsh/ohmyzsh/pull/8974.
