### ISSUE TITLE
cheat or Podman completion do not work

### ISSUE THREAD

**Issue by ChangheeOh** [ohmyzsh/ohmyzsh#9721]
**Describe the bug**

Some of zsh completion do not work on oh-my-zsh. (e.g. cheat, podman)
But other completion work properly on oh-my-zsh. (e.g. git)

**To Reproduce**
1. Install formulae as bellow
```
  $ brew install cheat
  $ brew install podman
```
2. Check whether auto completion work and do not work properly (Display not command options but the file list or current directory)
```
  $ cheat <TAB>
  Applications/       Documents/          Library/            Music/              Public/              ... (omitted) ...
  Desktop/            Downloads/          Movies/             Pictures/             ... (omitted) ...
  $ podman <TAB>
  Applications/       Documents/          Library/            Music/              Public/              ... (omitted) ...
  Desktop/            Downloads/          Movies/             Pictures/             ... (omitted) ...
```
**Expected behavior**
After I switch back to  original `.zshrc `, completion work perfectly as bellow

1. Switch to old `.zshrc.pre-oh-my-zsh`
```
  $ cp .zshrc.pre-oh-my-zsh .zshrc
```
2.  Check auto completion again and work perfectly
```
  $ cheat <TAB>
  zsh: do you wish to see all 215 possibilities (17 lines)?
  
  $ podman <TAB>
  attach       -- Attach to a running container
  build        -- Build an image using instructions from Containerfiles
  commit       -- Create new image based on the changed container
  container    -- Manage containers
  ... (omitted) ...
```
**Screenshots and/or Recordings**
You can also record an asciinema session: https://asciinema.org/

1) For completion error: https://asciinema.org/a/398039
2) For completion success: https://asciinema.org/a/398040

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? No

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro: `MacOS`/`Big Sur 11.2.2` (M1 Mac)
 - Latest ohmyzsh update?: Yes
 - ZSH Version: `zsh 5.8` (x86_64-apple-darwin20.0)
 - Terminal emulator: `iTerm2`, `Terminal` (Apple)

**Additional context**

If I add the following script line in `.zshrc`, I could successfully get things done on oh-my-zsh, too.
But I'm not sure this is proper way. Because the similar script line already executed in 'oh-my-zsh.sh'.

`autoload -U +X compinit; compinit`

**Comment by tomajask** [comment]
@ChangheeOh have you resolved this issue? I'm having a similar problem on my M1 Macbook. Autocompletion doesn't work, it just lists directories instead of commands.

Thanks in advance for any tips.

**Comment by ChangheeOh** [comment]
> @ChangheeOh have you resolved this issue? I'm having a similar problem on my M1 Macbook. Autocompletion doesn't work, it just lists directories instead of commands.
> 
> Thanks in advance for any tips.

As I mentioned above, I have added the following command in .zshrc to temporarily resolve this issue.
`autoload -U +X compinit; compinit`

**Comment by tomajask** [comment]
Thanks @ChangheeOh for quick response! I tried it, but it didn't work. What worked for me is adding following part to the `.zshrc`:
```shell
if type brew &>/dev/null && [[ `sysctl -n machdep.cpu.brand_string` =~ 'Apple M1' ]]
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi
```
after this:
```shell
autoload -Uz compinit; compinit
```
☝🏼 Homebrew is installed in a different directory on M1 computers so this part was missing to read completions.

**Comment by maxbrunet** [comment]
The reason: https://github.com/ohmyzsh/ohmyzsh/issues/10412#issuecomment-967029981
