### ISSUE TITLE
uninstall_oh_my_zsh doesn't work

### ISSUE THREAD

**Issue by hyejooLim** [ohmyzsh/ohmyzsh#9727]
I want to remove oh_my_zsh.
but uninstall_oh_my_zsh instruction does not work in my terminal (iterm2).

what is the correct instruction?

I can not find answer.

**Comment by rwmitchell** [comment]
How did it fail?

**Comment by rwmitchell** [comment]
Someone is going to find this in a similar search and never know how it was solved.

**Comment by hyejooLim** [comment]
Sorry, I found a solution.
1. Enter the "Finder" application and open hidden files. (shift + command + .)
2. You can see the oh_my_zsh folder.
3. Remove oh_my_zsh folder.
