### ISSUE TITLE
Escape key functions as alt

### ISSUE THREAD

**Issue by MrNilDev** [ohmyzsh/ohmyzsh#9731]
Hello, i'm using zsh with oh-my-zsh installed. this is weird, whenever I press escape and another key like `l` it will become alt + `l`. how can i disable it? 

I'm using Arch btw.

**Comment by mcornella** [comment]
That's the normal key sequence behavior, I don't think it can be changed.

**Comment by MrNilDev** [comment]
Normal key squence? But that's just for zsh, it works as expected in bash, fish...

**Comment by mcornella** [comment]
If you press [CTRL+V in bash](https://www.computerhope.com/unix/bash/bind.htm#keycodes) and press the same combination using either Esc and Alt you'll get the same sequence. For example, Alt+l gives me `^[l` and the same for Esc+l. In fact, you can test both of those combinations on an uppercase word and see that both change it to lowercase.

**Comment by MrNilDev** [comment]
That's right, but is there any way that i can disable it?

**Comment by mcornella** [comment]
I don't think so, unless your terminal emulator has such a setting. But I've never seen it.

**Comment by MrNilDev** [comment]
I use kitty terminal emulator. Does it support it ?

**Comment by mcornella** [comment]
I have no idea, [look up the docs](https://sw.kovidgoyal.net/kitty/conf.html#keyboard-shortcuts) maybe you find it. I'll close this as not OMZ-related.
