### ISSUE TITLE
Unable to omz update due to unknown option --interactive in vim

### ISSUE THREAD

**Issue by assist726** [ohmyzsh/ohmyzsh#9737]
```
❯ omz update
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan  4 2021 19:10:05)
Unknown option argument: "--interactive"
More info with: "vim -h"
```

I am on the latest version of vim installed from homebrew on MacOS but unclear why the --interactive option is unknown. Did previously have success running omz update on older versions of Vim

**Comment by mcornella** [comment]
Can you provide more information about how you're running it? vim shouldn't have anything to do with `omz update`. Are you running this from inside vim?

**Comment by toienMT** [comment]
I'm getting the same error. I'm running it in my iTerm window.
<img width="483" alt="image" src="https://user-images.githubusercontent.com/59892861/150242967-e45dc3f1-4de7-4e8c-8f2e-31b5ae76de0a.png">

**Comment by mcornella** [comment]
Can you provide a reproducible case as to how you run `omz update`? Is this run inside vim, or just on a normal terminal session?

**Comment by toienMT** [comment]
Just right in the terminal.
- Open terminal
- enter omz update or oh my zsh asks to update and get it too.
- get error

**Comment by mcornella** [comment]
Can you run `functions -t _omz::update`, and then try `omz update`, so it generates a trace, and post it here so I can take a look?

**Comment by toienMT** [comment]
▶ omz update
+_omz::update:1> cd /Users/toien/.oh-my-zsh
+_omz::update:1> git rev-parse HEAD
+_omz::update:1> local last_commit=fe04acd97ccf60b869eb105d8b76fbfed607a90a
+_omz::update:4> [[ '' != --unattended ]]
+_omz::update:5> ZSH=/Users/toien/.oh-my-zsh vi /Users/toien/.zshrc -f /Users/toien/.oh-my-zsh/tools/upgrade.sh --interactive
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 30 2021 06:51:40)
Unknown option argument: "--interactive"
More info with: "vim -h"
+_omz::update:5> return 1

**Comment by mcornella** [comment]
Have you aliased `zsh` to `vi ~/.zshrc`?

**Comment by toienMT** [comment]
Yes, I have created alias for 
- zsh='vi ~/.zshrc'
- szsh='source ~/.zshrc'

**Comment by mcornella** [comment]
I've updated the CLI functions to use `command zsh` so the alias is not triggered. Even so, using the name `zsh` for the alias is a very bad choice and will bring you many other problems in the future. I'd suggest using `zshrc` instead.

Also, do not use `source ~/.zshrc` since it can have side-effects. Instead use `exec zsh` or `omz reload`.

**Comment by toienMT** [comment]
ok thank you very much. Are `exec zsh` and `omz reload` build in to reload the `~/.zshrc` file?

**Comment by mcornella** [comment]
Exactly that yes. Use `omz reload` for extra protection.

**Comment by toienMT** [comment]
Thanks just ran `omz reload` and it worked. I did removed the 2 alias from my `~/.zshrc` file.

**Comment by mcornella** [comment]
You can rename the alias to something different than `zsh`. `zshrc` is a good alternative.

**Comment by assist726** [comment]
> You can rename the alias to something different than `zsh`. `zshrc` is a good alternative.

Thanks indeed it was due to the alias, all good now!
