### ISSUE TITLE
Issue in using theme when they are in their own folder in custom theme directory

### ISSUE THREAD

**Issue by TimeMuffins** [ohmyzsh/ohmyzsh#9738]
When trying to use a custom theme [powerlevel10k](https://github.com/romkatv/powerlevel10k), I ran into a problem where oh-my-zsh was throwing me errors saying couldn't find the theme.
`/Users/timemuffin/.oh-my-zsh/oh-my-zsh.sh:source:128: no such file or directory: /Users/timemuffin/.oh-my-zsh/themes/powerlevel10k.zsh-theme`
On checking the oh-my-zsh.sh script I noticed the condition written to handle custom themes only looked for zsh-theme file in the custom/themes directory but if the theme comes in its own folder there was no way to handle that.
`/Users/timemuffin/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme`
I just added one more condition to check for the theme in `$ZSH_CUSTOM/themes/$ZSH_THEME/$ZSH_THEME.zsh-theme` to the existing condition and the theme worked as expected.
```
elif [ -f "$ZSH_CUSTOM/themes/$ZSH_THEME/$ZSH_THEME.zsh-theme" ]; then
    source "$ZSH_CUSTOM/themes/$ZSH_THEME/$ZSH_THEME.zsh-theme"
```

**Comment by TimeMuffins** [comment]
I've created a [pull request](https://github.com/ohmyzsh/ohmyzsh/pull/9740) with the solution of this issue.

**Comment by mcornella** [comment]
In that case you need to set the `ZSH_THEME` variable to `folder/name`. You can see that when running `omz theme list`. That is way more flexible than adding a check to look in a folder of the same name.

```zsh
ZSH_THEME=powerlevel10k/powerlevel10k
```

That is so common in fact that [it is documented in p10k's README](https://github.com/romkatv/powerlevel10k#oh-my-zsh).
