### ISSUE TITLE
Where is the location of 'src' which I use to compile .zshrc when I update certain dot files?

### ISSUE THREAD

**Issue by josaladino2** [ohmyzsh/ohmyzsh#9757]
This is not a big problem, but I have been using 'src' to compile my .zshrc for sometime and I have no clue where it comes from or where it resides on my machine.  Can someopne enlighten me on where it comes from and where it is on the disk?  I can do a which src and I see the code but again, no ideal where is comes from or what plugin, if any, it is associated with.

Thanks for your help
Joe
joe@bram.net

**Comment by rwmitchell** [comment]
What code do you see?  I don’t have ‘src’. 

I do have ‘source’. It is a zsh built in command for loading a script, but it doesn’t ‘recompile’ it.

**Comment by mcornella** [comment]
It's the zsh_reload plugin.

**Comment by rwmitchell** [comment]
Fastest way to get a response is post the wrong information.  I learned something new.
It is defined in: ```.oh-my-zsh/plugins/zsh_reload/zsh_reload.plugin.zsh```
