### ISSUE TITLE
I have to source ~/.zshrc every time

### ISSUE THREAD

**Issue by wangliang1989** [ohmyzsh/ohmyzsh#9758]
I am on a new Apple M1.
The default shell is zsh. and I use the system's terminal.
I install zsh, following:
````
wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
sh install.sh
````
I found that I have to source ~/.zshrc every time. Certainly, I know I should source after editing the zshrc. But, even after restart the computer, I still have to source the zshrc again. For example, I install a new program and add its path into zshrc. And source the zshrc. But, when I open a new shell or restart the computer, I still need to source to make the new program can be found.

English is not my native language.

**Comment by adriandmitroca** [comment]
Could you share what was the issue?

**Comment by wangliang1989** [comment]
> Could you share what was the issue?

Sorry, I forgot that. I closed it by myself, so I think maybe it's just my mistake.
