### ISSUE TITLE
When copying a file, the tab auto-complete should offer the same name as the source file

### ISSUE THREAD

**Issue by njlr** [ohmyzsh/ohmyzsh#9777]
**Describe the solution you'd like**

Suppose I am in `/abc/def` and I want to copy `/xyz/hello.txt` to `/abc/def/hello.txt`:

```bash
$ pwd
/abc/def

$ cp /xyz/hello.txt hello.txt
```

I need to type out the full name `hello.txt`. 

Since this is a common use-case, it would be great if tab auto-complete could provide `hello.txt`:

```
$ cp /xyz/hello.txt h

(press tab)

$ cp /xyz/hello.txt hello.txt
```

**Comment by rwmitchell** [comment]
It is not common usage. Just use a period for the destination and cp will do the right thing.

**Comment by mcornella** [comment]
Exactly, when you pass in only the directory cp uses the same filename.
