### ISSUE TITLE
Tab Completion Menu Causes Incorrect Command Coloring

### ISSUE THREAD

**Issue by jrphill5** [ohmyzsh/ohmyzsh#9778]
**Describe the bug**
Color of command (after $PS1 prompt) including tab completed files and directories is incorrect when tab completion menu is used.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Use gentoo theme and git plugin (may or may not actually matter)
2. Start typing a command like `ls ` (assuming more than one entry will be available) and hit tab
3. When one of the autocomplete menu items is a directory, the entire command turns blue

**Expected behavior**
In previous versions of ohmyzsh, this should result in a colored PS1, but a white command regardless of autocomplete menu selection

**Screenshots and/or Recordings**
Screenshot available here: https://snipboard.io/iOVh8Z.jpg
First command was `ls test` and then hit tab (which worked correctly because there was only one option)
Second command was `ls te` and then hit tab (which failed because there were multiple options with a directory)

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)?
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

No, this was working fine until a recent update.

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

Searched, but did not see similar issue reported.

**Desktop (please complete the following information):**

 - OS / Distro: Ubuntu
 - If on Windows what version of WSL: N/A
 - Latest ohmyzsh update?: Yes
 - ZSH Version: commit 2d40b562e5da4c885babc1f7f09aa33a8a891eb2
 - Terminal emulator: GNOME Terminal (TERM=xterm-256color)

**Additional context**
Add any other context about the problem here. This can be themes, plugins, custom configs.

Using gentoo theme and git plugin.

**Comment by tjakobsen90** [comment]
I have the same issue.
