### ISSUE TITLE
profile unmatched

### ISSUE THREAD

**Issue by ewelinaewela** [ohmyzsh/ohmyzsh#9806]
Hi,

I see the following message when I open my Terminal (Mac, Big Sur):

/Users/.../.zprofile:6: unmatched '

could not find the solution for zprofile:6: unmatched ' anywhere

Does anybody know what is the reason of this problem?

**Comment by mcornella** [comment]
This is not an Oh My Zsh bug. You have an open quote in the .profile file in your home directory. Look it up and post the file contents if you can't find it.

**Comment by ewelinaewela** [comment]
Thank you! I do not see any .profile file in my home directory.

This is the contect of my  ~/.zprofile when I open it from Terminal:

export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile
(/opt/homebrew/bin/brew shellenv)

sudo vi /etc/paths

**Comment by mcornella** [comment]
You have an extra quote after `:$PATH"`. It's easy to overlook. You can't see the file from outside the terminal because files starting with a dot are hidden by default.

**Comment by mcornella** [comment]
BTW the `>> ~/.bash_profile` part will keep adding empty lines to the `.bash_profile` file every time you open a terminal, so you need to remove it.

**Comment by ewelinaewela** [comment]
Thank you!

        I have modified my ~/.zprofile:

export PATH="/usr/local/bin:$PATH" 
(/opt/homebrew/bin/brew shellenv)

sudo vi /etc/paths

        but now when I open the Terminal, I see this:

Last login: Sun Apr 11 18:38:05 on ttys000
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
Password:

        when I give the password, I get the below and cannot do anything else in Terminal

/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/opt/homebrew/bin
/opt/homebrew/bin/brew shellenv

~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
"/etc/paths" 8L, 96C

**Comment by rwmitchell** [comment]
Remove the sudo vi line.

**Comment by ewelinaewela** [comment]
Wonderful! 

I see now the message below when I open the Terminal and all works

```

Last login: Sun Apr 11 19:03:40 on ttys000
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
(base) \h:\W \u$ 
```

Thank you, much appreciated
