### ISSUE TITLE
emotty theme command not found

### ISSUE THREAD

**Issue by ExtremTechniker** [ohmyzsh/ohmyzsh#9811]
**Describe the bug**
When unsing the theme `emotty` there is an error because the command emotty not found

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this theme 'emotty'
3. See error

**Expected behavior**
The theme should be loaded

**Screenshots and/or Recordings**
![Bildschirmfoto 2021-04-11 um 22 31 22](https://user-images.githubusercontent.com/34032662/114320312-b0eef180-9b15-11eb-9d32-3b0b04f538ac.png)

**Desktop (please complete the following information):**

 - OS / Distro: macOS 11.2.3
 - Latest ohmyzsh update?: YES - commit `e9f805a`
 - ZSH Version: ---
 - Terminal emulator: Standard macOS Terminal

**Comment by mcornella** [comment]
The `emotty` theme needs the `emotty` plugin as well.

**Comment by Palladiawa** [comment]
same problem here, there is already a emotty dir in the dir plugins. Don't know the solution either.

**Comment by mcornella** [comment]
> same problem here, there is already a emotty dir in the dir plugins. Don't know the solution either.

You need to enable the emotty plugin.

**Comment by daniel-souza** [comment]
@mcornella but the first step is to enable the emotty plugin. Next, after ```source .\zshrc``` this message appears as not found.

What do you mean when you said to enable the emotty plugin, is there a different procedure?
