### ISSUE TITLE
VIPRE Endpoint: Trojan Detected

### ISSUE THREAD

**Issue by zgjimgjonbalaj** [ohmyzsh/ohmyzsh#9816]
**Describe the bug**
Started an iTerm2 instance on my mac this morning, got a prompt to update ohmyzsh, hit enter and my company's virus detector (VIPRE Endrpoint Security) threw a warning and quarantined an install.sh file. This action resulted in an update failure asking to try again. I have not tried again and most likely will not until I am able to figure out where the issue is. I know I have updated ohmyzsh before without any problems so a bit concerning that the latest update caused the endpoint to quarantine the install.sh file located at `~/.oh-my-zsh/tools/install.sh`.

The name of the potential virus appears to be a generic flag with the name Trojan.GenericKD.36677534

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Have VIPRE Endpoint Security installed (Version 11.0.28 (404) Def. 7.88185
2. Update ohmyzsh
3. See error

**Expected behavior**
To have ohmyzsh update without issues as before.

**Screenshots and/or Recordings**
![image](https://user-images.githubusercontent.com/60440190/114364249-350d9d00-9b47-11eb-8bc2-63fa2567411c.png)

**Desktop (please complete the following information):**

 - OS / Distro: macOS Catalina 10.15.7
 - Latest ohmyzsh update?: Updated until Fri April 9th, 2021. Update failed on Mon April 12th, 2021
 - ZSH Version: 5.7.1
 - Terminal emulator: iTerm2 Build 3.4.4

**Comment by GabrielFlorentin** [comment]
I also found this just now but in my case the Trojan was detected by Bitdefender.

**Comment by niallfleming** [comment]
Me too, bitdefender, I just posted in #q-a on discord about it, appears to be limited to install.sh, looking through install.sh on g-h I can't see anything worrying, and I can't actually see the contents of the file on my mac because bitdefender deletes it on access.
![Screenshot_2021-04-12_at_10 58 45](https://user-images.githubusercontent.com/2081905/114377942-1deaa180-9b7f-11eb-8612-6d71cc93fad9.png)

**Comment by rwmitchell** [comment]
Can you download just install.sh directly from GitHub and try that?  You can see that file and know it is ok.

**Comment by rwmitchell** [comment]
Can you recover the deleted file from TimeMachine and look at it there?

**Comment by zgjimgjonbalaj** [comment]
@rwmitchell 

I did a `git pull && git restore tools/install.sh` and VIPRE again quarantined the file. 
![image](https://user-images.githubusercontent.com/60440190/114381869-a9513c00-9b59-11eb-90d2-7a720a23c4f4.png)

**Comment by rwmitchell** [comment]
Download the file directly from: ```https://github.com/ohmyzsh/ohmyzsh/blob/master/tools/install.sh```
You can preview that file and verify it looks ok.  Copy it into place, without running anything else.
If VIPRE tags it gain, you'll know it is a false positive.   If it doesn't, then something is changing it from what is on the repo.

**Comment by niallfleming** [comment]
@rwmitchell it was identical. 

However bitdefender just updated again and the problem went away. So assuming the same for VIPRE I think this could be closed.

Can you confirm @zgjimgjonbalaj ?

**Comment by zgjimgjonbalaj** [comment]
@niallfleming @rwmitchell 

VIPRE has been updated but getting the same result 
![image](https://user-images.githubusercontent.com/60440190/114394332-15876c00-9b69-11eb-9256-2b375d10cf61.png)

![image](https://user-images.githubusercontent.com/60440190/114394377-20420100-9b69-11eb-9d8f-6046faa84fcf.png)

Highly doubt this file is being manipulated somewhere along the line, it does make sense that it's a false positive though. Going to ignore for now.

**Comment by zgjimgjonbalaj** [comment]
Update: So for me the endpoint is locked and doesn't allow me to restore the file, checking in with our IT Help Desk. I have also tried a few times to do git restore but no luck. I will post another update if and when it is resolved.

**Comment by mcornella** [comment]
Can you download a [few different versions of the install.sh script](https://github.com/ohmyzsh/ohmyzsh/commits/master/tools/install.sh) until you get to one that doesn't trigger the warning?

**Comment by mcornella** [comment]
I submitted a false positive request, let's see what they say.

**Comment by mcornella** [comment]
> I submitted a false positive request, let's see what they say.

Still haven't heard back from them, can you try https://github.com/ohmyzsh/ohmyzsh/issues/9816#issuecomment-818589097 to see if we can narrow down the commit at fault?

**Comment by zgjimgjonbalaj** [comment]
Update: My Company's IT team had to whitelist the directory and then we did another git pull -f. This seems to have resolved it, I was again prompted for an updated today and no issues but assuming it had to do with the whitelisting.

**Comment by mcornella** [comment]
Since there was no response I'll close this and mark it as not our issue.
