### ISSUE TITLE
Do NOT share history

### ISSUE THREAD

**Issue by giacgbj** [ohmyzsh/ohmyzsh#9818]
I've already read and tested all the possible combinations of parameters suggested in many tickets found here (e.g.: #2537) but nothing prevents the history to be shared among windows/tabs after closing/reopening iTerm2 on macOS Catalina.

The only way I found (elsewhere) is:
`HISTFILE=~/.zsh-history-${ITERM_SESSION_ID}`

Could this have any drawback?

**Comment by mcornella** [comment]
Not a bug. Post in the appropriate section.
