### ISSUE TITLE
New Git plugin alias to combine gaa and gcam

### ISSUE THREAD

**Issue by eclectic-coding** [ohmyzsh/ohmyzsh#9823]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
Git plugin

**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
I am requesting a new alias for the Git plugin that combines `gaa` and `gcam`.

**Describe alternatives you've considered**
It is true you can easily do the following from the CLI:
`gaa && gcam "My commit message"`

**Additional context**
I am requesting that we consider creating a new alias:
`gam` which combines `gaa` and `gcam`

**Related Issues**
No related issues

**Comment by mcornella** [comment]
That's easily created: `alias gam='gaa && gcam'`. You can put that in your zshrc file.

**Comment by eclectic-coding** [comment]
I agree and I have already done that, just thought it might be a nice addition to the plugin

**Comment by mcornella** [comment]
The git plugin already has a ton of aliases, and there doesn't seem to be demand for this specific alias (also it might encourage mistakes when it adds untracked files that you didn't know were created). Therefore I'm closing this feature request. Thanks

**Comment by iethree** [comment]
I want this!
