### ISSUE TITLE
Docker compose is now part of docker

### ISSUE THREAD

**Issue by OzzyCzech** [ohmyzsh/ohmyzsh#9831]
The Docker CLI now supports the compose command, including most of the docker-compose features and flags, without the need for a separate tool. Here is more about that: https://docs.docker.com/compose/cli-command/

**Is your feature request related to a particular plugin or theme? If so, specify it.**

* [Docker plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/docker) will need autocomplete update.
* Maybe there will be required change [docker-compose plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/docker-compose) also.

**Comment by unikitty37** [comment]
Yes, every time I use one of the aliases defined in the docker-compose plugin, I get that warning now.

Changing the aliases to `docker compose` instead of `docker-compose` will bite people still running old versions of Docker, though; perhaps the plugin should check the Docker version before setting the aliases?

**Comment by tucknology** [comment]
Another option would be to make a separate plugin, maybe called `compose-cli` which would have the new version of the plugin. This avoids breaking existing users running older versions, and is clearer since users must have the compose cli installed in the first place.

**Comment by Ririshi** [comment]
Perhaps this would warrant a separate version of the plugin? One which works with the old version of Docker, and a new one for the new version. Optionally, the older (and currently only existing) plugin could check if the Docker version is new enough to support the new syntax and suggest that the user "upgrades" to the new version of the plugin. Eventually, the old plugin can be removed as more and more people upgrade their Docker installation.

**Comment by omBratteng** [comment]
I think the `docker-compose` should remain a separate until the actual `docker-compose` is depreciated.
But `docker` plugin should get autocomplete for `docker compose`, right now it shows up like this, without any autocomplete.
![image](https://user-images.githubusercontent.com/1681525/123256549-60bae500-d4f1-11eb-9085-da15125f7361.png)

**Comment by johnnymetz** [comment]
What's the purpose of the `*`? It makes autocomplete unusable for `docker compose`.

**Comment by omBratteng** [comment]
@johnnymetz the `\*` appears when I try to tab from `docker compose`

**Comment by johnnymetz** [comment]
@omBratteng yes but why do we need the `\*`? I just see it as a nuisance.

**Comment by mcornella** [comment]
Fixed in c21ff38b8fda0584208ffd697dac0502e2327466, run `omz update` to get the fix.

**Comment by mcornella** [comment]
Regarding updating the Docker completion for `docker compose`, that is something in progress (the upstream project is [currently working on a generic completion generator](https://github.com/docker/cli/pull/3254)), so I'm going to close this until there is a release in the upstream project.
