### ISSUE TITLE
aws plugin acp() is broken for non-mfa profiles

### ISSUE THREAD

**Issue by grimm26** [ohmyzsh/ohmyzsh#9843]
**Describe the bug**
https://github.com/ohmyzsh/ohmyzsh/pull/9426 broke the aws plugin `acp()` function for any profile that does not use mfa with an assumed role (`source_profile` and `role_arn` set in the profile) with no access keys.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. create an awscli profile that sources another profile to assumes another role but does not use mfa.
2. Try to use `acp()` with that profile.

**Expected behavior**
It should use STS to get credentials and a session token from AWS. If you go back to https://github.com/ohmyzsh/ohmyzsh/commit/fc82aff77c14418df33d4d2d8c946d3adf023706, the `acp()` function will work fine for an awscli profile that has a `source_profile` and `role_arn` with no mfa.

**Desktop (please complete the following information):**

 - OS / Distro: macOS
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: iTerm2

**Comment by mcornella** [comment]
cc @maksyms

**Comment by maksyms** [comment]
@grimm26 thanks for the report. Could you please help me understand this better by sharing the (anonymised) `~/.aws/config so I could understand the whole thing?

Thanks.

**Comment by grimm26** [comment]
@maksyms 
```
[profile base_account]
region = us-east-2

[profile child_account]
role_arn = arn:aws:iam::123456789012:role/AdminAccess
source_profile = base_account
region = us-east-2
```

**Comment by fbozic** [comment]
I have the same issue. Here is my configuration.

```
[default]
region = eu-central-1

[profile root]
mfa_serial = arn:aws:iam::111111111111:mfa/my.name
duration_seconds = 43200
output = json

[profile dev]
role_arn = arn:aws:iam::999999999999:role/AdminRole
source_profile = root
output = json
```

**Comment by grimm26** [comment]
not the same issue, actually. My config has no mfa. Similar, though, since the change that I cited basically ignores a profile with a source profile that does not have mfa in that profile.

**Comment by sshvetsov** [comment]
Ran into the same problem when trying to use `acp`. I'm no zsh expert, but I think I've fixed a problem locally. Will submit PR shortly, but need someone to do a sanity check on my changes.

**Comment by grimm26** [comment]
@sshvetsov Your fix works for me!
@maksyms check it out
