### ISSUE TITLE
Suddenly got branch disappered on git repo folder

### ISSUE THREAD

**Issue by aa-ahmed-aa** [ohmyzsh/ohmyzsh#9850]
git branch name suddenly disappeared in agnoster theme

i'm not sure if this is after specific update or not but i checked issues here and didn't find anything related

![image](https://user-images.githubusercontent.com/9592546/115643594-53308580-a31d-11eb-871e-ac43941a6591.png)

i have checked the the theme file and try to quickly debug the problem and noticed commenting this line made things work again 
https://github.com/ohmyzsh/ohmyzsh/blob/079e7bb5e0a79171f3356d55d3f6302a82645a39/themes/agnoster.zsh-theme#L98

 - Latest ohmyzsh update? Yes
 - ZSH Version: [zsh 5.8 (x86_64-ubuntu-linux-gnu)]

**Comment by mcornella** [comment]
What does `echo ${commands[git]}` and `which -a git` show?

**Comment by aa-ahmed-aa** [comment]
first one is null 
![image](https://user-images.githubusercontent.com/9592546/115942145-0aa5d300-a4a9-11eb-87e4-9adc30dfd9e3.png)

**Comment by mcornella** [comment]
Try running `zmodload zsh/parameters` and then running the echo command again.

**Comment by aa-ahmed-aa** [comment]
still empty output

**Comment by mcornella** [comment]
Run `zsh -xvic exit &> ~/omz-debug.log` and send me the log file generated at my email (see [my profile](https://github.com/mcornella)) with a reference to this issue. You can go over it and remove any sensitive content before emailing it to me.

**Comment by aa-ahmed-aa** [comment]
Done
Thanks for your help  <3

**Comment by mcornella** [comment]
Hey, sorry for the late reply. I went over the log file and never found anything relevant. It's weird that `which -a git` shows actual binaries but `${commands[git]}` is empty. Try running `rehash` and then `echo ${commands[git]}` again.

**Comment by aa-ahmed-aa** [comment]
still empty

**Comment by ahmadnbl** [comment]
I got the same issue, but I don't know if the behavior is same with the issue faced by the OP.
Actually the branch name was showing first, but after several milliseconds, it become disappear. Is it same, or different issue?

<details> <summary>Video (82KB)</summary>

https://user-images.githubusercontent.com/16456963/120736688-e7922880-c516-11eb-97b3-99d9f0328e10.mp4

</details>

**Comment by keerati808080** [comment]
ในวันที่ ศ. 4 มิ.ย. 2021 09:29 น. Ahmad Nabili ***@***.***>
เขียนว่า:

**Comment by aa-ahmed-aa** [comment]
it might be the same and i didn't notice this 
Have you tried the solution i mentioned and does it work ?

**Comment by ahmadnbl** [comment]
I already tried the suggestions in this thread, but still didn't work. The issue on my side was intermittent, sometimes it will happened, sometimes it'll back to normal again. Usually become normal again when I move to another branch, but it still depends on what branch, and I didn't know what kind of specific branch that can caused this

**Comment by lwasyl** [comment]
Perhaps related, I no longer see branch remote status (ahead, behind). I do see branch name and dirty files though

```
─❯ which -a git                                                                                                                                                                                                                                                       
/usr/local/bin/git
/usr/bin/git

─❯ echo ${commands[git]}                                                                                                                                                                                                                                              
/usr/local/bin/git
```

**Comment by mcornella** [comment]
I'll close this since there's no follow-up. Reopen if this still happens and I'll try to help out.
