### ISSUE TITLE
Cursor does not show after ssh session timeout

### ISSUE THREAD

**Issue by robinpaulson** [ohmyzsh/ohmyzsh#9861]
**Describe the bug**
When I disconnect my device from the internet, any open ssh sessions will close. When this happens, the usual command-line appears, but without a cursor. All else is as expected; plugins, themes, etc. are all there.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Open an ssh session to a remote device
2. Disconnect from the internet
3. Wait for the ssh session to time out
4. Cursor does not show

**Expected behavior**
Cursor should show

**Screenshots and/or Recordings**
How it should look: ![Screenshot from 2021-04-25 14-21-35](https://user-images.githubusercontent.com/1186107/115978168-cb26d600-a5d1-11eb-8e31-01ab7ed7eabd.png)
How it does look: ![Screenshot from 2021-04-25 14-21-54](https://user-images.githubusercontent.com/1186107/115978173-d0842080-a5d1-11eb-95ae-af0a353c6cc9.png)

**Desktop (please complete the following information):**
 - OS / Distro: Ubuntu 20.04
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: yakuake/konsole/gnome-terminal (It fails in all three)

**Additional context**
plugins: git command-not-found timestamp colored-man-pages
theme: my own theme, a minor variant on "Gallois" ; see below for content

[rp_zsh_theme.txt](https://github.com/ohmyzsh/ohmyzsh/files/6371127/rp_zsh_theme.txt)

**Comment by mcornella** [comment]
If you run `clear` does that restore the cursor? Does the same happen while running bash or zsh without configuration (`zsh -f`)?

**Comment by robinpaulson** [comment]
Clear does not restore the cursor, no. I'm not sure how to run it without config. Do you mean without omz?

I ran zsh -f on the command line, is that what you mean? The cursor didn't show then either.

**Comment by mcornella** [comment]
> Clear does not restore the cursor, no. I'm not sure how to run it without config. Do you mean without omz?
> 
> I ran zsh -f on the command line, is that what you mean? The cursor didn't show then either. Does that mean this is a non-omz problem?

Sorry, I know this is old but I believe I meant `reset` instead of `clear`, which resets the terminal settings. Does that fix it for you?

**Comment by robinpaulson** [comment]
That's not a problem, I appreciate the assistance.

"reset" does fix the problem, yes. who knows if it's merely for the single session or for longer.

**Comment by mcornella** [comment]
It might be due to weird binary characters being output by a command or a cat of a binary file. I hope you can find the culprit.

**Comment by robinpaulson** [comment]
OK, it appears to be working as expected now. I've had a few ssh sessions drop out recently, the cursor now shows afterwards. I'm not entirely sure what happened, but thanks anyway!

@mcornella I have done that on a few very rare occasions, but not for some time.

**Comment by robinpaulson** [comment]
OK, it appears that did not solve the problem long-term
