### ISSUE TITLE
Deno completion not working properly

### ISSUE THREAD

**Issue by carlosala** [ohmyzsh/ohmyzsh#9862]
**Describe the bug**
Deno completions are not working properly when using the plugin. I think that it's due to having the completions in the plugin folder.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable the `deno` plugin
2. Try to trigger completions on `deno`
3. For me it's not working

**Expected behavior**
It should trigger the completions.

**Desktop (please complete the following information):**

 - OS / Distro: Debian
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: Alacritty

**Additional context**
My config is kinda common, I copy you the plugins array:
```
plugins=(deno git npm yarn)
source $ZSH/oh-my-zsh.sh
```

Thanks!

**Comment by mcornella** [comment]
```
autoload -Uz _deno
_comps[deno]=_deno
```

Adding this to the plugin should do it.

**Comment by carlosala** [comment]
Ok, I'm going to do a PR to solve it. Thanks
