### ISSUE TITLE
I get errors every time Oh My Zsh upgrades itself

### ISSUE THREAD

**Issue by bisdavid** [ohmyzsh/ohmyzsh#9875]
**Describe the bug**
Every time Oh My Zsh updates itself, I get the following spew on the console as part of the update...
This also shows up in the output of "omz changelog"

```
commit:is-breaking:3: failed to load module `zsh/regex': /local/p4clients/pkgbuild-aDkX6/workspace/src/Zsh/build/private/staging/lib/zsh/5.8/zsh/regex.so: cannot open shared object file: No such file or directory
commit:is-breaking:3: -regex-match not available for regex
commit:is-breaking:3: failed to load module `zsh/regex': /local/p4clients/pkgbuild-aDkX6/workspace/src/Zsh/build/private/staging/lib/zsh/5.8/zsh/regex.so: cannot open shared object file: No such file or directory
commit:is-breaking:3: -regex-match not available for regex
commit:is-breaking:3: failed to load module `zsh/regex': /local/p4clients/pkgbuild-aDkX6/workspace/src/Zsh/build/private/staging/lib/zsh/5.8/zsh/regex.so: cannot open shared object file: No such file or directory
commit:is-breaking:3: -regex-match not available for regex
commit:is-breaking:3: failed to load module `zsh/regex': /local/p4clients/pkgbuild-aDkX6/workspace/src/Zsh/build/private/staging/lib/zsh/5.8/zsh/regex.so: cannot open shared object file: No such file or directory
commit:is-breaking:3: -regex-match not available for regex
commit:is-breaking:3: failed to load module `zsh/regex': /local/p4clients/pkgbuild-aDkX6/workspace/src/Zsh/build/private/staging/lib/zsh/5.8/zsh/regex.so: cannot open shared object file: No such file or directory
commit:is-breaking:3: -regex-match not available for regex
commit:is-breaking:3: failed to load module `zsh/regex': /local/p4clients/pkgbuild-aDkX6/workspace/src/Zsh/build/private/staging/lib/zsh/5.8/zsh/regex.so: cannot open shared object file: No such file or directory
commit:is-breaking:3: -regex-match not available for regex
commit:is-breaking:3: failed to load module `zsh/regex': /local/p4clients/pkgbuild-aDkX6/workspace/src/Zsh/build/private/staging/lib/zsh/5.8/zsh/regex.so: cannot open shared object file: No such file or directory
commit:is-breaking:3: -regex-match not available for regex
commit:is-breaking:3: failed to load module `zsh/regex': /local/p4clients/pkgbuild-aDkX6/workspace/src/Zsh/build/private/staging/lib/zsh/5.8/zsh/regex.so: cannot open shared object file: No such file or directory
commit:is-breaking:3: -regex-match not available for regex
commit:is-breaking:3: failed to load module `zsh/regex': /local/p4clients/pkgbuild-aDkX6/workspace/src/Zsh/build/private/staging/lib/zsh/5.8/zsh/regex.so: cannot open shared object file: No such file or directory
commit:is-breaking:3: -regex-match not available for regex
commit:is-breaking:3: failed to load module `zsh/regex': /local/p4clients/pkgbuild-aDkX6/workspace/src/Zsh/build/private/staging/lib/zsh/5.8/zsh/regex.so: cannot open shared object file: No such file or directory
commit:is-breaking:3: -regex-match not available for regex
commit:is-breaking:3: failed to load module `zsh/regex': /local/p4clients/pkgbuild-aDkX6/workspace/src/Zsh/build/private/staging/lib/zsh/5.8/zsh/regex.so: cannot open shared object file: No such file or directory
commit:is-breaking:3: -regex-match not available for regex
```

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Wait for the next update, or run the command "omz changelog"

**Expected behavior**
A brief description of what should happen.
I would expect everything except the errors.  A cleaner output.

**Screenshots and/or Recordings**
You can also record an asciinema session: https://asciinema.org/

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
 Yes, but registration failed - I got an "Invite expired" message when I tried to use the URL above.

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support
No matches

**Desktop (please complete the following information):**

 - OS / Distro: [e.g. Arch Linux, macOS] 
   Amazon Linux 2
 - If on Windows what version of WSL: [e.g. WSL1, WSL2]

 - Latest ohmyzsh update?: [e.g. Yes/No]   YES
 - ZSH Version: [e.g. 5.6] 5.8
 - Terminal emulator: Windows Terminal

**Additional context**
Add any other context about the problem here. This can be themes, plugins, custom configs.

**Comment by mcornella** [comment]
It might be a conflict between two zsh versions (https://github.com/ohmyzsh/ohmyzsh/issues/5162). Can you run this and post the output?
```zsh
which -a zsh | while read zsh; do echo -n "$zsh: "; $zsh --version; done
```

**Comment by bisdavid** [comment]
Sorry, I didn't see your initial response til I got the email that the issue was closed.

❯ which -a zsh | while read zsh; do echo -n "$zsh: "; $zsh --version; done
/apollo/env/envImprovement/bin/zsh: zsh 5.8 (x86_64-pc-linux-gnu)
/usr/bin/zsh: zsh 5.7.1 (x86_64-koji-linux-gnu)
/bin/zsh: zsh 5.7.1 (x86_64-koji-linux-gnu)

The basic "which" command says that the first one is my "main" one.   I'm not sure how to update the others, or if it's safe to remove them.

**Comment by bisdavid** [comment]
I continue to get these errors every time Oh My ZSH updates.  I never got a response to the question above in the past year and a 1/2. :-( 

The errors today look like this:
```
commit:subject:4: -regex-match not available for regex
commit:is-breaking:3: failed to load module `zsh/regex': /local/p4clients/pkgbuild-hLNPO/workspace/src/Zsh/build/private/staging/lib/zsh/5.9/zsh/regex.so: cannot open shared object file: No such file or directory
```
But there are a few dozen of them...
