### ISSUE TITLE
/etc/profile.d/which2.sh:export:17:%20invalid%20option(s) on Fedora 34

### ISSUE THREAD

**Issue by naknode** [ohmyzsh/ohmyzsh#9888]
**Describe the bug**
Cannot seem to install or set the ZSH shell

**To Reproduce**
Steps to reproduce the behavior, for example:

1. `sudo dnf install zsh`
2. `zsh`
3. Select 0 to create blank  `.zshrc`
3. Receive output: "/etc/profile.d/which2.sh:export:17:%20invalid%20option(s)"

**Expected behavior**
Be able to use zsh. Cannot even set the shell.

**Desktop (please complete the following information):** 

 - OS / Distro: Fedora 34 (brand new install as of 3 hours ago)
 - Latest ohmyzsh update?: Yes
 - ZSH Version: Latest one
 - Terminal emulator: urxvt (but it happens in `gnome-terminal` too

**Additional context**
On a brand-new i3 config

**Comment by michelmzs** [comment]
@naknode This happened because the chsh utility are not available.
Try: dnf install util-linux-user

**Comment by mcornella** [comment]
If you can't even use zsh this is not an OMZ bug.
