### ISSUE TITLE
Conda environment name does not appear in the prompt

### ISSUE THREAD

**Issue by guochengqian** [ohmyzsh/ohmyzsh#9896]
**Describe the bug**
Conda environment name does not appear in the prompt. 
theme: robbyrussell
version: the latest version of oh-my-zsh

**Comment by guochengqian** [comment]
sovled by using powerlevel10k theme

**Comment by Betristor** [comment]
How could we make conda information show in the terminal in other themes? I want conda info to be shown in the terminal, but I don't like to be strained with little theme selection.
