### ISSUE TITLE
'mysql.server start' command can not run

### ISSUE THREAD

**Issue by jinl2011** [ohmyzsh/ohmyzsh#9907]
![image](https://user-images.githubusercontent.com/25602802/117905539-ed289400-b305-11eb-9414-fc1ddd42192b.png)

**Comment by jeffmhubbard** [comment]
The directory you are running it from must not be in your `$PATH`. `./mysql.server` works because you are providing a (relative) path `./`.  Also, this is not an OMZ issue in any way.
