### ISSUE TITLE
Vim won't open immediately after I press enter

### ISSUE THREAD

**Issue by awa5114** [ohmyzsh/ohmyzsh#9917]
I am using WSL with Ubuntu installed from the Microsoft Store along with the Windows Terminal.  I have observed that typing `vim` into my command prompt and pressing enter suspends the prompt. When I try to get out by pressing Ctrl+C, that's when vim actually opens. It seems to work with no issues, but I am frustrated that it won't open immediately after I press enter. 

Running VIM through WSL in powershell actually works fine and does not display this behavior, which is why I think `ohmyzsh` is causing the problem.
Has anyone ever observed this behavior? How can I fix it? Thanks

Please see [SO] post for more information (https://askubuntu.com/questions/1337966/vim-doesnt-open-immediately-after-i-press-enter?noredirect=1#comment2286365_1337966)

**Comment by Unu-tech** [comment]
@awa5114 
Hello. I got the same issue and found no solution. Have you solved the issue?

**Comment by Unu-tech** [comment]
@awa5114 
Hello. Just looked at your solution. Are you able to use XLaunch now?
