### ISSUE TITLE
[_adb] Broken autocompletion

### ISSUE THREAD

**Issue by dreamwhite** [ohmyzsh/ohmyzsh#9923]
**Describe the bug**
Autocomplete doesn't work for `adb pull`

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin `adb`
2. Write `adb pull /sdca` and spam TAB to autocomplete
3. See error

**Expected behavior**
A list of the remote files like depicted below on fish shell:

![image](https://user-images.githubusercontent.com/17933708/119224047-f206f800-bafc-11eb-98f9-f130e77b57e4.png)

**Desktop (please complete the following information):**

 - OS / Distro: Arch Linux
 - Latest ohmyzsh update?: Yes, I ran `omz update` before opening this issue
 - ZSH Version: 5.8
 - Terminal emulator: Tilix 1.9.4-3

**Additional context**
Add any other context about the problem here. This can be themes, plugins, custom configs.

I'm using PowerLevel10K as main theme and my zshrc can be consulted [here](https://github.com/dreamwhite/dotfiles/blob/master/zsh/.zshrc)

Many thanks for your effort in the community and have a nice weekend
dreamwhite

**Comment by gokulmurugesh** [comment]
i faced this issue in arch linux, it can be fixed by
`mv /usr/share/zsh/site-functions/_adb /usr/share/zsh/site-functions/_adb,bak`
`rm .zcompdump-*` and reload zsh terminal

pls do ensure the file ~/.zcompdump has the following lines
_comps=(...
'adb' '_adb'
..)
autoload -Uz ... _adb ..

i think it occurs because arch's android-tools package ships
usr/share/zsh/site-functions/
usr/share/zsh/site-functions/_adb
while zsh has its own [adb completion support](https://github.com/zsh-users/zsh/blob/03b2cd1bb013212d1f6c2b897156ac87b455c2ee/Completion/Unix/Command/_adb#L463-L477)
this may conflict eachother making it not to load at all

**Comment by dreamwhite** [comment]
> i faced this issue in arch linux, it can be fixed by
> `sudo mv /usr/share/zsh/site-functions/_adb /usr/share/zsh/site-functions/_adb.bak`
> `rm ~/.zcompdump-*`
> and reload zsh terminal
> 
> pls do ensure the file ~/.zcompdump-* has the following lines:
> _comps=(...
> 'adb' '_adb'
> ..)
> autoload -Uz ... _adb ..
> 
> i think it occurs because arch's android-tools package ships
> /usr/share/zsh/site-functions/
> /usr/share/zsh/site-functions/_adb
> 
> while [zsh has its own adb completion support.](https://github.com/zsh-users/zsh/blob/03b2cd1bb013212d1f6c2b897156ac87b455c2ee/Completion/Unix/Command/_adb#L463-L477)
> /usr/share/zsh/functions/Completion/Unix/_adb
> this may conflict eachother making it not to load at all
Thank you so much for replying.

To be fair I don't see any difference before making your edits.
If I try to do a simple `adb pull`I can't navigate through the android filesystem.
Can you please do your tests?
Again thanks and have a nice day

**Comment by gokulmurugesh** [comment]
Lets solve it in brief,
Let it be unchanged, its fresh from install
![Screenshot_20210707_153530](https://user-images.githubusercontent.com/76038200/124742242-24987300-df3a-11eb-9e13-d9fad031c829.png)

I have my mobile device connected. when i tried to adb pull /<tab>
![Screenshot_20210707_153605](https://user-images.githubusercontent.com/76038200/124742470-62959700-df3a-11eb-84f8-044348850f03.png)
its show my '/' root directory of my linux system (PC)

here's the ~/.zcompdump-<pcname>
![Screenshot_20210707_153730](https://user-images.githubusercontent.com/76038200/124742639-8b1d9100-df3a-11eb-8b53-7282aefa710f.png)
As you can see  'adb' '_adb' was not generated

Now let me rename the '_adb' site-function to _adb.bak to remove conflicts
![Screenshot_20210707_153819](https://user-images.githubusercontent.com/76038200/124742862-c28c3d80-df3a-11eb-9174-ec1771dd72ad.png)

I'll close all my terminals and manually delete my ~/.zcompdump-*
![Screenshot_20210707_154223](https://user-images.githubusercontent.com/76038200/124742934-d637a400-df3a-11eb-8241-452d163ce11d.png)

Now i'll reopen my terminal & it automatically generates .zshcompdump
as you can see the .zshcompdump now has 'adb' '_adb' generated in it.
![Screenshot_20210707_154304](https://user-images.githubusercontent.com/76038200/124743049-f5363600-df3a-11eb-9894-4dd22b31bb47.png)

now im in terminal trying to pull files with tab completeion
![Screenshot_20210707_155135](https://user-images.githubusercontent.com/76038200/124743285-375f7780-df3b-11eb-999f-a0d3f4774440.png)
you can see those file below are the ones present in root directory of my phone. tab completion is working now

those _adb in /usr/share/zsh/site-functions/ & /usr/share/zsh/functions/Completion/Unix/_adb are conflicting each other making omz not to load it.

**Comment by dreamwhite** [comment]
Alright, so apparently what I was doing wrong was loading twice the `_adb` completion via `plugins`.
So recapping I did the following steps:

1. `sudo pacman -S android-tools`
2.  `sudo mv /usr/share/zsh/site-functions/_adb /usr/share/zsh/site-functions/_adb.bak`
3.  `rm ~/.zcompdump-*`
4. removed `adb` from `plugins`:

```plugins=(
    git
    zsh-completions
)```

The completion works as expected but I think that something is wrong. Should I load `_adb` completion or leave the default one from `zsh-completions`?

**Comment by gokulmurugesh** [comment]
yes you are right,
Enabling oh-my-zsh's 'adb' plugin creates a new conflict. i.e between
`/usr/share/zsh/functions/Completion/Unix/_adb` &
`~/.oh-my-zsh/plugins/adb/_adb`
resulting no adb line generation in zcompdump-* & not loading

Difference between these files (ohmyzsh's _adb, zsh's built-in adb) & what file is the best for use?
* ohmyzsh's _adb suggests commands and description of pull,push,install,etc... but **lacks auto-completion for directories**.
To use omz's _adb rename `/usr/share/zsh/functions/Completion/Unix/_adb` file & add adb plugin to ~/.zshrc

* zsh's _adb has autocompletion for directories but does not provide command descriptions(i'll go with this)
To use zsh's _adb just remove the adb plugin and also remove conflicting site functions as shown in previous posts.

Thank you

**Comment by dreamwhite** [comment]
> yes you are right,
> Enabling oh-my-zsh's 'adb' plugin creates a new conflict. i.e between
> `/usr/share/zsh/functions/Completion/Unix/_adb` &
> `~/.oh-my-zsh/plugins/adb/_adb`
> resulting no adb line generation in zcompdump-* & not loading
> 
> Difference between these files (ohmyzsh's _adb, zsh's built-in adb) & what file is the best for use?
> 
>     * ohmyzsh's _adb suggests commands and description of pull,push,install,etc... but **lacks auto-completion for directories**.
>       To use omz's _adb rename `/usr/share/zsh/functions/Completion/Unix/_adb` file & add adb plugin to ~/.zshrc
> 
>     * zsh's _adb has autocompletion for directories but does not provide command descriptions(i'll go with this)
>       To use zsh's _adb just remove the adb plugin and also remove conflicting site functions as shown in previous posts.
> 
> 
> Thank you

Alright, everything is clear. Thank you so much for the explanation (despite I'm stoned af rn haha).
