### ISSUE TITLE
Display the current theme loaded when run omz theme

### ISSUE THREAD

**Issue by ricardofiorani** [ohmyzsh/ohmyzsh#9928]
Today when I run `omz theme` I get the following output.

```
Usage: omz theme <command> [options]

Available commands:

  list            List all available Oh My Zsh themes
  use <theme>     Load an Oh My Zsh theme
```

It would be nice to add in there the name of the current used/loaded theme.

**Comment by mdegis** [comment]
Can I work on this issue?

**Comment by mcornella** [comment]
This is already available via `omz theme list`.
