### ISSUE TITLE
Directory tab completion not working

### ISSUE THREAD

**Issue by GrpeApple** [ohmyzsh/ohmyzsh#9929]
**Describe the bug**
Tab completing on directories (upper) that only have execute permissions will not be able to access lower directories that have all permissions. 

**To Reproduce**
1. Install `zsh`
2. Install `oh-my-zsh`
3. Run:
```zsh
mkdir -p permissions/test/a
chmod u-rw permissions
```
4. Tab complete `ls permissions/test`

**Expected behavior**
Ignore read and write permissions of directories (upper), and act like the original `zsh` tab completion.

**Screenshots and/or Recordings**

[Video](https://user-images.githubusercontent.com/69628996/119450724-ec144f80-bd66-11eb-892d-01685125f1b6.mp4)

[![asciicast](https://asciinema.org/a/416064.svg)](https://asciinema.org/a/416064)
**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
~~Not yet.~~ Never will, sorry.

- Also searched existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=is%3Aissue+label%3ABug+label%3A"Topic%3A+completion") (label: Bug; Topic: completion)

**Mobile:**

- OS / Distro: Android 8.1.0 (Linux)
- Latest ohmyzsh update?: Yes
- ZSH Version: `zsh 5.8 arm-unknown-linux-androideabi`
- Terminal emulator: Termux

**Additional context**
[dotfiles](https://github.com/GrpeApple/dotfiles/tree/main/home/zsh)

**Comment by Brettdah** [comment]
that's not a bug that's a feature !
If you remove the right to read (u-w) you can see what's inside a directory yet you let the right to execute (or go through the directory) so if you know the directories you can cross...
if you don't you can't.

**Comment by GrpeApple** [comment]
> that's not a bug that's a feature !

If it is, I would like to disable it.

> If you remove the right to read (u-w) you can see what's inside a directory yet you let the right to execute (or go through the directory) so if you know the directories you can cross...
> if you don't you can't.

If I get what you are saying; that does not mean it should recursively apply that to nested directories that *have* the read permission (`r`), in other words: if I know the directories that *do not have* the read permission (`r`) but I would like to still tab complete the directories that *have* the read permission (`r`), this does not mean it should also apply to directories that *have* the read permission (`r`).

**Comment by mcornella** [comment]
You can use `zstyle ':completion:*' accept-exact-dirs true`:
> accept-exact-dirs
> > This is used by filename completion. Unlike accept-exact it is a boolean. By default, filename completion examines all components of a path to see if there are completions of that component, even if the component matches an existing directory. For example, when completion after /usr/bin/, the function examines possible completions to /usr.
> > 
> > **When this style is ‘true’, any prefix of a path that matches an existing directory is accepted without any attempt to complete it further. Hence, in the given example, the path /usr/bin/ is accepted immediately and completion tried in that directory.**
> >
> > This style is also useful when completing after directories that magically appear when referenced, such as ZFS .zfs directories or NetApp .snapshot directories. When the style is set the shell does not check for the existence of the directory within the parent directory.
> >
> > If you wish to inhibit this behaviour entirely, set the path-completion style (see below) to ‘false’.
