### ISSUE TITLE
Add `--no-restart` flag to `omz update`

### ISSUE THREAD

**Issue by Logicer16** [ohmyzsh/ohmyzsh#9936]
**Is your feature request related to a problem? Please describe.**
If `omz update` is ran inside a shell script, and it finds and available update, it will restart the shell and end execution of the shell script mid way through. For example, I use a script to run various updaters (such as `brew`, `pip`, `mas`, `softwareupdate`, `npm`, etc.), including `omz update`, and at the end of the script it writes the last date of successful update into a file, but because a successful `omz update` would stop the script before it could report a successful update.

**Describe the solution you'd like**
`omz update` should have a `--no-restart` flag.

**Describe alternatives you've considered**
My current workaround is to just comment out the restart code, though this doesn't provide the convenience of zsh restarting automatically for me when I run `omz update`.

**Comment by mcornella** [comment]
I added `--unattended` for that. That said, the proper way to update OMZ via a script is to call `$ZSH/tools/upgrade.sh` directly.

**Comment by Logicer16** [comment]
Thanks for your response, must have skipped over that part of the FAQ.￼￼￼🤦‍♂️
