### ISSUE TITLE
#8502 breaks ALT+B/ALT+F key bindings in iTerm2

### ISSUE THREAD

**Issue by mcornella** [ohmyzsh/ohmyzsh#9938]
Hi!
Don't know if this is the correct place to leave this comment or not. But this commit apparently brakes ALT+B / F key bindings in iTerm2.
I personally and many Linux user use them everyday. Specially if you are an Emacs user.

Right now, I had to roll back to previous commit to this one, to make it work again.

_Originally posted by @campco in https://github.com/ohmyzsh/ohmyzsh/issues/8502#issuecomment-849854367_

**Comment by mcornella** [comment]
@campco can you post the key sequence for ALT+Left arrow and ALT+Right arrow? You can get that by pressing <kbd>CTRL+V</kbd>, then the keyboard combination.

**Comment by campco** [comment]
In iTerm2: `CRTL+V` and then `ALT+LeftArrow` gives me : `^[`
Is exactly same for `ALT+RightArrow`.

**Comment by mcornella** [comment]
Can you test https://github.com/ohmyzsh/ohmyzsh/pull/9940? You can try it with `omz pr test 9940`.

**Comment by campco** [comment]
it seems to work!  :)
