### ISSUE TITLE
Anstroger theme Displaying not correctly in vscodium

### ISSUE THREAD

**Issue by Sambhrama754** [ohmyzsh/ohmyzsh#9949]
**Describe the bug**
When I installed vscodium and opened it I then I opened integrated terminal it was glitchy

**To Reproduce**
Steps to reproduce the behavior, for example:
1. I installed all my required plugins in codium
2. Open integrated terminal
3. See error

**Expected behavior**
It should appear correctly as in terminal app for gnome

**Desktop (please complete the following information):**

 - OS / Distro: Debian 10.9
 - Latest ohmyzsh update?: Yes
 - ZSH Version: latest
 - Terminal emulator: gnome terminal

**Additional context**
Anstroger theme

**Comment by jacobmealey** [comment]
What version of vscodium are you using? Also, could you include a screenshot of the problem or define what you mean by glitchy?

**Comment by Sambhrama754** [comment]
oh okie i serched on google and found that font is problem 
sorry for wating ur time
