### ISSUE TITLE
git plugin: add gpr for "git pull -r"

### ISSUE THREAD

**Issue by DanielYWoo** [ohmyzsh/ohmyzsh#9951]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
the git plugin

**Is your feature request related to a problem? Please describe.**
gpr is easier to remember and type, than gup.

**Describe the solution you'd like**
add an alias gpr for "git pull -r"

**Describe alternatives you've considered**
n/a

**Additional context**
Add any other context, screenshots or discord conversations about the feature request here. Also if you have any PRs related to this issue that are already open that you would like us to look at.

**Related Issues**
no

**Comment by robbyrussell** [comment]
@DanielYWoo interested in submitted a PR for this?

**Comment by DanielYWoo** [comment]
sure, PR #9964 created.

**Comment by DanielYWoo** [comment]
merged into master
