### ISSUE TITLE
rm -rf /* prompts wrong path

### ISSUE THREAD

**Issue by neo-expert** [ohmyzsh/ohmyzsh#9957]
**Describe the bug**
 when we try to run rm -rf /* with zsh, the shell prompts the wrong path:
```
➜  ~ rm -rf /*
zsh: sure you want to delete all 28 files in /home/user/ [yn]? n
➜  ~ 
```

but when we press y, it deletes everything under /

**Expected behavior**
the prompt shoud be like this:
```
➜  ~ rm -rf /*
zsh: sure you want to delete all files in / [yn]? n
➜  ~ 
```

**Comment by mcornella** [comment]
This bug exists in zsh from 5.5 to 5.8. It'll be fixed in the next release (fix commit: https://github.com/zsh-users/zsh/commit/cf134c15a0). Not our issue.
