### ISSUE TITLE
Syntax error with check_for_upgrade.sh

### ISSUE THREAD

**Issue by MIyulong** [ohmyzsh/ohmyzsh#9962]
**Describe the bug**
Syntax error
```
/Users/mac/.oh-my-zsh/tools/check_for_upgrade.sh:行32: 未预期的符号“)”附近有语法错误
/Users/mac/.oh-my-zsh/tools/check_for_upgrade.sh:行32: `() {'
/Users/mac/.oh-my-zsh/oh-my-zsh.sh:行21: autoload：未找到命令
/Users/mac/.oh-my-zsh/oh-my-zsh.sh:行39: 未预期的符号“(”附近有语法错误
/Users/mac/.oh-my-zsh/oh-my-zsh.sh:行39: `for plugin ($plugins); do'
```

**To Reproduce**
Steps to reproduce the behavior, for example:
1. cd ~/.oh-my-zsh/custom/plugins/
2. git clone plugins: zsh-autosuggestions,  zsh-syntax-highlighting, zsh-completions
3. and run command 
   ```
   sed -i "" "s/^plugins.*/plugins=(git zsh-autosuggestions zsh-syntax-highlighting zsh-completions)/" "${HOME}/.zshrc"
    source ~/.zshrc
   ```
4. and then, get those syntax errors

**Self Check**
➜  ~ zsh --version
zsh 5.8 (x86_64-apple-darwin20.0)
![image](https://user-images.githubusercontent.com/8175565/121622543-c6928000-caa0-11eb-9ea7-2f9262b6d3c1.png)

**Comment by mcornella** [comment]
You're not running zsh, you need to run `zsh` instead of doing `source ~/.zshrc`.
