### ISSUE TITLE
Please rename kubectx_prompt_info

### ISSUE THREAD

**Issue by tmoschou** [ohmyzsh/ohmyzsh#9974]
Hello,

Is it possible to please rename `kubectx_prompt_info` as it may sound a bit nitpicky but the change introduced in https://github.com/ohmyzsh/ohmyzsh/commit/5152d381bb828a4ed41fdbb430eb05970a8bb25c (2-days ago) causes tab completion for the `kubectl` command to now stop at `kubect` - for someone who struggles to notice the difference this is somewhat frustrating.

This happens even if the `kubectx` plugin is not enabled due to the default definition in `lib/prompt_info_functions.zsh`

**Comment by subnet-dev** [comment]
Same problem for me.

**Comment by Malet** [comment]
Has slowed me down a lot in the past couple of days, super annoying!
As a quick fix you can use the below, this will need to be reverted once there's an update that touches that file (I expect this would break updates unless it nukes changes to the git repo).

```
sed -i.bak -e 's/kubectx_prompt_info/# kubectx_prompt_info/' ~/.oh-my-zsh/lib/prompt_info_functions.zsh
```
