### ISSUE TITLE
suspended (tty output) when running sudo pipe command

### ISSUE THREAD

**Issue by Racle** [ohmyzsh/ohmyzsh#9975]
Ex. running `curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -` causes this:
```
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   983  100   983    0     0   1905      0 --:--:-- --:--:-- --:--:--  1901
[1]  + 378820 done                    curl https://packages.microsoft.com/keys/microsoft.asc | 
       378821 suspended (tty output)  sudo apt-key add -
```

When changing to `bash` I can do that just fine (in same terminal window). It doesn't work in in zsh for some reason.

OS: pop_os 20.10
ZSH: 5.8

**Comment by mcornella** [comment]
This is old; did you figure it out? I can't reproduce this. I doubt it is an Oh My Zsh bug but reopen if you feel otherwise.

**Comment by Racle** [comment]
> This is old; did you figure it out? I can't reproduce this. I doubt it is an Oh My Zsh bug but reopen if you feel otherwise.

This one is odd.
I can still reproduce this on my main system (pop_os virtual machine, upgraded to 21.04). But when I ssh to different machine with 100% same setup and config it works like it should.

Terminal emulator doesn't seems to matter as I have moved to Kitty from Tilix after I made this one (and tested that with gnome-terminal).

It's hard to reproduce and it isn't needed a lot (and using bash as an alternative is very fast workaround), so in my opinion this can be closed.

**Comment by mcornella** [comment]
Maybe this is related: https://stackoverflow.com/a/24056296/5798232.

**Comment by Racle** [comment]
> Maybe this is related: https://stackoverflow.com/a/24056296/5798232.

Found same thing earlier, didn't help. Not when I put that to terminal OR when I put that to my .zshrc file. 
This is very odd bug/behaviour.

And when I press `ctrl+d` terminal says that `zsh: you have suspended jobs.` and pressing that keycombo again prompts password input (because of `sudo apt-key add -`) and then closes terminal.


..and while I was writing this I testing out different things and found out that `stty -tostop | curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -` will work just fine.

And whats is even confusing, if I type `sudo su` and cancel password prompt with `ctrl+c`, I can use `curl | sudo apt-key` again normally. 
Or I can use `sudo curl | sudo apt-key` and it will also work.

**Comment by mcornella** [comment]
Does the same happen under normal zsh (`zsh -f`)?

**Comment by Racle** [comment]
> Does the same happen under normal zsh (`zsh -f`)?

Yes it does. Almost same behavior. Typing `sudo su` and cancelling that doesn't work anymore. But using `sudo curl | sudo apt-key` works.

**Comment by mcornella** [comment]
If you've run `sudo` previously and entered the password correctly, does `curl | sudo apt-key` work correctly?

**Comment by Racle** [comment]
> If you've run `sudo` previously and entered the password correctly, does `curl | sudo apt-key` work correctly?

That also works.

**Comment by mcornella** [comment]
Might this be a bug in `sudo` then?

**Comment by mcornella** [comment]
I don't have enough expertise to direct the debugging further, maybe the folks at the [zsh-users mailing list](https://zsh.org/mla) can better help you.

**Comment by Racle** [comment]
And there seems to be pretty similar message thread already there https://www.zsh.org/mla/users/2020/msg00121.html

But that might be my next place to check as this has nothing to do with ohmyzsh.
