### ISSUE TITLE
`asp` AWS plugin function unable to support `/` in profile names

### ISSUE THREAD

**Issue by SurrealTiggi** [ohmyzsh/ohmyzsh#9976]
**Describe the bug**
`asp` aws plugin profile switcher doesn't support profiles with `/` in the name

**To Reproduce**
1. Enable the `aws` plugin
2. Configure some random profiles with and without `/` in the name, example below
```bash
$ cat .aws/config
[default]
region = eu-west-1
output = json
[profile test]
region = eu-west-1
output = json
[profile test/1]
region = eu-west-1
output = json

```
3. `asp` incorrectly suggests `test/1\]` as an option which doesn't work, root of error can be seen by running `aws_profiles`
```bash
$ aws_profiles
default
test
[profile test/1]
```

**Expected behavior**
`aws_profiles` caters for optional `/` in profile name
```
$ aws_profiles
default
test
test/1

$ asp test/1
$ env | grep AWS_
AWS_DEFAULT_PROFILE=test/1
AWS_PROFILE=test/1
AWS_EB_PROFILE=/test/1
```

**Desktop (please complete the following information):**

 - OS / Distro: macOS
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: alacritty

**Comment by SurrealTiggi** [comment]
Can replicated it on https://sed.js.org, and fix by simply adding `\/` into the regex
![image](https://user-images.githubusercontent.com/2885448/122030477-a86b9f00-cd82-11eb-92eb-975e9ed3c5d8.png)

https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/aws/aws.plugin.zsh#L144
Changed to
```bash
grep --color=never -Eo '\[.*\]' "${AWS_CONFIG_FILE:-$HOME/.aws/config}" | sed -E 's/^[[:space:]]*\[(profile)?[[:space:]]*([-_\/[:alnum:]\.@]+)\][[:space:]]*$/\2/g'
```

Happy to log a PR as well, provided I'm not missing anything with this fix :)

**Comment by hans-d** [comment]
Same with ':' in the profile name
