### ISSUE TITLE
[git_prompt plugin] no longer indicates the working directory is clean with stashed changes

### ISSUE THREAD

**Issue by k3mist** [ohmyzsh/ohmyzsh#9978]
**Describe the bug**
git_prompt plugin no longer indicates if the working directory is clean.
it omits the directory is clean and instead only displays stashed changes

clean working directory with stashed changes
![image](https://user-images.githubusercontent.com/439440/122125869-f8884700-cdfe-11eb-9645-3b28aa1cd773.png)

clean working directory without stashed changes
![image](https://user-images.githubusercontent.com/439440/122125936-0e960780-cdff-11eb-8320-7e58b7145606.png)

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'git_prompt'
2. A clean git working directory with stashed changes

**Expected behavior**
git_prompt should indicate the working directory is clean

I believe the commit that changed this behavior is here on this line; 

https://github.com/ohmyzsh/ohmyzsh/commit/47c04d921ebb3fe4916eb131ae11557650aa1ae3#diff-847949367f1deddfdb1c527a2e3e8077e4b9a83b11777c510cbbf7bbf2bf994bR84

simply omitting `not stashed` resolves the issue.

![image](https://user-images.githubusercontent.com/439440/122126069-38e7c500-cdff-11eb-9726-5289d95c9edc.png)

Having stashed changes is not an indicator of a clean working branch in git and its disorienting when switching repositories locally which I do quite often for releases.

As git indicates the branch is clean it should also be reflected on the prompt;
![image](https://user-images.githubusercontent.com/439440/122126286-87955f00-cdff-11eb-9f30-9e9216d7bd8a.png)

**Comment by mcornella** [comment]
Thanks for the report, and apologies for the delay!
