### ISSUE TITLE
Minikube plugin Fedora 34 _minikube_root_command:36

### ISSUE THREAD

**Issue by Stenfrank** [ohmyzsh/ohmyzsh#9981]
The minikube plugin does not work on Fedora 34

**Describe the bug**
When enabling the minikube plugin, the autocomment returns the error `_minikube_root_command:36`

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'minikube'
2. Autocomplete command 'minikube ve'
3. `minikube ve_minikube_root_command:36: bad math expression: operand expected at "resume"'
_minikube_root_command:36: bad math expression: operand expected at "resume"
_minikube_root_command:36: bad math expression: operand expected at "resume"
minikube`

![image](https://user-images.githubusercontent.com/15841698/122303178-bc211d80-cec8-11eb-8bb0-61f9b541ea10.png)

 - OS / Distro: Linux
 - Latest ohmyzsh update?: Yes
 - ZSH Version: zsh 5.8 (x86_64-redhat-linux-gnu)

**Comment by lhauspie-adeo** [comment]
I think this issue is not relative to Oh My ZSH!.

Please refer to this opened issue : https://github.com/kubernetes/minikube/issues/11348

**Comment by Stenfrank** [comment]
Thanks
