### ISSUE TITLE
Incomplete installation of ZNT (zsh-navigation-tools)

### ISSUE THREAD

**Issue by galou** [ohmyzsh/ohmyzsh#9984]
**Describe the bug**
The installation of ZNT from this repository seems incomplete.

**To Reproduce**
Steps to reproduce the behavior with `zinit`:
1. `zinit snippet OMZP::zsh-navigation-tools`, this installs and binds `^R` to ` znt-history-widget`
2. `Ctrl-R`
3. An error is thrown: `_zsh_autosuggest_invoke_original_widget:9: znt-history-widget: function definition file not found`

**Expected behavior**
The "ZNT window" should open.

**Screenshots and/or Recordings**
You can also record an asciinema session: https://asciinema.org/

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro: Ubuntu 20.04.2 LTS
 - Latest ohmyzsh update?: Yes (3e7998a)
 - ZSH Version: 5.8
 - Terminal emulator: kitty

**Additional context**
Zinit plugin manager but I guess this is not related (cf. https://github.com/ohmyzsh/ohmyzsh/issues/5064, https://github.com/ohmyzsh/ohmyzsh/issues/5403).

**Workaround**

For `zinit`:

- `zinit snippet OMZP::zsh-navigation-tools` for the key binding.
- `zinit load psprint/zsh-navigation-tools` for the functionality.

**Comment by mcornella** [comment]
You can't use `zinit snippet` because that only loads the one file (`zsh-navigation-tools.plugin.zsh`). You need `zinit load`, but that doesn't work for Oh My Zsh plugins as far as I've seen. Since the plugin is a bundle of the upstream repository, you can just use `psprint`'s path:
```
zinit load psprint/zsh-navigation-tools
```
