### ISSUE TITLE
Allow chaining commands more easily

### ISSUE THREAD

**Issue by unlocomqx** [ohmyzsh/ohmyzsh#9993]
Hi, I don't know if ohmyzsh can solve this or if it's specific to each terminal

**Is your feature request related to a problem? Please describe.**
When a slow command is running (like `npm install` for example), I would like to chain the next command so I type `npm run dev` then `enter` to start the dev server right after the dependencies installation
The problem is that the output of `npm install` "overwrites" what I type, so I can't really see what I typed

**Describe the solution you'd like**
Pause the output of the current command when I start typing until enter or escape are pressed

**Additional context**
Another good use for this is when I restart my docker compose during dev
`docker compose down` takes a few seconds to complete so I chain the next command without having to wait
`docker compose up --build` to test my changes 

I don't know if this is useful for other people too, I just wanted to put this out there

**Comment by overlisted** [comment]
Use the `&&` operator? For example, `npm install && npm run dev` if you want to chain your npm commands

**Comment by unlocomqx** [comment]
@overlisted In most cases, I type commands on the fly as the current command is running, it's not always planned in advance.
It saves me a few seconds and it's better than waiting

I don't know if other people do the same thing, maybe it's just me. I just wanted to put this out there in case anybody finds it a good idea

Thanks

**Comment by DevinLeamy** [comment]
This would really nice to have!

**Comment by rwmitchell** [comment]
Using Ctrl-Z to pause the current job, then typing something like ```fg %1 && echo Success``` is the normal way.
Can you better describe how it would handle always running a new command or only conditionally if the previous succeeds.

Further, I suspect this is really a zsh issue, not something OMZ has control over.

**Comment by DevinLeamy** [comment]
@rwmitchell It would be nice to be able to write out the new `chained` command _while_ the current job is running. Currently, if you try to do this, you often times can't view the command you're writing because stdout outputs at your cursor position. For example, suppose you have a program that outputs "hello\n" a number of times. Writing `echo 'test'` while it runs might look like:
```
helloe
hello
hellocho
hello 't
helloest'
```
It would be great if this could be improved, provided it's within the scope of OMZ.

**Comment by rwmitchell** [comment]
You pause the command, add to it, then resume.  you said it was a long running command, the timeout won't make a difference.

omz is just spinner hub caps, you want a change to the car.

**Comment by unlocomqx** [comment]
You can already type in the next command and get it to run after the current finishes, you just don't see what you're typing very well. omz would just have to pause the output while you are typing, the resume it on enter or escape.

Do you think that omz can pause/resume the output on keyboard events?

**Comment by rwmitchell** [comment]
No, OMZ can’t just pause the output. Zsh, maybe, probably.

**Comment by unlocomqx** [comment]
Thanks for clarifying,

Cheers

**Comment by rwmitchell** [comment]
Even zsh can’t. Imagine you start an interactive program. Everything you typed would stop the program and return you to a prompt. You would never be able to enter anything.

**Comment by unlocomqx** [comment]
I didn't mean that the program would stop, just the output.
So, the program that is responsible for displaying the output would just "ignore" the output while you are typing. 
The program itself is never paused or stopped

I encounter a lot of situations where the current command takes 20s and then I start typing the next command which will run after it. 
If omz/zsh would ignore the output from command1 to let me easily type command2, that'd be great.
And then command2 will be executed after command1 finished (as is already the case now)

**Comment by unlocomqx** [comment]
I don't really want to freeze the terminal. This is not my request.
Anyway, I'll close this one as it doesn't seem possible for now
Cheers
