### ISSUE TITLE
tab do not useful in GIT?

### ISSUE THREAD

**Issue by Neyzoter** [ohmyzsh/ohmyzsh#9994]
```bash
git add <DIR>
```
![image](https://user-images.githubusercontent.com/16913995/122728395-adf94580-d2aa-11eb-92b5-1401dcac7617.png)

DIR can not be auto completed by TAB key.

**Comment by overlisted** [comment]
Maybe the directory is already added? Have you tried that with a directory that has unstaged (not added) files?

**Comment by Neyzoter** [comment]
> Maybe the directory is already added? Have you tried that with a directory that has unstaged (not added) files?

also not work

**Comment by grimm26** [comment]
FYI, I find that if I use https://github.com/git/git/blob/master/contrib/completion/git-completion.zsh then git completions work fine.

**Comment by nicain** [comment]
Hello all, I am hitting this as well on a fresh cloud VM:

git --version: git version 2.20.1
zsh --version: zsh 5.7.1 (x86_64-debian-linux-gnu)

Not sure what the problem is but plugins=(git)

**Comment by nicain** [comment]
Resolved my issue, documenting for posterity:

I was using virtualenv, and it appears that virtualenv inside of a git repo that does not have a .gitignore file will populate one fore you:

```
# created by virtualenv automatically
*
```

So it was git that was ignoring every file that I could possibly autocomplete.  Huh.  Anyways, HTH somebody else!
