### ISSUE TITLE
Update master to main

### ISSUE THREAD

**Issue by djcarpe** [ohmyzsh/ohmyzsh#9999]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
Nope. Just a change of the default repo to match some of the cultural changes of GitHub. 

https://github.com/github/renaming

**Is your feature request related to a problem? Please describe.**
Inclusive language.

**Describe the solution you'd like**
Updating the default master branch to main.

**Describe alternatives you've considered**
There are no replacements for ohmyzsh, long time user, fan, and supporter.

**Additional context**
I know this will break a lot of things, but wanted to start the converstion.

**Related Issues**
nil

**Comment by hllewelyn** [comment]
Already in progress: https://github.com/ohmyzsh/ohmyzsh/issues/9015

**Comment by djcarpe** [comment]
Thank you!
